### ISSUE TITLE
Markdown & Git: Неверная оценка.

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/support#1]

**Comment by Azizbek98** [comment]
Good afternoon.

My name is Azizbek Samatov. Before completing task 1 I pressed submit button by mistake. It shows me 0 score. But now I have completed but I'm not able to submit it. So can you accept it please.

Thank you for your understanding.

**Comment by Azizbek98** [comment]
> Good afternoon.
> 
> My name is Azizbek Samatov. Before completing task 1 I pressed submit button by mistake. It shows me 0 score. But now I have completed but I'm not able to submit it. So can you accept it please.
> 
> Thank you for your understanding.

azizbek98.github.io/rsschool-cv/cv

**Comment by Atasek** [comment]
Добрый вечер, также показывает 0 баллов. Просьба подсказать,что не так   https://atasek.github.io/rsschool-cv/cv

**Comment by algoritmiks** [comment]
Выставлена заниженная оценка по причине неверного описания комитов, хотя все комиты расписаны что в них делалось. 
Failed commit requirements: Commits do no follow guideline -> ["upd: education added" , "upd: technical skills added" , "upd: my projects added" , "upd: objective and work experience added"]

**Comment by kozlovmax** [comment]
My name is  Maksim Kozlov. In the second task, Markdown & Git put me 50 points out of 100. I want to find out why? Since all conditions are met.

**Comment by rsaldiny** [comment]
Hi. Can you check the second task please? I have lost 50 points,  but I have met the requirements.  It does not say  in the exercise that we need to call Pull Request a "GiT and Markdown" so I called it "Pull Request is created".

**Comment by AlekseiBY** [comment]
Hi. Sent
 task with htmlacademy to the bot for verification before finishing it. Received 0 points. And now after completing the task, the bot refuses to recheck it. Help plz(

**Comment by FireYourGuns** [comment]
Добрый день, проверьте пожалуйста моё домашнее задание Git&Markdown. На мой взгляд у меня всё сделано правильно, но оценка стоит ноль, не могу понять в чём дело

**Comment by DmitryYakorev** [comment]
My name is Dmitry Yakorev.I got 50 and no status. I want to find out why?

**Comment by apalchys** [comment]
@kozlovmax 
@DmitryYakorev 
@rsaldiny 
Please read carefully "Verification Results" table on "Auto-Test" page. Reason should be there.

@AlekseiBY 
Please read carefully "Verification Results" table on "Auto-Test" page and compare `Required courses` with `Passed courses`

**Comment by Venoboy** [comment]
Hi, i've got 50 points with message: Failed commit requirements: Commits do no follow guideline -> ["docks: final stage" , "docks: add 4-6 paragraphs" , "docks: add 1-3 paragraphs"]
What is wrong?

**Comment by tomsoer666** [comment]
Hi, i've got 50 points with message: 
Failed commit requirements: Less than 3 commits
But i have 3 commits in branch gh-pages, pls check what's wrong.

**Comment by KateSid** [comment]
Hi. I've the same problem as tomsoer666

**Comment by CHERNOMORGAMES** [comment]
Greetings!
Markdown & Git task.
I have 50 points with: Failed repository requirements: No cv.md file. (Status: 404)

FAQ says in that case: no repository "rsschool-cv" with branch "gh-pages", where there is "cv.md". Or in branch "master" there is no "README.md" file.

But, I have all files in place. Maybe the problem happened because I accidently commited gh-pages as first default branch, but changed it later. Anyway, on submission to check everything was as should be. I believe everything is done correctly in the task, so there must be an error on auto-test.

**Comment by Sinigami83** [comment]
Внесите, пожалуйста, изменения в задание в части https://github.com/rolling-scopes-school/tasks/blob/master/tasks/git-markdown.md#commits-requirements что 3 комита должны быть в ветке gh-pages

**Comment by Alexxeyva** [comment]
Please see if it is possible to solve my problem with 0 balls. I sent it several times by mistake, but now I figured it all out and the task on Markdown & Git was completed.

**Comment by Alexxeyva** [comment]
Hello. Please see if it is possible to solve my problem with 0 points. I sent it several times by mistake, but now I figured it all out and the task on Markdown & Git was completed.

**Comment by skulovets** [comment]
Hello, I'm sick, I can't send the first 2 tasks, what should I do?

**Comment by iMafusail** [comment]
Hello. I've got only 50 points in Markdown & Git task with a massage that my commits do not fallow commit requirements. What is wrong with them? Is that because they start with capital letters? In guideline they start with literals but i didnt think that that would be a problem.

**Comment by Venoboy** [comment]
> Hi, i've got 50 points with message: Failed commit requirements: Commits do no follow guideline -> ["docks: final stage" , "docks: add 4-6 paragraphs" , "docks: add 1-3 paragraphs"]
> What is wrong?

At task "HTML, CSS & Git Basics" got the same error, @apalchys i think it's not fair.

**Comment by samusevabsu** [comment]
Hello, I've only one commit with error in message 'Delete README file'. But 5 commits were created without errors. May I get 100% result?
--
Ekaterina Samuseva
https://github.com/samusevabsu

**Comment by apalchys** [comment]
@Venoboy `docks` is unknown prefix. please see https://docs.rs.school/#/git-convention

@tomsoer666 @KateSid  "Initial commit" was ignored because it doesn't follow guidelines. Task requirements  have a rule to make 3 commits which follow guidelines https://docs.rs.school/#/git-convention

@skulovets continue to study and do the rest tasks.

@samusevabsu unfortunately no.  (actually you could fix. there is a possibility to change commit message in Git)

**Comment by pavel-k-python** [comment]
Hello @apalchys!
I made a mistake when writing the first commit (`Inital commit` instead of `Init**i**al commit`).
Why now does this affect the points for the second task(`Git & HTML & CSS`)**?** (50 points out of 100)
https://github.com/pavel-k-python/rsschool-cv

**Comment by iMrOwl** [comment]
сделал вроде все верно, названия ок, ссылка есть, название веток и файлов верное, а поставили 50 балов, можно узнать где сняли?

**Comment by VNavrockij** [comment]
Hello.

I see no errors in completing the task for Markdown & Git.

Accrued 50 points.

Please clarify.
Thank you in advance.

https://vnavrockij.github.io/rsschool-cv/cv
https://github.com/VNavrockij/rsschool-cv
https://github.com/VNavrockij/rsschool-cv/pulls
https://github.com/VNavrockij/rsschool-cv/commits/gh-pages

**Comment by nati-f** [comment]
Hi!

I have verification results: Failed repository requirements: No cv.md file. (Status: 404)

![Uploading Снимок экрана 2020-03-09 в 5.43.29 ДП.png…]()

in Task0 https://app.rs.school/course/student/auto-test?course=ios-2020-q1

but I create this file and links work:
https://nati-f.github.io/rsschool-cv/cv
https://nati-f.github.io/rsschool-cv/cv.md

**Comment by GuzeevZhenya** [comment]
Привет, хотелось бы узнать момент по поводу оценок. У меня в score-таблице оценки идут 50,45,36,100,45,100 = 375, но в total стоит 262.5 
https://github.com/GuzeevZhenya

**Comment by Weranika** [comment]
I bealive you forgot to add toLowerCase operation for link in your script, due to browser was able to open my link and your script showed "Failed task requirements: No CV at https://weranika.github.io/rsschool-cv/cv. (Status: 404)" before my fix

**Comment by mariammanvelidze** [comment]
Hello. I got 50 points and "Failed repository requirements: No cv.md file". I have cv.md file in gh-pages branch, exactly where it had to be according to the task.

**Comment by Greblips** [comment]
Здравствуйте,случайно нажал резульататы по тестам Git & Markdown и Git & HTML & CSS о иполучил за них  0(

Failed task requirements: No CV at https://greblips.github.io/rsschool-cv/cv. (Status: 404)
--
Есть ли возможность убрать результаты и начать заново,заранее благодарю

**Comment by MikitheArtist** [comment]
Добрый день, подскажите пожалуйста  сабмитила HTML, CSS & Git Basics , выдает ошибку,
![2020-09-16_15h09_02](https://user-images.githubusercontent.com/56101985/93338606-36861980-f833-11ea-8ce0-470d2073568c.png)
![2020-09-16_15h12_17](https://user-images.githubusercontent.com/56101985/93338635-3ede5480-f833-11ea-8acc-8fb6c4f71bff.png)

 хотя в моей ветке gh-pages все есть

**Comment by KukushkinDmi1riy** [comment]
My name is Kukushkin Dmitry. I'v got 50 points out of 100 points in Git & Markdown task. I want to find out why? Since all conditions are met. The app send me this worrning (Commits do no follow guideline ....), but I used all your guides.

**Comment by Iriyamak** [comment]
> Здравствуйте,случайно нажал резульататы по тестам Git & Markdown и Git & HTML & CSS о иполучил за них 0(
> 
> ## Failed task requirements: No CV at https://greblips.github.io/rsschool-cv/cv. (Status: 404)
> Есть ли возможность убрать результаты и начать заново,заранее благодарю

Подобные таски можно сабмитить любое количество раз. Просто нажми Submit еще раз, и тест переоценит по новой.

**Comment by Iriyamak** [comment]
> Здравствуйте,случайно нажал резульататы по тестам Git & Markdown и Git & HTML & CSS о иполучил за них 0(
> 
> ## Failed task requirements: No CV at https://greblips.github.io/rsschool-cv/cv. (Status: 404)
> Есть ли возможность убрать результаты и начать заново,заранее благодарю

Просто снова сабмитни этот таск. Таски с гитом можно сабмитать неограниченное количество раз до дедлайна.

**Comment by Iriyamak** [comment]
> Добрый день, подскажите пожалуйста сабмитила HTML, CSS & Git Basics , выдает ошибку,
> ![2020-09-16_15h09_02](https://user-images.githubusercontent.com/56101985/93338606-36861980-f833-11ea-8ce0-470d2073568c.png)
> ![2020-09-16_15h12_17](https://user-images.githubusercontent.com/56101985/93338635-3ede5480-f833-11ea-8acc-8fb6c4f71bff.png)
> 
> хотя в моей ветке gh-pages все есть

Проблему уже решили в дискорде.

**Comment by Iriyamak** [comment]
> My name is Kukushkin Dmitry. I'v got 50 points out of 100 points in Git & Markdown task. I want to find out why? Since all conditions are met. The app send me this worrning (Commits do no follow guideline ....), but I used all your guides.

Hello. Your should read more carefully this - https://docs.rs.school/#/en/git-convention and https://www.conventionalcommits.org/en/v1.0.0-beta.2/
If your already fix it, cose your commits are right, please close the issue

**Comment by irinrudko** [comment]
Добрый вечер!
В самый первый день использования гита ошиблась с названием первого коммита – README.md (загружала через браузер, был добавлен автоматический комментарий системой). Далее все коммиты делала согласно гайдлайну. Но авто-тест снял 50 баллов за тот самый первый коммит. Даже пробовала копаться в истории коммитов и изменить комментарий, но пока тщетно.

Возможно ли как-то пересмотреть начисление баллов за это задание? 

P.S. Этот же коммит повлиял и на второе задание – HTML, CSS & Git Basics, так как все коммит скопировались при создании новой ветки.

**Comment by dzmitry-varabei** [comment]
@irinrudko такая проблема есть, мы трактуем её как ошибка при выполнении задания. Пока было время, можно было просто пересоздать репозиторий. После дедлайна - остается только делать следующий таск.

**Comment by NastyaDanilova** [comment]
Добрый день, подскажите пожалуйста сабмитила HTML, CSS & Git Basics , выдает ошибку,
![1](https://user-images.githubusercontent.com/43300688/93738310-259c2600-fbee-11ea-8be7-eb68e53c67e9.png)
![2](https://user-images.githubusercontent.com/43300688/93738317-29c84380-fbee-11ea-8f47-8ed39cf6966b.png)
Хотя файл в ветке rsschool-cv-html есть.

**Comment by annazubareva14** [comment]
My name is Anna Zubareva. In the second task, Markdown & Git put me 50 points out of 100. I have met the commit requirements. Can you check please? Thank you.

**Comment by Ivan-Sidorenko** [comment]
Добрый вечер! 
Прошу пожалуйста прокомментировать оценку 50 баллов за выполненное задание Markdown & Git.
Выполнил задание, ссылка https://github.com/rolling-scopes-school/ivan-sidorenko-JSFE2021Q1/blob/gh-pages/cv.md.
Ссылка на Pull Request https://github.com/rolling-scopes-school/ivan-sidorenko-JSFE2021Q1/pull/1.
В "Требовании к Pull Request" по ссылке https://rolling-scopes-school.github.io/stage0/#/tasks/git-markdown?id=%d0%a2%d1%80%d0%b5%d0%b1%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d1%8f-%d0%ba-pull-request, говориться: 
- Название Pull Request дайте по названию задания. В данном случае название Pull Request - Markdown & Git
Ведь можно было написать и так: 
- Название Pull Request дайте по названию задания. В данном случае название - Markdown & Git (без слов Pull Request).
Я же как простой юзер прочел, скопировал и получил за то что можно трактовать иначе 50 баллов.
Считаю что я могу быть оценен за задание на 100 баллов. Но также не обижусь если мне оставят добрый комментарий и оставят оценку 50 баллов. 

Благодарю!

**Comment by dzmitry-varabei** [comment]
Этот таск можно пересдать в RS APP до дедлайна сколько угодно раз. Если есть вопросы, пишите в канал #git-2021Q1 в Discord
