### ISSUE TITLE
Cross-Check webdev

### ISSUE THREAD

**Issue by Zelevzel** [rolling-scopes-school/support#100]
Ссылка на деплой вашего проекта:
https://rolling-scopes-school.github.io/zelevzel-JS2020Q3/webdev/
Ссылка на репозиторий с проектом на GitHub:
https://github.com/rolling-scopes-school/zelevzel-JS2020Q3/tree/gh-pages/webdev

Со всем согласен, но Student 2 забыл поставить +20 балов за этот пункт - Cтраница открывается по указанной ссылке, и она не пустая. (20/20)

Student 2

Score: 67

1. Панель навигации должна быть интерактивной. -2 балла
2. Блок Our  Community: смещение более, чем на 90px. За каждый логический элемент по -3 балла, итого: -6
3. Блок Implement Right Code: смещение более, чем на 90px. За каждый логический элемент по -3 балла, итого: -6
4. Блок Download: смещение более, чем на 90px. За каждый логический элемент по -3 балла.
Помимо кнопки, иконки apple и android тоже должны быть интерактивными -2 балла за невыполнение функционального требования, итого: -8
5. Блок Footer: смещение более, чем на 90px. За каждый логический элемент по -3 балла.
Credis | Privacy | Our team должны быть интерактивными и иметь разделитель -2 балла за невыполнение функционального требования, итого: -8
Проверял по новому и старому макету, после второго блока отклонения слишком большие.

**Comment by Alexey-Koren** [comment]
Нашёл ваш балл в скоре. У вас 87 баллов.
Ваша апелляция не подходит под правила, прочитайте пункт 4.
В разделе про апелляции https://docs.rs.school/#/cross-check-flow

Закрываю
