### ISSUE TITLE
Cross-Check 'webdev' - 'alexk08'

### ISSUE THREAD

**Issue by alexk08** [rolling-scopes-school/support#101]
1. Ссылка на деплой моего проекта:  https://rolling-scopes-school.github.io/alexk08-JS2020Q3/webdev/
2. Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/alexk08-JS2020Q3
3.  Оценка в результате самопроверки: 100 из 100. Проект выполнен согласно техническому заданию: функциональные требования соблюдены, совпадения по PP по каждому блоку в пределах 5px. Также я реализовал "первый экран" your-life на всю высоту вьюпорта, согласно рекомендациям создателя макета из видео https://youtu.be/mkttCkHiYck, а также фоновые картинки и цвета сделал на всю ширину экрана, что также не противоречит ТЗ. В остальном контент сайта расположен на 100% согласно макету.
4. Балл за cross-check из моего Score: 73

Комментарии: итоговая оценка сложилась из среднего арифметического трех оценок https://prnt.sc/uophku. Прошу Вас обратить внимание на оценку третьего проверяющего Score: 20. Комментарии проверяющий оставил не развернутые, и возможности связаться с ним для объяснения реализации проекта также не предоставил. Считаю, что данная проверка была осуществлена с нарушением критериев проверки, указанных в ТЗ. Прошу Вас пересмотреть итоговый балл.

**Comment by Sonahit** [comment]
### Рекомендация не должна иметь высокий приоритет. ТЗ должно быть абсолютом, если оного не прописано в ТЗ

Рекомендация - есть рекомендация, и она не иметь более высокий приоритет чем ТЗ **на то это и ТЗ**.

### Комментарии

Комментарии могут зависеть от самих проверяющих и особо критериев проверки самих комментариев от проверяющих нет. Поправьте меня, если они есть.

**Comment by InikonZS** [comment]
Поправлю - в условиях проверки сказано, что блоки проверяются независимо, для проверки каждого блока изображение выравнивается по проверяемому блоку (проверяющий не учел данное требование). 

С учетом того что как такового запрета на 100vh не было и выглядит это отлично и содержимое блока you life соответствует макету прямо по ПП при его позиционировании, здесь всё отлично.

По остальной части макета так же все верно, все требования к пп и интерактивности выполнены.
По коду - все отлично, креативно так

**Итого: 100**
