### ISSUE TITLE
Cross-Check 'webdev' - 'vadymkas'

### ISSUE THREAD

**Issue by VadymKas** [rolling-scopes-school/support#102]
Ссылка на деплой https://vadymkas-rsschool.netlify.app/
Ссылка на репозиторий https://rolling-scopes-school.github.io/vadymkas-JS2020Q3/webdev/ - **_не открывается "GitHub Pages is temporarily down for maintenance". Написал в дискорд согласно правил касательно данного вопроса, что не деплоится пул реквест._**

В итоге со мной согласно правил в дискорде связались пару человек и им была предоставлена рабочая ссылка на макет сайта https://vadymkas-rsschool.netlify.app/.

Студент dramantsevich проверил  мое задание в последние часы сабмита и выставил 0, так и не связавшись со мной согласно правил. 

Прошу перепроверить и выставить корректную оценку по заданию вместо 0 баллов от dramantsevich.

Спасибо за уделенное время!

**Comment by valerydluski** [comment]
1. Header +9
  Должен быть подсвечен первый элемент. (-1 Балл)
2. Your Life +7
  Иконки относительно пакета сильно уплывают (-3 Балла)
3. Rappresent +10
4. Our Community +5
  1, /, 5 должны быть раздельными элементами. (-2)
   Стрелки должны быть интерактивными. (-2)
   Картинку с помощью стилей надо было обрезать, а не просто поставить размер 20px (-1 балл)
5. Implement +10
6. Sign Up +3
   Галочка  должна быть интерактивной (-2 балла)
  Отклонения от макета -3 Балла
  Нет валидации (-2 Балла)
7. Download +10
   Кнопки отличаются от макета (снимать не стал).
8. Footer  +7
  Ссылки уплыли в бок (-3 Балла)

Будем считать что ссылка рабочая +20

Итого: 81 балл
