### ISSUE TITLE
Cross-Check 'webdev'  - 'alx28R'

### ISSUE THREAD

**Issue by alx28R** [rolling-scopes-school/support#103]
Деплой проекта: https://rolling-scopes-school.github.io/alx28r-JS2020Q3/webdev/
GitHub: https://github.com/rolling-scopes-school/alx28r-JS2020Q3
Оценка при самопроверке: 95 баллов.
Балл из Score(проверяющего): 5 баллов.

Один из проверяющих за моё задание поставил мне 5 баллов, а в комментариях указал только 2 ошибки, остальные двое поставили по 98 баллов, при этом описанные ошибки в комментариях частично сходятся с ошибками проверяющих, которые поставили 98 баллов.

Поэтому прошу пересмотреть работу, так как по моим подсчётам там выходит 94-95 баллов.

P.S. Проверяющий, который поставил мне 5 баллов, никак со мной не связался и не оставил свои Git, так что я не знаю как его зовут.

**Comment by InikonZS** [comment]
Нет валидации формы ( type = text и не задан pattern)
Выделенный жирным текст по идее должен быть задан тегом Strong а не B, но это не точно
Пагинация слайдера состоит из нужных элементов, и ховер есть по отдельности, но курсор на общем контейнере, здесь все отлично).
По ПП все сходится пиксель в пиксель, кроме блока my life is webdev, текст немного смещен вниз

По коду - **превосходно**. лучшее решение, которое удалось увидеть в рамках webdev таска. Хорошая структура, частично адаптив, кнопки цельные, теги по назначению, нейминг классов грамотный.

**Итого:** справедливо будет **100**, честная верстка и отличное сходство.
