### ISSUE TITLE
Cross-Check 'webdev' - 'mejey1'

### ISSUE THREAD

**Issue by mejey1** [rolling-scopes-school/support#104]
Ссылка на деплой https://mejey1-webdev.netlify.app/
Не правильно за самбил задание, указав не правильно ссылку.
Ссылка на гитхаб https://github.com/rolling-scopes-school/mejey1-JS2020Q3/tree/webdev

Со мной связались только 2 студента которым я предоставил ссылку.

Студент **ahtrewhr** не связался со мной по дискорд написал комментарий _"Извини, но ссылка не открывается, Видимо были нарушены условия использования репозитория."_ Пробовал связаться в дискорде в телеграмме, 2 дня результатов нет.

Студент **petedekterev** не связался со мной по дискорд написал комментарий _"За пустой репозиторий 0 баллов"_ Пробовал связаться в дискорде в vk, 2 дня результатов нет.
Спасибо.

**Comment by valerydluski** [comment]
Оформите апелляцию но правилам школы

**Comment by InikonZS** [comment]
Отличный ПП, элементы интерактивные. Верстка на абсолютах и только, нейминг классов не очень, рекомендуется называть по их функции, а не просто block1, можно почитать о методологии БЭМ.
- header
не надо делать липким (position: fixed) -3
- Блок _bg-image_ (You life) 
Нет иконок соцсетей -2 (интерактив)
Кнопка имеет бордер -3 (не соотвествие макету)
- Блок Sign-up 
input не соотвествует макету ( имеет border по умолчанию, не стилизован) -3
- Футер
Между элементами нет разделителей -3
Ниже футера белое пространство в 63px (связано с relative и смещением top на блоке внутри футера и самим футером в стандатном потоке) -2
Макет не отцентрован -2

Рекомендую ознакомиться с другими инструментами верстки, например flex и попрактиковаться в позиционировании стандартными margin и padding, иначе такую верстку никто не примет.
**Итого 85**
