### ISSUE TITLE
Cross-Check 'webdev' - 'Sedna13'

### ISSUE THREAD

**Issue by Sedna13** [rolling-scopes-school/support#105]
*Деплой проекта: https://rolling-scopes-school.github.io/sedna13-JS2020Q3/WebDev/
* GitHub: https://github.com/rolling-scopes-school/sedna13-JS2020Q3
* Оценка 96, курсор при наведении выбора не везде изменяется
* Балл за cross-check из Score - 91

Один из проверяющих моё задание, поставил мне за работу 73 балла, по критериям, которых не было описано при проверке работ. Проверяющий со мной не связался и не оставил свои Git для связи. Остальные двое проверяющих поставили по 100 баллов.

Поэтому прошу пересмотреть работу. Спасибо.

**Comment by valerydluski** [comment]
Апелляция производится только если ожидаемый вами балл и полученным по результатам кросс-чека средний балл отличаются на 15 и более процентов.
