### ISSUE TITLE
Cross-Check 'webdev' - 'Fodin'

### ISSUE THREAD

**Issue by Fodin** [rolling-scopes-school/support#106]
1. [Деплой](https://fodin-webdev.netlify.app/) 

1. [Репозиторий](https://github.com/Fodin/webdev) создан только что, работу делал в локальном, т.к. #85, а работать в публичном было бы неправильно.

1. 100 баллов. В силу своих возможностей старался писать код так, будто завтра мне его на собеседовании показывать сумасшедшему работодателю, поэтому пытался учесть все нюансы, только в ширине заголовков и размерах блоков текста допуская небольшое расхождение в пару пикселей, остальное выравнивал пиксель-в-пиксель. В работу взята новая версия макета.

1.  85 баллов (100, 55, 100).

**Comment by valerydluski** [comment]
Хорошая работа. Всё по ТЗ. Правда на кнопки лучше вешать курсор pointer хотя интерактивность есть. 

Итого: 100 баллов
