### ISSUE TITLE
Cross-Check 'webdev' - 'magklax'

### ISSUE THREAD

**Issue by magklax** [rolling-scopes-school/support#108]
Ссылка на деплой: https://rolling-scopes-school.github.io/magklax-JS2020Q3/webdev/
Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/magklax-JS2020Q3

Оценка в результате самопроверки: Страница соответствует макету на ширине 1600px с незначительными отклонениями, поэтому моя оценка 100. Просмотр страницы с пиксель перфект https://ibb.co/Vv0WbSS
Все ссылки и кнопки интерактивы (hover, focus, cursor: pointer). На странице присутствует h1. Изображение в блоке your life подложено под текст.

Балл за cross-check: 90 + 100 + 74 = 88 (последний проверяющий был анонимом)

**Comment by valerydluski** [comment]
Апелляция производится только если ожидаемый вами балл и полученным по результатам кросс-чека средний балл отличаются на 15 и более процентов.
