### ISSUE TITLE
Cross-Check 'webdev' - 'bakabokka'

### ISSUE THREAD

**Issue by BakaBokka** [rolling-scopes-school/support#109]
1.https://rolling-scopes-school.github.io/bakabokka-JS2020Q3/webdev/
2. https://github.com/rolling-scopes-school/bakabokka-JS2020Q3/tree/webdev/webdev
3. Моя оценка 100/100. 
Весь функционал на месте. 
Расхождений больше 5px нет. 
4. 100, 97, 75, 92   
Серьёзно, 92 и 75  это вообще никуда не годится : ).

Спасибо.

**Comment by valerydluski** [comment]
Апелляция производится только если ожидаемый вами балл и полученным по результатам кросс-чека средний балл отличаются на 15 и более процентов.
