### ISSUE TITLE
Cross-Check 'webdev' - 'makarchiknet'

### ISSUE THREAD

**Issue by makarchiknet** [rolling-scopes-school/support#110]
1 https://rolling-scopes-school.github.io/makarchiknet-JS2020Q3/webdev/
2. Моя оценка 80/100.
4.Не верно загрузила ссылку из-за этого проверяющий не попробовал со мной связаться и взять верную ссылку на проект. Поставил 5 балов.
Заранее спасибо за решение моего вопроса.

**Comment by InikonZS** [comment]
По интерактивности проблем нет, небольшой недостаток - кнопка формы не отправляет форму, хотя валидация по type email имеется.

По ПП весь макет смещен на -7 пикслей, отличается шрифт на input элементе формы, в остальном все сходится

Отсутствует один слайд в слайдере, слайды слипаются - 3

По коду - в целом средне, хорошо используются флексы, грамотно им заданы параметры, неплохая структура (в сравнении с абсолютами)

**Итого: 97**
