### ISSUE TITLE
Cross-Check 'webdev' - 'KaterinaRomanova'

### ISSUE THREAD

**Issue by KaterinaRomanova** [rolling-scopes-school/support#111]
1. https://katerinaromanova-webdev.netlify.app/
2. 100 все пункты из задания выполнены (все панели интерактивные, расхождений с шаблоном больше 5px нет)
3. оценки студентов: 100, 100, 92, 79
![image](https://user-images.githubusercontent.com/44569848/94462078-a85f4b00-01c3-11eb-93c5-67f472bc58aa.png)

**Comment by valerydluski** [comment]
Апелляция производится только если ожидаемый вами балл и полученным по результатам кросс-чека средний балл отличаются на 15 и более процентов.
