### ISSUE TITLE
Cross-Check 'webdev' - 'chernataly2020'.

### ISSUE THREAD

**Issue by chernataly2020** [rolling-scopes-school/support#112]
1. Ссылка на деплой вашего проекта: https://chernataly2020-js2020q3-webdev.netlify.app/

2. Ссылка на репозиторий с проектом на GitHub: 
https://github.com/rolling-scopes-school/chernataly2020-JS2020Q3/tree/webdev

3. Оценка в результате самопроверки, с ее аргументацией:  за свою работу ставила в среднем 80
 баллов, с учетом того, что могла не верно спозиционировать элементы из-за пока нехватки соответствующего опыта или могла не заметить мелкие недочеты. На моем мониторе позиционирование выглядело практически без отклонений. Ссылку указывала, скопировав ее из netlify.app. Но после деплоя обнаружила, что ссылка выглядит совсем не так: 
https://app.rs.school/course/student/chernataly2020-js2020q3-webdev.netlify.app
К ней добавлена приставка, о которой я даже не подозревала. Из-за этого работа и не открывалась. На почту проверяющему была отправлена первая ссылка на работу. Но оценка за ссылку все равно снижена на 20 баллов.
Прошу проверить мою работу и выставить справедливую оценку.
4. Балл за cross-check из вашего Score: 63

**Comment by chernataly2020** [comment]
![image](https://user-images.githubusercontent.com/69033364/94463366-7d75f680-01c5-11eb-95d0-81895ba0b83c.png)

**Comment by InikonZS** [comment]
+20 Ссылка пашет
   - Header +10
   - Блок Your Life +10-3
расстояние между иконками отличается
Написано расположить h1 на свое усмотрение, значит так надо.
   - Блок Rappresent +10
   - Блок Our Community +10-3
слайдер значительно ниже находится, хотя по горизонтали все норм.
   - Блок Implement +10-3
кнопка имеет другой текст и находится значительно ниже
   - Блок Sign Up +10-3
Совсем не сходится положение формы внутри блока, около 20 пикселей по вертикали и более 100 по горизонтали 
 - Блок Download +10
Тут все отлично и кнопочки красивые

 - Footer +10
И здесь все ровно.

----------
**Что понравилось**: прикольные ховеры на линках и на иконках соцсетей. Не было ожидаемого косяка с max-width вместо width, поэтому проверять было просто и ничего не посыпалось на мобиле и прекрасно выглядело на компе.

**Что не понравилось**: сначала работа показалась довольно качественной, но смутил перенос заголовков на другую строку в моей любимой Лисице... Собственно по коду - сплошной Absolute, где-то разбросаны флексы, которые не играют особой роли в позиционировании.
Много вообще удивительных вещей - например слайдер в "семантическом" теге <d> flex-direction: column; позиционирует слайды c помощью left по горизионтали.
Кнопки в блоке download каждая состоит из двух <a> тегов, по идее кнопка и иконка это всё одна кнопка должна быть.

Позвольте -3 по код ревью, с учетом что отклонения в других блоках так же незначительные есть и это точно не в угоду качества верстки.
Лиса рушит макет, заголовки переносятся на вторую строку, это судя по коду связано с копированием их ширины из макета.
Макет не отцентрован -2;

**Итого: 100 - 17 = 83**

**Comment by chernataly2020** [comment]
Спасибо большое за проверку! Верстке учусь, потому могу что-то вытворить нестандартно)). Кнопки и иконки в разных блоках, потому что я анимировала и кнопку и саму иконку)). Позиционировать элементы учусь!)
