### ISSUE TITLE
Cross-Check 'Webdew' - 'yury-chaikou'

### ISSUE THREAD

**Issue by yury-chaikou** [rolling-scopes-school/support#113]
Ссылка на деплой вашего проекта - https://rolling-scopes-school.github.io/yury-chaikou-JS2020Q3/
Ссылка на репозиторий с проектом на GitHub https://github.com/rolling-scopes-school/yury-chaikou-JS2020Q3/tree/gh-pages
Оценка в результате самопроверки, с ее аргументацией 
 страница открывается по указанной ссылке, и она не пустая, +20

Header +10 - 2 (первый пункт меню не подсвечен) = 8

Блок Your Life +10

Блок Rappresent +10

Блок Our Community +10-2 (не увидел фон) = 8

Блок Implement +10

Блок Sign Up +10

На блок стоит исключение по позиционированию, фоновая картинка утащилась с нарисованной формой, ничего не стал по этому поводу предпринимать - формально форма работает, регулярка на проверку адреса есть, кнопочка по наведению подсвечивается. 

Блок Download +10 - 3 (Не сделал как надо кнопки, сильное расхождение по ПП) =7

Footer +10
Итого 93. 
Работу делал в условиях нехватки времени, и признаю, что кое-что упустил - подсвеченность первого элемента, фон в Комьюнити, на доведение некоторых вещей просто не хватило времени. После переноса дедлайна внёс мелкие правки, стараясь минимально соответствовать ТЗ. 

Балл за cross-check из вашего Score 84

Суть претензии: работа проверена 3 студентами, одна из оценок следующего вида:

[Imgur](https://i.imgur.com/Yt7QjE9.png)

Score: 65

-Пиксель перфект  сделан на 60% - с таким обобщением -  без комментариев 

-проблема с валидностью кода (выдает 11 ошибок) - ТЗ не предполагало валидацию HTML

-не доделан блок Subscribe - Доделан. Форму можно передать обработчику на этой же странице (его создание не предусмотрено ТЗ), минимальная валидация email проводится, кнопка подсвечена. Сделано некрасиво - да, но формальности соблюдены.

-при наведении на ссылки в header и footer текст разъезжается в стороны - горизонтальное выравнивание в этих блоках ТЗ не предусматривает, а смещения меньше порога в 5px.

Вероятно, не выставленная четвёртым проверяющим оценка была отброшена системой как наименьшая, и результат был рассчитан с учётом такой формальной оценки, поставленной последним участником. Скажем так, меня не столько интересует моя оценка - средний балл всё равно высокий, и, согласно правилам аппелирования, при таком балле можно претендовать только на оценку > 99, сколько желание выяснить, почему не отбросилась наихудшая оценка, что будет у студента, которого проверили только 2 человека (не окажется ли у хорошей работы оценка 100+100+0/3=66), если отсутствие оценки = 0 баллов?

**Comment by valerydluski** [comment]
Апелляция производится только если ожидаемый вами балл и полученным по результатам кросс-чека средний балл отличаются на 15 и более процентов.

**Comment by yury-chaikou** [comment]
Вопрос касался не баллов, а ошибки в методике подсчёта. В документации
написано, что наименьшая оценка отбрасывается. У отброшена не была.

**Comment by valerydluski** [comment]
Отбрасывается оценка если проверили 4 студента.
