### ISSUE TITLE
Cross-Check 'Webdew' - 'vitalic-developer'

### ISSUE THREAD

**Issue by Vitalic-developer** [rolling-scopes-school/support#114]
1 https://rolling-scopes-school.github.io/vitalic-developer-JS2020Q3/webdev/
ссылка на сайт по макету 
мне не поставили за это 0 из за неправильной ссылки и никто со ной не связался.
2 https://github.com/rolling-scopes-school/vitalic-developer-JS2020Q3/tree/webdev
ссылка на github репозиторий.
3 оценка по моему мнению не ниже 80 баллов всё сделано в точности по pixel perfect но ссылку я случайно засабмитил не рабочую. то есть.
4 балл за cross chek - 25.

**Comment by valerydluski** [comment]
1. Header +10
2. Your Life +10
3. Rappresent +8
   В текстовом блоке есть важный текст, который выделен жирным. Для него нужно использовать логический элемент.(<b> не логический элемент) -2 балла
4. Our Community +8
  1, /, 5 должны быть раздельными элементами. -2 балла
5. Implement +8
     В текстовом блоке есть важный текст, который выделен жирным. Для него нужно использовать логический элемент.(<b> не логический элемент) -2 балла
6. Sign Up +10
7. Download +10
8. footer +10

Итого: 74 балла
