### ISSUE TITLE
Cross-Check 'webdev' - 'Zavrazhneva'

### ISSUE THREAD

**Issue by Zavrazhneva** [rolling-scopes-school/support#115]
https://rolling-scopes-school.github.io/zavrazhneva-JS2020Q3/webdev/
https://github.com/rolling-scopes-school/zavrazhneva-JS2020Q3
Изначально мне казалось на 100 , но в ходе кроссчека я увидела недостатки 
(картинка с главного экрана плохого качества -2 балла, в блоке implement уехал subtitle -3 балла )
две оценки считаю не очень честными, если можно их исправить, было бы очень здорово. Заранее благодарна :) 

Student 2
Score: 70
Баллы по блокам:
1. Open - 20
2. Header - 7
3. Your Life - 4
4. Rappresent - 7
5. Our Community - 4
6. Implement - 10
7. Sign Up - 7
8. Download - 7
9. Footer - 4
Итог - 70

Student 3
Score: 82
1. Блок Your Life, Блок Rappresent, Блок Our Community, Блок Implement , Блок Download, Footer: отклонение больше 5px : -3*6 = 18 баллов.
2. Функциональные требования выполнены в полном объёме.
Визуально макет с сайтом сходится. 
Итого: 100-18 = 82 балла.

**Comment by valerydluski** [comment]
Апелляция производится только если ожидаемый вами балл и полученным по результатам кросс-чека средний балл отличаются на 15 и более процентов.
