### ISSUE TITLE
Cross-Check 'webdev' - 'Silver248'

### ISSUE THREAD

**Issue by Silver248** [rolling-scopes-school/support#117]
1. https://silver248.github.io/webdev/
2. https://github.com/Silver248/webdev
3. 75 баллов - В интерактивной панели навигации у элемента About отступ до подчеркивания отсутствует. В футере Credit идет без подчеркивания. - вычеты за смещение макета более 5 px почти в каждом блоке.
4.  Средний балл кросс-чека - 66.5
{Student 4
Score: 38
Cтраница открывается по указанной ссылке и она не пустая +20.
Header  - 8 (xедер "липким" делать не нужно)
Your Life - 4 (текст и кнопка отличается больше чем на 5px)
Rappresent - 4 (текст и кнопка отличается больше чем на 5px
Our Community - 0 (размер блока не соответствует, нет визуальных эффектор на переключателе слайдеров )
Implement - 2 (отсутствие интерактивности, отклонение при наложении)
Sign Up - 0 (отсутствие интерактивности, несовпадение с макетом)
Download - 0 (две кнопки отсутствие интерактивности и несовпадение с макетом)
Footer - 0 (несовпадение с макетом) }

**Comment by valerydluski** [comment]
Апелляция производится только если ожидаемый вами балл и полученным по результатам кросс-чека средний балл отличаются на 15 и более процентов.
