### ISSUE TITLE
Cross-Check 'webdev' - 'Alidzhon Khosabekov'

### ISSUE THREAD

**Issue by Alidzhon** [rolling-scopes-school/support#118]
webdev Cross-Check: Submit

**Comment by Alidzhon** [comment]
Ссылка на репозиторий: https://alidzhon.github.io/webdev/

**Comment by Alidzhon** [comment]
Оценка не выставленна можете пожалуйста проверить

**Comment by valerydluski** [comment]
Оформите по правилам школы, пожалуйста.

**Comment by Alidzhon** [comment]
Ссылка на деплой проект: https://alidzhon.github.io/webdev/
Ссылка на репозиторий: https://github.com/Alidzhon/webdev

Оценка не выставлена в ходе проверки
Балл за cross-check 75, 50

**Comment by valerydluski** [comment]
1. Header +8
  Логотип должен быть по центру (-2 балла)
2. Your Life +5
  Иконки должны быть интерактивными (-2 балла)
  Все элементы расположены не по макету (-3 балла)
3. Rappresent +5
   В текстовом блоке есть важный текст, который выделен жирным. Для него нужно использовать логический элемент.(strong) -2 балла
  Кнопка и текст расположены не правильно (-3 балла)
4. Our Community +3
  1, /, 5 должны быть раздельными элементами. -2 балла
  Стрелки не интерактивные. -2 балла
  Все элементы расположены не по макету (-3 балла)
5. Implement +5
   В текстовом блоке есть важный текст, который выделен жирным. Для него нужно использовать логический элемент. -2 балла
  Кнопка и текст расположены не правильно (-3 балла)
6. Sign Up +8
  Поле your email должно иметь валидацию на тип email. -2 балла
7. Download +10
8. footer +5
  Панель навигации не интерактивная. -2 балла
  Логотип очень сильно уплыл -3 балла
9. Деплой +20

Итого: 69 балла

**Comment by Alidzhon** [comment]
Спасибо большое!
