### ISSUE TITLE
Cross-Check 'webdev' - 'SweetSheldon'

### ISSUE THREAD

**Issue by SweetSheldon** [rolling-scopes-school/support#119]
Ссылка на деплой: https://sweetsheldon-webdev.netlify.app/
Ссылка на репозиторий с проектом на GitHub: https://github.com/SweetSheldon/rsschool-tasks/tree/master/webdev
Оценка в результате самопроверки, с ее аргументацией: не заметил грубых отступлений от макета(старого), разве что, в поле E-mail есть разбежка, но не более 5 пкс.
Таким образом, выставил бы себе 100 баллов
Балл за cross-check из вашего Score: 79 
Вероятно,  проверяющий сверял со старым макетом

**Comment by valerydluski** [comment]
Апелляция производится только если ожидаемый вами балл и полученным по результатам кросс-чека средний балл отличаются на 15 и более процентов.
У вас в score за webdev 99 баллов.

**Comment by SweetSheldon** [comment]
Сори, подумал, что речь про ожидаемый балл от определенного проверяющего, а  не общий
