### ISSUE TITLE
 Cross-Check Singolo - k-gorod (https://github.com/k-gorod)

### ISSUE THREAD

**Issue by k-gorod** [rolling-scopes-school/support#12]
1. https://k-gorod.github.io/singolo/
2. https://github.com/k-gorod/singolo
3.
![image](https://user-images.githubusercontent.com/58625453/76358728-fb0e0e00-632a-11ea-8567-d00b3750b55c.png)
4. 60 баллов (Судя по всему)

**Comment by Stepbackru** [comment]
Приступил к рассмотру апелляции, ожидайте

**Comment by Sannnao** [comment]
Отличная работа, кроме одного момента:
![image](https://user-images.githubusercontent.com/44711578/76676932-8280a900-65d9-11ea-8654-ed914bcad659.png)
-3

**Comment by k-gorod** [comment]
Благодарю. Подскажите пожалуйста, почему оценки нет в скоре? Может быть я
что-то не так сделал, и мне нужно что-то исправить?

сб, 14 мар. 2020 г., 9:53 Sasha <notifications@github.com>:

**Comment by Sannnao** [comment]
Я перепроверил и есть еще пару замечаний:

- ![image](https://user-images.githubusercontent.com/44711578/76707582-6bd57180-6701-11ea-8cb1-d967863c78e7.png)
Тут текст не должен выпихивать другие элементы. -3

- ![image](https://user-images.githubusercontent.com/44711578/76707650-1188e080-6702-11ea-8532-ad8437fe2fad.png)
Тут у текста нет свойста text-align: justify -3

-9 в итоге.

Почему нету в скоре - не знаю, я только проверяю

**Comment by Sannnao** [comment]
> Отличная работа, кроме одного момента:
> ![image](https://user-images.githubusercontent.com/44711578/76676932-8280a900-65d9-11ea-8654-ed914bcad659.png)
> -3

Еще скажите. У вас так же отображается?

**Comment by Stepbackru** [comment]
Ваша оценка - 85 баллов 
Отзыв по пунктам ТЗ:
1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла 
2) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции About: минус -3 балла 
3) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Get a Quote: минус -3 балла 
4) Номер телефона в блоке Contacts не реализован ссылкой, работающей с префиксом tel:: минус -3 балла 
5) Электронная почта в блоке Contacts не реализована ссылкой, работающей с префиксом mailto:: минус -3 балла

**Comment by k-gorod** [comment]
1)
Задача была в том, чтобы текст был на протяжении всего блока, и
переносился. Этого есть и без text-align, так как я явно указываю ширину
блока. С этим свойством текст выглядит как растянутое дерьмо, поэтому, как
и так все по условию нормально выровнено, как написано в условии
"аналогами" решения проблемы смещения текста в блок. Я посчитал правильным
его убрать.

2)Блок сервисы-у меня нет там разницы в 2 пикселя. Возможно потому что у
меня экран старый, квадратный. И масштабирование другое. Видео-пожалуйста:
https://youtu.be/CZWWfTqTwC0
Все блоки на своих местах, и отмеряны марджинами. В некоторых местах с
точностью до сотых!

 Ссылки да, я сделал не правильно, и уже исправил, когда узнал что от меня
вообще требуют. И то, только на стриме.

Не плохо было бы Вам открыть вообще код, и прочитать те же условия ТЗ.


вс, 15 мар. 2020 г., 21:51 Alexander <notifications@github.com>:
