### ISSUE TITLE
Cross-check "Caesar cipher CLI tool" - ra44o

### ISSUE THREAD

**Issue by ra44o** [rolling-scopes-school/support#120]
- project repo (https://github.com/ra44o/nodejs-caeser-cipher-cli)
- 90 (1 - есть проблема с кодировкой, 2 - есть проблема с созданием файлов, если они не существоавали. остальные пункты, которые указал ревьюирующий, у меня выполняются корректно).
- 65 (комментарий ревьюирующего в [здесь](https://imgur.com/gallery/NT7ocLq))

**Comment by Student-Java** [comment]
https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f
