### ISSUE TITLE
 Cross-Check 'my_caesar_cli' - abzalt

### ISSUE THREAD

**Issue by AbzalT** [rolling-scopes-school/support#121]
Добрый день прошу провести апелляцию
репозиторий - https://github.com/AbzalT/nodejs-course-2020q3
код задачи - https://github.com/AbzalT/nodejs-course-2020q3/tree/master/src/tasks/task01
оценка на которую претендую - 100 балов, 
за что снимали балы:
1. код задачи лежит не в корне репозитория - на самом деле код задачи вложен в папку /src/tasks/, я сдавал эту задачу до появления тулы кросчека, на стриме допускалось вложенность задач
2. за отсутствие реадми файла - я использовал общий реадми проекта - в разделе этой задачи есть текст поясняющий где что лежит
дело в том что я использовал репозиторий на базе шаблона, а не отдельно под задачу - это в явном виде нигде не запрещено.
текущая оценка - (100 + 75 + 80) / 3 =  85 балов

**Comment by NexGenUA** [comment]
Приложение работает в соотвествии с тз. 
В файле README.md описание для запуска другого приложения.
В неочевидном месте (в файле TASKS.md) есть упоминание в какой дирректории находится код приложения, всего одной строкой.
Моя оценка 95.

**Comment by AbzalT** [comment]
спасибо
возражений и претензий не имею

**Comment by AbzalT** [comment]
а когда оценка в скор пойдет?

**Comment by AbzalT** [comment]
на всякий случай, после 2-й задачи, перенеси 1-ю задачу в отдельный репозиторий - https://github.com/at-rsschool/my_caesar_cli

**Comment by Student-Java** [comment]
Самое позднее в понедельник изменится оценка в скоре
