### ISSUE TITLE
Cross-Check 'Calculator' - 'AriMar775'

### ISSUE THREAD

**Issue by AriMar775** [rolling-scopes-school/support#122]
Добрый день!
1. Деплой: https://rolling-scopes-school.github.io/arimar775-JS2020Q3/calculator/
2. Репозиторий: https://github.com/rolling-scopes-school/arimar775-JS2020Q3
3. Самопроверка 40/40. Операции, за которые снижены баллы работают корректно (работа с отрицательными числами).
4. Результат 33. Проверка была проведена только двумя студентами, один из которых указал на отсутствие работы с отрицательными числами, второй выставил максимальный балл.

**Comment by CotRod** [comment]
Добрый день! Нас проверял, видимо, один и тот же человек, который не додумался нажать на минус, чтобы написать отрицательное число. Обидно, что те, кто урезают балл просто так - не указывают свой ник и с ними невозможно связаться. Правда у меня балл получился 35 и апелляцию я не могу подавать. Модераторы, пожалуйста, сделайте так, чтобы нельзя было анонимно проверять задания.

**Comment by Shemchuk** [comment]
Аналогичная ситуация, ребята!) Мой проверяющий тоже не смог найти кнопку изменения знака +/-, а также ещё и с возведением в степень не справился. В итоге баллы от трёх студентов получились 40/40/25, что в среднем как раз даёт 35. Остаётся поднажать и вкладываться в будущие задания

**Comment by valerydluski** [comment]
Каждый оформляет issue сам. Не надо тут в комментариях писать.

**Comment by valerydluski** [comment]
Ваша оценка - 40 баллов 
Отзыв по пунктам ТЗ:
Выполненные пункты:
1) 1 + 2 => 3 

2) 23 + 69.5 => 92.5 

3) 74 * 3 - 5 => 217 

4) 2 + 3 => 5 продолжаем ввод 4 => 4 - после равно следующая цифра перезаписывает результат 

5) есть кнопка, позволяющая очистить результат 

6) 25 √ => 5 или √ 25 => 5 - любой вариант правильный 

7) 9 √ + 1 => 4 или √ 9 + 1 => 4 - любой вариант правильный 

8) 2 ^ 2 => 4 

9) 15 ^ 3 => 3375 

10) 10.1 ^ 3 => 1030.301 

11) -9 / -3 => 3 

12) 2 + -2 => 0 

13) 2 / -2 => -1 

14) -9 ^ 3 => -729 

15) -9 √ => уведомление об ошибке или √ - 9 => уведомление об ошибке - любой вариант правильный 

16) 0.1 + 0.2 => 0.3 

17) 0.4 - 0.1 => 0.3 

18) 0.0004 + 0.0004 => 0.0008 

19) -0.1 * 0.2 => -0.02 

20) -0.15 + -0.15 => -0.3 - а не - 0.30
