### ISSUE TITLE
Cross-Check 'Calculator' - LexSava

### ISSUE THREAD

**Issue by LexSava** [rolling-scopes-school/support#123]
Деплой:
https://rolling-scopes-school.github.io/lexsava-JS2020Q3/calculator/

Репозиторий:
https://github.com/rolling-scopes-school/lexsava-JS2020Q3/pull/4

Своя оценка: 40
Все примеры из Cross-Check приложение считает без ошибок.

Баллы за crosscheck из Score:

Student1: 40
Student2: 25
Student3: 40

Student2 поставил 25 баллов, у него возникли проблемы с преобразованием числа в отрицательное. Что бы этого не было, мной заранее была написана подробная инструкция как работает эта функция в моем приложении (ни заметить эту инструкцию не возможно).
Прошу пересмотреть оценку Student2. Заранее спасибо.

**Comment by InikonZS** [comment]
- В мозилле выдает undefined вместо чисел, проблема в использовании нестандартного свойства outerText вместо textContent.
- В целом все работает, с отрицательными числами проблем не возникает, если действовать по инструкции, дроби выводятся корректно.

Итого: **40**
