### ISSUE TITLE
Cross-Check 'Calculator' - '@thrvrce'.

### ISSUE THREAD

**Issue by thrvrce** [rolling-scopes-school/support#124]
Деплой:
https://rolling-scopes-school.github.io/thrvrce-JS2020Q3/calculator/

Репозиторий:
https://github.com/rolling-scopes-school/thrvrce-JS2020Q3

Своя оценка: 35. Снизил из-за того, что проблему округлений решил просто округляя результат до 10 знаков после запятой. В целом калькулятор отрабатывает корректно по тестовым кейсам предложенным для проверки(базовая функциональность, степень\корень, отрицательные числа, дроби).

Оценки:
Student1: 40;
Student2: 30. Причина снижения: "Не работают операции с "-". По всем остальным операция вопросов нет".
Student3: 40;
Итоговая: 37.

Оценка Student2 при к Cross-Check была снижена с указанием на невозможность калькулятора работать с отрицательными числами, но калькулятор умеет работать с отрицательными числами.

**Comment by thrvrce** [comment]
Появилась четвертая оценка с после кросс-чека с максимальной оценкой, что привело к тому, что проблемная оценка с минимальным балом была проигнорирована. Возможно, проблему можно снимать.

**Comment by valerydluski** [comment]
закрываю, если всё нормально
