### ISSUE TITLE
Cross-Check 'Calculator' - 'RykeVl'

### ISSUE THREAD

**Issue by RykeVl** [rolling-scopes-school/support#125]
1. https://rolling-scopes-school.github.io/rykevl-JS2020Q3/calculator/
2. https://github.com/rolling-scopes-school/rykevl-JS2020Q3/tree/calculator
3. 40 - Все примеры из описания задания выполняются корректно. Проверил в трёх браузерах и отдавал на проверку другу. Ошибок не было.
4. 34 - 3 и 4 проверяющих написали, что отрицательные числа не реализованы. Лично лишний раз убеждался в том, что всё работает.

**Comment by valerydluski** [comment]
Ваша оценка - 40 баллов 
Отзыв по пунктам ТЗ:
Выполненные пункты:
1) 1 + 2 => 3 

2) 23 + 69.5 => 92.5 

3) 74 * 3 - 5 => 217 

4) 2 + 3 => 5 продолжаем ввод 4 => 4 - после равно следующая цифра перезаписывает результат 

5) есть кнопка, позволяющая очистить результат 

6) 25 √ => 5 или √ 25 => 5 - любой вариант правильный 

7) 9 √ + 1 => 4 или √ 9 + 1 => 4 - любой вариант правильный 

8) 2 ^ 2 => 4 

9) 15 ^ 3 => 3375 

10) 10.1 ^ 3 => 1030.301 

11) -9 / -3 => 3 

12) 2 + -2 => 0 

13) 2 / -2 => -1 

14) -9 ^ 3 => -729 

15) -9 √ => уведомление об ошибке или √ - 9 => уведомление об ошибке - любой вариант правильный 

16) 0.1 + 0.2 => 0.3 

17) 0.4 - 0.1 => 0.3 

18) 0.0004 + 0.0004 => 0.0008 

19) -0.1 * 0.2 => -0.02 

20) -0.15 + -0.15 => -0.3 - а не - 0.30
