### ISSUE TITLE
Cross-Check 'Calculator' - 'kornienko199004'.

### ISSUE THREAD

**Issue by kornienko199004** [rolling-scopes-school/support#126]
Деплой:
https://rolling-scopes-school.github.io/kornienko199004-JS2020Q3/calculator/

Репозиторий:
https://github.com/rolling-scopes-school/kornienko199004-JS2020Q3/tree/calculator/calculator

Своя оценка: 39. Проверял по форме https://calculator-cross-check.netlify.app/

Ваша оценка - 39 баллов 
Отзыв по пунктам ТЗ:
Частично выполненные пункты:
1) 10.1 ^ 3 => 1030.301  (в калькуляторе результат 1030.3)

Выполненные пункты:
1) 1 + 2 => 3 

2) 23 + 69.5 => 92.5 

3) 74 * 3 - 5 => 217 

4) 2 + 3 => 5 продолжаем ввод 4 => 4 - после равно следующая цифра перезаписывает результат 

5) есть кнопка, позволяющая очистить результат 

6) 25 √ => 5 или √ 25 => 5 - любой вариант правильный 

7) 9 √ + 1 => 4 или √ 9 + 1 => 4 - любой вариант правильный 

8) 2 ^ 2 => 4 

9) 15 ^ 3 => 3375 

10) -9 / -3 => 3 

11) 2 + -2 => 0 

12) 2 / -2 => -1 

13) -9 ^ 3 => -729 

14) -9 √ => уведомление об ошибке или √ - 9 => уведомление об ошибке - любой вариант правильный 

15) 0.1 + 0.2 => 0.3 

16) 0.4 - 0.1 => 0.3 

17) 0.0004 + 0.0004 => 0.0008 

18) -0.1 * 0.2 => -0.02 

19) -0.15 + -0.15 => -0.3 - а не - 0.30 

Оценки:
Student 1. Score: 30. Не реализована корректная работа с отрицательными числами
Итоговая: 30.

**Comment by InikonZS** [comment]
- отрицательные числа работают нормально
- корень из отрицательного числа выдает сообщение invalid input, но возведение в дробную степень отрицательного числа просто оставляет пустой экран.
- 10.1 ^ 2 = 102.0   10.1 ^ 3 => 1030.301 - недоработан корректный вывод дробных чисел.
- верстка и код "дефолтные", поэтому без фидбека по ним, многое теряем :( 

Итого: **39**
