### ISSUE TITLE
Cross-check'Calculator'---anastasiya-maximovich

### ISSUE THREAD

**Issue by anastasiya-maximovich** [rolling-scopes-school/support#127]
Добрый день.
Прошу перепроверить работу с калькулятором. Задеплоила неправильно)) Но, 3 ребят отписались и попросили другую рабочую ссылку. 4 студент не проверил. 
В итоге: всем сама даже написала, что при заливке потерялась работа с дробями и клавиша DEL.

Деплой:
https://anastasiya-maximovich.github.io/Calculator/

Репозиторий:
https://github.com/anastasiya-maximovich/Calculator

Оценки проверяющих:
Student 1 -- Score: 16
Student 2 -- Score: 26 (снято 10 -- Не работает десятичная точка и кнопка Del)
Student 3 -- Score: 40 (The link doesn't work so I've reached out with the student and seen the app. It is not perfect but has some strength.)
Итоговая: 27

Студент 1 не защитал работу с корнем из числа и +/-. Эти клавиши работают:

Student 1
Score: 16
23 + 69.5 => 92.5  не работает точка - 2 балла ///(согласна)
не работает кнопка del - 1 бал ///(согласна)
должно √ 25 => 5, у вас 25 - 1 балл ///(НЕ СОГЛАСНА)
должно √ 9 + 1 => 4, у вас 10 - 1 балл///(НЕ СОГЛАСНА)
должно 10.1 ^ 3 => 1030.301, не работает точка - 2 балла///(согласна)
должно -9 / -3 => 3 не работает - 2 балла///(НЕ СОГЛАСНА)
должно 2 + -2 => 0  не работает - 2 балла///(НЕ СОГЛАСНА)
2 / -2 => -1 и 3 / -2 => -1 и 4 / -2 => -1 не работает - 2 балла///(НЕ СОГЛАСНА)
должно  √ - 9 => уведомление об ошибке, у вас -9 - 1 балл///(НЕ СОГЛАСНА)
Действия с дробями не работают -10 баллов///(согласна)

**Comment by InikonZS** [comment]
Проверил, вроде все сходится с самооценкой и итоговый балл почти совпал.
Не работает точка, не работает del, с дробями полученными при делении вроде работает, полностью никак не проверить. _-10_
Со степенями и отрицательными числами все норм.
Итого: **30**
