### ISSUE TITLE
Cross-Check Calculator - Arseni-p

### ISSUE THREAD

**Issue by Arseni-p** [rolling-scopes-school/support#128]
1) деплой - https://rolling-scopes-school.github.io/arseni-p-JS2020Q3/calculator/
2) гитхаб - https://github.com/Arseni-p/Calculator
3) Оценка в результате самопроверки - 40 (требуемые в ТЗ примеры считаются правильно)
4) Балл за cross-check из вашего Score - 37 - (одна из трех оценок проверяюящих сильно занижена)

Комментарии:
Мою работу проверило 3 человека. Двое поставили по 40, а третий поставил 30 с комментариями:
@istad 
Score: 30
Базовая функциональность +10
Дополнительные математические операции +10
**Действия с отрицательными числами +2 (вместо +10)
Действия с дробями +8 (вместо +10)**

Оценивающий с ником "@istad" на контакт не выходит, на сообщения в дискорде не отвечает. Просил несколько человек поверить мою работу, у всех всё работало. За что сняты балы не понимаю и не знаю. Считаю, что эти замечания надуманные, а оценка выставлена несправедливо. Можно ли как-то оценить мою работу по этим замечаниям и исправить, если всё работает как надо?

Мой контакт в discord - @Arseni-p
Спасибо.

**Comment by valerydluski** [comment]
Апелляция производится только если ожидаемый вами балл и полученным по результатам кросс-чека средний балл отличаются на 15 и более процентов.
