### ISSUE TITLE
Logging & Error Handling - cross-check - valerydluski

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/support#129]
1) деплой - https://github.com/valerydluski/express-rest-service
2) Оценка в результате самопроверки - 100 

Комментарии:
Не успел засабмитить задание. Не было доступа к интернету.

**Comment by Student-Java** [comment]
деплой это развернутое приложение, а у тебя ссылка на репо

Ваша оценка - 100 баллов 
Отзыв по пунктам ТЗ:
Выполненные пункты:
1) Реализовано логирование (url, query parameters, body) для всех запросов к серверу с использованием middleware 

2) Добавлена централизованная обработка всех ошибок, которая включает отправку респонса с соответствующим кодом http статуса и их логирование с использованием middleware 

3) Добавлены обработка и логирование ошибок на событие uncaughtException (проверить) 

4) Добавлены обработка и логирование ошибок на событие unhandledRejection (проверить) 

5) Процесс логирования осуществляется единственным модулем
