### ISSUE TITLE
Cross-Check Singolo CasperCarver

### ISSUE THREAD

**Issue by CasperCarver** [rolling-scopes-school/support#13]
1. https://caspercarver.github.io/singolo/
2. https://github.com/CasperCarver/singolo
3.
  ```
3) В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, 
выходящий за размеры по макету, не скрыт: минус -3 балла 

4) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) 
текст  переносится на следующую строку: минус -3 балла 
```
Итого: 94
4.  
``` Student 1
Ваша оценка - 82 баллов 

Отзыв по пунктам ТЗ:

1) В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss 
отсутствуют до 24.02.2020: минус -10 баллов 

2) Трехколоночный макет в секции Services снизу реализован с display: flex, 
однако каждому ряду задан отдельный flex-контейнер: минус -2 балла 

3) В секции Services при добавлении избыточного текста в текстовую ячейку 
(ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла 

4) При увеличении длины значения элемента с именем в секции About 
(сами дописываем очень длинный текст) текст  переносится на следующую строку: минус -3 балла
```

Дополнительный комментарий: проверяющий не обратил внимание на мои другие ветки: task singolo1 я сделал 16 февраля, за 8 дней до дедлайна. 
По флексам  в флексах тоже не соглашусь. Задание по этому пункту выполнено в полной мере.
Я понимаю что разница не превышает 12 баллов, но все-таки, хотябы коммит проверьте-это не сложно. Просто самый большой балл снимают(10) за то что человек не увидел этот коммит... спасибо.

**Comment by sovaz1997** [comment]
Готов перепроверить, если что :)

**Comment by sovaz1997** [comment]
Превел ревью работы.
Отличная работа!
Итоговая оценка - 94 балла.

Проблемы только в добавлении избыточного текста в Services и в блок с именем в секции About, за это снижено 6 баллов (2*3). Дедлайны по выполнению соблюдены.
