### ISSUE TITLE
Cross-Check virtual keyboard  chernataly2020-JS2020Q3

### ISSUE THREAD

**Issue by chernataly2020** [rolling-scopes-school/support#130]
Ссылка на деплой вашего проекта: https://chernataly2020-js2020q3-momentum.netlify.app
Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/chernataly2020-JS2020Q3/tree/gh-pages/momentum
Оценка в результате самопроверки, с ее аргументацией.
Я оцениваю свою работу ориентировочно на 40 баллов. Один из проверяющих выставил 17 баллов, не заметив в работе ряд деталей.

3) есть кнопка, при клике по которой можно пролистать все фоновые изображения за сутки. Если кнопка смены изображений на время перехода одного изображения в другое становится неактивной, это не является ошибкой 

Эта кнопка - картинка бабочки на экране

4) изображения пролистываются в том же порядке, в котором они менялись бы в реальном времени (утро, день, вечер, ночь), начиная с того, которое соотвествует текущему времени суток. После пролистывания всех 24 картинок мы должны вернуться к первой и пойти по новому кругу (тому же самому) 

От времени суток пролистывание изображение зависит. Посмотрите код программы

7) есть кнопка, при клике по которой меняется цитата 

Эта кнопка спрятана под картинкой раскрытой книги

8) в приложении есть возможность указать город 

Попробуйте вместо города Желтые Воды ввести другое название города - прогноз погоды изменится.

9) для указанного пользователем города выводится прогноз погоды 

Этот пункт выполнятся, смотрите описание выше.

12) элементы приложения оптимально занимают площадь страницы. Проверям что нет ситуации когда все элементы прижаты к верху, низу, боку страницы, что они имеют достаточный размер, что автор приложил хоть какие-то усилия для размещения элементов на странице, а не просто добавил их. Соответствие приложения вашему вкусу не проверяем и не оцениваем 

Считаю, что элементы размещены оптимально.

15) интерактивность кликабельных элементов. Стили при наведении, фокусе, клике меняются плавно 
Интерактивность добавлено к иконке, кнопкам - книге и бабочке, и иконке погоды, это видно в коде

Балл за cross-check из вашего Score: 17 баллов.

**Comment by valerydluski** [comment]
А разве кроссчек уже закончился?
