### ISSUE TITLE
Cross-check momentum - cptShell

### ISSUE THREAD

**Issue by cptShell** [rolling-scopes-school/support#131]
[Проект](https://rolling-scopes-school.github.io/cptshell-JS2020Q3/momentum/)
[Репо с проектом](https://github.com/rolling-scopes-school/cptshell-JS2020Q3)

### Самопроверка по пунктам как в задании.
**Basic**

1) Время выводится и в нужном формате и обновляется +2
2) День, дата и месяц - все выводится как надо +2
3) Имя и цель вводятся с помощью Enter +2
4) Да, все данные выше сохраняются в local storage и да, отображаются корректно +2
5) Да, изображения меняются, это можно проверить прямо в консоли, взяв индекс и найдя эту же картинку в папке, что будет соответствовать времени суток
6) При клике текст все же исчезает, и в случае ввода целого "ничего" он возвращается и не ввиде заглушки, а по честному. Не бойтесь, если текст исчез, просто вводите буквы, в случае чего - все вернется на место.

**Background**
1) Из-за своей глупой ошибки в 2ух переменных я не заметил, кал сломал смену фона каждый час - честный 0
2) Кнопка есть, она в правом верхнем углу, она может пролистать фон за сутки и не только +2
3) Изображения листаются по нужному порядку, прямо как идут в сутках +2
4) При каждом обновлении у меня формируется массив 24 изображений, по 6 случайных с каждой папки. После выбора они загружаются в память, чтобы следующий пункт выполнялся. За этот пункт +2
5) 2 человека снимали мне оценку за фон, обоснование получил лишь от одного - он хотел это с анимацией. А я лично хотел, чтобы было как в примере из задания, где плавная смена на моем тормозящем ноуте тоже номинально грузится отлично, но иногда есть белый фон. Если верить примеру, то у меня, цитирую "нет ситуации, когда пользователь видит частично загрузившееся изображение". Следуя написанному в инструкции тексту и примеру из задания, на который я опирался, ставлю себе +2

**Quotes**
1) Да, цитата выводится после загрузки, если нету ошибки 429(too many requests) +2
2) Да, после загрузки, если нету 429, то заглушка цитаты меняется на новую цитату сама, без участия пользователя +2
3) Кнопка есть, даже 2!!Если вам надо сменить цитату - кликните на цитату, она даже оформлена по заданию как кликабельный элемент. К тому же кнопка, которая меняет фон так же меняет и цитату, я так задумал, чтобы отобразить суть значка refresh через его функционал +2

**Weather**
1) Город указать возможно +2
2) Да, при указании города выводится прогноз
3) Город сохраняется в хранилище и отображается при обновлении, да +2
4) Вот тут я чисто по времени не успевал, если бы я доделывал работу после дедлайна, то не писал бы вам. Тем не менее, функционал частично выполнен. Следуя cross-check flow, я бы поставил хотя бы +1
5) Иконка отображается и меняется в зависимости от погоды, все честно +2
6) Ввод погоды работает по принципу ввода имени и цели, за исключением проверки на возможность получения объекта погоды, то есть в случае некорректного ввода выводится ошибка алертом. Короче, все как и просили +2

**Adaptive**
1) Да, элементы расположены по отведенным им местам +2
2) Элементы в responsive 320px не налазят друг на друга, горизонтальной прокрутки нет, я не знаю, что еще там должно быть, короче рискну поставить +2
3) Содержимое не дергается, блоки всегда на своих местах, ни цитаты, ни погода, ни время - ничего не вылазит и ни с чем не конфликтует +2
4) Шрифт не менее 14px при любом разрешении, специально для читабельсти в зависимости от времени суток меняется не только текст, но так же лежит подложка на, чтобы в кейсах, где вы сами листаете изображения и фон вдруг начал сливаться с текстом, сама подложка сделала текст еще более различимым +2
5) Все, что можно нажать - имеет анимацию при наведении. В общем сами наведите и оцените +2

Одна оценка в кроссчеке(их поставил только 3 человека) сильно подкосила балл с ожидаемых мной **47** до **40,** что попадает под разницу **15%**

_Прошу вас оценить спорные для вас пункты хотя бы частично в мою пользу там, где это возможно. Для меня это правда очень важно. В любом случае, спасибо, что потратили на меня время_

**Comment by valerydluski** [comment]
Ваша оценка - 44 балла 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фоновые изображения меняются каждый час и выбираются в зависимости от времени суток (утро, день, вечер, ночь). Для проверки можно открыть приложение в хх часов 59 минут и подождать пару минут. Смена изображений запускается в 00 минут 00 секунд, но может занять некоторое время. 

Частично выполненные пункты:

2) при клике по кнопке для обновления фонового изображения происходит плавная смена фоновых изображений, нет ситуации, когда пользователь видит частично загрузившееся изображение. Плавность смены фоновых изображений проверяем только в полноэкранном режиме. 

Картинка подгружается полностью, но плавной сменной фона, это трудно назвать.

3) прогноз погоды включает в себя данные о температуре, относительной влажности воздуха, скорости ветра 

4) элемены приложения оптимально занимают площадь страницы. Проверям что нет ситуации когда все элементы прижаты к верху, низу, боку страницы, что они имеют достаточный размер, что автор приложил хоть какие-то усилия для размещения элементов на странице, а не просто добавил их. Соответствие приложения вашему вкусу не проверяем и не оцениваем 

многие элемент приклеены к краю страницы

5) при смене даты и времени, смене цитаты, смене фонового изображения, содержание страницы не дёргается, размеры блоков остаются прежними, кнопки для смены цитаты и смены фонового изображения остаются на своих местах 

при смене времени часы дергаются

Выполненные пункты:
фоновое изображение и приветствие изменяются в зависимости от времени суток (утро, день, вечер, ночь) 

1) время выводится в 24-часовом формате, обновляется каждую секунду 

2) выводится день недели, дата, месяц 

3) можно ввести имя пользователя и его цель. Для ввода данных используется клавиша Enter. Не являются ошибкой дополнительные способы ввода данных, например, при потере фокуса, как в исходном проекте 

4) имя пользователя и его цель сохраняются в local storage и отображаются после обновления страницы 

5) при клике в поле ввода текст, который там был, исчезает, если пользователь ничего не ввёл или ввёл пустую строку, текст восстанавливается. Не является ошибкой исчезновение текста только после того, как пользователь начал что-то печатать в поле ввода. Не проверяем поведение поля ввода при введении строки, состоящей из одних пробелов или знаков препинания и т.д. 

6) есть кнопка, при клике по которой можно пролистать все фоновые изображения за сутки. Если кнопка смены изображений на время перехода одного изображения в другое становится неактивной, это не является ошибкой 

7) изображения пролистываются в том же порядке, в котором они менялись бы в реальном времени (утро, день, вечер, ночь), начиная с того, которое соотвествует текущему времени суток. После пролистывания всех 24 картинок мы должны вернуться к первой и пойти по новому кругу (тому же самому) 

8) при обновлении страницы формируется новый список фоновых изображений на текущие сутки. То есть при обновлении страницы изображение скорей всего изменится (есть небольшая вероятность что новый список вернёт ту же картинку для текущего часа, тогда обновите страницу ещё раз). 

9) при загрузке приложения выводится цитата или другой короткий текст (высказывание, шутка, анекдот и т.д.) Наличие или отсутствие автора цитаты не является ошибкой 

10) при перезагрузке страницы цитата заменяется на другую (есть небольшая вероятность что API вернёт ту же цитату, тогда обновите страницу ещё раз)  

11) есть кнопка, при клике по которой меняется цитата 

12) в приложении есть возможность указать город 

13) для указанного пользователем города выводится прогноз погоды 

14) указанный пользователем город сохраняется в local storage и отображается при обновлении страницы. Также отображается прогноз погоды для него 

15) прогноз погоды включает в себя иконку погоды. Иконка погоды генерируется по тем данным, которые возвращает API. Для другого города иконка может быть другой. Проверяем не только наличие иконки, но и меняется ли она при изменении прогноза погоды 

16) если пользователь вводит пустую строку (поставил курсор, нажал Enter), отображается прежний город и прогноз погоды для него. Если пользователь вводит данные, для которых API погоды не возвращает результат, прогноз погоды не выводится, выводится уведомление об ошибке в человекочитаемом формате (подойдёт любой осмысленный текст или слово). Для строки состоящей из одних пробелов, или знаков препинания, или одних цифр поведение не проверяем 

17) приложение корректно отображается как на компьютере, так и на мобильных устройствах. Отсутствует горизонтальная полоса прокрутки. На мобильных устройствах (768px и меньше) вертикальная полоса прокрутки может присутствовать. Минимальное разрешение экрана, при котором проверяем корректность отображения приложения - 320px 

18) шрифт достаточного размера (не меньше 14рх) и контрастности, хорошо читается на любом фоне. Проверяем визуально, если есть сомнения, размер шрифта смотрим в DevTools браузера, для проверки контрастности используем рекомендованный в задании инструмент. 

19) интерактивность кликабельных элементов. Стили при наведении, фокусе, клике меняются плавно

**Comment by valerydluski** [comment]
К сожалению по правилам школы оценка повышаться не будет. 

Вот пункт из документации школы: В случае, когда полученная во время апелляции оценка отличается от оценки, полученной в шаге #4, менее чем на 15%, итоговая оценка повышаться не будет
