### ISSUE TITLE
cross-check shelter

### ISSUE THREAD

**Issue by Mikhail-Kurilov** [rolling-scopes-school/support#132]
при проверке моего shelter один студент поставил следующее:
human-cylon 
Score: 22
Я тоже не успела до конца доделать это задание :)
Не смогла открыть pets page, если она есть, срочно напиши мне в дискорд alinas(@human-cylon) или в телеграм baby_llama89 
сообщил, что открывается about-shelter. данная особа ответила пол часа назад с формулировкой, что сейчас поздно что-то менять. 
я бы не писал, но, зная, что некоторые студенты за 2 балла пишут в пм и с учетом того, что моя работа никак не хуже чем некоторые те, что я проверял прошу обратить внимание, ссылка ниже:
https://rolling-scopes-school.github.io/mikhail-kurilov-JS2020Q3/shelter/pages/main/main.html

**Comment by arumirinka** [comment]
@Mikhail-Kurilov просьба заполнить issue по шаблону, описанному в документации.
https://docs.rs.school/#/cross-check-flow?id=Апелляция
Цитата: "если issue назван или заполнен некорректно - обрабатываться он не будет".
