### ISSUE TITLE
Cross-check momentum  J-u-i-c-y

### ISSUE THREAD

**Issue by J-u-i-c-y** [rolling-scopes-school/support#133]
[Проект](https://rolling-scopes-school.github.io/j-u-i-c-y-JS2020Q3/momentum/)
[Репо с проектом](https://github.com/rolling-scopes-school/j-u-i-c-y-JS2020Q3)

Базовая функциональность

время выводится в 24-часовом формате, обновляется каждую секунду +2
выводится день недели, дата, месяц, например: "Пятница, 25 ноября" +2
можно ввести имя пользователя и его цель. Для ввода данных используется клавиша Enter +2
имя пользователя и его цель сохраняются в local storage и отображаются после обновления страницы +2
фоновое изображение и приветствие изменяются в зависимости от времени суток (утро, день, вечер, ночь) +2
при клике в поле ввода текст, который там был, исчезает, если пользователь ничего не ввёл или ввёл пустую строку, текст восстанавливается +2

Смена фонового изображения

фоновые изображения меняются каждый час и выбираются в зависимости от времени суток (утро, день, вечер, ночь) +2
есть кнопка, при клике по которой можно пролистать все фоновые изображения за сутки +2
изображения пролистываются в том же порядке, в котором они менялись бы в реальном времени (утро, день, вечер, ночь), начиная с того, которое соотвествует текущему времени суток +2
при обновлении страницы формируется новый список фоновых изображений на текущие сутки +2
при клике по кнопке для обновления фонового изображения происходит плавная смена фоновых изображений, нет ситуации, когда пользователь видит частично загрузившееся изображение +2

Цитата дня

при загрузке приложения выводится цитата или другой короткий текст (высказывание, шутка, анекдот и т.д.) +2
при перезагрузке страницы цитата заменяется на другую +2
есть кнопка, при клике по которой меняется цитата +2

Прогноз погоды

в приложении есть возможность указать город +2
для указанного пользователем города выводится прогноз погоды +2
указанный пользователем город сохраняется в local storage и отображается при обновлении страницы. Также отображается прогноз погоды для него +2
прогноз погоды включает в себя данные о температуре, относительной влажности воздуха, скорости ветра
прогноз погоды включает в себя иконку погоды +2
если пользователь вводит пустую строку, данные не меняются, отображается прежний прогноз погоды. Если пользователь вводит данные, для которых API погоды не возвращает результат, выводится уведомление об ошибке в человекочитаемом формате +2

Адаптивный дизайн

элемены приложения оптимально занимают площадь страницы +2
приложение корректно отображается как на компьютере, так и на мобильных устройствах. Отсутствует горизонтальная полоса прокрутки. Минимальное разрешение экрана, при котором проверяем корректность отображения приложения - 320px +2
при смене даты и времени, смене цитаты, смене фонового изображения, содержание страницы не дёргается, размеры блоков остаются прежними, кнопки для смены цитаты и смены фонового изображения остаются на своих местах +2
шрифт достаточного размера (не меньше 14рх) и контрастности Colour contrast checking tool, хорошо читается на любом фоне. Можно использовать полупрозрачный overlay (есть в коллекции изображений) или другой способ, позволяющий обеспечить читаемость текста. +2
интерактивность кликабельных элементов не сводится к свойству cursor:pointer. Стили при наведении, фокусе, клике меняются плавно (используйте свойство transition или @keyframes) +2

Оценка в результате самопроверки 50.
Оценка за кросс-чек 26.

Так как работу оценило всего 3 человека, эта оценка пошла в зачет.
Хотелось бы честной оценки, Спасибо)

**Comment by mauta** [comment]
итоговая оценка 48

Частично выполненные пункты:

1) фоновое изображение и приветствие изменяются в зависимости от времени суток (утро, день, вечер, ночь) - при смене времени суток, поменялся только фон  https://yadi.sk/i/v9JTFqfngwnhgA приветствие поменялось

2) при смене даты и времени, смене цитаты, смене фонового изображения, содержание страницы не дёргается, размеры блоков остаются прежними, кнопки для смены цитаты и смены фонового изображения остаются на своих местах

-все время дергаются часы, при смене цитаты, если цитата без автора, то сильный скачек всех блоков
