### ISSUE TITLE
Cross-Check shelter - babkinevgeny

### ISSUE THREAD

**Issue by babkinevgeny** [rolling-scopes-school/support#134]
1. https://rolling-scopes-school.github.io/babkinevgeny-JS2020Q3/shelter/pages/main/index.html
2. https://github.com/rolling-scopes-school/babkinevgeny-JS2020Q3
3. Результат самопроверки: 100, что и подтвердили проверяющие, которые не стали скрываться
4. Балл из score: 99

Студент, захотевший остаться инкогнито, поставил 96, пояснив свою оценку следующим комментарием "-4 за плохо читаемые бургеры на обеих страницах". Бургеры сделаны в соответствии с макетом и ТЗ, отображаются корректно в любом положении, даже по pixel perfect подходят. Обидно терять балл из-за некомпетентной оценки анонима.

**Comment by valerydluski** [comment]
Проверка производится только если ожидаемый вами балл и полученным по результатам шага #4 средний балл отличаются на 15 и более процентов
