### ISSUE TITLE
Cross-Check virtual-keyboard - korytsa

### ISSUE THREAD

**Issue by korytsa** [rolling-scopes-school/support#135]
1. https://rolling-scopes-school.github.io/korytsa-JS2020Q3/virtual-keyboard/
2. https://github.com/rolling-scopes-school/korytsa-JS2020Q3
3. Результат самопроверки: 32
4. еще не закончен cross-check

Не выполненные пункты:
1. Горизонтальные стрелки для перемещения в пределах строки
2. Подсветка клавиш виртуальной клавиатуры при кликах по клавишам физической клавиатуры
3. Озвучивание нажатия клавиш
4. Голосовой ввод текста

Проблема в том, что я сделала submit решения, а кого проверять не получила

**Comment by valerydluski** [comment]
Ваша оценка - 33 балла 
Отзыв по пунктам ТЗ:

Частично выполненные пункты:

1) есть клавиша Backspace, удаляющая символы перед курсором. Есть клавиша Enter для перехода на новую строку 
feedback: есть клавиша Backspace, удаляющая символы перед курсором. - удаляет последний символ в строке, а не предыдущий перед курсором

feedback: при смене языка при зажатых шифт и капс - не реализовано отображение рабочего состояния, соответсвенно потом появляются косяки типа капс внешне нажат а буквы маленькие и подобное. Это не оценивается - но лучше привести в порядок для портфолио

Не выполненные/не засчитанные пункты:

1) для перемещения в пределах строки добавлены стрелки влево-вправо клики по которым реализуют горизонтальную навигацию курсора. Визуально позиция курсора отображается в виде вертикальной мигающей чёрточки 

2) после перемещения позиции курсора ввод/удаление текста с виртуальной клавиатуры происходит по текущей позиции курсора в т.ч. внутри строки 

3) нажатие на клавиши физической клавиатуры подсвечивает соответствующие алфавитно-цифровые клавиши виртуальной клавиатуры. Проверка осуществляется при одинаковых языках виртуальной и физической клавиатур 

4) нажатие на клавиши Backspace, Enter физической клавиатуры подсвечивает соответствующие клавиши виртуальной клавиатуры, производит то же действие, которое происходит при кликах по клавишам Backspace и Enter мышкой (удаление символа и переход на новую строку)
Работу клавиш Shift и CapsLock виртуальной клавиатуры при кликах по клавишам физической клавиатуры не оцениваем и не проверяем из-за разной их работы в операционных системах Windows и MacOS 

5) при печати на виртуальной клавиатуре воспроизводится звук пишущей машинки, или другие звуки. Если звуки воспроизводятся и при печати на реальной клавиатуре, это не является ошибкой 

6) звуки при печати в русской и английской раскладке отличаются. Предусмотрены уникальные звуки для клавиш Shift, CapsLock, Backspace, Enter. Отличие звуков для клавиш Shift, CapsLock, Backspace, Enter в разных раскладках не требуется 

7) есть возможность включить и отключить озвучивание нажатия клавиш, для этого на виртуальной клавиатуре предусмотрена отдельная клавиша. Активное и неактивное состояние данной клавиши отличается визуально и переключается кликом. 

8) на виртуальной клавиатуре есть отдельная клавиша, при клике по которой можно включить/отключить голосовой ввод текста. Активное и неактивное состояние клавиши отличаются визуально 

9) если голосовой ввод текста включён, в окне для ввода текста выводится текст, который поступает на устройство записи звука (например, микрофон или стереомикшер) указанное в настройках операционной системы. Возможность изменить позицию курсора и/или вносить свои правки в процессе голосового ввода не проверяется и не оценивается. 

10) язык распознавания голоса en/ru меняется при переключении языка виртуальной клавиатуры. Нет требования смены языка "на лету". Последовательность действий при проверке: отключаем голосовой ввод, переключаем язык, включаем голосовой ввод. Если SpeechRecognition при установленном русском языке распознаёт как русский язык, так и английский, это не является ошибкой 

11) голосовой ввод текста продолжается до тех пор, пока активна клавиша голосового ввода
