### ISSUE TITLE
Cross-Check Singolo - ialeks94

### ISSUE THREAD

**Issue by IAleks94** [rolling-scopes-school/support#14]
1) Ссылка на деплой: https://ialeks94.github.io/singolo
2) Ссылка на репозиторий с проектом: https://github.com/IAleks94/singolo

3) Считаю что работа выполнена минимум на 94:

> 4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла
> 
> 5) Внизу как минимум одной из секций (кроме Footer) отсутствует небольшая линия другого цвета: минус -3 балла 
про несоответсвие еще можно поспорить(там как раз что то в раёне 2 пикселей), но фиг с ним.

4) 
```
Ваша оценка - 64 балла

Отзыв по пунктам ТЗ:

1) В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020: минус -10 баллов

2) В коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020: минус -10 баллов

3) В коммитах, или в ветках с коммитами, файлы singolo3.html и singolo3.сss или index.html и style.css отсутствуют до 09.03.2020: минус -10 баллов

4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла

5) Внизу как минимум одной из секций (кроме Footer) отсутствует небольшая линия другого цвета: минус -3 балла 
```
Жаль что человек не в состоянии проверить существование файлов по коммитам (я удалил из репозитория singolo1-3 после создания index)

**Comment by Ambrance** [comment]
В вашей работе 3 коммита за 10 марта (день, когда официально началась проверка).
Считаю честным проверить ваш вариант в предыдущем состоянии репозитория - у вас это 7 марта. 
Если согласны, то откатите изменения в варианте на gh-pages.

**Comment by IAleks94** [comment]
Хм, я не делал отдельной ветки и все через мастер ветку публиковал, так то там исправил переполнение имени в "про нас" и контента в "сервисе", + дописал свойство на растяжение текста (визуально разницы не заметил).  Можно ли откатить, а потом вернуть как было в мастер ветке ?

**Comment by Ambrance** [comment]
Можете создать ветку gh-pages от мастера и уже в ней откатиться на  коммит за 7 марта. В мастере тогда ничего не изменится.

**Comment by IAleks94** [comment]
15 минут гуглинга и я справился, смотри в ветке gh-pages

**Comment by amoebiusss** [comment]
@IAleks94 привет! Ваша итоговая оценка по обновленному алгоритму — 82, наименьшая оценка была исключена из подсчета. От заявленной она отличается на 12 баллов, минимальная разница для апелляции — 15.
