### ISSUE TITLE
Cross-Check RSS Игра в пятнашки - IGrakov

### ISSUE THREAD

**Issue by IGrakov** [rolling-scopes-school/support#141]
Ссылка на деплой вашего проекта: https://rolling-scopes-school.github.io/igrakov-JS2020Q3/gem-puzzle/
Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/igrakov-JS2020Q3.git
Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
Ссылка на форму для проверки проекта (если такая есть): https://rolling-scopes-school.github.io/checklist/

Забыл засабмитить задание gem-puzzle в RS App до дэдлайна, при этом деплой в gh-pages сделан вовремя

**Comment by ansivgit** [comment]
Отсутствует "Оценка в результате самопроверки, с ее аргументацией"

**Comment by IGrakov** [comment]
Оценка самопроверки +90
Выполнены пункты:
- вёрстка, дизайн, UI
- cостояние игрового поля генерируется случайным образом
- при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки
- игру можно начать заново без перезагрузки страницы
- отображается время игры и количество ходов
- реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage
- реализован выбор размера поля
- звуковое сопровождение передвижения фишек
- когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов»

Не выполнены пункты:
- фишки можно перетягивать мышкой
- анимация перемещения пятнашек на поле
- вместо цифр на карточках используются картинки
- реализовано автоматическое, анимированное завершение игры

**Comment by Viklysx** [comment]
Оценка выставлена в параллельном issues: https://github.com/rolling-scopes-school/support/issues/157
