### ISSUE TITLE
Cross-Check - gem-puzzle - blackymax. Забыл засабмитить работу в app.rs.school вовремя, залил на gh-pages до окончания deadline, правки не вносил.

### ISSUE THREAD

**Issue by blackymax** [rolling-scopes-school/support#142]
1. Deploy: https://rolling-scopes-school.github.io/blackymax-JS2020Q3/gem-puzzle
2. Repository: https://github.com/rolling-scopes-school/blackymax-JS2020Q3/tree/gh-pages
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
4. Task checklist: https://rolling-scopes-school.github.io/checklist/
5. Результат самопроверки:
Моя оценка - 115 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 

2) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 

3) реализовано автоматическое, анимированное завершение игры 

Частично выполненные пункты:
1) вёрстка, дизайн, UI 
Отзыв: Дизайна почти нет.
Выполненные пункты:
1) cостояние игрового поля генерируется случайным образом 

2) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 

3) игру можно начать заново без перезагрузки страницы 

4) отображается время игры и количество ходов 

5) реализован выбор размера поля 

6) звуковое сопровождение передвижения фишек 

7) анимация перемещения пятнашек на поле 

8) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 

9) вместо цифр на карточках используются картинки

**Comment by ansivgit** [comment]
Отсутствует "Оценка в результате самопроверки, с ее аргументацией"

**Comment by ansivgit** [comment]
Ваша оценка - 100 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 
2) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 
3) реализовано автоматическое, анимированное завершение игры 

Частично выполненные пункты:
1) вёрстка, дизайн, UI 
Отзыв: Дизайн не адаптивный, игра не влезает по высоте на экран 768
2) cостояние игрового поля генерируется случайным образом 
Отзыв: Игра генерирует только нерешаемые комбинации
3) отображается время игры и количество ходов 
Отзыв: Время отображается некорректно
4) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 
Отзыв: Игра генерит только нерешаемые комбинации, поэтому проверить невозможно. Однако, вижу, что есть в коде, потому -5б

Выполненные пункты:
1) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 
2) игру можно начать заново без перезагрузки страницы 
3) реализован выбор размера поля 
4) звуковое сопровождение передвижения фишек 
5) анимация перемещения пятнашек на поле 
6) вместо цифр на карточках используются картинки
