### ISSUE TITLE
Cross-Check RSS Игра в пятнашки - AGoravskiy

### ISSUE THREAD

**Issue by AGoravskiy** [rolling-scopes-school/support#143]
Деплой: https://rolling-scopes-school.github.io/agoravskiy-JS2020Q3/gem-puzzle/dist/
Репозиторий: https://github.com/rolling-scopes-school/agoravskiy-JS2020Q3
Задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md

Забыл засабмитить задание RSS Игра в пятнашки в RS App до дэдлайна, деплой и PR сделан вовремя.

Самопроверка:
 1) вёрстка, дизайн, UI: +10
 2) состояние игрового поля генерируется случайным образом: +10
 3) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки: +10
 4) игру можно начать заново без перезагрузки страницы: +10
 5) отображается время игры и количество ходов: +10
 6) анимация перемещения пятнашек на поле: +10
После дедлайна добавлено:
 1) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов»
 2) реализовано сохранение состояния игры
 3) реализован выбор размера поля

Итого, результат самопроверки - 60 баллов

**Comment by ansivgit** [comment]
Отсутствует "Оценка в результате самопроверки, с ее аргументацией"

**Comment by valerydluski** [comment]
Есть коммиты после дедлайна.
