### ISSUE TITLE
Cross-Check 'RSS ИГРА В ПЯТНАШКИ' - 'VVladislaVLL' - Не сделал Submit

### ISSUE THREAD

**Issue by VVladislaVLL** [rolling-scopes-school/support#144]
Сделал Pull-request до окончания dedline(видно по дате последнего коммита). Но забыл сделать submit для cross-check.
 
1. Ссылка на деплой проекта: https://rolling-scopes-school.github.io/vvladislavll-JS2020Q3/gem-puzzle/dist/
2. Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/vvladislavll-JS2020Q3/tree/gem-puzzle
3. Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
4. Ссылка на форму для проверки проекта: https://rolling-scopes-school.github.io/checklist/
5. Оценка в результате самопроверки, с ее аргументацией: 
145 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 

Частично выполненные пункты:
1) вместо цифр на карточках используются картинки 
Отзыв: Есть проблема с перемещением первой фишки, она меняет background. Не удалось отловить эту ошибку. Но функционал соответсвует задаче, поэтому минус половина.

Выполненные пункты:
1) вёрстка, дизайн, UI 
2) cостояние игрового поля генерируется случайным образом 
3) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 
4) игру можно начать заново без перезагрузки страницы 
5) отображается время игры и количество ходов 
6) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 
7) реализован выбор размера поля 
8) звуковое сопровождение передвижения фишек 
9) анимация перемещения пятнашек на поле 
10) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 
11) реализовано автоматическое, анимированное завершение игры

**Comment by Viklysx** [comment]
Ваша оценка - 120 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 

Частично выполненные пункты:
1) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 
Отзыв: После загрузки сохраненной игры фишки не перемещаются.
2) звуковое сопровождение передвижения фишек 
Отзыв: Звук работает очень плохо, его почти никогда нет. Лишь спустя несколько попыток удалось его как-то включить, но затем он исчез снова.
3) вместо цифр на карточках используются картинки 
Отзыв: Есть ошибка, о которой указал сам автор

Выполненные пункты:
1) вёрстка, дизайн, UI 

2) cостояние игрового поля генерируется случайным образом 

3) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 

4) игру можно начать заново без перезагрузки страницы 

5) отображается время игры и количество ходов 

6) реализован выбор размера поля 

7) анимация перемещения пятнашек на поле 

8) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 

9) реализовано автоматическое, анимированное завершение игры 

Штрафы:
1) Ошибки в консоли, связанные с исполняемым кодом(ошибки типа favicon.ico: Failed to load resource: the server responded with a status of 404 не учитываются): 

![image](https://user-images.githubusercontent.com/58310634/99865698-9ba41580-2bbc-11eb-8d56-f849493cb8e7.png)
