### ISSUE TITLE
Cross-Check RSS Игра в пятнашки - beafraidnotlearning

### ISSUE THREAD

**Issue by beafraidnotlearning** [rolling-scopes-school/support#145]
1. Деплой: https://rolling-scopes-school.github.io/beafraidnotlearning-JS2020Q3/gem-puzzle
2. Ссылка на репозиторий: https://github.com/rolling-scopes-school/beafraidnotlearning-JS2020Q3
3. Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/5d246c21ac145e1d4f8bc5cd2ec4d09dd8b68118/tasks/gem-pazzle/codejam-the-gem-puzzle.md
4. Ссылка на форму для проверки проекта: https://rolling-scopes-school.github.io/checklist/
5. Оценка в результате самопроверки: 170/170
 - вёрстка, дизайн, UI +10
 - cостояние игрового поля генерируется случайным образом +10
 - при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки +10
 - игру можно начать заново без перезагрузки страницы +10
 - отображается время игры и количество ходов +10
 - фишки можно перетягивать мышкой +10
 - реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage +10
 - реализован выбор размера поля +10
 - звуковое сопровождение передвижения фишек +10
 - анимация перемещения пятнашек на поле +10
 - когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» +10
 - вместо цифр на карточках используются картинки +30
 - реализовано автоматическое, анимированное завершение игры +30
 - В процессе самопроверки, ошибок в консоли, связанных с исполняемым кодом, не обнаружил -0
6. Сross-check еще не завершен

Проблема в том, что я забыл сделать сабмит ссылки на свое решение до окончания дедлайна в Cross-Check: Submit в RssApp и меня не смогут проверить другие студенты.

**Comment by Fodin** [comment]
Оценку самопроверки подтверждаю. 170 баллов.
