### ISSUE TITLE
Cross-Check RSS Игра в пятнашки - Crippton

### ISSUE THREAD

**Issue by Crippton** [rolling-scopes-school/support#146]
Забыл засабмитить задание gem-puzzle в RS App до дэдлайна, при этом деплой в gh-pages сделан вовремя

Ссылка на деплой вашего проекта:
https://rolling-scopes-school.github.io/crippton-JS2020Q3/src/

Ссылка на репозиторий с проектом на GitHub: 
https://github.com/rolling-scopes-school/crippton-JS2020Q3/tree/gh-pages/src
https://github.com/rolling-scopes-school/crippton-JS2020Q3/tree/gem-puzzle

Ссылка на задание: 
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
Ссылка на форму для проверки проекта (если такая есть): 
https://rolling-scopes-school.github.io/checklist/

Ваша оценка - 145 баллов 

Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 
2) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 

Частично выполненные пункты:
1) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 
Отзыв: сохранение есть, но с загрузкой проблема.

Выполненные пункты:
1) вёрстка, дизайн, UI 
2) cостояние игрового поля генерируется случайным образом 
3) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 
4) игру можно начать заново без перезагрузки страницы 
5) отображается время игры и количество ходов 
6) реализован выбор размера поля 
7) звуковое сопровождение передвижения фишек 
8) анимация перемещения пятнашек на поле 
9) вместо цифр на карточках используются картинки 
10) реализовано автоматическое, анимированное завершение игры

**Comment by ansivgit** [comment]
Отсутствует "Оценка в результате самопроверки, с ее аргументацией"

**Comment by Crippton** [comment]
Добавил результат самопроверки с описанием выполненных\невыполненных пунктов

**Comment by ai297** [comment]
Ваша оценка - 140 баллов 

Отзыв по пунктам ТЗ:
**Не выполненные/не засчитанные пункты:**
1. фишки можно перетягивать мышкой 
2. когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 

**Частично выполненные пункты:**
1. вёрстка, дизайн, UI
_Отзыв: Нет адаптива под маленькие экраны_
2. реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage
_Отзыв: При перезагрузке страницы состояние игрового поля восстанавливается из сохранённого, но сбрасывается количество ходов и время на 0. Плюс играть становится невозможно - после одного - двух ходов звучит звук победы и возможность продолжать игру блокируется, даже если паззл не собран. Непонятно как работает скор. если завершил игру за 1 ход получил меньше очков, чем за 50 ходов.. Тем не менее как-то результат сохраняется. Видимо чем меньше - тем лучше. Выиграть можно после авто-завершения, просто передвинув последнюю фишку туда-сюда_

**Выполненные пункты:**
1. cостояние игрового поля генерируется случайным образом 
2. при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 
3. игру можно начать заново без перезагрузки страницы 
4. отображается время игры и количество ходов 
5. реализован выбор размера поля 
6. звуковое сопровождение передвижения фишек 
7. анимация перемещения пятнашек на поле 
8. вместо цифр на карточках используются картинки 
9. реализовано автоматическое, анимированное завершение игры
_Отзыв: Если во время автоматического завершения игры начать новую игру - она продолжит собираться автоматически. Но проблемы не с этим. После Перезагрузки страницы ломается не только сохранённая игра, но и автоматическое завершение, пока не начнёшь новую игру. Баллов не снижаю за это, но ощущение недоделанности от работы остаётся_
10. Ошибок в консоли нет.
_Отзыв: Ошибки вылезают при попытке продолжить сохранённую игру, отдельно за это не снижаю. Но посторонний вывод в консоли присутствует, не почистили отладочные логи._

**Comment by Crippton** [comment]
спасибо!
