### ISSUE TITLE
Cross-Check 'gem-puzzle' - 'maxtadont'- не сделал submit

### ISSUE THREAD

**Issue by Maxtadont** [rolling-scopes-school/support#147]
https://rolling-scopes-school.github.io/maxtadont-JS2020Q3/gem-puzzle/
https://github.com/rolling-scopes-school/maxtadont-JS2020Q3
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
https://rolling-scopes-school.github.io/checklist/

Не сделал submit задания. Push и PullRequest сделаны до дедлайна.

Ваша оценка - 100 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 

2) вместо цифр на карточках используются картинки 

3) реализовано автоматическое, анимированное завершение игры 

Выполненные пункты:
1) вёрстка, дизайн, UI 

2) cостояние игрового поля генерируется случайным образом 

3) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 

4) игру можно начать заново без перезагрузки страницы 

5) отображается время игры и количество ходов 

6) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 

7) реализован выбор размера поля 

8) звуковое сопровождение передвижения фишек 

9) анимация перемещения пятнашек на поле 

10) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов»

**Comment by Viklysx** [comment]
Ваша оценка - 95 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 

2) вместо цифр на карточках используются картинки 

3) реализовано автоматическое, анимированное завершение игры 

Частично выполненные пункты:
1) вёрстка, дизайн, UI 
Отзыв: На маленьких экранах игровое поле очень маленькое.

Выполненные пункты:
1) cостояние игрового поля генерируется случайным образом 

2) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 

3) игру можно начать заново без перезагрузки страницы 

4) отображается время игры и количество ходов 

5) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 

6) реализован выбор размера поля 

7) звуковое сопровождение передвижения фишек 

8) анимация перемещения пятнашек на поле 

9) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов»

**Comment by Maxtadont** [comment]
Спасибо, 
да действительно на смартфоне поле мелковато
