### ISSUE TITLE
Cross-Check 'gem-puzzle' - 'katyamishha'- не сделала submit

### ISSUE THREAD

**Issue by katyamishha** [rolling-scopes-school/support#148]
https://rolling-scopes-school.github.io/katyamishha-JS2020Q3/gem-puzzle/
https://github.com/rolling-scopes-school/katyamishha-JS2020Q3
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
https://rolling-scopes-school.github.io/checklist/

Ваша оценка - 30 баллов
Отзыв по пунктам ТЗ:
Выполненные пункты:
1) вёрстка, дизайн, UI
2) cостояние игрового поля генерируется случайным образом
3) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки

**Comment by ansivgit** [comment]
Ваша оценка - 35 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) игру можно начать заново без перезагрузки страницы 
2) отображается время игры и количество ходов 
3) фишки можно перетягивать мышкой 
4) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 
5) реализован выбор размера поля 
6) звуковое сопровождение передвижения фишек 
7) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 
8) вместо цифр на карточках используются картинки 
9) реализовано автоматическое, анимированное завершение игры 

Частично выполненные пункты:
1) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 
Отзыв: Иногда в игре фишки залезают друг под друга

Выполненные пункты:
1) вёрстка, дизайн, UI 
2) cостояние игрового поля генерируется случайным образом 
3) анимация перемещения пятнашек на поле
