### ISSUE TITLE
Cross-Check 'Singolo' - 'HolubIvan'

### ISSUE THREAD

**Issue by HolubIvan** [rolling-scopes-school/support#15]
1. Ссылка на деплой: https://holubivan.github.io/singolo/

2. Ссылка на репозиторий с проектом: https://github.com/HolubIvan/singolo

3. Считаю что работа выполнена минимум на 88, мои ошибки:

1) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Services: минус -3 балла 
2) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции About: минус -3 балла 
3) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Get a Quote: минус -3 балла 
4) В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла 

'ошибки представленные проверяющим: 1) шрифты подключены в head, 2)fish text мог быть любым а не как в макете, 3) в input указаны required верно'

4. Балл за cross-check из Score выставленный проверяющим

Ваша оценка - 68 баллов 

Отзыв по пунктам ТЗ:

1) На странице отсутствует семейство шрифтов Lato. Шрифты не подключены в html путем добавления ссылки на cdn с ними либо не хранятся в папке assets: минус -5 баллов 

(сам про этот пункт узнал только сейчас при проверке :) )

2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Slider составляют более двух пикселей (2px): минус -3 балла 

(текст вообще другой в макете)

3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла 

(текст вообще другой в макете)

4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла 

(текст вообще другой в макете)

5) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла 

(в инпутах текст не прописан)

6) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify в секции Services: минус -3 балла 

(так же был удивлен что нужно делать именно так :) )

7) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify в секции About: минус -3 балла 

8) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify в секции Get a Quote: минус -3 балла 

9) В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла 

10) Не выполняется валидация обоих полей ввода с отметкой Required в макете, или указан неправильный тип "< input >", или отсутствуют необходимые атрибуты, или при пропуске/вводе невалидных значений форма отправляется без ожидаемых замечаний: минус -3 балла 

(нет валидации в name, пролазит вообще все что вводишь)

**Comment by igorburenko** [comment]
Готов проверить
