### ISSUE TITLE
Cross-Check 'gem-puzzle' - 'Nazimkov-1984'-забыл засабмитить ссылку

### ISSUE THREAD

**Issue by Nazimkov-1984** [rolling-scopes-school/support#150]
Забыл засабмитить ссылку!
https://rolling-scopes-school.github.io/nazimkov-1984-JS2020Q3/gem-puzzle/ - ссылка на деплой
https://github.com/rolling-scopes-school/nazimkov-1984-JS2020Q3/tree/gem-puzzle - ссылка на репозиторий
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md - ссылка на задание
Score 80/170
Ваша оценка - 80 баллов
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:

фишки можно перетягивать мышкой

реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage

реализован выбор размера поля

вместо цифр на карточках используются картинки

реализовано автоматическое, анимированное завершение игры

Выполненные пункты:

вёрстка, дизайн, UI

cостояние игрового поля генерируется случайным образом

при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки

игру можно начать заново без перезагрузки страницы

отображается время игры и количество ходов

звуковое сопровождение передвижения фишек

анимация перемещения пятнашек на поле

когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов»

**Comment by ansivgit** [comment]
Отсутствует "Оценка в результате самопроверки, с ее аргументацией"

**Comment by Nazimkov-1984** [comment]
> Отсутствует "Оценка в результате самопроверки, с ее аргументацией"

исправил!

**Comment by ansivgit** [comment]
Ваша оценка - 70 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 
2) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 
Отзыв: Кнопка присутствует, но сохраняет только время и ничего не восстанавливает
3) реализован выбор размера поля 
4) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 
Отзыв: вижу, что предусмотрена в коде, но по факту не выводится
5) вместо цифр на карточках используются картинки 
6) реализовано автоматическое, анимированное завершение игры 

Выполненные пункты:
1) вёрстка, дизайн, UI 
2) cостояние игрового поля генерируется случайным образом 
3) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 
4) игру можно начать заново без перезагрузки страницы 
5) отображается время игры и количество ходов 
6) звуковое сопровождение передвижения фишек 
7) анимация перемещения пятнашек на поле
