### ISSUE TITLE
Cross-Check 'gem-puzzle' - 'iqoffee'-забыл засабмитить ссылку

### ISSUE THREAD

**Issue by iqoffee** [rolling-scopes-school/support#152]
https://rolling-scopes-school.github.io/iqoffee-JS2020Q3/gem-puzzle/dist/
https://github.com/rolling-scopes-school/iqoffee-JS2020Q3
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
https://rolling-scopes-school.github.io/checklist/

push и pull request  сделаны вовремя

Ваша оценка - 80 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 

2) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 

3) анимация перемещения пятнашек на поле 

4) вместо цифр на карточках используются картинки 

5) реализовано автоматическое, анимированное завершение игры 

Выполненные пункты:
1) вёрстка, дизайн, UI 

2) cостояние игрового поля генерируется случайным образом 

3) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 

4) игру можно начать заново без перезагрузки страницы 

5) отображается время игры и количество ходов 

6) реализован выбор размера поля 

7) звуковое сопровождение передвижения фишек 

8) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов»

**Comment by ansivgit** [comment]
Ваша оценка - 63 балла 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 
2) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 
3) анимация перемещения пятнашек на поле 
4) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 
Отзыв: выпадают нереализуемые комбинации, так что - никогда не выводится

5) вместо цифр на карточках используются картинки 
6) реализовано автоматическое, анимированное завершение игры 

Частично выполненные пункты:
1) вёрстка, дизайн, UI 
Отзыв: Игра по высоте не влезает на экран 768, прокрутка есть, но верх игры не виден все равно

2) отображается время игры и количество ходов 
Отзыв: время игры отображается не в минутах и в секундах, а только в секундах, что не соответствует ТЗ (-2б)

Выполненные пункты:
1) cостояние игрового поля генерируется случайным образом 
2) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 
3) игру можно начать заново без перезагрузки страницы 
4) реализован выбор размера поля 
5) звуковое сопровождение передвижения фишек
