### ISSUE TITLE
Cross-Check 'virtual-keyboard' - 'iqoffee'-забыл засабмитить ссылку

### ISSUE THREAD

**Issue by iqoffee** [rolling-scopes-school/support#153]
https://rolling-scopes-school.github.io/iqoffee-JS2020Q3/virtual-keyboard/
https://github.com/rolling-scopes-school/iqoffee-JS2020Q3
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/ready-projects/virtual-keyboard.md
https://rolling-scopes-school.github.io/checklist/

push и pull request сделаны вовремя

Ваша оценка - 47.5 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Реализована анимация нажатия на кнопку 

Частично выполненные пункты:
1) Нажатие на кнопку на физической клавиатуре подсвечивает кнопку на виртуальной (проверять следуюет нажатие цифр, букв, знаков припинания, backspace, del(если она присутствует), enter, shift, alt, ctrl, tab, caps lock, space, стрелки вниз-вверх-влево-вправо) 
Отзыв: tag textarea
2) Есть переключение между русским и английским языком (сочетание клавиш для переключения языка должно быть указано на странице с клавиатурой), а так же сохранение выбранного языка 
Отзыв: just change language
Выполненные пункты:
1) Реализована генерация DOM-элементов и body в index.html пустой изначально (может находится только тег script) 

2) Клики мышкой по кнопкам на виртуальной клавиатуре или нажатие на кнопки физической клавиатуры, выводят символы в инпут (textarea)

**Comment by Viklysx** [comment]
Ваша оценка - 25 баллов 
Отзыв по пунктам ТЗ:
**Не выполненные/не засчитанные пункты:**
1) при переключении языка на клавише en/ru отображается установленный в данный момент язык 

2) для перемещения в пределах строки добавлены стрелки влево-вправо клики по которым реализуют горизонтальную навигацию курсора. Визуально позиция курсора отображается в виде вертикальной мигающей чёрточки 

3) после перемещения позиции курсора ввод/удаление текста с виртуальной клавиатуры происходит по текущей позиции курсора в т.ч. внутри строки 

4) нажатие на клавиши физической клавиатуры подсвечивает соответствующие алфавитно-цифровые клавиши виртуальной клавиатуры. Проверка осуществляется при одинаковых языках виртуальной и физической клавиатур 

5) при печати на виртуальной клавиатуре воспроизводится звук пишущей машинки, или другие звуки. Если звуки воспроизводятся и при печати на реальной клавиатуре, это не является ошибкой 

6) звуки при печати в русской и английской раскладке отличаются. Предусмотрены уникальные звуки для клавиш Shift, CapsLock, Backspace, Enter. Отличие звуков для клавиш Shift, CapsLock, Backspace, Enter в разных раскладках не требуется 

7) есть возможность включить и отключить озвучивание нажатия клавиш, для этого на виртуальной клавиатуре предусмотрена отдельная клавиша. Активное и неактивное состояние данной клавиши отличается визуально и переключается кликом. 

8) на виртуальной клавиатуре есть отдельная клавиша, при клике по которой можно включить/отключить голосовой ввод текста. Активное и неактивное состояние клавиши отличаются визуально 

9) если голосовой ввод текста включён, в окне для ввода текста выводится текст, который поступает на устройство записи звука (например, микрофон или стереомикшер) указанное в настройках операционной системы. Возможность изменить позицию курсора и/или вносить свои правки в процессе голосового ввода не проверяется и не оценивается. 

10) язык распознавания голоса en/ru меняется при переключении языка виртуальной клавиатуры. Нет требования смены языка "на лету". Последовательность действий при проверке: отключаем голосовой ввод, переключаем язык, включаем голосовой ввод. Если SpeechRecognition при установленном русском языке распознаёт как русский язык, так и английский, это не является ошибкой 

11) голосовой ввод текста продолжается до тех пор, пока активна клавиша голосового ввода 

**Частично выполненные пункты:**

1) в окне для ввода текста сохраняются возможности обычной физической клавиатуры: текст можно набирать, выделять, удалять, добавлять текст в средину строки. **_(нельзя добавлять текст в середину строки и удалять выделенный_)**

2) в окне для ввода текста отображается текущая позиция курсора в виде вертикальной мигающей чёрточки **_(курсор исчезает сразу с потерей фокуса, а должен быть всегда)_**

3) клавиша Shift меняет регистр букв - строчные переводит в заглавные, заглавные (при зажатой CapsLock) переводит в строчные. Две клавиши Shift в задании не требуются **_(нет отдельной клавиши shift, все действия повесили на caps)_**

4) клавиша Shift позволяет выводить дополнительные символы вместо цифр и символов основной раскладки 

5) активное и неактивное состояние клавиши Shift отличаются визуально 

6) переключение клавиши Shift происходит по клику, аналогично тому, как переключается состояние клавиши CapsLock в исходном проекте. Если после ввода одного символа клавиша Shift автоматически возвращается в исходное положение, за такой вариант реализации баллы не снимаем  

7) при зажатой клавише Shift на клавишах отображаются и в окне для ввода текста выводятся дополнительные символы соответствующей раскладки 

8) нажатие на клавиши Backspace, Enter физической клавиатуры подсвечивает соответствующие клавиши виртуальной клавиатуры, производит то же действие, которое происходит при кликах по клавишам Backspace и Enter мышкой (удаление символа и переход на новую строку) **_(нет подсветки)_**

Выполненные пункты:
1) при клике мышкой по клавишам с символами, эти символы отображаются в окне ввода текста. Есть клавиша пробел 

2) есть клавиша CapsLock, переводящая все буквы в верхний регистр. Активное и неактивное состояние клавиши отличаются визуально 

3) есть клавиша Backspace, удаляющая символы перед курсором. Есть клавиша Enter для перехода на новую строку 

4) клавиатуру можно скрыть и отобразить на экране 

5) для смены языка добавлена дополнительная клавиша en/ru, при клике по которой происходит переключение между русской и английской раскладкой клавиатуры 

6) символы нажатых алфавитно-цифровых клавиш физической клавиатуры выводятся в окне для ввода текста 

7) размер клавиш виртуальной клавиатуры и шрифта на них адаптируется под размер экрана. Минимальная ширина страницы, при которой проверяется корректность отображения и работы клавиатуры - 500рх 

8) размер шрифта на клавишах не меньше 14рх, достаточная контрастность шрифта и фона клавиш в активном и неактивном состоянии 

9) при переключении языка на других клавишах клавиатуры отображаются символы выбранного языка, при кликам по ним эти символы выводятся в окно для ввода текста
