### ISSUE TITLE
Cross-Check 'Shelter' - 'Fedarenchyk-16'

### ISSUE THREAD

**Issue by Fedarenchyk-16** [rolling-scopes-school/support#154]
1. https://rolling-scopes-school.github.io/fedarenchyk-16-JS2020Q3/shelter/pages/main/index.html
2.https://github.com/rolling-scopes-school/fedarenchyk-16-JS2020Q3/tree/shelter/shelter
3.https://github.com/rolling-scopes-school/tasks/blob/master/tasks/markups/level-2/shelter/shelter-DOM-ru.md
4.https://github.com/rolling-scopes-school/tasks/blob/master/tasks/markups/level-2/shelter/shelter-cross-check-ru.md
5.
<img width="778" alt="Снимок экрана 2020-11-18 в 18 58 48" src="https://user-images.githubusercontent.com/70834989/99554484-4a373300-29d0-11eb-9787-034e6eeed171.png">

6. Никак не 38. Самооценка - 69. Ссылка открывается и все работает. Люди пожелали остаться анонимными, либо игнорируют. Хочется получить реальные баллы за свой труд.
7. 38(((

**Comment by valerydluski** [comment]
Не хватает результата самооценки.

**Comment by Fedarenchyk-16** [comment]
> Не хватает результата самооценки.

Все, добавил.

**Comment by reagentJS** [comment]
### Оценка: 64 из 100

### 1. Открытие страниц на полностью развернутом окне браузера на десктопе
- Снято 2 балла за невыполнение требования ТЗ (страница main):
> У карточки питомца появляется тень при наведении. Причем наведение на любое место карточки питомца: картинку, имя, кнопку.
- Снято 2 балла за невыполнение требования ТЗ (страница pets):
> У карточки питомца появляется тень при наведении. Причем наведение на любое место карточки питомца: картинку, имя, кнопку.
- Снят 1 балл за то, что на странице pets при нажатии на логотип в бургер-меню нет перехода на страницу main
- Снято 2 балла за невыполнение требования ТЗ:
> при нажатии в каком-либо меню на "Help the shelter" или "Contacts" ничего не происходит, а сами элементы не интерактивные

**Итого: 23 из 30**

### 2. Adaptive
Замечаний нет.
**Итого: 30 из 30**

### 3. DOM & events

1. Main page

- Burger menu. Снято 2 балла за то, что при открытом бургере остаётся возможность скролла
- Slider. Не реализован слайдер (-10 баллов)
- Popup. Снято 5 баллов за невыполнение требований ТЗ:
> При нажатии на любое место карточки (блока) с описанием конкретного питомца появляется попап.
> При появлении попапа возможность скролла самой страницы пропадает.
> При наведении мышкой на затемненную область или кнопку с крестиком, т.е. при событии hover, кнопка получает эффект наведения

При ширине экрана 320px в popup текст в пунктах "Inoculations", "Diseases" выходит за пределы popup'a

Popup можно открыть только при нажатии на кнопку "Learn more", и то не всегда (есть проблемы из-за всплытия-погружения события). При этом в консоли валятся ошибки "Cannot read property 'addEventListener' of null"

2. Pets page

- Burger menu. Снято 2 балла за то, что при открытом бургере остаётся возможность скролла
- Popup. Снято 5 баллов за невыполнение требований ТЗ:
> При нажатии на любое место карточки (блока) с описанием конкретного питомца появляется попап.
> При появлении попапа возможность скролла самой страницы пропадает.
> При наведении мышкой на затемненную область или кнопку с крестиком, т.е. при событии hover, кнопка получает эффект наведения

При ширине экрана 320px в popup текст в пунктах "Inoculations", "Diseases" выходит за пределы popup'a

Popup можно открыть только при нажатии на кнопку "Learn more", и то не всегда (есть проблемы из-за всплытия-погружения события). При этом в консоли валятся ошибки "Cannot read property 'addEventListener' of null" и большое количество других ошибок

- Pagination. Снято 5 баллов за то, что стрелки, указывающие влево, не становятся активными при перелистывании направо. Числа, указывающие номер страницы, переключаются некорректно

**Итого: 11 из 40**

**Comment by valerydluski** [comment]
оценка выставлена в score
