### ISSUE TITLE
Cross-Check gem-puzzle - ZaimBeshich

### ISSUE THREAD

**Issue by ZaimBeshich** [rolling-scopes-school/support#155]
Deploy: https://rolling-scopes-school.github.io/zaimbeshich-JS2020Q3/gem-puzzle/

Repo: https://github.com/rolling-scopes-school/zaimbeshich-JS2020Q3/tree/gem-puzzle

Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md

Cross-Check form: https://rolling-scopes-school.github.io/checklist/

Чужих работ не проверял, тк не прикрепил свою ссылку.

Моя оценка: 75 балов
Не реализована  анимация, звук фишек, картинки вместо цифр, сохранение, размер поля,

**Comment by Viklysx** [comment]
Ваша оценка - 40 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 

2) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 

3) реализован выбор размера поля 

4) звуковое сопровождение передвижения фишек 

5) анимация перемещения пятнашек на поле 

6) вместо цифр на карточках используются картинки 

7) реализовано автоматическое, анимированное завершение игры 

Частично выполненные пункты:
1) вёрстка, дизайн, UI 
Отзыв: На экране 320px ширина игрового поля выходит за границы и появляется скролл.

Выполненные пункты:
1) cостояние игрового поля генерируется случайным образом 

2) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 

3) игру можно начать заново без перезагрузки страницы 

4) отображается время игры и количество ходов 

5) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 

Штрафы:
1) Ошибки в консоли, связанные с исполняемым кодом(ошибки типа favicon.ico: Failed to load resource: the server responded with a status of 404 не учитываются):

![image](https://user-images.githubusercontent.com/58310634/99864134-c5583f00-2bb2-11eb-8d82-8686eebb9dbe.png)

**Comment by Viklysx** [comment]
@valerydluski
