### ISSUE TITLE
Cross-Check 'gem-puzzle' - DenisOleksiuk

### ISSUE THREAD

**Issue by DenisOleksiuk** [rolling-scopes-school/support#156]
1. Deploy: https://rolling-scopes-school.github.io/denisoleksiuk-JS2020Q3/gem-puzzle/src/
2. Repo: https://github.com/rolling-scopes-school/denisoleksiuk-JS2020Q3/tree/gem-puzzle
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
4. Cross-Check form: https://rolling-scopes-school.github.io/checklist/
5. Чужих работ не проверял, так как моя ссылка не засабмителась (почему-то).
6. Оценил в 130 балов. Не сделал:
1) реализовано сохранение состояния игры и сохранение 10 лучших результатов с использованием LocalStorage: +10
2) автоматическое, анимированное завершение игры: +30
 170 max. score 170 - 10 - 30 = 130.

**Comment by valerydluski** [comment]
Есть коммиты после дедлайна
