### ISSUE TITLE
Cross-Check RSS Игра в пятнашки - IGrakov

### ISSUE THREAD

**Issue by IGrakov** [rolling-scopes-school/support#157]
Ссылка на деплой вашего проекта: https://rolling-scopes-school.github.io/igrakov-JS2020Q3/gem-puzzle/
Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/igrakov-JS2020Q3.git
Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
Ссылка на форму для проверки проекта (если такая есть): https://rolling-scopes-school.github.io/checklist/

Забыл засабмитить задание gem-puzzle в RS App до дэдлайна, при этом деплой в gh-pages сделан вовремя

Оценка самопроверки +90
Выполнены пункты:
- вёрстка, дизайн, UI
- cостояние игрового поля генерируется случайным образом
- при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки
- игру можно начать заново без перезагрузки страницы
- отображается время игры и количество ходов
- реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage
- реализован выбор размера поля
- звуковое сопровождение передвижения фишек
- когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов»

Не выполнены пункты:
- фишки можно перетягивать мышкой
- анимация перемещения пятнашек на поле
- вместо цифр на карточках используются картинки
- реализовано автоматическое, анимированное завершение игры

**Comment by Viklysx** [comment]
Ваша оценка - 85 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 

2) анимация перемещения пятнашек на поле 

3) вместо цифр на карточках используются картинки 

4) реализовано автоматическое, анимированное завершение игры 

Частично выполненные пункты:
1) вёрстка, дизайн, UI 
Отзыв: Игровое поле мелковато на маленьких экранах (проверяла с телефона - действительно не удобно попадать по фишкам). Кнопки с опциями можно было вынести как отдельное меню, а игровое поле за счет этого увеличить.

Выполненные пункты:
1) cостояние игрового поля генерируется случайным образом 

2) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 

3) игру можно начать заново без перезагрузки страницы 

4) отображается время игры и количество ходов 

5) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 

6) реализован выбор размера поля 

7) звуковое сопровождение передвижения фишек 

8) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов»
