### ISSUE TITLE
Cross-Check RSS Игра в пятнашки - AGoravskiy

### ISSUE THREAD

**Issue by AGoravskiy** [rolling-scopes-school/support#158]
Деплой: https://rolling-scopes-school.github.io/agoravskiy-JS2020Q3/gem-puzzle/dist/
Репозиторий: https://github.com/rolling-scopes-school/agoravskiy-JS2020Q3
Задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md

Забыл засабмитить задание RSS Игра в пятнашки в RS App до дэдлайна, деплой и PR сделан вовремя.

Самопроверка:

1) вёрстка, дизайн, UI: +10
2) состояние игрового поля генерируется случайным образом: +10
3) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки: +10
4) игру можно начать заново без перезагрузки страницы: +10
5) отображается время игры и количество ходов: +10
6) анимация перемещения пятнашек на поле: +10

Итого, результат самопроверки - 60 баллов

**Comment by ansivgit** [comment]
Ваша оценка - 58 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 
2) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 
Отзыв: Игра запоминает начальную раскладку и при загрузке возвращает не сохраненную, а начальную (как я понимаю). Результаты лучшие не показывает 
3) реализован выбор размера поля 
4) звуковое сопровождение передвижения фишек 
5) вместо цифр на карточках используются картинки 
6) реализовано автоматическое, анимированное завершение игры 

Частично выполненные пункты:
1) вёрстка, дизайн, UI 
Отзыв: Не соблюдено требование пустого body -2б
2) игру можно начать заново без перезагрузки страницы 
Отзыв: Игру можно начать заново, но после операций сохранения/восстановления получить можно только прежнюю раскладку, получить новую раскладку можно только при перезагрузке страницы. При этом не обнуляется время и количество ходов
3) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 
Отзыв: Не выводится время и кол-во ходов
Выполненные пункты:
1) cостояние игрового поля генерируется случайным образом 
Отзыв: После операций сохранения-загрузки игры генерится только при перезагрузке, однако, поскольку генерится, баллы не снижала
2) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 
3) отображается время игры и количество ходов 
4) анимация перемещения пятнашек на поле
