### ISSUE TITLE
Cross-Check RSS Игра в пятнашки - Tonia-SE

### ISSUE THREAD

**Issue by Tonia-SE** [rolling-scopes-school/support#159]
Ссылка на деплой проекта
https://rolling-scopes-school.github.io/tonia-se-JS2020Q3/gem-puzzle/

Ссылка на репозиторий с проектом на GitHub
https://github.com/rolling-scopes-school/tonia-se-JS2020Q3

Ссылка на задание
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md

Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты)
 
![screen cross-check](https://user-images.githubusercontent.com/64790742/99945913-8d095a00-2d86-11eb-86a2-44a57021db21.png)

Балл за cross-check в Score еще не отобразился

    
Оценка в результате самопроверки:
    Score: 170 / 170
    Basic scope +30
вёрстка, дизайн, UI: +10
состояние игрового поля генерируется случайным образом: +10
при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки: +10

    Advanced scope +60
игру можно начать заново без перезагрузки страницы: +10
отображается время игры и количество ходов: +10
фишки можно перетягивать мышкой: +10
реализовано сохранение состояния игры и сохранение 10 лучших результатов с использованием LocalStorage: +10
реализован выбор размера поля: +10
звуковое сопровождение передвижения фишек: +10

    Hacker scope +80
анимация перемещения пятнашек на поле: +10
когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов»: +10
вместо цифр используются картинки: +30
автоматическое, анимированное завершение игры: +30

    Балл за cross-check из вашего Score

**Comment by arumirinka** [comment]
Ваша оценка - 170 баллов 

Отзыв по пунктам ТЗ:
Выполненные пункты:
1) вёрстка, дизайн, UI 

2) cостояние игрового поля генерируется случайным образом 

3) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 

4) игру можно начать заново без перезагрузки страницы 

5) отображается время игры и количество ходов 

6) фишки можно перетягивать мышкой 

7) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 

8) реализован выбор размера поля 

9) звуковое сопровождение передвижения фишек 

10) анимация перемещения пятнашек на поле 

11) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 

12) вместо цифр на карточках используются картинки 

13) реализовано автоматическое, анимированное завершение игры 

Комментарии:
1. Нет возможности выбрать размер поля 5х5, 6х6, 7х7. Поскольку в ТЗ этого явно не указано, спорный момент - в пользу студента.
2. Было бы здорово неактивные кнопки как-то выделять внешне.
3. При нажатии "Autoplay" кнопка "End game" должна либо срабатывать корректно, либо становиться неактивной.
