### ISSUE TITLE
Cross-Check 'Gem puzzle' - 'jeben-hub'

### ISSUE THREAD

**Issue by jeben-hub** [rolling-scopes-school/support#160]
Деплой - https://rolling-scopes-school.github.io/jeben-hub-JS2020Q3/gem-puzzle/ 
Репозиторий - https://github.com/rolling-scopes-school/jeben-hub-JS2020Q3
Задание - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
Форма - https://rolling-scopes-school.github.io/checklist/
![image](https://user-images.githubusercontent.com/61472820/99955103-d2348880-2d94-11eb-94c1-3be01159261a.png)
![image](https://user-images.githubusercontent.com/61472820/99955128-dd87b400-2d94-11eb-8b51-28c9b042dd5f.png)
![image](https://user-images.githubusercontent.com/61472820/99955157-e7a9b280-2d94-11eb-845e-4c90db60d6ad.png)
Моя оценка - 115 баллов (самопроверка) 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 

2) анимация перемещения пятнашек на поле 

3) реализовано автоматическое, анимированное завершение игры 

Частично выполненные пункты:
1) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 
Отзыв: Выполнено сохранение текущей игры в localStorage. Т.е. если сделать хотя бы один ход и закрыть страницу, эта же игра продолжиться при открытии страницы(или перезагрузке)
Выполненные пункты:
1) вёрстка, дизайн, UI 

2) cостояние игрового поля генерируется случайным образом 

3) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 

4) игру можно начать заново без перезагрузки страницы 

5) отображается время игры и количество ходов 

6) реализован выбор размера поля 

7) звуковое сопровождение передвижения фишек 

8) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 

9) вместо цифр на карточках используются картинки 

![image](https://user-images.githubusercontent.com/61472820/99955412-5c7cec80-2d95-11eb-844b-d80d118b91c3.png)

**Comment by AV-Shell** [comment]
**Замечания.**
0) Не понятно для чего есть режим паузы, который останавливает время, но фишки всё равно можно перемещать.
1) После вывода сообщения об окончании игры, последняя фишка не доходит до своего места.  Игра загружается из локалсторэйдж с этого же хода. И можно выиграть игру в 1 клик, но собрать игру до конца получается нет возможности.
2) То, что в игре используются только картинки (а не 2 режима - картинки или цифры ), а так же то, что пустой квадрат сверху слева а не снизу справа, и привело к тому, что студенты не смогли проверить вашу работу, (сложно складывать только картинки да еще если пустой квадрат не там где надо). Пожалуйста более подробно изучайте то, что вам надо реализовать в задании. 
3) Нет проверки на сходимость комбинации.  С учетом этого пункта вместе с остальными проверить еще сложнее.
-5 баллов : (следует учитывать, что не все перемешивания случайным образом будут иметь решение)   
4) Нет возможности выключить звуковые сопровождения, звук есть всегда.  -5 баллов.

**Ваша оценка - 105 баллов** 

Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 

2) анимация перемещения пятнашек на поле 

3) реализовано автоматическое, анимированное завершение игры 

Частично выполненные пункты:
1) cостояние игрового поля генерируется случайным образом 
Отзыв: Нет проверки на сходимость комбинации.
2) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 
Отзыв: только сохранение игры
3) звуковое сопровождение передвижения фишек 
Отзыв: по Т.З.: есть возможность включать/выключать звуковое сопровождение передвижение фишек (звук на ваш выбор). Тут звук включен всегда.
Выполненные пункты:
1) вёрстка, дизайн, UI 

2) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 

3) игру можно начать заново без перезагрузки страницы 

4) отображается время игры и количество ходов 

5) реализован выбор размера поля 

6) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 

7) вместо цифр на карточках используются картинки
