### ISSUE TITLE
Cross-Check 'Gem puzzle' - Latvels

### ISSUE THREAD

**Issue by Latvels** [rolling-scopes-school/support#162]
Деплой -  https://rolling-scopes-school.github.io/latvels-JS2020Q3/gem-puzzle/
Репозиторий - https://github.com/rolling-scopes-school/latvels-JS2020Q3/tree/gem-puzzle
Задание - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
https://rolling-scopes-school.github.io/checklist/
Самооценка 80.
Балл за cross-check в Score:
![image](https://user-images.githubusercontent.com/67653783/99973680-13d32c80-2db1-11eb-9b4c-927a2827fa52.png)

Оценки проверяющих:
1 студент
![image](https://user-images.githubusercontent.com/67653783/99973157-82fc5100-2db0-11eb-99e2-913fa5bf1435.png)
2 студент
![image](https://user-images.githubusercontent.com/67653783/99973221-98717b00-2db0-11eb-9d10-9a433f8a42e7.png)
3 студент
![image](https://user-images.githubusercontent.com/67653783/99973271-a3c4a680-2db0-11eb-929d-76080dbcde20.png)

Прошу:
Если есть возможность проверить работу, так как её проверили только 3 студента из 4х и я не согласен с оценкой второго студента. Если бы проверили все 4 студента, данный issues не был бы создан.

**Comment by Viklysx** [comment]
Средняя оценка отличается от самооценки менее, чем на 15%, в таком случае апелляция не рассматривается.

**Comment by Latvels** [comment]
Понял.
