### ISSUE TITLE
Cross-Check 'Gem-puzzle' - Katkopikat

### ISSUE THREAD

**Issue by katkopikat** [rolling-scopes-school/support#163]
[Деплой] https://rolling-scopes-school.github.io/katkopikat-JS2020Q3/gem-puzzle/
[Репо] https://github.com/rolling-scopes-school/katkopikat-JS2020Q3/tree/gem-puzzle/gem-puzzle
[Таск] https://github.com/rolling-scopes-school/tasks/blob/master/tasks/gem-pazzle/codejam-the-gem-puzzle.md
[Форма проверки] https://rolling-scopes-school.github.io/checklist/

Скриншот с оценками за cross-check:
![image](https://user-images.githubusercontent.com/69801699/100005088-7b9d6d80-2dd9-11eb-9179-aadd201687c3.png)
![image](https://user-images.githubusercontent.com/69801699/100005122-86580280-2dd9-11eb-8f3b-3b4a34d348e2.png)
Балл за cross-check в Score: 105

Самопроверка: 130.
СДЕЛАНО:
[ + ] состояние игрового поля генерируется случайным образом: +10
[ + ] при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки: +10
[ + ] игру можно начать заново без перезагрузки страницы: +10
[ + ] отображается время игры и количество ходов: +10
[ + ] реализован выбор размера поля: +10
[ + ] звуковое сопровождение передвижения фишек: +10
[ + ] анимация перемещения пятнашек на поле: +10
[ + ] когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов»: +10
[ + ] вместо цифр используются картинки: +30

ЧАСТИЧНО:
[+-] вёрстка, дизайн, UI: +5 (не доделала меню по изначальной задумке, поэтому есть большие проблемы с удобством и из-за него сейчас много багов) +5
[ +- ] автоматическое, анимированное завершение игры: +15
У меня собирается поле с любым количеством фишек. Поле изначально генерируется не рандомной расстановкой фишек, а все фишки стоят в собранном порядке, а потом совершается автоматическое рандомное количество шагов (для разного размера поля диапазон этих ходов разный). Это решило проблему того, что некоторые комбинации случайного перемешивания не решаемы, а во-вторых, я могу записать историю перемешивания фишек и откатить ее в изначальное положение. В итоге, к этой истории я пушу все ходы пользователя, а если нажать "решить" то все явные дубликаты ходов туда-сюда удаляются (это сокращает кол-во ходов где-то в 2 раза), а потом раскручивает в обратную сторону. В итоге каждое поле сбирается, НО! Из-за того, что смена фишек происходит с помощью flex: order, откат происходит с диким мельтешением и плавной анимации попросту нет (order - это в принципе не анимируемое свойство), т.к часто во время смены order у пустышки и фишки, весь ряд на секунду тоже может сменить order. Я пыталась это пофиксить асинхронном внутри цикла, но добиться своего не хватило времени. Я бы поставила 15 баллов за логику и то, что любое поле всё же собирается (т.е. половина условия выполнена, а условие с анимацией - нет (хотя я понимаю, что анимацию мы делаем именно для пользователя)). Но я в свою очередь поставила человеку 15 баллов при том, что поле у него не собирается полностью, но видно, что логика сборки верная и что при наличии времени человек бы это доделал. Но это на ваше усмотрение.

НЕ ВЫПОЛНЕНО:
[ - ] фишки можно перетягивать мышкой: +0 (не успела).
[ - ] реализовано сохранение состояния игры и сохранение 10 лучших результатов с использованием LocalStorage: +0
( игра сохраняется в LocalStorage, подгрузить историю получилось, но кликабельность элементов почему-то нарушена (из 4 кв, на которые мы можем нажать, кликабельтными почему-то становились только 3, пришлось закомментить этот код, чтоб разобраться с ним в будущем, при этом случайно закомментила кусок, нужный для работы сохранения 10 результатов. Всё работало, но я последним коммитом, к сожалению, "сломала".)

P.S. Прошу прощения за лонгстори в комментариях. Спасибо большое за проверку!

**Comment by Viklysx** [comment]
Твоя оценка - 130 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фишки можно перетягивать мышкой 

2) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 

Частично выполненные пункты:
1) вёрстка, дизайн, UI 
Отзыв: Красивый, приятный дизайн, но есть проблема с отображением на маленьких экранах. Ширина игрового поля всегда фиксированная - 480px, а значит, на экранах с меньшей шириной поле не помещается и появляется горизонтальный скролл.
2) реализовано автоматическое, анимированное завершение игры 
Отзыв: Да, очень быстро, уследить сложно.

Выполненные пункты:
1) cостояние игрового поля генерируется случайным образом 

2) при клике по фишке, стоящей рядом с пустой клеткой, фишка перемещается на место пустой клетки 

3) игру можно начать заново без перезагрузки страницы 

4) отображается время игры и количество ходов 

5) реализован выбор размера поля 

6) звуковое сопровождение передвижения фишек 

7) анимация перемещения пятнашек на поле 

8) когда игра закончилась, выводится сообщение «Ура! Вы решили головоломку за ##:## и N ходов» 

9) вместо цифр на карточках используются картинки 

_Дополнительно:_ нужно подправить счетчик времени. Время не обнуляется при новой игре, а если несколько раз начать новую игру, то со временем происходит что-то странное.
