### ISSUE TITLE
Cross-Check - 'Node.js in Cloud AWS' - 'dartwlad'

### ISSUE THREAD

**Issue by dartwlad** [rolling-scopes-school/support#165]
Оценка за задание TASK 7 не проставлена. Мою работу  проверили только 3 участника.

**Comment by dartwlad** [comment]
Сможет кто-то помочь с этим?
буду благодарен за любой фидбек по этой ситуации

**Comment by dzmitry-varabei** [comment]
@dartwlad извини, вовремя не заметили. Но сертификат ты и так смог получить :)
