### ISSUE TITLE
 Cross-Check 'english-for-kids' - 'Zoobbi'.

### ISSUE THREAD

**Issue by Zoobbi** [rolling-scopes-school/support#169]
1. https://rolling-scopes-school.github.io/zoobbi-JS2020Q3/english-for-kids/
2. https://github.com/rolling-scopes-school/zoobbi-JS2020Q3/tree/english-for-kids
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rslang/english-for-kids.md
4. https://cross-check-english-for-kids.netlify.app/
5. Cross-Check не проводился
6. 170 т.к. все пункты техзадания выполнены
7. Оценка в score отсутствует

Здравствуйте, у меня случилась такая ситуация. Если без подробностей,   я делал таск с английским на протяжении всего этого, времени, с прошлой недели, всю семью подкосил ковид. В итоге продуктивность резко свалилась. Но всё же я вчера прямо к ночи доделал и лёг спать, а сейчас я понял, что забыл за этим всем засабмитить. Я полностью понимаю, что это мой косяк и как бы сам виноват, но мне прям до слёз обидно по 10 часов над этим всем сидеть и так получилось. Я прям душу вложил в этот проект. Эти курсы для меня как спасение от чего ещё больнее. Возможно ли мне как-то помочь? 

И гитхаб доказательство, что коммиты были вчера и я не вышел за сроки. Помогите пожалуйста!
![image](https://user-images.githubusercontent.com/26322565/101505543-86353680-3985-11eb-96e5-64f0ade1aea6.png)

заранее спасибо. 
P.S. сейчас  к сожалению не могу подтвердить документально, так как справки в поликлинике и выдадут их только по окончанию самоизоляции(минимум 14 декабря)

**Comment by reagentJS** [comment]
Итого: 168 из 170.
Снято 2 балла за то, что если с главной страницы перейти на страницу категории, в выезжающем меню не отображается текущая вкладка.
PS: тоггл топовый!
