### ISSUE TITLE
Cross-Check Singolo - Ambermist

### ISSUE THREAD

**Issue by Ambermist** [rolling-scopes-school/support#17]
https://ambermist.github.io/singolo/index.html - деплой проекта 
https://github.com/Ambermist/Ambermist.github.io - в папке singolo этого репозитория конечная задеплоенная версия index.html
https://github.com/Ambermist/singolo - репозиторий с частями singolo
моя оценка  - примерно 80 - 90 из-за неполных совпадений текста, но явно не - 30 за
отсутствующие части синголо, которые есть в репозитории singolo, все коммиты вовремя

**Comment by Sannnao** [comment]
- Посмотрел коммиты 8 марта (дедлайн) - части синголо есть, но конечный результат сильно недоработан.
![image](https://user-images.githubusercontent.com/44711578/76678196-de056380-65e6-11ea-8fdd-11e4738ac7e8.png)
И так в каждом последующем блоке

**Comment by Ambermist** [comment]
а конечный результат index, который на https://github.com/Ambermist/Ambermist.github.io лежит, не будет считаться?  я его забыла запушить в репозиторий singolo  до дедлайна, поэтому части и индекс в разных местах немного. И кстати исправления 9 уже не будут учитываться вообще? ведь было разрешено еще до среды кажется отправлять работы на проверку

**Comment by Sannnao** [comment]
About Us
``В поле, где находится имя, задаем очень большой текст (например, 'rajeshramayankoothrappali anastrophysicistinthephysicsdepartmentatcaltech'), чтобы он выходил за пределы блока, и не было переноса на следующую строку. Желательно, чтобы текст заканчивался тремя точками. Если текст выходит за размеры или переносится на другую строку, ставим -3.``
![image](https://user-images.githubusercontent.com/44711578/76706630-e601f800-66f9-11ea-9e7e-e273ff8113b6.png)

-10 за дедлайн, -3 за блок About Us

-13

**Comment by Ambermist** [comment]
но не -30 же, как поставил 1 человек из 4?
