### ISSUE TITLE
Cross-Check 'rs-css' - Flash9600

### ISSUE THREAD

**Issue by Flash9600** [rolling-scopes-school/support#170]
1) https://rolling-scopes-school.github.io/flash9600-JS2020Q3/rs-css/dist/index.html
2) https://github.com/rolling-scopes-school/flash9600-JS2020Q3/tree/rs-css
3) https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rs-css.md
4) https://rs-scc-cross-check.netlify.app/
5) 
![image](https://user-images.githubusercontent.com/70837972/102042585-a3d22800-3deb-11eb-8f82-106f134a5c28.png)
6) 170/170 все требования задания выполнены.
7)140 баллов в Score.
Мою работу проверили трое человек, двое оценили её на 170, ну а третий на 80, и не оставил своих контактов. Пожалуйста, помогите исправить оценку.

**Comment by natein** [comment]
Ваша оценка - 159 баллов.

Недочеты по ТЗ:

1. Вертикальная линейка прокрутки при любом масштабе и контент футера прижат к самому низу без отступов  - 1 балл
2. Отсутствует подсветка СSS кода -5 баллов
3. При наведении курсора на элемент в блоке с вёрсткой не подсвечивается соответствующий ему фрагмент в блоке с кодом -5 баллов
