### ISSUE TITLE
Cross-Check 'english-for-kids' - 'vladislavgribkov'.

### ISSUE THREAD

**Issue by vladislavgribkov** [rolling-scopes-school/support#171]
1. https://rolling-scopes-school.github.io/vladislavgribkov-JS2020Q3/english-for-kids/
2. https://github.com/rolling-scopes-school/vladislavgribkov-JS2020Q3/tree/english-for-kids
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rslang/english-for-kids.md
4. https://cross-check-english-for-kids.netlify.app/
5. 
- https://priscree.ru/img/e896dd4969d0c9.jpg
- https://priscree.ru/img/d9de6abafc464b.jpg
- https://priscree.ru/img/9f8c3596a0976a.jpg
6. На мой взгляд - 170, так как все условия задания выполнены. 
7. 115 баллов.
Здравствуйте, у меня случилась такая ситуация. Все проверяющие поставили мне максимальную оценку, а один поставил всего 5 баллов. Хотя все условия задания выполнены. Человек утверждает, что приложение не работает должным образом, хотя я проверил на разных устройствах и с разных браузеров работоспособность приложения.

**Comment by arumirinka** [comment]
Ваша оценка - 160 баллов.

Недочеты по ТЗ:

1. Отсутствует название на странице категории. -1
2. "При клике по оборотной стороне карточки ничего не происходит, произношение слова не звучит" - не выполнено. -2
3. "Все надписи, если это возможно, необходимо продублировать картинками или иконками" - не выполнено. -2
4. В футере отсутствует год создания приложения. -1
5. "Для каждой игры рандомные слова генерируются по-новой" - четырежды запускаю игру, четырежды предлагает начать с одного и того же слова. -2
6. Строка с сердечками скрывается под футером, на моем (стандартном) мониторе видна только при уменьшении размеров окна/переключении в адаптивный режим. -2

Итого: 170 - 10 = 160 баллов.

Комментарии:
1. Было бы здорово, если бы картинки при переключении train/play масштабировались с сохранением пропорций, а не просто растягивались по вертикали.
2. При нажатии на Start Game контент прижимается к верхнему краю экрана.
3. Строка с сердечками лучше бы смотрелась сверху, а не у самого футера - там ее сложно заметить.
4. Адаптивность реализована несколько странно. Карточки не сохраняют свой размер при изменении ширины экрана, вместо этого они растягиваются/сжимаются по горизонтали. При ширине 1249 отображаются по 2 карточки в ряд, при 1272 - 4 карточки. На мой взгляд, такого не должно быть.
5. При некоторых размерах экрана верхняя "панель управления" исчезает, уходя за верхний край экрана. Пример: ширина окна от 1253 до 1268, высота 710 пикселей.
6. На странице статистики при ширине 320 появляется блок пустого пространства под таблицей высотой примерно в саму таблицу.
7. Спинер при загрузке крутится в непривычную сторону :)
