### ISSUE TITLE
Cross-Check 'english-for-kids' - 'frenki1231'.

### ISSUE THREAD

**Issue by frenki1231** [rolling-scopes-school/support#172]
1) https://rolling-scopes-school.github.io/frenki1231-JS2020Q3/english-for-kids/#
2) https://github.com/rolling-scopes-school/frenki1231-JS2020Q3/tree/english-for-kids
3) https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rslang/english-for-kids.md
4) https://cross-check-english-for-kids.netlify.app/
5) 
![image](https://user-images.githubusercontent.com/70661525/102053320-9a02f180-3df8-11eb-8dbd-56e781e6ea32.png)
![image](https://user-images.githubusercontent.com/70661525/102053356-a8e9a400-3df8-11eb-9fd9-4a69470ca878.png)

6)Само проверка - 170, все условия задания выполнены в полной мере.
7) Score: 57.
Добрый день возникла печальная ситуация, при сабмите ссылки я не заметил, что отсутствует https:, в результате чего ссылка не открывается если нажать на нее в app, однако если ее просто скопировать, то все открывается верно. К сожалению, со мной связался только один студент, для уточнения ссылки, еще два студента не оставили контактов, а четвертый проверил только в воскресенье, а у меня не было возможности связаться с ним, чтобы предоставить ссылку верно.

**Comment by ai297** [comment]
### Ваша оценка - 170 баллов 
Все пункты ТЗ выполнены полностью.


**Комментарии:** 
1. _Было бы неплохо добавить какой-то ховер-эффект при наведении на заголовки столбцов в статистике, что бы показать что это интерактивные элементы. Иначе вообще не очевидно, что реализована сортировка._
2. _При переходе со страницы статистики на страницу repeat difficult в активном игровом режиме - куда-то пропадают стили кнопки Play.. Сначала показалось что её просто нет._

В целом хорошая работа, весь функционал действительно реализован. Разве что роутинга не хватает :-)
