### ISSUE TITLE
Cross-Check 'RS-CSS' - 'natein'.

### ISSUE THREAD

**Issue by natein** [rolling-scopes-school/support#173]
**Ссылка на деплой вашего проекта:** https://natein-rs-css.netlify.app/
**Ссылка на репозиторий с проектом на GitHub:** https://github.com/rolling-scopes-school/natein-JS2020Q3/tree/rs-css-source
**Ссылка на задание:** https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rs-css.md
**Ссылка на форму для проверки проекта:** https://rs-scc-cross-check.netlify.app/

**Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты):**
![CropperCapture 2](https://user-images.githubusercontent.com/12632270/102062703-c3724c00-3dfd-11eb-89df-b8401af8fcc9.jpg)
![CropperCapture 3](https://user-images.githubusercontent.com/12632270/102062734-ca995a00-3dfd-11eb-91ed-3fb03c3a1d75.jpg)
![CropperCapture 4](https://user-images.githubusercontent.com/12632270/102062754-d08f3b00-3dfd-11eb-8269-7c161f550e5f.jpg)

**Оценка в результате самопроверки, с ее аргументацией**: 135 баллов

**Невыполненные пункты:**

- подсветка html и css-кода в окне для ввода кода пользователем и блоке с кодом вёрстки
- при наведении курсора на строку в блоке с кодом, отвечающий этой строке элемент в блоке с примером вёрстки подсвечивается. Рядом с элементом отображается его html-код
- при наведении курсора на элемент в блоке с вёрсткой, подсвечивается соответствующий ему фрагмент в блоке с кодом. Рядом с элементом отображается его html-код

**Частично выполненные пункты:**

- текущий уровень подсвечен. При перезагрузке приложение открывается на этом же уровне

Из-за ошибки в реализации роутинга текущий уровень не всегда подсвечивается правильно.

**Балл за cross-check из вашего Score:** 110 баллов

**Comment by AV-Shell** [comment]
**Самооценка верна. 135 баллов** по пунктам тз.
Когда использована подсказка, то нельзя введя ответ и нажав enter перейти на следующий уровень.  Вначале создается впечатление, что игра вообще сломалась, не принимает ответы, при перезагрузке тоже. Но при переходе на другой уровень из списка всё работает. Я так понимаю это задумка автора. Взял подсказку - только через ресет всего сбросить.
Так же  можно было сделать чтобы нельзя было менять уровни пока выводится подсказка.  Или при смене уровня прекращать вывод подсказки. А так дописывает на новом уровне.
Нет обработки если введена полная чушь.  выкидывает ошибку.  Проще всего было обернуть querySelectorAll в блок try catch. 
Пункты  в тз про дизайн очень спорные, так что я всем засчитывал, у кого дизайн отличался от оригинала.
