### ISSUE TITLE
Cross-Check 'English-for-kids' - cptShell

### ISSUE THREAD

**Issue by cptShell** [rolling-scopes-school/support#176]
**Ссылка на деплой проекта**: https://rolling-scopes-school.github.io/cptshell-JS2020Q3/english-for-kids/pages/category/cathegory.html
**Ссылка на репо с проектом**: https://github.com/rolling-scopes-school/cptshell-JS2020Q3/tree/english-for-kids
**Ссылка на задание**: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rslang/english-for-kids.md

**А теперь мякотка**:
![d](https://user-images.githubusercontent.com/67701905/102212977-17a52b00-3ee7-11eb-8f88-2f008e8ff996.PNG)
Черт с тем проверяющим, который 5 баллов забрал за несуществующее требование, но вот тип, который поленился нажать на самую большую кнопку в центре с верху и ляпнул 90 - уже перебор.

**Самопроверка**:
Серьезно, я не знаю, что комментировать тут. Единственное, за что можно было бы в теории снять баллы, так это пункт с количеством категорий, но это блин делает ментор, если верить тз.
Весь возможный функционал у меня реализован, это подтверждают 2 из 3 оценок.
Рискну поставить себе 170

**Исходная оценка**: 142

_я пойму, если получится после проверки не 170, что может быть в итоге чуть меньше, чем 15%, но даже 160 баллов сильно больше, чем 142. Заранее спасибо_

**Comment by ai297** [comment]
Проверю

**Comment by ai297** [comment]
### Ваша оценка - 155 баллов 
Отзыв по пунктам ТЗ:

**Частично выполненные пункты:**

1) Вёрстка, дизайн, UI страницы категории 
_feedback: На странице категории отсутствует переключатель режима Train / Play. Вообще очень спорное и неочевидное решение. Кнопка не только отсутствует на странице категории, но и на main page она никак не выделена и не подписана. Нашёл совершенно случайно, тыкая на всё подряд. Не удивлюсь, если ваш проверяющий просто не нашёл эту кнопку. Снижаю 5 баллов за UI, но если честно снизил бы 10._
2) возле каждого слова указывается статистика - сколько раз по карточки с данным словом кликали в режиме тренировки, сколько раз данное слово угадывали в режиме игры, сколько ошибок при этом допустили, процент ошибок по каждому слову, или процент правильных ответов по каждому слову. Оба варианта подсчёта являются равноценными и правильными. После перезагрузки приложения статистика сохраняется. 
_feedback: Процент ошибок считается неправильно, то есть наоборот. Кейс - карточка верно угадана 2 раза и неверно - 1 раз. то есть имеем 1 ошибку из 3х попыток. % ошибок равен 1 / 3 то есть 33%. В приложении же выводится показатель в 67% - это процент правильных ответов, но не процент ошибок. По заданию допустимо оба варианта, просто некорректное название колонки. Но баллы снижаю, потому что данная ошибка нарушает логику работы приложения - слово с большим количеством ошибок не попадает в режим Train Dificult, в отличии от слова с меньшим количеством ошибок. (например слово с 4 правильными ответами и 1 ошибкой попадает в режим тренировки, а слово с 1 правильным ответом и 2 ошибками - нет, если таких слов больше 8)_
3) на странице со статистикой размещены кнопки Repeat difficult words и Reset. Кнопка Reset обнуляет статистику. При клике по кнопке Repeat difficult words открывается страница изучения слов с наибольшим процентом ошибок аналогичная странице категории. На странице Repeat difficult words может размещаться от нуля до восьми слов, в зависимости от того сколько слов угадывалось в режиме игры и при их угадывании были допущены ошибки. После нажатия на кнопку Reset количество слов на странице Repeat difficult words равно нулю 
_feedback: На странице Repeat difficult нет режима игры_


**Выполненные пункты:**
1) Вёрстка, дизайн, UI главной страницы приложения 

2) Вёрстка, дизайн, UI выезжающего меню 1) ссылки в меню рабочие и ведут на страницы с категориями слов 2) ссылка на текущую страницу внешне отличается от остальных 3) выезжающее меню присутствует на всех страницах приложения 
4) плавная анимация, меню закрывается как кликом по крестику, так и кликом на любом элементе приложения (кроме самого меню), и кликом по ссылке в самом меню 

3) при клике по карточке звучит произношение слова на английском языке 

4) на каждой карточке есть кнопка, при клике по которой карточка поворачивается, на обратной стороне указан перевод слова. Когда курсор мыши перемещается за границы карточки, она автоматически поворачивается на лицевую сторону 

5) кликом по переключителю Train/Play включается режим игры. В режиме игры указанные выше возможности режима тренировки отключаются, кнопка, при клике по которой карточка переворачивалась, и текст на карточке скрываются. Появляется кнопка Start game. На карточке остаётся только изображение, которое занимает всю её площадь (если это не противоречит вашему дизайну) 

6) после клика по кнопке Start game звучит английское произношение рандомного слова из тех, что находятся на странице. Для каждой страницы и для каждой игры рандомные слова генерируются по-новой 

7) после первого клика по кнопке Start game надпись на ней меняется на иконку Repeat, меняется внешний вид кнопки. При клике по кнопке Repeat произношение слова звучит ещё раз 

8) если пользователь кликнул по активной карточке с неправильным ответом, раздаётся звуковой сигнал error 

9) если пользователь кликнул по активной карточке с правильным ответом, раздаётся звуковой сигнал correct и после него звучит произношение рандомного слова из тех, которые ещё не звучали 

10) карточка с угаданным словом становится неактивной, при этом изменяется её внешний вид. Клики по неактивной карточке звуковыми эффектами не сопровождаются, на счёт игры не влияют 

11) после начала игры каждый клик по активной карточке является правильным или неправильным ответом. Эти ответы отображаются в виде звёздочек (или других символов) разного цвета в шкале с рейтингом, которая появляется в режиме игры. Если звёздочек слишком много и шкала заполнена ими полностью, предыдущие звёздочки скрываются, а новые продолжают добавляться 

12) когда угаданы все слова в категории 1) если все слова угаданы правильно, звучит сигнал success, карточки со словами скрываются, на странице отображается радостный смайлик (или другая картинка) 2) если при угадывании слов были ошибки, звучит сигнал failure, карточки со словами скрываются, на странице отображается грустный смайлик (или другая картинка) и количество допущенных ошибок 3) приложение автоматически перенаправляет на главную страницу со списком категорий 
feedback: Игровой режим работает. Но только после полной очистки local storage. Лучше иметь ввиду такие нюансы, т.к. деплой делается не в личном аккаунте. До очистки приложение полностью ломалось, консоль заливалась потоком ошибок. Работа приложения не должна нарушаться из-за некорректных данных в local storage. (Это просто комментарий / рекомендация)
13) страница со статистикой содержит перечень всех категорий, всех слов в каждой категории, перевод каждого слова. На мобильных разрешенияк в таблице со статистикой может присутствовать полоса прокрутки 

14) есть возможность сортировки данных по алфавиту, для числовых значений - по их величине. Сортировка может происходить в прямом и обратном порядке и должна охватывать весь диапазон данных
