### ISSUE TITLE
Cross-Check 'Covid 19 DashBoard'

### ISSUE THREAD

**Issue by andrew-nechai** [rolling-scopes-school/support#178]
Деплой - https://rolling-scopes-school.github.io/andrew-nechai-JS2020Q3/covid19/
Git проект - https://github.com/rolling-scopes-school/andrew-nechai-JS2020Q3/tree/covid-19
Задание - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/covid-dashboard.md
![image](https://user-images.githubusercontent.com/44904118/103178312-cc016280-4892-11eb-803c-a24df9b45e95.png)
Виртуальная клавиатура присутствует, данные о конкретной стране тоже показываются(нужно просто выбрать страну из списка).  Про упомянутый бонусы не понятно. Ожидаемый результат - 240 (конкретно для этого человека, хотя в остальных случаях тоже придрались ни к чему)

**Comment by valerydluski** [comment]
Оформи правильно.
