### ISSUE TITLE
Cross-Check 'Covid 19 DashBoard' - 'Soullnik'

### ISSUE THREAD

**Issue by Soullnik** [rolling-scopes-school/support#179]
**Ссылка на деплой вашего проекта:**  https://rolling-scopes-school.github.io/soullnik-JS2020Q3/covid-dashboard/build/
**Ссылка на репозиторий с проектом на GitHub:** https://github.com/rolling-scopes-school/soullnik-JS2020Q3/tree/covid-dashboard/covid-dashboard
**Ссылка на задание:** https://github.com/rolling-scopes-school/tasks/blob/master/tasks/covid-dashboard.md
**Ссылка на форму для проверки проекта:** https://covid-dashboard-cross-check.netlify.app/

**Оценка в результате самопроверки, с ее аргументацией:** 115 баллов

**Dыполненые пункты:**
* внешний вид приложения соответствует образцу или является его улучшенной версией. Каждый блок информации (таблица, список, карта, график) можно развернуть в полный экран + 10
* для стандартных разрешений экрана монитора до 1024×768 включительно приложение полностью помещается в экран. При меньшем разрешении экрана допускается наличие вертикальной полосы прокрутки +10
* в таблице корректно отображаются указанные в описании задания данные за весь период пандемии + 10
* данные можно просматривать за последний день (последнюю возвращаемую API дату) +10 
* данные можно просматривать для выбранной пользователем страны - +10
* данные можно просматривать из расчёта на 100 тыс. населения - +10
* есть список стран для каждой из которых по умолчанию отображается общее количество случаев заболевания за весь период пандемии +10
* есть возможность выбрать для отображения в списке любой другой показатель из тех, которые выводятся в таблице. Список стран сортируется по убыванию по выбранному показателю +10 
* возле каждой страны выводится изображение её флага +10
* на карте условными обозначениями: цветом или размером маркера указывается интенсивность распространения болезни +10
* карта интерактивная, есть возможность пертескивать карту, уменьшать и увеличивать масштаб +10

**Не выполненые пункты:**
* работает поиск по названию страны
* для ввода поискового запроса может использоваться виртуальная клавиатура
* есть возможность выбрать для отображения интенсивности распространения болезни другой показатель из тех, что могут отображаться в таблице 
* у карты есть легенда, для оформления карты используется кастомный дизайн
* есть график, который строится по общему количеству случаев заболевания 
* есть возможность просмотреть график по любому из выбранных показателей из тех, которые выводятся в таблице
* при наведении курсора на график появляется всплывающая подсказка с датой, соответствующей этой точке графика и данными по этой дате
* есть возможность просмотреть график как для мира в целом, так и для любой выбранной страны
* продуман и реализован не предусмотренный заданием дополнительный функционал 
* вёрстка адаптивная. Минимальная ширина страницы, при которой проверяется корректность отображения приложения, 500рх 

**Частично выполненные пункты:**
* при наведении курсора на страну на карте появляется всплывающая подсказка - название страны и показатель, который в данный момент используется для определения интенсивности распространения болезни +5

**Балл за cross-check из вашего Score:** 0

**Comment by valerydluski** [comment]
Оформи правильно.

**Comment by Soullnik** [comment]
> Оформи правильно.

Сделал

**Comment by valerydluski** [comment]
нет

**Comment by arumirinka** [comment]
Ваша оценка - 95 баллов

Отзыв по пунктам ТЗ:

Не выполненные/не засчитанные пункты:
1) вёрстка адаптивная. Минимальная ширина страницы, при которой проверяется корректность отображения приложения, 500рх 
2) данные можно просматривать из расчёта на 100 тыс. населения 
3) работает поиск по названию страны  
4) для ввода поискового запроса может использоваться виртуальная клавиатура 
5) есть возможность выбрать для отображения интенсивности распространения болезни другой показатель из тех, что могут отображаться в таблице  
6) у карты есть легенда, для оформления карты используется кастомный дизайн 
7) есть график, который строится по общему количеству случаев заболевания 
8) есть возможность просмотреть график по любому из выбранных показателей из тех, которые выводятся в таблице 
9) при наведении курсора на график появляется всплывающая подсказка с датой, соответствующей этой точке графика и данными по этой дате 
10) есть возможность просмотреть график как для мира в целом, так и для любой выбранной страны 
11) оригинальный интересный качественный дизайн приложения 
12) продуман и реализован не предусмотренный заданием дополнительный функционал 

Частично выполненные пункты:
1) в таблице корректно отображаются указанные в описании задания данные за весь период пандемии 
_feedback_: Отсутствуют данные по количеству случаев (cases). -3 балла
2) есть возможность выбрать для отображения в списке любой другой показатель из тех, которые выводятся в таблице. Список стран сортируется по убыванию по выбранному показателю 
_feedback_: Отсутствует возможность просмотреть данные из расчета на 100 тыс. населения. -3 балла
3) при наведении курсора на страну на карте появляется всплывающая подсказка - название страны и показатель, который в данный момент используется для определения интенсивности распространения болезни 
_feedback_: Подсказка появляется при клике, из требуемого в задании присутствует только название страны. -7 баллов

Выполненные пункты:
1) внешний вид приложения соответствует образцу или является его улучшенной версией. Каждый блок информации (таблица, список, карта, график) можно развернуть в полный экран 
2) для стандартных разрешений экрана монитора до 1024×768 включительно приложение полностью помещается в экран. При меньшем разрешении экрана допускается наличие вертикальной полосы прокрутки 
_feedback_: Шрифт слишком мелкий, плохо читается. -2 балла
3) данные можно просматривать за последний день (последнюю возвращаемую API дату) 
4) данные можно просматривать для выбранной пользователем страны 
5) есть список стран для каждой из которых по умолчанию отображается общее количество случаев заболевания за весь период пандемии 
6) возле каждой страны выводится изображение её флага 
7) на карте условными обозначениями: цветом или размером маркера указывается интенсивность распространения болезни 
8) карта интерактивная, есть возможность перетаскивать карту, уменьшать и увеличивать масштаб
