### ISSUE TITLE
Cross-Check Singolo - scientist26

### ISSUE THREAD

**Issue by scientist26** [rolling-scopes-school/support#18]
https://scientist26.github.io/singolo/ - ссылка на деплой
https://github.com/scientist26/singolo - ссылка на репозиторий с проектом
Оценка в результате самопроверки: около 90 баллов
 ```
   - 3 Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify в секции Services
   - 3  В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт
   - 3 При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку
   - 3 Визульные отличия элементов составляют более двух пикселей (2px) (нивигация header уплыла в Google Chrome) - но в Mozilla все ок(Pixel Perfect ставил в Mozilla и таски проверял там, т.к. Chrome никак не хотел работать)
```

> 72 балла 
> 
> Отзыв по пунктам ТЗ:
> 
> 1. В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020: минус -10 баллов  - **файлов с таким названием нет, но коммиты "feat: add main" и "init: start singolo task, add header" содержат первую часть и сделаны вовремя.**

> 
> 2. Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify в секции Services: минус -3 балла  - **согласен, текст в нескольких блоках вылетает**
> 
> 3. Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify в секции About: минус -3 балла  - **в изначальном задании не было ничего про text-align: justify, я использовал letter-spacing и текст в итоге равномерно распределен**
> 
> 4. Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify в секции Get a Quote: минус -3 балла  - **тоже что и п3**
> 
> 5. В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла - **согласен**
> 
> 6. При добавлении в сетку с изображениями элементов за 12-м (проверяя, добавляем их сами) следющие за 12-м отображаются на странице - не реализовано ограничение видимых двенадцатью показанными в макете: минус -3 балла - **реализовано ограничение видимых, все работает**
> 
> 7. При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку -3 балла - **согласен**

**Comment by Sannnao** [comment]
-6. Отличная работа!
