### ISSUE TITLE
Cross-Check. RS Clone. gitName: ruslanchampion

### ISSUE THREAD

**Issue by ruslanchampion** [rolling-scopes-school/support#183]
https://ruslanchampion.github.io/excel/dist/
https://github.com/ruslanchampion/excel/pull/12
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rsclone/rsclone.md

![оценки](https://user-images.githubusercontent.com/67142945/107724435-dd90b380-6cf4-11eb-83d3-23fce025f7f8.PNG)

Учитывая оценки проверяющих, не включая минимальной оценки, то результат честного подсчета не моей субъективной оценки равен 470 баллом это среднее между 3 (480, 480, 450) проверяющими кто поставил три первые оценки.

Оценка в score 383 из 480 возможных

**Comment by DKravchenkoEpam** [comment]
Оценка изменена на 460. (420 + 480 + 480) / 3 = 460
