### ISSUE TITLE
Cross-Check '2 - Linear Regression and Visualization' - 'YakovGrischenko'.

### ISSUE THREAD

**Issue by YakovGrischenko** [rolling-scopes-school/support#184]
деплой/реализация:
https://github.com/YakovGrischenko/rss-ml-intro/blob/main/2_linear_regression/seminar_and_homework.ipynb
задание:
https://github.com/rolling-scopes-school/ml-intro/blob/2021/2_linear_regression/seminar_and_homework.ipynb
ссылка на форму проверки:
https://rolling-scopes-school.github.io/checklist/

Оценка в результате самопроверки, с ее аргументацией:
Моя оценка 130
Все задания были выполнены и это подтвердили 3 проверяющих.

Балл за cross-check из вашего Score:
98 
(наименьшая оценка 0 не отбросилась и попала в рассчет среднего)

Сделал все вовремя, открыл для проверки репозиторий. закрыл когда начал делать следующую домашку, а оказывается в это время шел кроссчек еще и кто-то поставил 0 потому что мой репозиторий был закрыт. со мной на связь нигде не вышел, я тоже уже не смотрел оценки. В правилах написано 
**"Оценка за кросс-чек — среднее между оценками всех проверивших вашу работу. Если вас проверило 4 человека, наименьшая оценка отбрасывается, выставляется среднее между 3 оставшимися оценками."** 
но по факту среднее посчиталось с 0 тоже.
мне кажется это недоразумение и неудачное стечение обстоятельств.  оценка могла быть на 23% больше

Скриншот с оценками за cross-check:
![Screenshot 2021-02-17 at 23 52 39](https://user-images.githubusercontent.com/1833936/108239042-12c95580-717c-11eb-89ca-780a81ab3e95.png)

**Comment by Insafprog** [comment]
Все пункты задания выполнено. Соответствует 130 баллам.

**Comment by Insafprog** [comment]
Работа соответствует 130 баллам.
