### ISSUE TITLE
Cross-Check '2 - Linear Regression and Visualization' - 'Insafprog'

### ISSUE THREAD

**Issue by Insafprog** [rolling-scopes-school/support#185]
Репозиторий: https://github.com/Insafprog/rs_school_homeworld/blob/main/seminar_and_homework.ipynb
Задание: https://github.com/rolling-scopes-school/ml-intro/blob/2021/2_linear_regression/seminar_and_homework.ipynb
Чек лист: https://rolling-scopes-school.github.io/checklist/
![IMG_20210218_140030](https://user-images.githubusercontent.com/49731687/108347732-ecde9800-71f1-11eb-9863-64e61aabcbcc.jpg)
![IMG_20210218_135830](https://user-images.githubusercontent.com/49731687/108347737-eea85b80-71f1-11eb-9b8d-5a0a60f51118.jpg)
Ожидаемая оценка 130 баллов. Подтверждено двумя проверяющими. 
Оценка была снижена из-за отчёта на русском языке (в требованиях не было), и из-за удаления обоих из коррелирующих я пар (1. Удаление выполнялись с помощью кода путем отбирания только 1 из коррелирующих я фич, проверяющий не разобрался в коде. 2. В условиях задачи отсутствует данное требование, а лишь условие удаления коррелирующихся фич)
Итоговое score 126 баллов.

**Comment by dKosarevsky** [comment]
Работа соответствует 130 баллам. Выполнены все пункты. Замечаний нет.
