### ISSUE TITLE
Не верная оценка за выполненное задание Markdown & Git

### ISSUE THREAD

**Issue by Ivan-Sidorenko** [rolling-scopes-school/support#186]
Добрый вечер!
Прошу пожалуйста прокомментировать выставленную оценку по заданию Markdown & Git в размере 50 баллов.
Ссылка на выполненное задание https://github.com/rolling-scopes-school/ivan-sidorenko-JSFE2021Q1/blob/gh-pages/cv.md.
Ссылка на Pull Request https://github.com/rolling-scopes-school/ivan-sidorenko-JSFE2021Q1/pull/1.
В "Требовании к Pull Requast" по ссылке https://rolling-scopes-school.github.io/stage0/#/tasks/git-markdown?id=%d0%a2%d1%80%d0%b5%d0%b1%d0%be%d0%b2%d0%b0%d0%bd%d0%b8%d1%8f-%d0%ba-pull-request, говориться 
- Название Pull Request дайте по названию задания. В данном случае название Pull Request - Markdown & Git.
- Я понял буквально! Ведь можно было написать так: 
- Название Pull Request дайте по названию задания. В данном случае название - Markdown & Git (без слов Pull Request) я как простой юзер прочел и скопировал, понимая что это верно.

Благодарю если поймете и выставите мне 100 баллов, а также не обижусь если прокомментируете мое мнение, при этом оставив 50 баллов. Спасибо!

**Comment by dzmitry-varabei** [comment]
@Ivan-Sidorenko этот таск можно пересдать до дедлайна сколько угодно раз. Если есть вопросы, пиши в канал #git-2021Q1 в Discord

**Comment by Ivan-Sidorenko** [comment]
Дмитрий, благодарю за совет, с коллегами в discord пообщался, все
реализовал.
благодарю

пт, 19 февр. 2021 г. в 14:08, Dzmitry Varabei <notifications@github.com>:
