### ISSUE TITLE
Cross-Check '2 - Linear Regression and Visualization' - 'VVK1978'

### ISSUE THREAD

**Issue by VVK1978** [rolling-scopes-school/support#187]
Репозитарий: https://github.com/VVK1978/ML_INTRO_2021Q1/tree/main/task%202
Задание: https://github.com/rolling-scopes-school/ml-intro/blob/2021/2_linear_regression/seminar_and_homework.ipynb
Чек-лист: https://rolling-scopes-school.github.io/checklist/
![2](https://user-images.githubusercontent.com/70840645/108495171-23c7b300-72b1-11eb-9114-903116715d6d.png)
![3](https://user-images.githubusercontent.com/70840645/108495193-27f3d080-72b1-11eb-9b37-fd89bfab2bd2.png)
Ожидаемая оценка: 110-120 балов. Да, были нюансы в оформлении, тк не совсем понял как правильно оформлять на гитхабе. Проверяющий даже не пытался со мной обсудить мое решение.

**Comment by dKosarevsky** [comment]
Ваша оценка - 120 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Short report about the work done exists 

Выполненные пункты:
1) Histogram of player height distribution in meters is built correctly 

2) MSE function is written correctly and passes the asserts 

3) The dependence of test BallControl predictions and real BallControl score on Dribbling score is plotted correctly 

4) Linear Regression class is completed correctly and passes the asserts 

5) Float number from Value field extracted 

6) Correlation matrix is built 

7) A sequential process of dropping highly correlated features was carried out. No pairs of features with abs(corr) > 0.9 are left. 

8) Train-test split done. 

9) Model was trained on train dataset, predictions were made for both train and test 

10) Model performance was measured both on train and test data in terms of MSE or RMSE
