### ISSUE TITLE
Cross-Check '2 - Linear Regression and Visualization' - 'LilacRapture'

### ISSUE THREAD

**Issue by LilacRapture** [rolling-scopes-school/support#188]
Репозиторий: https://github.com/LilacRapture/rs_machine_learning/blob/master/seminar_and_homework_1_fin.ipynb
Задание: https://github.com/rolling-scopes-school/ml-intro/blob/2021/2_linear_regression/seminar_and_homework.ipynb
Форма для проверки: https://rolling-scopes-school.github.io/checklist/
Оценки:
![linear_regression_homework](https://user-images.githubusercontent.com/39832289/108497212-2da2e380-72bc-11eb-9455-64a62cd41a95.png)

Выполнено всё, кроме последнего, 5 задания, поэтому ожидаемая оценка около 80 баллов. В 4 задании в классе много повторений кода, но assert проходит. Человек, который поставил 12 без комментариев, не ответил в личке.
На данный момент оценка в score: 57

**Comment by dKosarevsky** [comment]
Ваша оценка - 80 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Float number from Value field extracted 

2) Correlation matrix is built 

3) A sequential process of dropping highly correlated features was carried out. No pairs of features with abs(corr) > 0.9 are left. 

4) Train-test split done. 

5) Model was trained on train dataset, predictions were made for both train and test 

6) Model performance was measured both on train and test data in terms of MSE or RMSE 

7) Short report about the work done exists 

Выполненные пункты:
1) Histogram of player height distribution in meters is built correctly 

2) MSE function is written correctly and passes the asserts 

3) The dependence of test BallControl predictions and real BallControl score on Dribbling score is plotted correctly 

4) Linear Regression class is completed correctly and passes the asserts

**Comment by dr-leto** [comment]
Issue is verified and score is updated
