### ISSUE TITLE
Cross-Check Singolo - BananaFo

### ISSUE THREAD

**Issue by BananaFo** [rolling-scopes-school/support#19]
Ссылка: https://bananafo.github.io/singolo/singolo.html
Проверяющим указаны следующие ошибки:
1) В Firefox есть сильное отклонение (т.е. бросается в глаза) от той же страницы, открытой в Google Chrome: минус -5 баллов 
2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла 
3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Portfolio составляют более двух пикселей (2px): минус -3 балла 
4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла 
5) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла 
6) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Footer составляют более двух пикселей (2px): минус -3 балла 
7) На странице отсутствует элемент "< h1 >", либо на нём есть свойство display: none: минус -3 балла 
8) В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла 
9) Номер телефона в блоке Contacts не реализован ссылкой, работающей с префиксом tel:: минус -3 балла 
10) Электронная почта в блоке Contacts не реализована ссылкой, работающей с префиксом mailto:: минус -3 балла 

Итоговый балл по этому рассмотрению - 68
Пункты 2-6 - не знаю на каком калькуляторе был просмотрен проект, но на 4 разных ПК всё отображалось корректно.
Пункты 7, 9, 10 - категорически не согласен - данные моменты применены. Вопрос: куда смотрел проверяющий?

**Comment by amoebiusss** [comment]
@BananaFo добрый день! Добавьте, пожалуйста, полученный итоговый балл и вашу оценку в описание.

**Comment by BananaFo** [comment]
> @BananaFo добрый день! Добавьте, пожалуйста, полученный итоговый балл и вашу оценку в описание.

Добавлено

**Comment by amoebiusss** [comment]
@BananaFo привет! Итоговая оценка по обновленному алгоритму — 91, наименьшая оценка не учитывалась при подсчете. Поэтому закрываю ишью. Хорошего дня!
