### ISSUE TITLE
Cross-Check '2 - Linear Regression and Visualization' - 'grnkvch'

### ISSUE THREAD

**Issue by grnkvch** [rolling-scopes-school/support#190]
Repository: https://github.com/grnkvch/rs_ml_course/blob/2_linear_regression/seminar_and_homework.ipynb
Task:
https://github.com/rolling-scopes-school/ml-intro/blob/2021/2_linear_regression/seminar_and_homework.ipynb
Form:
https://rolling-scopes-school.github.io/checklist/

![screencapture-app-rs-school-course-student-cross-check-submit-2021-02-21-12_22_08](https://user-images.githubusercontent.com/43145804/108620802-94043f00-743f-11eb-8e54-b0c6c5db5cfa.png)

![image](https://user-images.githubusercontent.com/43145804/108620868-07a64c00-7440-11eb-88b7-66603da67ffe.png)

Не понимаю почему так была посчитана итоговая оценка в таблице, ожидается (130+130+130+125)/4 = 128,75
P.S.
К сожалению, связаться с человеком, который не поставил оценку, не удалось

**Comment by dr-leto** [comment]
Issue is verified and score is updated.
