### ISSUE TITLE
Cross-Check 'Overfitting and Regularization - 'bormaley999'.

### ISSUE THREAD

**Issue by bormaley999** [rolling-scopes-school/support#191]
Привет!

Проверьте, пожалуйста, почему не отбросилась последняя оценка (ее по факту нет) от проверяющего.

Текст от проверяющего:
Не смог проверить задание, так как не открывается код в отличие от других участников.

Как должно быть подсчитано:
(100+60+65)/3 = 75 -> таким образом выбрасываем 0. Плюс, проверяющий, который поставил 0 в Дискорд мне не написал, у троих других проверяющих все ОК. 

Ссылка на ноутбук c домашкой: https://github.com/bormaley999/RS_School_ML_Intro/blob/main/3_overfitting_and_regularization/work_overfitting_regularization.ipynb

Скрин с оценками 
![1](https://user-images.githubusercontent.com/42649326/108744552-1cbbd180-754b-11eb-9d0f-3744d4489fe8.png)
в приложении.

**Comment by JackNightsky** [comment]
Я проверял эту работу. Нормально по итогу открылось. Видимо человек поспешил. Ноль ставить - это слишком. Мой комментарий прямо в центре, что выполнено, а что нет.

**Comment by dr-leto** [comment]
Issue is verified and score is updated
