### ISSUE TITLE
Problem with Codewars stage 1 for JS/FE 2021  tasks submission

### ISSUE THREAD

**Issue by RostyslavL** [rolling-scopes-school/support#192]
**I have a problem with my   Codewars stage 1 for JS/FE 2021  tasks submission :  correct tasks are not effected, what should i do**
![autotest](https://user-images.githubusercontent.com/69625842/109392755-2adc6a00-791e-11eb-8c73-abd15ea4eb83.JPG)
**username** : RostyslavL
![autotest_2](https://user-images.githubusercontent.com/69625842/109392821-8f97c480-791e-11eb-95ce-a14f59342b41.jpg)
**Description** : Correct  katas from  `Codewars  Stage 1` in` JS/FE 2020 for Poland` are not effected instead of `Codewars  Stage 2`

Plese help to solve this problem ,what should I do ?

**Comment by dzmitry-varabei** [comment]
fixed.
