### ISSUE TITLE
Cross-Check 'Feature_engineering_selection' - 'TarasNavakhatska'

### ISSUE THREAD

**Issue by TarasNavakhatska** [rolling-scopes-school/support#193]
1. Ссылка на репозиторий с заданием и решением.
https://github.com/TarasNavakhatska/RSS_EPAM/blob/main/feature_engineering_selection.ipynb
2. Самопроверка. Оценка 7. Отсутствует выполнение третьего задания (минус три балла). Есть сомнения по отсутствию функции проверки. В задании было указано "Сравните". Сравнение произведено визуально. Расхождения отсутствуют. 
3. Скриншоты оценок проверяющих и балла за кросс-чек приложены ниже.
4. Суть аппеляции...  Из-за того что кто-то начал перед дедлайном проверять кросс-чеки не смог открыть мой линк, хотя остальные открыли, и выставил ноль. У меня 4 проверяющих: 70, 60, 60 и типа не открытый стоит 0. В итоге 50. 
С уважением.
![Безымянный](https://user-images.githubusercontent.com/66428594/109541727-2d34f480-7ad5-11eb-9e04-95a389ed9975.png)
 
![Безымянный](https://user-images.githubusercontent.com/66428594/109541980-83a23300-7ad5-11eb-8834-d5409532f4ed.png)

**Comment by dKosarevsky** [comment]
Итоговая оценка 70.

Exercise 1 - Scaling (3/3 points)
Exercise 2 - Visualization (4/4 points)
Exercise 3 - Preprocessing Pipeline (0/3 points)

--------------
Замечания:
    1. Зачем определять функцию `function` дважды? =)

**Comment by dr-leto** [comment]
Done
