### ISSUE TITLE
Cross-Check 'HTML & CSS' - 'MrDreMeR'

### ISSUE THREAD

**Issue by MrDreMeR** [rolling-scopes-school/support#194]
1.https://github.com/MrDreMeR/rsschool-cv/pull/2
2. Ссылка на репозиторий с заданием и решением.
https://github.com/MrDreMeR/rsschool-cv/tree/rsschool-cv-html
3.Ссылка на задание.
https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/html-css.
4. Ссылка на форму для проверки проекта
https://html-css-git-cross-check.netlify.app/
5. Самооценка.  95 баллов выполнены все требования кроме множества семантических тэгов.
6. Подаю апелляцию и прошу проверить и оценить мою работу, так как просто не правильно понял здание и думал засабмитить нужно 09.03.2021 до 11.03.2021. Спасибо за понимание.
![image](https://user-images.githubusercontent.com/79418375/110509571-4a8c4300-8113-11eb-9f2e-b00c31f6b1cc.png)

**Comment by valerydluski** [comment]
Активистов желающих проверять все работы, которые забыли (не успели) отправить на проверку, нет.
