### ISSUE TITLE
Cross-Check 'HTML & CSS' - 'Maddy1313'

### ISSUE THREAD

**Issue by Maddy1313** [rolling-scopes-school/support#195]
1. https://github.com/Maddy1313/rsschool-cv/pull/2
2. Ссылка на репозиторий с заданием и решением.
https://github.com/Maddy1313/rsschool-cv/tree/rsschool-cv-html
3. Ссылка на задание.
https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/html-css.
4. Ссылка на форму для проверки проекта
https://html-css-git-cross-check.netlify.app/
5. Самооценка. 95 баллов выполнены все требования кроме множества семантических тэгов.
6. Подаю апелляцию и прошу проверить и оценить мою работу, так как просто не правильно понял здание и думал засабмитить нужно 09.03.2021 до 11.03.2021. Спасибо за понимание.

**Comment by valerydluski** [comment]
Активистов желающих проверять все работы, которые забыли (не успели) отправить на проверку, нет.
