### ISSUE TITLE
Cross-Check 'HTML & CSS' - 'ajax3101'

### ISSUE THREAD

**Issue by ajax3101** [rolling-scopes-school/support#196]
- Ссылка на деплой вашего проекта. https://ajax3101.github.io/rsschool-cv/
- Ссылка на репозиторий с проектом на GitHub. https://github.com/ajax3101/rsschool-cv
- Ссылка на задание. https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/html-css
- Ссылка на форму для проверки проекта (если такая есть). https://html-css-git-cross-check.netlify.app/
- Скриншот с оценками за cross-check 
![appeal](https://user-images.githubusercontent.com/3379715/110787938-a15e5d80-8276-11eb-983e-2e8f2b24eaf3.jpg)
(контакты проверяющих должны быть скрыты).
- Оценка в результате самопроверки, с ее аргументацией. (100)
- Балл за cross-check из вашего Score. (6.6)
=============================
Добрый день уважаемые админы! 
Рассказываю ситуацию. 
Работу я не списывал, а позаимствовал, что не запрещается школой RS School. Посмотрел[ ролик по крос-чеку](https://youtu.be/O9qR65Juy6U?t=424) в нем был разбор двух работ. Одна из работ мне понравилась, и я позаимствовал ее из открытого источника (GitHub - https://github.com/Wolf-Den1994/) исправил ошибки и адаптировал под себя (внес свои данные, исправил структуру как мне это надо было, оставил css не тронутым т.к. понравилась цветовая схема и фотка). При этом я в дискорде сказал человеку
![discord](https://user-images.githubusercontent.com/3379715/110788802-c56e6e80-8277-11eb-83e1-a1bb93574c83.jpg)
 спасибо за хороший мануал и ХТМЛ к работе. Но два (Кэпа) из трех студентов поставили по 0 балов и написали ментору курса о том, что я списал. (Хотя их просили проверить работу!)., но Бог с ними, студенты как студенты. Проще, не глядя в код, а только по внешнему виду, сделать вывод (не правильный на мой взгляд!) и сообщить о списывании.
Вопрос тогда получается открытым, что значит - списал? Что является списыванием в понимании Ваших менторов. И проверяет ли ментор лично работу, после сообщения о списывании? Или доверяет субъективному мнению другого студента при кросс-чеке?
Если бы я взял любой другой Фреймворк (Bootstrap, Tailwind, bulma, skeleton, Foundation, semantic ui и т.д. и т.п.) или даже в задание были ссылки на фрипик и канву, нашлись бы еще парочку которые по цветовой схеме решили, что опять списал.
Чтобы такого не повторялось пишите более конкретно задания, ставьте какие-то ограничения (у однокурсников не заимствовать), в лекциях, которые даете отключайте общий доступ к ресурсу и т.д. и т.п. И указывайте процент самостоятельности в работе, так как запрет на использование готовых решений, при условии их адаптации для своей задачи, Вы не ставите. 
В данный период времени я считаюсь отчисленным с курсов status Inactive (об этом мне сообщил главный ментор курса), очень жаль. А так хотелось освоить еще один язык.
Кто готов подержать меня в апелляции моей работы? Милости просим.

**Comment by valerydluski** [comment]
Да. вашу работу смотрели не только студенты. 
![image](https://user-images.githubusercontent.com/57412523/110894394-e03cf380-8308-11eb-9255-75ef818e0056.png).

За копирование кода других студентов, отчисление: https://docs.rs.school/#/dismission

**Comment by ajax3101** [comment]
<p>Я питал некие иллюзии: «Мол давайте дадим ему второй шанс, посмотрим, как справиться со вторым заданием – версткой, потом спросим алгоритмы и тогда окончательно отчислим! :)». Поэтому и запустил апелляцию. А тут получил еще одного «Кэпа», который видит то, что хочет видеть. У Вас как в банке - самая важная информация находиться где ни будь внизу и сделано маленьким шрифтом. Да мой бок, признаю, не осилил кучу  <strike>не нужной </strike> документации («впрыгнул в последний вагон уходящего поезда» 7 марта, дедлайн - 8 марта), пользовался только https://rolling-scopes-school.github.io/stage0/#/</p>
<p>Конечно можно было сказать, что Вы правила только добавили, но посмотрев историю на хабе, понял, что их написание даётся Вам не легко. Поэтому еще раз повторяюсь - Любое мнение должно быть выслушано, почему студент поступил так или иначе, даже если студент ошибается и неправ. Я считаю, что нельзя просто сказать студенту «ты неправ, ты списал и т.д.». Наоборот, вокруг этого можно выстроить обсуждение, выяснить, почему студент это сделал, думает именно так, какие были его мотивы, какая была его логика и доводы, а потом поправить студента, посмотреть на проблему, с другой стороны. Это нужно для того, чтобы студенты не делали те или иные ошибки, не боялись высказывать свои мысли. Нельзя так со студентами, студентов надо любить и охранять. Это пока у Вас большие наборы, «снимаете сливки» так сказать, но ниша Ваша не безграничная, есть сотня других фирм, к которым они могут уйти. Опять же, сильно высокий порог вхождения, не давая при этом ничего, кроме «посмотри там или там», «спроси у Гугла» и жестокий дедлайн. Исходя из Выше перечисленного у Вас профессиональные программисты и т.д., но нет профессиональных педагогов или людей знакомых с педагогикой. А если Вы позиционируете себя как школа, то у Вас в первую очередь должны быть **ПЕДАГОГИ**!</p>
<p>З найлепшымі пажаданнямі,
к.т.н., дацэнт, заг. каф. інфармацыйных тэхналогій Марозаў Дзяніс :)
</p>

**Comment by ai297** [comment]
> но нет профессиональных педагогов или людей знакомых с педагогикой
Об этом говорится на каждом вводном вебинаре. У нас комьюнити, то есть сообщество, которое собралось с целью обмена опытом и взаимного обучения. Но есть несколько строгих принципов.
Если вам не подходит формат, когда вас не учат, а лишь дают задачи, а учиться надо самому - что ж, поищите себе школу, которая подойдёт лично вам.
Нам же не подходят коллеги, которые не пытаются учиться, а пытаются как-то исхитриться и списать. Зачем? Ведь вы не получите знаний, списывая у других. И не принесёте пользу сообществу. Вы не проявляете уважения к сообществу, нарушая его правила и не желая знакомиться "с ненужной" документацией... Так не ожидайте уважения в ответ - мы так же не желаем знакомиться с вашими причинами :-)

Желаю вам удачи найти такую школу, которая вам подойдёт.
