### ISSUE TITLE
Cross-Check 'HTML & CSS' - 'KalinkinFiz'.

### ISSUE THREAD

**Issue by KalinkinFiz** [rolling-scopes-school/support#197]
- [Ссылка на деплой вашего проекта](https://github.com/KalinkinFiz/rsschool-cv/pull/7)
- [Ссылка на репозиторий с проектом на GitHub](https://github.com/KalinkinFiz/rsschool-cv)
- [Ссылка на задание](https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/html-css)
- [Ссылка на форму для проверки проекта (если такая есть).](https://html-css-git-cross-check.netlify.app/)
- Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
![image](https://user-images.githubusercontent.com/42799149/110820057-cb784580-829f-11eb-8a38-714ad6aa9478.png)
- Оценка в результате самопроверки, с ее аргументацией. 
100 / 100 :

1. вёрстка валидная +10
2. вёрстка семантическая +10 (**header, address, article, section, footer**)
3. используются заголовки h1-h6 +10
4. для оформления СV используются css-стили +10
5. контент размещается в блоке, который горизонтально центрируется на странице +10
6. на странице СV присутствует изображение, пропорции изображения не искажены, у изображения есть атрибут alt +10
7. контакты для связи и перечень навыков оформлены в виде списка ul > li +10 (**контакты у меня указаны в двух местах, а именно, в header и footer (в footer оформил в виде списка, обратите внимание)**)
8. CV содержит контакты для связи, краткую информацию о себе, перечень навыков, примеры кода или выполненных проектов, информацию об образовании и уровне английского +10
9. CV выполнено на английском языке +10
10. выполнены требования к репозиторию: есть ссылка на задание, скриншот страницы СV, ссылка на деплой страницы CV на GitHub Pages, выполнена самооценка +10

- Балл за cross-check из вашего Score (67)

P.S. Student 3 крайне некрасиво поступил, когда сам же, из-за своей невнимательности, оставил отметку 0 за проделанную работу. Я так понимаю, я не один у него такой оказался, кому он поставил 0...

**Comment by valerydluski** [comment]
Ваша оценка 100 баллов. Будет выставлена, после проверки всех апелляций.

**Comment by KalinkinFiz** [comment]
> Ваша оценка 100 баллов. Будет выставлена, после проверки всех апелляций.

спасибо большое, буду ждать результат уже в скор)
