### ISSUE TITLE
Cross-check 'react-game' - 'Elwa36s'

### ISSUE THREAD

**Issue by Elwa36s** [rolling-scopes-school/support#198]
[Deploy](https://elwa36s.github.io/react-game/)
[Repository](https://github.com/Elwa36s/react-game)
[Task](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/react/react-game.md)
![nespec](https://user-images.githubusercontent.com/70883253/110837904-e1433600-82b2-11eb-8bfa-e312d5a8708d.PNG)
![spec](https://user-images.githubusercontent.com/70883253/110837912-e30cf980-82b2-11eb-9eb6-f3df7927448c.PNG)
Самооценка: 60 / 100
Basic scope +25:
вёрстка, дизайн, UI. Выполняются требования к оформлению приложения +10
эффекты анимации. Анимация ходов, перемещения фигур, допустимых и недопустимых ходов, начала и окончания игры, победы и поражения и т.д +5
механика игры. Ходы, перемещения фигур, набранные баллы, окончание игры и т.д. подчиняются определённым свойственным игре правилам +10
Advanced scope +35
звуки и музыка. В игре есть звуки и музыка, и есть настройки звуков и музыки: возможность вкл/откл звуки, вкл/откл музыку, регулировать громкость звуков, регулировать громкость музыки +5
статистика. Пользователь информируется о состоянии игры, ведётся запись ходов, побед и поражений, времени игры, либо отображается другая статистика игры. Есть таблица рекордов, в которой сохраняются результаты предыдущих 10 игр +10
сохранение состояния игры при перезагрузке страницы. Сохраняются все опции игры: ходы, набранные очки, положение фигур и т д. Состояние игры сохраняется без необходимости кликать по кнопке save. Есть кнопка new game для запуска новой игры +10
возможность управления игрой с клавиатуры или не меньше пяти hot keys. Есть список горячих клавиш для управления игрой с клавиатуры +10
Cross-check score: 56.

**Comment by valerydluski** [comment]
Ваша, оценка в score 62 балла. Закрываю.
