### ISSUE TITLE
Cross-Check 'HTML & CSS' - 'daz80'.

### ISSUE THREAD

**Issue by daz80** [rolling-scopes-school/support#199]
1. deploy - https://daz80.github.io/rsschool-cv
2. repository - https://github.com/daz80/rsschool-cv
3. https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/html-css
4. 
![image](https://user-images.githubusercontent.com/36031300/110897192-0ca73e80-830e-11eb-861d-09158b256585.png)
5. Требования самопроверки
вёрстка валидная +10
вёрстка семантическая +10 (header, main, article, section, footer, nav)
используются заголовки h1-h6 +10
для оформления СV используются css-стили +10
контент размещается в блоке, который горизонтально центрируется на странице +10
на странице СV присутствует изображение, пропорции изображения не искажены, у изображения есть атрибут alt +10
контакты для связи и перечень навыков оформлены в виде списка ul > li +10 
CV содержит контакты для связи, краткую информацию о себе, перечень навыков, примеры кода или выполненных проектов, информацию об образовании и уровне английского +10
CV выполнено на английском языке +10
выполнены требования к репозиторию: есть ссылка на задание, скриншот страницы СV, ссылка на деплой страницы CV на GitHub Pages, выполнена самооценка +10
Score : 100
6. Балл за кросс-чек не стоит, работа не была оценена, хотя в разделе Cross-Check: Review, проверил и засабмитил все 4 работы, эти люди увидели мой отзыв и потом связывались со мной.
P.S. Прошу разобраться с этим недорозумением.

**Comment by Loktysh** [comment]
Ваша оценка - 90 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) вёрстка валидная. Проверить валидность вёрстки: https://validator.w3.org/ 

Выполненные пункты:
1) вёрстка семантическая. 2 балла за каждый уникальный семантический тег HTML5 

2) используются заголовки h1-h6. 5 баллов за каждый уникальный заголовок 

3) для оформления СV используются css-стили 

4) контент размещается в блоке, который горизонтально центрируется на странице 

5) на странице СV присутствует изображение, пропорции изображения не искажены, у изображения есть атрибут alt 

6) контакты для связи и перечень навыков оформлены в виде списка ul > li 

7) CV содержит контакты, краткую информацию о себе, навыки, примеры кода, образование, уровень английского 

8) CV выполнено на английском языке 

9) выполнены требования к репозиторию: есть ссылка на задание, скриншот страницы СV, ссылка на деплой страницы CV на GitHub Pages, указана дата дедлайна, выполнена самооценка
