### ISSUE TITLE
Cross-Check Singolo - GanulAnton

### ISSUE THREAD

**Issue by GanulAnton** [rolling-scopes-school/support#20]
Ссылка на деплой вашего проекта: https://ganulanton.github.io/Singolo/ 

Ссылка на репозиторий с проектом на GitHub: https://github.com/GanulAnton/Singolo

Оценка в результате самопроверки, с ее аргументацией: работа выполнена на 100 баллов, все соответствует заданным критериям проверки.

Балл за cross-check из вашего Score:

Ваша оценка - 77 баллов 

1) В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020: минус -10 баллов 

2) В коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020: минус -10 баллов 

3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла 

Аргументация:

1) Да, последний коммит и вправду сделан позже чем 24.02.2020, однако этот коммит затрагивал только переименование самого файла в репозитории Singolo (index.html -> singolo1.html), а основное решение было добавлено 23.02.2020

2) Точно такая же ситуация что и с п.1

3) Там все идеально совпадает, пересмотрите пожалуйста.

**Comment by hallovarvara** [comment]
Проведено ревью работы.

Моя оценка:
100

Проверила историю коммитов. Файл с содержимым `singolo1.html` был, но назывался по-другому. После дедлайна был переименован. Поскольку все содержимое сделано до дедлайна, снижать оценку смысла не вижу. По singolo 2 история другая — файл был залит 1 марта, так что здесь даже формальное условие выполнено. Содержимое тоже добавлено до дедлайна.

По Pixel Perfect претензий нет, [прилагаю скриншот (сделан с retina-дисплея)](https://user-images.githubusercontent.com/9438195/76619957-2c5e2800-653d-11ea-83ff-c92dd048495c.png). Максимальное найденное мной расхождение в форме составляет 2 px, что допустимо.

Есть небольшие замечания, не отразившиеся на оценке:

1. Трехколоночный макет сделан отдельными блоками-рядами, но flex там есть, поэтому баллы не снимаю. Оптимальнее было бы положить все элементы в один блок, задать `justify-content: space-between;` и выровнять их padding'ами.

2. В блоке Portfolio по условиям задания с интерактивом панели тегов все ок, но в будущем лучше на кликабельные элементы добавлять `cursor: pointer;`, чтобы пользователь понимал, что сюда можно нажать.

В остальном, макет отлично сверстан. Спасибо за работу.
