### ISSUE TITLE
Cross-Check HTML & CSS - Capral-Levi

### ISSUE THREAD

**Issue by Capral-Levi** [rolling-scopes-school/support#200]
1. https://capral-levi.github.io/rsschool-cv/
2. https://github.com/Capral-Levi/rsschool-cv
3. https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/html-css
4. -
5. Не успел по тому как решал в больнице с отравлением справку предоставил админу Valery Dluski
6. 90/100   Валидная верстка.
используются заголовки h1-h6
используются css стили
контент центрирован
у изображение есть атрибут alt
присутствует список
на английском 
выполнены требования к репозиторию
7. -

**Comment by ai297** [comment]
Ваша оценка - 70 баллов
--------
+ вёрстка валидная **+10**
+ вёрстка семантическая **+0** - *семантические HTML5 теги не используются*
+ используются заголовки h1-h6 **+10** - *нет заголовка h1, но условие задания выполнено*
+ для оформления СV используются css-стили **+10**
+ контент размещается в блоке, который горизонтально центрируется на странице **+0** - *контент занимает всю доступную ширину экрана, смотрится очень плохо на больших разрешениях*
+ на странице СV присутствует изображение, пропорции изображения не искажены, у изображения есть атрибут alt **+10**
+ контакты для связи и перечень навыков оформлены в виде списка ul > li **+5** - *контакты оформлены списком, перечень навыков - нет*
+ CV содержит контакты для связи, краткую информацию о себе, перечень навыков, примеры кода или выполненных проектов, информацию об образовании и уровне английского **+5** - *примеров кода и / или проектов нет совсем. Про владение языком написано, но уровень не указан, было бы лучше добавить - это гораздо понятнее для HRов будет.*
+ CV выполнено на английском языке **+10**
+ Выполнены требования к репозиторию: есть ссылка на задание, скриншот страницы СV, ссылка на деплой страницы CV на GitHub Pages, выполнена самооценка **+10**
