### ISSUE TITLE
Cross-Check 'HTML & CSS' - 'gorelikspb'

### ISSUE THREAD

**Issue by gorelikspb** [rolling-scopes-school/support#201]
Ссылка на деплой вашего проекта.
https://gorelikspb.github.io/rsschool-cv/
Ссылка на репозиторий с проектом на GitHub.
https://github.com/gorelikspb/rsschool-cv
Ссылка на задание.
https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/html-css
Ссылка на форму для проверки проекта (если такая есть).
https://html-css-git-cross-check.netlify.app/
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
![image](https://user-images.githubusercontent.com/66779925/110962138-acda8300-8361-11eb-95f2-9461d067f55f.png)

Оценка в результате самопроверки, с ее аргументацией.

92  исходя из округленногосреднего балла полученного при кросс-чеке (100+90+85)/3  (наименьшую оценку, 80 отбрасываем). 

Увы, оценка не засчитана, т.к. я пропустил сроки кросс-чека с моей стороны. Причина в том, что соответствующее сообщение в дискорде я не заметил (надо добавить что в канале довольно много анонсов не относящихся к данному курсу, касающиеся жителей определенных городов и т.п.). Поэтому был уверен, что дедлайн по кросс-чеку синхронизирован со дедлайном по сабмиту следующей порции заданий - как это устроено в другом курсе RS (ML Intro). 

О другом дедлайне узнал, уже выполнив кросс-чек предложенных в rs app работ. Теперь, конечно, буду знать о том что в данном курсе на кросс-чек отводится меньше времени, но надеюсь, что в первый раз такая неточность простительна,

и Балл за cross-check из вашего Score, сейчас выставленный в ноль, может быть исправлен на соответствующий, т.е. 92*0.2 ~= 18

**Comment by valerydluski** [comment]
Оценка обновится ночью. Закрываю
