### ISSUE TITLE
Cross-Check 'HTML & CSS' - 'InessaBoickova'.

### ISSUE THREAD

**Issue by InessaBoickova** [rolling-scopes-school/support#202]
Ссылка на деплой вашего проекта.
https://inessaboickova.github.io/rsschool-cv/
Ссылка на репозиторий с проектом на GitHub.
https://github.com/InessaBoickova/rsschool-cv
Ссылка на задание.
https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/html-css
Ссылка на форму для проверки проекта (если такая есть).
https://html-css-git-cross-check.netlify.app/
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
![](https://i.imgur.com/OVVDG8X.png)
Оценка в результате самопроверки с ее аргументацией.
Максимальный балл за задание +100
1.вёрстка валидная +0
2.вёрстка семантическая +6
В коде страницы присутствуют семантические теги HTML5 aside, footer, main,
3.используются заголовки h1-h6 +5(использовала только h2)
4.для оформления СV используются css-стили +10
5.контент размещается в блоке, который горизонтально центрируется на странице +10
6.на странице СV присутствует изображение, пропорции изображения не искажены, у изображения есть атрибут alt +10
7.контакты для связи и перечень навыков оформлены в виде списка ul > li  +5
(не заметила , что li "выпало" из ul . -5 баллов за невнимательность)
8.CV содержит контакты для связи, краткую информацию о себе, перечень навыков, примеры кода или выполненных проектов, информацию об образовании и уровне английского +10
9.CV выполнено на английском языке +10
10.выполнены требования к репозиторию: есть ссылка на задание, скриншот страницы СV, ссылка на деплой страницы CV на GitHub Pages, выполнена самооценка +10

Итого - 76 баллов .
Балл за cross-check из вашего Score.
54

Работа выполнена не идеально , но очень бы хотелось получить справедливый балл.
Спасибо .

**Comment by InikonZS** [comment]
- По идее 7 пункт выполнен - контакты для связи оформлены в виде списка +5

- Пункт 1 не выполнен из-за того, что выпал li. [Ссылка на эти ошибки](https://validator.w3.org/nu/?doc=https%3A%2F%2Finessaboickova.github.io%2Frsschool-cv%2F) , их ровно 2 по этим li 

Работа понравилась, структурно так, и стильно. 
Итого - **81**

Некоторые замечания по коду
- Элементы h2 вложены в div таким образом, что margin от h2 выходит за пределы div. Было бы лучше отключить margin для h2 и задать padding для div при таком раскладе, так удобнее. Хотя можно обойтись и элементом h2 только.

- По логике вещей код вставляется в 1 тег code и внутри него с помощью других тегов форматируется, иногда форматирование достигается тегом pre совместно с тегом code. http://htmlbook.ru/html/code

**Comment by InessaBoickova** [comment]
Здравствуйте . Спасибо за замечания , в дальнейшем учту )
