### ISSUE TITLE
Cross-Check Wildlife - AlmazerX

### ISSUE THREAD

**Issue by AlmazerX** [rolling-scopes-school/support#203]
1. https://rolling-scopes-school.github.io/almazerx-JSFE2021Q1/wildlife/
2. https://github.com/rolling-scopes-school/almazerx-JSFE2021Q1/pull/2
3. https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/wildlife
4. https://wildlife-cross-check.netlify.app/
5. ![image](https://user-images.githubusercontent.com/79789378/111270056-6fffdc00-8640-11eb-9b07-772ee207732f.png)
6. Не согласен с отсутствием placeholdera(+2), а так же картинки животных выполнялись с помощью flexbox (+4)
Итог: 39/50
7. 33/50
Отцентровка и бэкграунд не учитывался в оценивании(в вопросах дискорда rs school wildlife дали ясно понять, что таких критериев нет в шаблоне для проверки)

**Comment by ai297** [comment]
Кросс чек ещё не завершён, @valerydluski мне кажется можно закрыть.
