### ISSUE TITLE
Cross-Check wildlife katrinaiva

### ISSUE THREAD

**Issue by katrinaiva** [rolling-scopes-school/support#206]
Ссылка на деплой вашего проекта - https://rolling-scopes-school.github.io/katrinaiva-JSFE2021Q1/wildlife/ 
Ссылка на репозиторий с проектом на GitHub - https://github.com/rolling-scopes-school/katrinaiva-JSFE2021Q1/tree/wildlife
Ссылка на задание - https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/wildlife
Ссылка на форму для проверки проекта  - https://wildlife-cross-check.netlify.app/
Скриншот с оценками за cross-check - https://clip2net.com/s/4bmm60k
Оцениваю свою работу на 50 баллов из 50. Поскольку выполнены  все пункты в соответсвии с заданием. 
Балл за cross-check из вашего Score 22

**Comment by valerydluski** [comment]
неправильно оформили.
