### ISSUE TITLE
Cross-Check wildlife - svk-man

### ISSUE THREAD

**Issue by svk-man** [rolling-scopes-school/support#207]
Ссылка на деплой вашего проекта - https://rolling-scopes-school.github.io/svk-man-JSFE2021Q1/wildlife/
Ссылка на репозиторий с проектом на GitHub - https://github.com/rolling-scopes-school/svk-man-JSFE2021Q1/tree/wildlife
Ссылка на задание - https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/wildlife
Ссылка на форму для проверки проекта - https://wildlife-cross-check.netlify.app/
Скриншот с оценками за cross-check - https://ibb.co/nDH9Fb7
Оцениваю свою работу на 50 баллов из 50. Поскольку выполнены все пункты в соответствии с заданием.
Балл за cross-check из вашего Score: 18

**Comment by valerydluski** [comment]
есть коммиты после дедлайна. закрываю
