### ISSUE TITLE
Cross-Check  "Wild Life" -JennyBortnouskaya

### ISSUE THREAD

**Issue by JennyBortnouskaya** [rolling-scopes-school/support#208]
1. Ссылка на деплой проекта - https://rolling-scopes-school.github.io/jennybortnouskaya-JSFE2021Q1/wildlife/
2. Ссылка на репозиторий с проектом на GitHub - https://github.com/rolling-scopes-school/jennybortnouskaya-JSFE2021Q1/tree/wildlife
3. Ссылка на задание - https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/wildlife
4. Ссылка на форму для проверки проекта - https://wildlife-cross-check.netlify.app/
5. Скриншот с оценками за cross-check - https://clip2net.com/s/4bmm60k
![image](https://user-images.githubusercontent.com/19994174/111900738-53e7aa80-8a45-11eb-934c-4802f82d03a3.png)
![image](https://user-images.githubusercontent.com/19994174/111900757-5fd36c80-8a45-11eb-82d7-9070311d90e7.png)
![image](https://user-images.githubusercontent.com/19994174/111900770-7083e280-8a45-11eb-875a-a9c6186fd4c1.png)

Оцениваю свою работу на 45 баллов из 50. 

Перепроверка:

Не выполненные/не засчитанные пункты:

1) На странице обязательно должен присутствовать один элемент h1. Расположите его на свое усмотрение. Не проверяем какой именно элемент указан как h1, главное, чтобы он был и был только один. 
Да, действительно h1 продублирован в футере.

Частично выполненные пункты:

1) Панель навигации состоит из четырёх элементов: двух ссылок, иконки поиска и кнопки "Sign in" . Верстается в виде ненумерованного списка: ul > li > a.  Иконка поиска подключена в виде картинки -1 балл.
2) Логотип полностью повторяет логотип блока Header. Речь о визуальном сходстве, а не использовании точно таких же тегов. Используются те же теги что и в header. -2 балла

Всё остальное соответствует критериям. В задание нет ничего по поводу особого подключения шрифтов, например.

По поводу Pixel Perfect. Я согласна, что существуют расхождения, но не более 5px по горизонтали или более 10рх по вертикали.

![image](https://user-images.githubusercontent.com/19994174/111901207-99a57280-8a47-11eb-9fd1-4a79940ff124.png)

Прошу работу перепроверить и выставить честную оценку, так как считаю текущую неправильной.
Спасибо.

**Comment by valerydluski** [comment]
Апелляция рассматривается только если ожидаемый вами балл и полученный по результатам cross-check проверки средний балл отличаются на 15 и более процентов.

**Comment by valerydluski** [comment]
закрываю
