### ISSUE TITLE
Cross-Check "Wild Life" -Finnchick

### ISSUE THREAD

**Issue by Finnchick** [rolling-scopes-school/support#209]
1. https://rolling-scopes-school.github.io/finnchick-JSFE2021Q1/wildlife/
2. https://github.com/rolling-scopes-school/finnchick-JSFE2021Q1
3. https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/wildlife
4. 
![image](https://user-images.githubusercontent.com/24357052/111910554-e5b9dc80-8a72-11eb-876c-6a975ace7915.png)
5. 49 
6. Прошу проверить, ибо был на операции и не успел проверить чужие работы, написал по этому поводу Valery Dluski
#3588

**Comment by zil130** [comment]
### Ваша оценка - 44 балла
1. На странице два элемента h1. Минус 2 балла
2. Иконка поиска сверстана не ссылкой. Минус 1 балл
3. Для section.intro зачем-то прописан padding-top: 199px. Если бы его не было, было бы совпадение по ПП. Минус 2 балла
4. Пять ошибок при проверке через валидатор. Минус 1 балл
