### ISSUE TITLE
Cross-Check Singolo - daklin2

### ISSUE THREAD

**Issue by daklin2** [rolling-scopes-school/support#21]
Ссылка на деплой вашего проекта: https://daklin2.github.io/singolo/

Ссылка на репозиторий с проектом на GitHub: https://github.com/daklin2/singolo

Оценка в результате самопроверки, с ее аргументацией: 100 - 97 баллов(не валидировал только имя в форме, не понял нужно это или нет, и если да, то от чего избавляться... но, оба поля помечены как обязательные. возможно -3 за этот пункт)

Балл за cross-check из вашего Score: 82

**1 отзыв**
Ваша оценка - 81 баллов

1) В коммитах, или в ветках с коммитами, файлы singolo3.html и singolo3.сss или index.html и style.css отсутствуют до 09.03.2020: минус -10 баллов
 *Все дедлайны есть*

(рылся по всем папкам и веткам но кроме как index.html и style.css нету ничего, хотя должны быть singolo1,singolo2

2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла 
*отличается местами текст, а не логические контейнеры для него.*

3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла 
*отличается местами текст, а не логические контейнеры для него.*

4) Не выполняется валидация обоих полей ввода с отметкой Required в макете, или указан неправильный тип "< input >", или отсутствуют необходимые атрибуты, или при пропуске/вводе невалидных значений форма отправляется без ожидаемых замечаний: минус -3 балла (нет валидации name)
*тут наверно могу согласится, не знаю по заданию от чего валидировать name*

**2 отзыв**
Ваша оценка - 64 балла 

Отзыв по пунктам ТЗ:

1) В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020: минус -10 баллов 
 *Все дедлайны есть*

2) В коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020: минус -10 баллов 
 *Все дедлайны есть*

3) В коммитах, или в ветках с коммитами, файлы singolo3.html и singolo3.сss или index.html и style.css отсутствуют до 09.03.2020: минус -10 баллов 
 *Все дедлайны есть*

4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла 
*отличается местами текст, а не логические контейнеры для него.*

5) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла 
*отличается местами текст, а не логические контейнеры для него.*

**Comment by xmelsky** [comment]
under review

**Comment by xmelsky** [comment]
Оценка - 99. 
В поле textarea для placeholder'а (секция Get a Quote) не подключился правильный шрифт (Lato).
Отзыв: работа выполнена отлично. Есть только один момент. если в секции About Us в после с именем Desmond Miles вписать другую фамилию, например Desmond Milestone - то в результате вашего подхода Desmond останется вообще без фамилии. Технически это ошибка, но не подпадает под условия ТЗ (_текст видимым образом выходит за пределы строки блока или переносится на следующую строку_). Поэтому баллы не снимаются. В остальном претензий нет. 
По поводу валидации поля name: валидация форм это вообще отдельный топик. По условиям ТЗ достаточно было использовать только встроенную проверку на required и валидного email Использование pattern не требовалось. Понятно, что это очень слабая проверка и по-хорошему полная валидация должна проходить на сервере. И даже поля с pattern можно легко обойти просто направив запрос серверу с нужными полями формы, создав их вручную. минуя валидацию формы вообще. Так что у вас это не ошибка на данном этапе.
