### ISSUE TITLE
Cross-Check "Wild Life" -MalikImansaparov

### ISSUE THREAD

**Issue by MalikImansaparov** [rolling-scopes-school/support#210]
Deploy: https://rolling-scopes-school.github.io/malikimansaparov-JSFE2021Q1/wildlife/
Github: https://github.com/rolling-scopes-school/malikimansaparov-JSFE2021Q1/tree/wildlife
Task: https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/wildlife
Check form: https://wildlife-cross-check.netlify.app/
![Screenshot (31)](https://user-images.githubusercontent.com/50579392/111912654-cf247d00-8a94-11eb-80d9-257b1a801ab2.png)

Self-check 50/50 
1 Блок Header +10
* [x]  Блок Header содержит только логотип и панель навигации. Наличие 
* [x]  Логотип содержит два элемента - svg-иконку и текст. 
* [x]  На странице обязательно должен присутствовать один элемент <h1>
* [x]  Панель навигации состоит из четырёх элементов: двух ссылок, иконки поиска и кнопки "Sign in" . Верстается в виде ненумерованного списка: ul > li > a
* [x]  Все элементы панели навигации должны быть интерактивными
2. Блок Survival +10
* [x]  Расстояние между буквами заголовка регулируется css-свойством letter-spacing
* [x]  Разрывы строк в текстовом блоке регулируются шириной блока без использования тега <br>
* [x]  Кнопка Donate интерактивная. Используются указанные в макете стили для различных состояний кнопки
* [x]  У блоков Header и Survival общее фоновое изображение
3. Блок Latest articles +10
* [x]  Для вёрстки трёх изображений в ряд лучше использовать flexbox или grid. 
* [x]  Надписи поверх изображений можно разместить при помощи абсолютного позиционирования. 
* [x]  Стрелки слайдера интерактивны.
4. Блок Get notified +10
* [x]  Для отправки данных используется тег <form>
* [x]  Поле email верстается тегом <input> с типом text или email (оба варианта допустимы), поле send верстается тегом <input> с типом submit
* [x]  Надпись 'email' это placeholder.
5. Блок Footer +10
* [x]  Блок Footer содержит логотип, дополнительную панель навигации и ссылки на социальные сети
* [x]  Логотип полностью повторяет логотип блока Header. Речь о визуальном сходстве, а не использовании точно таких же тегов
* [x]  Дополнительная панель навигации и ссылки на социальные сети верстаются в виде ненумерованных списков: ul > li > a
* [x]  Иконки социальных сетей верстаются с использованием svg-файлов в качестве фоновых изображений
* [x]  Все ссылки в футере должны быть интерактивными
Score cross-check 42.4

Прошу работу перепроверить и выставить честную оценку, так как считаю текущую неправильной.
Буду очень благодарен. Спасибо.

**Comment by valerydluski** [comment]
У вас оценка за cross-check 50 баллов

**Comment by MalikImansaparov** [comment]
Аа запутался  😃
Спасибо!!!
