### ISSUE TITLE
Cross-Check "virtual-piano" - Satlykov

### ISSUE THREAD

**Issue by Satlykov** [rolling-scopes-school/support#211]
Ссылка на деплой вашего проекта. https://rolling-scopes-school.github.io/satlykov-JSFE2021Q1/virtual-piano/
Ссылка на репозиторий с проектом на GitHub. https://github.com/rolling-scopes-school/satlykov-JSFE2021Q1/tree/virtual-piano
Ссылка на задание.  https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/js-projects/virtual-piano
Ссылка на форму для проверки проекта (если такая есть). https://virtual-piano-cross-check.netlify.app/
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты). 
https://disk.yandex.uz/i/FOnTmysW6mqOhQ
https://disk.yandex.uz/i/1GqqWOoZQCulNw
Оценка в результате самопроверки с ее аргументацией. 
(Изначально оценил себя в 50 балов, не учитывая несколько имеющихся багов, но скорее всего моя оценка близка к оценки первых двух студентов). Моя главная проблема в тома что я в место ссылки на деплой сабмитнул ссылку на пул рэквест с самооценкой. Два из четырех студентов из-за этого не оценили мою работу при этом не оставили свои контакты что бы я мог с ними связаться. Помогите пожалуйста либо не учесть оценку двух последних студентов либо связаться с ними что бы предоставить ссылку на деплой.
Балл за cross-check из вашего Score. Сейчас в Score у меня 0.

Буду благодарен за понимание и благополучное решение вопроса, спасибо!

**Comment by valerydluski** [comment]
Cross-check ещё не завершён.
