### ISSUE TITLE
Cross-Check 'virtual-piano' - ilyBreathless

### ISSUE THREAD

**Issue by ilyBreathless** [rolling-scopes-school/support#212]
1.https://rolling-scopes-school.github.io/ilybreathless-JSFE2021Q1/virtual-piano/
2.https://github.com/rolling-scopes-school/ilybreathless-JSFE2021Q1/tree/virtual-piano
3.https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/js-projects/virtual-piano
4.https://virtual-piano-cross-check.netlify.app/
5.
![image](https://user-images.githubusercontent.com/72036113/112455190-8ad1ff00-8d6a-11eb-856c-69b0646a644b.png)
![image](https://user-images.githubusercontent.com/72036113/112455267-9c1b0b80-8d6a-11eb-9529-d42720a06411.png)
![image](https://user-images.githubusercontent.com/72036113/112455312-a89f6400-8d6a-11eb-898d-6cad55bad6fd.png)
6.Задание полностью удовлетворяет требованиям. Оценка 50/50 , что соответствует проверки 2/3 студентов .  Один студент поставил 30 баллов с совершенно несуществующими ошибками, которые он указал.  В следствие чего я получил в Score 43 балла.
7.
![image](https://user-images.githubusercontent.com/72036113/112455957-48f58880-8d6b-11eb-922e-5e87cdc77296.png)

**Comment by valerydluski** [comment]
Оценка в score 50 баллов.

**Comment by ilyBreathless** [comment]
Да, проверил 4-ый студент. Поэтому 50 зачло и 4ый не учитывался. Спасибо.
