### ISSUE TITLE
Cross-Check "virtual-piano" - AnnaLoft

### ISSUE THREAD

**Issue by AnnaLoft** [rolling-scopes-school/support#214]
1. Ссылка на деплой: 
https://rolling-scopes-school.github.io/annaloft-JSFE2021Q1/piano/

2. Ссылка на репозиторий с проектом на GitHub:
https://github.com/rolling-scopes-school/annaloft-JSFE2021Q1/tree/virtual-piano

3. Ссылка на задание:
https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/js-projects/virtual-piano

4. Ссылка на форму для проверки проекта (если такая есть):
https://virtual-piano-cross-check.netlify.app/

5. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты):
https://disk.yandex.ru/i/5c7ASC-EjeSwRw

6. Оценка в результате самопроверки с ее аргументацией: 
Считаю, что с учетом всех недоработок, работа заслуживает, как минимум, 38 баллов, поскольку баллы были снижены за следующие выполненные (полностью или частично) пункты:
- нажатие с клавиатуры работает, хоть и только на английской расскладке (в отзыве указано, что вообще не работает :() 
-  проигрывание с зажатой лкм работает корректно (в отзыве указано, что не также это не выполняется)
- некоторые комментарии я не доконца поняла, поскольку формулировка очень обтекаема.

В итоге, после самопроверки по форме имеем следующее:

Ваша оценка - 37.5 баллов 

Частично выполненные пункты:
a) при клике по клавише пианино мышкой клавиша переходит в активное состояние 
b) при клике по клавише клавиатуры, которая соответствует клавише пианино, проигрывается нота 
c) при клике по клавише клавиатуры, которая соответствует клавише пианино, клавиша пианино переходит в активное состояние 
d) можно провести курсором мышки с зажатой левой кнопкой по клавишам пианино, при этом клавиши, над которыми в данный момент находится курсор, переходят в активное состояние 
e) активное состояние клавиш пианино и соответствующих им букв или нот по стилю отличается от и неактивного состояния и состояния при наведении 

Выполненные пункты:
a) при клике по клавише пианино мышкой проигрывается соответствующая этой клавише нота 
b) можно провести курсором мышки с зажатой левой кнопкой по клавишам пианино, при этом будут проигрываться соответствующие данным клавишам ноты 
c) при клике по переключателю Notes/Letters сменяется отображение возле клавиш пианино названий соответствующих этим клавишам нот или букв 
d) активное и неактивное состояние кнопок переключателя отличаются по стилю 
e) реализована функциональность кнопки Fullscreen, которая позволяет развернуть приложение во весь экран, выйти из полноэкранного режима, в полноэкранном режиме взаимодействует с клавишей Esc клавиатуры 

6. Балл за cross-check из вашего Score: 
35 баллов

**Comment by valerydluski** [comment]
Апелляция рассматривается только если ожидаемый вами балл и полученный по результатам cross-check проверки средний балл отличаются на 15 и более процентов.
