### ISSUE TITLE
Cross-Check online-zoo George Washington

### ISSUE THREAD

**Issue by geowashto** [rolling-scopes-school/support#216]
1. https://rolling-scopes-school.github.io/geowashto-JSFE2021Q1/online-zoo/
2. https://github.com/rolling-scopes-school/geowashto-JSFE2021Q1/tree/online-zoo/online-zoo
3. https://github.com/rolling-scopes-school/stage0/blob/master/stage1/tasks/online-zoo/variant-5.md
4. Ребята, сорри, но забросил свой вариант 5 на проверку в группу варианта 2. Засабмитил до дедлайна, но была ночь - не лучшее время для внимания, почему то подумал, что v-2 - это вторая неделя,:) Естественно, что от проверяющих пришли нули. Жаль недельного труда. Можно ли до окончания дедлайна Кросс-чека дать эту работу на проверку учащимся из моего варианта? Спасибо за любые предложения в дискорд, или мейлом geowashto@gmail.com
5

**Comment by valerydluski** [comment]
Не попадает, под возможные варианты для подачи апелляций
