### ISSUE TITLE
Cross-Check Сlean-code-s1e1 - mayerror

### ISSUE THREAD

**Issue by mayerror** [rolling-scopes-school/support#217]
https://mayerror.github.io/clean-code-s1e1/
https://github.com/mayerror/clean-code-s1e1
https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/clean-code/clean-code-s1e1
https://rolling-scopes-school.github.io/checklist/
![FireShot Capture 024 - App _ The Rolling Scopes School - app rs school](https://user-images.githubusercontent.com/76498266/114263315-66725580-99ed-11eb-8c14-699a82b4ebd4.png)
Оценка в результате самопроверки: 45 / 45
Все пункты были выполнены. 
Комментарии по поводу штрафа  "Коммит содержит изменения по нескольким правилам, НЕ перекрывающим друг друга."
Если вы посмотрите, на коммит 2.1 именно он полностью содержит все изменения согласно требованиям по пункту 2.1. В коммите 1.1 действительно появились отступы, это из-за моего неоднозначного понимания пункта, все таки первый пункт задания, первый коммит.  Касательно, коммита 3.5 и 3.6, опять же история идет к коммиту 1.1 в котором я изменяя 4 пробела на 2, фактически закрыл требования по 3.5, соответсвенно пришлось изобретать велосипед чтобы создать эти коммиты. 
Итог: считаю несправедливым снятие почти половины баллов -20 Student 1, за мое неоднозначное понимание требования 1 пункта задания, что повлияло на некоторые следующие пункты. Возможно если бы было 4 оценки, она бы отсеялась, но увы, только 2 оценки.
Балл за cross-check из Score: 34

**Comment by diman17** [comment]
Оценка: 25 / 45
коммит 'refactor: add missing indents according to rule 3.5 in html-and-css.md' содержит изменения по нескольким правилам, НЕ перекрывающим друг друга (-20), а именно: 
3.6 Пробел после названий свойств
3.8 Разделение селекторов и свойств
![Скриншот 10-04-2021 233800](https://user-images.githubusercontent.com/42317715/114284212-087a5800-9a57-11eb-859a-455e177be88d.jpg)
