### ISSUE TITLE
Cross-Check Singolo - kejno

### ISSUE THREAD

**Issue by Kejno** [rolling-scopes-school/support#22]
Ссылка на деплой вашего проекта: https://kejno.github.io/singolo/

Ссылка на репозиторий с проектом на GitHub: https://github.com/Kejno/singolo

Оценка в результате самопроверки, с ее аргументацией: 97 баллов.
В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт

Балл за cross-check из вашего Score:

Student 1
Ваша оценка - 74 балла 

Отзыв по пунктам ТЗ:

В Firefox есть сильное отклонение (т.е. бросается в глаза) от той же страницы, открытой в Google Chrome: минус -5 баллов
**Я проверял на firefox, все идеально. Студент 2 поставил мне 97 и не увидел расхождения и несоответствия более ,чем в 2px ** 

Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла 
**Нет у меня расхождений по макету+ второй проверяющий этого тоже не увидел и поставил 97 баллов**

Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Portfolio составляют более двух пикселей (2px): минус -3 балла 
**Нет у меня расхождений по макету+ второй проверяющий этого тоже не увидел и поставил 97 баллов**

Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла 
**Нет у меня расхождений по макету+ второй проверяющий этого тоже не увидел и поставил 97 баллов**

Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Form составляют более двух пикселей (2px): минус -3 балла 
**Нет у меня расхождений по макету+ второй проверяющий этого тоже не увидел и поставил 97 баллов**

Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Footer составляют более двух пикселей (2px): минус -3 балла 
**Нет у меня расхождений по макету+ второй проверяющий этого тоже не увидел и поставил 97 баллов**

Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify в секции Form: минус -3 балла 
**Во всех секциях я использовал text-align: justify и это видно по соответствию текста с макетом**

**Comment by Sannnao** [comment]
У меня тоже несоответствия, но эта частая проблема в зависимости от непонятно чего.
 По функционалу только -3 за оферфлоу текста
Предварительная оценка 97

**Comment by Kejno** [comment]
Конечно, локально все соответствует макету. Если бы во время работы с Синголо было отклонение, я бы его исправил. Тем более у другого проверяющего проблем и вопросов с мой макетом не было. Единстенное, за что сняли -3 , это за показ избыточного текста.

**Comment by amoebiusss** [comment]
@Sannnao привет, какой статус по этой апелляции?

**Comment by Sannnao** [comment]
> @Sannnao привет, какой статус по этой апелляции?

Изменили ведь подход к выставлению оценок, где худший результат откидывается. Разве нет?

**Comment by amoebiusss** [comment]
@Kejno окей, значит этот ишью нужно закрыть
