### ISSUE TITLE
Cross-check 'online zoo' - VanWilder199

### ISSUE THREAD

**Issue by VanWilder199** [rolling-scopes-school/support#220]
1.Deploy: https://rolling-scopes-school.github.io/vanwilder199-JSFE2021Q1/online-zoo/pages/MainLending/
2.Repository: https://github.com/rolling-scopes-school/vanwilder199-JSFE2021Q1/tree/online-zoo
3.Task: https://github.com/rolling-scopes-school/stage0/blob/master/stage1/tasks/online-zoo/variant-2.md
4.Check:  https://github.com/rolling-scopes-school/stage0/blob/master/stage1/tasks/online-zoo/variant-2.md там же внизу
5.Screenshot: 
![online zoo](https://user-images.githubusercontent.com/72692962/114264982-d20cf080-99f6-11eb-937e-7f8deb4bc32d.png)
My estimation: 72 
Отвалились картинки животных в сайд баре
Не все блоки вписываются в 20px
Студент 2 : 
отсутствуют страницы других животных - 30. Страницы были, на них можно перейти через страницу map. Не добавил изначально ссылки в сайд баре. (после этого студента добавил ссылки в сайд баре, чтобы другие не поставили тоже самое).
При этом в условиях на оценку не указано что кнопки по сайд бару должны вести на другие страницы 
Score 47 из 80

Студент podlesskiyi: 
work done very  well. found no errors 
Score 50 из 80
Прошу дать ему предупреждение.

**Comment by valerydluski** [comment]
Есть коммиты после дедлайна
