### ISSUE TITLE
Cross-Check 'online-zoo' - casper992

### ISSUE THREAD

**Issue by casper992** [rolling-scopes-school/support#223]
доброго времени суток, уважаемые "наставники"
https://rolling-scopes-school.github.io/casper992-JSFE2021Q1/online%20zoo/ деплой
https://github.com/rolling-scopes-school/casper992-JSFE2021Q1/tree/gh-pages
https://github.com/rolling-scopes-school/stage0/blob/master/stage1/tasks/online-zoo/variant-2.md  (формы для проверки нет, критерии оценок идут после задания)

![score](https://user-images.githubusercontent.com/60609364/114270310-53bf4700-9a14-11eb-9f40-92de2daad40a.png)

по самопроверке:  не согласен с проверяющими за снижение балов за страницу: contakt us из за одного свойства: margin: 0 auto; для экрана 1920px выставлено всё отлично, согласно задания, не моя вина, что у проверяющего разрешение монитора больше.  и ещё бесит, когда снимают балы, а за что, не пойми, не первый раз сталкиваюсь, когда проверяющий ставит не по критериям оценок а сугубо столько, сколько хочется ему!
свою работу оцениваю в +-75 балов 

спасибо за проделанную работу, добра!

**Comment by valerydluski** [comment]
Есть коммиты после дедлайна

**Comment by casper992** [comment]
Commits on Apr 7, 2021 мой последний коммит дедлайн был до 9 числа

**Comment by casper992** [comment]
> Есть коммиты после дедлайна

Commits on Apr 7, 2021 мой последний коммит дедлайн был до 9 числа

**Comment by valerydluski** [comment]
Дедлайн был 5-го апреля
