### ISSUE TITLE
Cross-Check 'online-zoo' - AlionaMu

### ISSUE THREAD

**Issue by AlionaMu** [rolling-scopes-school/support#224]
1. Deploy: https://rolling-scopes-school.github.io/alionamu-JSFE2021Q1/online-zoo/pages/landing/
2. Repo: https://github.com/rolling-scopes-school/alionamu-JSFE2021Q1
3. Task: https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-4
4. Cross-check form: https://sergeyshalyapin.github.io/cross-check/index.html
5. 
![image](https://user-images.githubusercontent.com/34584155/114270617-0d6ae780-9a16-11eb-82a3-51ffc3426c3a.png)
![image](https://user-images.githubusercontent.com/34584155/114270624-1a87d680-9a16-11eb-8e6c-6a4f799ef858.png)
6. Self-assessment: 74
  ( Хочу обратить внимание, что Student3 снял 26 баллов за якобы неподключенные шрифты, которые на самом деле подключены. И так как мою работу проверили только 3 студента, то оценка данного студента критично повлияла на окончательную оценку)
7. Score: 57

**Comment by dzevakov** [comment]
Score: 69
## Landing
### Header
- Design не работает как ссылка на оригинальную страницу Figma: -1.
### Pets in zoo
- Нажатие на карточку животного из перечня не ведет на страницу соответствующего животного: -1 за весь блок.
- (Скейл карточек при ховере не соответствует ТЗ)
### Footer
- Отступы от границ элементов (или наборов элементов) до краев блока, по горизонтали или вертикали, отличаются более чем на 20px: -1
## Map
### Footer
- Отступы от границ элементов (или наборов элементов) до краев блока, по горизонтали или вертикали, отличаются более чем на 20px: -1
## Zoos
### Footer (x3 pages)
- Contact Us не работает как ссылка на Error 404: -1.
### Footer (x4 pages)
- Отступы от границ элементов (или наборов элементов) до краев блока, по горизонтали или вертикали, отличаются более чем на 20px: -1
## 404
- Go back and try a different link не работает как ссылка на Landing: -1.
### =====================================
В целом в верстке много не соответствий с макетом выражающихся в несоответствии размеров тултипов, расположения текста внутри них, расположения элементов внутри блоков на всех страницах, но не превышающих отклонение в 20рх допустимых согласно ТЗ.
