### ISSUE TITLE
Cross check "Online-zoo v2" - Serhii - (seven8959)

### ISSUE THREAD

**Issue by seven8959** [rolling-scopes-school/support#225]
1. https://rolling-scopes-school.github.io/seven8959-JSFE2021Q1/online-zoo/
2. https://github.com/rolling-scopes-school/seven8959-JSFE2021Q1/tree/online-zoo
3. https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/online-zoo
4. https://sergeyshalyapin.github.io/cross-check/index.html
5. 
![Screenshot_1](https://user-images.githubusercontent.com/67795802/114273819-43af6380-9a24-11eb-9373-c38eb2c09a7a.png)
6. 80, все пункты выполнил, как указано в задании, так же все проверки на pixel perfect выполнил. Единственное - это изначально в условии для всех страниц кроме landing, в футере лого должно было быть не интерактивным, и не перебрасывать на landing page. А когда появились требования для проверки задания, то там лого в футере должно было быть интерактивным на всех страницах. Но я сдал работа, до того как это увидел, и в итоге ничего не менял. 
  Так же у меня на данный момент есть коммиты после дедлайна, но это коммиты уже для адаптива. А ссылка на дэплой, старая. там еще нет адаптива. 
7. 
![Screenshot_2](https://user-images.githubusercontent.com/67795802/114273996-2333d900-9a25-11eb-9aa4-1fdb6a17f6f3.png)

**Comment by diman17** [comment]
Оценка: 79/80
Отличная работа, единственное на страницах с животными в header верхний паддинг 49px, а должен быть 30px, и еще на странице с пандой в .plug-text нужно обнулить letter-spacing
