### ISSUE TITLE
Cross check "Clean-code-s1e1" - iusmanof - (Ihar Usmanau(@iusmanof))

### ISSUE THREAD

**Issue by iusmanof** [rolling-scopes-school/support#226]
1. Deploy: https://iusmanof.github.io/clean-code-s1e1/
2. Repo: https://github.com/iusmanof/clean-code-s1e1
3. Task: https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/clean-code/clean-code-s1e1
![Новый точечный рисунок](https://user-images.githubusercontent.com/74846667/114285865-0e763600-9a63-11eb-97e0-67aa911b0bc1.png)
![Новый точечный рисунок](https://user-images.githubusercontent.com/74846667/114317672-eb568f80-9b11-11eb-8801-80c1a66f4ded.png)

6. Self-assessment: 43
( Хочу обратить внимание, что Student1 неправильно подсчитал баллы. И мою работу  оценило мало людей)
7. Score: 20

**Comment by iusmanof** [comment]
cross check

**Comment by valerydluski** [comment]
Неправильное оформление.

**Comment by valerydluski** [comment]
и скриншот нужен всех оценок, а не одной

**Comment by iusmanof** [comment]
Исправил ссылку 
Добавил скриншоты

**Comment by Akisole** [comment]
## TLDR: 0 баллов.

# Первичная оценка работоспособности приложения
Как видно из скрина - внешний вид приложения изменился.

![изображение](https://user-images.githubusercontent.com/32121754/114597406-6bf3c800-9c99-11eb-813b-9ddeff12b48e.png)

Это подпадает под штрафной пункт 
> Работа с невыполненным обязательным требованием задания "Весь функционал приложения должен исправно работать после ваших изменений (_-45 баллов_)"
![изображение](https://user-images.githubusercontent.com/32121754/114598777-f557ca00-9c9a-11eb-9916-5ebd85f308a9.png)

Несмотря на это - рассмотрим остальные моменты проверки.

# Проверка согласованности с руководствами 

    - Не выполнен пункт 1.2 начального уровня
![изображение](https://user-images.githubusercontent.com/32121754/114586447-57a9ce00-9c8d-11eb-85f7-4552227f2dc1.png)

    - Не выполнен пункт 2.1 начального уровня [1 отступ = 2 пробела]
![изображение](https://user-images.githubusercontent.com/32121754/114587001-e6b6e600-9c8d-11eb-90f3-be0f4aedaa52.png)

    - Не выполнен пункт 2.4 начального уровня
Используется атрибут `type` для подключения стилей и скриптов

    - Не выполнен пункт 3.4 начального уровня
Неоднократно используются теговые селекторы не для сброса дефолтных стилей, а для их переопределения

    - Не выполнен пункт 3.5 начального уровня
![изображение](https://user-images.githubusercontent.com/32121754/114589347-41514180-9c90-11eb-8eca-2fd306fe45d2.png)

    - Частично выполнен пункт 1.1 продвинутого уровня
Каждый элемент [`<section>`](https://developer.mozilla.org/ru/docs/Web/HTML/Element/section#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D0%B5), [`<article>`](https://developer.mozilla.org/ru/docs/Web/HTML/Element/article#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D0%B5) должен быть идентифицирован, обычно путём добавления заголовка в качестве дочернего элемента. 

    - Не выполнен пункт 1.2 продвинутого уровня
В ходе работы с приложением отсутствует атрибут `alt`
![изображение](https://user-images.githubusercontent.com/32121754/114591045-21228200-9c92-11eb-9679-24f9c9ebe2bc.png)

    - Не выполнен пункт 2.1 продвинутого уровня
БЭМ частично выполнен на инициализированных "задачах" приложения, при добавлении новых компонент - БЭМ-именованные классы не используются, применяется изначально существующее именование (классы `task`, `edit`, `delete`). Таким образом так же введенные новые классы практически не несут никакого смысла, т.к. дублируют изначальные.
Так же есть "не подцепленные" к блоку некоторые элементы (будь там вместо `id` - `class` было бы хорошо) [[линк](https://yoksel.github.io/html-tree/)]
![изображение](https://user-images.githubusercontent.com/32121754/114595226-d0615800-9c96-11eb-954a-0c4f824b9398.png)

##
## Подытог: 22.5 балла.

## Штрафные баллы
Присутствуют замечания к коммитам по пунктам _Коммиты содержат изменения по нескольким правилам, НЕ перекрывающим друг друга_ и _Формат коммит сообщений составлен вразрез указаным в задании требованиям_

Например:
 - [Пересечение](https://github.com/iusmanof/clean-code-s1e1/commit/a37aeb78bbe31ceae7c3671e13d12b917ee3ce9b) пунктов 1.2 продвинутого уровня (альтернатива мультимедия) **И** 2.1 начального уровня (форматирование html) **c** 2.5 начального уровня (разбиение длинных строк);
 - [Коммит](https://github.com/iusmanof/clean-code-s1e1/commit/ef1f6f0413c6dbe7d5244354bf5c272fd920e62c) содержит изменение по одному из пунктов. Изменение не отражено в названии коммита
#
# Итог
**С** учетом визуального различия или **без**: 0 баллов

**Comment by iusmanof** [comment]
Спасибо за оценку

чт, 15 апр. 2021 г. в 16:55, Valery ***@***.***>:

**Comment by iusmanof** [comment]
А можно ли исправить оценку ?

пт, 16 апр. 2021 г., 5:48 Igor Usmanov ***@***.***>:

**Comment by valerydluski** [comment]
А что с ней?

сб, 17 апр. 2021 г., 20:30 iusmanof ***@***.***>:

**Comment by iusmanof** [comment]
Стало 0.

сб, 17 апр. 2021 г. в 21:13, Valery ***@***.***>:

**Comment by valerydluski** [comment]
Всё верно, работу оценили в 0 баллов
