### ISSUE TITLE
Cross check "Online-zoo-v-2" - "Masterofonion"

### ISSUE THREAD

**Issue by Masterofonion** [rolling-scopes-school/support#227]
1. https://rolling-scopes-school.github.io/masterofonion-JSFE2021Q1/online-zoo/Pages/index.html
2. https://github.com/rolling-scopes-school/masterofonion-JSFE2021Q1 (последний коммит сделан 6 апреля по UTC +3 в 00-05, то есть в 21-05 по обычному UTC, по которому был дедлайн на 23-59) 
3. https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-2
4. Формы нет, вроде как(
5. 
![Снимок экрана 2021-04-11 в 01 59 04](https://user-images.githubusercontent.com/79205849/114286794-94e24600-9a6a-11eb-8fd0-6944897306fb.png)
6. Рассчитываю на оценку  около 80 баллов. Претензии по поводу отсутствующих страниц неоправданны, переход можно совершить кликнув по карточкам в лендинге или зайти на страницу Панды кликнув по zoo и изменить название  panda  на необходимое(lemur, gorilla, eagle). Валидность не учитывается при выставлении баллов. Это первая оценка. По второй оценке - h1 должен находиться не в хедере, а в любом месте на странице, на всех страницах он присутствует, претензия по отсутствию страниц снова неоправданна. Сейчас нахожусь не дома, открыл свою страницу на маке в девтулз, отзывы по-прежнему не выходят за границу 1920 пикселей. Третья оценка - в задании указано, что карточка должна быть интерактивной и что у нее должна быть анимация расширения в стороны на 20 пикселей, все это присутствует в макете. Наличие кнопки на карточке не прописано в задании, в моем понимании это надпись, тк по заданию клик по любой области карточки и так ведет на соответствующую страницу, то есть карточка и так уже является кнопкой и зачем на ней еще одна кнопка выполняющая ту же функцию мне не ясно. Это касается обоих минусов за карточки. Последний минус уже на усмотрение, но в целом по заданию прописана интерактивность и она присутствует на ссылках VIEW MAP и не только курсор: поинтер. Заранее спасибо проверяющему, если таковой найдется, не важно, если вдруг будут какие-то новые косяки и балл будет еще ниже, но хочется справедливости, а не пофигистичной проверки. 
7. 62 балла - оценка за кроссчек попавшая в скор.

**Comment by spherical-horse** [comment]
Ваша оценка - 73 балла

Шрифт или семейство шрифтов не подключено (Montserrat не загружен, показывается fallback sans-serif): -1 балл. И так на каждой странице (всего 4 типа страниц)

Landing:
В блоке Pay and Feed отличие от макета 77 px -1 балл

Contact Us:
В блоке Contact Us отличие от макета 110px -1 балл

Zoos Page:
В блоке Did you know отличия от макета 35px -1 балл
