### ISSUE TITLE
Cross check "Online-zoo v1" - BedrickijV

### ISSUE THREAD

**Issue by BedrickijV** [rolling-scopes-school/support#228]
1. https://rolling-scopes-school.github.io/bedrickijv-JSFE2021Q1/online-zoo/
2. https://github.com/rolling-scopes-school/bedrickijv-JSFE2021Q1/tree/online-zoo/online-zoo
3. https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/online-zoo
4. https://sergeyshalyapin.github.io/cross-check/index.html
5. 
![issue](https://user-images.githubusercontent.com/50704137/114300632-f2f24600-9ac9-11eb-921f-b2fe0190511e.jpg)
6. Оценка по результату самопроверки - 79, выполнены все пункты согласно ТЗ, за исключением наличия рамки на активном животном на странице ZOO. 
7. 53/80 - данная оценка получилась так как меня проверили 3 человека и одному из них попался не тот вариант который он делал, следовательно согласно написанному в анонсах - он мне поставил 0. А так как если проверили менее 4 людей - все оценки идут в зачёт - то получилось 80+79+0 = 53.

**Comment by valerydluski** [comment]
Ваша оценка 79 баллов
