### ISSUE TITLE
Cross-Check online-zoo - yura-yushkevich

### ISSUE THREAD

**Issue by Yura-Yushkevich** [rolling-scopes-school/support#231]
Ссылка на деплой - https://rolling-scopes-school.github.io/yura-yushkevich-JSFE2021Q1/online-zoo/pages/landing/index.html
Ссылка на репозиторий с проектом на GitHub - https://github.com/rolling-scopes-school/yura-yushkevich-JSFE2021Q1/tree/online-zoo
Ссылка на задание - https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-6
Ссылка на форму для проверки проекта (если такая есть).
Скриншот с оценками за cross-check - http://joxi.ru/823zMq4iaqbBYm.
Балл за cross-check из Score - 73.

**Comment by valerydluski** [comment]
Коммиты после дедлайна
