### ISSUE TITLE
Cross-Check online-zoo-v3 - FazylovAsylkhan

### ISSUE THREAD

**Issue by FazylovAsylkhan** [rolling-scopes-school/support#232]
1. Ссылка на деплой - https://rolling-scopes-school.github.io/fazylovasylkhan-JSFE2021Q1/online-zoo/pages/landing/
2. Ссылка на репозиторий с проектом на GitHub - https://github.com/rolling-scopes-school/fazylovasylkhan-JSFE2021Q1/tree/online-zoo
3. Ссылка на задание - https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-3
4. Ссылка на форму для проверки проекта (если такая есть).
5. Скриншот с оценками за cross-check -  http://dl4.joxi.net/drive/2021/04/12/0043/3410/2825554/54/d25c4d61c0.png
6. Аргументация против оценки 43: 
Ошибка допущенная мной имеет место быть(нет якорной ссылки в меню подвала), но за нее снято слишком много - 30 баллов.
Ошибка в критерии оценки была допущена - сам автор таска подтвердил (со слов Иры).
Скрин из переписки: http://joxi.ru/5md9G8Yi8y9lR2. 
7. Балл за cross-check из Score - 67.
Благодарю за внимание.

**Comment by valerydluski** [comment]
Коммиты после дедлайна
