### ISSUE TITLE
Cross-Check 'online-zoo. week#3-4 v3' - 'IMGarry'

### ISSUE THREAD

**Issue by IMGarry** [rolling-scopes-school/support#233]
1. Deploy: https://rolling-scopes-school.github.io/imgarry-JSFE2021Q1/online-zoo/pages/landing/
2. Репозиторий: https://github.com/rolling-scopes-school/imgarry-JSFE2021Q1/tree/online-zoo
3. Task: https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-3
4. Done 23.04.2021 / deadline 20.04.2021
5. Самооценка 40/40, адаптив сделан для всех разрешений на всех страницах. 

Добрый вечер. 
Прошу дать возможность получить оценку за работу. 
Опоздание связано с тем, что я находился в больнице с 13.04.2021 по 16.04.2021. 
Была проведена операция в плечевом суставе, удалено образование, которое вызывало компрессию нерва, и были постоянные боли и проблемы с рукой. 
На сегодняшний день швы еще не сняты, но двигательные функции восстанавливаются.

**Comment by valerydluski** [comment]
Удалите справку, оформите правильно название issue

**Comment by IMGarry** [comment]
Название оформил правильно, справку удалил.

**Comment by Akisole** [comment]
### TLDR: 22 балла.
## Landing
Landing на 640px: 
 - Отступы между логотипами в футере: -1.
 - Отступы между именами соцсетей в футере: -1.
 
Landing на 320px: 
 - Расположение элементов в блоке pay and feed: -1.
 - ❗ Не появилась карусель с иконками животных и стрелками, или нарушены отступы между элементами внутри: -1.
 
Проверяем на отзывчивость (Responsive):
 - В ходе изменения размера появляется горизонтальная полоса прокрутки: -4.
### Подытог: 7
## Map
### Подытог: 10
## Zoos
Zoos на 1200рх:
* Расположение элементов в блоке pay and feed: -1.

Проверяем на отзывчивость (Responsive):
* В ходе изменения размера появляется горизонтальная полоса прокрутки: -4.
### Подытог: 5
## Error 404
Error 404 на 1200рх:
* Расположение элементов и кнопки Back to main page в блоке Oops: -1.

Проверяем на отзывчивость (Responsive):
* В ходе изменения размера появляется горизонтальная полоса прокрутки: -4.
* Отсутствует хотя бы один элемент (кроме указанных или фоновых элементов), или есть лишний: -2. (логотип в хедере, изображения в футере)
### Подытог: 0
# Итог: 22
