### ISSUE TITLE
Cross-Check 'online-zoo-w-34-v-1' - 'g5-freemen'.

### ISSUE THREAD

**Issue by g5-freemen** [rolling-scopes-school/support#234]
https://rolling-scopes-school.github.io/g5-freemen-JSFE2021Q1/online-zoo/
https://github.com/rolling-scopes-school/g5-freemen-JSFE2021Q1/tree/online-zoo/online-zoo
https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-1?id=%d0%92%d0%b0%d1%80%d0%b8%d0%b0%d0%bd%d1%82-1
![image](https://user-images.githubusercontent.com/36886126/115937059-8e5ac200-a49f-11eb-9e6c-7b27e2b30720.png)
0 баллов по первой оценке

**Comment by valerydluski** [comment]
Есть коммиты после дедлайна, могу предположить, что человек выставлял оценку в первый день кросс-чек. И оставил контакты.
