### ISSUE TITLE
Cross-Check 'Online-zoo-w-34-v-6'-'Mustafina1990'

### ISSUE THREAD

**Issue by Mustafina1990** [rolling-scopes-school/support#235]
https://rolling-scopes-school.github.io/mustafina1990-JSFE2021Q1/online-zoo/pages/1600px/desktop-petstory/
https://github.com/rolling-scopes-school/mustafina1990-JSFE2021Q1/tree/online-zoo/online-zoo
https://github.com/rolling-scopes-school/stage0/blob/master/stage1/tasks/online-zoo/variant-6.md
https://sergeyshalyapin.github.io/cross-check/
![Submit](https://user-images.githubusercontent.com/71671138/115951379-2335dd80-a4e9-11eb-8c25-97662948e4ba.jpg)
Оценка в результате самопроверки с ее аргументацией: работа не проверялась другими студентами. Submit был сделан вовремя, после продления Submit ссылка исчезла, я повторно засабмитила в позволенное для этого время, всё прошло успешно, но после Submit мою работу не проверил не один студент и мне не пришло на проверку работ.
Балл за cross-check из вашего Score:  0

**Comment by mrstatic23** [comment]
Страница: Landing; Блок: 1000px; Отступы между элементами меню в хедере нарушены.
Страница: Landing; Блок: 1000px; Расположение элементов в блоке Watch your favorite animal online нарушено.
Страница: Landing; Блок: 1000px; Расположение элементов в блоке The Backstage нарушено.
Страница: Landing; Блок: 1000px; Расположение или отступы между кнопками вправо/влево в блоке Pets нарушены.
Страница: Landing; Блок: 1000px; Вид растений справа или слева в блоке Pets нарушен.
Страница: Landing; Блок: 1000px; Количество, расположение или отступы между отзывами в блоке Testimonials нарушены.
Страница: Landing; Блок: 1000px; Расположение кнопки leave feedback в блоке Testimonials нарушено.
Страница: Landing; Блок: 1000px; Вид растения справа в блоке Testimonials нарушен.
Страница: Landing; Блок: 1000px; Отступы между элементами меню в футере нарушены.

Страница: Landing; Блок: 640px; Хедер не стал фиксированным.
Страница: Landing; Блок: 640px; Расположение элементов в блоке Watch your favorite animal online нарушено.
Страница: Landing; Блок: 640px; Вид, расположение или отступы между отзывами в блоке Testimonials нарушены.
Страница: Landing; Блок: responsive; В ходе изменения размера появляется горизонтальная полоса прокрутки.

Страница: Map; Блок: 1000px; Хедер не тянется на всю ширину, или элементы хедера горизонтально не фиксированы, при наличии горизонтальной полосы прокрутки.
Страница: Map; Блок: 1000px; На карте исчезают иконки животных, или их позиция на карте сильно смещается, более чем на 30px.
Страница: Map; Блок: 1000px; Расположение элементов внутри формы Subscribe to our news в футере нарушено.
Страница: Map; Блок: 1000px; Расположение кнопки donate for volunteers в футере нарушено.

Страница: Map; Блок: 640px; Хедер не стал фиксированным.
Страница: Map; Блок: 640px; Не пропала форма Subscribe to our news в футере (она должна скрыться).
Страница: Map; Блок: 640px; Расположение кнопки donate for volunteers в футере нарушено.
Страница: Map; Блок: 640px; Расположение или отступы между иконками соцсетей в футере нарушены.
Страница: Map; Блок: 640px; Отступы между элементами меню в футере нарушены.

Страница Zoos Не cделана.

Страница Donate Не cделана.

Проверил работу. Оцена 1 балл

**Comment by Mustafina1990** [comment]
У меня блоки на 1000px - не содержат эти нарушения: 
Страница: Landing; Блок: 1000px; Отступы между элементами меню в хедере нарушены.
(разница по pixel perfect менее 10px) 
![image](https://user-images.githubusercontent.com/71671138/116907829-ca81e580-ac4a-11eb-9ee0-a2c303366ea5.png)

Страница: Landing; Блок: 1000px; Расположение или отступы между кнопками вправо/влево в блоке Pets нарушены.
Страница: Landing; Блок: 1000px; Вид растений справа или слева в блоке Pets нарушен.
(по этим пунктам тоже всё норм) 
![Online zoo - pets](https://user-images.githubusercontent.com/71671138/116907943-f8672a00-ac4a-11eb-9f94-11d681004307.jpg)
Страница: Landing; Блок: 1000px; Вид растения справа в блоке Testimonials нарушен.
(растение тоже на месте)
Страница: Landing; Блок: 1000px; Отступы между элементами меню в футере нарушены.
(в пределах 10px)
![Online zoo - footer](https://user-images.githubusercontent.com/71671138/116908122-36644e00-ac4b-11eb-997a-950108292679.jpg)

Страница: Map; Блок: 1000px; На карте исчезают иконки животных, или их позиция на карте сильно смещается, более чем на 30px.
![Map - animals](https://user-images.githubusercontent.com/71671138/116908831-09fd0180-ac4c-11eb-9676-8af5277959db.jpg)

(у меня всё норм)

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/116981886-cbf5f100-acd0-11eb-8c4a-d5e2f03a868b.png)
