### ISSUE TITLE
Cross-Check 'online-zoo. week#3&4-v-5' - 'VDudevich'.

### ISSUE THREAD

**Issue by VDudevich** [rolling-scopes-school/support#236]
1. Ссылка на деплой вашего проекта.
https://rolling-scopes-school.github.io/vdudevich-JSFE2021Q1/online-zoo/index.html
2. Ссылка на репозиторий с проектом на GitHub.
https://github.com/rolling-scopes-school/vdudevich-JSFE2021Q1/tree/online-zoo
3. Ссылка на задание.
https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-5?id=%d0%90%d0%b4%d0%b0%d0%bf%d1%82%d0%b8%d0%b2%d0%bd%d0%be%d1%81%d1%82%d1%8c-%d0%bd%d0%b5%d0%b4%d0%b5%d0%bb%d1%8f-3amp4
4. Ссылка на форму для проверки проекта (если такая есть).
https://sergeyshalyapin.github.io/cross-check/
5. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
![app rs school_course_student_cross-check-submit_course=js-fe-2021Q1](https://user-images.githubusercontent.com/22483740/115951975-f206de80-a4e3-11eb-8da3-ea58f6909d8f.png)
6. Оценка в результате самопроверки с ее аргументацией.
40, все пункты выполенны, включая фиксированные размеры и критерии проверки на респонсив.
7. Балл за cross-check из вашего Score.
27

**Comment by igorlyatskiy** [comment]
**Ваш балл: 35**

Страница: Landing; Блок: 1200px; На карте исчезают иконки животных, или их позиция на карте сильно смещается, более чем на 30px, в блоке Map. (карта искривлена, растянута непропорционально, иконки смещены)

Страница: Landing; Блок: 640px; На карте исчезают иконки животных, или их позиция на карте сильно смещается, более чем на 30px, в блоке Map:. (карта искривлена, растянута непропорционально, иконки смещены)

Страница: Landing; Блок: 320px; Расположение кнопки donate for volunteers в футере нарушено. (на этой и последующих страницах отклонение расположения кнопки от макета больше 10px)

Страница: Map; Блок: 320px; Расположение кнопки donate for volunteers в футере нарушено.

Страница: Zoos; Блок: 320px; Расположение кнопки donate for volunteers в футере нарушено.
