### ISSUE TITLE
Cross-Check 'online-zoo. week#3&4'-'Mayd1'

### ISSUE THREAD

**Issue by Mayd1** [rolling-scopes-school/support#238]
1. Ссылка на Deploy вашего проекта:
   https://rolling-scopes-school.github.io/mayd1-JSFE2021Q1/online-zoo/lending_pages/
2 .Ссылка на репозиторий с проектом на GitHub:
   https://github.com/rolling-scopes-school/mayd1-JSFE2021Q1/tree/online-zoo
3. Ссылка на задание:
   https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-1
4. Ссылка на форму для проверки проекта (если такая есть):
   https://sergeyshalyapin.github.io/cross-check/
5.Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты):
![image](https://user-images.githubusercontent.com/64355801/115991716-6cae2780-a5d2-11eb-9016-ad7fe8718929.png)
6.Оценка в результате самопроверки с ее аргументацией:
 25-30 баллов, все разрешения выполнены, да есть ошибки, но это никак не -30 баллов, которые мне поставили 
  анонимна 2 последних студента.
7.Балл за cross-check из вашего Score:
   14.

**Comment by valerydluski** [comment]
Есть коммиты после дедлайна

**Comment by Mayd1** [comment]
Так submit же был продлен на сутки

  
>Понедельник, 26 апреля 2021, 17:35 +03:00 от Valery ***@***.***>:
> 
> 
>Есть коммиты после дедлайна
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Петя Тишкевич

**Comment by valerydluski** [comment]
сабмит, но не дедлайн задания

**Comment by Mayd1** [comment]
блин, обидно, я не знал, думал одно подразумевает и другое, спасибо

  
>Понедельник, 26 апреля 2021, 21:42 +03:00 от Valery ***@***.***>:
> 
> 
>сабмит, но не дедлайн задания
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Петя Тишкевич
