### ISSUE TITLE
Cross-Check 'online-zoo. week#3&4-v-5' - 'xx3u'

### ISSUE THREAD

**Issue by xx3u** [rolling-scopes-school/support#239]
- Ссылка на деплой вашего проекта.
 https://rolling-scopes-school.github.io/xx3u-JSFE2021Q1/online-zoo/pages/about/about.html 
- Ссылка на репозиторий с проектом на GitHub.
https://github.com/rolling-scopes-school/xx3u-JSFE2021Q1/tree/online-zoo
- Ссылка на задание.
https://github.com/rolling-scopes-school/stage0/blob/master/stage1/tasks/online-zoo/variant-5.md
- Ссылка на форму для проверки проекта (если такая есть).
https://sergeyshalyapin.github.io/cross-check/
- Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
![image](https://user-images.githubusercontent.com/45433350/116035171-55c90d00-a686-11eb-826b-74ef22625ff2.png)
- Оценка в результате самопроверки с ее аргументацией.
36 -> В ходе изменения размера появляется горизонтальная полоса прокрутки: -4.
- Балл за cross-check из вашего Score.
28

**Comment by spherical-horse** [comment]
**Итого - 20 баллов**

**Landing(1200)**
1. Расположение карточек животных в блоке Watch your favorite animal online: -1.
2. Расположение элементов или вид стрелок в блоке Pay and feed: -1.
3. Расположение кнопки donate for volunteers в футере: -1.

**Landing(640)**
1. Расположение карточек животных в блоке Watch your favorite animal online: -1

**Landing(320)**
1. Расположение карточек животных в блоке Watch your favorite animal online: -1
2. Расположение элементов в блоке How it works: -1.
3. Расположение элементов в блоке Testimonials: -1.
4. Вид, расположение или отступы между полями в форме Contact Us: -1.
5. Расположение кнопки donate for volunteers в футере: -1.

**Zoos(1200)**
1. Вид, расположение или отступы между иконками животных в сайдбаре: -1.
2. Расположение прочих элементов в блоке The Zoo: -1.

**Zoos(640)**
1. Вид, расположение или отступы между иконками животных в сайдбаре: -1.

**Zoos(320)**
1. Расположение или отступы между кнопками вверх/вниз и иконками животных в сайдбаре: -1.

**Map(1200)**
1. Отступы между элментами меню в хедере: -1.
2. Расположение прочих элементов в блоке Choose your favorite: -1.

**Map(320)**
1. Расположение прочих элементов в блоке Choose your favorite: -1.

**Responsive**
1. В ходе изменения размера появляется глобальная горизонтальная полоса прокрутки: -4.

P.S. очень много расхождений с PP ровно по 10 пикселей (это верхний предел допуска, за них баллы не снимал)
