### ISSUE TITLE
Cross-Check Singolo - algoritmiks

### ISSUE THREAD

**Issue by algoritmiks** [rolling-scopes-school/support#24]
**[Ссылка на деплой](https://algoritmiks.github.io/singolo/index.html)**

**[Ссылка на репозиторий проекта](https://github.com/algoritmiks/singolo)**

Студент 2 снял с меня 20 баллов по следующей формулировке:

> Student 2
> 1. style1.css - последний commit 6.03.2020.
> 
> 2. style2.css - последний commit 6.03.2020.
> 
> 3. блок Portfolio, четырехколоночный макет смещен на несколько пикселей (за это не снижал)

6 марта мной вносились мелкие правки в эти файлы. По условиям проверки изменения были допустимы вплоть до дедлайна. Пункты, по которым были сняты баллы:

**Если в коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020, ставим -10.
Если в коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020, ставим -10.**

**файлы singolo1.html и singolo1.css были созданы в репозитории 14 февраля 2020.**
Commit: 37ddcfc60400bedf1681a168fa16a7e925919fdd
Parents: 4c912815e4d30333b0f957cd00bd04f9279ae5f1
Author: Aleksey Osipov <alexey11rus@gmail.com>
Date: Fri Feb 14 2020 19:11:29 GMT+0300 (Москва, стандартное время)

**файлы singolo2.html и singolo2.css были созданы в репозитории 25 февраля 2020**
Commit: 53f6d19b6f9d092aeb8c58ee40053c6856f98546
Parents: e9b304fa76e26bb6cc11c78de26d5161344b6908
Author: Aleksey Osipov <alexey11rus@gmail.com>
Date: Tue Feb 25 2020 14:19:50 GMT+0300 (Москва, стандартное время)

Файлы были созданы вовремя, без каких-либо нарушений. Считаю занижение оценки полностью не обоснованным, сам оцениваю свою работу на 100 баллов, т.к. она отвечает всем требованиям задачи. На данный момент, после проверки двумя студентами, оценка в скоре 90 баллов

**Comment by xmelsky** [comment]
under review

**Comment by xmelsky** [comment]
Оценка - 100.
Все дедлайны соблюдены. Претензий по ТЗ нет.
Одна деталь - фалы singolo2.html и singolo2.css в заявленном коммите 53f6d19 называются index2.html и style2.css.
