### ISSUE TITLE
Cross-Check 'Online-zoo week#3&4-v-2' - 'v-cherevko'.

### ISSUE THREAD

**Issue by v-cherevko** [rolling-scopes-school/support#240]
1. Ссылка на деплой вашего проекта.
- https://rolling-scopes-school.github.io/v-cherevko-JSFE2021Q1/online-zoo/index.html
2. Ссылка на репозиторий с проектом на GitHub.
- https://github.com/rolling-scopes-school/v-cherevko-JSFE2021Q1/tree/online-zoo
3. Ссылка на задание.
- https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-2
4. Ссылка на форму для проверки проекта (если такая есть).
- https://sergeyshalyapin.github.io/cross-check/
5. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
![Снимок экрана 2021-04-26 102342](https://user-images.githubusercontent.com/63780906/116044411-8d7d8800-a679-11eb-9d9f-c19c88c60ec8.png)
6. Оценка в результате самопроверки с ее аргументацией.
- 39 / 40 Страница: Contact Us Нет бургер меню в хедере: -1.
7. Балл за cross-check из вашего Score.
- 24

**Comment by helenakrasnova** [comment]
**Результат проверки - 29 баллов**
Страница: Landing; Блок: 1200px; Расположение элементов в блоке Welcome to the zoo / How it works нарушено.

Страница: Landing; Блок: 1200px; Расположение элементов в блоке pay and feed нарушено.

Страница: Landing; Блок: 1200px; Отступы между кнопками вправо/влево в блоке what our users think нарушены.

Страница: Landing; Блок: 1200px; Расположение или отступы между элементами в блоке care for the animals you love нарушены.

Страница: Landing; Блок: 640px; Расположение элементов в блоке pay and feed нарушено.

Страница: Landing; Блок: 640px; Отступы между отзывами в блоке what our users think нарушены.

Страница: Landing; Блок: 640px; Расположение карточки животного в блоке care for the animals you love нарушено.

Страница: Landing; Блок: 320px; Расположение элементов в блоке pay and feed, или вид кнопки Donate now нарушено.

Страница: Map; Блок: responsive; Элементы хедера или футера (кроме указанных), обрезаются или выходят за край экрана, хотя в дизайне они вписаны в границы.

Страница: Contact Us; Блок: 320px; Расположение кнопки send message в блоке Get in touch нарушено.

**Довольно много расхождений по высоте основных блоков, величине картинок**
