### ISSUE TITLE
Cross-check (photo-filter) - Rob-n-Dude

### ISSUE THREAD

**Issue by Rob-n-Dude** [rolling-scopes-school/support#241]
1. Ссылка на деплой проекта 
https://rolling-scopes-school.github.io/rob-n-dude-JSFE2021Q1/photo-filter

2. Ссылка на репозиторий с проектом на GitHub 
https://github.com/rolling-scopes-school/rob-n-dude-JSFE2021Q1/tree/photo-filter

3. Ссылка на задание
https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/js-projects/photo-filter

4. Ссылка на форму для проверки 
https://photo-filter-cross-check.netlify.app/

5. Скриншот с оценками отсутствует, так как я не засабмитил ссылку на деплой своевременно, прилагаю скрин PR с самооценкой (задание было выполнено согласно дедлайну) 
![image](https://user-images.githubusercontent.com/79657675/116238666-563ad400-a76a-11eb-8f2b-6d0dfffab4e7.png)

P.S. Благодарю за понимание

**Comment by irinainina** [comment]
Привет. Хорошая работа. 
Не совпадает фильтр blur для скачанного изображения и изображения в приложении, если картинка маленькая (для больших совпадает ) - 2.5 балла
Всего 57.5 баллов
