### ISSUE TITLE
Cross-check (photo-filter) - Ars-N

### ISSUE THREAD

**Issue by Ars-N** [rolling-scopes-school/support#242]
Ссылка на деплой проекта
https://rolling-scopes-school.github.io/ars-n-JSFE2021Q1/photo-filter/

Ссылка на репозиторий с проектом на GitHub
https://github.com/rolling-scopes-school/ars-n-JSFE2021Q1/tree/photo-filter

Ссылка на задание
https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/js-projects/photo-filter

Ссылка на форму для проверки
https://photo-filter-cross-check.netlify.app/

Скриншот с оценками отсутствует, так как я не засабмитил ссылку на деплой своевременно (был уверен, что все сделал), прилагаю скрин PR с самооценкой (задание было выполнено согласно дедлайну)
![image](https://user-images.githubusercontent.com/78049864/116260524-6f01b480-a77f-11eb-9aef-05f4a3efa52a.png)

**Comment by valerydluski** [comment]
есть коммиты после дедлайна

**Comment by igorlyatskiy** [comment]
Ваша оценка - 53 балла 

Не выполненные/не засчитанные пункты:
1) особое внимание обратите на фильтр `blur` (как проверить данный фильтр: загрузите очень большое или очень маленькое изображение, изображение вытянутое в ширину или в высоту, измените значение фильтра `blur`, сравните размытие изображения, загруженного на компьютер и открытого в графическом редакторе, с размытием этого же изображения в приложении). Полупрозрачные края картинки при использовании данного фильтра - норма, так и должно быть. Если заметили отличия, используйте для сравнения демо приложения, в нём фильтр `blur` работает корректно 

Частично выполненные пункты:
1) изображение скачивается на компьютер вместе с добавленными фильтрами. Внешний вид скачанного изображения совпадает с внешним видом изображения, которое редактировалось на странице приложения 
![image](https://user-images.githubusercontent.com/77933579/116669339-2298bd80-a9a7-11eb-98ad-aa4321ee14db.png)
В нормальных условиях всё действительно сохраняется с фильтрами, но есть какая-то последовательность действий, когда происходит подобное

Блюр ломается на очень маленьких картинках, похоже, что вы его не пересчитываете
