### ISSUE TITLE
Cross-Check 'photo-filter' - 'RykeVl'

### ISSUE THREAD

**Issue by RykeVl** [rolling-scopes-school/support#245]
1. https://rolling-scopes-school.github.io/rykevl-JSFE2021Q1/photo-filter/
2. https://github.com/rolling-scopes-school/rykevl-JSFE2021Q1/tree/photo-filter
3. https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/js-projects/photo-filter
4. https://photo-filter-cross-check.netlify.app
5. 80 / 80 Все пункты выполнены. Есть видео с самопроверкой.
6. 0.
Подаю апелляцию, так как забыл засабмитить таск. В дискорде видел вопросы от человека с точно такой же проблемой, администраторы сказали ему в таком случае подавать апелляцию. Последний коммит был сделан в 1:17, дедлайн в 3:00.

**Comment by irinainina** [comment]
Привет. 
По поводу 80 / 80 Все пункты выполнены есть сомнение. Максимальный балл за таск всего 60.
1. При перелистывании фото при нажатии на кнопку `Next picture`  иногда проскакивает две картинки - стартовая и только потом из интернета - 2 балла
2. после последнего двадцатого изображения должно снова загружаться первое, а не стартовое как в данной работе - -2 балла
3. выбранное изображение, вписывается в предназначенное для него окно занимая всю возможную площадь - маленькие картинки не растягиваются по размеру экрана -1 балл
Итого 55 баллов
P.S. Дизайн приложения понравится
