### ISSUE TITLE
Cross-check (photo-filter) - NiFroPP

### ISSUE THREAD

**Issue by NiFroPP** [rolling-scopes-school/support#246]
1. Ссылка на деплой проекта:
https://rolling-scopes-school.github.io/nifropp-JSFE2021Q1/photo-filter/

2. Ссылка на репозиторий с проектом на GitHub:
https://github.com/rolling-scopes-school/nifropp-JSFE2021Q1/tree/photo-filter

3. Ссылка на задание:
https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/js-projects/photo-filter

4. Ссылка на форму для проверки:
https://photo-filter-cross-check.netlify.app/

5. Скриншот с оценками отсутствует, так как я не сделал сабмит на деплой своевременно, прилагаю скрин PR с самооценкой (задание было выполнено согласно дедлайну и без коммитов после дедлайна)
![](https://files.fm/thumb_show.php?i=f9q9mb5fc)

PS Спасибо, если сможете / не сможете проверить работу и выставить оценку.

**Comment by irinainina** [comment]
Привет.
Баллы не снижала, но ошибки отметила
1. в const images = ['01.jpg', '02.jpg', '03.jpg', '05.jpg'... нет картинки 04.jpg'
ставилась задача написать код самостоятельно, а не скопировать с предложенных примеров
2. из-за функции setTimeout картинки листаются очень медленно
Сняла баллы
1.  Внешний вид скачанного изображения совпадает с внешним видом изображения, которое редактировалось на странице приложения (частично не совпадает) - 2.5 балла
2. особое внимание обратите на фильтр `blur` - не совпадает совсем - -5 баллов
Всего 52.5 балла
