### ISSUE TITLE
Cross-Check "photo-filter" - spice2445

### ISSUE THREAD

**Issue by spice2445** [rolling-scopes-school/support#247]
1. Ссылка на деплой вашего проекта:
https://rolling-scopes-school.github.io/spice2445-JSFE2021Q1/photo-filter/
2. Ссылка на репозиторий с проектом на GitHub:
https://github.com/rolling-scopes-school/spice2445-JSFE2021Q1/tree/photo-filter/photo-filter
3. Ссылка на задание: 
https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/js-projects/photo-filter
4. Ссылка на форму для проверки проекта:
https://photo-filter-cross-check.netlify.app/
5. Скриншот с оценками за cross check:
![IMG_20210430_143021](https://user-images.githubusercontent.com/79026145/116690217-c000eb00-a9c1-11eb-8175-ee9ca02e5d20.jpg)
![IMG_20210430_143006](https://user-images.githubusercontent.com/79026145/116690223-c1321800-a9c1-11eb-8b7b-11b941fd00b1.jpg)
6. Самооценка 53/60 баллов.

Feedback: не успел проверить работы других

**Comment by irinainina** [comment]
Привет!
То, что используешь для отображения фото канвас, отлично. Сразу исчезли проблемы с несовпадением фото в приложении и скачанного на компьютер.
Но проблема с перелистыванием фото есть. В приложение не загружаются картинки со сторонних ресурсов (гитхаба) как это требовалось в задании. Все изображения лежат в папке проекта. 
Ошибки
1. при нажатии на кнопку `Next picture` загружается изображение из папки с картинками, расположенной на Github - -5 баллов
2. После 20 картинки должна грузиться первая - 2.5 балла
3. Ошибка при перелистывании фото - отсутствует картинка img-day-3.jpg - 0.5 балла
Итого 52 балла.
