### ISSUE TITLE
Cross-Check 'online-zoo-w-34-v-1' - 'zhengis-alinur'

### ISSUE THREAD

**Issue by zhengis-alinur** [rolling-scopes-school/support#248]
1)  Ссылка на деплой: https://rolling-scopes-school.github.io/zhengis-alinur-JSFE2021Q1/online-zoo/pages/about/
2) Ссылка на репозиторий: https://github.com/rolling-scopes-school/zhengis-alinur-JSFE2021Q1
3) Cсылка на задание: https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-1
4) Ссылка на форму для проверки: https://sergeyshalyapin.github.io/cross-check/
5) ![image](https://user-images.githubusercontent.com/62282182/116703747-6eba2100-a9ec-11eb-8969-0d8211055537.png)
6) Оценка в результате самопроверки с ее аргументацией: 
Страница: Landing; Блок: responsive; В какой-либо момент, элементы (кроме указанных, рельефа, фоновых элементов) наезжают на другие элементы, хотя во всех дизайнах между ними есть отступ. Pay and feed где-то в районе 500-550px
Страница: Zoos; Блок: responsive; В какой-либо момент, элементы хедера или футера (кроме указанных) наезжают на другие элементы, хотя во всех дизайнах между ними есть отступ. Rнопки лайка и инфо

Балл за cross-check из вашего Score: 0

**Comment by valerydluski** [comment]
Есть коммиты после дедлайна

**Comment by zhengis-alinur** [comment]
Непонятно почему в скор не зачислились баллы, которые поставили проверяющие(я с их оценками согласен), а в скоре просто ноль.

**Comment by irinainina** [comment]
> Непонятно почему в скор не зачислились баллы, которые поставили проверяющие(я с их оценками согласен), а в скоре просто ноль.

Вероятно, сам не проверил вовремя все присланные на проверку работы
