### ISSUE TITLE
Cross-check photo-filter - dauniusha

### ISSUE THREAD

**Issue by Dauniusha** [rolling-scopes-school/support#249]
1. https://rolling-scopes-school.github.io/dauniusha-JSFE2021Q1/photo-filter
2. https://github.com/rolling-scopes-school/dauniusha-JSFE2021Q1
3. https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/js-projects/photo-filter
4. https://photo-filter-cross-check.netlify.app/
5. Не сабмитил(
6. Ставил 60 из 60, но после заметил, что у меня вместо 'input' 'mousemove', перекомичивать не стал)
7. Не сабмитил(

**Comment by irinainina** [comment]
Отличная работа.
Все пункты требований выполнены полностью
Всего 60 баллов
