### ISSUE TITLE
Cross-Check Singolo - SkaymanT

### ISSUE THREAD

**Issue by SkaymanT** [rolling-scopes-school/support#25]
Ссылка на деплой вашего проекта: https://skaymant.github.io/singolo/

Ссылка на репозиторий с проектом на GitHub: https://github.com/SkaymanT/singolo

Оценка в результате самопроверки, с ее аргументацией: 100

Балл за cross-check из вашего Score: 98

Student 3
Оценка - 91 баллов

_Отзыв по пунктам ТЗ:_

1. При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла

2. Социальные иконки в Footer-e без интерактивных стилей, при наведении на логотипы соц.сетей ничего не происходит: минус -3 балла

3. Социальные иконки в секции About без интерактивных стилей, при наведении на логотипы соц.сетей ничего не происходит: минус -3 балла

_Аргументация_

1. Согласно [Топ ошибок проверяющих при cross-check Singolo](https://not-saint.github.io/Cross-check-FAQ/singolo.html) в именах (Adam Jensen, Desmond Miles, Scolara Visari) реализовано проверка на переполнение.

2. Согласно [Топ ошибок проверяющих при cross-check Singolo](https://not-saint.github.io/Cross-check-FAQ/singolo.html) в моем проекте  интерактивность элементов реализовано минимальной интерактивностью, только cursor: pointer.

3. Согласно [Топ ошибок проверяющих при cross-check Singolo](https://not-saint.github.io/Cross-check-FAQ/singolo.html) в моем проекте  интерактивность элементов реализовано минимальной интерактивностью, только cursor: pointer.

 Считаю занижение оценки полностью не обоснованным, сам и 3 остальных проверяющих оценивают свою работу на 100 баллов, т.к. она отвечает всем требованиям задачи.

**Comment by amoebiusss** [comment]
@SkaymanT Оценка отличается от ожидаемой на 2 балла, минимальная разница — 15.

https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f
