### ISSUE TITLE
Cross-Check 'photo-filter' - '2670207'

### ISSUE THREAD

**Issue by 2670207** [rolling-scopes-school/support#250]
1. Ссылка на деплой вашего проекта:
https://rolling-scopes-school.github.io/2670207-JSFE2021Q1/photo-filter/
2. Ссылка на репозиторий с проектом на GitHub:
https://github.com/rolling-scopes-school/2670207-JSFE2021Q1/tree/photo-filter/photo-filter
3. Ссылка на задание:
https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/js-projects/photo-filter
4. Ссылка на форму для проверки проекта:
https://photo-filter-cross-check.netlify.app/
5. Скриншот с оценками за cross check:
![image](https://user-images.githubusercontent.com/6748500/116810392-316ca500-ab4c-11eb-881c-00be7985f605.png)
Самооценка 57/60 баллов.
Feedback: не успел проверить работы других

**Comment by igorlyatskiy** [comment]
Ваша оценка - **53 балла**

Частично выполненные пункты:

1) на странице отображается изображение и настройки css-фильтров `blur`, `invert`, `saturate`, `sepia`, `hue rotate` в виде ползунков. Напротив каждого ползунка есть поле, в котором отображается значение соответствующего css-фильтра. Дополнительные фильтры можно добавить по своему усмотрению. Стартовое изображение загружается из файлов самого приложения. Его соответствие времени суток не требуется

2) при клике по кнопке `Reset`, сбрасываются значения всех css-фильтров. При этом возвращаются к исходному состоянию положение ползунков, значения в соответствующих им полях и внешний вид изображения

3) при клике по кнопке `Load picture` открывается окно выбора файлов на компьютере, выбранное изображение, вписывается в предназначенное для него окно занимая всю возможную площадь. Пропорции изображения при этом не искажаются. Если в приложении установлены пользовательские значения фильтров, при загрузке нового изображения они сохраняются. Одно и то же изображение можно загружать повторно (как проверить: загрузите изображение, нажмите на `Next picture`, чтобы картинка сменилась, снова загрузите то же самое изображение с компьютера. Формат изображения, которое использует проверяющий при проверке данного пункта, может быть jpg, jpeg, png, неанимированный gif)

Вам уже отписали про эти ошибки в отзывах на скрине
