### ISSUE TITLE
Cross-Check: Review Self-introduction

### ISSUE THREAD

**Issue by Aleks-Zal** [rolling-scopes-school/support#251]
Добрый день.
Прошу пойти на встречу и засчитать мне 100 баллов за задание Self-introduction.
Моя проблема была в том что я не вовремя проверил работы других студентов. Это произошло уже на следующий день после дедлайна. Следовательно баллы мне не защитались. Причиной не соблюдения сроков стала длительная командировка по работе. 

Сабмит с моей стороны был сделан вооремя.
Submitted https://youtu.be/HmOXeE_GXqQ on 2021-04-19.

Но другие работы проверил только 24.04... сроки дедлайна были до 23.04.

1. Cсылка на задание: https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/self-introduction/self-introduction
2. Ссылка на транскрипт выступления: https://docs.google.com/document/d/1hqxpbTJbELm-YXwQAqNx1UpEHJV7SyGgvotnFES_2oY/edit?usp=sharing
3. Done 19.04.2021 / deadline 19.04.2021
4. Score: 100 / 100
Есть ссылка на видеозапись выступления - 50
Есть ссылка на транскрипт выступления - 50
5. Ссылка на YouTube видео с самооценкой - https://youtu.be/HmOXeE_GXqQ

![Снимок экрана (4)](https://user-images.githubusercontent.com/58571646/116886942-5e938300-ac32-11eb-9434-b28281fd0be3.png)

**Comment by irinainina** [comment]
Привет! Все требования выполнены.
Всего 100 баллов
