### ISSUE TITLE
Cross-Check 'photo-filter' - DIJITEA

### ISSUE THREAD

**Issue by DIJITEA** [rolling-scopes-school/support#252]
Ссылка на деплой проекта: 
https://rolling-scopes-school.github.io/dijitea-JSFE2021Q1/photo-filter/

Ссылка на репозиторий с проектом на GitHub: 
https://github.com/rolling-scopes-school/dijitea-JSFE2021Q1/tree/photo-filter

Ссылка на задание:
https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/js-projects/photo-filter

Ссылка на форму для проверки проекта:
https://photo-filter-cross-check.netlify.app/

Скриншот с оценками за cross check:
![image](https://user-images.githubusercontent.com/57596699/117000998-e214a900-acf2-11eb-9c9e-d8a551818958.png)

Прошу рассмотреть апелляцию, получил 0 баллов из-за отсутствия  Cross-Check: Review  т.к. не было возможности провести его, сделал данный 'issues' как только появилась данная возможность ( мне сообщили, что для данного задания сделали исключение и я могу получить баллы за него)

**Comment by irinainina** [comment]
Всего 55 баллов
Большое отличие размытия фото в приложении и при скачивании на компьютер
![screenshot_13](https://user-images.githubusercontent.com/23195079/117008968-eee5cc80-acf3-11eb-81f4-987d4d9f6f3d.png)
