### ISSUE TITLE
Online-zoo/vanwilder199

### ISSUE THREAD

**Issue by VanWilder199** [rolling-scopes-school/support#253]
1. https://rolling-scopes-school.github.io/vanwilder199-JSFE2021Q1/online-zoo/pages/MainLending/index.html
2. https://github.com/rolling-scopes-school/vanwilder199-JSFE2021Q1/tree/online-zoo
3. https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-2
4. https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/online-zoo/variant-2 ( в самом низу)
5.
![Crosscheck](https://user-images.githubusercontent.com/72692962/117649183-e24ff100-b197-11eb-86a3-2e021fd1e1d0.png)
На мои взгляд все требования из за которых можно снизить балл выполнены. **Возможно не все проверяющие дождались когда страница полностью прогрузится**.  К примеру сайд бар переключения животных полностью работает. В автоматической карусели так же все установлено правильно раз в 60 сек после клика смена картинки и т.д.

**Comment by valerydluski** [comment]
Оформите по требованиям
