### ISSUE TITLE
2021Q1 JS/FE Продолжаю учиться

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/support#257]
Часть неактивных в мае студентов была отчислена. 
Если вы по ошибке попали в их число, и продолжаете учиться на курсе, оставьте сообщение ниже

**Comment by Regin99** [comment]
Продолжаю учиться, в своем темпе

**Comment by ShikiLe** [comment]
Продолжаю

**Comment by NachinkaShaurmi** [comment]
Записан что бы была возможность попасть на Angular, если она будет и так то можно не восстанавливать.

**Comment by moonbek007** [comment]
Продолжаю

**Comment by Marculis** [comment]
продолжаю

**Comment by kpogotskaia** [comment]
Продолжаю.

**Comment by Lam-ss** [comment]
я продолжаю учиться в своем темпе

**Comment by Anton-Gadiyatov** [comment]
Продолжаю.

**Comment by IgorAblyak** [comment]
Прошу продлить обучение

**Comment by biburat2** [comment]
продолжаю учиться.

**Comment by dmp11** [comment]
Продолжаю учиться

**Comment by Serhii-Aha** [comment]
Я продолжаю учиться.

**Comment by evgen-kent** [comment]
продолжаю учиться

**Comment by Santerna** [comment]
Продолжаю учиться

**Comment by sezardino** [comment]
Продолжа. учиться

**Comment by Kolenchitssi** [comment]
я вроде еще не отчислен, подстрахуюсь, сейчас нет возможности успевать в ритме со всеми, но я продолжаю учится.

**Comment by Vorfall** [comment]
> Часть неактивных в мае студентов была отчислена.
> Если вы по ошибке попали в их число, и продолжайте учиться на курсе, оставьте сообщение ниже

Продолжаю учиться, в своем темпе

**Comment by nadezdatsygankova** [comment]
Продолжаю учиться

**Comment by KirillMalko** [comment]
Продолжаю развиваться

**Comment by egorastapchyk** [comment]
Продолжаю учиться, в своем темпе
