### ISSUE TITLE
Cross-Check 'Match-Match Game' - 'Crable75'

### ISSUE THREAD

**Issue by Crable75** [rolling-scopes-school/support#258]
Ссылка на деплой вашего проекта.
https://rolling-scopes-school.github.io/crable75-JSFE2021Q1/match-match-game/

Ссылка на репозиторий с проектом на GitHub.
https://github.com/rolling-scopes-school/crable75-JSFE2021Q1/tree/match-match-game-src

Ссылка на задание.
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/match-match-game.md

Ссылка на форму для проверки проекта (если такая есть).
Отсутствует

Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
Никто не оценил вообще.
![image](https://user-images.githubusercontent.com/24875394/120780533-e53cc800-c530-11eb-9fee-e52d541c9d0a.png)

Оценка в результате самопроверки с ее аргументацией.
80 - не сделана задача по добавлению аватара.

Балл за cross-check из вашего Score.
0

**Comment by Wolf-Den1994** [comment]
Здравствуйте. Буду проверять вашу работу по версии на момент дедлайна.

 +10 - Верстка содержит все описанные в требованиях блоки
 +15 - Соблюдены **НЕ** все требования к валидации полей для регистрации игрока в приложении.

>  - Имя / Фамилия не может быть пустым. (если написать одну букву, а потом удалить поля имя/фамилия пустое, но подсвечено как правильно, и регистрация проходит)
>  - Имя / Фамилия не может состоять из цифр. (внимательно читаем ТЗ, понимаем что содержать цифры может, и это же подтвердил автор таска в гугл доке вопросами-ответами)
>  - Количество символов не должно превышать 30 символов включая пробелы. (а оно у вас превышает и проходит регистрация в итоге после игры страница скор легко ломается)
>  - После нажатия на кнопку cancel вся ранее заполненная информация должна быть сброшена. (страница перезагружается, данные оказываются в адресной строке, при последующей регистрации в окне если нажать кнопку cancel то ничего не происходит, она перестаёт работать)

 +20 - Реализован игровой цикл.
 +10 - Реализована таблица рекордов.
 +10 - Реализована страница settings.
 +10 - Реализована страница about game.
 +0 - Реализована механика добавления аватара игрока, который хранится в indexedDb в base64 формате и отображается в header и на странице рекордов.

Заметил еще парочку небольших бага, за которые баллы не снимаю, т.к. в тз не четко не указано. После регистрации если нажать на аватарку, то начинается игровой цикл. 
Словил баг, когда играл второй раз на том же аккаунте: когда оставалось 4 карточки неоткрытые игра завершилась, больше не смог поймать такой баг.
Ну и вместо аватарки девушки лучше всё же было использовать картинку ананимуса (пример в модалке регистрации).

Работа хорошая. Итоговая оценка: 75.

**Comment by Crable75** [comment]
Благодарю! Issue я закрываю или кто-то должен его закрыть?

**Comment by Crable75** [comment]
По оценке - она должна появиться в скоре?

**Comment by valerydluski** [comment]
нет, issue я сам закрою, когда буду выставлять оценки
