### ISSUE TITLE
Cross-Check 'MatchMatch-game' - 'Nata-Roma'

### ISSUE THREAD

**Issue by Nata-Roma** [rolling-scopes-school/support#259]
1. Ссылка на деплой вашего проекта.
https://rolling-scopes-school.github.io/nata-roma-JSFE2021Q1/match-match-game/index.html
2. Ссылка на репозиторий с проектом на GitHub.
https://github.com/rolling-scopes-school/nata-roma-JSFE2021Q1/tree/match-match-game/match-match-game
3. Ссылка на задание.
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/match-match-game.md
4. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
![Score page](https://user-images.githubusercontent.com/67419233/120788926-96476080-c539-11eb-94d4-9233cee2cfc6.png)
5. Оценка в результате самопроверки с ее аргументацией.
110/110 Все пункты ТЗ выполнены, включая работу с indexedDB.
6. Балл за cross-check из вашего Score.
100

**Comment by valerydluski** [comment]
Рассмотрение апелляции происходит только если ожидаемый вами балл и полученный по результатам cross-check балл отличаются на 10 и более процентов.

**Comment by Nata-Roma** [comment]
> Рассмотрение апелляции происходит только если ожидаемый вами балл и полученный по результатам cross-check балл отличаются на 10 и более процентов.

110 * 100 = 10%

**Comment by valerydluski** [comment]
Согласен не правильно посчитал

**Comment by valerydluski** [comment]
110 - 100%
100 - 90,9%
100 - 90,9 = ?

**Comment by Nectire** [comment]
> 110 это 100%
> 100 это примерно 90,9%
> 100 - 90,9 = ?

Разве апелляция не проходит? 110/100 * 10 = 11%. Лично у меня точно такая же проблема, точно такая же оценка за кросс-чек

**Comment by valerydluski** [comment]
> > 110 это 100%
> > 100 это примерно 90,9%
> > 100 - 90,9 = ?
> 
> Разве апелляция не проходит? 110/100 * 10 = 11%. Лично у меня точно такая же проблема, точно такая же оценка за кросс-чек

От 110 баллов 10 процентов это сколько?
