### ISSUE TITLE
Cross-Check Singolo-Dianakove32

### ISSUE THREAD

**Issue by Dianakove32** [rolling-scopes-school/support#26]
[Ссылка на деплой  вашего проекта](https://dianakove32.github.io/singolo/):
 
[Cсылка на репозиторий с проектом на  GitHub](https://github.com/Dianakove32/singolo):
 

_Работа проверена тремя студентами с соответствующими баллами: 91, 60, 86.
Балл за cross-check из моего Score: 79.
Был выявлен ряд замечаний, часть которых считаю необоснованными. Сама оцениваю свою работу на 90 баллов._

Student 1:
3) Стрелки слайдера без интерактивных стилей, при наведении на стрелки, ничего не происходит: минус -3 балла 
_( согласно условию,_ 

> интерактивность элементов: достаточно наличия минимальной интерактивности, например, только cursor: pointer, 

_в моей работе этот пункт соответствует требованию: при наведении на стрелки изменяется курсор)._

Student 2:
0) Не отображаются социальные иконки в секции About Us и Footer: -10 баллов 
_(социальные иконки отображаются и являются интерактивными)._
00) Изменения в файлы index.html и style.css после дедлайна 08.03.2020: -10 баллов
_(Все части сданы до дедлайна, что можно отследить по коммитам. часть третья была сдана 7 марта, а index.html and style.css 9 числа, которое являлось последним днем сдачи и были внесены минимальные правки);_
2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Header составляют более двух пикселей (2px): минус -3 балла
_(вопрос с текстом, а не логическим контейнеры для него);_
4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла
_(отличается местами текст, а не логические контейнеры для него. По условию:_ 
> отклонение даже немного больше 2px по горизонтали для текстовых элементов - не ошибка.);
5) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла
_(отличается местами текст, а не логические контейнеры для него);_
6) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Footer составляют более двух пикселей (2px): минус -3 балла
_(отличается местами текст, а не логические контейнеры для него);_

**Comment by xmelsky** [comment]
under review

**Comment by xmelsky** [comment]
Оценка - 89.
По дедлайнам замечаний нет. Работа выполнена очень хорошо, но есть некоторые замечания. 

Проблема с различиями в firefox сетки в секции Portfolio скорее всего связана с неправильной реализацией этой сетки. Не совсем верный подход создавать строки (rows) искусственно с помощью элементов div. Правильнее дочерние элементы блока flex позиционировать свойствами flex контейнера, например justify-content, align-items, width дочерних элементов и тп. Тем более, что такое искусственное разделение на rows или columns очень затрудняет динамическую работу с этими элементами посредством js (например фильтрация и тп).

Разделители ссылок блока nav - у первого элемента home с левой стороны не должно быть этого разделителя. это реализуется средствами css, например селекторами, которые позволяют выбрать все дочерние, кроме первого. или все четные или наоборот. Вот ссылка, где [подробно объясняются](https://css-tricks.com/useful-nth-child-recipies/). Шрифт в nav тоже не соответствует Lato.
