### ISSUE TITLE
Cross-Check 'Match-match-game' - 'listgarten100'

### ISSUE THREAD

**Issue by listgarten100** [rolling-scopes-school/support#261]
1. Ссылка на деплой вашего проекта.
https://listgarten100-match-game.netlify.app/#
2. Ссылка на репозиторий с проектом на GitHub.
https://github.com/rolling-scopes-school/listgarten100-JSFE2021Q1/tree/match-match-game
3. Ссылка на задание.
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/match-match-game.md
4. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
![image](https://user-images.githubusercontent.com/73188490/120886038-8e98c200-c5f4-11eb-994b-9bcb15ddf4dc.png)
![image](https://user-images.githubusercontent.com/73188490/120886044-96586680-c5f4-11eb-9e72-263939e539f5.png)
5. Оценка в результате самопроверки с ее аргументацией.
110/110. Все пункты ТЗ выполнены, включая валидацию при регистрации, проверящие снизили баллы за наличие цифр в имени и фамилии, но по тз имя и фамилия могут содержать цифры, они не могут полностью из них состоять.
6. Балл за cross-check из вашего Score.
88

**Comment by igorlyatskiy** [comment]
Привет! Хорошая работа, всё выполнено согласно ТЗ, перепроверил форму регистрации несколько раз. **Моя отметка 110/110**
Успехов!
