### ISSUE TITLE
Cross-Check: 'Self-Introduction' - 'Nectire'

### ISSUE THREAD

**Issue by Nectire** [rolling-scopes-school/support#262]
Cсылка на задание: https://rolling-scopes-school.github.io/stage0/#/stage1/tasks/self-introduction/self-introduction

Ссылка на репозиторий с проектом: https://github.com/rolling-scopes-school/nectire-JSFE2021Q1/tree/self-introduction

Ссылка на транскрипт выступления: https://docs.google.com/document/d/1EVTr6fQsn82GvppC87qHZlCq5ye6QUBKY-ikiLLS9ao/edit

Done: 19.04.2021 / 19.04.2021

Скриншот cross-check:
![cross-check](https://user-images.githubusercontent.com/72974641/120919276-5f03bb80-c6c1-11eb-903a-ee69eb96749d.png)
Score: 100 / 100

В ходе деплоя задания по своей невнимательности отправил ссылку на мой приватный репозиторий с заданием. В ходе кросс-чека с некоторыми студентами мне удалось связаться и скинуть им ссылку на ютуб видео, но 1 из проверяющих, посчитал что неправильный деплой задания считается грубой ошибкой, хотя в критериях оценки этого пункта нет. Хотелось бы узнать, считается ли оценка объективной?
Есть ссылка на видеозапись выступления: 50
Есть ссылка на транскрипт выступления: 50
Ссылка на YouTube видео:  https://www.youtube.com/watch?v=phQWKim9j4M

Оценка в Score: 83

**Comment by valerydluski** [comment]
Да, считается, по задеплоеной ссылки работу проверить нет возможности. Так что хорошо, что не 0

**Comment by Nectire** [comment]
Понял, спасибо за ответ
