### ISSUE TITLE
Cross-Check Typescript basycs - Kutsak-Nataly

### ISSUE THREAD

**Issue by Kutsak-Nataly** [rolling-scopes-school/support#263]
## Ссылка на деплой вашего проекта.
<https://github.com/Kutsak-Nataly/Express-REST-service/pull/2>
___
## Ссылка на репозиторий с проектом на GitHub.
   <https://github.com/Kutsak-Nataly/Express-REST-service>
## Ссылка на задание.
   <https://github.com/rolling-scopes-school/basic-nodejs-2021Q2/blob/master/descriptions/typescript-basics.md>
   <https://github.com/rolling-scopes-school/basic-nodejs-2021Q2/blob/master/cross-check/typescript-basics.md>
## Ссылка на форму для проверки проекта (если такая есть).
   <https://boring-ride-216864.netlify.app/>
## Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
    
![изображение](https://user-images.githubusercontent.com/73638937/120921882-b6f4ef00-c6ce-11eb-9bb5-4afc77dd395f.png)

## Оценка в результате самопроверки с ее аргументацией.
1-е задание. Все условия выполнены - 60 баллов
2-е задание. Ошибок компиляции, линтера нет. Приложение запускается. Все тесты пройдены. tsconfig.json строгий, как указано в кросс-чеке (кроме "module": "es2020" - 5 баллов за это). Работает. 185 баллов
штрафных нет.
Суммарно - 245
## Балл за cross-check из вашего Score.
228 - средний балл за это задание. Проверило 3 человека

**Comment by natein** [comment]
**Итоговая оценка:** 235 баллов

**Первая часть:** 55 баллов
Во всех models
В конструктор в качестве аргумента передаётся объект. А из описания параметров в документации следует, что аргументы идут через запятую, например: new User(id, name, login, password) - 3 места

board.memory.repository.js и board.service.js
Возвращаемый тип getById указан {Promise<void>}, хотя на самом деле возвращается {Promise<Board>} - 2 места

user.memory.repository.js и user.service.js
Возвращаемый тип getById указан {Promise<void>}, хотя на самом деле возвращается {Promise<User>} - 2 места

Всего описано 37 функций.
Из них 7 засчитываю как описанные частично и они получают коэффициент 0.5

**Вторая часть** 190 баллов
Ошибки, сыплющиеся в консоль во время тестов, желательно было бы исправить.

Штраф за "Меньше 3 коммитов в каждой части, не считая коммиты, вносящие изменения только в Readme.md". У тебя в первой части меньше 3 коммитов. -10 баллов.
