### ISSUE TITLE
Cross-check 'Match-Match Game' - 'upmyskills'

### ISSUE THREAD

**Issue by upmyskills** [rolling-scopes-school/support#264]
**DEPLOY**: [HERE](https://rolling-scopes-school.github.io/upmyskills-JSFE2021Q1/match-match-game/);
**GITHUB**: [repo on github](https://github.com/rolling-scopes-school/upmyskills-JSFE2021Q1/tree/match-match-game/stage2);
**TASK**: [Match-match game](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/match-match-game.md);
**SCREENSHOT**:
![изображение](https://user-images.githubusercontent.com/75721735/121035176-4b864c80-c7b6-11eb-9d9c-1e779867eaaf.png)
**ARGs**: Человек проверил до того как в задании изменили максимальный балл с 80 на 110. И больше не появлялся. Связаться с ним не удалось. Думаю, 77 там должно быть, если рассуждать по-человечески, да и по справедливости тоже.
Моя оценка себе: 100. Так как на тот момент indexedDB была, но не был реализован выход из профиля, думаю это никак не -30.
**Score**: 89;

**Comment by valerydluski** [comment]
есть коммиты после дедлайна

**Comment by valerydluski** [comment]
Так максимальный балл 110 был с самого начала

**Comment by upmyskills** [comment]
Правда? Только написано было так, что большинство поняло, что 80. Так и оценивали...
![изображение](https://user-images.githubusercontent.com/75721735/121257589-8a033080-c8b6-11eb-829e-e55f3196ebf0.png)

**Comment by valerydluski** [comment]
я на выходных проверю

**Comment by valerydluski** [comment]
но сразу предупреждаю, я применю штраф за коммиты после дедлайна

**Comment by upmyskills** [comment]
Хех...) Со штрафами надеюсь хотябы то на то и выйдет, что есть...)
Но, в любом случае спасибо, что не оставили без внимания.)
