### ISSUE TITLE
JS/FE 2021Q1 Дополнительная регистрация на CoreJS интервью

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/support#265]

**Comment by alibek-gao** [comment]
Не успел зарегестрироваться(

**Comment by akool** [comment]
Запрашиваю возможность записаться на интервью. Упустил дату основной записи.

**Comment by umidullo** [comment]
+

**Comment by YaGrig** [comment]
.

**Comment by VelichkoRoman** [comment]
Не успел зарегестрироваться(

**Comment by chekni** [comment]
Забыла записаться во время основной записи( Прошу внести меня в лист ожидания на интервью

**Comment by Nectire** [comment]
Тоже не успел зарегистрироваться. Прошу внести меня в лист ожидания на интервью.

**Comment by LenarFF** [comment]
Прозевал запись на интервью. Запишите, если не поздно

**Comment by drunich-z** [comment]
Добрый день! Наверное, прозевал запись. В разделе интервью кнопка регистрации 10 минут назад  (17.06, 14:20 UTC) была активна - нажал, RSS app - зарегистрировала(о). Тем не менее, прошу внести меня в лист ожидания на интервью.
 (Andrey Zverev, drunich-z)

**Comment by MadPapaya** [comment]
Кнопку регистрации нажал, но уже после новости о готовом новом распределении. Надеюсь все ок, но на всякий случай прошу проверить и если что внести в лист ожидания  на интервью.

**Comment by gtycbjyth** [comment]
Прозевал запись на интервью. Запишите меня пжлст.

**Comment by oleksawn** [comment]
Кнопку регистрации нажала, но после готового распределения. На всякий случай прошу внести в лист ожидания на интервью.

**Comment by AliaxeiSehiyenia** [comment]
Прозевал запись на интервью.

**Comment by dzmitry-varabei** [comment]
Всем привет! всех распределил по менторам
