### ISSUE TITLE
Cross-Check 'Async race' - 'DvorakKatsiaryna'.

### ISSUE THREAD

**Issue by DvorakKatsiaryna** [rolling-scopes-school/support#267]
1. Ссылка на деплой вашего проекта: https://rolling-scopes-school.github.io/dvorakkatsiaryna-JSFE2021Q1/async-race/
2. Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/dvorakkatsiaryna-JSFE2021Q1/tree/async-race (gh-pages: https://github.com/rolling-scopes-school/dvorakkatsiaryna-JSFE2021Q1/tree/gh-pages/async-race)
3. Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
4. Ссылка на форму для проверки проекта (если такая есть): нет
5. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты):

![app rs school_course_student_cross-check-submit_course=js-fe-2021Q1 (1)](https://user-images.githubusercontent.com/74607583/122894908-4ac1ee80-d350-11eb-8f97-76287336a8ef.png)
6. Оценка в результате самопроверки с ее аргументацией: Выполнены все требования задания 190/190.
7.Балл за cross-check из вашего Score: После официально установленного дедлайна стоял балл 190, после того, как продлили дедлайн проверки и проверил еще один студент (вероятно, не запустив сервер, заполняла форму, где можно указать на необоснованные комментарии), стал 133.

**Comment by valerydluski** [comment]
Исправлю оценку.
