### ISSUE TITLE
Cross-Check: English For Kids - AzizbekSavkimov

### ISSUE THREAD

**Issue by AzizbekSavkimov** [rolling-scopes-school/support#269]
1. Ссылка на деплой вашего проекта: https://azizbeksavkimov-english-for-kids.netlify.app/ 
2. Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/azizbeksavkimov-JSFE2021Q1/tree/english-for-kids
3. Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rslang/english-for-kids.md
4. Ссылка на форму для проверки проекта (если такая есть): нет
5. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты): нет

**Comment by igorlyatskiy** [comment]
Моя отметка **202** балла

> на главной странице приложения размещаются ссылки на страницы с категориями слов
> минимальное количество категорий - восемь
Их не 8, их 6, в бургере их вообще 7. Минус 3 балла (итого минус 3)

Поймал баг 'cannot read property map of undefined. В game-container.tsx: 105'. Минус 5 (итого минус 8)

> Вёрстка, дизайн, UI главной страницы приложения
> +20 - выполнены все описанные требования к оформлению приложения
-10, адаптива нет, итого минус 18

> Вёрстка, дизайн, UI выезжающего меню:
>  +15 - выполнены все описанные требования к оформлению приложения
Выполнены не все, адаптива нет. -5, итого минус 23

Advanced scope выполнен полностью, hacker scope не выполнен вообще.

145 за основной + 80 за повышенный - 23 за штрафы=202 балла

**Comment by AzizbekSavkimov** [comment]
спасибо огромное!
