### ISSUE TITLE
Cross-Check Singolo-Jimmba

### ISSUE THREAD

**Issue by Jimmba** [rolling-scopes-school/support#27]
[Деплой](https://jimmba-singolo.netlify.com/)
[Репозиторий](https://github.com/Jimmba/singolo)

Суть проблемы:
Не заметил, что конечные файлы должны называться index.html и style.css и запушил по образцу первых двух тасков с именами singolo.html и singolo.css. Несмотря на то, что в репозитории лежит ссылка на задеплоенную страницу один из проверяющих не стал ее проверять и указал на отсутствие файлов. Собственно, после этой проверки я и обнаружил, что файл должны быть названы по-другому. Для остальных проверяющих я (уже после дедлайна) скопировал файлы singolo.html и singolo.css, переименовав их, как положено в репозиторий, добавив соответствующий комментарий в readme (обращаю внимание, что index.html и style.css - полная копия singolo.html и singolo.css, которые были запушены еще 6 марта. Единственное изменение - это исправление адреса ссылки на css-файл, т.к. он переименован). Т.е. по сути задание было выполнено 6 марта, проблема лишь в том, что были не переименованы файлы.

Задание считаю выполненным полностью (можно придираться к блоку Contact information, там иконки и текст немного смещены относительно макета, но я решил, что в макете их не выровняли - там они расположены криво, и решил оставить выровненными по левому краю). Не знаю, считать ли это за ошибку, ну, пусть -3.

За отсутствие файлов (если не учитывать, что файлы все-таки были, только под другими именами) - предусмотрен штраф в 10 баллов:
![image](https://user-images.githubusercontent.com/32487200/76628123-561f4b00-654d-11ea-9058-b057e247e548.png)

Итого:  87 баллов.

Естественно, оценка на ваше усмотрение, но я считаю, что ставить 0, не попытавшись разобраться, где же файлы (задеплоенная страница же есть) как-то через чур. 

Балл из score после проверки двумя студентами - 50 (один из них поставил 100, второй написал, что отсутствуют файлы, следовательно, поставил 0). Недавно появился отзыв третьего студента, но скор еще не изменился).

Благодарю за рассмотрение вопроса.

**Comment by amoebiusss** [comment]
@Jimmba добрый день! Добавьте, пожалуйста, в описание балл, на который вы сами оцениваете задание.

**Comment by Jimmba** [comment]
@amoebiusss , приветствую. Я указал, скрин ниже:
![image](https://user-images.githubusercontent.com/32487200/76689639-f7d79280-6648-11ea-9b64-ebbd059b4619.png)

**Comment by Jimmba** [comment]
Прошу пересмотреть выставленную одним из проверяющих оценку (0 баллов). Если бы он проверил работу и выставил бы ожидаемую мной оценку (87 баллов), то итоговый балл у меня был бы 95 баллов (против имеющихся 73), что выше на 22 балла.

**Comment by amoebiusss** [comment]
@Jimmba добрый день! Итоговая оценка по обновленному алгоритму — 97, наименьшая оценка (0) не учитывалась при подсчете. Закрываю ишью, хорошего дня!
