### ISSUE TITLE
Cross-Check 'English for kids S1E1' - 'Vitaly-Khvisevich'.

### ISSUE THREAD

**Issue by Vitaly-Khvisevich** [rolling-scopes-school/support#270]
Ссылка на деплой вашего проекта: https://rolling-scopes-school.github.io/vitaly-khvisevich-JSFE2021Q1/english-for-kids/
Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/vitaly-khvisevich-JSFE2021Q1/tree/English-for-kids
Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rslang/english-for-kids.md
Ссылка на форму для проверки проекта (если такая есть): нет
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты): 
![App-The-Rolling-Scopes-School](https://user-images.githubusercontent.com/68824186/125376117-034ce200-e393-11eb-98f2-70ab109e4c82.png)

**Comment by Wolf-Den1994** [comment]
Привет, сейчас буду проверять эту работу.
По началу тоже не произносились слова, пока не очистил локалсторейдж. Видимо совпали слова со студентами, которые так же засоряют локалсторейдж. Узнай у своего ментора как лучше с ним работать. Потому что я брал один большой массив объектов и записывал его в значения по одному ключу, а не создавал 64 ключа и значения. Высока вероятность получить ошибку приложения как собственно и было.
Старайся использовать одно наименование классов, или в camelCase или через дефис ну или через _.
В остальном всё хорошо сделано, за исключением **Вёрстка, дизайн, UI выезжающего меню: _+10 - ссылка на текущую страницу внешне отличается от остальных_**
Тут заслуженные 265

**Comment by Vitaly-Khvisevich** [comment]
Спасибо за проверку!!!
