### ISSUE TITLE
Cross-Check 'English-for-kids' - BlackPawsStudio

### ISSUE THREAD

**Issue by BlackPawsStudio** [rolling-scopes-school/support#271]
1. Деплой: https://rolling-scopes-school.github.io/blackpawsstudio-JSFE2021Q1/english-for-kids/
2. Репозиторий: https://github.com/rolling-scopes-school/blackpawsstudio-JSFE2021Q1/
3. Задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rslang/english-for-kids.md
4. Скриншоты оценок:
![image](https://user-images.githubusercontent.com/75565111/125617731-f1b83c7a-b708-4b1a-85bd-b7a6bc981ff4.png)
![image](https://user-images.githubusercontent.com/75565111/125617758-7dcbd30b-d46b-43ec-91d7-5858bcf6ab9e.png)
![image](https://user-images.githubusercontent.com/75565111/125617826-859db71a-acd6-405d-9296-458af1bbba6b.png)
![image](https://user-images.githubusercontent.com/75565111/125617880-b3bb480f-f27b-4f91-81f6-2fd3aa8899a9.png)
5. С оценками полностью согласен, они выставлены адекватно, но в скоре у меня получился 0, так как я перепутал время дедлайна проверки заданий. Раньше дедлайны были по примеру: 12.07 23:59 utc, что означало, что дедлайн 13.07 в 3 часа ночи по Москве. Сейчас я по аналогии решил, что 13.07 02:59 utc - это проверка до ночи 13 числа. В итоге вышло, что проверил я после конца дедлайна и в скор пошёл 0. Валерий Длуский сказал, что можно подать апелляцию. Очень жаль терять баллы из-за такой путаницы.
6. Оценка в скор: 0

**Comment by igorlyatskiy** [comment]
Привет! Все требования основного и повышенного уровней выполнены, за исключением:

> Вёрстка, дизайн, UI выезжающего меню:
> ссылка на текущую страницу внешне отличается от остальных

Моя отметка **215** баллов. Успехов во втором этапе таска, сабмить задание вовремя!
