### ISSUE TITLE
Cross-Check English for kids S1E1 Veronaten

### ISSUE THREAD

**Issue by veronaten** [rolling-scopes-school/support#272]
1. https://rolling-scopes-school.github.io/veronaten-JSFE2021Q1/english-for-kids/english-for-kids/
2. https://github.com/rolling-scopes-school/veronaten-JSFE2021Q1/tree/EFK
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rslang/english-for-kids.md
4. 
![1](https://user-images.githubusercontent.com/70721273/126636663-a6e47e21-481d-4c3c-8200-7a6dc8100ba4.jpg)
![2](https://user-images.githubusercontent.com/70721273/126636678-0a77d349-4024-4bd7-b847-1f3067b5b19e.jpg)

5. Здравствуйте, я неправильно посмотрела дату кросс-чека и проверила работы студентов позже на сутки (думала, что 13-го числа до конца дня..). Из-за этого мне не засчитали баллы по первой части задания. И не засчитали баллы ребятам, которых я проверяла. Мне очень жаль(( Из-за невнимательности подвела других и себе баллы не заработала. 
Может быть как-то можно исправить ситуацию? 
Я была уверена, что баллы выставят после второй части задания, а потом увидела, что у меня 0. И решила все же побороться за баллы)
Буду очень благодарна, если будет возможность зачесть те баллы, которые мне поставили ребята.

**Comment by valerydluski** [comment]
Скройте на скринах гитхабы проверяющих и их контакты

**Comment by veronaten** [comment]
Готово!)

**Comment by veronaten** [comment]
Благодарю!!!
