### ISSUE TITLE
 Cross-CheckEnglish for kids - s1e2 - Gena888

### ISSUE THREAD

**Issue by Gena888** [rolling-scopes-school/support#273]
1. https://gena888-english-for-kids-s1e2.netlify.app/
2. https://github.com/rolling-scopes-school/gena888-JSFE2021Q1/tree/english-for-kids-s1e2
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rslang/english-for-kids-admin-panel.md
4. no form for check
5. no ankets
6. Score: 205/ 205
All requirements are taken into account.
7. 0
Hello i lost the deadline time to submit my task, check me please :)

**Comment by igorlyatskiy** [comment]
**200/205**

Привет! Все требования выполнены, но в консоль крайне щедро сыплются console.log и ошибки, сайт у меня почему-то не открылся в хроме (только в инкогнито). Моя отметка **200** баллов 
![image](https://user-images.githubusercontent.com/77933579/126869355-ec5bf719-7da6-4e50-a625-edb49e8be4b3.png)

**Comment by Gena888** [comment]
Привет, да не успел убрать все ошибки и логи, большой таск для такого
количества времени)
Не знаю почему не открывался, должно было быть ок, может какой экстеншен
конфликтует у тебя хз 🤷 хироку мог долго отвечать пока проснулся но чтобы
вообще не открывалась такого не было у меня)
В любом случае спасибо 🤝☺️

Сб, 24 июля 2021 г. в 16:07, Igor Lyatskiy ***@***.***>:
