### ISSUE TITLE
Cross-Check 'Chess S1E2' - 'FazylovAsylkhan'

### ISSUE THREAD

**Issue by FazylovAsylkhan** [rolling-scopes-school/support#274]
1. Deploy: https://fazylovasylkhan-jsfe2021q1.netlify.app/
2. Repository: https://github.com/rolling-scopes-school/fazylovasylkhan-JSFE2021Q1/tree/codejam-chess
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/chess/codejam-chess-part-two.md
4. Screenshot: http://dl3.joxi.net/drive/2021/07/24/0048/1322/3163434/34/c842adc0a1.jpg
5. Score: 
 +20/30 - присутствует верстка со всеми базовыми элементами (Игроки, таблицы ходов, игровое поле)
   notes: не реализована таблица ходов: -10
 +20 - все фигуры ходят согласно правилам шахмат
 +10 - реализована возможность смены имени игрока
 +10 - реализован запуск игрового цикла
 +10 - есть подсветка доступных шагов для фигуры
 +10 - реализована возможность перетаскивать фигуры с помощью drag and drop
 +10 - реализована подсветка ситуации ШАХ и подсвечиваются клетки из-за которых она возникла
 +10 - реализована подсветка ситуации МАТ и подсвечиваются клетки из-за которых она возникла
 +5 - игрок, совершающий ход, имеет соответствующую отметку
 +5 - при смене игрока доска поворачивается с анимацией
   notes: в стриме были комментарии - не снижать баллы за это
 +5 - после победы есть возможность вернуться в Лобби
   notes: есть возможность просто выйти в лобби
 +10 - Присутствует возможность включения авто превращения пешки, которая дошла до последней горизонтали, в ферзя
 Итого:  125 баллов
 
 Примечание: 
   1) Приложение сделано на реакте
   2) Не вошло в критерии оценки, но было реализовано: En passant  ход пешкой, секундомер
   3) В приложении отсутствуют баги
   4) Хороший дизайн :)

**Comment by igorlyatskiy** [comment]
**125/480**

Привет! По поводу багов в приложении сильно сказано, я сразу нашёл баг, когда король попадает под шах, подсвечивается как мат, а когда король уходит из-под шаха, клетка остается подсвеченной. Второй момент: ставлю детский мат, таймер не останавливается. Сетевой игры, бота и тд не присутствует, учитывая баги и фичи, моя отметка 125 баллов из 480 возможных. Успехов!
