### ISSUE TITLE
JS/FE 2021Q1 Сертификат

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/support#276]
Этот тред создан для решения любых проблем связанных с сертификатом RS School

**Comment by Vitebsk121** [comment]
Привет, мне ошибочно пришёл сертификат об успешном окончании курса. Последние 25 дней я был в больнице с ковидом и не сдал бэк часть по последнему таску и не попал на кор интервью. Т.к. я вылетел из топ 20 скора в топ 300 мне сертификат уже преимуществ не даёт при трудоустройстве в епам, но спасибо что прислали) Правда , наверное это значит, что в логике выдачи сертификатов есть ошибка. За кор интервью у меня 0. Удачи

**Comment by Sweet-ka** [comment]
Добрый день! Получилось так, что ментор почему-то не проверил мои "шахматы" (я ожидала оценку от своего ментора, не знала что другой должен проверять, поэтому не задавала вопросов). Оценка была выставлена потом с опозданием, и общее количество баллов превысило проходной. Могу ли я еще получить сертификат?

**Comment by OverNovik** [comment]
Добрый день. Ментор вчера проверил работы и баллы только сегодня начислились. Возможно ли еще получить сертификат?

**Comment by dzmitry-varabei** [comment]
@Sweet-ka @OverNovik сертификаты выдал!

**Comment by nairabrab** [comment]
Приветствую, у меня на гитхабе было не заполнено имя (оттуда же оно в сертификате берется?) и соответственно серт пришел также не заполненный. Имя добавил, можно мне сертификат перевыпустить, пожалуйста?

**Comment by dzmitry-varabei** [comment]
@nairabrab заполни имя в профайле RS APP https://app.rs.school/profile

**Comment by IMGarry** [comment]
Добрый день! Скажите пожалуйста, возможно ли еще получить сертификат? Ментор вчера проверил работу и баллы добавились только сегодня.

**Comment by nairabrab** [comment]
@dzmitry-varabei заполнил, все еще требуется админское вмешательство)

**Comment by dzmitry-varabei** [comment]
@nairabrab @IMGarry сертификаты выдал! ссылка на сертификат есть в вашем профайле RS APP
