### ISSUE TITLE
Cross-Check 'CV. Cross-Check' nikita-resh

### ISSUE THREAD

**Issue by nikita-resh** [rolling-scopes-school/support#277]
1. Deploy: https://nikita-resh.github.io/rsschool-cv
2. Repo: https://github.com/nikita-resh/rsschool-cv
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/html-css.md
4. Form: https://cv-cross-check.netlify.app/
5. Screenshot:
![Снимок экрана (18)_LI](https://user-images.githubusercontent.com/73827665/127634918-d7bdf6a6-63ba-4b48-a237-93b8a2ef19f7.jpg)
6. Self-check: 100/100. Everything is fine (in particular requirements about PR)
7. 
![image](https://user-images.githubusercontent.com/73827665/127635426-d3c267d4-a925-4b55-9972-ce30d658a9e0.png)

**Comment by igorlyatskiy** [comment]
Учитывая качество работы и прикрепленное видео с самооценкой, моя отметка **100/100**
Успехов на курсе!
