### ISSUE TITLE
Cross-Check Singolo - M-fil

### ISSUE THREAD

**Issue by M-fil** [rolling-scopes-school/support#28]
Ссылка на деплой вашего проекта: https://m-fil.github.io/singolo/
Ссылка на репозиторий с проектом на GitHub: https://github.com/M-fil/singolo

Оценка в результате самопроверки, с ее аргументацией: 
Работа выполнена на 91 балл. 
Ошибки:
1) В секции About в описании Adam Jensen слово не перенесено на следующую строку. (-3 баллa).
2) сдвинулся Footer из-за кнопки submit в Get a Quote. (-3 балла).
3) Высота бейджей в секции Portfolio отличается больше чем на 2px.(-3 балла).

**Отзыв**
Прошу прощения за ошибку при первой попытке(((

- ширина макета не фиксированная (1024px);

Ваша оценка - 70 баллов 

Отзыв по пунктам ТЗ:

1) В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020: минус -10 баллов 

2) В коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020: минус -10 баллов 

3) В коммитах, или в ветках с коммитами, файлы singolo3.html и singolo3.сss или index.html и style.css отсутствуют до 09.03.2020: минус -10 баллов 

Общий балл в score: 84

**Comment by amoebiusss** [comment]
Оценка отличается от ожидаемой на 7 баллов, минимальная разница — 15.

https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f
