### ISSUE TITLE
Cross-Check museum - AV-63-dev

### ISSUE THREAD

**Issue by AV-63-dev** [rolling-scopes-school/support#280]
Deploy: https://rolling-scopes-school.github.io/av-63-dev-JSFEPRESCHOOL/museum/
Repository: https://github.com/rolling-scopes-school/av-63-dev-JSFEPRESCHOOL/tree/gh-pages
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/museum/museum.md
Form for verification: https://museum-stage0-cross-check.netlify.app/
Screenshot with review:
![image](https://user-images.githubusercontent.com/73535473/128457450-ecd57324-a1ab-48b5-a4ec-cae8c1468205.png)
My result: 83
![image](https://user-images.githubusercontent.com/73535473/128459701-7b5043bc-8ed1-4dab-a41c-9710b59db687.png)
Result  from Score: 55

**Comment by valerydluski** [comment]
Ваша оценка - 69 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) два элемента nav (основная и вспомогательная панель навигации) 

2) три списка ul > li > a (основная и вспомогательная панель навигации, ссылки на соцсети) 

3) одиннадцать кнопок button (шесть из них в секции Video, пять в секции Tickets) 

4) три тега input type="radio" (в секции Tickets) 

5) два тега input type="number"(в секции Tickets) 

6) два тега input type="range" (громкось и прогрес-бар видео) 

7) секция Video 

8) секция Tickets 

9) блок footer 

10) иконки добавлены в формате .svg. SVG может быть добавлен любым способом. Обращаем внимание на формат, а не на способ добавления 

11) изображения добавлены в формате .jpg, изображение карты добавлено в формате .png 
feedback: есть изображения в формате jpg
12) переключаются радиокнопки в блоке Tickets, одновременно может быть выбрана только одна кнопка 

Частично выполненные пункты:
1) изменение стиля интерактивных элементов при наведении и клике. Интерактивность включает в себя не только изменение внешнего вида курсора, например, при помощи свойства cursor: pointer, но и другие визуальные эффекты – изменение цвета фона или шрифта, появление подчёркивания и т.д. Если в макете указаны стили при наведении и клике, для элемента указываем эти стили, если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета 

2) интерактивность при наведении иконок социальных сетей в футере предусматривает изменение цвета иконки и круглой границы вокруг иконки на золотистый 

Выполненные пункты:
1) Вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." 

2) header, main, footer 

3) шесть элементов section (по количеству секций) 

4) только один заголовок h1 

5) шесть заголовков h2 (по количеству секций) 

6) шесть заголовков h3 (по количеству карточек) 

7) для всех элементов img указан обязательный атрибут alt 

8) блок header 

9) секция Welcome 

10) секция Visiting 

11) секция Explore 

12) секция Contacts 

13) для построения сетки используются флексы или гриды 

14) при уменьшении масштаба страницы браузера вёрстка размещается по центру, а не сдвигается в сторону 

15) фоновый цвет каждого блока и секции тянется на всю ширину страницы 

16) расстояние между буквами, там, где это требуется по макету, регулируется css-свойством letter-spacing 

17) фоновое изображение блока Welcome остаётся на своём месте даже если сильно уменьшить масштаб страницы 

18) плавная прокрутка по якорям 

19) обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике не влияющее на соседние элементы 

20) интерактивность при наведении карточек в секции Visiting предусматривает плавное растягивание подчёркивания заголовка карточки на всю ширину карточки

**Comment by AV-63-dev** [comment]
"Не выполненные/не засчитанные пункты:
два элемента nav (основная и вспомогательная панель навигации)
три списка ul > li > a (основная и вспомогательная панель навигации, ссылки на соцсети)"

один nav и ul > li > a - полноценные в header. Это тогда частично выполненные пункты?

**Comment by valerydluski** [comment]
вы не засамбитили правильную ссылку, я сразу не заметил. Такие апелляций не рассматриваются

**Comment by AV-63-dev** [comment]
А зачем тогда мне админы говорили про апелляцию?

**Comment by valerydluski** [comment]
видимо не знали про ссылку

**Comment by AV-63-dev** [comment]
ситуацию описывал как есть https://discord.com/channels/516715744646660106/604238535502856194/872393706035097660 трудно было не заменить, Конкретно с jegius общались потом лично. Он же инициатор ситуации когда студент оценил, а админ вмешался и изменил оценку.
Суть не в балах, вижу двойные стандарты. Предлагаю не тратить временя на ерундовую работу.
