### ISSUE TITLE
Cross-Check 'museum' - reido0

### ISSUE THREAD

**Issue by reido0** [rolling-scopes-school/support#281]
Deploy:  https://rolling-scopes-school.github.io/reido0-JSFEPRESCHOOL/museum/ 
Repository: https://github.com/rolling-scopes-school/reido0-JSFEPRESCHOOL/tree/gh-pages
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/museum/museum.md
Form for crosscheck: https://museum-stage0-cross-check.netlify.app/
<img width="1211" alt="Снимок экрана 2021-08-06 в 12 50 34" src="https://user-images.githubusercontent.com/81753427/128509852-f3805ab0-dba9-48b0-a2f7-f863cf0c5ddc.png">
Самооценка: 100/100 все пункты выполнены, есть незначительные отклонения при проверке PixelPerfect, но находятся в допустимых пределах. 
Не согласен с оценкой 88 балов последнего проверяющего, пункты за которые он снял балы не соответствуют действительности! Или он перепутал работы и фидбэки или намеренно снял просто так балы.
<img width="1267" alt="Снимок экрана 2021-08-06 в 12 58 40" src="https://user-images.githubusercontent.com/81753427/128510979-1482abca-cb40-4e63-b37f-29c83d25ba60.png">

**Comment by YuliyaMinsk** [comment]
Антон, тебе же выше 96 не смогут поставить, какой смысл в перепроверке?
Есть такой пункт в правилах: "В случае, когда полученная во время апелляции оценка отличается от оценки, полученной в шаге #4, менее чем на 10%, итоговая оценка повышаться не будет."

**Comment by reido0** [comment]
Добрый день. На счет этого пункта я знаю. Просто решил попробовать добиться справедливости, ведь в моем случае явная ошибка. Те пункты за которые снизил человек оценку не соответствуют действительности, это неправда. 

  
>Суббота, 7 августа 2021, 1:25 +03:00 от Yuliya Niaverava ***@***.***>:
> 
> 
>Антон, тебе же выше 96 не смогут поставить, какой смысл в перепроверке?
>Есть такой пункт в правилах: "В случае, когда полученная во время апелляции оценка отличается от оценки, полученной в шаге  #4 , менее чем на 10%, итоговая оценка повышаться не будет."
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android . 
 
 
--
Антон Mатвеев

**Comment by YuliyaMinsk** [comment]
Проверила работу, все пункты ТЗ выполнены. 
В частности кнопки Play на картинке с видео и на панели управления сделаны через тег button, с интерактивностью. При наведении курсора плавно меняют цвет ссылки, кнопки, иконки соцсетей, подчеркивания под заголовками карточек, даже радиокнопки в разделе Tikets и текст логотипа (картинка не меняет, но в критериях этого нету).

Единственное, что может вызвать вопросы - добавление иконок соцсетей через иконочные шрифты, но формально они загружаются также в .svg формате, так что критерии таска считаю выполненными.

Ваша оценка - 110 баллов из 110
Отзыв по пунктам ТЗ:
Выполненные пункты:
1) Вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." 

2) header, main, footer 

3) шесть элементов section (по количеству секций) 

4) только один заголовок h1 

5) шесть заголовков h2 (по количеству секций) 

6) шесть заголовков h3 (по количеству карточек) 

7) два элемента nav (основная и вспомогательная панель навигации) 

8) три списка ul > li > a (основная и вспомогательная панель навигации, ссылки на соцсети) 

9) одиннадцать кнопок button (шесть из них в секции Video, пять в секции Tickets) 

10) три тега input type="radio" (в секции Tickets) 

11) два тега input type="number"(в секции Tickets) 

12) два тега input type="range" (громкось и прогрес-бар видео) 

13) для всех элементов img указан обязательный атрибут alt 

14) блок header 

15) секция Welcome 

16) секция Visiting 

17) секция Explore 

18) секция Video 

19) секция Tickets 

20) секция Contacts 

21) блок footer 

22) для построения сетки используются флексы или гриды 

23) при уменьшении масштаба страницы браузера вёрстка размещается по центру, а не сдвигается в сторону 

24) фоновый цвет каждого блока и секции тянется на всю ширину страницы 

25) иконки добавлены в формате .svg. SVG может быть добавлен любым способом. Обращаем внимание на формат, а не на способ добавления 

26) изображения добавлены в формате .jpg, изображение карты добавлено в формате .png 

27) расстояние между буквами, там, где это требуется по макету, регулируется css-свойством letter-spacing 

28) фоновое изображение блока Welcome остаётся на своём месте даже если сильно уменьшить масштаб страницы 

29) переключаются радиокнопки в блоке Tickets, одновременно может быть выбрана только одна кнопка 

30) плавная прокрутка по якорям 

31) изменение стиля интерактивных элементов при наведении и клике. Интерактивность включает в себя не только изменение внешнего вида курсора, например, при помощи свойства cursor: pointer, но и другие визуальные эффекты – изменение цвета фона или шрифта, появление подчёркивания и т.д. Если в макете указаны стили при наведении и клике, для элемента указываем эти стили, если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета 

32) обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике не влияющее на соседние элементы 

33) интерактивность при наведении карточек в секции Visiting предусматривает плавное растягивание подчёркивания заголовка карточки на всю ширину карточки 

34) интерактивность при наведении иконок социальных сетей в футере предусматривает изменение цвета иконки и круглой границы вокруг иконки на золотистый
