### ISSUE TITLE
Cross-Check 'museum' - 'bartosh93'

### ISSUE THREAD

**Issue by bartosh93** [rolling-scopes-school/support#282]
https://rolling-scopes-school.github.io/bartosh93-JSFEPRESCHOOL/museum/
https://github.com/rolling-scopes-school/bartosh93-JSFEPRESCHOOL/tree/gh-pages/museum
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/museum/museum.md
 https://museum-stage0-cross-check.netlify.app/
![image](https://user-images.githubusercontent.com/47864515/128637933-ed0e0727-7f60-4024-8eb7-285cbe8f6ac6.png)
![image](https://user-images.githubusercontent.com/47864515/128637969-ebbdad2e-e729-4763-ad99-d6f9713f7bd5.png)
![image](https://user-images.githubusercontent.com/47864515/128637978-30d10a73-acbd-4efb-9509-da6241344f47.png)
![image](https://user-images.githubusercontent.com/47864515/128637995-d914093a-0008-4fb9-99a4-bc57f545daf3.png)
Согласен с оценкой проверяющих.

**Comment by valerydluski** [comment]
ваша оценка 76 баллов
