### ISSUE TITLE
Cross-Check 'vertical-slider' - 'Dmitriy-hello-world'

### ISSUE THREAD

**Issue by Dmitriy-hello-world** [rolling-scopes-school/support#283]
1) https://rolling-scopes-school.github.io/dmitriy-hello-world-JSFEPRESCHOOL/vertical-slider/
    2) https://github.com/rolling-scopes-school/dmitriy-hello-world-JSFEPRESCHOOL/tree/vertical-slider
    3) https://github.com/rolling-scopes-school/tasks/blob/master/tasks/js30/js30-3.md
    4) (требования к заданию) https://github.com/rolling-scopes-school/tasks/blob/master/tasks/js30/js30.md
    5) 
![1](https://user-images.githubusercontent.com/74368318/130982875-483d0148-d39b-4373-a943-2ae8489c5155.jpg)
![2](https://user-images.githubusercontent.com/74368318/130982897-fbc4e7a5-609b-41e4-826f-4c0fbf8930e5.jpg)
   6)  6.1) Разобраться в коде чужого проекта, понять его, воспроизвести исходное приложение - 10 баллов
        6.2) Дополнить исходный проект обязательным дополнительным функционалом - 10 баллов
        6.3) Дополнить исходный проект дополнительным функционалом на выбор:
              -пролистывание слайдера колёсиком мышки - 10 баллов
              -пролистывание слайдера не только кликами по кнопкам, но и свайпами мышки - 10 баллов 
              -слайдер работает автоматически каждые 6 секунд(таймер обновляется после перелистывания слайдов вручную)               - 10 баллов
       общий балл - 30/30 баллов
   7) 25

**Comment by irinainina** [comment]
25 баллов полностью заслужены. 
- Разобраться в коде чужого проекта, понять его, воспроизвести исходное приложение - 10 баллов
- Дополнить исходный проект обязательным дополнительным функционалом - не реализовано
- Дополнительный функционал на выбор
  - пролистывание слайдера колёсиком мышки - 5 баллов (пролистывает несколько слайдов за раз)
  - пролистывание слайдера не только кликами по кнопкам, но и свайпами мышки - 5 баллов  (пролистывает несколько слайдов за раз)
  - слайдер работает автоматически каждые 6 секунд - 5 баллов (работает хорошо, но по сложности значительно проще нереализованного обязательного дополнительного функционала)
 
 Итого - 25 баллов
