### ISSUE TITLE
Cross-Check js30 - mariaanisimova3091

### ISSUE THREAD

**Issue by mariaanisimova3091** [rolling-scopes-school/support#284]
Ссылка на деплой : https://boring-gates-640833.netlify.app/

Ссылка на репозиторий: https://github.com/rolling-scopes-school/mariaanisimova3091-JSFEPRESCHOOL/pull/3

Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/js30/js30.md#part1

Ссылка на форму для проверки проекта: https://js30-cross-check.netlify.app/

Скриншот с оценками за cross-check: <img width="1440" alt="Снимок экрана 2021-08-27 в 20 03 23" src="https://user-images.githubusercontent.com/76406235/131163462-59bbc85d-09d4-4b02-8769-b9d183acafdf.png">

Оценка в результате самопроверки с ее аргументацией : 30/30 
1. Часы работают и показывают верное время;
2. Выполнен  обязательный дополнительный функционал : точное время (часы минуты и секунды), полное название дня недели, дату (число и название месяца), год;
3.  Имеется дополнительный функционал:
- изменяются  картинки фона ( картинки ужала, пробовала по разному но плавность появляется примерно через минуту после того как картинки подгрузятся),
- плеер с проигрыванием расслабляющей мелодии.

Балл за cross-check из вашего Score: 15.

**Comment by irinainina** [comment]
Хорошая работа, хоть и не идеальная - стрелки часов изначально в неправильном положении и перескакивают на своё место на глазах пользователя, смена фона реализована некачественно, при смене фон дёргается, а должен сменяться плавно. Но основная проблема - неверная ссылка, из-за которой студенты не смогли проверить вашу работу. 
Насколько я знаю, такие работы на апелляции не рассматриваются. здесь ошибка не проверяющих, а автора работы.
