### ISSUE TITLE
Cross-Check 'CV' - 'Gricyan'

### ISSUE THREAD

**Issue by Gricyan** [rolling-scopes-school/support#285]
1. Deploy - https://gricyan.github.io/rsschool-cv/
2. Repository GitHub - https://github.com/Gricyan/rsschool-cv/tree/gh-pages
3. Task - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv.md
4. Check form - https://cv-stage1-cross-check.netlify.app/
5. ![Student 1 Check](https://user-images.githubusercontent.com/88500321/134129021-b23f6fa9-5a5d-465c-8678-7aa99a99ef34.jpg)

6. Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) есть видеорезюме автора CV на английском языке. Видеорезюме встраивается в страницу CV как видео, а не в виде кнопки или ссылки. Продолжительность видео 3-5 минут (±15 секунд). В описание видео на YouTube добавлена ссылка на его транскрипцию на английском языке (например, в документе Google Docs). 
feedback: Согласен, на данный момент видеорезюме отсутствует.

Частично выполненные пункты:
1) CV содержит пример вашего кода (например, решение задачи с сайта codewars) с подсветкой кода 
feedback: В описании таска https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/html-css.md указано, что CV должно содержать пример кода ИЛИ пример html-разметки, или ссылку на выполненный проект. Есть ссылки на проекты.

2) CV содержит изображения-ссылки на выполненные вами проекты. При клике по изображению страница проекта открывается в новой вкладке. У каждого проекта есть название, небольшое описание, указан перечень используемых технологий 
feedback: Подтверждаю, отсутствует описание, не добавил.

Выполненные пункты:
1) вёрстка валидная. Проверить валидность вёрстки: https://validator.w3.org/ 

2) вёрстка семантическая. В коде страницы присутствуют семантические теги HTML5, например, article, aside, figure, figcaption, footer, header, main, nav, section, используются заголовки h1-h6. 2 балла за каждый уникальный семантический тег HTML5 и за каждый уникальный заголовок h1-h6, но не больше 20 баллов. Заголовок h1 может быть только один 

3) для оформления СV используются css-стили. 1 балл за каждый стилизованный элемент, но не больше 10 баллов 

4) контент размещается в блоке, который горизонтально центрируется на странице. Фоновый цвет, если он есть, тянется во всю ширину страницы 

5) вёрстка адаптивная: ни на одном из разрешений экрана до 320px включительно не появляется горизонтальная полоса прокрутки, при этом всё содержание страницы сохраняется 

6) есть адаптивное бургер-меню. Ссылки в пунктах меню ведут на основные разделы CV. При кликах по пунктам меню реализована плавная прокрутка по якорям. При уменьшении ширины экрана меню становится адаптивным. 

7) на странице СV присутствует изображение - фото или аватарка автора CV, пропорции изображения не искажены, у изображения есть атрибут alt (может быть пустым) 

8) контакты для связи и перечень навыков оформлены в виде списка ul > li 

9) CV содержит контакты, краткую информацию о себе, навыки, образование, уровень английского 

10) CV выполнено на английском языке 

11) выполнены требования к репозиторию: есть ссылка на задание, скриншот страницы СV, ссылка на деплой страницы CV на GitHub Pages, указана дата дедлайна, выполнена самооценка (самооценку расписываем по пунктам критериев оценки, указывая балл за каждый пункт) 
feedback: Требования выполнены! Скриншоты прилагаются.

12) дизайн, оформление, качество выполнения CV не ниже чем в примерах CV, приведённых в материалах к заданию 
feedback: Считаю отзыв субъективным, поскольку не указано в чем именно ниже

7. Score - 140 баллов 
![Pull Request](https://user-images.githubusercontent.com/88500321/134132669-01466821-2c52-47e8-b12d-c1459944fe85.jpg)
![Pull Request description](https://user-images.githubusercontent.com/88500321/134132704-021341a7-65a9-4b0e-bc6b-d094d74e5206.jpg)

**Comment by valerydluski** [comment]
не попадает под правила апелляций

**Comment by Gricyan** [comment]
Добрый день. Все ок. Даже могу сказать спасибо этому человеку )), помог исправить ошибки. Однако, требования к репозиторию все же были выполнены.

**Comment by Gricyan** [comment]
Добрый вечер. Я понимаю, конечно же, что я в лучших стилях учебы в самый последний момент, даже последние минуты сабмитил задание. Ну так уж вышло. Хотелось сделать по больше и еще целая ночь впереди. Но в 1:58 оно меня уже не пустило. Живу в Варшаве, должно было. Но увы. Что делать? Планировал еще до утра доделать, однако наверное уже и смысла нет.






25 сентября 2021, 08:40:22, от "Valery" ***@***.***>:


не попадает под правила апелляций
