### ISSUE TITLE
Cross-Check CV - Marina2609

### ISSUE THREAD

**Issue by Marina2609** [rolling-scopes-school/support#286]
https://marina2609.github.io/rsschool-cv/
https://github.com/Marina2609/rsschool-cv
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv.md
https://cv-stage1-cross-check.netlify.app/
![Снимок 3](https://user-images.githubusercontent.com/78434449/134464686-8ae273c9-9ed8-4038-9f13-96f149fb7db5.PNG)
https://github.com/Marina2609/rsschool-cv/pull/3

**Comment by valerydluski** [comment]
с какой целью подаётся апелляция?

**Comment by Marina2609** [comment]
Здравствуйте!  Просто, я считаю, что мне не обоснованно занизили балл и скрыли свою личность. А так как я не имела возможности ответить этому человеку, я вам и написала. Можно её уже отменить. Четвертый человек меня проверил в последний момент. Спасибо!09:42, 25 сентября 2021 г., Valery ***@***.***>:
с какой целью подаётся апелляция?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

-- Отправлено из мобильного приложения Яндекс.Почты
