### ISSUE TITLE
Cross-Check 'CV' - 'ichernous94'

### ISSUE THREAD

**Issue by ichernous94** [rolling-scopes-school/support#287]
1. Deploy - https://ichernous94.github.io/rsschool-cv/
2. Repository GitHub - https://github.com/ichernous94/rsschool-cv
3. Task - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv.md
4. Check form - https://cv-stage1-cross-check.netlify.app/
5. ![](https://i2.paste.pics/4f12de5e29f5f9a918217625c97442ad.png)
6. 
  Не выполненные/не засчитанные пункты:
  1. CV содержит изображения-ссылки на выполненные вами проекты. При клике по изображению страница проекта открывается в новой вкладке. У каждого проекта есть название, небольшое описание, указан перечень используемых технологий
  2. есть видеорезюме автора CV на английском языке. Видеорезюме встраивается в страницу CV как видео, а не в виде кнопки или ссылки. Продолжительность видео 3-5 минут (±15 секунд). В описание видео на YouTube добавлена ссылка на его транскрипцию на английском языке (например, в документе Google Docs).

  Частично выполненные пункты:
  1. есть адаптивное бургер-меню. Ссылки в пунктах меню ведут на основные разделы CV. При кликах по пунктам меню реализована плавная прокрутка по якорям. При уменьшении ширины экрана меню становится адаптивным.
  Все остальные пункты выполнены.

7. Score: 130 / 160

**Comment by valerydluski** [comment]
ожидаемый балл отличается от оценки в скоре на 3 балла, это меньше 10%
