### ISSUE TITLE
Cross-Check CV - Alisa202023

### ISSUE THREAD

**Issue by Alisa202023** [rolling-scopes-school/support#289]
Добрый день. Я заболела сильно и забыла, что нужно было до 20 числа засабмитить задание на платформе. Задание выполнено было, но вот так вышло. Имеется справка. Возможно как-то получить баллы за это задание? 
Только в понедельник возможно закроют больничный.

Ссылка на deploy: https://Alisa202023.github.io/rsschool-cv/
Ссылка на репозиторий: https://github.com/Alisa202023/rsschool-cv
Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv.md
Форма для проверки проекта: https://cv-stage1-cross-check.netlify.app/

Буду рада обратной связи.

**Comment by irinainina** [comment]
Привет. 
Оценка за таск 100 баллов
Не выполненные пункты
- нет примера кода
- нет ссылок на выполненные проекты
- нет видеорезюме
- нет адаптивного бургер-меню

Частично выполненные пункты:
- адаптивность (контент прижат к краям экрана, номер телефона переносится на 5 строчек)
- контакты для связи и перечень навыков оформлены в виде списка ul > li (только перечень навыков оформлен по требованиям)
- выполнены требования к репозиторию (нет самооценки по пунктам)
- дизайн, оформление, качество выполнения CV не ниже чем в примерах CV, приведённых в материалах к заданию

**Comment by Alisa202023** [comment]
Спасибо большое))

сб, 25 сент. 2021 г., 09:37 Irina ***@***.***>:
