### ISSUE TITLE
Cross-Check Singolo - wayjewish

### ISSUE THREAD

**Issue by wayjewish** [rolling-scopes-school/support#29]
https://wayjewish.github.io/singolo/
https://github.com/wayjewish/singolo
Считаю что сделал на 100 баллов но не исключаю что что то упустил
Оценили на 96 баллов

На призыв проверяющим объявиться не ответили поэтому тут.

Student 2
h1 tag has display:none
**Сразу видно что человек в код не заглядывал, ибо h1 есть на странице и у него нет display: none, правда он скрыт другими стилями**

Student 3
Ваша оценка - 85 баллов
Отзыв по пунктам:
1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Portfolio составляют более двух пикселей (2px): минус -3 балла
**Не увидел отличий от макета как и другие проверяющие https://prnt.sc/rfv6s8**
2) На странице отсутствует элемент "< h1 >", либо на нём есть свойство display: none: минус -3 балла
**Про h1 тоже самое, в код не смотрел**
3) Социальные иконки в секции About без интерактивных стилей, при наведении на логотипы соц.сетей ничего не происходит: минус -3 балла
**Есть cursor: pointer; там**
4) Социальные иконки в Footer-e без интерактивных стилей, при наведении на логотипы соц.сетей ничего не происходит: минус -3 балла
**Есть cursor: pointer; там**
Не снимал баллы за то, что все находиться на левой стороне экрана.
**По заданию нет необходимости центрировать**

**Comment by amoebiusss** [comment]
Оценка отличается от ожидаемой на 4 балла, минимальная разница — 15.

https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f
