### ISSUE TITLE
Cross-Check 'CV' - 'AlexXG0152'

### ISSUE THREAD

**Issue by AlexXG0152** [rolling-scopes-school/support#290]
1. Deploy - https://alexxg0152.github.io/rsschool-cv/index
2. Repository - https://github.com/AlexXG0152/rsschool-cv
3. Task - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv.md
4. Check form - https://cv-stage1-cross-check.netlify.app/
5. ![Screenshot 2021-09-24](https://user-images.githubusercontent.com/34213814/134697806-747c5a54-c9c3-4c91-aeff-a3a9f10b5526.jpg)
6. Ваша оценка - 148.

Мой отзыв по пунктам ТЗ, информация о том, что не защитал автор кросс-чека ниже:
Не выполненные/не засчитанные пункты:
1) есть видеорезюме автора CV на английском языке. Видеорезюме встраивается в страницу CV как видео, а не в виде кнопки или ссылки. Продолжительность видео 3-5 минут (±15 секунд). В описание видео на YouTube добавлена ссылка на его транскрипцию на английском языке (например, в документе Google Docs). 

Частично выполненные:
1) CV содержит изображения-ссылки на выполненные вами проекты. При клике по изображению страница проекта НЕ открывается в новой вкладке. У каждого проекта есть название, небольшое описание, указан перечень используемых технологий. 
По собсвенной невнимательности убрал из <a> тега  " target='_blank' ", на что мне было справедливо указано в процессе кросс-чека 👍. Балл сам себе за это я снизил.  

Выполненные пункты:
1) вёрстка валидная. Проверить валидность вёрстки: https://validator.w3.org/ 

2) вёрстка семантическая. В коде страницы присутствуют семантические теги HTML5, например, article, aside, figure, figcaption, footer, header, main, nav, section, используются заголовки h1-h6. 2 балла за каждый уникальный семантический тег HTML5 и за каждый уникальный заголовок h1-h6, но не больше 20 баллов. Заголовок h1 может быть только один 

3) для оформления СV используются css-стили. 1 балл за каждый стилизованный элемент, но не больше 10 баллов 

4) контент размещается в блоке, который горизонтально центрируется на странице. Фоновый цвет, если он есть, тянется во всю ширину страницы 

5) вёрстка адаптивная: ни на одном из разрешений экрана до 320px включительно не появляется горизонтальная полоса прокрутки, при этом всё содержание страницы сохраняется 

6) есть адаптивное бургер-меню. Ссылки в пунктах меню ведут на основные разделы CV. При кликах по пунктам меню реализована плавная прокрутка по якорям. При уменьшении ширины экрана меню становится адаптивным. 

7) на странице СV присутствует изображение - фото или аватарка автора CV, пропорции изображения не искажены, у изображения есть атрибут alt (может быть пустым) 

8) контакты для связи и перечень навыков оформлены в виде списка ul > li 

9) CV содержит контакты, краткую информацию о себе, навыки, образование, уровень английского 

10) CV содержит пример вашего кода (например, решение задачи с сайта codewars) с подсветкой кода 

11) CV содержит изображения-ссылки на выполненные вами проекты. При клике по изображению страница проекта открывается в новой вкладке. У каждого проекта есть название, небольшое описание, указан перечень используемых технологий. (Выполнено частично по собслвенной невнимательности, убрал из <a> тега target="_blank" ).

12) CV выполнено на английском языке 

13) выполнены требования к репозиторию: есть ссылка на задание, скриншот страницы СV, ссылка на деплой страницы CV на GitHub Pages, указана дата дедлайна, выполнена самооценка (самооценку расписываем по пунктам критериев оценки, указывая балл за каждый пункт) 

14) дизайн, оформление, качество выполнения CV не ниже чем в примерах CV, приведённых в материалах к заданию 

***

Автор отзыва не засчитал следующие выполненные пункты, а также вместо 20 баллов за семантическую верстку поставил 10.
Не выполненные/не засчитанные пункты:

1) вёрстка адаптивная: ни на одном из разрешений экрана до 320px включительно не появляется горизонтальная полоса прокрутки, при этом всё содержание страницы сохраняется

2) есть адаптивное бургер-меню. Ссылки в пунктах меню ведут на основные разделы CV. При кликах по пунктам меню реализована плавная прокрутка по якорям. При уменьшении ширины экрана меню становится адаптивным.

3) CV содержит изображения-ссылки на выполненные вами проекты. При клике по изображению страница проекта открывается в новой вкладке. У каждого проекта есть название, небольшое описание, указан перечень используемых технологий

4) дизайн, оформление, качество выполнения CV не ниже чем в примерах CV, приведённых в материалах к заданию 

***

7. Score: 
   проверявшего:   90;
   мой:                    148.

Спасибо!

**Comment by irinainina** [comment]
Привет. Самооценка 148, балл за задание в score 148. причин для апелляции нет. 
Апелляция проводится только если ожидаемый вами балл и балл в score отличаются на 10 и более процентов.

**Comment by AlexXG0152** [comment]
Понял, спасибо
