### ISSUE TITLE
Cross-Check 'museum' - na1led

### ISSUE THREAD

**Issue by na1led** [rolling-scopes-school/support#293]
Деплой - https://rolling-scopes-school.github.io/na1led-JSFE2021Q3/
Репо - https://github.com/rolling-scopes-school/na1led-JSFE2021Q3
Задание - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/museum/museum-stage1.md
Успел замержить проект в gh-pages, но ссылка не добавлялась, вылезал 'An error ocurred' хоть я и успевал ее отправить, была еще минута до обновления кросс чека
Можно как то решить этот вопрос?

**Comment by irinainina** [comment]
Привет. Хорошая работа. Форму только нужно было выполнить как модальное окно - отображать и скрывать по клику. 
Мне действительно очень жаль, но эта работа не проходит по требованиям. На апелляцию подаются работы, в оценке которых ошиблись проверяющие. В данном случае ошибка не проверяющих, а твоя собственная
Цитирую ТЗ:
> Как сабмитить задание
> Засабмитить задание необходимо как можно раньше, как только в rs app появится такая возможность.

**Comment by na1led** [comment]
Понял, спасибо за объяснение
