### ISSUE TITLE
Cross-Check 'museum' - AndyGuit

### ISSUE THREAD

**Issue by AndyGuit** [rolling-scopes-school/support#294]
1. Deploy - https://rolling-scopes-school.github.io/andyguit-JSFEPRESCHOOL/museum/
2. Repository GitHub - https://github.com/rolling-scopes-school/andyguit-JSFEPRESCHOOL/tree/museum
3. Task - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/museum/museum-stage1.md
4. Check form - https://museum-cross-check.netlify.app/
5.
![Screenshot_313](https://user-images.githubusercontent.com/77016285/135475013-0df419fc-f513-4b19-becb-08a8840d28eb.jpg)
 
6.  Ваша оценка - 158 баллов 
Отзыв по пунктам ТЗ:
Частично выполненные пункты:
1) в футере добавлены ссылки на соцсети. Круглая граница вокруг иконок соцсетей выполнена при помощи css 

2) кнопке "Book" в форме покупки билетов добавлен ripple-эффект. Демо: https://50projects50days.com/projects/button-ripple-effect/ 

Выполненные пункты:
1) Вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." 

2) header, main, footer 

3) семь элементов section (по количеству секций) 

4) только один заголовок h1 

5) семь заголовков h2 (по количеству секций) 

6) шесть заголовков h3 (по количеству карточек) 

7) два элемента nav (основная и вспомогательная панель навигации) 

8) три списка ul > li > a (основная и вспомогательная панель навигации, ссылки на соцсети) 

9) тринадцать кнопок button (четыре из них в секции Video, пять в секции Tickets, по две - стрелки слайдера и плейлиста) 

10) три тега input type="radio" (в секции Tickets) 

11) два тега input type="number"(в секции Tickets) 

12) два тега input type="range" (громкось и прогрес-бар видео) 

13) для всех элементов img указан обязательный атрибут alt 

14) блок header 

15) секция Welcome 

16) секция Visiting 

17) секция Explore 

18) секция Video 

19) секция Gallery 

20) секция Tickets 

21) секция Contacts 

22) блок footer 

23) форма плавно выдвигается слева при открытии и плавно возвращается назад при закрытии. В открытом состоянии под формой есть полупрозрачный overlay, который занимает весь экран. Форма и overlay прокручиваются вместе со страницей 

24) форма открывается при клике по кнопке Buy Now в секции Tickets и закрывается кликом по иконке с крестиком в верхнем правом углу или кликом по overlay 

25) при вёрстке формы используются следующие элементы: form, input type="date", input type="time", input type="text", input type="email", input type="tel", input type="number", select 

26) вёрстка формы соответствует макету 

27) добавлен favicon 

28) для построения сетки используются флексы или гриды 

29) при уменьшении масштаба страницы браузера вёрстка размещается по центру, а не сдвигается в сторону 

30) фоновый цвет каждого блока и секции тянется на всю ширину страницы 

31) иконки добавлены в формате .svg. SVG может быть добавлен любым способом. Обращаем внимание на формат, а не на способ добавления 

32) расстояние между буквами, там, где это требуется по макету, регулируется css-свойством letter-spacing 

33) переключаются радиокнопки в блоке Tickets, одновременно может быть выбрана только одна кнопка 

34) в блоке Contacts правильно указанны ссылки на почту mailto и на телефон tel 

35) плавная прокрутка по якорям 

36) параллакс 

37) при кликам по кнопке Discover the Louvre и карточкам секции Visiting открываются полноэкранные панорамы Google Street View встроенные в страницы вашего сайта при помощи iframe 

38) изменение стиля интерактивных элементов при наведении и клике. Интерактивность включает в себя не только изменение внешнего вида курсора, например, при помощи свойства cursor: pointer, но и другие визуальные эффекты – изменение цвета фона или шрифта, появление подчёркивания и т.д. Если в макете указаны стили при наведении и клике, для элемента указываем эти стили, если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета 

39) обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике не влияющее на соседние элементы 

40) интерактивность при наведении карточек в секции Visiting предусматривает плавное растягивание подчёркивания заголовка карточки на всю ширину карточки 

41) интерактивность при наведении иконок социальных сетей в футере предусматривает изменение цвета иконки и круглой границы вокруг иконки на золотистый 

42) можно передвигать ползунки громкости и прогресс-бара видео, при этом цвет шкалы до и после ползунка отличается и соответствует макету 

43) кликами по кнопкам + и - в секции Tiskets можно менять количество билетов Basic и Senior от 0 до 20 

44) при перезагрузке (обновлении) страницы картины в блоке Galery отображаются в рандомном порядке 

7. меньше 150

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/135512751-2d2582db-dedf-4d04-93b7-a7f31844dfa9.png)

**Comment by irinainina** [comment]
Привет! 150 баллов из 150 возможных. 
Отличная работа, заслужено высокий балл, но в апелляции нет смысла.

**Comment by AndyGuit** [comment]
> 
> 
> Привет! 150 баллов из 150 возможных. Отличная работа, заслужено высокий балл, но в апелляции нет смысла.

Да, в score как раз пошло 150. Думал будет меньше, обидно было бы, т.к. я очень старался)
