### ISSUE TITLE
Pull Request Name

### ISSUE THREAD

**Issue by rsaldiny** [rolling-scopes-school/support#3]
When I created Pull Request I used the name PULL REQUEST IS CREATED. I did not use the name GIT&Markdown. I created PULL request correctly, I believe that the mark should be corrected because all requirements are met, but the name is only thing that was not mentioned in the exercise. It did not say that we need to create specific name for the pull request.

**Comment by NiksRakevich** [comment]
Hello @rsaldiny ,
This task contains PR requirements (please see the screenshot below) that require task name in the PR.
![image](https://user-images.githubusercontent.com/32455265/74662596-48bfac80-51ab-11ea-8570-71bcc226f22c.png)
Read the tasks more carefully.
Thank you,
Nikita.
