### ISSUE TITLE
Cross-Check Singolo - creator674

### ISSUE THREAD

**Issue by Creator674** [rolling-scopes-school/support#30]
Считаю что сделал минимум на 90 баллов, но не исключаю что, что-то упустил:

` Student 2:`
` файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020, ставим -10.`
**(тут вроде согласен, но вроде помню что дедлайн был 4-ого, хотя в доках действительно написано что второго)**
` Если в коммитах, или в ветках с коммитами, файлы singolo3.html и singolo3.сss или index.html и style.css отсутствуют до 09.03.2020, ставим -10.`
**(файлы присутствуют до 9 марта, полностью сделаный проект тоже)**
` Все съезжает в 5 блоках - 15`
**(у меня все ровно, не знаю как он смотрел)**
` Header:`
`кнопка Home всегда выделена - 3`
**(нет, она просто другого цвета)**
` Our service - нет одной иконки и шрифт не тот - 3`
**(все иконки и шрифты правильные)**
` Get a Quote - им не валидируется - 3`
**(чаво?:D)**

`Student 1`
`Ваша оценка - 85 баллов `
`Отзыв по пунктам ТЗ:`
`1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Header составляют более двух пикселей (2px): минус -3 балла `
**(Не согласен, у меня все красиво и на своём месте, возможно это про буквы, но если не ошибаюсь, съезд буквами разрешен в строке, но сама строка на месте)**
`2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла `
**(Не согласен, у меня все красиво и на своём месте, возможно это про буквы, но если не ошибаюсь, съезд буквами разрешен в строке, но сама строка на месте)**
`3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла `
**(Не согласен, у меня все красиво и на своём месте, возможно это про буквы, но если не ошибаюсь, съезд буквами разрешен в строке, но сама строка на месте)**
`4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла `
**(Не согласен, у меня все красиво и на своём месте, возможно это про буквы, но если не ошибаюсь, съезд буквами разрешен в строке, но сама строка на месте)**
`5) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции About: минус -3 балла `
**(Тут соглашусь, есть недочет)**

**Comment by Sannnao** [comment]
Student 2:
1. По первому - справедливо.  -10
2. По второму такая же история. Нет файлов singolo3.html и singolo3.сss или index.html и style.css ни в одной из веток.  -10
3. https://prnt.sc/rg0znq - это не ровно. Но только в двух блоках. Справедливо. -6
4. Не справедливо. Просто на макете это подразумевалось как цвет с hover, думаю тут не стоит снимать.
5. Не справедливо. Иконки все есть, шрифт правильный.
6. Не справедливо. Все валидируется.
Student 1:
1. Не справедливо. Шрифты могут не совпадать (хотя на самом деле легко фиксятся с помощью letter-spacing);
2. Справедливо. Иконки можно было подогнать идеально при желании https://prnt.sc/rg18e0. -3
3. Не справедливо. В секции About разбежка максимум 1 пиксель.
4. Не справедливо. Никаких различий нет (кроме шрифтов)
5. Справедливо. -3

**Comment by Creator674** [comment]
Student 2: 
2. Т. К. В 3 части задания png и jpg файлы были полным макетом, я объединил 1 и 2 части сразу, и начал делать третью вместе с ними, а не отдельно. (Или же все-таки так нельзя) …

**Comment by Sannnao** [comment]
Да, я понимаю что по факту задание выполнено, но:
- допустим проверяющий заходит, смотрит что этих файлов нет (которые кстати требуются по заданию) - ему нужно догаться что они у тебя в файле с другим именем лежат, догадаться в каком именно конечный результат. 
- Если есть требование к заданию сделать файлы с определенным именем, то это требование надо соблюдать, тем более в условиях беспощадного кроссчека.
- Нейминг в программировании - это очень важно. Тебе кажется что вроде ничего не произошло, а это вызвало лютое неудобство и путаницу. Я считаю это справедливый минус

**Comment by Sannnao** [comment]
Это пока не окончательная оценка, выясняю как поступить в этой ситуации

**Comment by Sannnao** [comment]
> Все съезжает в 5 блоках - 15
> (у меня все ровно, не знаю как он смотрел)
- В обоих случаях люди смотрели твой файл из gh-pages, опять про путаницу в файлах, которую уже обсудили. Я сам 10 минут потратил что бы найти нужный файл (а если учесть что изначально проверил не тот файл - то несколько часов)

  В итоге -10 за все. Думаю справедливо.
