### ISSUE TITLE
Cross-Check 'museum-adaptive' - 'Dmitriy-hello-world'

### ISSUE THREAD

**Issue by Dmitriy-hello-world** [rolling-scopes-school/support#300]
1. https://rolling-scopes-school.github.io/dmitriy-hello-world-JSFE2021Q3/museum-adaptive/
2. https://github.com/rolling-scopes-school/dmitriy-hello-world-JSFE2021Q3/tree/museum-adaptive
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/museum/museum-adaptive.md
4. https://museum-adaptive-cross-check.netlify.app/
5.
![1](https://user-images.githubusercontent.com/74368318/136547406-1e52d2ed-300a-4315-ba24-84038081dada.jpg)
![2](https://user-images.githubusercontent.com/74368318/136547408-30486024-337d-4905-90e8-2ca58ae5df37.jpg)
![3](https://user-images.githubusercontent.com/74368318/136547411-9b9da11c-7c37-4170-9c3a-a4d8a73875fa.jpg)
![4](https://user-images.githubusercontent.com/74368318/136547414-d5113183-f163-4953-8f13-c1a40eb66f3f.jpg)
6.  Моя оценка - 149 баллов из 160 баллов
  Не выполненные/не засчитанные пункты:

  1) кастомного видеоплеера в секции `Video` 
  2) слайдера в секции `Video` 
  3) YouTube-видео в плейлисте в секции `Video`, маленькие видео выровнены по краям большого 
  4) галереи изображений и изображений в ней   

  Частично выполненные пункты:

  1) слайдера в секции `Welcome` 
  2) слайдера сравнения изображений в секции `Explore` 
  3) карты 
 
  Выполненные пункты:
  1) Блок header 
  2) Секция Welcome 
  3) Секция Visiting 
  4) Секция Explore 
  5) Секция Video 
  6) Секция Gallery 
  7) Секция Tickets 
  8) Форма покупки билетов 
  9) Секция Contacts 
  10) Блок footer  
  11) Блок header 
  12) Секция Welcome 
  13) Секция Visiting 
  14) Секция Explore 
  15) Секция Video 
  16) Секция Gallery 
  17) Секция Tickets 
  18) Форма покупки билетов 
  19) Секция Contacts 
  20) Блок footer  
  21) Блок header 
  22) Секция Welcome 
  23) Секция Visiting 
  24) Секция Explore 
  25) Секция Video 
  26) Секция Gallery 
  27) Секция Tickets 
  28) Форма покупки билетов 
  29) Секция Contacts 
  30) Блок footer  
  31) Ни на одном из разрешений до 320px включительно не появляется горизонтальная полоса прокрутки,  элементы не должны скрываться, обрезаться, наезжать друг на друга, если это не предусмотрено макетом. 
  32) при нажатии на бургер-иконку меню появляется, плавно выдвигаясь слева, бургер-иконка изменяется на крестик. При нажатии на крестик меню исчезает, плавно возвращаясь назад, иконка крестика превращается в бургер-иконку 
  33) ссылки в меню работают, обеспечивая плавную прокрутку по якорям 
  34) при клике по ссылке в адаптивном меню, или при клике по любому месту сайта, кроме самого адаптивного меню, меню закрывается 
  35) вёрстка меню соответствует макету на всех проверяемых разрешениях 
  36) Результат проверки скорости сайта для мобильных устройств: 0 to 49 (red): Poor - не выполнено 0 ,баллов; 50 to 89 (orange): Needs Improvement - частично выполнено - 4 баллов; 90 to 100 (green): Good - выполнено полностью - 8 баллов 
7. score: 134

**Comment by AlekseyVY** [comment]
/// Итого: 122 балла.


Ваша оценка - 122 балла 
Отзыв по пунктам ТЗ:
Частично выполненные пункты:
1) Блок header 

2) Секция Welcome 

3) Секция Visiting 

4) Секция Explore 

5) Секция Video 

6) Секция Gallery 

7) Секция Tickets 

8) Форма покупки билетов 

9) Секция Contacts 

10) Блок footer  

11) Секция Welcome 

12) Секция Visiting 

13) Секция Video 

14) Секция Gallery 

15) Секция Tickets 

16) Блок footer  

17) Секция Welcome 

18) Секция Visiting 

19) Секция Gallery 

Выполненные пункты:
1) Блок header 

2) Секция Explore 

3) Форма покупки билетов 

4) Секция Contacts 

5) Блок header 

6) Секция Explore 

7) Секция Video 

8) Секция Tickets 

9) Форма покупки билетов 

10) Секция Contacts 

11) Блок footer  

12) Ни на одном из разрешений до 320px включительно не появляется горизонтальная полоса прокрутки,  элементы не должны скрываться, обрезаться, наезжать друг на друга, если это не предусмотрено макетом. 

13) слайдера в секции `Welcome` 

14) слайдера сравнения изображений в секции `Explore` 

15) кастомного видеоплеера в секции `Video` 

16) слайдера в секции `Video` 

17) YouTube-видео в плейлисте в секции `Video`, маленькие видео выровнены по краям большого 

18) галереи изображений и изображений в ней 

19) карты 

20) при нажатии на бургер-иконку меню появляется, плавно выдвигаясь слева, бургер-иконка изменяется на крестик. При нажатии на крестик меню исчезает, плавно возвращаясь назад, иконка крестика превращается в бургер-иконку 

21) ссылки в меню работают, обеспечивая плавную прокрутку по якорям 

22) при клике по ссылке в адаптивном меню, или при клике по любому месту сайта, кроме самого адаптивного меню, меню закрывается 

23) вёрстка меню соответствует макету на всех проверяемых разрешениях 

24) Результат проверки скорости сайта для мобильных устройств: 0 to 49 (red): Poor - не выполнено 0 ,баллов; 50 to 89 (orange): Needs Improvement - частично выполнено - 4 баллов; 90 to 100 (green): Good - выполнено полностью - 8 баллов

**Comment by Dmitriy-hello-world** [comment]
То-есть я правильно понимаю, что согласно правилам школы указанным в документации, а именно:
![image](https://user-images.githubusercontent.com/74368318/137391558-4efa18bb-415e-4c51-8f55-087a0a0f9e38.png)
Оценка не отличается более чем на 10% и соответственно изменения не произойдут ?
