### ISSUE TITLE
Cross-Check 'museum-adaptive' - 'ereticor'

### ISSUE THREAD

**Issue by ereticor** [rolling-scopes-school/support#302]
Ссылка на деплой вашего проекта - https://rolling-scopes-school.github.io/ereticor-JSFE2021Q3/museum/
    Ссылка на репозиторий с проектом на GitHub - https://github.com/rolling-scopes-school/ereticor-JSFE2021Q3.git
    Ссылка на задание - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/museum/museum-adaptive.md
    Ссылка на форму для проверки проекта (если такая есть) - https://museum-adaptive-cross-check.netlify.app/
    Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты) - одна оценка
![изображение](https://user-images.githubusercontent.com/79747854/136567393-cc45b8f3-8ad6-46d4-a3bf-2c1f6a30f935.png)

    Оценка в результате самопроверки с ее аргументацией - 154 балла (152 если учитывать отхождение ссылок в footer на разрешениях менее 350px)
    Вёрстка соответствует макету. Ширина экрана 1024px +40
Блок header +4
Секция Welcome +4
Секция Visiting +4
Секция Explore +4
Секция Video +4
Секция Gallery +4
Секция Tickets +4
Форма покупки билетов +4
Секция Contacts +4
Блок footer +4

Вёрстка соответствует макету. Ширина экрана 768px +40
Блок header +4
Секция Welcome +4
Секция Visiting +4
Секция Explore +4
Секция Video +4
Секция Gallery +4
Секция Tickets +4
Форма покупки билетов +4
Секция Contacts +4
Блок footer +4

Вёрстка соответствует макету. Ширина экрана 420px +40
Блок header +4
Секция Welcome +4
Секция Visiting +4
Секция Explore +4
Секция Video +4
Секция Gallery +4
Секция Tickets +4
Форма покупки билетов +4
Секция Contacts +4
Блок footer +4
Ни на одном из разрешений до 320px включительно не появляется горизонтальная полоса прокрутки +6
Совмещается адаптивная и респонсивная (резиновая) вёрстка +12 При изменении ширины экрана плавно изменяются размеры:
слайдера в секции Welcome +2
слайдера сравнения изображений в секции Explore +2
кастомного видеоплеера в секции Video +0
слайдера в секции Video +2
YouTube-видео в плейлисте в секции Video, маленькие видео выровнены по краям большого +2
галереи изображений и изображений в ней +2
карты +2

На ширине экрана 1024рх и меньше реализовано адаптивное меню +12
    при нажатии на бургер-иконку меню появляется, плавно выдвигаясь слева, бургер-иконка изменяется на крестик. При нажатии на крестик меню исчезает, плавно возвращаясь назад, иконка крестика превращается в бургер-иконку +2
    ссылки в меню работают, обеспечивая плавную прокрутку по якорям +2
    при клике по ссылке в адаптивном меню, или при клике по любому месту сайта, кроме самого адаптивного меню, меню закрывается +2
    вёрстка меню соответствует макету на всех проверяемых разрешениях +6
Оптимизация скорости загрузки страницы +4 Результат проверки скорости сайта для мобильных устройств:
    0 to 49 (red): Poor - не выполнено, 0 баллов
    50 to 89 (orange): Needs Improvement - частично выполнено +4
    90 to 100 (green): Good - выполнено полностью +0

    Балл за cross-check из вашего Score - 118

**Comment by ereticor** [comment]
Вторая оценка за крос-чек (через два или три дня после дедлайна)
![изображение](https://user-images.githubusercontent.com/79747854/137112136-fa2b34e7-5d3e-4156-95ca-117f060c9566.png)

**Comment by valerydluski** [comment]
Ну учитывая, что я тоже смотрел работу видимо да
