### ISSUE TITLE
Cross-Check 'museum-adaptive' - 'jirafek'

### ISSUE THREAD

**Issue by Jirafek** [rolling-scopes-school/support#304]
1. Ссылка на деплой вашего проекта: https://rolling-scopes-school.github.io/jirafek-JSFE2021Q3/museum-adaptive/
2. Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/jirafek-JSFE2021Q3/tree/museum-adaptive
3. Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/museum/museum-adaptive.md
4. Ссылка на форму для проверки проекта: https://museum-adaptive-cross-check.netlify.app
5. Скриншот с оценками за cross-check:
![Снимок экрана 2021-10-08 в 18 20 53](https://user-images.githubusercontent.com/86237844/136582645-3f178ed2-3253-4758-9f2c-c9f8e0d5249f.png)
![Снимок экрана 2021-10-08 в 18 21 09](https://user-images.githubusercontent.com/86237844/136582692-300872c7-8ee2-4563-aa9f-851d3a8fb08c.png)
6. 
Оценка в результате самопроверки с ее аргументацией:
Ваша оценка - 68 баллов
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
    Форма покупки билетов

    Секция Visiting

    Секция Explore

    Секция Tickets

    Форма покупки билетов

    Секция Welcome

    Секция Visiting

    Секция Explore

    Секция Video

    Секция Gallery

    Секция Tickets

    Форма покупки билетов

    Блок footer

    Ни на одном из разрешений до 320px включительно не появляется горизонтальная полоса прокрутки, элементы не должны скрываться, обрезаться, наезжать друг на друга, если это не предусмотрено макетом.

    слайдера в секции Welcome

    кастомного видеоплеера в секции Video

    слайдера в секции Video

    карты

    при клике по ссылке в адаптивном меню, или при клике по любому месту сайта, кроме самого адаптивного меню, меню закрывается

    Результат проверки скорости сайта для мобильных устройств: 0 to 49 (red): Poor - не выполнено 0 ,баллов; 50 to 89 (orange): Needs Improvement - частично выполнено - 4 баллов; 90 to 100 (green): Good - выполнено полностью - 8 баллов

Частично выполненные пункты:

    Секция Explore

    Секция Video

    Блок footer

    Секция Welcome

    Секция Video

    Секция Gallery

    YouTube-видео в плейлисте в секции Video, маленькие видео выровнены по краям большого

    вёрстка меню соответствует макету на всех проверяемых разрешениях

Выполненные пункты:

    Блок header

    Секция Welcome

    Секция Visiting

    Секция Gallery

    Секция Tickets

    Секция Contacts

    Блок header

    Секция Contacts

    Блок footer

    Блок header

    Секция Contacts

    слайдера сравнения изображений в секции Explore

    галереи изображений и изображений в ней

    при нажатии на бургер-иконку меню появляется, плавно выдвигаясь слева, бургер-иконка изменяется на крестик. При нажатии на крестик меню исчезает, плавно возвращаясь назад, иконка крестика превращается в бургер-иконку

    ссылки в меню работают, обеспечивая плавную прокрутку по якорям
7. Балл за cross-check из вашего Score: 27
    Сделал issue заново, правильно. Мне один студент дал 22 бала с которыми я точно не согласен, и общий скор за museum-adaptive получился 27.

**Comment by AlekseyVY** [comment]
/// Итого: 11 баллов.


Ваша оценка - 11 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Секция Welcome 

2) Секция Visiting 

3) Секция Explore 

4) Секция Video 

5) Секция Gallery 

6) Секция Tickets 

7) Форма покупки билетов 

8) Секция Contacts 

9) Блок footer  

10) Секция Welcome 

11) Секция Visiting 

12) Секция Explore 

13) Секция Video 

14) Секция Gallery 

15) Секция Tickets 

16) Форма покупки билетов 

17) Секция Contacts 

18) Блок footer  

19) Блок header 

20) Секция Welcome 

21) Секция Visiting 

22) Секция Explore 

23) Секция Video 

24) Секция Gallery 

25) Секция Tickets 

26) Форма покупки билетов 

27) Секция Contacts 

28) Блок footer  

29) Ни на одном из разрешений до 320px включительно не появляется горизонтальная полоса прокрутки,  элементы не должны скрываться, обрезаться, наезжать друг на друга, если это не предусмотрено макетом. 

30) слайдера в секции `Welcome` 

31) слайдера сравнения изображений в секции `Explore` 

32) кастомного видеоплеера в секции `Video` 

33) слайдера в секции `Video` 

34) YouTube-видео в плейлисте в секции `Video`, маленькие видео выровнены по краям большого 

35) галереи изображений и изображений в ней 

36) карты 

37) вёрстка меню соответствует макету на всех проверяемых разрешениях 

38) Результат проверки скорости сайта для мобильных устройств: 0 to 49 (red): Poor - не выполнено 0 ,баллов; 50 to 89 (orange): Needs Improvement - частично выполнено - 4 баллов; 90 to 100 (green): Good - выполнено полностью - 8 баллов 

Частично выполненные пункты:
1) при нажатии на бургер-иконку меню появляется, плавно выдвигаясь слева, бургер-иконка изменяется на крестик. При нажатии на крестик меню исчезает, плавно возвращаясь назад, иконка крестика превращается в бургер-иконку 

2) ссылки в меню работают, обеспечивая плавную прокрутку по якорям 

3) при клике по ссылке в адаптивном меню, или при клике по любому месту сайта, кроме самого адаптивного меню, меню закрывается 

Выполненные пункты:
1) Блок header 

2) Блок header
