### ISSUE TITLE
Cross-Check 'Momentum' - 'helacyan'

### ISSUE THREAD

**Issue by helacyan** [rolling-scopes-school/support#310]
1. https://helacyan-momentum.netlify.app/?#
2.  https://github.com/rolling-scopes-school/helacyan-JSFE2021Q3/tree/momentum - приватный репозиторий, изменений в деплой после дедлайна внесено не было
![](https://i.imgur.com/YrmNdgo.png)
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/momentum/momentum-stage1.md
4. https://momentum-crosscheck.netlify.app
5. ![](https://i.imgur.com/wNNqGFy.png) и ![](https://i.imgur.com/YHOGv9D.png)
6. 
Оценка - 141/150 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) изображения перелистываются по кругу: после двадцатого изображения идёт первое (клик по правой стрелке), перед 1 изображением идёт 20 (клик по левой стрелке) 

2) ToDo List - список дел (как в оригинальном приложении) или Список ссылок (как в оригинальном приложении) или Свой собственный дополнительный функционал, по сложности аналогичный предложенным 

Частично выполненные пункты:
1) изображения можно перелистывать кликами по стрелкам, расположенным по бокам экрана.Изображения перелистываются последовательно - после 18 изображения идёт 19 (клик по правой стрелке), перед 18 изображением идёт 17 (клик по левой стрелке) 

2) переводится приветствие и placeholder 

Выполненные пункты:
1) время выводится в 24-часовом формате, например: 21:01:00 

2) время обновляется каждую секунду - часы идут. Когда меняется одна из цифр, остальные при этом не меняют своё положение на странице (время не дёргается) 

3) выводится день недели, число, месяц, например: "Воскресенье, 16 мая" / "Sunday, May 16" / "Нядзеля, 16 траўня" 

4) текст приветствия меняется в зависимости от времени суток (утро, день, вечер, ночь). Проверяется соответствие приветствия текущему времени суток 

5) пользователь может ввести своё имя. При перезагрузке страницы приложения имя пользователя сохраняется 

6) ссылка на фоновое изображение формируется с учётом времени суток и случайного номера изображения (от 01 до 20). Проверяем, что при перезагрузке страницы фоновое изображение изменилось. Если не изменилось, перезагружаем страницу ещё раз 

7) при смене слайдов важно обеспечить плавную смену фоновых изображений. Не должно быть состояний, когда пользователь видит частично загрузившееся изображение или страницу без фонового изображения. Плавную смену фоновых изображений не проверяем: 1) при загрузке и перезагрузке страницы 2) при открытой консоли браузера 3) при слишком частых кликах по стрелкам для смены изображения 

8) при перезагрузке страницы приложения указанный пользователем город сохраняется, данные о нём хранятся в local storage 

9) для указанного пользователем населённого пункта выводятся данные о погоде, если их возвращает API. Данные о погоде включают в себя: иконку погоды, описание погоды, температуру в °C, скорость ветра в м/с, относительную влажность воздуха в %. Числовые параметры погоды округляются до целых чисел 

10) выводится уведомление об ошибке при вводе некорректных значений, для которых API не возвращает погоду (пустая строка или бессмысленный набор символов) 

11) при загрузке страницы приложения отображается рандомная цитата и её автор 

12) при перезагрузке страницы цитата обновляется (заменяется на другую). Есть кнопка, при клике по которой цитата обновляется (заменяется на другую) 

13) при клике по кнопке Play/Pause проигрывается первый трек из блока play-list, иконка кнопки меняется на Pause 

14) при клике по кнопке Play/Pause во время проигрывания трека, останавливается проигрывание трека, иконка кнопки меняется на Play 

15) треки пролистываются по кругу - после последнего идёт первый (клик по кнопке Play-next), перед первым - последний (клик по кнопке Play-prev) 

16) трек, который в данный момент проигрывается, в блоке Play-list выделяется стилем 

17) после окончания проигрывания первого трека, автоматически запускается проигрывание следующего. Треки проигрываются по кругу: после последнего снова проигрывается первый. 

18) добавлен прогресс-бар в котором отображается прогресс проигрывания 

19) при перемещении ползунка прогресс-бара меняется текущее время воспроизведения трека 

20) над прогресс-баром отображается название трека 

21) отображается текущее и общее время воспроизведения трека 

22) есть кнопка звука при клике по которой можно включить/отключить звук 

23) добавлен регулятор громкости, при перемещении ползунка регулятора громкости меняется громкость проигрывания звука 

24) можно запустить и остановить проигрывания трека кликом по кнопке Play/Pause рядом с ним в плейлисте 

25) переводится язык и меняется формат отображения даты 

26) переводится прогноз погоды в т.ч описание погоды и город по умолчанию 

27) переводится цитата дня т.е цитата отображается на текущем языке приложения. Сама цитата может быть другая 

28) переводятся настройки приложения, при переключении языка приложения в настройках, язык настроек тоже меняется 

29) в качестве источника изображений может использоваться Unsplash API 

30) в качестве источника изображений может использоваться Flickr API 

31) в настройках приложения можно указать язык приложения (en/ru или en/be)  

32) в настройках приложения можно указать источник получения фото для фонового изображения: коллекция изображений GitHub, Unsplash API, Flickr API 

33) если источником получения фото указан API, в настройках приложения можно указать тег/теги, для которых API будет присылает фото 

34) в настройках приложения можно скрыть/отобразить любой из блоков, которые находятся на странице: время, дата, приветствие, цитата дня, прогноз погоды, аудиоплеер, список дел/список ссылок/ваш собственный дополнительный функционал 

35) Скрытие и отображение блоков происходит плавно, не влияя на другие элементы, которые находятся на странице, или плавно смещая их 

36) настройки приложения сохраняются при перезагрузке страницы 

7. Балл за cross-check из Score - 108/150

**Comment by AlekseyVY** [comment]
Ваша оценка - 143.5 балла 


Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) время выводится в 24-часовом формате, например: 21:01:00 

2) ToDo List - список дел (как в оригинальном приложении) или Список ссылок (как в оригинальном приложении) или Свой собственный дополнительный функционал, по сложности аналогичный предложенным 

Частично выполненные пункты:
1) можно запустить и остановить проигрывания трека кликом по кнопке Play/Pause рядом с ним в плейлисте 

Выполненные пункты:
1) время обновляется каждую секунду - часы идут. Когда меняется одна из цифр, остальные при этом не меняют своё положение на странице (время не дёргается) 

2) выводится день недели, число, месяц, например: "Воскресенье, 16 мая" / "Sunday, May 16" / "Нядзеля, 16 траўня" 

3) текст приветствия меняется в зависимости от времени суток (утро, день, вечер, ночь). Проверяется соответствие приветствия текущему времени суток 

4) пользователь может ввести своё имя. При перезагрузке страницы приложения имя пользователя сохраняется 

5) ссылка на фоновое изображение формируется с учётом времени суток и случайного номера изображения (от 01 до 20). Проверяем, что при перезагрузке страницы фоновое изображение изменилось. Если не изменилось, перезагружаем страницу ещё раз 

6) изображения можно перелистывать кликами по стрелкам, расположенным по бокам экрана.Изображения перелистываются последовательно - после 18 изображения идёт 19 (клик по правой стрелке), перед 18 изображением идёт 17 (клик по левой стрелке) 

7) изображения перелистываются по кругу: после двадцатого изображения идёт первое (клик по правой стрелке), перед 1 изображением идёт 20 (клик по левой стрелке) 

8) при смене слайдов важно обеспечить плавную смену фоновых изображений. Не должно быть состояний, когда пользователь видит частично загрузившееся изображение или страницу без фонового изображения. Плавную смену фоновых изображений не проверяем: 1) при загрузке и перезагрузке страницы 2) при открытой консоли браузера 3) при слишком частых кликах по стрелкам для смены изображения 

9) при перезагрузке страницы приложения указанный пользователем город сохраняется, данные о нём хранятся в local storage 

10) для указанного пользователем населённого пункта выводятся данные о погоде, если их возвращает API. Данные о погоде включают в себя: иконку погоды, описание погоды, температуру в °C, скорость ветра в м/с, относительную влажность воздуха в %. Числовые параметры погоды округляются до целых чисел 

11) выводится уведомление об ошибке при вводе некорректных значений, для которых API не возвращает погоду (пустая строка или бессмысленный набор символов) 

12) при загрузке страницы приложения отображается рандомная цитата и её автор 

13) при перезагрузке страницы цитата обновляется (заменяется на другую). Есть кнопка, при клике по которой цитата обновляется (заменяется на другую) 

14) при клике по кнопке Play/Pause проигрывается первый трек из блока play-list, иконка кнопки меняется на Pause 

15) при клике по кнопке Play/Pause во время проигрывания трека, останавливается проигрывание трека, иконка кнопки меняется на Play 

16) треки пролистываются по кругу - после последнего идёт первый (клик по кнопке Play-next), перед первым - последний (клик по кнопке Play-prev) 

17) трек, который в данный момент проигрывается, в блоке Play-list выделяется стилем 

18) после окончания проигрывания первого трека, автоматически запускается проигрывание следующего. Треки проигрываются по кругу: после последнего снова проигрывается первый. 

19) добавлен прогресс-бар в котором отображается прогресс проигрывания 

20) при перемещении ползунка прогресс-бара меняется текущее время воспроизведения трека 

21) над прогресс-баром отображается название трека 

22) отображается текущее и общее время воспроизведения трека 

23) есть кнопка звука при клике по которой можно включить/отключить звук 

24) добавлен регулятор громкости, при перемещении ползунка регулятора громкости меняется громкость проигрывания звука 

25) переводится язык и меняется формат отображения даты 

26) переводится приветствие и placeholder 

27) переводится прогноз погоды в т.ч описание погоды и город по умолчанию 

28) переводится цитата дня т.е цитата отображается на текущем языке приложения. Сама цитата может быть другая 

29) переводятся настройки приложения, при переключении языка приложения в настройках, язык настроек тоже меняется 

30) в качестве источника изображений может использоваться Unsplash API 

31) в качестве источника изображений может использоваться Flickr API 

32) в настройках приложения можно указать язык приложения (en/ru или en/be)  

33) в настройках приложения можно указать источник получения фото для фонового изображения: коллекция изображений GitHub, Unsplash API, Flickr API 

34) если источником получения фото указан API, в настройках приложения можно указать тег/теги, для которых API будет присылает фото 

35) в настройках приложения можно скрыть/отобразить любой из блоков, которые находятся на странице: время, дата, приветствие, цитата дня, прогноз погоды, аудиоплеер, список дел/список ссылок/ваш собственный дополнительный функционал 

36) Скрытие и отображение блоков происходит плавно, не влияя на другие элементы, которые находятся на странице, или плавно смещая их 

37) настройки приложения сохраняются при перезагрузке страницы
