### ISSUE TITLE
Cross-Check 'momentum' - 'Olgasinkevich'.

### ISSUE THREAD

**Issue by Olgasinkevich** [rolling-scopes-school/support#311]
Deploy: https://olgasinkevich.github.io/momentum/index.html
Ссылка на репозиторий с проектом на GitHub: https://github.com/Olgasinkevich/momentum
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/momentum/momentum-stage1.md
Ссылка на форму для проверки проекта: такой нет.
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
![Submit 4](https://user-images.githubusercontent.com/70839914/139446415-3b4dc3c0-7d06-4c49-90d9-a6c627908f06.png)
![Submit 3](https://user-images.githubusercontent.com/70839914/139446420-901fdb51-0370-4f73-a420-0d21ac767239.png)
![Submit 2](https://user-images.githubusercontent.com/70839914/139496192-055be539-8b0b-415e-b0f6-76d13b787fe4.png)
![Submit 1](https://user-images.githubusercontent.com/70839914/139446424-f65b9971-35d1-4d2c-b3ac-315d05383518.png)

Оценка в результате самопроверки с ее аргументацией: 85/150: сделаны часы и календарь (+15), приветствие (+10), фоновое изображение со ссылкой на API(+20, +10), погода (+15), цитата (+15). Возникла проблема с тем, что я, к сожалению, забыла форкнуть репозиторий с фоновыми изображениями на свой github. В школьном репозитории была переименована папка 'day' и после этого фоновые изображения перестали открываться с 12 дня до 18 часов. В консоли видно, что идет запрос на ресурс и выдается ошибка. Также в другое время суток фоновое изображение отображается. Проверяющие студенты согласны, что js по фоновым изображениям работает и вопрос в запросе к уже не существующей директории (backend), однако после дедлайна оценку можно исправить только путем апелляции. Очень надеюсь на ваше понимание и снисходительность, потому что в моем случае эти дополнительные баллы почти +50% к score за задание и это очень важно для меня. Спасибо.
Балл за cross-check из вашего Score: 55/150.

**Comment by Olgasinkevich** [comment]
Здравствуйте. Подскажите, пожалуйста, почему не защитано,что часы выводятся
в 24:00:00 формате?😳 По моим подсчётам по ведомости проверки за часы,
календарь, приветствие, цитату, погоду получается 85 баллов. Вечером ещё
один студент пересмотрел работы и поставил 80, т к в начале не заметил
наличие фонового изображения...
Спасибо  большое за уделённое время!

пт, 29 окт. 2021 г., 20:54 Aleksey ***@***.***>:

**Comment by AlekseyVY** [comment]
![1](https://user-images.githubusercontent.com/32457125/139524374-770ce0dc-254d-4622-a125-0aab1fb720ab.png)

**Comment by Olgasinkevich** [comment]
@AlekseyVY, простите, но у меня время отображается в 24-часовом формате. Я прикрепила скрин всего экрана выше в комментарии. Как такое может быть?

**Comment by AlekseyVY** [comment]
Это вашь код, не мой.

**Comment by Olgasinkevich** [comment]
@AlekseyVY к сожалению,
1) я не вижу, что это конкретно мое приложение, так как скрин показывает только часть
2)я еще не разработчик на проекте, который получает зарплату за поиск и устранение багов, а студент на курсе, поэтому была бы очень благодарна за обратную связь и хотя бы предположение, почему именно у Вас время отображается не так, ведь до этого минимум у меня и 4 человек все было хорошо? Другой браузер? Настройки?  Возможно, время все же отображается в формате 24:00:00 и почему-то у Вас появляется приставка "AM"? 
Та проблема, с которой я открывала апелляцию, давала +30 баллов. Вы же добавили только 5 баллов, констатируя, что проблемы с изображениями нет. -25 баллов за неверное отображение времени, проблемы с которым до сих пор ни у кого не возникало, при том, что максимум за время +15 баллов?
