### ISSUE TITLE
Cross-Check 'Self-introduction' - 'frodibjorn'

### ISSUE THREAD

**Issue by frodiBjorn** [rolling-scopes-school/support#313]
Болею, видео записал, пулреквест сделал, все сроки соблюдены, но по состоянию здоровья, совсем забыл, что надо ещё засабмитить на rsschool, обидно будет потерять баллы, прошу войти в положение и проверить таск
![image](https://user-images.githubusercontent.com/79738906/139817956-1023a489-0919-459c-8145-d11657ad75ae.png)

1. https://www.youtube.com/watch?v=EUMLEg1HmMo
2. https://github.com/rolling-scopes-school/frodibjorn-JSFE2021Q3/tree/self-introduction
3. https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/self-introduction
4. 
![image](https://user-images.githubusercontent.com/79738906/139805808-7c6fe323-f52d-4c58-a188-2cffc21a0c63.png)
5. Score: 100 / 100
Есть ссылка на видеозапись выступления. В видео автор рассказывает о себе на английском языке, видео имеет длительность около 3–5 минут (отклонение в пределах 15 секунд ошибкой считать не нужно) — +50 баллов
В описании видео на YouTube есть ссылка на транскрипт выступления. Транскрипт на английском языке и содержит полный текст выступления (может быть незначительно отредактирован) — +50 баллов

**Comment by igorlyatskiy** [comment]
Ваша отметка **100 баллов**

**Comment by frodiBjorn** [comment]
Благодарю за проверку, оперативно)
