### ISSUE TITLE
Cross-Check HTML builder - avkomosko

### ISSUE THREAD

**Issue by avkomosko** [rolling-scopes-school/support#314]
1. Deploy: https://github.com/avkomosko/HTML-builder
2. Task: https://github.com/EvgeniiMal/HTML-builder
3. Crosscheck: https://github.com/EvgeniiMal/HTML-builder/wiki/HTML-builder-crosscheck
4. Screenshot:
![crosscheck](https://user-images.githubusercontent.com/84735861/141420146-1d61f880-2705-4036-a848-e76ccf161195.png)
5.  Self-rating: 150/150:
Я выполнил все требования технического задания. Использовал Node 16.13.0 LTS как того требуют условия кроссчека. Я предполагаю, что у Student3 версия Node 12 или ниже и ошибка была из-за этого. У других проверяющих ошибок нет.
6. Score: 143

**Comment by valerydluski** [comment]
Апелляция проводится только если ожидаемый вами балл и балл в score отличаются на 10 и более процентов.
