### ISSUE TITLE
Cross-Check 'HTML-Builder' - 'AndreyKryukov'

### ISSUE THREAD

**Issue by AndreyKryukov** [rolling-scopes-school/support#315]
- Ссылка на деплой вашего проекта: https://github.com/AndreyKryukov/HTML-builder
- Ссылка на репозиторий с проектом на GitHub: https://github.com/AndreyKryukov/HTML-builder
- Ссылка на задание: https://github.com/EvgeniiMal/HTML-builder
- Ссылка на форму для проверки проекта: https://github.com/EvgeniiMal/HTML-builder/wiki/HTML-builder-crosscheck
- Скриншот с оценками за cross-check:
![скрин](https://user-images.githubusercontent.com/79280578/141421676-2b23e40a-56fb-4cf8-92e7-40dae54e73cb.png)
- Оценка в результате самопроверки с ее аргументацией: себя оценил в 100 баллов из 150, так как первые 5 заданий выполняются полностью без ошибок.
- Балл за cross-check из вашего Score: 87/150

**Comment by GGwpAiushtha** [comment]
Ваша отметка: 100/150 баллов

**Comment by AlekseyVY** [comment]
Итого: 100 баллов.

01: +20;
02: +20;
03: +20;
04: +20;
05: +20;
06: +0; (ваш файл index.js в 06 задании пустой);
Total: 100;
