### ISSUE TITLE
Cross-Check HTML-builder - valentine909

### ISSUE THREAD

**Issue by valentine909** [rolling-scopes-school/support#316]
Ссылка на репозиторий - https://github.com/valentine909/HTML-builder
Ссылка на задание - https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-builder
Ссылка на форму проверки - https://github.com/EvgeniiMal/HTML-builder/wiki/HTML-builder-crosscheck
Скриншот с оценками проверяющих:

![image](https://user-images.githubusercontent.com/52207950/141424407-ced03e7f-9d3a-40c0-9286-124173ee7584.png)

Оценка в результате самопроверки - 150 баллов. Все задания выполнены.
Итоговый балл за кросс-чек - 113.

**Comment by AlekseyVY** [comment]
Итого: 150 баллов.

01: +20;
02: +20;
03: +20;
04: +20;
05: +20;
06: +50;
Total: 150. Все работает.

**Comment by valentine909** [comment]
Спасибо)
