### ISSUE TITLE
Cross-Check HTML-builder - nadyar9

### ISSUE THREAD

**Issue by NadyaR9** [rolling-scopes-school/support#317]
Ссылка на репозиторий - https://github.com/NadyaR9/HTML-builder
Ссылка на задание - https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-builder
Ссылка на форму проверки - https://github.com/EvgeniiMal/HTML-builder/wiki/HTML-builder-crosscheck
Скриншот с оценками проверяющих:
![image](https://user-images.githubusercontent.com/62769869/141432036-9812ff05-a993-4fa7-aff9-8252b062c0eb.png)
![image](https://user-images.githubusercontent.com/62769869/141432088-d3d0a615-8745-4b45-8108-9a106327607e.png)
Оценка в результате самопроверки - 150 баллов. Все задания выполнены. Функция fsPromises.cp() нигде не используется.
Итоговый балл за кросс-чек - 132,5.

**Comment by valerydluski** [comment]
ваша оценка в score 150 баллов. Нет причин для апелляции
