### ISSUE TITLE
Cross-Check 'HTML-builder' - 'SergeyKozlovskiy'.

### ISSUE THREAD

**Issue by SergeyKozlovskiy** [rolling-scopes-school/support#318]
- Deploy:  https://github.com/SergeyKozlovskiy/HTML-builder
 - Repositories: https://github.com/SergeyKozlovskiy/HTML-builder
 - Task: https://github.com/SergeyKozlovskiy/HTML-builder
 - Ссылка на форму для проверки проекта: https://github.com/EvgeniiMal/HTML-builder/wiki/HTML-builder-crosscheck
- 
![1](https://user-images.githubusercontent.com/56650160/141720899-28bc4339-a754-4120-b596-85a390e51131.png)
- Оценка в результате самопроверки с ее аргументацией: 150 / 150 Задание было выполнено в полном объеме 
- Балл за cross-check из вашего Score: 0
 Прошу помочь, т.к. я провалил кросс чек по причине больничного, не было возможности проверить работы. Прилагаю фото эл. больничного листа. Спасибо!
![больничный](https://user-images.githubusercontent.com/56650160/141721489-6e8108ea-3ef4-4123-8e70-ba35122f2d52.jpg)

**Comment by AlekseyVY** [comment]
Итого: 130 баллов.


01: +20;
02: +20;
03: +20;
04: +20;
05: +0 (выкидывает ошибку)
![Screenshot (41)](https://user-images.githubusercontent.com/32457125/142754661-1918be9a-ec40-4215-af34-eb2deac87349.png)
06: +50;
Всего: 130;
