### ISSUE TITLE
Cross-Check 'CIPHERING CLI TOOL' - Aleksey (kornienko199004)#3084

### ISSUE THREAD

**Issue by kornienko199004** [rolling-scopes-school/support#319]
Добрый день.
Ссылка на репозиторий: [https://github.com/kornienko199004/ciphering-cli-tool/pull/1](https://github.com/kornienko199004/ciphering-cli-tool/pull/1)
Ссылка на задание: [https://github.com/rolling-scopes-school/basic-nodejs-course/blob/master/descriptions/ciphering-cli-tool.md](https://github.com/rolling-scopes-school/basic-nodejs-course/blob/master/descriptions/ciphering-cli-tool.md)
Ссылка на форму: [https://boring-ride-216864.netlify.app/](https://boring-ride-216864.netlify.app/)
Скриншот с проверкой: 
![image](https://user-images.githubusercontent.com/30842914/142753943-110705af-1b73-48ec-899b-57536811dc1e.png)

Самопроверка: 
Ваша оценка - 95 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Если аргументы input и/или output ведут к несуществующему файлу либо директории,приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 

2) Если любой из аргументов дублируется, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 

3) Если config невалиден или отсутствует, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 

4) Чтение реализовано при помощи кастомного стрима (класс, отнаследованный от Readable) 

5) Запись реализована при помощи кастомного стрима (класс, отнаследованный от Writable) 

6) Для передачи сообщения в process.stderr используются пользовательские ошибки и их обработка 

Частично выполненные пункты:
1) Если переданы все аргументы и они корректны, приложение читает из файла и записывает в файл преобразованный текст, при этом предыдущие записи не удаляются 
Отзыв: Удаляются предыдущие записи
2) Приложение работает в соответствии с описанными в задании примерами 
Отзыв: Не все примеры выполняются корректно
Выполненные пункты:
1) В README.md должно быть описано, как можно запустить программу из командной строки, описаны аргументы, которые можно передать приложению 

2) Если не передан аргумент с путем до файла на чтение, то чтение осуществляется из process.stdin 

3) Если не передан аргумент с путем до файла на запись, то вывод осуществляется в process.stdout 

4) Шифруются/дешифруются только латинские буквы, регистр сохраняется, остальные символы не изменяются 

5) Если текст вводится из консоли, то программа не должна завершаться после выполнения шифровки/дешифровки введенного текста, т.е. должна быть возможность ввести еще текст 

6) Кодовая база не находится в одном файле, а разделена на файлы в соответствии с выполняемыми задачами (например - функция, преобразующая строку, в отдельном файле, код, создающий transform стрим, в отдельном файле, функция для парсинга и валидации аргументов в отдельном файле и т.п.) 

Балл за cross-check из вашего Score: 48

**Comment by igorlyatskiy** [comment]
На фотографии комментарии не всех проверяющих, не видны выставленные ими баллы

**Comment by kornienko199004** [comment]
Поправил скриншот. Теперь на фотографии все комментарии

**Comment by AV-Shell** [comment]
# **Ваша оценка - 95 - 2/5*150 = 35 баллов **
## Отзыв по пунктам ТЗ:
## Не выполненные/не засчитанные пункты:
1) Если аргументы input и/или output ведут к несуществующему файлу либо директории,приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 
Отзыв: Приложение создает выходной файл, а если нет входного приложение пишет ошибку в stdout и выходит с кодом 0
2) Если любой из аргументов дублируется, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 
Отзыв: если аргументы дублируются - приложение крашится.
3) Если config невалиден или отсутствует, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 
Отзыв: Если конфиг невалиден приложение крашится, если не задан, приложение не выдает ошибки, переписывает из файла в файл
4) Чтение реализовано при помощи кастомного стрима (класс, отнаследованный от Readable) 

5) Запись реализована при помощи кастомного стрима (класс, отнаследованный от Writable) 

6) Для передачи сообщения в process.stderr используются пользовательские ошибки и их обработка 

## Частично выполненные пункты:
1) Если переданы все аргументы и они корректны, приложение читает из файла и записывает в файл преобразованный текст, при этом предыдущие записи не удаляются 
Отзыв: Предыдущие записи удаляются
2) Приложение работает в соответствии с описанными в задании примерами 
Отзыв: R1 делает тоже самое, что и R0 ошибка в строке const dif = parseInt(mode) === 8 ? 8 : -8; а должно быть const dif = parseInt(mode) === 1 ? 8 : -8;
## Выполненные пункты:
1) В README.md должно быть описано, как можно запустить программу из командной строки, описаны аргументы, которые можно передать приложению 

2) Если не передан аргумент с путем до файла на чтение, то чтение осуществляется из process.stdin 

3) Если не передан аргумент с путем до файла на запись, то вывод осуществляется в process.stdout 

4) Шифруются/дешифруются только латинские буквы, регистр сохраняется, остальные символы не изменяются 

5) Если текст вводится из консоли, то программа не должна завершаться после выполнения шифровки/дешифровки введенного текста, т.е. должна быть возможность ввести еще текст 

6) Кодовая база не находится в одном файле, а разделена на файлы в соответствии с выполняемыми задачами (например - функция, преобразующая строку, в отдельном файле, код, создающий transform стрим, в отдельном файле, функция для парсинга и валидации аргументов в отдельном файле и т.п.) 

## Штрафы:
1) Запись, чтение, трансформация текста осуществляются без использования потоков (streams) 
**Отзыв: Трансформ стримов должно быть 3 вида, по одному виду на каждый шифр. Об этом писалось в условиях и неоднократно говорилось. И нужно было быть создавать столько экземпляров классов стримов сколько их в конфиге и пайпить их  (как пайпить их было показано в лекции опросов и ответов или в лекции про стримы). Таково было задание.  Применяю 2/5 штрафа, так как есть ридстрим, райтстрим и один трансформ стрим из 3.**
