### ISSUE TITLE
Cross-Check Singolo - Helgaant

### ISSUE THREAD

**Issue by HelgaAnt** [rolling-scopes-school/support#32]
Ссылка на деплой: (https://helgaant.github.io/Singolo/)

Ссылка на репозиторий с проектом: (https://github.com/HelgaAnt/Singolo/tree/gh-pages)

Я проверила свою работу по чек-листу, получилось  94 балла.
Не согласна со следующими пунктами проверяющих:

1) На странице отсутствует семейство шрифтов Lato. Шрифты не подключены в html путем добавления ссылки на cdn с ними либо не хранятся в папке assets
Комментарий: - шрифты находятся в папке assets/fonts, ссылка на файл стилей указана. При просмотре кода загруженной страницы у элементов указаны шрифты.

2, 3, 4, 5, 6)  Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Slider, Services, Portfolio, Get a Quote, Footer составляют более двух пикселей (2px):  - в сумме минус 15 баллов
Комментарий:- При наложении макета вижу только расхождения в 1 пиксель в секции About Us

9) Внизу как минимум одной из секций (кроме Footer) отсутствует небольшая линия другого цвета: минус -3 балла 
Комментарий:- после каждой секции присутствует линия другого цвета. Линии видно на странице сайта.

10) При добавлении в сетку с изображениями элементов за 12-м (проверяя, добавляем их сами) следующие за 12-м отображаются на странице - не реализовано ограничение видимых двенадцатью показанными в макете: минус -3 балла 
Комментарий:- при добавлении изображений лишние скрываются, указано свойство
 overflow: hidden;

Балл за cross-check из Score выставленный проверяющим
Student 3
Ваша оценка - 68 баллов 
Отзыв по пунктам ТЗ:
1)  На странице отсутствует семейство шрифтов Lato. Шрифты не подключены в html путем добавления ссылки на cdn с ними либо не хранятся в папке assets: минус -5 баллов 
2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Slider составляют более двух пикселей (2px): минус -3 балла 
3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла 
4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Portfolio составляют более двух пикселей (2px): минус -3 балла 
5) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла 
6) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Footer составляют более двух пикселей (2px): минус -3 балла 
7) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Services: минус -3 балла 
8) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Get a Quote: минус -3 балла 
9) Внизу как минимум одной из секций (кроме Footer) отсутствует небольшая линия другого цвета: минус -3 балла 
10) При добавлении в сетку с изображениями элементов за 12-м (проверяя, добавляем их сами) следющие за 12-м отображаются на странице - не реализовано ограничение видимых двенадцатью показанными в макете: минус -3 балла

**Comment by Sannnao** [comment]
Пожалуйста, еще раз внимательно проверьте свою работу. У меня не соответствует почти все, кроме первого блока.

**Comment by HelgaAnt** [comment]
Я проверила работу, сделала снимки экрана, положила сюда (https://github.com/HelgaAnt/Singolo/tree/master/Screen).
У меня совпадает с макетом. Может я что-то не так делаю?

**Comment by Sannnao** [comment]
- Our Services и последующие блоки расходятся более чем на 2px. -15
- Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Get a Quote: минус -3 балла
- Внизу как минимум одной из секций (кроме Footer) отсутствует небольшая линия другого цвета: минус -3 балла

 - 21
