### ISSUE TITLE
Cross-Check 'CIPHERING CLI TOOL' - vzamko

### ISSUE THREAD

**Issue by vzamko** [rolling-scopes-school/support#320]
1. Ссылка на репозиторий - https://github.com/vzamko/Ciphering-CLI-Tool
2. Ссылка на задание - https://github.com/AlreadyBored/basic-nodejs-course/blob/review-2021Q4/descriptions/caesar-cipher-cli-tool.md
3. Ссылка на форму - https://boring-ride-216864.netlify.app/
4. Оценка
<img width="1361" alt="Screenshot 2021-11-21 at 10 11 39" src="https://user-images.githubusercontent.com/23373814/142754704-6a8cffa9-295d-48e3-9030-b143003a6cdb.png">
<img width="1361" alt="Screenshot 2021-11-21 at 10 09 01" src="https://user-images.githubusercontent.com/23373814/142754652-4e250120-67d6-4f5b-9cc7-49301be7ff9f.png">
5. Самопроверка - 160
6. Балл за кросс-чек - 90

Человек поставил 20 балов за ридми и утверждает что вообще ничего не работает, что ну никак не соответствует действительности.

**Comment by vzamko** [comment]
Очевидно он запускал на старой версии ноды. В начале курса было сказано использовать 16.13.

**Comment by natein** [comment]
### **Ваша оценка - 150 баллов**

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) Чтение реализовано при помощи кастомного стрима (класс, отнаследованный от Readable)

2) Запись реализована при помощи кастомного стрима (класс, отнаследованный от Writable)

3) Для передачи сообщения в process.stderr используются пользовательские ошибки и их обработка

**Частично выполненные пункты:**

1) Если config невалиден или отсутствует, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0

**Отзыв:** Если указать опцию конфигурации, но при этом опустить значение, то приложение падает (пример: "node index -c" или "node index --config". Тоже самое касается опций -i, --input, -o, --output. Только в этом случае выдаётся неправильная ошибка "файл не существует".

**Выполненные пункты:**

1) В README.md должно быть описано, как можно запустить программу из командной строки, описаны аргументы, которые можно передать приложению

2) Если переданы все аргументы и они корректны, приложение читает из файла и записывает в файл преобразованный текст, при этом предыдущие записи не удаляются

3) Приложение работает в соответствии с описанными в задании примерами

4) Если аргументы input и/или output ведут к несуществующему файлу либо директории,приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0

5) Если любой из аргументов дублируется, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0

6) Если не передан аргумент с путем до файла на чтение, то чтение осуществляется из process.stdin

7) Если не передан аргумент с путем до файла на запись, то вывод осуществляется в process.stdout

8) Шифруются/дешифруются только латинские буквы, регистр сохраняется, остальные символы не изменяются

9) Если текст вводится из консоли, то программа не должна завершаться после выполнения шифровки/дешифровки введенного текста, т.е. должна быть возможность ввести еще текст

10) Кодовая база не находится в одном файле, а разделена на файлы в соответствии с выполняемыми задачами (например - функция, преобразующая строку, в отдельном файле, код, создающий transform стрим, в отдельном файле, функция для парсинга и валидации аргументов в отдельном файле и т.п.)

**Примечание:** Также приложение падает, если output файл установить в readonly. Но этого нет в форме кроссчека, а только в ТЗ, поэтому оценку не снижала.
