### ISSUE TITLE
Cross-Check 'Ciphering CLI tool' - svetlana-tyshkevich 

### ISSUE THREAD

**Issue by svetlana-tyshkevich** [rolling-scopes-school/support#321]
- Ссылка на репозиторий: https://github.com/svetlana-tyshkevich/ciphering-cli-tool
- Ссылка на задание: https://github.com/rolling-scopes-school/basic-nodejs-course/blob/master/descriptions/ciphering-cli-tool.md
- Ссылка на форму для проверки проекта: https://boring-ride-216864.netlify.app/
- Скриншот с оценками за cross-check: 
![image](https://user-images.githubusercontent.com/70635819/142783611-393086f1-d511-4304-a94e-c8d1b61c834d.png)

- Оценка в результате самопроверки с ее аргументацией: **180 /190**
**Базовая реализация**

- [x] В README.md должно быть описано, как можно запустить программу из командной строки, описаны аргументы, которые можно передать приложению *плюс 10 баллов.*
- [x] Если переданы все аргументы и они корректны, приложение читает из файла и записывает в файл преобразованный текст, при этом предыдущие записи не удаляются *плюс 20 баллов*
- [x] Приложение работает в соответствии с описанными в задании примерами *плюс 30 баллов*
- [x] Если аргументы input и/или output ведут к несуществующему файлу либо директории,приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 *плюс 10 баллов*
- [x] Если любой из аргументов дублируется, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 *плюс 10 баллов*
- [x] Если config невалиден или отсутствует, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от *0 плюс 20 баллов*. Объем валидации config:
 -проверяется, что config имеет формат {XY(-)}n
 -проверяется, что X соответствует одному из шифров
 -проверяется, что для ROT-8 и Цезаря присутствует элемент Y
 -проверяется, что для Атбаш отсутствует элемент Y
 -проверяется, что Y — это 1 или 0
- [x] Если не передан аргумент с путем до файла на чтение, то чтение осуществляется из process.stdin *плюс 10 баллов*
- [x] Если не передан аргумент с путем до файла на запись, то вывод осуществляется в process.stdout *плюс 10 баллов*
- [x] Шифруются/дешифруются только латинские буквы, регистр сохраняется, остальные символы не изменяются *плюс 20 баллов*
- [x] Если текст вводится из консоли, то программа не должна завершаться после выполнения шифровки/дешифровки введенного текста, т.е. должна быть возможность ввести еще текст *плюс 10 баллов*
- [x] Кодовая база не находится в одном файле, а разделена на файлы в соответствии с выполняемыми задачами (например - функция, преобразующая строку, в отдельном файле, код, создающий transform стрим, в отдельном файле, функция для парсинга и валидации аргументов в отдельном файле и т.п.) *плюс 10 баллов*

**Продвинутая реализация**

- [x] Чтение реализовано при помощи кастомного стрима (класс, отнаследованный от Readable) *плюс 10 баллов*
- [x] Запись реализована при помощи кастомного стрима (класс, отнаследованный от Writable) *плюс 10 баллов*
- [ ] Для передачи сообщения в process.stderr используются пользовательские ошибки и их обработка *плюс 10 баллов*

- Балл за cross-check из Score: **157**
Один из проверяющих снял баллы за коммиты после дедлайна, но сроки все в порядке.

**Comment by AV-Shell** [comment]
svetlana-tyshkevich

1)Пункт: Если аргументы input и/или output ведут к несуществующему файлу либо директории,приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0.
Отзыв Процесс завершается с кодом 0, если пути к input и или output  ведут к директории а не к файлу. И ошибка пишется в process.stdout (index.js строка 16 console.log(error); )  -5 баллов.

2) Пункт Если config невалиден или отсутствует, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0
Если передать "node index.js -i input.txt -o output.txt -c"  (конфиг невалиден или отсутствует) то приложение крашится. -5 баллов. (ну как бы передает сообщение в stderr и завершается с кодом отличным от 0, но это необработанный случай.  config.js:47 TypeError: Cannot read properties of undefined (reading 'split'))


Ваша оценка - 170 баллов 

# Отзыв по пунктам ТЗ:
## Не выполненные/не засчитанные пункты:

1) Для передачи сообщения в process.stderr используются пользовательские ошибки и их обработка 

## Частично выполненные пункты:

1) Если аргументы input и/или output ведут к несуществующему файлу либо директории,приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 
Отзыв: Процесс завершается с кодом 0, если пути к input и или output файлам ведут к директории а не к файлу. И ошибка пишется в process.stdout (index.js строка 16 console.log(error); )
2) Если config невалиден или отсутствует, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 
Отзыв: Если передать "node index.js -i input.txt -o output.txt -c" (конфиг невалиден или отсутствует) то приложение крашится. -5 баллов.

##Выполненные пункты:

1) В README.md должно быть описано, как можно запустить программу из командной строки, описаны аргументы, которые можно передать приложению 

2) Если переданы все аргументы и они корректны, приложение читает из файла и записывает в файл преобразованный текст, при этом предыдущие записи не удаляются 

3) Приложение работает в соответствии с описанными в задании примерами 

4) Если любой из аргументов дублируется, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 

5) Если не передан аргумент с путем до файла на чтение, то чтение осуществляется из process.stdin 

6) Если не передан аргумент с путем до файла на запись, то вывод осуществляется в process.stdout 

7) Шифруются/дешифруются только латинские буквы, регистр сохраняется, остальные символы не изменяются 

8) Если текст вводится из консоли, то программа не должна завершаться после выполнения шифровки/дешифровки введенного текста, т.е. должна быть возможность ввести еще текст 

9) Кодовая база не находится в одном файле, а разделена на файлы в соответствии с выполняемыми задачами (например - функция, преобразующая строку, в отдельном файле, код, создающий transform стрим, в отдельном файле, функция для парсинга и валидации аргументов в отдельном файле и т.п.) 

10) Чтение реализовано при помощи кастомного стрима (класс, отнаследованный от Readable) 

11) Запись реализована при помощи кастомного стрима (класс, отнаследованный от Writable) 

## Проверил AV-Shell.  Итоговая оценка **170 баллов**.   Итоговая оценка отличается от полученной в ходе кроссчека на **8%**. Дальшейшее решение за админами.
