### ISSUE TITLE
Cross-Check 'art-quiz' - 'kchrgn'

### ISSUE THREAD

**Issue by kchrgn** [rolling-scopes-school/support#322]
1. Deploy - https://rolling-scopes-school.github.io/kchrgn-JSFE2021Q3/art-quiz/
2. Repository - https://github.com/rolling-scopes-school/kchrgn-JSFE2021Q3/tree/art-quiz/art-quiz
3. Task - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/art-quiz/art-quiz.md
4. Cross-check form - https://art-quiz-cross-check.netlify.app/
5. Cross-check screenshots:
![image](https://user-images.githubusercontent.com/88321335/143551616-afb1990d-8bef-4a0d-bb44-f67c8a2f8aac.png)
![image](https://user-images.githubusercontent.com/88321335/143551891-1dac020f-45ab-4d72-8716-a9ce75eb121d.png)
![image](https://user-images.githubusercontent.com/88321335/143552064-5bb7406f-2756-485b-bdc6-0cb0d39956fd.png)
6. Self Score - 80 (Не выполнены требования к верстке и дизайну, реализован основной функционал викторины в js. Подробно выполненные пункты перечислены в конце issue)
7. Cross-check score - 50 (Один из проверяющих не смог открыть проект и поставил 0, у двух других все открылось и работает, выставлены баллы 70 и 80. В итоге оценка за счет 0 снижена до 50)

Выполненные пункты:

на карточке сыгранной категории отображается результат прохождения раунда - количество вопросов, на которые был дан правильный ответ

варианты ответов на вопросы генерируются случайным образом. В вариантах ответов на вопросы викторины должен быть правильный ответ и только один. Правильный ответ в разных вопросах должен находиться на разных местах, а не, например, всегда быть только первым. Варианты ответов должны быть разными. В вариантах ответов не должны повторяться картины одного и того же художника.

после того, как ответ выбран, появляется модальное окно с правильным ответом на вопрос и кнопкой "Продолжить". При клике по кнопке "Продолжить" пользователь переходит к следующему вопросу категории

после окончания раунда выводится уведомление об окончании раунда и отображается результат прохождения раунда - количество вопросов, на которые был дан правильный ответ. Есть кнопка "Продолжить" при клике по которой пользователь перенаправляется на страницу категорий данного типа вопросов

если раунд проигрывался повторно и результаты изменились, эти изменения отображаются на странице с результатами

Частично выполненные пункты:

вёрстка, дизайн, UI стартовой страницы приложения. Выполняются требования к вёрстке и оформлению приложения. На стартовой странице есть кнопка, при клике по которой открываются настройки викторины, и две кнопки, при кликах по которым можно выбрать тип вопроса: угадать художника по картине, угадать картину по имени её автора

реализована навигация по страницам приложения. Со стартовой страницы при клике по кнопке с типом вопроса пользователь попадает на страницу категорий выбранного типа вопросов. Со страницы категорий пользователь может вернуться на стартовую страницу приложения. Со страницы категорий при клике по карточке категории пользователь попадает на страницу с вопросами категории. На карточке сыгранной категории есть кнопка или ссылка, при клике по которой пользователь попадает на страницу с результатами прохождения раунда. Со страницы с вопросами и со страницы с результатами пользователь может вернуться на страницу категорий или на стартовую страницу приложения

вёрстка, дизайн, UI страницы категории. Выполняются требования к вёрстке и оформлению приложения. На странице категорий размещаются карточки категорий. Карточки категорий могут иметь названия, или их можно просто пронумеровать.

карточка сыгранной категории внешне отличается от карточки категории, которая ещё не игралась

вёрстка, дизайн, UI страницы с вопросами. Выполняются требования к вёрстке и оформлению приложения. Вопросы в викторине идут в том порядке, в каком информация про картины и их авторов размещается в коллекции исходных данных.

Плавная смена изображений, картинки сначала загружаются, потом отображаются, нет ситуации, когда пользователь видит частично загрузившиеся изображения. Плавную смену изображений не проверяем: 1) при загрузке и перезагрузке приложения 2) при открытой консоли браузера

Не выполненные/не засчитанные пункты:

в настройках есть возможность включать/выключать звук, есть регулятор громкости звука. Если звук включён, есть звуковая индикация правильных и неправильных ответов, звуковое сопровождение окончания раунда

в настройках есть возможность включать/выключать игру на время. Если выбрана игра на время, на странице с вопросами викторины отображается таймер, отсчитывающий время, которое отведено для ответа на вопрос

в настройках можно указать время для ответа на вопрос в интервале от 5 до 30 секунд с шагом в 5 секунд. Если время истекает, а ответа нет, это засчитывается как неправильный ответ на вопрос

при перезагрузке страницы приложения настройки сохраняются

правильным и неправильным ответам пользователя соответствуют индикаторы разного цвета

вёрстка, дизайн, UI страницы с результатами. Выполняются требования к вёрстке и оформлению приложения

страница с результатами содержит превью всех картин категории

картины, на вопросы про которые или про их авторов был дан правильный ответ, цветные; картины, на вопросы про которые или про их авторов был дан неправильный ответ, черно-белые

при клике по картине выводится информация о ней - название, автор, год создания

5 баллов за каждую уникальную сложную анимацию, улучшающую интерфейс и удобство использования приложения, но не больше 20 баллов

дополнительными баллами оценивается очень высокое качество оформления приложения, продуманность отдельных деталей интерфейса, улучшающие внешний вид приложения и удобство пользования им, а также выполненный на высоком уровне и сложный в реализации свой собственный дополнительный функционал, существенно улучшающий качество и/или возможности приложения

**Comment by igorlyatskiy** [comment]
Очень низкое качество выполнения работы, за такое предусмотрена отметка в 0 баллов. Скорее всего, апелляция только понизит баллы.
