### ISSUE TITLE
Менторинг интервью

### ISSUE THREAD

**Issue by Olgasinkevich** [rolling-scopes-school/support#327]
Здравствуйте. У меня для интервью указан ментор ARTEM DMITRIEV. Гитхаб @dmitriev-web не открывается, телеграм artem_dmitriev не существует. Дискорд указано, что нет.

**Comment by IrinaSendetskaya** [comment]
Привет! Меня зовут Ира, я твой потенциальный ментор) https://github.com/irinasendetskaya

**Comment by Olgasinkevich** [comment]
Здравствуйте. Очень приятно! Спасибо! Каким образом можно с Вами связаться
через мессенджеры, чтобы договориться о проведении интервью?

пт, 3 дек. 2021 г., 18:04 Sendetskaya ***@***.***>:
