### ISSUE TITLE
Cross-Check Task 1 - htotygetki

### ISSUE THREAD

**Issue by htotygetki** [rolling-scopes-school/support#329]
This's my future job

**Comment by htotygetki** [comment]
?
--
Sent from Mail.ru app for Android Wednesday, 22 December 2021, 07:29AM +03:00 from Maxim Shylau  ***@***.*** :

**Comment by AlreadyBored** [comment]
> ?

This issue is invalid. It doesn't contain any useful information. If you still need it, create correct one

**Comment by htotygetki** [comment]
I understand that. it's just my training before the main tasks. why do you want it?
I did it 1 week.
I can get something not understand)) I still quite beginner.
Sent from Mail.ru app for Android Thursday, 23 December 2021, 07:48AM +03:00 from Maxim Shylau  ***@***.*** :
