### ISSUE TITLE
Cross-Check Singolo - MarinaLitueva

### ISSUE THREAD

**Issue by MarinaLitueva** [rolling-scopes-school/support#33]
Ссылка на деплой: (https://inspiring-panini-339739.netlify.com/)

Ссылка на репозиторий с проектом: (https://github.com/MarinaLitueva/singolo)

Я проверила свою работу по чек-листу, получилось 97 балла.
Не согласна со следующими пунктами проверяющих:

**Student 1**
1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Portfolio составляют более двух пикселей (2px): минус -3 балла 

2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла 

3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла 

4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Footer составляют более двух пикселей (2px): минус -3 балла 

5) Стрелки слайдера без интерактивных стилей, при наведении на стрелки ничего не происходит: минус -3 балла 

**Student 2**

1) нету ссылки на git репозитория, нельзя отследить коммиты, файлы, шрифты, и принадлежность работы

**Student 3**

Ваша оценка - 85 баллов 
1) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Services: минус -3 балла 

2) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции About: минус -3 балла 

3) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Get a Quote: минус -3 балла 

4) При добавлении в сетку с изображениями элементов за 12-м (проверяя, добавляем их сами) следющие за 12-м отображаются на странице - не реализовано ограничение видимых двенадцатью показанными в макете: минус -3 балла

**Comment by xmelsky** [comment]
under review
