### ISSUE TITLE
Cross-Check ' christmas-task#1 - Игрушки'

### ISSUE THREAD

**Issue by Cigaro** [rolling-scopes-school/support#330]
1. https://cigaro-christmas-task.netlify.app/
2. https://github.com/rolling-scopes-school/cigaro-JSFE2021Q3/tree/christmas-task%231
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/christmas-task/christmas-task-part1.md
4. 
![1](https://user-images.githubusercontent.com/18151955/147705167-84444d09-3db9-4ae1-a019-e6c82d54af04.PNG)
![2](https://user-images.githubusercontent.com/18151955/147705188-6a3527b2-6d3d-4b53-a2fe-e9e6ef5eec2a.PNG)
![3](https://user-images.githubusercontent.com/18151955/147705190-930d6e66-5687-4337-b2c5-d5c529dce09a.PNG)
![4](https://user-images.githubusercontent.com/18151955/147705191-8aee4155-8caa-4ce0-b3e9-93692989317b.PNG)
**По поводу оценок проверяющих, ничего против не имею!**
_Две из 4 проверяемых мною работ были отлично сделаны и я их сразу проверил, а две другие просили отложить до последнего. Но в силу того что не получалось разобраться с christmas-task#2, увлёкся и опомнился когда выходил на перекур, а это было на пол часа позже дедлайна. Очень прошу добавить мне в Score баллы за christmas-task#1, ошибку осознал, больше такого не повторится!!! За ранее спасибо)_

Ваша оценка - 164 баллов
Отзыв по пунктам ТЗ:
Страница с игрушками содержит карточки всех игрушек а также фильтры, строку поиска, поле для сортировки. Выполняются требования к вёрстке +7
Карточка игрушки содержит её изображение, название, текстом или условным значком обозначено количество экземпляров, год покупки, форма, цвет, размер, является ли игрушка любимой +10
Карточки игрушек добавляются динамически средствами JavaScript (на кросс-чеке этот пункт не проверяется)
Добавление игрушек в избранное :
*  кликая по карточке с игрушкой или по кнопке на ней игрушку можно добавлять в избранное или удалять из избранного. 
    Карточки добавленных в избранное игрушек внешне отличаются от остальных +10
*  на странице отображается количество добавленных в избранное игрушек. При попытке добавить в избранное больше 20 
   игрушек, выводится всплывающее уведомление с текстом "Извините, все слоты заполнены" +10
Сортировка :
  Сортируются только те игрушки, которые в данный момент отображаются на странице
*   сортировка игрушек по названию в возрастающем и спадающем порядке +10
*   сортировка игрушек по году их приобретения в возрастающем и спадающем порядке +10
Фильтры в указанном диапазоне от и до :
*  фильтры по количеству экземпляров +10
*  фильтры по году покупки +10
*  для фильтрации в указанном диапазоне используется range slider с двумя ползунками. При перемещении ползунков 
   отображается их текущее значение, разный цвет слайдера до и после ползунка +10
Фильтры по значению :
   Выбранные фильтры выделяются стилем.
*  фильтры по форме +5
*  фильтры по цвету +5
*  фильтры по размеру +5
*  можно отобразить только любимые игрушки +5
*  можно отфильтровать игрушки по нескольким фильтрам одного типа +10
*  Для нескольких фильтров одного типа отображаются игрушки, которые соответствуют хоть одному выбранному фильтру. 
   Например, можно отобразить снежинки и колокольчики; или белые, синие и красные игрушки; или большие и средние.
*   Можно отфильтровать игрушки по нескольким фильтрам разного типа +16
    Для нескольких фильтров разного типа отображаются только те игрушки, которые соответствуют всем выбранным 
    фильтрам. Например, можно отобразить только синие шары. Или любимые белые и красные игрушки купленные в 1940- 
    1960 годах. Если игрушек, соответствующих всем выбранным фильтрам нет, на странице выводится уведомление в 
     человекочитаемом формате, например, "Извините, совпадений не обнаружено"
Сброс фильтров:
*  есть кнопка reset для сброса фильтров +10
   Кнопка reset сбрасывает только фильтры, не влияя на порядок сортировки или игрушки, добавленные в избранное.
   После использования кнопки reset фильтры остаются работоспособными
*  при сбросе фильтров кнопкой reset, ползунки range slider сдвигаются к краям, значения ползунков возвращаются к 
   первоначальным, range slider закрашивается одним цветом +10
Сохранение настроек в local storage :
*  выбранные пользователем фильтры, порядок сортировки, добавленные в избранное игрушки сохраняются при 
    перезагрузке страницы. Есть кнопка сброса настроек, которая очищает local storage + 0
Поиск :
*  при открытии приложения курсор находится в поле поиска +2
*  автозаполнение поля поиска отключено (нет выпадающего списка с предыдущими запросами) +2
*  есть placeholder +2
*  в поле поиска есть крестик, позволяющий очистить поле поиска +0
*  если нет совпадения последовательности букв в поисковом запросе с названием игрушки, выводится уведомление в 
   человекочитаемом формате, например "Извините, совпадений не обнаружено" +0
* при вводе поискового запроса на странице остаются только те игрушки, в которых есть указанные в поиске буквы в 
   указанном порядке. При этом не обязательно, чтобы буквы были в начале слова. Регистр символов при поиске не 
   учитывается +5  
*  Поиск ведётся только среди игрушек, которые в данный момент отображаются на странице.
   если очистить поле поиска, на странице отображаются игрушки, соответствующие всем выбранным фильтрам и настройкам 
   сортировки +0
*  Дополнительный функционал на выбор +0

Балл за cross-check из Score = 0

**Comment by igorlyatskiy** [comment]
В виде исключения ваша отметка **164** балла. В будущем сначала проверяйте все работы, а если проверяемые попросят, перепроверяйте позже ещё раз

**Comment by Cigaro** [comment]
теперь так и делаю, спасибо)
