### ISSUE TITLE
Cross-Check  'christmas-task#1'  'geekedger'

### ISSUE THREAD

**Issue by geekedger** [rolling-scopes-school/support#331]
1) Deploy: https://geekedger-christmas-task1.netlify.app/
2) Repo: https://github.com/rolling-scopes-school/geekedger-JSFE2021Q3/tree/christmas-task/christmas-task
3) Task: https://app.rs.school/course/entityDetails?course=js-fe-2021Q3&entityType=task&entityId=1314
4) Screen:
![score](https://user-images.githubusercontent.com/90379514/147709515-6ce1533a-6c14-4bff-ac7d-3c3eb4144f97.jpg)
5) Score: 132

Я засабмитил некорректную ссылку на деплой (видно на скриншоте). К сожалению, 2 из 4х проверяющих не оставили свои контакты и в дискорде по нику их не находит. Есть ли возможность получить дополнительную оценку, отличную от  0  в моей ситуации?

**Comment by igorlyatskiy** [comment]
Есть коммиты после дедлайна
