### ISSUE TITLE
CV#3. CV. Cross-Check

### ISSUE THREAD

**Issue by Dereamor** [rolling-scopes-school/support#332]
1. Deploy: https://Dereamor.github.io/rsschool-cv/
2. Repo: https://github.com/Dereamor/rsschool-cv/tree/rsschool-cv-html
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. Screen:
![image](https://user-images.githubusercontent.com/90096824/148375088-6caa9048-003c-428e-a40f-86321248fb4c.png)
5. Ваша оценка - 125 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

Выполненные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

16) информацию об образовании и уровне английского 

17) CV выполнено на английском языке

**Comment by irinainina** [comment]
Пожалуйста, оформи issue по требованиям https://docs.rs.school/#/cross-check-flow?id=Апелляция
Не хватает пункта
- Оценка в результате самопроверки с ее аргументацией. Т.е. самооценку нужно сделать по пунктам

**Comment by irinainina** [comment]
Работа соответствует требованиям.
120 баллов
Совет на будущее. Стили лучше писать в файле style.css, а не в index.html
