### ISSUE TITLE
CV#3. CV. Cross Check

### ISSUE THREAD

**Issue by Ellonanew** [rolling-scopes-school/support#333]
Deploy - https://ellonanew.github.io/rsschool-cv/
Repository - https://github.com/Ellonanew/rsschool-cv
Task -  https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Форма проверки - https://cv-cross-check.netlify.app
Screenshot
![cv-html-screen](https://user-images.githubusercontent.com/96070040/148389373-95a065b8-b3b5-47d7-81b3-c556b7007640.png)
Score
Ваша оценка - 117.5 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) элемент nav 
Частично выполненные пункты:
1) header, main, footer 
2) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

Выполненные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 
2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 
3) только один заголовок h1 
4) заголовки h2 
5) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 
6) для оформления СV используются css-стили 
7) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 
8) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 
9) краткую информацию о себе 
10) контакты для связи 
11) перечень навыков 
12) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 
13) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 
14) информацию об образовании и уровне английского 
15) CV выполнено на английском языке

**Comment by irinainina** [comment]
Пожалуйста, оформи issue по требованиям https://docs.rs.school/#/cross-check-flow?id=Апелляция
Не хватает пунктов
- Ссылка на форму для проверки 
- Скриншот (сделай скриншот самого CV)
- Оценка в результате самопроверки с ее аргументацией. Т.е. самооценку нужно сделать по пунктам

**Comment by irinainina** [comment]
С самооценкой согласна.
117,5 баллов
Работа отличная, жаль что не все пункты требований выполнены .
