### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'Ragimov Fuad'

### ISSUE THREAD

**Issue by Mangecu** [rolling-scopes-school/support#335]
1. Deploy: https://mangecu.github.io/rsschool-cv/
2. Repo: https://github.com/Mangecu/rsschool-cv
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. Screen: 
![image](https://user-images.githubusercontent.com/65713888/148381105-944a4731-fa29-4913-8184-b320d159b983.png)
_______________________________________________________________________________________________________________________________________
5. Ваша оценка - 105 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) элемент nav 

3) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

Частично выполненные пункты:
1) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

Выполненные пункты:
1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

2) header, main, footer 

3) только один заголовок h1 

4) заголовки h2 

5) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

6) для оформления СV используются css-стили 

7) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

8) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

9) краткую информацию о себе 

10) контакты для связи 

11) перечень навыков 

12) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

13) информацию об образовании и уровне английского 

14) CV выполнено на английском языке

**Comment by irinainina** [comment]
115 баллов
Самооценка немного занижена, баллы за сабмит отнимать не нужно.
Очень хорошее CV!
