### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'vikstasenkova'

### ISSUE THREAD

**Issue by vikstasenkova** [rolling-scopes-school/support#336]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Screenshot: 
![cv#3](https://user-images.githubusercontent.com/96073787/148382794-152b17b8-c67a-43aa-b3b5-93f21fffa904.PNG)
Repository: https://github.com/vikstasenkova/rsschool-cv
Deploy: https://vikstasenkova.github.io/rsschool-cv/
Score: 115/120
[  ] засабмиченна в rs app ссылка на CV, задеплоенное на gh-pages +10
[x]вёрстка валидная +10
[x]вёрстка семантическая +20
[x]В коде странице присутствуют и используются по назначению следующие элементы:
[x]header, main, footer +5
[x]элемент nav +5
[x]только один заголовок h1 +5
[x]заголовки h2 +5
[x]в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
[x]для оформления СV используются css-стили +10
[x]при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
[x]на странице СV есть фото автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка +10
CV содержит:
[x]краткую информацию о себе +5
[x]контакты для связи +5
[x]перечень навыков +5
[x]пример кода. Код добавлен при помощи символов и тегов +5
[ ]перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +0
[x]информацию об образовании и уровне английского +5
[x]CV выполнено на английском языке +10
Прошу не учитывать за ошибку сдачу cv#3 после дедлайна, в связи с возникновением путаницы со временем). 06.01.2022 в час ночи в личном кабинете дедлайн был 13.01.22. А утром опять 06.01.22

**Comment by irinainina** [comment]
120 баллов.
Работа полностью соответствует требованиям.
В перечень проектов рекомендовалось добавить само CV, постепенно их будет становиться больше.
Успехов!
