### ISSUE TITLE
CV. Cross-Check

### ISSUE THREAD

**Issue by maximax15** [rolling-scopes-school/support#337]
1.1.https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2.
![screen CV3](https://user-images.githubusercontent.com/92719529/148394186-ec6571ff-0c5c-4d63-a042-b350bbc31ec4.png)
3.Deploy: https://maximax15.github.io/rsschool-cv/
4.done 06.01.2022/deadline 06.01.2022
5.  засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
вёрстка валидная +10
вёрстка семантическая:
header, main, footer +5
элемент nav +5
только один заголовок h1 +5
заголовки h2 +5
в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
для оформления СV используются css-стили +10
при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
CV содержит:
краткую информацию о себе +5
контакты для связи +5
перечень навыков:отсутствует
пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения:отсутствует
информацию об образовании и уровне английского +5
CV выполнено на английском языке +10
score 120/130

P.S. Сделал еще вчера до дедлайна оставалось сделать деплой и засамбитить,увидел в дискорде,что переносят задание...оказалось это был перенос кросс-чека

**Comment by irinainina** [comment]
Пожалуйста, оформи issue по требованиям https://docs.rs.school/#/cross-check-flow?id=Апелляция
Не хватает пункта
- Оценка в результате самопроверки с ее аргументацией. Т.е. самооценку нужно сделать по пунктам

**Comment by maximax15** [comment]
отредактирова

> Пожалуйста, оформи оформить по требованиям [https://docs.rs.school/#/cross-check-flow?id=Апелляция](https://docs.rs.school/#/cross-check-flow?id=%D0%90%D0%BF%D0%B5%D0%BB%D0%BB%D1%8F%D1%86%D0%B8%D1%8F) Не хватает пункта
> 
> * Оценка в результате самопроверки с ее аргументацией. Т.е. самооценку нужно сделать по пунктам

отредактировал:добавил пункты

**Comment by irinainina** [comment]
120 баллов
все требования выполнены
изображение логотипа курса лучше брать с прозрачностью, например, со вкладки score rs app https://app.rs.school/static/images/logo-rsschool3.png

**Comment by maximax15** [comment]
> 120 баллов все требования Выполнены изображение логотипа курса лучше брать с прозрачностью, например, со вкладки оценка RS приложение https://app.rs.school/static/images/logo-rsschool3.png

подскажи,пожалуйста,я могу учавствовать в кросс-чеке?
захожу в crosscheck review,в 'поиске' студенты отсутствуют
