### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'EkaterinaBurak'

### ISSUE THREAD

**Issue by EkaterinaBurak** [rolling-scopes-school/support#338]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Repositiry: https://github.com/EkaterinaBurak/rsschool-cv
Screenshot:
<img width="360" alt="resume" src="https://user-images.githubusercontent.com/81382292/148412920-ca37549a-5eec-42eb-82fe-06a61d646012.png">
Deploy: https://EkaterinaBurak.github.io/rsschool-cv/
Done 06.01.2022 / deadline 13.01.2022
Score: 120
Cross-check form: https://cv-cross-check.netlify.app/

Считаю, что все требования к заданию выполнены.
Работа сдана позднее из-за того, что в личном кабинете сперва был указан дедлайн 13.01.22, а утром изменен на 06.01.2022.

Выполнены пункты:
студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
вёрстка валидная +10
для проверки валидности вёрстки используйте сервис https://validator.w3.org/
валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью.
если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
вёрстка семантическая +20
В коде странице присутствуют и используются по назначению следующие элементы:
Под "используются по назначению" имеется в виду, что у элементов есть какое-то содержание, соответствующее типу элемента, а не добавлены пустые теги для получения баллов. Правильность использования элементов не проверяется и на балл не влияет.
header, main, footer +5
элемент nav +5
только один заголовок h1 +5
заголовки h2 +5
в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
Если ссылка в футере ведёт на курс stage0, это не ошибка.
для оформления СV используются css-стили +10
при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
Также допускается использование нумерованого списка ol > li или ol > li > a
Содержание CV +30
CV содержит:
краткую информацию о себе +5
контакты для связи +5
перечень навыков +5
пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
информацию об образовании и уровне английского +5
CV выполнено на английском языке +10

**Comment by irinainina** [comment]
120 баллов
Не совсем удачный вариант со ссылками на проекты, там нужно было указать каждый проект отдельно, а не добавить ссылку на гитхаб, но в целом отличная работа

**Comment by EkaterinaBurak** [comment]
Спасибо!

**Comment by EkaterinaBurak** [comment]
Здравствуйте! В моём личном кабинете не обновлена оценка за задание.
