### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Kirill Trots'

### ISSUE THREAD

**Issue by aperolka** [rolling-scopes-school/support#339]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot:
![kirill trots](https://user-images.githubusercontent.com/92181687/148410622-bd25b4f6-ac31-4ae7-87a0-680498ece1b9.png)
3. My repository: https://github.com/aperolka/rsschool-cv
4. Deploy: https://aperolka.github.io/rsschool-cv/
5. Score: 110/120 
6. [x] засабмиченна в rs app ссылка на CV, задеплоенное на gh-pages +10
[+/-]вёрстка валидная +10
[x]вёрстка семантическая +20
[x]В коде странице присутствуют и используются по назначению следующие элементы:
[x]header, main, footer +5
[x]элемент nav +5
[x]только один заголовок h1 +5
[x]заголовки h2 +5
[x]в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
[x]для оформления СV используются css-стили +10
[x]при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
[x]на странице СV есть фото автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка +10
CV содержит:
[x]краткую информацию о себе +5
[x]контакты для связи +5
[x]перечень навыков +5
[x]пример кода. Код добавлен при помощи символов и тегов +5
[ ]перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +0
[+/-]информацию об образовании и уровне английского +5
[x]CV выполнено на английском языке +10

Здравствуйте! Я перепутал дедлайн сдачи CV#3 Cross-Check с 13-м числом.  Не смог разобраться с дедлайнами. Могу ли я еще сдать работу? Спасибо

**Comment by irinainina** [comment]
120 баллов.
Отличная работа! очень понравилась
Проблема с изображением в секции about, оно не отображается из-за ошибки в адресе

**Comment by aperolka** [comment]
Irina спасибо Вам огромное!
