### ISSUE TITLE
Cross-Check Singolo - annakisel

### ISSUE THREAD

**Issue by annakisel** [rolling-scopes-school/support#34]
Ссылка на деплой вашего проекта: https://annakisel.github.io/singolo/index.html

Ссылка на репозиторий с проектом на GitHub: https://github.com/annakisel/singolo

Оценка в результате самопроверки, с ее аргументацией: 97 баллов,
потому что в секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт. -3 балла

Оценки студентов: 1) 97 баллов 2) 94 балла 3) 70 баллов 4) 97 баллов

вот комментарии проверок студентами, с которыми я не согласна:
3 студент:
1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличие (не задана ширина 1020px) секции header составляют более  двух пикселей (2px); -3 балла;
2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличие (не задана ширина 1020px) секции Slider составляют более  двух пикселей (2px); -3 балла;
3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличие (не задана ширина 1020px) секции Our Services  составляют более  двух пикселей (2px); -3 балла;
4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличие (не задана ширина 1020px) секции Portfolio составляют более  двух пикселей (2px); -3 балла;
5) Несоответствие снимку макета, наложенному на страницу. Визуальные отличие (не задана ширина 1020px) секции About Us составляют более  двух пикселей (2px); -3 балла;
6) Несоответствие снимку макета, наложенному на страницу. Визуальные отличие (не задана ширина 1020px) секции Get a Quote составляют более  двух пикселей (2px); -3 балла;
7) Несоответствие снимку макета, наложенному на страницу. Визуальные отличие (не задана ширина 1020px) секции footer составляют более  двух пикселей (2px); -3 балла;
8) Выходящий текст в текстовой  ячейке блока Our Services (не заголовок) не скрыт; -3 балла;
9) Отсутствует интерактивность социальных иконок в блоке About Us; -3 балла;
10) Отсутствует интерактивность социальных иконок в блоке footer; -3 балла;

Тут я в принципе не поняла откуда взялись все эти комментарии, так как верен только пункт 8;

2 студент:
2) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла (В блоке "о нас" при увеличение текста имени у Вас появляется скролл, который двигает блок - это ошибка.) 

скролл двигает только текст, но "текст видимым образом выходит за пределы строки блока или переносится на следующую строку" -  это не верное утверждение, так что это придирка

**Comment by amoebiusss** [comment]
Оценка отличается от ожидаемой на 7 баллов, минимальная разница — 15.

https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f
