### ISSUE TITLE
CV. Cross-Check

### ISSUE THREAD

**Issue by Hemetek** [rolling-scopes-school/support#340]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot: 
![image](https://user-images.githubusercontent.com/83182370/148449630-4d64bc65-e8be-4d0b-943d-393e2af40f33.png)

3. Deploy: https://hemetek.github.io/rsschool-cv/

4. Done 06.01.2022 / deadline 05.01.2022

5. Score: 80 / 120
[x]вёрстка семантическая +10
[x]В коде странице присутствуют и используются по назначению следующие элементы:
[x]header, main, footer +5
[x]элемент nav +5
[x]в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
[x]для оформления СV используются css-стили +10
[x]при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
[x]на странице СV есть фото автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
[x]CV выполнено на английском языке +10

**Comment by Bumble-sakh** [comment]
63 балла

> [x]header, main, footer +5
> [x]элемент nav +5

Элементы main и nav отсутствуют. 

> [x]в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10

только год и логотип курса.

> [x]на странице СV есть фото автора, пропорции изображения не искажены, у изображения есть атрибут alt +10

Изображение красивого горного хребта сложно ассоциировать с аватаром автора. Но картинка есть, атрибут alt присутствует. Баллы поставил полностью.
