### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Natalia Satir' 

### ISSUE THREAD

**Issue by satirnatalia** [rolling-scopes-school/support#341]
1. Task: [https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md](url)
2. Screenshot:
 
![prt scr cv](https://user-images.githubusercontent.com/96115657/148449993-eb174273-ccb7-4e40-9b71-951a731c2043.png)

3. My repository: [https://github.com/satirnatalia/rsschool-cv](url)
4. Deploy: [https://satirnatalia.github.io/rsschool-cv/](url)
5. Score 115/120
[+] сабмит в rs app ссылку на своё CV, задеплоенное на gh-pages +10
[+] вёрстка валидная +10
[+] вёрстка семантическая +20
[+] header, main, footer +5
[+] элемент nav +5
[+] только один заголовок h1 +5
[+] заголовки h2 +5
[+-] в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
[+] для оформления СV используются css-стили +10
[+] при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
[+-] на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
[+] навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
CV содержит:
[+] краткую информацию о себе +5
[+] контакты для связи +5
[+] перечень навыков +5
[+] пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
[-] перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
[+] информацию об образовании и уровне английского +5
[+] CV выполнено на английском языке +10

6. Cделала все до дедлайна, но не нажала сабмит в автотесте, потому что заметила ошибку (не прогрузилась фото профиля). Одновременно с этим узнала о переносе дедлайна (подумала, что для сабмита CV3) и решила перенести все правки на следующий день, поэтому пропустила дедлайн

**Comment by Bumble-sakh** [comment]
120 баллов

Хорошее cv, интересно реализован уровень языка и скиллы, хорошая адаптивность.

на будущее будьте внимательнее: 
ссылки в апелляции ведут не туда, но это, видимо, от волнения...
JPG и jpg - это разные расширения, поэтому фото не грузилось
