### ISSUE TITLE
Missed Deadline / no internet due to hurricane

### ISSUE THREAD

**Issue by rustana** [rolling-scopes-school/support#342]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv.md

2. Screenshot: ![myResume-cv3](https://user-images.githubusercontent.com/86327711/148426877-3fca0633-c80e-40b7-af3f-96131ca32f82.png)
  
3. Deploy: https://rustana.github.io/rsschool-cv/

4. Done 06/01/2022 / deadline 5/1/2022

**Comment by irinainina** [comment]
Пожалуйста, оформи issue по требованиям https://docs.rs.school/#/cross-check-flow?id=Апелляция
Не хватает пункта
- Оценка в результате самопроверки с ее аргументацией. Т.е. самооценку нужно сделать по пунктам

**Comment by rustana** [comment]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv.md

2. Screenshot: ![myResume-cv3](https://user-images.githubusercontent.com/86327711/148426877-3fca0633-c80e-40b7-af3f-96131ca32f82.png)
  
3. Deploy: https://rustana.github.io/rsschool-cv/

4. Done 06/01/2022 / deadline 5/1/2022
5. 130/130

6. студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
вёрстка валидная +10
header, main, footer +5
элемент nav +5
только один заголовок h1 +5
заголовки h2 +5
в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
для оформления СV используются css-стили +10
при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10

CV содержит:
краткую информацию о себе +5
контакты для связи +5
перечень навыков +5
пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
информацию об образовании и уровне английского +5
CV выполнено на английском языке +10

**Comment by Bumble-sakh** [comment]
110 баллов

> 1) элемент nav

feedback: nav определяет отдельную секцию документа, назначение которой обозначение ссылок навигации.
у вас в нем находятся контакты. навигации на странице нет.

> 2) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону

feedback: main едет влево

>1) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a

feedback: отсутствует навигация
