### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'NikitaShakhovich'

### ISSUE THREAD

**Issue by NikitaShakhovich** [rolling-scopes-school/support#343]
1. Deploy: https://nikitashakhovich.github.io/rsschool-cv/
2. Repository: https://github.com/NikitaShakhovich/rsschool-cv
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. Screenshot: ![CV](https://user-images.githubusercontent.com/77278804/148460232-8f032896-6e0a-4b1c-beca-343ca4b3e04c.png)
5. Засабмитил в rs app ссылку на своё CV, Задеплоенное на gh-pages +10
Вёрстка валидная +10
Вёрстка семантическая:
header, main, footer +5
элемент nav +5
только один заголовок h1 +5
заголовки h2 +5
в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
для оформления СV используются css-стили +10
при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
CV содержит:
краткую информацию о себе +5
контакты для связи +5
перечень навыков +5
пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
информацию об образовании и уровне английского +5
CV выполнено на английском языке +10
score 120/120

Здравствуйте! Запутался с дедлайнами сдачи CV#3 Cross-Check. Можно еще сдать работу? Спасибо

**Comment by Bumble-sakh** [comment]
120 баллов
Понравилась работа с svg, использование переменных в css.
Из недочетов:
футер растянут на всю ширину, но его содержимое уезжает влево.
