### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Ksenia Shevtsova'

### ISSUE THREAD

**Issue by illusiondelusion** [rolling-scopes-school/support#344]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot: 
![cv](https://user-images.githubusercontent.com/60574829/148452885-d2aa514d-9567-465b-948c-b935e80da737.jpg)
3. Repository: https://github.com/illusiondelusion/rsschool-cv
4. Deploy: https://illusiondelusion.github.io/rsschool-cv/
5. Score:  115/120
- [x] студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages => создана апелляция +10
- [x] вёрстка валидная +10
- [x] вёрстка семантическая +18,5
  В коде странице присутствуют и используются по назначению следующие элементы:
  - [x] header, main, footer +5
  - [x] элемент nav +5
  - [x] только один заголовок h1 +5
  - [±] заголовки h2 +3,5
- [x] в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
- [x] для оформления СV используются css-стили +10
- [x] при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
- [x] на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
- [x] навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
- [x] Содержание CV +25
  CV содержит:
  - [x] краткую информацию о себе +5
  - [x] контакты для связи +5
  - [x] перечень навыков +5
  - [x] пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
  - [ ] перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения
  - [x] информацию об образовании и уровне английского +5
- [x] CV выполнено на английском языке +10

**Comment by Bumble-sakh** [comment]
120 баллов
Верстка отлично смотрится в плоть до 320px
Жаль что вместо h2 используются h3

**Comment by illusiondelusion** [comment]
@Bumble-sakh Спасибо Вам большое!
