### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Sergey Pobudey'

### ISSUE THREAD

**Issue by ps0m** [rolling-scopes-school/support#345]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. 
![image](https://user-images.githubusercontent.com/96006903/148475155-734f16b2-fa28-443a-89c8-5868dd2656da.png)
3. Deploy: https://ps0m.github.io/rsschool-cv/
4. Done:07.01.2022/ Deadline 06.01.2022 with extension to 13.01.2022
5. Score: 120/130

Выполнены пункты:
- [x] студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages  +10
- [x] вёрстка валидная +10
- [x] вёрстка семантическая +20
- [x] В коде странице присутствуют и используются по назначению следующие элементы:
- [x] header, main, footer +5
- [x] элемент nav +5
- [x] только один заголовок h1 +5
- [x] заголовки h2 +5
- [x] в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
- [x] для оформления СV используются css-стили +10
- [x] при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
- [x] на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
- [x] навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10- - 
- [x] Содержание CV +25
CV содержит:
- [x] краткую информацию о себе +5
- [x] контакты для связи +5
- [x] перечень навыков +5
- [x] пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
- [x] перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения. P.s. т.к. проектов нет, то указал ссылку на GitHub
- [x] информацию об образовании и уровне английского +5
- [x] CV выполнено на английском языке +10

**Comment by Bumble-sakh** [comment]
120 баллов
Хорошо выполненное cv, строго по плану.
