### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'Sergey Kravchenko'

### ISSUE THREAD

**Issue by svk-man** [rolling-scopes-school/support#346]
1. Deploy: https://svk-man.github.io/rsschool-cv/
2. Repository: https://github.com/svk-man/rsschool-cv
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. Form: https://cv-cross-check.netlify.app/
5. Screenshot:
![](https://raw.githubusercontent.com/svk-man/rsschool-cv/gh-pages/cv.PNG)
6. Done 07.01.2022 / deadline 10.01.2022
7. Score: 120 / 130
- [x] студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
- [x] вёрстка валидная +10
  - для проверки валидности вёрстки используйте сервис https://validator.w3.org/
  - валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью.
  - если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
- [x] вёрстка семантическая +20
  В коде странице присутствуют и используются по назначению следующие элементы:
  Под "используются по назначению" имеется в виду, что у элементов есть какое-то содержание, соответствующее типу элемента, а не добавлены пустые теги для получения баллов. Правильность использования элементов не проверяется и на балл не влияет.
    - header, main, footer +5
    - элемент nav +5
    - только один заголовок h1 +5
    - заголовки h2 +5
- [x] в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
  Если ссылка в футере ведёт на курс stage0, это не ошибка.
- [x] для оформления СV используются css-стили +10
- [x] при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
- [x] на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
- [x] навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
  Также допускается использование нумерованого списка ol > li или ol > li > a
- [x] Содержание CV +30
  CV содержит:
    - краткую информацию о себе +5
    - контакты для связи +5
    - перечень навыков +5
    - пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
    - перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
    - информацию об образовании и уровне английского +5
- [x] CV выполнено на английском языке +10

8. Дополнительная информация:
- Адаптивность выполнена вплоть до 480px.
- Проекты будут добавляться/корректироваться по мере выполнения.

Буду рад критике и рекомендациям :)

**Comment by Bumble-sakh** [comment]
120 баллов, отличная работа.
Единственное:
Список проектов есть, но ссылки, к сожалению, ведут не на код проекта или его деплой, а на задание к проекту.
