### ISSUE TITLE
CV. Cross-Check

### ISSUE THREAD

**Issue by MMirzoev** [rolling-scopes-school/support#347]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot: ![CV. Cross-Check](https://user-images.githubusercontent.com/80441946/148504806-5a238c8f-01da-470a-befc-91e837e90afe.jpg)
3. Deploy: https://MMirzoev.github.io/rsschool-cv/
4. Done 07.01.2022 / deadline 06.01.2022
5. Score: 120 / 120
- [x] студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
- [x] вёрстка валидная +10
- [x] вёрстка семантическая +20
В коде странице присутствуют и используются по назначению следующие элементы:
- [x] header, main, footer +5
- [x] элемент nav +5
- [x] только один заголовок h1 +5
- [x] заголовки h2 +5
- [x] в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
Если ссылка в футере ведёт на курс stage0, это не ошибка.
- [x] для оформления СV используются css-стили +10
- [x] при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
- [x] на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
- [x] навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
Также допускается использование нумерованого списка ol > li или ol > li > a
- [x] Содержание CV +30
CV содержит:
- [x] краткую информацию о себе +5
- [x] контакты для связи +5
- [x] перечень навыков +5
- [x] пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
- [x] перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
- [x] информацию об образовании и уровне английского +5
- [x] CV выполнено на английском языке +10
**Здравствуйте! Я перепутал дедлайн сдачи CV#3 Cross-Check с 10-м числом. Могу ли я еще сдать свою работу? Спасибо.**

**Comment by irinainina** [comment]
120 баллов
Прекрасная работа, такую проверять легко и приятно
Небольшие уточнения, чтобы от проверки была польза
- Codepen не входит в список навыков. Ссылку на Codepen возможно лучше разместить в другом пункте, например, там где пишешь про код
- код css в качестве примера кода выглядит немного неожиданно
- в контактах рекомендуется указать никнейм в дискорде rs school
- код достаточно хороший, можно поработать над форматированием кода и единством стиля - например, где-то ссылки в li пишутся в одной строке, где-то в отдельной. Оба варианта могут быть, но лучше выбрать и придерживаться какого-то одного
Но вообще работа отличная

**Comment by MMirzoev** [comment]
Спасибо за советы!
