### ISSUE TITLE
Апелляция

### ISSUE THREAD

**Issue by 4oVEN** [rolling-scopes-school/support#348]
1. Task https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot: 
![image](https://user-images.githubusercontent.com/70946093/148460119-f28b00ad-b8e4-43dd-ad0b-9e08d25d2b2b.png)
3. My repository: https://4oVEN.github.io/rsschool-cv/
4. Score: 110/120
[+]засабмиченна в rs app ссылка на CV, задеплоенное на gh-pages +10
[+]вёрстка валидная +10
[+]вёрстка семантическая +20
[+]В коде странице присутствуют и используются по назначению следующие элементы:
[+]header, main, footer +5
[+]элемент nav +5
[+]только один заголовок h1 +5
[-]заголовки h2 -0
[+]в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
[+]для оформления СV используются css-стили +10
[+]при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
[+]на странице СV есть фото автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка +10
CV содержит:
[+]краткую информацию о себе +5
[+]контакты для связи +5
[+]перечень навыков +5
[-]пример кода. Код добавлен при помощи символов и тегов -0
[+ ]перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
[+]информацию об образовании и уровне английского +5
[+]CV выполнено на английском языке +10

Здравствуйте! Я перепутал дедлайн сдачи CV#3 Cross-Check и не успел проверь работы других студентов. Могу ли я еще сдать работу? Большое спасибо!

**Comment by mserykh** [comment]
Оценка 120
Мне понравился ваш дизайн, а ещё вы сделали ваше резюме responsive и меню для мобилок, круто!
Хорошо бы добавить h2 и hover эффекты на ссылки, сейчас у вас ссылки не отличаются от текста. 
Отличная работа, успехов в обучении!

**Comment by 4oVEN** [comment]
Большое спасибо!) Очень приятно получить такую высокую оценку!
