### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Ilia Shavrin'

### ISSUE THREAD

**Issue by Garthaur** [rolling-scopes-school/support#349]
1 Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Screenshot:  
![image](https://user-images.githubusercontent.com/64901116/148528520-0bfa59b2-249b-4113-9bbb-1bdac61392a4.png)
3 My repository: https://github.com/Garthaur/rsschool-cv
4 Deploy:  https://garthaur.github.io/rsschool-cv/
5 Score:  110/120
6  засабмиченна в rs app ссылка на CV, задеплоенное на gh-pages +10
[+]вёрстка валидная +10
[+]вёрстка семантическая +20
[+]В коде странице присутствуют и используются по назначению следующие элементы:
[+]header, main, footer +5
[+]элемент nav +5
[+]только один заголовок h1 +5
[+]заголовки h2 +5
[+]в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
[+]для оформления СV используются css-стили +10
[-]при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +0
[+]на странице СV есть фото автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
[+]навигация, контакты для связи и перечень навыков оформлены в виде списка +10
CV содержит:
[+]краткую информацию о себе +5
[+]контакты для связи +5
[+]перечень навыков +5
[+]пример кода. Код добавлен при помощи символов и тегов +5
[+]перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
[+]информацию об образовании и уровне английского +5
[+]CV выполнено на английском языке +10

Здравствуйте, немножко запутался с дедлайном.
при масштабировании верстка не сдвигается в стороны но футер и хидер отрываются
ссылку на проект вставил кривовато, она ведёт на репозиторий, а не на сайт, решил включить в оценку так как в CV присутствует)

**Comment by irinainina** [comment]
Ты засабмитил работу в rs app? Тогда дождись результата проверки. Апелляции до дедлайна кросс-чека только для тех, кто не засабмитил таск вовремя

**Comment by Garthaur** [comment]
я не засабмитил
если речь об этом "засабмиченна в rs app ссылка на CV, задеплоенное на gh-pages +10", то прошу прощения я неправильно понял этот пункт)

**Comment by Garthaur** [comment]
я не засабмитил
если речь об этом "засабмиченна в rs app ссылка на CV, задеплоенное на
gh-pages +10", то прошу прощения я неправильно понял этот пункт)

пт, 7 янв. 2022 г. в 13:46, Irina ***@***.***>:

**Comment by Bumble-sakh** [comment]
120 баллов
 Молодец. Для, как я понимаю, первой верстки хорошо.
 А самое главное, ты полностью выполнил все пункты задания.
 Ну и цветовая гамма веселенькая)
 
Не останавливайся на достигнутом, развивайся дальше!

**Comment by Garthaur** [comment]
спасибо, буду стараться))
