### ISSUE TITLE
Cross-Check Singolo - IlyaShihutin

### ISSUE THREAD

**Issue by IlyaShihutin** [rolling-scopes-school/support#35]
1. Ссылка на деплой: https://IlyaShihutin.github.io/singolo/ .
2. Ссылка на репозиторий с проектом: https://github.com/IlyaShihutin/singolo .
3. Считаю что работа выполнена на 94 балла :
    1)В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла
    2) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла

4. 
             Student 2
Ваша оценка - 76 баллов
(тут проверяющий насчитал 7 ошибок по -3, а в итоге поставил -24)
Отзыв по пунктам:

1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Portfolio составляют более двух пикселей (2px): минус -3 балла
(Не согласен, так как отклонение меньше 2px)
2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла
(Не согласен, так как отклонение меньше 2px)
3) В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла
(Согласен)
4) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла
(Согласен)
5) Социальные иконки в секции About без интерактивных стилей, при наведении на логотипы соц.сетей ничего не происходит: минус -3 балла
(Не согласен, интерактивность имеется)
6) Внутри тэга "< form >" отсутствует кнопка Submit, или она реализована не с помощью "< button >" или "< input >": минус -3 балла
(Не согласен , кнопка в форме имеется)
7) Социальные иконки в Footer-e без интерактивных стилей, при наведении на логотипы соц.сетей ничего не происходит: минус -3 балла
(Не согласен, интерактивность имеется)

             Student 1
1) В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020: минус -10 баллов
(Согласен на половину, файлы до дедлайна есть, но неправильно названы)
2) В коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020: минус -10 баллов
(Не согласен, все имеется)
3) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла
(Согласен)

**Comment by amoebiusss** [comment]
@IlyaShihutin привет! Ваша итоговая оценка по обновленному алгоритму — 83, наименьшая оценка была исключена из подсчета. Итоговая от заявленной отличается на 11 баллов, минимальная разница для апелляции — 15, поэтому закрываю ишью. Хорошего дня!
