### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Veronika Rusakovich'

### ISSUE THREAD

**Issue by VerikaVeri** [rolling-scopes-school/support#350]
Deploy: https://VerikaVeri.github.io/rsschool-cv/
Repository: https://github.com/VerikaVeri/rsschool-cv
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Screenshot:
![support2](https://user-images.githubusercontent.com/91460353/148540312-2ba6cbd3-1dad-4f05-bdf1-a3966e0fb066.jpg)

Score: 120/120
[+]засабмиченна в rs app ссылка на CV, задеплоенное на gh-pages +10
[+]вёрстка валидная +10
[+]вёрстка семантическая +20
[+]В коде странице присутствуют и используются по назначению следующие элементы:
[+]header, main, footer +5
[+]элемент nav +5
[+]только один заголовок h1 +5
[-]заголовки h2 -0
[+]в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
[+]для оформления СV используются css-стили +10
[+]при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
[+]на странице СV есть фото автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка +10
CV содержит:
[+]краткую информацию о себе +5
[+]контакты для связи +5
[+]перечень навыков +5
[+]пример кода. Код добавлен при помощи символов и тегов 10
[+ ]перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
[+]информацию об образовании и уровне английского +5
[+]CV выполнено на английском языке +10

Здравствуйте, у меня проблема - 4 января было создано CV3 и отправлено на проверку, все сломалось на Замержите Pull Request из ветки rsschool-cv-html в ветку gh-pages, пока возилась с этой ошибкой, все сроки вышли и пришлось смириться с тем, что провалила задание((( Потом увидела, что дедлайн перенесли на 13-е, продолжила разбираться с ошибкой, а потом оказалось, что дедлайн оставили 6-го. Подскажите, что мне делать, есть ли еще шанс сдать задание?

**Comment by Bumble-sakh** [comment]
CV не задеплоено.
ветки gh-pages и rsschool-cv-html пустые.

**Comment by VerikaVeri** [comment]
> CV не задеплоено. ветки gh-pages и rsschool-cv-html пустые.

Проблема с git push: git bash  выдает ошибку и просит логин (в браузере залогинилась в git hub). По рекомендации (дискорд) создала ssh ключ

Сделать git bash по-прежнему не получается, тк на гите старая версия CV3, а на компе - новая, папка сохранена на диске д, а не перенесена с гита на десктоп (как в инструкции по ключам)... Подскажите, что делать, чтобы перенести CV3 с компа на гит (git bash по-прежнему выдает ошибку)?

**Comment by igorlyatskiy** [comment]
@VerikaVeri этот вопрос лучше задать в дискорд-канале `git-stage0` или `cv-stage0`

**Comment by VerikaVeri** [comment]
> @VerikaVeri этот вопрос лучше задать в дискорд-канале `git-stage0` или `cv-stage0`

Спасибо, вроде починила, проверьте еще раз, пожалуйста

**Comment by igorlyatskiy** [comment]
Ничего не изменилось. Вам надо создать PR из ветки `rsschool-cv-html` в ветку `gh-pages` и замержить его

**Comment by spherical-horse** [comment]
**Ваша оценка - 110 баллов** 

Отзыв по пунктам ТЗ:

Не выполненные/не засчитанные пункты:
1) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 
_feedback: Верстка изначально прибита к левому краю. Там и остается при изменении масштаба._
Частично выполненные пункты:
1) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 
_feedback: Ссылки добавлены некорректно, и из-за этого не отображаются на экране._ 
2) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
_feedback: Контакты для связи выполнены не в виде списка. Можно было использовать список из одного элемента_

Выполненные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 
2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 
3) header, main, footer 
4) элемент nav 
5) только один заголовок h1 
6) заголовки h2 
7) для оформления СV используются css-стили 
8) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 
9) краткую информацию о себе 
10) контакты для связи 
11) перечень навыков 
12) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 
13) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 
14) информацию об образовании и уровне английского 
15) CV выполнено на английском языке
