### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Leonid-Niselovsky'

### ISSUE THREAD

**Issue by Leonid-Niselovsky** [rolling-scopes-school/support#351]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot:
![Screen Shot 2022-01-07 at 6 23 53 AM](https://user-images.githubusercontent.com/88901199/148551665-bc7cea95-56cd-4640-99f7-d10932a9fb53.png)
![Screen Shot 2022-01-07 at 6 24 33 AM](https://user-images.githubusercontent.com/88901199/148551676-e13f51b3-85c9-4030-aebc-738d67c86bd4.png)
3. My repository: https://github.com/Leonid-Niselovsky/rsschool-cv
4. Deploy: https://Leonid-Niselovsky.github.io/rsschool-cv/
5. Score: 120 / 120
 [x] засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages (+10)
 [x] вёрстка валидная (+10)
для проверки валидности вёрстки используйте сервис https://validator.w3.org/
валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью.
если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
[x] вёрстка семантическая (+20)
В коде странице присутствуют и используются по назначению следующие элементы:
Под "используются по назначению" имеется в виду, что у элементов есть какое-то содержание, соответствующее типу элемента, а не добавлены пустые теги для получения баллов. Правильность использования элементов не проверяется и на балл не влияет.
[x] header, main, footer (+5)
[x] элемент nav (+5)
[x] только один заголовок h1 (+5)
[x] заголовки h2 (+5)
[x] в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс (+10)
[x] для оформления СV используются css-стили (+10)
[x] при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (+10)
[x] на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt (+10)
[x] навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a (+10)
[x] Содержание CV (+30)
CV содержит:
[x] краткую информацию о себе (+5)
[x] контакты для связи (+5)
[x] перечень навыков (+5)
[x] пример кода. Код добавляется при помощи символов и тегов, а не картинкой (+5)
[x] перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения (+5)
[x] информацию об образовании и уровне английского (+5)
[x] CV выполнено на английском языке (+10)

Извиняюсь что перепутал сроки дедлайнов, проверьте пожалуйста, работа очень похожа на пример с задания, я только учусь вёрстке и по этому взял дизайн с примера за основу, я не копировал код, а лишь делал всё согласно гайдлайна

**Comment by Bumble-sakh** [comment]
120 баллов.
Молодец. Хорошее, приятное cv. Даже добавить нечего.
Продолжай в том же духе.

**Comment by Leonid-Niselovsky** [comment]
> 120 баллов. Молодец. Хорошее, приятное cv. Даже добавить нечего. Продолжай в том же духе.

Большое спасибо за приятный фидбэк
