### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Alexandra Sergeychik'

### ISSUE THREAD

**Issue by aliaxandra** [rolling-scopes-school/support#352]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot:
![sergeychik-cv](https://user-images.githubusercontent.com/12713348/148579606-6e5ee754-10e3-4f75-9025-d9bd41e05fcc.png)
3. My repository: [https://github.com/aliaxandra/rsschool-cv](https://github.com/aliaxandra/rsschool-cv)
4. Deploy: https://aliaxandra.github.io/rsschool-cv
5. Score: 120 / 120 
- [x] студент засабмитил в [rs app](https://app.rs.school/course/student/cross-check-submit?course=js-fe-preschool) ссылку на своё CV, задеплоенное на `gh-pages` +10 
- [x] вёрстка валидная +10 
- [x] вёрстка семантическая +20 
  - [x] `header`, `main`, `footer` +5 
  - [x] элемент `nav` +5 
  - [x] о один заголовок `h1` +5 
  - [x] заголовки `h2` +5 
- [x] в footer есть ссылка на гитхаб автора работы, год создания приложения, [логотип курса](https://rs.school/images/rs_school_js.svg) со [ссылкой на курс](https://rs.school/js/) Если ссылка в футере ведёт на [курс stage0](https://rs.school/js-stage0/), это не ошибка. +10
- [x] для оформления СV используются css-стили +10 
- [x] при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10 
- [x] на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут `alt` +10 
- [x] навигация, **контакты** для связи и **перечень навыков** оформлены в виде списка `ul > li` или `ul > li > a`. Также допускается использование нумерованого списка `ol > li` или `ol > li > a` +10 
- [x] Содержание CV +30
  - [x] краткую информацию о себе +5 
  - [x] контакты для связи +5 
  - [x] перечень навыков +5 
  - [x] пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5 
  - [x] перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5 
  - [x] информацию об образовании и уровне английского +5 
- [x] CV выполнено на английском языке +10

Я сориентировалась на измененные сроки в связи с событиями в Казахстане, решила воспользоваться дополнительным временем, чтобы добавить responsive и использовать этот CV в будущем. Прошу проверить!

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов** 

Отзыв по пунктам ТЗ:
Выполненные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

16) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

17) информацию об образовании и уровне английского 

18) CV выполнено на английском языке

**Comment by aliaxandra** [comment]
**Мои баллы не отображаются в Score.** 
Прошу добавить.

![image](https://user-images.githubusercontent.com/12713348/149326058-263c4ede-574c-482d-90be-3983ff90d4b6.png)

Спасибо!
