### ISSUE TITLE
CV#3. CV. Cross Check -Tolkachova Yulia

### ISSUE THREAD

**Issue by yuliabalkiss** [rolling-scopes-school/support#353]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot:
![Снимок](https://user-images.githubusercontent.com/93052112/148597555-318b50bd-17de-46db-9234-96145cefa35a.JPG)
3. Deploy: https://yuliabalkiss.github.io/rsschool-cv/
4.  Score:120/120
5. Критерии оценки
Максимальный балл за задание +120

{+}студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
(+)вёрстка валидная +10
(+)header, main, footer +5
(+)элемент nav +5
(+)только один заголовок h1 +5
(+)заголовки h2 +5
(+)в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
(+)для оформления СV используются css-стили +10
(+)при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
(+)на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
(+)навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
 (+)CV содержит краткую информацию о себе +5
(+)контакты для связи +5
(+)перечень навыков +5
(+)пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
(+)перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
(+)информацию об образовании и уровне английского +5
(+)CV выполнено на английском языке +10

Добрый вечер, в связи с переносами дедлайна по Сross Check, после submita ссылки на Сv продолжила работу над проектом. По завершению оформления, обнаружила, что мое CV уже проверили и выставили баллы, по незаконченному варианту. Можно ли перепроверить мою работу, законченного варианта. Благодарю.

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов** 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) элемент nav 

2) только один заголовок h1 

Выполненные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) заголовки h2 

5) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

6) для оформления СV используются css-стили 

7) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

8) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

9) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

10) краткую информацию о себе 

11) контакты для связи 

12) перечень навыков 

13) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

14) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

15) информацию об образовании и уровне английского 

16) CV выполнено на английском языке

**Comment by yuliabalkiss** [comment]
Спасибо, за проверку.
