### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Yuri Solianin'

### ISSUE THREAD

**Issue by yuri-sol** [rolling-scopes-school/support#354]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md#%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%B2%D1%91%D1%80%D1%81%D1%82%D0%BA%D0%B5
2. Screenshot:
![screen3](https://user-images.githubusercontent.com/96115159/148599911-497f7555-04b6-490c-b2da-d069c53f9f60.png)
3. Deploy: https://yuri-sol.github.io/rsschool-cv/
4. Done 07.01.2022 / deadline 06.01.2022
5. Score: 115/120

- засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10;
- вёрстка валидная +10
- header, main, footer +5
- элемент nav +5
- только один заголовок h1 +5
- заголовки h2 +5
- в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
- для оформления СV используются css-стили +10
- при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
- на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
- навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10

CV содержит:
- краткую информацию о себе +5
- контакты для связи +5
- перечень навыков +5
- пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
- информацию об образовании и уровне английского +5
- CV выполнено на английском языке +10

Здравствуйте. Запутался что то в переносах дедлайнов. Если кто то сможет оценить эту первую в жизни верстку , то буду благодарен. Из общей суммы вычел 5 баллов за "перечень выполненных учебных проектов" , который отсутствует.
Общий стиль продиктован условиями таска и стремлением к минимализму)

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов**
 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

Выполненные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

16) информацию об образовании и уровне английского 

17) CV выполнено на английском языке

**Comment by yuri-sol** [comment]
Благодарю!
