### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Sqverick'

### ISSUE THREAD

**Issue by Sqverick** [rolling-scopes-school/support#355]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot:
![image](https://user-images.githubusercontent.com/69648214/148598576-4631ac40-7a4d-4e22-b840-82c3ac2c79ea.png)
3. Deploy: https://sqverick.github.io/rsschool-cv/
4. Done 07.01.2022 / deadline 06.01.2022
5. Score: 120/130
- сабмит в rs app ссылку на своё CV, задеплоенное на gh-pages +10
- вёрстка валидная +10
- вёрстка семантическая +20
В коде присутствуют:
а)header, main, footer +5
б)элемент nav +5
в)только один заголовок h1 +5
г)заголовки h2 +5
 - в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
- для оформления СV используются css-стили +10
 - при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +5/10
- на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
- навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
Также допускается использование нумерованого списка ol > li или ol > li > a
- Содержание CV +25
CV содержит:
краткую информацию о себе +5
контакты для связи +5
перечень навыков +5
пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 0/5
информацию об образовании и уровне английского +5
-CV выполнено на английском языке +10

Произошла следующая ситуация: в ночь на 6 января у меня было готово задание полностью, но возникли проблемы с гитхабом, с которыми я очень долго разбиралась. Я увидела информацию о том, что сроки дедлайнов перенесены, поэтому решила, что лучше выполню задание чуть позже в меньшей спешке. 
Сегодня 7.01.2022 я выполнила задание, но сроки дедлайна уже были нарушены.
Есть еще один момент: если посмотреть по моим коммитам, то проект создан сегодня. На самом деле он выполнялся несколько дней подряд, но, увы, проблемы с гитхабом не были решены, поэтому пришлось создать проект с самого начала. 
Если посмотреть мою историю выполнения заданий в приложении RSS, то за CV1 и CV2 у меня стоит по 100 баллов, а значит cv существовал до сегодняшнего дня. 
Очень прошу проверить задание!

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов** 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

Выполненные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

16) информацию об образовании и уровне английского 

17) CV выполнено на английском языке
