### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - Maxim-Kolmykov

### ISSUE THREAD

**Issue by maxim-kolmykov** [rolling-scopes-school/support#357]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot:
![2022-01-08_05-49-36](https://user-images.githubusercontent.com/96133680/148629087-775c8cb6-d7ac-4499-a965-983f606fbb8e.jpg)
3. Deploy: https://maxim-kolmykov.github.io/rsschool-cv/
4. Score:120/120
5. Критерии оценки
Максимальный балл за задание +120
(+) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
(+) вёрстка валидная +10
(+) вёрстка семантическая +20
header, main, footer +5
элемент nav +5
только один заголовок h1 +5
заголовки h2 +5
(+) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
(+) для оформления СV используются css-стили +10
(+) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
(+) на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
(+) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
(+) Содержание CV +30
CV содержит:
краткую информацию о себе +5
контакты для связи +5
перечень навыков +5
пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
информацию об образовании и уровне английского +5
(+) CV выполнено на английском языке +10

Здравствуйте!  Запутался датой CV#3 Cross-Check в связи с переносами дедлайнов на позднее число, и по этому не нажал на Submit, думал времени предостаточно, и хотел засабмитить (идеальную для меня) адаптивную верстку с @media, плюс боролся неустранимыми багами кроссплатформенности и адаптивности, а потом несколько суток был без доступа к компьютеру, в итоге когда узнал о переносе дедлайнов, пришлось задеплоить проект "как есть", без @media запросов.  Хотелось бы что-бы работа не пропала и была оценена.  Не стал добавлять в "перечень выполненных учебных проектов" древние сайты и сверстанные письма 12 летней давности с табличной версткой, к тому же исходников не сохранилось, а ссылки на веб.архив на рекламно-коммерческими проекты не подходит под понятие "учебные проекты". 
Очень прошу проверить задание! Заранее благодарю!

**Comment by irinainina** [comment]
120 баллов
Отличная работа, хороший код, качественный дизайн.
Этот таск будет выдаваться на этапе stage#1, там появятся новые требования в т.ч требования по адаптивности, возможность его доработать ещё будет
Такие работы проверять легко и приятно. Спасибо!

**Comment by maxim-kolmykov** [comment]
> 120 баллов Отличная работа, хороший код, качественный дизайн. Этот таск будет выдаваться на этапе stage#1, там появятся новые требования в т.ч требования по адаптивности, возможность его доработать ещё будет Такие работы проверять легко и приятно. Спасибо!

Большое спасибо! За то что оценили работу! Очень приятно слышать позитивную оценку!
