### ISSUE TITLE
Cross-Check 'CV#3. Cross Check'

### ISSUE THREAD

**Issue by bsandue** [rolling-scopes-school/support#358]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2.
![Скриншот 2022-01-08 12 41 53](https://user-images.githubusercontent.com/89155849/148634667-c9e26981-c360-4abe-a590-3ae6c1edf23f.png)
![Скриншот 2022-01-08 12 42 03](https://user-images.githubusercontent.com/89155849/148634669-244582a3-b0d6-4a7d-b7ad-3d82c262b679.png)
3. My repository: https://github.com/bsandue/rsschool-cv
4. Deploy: https://bsandue.github.io/rsschool-cv/
5. Score: 100/120  засабмиченна в rs app ссылка на CV, задеплоенное на gh-pages +10
[+/-]вёрстка валидная +10
[x]вёрстка семантическая +20
[x]В коде странице присутствуют и используются по назначению следующие элементы:
[x]header, main, footer +5
[x]элемент nav +5
[x]только один заголовок h1 +5
[x]заголовки h2 +5
[x]в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
[x]для оформления СV используются css-стили +10
[x]на странице СV есть фото автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка +10
CV содержит:
[x]краткую информацию о себе +5
[x]контакты для связи +5
[x]перечень навыков +5
[x]пример кода. Код добавлен при помощи символов и тегов +5
[ ]перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +0
[+/-]информацию об образовании и уровне английского +5
[x]CV выполнено на английском языке +10
Здравствуйте! Я не смогла здать раньше в срок из-за отсутствия интернета в нашем регионе. Могу ли я еще сдать работу? Спасибо

**Comment by turn2river** [comment]
120 баллов
Хорошая работа с приятной цветовой гаммой.
Несколько моментов которые стоит подкорректировать:
- Заголовок h1 имеет абсолютное позиционирование, из-за чего на разных разрешениях он "ползает вверх-вниз"
- Валидатор ругается на 122 строку в html, там есть лишнее слово git, валидатор воспринимает это как атрибут.
- Иконки гитхаба и школы в footer-е - растянуты, иконкам стоит задать только один из атрибутов: height или width, тогда они будут уменьшены пропорционально. 

Хорошая работа, удачного обучения! :)
