### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Ksenia Neustroeva'

### ISSUE THREAD

**Issue by k0ntinuum** [rolling-scopes-school/support#359]
1. Deploy: https://k0ntinuum.github.io/rsschool-cv/
![image](https://user-images.githubusercontent.com/90222151/148544355-9e28c8c7-bcfd-49a0-9124-772551cd5ce2.png)
2. Repository: https://github.com/k0ntinuum/rsschool-cv/
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. Score: 125 / 130
- [x] студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages (+10)
- [x] вёрстка валидная
https://validator.w3.org/: Document checking completed. No errors or warnings to show.  (+10)
- [x] header, main, footer (+5)
- [x] элемент nav (+5)
- [x] только один заголовок h1 (+5)
- [x] заголовки h2 (+5)
- [x] в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс (+10)
- [x] для оформления СV используются css-стили (+10)
- [x] при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (+10)
- [x] на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt (+10)
- [x] навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a (+10)

CV содержит:
- [x] краткую информацию о себе (+5)
- [x] контакты для связи (+5)
- [x] перечень навыков (+5)
- [x] пример кода. Код добавляется при помощи символов и тегов, а не картинкой (+5)
- [ ] перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения (0 баллов)
- [x] информацию об образовании и уровне английского (+5)
- [x] CV выполнено на английском языке (+10)

Здравствуйте. Из-за путаницы с дедлайнами я успела засабмитить ссылку, но отложила выполнение таска буквально на следующий день (потому что была уверена в другой дате), из-за чего трое проверяющих коллективно под вечер выставили мне 0 баллов (правда, один поставил мне чьи-то 90 баллов за отсутствующую на момент его проверки работу).
Ревью студентов я выполнила, прошу вас проверить и мою работу. Благодарю.

**Comment by turn2river** [comment]
120 баллов

Отличная минималистичная работа!
Из комментариев только про раздел с проектами, который можно добавить и дать ссылку на проект CV.
В остальном всё хорошо, работа понравилась, такие работы приятно проверять! 
Удачного обучения! :)

**Comment by k0ntinuum** [comment]
Очень приятно, большое спасибо за ревью!
