### ISSUE TITLE
Cross-Check Singolo - OksanaTukach

### ISSUE THREAD

**Issue by OksanaTukach** [rolling-scopes-school/support#36]
1. Ссылка на деплой проекта: https://oksanatukach.github.io/Singolo/
2. Ссылка на репозиторий с проектом на GitHub: https://github.com/OksanaTukach/Singolo 
3. Считаю, что работа выполнена на 77-80 баллов : 
     1) В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 
         24.02.2020: минус -10 баллов
     2) В коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 
         02.03.2020: минус -10 баллов
4. Балл за cross-check из Score: 62

Student 1
Singolo 1:

First of all, commit history says that it was submitted after the deadline. (с этим согласна)

Header: The logo's letter-spacing is not set properly which makes it more stretched horizontally than in the PSD files.( не согласна, отклонения меньше 2px) 

The navigation items are set properly but they are missing a small circle in between. ( согласна)

Slider - looks fine, again hardcoded. The arrows could have another interactive effect than making it bigger. A color change is better for the user maybe. ( с этим согласна, но это не должно влиять на оценку)

Our services: The icons are not properly centered, the text is a little offset. (менее 2px)

Singolo 2: Submitted after the deadline. (согласна)

The texts in both blocks are a little off. The first block was done using flex, kudos for that. The navigation for the portfolio block is a little offset. The pictures and social icons in About Us block are a little bigger? (не согласна)

Singolo 3: Submitted on the deadline.

The text aside the form is not formatted right. 
A line in the text is added redundantly. ( с этим не согласна)
The form placeholders are not positioned as per PSD. (согласна)
The footer copyright text is missing a space -- 'Copyright2013'. (действительно забыла поставить пробел)
The social icons are bigger. ( не согласна)

Overall, I'd mark the work for around 70, however since two blocks were submitted after the deadline, I have to subtract 20 points. Mark: 50. 

Student 2
Ваша оценка - 71 баллов 

Отзыв по пунктам ТЗ:

1) В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020: минус -10 баллов ( согласна)

2) В коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020: минус -10 баллов (согласна)

3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла (не вижу различий более 2px)

4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла (не вижу различий более 2px)

5) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла (не согласна)

Student 3
1. Больше всего бросаются в глаза изображения телефонов при просмотре через firefox. Их нужно было не вырезать из макета вместе с фоном, а сделать одним из трех способов, описанных в задании.( я сделала одним из 3 способов)

2. На оценку также повлияло отсутствие сабмитов по singolo1 и singolo2 в срок до 24.02.2020 и 02.03.2020 соответственно.

3. Трехколоночный макет Our Services сделан хорошо, однако изображения несимметричны и имеют отклонения от макета.(отклонения не более 2px)

4. Текст профиля в блоке About Us не переносится на другую строку при добавлении символов, но обрезается до одного слова.(не согласна)

**Comment by amoebiusss** [comment]
@OksanaTukach привет! Верстка выглядит неплохо и в Chrome, и в Firefox. Но я заметила такие погрешности:

1. Из-за того, что перенос текста в абзаце сделан тегом `<br>`, он появляется именно в этом месте при любой ширине блока: 
![image](https://user-images.githubusercontent.com/26903136/77312403-fd9d3a00-6d12-11ea-87f5-5697cf162c95.png)

Более корректным способом реализации текста с переносами будет использование css-свойства `hyphens`: https://css-tricks.com/almanac/properties/h/hyphenate/

2. Не очень аккуратно позиционированы иконки в блоке Our Services. Скриншот верстки: 
![image](https://user-images.githubusercontent.com/26903136/77313312-a9935500-6d14-11ea-8ce6-26cf1e4fe5a3.png)

И тот же блок из макета: 
![image](https://user-images.githubusercontent.com/26903136/77313368-cb8cd780-6d14-11ea-8b11-ea04de44e58e.png)

3. Не заданы отступы и правильные стили для текста в input и textarea:
![image](https://user-images.githubusercontent.com/26903136/77313645-46ee8900-6d15-11ea-8697-84b6874b6322.png)

4. Иконка не такая, как в макете. Верстка: 
![image](https://user-images.githubusercontent.com/26903136/77313749-7e5d3580-6d15-11ea-88a2-6bb3acb63b78.png)

Иконка из макета:
![image](https://user-images.githubusercontent.com/26903136/77313783-8a48f780-6d15-11ea-8f4a-498d56cabfc2.png)


Расчет финальной оценки:
100 - 10 * 2 (несоблюдение дедлайнов) - 3 (уехавший текст в секции Get a Quote) - 3 (иконки) - 3 (стили текста в полях формы) = **71 балл**
