### ISSUE TITLE
CV#3. CV. Cross Check DmitryYarigin

### ISSUE THREAD

**Issue by DmitryYarigin** [rolling-scopes-school/support#361]
1. https://DmitryYarigin.github.io/rsschool-cv/ 
 2.  https://github.com/DmitryYarigin
 3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
 4. https://cv-cross-check.netlify.app/
 5. https://i.ibb.co/vHhKCJ3/2022-01-08-13-00-01.png
 6. 105. верстка не валидная и нет перечня выполненных работ а не как не 85 как оценил один член жури
 7. балла еще нет

**Comment by irinainina** [comment]
Апелляции принимаются только после дедлайна кросс-чека, если балл за кросс-чек больше чем на 10% отличается от самооценки.
Апелляция отклонена.

**Comment by irinainina** [comment]
Закрываю, если балл за кросс-чек больше чем на 10% будет отличаться от самооценки, создай, пожалуйста, новое
