### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Vadim Martinkevich'

### ISSUE THREAD

**Issue by Wadimx199789** [rolling-scopes-school/support#362]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Screenshot:
![image](https://user-images.githubusercontent.com/60059458/148647629-10fb89c8-3d55-4c4e-8b60-e3ccb236fbc5.png)
Deploy: https://wadimx199789.github.io/rsschool-cv/
Score:125/130
Критерии оценки
Максимальный балл за задание +120
{+}студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
(+)вёрстка валидная +10
(+)header, main, footer +5
(+)элемент nav +5
(+)только один заголовок h1 +5
(+)заголовки h2 +5
(+)в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
(+)для оформления СV используются css-стили +10
(+)при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
(+)на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
(+)навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
(+)CV содержит краткую информацию о себе +5
(+)контакты для связи +5
(+)перечень навыков +5
(-)пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
(+)перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
(+)информацию об образовании и уровне английского +5
(+)CV выполнено на английском языке +10

Добрый вечер, в связи с переносами дедлайна по Сross Check, продолжил работу над проектом. По завершению оформления, обнаружил, что мое CV уже нельзя засабмитить. Можно ли проверить мою работу?  Благодарю.

**Comment by spherical-horse** [comment]
**Ваша оценка - 103 балла** 

Отзыв по пунктам ТЗ:

Не выполненные/не засчитанные пункты:

1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

2) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

Частично выполненные пункты:

1) header, main, footer 
_feedback: Нет тега main_

2) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 
_feedback: Нет ссылки на гитхаб. При клике на логотип гитхаба откроется ссылка на курс._

3) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
_feedback: Отсутствует навигация (не теги nav, а что-то вроде меню.)_

Выполненные пункты:

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) элемент nav 

3) только один заголовок h1 

4) заголовки h2 

5) для оформления СV используются css-стили 

6) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

7) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

8) краткую информацию о себе 

9) контакты для связи 

10) перечень навыков 

11) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

12) информацию об образовании и уровне английского 

13) CV выполнено на английском языке
