### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'lilpavlik'

### ISSUE THREAD

**Issue by lilpavlik** [rolling-scopes-school/support#363]
Добрый вечер! В связи с сессией в университете, а честно говоря в большей степени в связи с моей невнимательностью я не правильно разобрался с 3 заданием CV и не засамбил его, думая, что третье задание это просто проверка. Был не прав, в следующий раз буду внимательнее. Есть ли возможность засамбить 3 СV, через апелляцию, я буду очень благодарен? Спасибо за ответ 

Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md  
 
Markdown CV: https://lilpavlik.github.io/rsschool-cv/cv

HTML&CSS CV: https://lilpavlik.github.io/rsschool-cv/

GitHub rsschool-cv-html: https://github.com/lilpavlik/rsschool-cv/tree/rsschool-cv-html

Screenshot: 
![image](https://user-images.githubusercontent.com/92550782/148652136-3616b5c8-97eb-46b9-964c-1933a24d3193.png)

![image](https://user-images.githubusercontent.com/92550782/148652145-4e01159b-5765-4fcb-ad71-3dd3dc8f0b70.png)

**Comment by irinainina** [comment]
Пожалуйста, оформи issue по требованиям https://docs.rs.school/#/cross-check-flow?id=Апелляция
Не хватает пункта
- Оценка в результате самопроверки с ее аргументацией. Т.е. самооценку нужно сделать по пунктам

**Comment by irinainina** [comment]
Закрываю, так как создано второе issue https://github.com/rolling-scopes-school/support/issues/368
