### ISSUE TITLE
CV#3 Cross-Check _ Doston Kayimov

### ISSUE THREAD

**Issue by DostonKayimov** [rolling-scopes-school/support#364]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot:
![photo_2022-01-08_20-27-03](https://user-images.githubusercontent.com/82517850/148651763-31eb33fe-79de-4ca4-899f-a8fd924feb55.jpg)
3. My repository: https://github.com/DostonKayimov/rsschool-cv
4. Deploy: https://DostonKayimov.github.io/rsschool-cv/

 -студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
 -вёрстка валидная +10
 -вёрстка семантическая +20
В коде странице присутствуют и используются по назначению следующие элементы
-header, main, footer +5
 -элемент nav +5
 -только один заголовок h1 +5
 -заголовки h2 +5
 -в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
Если ссылка в футере ведёт на курс stage0, это не ошибка
-для оформления СV используются css-стили +10
 -при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
 -на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
 -навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
Также допускается использование нумерованого списка ol > li или ol > li > a
 -Содержание CV +30
CV содержит:
 -краткую информацию о себе +5
 -контакты для связи +5
 -перечень навыков +5
 -пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
 -перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
 -информацию об образовании и уровне английского +5
 -CV выполнено на английском языке +10

**Привет! Я по ошибке поставил неправильную ссылку на кнопку "Submit".
Могу ли я по-прежнему представлять свою работу?
Спасибо!**

**Comment by irinainina** [comment]
Привет! Твою работу проверят в ходе кросс-чека. Апелляцию можно будет подать только если балл за работу после дедлайна кросс-чека будет минимум на 10% ниже самооценки.
Сейчас апелляцию отклоняю.

**Comment by irinainina** [comment]
105 баллов по результатам кросс-чека
Успехов!
