### ISSUE TITLE
CV#3. CV. Cross Check [Jamal Muslimov (SkarabeyDM)] (Апелляция)

### ISSUE THREAD

**Issue by SkarabeyDM** [rolling-scopes-school/support#365]
1. Deploy: https://skarabeydm.github.io/rsschool-cv/
![image](https://user-images.githubusercontent.com/46022177/148651102-00ead74a-e436-46db-ac6e-75b58614be70.png)
2. Repository: https://github.com/SkarabeyDM/rsschool-cv/
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. Score: 130/130

- [x] Засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages (+10)
- [x] Вёрстка валидная, за исключением того, что валидатор ругается на экземпляр кода (+10)
https://validator.w3.org/ 
![image](https://user-images.githubusercontent.com/46022177/148651451-52357f20-61ed-4a6b-91d1-c48bc5d0b32e.png)
- [x] header, main, footer (+5)
- [x] элемент nav (+5)
- [x] h1 только один (+5)
- [x] заголовки h2 (+5)
- [x] в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. (+10)
- [x] для оформления СV используются css-стили (+10)
- [x] при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (+10)
- [x] на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. (+10)
- [x] навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a (+10)
- [x] краткую информацию о себе (+5)
- [x] контакты для связи (+5)
- [x] перечень навыков (+5)
- [x] пример кода. Код добавляется при помощи символов и тегов, а не картинкой (+5)
- [x] перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения (+5)
- [x] информацию об образовании и уровне английского (+5)
- [x] CV выполнено на английском языке (+10)

Здравствуйте! Извиняюсь, что опоздал со сдачей таска, надеюсь, больше не повторится.

**Comment by irinainina** [comment]
120 баллов. Очень хорошая красивая и интересная работа. Проверять такие одно удовольствие. Спасибо!

**Comment by SkarabeyDM** [comment]
@irinainina, благодарствую)
