### ISSUE TITLE
CV#3. CV. Cross Check [Mikalai Paliakou (@lazzzaroni)] (апелляция)

### ISSUE THREAD

**Issue by lazzzaroni** [rolling-scopes-school/support#366]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot:
<img width="495" alt="Screenshot 2022-01-03 at 10 46 34" src="https://user-images.githubusercontent.com/68731150/147917336-9c7a3c84-fac7-438b-b31f-95b870efa305.png">

3. Deploy: https://lazzzaroni.github.io/rsschool-cv/
4. Done 03.01.2022 / deadline 03.01.2022
5. Score: 130 / 120

- [ 10 ] - студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages (10/10)
- [ 10 ] - вёрстка валидная (10/10)
- [ 20 ] вёрстка семантическая (20/20)
- [ 10 ] - в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс (10/10)
- [ 10 ] - для оформления СV используются css-стили (10/10)
- [ 10 ] - при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (10/10)
- [ 10 ] - на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt (10/10)
- [ 10 ] - навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a (10/10)
- [ 30 ] - Содержание CV (30/30)
- [ 10 ] - CV выполнено на английском языке (10/10)

**Comment by turn2river** [comment]
120 баллов.

CV супер! Один из проектовForkify App - особенно понравился, очень высокий уровень исполнения. Тебе пора искать работу :)
