### ISSUE TITLE
CV3 after deadline.Consider my task please.

### ISSUE THREAD

**Issue by AlexiGha** [rolling-scopes-school/support#367]
1. Deploy https://alexigha.github.io/rsschool-cv/
2. User GitHub: https://github.com/AlexiGha/rsschool-cv
3. Prinscreen: 
![image](https://user-images.githubusercontent.com/95225716/148655944-6bbf3812-49dd-4039-94ec-c857b3c96ab5.png)
4. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
5. Instruction for marks: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md#%D0%BA%D1%80%D0%B8%D1%82%D0%B5%D1%80%D0%B8%D0%B8-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8
6. Score: 98/120
0/10 submit in rsschool after deadline :(
 0/10 no valid has 6 errors
+ 20 all semantic elements
+10 footer with links
+10 use css styles
+ 10 Stability change scale, page stay in center
+10 photo with atribute
+8/10 have ul, not only in nav
+25 /30 haven't only  study projects
+ 10 all done in English
-10 not in time, after deadline
-5 no wonder flexbox for nav

**Comment by turn2river** [comment]
120 баллов

Хорошая работа, я бы поработал над шрифтами, лобстер в UpperCase не очень смотрится, когда пишешь им подряд. в остальном приятная работа :) Удачного обучения :)
