### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'lilpavlik'

### ISSUE THREAD

**Issue by lilpavlik** [rolling-scopes-school/support#368]
Добрый вечер! В связи с сессией в университете, а честно говоря в большей степени в связи с моей невнимательностью я не правильно разобрался с 3 заданием CV и не засамбил его, думая, что третье задание это просто проверка. Был не прав, в следующий раз буду внимательнее. Есть ли возможность засамбить 3 СV, через апелляцию, я буду очень благодарен? Спасибо за ответ

Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md

Markdown CV: https://lilpavlik.github.io/rsschool-cv/cv

HTML&CSS CV: https://lilpavlik.github.io/rsschool-cv/

GitHub rsschool-cv-html: https://github.com/lilpavlik/rsschool-cv/tree/rsschool-cv-html

Screenshot: 

![image](https://user-images.githubusercontent.com/92550782/148655195-5d853077-285a-4bec-8137-62ada6ee359f.png)

![image](https://user-images.githubusercontent.com/92550782/148655201-4e543d5a-cd35-4e3d-a062-aaea2be5573c.png)

Оценка: 110 из 130

*студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages (+10)
*вёрстка валидная: нет (0)
*header, main, footer (+5)
*элемент nav (+5)
*только один заголовок h1 (+5)
*заголовки h2 (+5)
*в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс (+10)
*для оформления СV используются css-стили (+10)
*при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (+10)
*на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt (+10)
*навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a : не все из перечисленного (+5)
CV содержит:

*краткую информацию о себе (+5)
*контакты для связи (+5)
*перечень навыков (+5)
*пример кода. Код добавляется при помощи символов и тегов, а не картинкой (+5)
*перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения (0)
*информацию об образовании и уровне английского (+5)
*CV выполнено на английском языке (+10)

Составил самопроверку, по пунктам, отвечал честно.

**Comment by spherical-horse** [comment]
**Ваша оценка - 100 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**
1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

2) только один заголовок h1 

3) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

**Частично выполненные пункты:**
1) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 
_feedback: Нет года создания приложения_

2) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
_feedback: Списком оформлен только перечень навыков._

**Выполненные пункты:**
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) header, main, footer 

3) элемент nav 

4) заголовки h2 

5) для оформления СV используются css-стили 

6) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

7) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

8) краткую информацию о себе 

9) контакты для связи 

10) перечень навыков 

11) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

12) информацию об образовании и уровне английского 

13) CV выполнено на английском языке

**Comment by lilpavlik** [comment]
Спасибо, с оценкой согласен, теперь мне просто ожидать когда результат появится в rs app, верно?

**Comment by spherical-horse** [comment]
Да, именно так. Результат появится в RS App после проверки всех апелляций.
