### ISSUE TITLE
CV#3. CV. Cross Check  [Zhandos Bocholoev (azyamazya)]

### ISSUE THREAD

**Issue by Azyamazya** [rolling-scopes-school/support#369]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Screenshot:
![Безымянный](https://user-images.githubusercontent.com/93484663/148655228-63225778-aba2-45e9-9ae7-a8947c0e0708.png)

Deploy: https://azyamazya.github.io/rsschool-cv/
Score:115/130
Критерии оценки

Максимальный балл за задание +120

{+}студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
(+)вёрстка валидная +10
![validator](https://user-images.githubusercontent.com/93484663/148655582-ed71cfa1-c57d-4d0b-9032-b4474be71b63.png)

(+)header, main, footer +5
(+)элемент nav +5
(+)только один заголовок h1 +5
(+)заголовки h2 +5
(+)в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
(+)для оформления СV используются css-стили +10
(-)при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону -10
(+)на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
(+)навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
(+)CV содержит краткую информацию о себе +5
(+)контакты для связи +5
(+)перечень навыков +5
(+)пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
(-)перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения -5
(+)информацию об образовании и уровне английского +5
(+)CV выполнено на английском языке +10

Добрый вечер, в связи с переносами дедлайна по Сross Check, продолжил работу над проектом. По завершению оформления, обнаружил, что мое CV уже нельзя засабмитить. Можно ли проверить мою работу? Благодарю.

**Comment by irinainina** [comment]
115 баллов
Привет! Хорошая работа.
С самооценкой согласна
Контент не центрируется и нет ссылок на проекты, хоть на само CV можно было ссылку сделать
Успехов!
