### ISSUE TITLE
Cross-Check Singolo - rsodst

### ISSUE THREAD

**Issue by rsodst** [rolling-scopes-school/support#37]
https://rsodst.github.io/singolo/singolo/index.html - деплой (ветка gh-pages)
https://github.com/rsodst/singolo - репозиторий
Балл за кроссчек 67, ожидаемый балл 100.
Один комментарий очень удручает: Отсутствуют файлы index.html и style.css. Ещё один проверяющий решил не проверять. Можно чекнуть этот момент?

**Comment by amoebiusss** [comment]
@rsodst пожалуйста, добавьте в описание тот балл, на который вы сами оцениваете задание

**Comment by rsodst** [comment]
Пофиксил описание issue, ожидаемый бал получен в результате самостоятельной проверки решения по чек-листу.

**Comment by amoebiusss** [comment]
@rsodst спасибо! Еще один момент, ссылка на деплой ведет на 404

**Comment by rsodst** [comment]
Прошу прощения, вчера добавил singolo-dom и сломал. Забыл обновить в комменте.

**Comment by rsodst** [comment]
Не знаю как обновить ссылку в сабмите((  Надо было на репозиторий ссылку вставлять, или не мержить singolo-dom.

**Comment by amoebiusss** [comment]
@rsodst привет! Работа выглядит очень аккуратно. Есть пара небольших погрешностей, которые я заметила:

1. Не очень аккуратно обрезается текст при переполнении:
![image](https://user-images.githubusercontent.com/26903136/77316744-042faf80-6d1b-11ea-9079-75efd881e087.png)

2. _(этот пункт не влияет на оценку)_ Если для именования классов используется БЭМ, то такие селекторы, как `ourservice__service__card__content__text` или `footer__content__details__detail__buttons` говорят о неправильном подходе к именованию. Элементы можно вкладывать только в блоки, но не в другие элементы. Подробнее: https://ru.bem.info/methodology/quick-start/#%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF%D1%8B-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%D0%B8

Итого 100 - 3 (обрезка текста) = **97 баллов**
