### ISSUE TITLE
CV3. CV Cross-Check - 'Aryina'

### ISSUE THREAD

**Issue by Aryina** [rolling-scopes-school/support#370]
1. Задание -  https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Deploy:  https://Aryina.github.io/rsschool-cv/cv
     https://Aryina.github.io/rsschool-cv/
3. 08.01.22 выполнила
4. Старалась максимально выполнить требования. Использовала пример.

![CV3](https://user-images.githubusercontent.com/96743039/148656370-3838dc07-837a-4f6d-9081-4a3b3604a1f0.png)
 5. Я немного запуталась и не смогла вовремя добавить ссылку в  CV Cross-Check. Спасибо.

**Comment by turn2river** [comment]
Распиши, пожалуйста, самооценку по пунктам.

**Comment by Aryina** [comment]
Максимальный балл за задание +120

1. Студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10 
2. Вёрстка валидная +10
3. В коде странице присутствуют и используются по назначению следующие элементы:
header, main, footer +5
элемент nav +5
только один заголовок h1 +5
заголовки h2 +5
4. В footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
для оформления СV используются css-стили +10
при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
на странице СV есть фото или аватарка автора,  у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li  +10
5. Содержание CV +30
CV содержит:
краткую информацию о себе +5
контакты для связи +5
перечень навыков +5
6. Пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
информацию об образовании и уровне английского +5
7. CV выполнено на английском языке +10

**Comment by turn2river** [comment]
По ссылке https://aryina.github.io/rsschool-cv/ не открывается CV, необходимо замержить Pull Request в ветку gh-pages. 
Комментарий про мерж: 
У тебя репозиторий в репозитории, это можно увидеть, если открыть ветку rsschool-cv-html, там будет видно папку "со стрелкой" rsschool-cv, необходимо локально удалить эту папку, запушить на гитхаб в ветку rsschool-cv-html и потом уже открыть и замержить Pull Request в gh-pages, без этого деплой не произойдёт, т.к. гитхаб не поймёт что именно нужно деплоить.

**Comment by Aryina** [comment]
Спасибо за помощь! Вторая ссылка открывается на страничку CV
![10](https://user-images.githubusercontent.com/96743039/148659749-89d426ac-fb8b-4b01-997b-b22530d99a51.png)
.

**Comment by turn2river** [comment]
120 баллов

Хорошая работа. Небольшой момент, который может ещё улучшить работу:
при уменьшении масштаба вёрстка "разъезжается", чтобы этого не происходил, надо задать ширину контейнеру width: 1440px, например, и свойство margin: 0 auto; , это надо сделать для контейнров header, main и footer, тогда вёрстка будет всегда по центру и на разных разрешениях (2к, 4к) будет смотреться хорошо :)
В остальном приятная работа, удачного обучения :)

**Comment by Aryina** [comment]
Спасибо большое за помощь, удачи!
