### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Kamilla Safarova'

### ISSUE THREAD

**Issue by KamillaSV** [rolling-scopes-school/support#371]
1.Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot:
![image](https://user-images.githubusercontent.com/96070554/148663718-41d68163-72ca-4dca-8520-d069e992d000.png)
3. Deploy: https://kamillasv.github.io/rsschool-cv/
4. Done 09.01.2022 / deadline 10.01.2022
5. Score: 115 /120
Cтудент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages (10/10)
вёрстка валидная (10/10)
вёрстка семантическая (20/20)
для оформления СV используются css-стили (10/10)
в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс (10/10)
при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (0/10)
на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt (10/10)
навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a (10/10)
Содержание CV (25/30)
CV выполнено на английском языке (10/10)

Доброго времени суток!
В связи с информацией в announcments о переносе дедлайна по Сross Check#3 на 13 января, не засабмитила вовремя ссылку на CV. Прошу  проверить мою работу.
Заранее спасибо!

**Comment by Bumble-sakh** [comment]
115 баллов.
Хорошая работа.
Недочеты вы сами указали.
В качестве примера работ можно было добавить само cv

**Comment by KamillaSV** [comment]
Спасибо за обратную связь!
Действительно, про само СV не догадалась)
