### ISSUE TITLE
CV#3. CV Cross-Check. pavel-ponomarenko

### ISSUE THREAD

**Issue by Pavel-Ponomarenko** [rolling-scopes-school/support#372]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot: https://ibb.co/xg4bDNw
3. Deploy: (https://Pavel-Ponomarenko.github.io/rsschool-cv/)
4. 09.01.2022/06.01.2022
5. Score: 130 /120
-Студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages (10/10)
-Вёрстка валидная (10/10)
-Вёрстка семантическая (20/20)
-Для оформления СV используются css-стили (10/10)
-В footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс (10/10)
-При уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (10/10)
-На странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt (10/10)
-Навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a (10/10)
-Содержание CV (30/30)
-CV выполнено на английском языке (10/10)

В связи с продолжительным празднованием Нового Года не заметил, как поменяли дедлайн с 13 на  6. Прошу понять и простить.
Спасибо за внимание и с прошедшими праздниками!

**Comment by turn2river** [comment]
120 баллов.

Оригинальная работа, выделяющаяся на фоне других.
Небольшие доработки, исправление которых поможет улучшить работу:
- при разрешениях >1940 появляются белые полоски по краям, изображение не масштабируется при увеличении разрешения
- непривычно смотреть на код, который отформатирован "по центру"

В остальном хорошая работа, все пункты ТЗ выполнены, удачного обучения :)

**Comment by Pavel-Ponomarenko** [comment]
> Оригинальная работа, выделяющаяся на фоне других.

Благодарю за отзыв, очень приятно видеть такой ответ.

> Небольшие доработки, исправление которых поможет улучшить работу:
> 
> - при разрешениях >1940 появляются белые полоски по краям, изображение не масштабируется при увеличении разрешения

При разрешении 1920+, сделал я это намерено для демонстрации центрирования контента. Так же в тз не было конкретики по поводу адаптивной верстки, максимального и минимальных разрешений, а так же медиа запросах.

> - непривычно смотреть на код, который отформатирован "по центру"

Вот это я и сам не понял зачем, но визуально получилось прикольно :)

> В остальном хорошая работа, все пункты ТЗ выполнены, удачного обучения :)

Ещё раз спасибо!)
