### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Damir Ilkaev'

### ISSUE THREAD

**Issue by river-knows** [rolling-scopes-school/support#374]
1. Deploy - https://river-knows.github.io/rsschool-cv/
2. Task - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
![изображение](https://user-images.githubusercontent.com/82723666/148691626-56f6cc3f-7772-46dd-9106-fd3af216b53a.png)
3. Repository https://github.com/river-knows/rsschool-cv
4. Score **125 / 130**
- cтудент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages **10/10**
- вёрстка валидная **10/10**
![изображение](https://user-images.githubusercontent.com/82723666/148691709-cdc6a51a-2b4e-4068-912c-c4f6772982d3.png)
- вёрстка семантическая **20/20**
 header, main, footer **5/5**
 элемент nav **5/5**
 только один заголовок h1 **5/5**
 заголовки h2 **5/5**
- в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс **10/10**
- для оформления СV используются css-стили **10/10**
- при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону **10/10**
- на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt **10/10**
- навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a **10/10**
- CV содержит:
 краткую информацию о себе **5/5**
 контакты для связи **5/5**
 перечень навыков **5/5**
 пример кода. Код добавляется при помощи символов и тегов, а не картинкой **0/5**
 перечень выполненных учебных проектов со ссылками на исходный код или страницу  приложения **5/5**
 информацию об образовании и уровне английского **5/5**
- CV выполнено на английском языке **10/10**

Здравствуйте, вовремя не успел засабмитить ссылку, прошу, если еще возможно, проверить. Спасибо!

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

16) информацию об образовании и уровне английского 

17) CV выполнено на английском языке
