### ISSUE TITLE
CV#3. CV Cross-Check Dmitry Vedenko

### ISSUE THREAD

**Issue by Blackwo0d** [rolling-scopes-school/support#375]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.mdb
2. Screenshot:
![](https://user-images.githubusercontent.com/96013782/148693905-8313380c-8df9-4f6e-9f69-7af4daf08141.JPG)
3. Deploy: https://blackwo0d.github.io/rsschool-cv/
4. Done 09.01.22 / deadline 10.01.2022
5. Score: 130 /120
-Студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages (10/10)
-Вёрстка валидная (10/10)
-Вёрстка семантическая (20/20)
-Для оформления СV используются css-стили (10/10)
-В footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс (10/10)
-При уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (10/10)
-На странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt (10/10)
-Навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a (10/10)
-Содержание CV (30/30)
-CV выполнено на английском языке (10/10)

Здравствуйте.
Не успел выполнить задание вовремя, за что прошу прощения.
В связи с переносом дедлайна по заданию на 10.01.22 прошу проверить мою работу.

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов** 

Отзыв по пунктам ТЗ:

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

16) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

17) информацию об образовании и уровне английского 

18) CV выполнено на английском языке
