### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'Titaev Pavel'

### ISSUE THREAD

**Issue by TitaevPA** [rolling-scopes-school/support#376]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot:
   ![image](https://user-images.githubusercontent.com/29667418/148694469-06043983-a964-4d91-85d7-214103baf28e.png)
3. Deploy: https://titaevpa.github.io/rsschool-cv/
4. Done 09.01.2022 / deadline 10.01.2022
5. Score: 115 / 120
   вёрстка валидная +10
   семантика:
     - есть теги header, main, footer +5
     - элемент nav +5
     - только один заголовок h1 +5
     - несколько заголовков h2
   в footer есть:
     - ссылка на гитхаб автора работы
     - год создания приложения
     - логотип курса со ссылкой на курс +10
   для оформления СV используются css-стили +10
   при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, 
     а не сдвигается в сторону +10
   на странице СV есть фото или аватарка автора, пропорции изображения не искажены, 
     у изображения есть атрибут alt +10
   навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
   Содержание CV +30 / 25
   CV содержит:
     - краткую информацию о себе +5
     - контакты для связи +5
     - перечень навыков +5
     - пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
     - перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5/0
     - информацию об образовании и уровне английского +5
   CV выполнено на английском языке +10

Доброго времени суток!
В связи с информацией в announcments о переносе дедлайна по Сross Check#3 на 13 января, уехал отдыхать 6-го не отправив работу и физически не мог её доделать и отправить до 9-го. Прошу проверить мою работу.
Заранее спасибо!

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов**
 
Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**
1) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

**Выполненные пункты:**
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

16) информацию об образовании и уровне английского 

17) CV выполнено на английском языке
