### ISSUE TITLE
CV#3. CV. Cross-Check - [Alexandra Lukashevich @aldevgh]

### ISSUE THREAD

**Issue by aldevgh** [rolling-scopes-school/support#377]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Screenshot:
![Screenshot_CV3(1)](https://user-images.githubusercontent.com/94435594/148703697-0dc21a54-1c42-4af5-8f3e-40d79b9f0258.png)
Deploy: https://aldevgh.github.io/rsschool-cv/
Done 09.01.2022 / deadline 06.01.2022
Score: 120 / 130
* студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages (10/10)
* вёрстка валидная. Результат проверки на https://validator.w3.org/: "Document checking completed. No errors or warnings to show." (10 / 10)
* вёрстка семантическая (20/20)
* в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс (10/10)
Если ссылка в футере ведёт на курс stage0, это не ошибка.
* для оформления СV используются css-стили (10/10)
* при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (10/10)
* на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt (10/10)
* навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a
Также допускается использование нумерованого списка ol > li или ol > li > a - выполнено частично: контакты для связи не cоответствуют требованию (5/10)
* Содержание CV (25/30)
CV содержит:
краткую информацию о себе +5
контакты для связи +5
перечень навыков +5
пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения -  не выполнено +0
информацию об образовании и уровне английского +5
* CV выполнено на английском языке (10/10)

**Comment by Bumble-sakh** [comment]
120  баллов
Хорошая, качественная работа.

**Comment by aldevgh** [comment]
> 120 баллов Хорошая, качественная работа.

Благодарю за уделенное время!
