### ISSUE TITLE
Cross-Check - CV#3. CV. Cross Check - Titansv83

### ISSUE THREAD

**Issue by Titansv83** [rolling-scopes-school/support#378]
Deploy: https://titansv83.github.io/rsschool-cv/
 Done 10.01.2022 / deadline 10.01.2022
 Repositories: https://github.com/Titansv83/rsschool-cv
 Task link: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
 Score: 115 / 120
  вёрстка валидная +10
  семантика:
        есть теги header, main, footer +5
        элемент nav +5
        только один заголовок h1 +5
        несколько заголовков h2
        в footer есть:
        ссылка на гитхаб автора работы
        год создания приложения
        логотип курса со ссылкой на курс +10
        для оформления СV используются css-стили +10
        при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали,
        а не сдвигается в сторону +10
        на странице СV есть фото или аватарка автора, пропорции изображения не искажены,
        у изображения есть атрибут alt +10
        навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
        Содержание CV +30 / 25
        CV содержит:
        краткую информацию о себе +5
        контакты для связи +5
        перечень навыков +5
        пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
        перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5/0
        информацию об образовании и уровне английского +5
        CV выполнено на английском языке +10

Доброго времени суток!
В связи с информацией в announcments о переносе дедлайна по Сross Check#3 на 13 января, решил сделать CV более красивым и пропустил изменение сроков дедлайна на 6 января. Прошу проверить мою работу.
Заранее спасибо!

**Comment by YuliyaMinsk** [comment]
**120 баллов**
Хорошая работа, выполнены все пункты ТЗ кроме перечня учебных проектов со ссылками (-5 баллов)
