### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'farukish'

### ISSUE THREAD

**Issue by farukish** [rolling-scopes-school/support#379]
1. Моя разработка: https://farukish.github.io/rsschool-cv/
2. Мой репозиторий: https://github.com/farukish/rsschool-cv/
3. Скриншот:
![Снимок экрана 2022-01-10 в 08 16 46](https://user-images.githubusercontent.com/96256455/148721986-414e63d5-2500-441b-98a3-8ffdb54c1df5.png)
4. Форма для проверки: https://cv-cross-check.netlify.app/
5. Ожидаемый результат: 120/120.
Считаю свою работу одну из лучших!  
Выполненные пункты:
- студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages
- вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
- header, main, footer
- элемент nav
- только один заголовок h1
- заголовки h2
- в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка.
- для оформления СV используются css-стили
- при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону
- на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt.
- навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a
- краткую информацию о себе
- контакты для связи
- перечень навыков
- пример кода. Код добавляется при помощи символов и тегов, а не картинкой
- перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения
- информацию об образовании и уровне английского
- CV выполнено на английском языке

**Comment by Bumble-sakh** [comment]
120 баллов.
Действительно, отличная работа, которой можно гордится.

**Comment by farukish** [comment]
Здравствуйте, подскажите пожалуйста почему у меня до сих пор нету балла оценки за мою работу?! и моя работа отобрана в список лучших? ее просто в списке нету
