### ISSUE TITLE
Cross-Check Singolo - Roman-Yarinski

### ISSUE THREAD

**Issue by Roman-Yarinski** [rolling-scopes-school/support#38]
Ссылка на деплой: https://roman-yarinski.github.io/singolo/singolo.html

Ссылка на репозиторий с проектом: https://github.com/Roman-Yarinski/singolo

Считаю что работа выполнена на 100 баллов
Аргументы (по пунктам выставленных ниже проверяющим):

1) Визуальные отличия элементов секции Get a Quote в пределах погрешности.
2) Текст в местах, где находится несколько строк растянут равномерно на ширину блока.Services.
3) Текст в местах, где находится несколько строк растянут равномерно на ширину блока.About.
4) Текст в местах, где находится несколько строк растянут равномерно на ширину блока.Get a Quote.
5) При добавлении в сетку с изображениями элементов за 12-м, следющие за 12-м не отображаются на странице.
Балл за cross-check из Score выставленный проверяющим
Ваша оценка - 85 баллов 

Отзыв по пунктам ТЗ:

1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла.

2) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Services: минус -3 балла.

3) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции About: минус -3 балла.

4) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Get a Quote: минус -3 балла 

5) При добавлении в сетку с изображениями элементов за 12-м (проверяя, добавляем их сами) следющие за 12-м отображаются на странице - не реализовано ограничение видимых двенадцатью показанными в макете: минус -3 балла.

Остальные 3 проверяющих выставили следующие баллы: 97, 95, 94.

**Comment by amoebiusss** [comment]
Добрый день! Фактическая оценка отличается от ожидаемой на 7 баллов, минимальная разница для апелляции — 15.

https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f
