### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check'-'BelTat'

### ISSUE THREAD

**Issue by BelTat** [rolling-scopes-school/support#381]
1. Деплой - https://beltat.github.io/rsschool-cv/
2. Репозиторий - https://github.com/BelTat/rsschool-cv
3. Задание - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. Формы для проверки проекта https://cv-cross-check.netlify.app/
5. Скриншоты с оценками: 
![Screenshot_20220110_095043_com google android apps photos](https://user-images.githubusercontent.com/95576009/148727695-62855131-0215-4cfb-aabf-4c8905b67b22.jpg)
![Screenshot_20220110_094618_com android chrome](https://user-images.githubusercontent.com/95576009/148727700-9ff193c7-4d2f-4516-8675-469debe311f7.jpg)
6. Оценка в результате самопроверки с аргументацией: 
Ваша оценка - 125 баллов 
Отзыв по пунктам ТЗ:
Частично выполненные пункты:
1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

Выполненные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) header, main, footer 

3) элемент nav 

4) только один заголовок h1 

5) заголовки h2 

6) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

7) для оформления СV используются css-стили 

8) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

9) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

10) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

11) краткую информацию о себе 

12) контакты для связи 

13) перечень навыков 

14) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

15) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

16) информацию об образовании и уровне английского 

17) CV выполнено на английском языке 
7. Балл за cross-check из score - 41.

P.S.
Считаю оценку в  10 баллов, полученную от Student  2 , необъективной и незаслуженно низкой. Работа соответствует  требованиям задания, корректно отображается в 3 разных браузерах. Буду благодарна за проверку моей работы.

**Comment by irinainina** [comment]
Привет. Апелляция по результатам кросс-чека будет доступна только завтра. Пока апелляцию отклоняю.

**Comment by BelTat** [comment]
Привет, ок.

**Comment by irinainina** [comment]
117,5 баллов по результатам кросс-чека
Успехов!

**Comment by BelTat** [comment]
Спасибо!
