### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'EkaterinaBurak'

### ISSUE THREAD

**Issue by EkaterinaBurak** [rolling-scopes-school/support#382]
Здравствуйте! Ранее мной подана апелляция, которая удовлетворена, за задание начислен максимальный балл. Вместе с тем, баллы за задание в личном кабинете не обновлены. Прошу исправить.
1. Ссылка на проверенное задание: https://github.com/rolling-scopes-school/support/issues/338
2. Скрин личного кабинета: ![image](https://user-images.githubusercontent.com/81382292/148772133-5a719162-d68d-4ff1-bb8f-5546844dfedb.png)

**Comment by irinainina** [comment]
Привет! Всё в порядке. Баллы появятся когда закроют все апелляции. Они будут, но позже. Issue закрываю.
