### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'LaSofi24'

### ISSUE THREAD

**Issue by LaSofi24** [rolling-scopes-school/support#383]
1. Деплой проекта: https://LaSofi24.github.io/rsschool-cv/
2. Репозиторий на GitHub: https://github.com/LaSofi24/rsschool-cv
3. Задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. Самопроверка: 
- [ ]  студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10 **(0)**
_(не смогла засабмитить из за пропуска дедлайна)_
- [ ]  вёрстка валидная +10  **(0)**
_(есть 3 ошибки "пробелы в названии id или class")_
- [ ]  вёрстка семантическая +20 **(20)**
- header, main, footer +5
- элемент nav +5
- только один заголовок h1 +5
- заголовки h2 +5
_(есть заголовки h3)_
- [ ]  в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10 **(10)**
- [ ]  для оформления СV используются css-стили +10 **(10)**
- [ ]   при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10 **(10)**
- [ ]  на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10 **(10)**
- [ ]   навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10 **(10)**
- [ ]   Содержание CV +30 **(20)**
- краткую информацию о себе +5
- контакты для связи +5
- перечень навыков +5
- пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
_(кода пока нет)_
- перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
_(проектов нет пока, есть ссылка на CV)_
- информацию об образовании и уровне английского +5
- [ ]   CV выполнено на английском языке +10 **(10)**

ИТОГО: 90/130

Прошу проверить мою работу, не смогла засабмитить вовремя, так как были проблемы с интернетом, находилась в другом городе. Так как не успела засабмитить вовремя, то работы других ребят мне тоже не были доступны.

**Comment by igorlyatskiy** [comment]
Списанные работы не подлежат апелляции.
