### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'F4bulouS'

### ISSUE THREAD

**Issue by F4bulouS** [rolling-scopes-school/support#384]
1. Ссылка на деплой вашего проекта: https://f4bulous.github.io/rsschool-cv/
2. Ссылка на репозиторий с проектом на GitHub: https://github.com/F4bulouS/rsschool-cv
3. Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. Ссылка на форму для проверки проекта (если такая есть): https://cv-cross-check.netlify.app/
5. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты): 
![image](https://user-images.githubusercontent.com/38176231/148781420-48a10352-3349-4b55-a634-b1eb014ae8c4.png)
6. Оценка в результате самопроверки с ее аргументацией (**120/120**): 
    * Студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages: 10/10;
    * Вёрстка валидная (включая CSS): 10/10;
    * Вёрстка семантическая: 20/20;
    * Ссылки и логотипы в футере (кликабельные картиночки): 10/10;
    * Использование CSS: 10/10;
    * Размещение верстки по центру: 10/10;
    * Есть фото: 10/10;
    * Навигация и контакты оформлены в списках (маркированный список): 10/10;
    * Содержание CV: 30/30 (всё есть, но один из проектов ссылается лишь на новость о этом проекте, так как исходники - 
    гостайна, я не имею право их выкладывать);
    * CV выполнено на английском языке: 10/10.
  7. Балл за cross-check из вашего Score: Я получу (115 + 105 * 3) ~= 109 баллов. 

**Всем мира в дом.** 
Я немножко дезориентировался по поводу дедлайна (был 6 января, потом ушел на более позднюю дату, но неожиданно работу проверили 6-7 января) и засабмитил "сырую" работу. Сейчас я её доработал. Возможно ли её перепроверить? :-)

**Comment by spherical-horse** [comment]
**Ваша оценка - 130 баллов** 

Отзыв по пунктам ТЗ:

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

16) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

17) информацию об образовании и уровне английского 

18) CV выполнено на английском языке

**Comment by F4bulouS** [comment]
Большое спасибо за проделанную работу!
