### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'Spiritlm'

### ISSUE THREAD

**Issue by Spiritlm** [rolling-scopes-school/support#386]
1. Deploy https://spiritlm.github.io/rsschool-cv/
![image](https://user-images.githubusercontent.com/90802803/148827678-b08d18f0-d70b-4d7e-8647-9feb4f9c0b0d.png)
2. https://spiritlm.github.io/rsschool-cv/
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. Score: 110 / 130

- [ ] вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

- [ ]  header, main, footer 

- [ ] элемент nav 

- [ ] только один заголовок h1 

- [ ] заголовки h2 

- [ ] в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

- [ ] для оформления СV используются css-стили 

- [ ] при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

- [ ] на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

- [ ] краткую информацию о себе 

- [ ] контакты для связи 

- [ ] перечень навыков 

- [ ] пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

- [ ] информацию об образовании и уровне английского 

- [ ] CV выполнено на английском языке 

Прошу проверить мою работу. 
В связи с отсутствием времени не успел сделать задания до дедлайна. Так как не успел хотел принести хоть какую-то пользу и проверить работы других студентов, но видимо из-за незасабмиченной ссылки список студентов для проверки оказался недоступным. 
В итоге работу выполнил, но с сильным отставанием от дедлайна. 
Заранее спасибо!

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**
1) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

**Частично выполненные пункты:**
1) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
_feedback: Контакты и список навыков не в виде списка._

Выполненные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) краткую информацию о себе 

12) контакты для связи 

13) перечень навыков 

14) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

15) информацию об образовании и уровне английского 

16) CV выполнено на английском языке

**Comment by Spiritlm** [comment]
Огромное спасибо!

**Comment by Spiritlm** [comment]
Что то в итоге так баллы и не начислили
