### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'antonkryzhchenko'

### ISSUE THREAD

**Issue by antonkryzhchenko** [rolling-scopes-school/support#387]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Screenshot: 
![screenshot_1](https://user-images.githubusercontent.com/94857853/148835232-a53c89c3-6b9d-4256-9c43-2d488f831adb.png)

Deploy: https://antonkryzhchenko.github.io/rsschool-cv/
Done 10.01.2022 / deadline 06.01.2022
Score: 125/130
студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
вёрстка валидная +10
header, main, footer +5
элемент nav +5
только один заголовок h1 +5
заголовки h2 +5
в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
Если ссылка в футере ведёт на курс stage0, это не ошибка.
для оформления СV используются css-стили +10
при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
CV содержит:
краткую информацию о себе +5
контакты для связи +5
перечень навыков +5
пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 0
информацию об образовании и уровне английского +5
CV выполнено на английском языке +10
Здравствуйте! Совсем запутался в переносах дедлайна. 
Проверьте, пожалуйста, мою работу. Заранее спасибо!

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов** 

Отзыв по пунктам ТЗ:

**Частично выполненные пункты:**
1) заголовки h2 
_feedback: Только один заголовок h2_

**Выполненные пункты:**
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

7) для оформления СV используются css-стили 

8) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

9) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

10) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

11) краткую информацию о себе 

12) контакты для связи 

13) перечень навыков 

14) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

15) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

16) информацию об образовании и уровне английского 

17) CV выполнено на английском языке
