### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'saukadruzha'

### ISSUE THREAD

**Issue by saukadruzha** [rolling-scopes-school/support#388]
Deploy: https://saukadruzha.github.io/rsschool-cv/
![image](https://user-images.githubusercontent.com/71442745/148835505-7cd25a4a-1cce-40bd-accd-62ce86a4ee87.png)
Ссылка на репозиторий с проектом на GitHub: https://github.com/saukadruzha/rsschool-cv
Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Ссылка на форму для проверки проекта (если такая есть): https://cv-cross-check.netlify.app/
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты):
![image](https://user-images.githubusercontent.com/71442745/148834363-75de8c3d-736a-44de-8c71-57f3b62a6e12.png)
Оценка в результате самопроверки с ее аргументацией (**95/120**):
1) Студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages  (+10);
2) Вёрстка валидная (+10); (проверено через валидатор: https://validator.w3.org/);
3) Вёрстка семантическая (5/20):
•    Header, main, footer (0/5) – нет Header;
•    Элемент nav (0/5) – нет Nav;
•    Только один заголовок h1 (0/5) нет h1;
•    Заголовки h2 (+5);
4) В footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс (+10);
5) Для оформления СV используются css-стили (+10);
6) При уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (0/10);
7) На странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt (0/10);
8) Навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a (+10);
9) Содержание CV (+30)

CV содержит:
•    краткую информацию о себе (+5);
•    контакты для связи (+5);
•    перечень навыков (+5);
•    пример кода. Код добавляется при помощи символов и тегов, а не картинкой (+5);
•    перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения (+5);
•    информацию об образовании и уровне английского (+5);
10)     CV выполнено на английском языке (+10);
Всего: 95/120

Здравствуйте! Из-за путаницы с дедлайном(сначала он был 6-го, потом 10-го, а потом снова 6-го :) я засабмитил ссылку 3-го января, а дальше всё пошло не по плану. Я выполнил ревью студентов, а студенты выполнили ревью моей работы, с которым я согласен, но баллы за задание мне не были зачислены. Прошу вас проверить мою работую. Заранее благодарю!

**Comment by igorlyatskiy** [comment]
Твою работу проверили, баллы будут начислены после дедлайна кросс-чека

**Comment by saukadruzha** [comment]
Понятно. Спасибо за ответ!
