### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'darap1'

### ISSUE THREAD

**Issue by darap1** [rolling-scopes-school/support#389]
Task : https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Screen :
![skrin](https://user-images.githubusercontent.com/46171266/148840487-1f851e4d-751f-420b-bbb3-169dcf85329f.png)
Deploy : https://darap1.github.io/rsschool-cv/
Done 10.01.2022 / deadline 06.01.2022

Score: 120 / 130

на gh-pages (+10)
вёрстка валидная. Результат проверки на https://validator.w3.org/: "Document checking completed. No errors or warnings to show." (+10)
header, main, footer (+5)
элемент nav (+5)
только один заголовок h1 (+5)
заголовки h2 (+5)
в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс (+10)
для оформления СV используются css-стили (+10)
при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (+10)
на странице аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt (+10)
навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a : (+10)

CV содержит:

краткую информацию о себе (+5)
контакты для связи (+5)
перечень навыков (+5)
пример кода. Код добавляется при помощи символов и тегов, а не картинкой (+5)
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения (+5)
информацию об образовании и уровне английского (+5)
CV выполнено на английском языке (+10)

Не уверен что успел , у меня разница во времени 2 часа. у меня еще 10 число , извиняюсь что не учел .После анонса из дискорда увидел , что дедлайны перенесены на 13 число в расписании rs app , потом когда увидел другой анонс уже понял , что не успею во время.

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов** 

Отзыв по пунктам ТЗ:

**Выполненные пункты:**
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

16) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

17) информацию об образовании и уровне английского 

18) CV выполнено на английском языке

**Comment by darap1** [comment]
Спасибо большое , за проделанную работу и оценку.
