### ISSUE TITLE
Cross-Check Singolo - irinabro85

### ISSUE THREAD

**Issue by irinabro85** [rolling-scopes-school/support#39]
Здравствуйте.

Ссылка на деплой вашего проекта: https://irinabro85.github.io/singolo/

Ссылка на репозиторий с проектом на GitHub: https://github.com/irinabro85/singolo

Оценка в результате самопроверки, с ее аргументацией: 91 (ниже по каждому пункту написала)

Балл за cross-check из вашего Score: 82

**Student 1**
1) В Firefox есть сильное отклонение (т.е. бросается в глаза) от той же страницы, открытой в Google Chrome: минус -5 баллов
-> Сжимаются по ширине иконки в Сервисах
**_(у меня не сжимаются ни в Chrome, ни в Firefox. Может не подгрузилась страница до конца? если перезагрузить, то все ок)_**

2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла
-> Заголовок сильно съехал
3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла
-> Заголовок сильно съехал
_**2-3 (в файле с проверочными инструкциями написано про шрифты: Исключение в первых двух пунктах составляет сам текст, а именно ширина слов и отступ между буквами. Их не учитываем при сопоставлении.)**_

4) В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла
5) При добавлении в сетку с изображениями элементов за 12-м (проверяя, добавляем их сами) следющие за 12-м отображаются на странице - не реализовано ограничение видимых двенадцатью показанными в макете: минус -3 балла
6) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла
_**4-6 согласна**_

**Student 2**
Ваша оценка - 73 балла
Отзыв по пунктам ТЗ:
1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Header составляют более двух пикселей (2px): минус -3 балла
2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Slider составляют более двух пикселей (2px): минус -3 балла
3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла
4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла
_**1-4:  (в файле с проверочными инструкциями написано про шрифты: Исключение в первых двух пунктах составляет сам текст, а именно ширина слов и отступ между буквами. Их не учитываем при сопоставлении.)**_

5) Стрелки слайдера без интерактивных стилей, при наведении на стрелки ничего не происходит: минус -3 балла
_**изменяется курсор**_

6) В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла
7) При добавлении в сетку с изображениями элементов за 12-м (проверяя, добавляем их сами) следющие за 12-м отображаются на странице - не реализовано ограничение видимых двенадцатью показанными в макете: минус -3 балла
8) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла
_**6-8 согласна**_

9) Не выполняется валидация обоих полей ввода с отметкой Required в макете, или указан неправильный тип "< input >", или отсутствуют необходимые атрибуты, или при пропуске/вводе невалидных значений форма отправляется без ожидаемых замечаний: минус -3 балла
_**тут написано: https://not-saint.github.io/Cross-check-FAQ/singolo.html
,что валидация полей: использование атрибута required и нужного типа полей - достаточная валидация для этого задания.**_

**Student 3**
Ваша оценка - 83 балла 
Отзыв по пунктам ТЗ:
1) В Firefox есть отклонение (т.е. бросается в глаза) от той же страницы, открытой в Google Chrome:(полетели 2 картинки в блоке Services) минус -2 баллов 
У меня все картинки на своем месте в обоих браузерах (проверяла с Pixel Perfect в Chrome, Firefox b Firefox Nightly)
2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Portfolio составляют более двух пикселей (2px): минус -3 балла 
3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла 
4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла 
_**2-4:  (в файле с проверочными инструкциями написано про шрифты: Исключение в первых двух пунктах составляет сам текст, а именно ширина слов и отступ между буквами. Их не учитываем при сопоставлении.)**_

5) При добавлении в сетку с изображениями элементов за 12-м (проверяя, добавляем их сами) следющие за 12-м отображаются на странице - не реализовано ограничение видимых двенадцатью показанными в макете: минус -3 балла 
6) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла 
_**5-6 согласна**_

**Student 4**
Ваша оценка - 91 баллов 
Отзыв по пунктам ТЗ:
1) Стрелки слайдера без интерактивных стилей, при наведении на стрелки ничего не происходит: минус -3 балла 
_**Изменяется курсор**_

2) При добавлении в сетку с изображениями элементов за 12-м (проверяя, добавляем их сами) следующие за 12-м отображаются на странице - не реализовано ограничение видимых двенадцатью показанными в макете: минус -3 балла 
3) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла 
_**2-3 согласна**_

Спасибо за проверку)

**Comment by amoebiusss** [comment]
Добрый день! Оценка отличается от ожидаемой на 9 баллов, минимальная разница для апелляции — 15.

https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f
