### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'Aliaksandra86'

### ISSUE THREAD

**Issue by Aliaksandra86** [rolling-scopes-school/support#390]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot:
![](https://user-images.githubusercontent.com/96070769/148843394-021ae7de-1449-4e7a-8fba-f4557904f7c5.png")
3.Deploy: https://aliaksandra86.github.io/rsschool-cv/
4.Done 10.01.2022 / deadline 10.01.2022
5. Score: 80%/100%

Здравствуйте. 
На GitHub Pull requests был сделан 10.01.2022 в 23.59.
Задание к изначальному сроку не успела сделать, отложила.
Узнала про отложенный дедлайн 08.01.2022 и решила воспользоваться шансом.
Очень прошу зачесть и  проверить мою работу.
Заранее спасибо.

**Comment by Aliaksandra86** [comment]
[](https://user-images.githubusercontent.com/96070769/148844835-21065150-8c1c-428d-9b0a-70c198f33387.png)

**Comment by irinainina** [comment]
Привет! Пожалуйста, добавь самооценку своей работы по пунктам. Посмотри, как оформлены другие апелляции

**Comment by Aliaksandra86** [comment]
Извиняюсь. Я думала. что это выставляют проверяющие. Исправилась. 

1. вёрстка валидная +10
![](https://user-images.githubusercontent.com/96070769/148907841-08c4f050-7675-4fa9-8243-7adc4c3f5ef7.png)

2. вёрстка семантическая +20:
- header, main, footer +5
- элемент nav +5
- только один заголовок h1 +5
- заголовки h2 +5

3. в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10

4. для оформления СV используются css-стили +10

5. при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10

6. на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10

7. навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10 

8. Содержание CV +20
CV содержит:
- краткую информацию о себе +5
- контакты для связи +5
- пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
- информацию об образовании и уровне английского +5

9. CV выполнено на английском языке +10 

ИТОГО: 110
 
Я не знаю оценивается ли "студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10" подача через апелляцию. Но, справедливости ради, не учитывала в балл.

**Comment by spherical-horse** [comment]
**Ваша оценка - 110 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**
1) перечень навыков 

2) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

**Частично выполненные пункты:**
1) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 
_feedback: Незначительно искажены пропорции изображения._
2) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
_feedback: Нет списка навыков_

**Выполненные пункты:**
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) краткую информацию о себе 

11) контакты для связи 

12) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 
feedback: Пример кода лучше было вставить при помощи тегов pre и code
13) информацию об образовании и уровне английского 

14) CV выполнено на английском языке

**Comment by Aliaksandra86** [comment]
спасибо.
