### ISSUE TITLE
CV#3. CV. Cross-Check - DimaLoginovskiy

### ISSUE THREAD

**Issue by Dimalogin** [rolling-scopes-school/support#391]
1.https://dimalogin.github.io/rsschool-cv/
2.https://github.com/Dimalogin/rsschool-cv
3.https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4.https://cv-cross-check.netlify.app/
5.
6.
- Студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages: 10/10;
- Вёрстка валидная (включая CSS): 0/10; (есть ошибки в валидаторе)
- Вёрстка семантическая: 20/20;
- Ссылки и логотипы в футере (кликабельные картиночки): 10/10;
- Использование CSS: 10/10;
- Размещение верстки по центру: 10/10;
- Есть аватар: 10/10;
- Навигация и контакты оформлены в списках (маркированный список): 10/10;
- Содержание CV: 30/30 (всё есть, кроме ссылки на discord);
CV выполнено на английском языке: 10/10.
7.

Не успел сдать CV 3 до дедлайна т к 
- во время верстки появились некоторые идеи которые хотелось реализовать 
- думал что дедлайн до 13. немного расслабился

**Comment by spherical-horse** [comment]
**Ваша оценка - 105 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

2) элемент nav 

3) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

**Частично выполненные пункты:**

1) header, main, footer 
_feedback: Отсутствует элемент main_

2) только один заголовок h1 
_feedback: 3 заголовка h1, но они скрываются и отображаются по-одному через media-запросы._

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) заголовки h2 

3) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

4) для оформления СV используются css-стили 

5) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

6) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

7) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

8) краткую информацию о себе 

9) контакты для связи 

10) перечень навыков 

11) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

12) информацию об образовании и уровне английского 

13) CV выполнено на английском языке
