### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'AngleW' (Victor Romaneyko) 

### ISSUE THREAD

**Issue by AngleW** [rolling-scopes-school/support#392]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot: (https://user-images.githubusercontent.com/27384891/148862359-6ae5b384-d828-4754-9d96-167a4185cc30.png)
3. Deploy: https://AngleW.github.io/rsschool-cv/
4. Score: 130 /120
-Студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages (10/10)
-Вёрстка валидная (10/10)
-Вёрстка семантическая (20/20)
-Для оформления СV используются css-стили (10/10)
-В footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс (10/10)
-При уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону (10/10)
-На странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt (10/10)
-Навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a (10/10)
-Содержание CV (30/30)
-CV выполнено на английском языке (10/10)

Добрый день! Прошу прощения, запутался с переносами дэдлайнов.
Прошу проверить мою работу, если это еще возможно.
Заранее спасибо за понимание!

**Comment by spherical-horse** [comment]
**Ваша оценка - 115 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 
_feedback: Error: Element pre not allowed as child of element code in this context. (Suppressing further errors from this subtree.)
Error: Stray start tag footer.
Fatal Error: Cannot recover after last error. Any further errors will be ignored._
2) элемент nav 

**Выполненные пункты:**
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) header, main, footer 

3) только один заголовок h1 

4) заголовки h2 

5) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

6) для оформления СV используются css-стили 

7) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

8) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

9) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

10) краткую информацию о себе 

11) контакты для связи 

12) перечень навыков 

13) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

14) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

15) информацию об образовании и уровне английского 

16) CV выполнено на английском языке
