### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'Dossymzhan'

### ISSUE THREAD

**Issue by Dossymzhan** [rolling-scopes-school/support#393]
1. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. 
![image](https://user-images.githubusercontent.com/49535489/148873581-2eb3a11b-644a-410e-be46-901a8ab87595.png)
3. https://dossymzhan.github.io/rsschool-cv/
4. 125 out of 130

Добрый день,

Прошу засчитать мою работу по данному заданию. Вроде задеплоил вовремя, проверил 4 студентов, и мою работу проверили  3 студента.

**Comment by igorlyatskiy** [comment]
Баллы будут начислены после следующего пересчёта скора
