### ISSUE TITLE
CV#3. CV. Cross-Check - Pereguda

### ISSUE THREAD

**Issue by Pereguda** [rolling-scopes-school/support#394]
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv.md
![image](https://user-images.githubusercontent.com/78586042/148876224-26464ff4-66e0-451f-b7ea-d618b31bd391.png)
https://pereguda.github.io/rsschool-cv/
Done 03.01.2022 / deadline 04.01.2022
Score: 120 / 120
Самопроверка
засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
вёрстка валидная +10
image
вёрстка семантическая +20
header, main, footer +5
элемент nav +5
только один заголовок h1 +5
заголовки h2 +5
в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
для оформления СV используются css-стили +10
при уменьшении масштаба страницы вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
на странице СV есть фото автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
Содержание CV +30
краткая информация о себе +5
контакты для связи +5
перечень навыков +5
пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
информацию об образовании и уровне английского +5
CV выполнено на английском языке +10

Доброе утро!
Работу засабмитил вовремя, оценки по кросс-чеку по ней есть, чужие работы тоже проверил в последний день дедлайна 10 января (как только дали интернет, я из Казахстана, с Алматы). Прошу засчитать мою работу по данному заданию.

**Comment by igorlyatskiy** [comment]
Баллы будут начислены после следующего пересчёта скора, повода для апелляции нет

**Comment by Pereguda** [comment]
Спасибо! Прошу прощения за лишние хлопоты.

вт, 11 янв. 2022 г. в 14:55, Igor Lyatskiy ***@***.***>:
