### ISSUE TITLE
CV#3. CV. Cross-Check - NikolayPhizik

### ISSUE THREAD

**Issue by NikolayPhizik** [rolling-scopes-school/support#395]
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv.md
![image](https://user-images.githubusercontent.com/81764027/148877718-153870af-9ef6-49e8-bf74-f5ac0249ba69.png)
https://nikolayphizik.github.io/rsschool-cv/
Score: 120 / 120
В ходе самопроверки установил, что моя работа удовлетворяет всем пунктам критерий оценки.
Работу я выполнил раньше срока, но в связи с событиями происходящими в Казахстане, у нас отсутствовал интернет с 5 по 11 января и поэтому не смог выполнить кроссчек в нужный срок. На данный момент 11 января я проверил работы четырех студентов и засабмитил. Поэтому прошу проверить мою работу и зачислить мне баллы. Сам я из Казахстана, Жамбылская область, село Мерке.

**Comment by igorlyatskiy** [comment]
Все работы были проверены до закрытия кросс-чека, баллы будут начислены после следующего пересчёта скора
