### ISSUE TITLE
Cross-Check 'CV#3. CV Cross-Check' - 'Makoni1'

### ISSUE THREAD

**Issue by Makoni1** [rolling-scopes-school/support#396]
1. **Ссылка на деплой проекта:** Deploy: https://makoni1.github.io/rsschool-cv/
2. **Ссылка на репозиторий с проектом на GitHub:** https://github.com/Makoni1/rsschool-cv/pull/3
3. **Ссылка на задание:** https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. **Форма для проверки:** https://cv-cross-check.netlify.app/
5. **Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).**
![1](https://user-images.githubusercontent.com/67749844/148879253-7a4d72fd-357f-41d6-ae55-7181402e9733.png)
6. **Оценка в результате самопроверки с ее аргументацией.**  120-130 баллов. Считаю хорошая работа.

В связи с отключением интернета в Казахстане, в городе Алматы с 5 января - 10 января, дедлайны сдвинули.

Интернет в Алматы дают с 9 утра до 1 обеда в ближайшие дни.

Так как успела засабмитить до отключение, проверили только двое человек мою работу, cделала cross check 10 января, но все равно стоит 0 баллов в рейтинге. 

Прошу проверить и поставить баллы за данное задание.

Спасибо за понимание.

**Comment by igorlyatskiy** [comment]
![image](https://user-images.githubusercontent.com/77933579/148912427-3a6f0865-c742-4aab-a7fc-38bcc18430cb.png)
Вы получиши ваши баллы за работу, отобразятся они после следующего пересчета скора
Нет повода для апелляции
