### ISSUE TITLE
Cross-Check 'Docker basics' - 'evitla'

### ISSUE THREAD

**Issue by evitla** [rolling-scopes-school/support#397]
- Ссылка на PR: https://github.com/evitla/nodejs2021Q4-service/pull/4
- Ссылка на репозиторий с проектом: https://github.com/evitla/nodejs2021Q4-service
- Ссылка на задание: https://github.com/rolling-scopes-school/basic-nodejs-course/blob/master/descriptions/docker-basics.md
- Оценка в результате самопроверки с ее аргументацией: 130 / 130
## Базовая реализация:
- [x]  Наличие в `Readme.md` секции с инструкцией как запустить приложение **плюс 20 баллов**
- [x] Используется `user-defined bridge` **плюс 30 баллов**
- [x] При возникновении ошибки контейнер должен перезапускается автоматически **плюс 30 баллов**
- [x] Логи и файлы базы данных хранятся в `volumes`, а не в контейнере **плюс 30 баллов**

## Продвинутая реализация
- [x] Итоговый docker-образ с приложением имеет размер меньше 300 мб **плюс 20 баллов**

## Штрафы
Штрафов нет

**Comment by AlreadyBored** [comment]
Ваша оценка - 0 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Используется user-defined bridge 
Отзыв: There are no networks to connect containers with db and application at all
2) При возникновении ошибки контейнер перезапускается автоматически 
Отзыв: I put line with error inside of your code and it didn't lead to container restart
3) Логи и файлы базы данных хранятся в volumes, а не в контейнере 
Отзыв: There are no volumes at all
4) Итоговый docker-образ с приложением имеет размер меньше 300 мб 
Отзыв: Docker image's size is 328 Mb
Частично выполненные пункты:
1) Наличие в Readme.md секции с инструкцией как запустить приложение 
Отзыв: There is instruction for Docker Compose CLI usage inside of the README.md. typing "docker-compose up" doesn't create container. If you have only Dockerfile you should put there instructions for Docker CLI instead
Штрафы:
1) При изменении файлов в папке src приложение не перезапускается 

2) Postgress image не указана как зависимость для node image
