### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'Spin4ester'

### ISSUE THREAD

**Issue by Spin4ester** [rolling-scopes-school/support#398]
1. https://spin4ester.github.io/rsschool-cv/
2. https://github.com/Spin4ester/rsschool-cv
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. https://cv-cross-check.netlify.app/
5.
<img width="1394" alt="Screenshot 2022-01-11 at 12 39 34" src="https://user-images.githubusercontent.com/90529956/148893702-fb5ea72e-078e-4728-bbaf-a28dee19bf1e.png">
<img width="1394" alt="Screenshot 2022-01-11 at 12 39 16" src="https://user-images.githubusercontent.com/90529956/148893717-af478921-32ea-44c6-ae11-8d72b197020b.png">
<img width="1394" alt="Screenshot 2022-01-11 at 12 38 29" src="https://user-images.githubusercontent.com/90529956/148893724-1e30532c-b295-43e6-8aea-ba609c5227eb.png">
6. Работа выполнена согласно критериям. Проблема в том, что в рс апп локация у меня установлена Будапешт, Венгрия, однако почти уже 3 месяца в связи с обстоятельствами я нахожусь в Казахстане. Само CV я отправил еще за два дня до дедлайна, интернет дали впервые с 4 го числа вчера, задание по кросс чеку я выполнил, однако баллы не зачислились. 
7. 0/120

**Comment by igorlyatskiy** [comment]
Вы получили баллы за кроссчек, повода для апелляции нет
![image](https://user-images.githubusercontent.com/77933579/148913287-b227b9ec-dde6-4c1e-ad3d-7968b8357db4.png)
