### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'dixrom'

### ISSUE THREAD

**Issue by diXrom** [rolling-scopes-school/support#399]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Screenshot: ![image](https://cdn.discordapp.com/attachments/574907131363590174/925820405187485716/unknown.png)
3. Deploy: https://dixrom.github.io/rsschool-cv/
4. Done 29.12.2021 / Deadline 10.01.2022
5. Score: 125 / 120
6. В связи с печальными событиями происходящими в Казахстане и соответственно отсутствия интернета с 5 по 11 января не смог выполнить кроссчек до дедлайна.
7. Моя работа проверена 4 студентамии отправлена была 29.12.2021, я в свою очередь только сегодня проверил работы других студентов и засабмитил. Но в Score нет баллов по CV#3, как понимаю из за позднего кроссчека?
![image](https://cdn.discordapp.com/attachments/574907131363590174/930522330558521445/unknown.png) 
![image](https://cdn.discordapp.com/attachments/574907131363590174/930522366138785853/unknown.png) 
![image](https://cdn.discordapp.com/attachments/574907131363590174/930522425634979890/unknown.png) 
![image](https://cdn.discordapp.com/attachments/574907131363590174/930522513488879666/unknown.png) 
8. Прошу рассмотреть мою ситуацию и прощу прощения за доставленные неудобства.

**Comment by spherical-horse** [comment]
**Ваша оценка - 115 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

2) информацию об образовании и уровне английского 

**Частично выполненные пункты:**

1) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
_feedback: Перечень навыков оформлен не списком_

**Выполненные пункты:**
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) краткую информацию о себе 

12) контакты для связи 

13) перечень навыков 

14) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

15) CV выполнено на английском языке

**Comment by diXrom** [comment]
> **Не выполненные/не засчитанные пункты:** 
> - информацию об образовании и уровне английского

Предпоследний блок это слайдер, там есть информация об образовании и уровень английского.

**Comment by diXrom** [comment]
> **Ваша оценка - 115 баллов**
> 
> Отзыв по пунктам ТЗ:
> 
> **Не выполненные/не засчитанные пункты:**
> 
>     1. перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения
> 
>     2. информацию об образовании и уровне английского
> 
> 
> **Частично выполненные пункты:**
> 
>     1. навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a
>        _feedback: Перечень навыков оформлен не списком_
> 
> 
> **Выполненные пункты:**
> 
>     1. студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages
> 
>     2. вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
> 
>     3. header, main, footer
> 
>     4. элемент nav
> 
>     5. только один заголовок h1
> 
>     6. заголовки h2
> 
>     7. в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка.
> 
>     8. для оформления СV используются css-стили
> 
>     9. при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону
> 
>     10. на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt.
> 
>     11. краткую информацию о себе
> 
>     12. контакты для связи
> 
>     13. перечень навыков
> 
>     14. пример кода. Код добавляется при помощи символов и тегов, а не картинкой
> 
>     15. CV выполнено на английском языке

Предпоследний блок это слайдер, там есть информация об образовании и уровень английского.

**Comment by spherical-horse** [comment]
В первый раз у меня некорректно работал слайдер. После обновления страницы увидел в слайдере информацию об образовании и уровне английского. Оценку отредактировал.
