### ISSUE TITLE
Cross-Check Singolo - Sergey0s

### ISSUE THREAD

**Issue by Sergey0s** [rolling-scopes-school/support#40]
Деплой - https://sergey0s.github.io/singolo/
Репозиторий - https://github.com/Sergey0s/singolo
Оценка в результате самопроверки - 94 : 
- В Our Services отсутствует небольшая линия другого цвета
- В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт
Балл за кросс чек - 83

Проблема в том, что Student 1 оценил работу в 58 баллов.

Student 1
Ваша оценка - 58 баллов 
Отзыв по пунктам ТЗ:

1) В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020: минус -10 баллов
2) В коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020: минус -10 баллов
3) В коммитах, или в ветках с коммитами, файлы singolo3.html и singolo3.сss или index.html и style.css отсутствуют до 09.03.2020: минус -10 баллов  

 **- НЕ ВЕРНО, все файлы создавались, коммитились и даже мерджились в мастер ветку до дедлайна, в истории коммитов это прекрасно видно.**

4) Внизу как минимум одной из секций (кроме Footer) отсутствует небольшая линия другого цвета: минус -3 балла   **+ СОГЛАСЕН**
5) В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла  **+ СОГЛАСЕН**
6) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла   **- НЕ ВЕРНО, т.к. на переполнение проверяются только элементы с именем**
7) Социальные иконки в Footer-e без интерактивных стилей, при наведении на логотипы соц.сетей ничего не происходит: минус -3 балла   **- НЕ ВЕРНО, курсор меняется на pointer**

Пожалуйста, прошу Вас восстановить справедливость.

**Comment by amoebiusss** [comment]
@Sergey0s добрый день! Апелляция доступна при разнице минимум 15 баллов между ожидаемой и фактической оценкой.

https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f

**Comment by Sergey0s** [comment]
@amoebiusss Я видел это, но Вы считаете нормальным мне терять 11 баллов из за некомпетентности проверяющего? То есть я просто должен установить ожидаемую оценку на 100 и тогда Вы бы ознакомились с работой? Хотелось решить все по честному.

**Comment by amoebiusss** [comment]
@Sergey0s мы всё же надеемся на отсутствие подобных манипуляций и на адекватную самооценку. Возможности перепроверить абсолютно все работы нет, поэтому апелляция предназначена для случаев, когда разница в баллах значительна.

Спасибо за понимание!
