### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'Olga Ezzhlkina'

### ISSUE THREAD

**Issue by OlgaEzzhlkina** [rolling-scopes-school/support#400]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Deploy: https://olgaezzhlkina.github.io/rsschool-cv/
3. Repository: https://github.com/OlgaEzzhlkina/rsschool-cv

Добрый день! Прошу прощения, в связи в отключением интернета не смогла сдать задание до дэдлайна. Если ещё есть возможность проверить таск буду очень рада!

**Comment by igorlyatskiy** [comment]
Добавь самооценку
