### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'Olga Ezzhlkina'

### ISSUE THREAD

**Issue by OlgaEzzhlkina** [rolling-scopes-school/support#401]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Deploy: https://olgaezzhlkina.github.io/rsschool-cv/
3. Repository: https://github.com/OlgaEzzhlkina/rsschool-cv
4. Score: 110 / 120

" UPD2. Если вы не засабмитили CV#3, до 10.01 23:59 UTC создайте, пожалуйста, апелляцию. "

В Discord написали для студентов из Казахстана дата подачи апелляций не ограничена!

**Comment by igorlyatskiy** [comment]
Отредактируйте текст этого issue так, чтобы был пункт 4 с самооценкой. После того, как отредактируете, я сниму метку `invalid`

**Comment by OlgaEzzhlkina** [comment]
Самостоятельная оценка:
1. Вёрстка валидная +10
2. Используются тэги header, main, footer +5
3. Элемент nav +5
4. Один заголовок h1 +5
5. Заголовки h2 +5
6. В footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
7. Для оформления СV используются css-стили +10
8. На странице СV есть фото автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
9. Навигация и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
10. Контакты для связи +5
11. Перечень навыков +5
12. Пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
13. CV выполнено на английском языке +10
95 / 120

**Comment by YuliyaMinsk** [comment]
У меня вышло: **120 баллов**

Очень хорошая работа. Не знаю как получилось 95 на самопроверке. Возможно, не посчитан сабмит ссылки, сохранения центровки контента, наличие раздела "О себе", информации об образовании и уровне английского.
Я нашла только две недоработки:
- Нет списка контактов выполнен не списком -3 балла,
- Нет перечня проектов, -5 баллов.

**Comment by OlgaEzzhlkina** [comment]
Спасибо!)))))

**Comment by OlgaEzzhlkina** [comment]
Спасибо большое!!!😊

ср, 12 янв. 2022 г., 3:29 Yuliya Niaverava ***@***.***>:
