### ISSUE TITLE
Cross-Check 'CV#3.CV.Cross Check - 'liracentavra'

### ISSUE THREAD

**Issue by LiraCentavra** [rolling-scopes-school/support#402]
1. https://liracentavra.github.io/rsschool-cv/
2. https://github.com/LiraCentavra/rsschool-cv
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
5. Мою работу не проверили т.к. я только в 23.30 10.01 смогла сохранить проект на GitHub (были проблемы с подключением к Интернету, не помогал VPN).
6. 120 баллов, т.к. соблюдены все требования к работе.
7. Нету балла за Crocc-Check, т.к. см. пункт 5.

**Comment by LiraCentavra** [comment]
1. Студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
2. Вёрстка валидная +10 :
![HTML Checker](https://user-images.githubusercontent.com/93795853/149009498-9915db77-8365-4607-a252-8020614d66b5.png)
3. В коде странице присутствуют и используются по назначению следующие элементы:
- header, main, footer +5
- элемент nav +5
- только один заголовок h1 +5
- заголовки h2 +5
4. В footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
для оформления СV используются css-стили +10
5. При уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
6. На странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
7. Навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
8. Содержание CV +30
CV содержит:
краткую информацию о себе +5
контакты для связи +5
перечень навыков +5
пример кода. Код добавляется при помощи символов и тегов, а не картинкой +5
перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения +5
информацию об образовании и уровне английского +5
9.CV выполнено на английском языке +10
Всего 120 баллов. Все требования соблюдены.

**Comment by LiraCentavra** [comment]
Нашла, что я не сделала: не указала в Projects, что CV и есть мой проект. Просто написала, что проектов у меня пока нет.
Итого самооценка 110/120.

**Comment by igorlyatskiy** [comment]
Работа списана, за это в школе отчисляют

**Comment by LiraCentavra** [comment]
Здравствуйте! Я с полного нуля, ещё не разбираюсь в вёрстке. Использовала образец как начальный вариант с изменениями. Как основу. Ведь я внесла свои изменения. Для меня понимание этого всего было выходом в открытый космос. В дискорде ребята смотрели моё cv, сказали для начала пойдет. Я не смогу так быстро сверстать что-то совсем другое. В процессе учёбы конечно буду его менять. Не отчисляйте. Поставьте ноль баллов. Но это не было целью списать. Это было первое столкновение и понимание html. css. Я обещаю переделать cv не беря образец в основу, как только разберусь ещё лучше с html и css.
