### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'kandcom'

### ISSUE THREAD

**Issue by kandcom** [rolling-scopes-school/support#403]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Scrennshot
![image](https://user-images.githubusercontent.com/17139673/148983409-9426b1d2-a749-45dd-bba2-0831c0d54f9b.png)
3. Deploy: https://kandcom.github.io/rsschool-cv/
4. Done 2022-01-04. DeadLine 2022-01-10
5. Srore 120-120
6. С 4 по 10 января в Казахстане, большую часть дня отсутствовал мобильный, домашний интернет. 
7, Работа была проверена 4 студентами. Получил высокую оценку, однако работы других студентов проверил лишь сегодня. Поэтому оценку за cv#3 у меня нет(((

**Comment by spherical-horse** [comment]
**Ваша оценка - 110 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) элемент nav 

2) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

**Частично выполненные пункты:**

1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 
_feedback: Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections._

2) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
_feedback: Отсутствует навигация_

**Выполненные пункты:**
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) header, main, footer 

3) только один заголовок h1 

4) заголовки h2 

5) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

6) для оформления СV используются css-стили 

7) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

8) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

9) краткую информацию о себе 

10) контакты для связи 

11) перечень навыков 

12) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

13) информацию об образовании и уровне английского 

14) CV выполнено на английском языке
