### ISSUE TITLE
Cross-Check "Art-Quiz"-Archi-Minsk

### ISSUE THREAD

**Issue by Archi-Minsk** [rolling-scopes-school/support#404]
1.Deploy:  https://archi-minsk-art-quiz.netlify.app/
2.Repository link: https://github.com/rolling-scopes-school/archi-minsk-JSFE2021Q3/tree/art-quiz
3. Task:  https://github.com/rolling-scopes-school/tasks/blob/master/tasks/art-quiz/art-quiz.md
4. Form: https://art-quiz-cross-check.netlify.app/
5.  Из-за мое не внимательности task не был отправлен на проверку, если есть такая возможность проверьте пожалуйста мою работу, эти балы для меня очень важны. (после дедлайна работа не изменялась)
6. Score 220/ 190
       - не выполнено: 
            a) Одновременная загрузка и плавная смена изображений
            b) Уникальная сложная анимаця
            с) Дополнительный функционал

**Comment by igorlyatskiy** [comment]
К сожалению, подобные апелляции не проверяются
