### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'toshaby'

### ISSUE THREAD

**Issue by ToshaBY** [rolling-scopes-school/support#405]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Screenshot:
![image](https://user-images.githubusercontent.com/13542222/149075378-ef34f423-4d1f-4b38-aaeb-3c17f0bd8e4e.png)

3. Deploy: https://toshaby.github.io/rsschool-cv/
4. Done 05.01.2022 / Deadline 06.01.2022
5. Score: 120/120

Сабмитил задание и 04.01 (до старого дедлайна) и 05.01 (как узнал что дедлайн перенесли). После старта кросс-чека не подгружались CV других студентов. Узнал 10.01 что это проблема не у одного меня (я из Беларуси) и решается подключением через впн. 11.01 приехал в офис на работу, что бы подключится через рабочий впн и проверил задания других студентов. Но баллы не пришли как за работу так и за кросс-чек. Прошу понять и простить. Не успел сделать вовремя из-за технических проблем.

**Comment by ToshaBY** [comment]
Самостоятельная оценка:

1. Засабмитил в rs-app задеплоеное на gh-pages (+10)
2. Верстка валидня, но есть ошибки (неправильный эскейп), частично снимаю балл (+5)
3. Вёрстка семантическая (+20)
4. Все необходимое есть в футере (+10)
5. Используются стили (+10)
6. Страница не сдвигается в сторону (+10)
7. Есть фото с alt (+10)
8. Пункты навигации не оформил списком, все остально - списками, частично снимаю балл (+5)
9. Содержание CV (+30)
10. На английском языке (+10)

Итоговая оценка: 115 (мелкие недоработки, частичное снятие баллов)

**Comment by spherical-horse** [comment]
**Ваша оценка - 115 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 
_feedback: Error: Bad character   after <. Probable cause: Unescaped <. Try escaping it as <._

**Частично выполненные пункты:**

1) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
_feedback: Навигация оформлена не списком_

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) header, main, footer 

3) элемент nav 

4) только один заголовок h1 

5) заголовки h2 

6) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

7) для оформления СV используются css-стили 

8) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

9) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

10) краткую информацию о себе 

11) контакты для связи 

12) перечень навыков 

13) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

14) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

15) информацию об образовании и уровне английского 

16) CV выполнено на английском языке
