### ISSUE TITLE
Cross-Check 'Docker basics' - 'jamask'.

### ISSUE THREAD

**Issue by jamask** [rolling-scopes-school/support#406]
1. Ссылка на деплой вашего проекта: [Task-7](https://github.com/jamask/nodejs2021Q4-service/pull/4)
2. Ссылка на репозиторий с проектом на GitHub: [https://github.com/jamask/nodejs2021Q4-service](https://github.com/jamask/nodejs2021Q4-service)
3. Ссылка на задание.  [https://github.com/rolling-scopes-school/basic-nodejs-course/blob/master/descriptions/logging-error-handling.md](https://github.com/rolling-scopes-school/basic-nodejs-course/blob/master/descriptions/logging-error-handling.md)
 
   В связи с ситуацией в Казахстане не смог вовремя сдать задание. Я из города Костанай республика Казахстан

**Comment by AlreadyBored** [comment]
Ваша оценка - 60 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) При возникновении ошибки контейнер перезапускается автоматически 

2) Итоговый docker-образ с приложением имеет размер меньше 300 мб 
Отзыв: Docker image size is 333 Mb
Выполненные пункты:
1) Наличие в Readme.md секции с инструкцией как запустить приложение 

2) Используется user-defined bridge 

3) Логи и файлы базы данных хранятся в volumes, а не в контейнере 

Штрафы:
1) При изменении файлов в папке src приложение не перезапускается
