### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - SimpleJean

### ISSUE THREAD

**Issue by SimpleJean** [rolling-scopes-school/support#407]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
2. Deploy: https://simplejean.github.io/rsschool-cv/
3. Repository: https://github.com/SimpleJean/rsschool-cv
4. 100/130
5. Из-за отсутствия интернета в Казахстане не смог вовремя(до дедлайна) выполнить таску. Хотя я вижу оценки моего CV и с ними полностью согласен.

**Comment by spherical-horse** [comment]
**Ваша оценка - 115 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) элемент nav 

**Частично выполненные пункты:**

1) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 
_feedback: Картинка незначительно искажена._

2) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
_feedback: Контакты для связи не в виде списка._

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) только один заголовок h1 

5) заголовки h2 

6) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

7) для оформления СV используются css-стили 

8) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

9) краткую информацию о себе 

10) контакты для связи 

11) перечень навыков 

12) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

13) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

14) информацию об образовании и уровне английского 

15) CV выполнено на английском языке
