### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'Aigerim Amanbayeva

### ISSUE THREAD

**Issue by Aigeri** [rolling-scopes-school/support#408]
https://aigeri.github.io/rsschool-cv/
![018FA04A-42DD-47ED-83AC-44CC82702FA8](https://user-images.githubusercontent.com/52953860/149146118-8a4f0998-ec90-4932-a191-6a7f83152f9b.png)
![DDD94D13-62E8-4187-861C-47EC7B32EE4F](https://user-images.githubusercontent.com/52953860/149146477-5d040fc3-a3a6-45f8-bec1-f7db13f9faf6.png)
![8DD426EF-C5A8-44E9-BD6D-729224EE4C2B](https://user-images.githubusercontent.com/52953860/149146491-2d2dd7b3-3a14-47ab-aec7-1cc332be74d6.png)

Прошу начислить мне 120 баллов за CV3. Мою работу проверили 4 человека. Я также проверила работы 4 человек, сразу как у нас в Алматы включили интернет.

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

**Частично выполненные пункты:**

1) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
_feedback: Навигация и контакты для связи не в виде списка_

**Выполненные пункты:**
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) краткую информацию о себе 

12) контакты для связи 

13) перечень навыков 

14) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

15) информацию об образовании и уровне английского 

16) CV выполнено на английском языке
