### ISSUE TITLE
Cross-Check Singolo - Pakertak

### ISSUE THREAD

**Issue by Pakertak** [rolling-scopes-school/support#41]
https://pakertak.github.io/singolo/index.html
https://github.com/Pakertak
Оцениваю в 80 баллов.
Student 3:
"Ваша оценка - 67 баллов 
Отзыв по пунктам ТЗ:
1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла 
2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Footer составляют более двух пикселей (2px): минус -3 балла 
3) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Get a Quote: минус -3 балла 
4) Внизу как минимум одной из секций (кроме Footer) отсутствует небольшая линия другого цвета: минус -3 балла 
5) В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла 
6) При добавлении в сетку с изображениями элементов за 12-м (проверяя, добавляем их сами) следющие за 12-м отображаются на странице - не реализовано ограничение видимых двенадцатью показанными в макете: минус -3 балла 
7) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла 
8) Внутри тэга "< form >" отсутствует кнопка Submit, или она реализована не с помощью "< button >" или "< input >": минус -3 балла"
**Кнопка имеется**
"9) Не выполняется валидация обоих полей ввода с отметкой Required в макете, или указан неправильный тип "< input >", или отсутствуют необходимые атрибуты, или при пропуске/вводе невалидных значений форма отправляется без ожидаемых замечаний: минус -3 балла 
10) Номер телефона в блоке Contacts не реализован ссылкой, работающей с префиксом tel:: минус -3 балла 
11) Электронная почта в блоке Contacts не реализована ссылкой, работающей с префиксом mailto:: минус -3 балла"
-------------------------------------------------------------------------------------------------------
Student 2
Ваша оценка - 0 баллов 
Отзыв по пунктам ТЗ:
1) Pепозиторий singolo не существует, или в нем не присутствуют index.html и style.css файлы: минус -100 баллов
**Все файлы в gh-pages, похоже студент просто не проверил**
-------------------------------------------------------------------------------------------------------
Общий балл: 54.
Прошу пересмотреть решение.

**Comment by amoebiusss** [comment]
@Pakertak добрый день! Добавьте в описание балл, на который вы сами оцениваете задание. Спасибо!

**Comment by amoebiusss** [comment]
@Pakertak привет! Ваша итоговая оценка по обновленному алгоритму — 72, наименьшая оценка (ноль) была исключена из подсчета. Итоговая от заявленной отличается на 8 баллов, минимальная разница для апелляции — 15, поэтому закрываю ишью. Хорошего дня!
