### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'theV1rTual (Amanzhol Arystan)'

### ISSUE THREAD

**Issue by theV1rTual** [rolling-scopes-school/support#410]
https://github.com/theV1rTual/rsschool-cv

Добрый день, прошу посмотреть мою работу и начислить баллы. Я знаю что сделал неправильную ссылку, но все остальные пункты у меня правильные. Я проверил 4 человек и 4 человека проверили меня.

**Comment by igorlyatskiy** [comment]
Оформите апелляцию по правилам

**Comment by theV1rTual** [comment]
Ссылка на деплой вашего проекта: https://github.com/theV1rTual/rsschool-cv
Ссылка на репозиторий с проектом на GitHub: https://github.com/theV1rTual/rsschool-cv
Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Ссылка на форму для проверки проекта (если такая есть):  https://cv-cross-check.netlify.app/
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты): 

<img width="1920" alt="Снимок экрана 2022-01-12 в 23 22 47" src="https://user-images.githubusercontent.com/71083612/149190998-127b369a-ca11-4a29-ad68-0b4e15dee13f.png">


<img width="1920" alt="Снимок экрана 2022-01-12 в 23 21 42" src="https://user-images.githubusercontent.com/71083612/149190931-f28ea0fa-8365-49fc-8903-87998f69da95.png">


Оценка в результате самопроверки с ее аргументацией: 115, сделал все кроме ссылки в футере на stage0  и ссылки на деплой 
Балл за cross-check из вашего Score: 0

**Comment by igorlyatskiy** [comment]
CV не задеплоено, ссылка на деплой неверная

**Comment by theV1rTual** [comment]
Да, я не смог разобраться как сделать деплой. Просто ссылку гитхаб вставил
