### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'madiyar-yp'

### ISSUE THREAD

**Issue by madiyar-yp** [rolling-scopes-school/support#411]
1. Deploy: https://madiyar-yp.github.io/rsschool-cv/
2. Repository: https://github.com/madiyar-yp/rsschool-cv
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. Screenshots:
![Inkedcross-check-01_LI png](https://user-images.githubusercontent.com/69837840/149317864-6c3e3f04-431c-4e1c-a19e-6a40f3215bfd.jpg)
![cross-check-02](https://user-images.githubusercontent.com/69837840/149317920-e56c9a09-09bb-455f-bd03-a12c63aba1f2.png)
5. В Казахстане в Алматы с вечера 5 января и до 10 января не было интернета, по этому не сделал кросс-чек ревью. В скриншотах видно что оценили мою работу, но очки все еще не начислены.

**Comment by turn2river** [comment]
120 баллов.

Приятная минималистичная работа, понравился стиль подстветки кода :)
Не хватает навигации и перечня работ, в будущем, уверен, эти пункты появятся, удачного обучения! :)
