### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'aliaxandra'  - Баллы не добавлены в Score

### ISSUE THREAD

**Issue by aliaxandra** [rolling-scopes-school/support#412]
**Мои баллы не отображаются в Score.** 
Прошу добавить.

![image](https://user-images.githubusercontent.com/12713348/149326058-263c4ede-574c-482d-90be-3983ff90d4b6.png)

Спасибо!

_Originally posted by @aliaxandra in https://github.com/rolling-scopes-school/support/issues/352#issuecomment-1012070550_

**Comment by igorlyatskiy** [comment]
Баллы будут добавлены, когда закончат появляться апелляции по этому заданию
