### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'kbatyr' 

### ISSUE THREAD

**Issue by kbatyr** [rolling-scopes-school/support#413]
Deploy: https://kbatyr.github.io/rsschool-cv/
Repository: https://github.com/kbatyr/rsschool-cv
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
Screenshots:
![image](https://user-images.githubusercontent.com/53165607/149327018-601a860b-91b5-40ab-971a-425c378f1157.png)
![image](https://user-images.githubusercontent.com/53165607/149327081-f1742e49-9e21-4133-ade6-dd1330c6e30d.png)
В  связи с отстуствием доступа к интернету в Казахстане на период с 5 по 10 января, не получилось провести кросс-чек ревью.
Прикрепил скрины, где видно что оценили мою работу, однако очки за таск не были начислены.
Заранее благодарю!

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов**
 
Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

16) информацию об образовании и уровне английского 

17) CV выполнено на английском языке

**Comment by kbatyr** [comment]
Спасибо!

**Comment by kbatyr** [comment]
Баллы до сих пор не зачислились. В чем может быть дело?
