### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'AlmasAbdykadyr'

### ISSUE THREAD

**Issue by almasabdykadyr** [rolling-scopes-school/support#414]
1. Deploy: https://almasabdykadyr.github.io/rsschool-cv/
2. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
![rsschoolcv](https://user-images.githubusercontent.com/59607697/149339260-a9ca0a22-e1e7-4192-a7d4-c3b52dc4bdf5.png)
3. Repository: https://github.com/almasabdykadyr/rsschool-cv
4. Score: 120/130
-----------------------------------------
Добрый день, вовремя не успел засабмитить ссылку, можете пожалуйста проверить.

**Comment by spherical-horse** [comment]
**Ваша оценка - 120 баллов** 

Отзыв по пунктам ТЗ:

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

16) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

17) информацию об образовании и уровне английского 

18) CV выполнено на английском языке
