### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'arariio'

### ISSUE THREAD

**Issue by ARARIIO** [rolling-scopes-school/support#415]
1. Deploy: https://arariio.github.io/rsschool-cv/
2. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
3. Screenshot: 
![image](https://user-images.githubusercontent.com/92432334/149340742-b5868aec-91db-4193-ad3e-7cdd69d7ffac.png)
4. Repository: https://github.com/arariio/rsschool-cv
5. Score: 120/130
---
Не выставили оценку

**Comment by spherical-horse** [comment]
**Ваша оценка - 115 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

2) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) header, main, footer 

3) элемент nav 
_feedback: Ссылки в элементе nav нерабочие._ 

4) только один заголовок h1 

5) заголовки h2 

6) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

7) для оформления СV используются css-стили 

8) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

9) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

10) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

11) краткую информацию о себе 

12) контакты для связи 

13) перечень навыков 

14) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

15) информацию об образовании и уровне английского 

16) CV выполнено на английском языке
