### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'jazi29'

### ISSUE THREAD

**Issue by jazi29** [rolling-scopes-school/support#416]
1. Deploy: https://jazi29.github.io/rsschool-cv/
2. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
3. Screenshot:
![Capture1](https://user-images.githubusercontent.com/79010812/149373324-eca93c1b-0f03-4a65-9efc-1b39816a4d62.PNG)
![Capture2](https://user-images.githubusercontent.com/79010812/149373290-338c0133-bfac-4e2a-9481-45d6ffa899e9.PNG)
6. Repository: https://github.com/jazi29/rsschool-cv
7. Score: 100/120

**Comment by spherical-horse** [comment]
**Ваша оценка - 83 балла** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

2) header, main, footer 

3) элемент nav 

4) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 
_feedback: Текст разъезжается в разные стороны. Вся верстка разваливается._

5) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

**Частично выполненные пункты:**

1) заголовки h2 
_feedback: Только один заголовок h2_

2) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 
_feedback: Изображение добавлено как фон. Атрибут alt отсутствует._

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) только один заголовок h1 

3) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 
_feedback: Вся верстка развалилась. Нашел эти элементы только в исходном коде. Год создания приложения был написан белым текстом на белом фоне._

4) для оформления СV используются css-стили 

5) краткую информацию о себе 

6) контакты для связи 

7) перечень навыков 

8) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

9) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 
_feedback: В питоновском коде критично важны пробелы (или табы). У вас код выводится без отступов. Нужно было использовать теги pre и code._

10) информацию об образовании и уровне английского 

11) CV выполнено на английском языке
