### ISSUE TITLE
Cross-Check 'Docker basics' - 'unpin'

### ISSUE THREAD

**Issue by unpin** [rolling-scopes-school/support#417]
0. Причина: В связи с ситуацией в Казахстане, небыло возможности выполнить задание, т.к. по всей стране не было доступа к интернету в течении недели. 
1. Ссылка на Pull Request: [Docker Basics PR](https://github.com/unpin/nodejs2021Q4-service/pull/4)
2. Ссылка на репозиторий с проектом: [unpin/nodejs2021Q4-service](https://github.com/unpin/nodejs2021Q4-service)
3. Ссылка на задание: [Docker Basics](https://github.com/rolling-scopes-school/basic-nodejs-course/blob/master/descriptions/docker-basics.md)
4. Ссылка на форму для проверки проекта: [RSS TASKS CHECKLIST](https://boring-ride-216864.netlify.app)
5. Оценка в результате самопроверки с ее аргументацией: (130 баллов)

## Базовая реализация:
* [x] Наличие в `Readme.md` секции с инструкцией как запустить приложение **плюс 20 баллов**
* [x] Используется `user-defined bridge` **плюс 30 баллов**
![network](https://user-images.githubusercontent.com/42736230/149366284-9c34289c-f444-4613-a22c-a75b51423e0e.png)
* [x] При возникновении ошибки контейнер должен перезапускается автоматически **плюс 30 баллов**
> 1. При возникновении ошибки контейнер автоматически перезапускается. 
> 2. При изменении файлов в папке `src` перезапускается приложение.
* [x] Логи и файлы базы данных хранятся в `volumes`, а не в контейнере **плюс 30 баллов**
![0logs](https://user-images.githubusercontent.com/42736230/149366725-125a0eb7-eeaf-4771-a91a-5b9b71c8fd1d.png)
![logs](https://user-images.githubusercontent.com/42736230/149366550-2537aa69-b790-4df7-af90-4d1c71efacf1.png)

## Продвинутая реализация
* [x] Итоговый docker-образ с приложением имеет размер меньше 300 мб **плюс 20 баллов**
![Screenshot 2022-01-13 044305](https://user-images.githubusercontent.com/42736230/149234875-6cf21b1f-07ab-4578-8292-70cdae5fefe9.png)

## Штрафы:
* [ ] Внесение изменений в репозиторий после дедлайна не считая коммиты, вносящие изменения только в `Readme.md` **минус 30% от максимального балла за задание (для этого задания 39 баллов)**
* [ ] За отсутствие отдельной ветки для разработки **минус 20 баллов**
* [ ] За отсутствие `Pull Request` **минус 20 баллов**
* [ ] За неполную информацию в описании `Pull Request` **минус 10 баллов**
* [ ] Используется `default bridge network driver` **минус 20 баллов**
![network2](https://user-images.githubusercontent.com/42736230/149376282-79a84542-6960-4db1-a41e-949ebd7c6917.png)
* [ ] Конфигурация приложения жестко прописана в` docker-compose.yml` и `Dockerfile` **минус 20 баллов**
> Переменные среды (PORT и DB-related переменные) хранятся в .env, и используются в `docker-compose.yml`
* [ ] При изменении файлов в папке `src` приложение не перезапускается **минус 20 баллов**
> При изменении файлов в папке `src` приложение перезапускается.
* [ ] Должен использоваться специфичный образ. (Например `postgres` и `node`, а не `ububtu` с установкой `node` или `postgres`) **минус 20 баллов** в случае, если не используется.
* [ ] `Postgress image` не указана как зависимость для node `image` **минус 20 баллов**
![depends](https://user-images.githubusercontent.com/42736230/149375426-778f8234-88e9-4eea-a029-22c1822fcea8.png)

**Comment by ThorsAngerVaNeT** [comment]
Добрый день.
Замечание: Некорректно сделана проброска порта для postgres, при изменении значения порта в .env внутри контейнера порт у postgres не меняется и получается ситуация, когда порт прокинут на незадействованный внутри контейнера порт.
Ваша оценка - 130 баллов 
Отзыв по пунктам ТЗ:
Выполненные пункты:
1) Наличие в Readme.md секции с инструкцией как запустить приложение 

2) Используется user-defined bridge 

3) При возникновении ошибки контейнер перезапускается автоматически 

4) Логи и файлы базы данных хранятся в volumes, а не в контейнере 

5) Итоговый docker-образ с приложением имеет размер меньше 300 мб
