### ISSUE TITLE
Cross-Check 'CV#3.Cross Check'- 'BlackDeepSky'

### ISSUE THREAD

**Issue by BlackDeepSky** [rolling-scopes-school/support#418]
1.Deploy
https://blackdeepsky.github.io/rsschool-cv/
2. Task
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
3.Repositories
https://github.com/BlackDeepSky/rsschool-cv/tree/gh-pages
4.Screenshot
![Image alt](https://i2.piccy.info/i9/d9fa0b55e5cc1f9e07e899caa47c35f6/1642103336/43943/1454729/Screenshot_12_800.jpg)
![Image alt](https://i2.piccy.info/i9/f2863e465bea16e2fe8555fac01fe0db/1642103425/3553/1454729/Screenshot_13_240.jpg)
![Image alt](https://i2.piccy.info/i9/4fdf6aed93b7beb02bf9a848a2978f13/1642103477/39745/1454729/Screenshot_14_800.jpg)
![Image alt](https://i2.piccy.info/i9/6164c4b2a7ad9f2676801022be021e0d/1642103526/33159/1454729/35207Screenshot_15_800.jpg)
5.Причина. В спешке проверки, совсем вылетело из головы, думал что всех проверил в кросс чеке, но оказалось что 3-х. Проверял до дедлайна. 11.01.22 проверил четвертого, но уже было поздно. Прошу засчитать работу

**Comment by spherical-horse** [comment]
**Ваша оценка - 93 балла** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

2) элемент nav 

3) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

4) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

**Частично выполненные пункты:**

1) header, main, footer 
_feedback: Теги header и footer пустые (не используются по назначению)._

2) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
_feedback: Навигация отсутствует. Контакты для связи не в виде списка_

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) только один заголовок h1 

3) заголовки h2 

4) для оформления СV используются css-стили 

5) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

6) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

7) краткую информацию о себе 

8) контакты для связи 

9) перечень навыков 

10) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

11) информацию об образовании и уровне английского 

12) CV выполнено на английском языке
