### ISSUE TITLE
Cross-Check 'CV#3.Cross Check'- 'GuPy0zDeSs' 

### ISSUE THREAD

**Issue by GuPy0zDeSs** [rolling-scopes-school/support#419]
1. Deploy
https://gupy0zdess.github.io/rsschool-cv/
2. Task
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
3. Repositories
https://github.com/GuPy0zDeSs/rsschool-cv/tree/gh-pages
4. Screenshot
![1](https://user-images.githubusercontent.com/82028057/149516321-fd14e6b0-d5a2-437f-ac10-56027f4bd37f.jpeg)
![2](https://user-images.githubusercontent.com/82028057/149516353-da9cc770-1e1f-416f-8345-55ba2fe93d2f.jpeg)
![3](https://user-images.githubusercontent.com/82028057/149516357-c704d6e7-5182-402c-9c48-200b5589ec6c.jpeg)
![4](https://user-images.githubusercontent.com/82028057/149516359-cc544d01-032f-4a35-9a4d-1abab866cd2b.jpeg)
![5](https://user-images.githubusercontent.com/82028057/149516360-672fa921-b4e5-4e56-a4d6-9dd296f86eb8.jpeg)
![6](https://user-images.githubusercontent.com/82028057/149516361-cbc5db61-a094-4b52-9340-ac4318393f51.jpeg)
![7](https://user-images.githubusercontent.com/82028057/149516363-f9f1b50b-ef4d-40e5-853b-ba2fcf9e8137.jpeg)

5.Причина. В связи с отсутствием интернета смог проверить Cross check - review только 2022-01-11, но уже было поздно. Прошу засчитать работу.

**Comment by igorlyatskiy** [comment]
Контакты проверяющих должны быть скрыты
