### ISSUE TITLE
Cross-Check Singolo - mirel557788

### ISSUE THREAD

**Issue by mirel557788** [rolling-scopes-school/support#42]
[Ссылка на деплой:](https://mirel557788.github.io/singolo/)
[Ссылка на репозиторий проекта:](https://github.com/mirel557788/singolo)
**Оценка в результате самопроверки, с ее аргументацией: 82 балла**
В репозитории есть все ветки с соответствующими файлами и коммитами, все загружено вовремя (30 баллов сняли без какой-либо причины).
Ошибка "Изображения, части изображений с телефонами или моделирующие их блоки расположены слоями с нарушением порядка z-index" - не применима к этой работе, поскольку картинка накладывалась не слоями по отдельности с тенью, а целиком (z-index просто не испольщовался).
Если снимается балл за "Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Slider составляют более двух пикселей (2px).", то нет причины дополнительно снимать за "Изображения, части изображений с телефонами или моделирующие их блоки находятся не на своем месте. Горизонтальная картинка на 117px выступает вправо, тень от неё выходит за пределы блока : минус".
Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote, Portfolio составляют более двух пикселей (2px). - здесь отклонений между элементами нет. На лекциях говорилось, что важно, чтобы совпадал шрифт построчно (расстояние между буквами может и не совпадать - требования по letter-spacing не было).
Несколько раз баллы снимаются за один и тот же пункт, просто описывается разными словами.
Ошибки, выявленные в результате самопроверки:
Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Header составляют более двух пикселей (2px)
Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Slider составляют более двух пикселей (2px)
Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px)
Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции About

Балл за cross-check из вашего Score: 65 баллов (среднее)
Student 4 - 37, Student 3 - 58 (баллы, с которыми не согласна)

**Comment by amoebiusss** [comment]
@mirel557788 привет! Алгоритм расчета итоговой оценки обновился и из него была исключен наименьший балл. Таким образом, ваша итоговая оценка — 75. От заявленной она отличается на 7 баллов, минимальная разница для апелляции — 15.
