### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'KairYergozha'

### ISSUE THREAD

**Issue by KairYergozha** [rolling-scopes-school/support#420]
1. Deploy: https://KairYergozha.github.io/rsschool-cv/
2. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
![image](https://user-images.githubusercontent.com/96070791/149518554-4288f0c1-4d67-45f1-b04a-f8f381817528.png)

3. 
![image](https://user-images.githubusercontent.com/96070791/149519165-76f9241e-9758-4f1e-b85a-0126119de78a.png)

4. Repository: https://github.com/KairYergozha/rsschool-cv
5. Score: 107/130
Не успел проверить задание других студентов из за отключения интернете в период с 05.01.2022 до 11.01.2022

**Comment by spherical-horse** [comment]
**Ваша оценка - 110 баллов** 

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**

1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

**Частично выполненные пункты:**

1) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 
_feedback: Логотип курса не в футере. Отсутствует ссылка на курс._

2) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 
_feedback: Картинка не отображается._

**Выполненные пункты:**

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) header, main, footer 

3) элемент nav 

4) только один заголовок h1 

5) заголовки h2 

6) для оформления СV используются css-стили 

7) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

8) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

9) краткую информацию о себе 

10) контакты для связи 

11) перечень навыков 

12) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

13) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

14) информацию об образовании и уровне английского 

15) CV выполнено на английском языке
