### ISSUE TITLE
Cross-Check 'CV#3. Cross Check' - 'farizaten6'

### ISSUE THREAD

**Issue by farizaten6** [rolling-scopes-school/support#421]
- Deploy: https://farizaten6.github.io/rsschool-cv/
- Repository: https://github.com/farizaten6/rsschool-cv
- Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
- 
![image](https://user-images.githubusercontent.com/96007194/149649901-aefa96a6-78d6-4ee3-9f6b-d07e57bee473.png)
- Score 120/130 , тк верстка не проходит проверку через валидатор и я не успела проверить задания других студентов до дедлайна из-за отключений интернета в стране в период с 05.01.2022 до 11.01.2022
- На данный момент балл в Score - 0

**Comment by WiiJoy** [comment]
Добрый день!

Ваша оценка - **118 баллов**

Отзыв по пунктам ТЗ:

**Не выполненные/не засчитанные пункты:**
1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

**feedback**: Проверка валидатором выдает 3 error: 2 относятся к примеру кода (использование спецсимволов), 1 к src лого (путь и имя файла должны быть без пробелов)

**Частично выполненные пункты:**
1) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

**feedback**: Сбрасываю 2 балла за небольшое искажение размера: исходное фото квадратное, отрендеренное имеет другую пропорцию. Стоило в текущем исполнении для object-fit принять значение contain (cover как раз растянул изображение) и поиграться с размерами самого img

Выполненные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) header, main, footer 

3) элемент nav 

4) только один заголовок h1 

5) заголовки h2 

6) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

7) для оформления СV используются css-стили 

8) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

9) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

10) краткую информацию о себе 
**feedback**: Предположу, что под Junior Frontend Developer - та самая краткая информация о себе. Немного не явно, конечно, но главное - наличие :)
11) контакты для связи 

12) перечень навыков 

13) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 
**feedback**: Пример кода вылезает за границы контейнера + именно в нем выпадают 2 из 3 errors при проверке валидности. Стоит идти из структуры pre - code (а не наоборот, тк тогда обеспечивается сначала сохранение преформатирования, а после - обозначение самого кода), для pre, в качестве обеспечения выравнивания контента в левую сторону, можно принять отрицательный margin-left (плюсминус 90px в данном случае), спецсимволы (>, <) стоило заменить их мнемоничными аналогами (`&lt;` для <, `&gt;` для >)
14) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 
**feedback**: Опять же, несколько неявно, но есть
15) информацию об образовании и уровне английского 

16) CV выполнено на английском языке
