### ISSUE TITLE
Portfolio 1

### ISSUE THREAD

**Issue by MLitvinka** [rolling-scopes-school/support#422]
Добрый день! Прошлую неделю провалялся в кровати, у родных подтвержденный ковид, сам сдал тест только сегодня. Не могу сдать в срок Portfolio#1 , нуждаюсь приблизительно в 3х днях дополнительно. Можно ли это организовать? 
С уважениием Матвей Литвинка

**Comment by igorlyatskiy** [comment]
Покажете справку в лс админу, оформите апелляцию по правилам и можно
