### ISSUE TITLE
CV#3 Andrei Lanovskii

### ISSUE THREAD

**Issue by Lanowski** [rolling-scopes-school/support#424]
Добрый день! 

Я случайно создал аппил на свой CV через другую ссылку. 

Вот ссылка на мой аппил, подавал его в срок, но, к сожалению, не туда. Думал, что аппил нужно подавать через  Report a data issue. 

Аппил:
https://github.com/rolling-scopes/rsschool-app/issues/1116

CV :
https://htmlpreview.github.io/?https://github.com/Lanowski/rsschool-cv/blob/rsschool-cv-html/index.html
https://Lanowski.github.io/rsschool-cv/

Можете ли вы рассмотреть CV?

С уважением, 
Андрей

**Comment by ilyatskiy** [comment]
Оформите апелляцию как надо, в этом репозитории

**Comment by igorlyatskiy** [comment]
Оформи апелляцию по правилам
