### ISSUE TITLE
Cross-Check: Portfolio#1- 'AibekKen'

### ISSUE THREAD

**Issue by AibekKen** [rolling-scopes-school/support#425]
Доброго дня! 
Из за ситуации в Казахстане с интернетом не успел до дедлайна засабмитить задание  Portfolio#1. На один день опоздал. 

#### Вёрстка семантическая (20/20)
В коде странице присутствуют следующие элементы (указано минимальное количество, может быть больше):
 - [x] < header >, < main >, < footer > (2)
 - [x] шесть элементов <section>  (2)
 - [x] только один заголовок < h1 > (2)
 - [x] пять заголовков < h2 >  (2)
 - [x] один элемент <nav> (панель навигации) (2)
 - [x] два списка ul > li > a (панель навигации, ссылки на соцсети) (2)
 - [x] десять кнопок <button> (2)
 - [x] два инпута: <input type="email"> и <input type="tel"> (2)
 - [x] один элемент <textarea> (2)
 - [x] три атрибута placeholder (2)
#### Вёрстка соответствует макету (48/48)
 - [x] блок <header> (6)
 - [x] секция hero (6)
 - [x] секция skills (6)
 - [x] секция portfolio (6)
 - [x] секция video (6)
 - [x] секция price(6)
 - [x] секция contacts (6)
 - [x] блок <footer> (6)
#### Требования к css (12/12)
 - [x] для построения сетки используются флексы или гриды (2)
 - [x] при уменьшении масштаба страницы браузера вёрстка размещается по центру, а не сдвигается в сторону (2)
 - [x] фоновый цвет тянется на всю ширину страницы (2)
 - [x] иконки добавлены в формате .svg. SVG может быть добавлен любым способом. (2)
- [x] изображения добавлены в формате .jpg (2)
- [x] есть favicon (2)
- Интерактивность, реализуемая через css (20/20)
 - [x] плавная прокрутка по якорям (5)
 - [x] ссылки в футере ведут на гитхаб автора проекта и на страницу курса https://rs.school/js-stage0/ (5)
 - [x] интерактивность включает в себя не только изменение внешнего вида курсора, например, при помощи свойства cursor: pointer, но и другие визуальные эффекты, например, изменение цвета фона или цвета шрифта. Если в макете указаны стили при наведении и клике, для элемента указываем эти стили. Если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета (5)
- [x] обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике не влияющее на соседние элементы (5)

**Comment by viGITory** [comment]
+ Вёрстка валидная 10/10
+ Вёрстка семантическая 20/20
+ Вёрстка соответствует макету 48/48
+ Требования к css 12/12
+ Интерактивность, реализуемая через css 20/20

Итого: 110/100
