### ISSUE TITLE
Portfolio#1-Abylkhayir

### ISSUE THREAD

**Issue by Abylkhayir** [rolling-scopes-school/support#428]
Здравствуйте, как вы знаете из-за сложившихся обстоятельств в Казахстане, были определенные проблемы как с выполнением задания и также с его сдачей. Ввиду этих факторов, я старался в последние дни сделать пропущенные мною задания, однако проделать определенную работу еще предстоит. Прошу вас предоставить доступ на сдачу заданий в течении двух или трех дней, а именно:
Portfolio#1 - https://app.rs.school/course/entityDetails?course=js-fe-preschool&entityType=task&entityId=1188
CV#1. - Markdown & Git-https://app.rs.school/course/entityDetails?course=js-fe-preschool&entityType=task&entityId=1176
CV#2. HTML, CSS & Git Basics - https://app.rs.school/course/entityDetails?course=js-fe-preschool&entityType=task&entityId=1178
CV#3. CV. Cross Check - https://app.rs.school/course/entityDetails?course=js-fe-preschool&entityType=task&entityId=1309

Спасибо за внимание.

**Comment by igorlyatskiy** [comment]
Подавайте апелляции в общем порядке и указывайте причину.
