### ISSUE TITLE
Cross-Check Singolo - oddzye

### ISSUE THREAD

**Issue by oddzye** [rolling-scopes-school/support#43]
Ссылка на деплой вашего проекта - https://oddzye.github.io/singolo/singolo.html

Ссылка на репозиторий с проектом на GitHub - https://github.com/oddzye/singolo

Оценка в результате самопроверки, с ее аргументацией. 
Оценка - 74.
В корне репозитория нет файлjd index.html и style.css, они заменены на singolo.html и singolo.css. Возможно, я не прав, но ставить 0 за работу при несоблюдении этого требования - жестко. Старался сверстать pixel perfect, по мнению студентов, отклонение в каждей секции больше чем на 2px. Рассудите, пожалуйста. 
Если в коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020, -10.
Если в коммитах, или в ветках с коммитами, файлы singolo3.html и singolo3.сss или index.html и style.css отсутствуют до 09.03.2020,  -10.
Добавляем избыточный текст в текстовую ячейку (не заголовок), и если текст, выходящий за размеры не скрыт, ставим -3.
Четырех колоночный макет с изображениями должен иметь строгие отступы между элементами. Сами картинки, при этом, могут быть немного смещены. Важно, чтобы сетка полностью соотвествовала наложенному изображнию. Если сетка имеет неверные размеры или отступы, ставим -3.

Балл за cross-check из вашего Score - 46

**Comment by amoebiusss** [comment]
@oddzye привет! Ваша итоговая оценка по обновленному алгоритму — 73, что лишь на балл отличается от заявленной. Минимальная разница для апелляции — 15, поэтому закрываю ишью. Хорошего дня!
