### ISSUE TITLE
Portfolio 1

### ISSUE THREAD

**Issue by AndreiLazerko** [rolling-scopes-school/support#430]
https://rolling-scopes-school.github.io/andreilazerko-JSFEPRESCHOOL/portfolio/

Оценку снизили из-за валидности на 10, а проверка показала , что у меня все хорошо.
![Uploading Screenshot_20220120-123449_Samsung Internet.jpg…]()

**Comment by irinainina** [comment]
Апелляцию необходимо оформить согласно требованиям. предоставив скриншоты оценок всех проверяющих
