### ISSUE TITLE
Cross Check 'CV' - 'NikolayLuz'

### ISSUE THREAD

**Issue by NikolayLuz** [rolling-scopes-school/support#431]
Добрый вечер! В связи с ситуацией, которая была в Казахстане, не мог сделать необходимые задания до дедлайна. Прошу разрешить мне доступ к сдаче заданий: CV#1, CV#2, CV#3. Спасибо!

1. Deploy: https://nikolayluz.github.io/rsschool-cv/
             https://nikolayluz.github.io/rsschool-cv/cv
2. Repository: https://github.com/NikolayLuz/rsschool-cv
3. Tasks:  https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cvstage0.md#%D0%BA%D1%80%D0%B8%D1%82%D0%B5%D1%80%D0%B8%D0%B8-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8
4. Score 110/120
 - студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages +10
 - вёрстка валидная +5
 - вёрстка семантическая +15
    :header, main, footer +5
    :только один заголовок h1 +5
    :заголовки h2 +5
 - в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс +10
 - для оформления СV используются css-стили +10
 - при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону +10
 - на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt +10
 - навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a +10
 - Содержание CV +20
    :краткую информацию о себе +5
    :контакты для связи +5
    :перечень навыков +5
    :информацию об образовании и уровне английского +5
 - CV выполнено на английском языке +10

**Comment by viGITory** [comment]
+ студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 10/10
+ вёрстка валидная 5/10
    + Warning: Consider avoiding viewport values that prevent users from resizing documents.
    + Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.
+ вёрстка семантическая 15/20 (нет nav)
    + header, main, footer +5
    + только один заголовок h1 +5
    + заголовки h2 +5
+ в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс 10/10
+ для оформления СV используются css-стили 10/10
+ при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 10/10
+ на странице СV есть фото или аватарка автора, пропорции изображения не искажены, у изображения есть атрибут alt 10/10
+ навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a 10/10
+ Содержание CV 20/30 (нет примеров кода и проектов)
    + краткую информацию о себе +5
    + контакты для связи +5
    + перечень навыков +5
    + информацию об образовании и уровне английского +5
+ CV выполнено на английском языке +10

**Comment by igorlyatskiy** [comment]
CV#3 выставил
