### ISSUE TITLE
Cross-Check 'Portfolio#1' - 'Der-thun'

### ISSUE THREAD

**Issue by Der-thun** [rolling-scopes-school/support#433]
1. https://rolling-scopes-school.github.io/der-thun-JSFEPRESCHOOL/portfolio/
2. https://github.com/rolling-scopes-school/der-thun-JSFEPRESCHOOL/tree/gh-pages
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1.md
4. https://portfolio-part1-check-list.netlify.app/
5. 
![image](https://user-images.githubusercontent.com/75979865/150475868-5a58838c-1746-49f7-8e81-461b409af16e.png)
6.
-иконки в футере в списке 
-текст кнопки Autumn  действительно не меняется
-отсутствие горизонтальной прокрутки не было в требованиях задания
-заданием не запрещено использование абсолютного позиционирования и не оговорено количество его использования
-заданием является фиксированная верстка, я обязан был использовать css свойства из фигмы
Моя самооценка: 100
7. Балл из Score: 83

**Comment by WiiJoy** [comment]
Привет! Все на месте, замечаний никаких.
100/100
