### ISSUE TITLE
Cross-Check 'Portfolio#1' - 'Laroikin'

### ISSUE THREAD

**Issue by Laroikin** [rolling-scopes-school/support#434]
1. https://rolling-scopes-school.github.io/laroikin-JSFEPRESCHOOL/portfolio/
2. https://github.com/rolling-scopes-school/laroikin-JSFEPRESCHOOL
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1.md
4. https://portfolio-part1-check-list.netlify.app/
5. <img width="1424" alt="Снимок экрана 2022-01-21 в 12 24 30" src="https://user-images.githubusercontent.com/48063190/150484258-8c66339e-0dd4-4e15-ab7f-7b27150c57e6.png">
6. Моя оценка: 100/100
-Верстка валидная
-Вёрстка семантическая (но есть не все из 10 тегов button)
-Верстка соответствует макету
-Все требования к css выполнены
-Интерактивность, реализуемая через css присутствует
Макет сверстан 1 к 1, при использовании расширения Perfect Pixel на разрешении 1440x900 различия между макетом и версткой не заметны.
7. Оценка из RS App: 88/100

**Comment by WiiJoy** [comment]
Ваша отметка - **105.5 балла(ов)**

Отзыв по пунктам ТЗ:

Частично выполненные пункты:
1) Вёрстка семантическая +20
Скрипт для проверки семантической вёрстки https://discord.com/channels/516715744646660106/536470834638880790/929454760417951794 
Скрипт выполняется в консоли и показывает выполняются ли требования по количеству добавленных тегов
Баллы за частично выполненные пункты нужно ввести вручную, автоматический подсчёт в этом пункте будет работать с ошибкой — 19 балл(а)
**Комментарий проверяющего: -1 балл: 5 button из 10 необходимых. Очень странное решение сделать из кнопок в hero и price ссылочные сущности, когда это явные кнопки по макету. Т.е. - балл только за счет того, что кнопочные сущности сделаны ссылочными, увы**
2) блок header — 5 балл(а)
**Комментарий проверяющего: -1 балл: неверное позиционирование в header за счет отсутствия боковых отступов (padding, к примеру).
в девтулс на 1440 все выглядит нормально, но все должно выглядеть нормально и в полноэкранном режиме на экранах с разрешением > 1440px :)**
3) блок footer — 5 балл(а)
**Комментарий проверяющего: -1 балл, аналогично блоку header**
4) интерактивность включает в себя не только изменение внешнего вида курсора, например, при помощи свойства cursor: pointer, но и другие визуальные эффекты, например, изменение цвета фона или цвета шрифта. Если в макете указаны стили при наведении и клике, для элемента указываем эти стили. Если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета — 3.5 балл(а)
**Комментарий проверяющего: Итак:
- очень не хватает cursor: pointer на кнопках в блоках portfolio, video и contacts;
- очень не хватает интерактивности на инпутах и textarea при входе в них;
- концептуально: макет предусматривает интерактивность для кнопки Play в блоке Video. Затемнение постера видео при наведении на постер - имхо, неправильная реализация. В данном случае, мне кажется, было бы правильнее (если хочется затемнять постер) производить это во время наведения мышки именно на кнопку.

С учетом всех этих мыслей я все же скину 1.5 балла**


Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.

Привет! Хорошая работа, но в некоторых моментах у тебя получилось самому же себе снизить баллы) (в случае с кнопками, например)
В любом случае, ты молодец, и итоговая оценка это показывает: 100 из 100. Так держать, но будь внимательнее с ТЗ :)
