### ISSUE TITLE
Cross-Check Portfolio#1 - ' vitalikhilinski'

### ISSUE THREAD

**Issue by VitaliKhilinski** [rolling-scopes-school/support#435]
1.  https://rolling-scopes-school.github.io/vitalikhilinski-JSFEPRESCHOOL/portfolio/ 
2. https://github.com/rolling-scopes-school/vitalikhilinski-JSFEPRESCHOOL
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1.md
4. https://portfolio-part1-check-list.netlify.app/
5. 
![image](https://user-images.githubusercontent.com/95978036/150502613-c086eeda-0788-4626-ba42-b77bbaa1847e.png)
6. Моя оценка: 100/100.
 -Вся верстка совпадает с макетом.
7. Оценка в RS APP: 90/100

**Comment by Bumble-sakh** [comment]
100 баллов

Частично выполненные пункты:
1) обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике не влияющее на соседние элементы — 2 балл(а)
Комментарий проверяющего: на иконках и кнопке видео есть transition, а на остальных кнопках отсутствует.

Комментарии к выполненным пунктам:
1) секция contacts
Комментарий проверяющего: В форме контактов нет затемнения полей ввода

Хорошая работа.
+ Использование и гридов и флексов.
