### ISSUE TITLE
Portfolio#1-FarAK10

### ISSUE THREAD

**Issue by FarAK10** [rolling-scopes-school/support#437]
1. Deploy  https://rolling-scopes-school.github.io/farak10-JSFEPRESCHOOL/portfolio/
2. Repo https://github.com/rolling-scopes-school/farak10-JSFEPRESCHOOL
3. Task https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1.md
4. Self-checked form https://portfolio-part1-check-list.netlify.app/
5. 
![image](https://user-images.githubusercontent.com/93331463/150542920-b892b9da-3a92-4bbc-99df-4736e561909e.png)
6. Good afternoon. I would like to say that from 110 balls my work deserve more than 99,5 balls because it meets all requirements. But these 2 students didnt check it properly(especially the last one ) and maybe counted my score wrongly. Im sure that you will check much more objectively. Thank for your support.
7. my score is  98

**Comment by WiiJoy** [comment]
Привет, хорошая работа!  Дотянула на максимальный балл :)

Все огрехи описал чуть ниже. Продолжай в том же духе и успехов!

Ваша отметка - **106 баллов** = 100 из 100
Отзыв по пунктам ТЗ:

Частично выполненные пункты:
1) Вёрстка семантическая +20
Скрипт для проверки семантической вёрстки https://discord.com/channels/516715744646660106/536470834638880790/929454760417951794 
Скрипт выполняется в консоли и показывает выполняются ли требования по количеству добавленных тегов
Баллы за частично выполненные пункты нужно ввести вручную, автоматический подсчёт в этом пункте будет работать с ошибкой — 19.5 балл(а)
Комментарий проверяющего: 9 кнопок из 10. 19.5/20

2) секция video — 4 балл(а)
Комментарий проверяющего: Видео не имеет отступов от края страницы = несоответствие размеру. 4/6
![Screenshot_8](https://user-images.githubusercontent.com/73646765/151314779-0fbea6e4-6100-485a-b5ca-a627b96e80f1.jpg)

3) интерактивность включает в себя не только изменение внешнего вида курсора, например, при помощи свойства cursor: pointer, но и другие визуальные эффекты, например, изменение цвета фона или цвета шрифта. Если в макете указаны стили при наведении и клике, для элемента указываем эти стили. Если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета — 4.5 балл(а)
Комментарий проверяющего: Не хватает pointer'ов в выборе языка и кнопке Play. 4.5/5

4) обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике не влияющее на соседние элементы — 4 балл(а)
Комментарий проверяющего: Часть интерактивных элементов не имеет плавной интерактивности (например, ссылка в RSS)

Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.
