### ISSUE TITLE
Апелляция по заданию Portfolio#1 - Khitraya

### ISSUE THREAD

**Issue by Khitraya** [rolling-scopes-school/support#438]
1. https://rolling-scopes-school.github.io/khitraya-JSFEPRESCHOOL/portfolio/
2. https://github.com/rolling-scopes-school/khitraya-JSFEPRESCHOOL
3.  https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1.md
4. https://portfolio-part1-check-list.netlify.app/
5. ![Снимок экрана 2022-01-21 205448](https://user-images.githubusercontent.com/77242826/150576424-4f3aa7ec-871f-4c1f-9b6a-f49f8c3427bf.png)
![Снимок экрана 2022-01-21 205516](https://user-images.githubusercontent.com/77242826/150576428-04acd4b3-fba5-4e9f-a1cb-9e3404e5efbb.png)
6.  Моя оценка 108/110. Оценки двух других студентов 108 и 110 соответственно.
Здравствуйте! Не согласна с оценкой моей работы студентом @arshawker.  За то, что не располагается по центру верстка согласно форме для кросс-чека снижается 2 балла. Частично он снял за интерактивность. За что конкретно остальные баллы (около 40) были списаны, не указано. При этом умышленно снижена оценка еще на 5 баллов, так как общую сумму студент указал в 65, а выставил 60. Сообщение ему лично отправлено было, однако по состоянию на 21.01. студент на связь не выходил.

**Comment by arshawker** [comment]
Здравствуйте, апелляцию принял. Мой косяк. Оценку исправил.
Но ни каких писем от студента не в телеграмме не на почту мне не приходило.
С уважением, Арслан.

пт, 21 янв. 2022 г., 19:03 Khitraya ***@***.***>:
