### ISSUE TITLE
Cross-Check 'portfolio#1 - Фиксированная вёрстка' - 'TanyaSummer'.

### ISSUE THREAD

**Issue by TanyaSummer** [rolling-scopes-school/support#439]
1. https://rolling-scopes-school.github.io/tanyasummer-JSFEPRESCHOOL/portfolio/
2. https://github.com/rolling-scopes-school/tanyasummer-JSFEPRESCHOOL
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1.md
4. https://portfolio-part1-check-list.netlify.app/
5. ![78465321,](https://user-images.githubusercontent.com/46902111/150588623-ac9963ef-9d93-4f21-b3fd-4dddb9b27e78.png)
6. 98
7. Ваша отметка - 98 балла(ов)
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) при уменьшении масштаба страницы браузера вёрстка размещается по центру, а не сдвигается в сторону

Частично выполненные пункты:
1) Вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований — 5 балл(а)
2) Вёрстка семантическая +20
Скрипт для проверки семантической вёрстки https://discord.com/channels/516715744646660106/536470834638880790/929454760417951794 
Скрипт выполняется в консоли и показывает выполняются ли требования по количеству добавленных тегов
Баллы за частично выполненные пункты нужно ввести вручную, автоматический подсчёт в этом пункте будет работать с ошибкой — 18 балл(а)
3) секция portfolio — 5 балл(а)
Комментарий проверяющего: нет эффекта активной кнопки
4) изображения добавлены в формате .jpg — 1 балл(а)
5) есть favicon — 1 балл(а)

Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.

8. 87

**Comment by viGITory** [comment]
Ваша отметка - 79 балла(ов)

Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
Комментарий проверяющего: Error: Attribute href not allowed on element button at this point (кнопка play на видео)

Частично выполненные пункты:
1) блок header — 3 балл(а)
Комментарий проверяющего: Расхождения больше 10px в навигации
2) секция hero — 4 балл(а)
Комментарий проверяющего: Неправильный перенос абзаца с текстом, расхождения больше 10px
3) секция skills — 3 балл(а)
Комментарий проверяющего: Нет полос у заголовка, неправильный перенос текста в Audio (расхождения больше 10px)
4) секция portfolio — 4 балл(а)
Комментарий проверяющего: Нет полос и неправильный размер шрифта у заголовка
5) секция video — 5 балл(а)
Комментарий проверяющего: Нет полос и неправильный размер шрифта у заголовка
6) секция price — 4 балл(а)
Комментарий проверяющего: Нет полос и неправильный размер шрифта у заголовка
7) секция contacts — 4 балл(а)
Комментарий проверяющего: Расхождения больше 10px в заголовке
8) блок footer — 2 балл(а)
Комментарий проверяющего: Расхождения больше 10px (год, гитхаб и ссылка на RSS)
9) изображения добавлены в формате .jpg — 1 балл(а)
Комментарий проверяющего: Фон в Contacts .png
10) обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике не влияющее на соседние элементы — 4 балл(а)
Комментарий проверяющего: Нет плавности на соцсетях


Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.
