### ISSUE TITLE
Cross-Check Singolo - marta-r

### ISSUE THREAD

**Issue by marta-r** [rolling-scopes-school/support#44]
Ссылка на деплой вашего проекта - https://marta-r.github.io/singolo/
Ссылка на репозиторий с проектом на GitHub - https://github.com/marta-r/singolo

У меня есть одна ошибка: Текст, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции About, (-3)
Все остальные снижения, на мой взгляд, не заслужены((

1. Ваша оценка - 74 балла 

Отзыв по пунктам ТЗ:

1) В Firefox есть сильное отклонение (т.е. бросается в глаза) от той же страницы, открытой в Google Chrome: минус -5 баллов 

2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Header составляют более двух пикселей (2px): минус -3 балла 

3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Slider составляют более двух пикселей (2px): минус -3 балла 

4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла 

5) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Portfolio составляют более двух пикселей (2px): минус -3 балла 

6) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла 

7) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла 

8) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Footer составляют более двух пикселей (2px): минус -3 балла 

2. Ваша оценка - 88 баллов 

Отзыв по пунктам ТЗ:

1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Header составляют более двух пикселей (2px): минус -3 балла 

2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла 

3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла 

4) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции Get a Quote: минус -3 балла 

3. Ваша оценка - 85 баллов 

Несовпадение на более чем 2px:

Блоки:

Our Services уплыл весь (-3)

Portfolio уплыл на 6 px (-3)

About плывет текст и иконки даже если выровнять на 6px(-3)

Footer -3

Get a Quote

Текст, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции About, (-3)

**Comment by amoebiusss** [comment]
@marta-r привет! Ваша итоговая оценка по обновленному алгоритму — 90, наименьшая оценка была исключена из подсчета. От заявленной она отличается на 7 баллов, минимальная разница для апелляции — 15.
