### ISSUE TITLE
Cross-Check "portfolio#1" - First-quantum-mind

### ISSUE THREAD

**Issue by First-quantum-mind** [rolling-scopes-school/support#440]
- Ссылка на деплой вашего проекта: https://rolling-scopes-school.github.io/first-quantum-mind-JSFEPRESCHOOL/portfolio/
- Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/first-quantum-mind-JSFEPRESCHOOL/tree/gh-pages
- Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1.md
- Ссылка на форму для проверки проекта: https://portfolio-part1-check-list.netlify.app/
- Скриншот с оценками за cross-check
![image](https://user-images.githubusercontent.com/78071146/150628689-63332987-68cf-4ab1-be0f-d53fcf885cee.png)
![image](https://user-images.githubusercontent.com/78071146/150628703-d52a67d8-4e7c-4a62-82e9-e2b879ae145f.png)
![image](https://user-images.githubusercontent.com/78071146/150631620-33b93bc9-465f-4ed2-87fc-a9c8bc2a4d16.png)
- Оценка в результате самопроверки  Score: 85. У Студента №3 не начислен score. ПРОСТО НАЗНАЧЬТЕ мне Score 3 cтудента и ВСЕ.  
- Балл за cross-check из вашего Score: 57  
![image](https://user-images.githubusercontent.com/78071146/150628800-dd98b3bf-60a0-4c16-85b1-de2b851cba7f.png)

**Comment by WiiJoy** [comment]
Привет, проверка в любом случае должна быть полная, и на ее основе будет производиться итоговое изменение (или неизменение) вашей оценки в score.

У вас действительно хорошая работа, но есть еще над чем поработать дальше) Продолжайте в том же духе и успехов в обучении!

Ваша отметка - **Math.ceil(84.5) баллов**

Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
Комментарий проверяющего: Проверка выдает 5 warnings и 5 errors, ругается на дубликаты id, чего быть в принципе не должно
![Screenshot_1](https://user-images.githubusercontent.com/73646765/151312380-c050848a-31c5-467b-877b-872ad97ddd6f.jpg)

2) обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике не влияющее на соседние элементы
Комментарий проверяющего: Плавность интерактивности не реализована, увы

Частично выполненные пункты:
1) Вёрстка семантическая +20
Скрипт для проверки семантической вёрстки https://discord.com/channels/516715744646660106/536470834638880790/929454760417951794 
Скрипт выполняется в консоли и показывает выполняются ли требования по количеству добавленных тегов
Баллы за частично выполненные пункты нужно ввести вручную, автоматический подсчёт в этом пункте будет работать с ошибкой — 18.5 балл(а)
Комментарий проверяющего: Скрипт обозначил 14 баллов.
Незасчитанные пункты:
+0 score for "nav"
+0 score for "header ul/footer ul"
+0 score for "main button,header button,footer button"
Навигация: есть, баллы в полном объеме. 2/2
Списки: в навигации есть, в соцсетях нет. 1/2
Кнопки: 9 из 10. 1.5/2
Итого за пункт 18.5 баллов

2) блок header — 5 балл(а)
Комментарий проверяющего: Несколько не до конца спозиционирована навигация, но каких-то критичностей не вижу. 5/6
![Screenshot_2](https://user-images.githubusercontent.com/73646765/151312431-377f07a0-2518-46af-b3aa-545c6348fb14.jpg)

3) секция skills — 5 балл(а)
Комментарий проверяющего: 16 пикселей разница в позиции второго скила. 5/6
![Screenshot_4](https://user-images.githubusercontent.com/73646765/151312487-cafe0cb9-0d5b-4158-9d5d-4ddac94fdba8.jpg)

4) секция portfolio — 5 балл(а)
Комментарий проверяющего: Следует поколдовать с отступами в изображениях портфолио. 5/6
![Screenshot_5](https://user-images.githubusercontent.com/73646765/151312508-521e4938-6795-4ad6-9eb7-5d08b07cc4eb.jpg)

5) секция contacts — 4 балл(а)
Комментарий проверяющего: Достаточно сильная разница, увы. 4/6
![Screenshot_6](https://user-images.githubusercontent.com/73646765/151312522-f3812a61-5bca-4849-b501-3260bab18d40.jpg)

6) блок footer — 4 балл(а)
Комментарий проверяющего: Аналогично в футере - большая разница в позиционировании. 4/6
![Screenshot_7](https://user-images.githubusercontent.com/73646765/151312545-864d4ef3-2f46-4dd5-b7ef-c48f6a68730c.jpg)

7) ссылки в футере ведут на гитхаб автора проекта и на страницу курса https://rs.school/js-stage0/ — 4 балл(а)
Комментарий проверяющего: Ссылки есть, но ведут не туда. Снял 1 балл за это.
Ссылка c github должна вести на ваш профиль github, а ссылка с RSS - на страницу https://rs.school/js-stage0/

8) интерактивность включает в себя не только изменение внешнего вида курсора, например, при помощи свойства cursor: pointer, но и другие визуальные эффекты, например, изменение цвета фона или цвета шрифта. Если в макете указаны стили при наведении и клике, для элемента указываем эти стили. Если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета — 4 балл(а)
Комментарий проверяющего: Для кнопок не хватает pointer'a, нет интерактивности у языка сайта

Комментарии к выполненным пунктам:

1) секция hero
Комментарий проверяющего: Разница 7 пикселей - а это в пределах нормы. Но я бы все равно немного пошаманил с выравниванием)
![Screenshot_3](https://user-images.githubusercontent.com/73646765/151312469-6dfc7d61-926e-4411-b240-547f90f17b20.jpg)

Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.
