### ISSUE TITLE
Cross-Check Portfolio 1 - Nabarouski

### ISSUE THREAD

**Issue by Nabarouski** [rolling-scopes-school/support#442]
1. Deploy: https://nabarouski-portfolio1.netlify.app/
2. Github: https://github.com/rolling-scopes-school/nabarouski-JSFEPRESCHOOL/tree/main
3.  Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1-hints.md
4. Cross-Check Form: https://portfolio-part1-check-list.netlify.app/
5.
![Снимок веб-страницы_22-1-2022_204131_app rs school](https://user-images.githubusercontent.com/72649286/150649706-3a71fb8e-2384-47ad-8921-e5ae3074db28.jpeg)
![Снимок веб-страницы_22-1-2022_204317_app rs school](https://user-images.githubusercontent.com/72649286/150649716-f298bfd5-6877-4378-84fc-f713c98a4a30.jpeg)
![Снимок веб-страницы_22-1-2022_204526_app rs school](https://user-images.githubusercontent.com/72649286/150649721-11bdad6a-965b-4cf3-b674-6c0e40072ac5.jpeg)
6. Пункты с которыми я не согласен, выделил красным цветом. 
В ТЗ (https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1-hints.md) ничего не написано про footer и про ссылки в нем, и что он должен быть оформлен с помощью списка ul/li. Footer я сделал, но ссылки не добавлял, и сделал через span. Также в секции Contacts я ввел заголовок h3 (на мой взгляд там шрифт меньше чем в предыдущих секциях), т.к. в ТЗ ничего не было написано про h2  в секции Contacts. Прошу перепроверить мою работу. Моя оценка 75+.
Оценка в score 65.
Спасибо.

**Comment by WiiJoy** [comment]
Привет! По итогам проверки я пришел к выводу, что проставленная итоговая текущая оценка - актуальная и справедливая. Работа хорошая, но, увы, в ней присутствует достаточно огрехов, и часть из них - то ли невнимательность, то ли нежелание следовать конкретному ТЗ.

Я постарался максимально наглядно отобразить, что не так. Надеюсь, это будет полезно и в будущем ты будешь чуточку внимательнее относиться к требованиям.

Успехов в дальнейшем обучении, не останавливайся на достигнутом!

Ваша отметка - **66 баллов**

Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
Комментарий проверяющего: Не выполнено, выпадает 4 error.
Проблема в обертке h2 внутрь span - такого быть не должно
![Screenshot_1](https://user-images.githubusercontent.com/73646765/151302586-721382cb-51c1-4190-85d3-a9deb6b2b3e2.jpg)

2) фоновый цвет тянется на всю ширину страницы
Комментарий проверяющего: Нет фонового цвета, который должен покрывать все свободную от верстки область приложения.
![Screenshot_10](https://user-images.githubusercontent.com/73646765/151302614-97fe0c2b-a984-4924-9c60-081132510ab9.jpg)

3) ссылки в футере ведут на гитхаб автора проекта и на страницу курса https://rs.school/js-stage0/
Комментарий проверяющего: Нет ссылок в футере на указанные ресурсы
![Screenshot_11](https://user-images.githubusercontent.com/73646765/151302640-64bc4714-a900-4fac-bb0b-8251d6dd931f.jpg)

Частично выполненные пункты:
1) Вёрстка семантическая +20
Скрипт для проверки семантической вёрстки https://discord.com/channels/516715744646660106/536470834638880790/929454760417951794 
Скрипт выполняется в консоли и показывает выполняются ли требования по количеству добавленных тегов
Баллы за частично выполненные пункты нужно ввести вручную, автоматический подсчёт в этом пункте будет работать с ошибкой — 16 балл(а)
Комментарий проверяющего: По скрипту проверки получилось 10 баллов. Незачтенные элементы:
+0 score for "h2"
+0 score for "header ul/footer ul"
+0 score for "main button,header button,footer button"
+0 score for "input[type="email"]/input[type="tel"]"
+0 score for "input, textarea[placeholder]"
Давай проверять ручками.
Заголовки: 4 h2 из 5 необходимых. Решение сделать h3 вместо одного h2 - твое собственное, но в первую очередь (обращаю внимание здесь и не буду возвращаться к этому в последующих комментариях) необходимо выполнить требования ТЗ. В них четко прописано, что должно быть 5 заголовков h2 - от этого мы и прыгаем :) 1.5/2
Списки: по ТЗ должно быть 2 списка: один - навигация в header (есть), второй - соцсети в футере (его нет). 1/2
Кнопки: должно быть 10 кнопок, из них сделаны только 9. 1.5/2
Инпуты: не выполнено, тк вместо инпутов с соответствующими типами установлены textarea. 0/2
textarea: не снижаю, тк как минимум там. где он должен быть, он есть. 2/2
Итого за пункт получаем 16 баллов

2) блок header — 4 балл(а)
Комментарий проверяющего: Белая полоса над header, несоответствие шрифта и его размера в навигации. 4/6
Заголовки - serif, остальной контент - sans-serif. Не путать :)
![Screenshot_2](https://user-images.githubusercontent.com/73646765/151302883-1dc504ae-73d9-411d-8790-61da060bb261.jpg)

3) секция hero — 3 балл(а)
Комментарий проверяющего: Позиционирование и шрифты не соответствуют макету. 3/6
![Screenshot_3](https://user-images.githubusercontent.com/73646765/151302908-90d91e6c-6e2b-45e4-bdf8-9e80f2cc0f6b.jpg)

4) секция skills — 3 балл(а)
Комментарий проверяющего: Несоответствие шрифтов в тайтле секции и описаний скилов, несоответствие длины палочек, общее позиционирование контента. 3/6
![Screenshot_4](https://user-images.githubusercontent.com/73646765/151302924-5268e93d-cdc0-4001-890e-8d53bae7340f.jpg)

5) секция portfolio — 3 балл(а)
Комментарий проверяющего: Опять же, позиционирования и, видимо, высоты блоков.
При выравнивании макета по первой линии картинок портфолио, вторая линия не попадает в макет по размеру. 3/6
![Screenshot_5](https://user-images.githubusercontent.com/73646765/151302952-9a3c823e-cb72-4905-9604-492a4bbf1b91.jpg)

6) секция video — 3 балл(а)
Комментарий проверяющего: Для проверки позволил себе выравнять по постеру видео для наглядности: разница в позиционировании кнопки Play и отступе между заголовком и постером. Учитывая объем работ в сравнении с объемом самого блока - 3/6
![Screenshot_6](https://user-images.githubusercontent.com/73646765/151302980-d65f3ad7-56a5-45a6-ae38-90556385cb9a.jpg)

7) секция price — 4 балл(а)
Комментарий проверяющего: Аналогично, проблемы с общим позиционированием. 4/6
![Screenshot_7](https://user-images.githubusercontent.com/73646765/151303078-ad855fc3-0a86-42db-ba5d-34ceef723f32.jpg)

8) секция contacts — 4 балл(а)
Комментарий проверяющего: Сделал выравнивание по фону для наглядности. Достаточно поиграться с отступами между блоков (и высотой инпутов, которые должны быть инпутами) - и в принципе все встанет на свои места. 4/6
![Screenshot_8](https://user-images.githubusercontent.com/73646765/151303091-d5fd67b8-9fa9-4102-b2fc-f281eed9d621.jpg)

9) блок footer — 5 балл(а)
Комментарий проверяющего: Критично различие в позиционировании только у соцсетей, остальное в пределах нормы. 5/6
![Screenshot_9](https://user-images.githubusercontent.com/73646765/151303101-a23c0567-e306-46b6-bd49-16aadee16ae0.jpg)

10) интерактивность включает в себя не только изменение внешнего вида курсора, например, при помощи свойства cursor: pointer, но и другие визуальные эффекты, например, изменение цвета фона или цвета шрифта. Если в макете указаны стили при наведении и клике, для элемента указываем эти стили. Если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета — 4 балл(а)
Комментарий проверяющего: 4 балла из 5: неверная отработка hover'а на кнопке Play: сама иконочка кнопки должна менять цвет, а не задаваться background кнопки
11) обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике не влияющее на соседние элементы — 2 балл(а)
Комментарий проверяющего: 2 балла за старание: плавность есть только в header

Комментарии к выполненным пунктам:

1) для построения сетки используются флексы или гриды
Комментарий проверяющего: Выполнено, но я бы посоветовал не писать стили в html, а оформлять их отдельным css файлом и уже его подключать в html

Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.
