### ISSUE TITLE
Cross-Check 'portfolio#1' - 'farizaten6'

### ISSUE THREAD

**Issue by farizaten6** [rolling-scopes-school/support#444]
1. https://rolling-scopes-school.github.io/farizaten6-JSFEPRESCHOOL/portfolio/
2. https://github.com/rolling-scopes-school/farizaten6-JSFEPRESCHOOL
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1.md
4. https://portfolio-part1-check-list.netlify.app/
5. Score: 106 / 110
пункты выполненные не до конца:
> иконки добавлены в формате .svg. SVG может быть добавлен любым способом. Обращаем внимание на формат, а не на способ добавления
> изображения добавлены в формате .jpg
6. На данный момент Score = 0,  тк дедлайн для Казахстана был сдвинут на неделю из-за отключений интернета в стране в период с 05.01.2022 до 11.01.2022

**Comment by WiiJoy** [comment]
Привет! Хорошая работа, но в ней присутствует достаточно много мелких недочетов, которые, увы, повлияли и на итоговую оценку.

Я постарался максимально наглядно показать, что не так. Тебе же пожелание - продолжай совершенствовать свои навыки и, самое главное, практиковаться! Успехов!

Ваша отметка - Math.ceil(82.4) = **83 балла**

Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) фоновый цвет тянется на всю ширину страницы
Комментарий проверяющего: Не выполнено, тк фоновый цвет (черный по макету) на всем свободном пространстве отсутствует
![Screenshot_35](https://user-images.githubusercontent.com/73646765/151295697-7fe39f7a-561f-4af6-84b2-6a5361fbaba4.jpg)

Частично выполненные пункты:
1) Вёрстка семантическая +20
Скрипт для проверки семантической вёрстки https://discord.com/channels/516715744646660106/536470834638880790/929454760417951794 
Скрипт выполняется в консоли и показывает выполняются ли требования по количеству добавленных тегов
Баллы за частично выполненные пункты нужно ввести вручную, автоматический подсчёт в этом пункте будет работать с ошибкой — 18.5 балл(а)
Комментарий проверяющего: Скрипт показал 16 баллов.
+0 score for "header ul/footer ul"
+0 score for "main button,header button,footer button"
По спискам - 1 балл есть, тк в header навигация сделана списком. За список соцсетей минус, на момент проверки реализовано дивами.
По кнопкам - насчитал 9 из 10 необходимых, так что +1.5 балла в копилку.
Итого за пункт 18.5 баллов

2) блок header — 3 балл(а)
Комментарий проверяющего: Нет лого, несоответствие в позиционировании навигации. Над header белая полоса. 3/6
![Screenshot_29](https://user-images.githubusercontent.com/73646765/151295786-8fd9fa8d-ddaa-400d-ba65-cbcfb96340a6.jpg)

3) секция hero — 4 балл(а)
Комментарий проверяющего: Стоило чуть поиграться с отступами, тк структура более-менее такая, но сдвиг явно больше 10 пикселей (кстати, и с выравниванием фона я бы тоже поигрался). 4/6
![Screenshot_28](https://user-images.githubusercontent.com/73646765/151295822-cde05636-f4d7-4ffe-a1b6-48139cf8cd61.jpg)

4) секция skills — 3 балл(а)
Комментарий проверяющего: Есть явный перекос в высоте элементов + палочки заголовка доходят до самого заголовка. 3/6
За что не снижал: на скрине видно, что для выравнивания блока по тайтлу пришлось поднять макет на 24px. В идеале поставленный макет на твой сайт должен совпадать от макушки до самого подвала)
![Screenshot_30](https://user-images.githubusercontent.com/73646765/151295831-4075d9a0-b1ba-4a1b-9fff-a92ad5cb0ed4.jpg)

5) секция portfolio — 5 балл(а)
Комментарий проверяющего: Те же палочки в заголовке + несколько не соответствуют размеры самих изображений макету. Не критично, но за все -1. 5/6
![Screenshot_31](https://user-images.githubusercontent.com/73646765/151295841-24a85908-335b-4aad-88ef-f2e08a0bbcd1.jpg)

6) секция video — 5.5 балл(а)
Комментарий проверяющего: Здесь вопросов нет, все совпадает, кроме палочек у тайтла секции. 5.5/6

7) секция price — 4 балл(а)
Комментарий проверяющего: Черточки у тайтла + непопадание в размеры блоков. 4/6
![Screenshot_32](https://user-images.githubusercontent.com/73646765/151295863-ec97eca7-0add-4700-8029-f2df67a0515a.jpg)

8) секция contacts — 3 балл(а)
Комментарий проверяющего: Выравнил секцию по картинке, результат критичен. Непопадание в размеры и положение. 3/6
![Screenshot_33](https://user-images.githubusercontent.com/73646765/151295873-8026ee64-c010-4dfb-951e-25b34a9e151a.jpg)

9) блок footer — 4 балл(а)
Комментарий проверяющего: В футере тоже не гладко с позиционированием. 4/6
Общей ошибкой здесь и выше видится в недостаточных боковых отступах контейнера в целом. А дальше - чудеса пэддингов и мержинов :)
![Screenshot_34](https://user-images.githubusercontent.com/73646765/151295885-017ecf7b-0eb2-4af4-a2ee-211e21c1c608.jpg)

10) иконки добавлены в формате .svg. SVG может быть добавлен любым способом. Обращаем внимание на формат, а не на способ добавления — 1 балл(а)
Комментарий проверяющего: Выполнено на 50% - иконки блока skills не в svg, иконки в header нет вообще

11) изображения добавлены в формате .jpg — 1.9 балл(а)
Комментарий проверяющего: Фон Contacts в png :)
Прям рррр. Сниму 0.1 балла за этот вопиющий случай

12) интерактивность включает в себя не только изменение внешнего вида курсора, например, при помощи свойства cursor: pointer, но и другие визуальные эффекты, например, изменение цвета фона или цвета шрифта. Если в макете указаны стили при наведении и клике, для элемента указываем эти стили. Если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета — 2 балл(а)
Комментарий проверяющего: Поставлю половину баллов из возможного, тк pointer в принципе почти везде есть. Очень не хватает hover-эффектов, особенно для текстовых интерактивных элементов (навигация, ссылки в футере), у кнопок в портфолио, у кнопки в видео

13) обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике не влияющее на соседние элементы — 1 балл(а)
Комментарий проверяющего: Балл за попытку (в навигации есть transition), но оно не работает. Советую еще немного попрактиковаться с этим свойством)

Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.
