### ISSUE TITLE
Cross-Check 'Portfolio#1' - 'SviridovaElena'.

### ISSUE THREAD

**Issue by SviridovaElena** [rolling-scopes-school/support#449]
1.  https://sviridovaelena-jsfepreschool-portfolio1.netlify.app.
2. Repo: https://rolling-scopes-school.github.io/sviridovaelena-JSFEPRESCHOOL/
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1.md
4. Form: https://portfolio-part1-check-list.netlify.app/
5. Score: Ваша отметка - 100 балла(ов)

 пожалуйста, проверьте! не успела засабмитить по болезни( виновата! исправлюсь!
Прошлую апелляцию написала  некорректно((( Заранее огромное спасибо за потраченное время!

**Comment by viGITory** [comment]
Ваша отметка - 78 балла(ов)

Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике не влияющее на соседние элементы

Частично выполненные пункты:
1) Вёрстка семантическая +20
Скрипт для проверки семантической вёрстки https://discord.com/channels/516715744646660106/536470834638880790/929454760417951794 
Скрипт выполняется в консоли и показывает выполняются ли требования по количеству добавленных тегов
Баллы за частично выполненные пункты нужно ввести вручную, автоматический подсчёт в этом пункте будет работать с ошибкой — 14 балл(а)
2) секция hero — 4 балл(а)
Комментарий проверяющего: Неправильный перенос слов, расхождения больше 10px
3) секция skills — 1 балл(а)
Комментарий проверяющего: Расхождения больше 10px
4) секция portfolio — 1 балл(а)
Комментарий проверяющего: Расхождения больше 10px
5) секция price — 4 балл(а)
Комментарий проверяющего: Неправильный размер шрифта у заголовков карточек, расхождения больше 10px
6) секция contacts — 5 балл(а)
Комментарий проверяющего: Нет placeholder у textarea
7) изображения добавлены в формате .jpg — 1 балл(а)
Комментарий проверяющего: Все фотографии в секции Portfolio .png
8) плавная прокрутка по якорям — 4 балл(а)
Комментарий проверяющего: Нет якоря на секцию Video
9) ссылки в футере ведут на гитхаб автора проекта и на страницу курса https://rs.school/js-stage0/ — 2 балл(а)
Комментарий проверяющего: Нет ссылки на RSSchool
10) интерактивность включает в себя не только изменение внешнего вида курсора, например, при помощи свойства cursor: pointer, но и другие визуальные эффекты, например, изменение цвета фона или цвета шрифта. Если в макете указаны стили при наведении и клике, для элемента указываем эти стили. Если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета — 3 балл(а)
Комментарий проверяющего: Нет cursor: pointer на кнопках в секциях hero, portfolio, video, contacts

Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.

**Comment by SviridovaElena** [comment]
Большое спасибо!!!
