### ISSUE TITLE
Cross-Check Singolo - CRiDL189

### ISSUE THREAD

**Issue by CRiDL189** [rolling-scopes-school/support#45]
Ссылка на деплой: (https://cridl189.github.io/singolo/)

Ссылка на репозиторий с проектом: (https://github.com/CRiDL189/singolo)

Я проверила свою работу по чек-листу, получилось 100 баллов.
Не согласна со следующими пунктами проверяющего:
Студент 3
Singolo 2 сделан после дедлайна -10
Singolo 3 сделан после дедлайна -10 
Хедер: Размер шрифта навигации отличается -3
Сервис: Расстояние между заголовком и текстом отличается -3
Портфолио: Отступы отличаются -3
Общий балл: 71

**Comment by Sannnao** [comment]
Идеальная работа! 100 баллов
