### ISSUE TITLE
Cross-Check 'Portfolio2' - 'jushetcon'.

### ISSUE THREAD

**Issue by jushetcon** [rolling-scopes-school/support#451]
1.Deploy: https://rolling-scopes-school.github.io/jushetcon-JSFEPRESCHOOL/portfolio/
2.GitHub: https://github.com/rolling-scopes-school/jushetcon-JSFEPRESCHOOL/tree/gh-pages
3.Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part2.md
4.Cross-Check-Form: https://portfolio-part2-check-list.netlify.app/
5.
![image](https://user-images.githubusercontent.com/71011625/151446092-62872b7f-57d2-45e1-96bd-1ecf1368f876.png)

Оценка в результате самопроверки с ее аргументацией. 50/75 
![image](https://user-images.githubusercontent.com/71011625/151446502-0c1223e8-1fca-464e-a4be-a2a49b5dd20f.png)

**Comment by WiiJoy** [comment]
Привет! Это было сложно (с учетом выполнения третьей части портфолио), но я постарался максимально вернуться к состоянию второй части и на этом произвести проверку.

Основные проблемы - нереализованное адаптивное меню (есть заготовка бургера только) и действительно большие проблемы с адаптивностью :)

Надеюсь, мои комментарии окажутся чем-либо полезными.

Удачи в дальнейшем обучении и не останавливайся на достигнутом!

**Ваша отметка - 50 балла(ов)**

Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) при нажатии на бургер-иконку справа плавно появляется адаптивное меню, бургер-иконка изменяется на крестик
Комментарий проверяющего: Меню не выезжает при клике на место бургера

2) высота адаптивного меню занимает всю высоту экрана. При ширине экрана 768-620рх вёрстка меню соответствует макету, когда экран становится уже, меню занимает всю ширину экрана
Комментарий проверяющего: Нет возможности проверить, тк нет меню

3) при нажатии на крестик адаптивное меню плавно скрывается уезжая за правую часть экрана, крестик превращается в бургер-иконку
Комментарий проверяющего: Нет возможности проверить, тк нет меню

4) бургер-иконка, которая при клике превращается в крестик, создана при помощи css-анимаций без использования изображений
Комментарий проверяющего: Нет возможности проверить, тк нет меню

5) ссылки в адаптивном меню работают, обеспечивая плавную прокрутку по якорям
Комментарий проверяющего: Нет возможности проверить, тк нет меню

6) при клике по ссылке в адаптивном меню адаптивное меню плавно скрывается, крестик превращается в бургер-иконку
Комментарий проверяющего: Нет возможности проверить, тк нет меню

Частично выполненные пункты:
1) блок header — 3.5 балл(а)
Комментарий проверяющего: Полтора балла за несовпадающий бургер
<img width="874" alt="Снимок экрана 2022-02-04 в 12 22 19" src="https://user-images.githubusercontent.com/73646765/152506775-4e81b2d0-e4e4-4da1-a7e1-9f395272c28c.png">

2) секция price — 4.5 балл(а)
Комментарий проверяющего: Минус полбалла: несоответствие позиционирования блоков больше 10px: стоит немножко поиграть с отступами :)
<img width="822" alt="Снимок экрана 2022-02-04 в 12 23 32" src="https://user-images.githubusercontent.com/73646765/152506804-e8fc68a3-a442-4c38-befe-a24f21658a1c.png">

3) секция contacts — 4 балл(а)
Комментарий проверяющего: В контактах тоже не все гладко, но скину только 1 балл, тк критичное различие только у блока message
<img width="812" alt="Снимок экрана 2022-02-04 в 12 25 23" src="https://user-images.githubusercontent.com/73646765/152507017-aa7fbad9-386a-44e3-9d07-2a9f3c134759.png">

4) блок footer — 4 балл(а)
Комментарий проверяющего: Стоит немного поиграться с размерами и позиционированием ссылки на школу и позиционированием социальных сетей
<img width="867" alt="Снимок экрана 2022-02-04 в 12 26 32" src="https://user-images.githubusercontent.com/73646765/152507018-8c6039ce-5e1d-4358-9ace-df6743fa9212.png">

5) нет полосы прокрутки при ширине страницы от 1440рх до 768рх — 2 балл(а)
Комментарий проверяющего: Ставлю половину баллов:
до 1000px верстка разрушается (секция price не адаптивится), с 1000px до 769 включительно пропадает языковая панель
<img width="1312" alt="Снимок экрана 2022-02-04 в 12 27 57" src="https://user-images.githubusercontent.com/73646765/152507057-59705f03-b157-4b67-b37f-b791096045f4.png">
<img width="1042" alt="Снимок экрана 2022-02-04 в 12 30 21" src="https://user-images.githubusercontent.com/73646765/152507081-4fc69e2c-9d90-44e3-8984-9ef05078f33f.png">

6) нет полосы прокрутки при ширине страницы от 768рх до 480рх — 3 балл(а)
Комментарий проверяющего: Скину 2 балла за header, который разрастается из-за языковой панели, и который не вмещается на разрешениях ниже 600px
<img width="783" alt="Снимок экрана 2022-02-04 в 12 32 56" src="https://user-images.githubusercontent.com/73646765/152507124-ee5d5c10-7bb1-4637-9856-9b09dca54547.png">
<img width="698" alt="Снимок экрана 2022-02-04 в 12 43 34" src="https://user-images.githubusercontent.com/73646765/152507277-a15bd23b-783e-46ca-979d-322a1679c005.png">

7) нет полосы прокрутки при ширине страницы от 480рх до 320рх — 3 балл(а)
Комментарий проверяющего: Минус 2 балла за аналогичную ситуацию с header и hero
<img width="448" alt="Снимок экрана 2022-02-04 в 12 43 45" src="https://user-images.githubusercontent.com/73646765/152507290-c4a944e7-eac2-4080-b76d-d3002c7cd2ee.png">

8) при ширине страницы 768рх панель навигации скрывается, появляется бургер-иконка — 1.5 балл(а)
Комментарий проверяющего: Выполнено частично, тк панель навигации скрывается, но бургер-иконка полноценно не реализована


Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.
