### ISSUE TITLE
Cross-Check 'portfolio#2' - 'SerhiiKolliev'

### ISSUE THREAD

**Issue by SerhiiKolliev** [rolling-scopes-school/support#453]
Deploy: https://rolling-scopes-school.github.io/serhiikolliev-JSFEPRESCHOOL/portfolio/
Repo: https://github.com/rolling-scopes-school/serhiikolliev-JSFEPRESCHOOL
Task link: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part2-hints.md
Cross-check form: https://portfolio-part2-check-list.netlify.app
Screenshots: 
![1](https://user-images.githubusercontent.com/95614269/151537093-b9d86bf4-4caa-4a70-a15a-6bfd819b43c1.png)
![2](https://user-images.githubusercontent.com/95614269/151537106-75e77666-c484-453c-b1cd-48d79073536f.png)

Претензия по большей части не к низким оценкам (я с ними согласен), а к тому, что данные анонимные студенты не сочли нужным комментировать мои ошибки, а это прямое нарушение правил Cross-check. Я хотел бы услышать рекомендации, но получил наплевательски поставленную оценку. 
Балл за cross-check из вашего Score: 39

**Comment by igorlyatskiy** [comment]
Студенты не обязаны комментировать ошибки

**Comment by SerhiiKolliev** [comment]
> Ответственность за отсутствие комментария, поясняющего причину снижения баллов во время cross-check проверки.

Ок, я понял
