### ISSUE TITLE
Cross-Check 'portfolio#2' - 'Ruper23'

### ISSUE THREAD

**Issue by Ruper23** [rolling-scopes-school/support#455]
1. https://rolling-scopes-school.github.io/ruper23-JSFEPRESCHOOL/portfolio/
2. https://github.com/rolling-scopes-school/ruper23-JSFEPRESCHOOL
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part2.md
4. https://portfolio-part2-check-list.netlify.app/
5. ![app rs school](https://user-images.githubusercontent.com/64148185/151556989-fafa8259-2f8e-4693-91e3-52c09f55ff9f.png)
6. Ваша отметка - 81 балла(ов)
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) при клике по ссылке в адаптивном меню адаптивное меню плавно скрывается, крестик превращается в бургер-иконку (но уже исправлено)
Все оставшиеся пункты выполнены.
7. По итогу кросс-чека 68 баллов

**Comment by valerydluski** [comment]
Производится только если ожидаемый вами балл и полученный средний балл отличаются на 10 и более процентов.

**Comment by Ruper23** [comment]
не справедливо! 9+ %
