### ISSUE TITLE
Cross-Check -  'portfolio#2' - 'yuliabalkiss'

### ISSUE THREAD

**Issue by yuliabalkiss** [rolling-scopes-school/support#456]
Добрый день. У меня сложилась такая ситуация, что мне пришлось лечь  на операцию и я не успела  полностью выполнить таsk portfolio#2. Заранее я узнавала в дискорде, могут ли мне пойти на встречу и перенести дедлайн по таску на несколько дней, так как сложилась такая ситуация у меня. @igorlyatskiy ответил, что можно через апелляцию.(справку я ему скриншотом предоставляла). Задание доделала, как смогла. Если есть возможность проверить, буду очень благодарна. Спасибо!

1.Deploy:  https://rolling-scopes-school.github.io/yuliabalkiss-JSFEPRESCHOOL/portfolio/
2.GitHub. repo: https://github.com/rolling-scopes-school/yuliabalkiss-JSFEPRESCHOOL
3.Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part2.md
4.Cross-check screenshot: ![image](https://user-images.githubusercontent.com/93052112/151661665-f2b06e58-68c3-4bc9-9bc5-aa25b68e01cd.png)
5. Screenshot:![image](https://user-images.githubusercontent.com/93052112/151661978-53db166e-c759-41a9-b4d2-57fd914f5646.png)

**Comment by WiiJoy** [comment]
Привет! Хорошая работа, ты большая молодец!
Могу посоветовать обратить внимание на отступы и на адаптив блоков на 1440-768 (Price) и всей нижней части приложения на <480px. Но в общем и целом ты хорошо постаралась.

По всем моментам постарался оставить комментарии, надеюсь они будут чем-либо полезны)

Не останавливайся, продолжай в том же духе и успехов в дальнейшем обучении!)

**Ваша отметка - 71 балла(ов)**
Отзыв по пунктам ТЗ:

Частично выполненные пункты:
1) блок header — 5 балл(а)
Комментарий проверяющего: Скину 1 балл за header, тк элементам не хватает боковых отступов для правильного позиционирования (чуть больше пэддинга - 60px вместо 40)
<img width="880" alt="Снимок экрана 2022-02-04 в 14 01 44" src="https://user-images.githubusercontent.com/73646765/152522689-fe9dddd4-6460-486a-856b-2cfdcf97a3c2.png">

2) секция skills — 4 балл(а)
Комментарий проверяющего: Есть некоторая проблема с позиционированием элементов по блокам - следует поиграться с отступам
<img width="878" alt="Снимок экрана 2022-02-04 в 14 17 21" src="https://user-images.githubusercontent.com/73646765/152522753-5d50e1c8-be2e-4362-ac38-a54a7c1b3302.png">

3) секция portfolio — 4 балл(а)
Комментарий проверяющего: Не попадают кнопки в необходимые позиции. Возможно, можно было бы поиграться с размером их обертки
<img width="925" alt="Снимок экрана 2022-02-04 в 14 20 22" src="https://user-images.githubusercontent.com/73646765/152522793-9957a758-bc6b-4cef-bc6c-59bd80f89d60.png">

4) секция price — 5 балл(а)
Комментарий проверяющего: Скину 1 балл за непопадание в размеры блоков прайса - но тут, опять же, достаточно поиграться отступами для решения большей части несоответствия). 
<img width="851" alt="Снимок экрана 2022-02-04 в 14 39 11" src="https://user-images.githubusercontent.com/73646765/152522927-5c5898a3-ebed-43be-a7c9-1aa272cb5fb6.png">

5) секция contacts — 5 балл(а)
Комментарий проверяющего: Выравнивать либо картинку, либо весь контент - но разница 20px. Скорее всего снова отступами поиграть будет достаточно)
<img width="869" alt="Снимок экрана 2022-02-04 в 14 24 53" src="https://user-images.githubusercontent.com/73646765/152522980-ae69262c-50e0-4a1e-9546-087aac3fdff2.png">

6) блок footer — 5 балл(а)
Комментарий проверяющего: Так же -1 балл за позиционирование больше 10px от макета. И опять же - отступы :)
<img width="813" alt="Снимок экрана 2022-02-04 в 14 26 07" src="https://user-images.githubusercontent.com/73646765/152523019-9bc5433a-e5b8-4d6e-ad7c-626f341288c4.png">

7) нет полосы прокрутки при ширине страницы от 1440рх до 768рх — 2 балл(а)
Комментарий проверяющего: Не адаптивится блок Price
<img width="1068" alt="Снимок экрана 2022-02-04 в 14 32 29" src="https://user-images.githubusercontent.com/73646765/152523065-c21d8f5f-e31b-4528-b6cb-3776180864b3.png">

8) нет полосы прокрутки при ширине страницы от 480рх до 320рх — 2 балл(а)
Комментарий проверяющего: Не адаптивится достаточно много блоков + адаптивное меню заезжает за левые границы экрана, что тоже не есть хорошо
<img width="439" alt="Снимок экрана 2022-02-04 в 14 41 32" src="https://user-images.githubusercontent.com/73646765/152523269-6fb5b811-639a-4310-93a8-7774eb848bed.png">

9) высота адаптивного меню занимает всю высоту экрана. При ширине экрана 768-620рх вёрстка меню соответствует макету, когда экран становится уже, меню занимает всю ширину экрана — 3 балл(а)
Комментарий проверяющего: Скину балл за отсутствие темной подложки на части приложения, не покрытого адаптивным меню
<img width="917" alt="Снимок экрана 2022-02-04 в 14 27 36" src="https://user-images.githubusercontent.com/73646765/152523131-83917ed2-8e09-4697-a1d7-43c2bfe1fce4.png">

10) ссылки в адаптивном меню работают, обеспечивая плавную прокрутку по якорям — 1.5 балл(а)
Комментарий проверяющего: Ставлю полтора балла за баг: на секцию Price прокрутка не происходит. Остальные разделы отрабатывают


Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.

**Comment by yuliabalkiss** [comment]
Спасибо огромное за проверку, а особенно за компетентные комментарии к каждому блоку. Ошибки свои изучила, выводы сделала. Спасибо за достойную оценку моей работы и советы. :)
