### ISSUE TITLE
'Async Race'-'adzinetskatsiaryna'

### ISSUE THREAD

**Issue by adzinetskatsiaryna** [rolling-scopes-school/support#457]
1 https://rolling-scopes-school.github.io/adzinetskatsiaryna-JSFE2021Q3/#/
2 https://github.com/rolling-scopes-school/adzinetskatsiaryna-JSFE2021Q3/tree/async-race
3 https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
4
![Screenshot_1](https://user-images.githubusercontent.com/60846580/151665160-d3884dd5-49af-4ccc-aea9-937a53151e58.png)
![Screenshot_2](https://user-images.githubusercontent.com/60846580/151665163-3747faf4-b8ca-4646-abef-4c76e8f96bb5.png)
![Screenshot_3](https://user-images.githubusercontent.com/60846580/151665165-bf7cd721-54f1-4135-8bc8-e86a6eba4980.png)
![Screenshot_4](https://user-images.githubusercontent.com/60846580/151665208-36841bff-d6ad-4eee-bb1c-a905aa0bc35b.png)
Поясню ситуацию, вчера я увидела, что проверяющий не засчитал мне страницу winners, и поставил 135 баллов, хотя она была полностью выполнена и у других проверяющих она также открывалась. Мы с ним связались, он исправил оценку и запушил ее, скрин переписки я прилагаю в 4 скрине, у него не был перезапущен сервер во время проверки. Но тк исправил он оценку уже после завершения кросс чека она не учлась для определения средней в скор, в скоре средняя считается от первой оценки 135. Можно ли как-то засчитать его оценку.
5 175 (я не правильно поняла тз, и у меня машинки стартуют после того как дождутся ответа от сервера, и если приходит 500 ответ, она не стартует, а нужно было реализовать старт и ответ получать во время движения, и если он 500 машинка должна остановится во время движения)
6 158

**Comment by DmytroZozuliak** [comment]
Итого 171 балл

1.	Basic structure:
o	(+5) There should be two views on the site: "Garage" and "Winners".
o	(+5) "Garage" view should contain its name, page number, and the full amount of items in the database (how many car user has in his garage).
o	(+5) "Winners" view should contain its name, page number, and the full amount of items in the database (how many records the winners table contains).
o	(+6) View state should be saved when user switches from one view to another. For example, page number shouldn't be reset, input controls should contain that they contained before switching, etc.
Отнял 4 балла. Инпуты и позиция машинок не сохраняется. Нужно тогда блокиировать переход между «страницами» до истичения анимации машинки, илиже сохранять их текущее местоположение.  

2.	"Garage" view:
o	(+15) User should be able to create, update, delete a car, and see the list of the cars. Car has only two attributes: "name" and "color". For "delete"-operation car should be deleted from "garage" table as well as from "winners".
o	(+10) User should be able to select any color from an RGB-Palete like here and see the picture of the car colored with the color selected and car's name.
o	(+5) Near the car's picture should be buttons to update its attributes or delete it.
o	(+10) There should be pagination on the "Garage" view (7 cars per one page).
o	(+10) There should be a button to create random cars (100 cars per click). Name should be assembled from two random parts, for example "Tesla" + "Model S", or "Ford" + "Mustang" (At least 10 different names for each part). Color should be also generated randomly.
3.	Car animation:
o	(+5) Near the car's picture should be buttons for starting / stoping the car engine.
o	(+20) User clicks to the engine start button -> UI is waiting for car's velocity answer -> animate the car and makes another request to drive. In case api returned 500 error car animation should be stopped.
o	(+5) User clicks to the engine stop button -> UI is waiting for answer for stopping engine -> car returned to it's initial place.
o	(+5) Start engine button should be disabled in case car is already in driving mode. As well as stop engine button should be disabled when car is on it's initial place.
o	(+15) Car animation should work fine on any screen (smallest screen size is 500px).
4.	Race animation:
o	(+10) There should be a button to start race. After user clicks this button all the cars on the current page start driving.
o	(+10) There should be a button to reset race. After user clicks this button all the cars return to it's initial places.
o	(+10) After some car finishes first user should see the message contains car's name that shows which one has won.
5.	"Winners" view:
o	(+10) After some car wins it should be displayed at the "Winners view" table.
o	(+5) There should be pagination (10 winners per one page).
o	(+10) Table should include the next culumns: "№", "Image of the car", "Name of the car", "Wins number", "Best time in seconds" (names of the columns can differ). If the same car wins more than once the number of wins should be incremented while best time should be saved only if it's better than the stored one.
o	(+7) User should be able to sort cars by wins number and by best time (ASC, DESC).
Снял 3 балла. При пагинации не сохраняется сортировка

Не правильна логика в анимации машинок.
-10 баллов. Очень легко можно сломать приложени, к примеру запустить по отдельности машинки и запустить гонку. Тогда или анимация будет глючить или победитель не тот отобразится.
-2 балла, очень странное время вывода победителя в 25 сек и т.д. Даже считая с момента нажатия кнопки race прошло от силы 9с.
Замечания:
1)	из-за наложения области машинки, очень маленькая область нажатия клавиши remove
2)	При удалении последней машинки со страницы, страница остается пустая. Тоже самое и с победителями.
3)	Очень много не обработанных ошибок (Uncaught (in promise))
