### ISSUE TITLE
Cross-Check 'Portfolio#1,2' - 'DaniyarKulov'.

### ISSUE THREAD

**Issue by DaniyarKulov** [rolling-scopes-school/support#458]
1.https://rolling-scopes-school.github.io/daniyarkulov-JSFEPRESCHOOL/portfolio/
2. https://github.com/rolling-scopes-school/daniyarkulov-JSFEPRESCHOOL
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part1.md
4. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part2.md
5. ![image](https://user-images.githubusercontent.com/91828656/151706823-0a2ed8ea-d076-4f6f-a548-fc2dbad296f2.png)
![image](https://user-images.githubusercontent.com/91828656/151706853-da189a68-e22d-4de2-abf0-fd082b90d9ba.png)
6. оценку выставите какую считаете нужной я просто опоздал с проверкой кросс чека на 1 день в этих двух заданиях из-за этого мне не выставили баллы поэтому подал на апелляцию что бы их получить.
7. 0/100 из-за того что не вовремя проверил работы опоздал на 1 день в двух заданиях.

**Comment by valerydluski** [comment]
не попадает под правила апелляций
