### ISSUE TITLE
Cross-Check Singolo - selfmotivation

### ISSUE THREAD

**Issue by selfmotivation** [rolling-scopes-school/support#46]
https://selfmotivation.github.io/singolo/
https://github.com/selfmotivation/singolo

У меня есть 4 оценки от студентов, но в скоре 0, нигде не нашёл свой балл, поэтому даже не знаю, могу ли подать апелляцию. Если ошибся и где-то недочитал, прошу прощения.

Собственная объективная (по возможности) оценка и сравнение с комментариями оценивших:
// Сравнение с .jpg производится на разрешении 1020px, не зря же оно было указано в задании.

1. Не сданы вовремя singolo1 и singolo2. -20.
2. Наложение элементов подгонялось сначала в общем формате, а когда появлялось расхождение, то вплоть до индивидуальной стилизации. И сейчас в сравнении с .jpg отсутствует проблема.
3. text-align: justify не задан у меня, забыл. За все три блока, где встречается, -9 в сумме.
4. Блок About Us. Большой текст имени выходит за пределы блока. -3

В итоге я бы себе списал -32. (Что-то мне подсказывает, что зря я эту апелляцию подаю, себе в ущерб... Ну да ладно).

Работа с возражениями:
**>Student 1.** _Если изображения, или части изображений, находятся не на своем месте, ставим -3.(Блок Slider)_
Ответ: Вы выложили краткий список частых ошибок. Элемент в слайдере, не подразумевалось, что должен быть расположен как-то идеально. Четкая инструкция - с помощью absolute и на ширине экрана 1020px. На ней все совпадает как положено. Остальные элементы, к которым придирки не было, выровнялись сами за счет flex, что естественно.

**Student 1.** _Добвляем в сетку больше элементов с изображениями (чтобы получить, например, 15) - то следующие за 12-м не должны показываться (т.е. 13, 14, 15 не видны). В противном случае, ставим -3._
Ответ: У меня по умолчанию задано 15 элементов, а не 12, которые (лишние 3) не отображаются на ширине 1020px и на родном разрешении ноутбука (1366px). Не понимаю, как в принципе выявлена эта проблема.

**Student 2.** _Шрифты не работают должным образом.  Большое несовпадение в размерах в header и slider._
Ответ: Шрифты совпадают, не вижу проблем отображения, кэш сбросил. Несовпадение размеров также не фиксирую. Скриншот моего отображения приложу ниже.

**Student 2.** _В our services текст выходит за пределы.(под заголовком) В about та же проблема_
Ответ: В About Us согласен, -3. Но в Our Services проблема отсутствует.

**Student 3** _Очень плохо что сделал адаптивный макет, мешало проверки._
Ответ: Это шутка?

**Comment by amoebiusss** [comment]
@selfmotivation привет! В скоре появилась ваша оценка, 78. Ишью закрываю, хорошего дня!
