### ISSUE TITLE
Cross-Check 'portfolio#3' - 'AnnAbrajeeva'

### ISSUE THREAD

**Issue by AnnAbrajeeva** [rolling-scopes-school/support#460]
1. https://rolling-scopes-school.github.io/annabrajeeva-JSFEPRESCHOOL/portfolio/
2. https://github.com/rolling-scopes-school/annabrajeeva-JSFEPRESCHOOL/tree/portfolio
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio-part3.md
4. https://portfolio-part3-check-list.netlify.app/
5.
![app rs school_course_student_cross-check-submit_course=js-fe-preschool](https://user-images.githubusercontent.com/66987410/152471646-01bc7911-daa1-4848-b33c-a467375ef6ce.png)
6. 
Смена изображений в секции portfolio +25
Перевод страницы на два языка +25
Переключение светлой и тёмной темы +25
Дополнительный функционал +10
Итого: 75 
7. Score: 50

**Comment by spherical-horse** [comment]
**Ваша отметка - 75 балла(ов)**

Отзыв по пунктам ТЗ:


Все пункты выполнены полностью!
