### ISSUE TITLE
Cross-check 'Portfolio3' superDimitrius

### ISSUE THREAD

**Issue by superDimitrius** [rolling-scopes-school/support#461]
https://rolling-scopes-school.github.io/superdimitrius-JSFEPRESCHOOL/
[Ссылка на репозиторий с проектом на GitHub.](https://github.com/rolling-scopes-school/superdimitrius-JSFEPRESCHOOL)
[Ссылка на задание.](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/portfolio/portfolio.md)
[Ссылка на форму для проверки проекта (если такая есть).](https://portfolio-part2-check-list.netlify.app/)
![Снимок](https://user-images.githubusercontent.com/90276723/152740732-694e6c1e-09ea-4cd7-9f6d-f7d41d335a62.PNG)

Не зачтены баллы за задание, т.к. не вовремя закончил Кросс-чек из-за обилия работы и болезни.
Если возможно, было бы очень приятно их получить=)
P.S кросс -чек просрочен на примерно 12 часов)

**Comment by igorlyatskiy** [comment]
Скиньте документ, подтверждающий болезнь, мне в лс в дискорде
