### ISSUE TITLE
js30#1.2-audio-player submit

### ISSUE THREAD

**Issue by devbearu** [rolling-scopes-school/support#462]
1. https://rolling-scopes-school.github.io/devbearu-JSFEPRESCHOOL/audio-player/
2. https://github.com/rolling-scopes-school/devbearu-JSFEPRESCHOOL/tree/audio-player
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/js30%23/js30-2.md
4. https://audio-player-cross-check.netlify.app/

Добрый вечер друзья. Сижу на больничном с температурой. Собрался с силами и доделал проект audio-player. За 10 минут до дедлайна возникла проблема при мёрже ветки где я работал в gh-pages. Пока решил проблему и залил на gh-pages на часах было 23:59 по UTC и приложение закрыло доступ к отправке ссылки. Прошу понять и простить дать возможность залить ссылку и пойти на кросс-чек.
P.S пока доделывал задание, пропотел так, что температура спала.

**Comment by igorlyatskiy** [comment]
Скинь мне в лс в дискорде справку

**Comment by devbearu** [comment]
направил данные в ЛС дискорда

**Comment by WiiJoy** [comment]
Привет!
Где время, Лебовски? :)

Ладно, без шуток: работа на первый взгляд хорошая, но я - не я, если не придерусь к чему-нибудь)
Очень жаль, что у тебя оказались не все требования по ТЗ выполнены. + к этому есть и другие некоторые заковыки.

Надеюсь, что мои комментарии будут полезны)

В любом случае ты молодец! Береги здоровье, возьми в вооружение привычку заранее делать сабмит и в первую очередь выполнять требования ТЗ - и все обязательно будет круто)

Успехов в учебе!

Ваша отметка - **55 балла(ов)**
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Отображается продолжительность аудиотрека и его текущее время проигрывания
Комментарий проверяющего: Отображения времени нет
<img width="902" alt="Снимок экрана 2022-02-21 в 00 17 36" src="https://user-images.githubusercontent.com/73646765/154865036-0aea6a37-b7cb-4f43-a87d-02d81aff2c54.png">

Частично выполненные пункты:
1) Очень высокое качество оформления приложения и/или дополнительный не предусмотренный в задании функционал, улучшающий качество приложения — 5 балл(а)
Комментарий проверяющего: Поставлю 5 баллов
С одной стороны - есть доп функционал в виде возможности включить/отключить автоматическое воспроизведение следующей песни, есть регулятор громкости.

С другой:
- логически ожидаешь изменение иконки кнопки громкости при мьюте. Т.е. при клике по ней в первый раз, либо при перемещении ползунка громкости в самое левое состояние. Но нет, иконка не меняется;

- в дополнение к этому, включить звук повторным кликом по кнопке громкости не получается - в консоли соответствующая ошибка. Благо при изменении громкости ползунком он возвращается, но это явный баг;
<img width="384" alt="Снимок экрана 2022-02-21 в 00 22 01" src="https://user-images.githubusercontent.com/73646765/154865061-1e9d3b7a-af41-4706-b78d-71eb890aa045.png">

- нужно внимательнее относиться к верстке и возможным разрешениям пользователей. Иначе может получиться такое:
<img width="885" alt="Снимок экрана 2022-02-21 в 00 30 36" src="https://user-images.githubusercontent.com/73646765/154865089-1eb3225a-4442-433e-ab47-0767820cb8a3.png">

В общем и целом оценка набрана, но здесь явно еще есть, над чем поработать :)

Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.

**Comment by devbearu** [comment]
Спасибо большое за оценку и комментарии
