### ISSUE TITLE
Cross-check:js30#1.2-audio-player   FarAK10

### ISSUE THREAD

**Issue by FarAK10** [rolling-scopes-school/support#464]
1) https://rolling-scopes-school.github.io/farak10-JSFEPRESCHOOL/audio-player/
2) https://github.com/rolling-scopes-school/farak10-JSFEPRESCHOOL/tree/audio-player
3) https://github.com/rolling-scopes-school/tasks/blob/master/tasks/js30%23/js30-2.md
4) https://docs.rs.school/#/cross-check-flow
5) ![image_2022-02-09_22-01-17](https://user-images.githubusercontent.com/93331463/153251365-a95bc35a-9924-4821-b43e-67a3a43af3f6.png)
6)  Good afternoon.I have done all the requirements and added some additional features(everything works perfectly) but the last person who checked my work  assessed  in not the  proper way
My score is 60/60

**Comment by WiiJoy** [comment]
Привет! Хорошая работа - молодец)

Здесь явно **60/60** (при выставленных 65 из 70). Но все же есть кое-какие недочеты.

1. Ссылка с лого rs.school должна вести на курс (https://rs.school/js-stage0/), а не просто на сайт школы. Да, это не ошибка и 5 баллов из запасной десятки снято не за это, но не мог не отметить :)

2. То, за что снято 5 баллов: дополнительный функционал. Кроме его наличия я все же предполагаю (и ожидаю) его правильную отработку.

Минус за громкость.
Правильное поведение ползунка громкости - при перемещении его в минимальное положение, громкость должна быть равна 0.
На деле же получилось, что и мьюта на минимальном положении нет, что и самого минимального положения, как оказалось, нет, тк его не поймать :)
<img width="1037" alt="Снимок экрана 2022-02-20 в 16 17 50" src="https://user-images.githubusercontent.com/73646765/154845286-162ddfa7-bd41-4151-9868-af526a2ae9ca.png">

Еще один момент - очень странно видеть объявление переменных через var рядом с let и const. Нужно бы определиться, старовер ли ты, или все же используешь чуть более актуальными методами :)

На итог это, конечно, не повлияло, но надеюсь, что это полезные замечания)

Успехов в дальнейшем обучении!
