### ISSUE TITLE
Cross-Check 'js30#1.1-eco-sounds' - 'seozdev'

### ISSUE THREAD

**Issue by seozdev** [rolling-scopes-school/support#465]
Доброго времени. Прошу по возможности проверить работу и выставить оценки. Не выполнил работу в срок (и не участвовал в кроссчеке) по причине болезни (covid19). Фото больничного листа отправил в дискорд Irina(@irinainina) и попрошу по возможности отписать тут об этом.

Заранее всем! спасибо за найденное время.

1. https://rolling-scopes-school.github.io/seozdev-JSFEPRESCHOOL/eco-sounds/
2. https://github.com/rolling-scopes-school/seozdev-JSFEPRESCHOOL/tree/eco-sounds
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/js30%23/js30-1.md
4. https://eco-sounds-cross-check.netlify.app/
Оценка: 60

**Comment by WiiJoy** [comment]
Привет!

**Оценка: 59/60**

Хорошая работа, но очень заметно, что ты сильно поторопился)
Не надо так)

Баллы - баллами, но по-первых - свое здоровье важнее, во-вторых - внимательность к ТЗ и деталям.
Очень грустно было отнимать балл за неполностью выполненный пункт и не иметь возможность за что-нибудь накинуть за последний пункт.

Но, увы:
1. есть не меньше пяти интерактивных элементов, с которыми пользователи могут взаимодействовать. Изменение внешнего вида самого элемента и состояния курсора при наведении, плавные анимации: плавность есть только у кнопки Play/Pause и птички. Все остальные интерактивные элементы плавности не имеют.
2. Очень высокое качество оформления приложения и/или дополнительный не предусмотренный в задании функционал, улучшающий качество приложения: тк выполненная работа аналогична демке, без видимых изменений, улучшений и добавлений - за этот пункт нечего добавить :(

В любом случае, ты молодец! Не останавливайся на достигнутом и успехов в дальнейшем обучении!)

**Comment by seozdev** [comment]
привет!) Спасибо за проверку и отзыв. Да, согласен торопился. Опять же чтобы ещё успеть попасть в след. таск уже на общих основаниях.
