### ISSUE TITLE
Cross-Check js30#3.2-memory-game - Akorsikov

### ISSUE THREAD

**Issue by Akorsikov** [rolling-scopes-school/support#466]
Уважаемый Активист! Вы не обязаны проверять эту работу, но я буду очень признателен если Вы найдете время и желание на проверку и оценку. С Вашей стороны будете иметь уникальную возможность проверить работу, наверное, самого великовозрастного студента RSSchool (27 февраля мне исполняется 53года).
1. Deploy: https://rolling-scopes-school.github.io/akorsikov-JSFEPRESCHOOL/memory-game/
2. Repo: https://github.com/rolling-scopes-school/akorsikov-JSFEPRESCHOOL/tree/gh-pages/memory-game
3. Task : https://github.com/rolling-scopes-school/tasks/blob/master/tasks/js30%23/js30-8.md
4. Check form: https://memory-game-cross-check.netlify.app/
5. Самопроверка (оценка: 60 баллов). Выполнены все требования по заданию и добавлены следующие функции:
- в LocalStorage сохраняются не только 10 последних, но и 10 лучших игр;
- сброс статистики и удаление из LocalStorage только своих данных;
- смена темы игровых карточек;
- добавлен аудиоплеер меняющий трек согласно выбранной темы карточек.
6. Это аппеляция не на оценку, а похоже я не засабмитил ссылку. Когда сделал первый деплой  и хотел засабмитить ссылку в списке заданий у Submit не увидел Js30#3.2(ссылка ниже) и решил что еще не подгружена возможность, отложил на потом и погрузившись в задание ЗАБЫЛ про Submit.
 ![Submit, список заданий](https://user-images.githubusercontent.com/44119324/155094903-deeb971f-9af4-482c-9cbf-dc5fa4a642ed.png) Оказывается надо было скролить список! 
7. Привожу ссылку на мои Deploy где видно когда был первый и последний.
 List deploy: https://github.com/rolling-scopes-school/akorsikov-JSFEPRESCHOOL/deployments/activity_log?environment=github-pages
С уважением,
Корсиков Александр.

**Comment by WiiJoy** [comment]
Доброго времени! :)

Я не буду устанавливать каких-либо лейблов проверки, но любопытство победило)

Работа замечательная, по форме - 70 из 70! Очень жаль, что не было сабмита :(

Но и несколько пожеланий:

1. Аудиоплеер: тут 2 момента.
Первое - не думаю, что здесь требуется настолько явный плеер. Воспроизведение или остановка фоновой музыки - более чем достаточно для игры.
Второе - (придирка) по умолчанию хотелось бы, чтобы музыка играла сразу при загрузке страницы и при смене темы (если перед сменой пользователь не нажал кнопку отключения звука) :)

2. localStorage:
Сейчас каждая пара данных игры хранится отдельной записью в ls. Мне кажется это не очень удобным и на мой взгляд все это можно было бы хранить в одной-двух записях (например, одна запись на массив последних результатов, одна запись на массив лучших)

Не останавливайтесь на достигнутом и удачи в дальнейшем обучении! Вы большой молодец!)
