### ISSUE TITLE
Cross-Check 'memory-game' - 'TakeFives'.

### ISSUE THREAD

**Issue by TakeFives** [rolling-scopes-school/support#467]
Засабмитила в gh-pages, но завтыкала засабмитить ссылку на проверку :(

Deploy: https://rolling-scopes-school.github.io/takefives-JSFEPRESCHOOL/memory-game/
Task: 
https://github.com/rolling-scopes-school/takefives-JSFEPRESCHOOL/tree/gh-pages/memory-game
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/js30%23/js30-8.md
https://memory-game-cross-check.netlify.app/

Done 21.02.2022 / deadline 22.02.2020
Score: 70 / 60

Задание j#30 memory-game:
Вёрстка +10
Логика игры. Карточки, по которым кликнул игрок, переворачиваются согласно правилам игры +10
Игра завершается, когда открыты все карточки +10
По окончанию игры выводится её результат - количество ходов, которые понадобились для завершения игры +10
Результаты последних 10 игр сохраняются в local storage. Есть таблица рекордов, в которой сохраняются результаты предыдущих 10 игр +10
По клику на карточку – она переворачивается плавно, если пара не совпадает – обе карточки так же плавно переварачиваются рубашкой вверх +10
Дополнительный не предусмотренный в задании функционал (отображение сделанных ходов в процессе игры, кнопка перезагрузки игры) +10

Итого 70 :)

**Comment by WiiJoy** [comment]
Привет!

Хорошая работа, на твердые 60 баллов :)
По форме, конечно, 70 не получилось. Вот почему:

1. Я смог сломать игру :)
При каких-то обстоятельствах если успеть прокликать две карты до тех пор, пока не закроются две открытые - есть вероятность, что эти 2 карты перестанут открываться в принципе. Есть предположение, что такое происходит, если эти 2 карты - пара, но сильно в это я не проверял, мне был интересен сам факт)
Баг остается даже после перезагрузки поля. После перезагрузки страницы баг скидывался

Видео: https://drive.google.com/file/d/1YQpIQvBSfVviZhNCCCZa1osNgdF5ubSo/view

2. При повторном клике на первую перевернутую карту хотелось бы, чтобы этот клик по ней не читался :)
Сейчас получается, что при клике карта резко становится неперевернутой с последующим переворачиванием. В общем, не очень хорошо, на мой взгляд :)

В общем и целом ты молодец и очень жаль, что забывчивость зашла в твои владения)
Гони эту забывчивость метлой и в будущем старайся сабмитить таски заранее)

Не останавливайся на достигнутом и успехов в дальнейшем обучении!)

PS: лейблы не выставляю, тк по сути забывчивость не подпадает под рассмотрение апелляции, отзыв исключительно для фидбэка. Остальное - на усмотрение администрации курсов)
