### ISSUE TITLE
Cross-Check '3_linear_regression' - 'albert-bariev'

### ISSUE THREAD

**Issue by albert-bariev** [rolling-scopes-school/support#468]
Ссылка на деплой вашего проекта: https://github.com/albert-bariev/rs-school-ml/blob/main/3_linear_regression.ipynb
Ссылка на задание: https://github.com/rolling-scopes-school/ml-intro/blob/2022/3_linear_regression/linear_regression.ipynb
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты): 
![image](https://user-images.githubusercontent.com/52201316/160582266-bb5e6f14-0bbc-471f-bb59-a2b9999a8851.png)

Оценка в результате самопроверки с ее аргументацией: 32. 
- 2,3,4 проверяющие поставили максимальный балл, но 2 не обновил его с учетом изменившегося максимума (выросло с 30 до 32, а он поставил 30)
- 1 проверяющий снял баллы не по объективным причинам. Задания, за которые он снизил балл были выполнены по ТЗ.

Балл за cross-check из вашего Score: 31

**Comment by UladzislauSakalou** [comment]
Хорошая работа. В последнем задании действительно не предоставлены комментарии в коротком отчете, а именно:
- Can you find a logical explanation for high correlation of some of your features?
- How could you pottentially improve the model?
Однако я считаю что снимать все баллы за short report чересчур. Снял 0.5.

1. 1 point
2. 1 point
3. 6 points
4. 1 point
5. 1 point
6. 1 point
7. 3 points
8. 1 point
9.  5 points
10. 1 point
11. 1 point
12. 9.5 points


Total: 31.5

**Comment by dr-leto** [comment]
Updated in Scores
