### ISSUE TITLE
Cross-Check Singolo - 4-o-4

### ISSUE THREAD

**Issue by 4-o-4** [rolling-scopes-school/support#47]
https://github.com/4-o-4/singolo
https://4-o-4.github.io/singolo

Я проверила свою работу по чек-листу, получилось 87 баллов.
Не согласна со следующими пунктами проверяющих:

**Student 1**
В коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020: минус -10 баллов

**Student 3**
Если в коммитах, или в ветках с коммитами, файлы singolo2.html и singolo2.сss отсутствуют до 02.03.2020, ставим -10.
Если в коммитах, или в ветках с коммитами, файлы singolo3.html и singolo3.сss или index.html и style.css отсутствуют до 09.03.2020, ставим -10.
В Firefox есть сильное отклонение (т.е. бросается в глаза) от той же страницы, открытой в Google Chrome, а именно - высота <textarea> в форме, ставим -5.
На странице обязательно должен присутствовать один элемент h1. Если он отсутствует в разметке, либо на нем есть свойство display: none (в данном случае элемент скрыт, другим способом), ставим -3.
Блок Get a Quote Указатель на номер телефона - должен быть ссылкой типа tel. Если нет, ставим -3.
Указатель на email - должен быть ссылкой типа mail. Если нет, ставим -3.

**Comment by amoebiusss** [comment]
@4-o-4 привет, хорошая работа! Вот небольшие замечания:

1. За счет добавления кнопки уехал футер:
![image](https://user-images.githubusercontent.com/26903136/77317493-57eec880-6d1c-11ea-92e8-bacfbaf46493.png)

100 - 3 (смещенный футер) - 10 * 3 (в репо действительно нет отдельных частей макета)= ** 67 баллов**
