### ISSUE TITLE
Cross-check Shelter

### ISSUE THREAD

**Issue by Evkolkovskiy** [rolling-scopes-school/support#471]
Ссылка на деплой https://rolling-scopes-school.github.io/evkolkovskiy-JSFE2022Q1/shelter/.
Ссылка на задание https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1
Добрый день. Возможно ли изменить засабмиченную ссылку на вышеуказанную. Сбило с толку, что на скриншоте дерева проекта index.html не вынесен на верхний уровень. И соответственно из-за этого моя ссылка не открывалась. Спасибо.

**Comment by Artem-Gevondyan** [comment]
Cross-Check 'Shelter' - 'artem-gevondyan'.
Деплой: https://rolling-scopes-school.github.io/artem-gevondyan-JSFE2022Q1/shelter/pages/main/
Задание: https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1
Добрый день! Забыл засабмитить ссылку на таск. Очень не хочу терять баллы за это задание.

**Comment by igorlyatskiy** [comment]
@Artem-Gevondyan удалил комментарий, апелляцию надо создавать отдельным issue. И оформлять надо по правилам

**Comment by igorlyatskiy** [comment]
@Evkolkovskiy дополни пункты, название issue

**Comment by valerydluski** [comment]
закрываю
