### ISSUE TITLE
Cross-Check Shelter Alexeykoh

### ISSUE THREAD

**Issue by Alexeykoh** [rolling-scopes-school/support#472]
[Ссылка на деплой вашего проекта.]https://rolling-scopes-school.github.io/alexeykoh-JSFE2022Q1/shelter/pages/main/index.html
[Ссылка на репозиторий с проектом на GitHub.](https://github.com/rolling-scopes-school/alexeykoh-JSFE2022Q1/tree/gh-pages/shelter)
[Ссылка на задание.](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md)

**Comment by igorlyatskiy** [comment]
Причина подачи?

**Comment by valerydluski** [comment]
закрываю
