### ISSUE TITLE
 Cross-Check 'Shelter' - 'OstapchelaEst'.

### ISSUE THREAD

**Issue by OstapchelaEst** [rolling-scopes-school/support#473]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/ostapchelaest-JSFE2022Q1/shelter/pages/main/
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/ostapchelaest-JSFE2022Q1/tree/shelter
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/
Введу большой загруженности, запутался в днях и забыл засабмитить ссылку на проект. Прошу проверить мою работу и выставить оценку. Заранее спасибо.

**Comment by Xtcnz181988** [comment]
1.  background-color при hover кнопки не соответствует макету - **минус 3 балла (по 1 баллу за каждый элемент)**.
![image](https://user-images.githubusercontent.com/91630257/163229739-cdd194e8-73c6-487b-80f8-9bfa37c4fc64.png)
![image](https://user-images.githubusercontent.com/91630257/163230475-5f5d592c-e435-4632-82d5-0f7c17493774.png)
![image](https://user-images.githubusercontent.com/91630257/163230500-a26973df-0c7a-4dd7-bf54-40c3c599e4f7.png)
![image](https://user-images.githubusercontent.com/91630257/163230689-653d2c6c-0d59-45c1-9ce0-7fa1c785dc7e.png)
Обратите внимание на последний пункт.
2. Обратите внимание на Logo. У Вас интерактивно исключительно 
![image](https://user-images.githubusercontent.com/91630257/163231070-d702d4c5-d84e-438b-92ee-6abd4a7b4b63.png)
а должен быть интерактивен элемент. В критериях такого требования не было - баллы не снимал.
**ИТОГОВОЕ КОЛИЧЕСТВО БАЛЛОВ = 97 **

**Comment by OstapchelaEst** [comment]
Спасибо за ревью, по поводу ховеров в тз строго  не оговаривалось точное совпадение эффекта ховера с тем, что указанно в макете,оснганым условием является его интерактивность.

**Comment by Xtcnz181988** [comment]
> Спасибо за ревью, по поводу ховеров в тз строго не оговаривалось точное совпадение эффекта ховера с тем, что указанно в макете ,основным условием является его интерактивность.

![image](https://user-images.githubusercontent.com/91630257/163529173-d093045d-634e-40b3-bd86-7ade5e9d9367.png)
В ТЗ написано на ваше усмотрение И ИСХОДЯ ИЗ МАКЕТА. И означает что И из макета И возможно дополнительный функционал по Вашему желанию. Если бы была написано из макета ИЛИ по вашему усмотрению, то я бы согласился
