### ISSUE TITLE
Cross-Check Shelter Desktop - AlisaFed .

### ISSUE THREAD

**Issue by AlisaFed** [rolling-scopes-school/support#475]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/alisafed-JSFE2022Q1/shelter/pages/main/
Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/alisafed-JSFE2022Q1/tree/gh-pages/shelter
Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/

**Comment by igorlyatskiy** [comment]
@AlisaFed нет формы для проверки задания

**Comment by AlisaFed** [comment]
@igorlyatskiy https://shelter-desktop-v1.netlify.app/
Прошу прощения, что не добавила изначально.

**Comment by ipipka** [comment]
### Итоговый балл: 39 
__________
**Обнаруженные проблемы (не выполнены пункты требований):**

**Страница main**
[-1 балл] Страница main: Not only. Отступы внутри сетки по горизонтали отличаются более чем на 10px (положение текста отличается на 40 пикселей)
[-1 балл] Страница main: About. Отступы внутри сетки по горизонтали отличаются более чем на 10px (отступ между заголовком и текстом отличается на 15 пикселей)
[-1 балл] Страница main: Our Friends. Отступы внутри сетки отличаются более чем на 10px
[-1 балл] Страница main: Footer. Отступы внутри сетки по горизонтали отличаются более чем на 10px (положение блоков с текстом отличается на 15-20 пикселей)
[-1 балл] Страница main: Header. Элемент About the shelter не подсвечен
[-1 балл] Страница main: Header. Элемент Our pets не работает как ссылка на страницу our pets
[-2 балла] Страница main: Header. На странице нет элемента `<h1>`
[-1 балл] Страница main: Our Friends. Кнопка "влево" есть, но не интерактивная
[-1 балл] Страница main: Our Friends. Кнопка "вправо" есть, но не интерактивная
[-2 балла] Страница main: Our Friends. Карточки не интерактивные
[-1 балл] Страница main: Our Friends. Кнопка Get to know the rest есть, но не интерактивная, или не работает как ссылка на страницу our pets
[-2 балла] Страница main: Our Friends. Кнопки Learn more не меняют цвет при наведении на карточку
[-1 балл] Страница main: In addition. Блок со ссылкой на банковский счет есть, но он не интерактивный, или не является ссылкой
[-2 балла] Страница main: Footer. Элемент email не работает как ссылка на почтовый сервис
[-2 балла] Страница main: Footer. Элемент телефон не работает как ссылка на сервис звонков
[-1 балл] Страница main: Footer. Хотя бы один элемент "локация" не работает как ссылка на google maps


**Страница our pets**
_Не создана страница our pets_
__________
**Некоторые замечания, за которые не снижала балл** (это описано в задании, но не учитывается в требованиях):

- В макете с дизайном есть отдельный фрейм, на котором собран весь интерактив для элементов (в том числе то, как должны выглядеть кнопки, пункты меню при наведении курсора (:hover)), твои эффекты не соответствуют тому, что "предлагает дизайнер"
- Цвет границы у кнопки "Get to know the rest" отличается от макета
- Странное положение для якоря #Pets - где-то посреди блока, нужно бы по верхней части блока
__________
- У тебя нет какого-то единого подхода к именованию классов. Такой код будет очень сложно поддерживать - именование классов должно быть максимально предсказуемым.
Какие-то классы начинаются с большой буквы, какие-то с маленькой (`Donation`, `puppy`). Где-то использкется kebab-case (`icon-phone`), где-то camelCase (`HeadingDonation`, `photoKatrine`), где-то snake_case (`Donation_content`, `button_primary`), а где-то вообще смесь :)
Все-таки в css принята kebab-case нотация (то есть в названии css-класса слова разделяются дефисами и все буквы маленькие)
Когда используется один стиль именования, то код легче читается и проще в поддержке (`donation`, `puppy`, `icon-phone`, `heading-donation`, `photo-katrine`, `donation-content`, `button-primary`)
Если идти еще дальше, то полезно будет почитать про БЭМ - это очень удобный подход, но для проектов побольше (на мой взгляд) - там в именовании одно класса могут быть и нижние подчеркивания _ и дефисы -, но есть четкие правила когда какой из разделителей используется
- Ну и названия классов вида `button_arrow2` - это не гуд. Через неделю ты не вспомнишь, что это значит!
В данном случае лучше будет `button_arrow_right` и `button_arrow_left`, например. 
А можно пойти еще дальше и сделать `button-round` - универсальную круглую кнопку (ее же можно будет использовать и в постраничной навигации)
А стрелочки в виде иконок или картинок добавить внутри кнопки. Условно что-то такое
`<button class="button-round"><img src="arrow-right.svg" alt="arrow right"></button>`
__________
Если это одна из первых работ, то это неплохо! Видно, что местами тяжеловато (и видимо не все успела), но все придет с опытом, главное продолжать!
Успехов в дальнейшей учебе!

**Comment by AlisaFed** [comment]
@ipipka  Спасибо за проверку и советы! Это действительно был мой первый сайт в жизни)
