### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'Dmitri-Korolev'

### ISSUE THREAD

**Issue by Dmitri-Korolev** [rolling-scopes-school/support#476]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/dmitri-korolev-JSFE2022Q1/shelter/pages/main/
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/dmitri-korolev-JSFE2022Q1/tree/gh-pages/shelter
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/

Прошу проверить мою работу и выставить оценку.

**Comment by ipipka** [comment]
### **Итоговый балл: 80**
__________
**Обнарушенные проблемы (не выполнены пункты требований):**
[-1 балл] Страница main: Help. Отступ до нижнего края блока отличается от макета на 40 пикселей
[-1 балл] Страница main: Footer. Отступ до нижнего края блока отличается от макета на 56 пикселей 
Это случилось из-за того, что ты задаешь у футера height: 350px и padding-top: 56px. В сумме высота блока получилась 350 + 56 = 416px, а в макете футер высотой в 350 пикселей. Чтобы лучше понимать как высчитывается высота блока и какие существуют варианты советую ознакомиться с понятием box model (блочная модель) и свойством box-sizing
[-1 балл] Страница main: Our Friends. Отступы внутри карточек отличаются больше, чем на 10 пикселей. Отступы между элементами (сетка) отличаются большем, чем на 10 пикселей
[-1 балл] Страница main: Help. Отступы между элементами отличаются от макета больше, чем на 10 пикселей
[-1 балл] Страница main: In addition. Элемент с номерм банковской карточки отличается более, чем на 30 пикселей от мекета (за счет отсупа справа)
Это происходит из-за того, что в верстке у тебя это блочный элемент и он занимает всю ширину родителя. Тут могло бы помочь, например, display: inline-block
[-1 балл] Страница main: Footer. Отступы и у ссылок с адресами отличаются более, чем на 10 пикселей
[-1 балл] Страница main: Not only. Размер текста на кнопке отличается более, чем на 4 пикселя
Происходит из-за того, что не указано свойство letter-spacing. По данной проблеме в других блоках штрафовать не буду, так как использется один css-класс.
[-1 балл] Страница main: About. Размер текста в заголовке отличается более, чем на 4 пикселя
Происходит из-за того, что для заголовка не задано свойство font-weight (поэтому используется значение по умолчанию bold, а по макету должно быть normal). По данной проблеме в других блоках штрафовать не буду, так как использется один css-класс.
[-1 балл] Страница main: Not Only. Кнопка Make a Friend не работает как якорная ссылка на блок Our Friends
[-2 балла] Страница main: Our Friends. Кнопки Learn more не меняют цвет при наведении на карточку
[-1 балл] Страница main: Our Friends. Кнопка Get to know the rest не работает как ссылка на страницу our pets
[-1 балл] Страница our pets: Footer. Отступ до нижнего края блока отличается от макета на 56 пикселей 
[-1 балл] Страница our pets: Our Friends. Отступы между элементами карточек и постраничной навигацией отличаются больше, чем на 10 пикселей
[-1 балл] Страница our pets: Footer. Отступы и у ссылок с адресами отличаются более, чем на 10 пикселей
[-1 балл] Страница our pets: Our Friends. Кнопки пагинации есть, но кнопки "влево" интерактивные
[-1 балл] Страница our pets: Our Friends. Кружочек страницы в пагинации интерактивный
[-2 балла] Страница our pets: Our Friends. Кнопки Learn more не меняют цвет при наведении на карточку
[-1 балл] Страница our pets: Our Friends. Хотя бы один элемент "локация" не работает как ссылка на google maps
__________
**Некоторые замечания, за которые не снижала балл** (это описано в задании, но не учитывается в требованиях):
1. У ссылок email и tel в футере должен быть кликабельный не только текст, но и иконка
2. На странице "our pets" шапка должна фиксироваться при скролле
3. Элементы меню не меняют цвет по на наведению, хотя в дизайне отрисованы все состояния
__________
Неплохая работа, но есть куда стремиться. Чуть больше внимательности к мелочам и все будет замечательно!
Успехов в дальнейшем обучении :-)
