### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'perfilovv'

### ISSUE THREAD

**Issue by perfilovv** [rolling-scopes-school/support#477]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/perfilovv-JSFE2022Q1/shelter/pages/main/index.html
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/perfilovv-JSFE2022Q1/tree/gh-pages/shelter
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/

Забыл засабмитить шелтер, прошу проверить мою работу и выставить оценку.

**Comment by madkorney** [comment]
привет!

# общая оценка 91 балл

хорошая работа, молодец. но есть недочеты.



## страница Main

- header
  - Элемент `Help the shelter` не работает как якорная ссылка на блок *Help*: **-1**.
  - Элемент `Contacts` не работает как якорная ссылка на блок *Footer*: **-1**.
  - На странице два элемента `<h1>`: **-1**. 

- start (Not only)
  - ссылка с кнопки Make the friend ведет на Our Pets, а должна на блок Our Pets на главной странице: **-1**

- about
  - все отлично


- our friends
  - недочет по интерактивности карточек. при ховере на **карточку** курсор должен поменять форму на pointer. не снижал  
  
- help
  - расстояние между блоками в сетке задано паддингами, а нужно было свойcтвами flex. из за этого к правому краю накапливается сдвиг, для посл элемента в строке - больше 25 пикселей, то есть нарушение сетки бболее чем на 10 пикс.  : **-1**
![сс_1](https://user-images.githubusercontent.com/1611438/163716814-a8bd49c3-b78b-4ff9-9707-3e66be56d7f4.jpg)
  
- donation
  - нет эффекта при ховере над кнопкой с номером пластик.карты - нет изменения фона кнопки. не снижал 
  - у враппера не заданы отступы, поэтому flex-элементы собака и блок с текстом и кнопком имеют неправильное расстояние междуу ними. сдвиг больше 10 пикс. : **-1**


- footer
  - небольшие расхождения с макетом в позиционировании блоков, не снижал
ссылка на телефон некорректная и иконки в футере не работают как ссылки  - **минус 2**
		

### итого за Main 60 - 5 = 55 баллов


## страница Pets

- header
  - Элемент `Help the shelter` не работает как якорная ссылка на блок *Help* страницы *main*: **-1**.
  - Элемент `Contacts` не работает как якорная ссылка на блок *Footer*: **-1**.

- our friends
  - по сетке  нет замечаний, замечание к карточкам - см выше
  - Кнопки "влево" интерактивные: **-1**.  (должны быть disabled)
  - Кружочек страницы интерактивный: **-1**.  (не должен иметь никаких ховер эффектов)

- footer
  - все отлично

### итого за Pets 40 - 4 = 36 баллов

**Comment by perfilovv** [comment]
Спасибо большое!
