### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'queuelia'

### ISSUE THREAD

**Issue by queuelia** [rolling-scopes-school/support#478]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/queuelia-JSFE2022Q1/Shelter/index.html

Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/queuelia-JSFE2022Q1/tree/gh-pages/Shelter

Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1

Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/

Произошли проблемы с правильным деплоем проекта за несколько минут до дедлайна.
Прошу проверить мою работу и выставить оценку.

**Comment by LidaChk** [comment]
**Итоговое клочисетво баллов = 100** 

Шикарная работа. Все тютельку в тютельку, кроме одного оступа.

Есть несколько замечаний по несоотвествию тз не влияющих на оценку:
- Main - About - увеличен отступ на 15 пикселей ( в пределах 20) .about { height: 573px;} выставлена - а в макете 588

![image](https://user-images.githubusercontent.com/20344968/163248427-87dc37d8-0ba3-423d-8159-fb6af79d58a0.png)

- Не хвататет курсор поинтер на стрелочках  в блоке Friends на страние Main
- По тз хедер на странице Pets липкий.
