### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'Vlad-Moskalenko'.

### ISSUE THREAD

**Issue by Vlad-Moskalenko** [rolling-scopes-school/support#479]
1. https://rolling-scopes-school.github.io/vlad-moskalenko-JSFE2022Q1/shelter/pages/main/
2. https://github.com/rolling-scopes-school/vlad-moskalenko-JSFE2022Q1/tree/gh-pages/shelter
3. https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter
4. https://shelter-desktop-v1.netlify.app/

Добрый день. Засабмитил нерабочую ссылку, неправильно задеплоил проект вечером, к утру когда сформировал правильную ссылку заметил что путь к файлам css не работает, тоже исправил. В самом оформлении или дополнительно ничего не исправлял, только путь к файлам css.
Прошу проверить мою работу и выставить оценку. Заранее спасибо

**Comment by ipipka** [comment]
### Итоговый балл: 59
__________
**Обнарушенные проблемы (не выполнены пункты требований):**

**Страница main**
[-2 балла] Страница main: Our Friends. Кнопки Learn more не меняют цвет при наведении на карточку
[-2 балла] Страница main: Help. Сеточная структура элементов нарушена (не 5 элементов сверху, 4 снизу)

**Страница our pets**
_**На данной странице не подключен css, поэтому, к сожалению, практически все параметры не выполняются :(**_
[-1 балл] Страница our pets: Header. Отступы от границ элементов отличаются более чем на 20px
[-1 балл] Страница our pets: Our Friends. Отступы от границ элементов отличаются более чем на 20px
[-1 балл] Страница our pets: Footer. Отступы от границ элементов отличаются более чем на 20px
[-1 балл] Страница our pets: Header. Отступы внутри набора отличаются более чем на 10px
[-1 балл] Страница our pets: Our Friends. Отступы внутри набора отличаются более чем на 10px
[-1 балл] Страница our pets: Footer. Отступы внутри набора отличаются более чем на 10px
[-1 балл] Страница our pets: Header. Цвет фона блока или элемента отличается от дизайна
[-1 балл] Страница our pets: Our Friends. Цвет фона блока или элемента отличается от дизайна
[-1 балл] Страница our pets: Footer. Цвет фона блока или элемента отличается от дизайна
[-1 балл] Страница our pets: Header. Разница в размере шрифта более чем 4px
[-1 балл] Страница our pets: Our Friends. Разница в размере шрифта более чем 4px
[-1 балл] Страница our pets: Footer. Разница в размере шрифта более чем 4px
[-1 балл] Страница our pets: Header. Логотип есть, но не работает как ссылка на страницу main
[-1 балл] Страница our pets: Header. Элемент About the shelter не работает как ссылка на страницу main (ведет на страницу 404)
[-1 балл] Страница our pets: Header. Элемент Our pets не подсвечен
[-1 балл] Страница our pets: Header. Элемент Help the shelter не работает как якорная ссылка на блок Help страницы main (ведет на страницу 404)
[-1 балл] Страница our pets: Header. Фон сильно отличается от того, что на макете
[-2 балла] Страница our pets: Our Friends. Кнопки пагинации есть, но все кнопки одного цвета или фона
[-1 балл] Страница our pets: Our Friends. Кнопки пагинации есть, но кнопки "влево" интерактивные
[-1 балл] Страница our pets: Our Friends. На кружочке страницы в пагинации нет цифры, или там не единица
[-1 балл] Страница our pets: Our Friends. Кружочек страницы в пагинации интерактивный
[-2 балла] Страница our pets: Our Friends. Карточки есть, но сеточная структура элементов нарушена (не по 4 в ряду)
[-2 балла] Страница our pets: Our Friends. Карточки не интерактивные
[-2 балла] Страница our pets: Our Friends. Кнопки Learn more не меняют цвет при наведении на карточку
[-2 балла] Страница our pets: Footer. Сеточная структура элементов нарушена
[-2 балла] Страница our pets: Footer. Элемент email не работает как ссылка на почтовый сервис
[-2 балла] Страница our pets: Footer. Элемент телефон не работает как ссылка на сервис звонков
[-1 балл] Страница our pets: Footer. Хотя бы один элемент "локация" не работает как ссылка на google maps
[-1 балл] Страница our pets: Footer. Картинка собаки есть, но сильно смещена, или накладывается на текст или другие блоки
[-1 балл] Страница our pets: Footer. Фон сильно отличается от того, что на макете
__________
**Некоторые замечания, за которые не снижала балл** (это описано в задании, но не учитывается в требованиях):
1. В описании задания есть такое требование: "При ширине окна выше 1280px верстка должна оставаться по центру, а не растягиваться на всю ширину окна". У тебя, конечно, верстка не растягивается, но и не выравнивается по центру
2. В секциях с фоном-градиентом ты указываешь в качестве фона картинку с паттерном ("шумом"), но она не отображается из-за того, что для этой картинки прописан некорректный путь в css
3. В блоке "About the shelter" вы потерялась одна буква в тексте, поэтому немного съехала строка текста ;)
4. В макете с дизайном есть отдельный фрейм, на котором собран весь интерактив для элементов (в том числе то, как должны выглядеть кнопки, пункты меню при наведении курсора (:hover))
5. У карточек при наведении курсора (:hover) должен менять фон, появляться тень (помимо подсветки кнопки)
6. Ссылка с номера карточки по заданию не должна приводить к переходу на другую страницу
7. В ссылках с email и телефоном должны быть кликабельны не только текст, но и иконки
8. Ссылки на гугл-карты должны открываться в отдельном окне/вкладке (см. target="_blank")
9. В случае с иконками в разделе "Help" для позиционирования как в макете (5 + 4) мне помог column-gap: 120px и justify-content: center;
__________
Очень жалко, что на второй странице не подключен css! 
Хорошая чистая html разметка!
Успехов в дальнейшей учебе!
