### ISSUE TITLE
Cross-Check Singolo - IxionBY

### ISSUE THREAD

**Issue by IxionBY** [rolling-scopes-school/support#48]
Ссылка на деплой вашего проекта: https://ixionby.github.io/singolo/

Ссылка на репозиторий с проектом на GitHub: https://github.com/IxionBY/singolo

Оценка в результате самопроверки, с ее аргументацией: работа выполнена на 100 баллов, все соответствует заданным критериям проверки.

Балл за cross-check из вашего Score:

Student 1
Ваша оценка - 72 балла 

Отзыв по пунктам ТЗ:

1) В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020: минус -10 баллов 

2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Header составляют более двух пикселей (2px): минус -3 балла 

3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Slider составляют более двух пикселей (2px): минус -3 балла 

4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла 

5) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Portfolio составляют более двух пикселей (2px): минус -3 балла 

6) При увеличении длины значения элемента с именем в секции About (сами дописываем очень длинный текст) текст видимым образом выходит за пределы строки блока или переносится на следующую строку: минус -3 балла 

7) Внутри тэга "< form >" отсутствует кнопка Submit, или она реализована не с помощью "< button >" или "< input >": минус -3 балла
 
Student 2
Отзыв по пунктам ТЗ:

1) В коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020:    -10 баллов 

2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Header составляют более двух пикселей (2px) (навигационные ссылки):    -3 балла 

3) Номер телефона в блоке Contacts не реализован ссылкой, работающей с префиксом tel: (ссылка с правильным префиксом установлена не на номер телефона, а на соседнюю в строке иконку):    -1 балл

4) Электронная почта в блоке Contacts не реализована ссылкой, работающей с префиксом mailto: (ссылка с правильным префиксом установлена не на эл. почту, а на соседнюю в строке иконку):    -1 балл

Student 3
1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции header-navigation составляют более  двух пикселей (2px); -3 балла;
2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции form составляют более  двух пикселей (2px); -3 балла;

Аргументация:
1 оценщик
1) Файлы с первой частью Singolo был закомичен 20 февраля, с названиями index.html и style.css(что укладывается в рамки дедлайна).
2) пункты 2-5 Настолько сильные отклонения с макетом отсутствуют, перепроверьте пожалуйста
3) пункт 6 - Текст пропадает и не переносится, точки появляются в конце строки
4) пункт 7 - Кнопка < button > присутствует и находится внутри формы

2 оценщик
1) Файлы с первой частью Singolo был закомичен 20 февраля, с названиями index.html и style.css(что укладывается в рамки дедлайна).
2) Настолько сильные отклонения с макетом отсутствуют, перепроверьте пожалуйста
3) пункты 3,4 - Согласно таску ссылками должны быть указатели(что трактовать можно по разному), в моем случае я подумал, что указателями являются значки перед номером и адресом почты. 

3 оценщик
1) пункты 1,2 - Настолько сильные отклонения с макетом отсутствуют, перепроверьте пожалуйста

**Comment by amoebiusss** [comment]
@IxionBY привет! Работа очень аккуратная. Есть небольшие замечания:

1. Достаточно большое визуальное расхождение в тексте элементов меню в хедере:
![image](https://user-images.githubusercontent.com/26903136/77318115-8a4cf580-6d1d-11ea-915c-1689ac08b7bc.png)

2. _(этот пункт не влияет на итоговый балл)_ При экспорте графики лучше не сжимать ее до состояния, когда картинки начинают выглядеть плохо и появляются артефакты:
![image](https://user-images.githubusercontent.com/26903136/77318704-88cffd00-6d1e-11ea-8b1a-31e3dedab016.png)
![image](https://user-images.githubusercontent.com/26903136/77318718-908fa180-6d1e-11ea-8e04-270216c48dba.png)

Итоговый балл:
100 - 10 (в коммитах, или в ветках с коммитами, файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020) - 3 (элементы в хедере) = **87 баллов**
