### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'destr1ke'.

### ISSUE THREAD

**Issue by destr1ke** [rolling-scopes-school/support#480]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/destr1ke-JSFE2022Q1/shelter/pages/main/
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/destr1ke-JSFE2022Q1/tree/shelter
Ссылка на задание :  https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/
Перепутал день с дедлайном и забыл задеплоить проект, вчера расстроился утром , а позже увидел в дискорде, что еще можно все исправить. Прошу прощения и проверить мою работу. Большое спасибо!

**Comment by Xtcnz181988** [comment]
1. 
![image](https://user-images.githubusercontent.com/91630257/163222019-e6c7f4e6-301f-4f7d-83ea-7172e79fe684.png)
Лого должно быь интерактивным, но остовлять нас на странице main - минус 2 бала;
![image](https://user-images.githubusercontent.com/91630257/163224312-e7c4f882-429d-487b-a21f-e2a261b7e95f.png)

2. 
![image](https://user-images.githubusercontent.com/91630257/163223558-204f4ebf-d919-4023-b9e5-6ff0d2f57971.png)
Номер должен быть ссылкой, которая никуда не ведет. У Вас ведет в хедер. В кретериях оценки такого нет, но на будущее внимательней читайте ТЗ. Баллы не снимал.
3.  Все остальное выполнено в соответствии с требованиями ТЗ и макета.
**ИТОГОВОЕ КОЛИЧЕСТВО БАЛЛОВ (100 - 2) = 98 баллов**
