### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'elena-zakharoshka'.

### ISSUE THREAD

**Issue by elena-zakharoshka** [rolling-scopes-school/support#481]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/elena-zakharoshka-JSFE2022Q1/shelter/pages/main/index.html
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/elena-zakharoshka-JSFE2022Q1/tree/gh-pages/shelter
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/
Добрый день. В день дедлайна запуталась с формированием ссылки на проект, поэтому не засабмитила ссылку. Только сегодня увидела в дискорте, что можно подать аппеляцию, и исправить, в виде исключения, только это задание. Был вопрос в отображении картинок, поэтому вчера были исправлены пути. Больше изменений не вносилось. Если еще есть такая возможность, прошу проверить мою работу. Большое спасибо!

**Comment by WiiJoy** [comment]
Привет, итоговая оценка: **90**

1.  Зазоры с каждой стороны по 8px - это не есть хорошо. Проверь внимательно, из-за чего именно это происходит, тк в будущем это может вылиться в проблемы. Относится ко всей странице. Тк итоговый зазор меньше 20px - баллы не скидываются
![Screenshot_27](https://user-images.githubusercontent.com/73646765/163179323-ec44873c-74dd-4a8d-9cdb-b1ea1c32911d.jpg)

2. Отступы внутри набора или сетки между элементами, по горизонтали или вертикали, отличаются более чем на 10px в блоках:
  - -1 за блок Our Friends страницы main: следует поработать еще над отступами между элементами. Имхо, следует обернуть карточки в отдельную обертку, чтобы в ней задать необходимые отступы именно между карточками, а во внешней обертке задать необходимые отступы между стрелками и блоком этих карточек
![Screenshot_24](https://user-images.githubusercontent.com/73646765/163179835-066d0e76-71b4-4a82-9ee2-cf751f6716de.jpg)

  - -1 балл за Help страницы main: нужно поработать еще над позиционированием:
![Screenshot_25](https://user-images.githubusercontent.com/73646765/163180064-5944ec51-3247-427b-8746-0e1509639174.jpg)

3. Отступы от границ элементов (или наборов элементов) до краев блока, по горизонтали или вертикали, отличаются более чем на 20px у блока header страницы pets - не хватает 23px сверху, -1 балл:
![Screenshot_26](https://user-images.githubusercontent.com/73646765/163180197-402ce99b-63f6-4ca1-a18e-6bcd462bf198.jpg)

4. Элемент About the shelter не подсвечен на странице main, -1 балл:
![Screenshot_27](https://user-images.githubusercontent.com/73646765/163180493-c1431e3c-52db-4bdc-97ea-78d736cc4813.jpg)
+ стоит придерживаться макетных эффектов наведения для всех сущностей, в тч для элементов панели навигации :)

5. (без снижения) - будь внимательней к текстам, тут очепятка :)
![Screenshot_29](https://user-images.githubusercontent.com/73646765/163180703-6eaa79b4-1889-426d-a197-95bd84be4847.jpg)

6. Кнопки Learn more не меняют цвет при наведении на карточку на странице main (-2):
![Screenshot_30](https://user-images.githubusercontent.com/73646765/163181143-2fcd3019-ec7a-4dc0-8d42-4033c2e43522.jpg)

7. Элемент Our pets не подсвечен в навигации на странице pets (-1):
![Screenshot_31](https://user-images.githubusercontent.com/73646765/163181376-050b9d9d-16fc-4598-acaf-881d9dec5b83.jpg)

8. Кнопки Learn more не меняют цвет при наведении на карточку на странице pets (-2):
![Screenshot_32](https://user-images.githubusercontent.com/73646765/163181529-375b6790-eabf-4776-a260-f2d86bd72c19.jpg)

9. Кружочек с единичкой в пагинации не должен быть интерактивным, а у тебя он интерактивится, увы (-1) :(
![Screenshot_33](https://user-images.githubusercontent.com/73646765/163181709-27b0d685-c095-4104-b2b1-aa59be4abc53.jpg)

Хорошая работа, но будь чуточку внимательнее к деталям и требованиям ТЗ. На самом деле мелочи, из-за которых снизился балл, которых могло бы не быть при более ответственном подходе.

В любом случае ты молодец и не останавливайся на достигнутом! Успехов! ;)
