### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'Tkachkovski'.

### ISSUE THREAD

**Issue by Tkachkovski** [rolling-scopes-school/support#482]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/tkachkovski-JSFE2022Q1/shelter/pages/main/
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/tkachkovski-JSFE2022Q1/tree/gh-pages/shelter
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/
Добрый день. Засабмитил неверную ссылку, после сабмита в работе нечего не менялось, связаться со всеми проверяющими в ходе кросс-чека не удалось. Прошу проверить мою работу если еще есть такая возможность. Заранее спасибо.

**Comment by madkorney** [comment]
привет!

# **общая оценка 82 балла**

хорошая работа, молодец. но есть недочеты.

- общее.
 к сожалению шрифты не подгрузились (видимо неверно указаны пути в @font-face). из-за этого при рендеринге они сильно не совпадают с макетом , больше чем на 4пикс.  это -1 за каждый блок, итого  -7 для main, -3 для pets. не забывай плз после деплоя проверять такие вещи. в твоем случае это сильно повлияло на положение элементов во всех блоках. всего за это **минус 10** к общей оценке

## страница Main
- header
  - пункты меню при ховере не меняют цвет (не снижал за это)
  - заголовок-лого разнесло, но это не сдвинуло другие элементы (уже снял баллы за шрифты)

- start
  - заголовок разнесло, но это не сдвинуло другие элементы (уже снял баллы за шрифты)

- about
  - заголовок разнесло, но это не сдвинуло другие элементы (уже снял баллы за шрифты)

- our friends
  - заголовок разнесло, но это не сдвинуло другие элементы (уже снял баллы за шрифты)
  - блок с карточками смещен по вертикали на 45 пикс - **минус 1**

  - карточки "pets"
ошибки:
    - нет тени при ховере (нет в критериях, не снижал)
    - без ховера - цвет фона карточки не задан, она получается прозрачная (нет в критериях, не снижал)
    - при ховере на карточке фон карточки меняется не на тот цвет, что в макете (нет в критериях, не снижал)
    - при ховере на *карточке* заливка кнопки не меняется - **минус 2**
    - при ховере над кнопкой learn more меняется заливка кнопки на макетный цвет кнопок без ховера (нет в критериях, не снижал)
    - круглые кнопки вправо-влево подсвечиваются квадратиками. нужно менять кнопку, а не обертывающий div (нет в критериях, не снижал)
    - при ховере на кнопки вправо-влево-get to know more подсвечивается карточка Woody. Woody безусловно хорош, но все же это надо исправить ) (нет в критериях, не снижал)

надо было так
    - сделать статичный фон карточки цветом #FAFAFA, 
    - при ховере на *карточку* 
        а) менять фон карточки на #FFFFFF, 
	б) показать тень карточки, box-shadow: 0px 2px 35px 14px rgba(13, 13, 13, 0.04);
	в) поменять фон *кнопки* на #FDDCC4
   и отдельно ховер кнопки не обрабатывать
    - при ховере на кнопки со стрелками менять цвет кнопки, а не цвет ее обертки
  
- help
  - заголовок секции поплыл из за неподгруженного шрифта (уже снял баллы за шрифты)

- you can make a donation 
  - заголовок секции поплыл из за неподгруженного шрифта (уже снял баллы за шрифты)
  - нет ховер эффекта на кнопке с номером кредитной карты (осветление фона). однако курсор меняется, сама ссылка - именно ссылка, так что штрафа нет.


- footer
  - из за неподгруженного шрифта положение ссылок и иконок сильно смещено при снижении ширины экрана меньше 1329 пикс - проиходит перенос в заголовках и адреса /емейл / телефон отталкиваюся вниз (а проверять необходимо на 1280/1297). тут я придираться не стал, проверил на 1330, 
  - блок с адресами сдвинут вправо на 15 пикс. это элемент сетки, больше разрешенных 10 пикс - **минус 1**
  - у номера телефона неверный шрифт - arial вместо georgia. нет в критериях оценки - не снижал
  - цвет ссылок при ховере меняется на черный у емейл и телефона - такого нет в макете
  
### Итого за Main 60 - 7 - 4 = 49 баллов
  
## страница Pets
 
- header
  - нет подсветки пунктов меню при ховере (не снижал)
  - логотип - ссылка есть, но она не ведет на страницу main  **минус 1**
 
- our pets
  - все те же проблемы с карточками, как в main, кроме подсветки Вуди от кнопок. (тут уже не снижал, это те же самые карточки которые уже оценил в Main)
  - блок с карточками и кнопки пагинации расположены на 45 пикс не, чем необходимо ( неверное растояние между заголовком и сеткой с карточками) **минус 1**
   - пагинация:
     а) кнопка с номером страницы не должна быть интерактивной ( **минус 1**)
     б) подсветка кнопок вправо - квадратом(опять обертка), а не самой круглой кнопки (не снижал)
	 
 
- footer
  - все те же проблемы как и в main  - **минус 1** за сдвинутый блок адресов
 
### Итого за Pets 40 - 3 - 4 = 33 балла  

![apellation-tkachkovski](https://user-images.githubusercontent.com/1611438/163193198-1720f94a-d609-435e-8230-be5f3590b5b9.png)
