### ISSUE TITLE
Cross-Check Shelter - ZeD125B

### ISSUE THREAD

**Issue by ZeD125B** [rolling-scopes-school/support#483]
1. https://rolling-scopes-school.github.io/zed125b-JSFE2022Q1/Shelter/index.html
2. https://github.com/rolling-scopes-school/zed125b-JSFE2022Q1/tree/Shelter
3. https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
4. https://shelter-desktop-v1.netlify.app/

Опоздал с deploy. Прошу вас проверить работу, дали первый и последний шанс потеряшкам сдать работу после deadline по фиксированной верстке. Спасибо.

**Comment by ZeD125B** [comment]
> Нет формы для проверки и неправильное название issue

Исправил

**Comment by madkorney** [comment]
привет!

### общая оценка 93 балла

хорошая работа, молодец. но есть недочеты.



## страница Main
расположение элементов идеальное во всех блоках страницы

- header
  - лого не является ссылкой, это есть в ТЗ, но нет в критериях оценки - не снижал
  - меню - пункты меню не меняют цвет при ховере, но ссылки из меню сделаны верно, курсор меняется -  не снижал

- start
все отлично

- about
все отлично

- our friends
  - недочет по интерактивности карточек. при ховере на **карточку** должна подсвечиваться **кнопка** на карточке, а отдельно ховер на кнопке не нужно обрабатывать. не снижал  
  
- help
отлично, нет замечаний
  
- donation
небольшая ошибка - нет эффекта при ховере над кнопкой с номером пластик.карты - нет изменения фона кнопки. не снижал 


- footer
ссылка на телефон некорректная (должно быть `tel:` , а у тебя ссылка на стр. 404 ) и иконки в футере не работают как ссылки  - **минус 2**
		

### итого за Main 60 - 2 = 58 баллов


## страница Pets

- header
  - Логотип есть, но не работает как ссылка на страницу *main*: **минус 1**.
  - меню - неверный шрифт(д быть arial), не меняется цвет шрифта при ховере **минус 1**
  - неверно задано расстояние между пунктами меню, от этого оно сжато относительно макета, и расстояние от лого до меню отличается более, чем на 10пикс. **минус 1** 
![сс](https://user-images.githubusercontent.com/1611438/163543512-ecc8f282-4a06-4aed-939f-2a6e3791075f.png)



- our friends
по сетке  нет замечаний, замечания к карточкам - см выше

- footer
ссылка на телефон некорректная и иконки в футере не работают как ссылки  - **минус 2**

### итого за Pets 40 - 5 = 35 баллов
