### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'srgMet'. 

### ISSUE THREAD

**Issue by srgMet** [rolling-scopes-school/support#484]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/srgmet-JSFE2022Q1/shelter/pages/main/index.html
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/srgmet-JSFE2022Q1/tree/gh-pages
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/
не мог залить на работе стоит прокси,  уже и друзей опытных подключили, в чате тоже помощи не нашел, в итоге в качестве эксперемента скачал дэсктопную версию гитхаба и через нее делал clone push, выдавало примерно такое
https://cdn.discordapp.com/attachments/943477773073264670/963714421530689556/unknown.png

**Comment by ipipka** [comment]
### Итоговый балл: 90
__________
**Обнарушенные проблемы (не выполнены пункты требований):**

**Страница main**
[-1 балл] Страница main: Our Friends. Отступы внутри сетки по горизонтали отличаются более чем на 10px
[-1 балл] Страница main: Help. Отступы внутри сетки по горизонтали отличаются более чем на 10px
[-1 балл] Страница main: Not only. Цвет заголовка и цвет текста не соответствуют макету (для заголовка должен быть #545454, для текста #4c4c4c)
[-1 балл] Страница main: About. Цвет заголовка не соответствует макету (должен быть #545454, штрафую отдельно так как на заголовках разные css-классы)
[-1 балл] Страница main: Our Friends. Цвет заголовка не соответствует макету (должен быть #545454, штрафую отдельно так как на заголовках разные css-классы)
[-2 балла] Страница main: Our Friends. Кнопки Learn more не меняют цвет при наведении на карточку

**Страница our pets**
[-1 балл] Страница our pets: Our Friends. Цвет заголовка не соответствует макету (должен быть #545454, а ты задаешь #292929)
[-2 балла] Страница our pets: Our Friends. Кнопки Learn more не меняют цвет при наведении на карточку
__________
**Некоторые замечания, за которые не снижала балл** (это описано в задании, но не учитывается в требованиях):

В макете с дизайном есть отдельный фрейм, на котором собран весь интерактив для элементов (в том числе то, как должны выглядеть кнопки, пункты меню при наведении курсора (:hover)), твои эффекты не соответствуют тому, что "предлагает дизайнер"
Ссылка с номера карточки по заданию не должна приводить к переходу на другую страницу
В ссылках с email и телефоном должны быть кликабельны не только текст, но и иконки
Ссылки на гугл-карты должны открываться в отдельном окне/вкладке (см. target="_blank") и карта должна открываться "с любой локацией на ваш выбор"
__________
Неплохая работа! Чуть больше внимания к деталям и все будет супер :)
Успехов в дальнейшей учебе!

**Comment by Msmarin** [comment]
спасибо, буду стараться
