### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'dikiyrot'.

### ISSUE THREAD

**Issue by dikiyrot** [rolling-scopes-school/support#485]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/dikiyrot-JSFE2022Q1/shelter/pages/main/
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/dikiyrot-JSFE2022Q1/tree/gh-pages/shelter/
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/

Добрый день. В день дедлайна засабмитил неверную ссылку. 
Из-за не верной ссылки, думал что я не правильно сделал деплой проекта. Вследствии чего, уже после дедлайна 13.04.2022 снес все ветки и залил проект заново. Но как оказалось деплой от 11.0422022 был проведен успешно (была неверная ссылка). Это подтверждается проверкой проекта 12.04.2022 пользователем Student 1.

Комментарий пользователя Student 1:
```
Score: 97

Привет. Ссылка должна быть вот такая:

 https://rolling-scopes-school.github.io/dikiyrot-JSFE2022Q1/shelter/pages/pets/index.html  

       Общий балл: 97

cтраница MAIN:

     Header:

           Отступы от границ элементов до краев блока, по вертикали, отличаются более чем на 20px: -1.

страница OUR PETS:

     Header:

          Элемент Contacts не работает как якорная ссылка на блок Footer: -1.

          Кружочек страницы интерактивный: -1.
```
После повторного залива и деплоя никаких корректировок и изменений внесено не было. Осознаю, что нарушил правило перезаливом после дедлайна. Обещаю, что впредь такое не повторится. Если есть такая возможность, прошу проверить мою работу. Большое спасибо!

**Comment by ipipka** [comment]
### Итоговый балл: 96
__________
**Обнаруженные проблемы (не выполнены пункты требований):**

**Страница main**
[-1 балл] Страница main: Header. Отступы от границ элементов до краев блока отличаются более чем на 20px (у шапки должен быть отступ сверху страницы в 60 пикселей, а у тебя только 30)
[-1 балл] Страница main: Not only. Отступы внутри набора или сетки между элементами отличаются более чем на 10px (положение блока с текстом отличается от макета на 30 пикселей)

**Страница our pets**
[-1 балл] Страница our pets: Header. Элемент Contacts не работает как якорная ссылка на блок Footer (ссылка ведет на несуществующий якорь)
[-1 балл] Страница our pets: Our Friends. Кружочек страницы в пагинации интерактивный
__________
**Некоторые замечания, за которые не снижала балл:**

- На странице our pets в пагинации у неактивных кнопок все-таки cursor: pointer; надо убрать...
- Светлые кнопки (стрелочки, "Learn more" на карточке) неприятно дергаются при наведении и мелькает черная рамка. Это из-за того, что ты обнуляешь border по наведению. Я чтобы избежать такого эффекта для всех состояний этих кнопок использовала бордер в 2 пикселя. Просто там, где его не должно быть видно делала его прозрачным. 
Например, для светлой кнопки задан `border: 2px solid #F1CDB3;` тогда по наведению вместо обнуления бордера использую `border-color: transparent;`
__________
Хорошая работа, чистая и аккуратная разметка!
Успехов в дальнейшей учебе!
