### ISSUE TITLE
Cross-Check: Shelter Desktop - IsakovAndrew

### ISSUE THREAD

**Issue by IsakovAndrew** [rolling-scopes-school/support#486]
1.https://rolling-scopes-school.github.io/isakovandrew-JSFE2022Q1/Shelter/pages/main/
2.https://rolling-scopes-school.github.io/isakovandrew-JSFE2022Q1/Shelter/pages/main/
3.https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
4.https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
5.https://shelter-desktop-v1.netlify.app/
6.Нету оценок
7.100/100 
Есть блок Header.
Есть логотип.
Есть панель навигации. Панель навигации интерактивная. 
Элемент About the shelter подсвечен.
Элемент Our pets работает как ссылка на страницу our pets.
Элемент Help the shelter работает как якорная ссылка на блок Help.
Элемент Contacts работает как якорная ссылка на блок Footer.
На странице есть элемент <h1>.
Есть блок Not only.
Есть кнопка Make a Friend. Кнопка интерактивная, работает как якорная ссылка на блок Our Friends.
Есть картинки собаки. 
Есть блок About.
Картинка есть, не смещена, не накладывается на текст или другие блоки.
Текст заголовка имеет верные размеры.
Кавычки имеют правильный вид.
Есть блок Our Friends.
Есть кнопка "влево". Кнопка интерактивная.
Есть кнопка "вправо". Кнопка интерактивная.
Есть карточки с питомцами. При этом:
Сеточная структура элементов не нарушена.
Количество карточек соотвествует макету.
Структура карточек не нарушена.
Карточки интерактивные.
Кнопки Learn more меняют цвет при наведении на карточку.
Есть кнопка Get to know the rest. Кнопка интерактивная, работает как ссылка на страницу our pets.
Есть блок Help.
Сеточная структура элементов не нарушена.
Изображение иконок не отсутствуют.
Не нарушена структура.
Есть блок In addition.
Есть блок со ссылкой на банковский счет. Блок интерактивный, и является ссылкой.
Есть картинки собаки. Картинка собаки, не смещена, не накладывается на текст или другие блоки.
Есть блок Footer.
Сеточная структура элементов не нарушена.
Элемент email работает как ссылка на почтовый сервис.
Элемент телефон работает как ссылка на сервис звонков.
Все элементы локации работают как ссылки на google maps.
Есть картинки собаки. Картинка собаки, не смещена, не накладывается на текст или другие блоки.
Создана страница our pets +40.

Есть блок Header.
 Логотип есть, работает как ссылка на страницу main.
Панель навигации есть, интерактивная.
Элемент About the shelter работает как ссылка на страницу main.
Элемент Our pets  подсвечен.
Элемент Help the shelter работает как якорная ссылка на блок Help страницы main.
Элемент Contacts работает как якорная ссылка на блок Footer.
Есть блок Our Friends.
Есть кнопки навигации. 
Кнопки "влево" не интерактивные.
Кнопки "вправо" интерактивные.
На кружочке страницы есть цифра один.
Кружочек страницы не интерактивный.
Есть карточки с питомцами. 
Карточки интерактивные.
Кнопки Learn more меняют цвет при наведении на карточку.
Есть блок Footer.
Сеточная структура элементов не нарушена.
Элемент email работает как ссылка на почтовый сервис.
Элемент телефон работает как ссылка на сервис звонков.
Все элементы локации работают как ссылки на google maps.
Картинка собаки есть, не смещена, не накладывается на текст или другие блоки.
8.Нету оценки

**Comment by ThorsAngerVaNeT** [comment]
Ваша отметка - 88 балла(ов)
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Страница main: Footer
Комментарий проверяющего: У футера снизу есть белая полоса в 40px. Соответственно все элементы футера не примыкают к его нижнему краю.
2) Страница main: Header
Комментарий проверяющего: Цвет активной страницы не выделен согласно макету.
3) Страница main: Our Friends
Комментарий проверяющего: Цвета заголовка блока, фона и текста кнопок "влево", "вправо", "Learn more", имени животного и самой карточки не соответствуют макету.
4) Страница main: Help
Комментарий проверяющего: Цвет подписей не соответствует макету.
5) Страница main: In addition
Комментарий проверяющего: Цвета заголовка и подзаголовка не соответствуют макету.
6) Карточки не интерактивные
Комментарий проверяющего: При наведении на карточку сама карточка не интерактивна (в макете есть пример интерактивности карточки - изменени цвета и добавление тени)
7) Страница our pets: Footer
Комментарий проверяющего: У футера снизу есть белая полоса в 40px. Соответственно все элементы футера не примыкают к его нижнему краю.
8) Страница our pets: Header
Комментарий проверяющего: Цвет активной страницы не выделен согласно макету.
9) Страница our pets: Our Friends
Комментарий проверяющего: Цвета заголовка, имён животных, фона и текста кнопок "Learn More" и фона самой карточки не соответствуют макету
10) На странице нет элемента <h1>


Комментарии к выполненным пунктам:

1) Страница main: Header
Комментарий проверяющего: Подчёркивание активной страницы расположено не в соответствии с макетом. Балл не снимал.
2) Нарушена структура (например текст сверху, иконка снизу) в одном или более элементе
Комментарий проверяющего: Letter-spacing для подписей задан не верно из-за этого есть небольшое смещение относительно макета. Балл не снимал.
3) Кнопки пагинации есть, но кнопки "вправо" не интерактивные
Комментарий проверяющего: Стоило так же менять курсор. Балл не снимал.


Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.
