### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'ticavin'.

### ISSUE THREAD

**Issue by ticavin** [rolling-scopes-school/support#487]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/ticavin-JSFE2022Q1/shelter
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/ticavin-JSFE2022Q1/tree/gh-pages/shelter
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/
Все пункты выполнены

Так получилось, что не успел засабмитеть ссылку. Только сегодня увидел в дискорде, что есть возможность через апелляцию получить проверку. Прошу проверить мою работу

**Comment by ipipka** [comment]
### Итоговый балл: 96
__________
**Обнаруженные проблемы (не выполнены пункты требований):**

**Страница main**
_Замечаний нет_

**Страница our pets**
[-1 балл] Страница our pets: Header. Логотип есть, но не работает как ссылка на страницу main
[-1 балл] Страница our pets: Header. Элемент Contacts не работает как якорная ссылка на блок Footer (ссылка переносит на страницу main, а нужно было реализовать якорную ссылку на футер текущей страницы)
[-1 балл] Страница our pets: Our Friends. Кнопки пагинации есть, но кнопки "влево" интерактивные
[-1 балл] Страница our pets: Our Friends. Кружочек страницы в пагинации интерактивный
__________
**Некоторые замечания, за которые не снижала балл:**

- В секциях с фоном-градиентом должен быть не только сам градиент, но и картинка с паттерном ("шумом")
- У карточек с питомцами при наведении курсора (`:hover`) должен меняется фон и появляться тень (помимо подсветки кнопки)
- Ссылки на гугл-карты по условиям задания должны открываться в новой вкладке (см. `target="_blank"`)
- `input` обернутый в ссылку, как и кнопка обернутая в ссылку - спецификацией точно такое не предусмотрено
Вместо кнопки можно просто использовать ссылку, которую стилизовать как кнопку. По инпуту вообще не очень поняла конструкцию, там достаточно было ссылки :)
А чтобы отлавливать такие ошибки можно использовать валидатор https://validator.w3.org/
- Меня немного напрягло наличие css-классов с заглавной буквы (`Donation`), как-то это не очень принято в css. Все таки kebab-case и все маленькие или какая-то общая методоллогия, вроде БЭМ
А когда часть классов с большой буквы, а часть с маленькой, это будет путать и провоцировать ошибки (не забываем, что названия классов в css регистрозависимы)
- Некоторые вещи придется переделывать для адаптивности. Например, иконки в блоке help на странице main. Если немного поподбирать параметры, то можно добиться того, чтобы вывод был в один блок flex, а не два отдельных (`flex-wrap: wrap`, `justify-content: center;` и правильно подобранный `gap` и никаких размеров для самих блоков "иконка + текст"). Тогда будет сильно проще сделать адаптивность
__________
Хорошая работа, но есть куда стремиться!
Успехов в дальнейшей учебе!
