### ISSUE TITLE
Cross-Check 'Shelter.Desktop' - 'gavrishdaria'

### ISSUE THREAD

**Issue by GavrishDaria** [rolling-scopes-school/support#489]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/gavrishdaria-JSFE2022Q1/shelter/pages/main/
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/gavrishdaria-JSFE2022Q1
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/
Доброго времени суток. Не засабмитила ссылку в установленный срок. Работы выполняла добросовестно, поэтому буду максимально благодарна возможности проверке мое задание.

**Comment by WiiJoy** [comment]
Привет! Хорошая работа, ты молодец. Итоговый балл - **88** из 100!
Ниже все найденные замечания :)

Желаю идти вперед дальше и успехов в обучении!)

1. В блоке our friends страницы main нужно немного поиграться с позиционированием слайдера - сейчас разница ровно 10px + перенос заголовка не по макету.
<img width="1306" alt="Снимок экрана 2022-04-18 в 09 11 25" src="https://user-images.githubusercontent.com/73646765/163763695-3cbb7124-10e6-4848-a9ca-cfebd5d65849.png">

2. В блоке help стоит проверить отступы между элементами + заголовок.
<img width="1329" alt="Снимок экрана 2022-04-18 в 09 08 13" src="https://user-images.githubusercontent.com/73646765/163763754-4a2865c2-4c15-463b-8790-295134f01640.png">

3. Фон для header + not only должен выглядеть как единое целое + не хватает наложенного узора. Советую попробовать задать фон исключительно блоку not only, задать ему верхний padding на величину хедера, а сам хедер абсолютно спозиционировать (и не давать ему фон). Должно все получиться ;)
<img width="1322" alt="Снимок экрана 2022-04-18 в 09 08 59" src="https://user-images.githubusercontent.com/73646765/163763984-68e014ec-4982-4de6-921c-8f2800becc83.png">
По цвету аналогичные замечания по футеру обеих страниц

4. Панель навигации есть, но не интерактивная - точнее, не реализована интерактивность по макету. Стандартный pointer для ссылки не считается :)
Следует добавить ховер к этим элементам

5. Не снижается оценка: внутрь тега button не очень круто ставить ссылку :) Намного проще вместо тега button сразу использовать тег а, стилизовав его под кнопку)

6. Не снижается оценка: в карточках питомцев текст в кнопках немного не выравнен по центру, а у самого ховера карточки есть явные отличия от того, что задумано по макету. Стоит с этими моментами еще немного поработать :)

7. Не снижается оценка: иконка с телефоном обрезана на 1 или 2px
<img width="286" alt="Снимок экрана 2022-04-18 в 09 38 21" src="https://user-images.githubusercontent.com/73646765/163766581-528776f6-948e-4080-8291-c9887cbe9271.png">

8. Много несоответствий в блоке our friends страницы pets. Следует поработать с заголовком, отступами и размерами кнопок пагинации
<img width="1371" alt="Снимок экрана 2022-04-18 в 09 50 53" src="https://user-images.githubusercontent.com/73646765/163768094-20d37607-60ed-4f3b-95ad-b62a67286502.png">
<img width="426" alt="Снимок экрана 2022-04-18 в 09 50 59" src="https://user-images.githubusercontent.com/73646765/163768106-3b393039-6453-4bd1-8f25-261e4431f55f.png">

9. Аналогичное замечание по навигации страницы our pets - как на странице main

10. Карточки животных аналогично страницы main

11. Пагинация:
- левые кнопки должны быть неактивны и отмечены сереньким
- кружок с цифрой должен быть залит цветом и не иметь эффектов наведения
<img width="413" alt="Снимок экрана 2022-04-18 в 10 02 22" src="https://user-images.githubusercontent.com/73646765/163769528-904397d0-1b9a-421d-b093-47eef9001438.png">

**Comment by GavrishDaria** [comment]
большое спасибо за проверку и дельные советы!

**Comment by valerydluski** [comment]
выставил оценку
