### ISSUE TITLE
Cross-Check Singolo - sergiowork

### ISSUE THREAD

**Issue by sergiowork** [rolling-scopes-school/support#49]
Ссылка на деплой вашего проекта - http://bestdevapp2.000webhostapp.com/sites/singolo-main/singolo.html

Ссылка на репозиторий с проектом на GitHub - https://github.com/sergiowork/singolo

Оценка в результате самопроверки, с ее аргументацией ---->  94 баллов

-3 Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции About us
В остальных секциях text-align: justify присутствует:
.services__text p { text-align: justify; }
.form-wrap .contact-info > p { text-align: justify; }

-3 В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт

+ все отклонения в пределах 2px
+ все файлы в репозиторий заливались до дедлайна https://github.com/sergiowork/singolo/commits/master?after=792f6001397186e387dcc9e79685e33d8ac5d53a+34
+ при добавлении картинок > 12-ти, картинки скрываются. Для этого был реализован класс portfolio__img__hide 
В исходном коде страницы, при верстке, в качестве примера, были добавлены  картинки с использованием этого класса
img class="portfolio__img portfolio__img__hide" src="assets/img/project9.jpg" alt="project9"
img class="portfolio__img portfolio__img__hide" src="assets/img/project10.jpg" alt="project10"
 img class="portfolio__img portfolio__img__hide" src="assets/img/project11.jpg" alt="project11"
img class="portfolio__img portfolio__img__hide" src="assets/img/project12.jpg" alt="project12"

Балл за cross-check из вашего Score - 59

Student 1
Ваша оценка - 0 баллов 
Отзыв по пунктам ТЗ:
1) Pепозиторий singolo не существует, или в нем не присутствуют index.html и style.css файлы: минус -100 баллов 

Student 2
-10 - файлы singolo1.html и singolo1.сss отсутствуют до 24.02.2020
-10 - файлы singolo3.html и singolo3.сss или index.html и style.css отсутствуют до 09.03.2020
-3 - сдвиг размеров блока Portfolio
-3 - сдвиг размеров блока Get a Quote
-3 - Блок Our Services - не проходит тест на переполнение текстом, текст не скрывается
-3 - Блок Portfolio - не проходит тест на переполнение картинками, лишние картинки не скрываются

Student 3
Балл снимала за то, что отмечено в конце "- ... текст". Одинаковые ошибки по блокам считала за одну (почти каждая в -3 балла оценивалась).
Балл: 88

+ Навигация в header сделана через nav и li
+ Контакты в contact information с соответствующими href
+ Социальные иконки сделаны списком
+ Копирайт копируется согласно ТЗ
+ Цветной фон блоков занимает 100% окна просмотра (часто это является требованием к проектам)
+ В about us в поле с именем при добавлении большого количества текста лишний текст скрывается, на новую строку не переносится
+ В about us в поле с именем при добавлении большого количества текста лишний текст переносится на новые строки
+ В FireFox страница не ломается
+ Проект заливался вовремя
+ Интересная реализация hover у imput
> В about us заливка иконок выходит немного за границы иконки при hover
> Некоторым ссылкам при hover можно добавить дополнительный эффект для лучшей визуализации наведения. Например, можно добавить смену opacity.
> Можно добавить плавность перехода для интерактивных элементов
> В input для лучшей валидации можно добавить pattern
> Стоит посмотреть и подправить line height у текстовых элементов. Например в about us, get a quote
> В portfolio в тексте потеряно est
> При добавлении дополнительных картинок они появляются на странице и расширяют блок. Если работать с классами, то в данной ситуации пришлось бы добавлять JS для управлениями классом для лишних карточек. Я бы пересмотрела такой подход. Можно ограничиться css. Как вариант overflow.
> В галерее с изображениями имеет смысл использовать grid или flex
- К сожалению декоративная линия в конце slider значительно шире линии на макете
- Кнопка в all в portfolio отличается более чем на 2 px
- Есть отличия в ширине текстовых элементов и размере шрифта (about us, get a quote, services) (здесь имеется ввиду не ширина самого текста, а блока, в котором он лежит)

Student 4
Ваша оценка - 79 баллов
Отзыв по пунктам ТЗ:
1) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Services составляют более двух пикселей (2px): минус -3 балла
2) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции About составляют более двух пикселей (2px): минус -3 балла
3) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов секции Get a Quote составляют более двух пикселей (2px): минус -3 балла
4) Несоответствие снимку макета, наложенному на страницу. Визуальные отличия элементов Footer составляют более двух пикселей (2px): минус -3 балла
5) Текст в местах, где находится несколько строк, должен быть растянут равномерно на ширину блока. Отсутствует свойство text-align: justify или его аналог в секции About: минус -3 балла
6) В секции Services при добавлении избыточного текста в текстовую ячейку (ниже подзаголовков) текст, выходящий за размеры по макету, не скрыт: минус -3 балла
7) При добавлении в сетку с изображениями элементов за 12-м (проверяя, добавляем их сами) следующие за 12-м отображаются на странице - не реализовано ограничение видимых двенадцатью показанными в макете: минус -3 балла

**Comment by amoebiusss** [comment]
@sergiowork привет, хорошая работа! Есть несколько замечаний:

1. Относительно небольшие расхождения (~5px) по высоте в блоках в начале страницы привели к достаточно большому расхождению к концу страницы:
![image](https://user-images.githubusercontent.com/26903136/77319801-82db1b80-6d20-11ea-85b2-6bc53e827522.png)
![image](https://user-images.githubusercontent.com/26903136/77319934-bc138b80-6d20-11ea-901c-538617863971.png)

2. Достаточно большие расхождения в тексте блока Get a Quote:
![image](https://user-images.githubusercontent.com/26903136/77320130-0dbc1600-6d21-11ea-9450-2e26bd29d871.png)

3. В блоке Our services не обрезается избыточный текст в колонках:
![image](https://user-images.githubusercontent.com/26903136/77320295-5b388300-6d21-11ea-8f00-34ed1902fdf8.png)

4. Не работает скрытие "лишних" элементов в блоке Portfolio:
![image](https://user-images.githubusercontent.com/26903136/77320445-9e92f180-6d21-11ea-87c5-f0a569c2783d.png)

5. (этот пункт не влияет на оценку) Не стоит пренебрегать фоллбек-шрифтами. Сейчас в момент загрузки страницы на ней вообще нет текста, потому что нужный шрифт еще не загружен:
![image](https://user-images.githubusercontent.com/26903136/77319488-f4669a00-6d1f-11ea-8608-81bfeefbdeae.png)

Если бы параметры шрифта были заданы подобным образом: `font-family: Lato, sans-serif;`, то на время загрузки шрифта Lato текст отображался бы доступным системным шрифтом. Это более приемлемое поведение.

Итого:
100 - 3 (сдвиг блока Our Services) - 3 (сдвиг блока Get a Quote) - 3 (расхождения в тексте в блоке Get a Quote) - 3 (не обрезается лишний текст) - 3 (не скрываются лишние блоки в Portfolio) = **85 баллов**

**Comment by sergiowork** [comment]
Спасибо!!!
