### ISSUE TITLE
Cross-check 'Shelter.Desktop' - '0895000'

### ISSUE THREAD

**Issue by 0895000** [rolling-scopes-school/support#491]
Ссылка на депдлой проекта: https://rolling-scopes-school.github.io/0895000-JSFE2022Q1/shelter/pages/main/
Ссылка на репозиторий с проектом на GitHub: https://rolling-scopes-school.github.io/0895000-JSFE2022Q1/
Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app
Здравствуйте! Пропустил deadline из-за невнимательности, не посмотрел время deadline. Если есть возможность проверить работу, буду очень благодарен. Спасибо!

**Comment by WiiJoy** [comment]
Привет!

1. Кнопки карточек с животными при наведении на карточку не принимают активный вид - актуально для обеих страниц. Фоны для ховера карточек недоработаны (нет изменения цвета согласно макету)
2. Клик по лого на странице our pets не перекидывает на страницу main
3. Элемент Help the shelter не работает как якорная ссылка на блок Help страницы main
4. Стоит поработать с ховером элементов в принципе, тк почти все кнопки оставляют видимый border, которого быть не должно

Итог: **94** балла

Успехов в дальнейшем обучении!

**Comment by 0895000** [comment]
Спасибо!

**Comment by valerydluski** [comment]
выставил оценку
