### ISSUE TITLE
Cross-Check 'Shelter Desktop' - 'Alchi-Alchi'

### ISSUE THREAD

**Issue by Alchi-Alchi** [rolling-scopes-school/support#492]
Deploy: [Shelter](https://rolling-scopes-school.github.io/alchi-alchi-JSFE2022Q1/Shelter/index.html)
Repository: [github](https://github.com/rolling-scopes-school/alchi-alchi-JSFE2022Q1/tree/gh-pages)
Task: [Shelter task](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md)
Check form: [Form](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md#%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8-cross-check-%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1)
![image](https://user-images.githubusercontent.com/50367039/163467769-2f63e13f-9138-4ed7-9032-54159f336c1a.png)
![image](https://user-images.githubusercontent.com/50367039/163468101-d2e5224a-be19-4ee8-aad9-2ad22930ed4e.png)
По невнимательности засабмитил не ту ссылку. Проект не сложил в одну папку. В результате ошибка 404.  В дискорде помочь не смогли. В вопросах к админам видел ответ, что на первый кросс-чек пойдут навстречу и те кто неправильно засабмитил ссылку могут подать аппеляцию. Из четырёх проверяющих, контакты оставили лишь двое. Я сбросил им актуальный деплой. Один так и не проверил. Проверка другого не совсем объективна. Не засчитаны например ссылки в футере на иконках, и непонятки с интерактивностью кнопок в пагинации. Скриншот выше. Еще двое контактов не оставили.  По поводу деплоя. Когда мне написали, что не та ссылка, я создал новую ветку, сбросил туда те же файлы и задеплоил уже правильно. Файлы не менял. Можно сравнить их (старые файлы я не удалял, чтобы можно было посмотреть дату коммитов). Прошу проверить мою работу.

**Comment by ipipka** [comment]
### Итоговый балл: 85
__________
**Обнаруженные проблемы (не выполнены пункты требований):**

**Страница main**
[-1 балл] Страница main: Footer. Отступ от границ элементов до краев блока отличаются более чем на 20px
[-1 балл] Страница main: Our Friends. Отступы внутри набора отличаются более чем на 10px (кнопки вправо/влево сильно уехали относительно макета; из-за неверных размеров карточек с питомцами отличается расстояние между карточками и до кнопки Get to know the rest, лишние отступы внутри карточек вокруг изображений)
[-1 балл] Страница main: Help. Отступы внутри набора отличаются более чем на 10px (иконки во втором ряде не совпадают с макетом)
[-1 балл] Страница main: Footer. Отступы внутри набора отличаются более чем на 10px (ссылка с телефоном и картинка не попадают в макет)
[-1 балл] Страница main: Our Friends. Фоновый цвет карточек не совпадает с макетом
[-1 балл] Страница main: Help. Нарушена структура (например текст сверху, иконка снизу) в одном или более элементе (выравнивание иконки должно быть по центру относительно ее названия)
[-2 балла] Страница main: Footer. Элемент email не работает как ссылка на почтовый сервис. По условиям задания элемент - это икока + текст, у тебя ссылка только на иконке (и я ее заметила абсолютно случайно), так как остальные ссылки реализованы аналогично, то штрафую только за первую подобную ошибку, но будь внимательнее

**Страница our pets**
[-1 балл] Страница our pets: Header. Отступ от границ элементов до краев блока отличаются более чем на 20px (отступы в шапке отличаются на 43 пикселя)
[-1 балл] Страница our pets: Our Friends. Отступ от границ элементов до краев блока отличаются более чем на 20px (нижний отступ блока отличается от макета на 30 пикселей)
[-1 балл] Страница our pets: Our Friends. Отступы внутри набора отличаются более чем на 10px (из-за неверных размеров карточек с питомцами отличается расстояние между карточками и сетка карточек не попадает в макет)
[-1 балл] Страница our pets: Footer. Отступы внутри набора отличаются более чем на 10px (ссылка с телефоном и картинка не попадают в макет)
[-1 балл] Страница our pets: Our Friends. Отсутствует элемент или картинка (на кнопках постраничной навигации нет иконок `<<` `<` `>` `>>`)
[-2 балла] Страница our pets: Footer. Элемент email не работает как ссылка на почтовый сервис (аналогично главной странице, поэтому так же штрафую только за первую подобную ошибку)
__________
**Некоторые замечания, за которые не снижала балл:**

- У тебя очень много css написано через селектор id (`#id`). Во-первых, это плохо потому что данный селектор имеет высокую специфичность и его стараются не использовать, а обходиться классами (`.class`)
Во-вторых, сложилось ощущение, что ты перепутал и используешь id вместо class. Не забывай, что id на странице должен быть уникальным (на одной странице не должно быть двух элементов в одинаковым id) но при этом может быть много элементов с одинаковым class.
У тебя же на каждой карточке установлен `id="card"` (а надо бы использовать `class="card"`)
Чтобы отлавливать такие ошибки можно использовать валидатор https://validator.w3.org/

- В макете с дизайном есть отдельный фрейм, на котором собран весь интерактив для элементов (в том числе то, как должны выглядеть кнопки, пункты меню при наведении курсора (`:hover`)), твои эффекты не соответствуют тому, что "предлагает дизайнер"

- Градиент все-таки в реальной жизни лучше делать через css (`linear-gradient`, `radial-gradient`), потому что твоя картинка с градиентом весит 1,2 Мб и на мобильном интернете может загружаться очень долго (а это первый укран, пока картинка не загрузится светлый текс ты не прочитаешь)

- Размер блока с номером банковской карточки не совпадает с макетом, можно было использовать `display: inline-block;`

- С неактивных кнопок постраничной навигации нужно бы убрать `cursor: pointer`
__________
Обязательно разберись с id и class!
Неплохо, но есть куда стремиться! И чуть больше внимания к деталям макета :)
Успехов в дальнейшей учебе!

**Comment by valerydluski** [comment]
выставил оценку
