### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'DpAkyJ1A'

### ISSUE THREAD

**Issue by DpAkyJ1A** [rolling-scopes-school/support#496]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/dpakyj1a-JSFE2022Q1/shelter/pages/main
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/dpakyj1a-JSFE2022Q1/tree/shelter
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/
Сделал shelter до дедлайна и залил на гитхаб, а на следующий день дошел до кросчека и оказалось, что положить ссылку на проект уже нельзя( 
Прошу понять и простить. Впредь требования буду читать внимательнее)
Заранее спасибо!

**Comment by LidaChk** [comment]
## отметка - 97 баллов

Мне показалось,что работа очень хорошая и аккуратная. может быть поехала после адаптива, но тут ничего не поделаешь

-  main: Header и main: Not only -1 за все, чтобы совместить как миминум лого нужно 25 пикселей. остальное друг за друга цепряется. 
![image](https://user-images.githubusercontent.com/20344968/164078720-fb87880b-8016-4900-b6fc-4ed30698efc4.png)

- Блок main:Pets  -1 балла отступы от краев и -1 балл за отступы между заголовком и иконками.
![image](https://user-images.githubusercontent.com/20344968/164079230-67d66507-f572-4823-a560-88079ebece20.png)

- страница Pets - где то там 15 пикселей по горизонтали лишние, но в пределах допустимого.

По остальным требованиям - все прекрасно.

**Comment by valerydluski** [comment]
выставил оценку
