### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'Gorizontal'

### ISSUE THREAD

**Issue by Gorizontal** [rolling-scopes-school/support#497]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/gorizontal-JSFE2022Q1/shelter/pages/main/
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/gorizontal-JSFE2022Q1/tree/shelter
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/

Добрый день. 
Я не успел выполнить интерактив, и не сделал переход с одной страницы на другую, поэтому студенты не проверили вторую страницу и срезали баллы, а т.к. они были анонимами я не смог им написать (двое из 3х анонимы). Плюс не согласен с комментариями проверяющих. Такие как не совпадает фот и несовпадение в пикселях и шрифтах более чем на 10px и 4 px соответственно. Возможно это из за того что у меня не центрировался макет с серединой их экрана. 

Деплой второй свёрстанной страницы  https://rolling-scopes-school.github.io/gorizontal-JSFE2022Q1/shelter/pages/pets/

Ниже моя самопроверка
Ваша отметка - 65 балла(ов)
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Панель навигации есть, но не интерактивная
2) Элемент Our pets не работает как ссылка на страницу our pets
3) Элемент Help the shelter не работает как якорная ссылка на блок Help
4) Элемент Contacts не работает как якорная ссылка на блок Footer
5) Кнопка Make a Friend есть, но не интерактивная, или не работает как якорная ссылка на блок Our Friends
6) Кнопка "влево" есть, но не интерактивная
7) Кнопка "вправо" есть, но не интерактивная
8) Карточки не интерактивные
9) Кнопки Learn more не меняют цвет при наведении на карточку
10) Кнопка Get to know the rest есть, но не интерактивная, или не работает как ссылка на страницу our pets
11) Блок со ссылкой на банковский счет есть, но он не интерактивный, или не является ссылкой
12) Элемент email не работает как ссылка на почтовый сервис
13) Элемент телефон не работает как ссылка на сервис звонков
14) Хотя бы один элемент "локация" не работает как ссылка на google maps
15) Логотип есть, но не работает как ссылка на страницу main
16) Панель навигации есть, но не интерактивная
17) Элемент About the shelter не работает как ссылка на страницу main
18) Элемент Help the shelter не работает как якорная ссылка на блок Help страницы main
19) Элемент Contacts не работает как якорная ссылка на блок Footer
20) Кнопки пагинации есть, но кнопки "влево" интерактивные
21) Кнопки пагинации есть, но кнопки "вправо" не интерактивные
22) Кружочек страницы в пагинации интерактивный
23) Карточки не интерактивные
24) Кнопки Learn more не меняют цвет при наведении на карточку
25) Элемент email не работает как ссылка на почтовый сервис
26) Элемент телефон не работает как ссылка на сервис звонков
27) Хотя бы один элемент "локация" не работает как ссылка на google maps
Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.

ВОТ комментарии проверяющих:
Student 2
Score: 34
Ваша отметка - 34 балла(ов)
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Страница main: Header
2) Страница main: Not only
3) Страница main: About
4) Страница main: Our Friends
5) Страница main: Help
6) Страница main: In addition
7) Страница main: Footer
8) Страница main: Header
9) Панель навигации есть, но не интерактивная
10) Элемент Our pets не работает как ссылка на страницу our pets
11) Элемент Help the shelter не работает как якорная ссылка на блок Help
12) Элемент Contacts не работает как якорная ссылка на блок Footer
13) Кнопка Make a Friend есть, но не интерактивная, или не работает как якорная ссылка на блок Our Friends
14) Кнопка "влево" есть, но не интерактивная
15) Кнопка "вправо" есть, но не интерактивная
16) Карточки не интерактивные
17) Кнопки Learn more не меняют цвет при наведении на карточку
18) Кнопка Get to know the rest есть, но не интерактивная, или не работает как ссылка на страницу our pets
19) Блок со ссылкой на банковский счет есть, но он не интерактивный, или не является ссылкой
20) Элемент email не работает как ссылка на почтовый сервис
21) Элемент телефон не работает как ссылка на сервис звонков
22) Хотя бы один элемент "локация" не работает как ссылка на google maps
23) Создана страница our pets

Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.

Student 3
Score: 37
Фон первого экрана отличается
Нет h1 заголовка
About the shelter синего цвета
Нет hover эффектов
Нет страницы pets

Как итог 47 баллов.

**Comment by LidaChk** [comment]
**Итоговый балл: 63**
_________________________________________________________
Замечания:
- В градиент не попал. Неправильно прописан путь текстуры ( сняла 1 бал, так как одна ошибка по всем блокам где используется градиент)
 ![image](https://user-images.githubusercontent.com/20344968/163687489-127593e0-10b4-4685-ab1c-3f177bec6d43.png)
 background: url(noise_lines_transparent@2X.png), radial-gradient(100% 215.42% at 0% 0%, #5B483A 0%, #262425 100%), #211F20;
 
- Не скинуты стили ссылок, поэтому, там , где ссылка есть - остался синий цвет( за это не стала снимать, так как цвет в css правильно выставлен у элемента)
 ![image](https://user-images.githubusercontent.com/20344968/163687553-ea546fbf-2874-4082-b913-ee36e344f93e.png)
  
- По перфект пикселю все совпадает на обеих страницах.
- Интерактивность отсутвует полностью на обеих страницах.
- на странице Pets нет заголовка h1.
__________________________________________________________
**_Отчет из формы_**
Ваша отметка - 63 балла(ов)
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Панель навигации есть, но не интерактивная
2) Элемент Our pets не работает как ссылка на страницу our pets
3) Элемент Help the shelter не работает как якорная ссылка на блок Help
4) Элемент Contacts не работает как якорная ссылка на блок Footer
5) Кнопка Make a Friend есть, но не интерактивная, или не работает как якорная ссылка на блок Our Friends
6) Кнопка "влево" есть, но не интерактивная
7) Кнопка "вправо" есть, но не интерактивная
8) Карточки не интерактивные
9) Кнопки Learn more не меняют цвет при наведении на карточку
10) Кнопка Get to know the rest есть, но не интерактивная, или не работает как ссылка на страницу our pets
11) Блок со ссылкой на банковский счет есть, но он не интерактивный, или не является ссылкой
12) Элемент email не работает как ссылка на почтовый сервис
13) Элемент телефон не работает как ссылка на сервис звонков
14) Хотя бы один элемент "локация" не работает как ссылка на google maps
15) Логотип есть, но не работает как ссылка на страницу main
16) Панель навигации есть, но не интерактивная
17) Элемент About the shelter не работает как ссылка на страницу main
18) Элемент Help the shelter не работает как якорная ссылка на блок Help страницы main
19) Элемент Contacts не работает как якорная ссылка на блок Footer
20) На странице нет элемента <h1>
21) Кнопки пагинации есть, но кнопки "влево" интерактивные
22) Кнопки пагинации есть, но кнопки "вправо" не интерактивные
23) Карточки не интерактивные
24) Кнопки Learn more не меняют цвет при наведении на карточку
25) Элемент email не работает как ссылка на почтовый сервис
26) Элемент телефон не работает как ссылка на сервис звонков
27) Хотя бы один элемент "локация" не работает как ссылка на google maps
28) Фон сильно отличается от того, что на макете (не имеется ввиду смещенная картинка или градиент)

**Comment by valerydluski** [comment]
выставил оценку
