### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'nvfnvm'

### ISSUE THREAD

**Issue by nvfnvm** [rolling-scopes-school/support#499]
1. Ссылка на деплой проекта: https://rolling-scopes-school.github.io/nvfnvm-JSFE2022Q1/shelter/pages/main/index.html
2. Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/nvfnvm-JSFE2022Q1/tree/shelter
3. Ссылка на задание : https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
4. Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app/ 
5.
![image](https://user-images.githubusercontent.com/96121715/164784912-021fc913-c10e-4eab-a02d-5953c199e3e4.png)
![image](https://user-images.githubusercontent.com/96121715/164784945-bedcddc6-02d9-4999-a49b-97f79263f8ec.png)
![image](https://user-images.githubusercontent.com/96121715/164784994-d6f1a057-1913-4282-b6cb-fe50a7a268d1.png)
![image](https://user-images.githubusercontent.com/96121715/164785027-8b0c4b24-40d9-4c0b-a6f1-3a97a8911cea.png)
6. Оценка 0, т.к. информации о датах cross-chrck проверки не было ни в расписании, ни в задании. Проверил работы только 16 числа, думал, что проверка работ длится до конца недели. Прошу понять и простить меня. Впредь требования и сроки сдачи и кроссчеков буду читать внимательнее!
7. Балл 0

**Comment by ThorsAngerVaNeT** [comment]
Ваша отметка - 95 балла(ов)
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Страница main: Help
Комментарий проверяющего: Нижний ряд не совпадает с макетом
2) Страница main: Header
Комментарий проверяющего: Цвет ссылок при ховере не того цвета
3) Страница main: Our Friends
Комментарий проверяющего: При ховере карточек кнопки закрашиваются не в тот цвет
4) Страница our pets: Header
Комментарий проверяющего: Цвет активной ссылки не по макету
5) Страница our pets: Our Friends
Комментарий проверяющего: Цвет кнопок при ховере карточки не по макету.
Цвет кнопок "вправо" при ховере не по макету


Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.

**Comment by valerydluski** [comment]
выставил оценку
