### ISSUE TITLE
HTML/CSS Self Education : неверная оценка

### ISSUE THREAD

**Issue by Antonmchx** [rolling-scopes-school/support#5]
Hello!

My name is Anton. I have an issue with  HTML/CSS Self Education task. I have completed all required courses and challenges on HTML Academy and have gotten badges for them on my profile page https://htmlacademy.ru/profile/id1365667 .  But when I test this task in Auto-test I get 0 points and a message that not all of the required courses are passed. Please help 
![chrome_2CAuRMIeUl](https://user-images.githubusercontent.com/39671240/74504217-8bac2680-4f04-11ea-8e08-6160502cc2b6.png)

Thank you

**Comment by aleshkinpaul** [comment]
Добрый день

Проблема, аналогичная @Antonmchx. Просьба также проверить и подсказать, что делать в этой ситуации. Мой link: https://htmlacademy.ru/profile/id662269
