### ISSUE TITLE
Cross-Check: Submit 'Shelter. Desktop' - ' artem-gevondyan'

### ISSUE THREAD

**Issue by Artem-Gevondyan** [rolling-scopes-school/support#500]
1. https://rolling-scopes-school.github.io/artem-gevondyan-JSFE2022Q1/shelter/pages/main/
2. https://github.com/rolling-scopes-school/artem-gevondyan-JSFE2022Q1
3. https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1
4. Забыл засабмитить ссылку в [Cross-Check: Submit].

**Comment by madkorney** [comment]
привет!

# общая оценка 92 балла

хорошая работа, молодец. 



## страница Main

- header
  - весь блок header сдвинут по вертикали на 15 пикс. - в рамках разрешенных 20пикс, не снижал.
  - у меню неверный отступ справа , в итоге сдвиг меню на 70 пикс, **минус 1**
  - цвет шрифта меню должен быть primary, а вот при ховере должен менятся на #FFFFFF. **минус 1** 
  - лого по ТЗ должно быть интерактивное (cursor: pointer;), не снижал.
![сс_1_1](https://user-images.githubusercontent.com/1611438/165785734-a31a3b57-f3a3-42be-a8b8-fcc8d1f2ad63.jpg)


- start (Not only)
  - весь блок not only сдвинут по вертикали на 20пикс, не снижал.
  - текстовая часть - заголоввок, текст и кнопка - неверный отступ слева, сдвиг на 40пикс, **минус 1** 
  

- about
  - картинка петов и текстовый блок сдвинуты друг относительно друга по вертикали на 15 пикс.  это элементы сетки, где несовпадение допускается не больше чем на 10пикс.  **минус 1** 


- our friends
  - сам блок сдвинут по вертикали на 60 писк (результат несовпадений выше), но проверяем каждый блок отдельно по ПП.
  - позициционирование элементов внутри блока - отлично.
  - карточки - недочеты интерактивности. нет  изменения цвета фона, не появляется тень. другие эффекты есть, не снижал.
  - кнопки - не совсем верно при ховере - по макету рамка не должна быть видна при ховере, не снижал.
  - кнопка Get to know the rest - не работает как ссылка на стр Pets. **минус 1**
  
    
- help
  - позициционирование элементов внутри блока - отлично.
  
- donation
  - текстовый блокспозиционирован отлично, а вот бобик уехал по вертикали на 10 пикс, не снижал.
  
- footer
  - заголовки и картинка - спозиционированы отлично
  - адреса съехали на 5 пикс вниз
  - иконки почты и телефона  должны быть соответствующими ссылками. не снижал.
  
		

### итого за Main 60 - 5 = 55 баллов


## страница Pets

- header
  - лого - нет ссылки на страницу main, **минус 1**
  - меню - help the shelter должно вести на страницу main в блок #help, **минус 1**
  - так же как и в main - само меню сдвинуто на 70пикс. **минус 1**
  
  
- our friends
  - по самим карточкам - все замечания см выше. второй раз не снижал. 
  - позиционирование сетки и пагинации - практически идеально.
  - кнопки пагинации - ошибки интерактивности. кнопки влево должны быть disabled (без эффектов при ховере),ну и на кнопки вправо надо бы `cursor: pointer;` 
  - Кнопки "влево" интерактивные: **минус 1**.

  
  

- footer
  - все аналогично main. не снижал

### итого за Pets 40 - 3 = 37 баллов

**Comment by valerydluski** [comment]
выставил оценку
