### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'XXXmez'

### ISSUE THREAD

**Issue by XXXmez** [rolling-scopes-school/support#501]
Ссылка на деплой проекта:  https://rolling-scopes-school.github.io/xxxmez-JSFE2022Q1/shelter
Ссылка на репозиторий с проектом на GitHub : https://github.com/rolling-scopes-school/xxxmez-JSFE2022Q1/tree/gh-pages
Ссылка на задание : https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter
Ссылка на форму для проверки проекта: https://shelter-desktop-v1.netlify.app
Скриншот с оценками за cross-check:
![Inked163705513-dc46920f-9dd6-47d7-a9e6-59c46098b864_LI](https://user-images.githubusercontent.com/57019591/163705574-e468359b-c460-43f8-8f78-eba39773d02a.jpg)

Работа выполнена в полном объеме

Так получилось, что не имея доступа к дискорду по рабочим причинам, не мог узнать когда будет дедлайн cross-check проверок работ студентов. Так же раньше в расписание, если не путаю было написано, "Shelter. Desktop. Cross-check." то есть изначально я думал что как раз таки дедлайн всего и будет с концом недели. Да и больше нигде я не смог найти что-ли о дедлайне cross-check. Ну и получилось так, что восстановив дискорд, начал проверять работы, и после этого обратил внимание на score, где и заметил что уже у всех стоят баллы, за это задание. Прошу пожалуйста, проверить работу и выставить баллы.

**Comment by XXXmez** [comment]
А можно узнать почему отказ?

**Comment by igorlyatskiy** [comment]
В виде исключения за первый кроссчек **100**

**Comment by valerydluski** [comment]
выставил оценку
