### ISSUE TITLE
Cross-Check Shelter. Desktop - CNIkita

### ISSUE THREAD

**Issue by CNikita** [rolling-scopes-school/support#502]
Ссылка на деплой вашего проекта - https://rolling-scopes-school.github.io/cnikita-JSFE2022Q1/shelter/pages/main/
Ссылка на репозиторий с проектом на GitHub - https://github.com/rolling-scopes-school/cnikita-JSFE2022Q1/tree/shelter/shelter
Ссылка на задание - https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта (если такая есть) - https://shelter-desktop-v1.netlify.app/
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты) - ![Снимок](https://user-images.githubusercontent.com/50703446/163730540-8f71b016-a945-4c3f-9a66-0a952b2c7bbc.JPG)
Оценка в результате самопроверки с ее аргументацией - 100 (не заметил инфу о том что надо проверить работы до четверга и проверил в пятницу, был не внимателен, признаю, прошу понять и простить)
Балл за cross-check из вашего Score - 0

**Comment by WiiJoy** [comment]
Привет!

Привет! Отличная работа ;)

**Итог: 99 баллов**

1. На градиентном фоне нет узора, который должен быть (точнее, он предполагался, но он не загружается) -1
<img width="1530" alt="Снимок экрана 2022-05-08 в 13 07 15" src="https://user-images.githubusercontent.com/73646765/167291439-a7bd9284-f1a7-4410-af7e-4129a2a3cb39.png">

**Comment by valerydluski** [comment]
updated scores for the task
