### ISSUE TITLE
Cross-Check Shelter. Desktop - DeliasZen

### ISSUE THREAD

**Issue by DeliasZen** [rolling-scopes-school/support#503]
Ссылка на деплой вашего проекта - https://rolling-scopes-school.github.io/deliaszen-JSFE2022Q1/shelter/pages/main/
Ссылка на репозиторий с проектом на GitHub - https://rolling-scopes-school.github.io/deliaszen-JSFE2022Q1/shelter
Ссылка на задание - https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Ссылка на форму для проверки проекта (если такая есть) - https://shelter-desktop-v1.netlify.app/
Оценка в результате самопроверки с ее аргументацией - согласен с первым проверяющим: Сеточная структура элементов нарушена. 98 баллов.
Балл за cross-check из вашего Score - 0

Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты)- 
![image](https://user-images.githubusercontent.com/87693671/163876873-a4179b8a-11b8-41f2-8256-972d39b67799.png)

Проект был отправлен за несколько часов до наступления дедлайна (ссылки валидны и были проверены в течение 30 минут), работы других студентов в ходе кросс-чек проверки были рассмотрены 13.04, но по какой-то причине балл за работу не был проставлен. Прошу помочь в решении данной проблемы, а также указать на допущенную ошибку.

**Comment by igorlyatskiy** [comment]
Привет! Узнаю, почему отметки нет, и решим, что дальше делать
