### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - aleksa_mnk

### ISSUE THREAD

**Issue by aleksa-mnk** [rolling-scopes-school/support#505]
https://rolling-scopes-school.github.io/aleksa-mnk-JSFE2022Q1/shelter/pages/main/
https://github.com/rolling-scopes-school/aleksa-mnk-JSFE2022Q1/tree/shelter
https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md
Не засабмитила вовремя.

**Comment by LidaChk** [comment]
## отметка - 88 баллов

В принципе, неплохая работа. надо только разобраться с отступами. У вас все получится, удачи.

Не выполненные/не засчитанные пункты:

1. Страница main: In addition
  - Собака и описание расползлись к краям. Нет отступов.

2. Страница main: Footer
  - Комментарий проверяющего: Нет отступов от левого краев.
![image](https://user-images.githubusercontent.com/20344968/164075994-10d0ebcb-f0de-4657-9566-e6f8895e349a.png)


3. Страница main: In addition
  - justify-content:space-between;Но собакак и описание по маеку в центре, надо было center и gap. 
![image](https://user-images.githubusercontent.com/20344968/164075908-bc3ea6f6-a9ff-42cd-bc1c-5e6879c5fbf6.png)


4. Фон сильно отличается от того, что на макете (не имеется ввиду смещенная картинка или градиент)
  - нет текстуры шума в градиенте хедера и футера (сняла -1 за обе страницы)
  ![image](https://user-images.githubusercontent.com/20344968/163973323-fcc174bb-458f-46ae-a674-4624bd1749b0.png)

5. Сеточная структура элементов нарушена (не 5 элементов сверху, 4 снизу)
 - 6-3 на 1280.


6. Страница our pets: Our Friends
 - Отуступ от Top меньше на 40px , чем на макете

7. Страница our pets: Footer
 - Нет отступов от левого краев.

8. Страница our pets: Our Friends 
 - Отступы между карточками более чем на 10px больше чем на макете ( неправильный размер контейнера)

9. Логотип есть, но не работает как ссылка на страницу main
 - логотип оставляет на странице Pets

10. На странице нет элемента <h1>

**Comment by aleksa-mnk** [comment]
Спасибо!

**Comment by valerydluski** [comment]
@aleksa-mnk в следующий раз правильно пишите свой гит в названии

**Comment by valerydluski** [comment]
выставил оценку
