### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'VeronikaNemirova'

### ISSUE THREAD

**Issue by VeronikaNemirova** [rolling-scopes-school/support#506]
1. https://rolling-scopes-school.github.io/veronikanemirova-JSFE2022Q1/shelter/index.html
2. https://github.com/rolling-scopes-school/veronikanemirova-JSFE2022Q1/pull/6
3. https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1
4. https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md#%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8-cross-check-%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1
5. 
![cross-check1](https://user-images.githubusercontent.com/95870278/163960506-0067b345-da03-48dc-8929-b59bdc18ca54.png)
![cross-check2](https://user-images.githubusercontent.com/95870278/163960540-c218fe5c-2f73-4e9b-a667-3182e8b62c9b.png)
6. Оценка 0, т.к. информации о датах cross-chrck проверки не было ни в расписании, ни в задании. Я проверилп все присланные мне работы, но поздно (18.04.2022). Чисто случайно открыла cross-check. Review
7. Балл 0

**Comment by igorlyatskiy** [comment]
Информация была в анонсах. Будь внимательнее

**Comment by madkorney** [comment]
привет!

# общая оценка 92 балла

хорошая работа, молодец. здорово, что ты пыталась "улучшить" макет, однако в даном случае это противоречит цели этой задачи - научиться верстать по заданному макету.
в некоторых местах в итоге "улучшения" приводят к нарушению критериев оценки и пришлось снижать баллы.



## страница Main

- header
  - меню спозиционировано неверно - и по вертикали и по горизонтали. в рамках разрешенного.
  - цвет шрифта при ховере должен быть #FFFFFF , а не primary
  - лого-завернулька - не самое удачное решение)), см. про лого в our pets. формально можно было бы придраться, что после поворота расхождение с макетом больше разрешенных пикселей, но я не снижал.


- start (Not only)
  - небольшие погрешности в позиционировании, в рамках дозволенного
  - эффект при ховере на кнопку - не как в макете. (должен изменятся цвет кнопки), не снижал

- about
  - все хорошо.


- our friends
  - заголовок на месте, но блок слайдера и кнопка Get to know the rest смещены по вертикали на 23пикс. при этом кнопки вправо-влево тоже смещены относительно кускас карточками на 8 пикс. **минус 1**
  - эффект при ховере на кнопку Get to know the rest - не как в макете. (должен изменятся цвет кнопки), не снижал
  - эффект при ховере на кнопки вправо-влево - не как в макете. (должен изменятся цвет кнопки, а не ее размер), не снижал
  - неверно заданы отсупы в сетке карточек, из за этого пространство между ними на 17 пикс шире, чем необхоимо **минус 1**
  - карточки животных - много проблем. во первых стоило задать один класс всем карточкам на обоих страницах, иначе они работают по разному теперь.  pre-last и last можно было задать вторым классом, типа так:  
   `class="card  pre-last"` - тогда в css для `.card` ты бы описала внешний вид карточек, один раз для всех и ховер на карточки, а для класса `.pre-last` - только его исчезновение в нужный момент при адаптиве. а лучше такие классы как last вообще не добавлять, а работать с css псевдоклассами `.nth-child()` , `.nth-last-child()` либо вообще убирать карточки через JS.
  во-вторых, из за разных классов не выполняются требования по интерактиву для второй и третьей карточек.  должно быть так - при ховере над *карточкой* размер не изменяется, меняется фон, меняется подсветка *кнопки* learn more, появляется тень. отдельно ховер над кнопкой learn more не обрабатываем. у тебя у второй и третьей карточки не меняется кнопка при ховере на карточку. у карточек не закруглен бордер - от этого при ховере на карточку кошки наверху вылезаяют уголки, тк там прозрачный png, плюс фон изменяется на неверный цвет. итого по карточкам **минус 2**
  
  
- help
  - заголовок сдвинут на 35 пикс по горизонтали. **минус 1**
  - иконки в сетке не на местах. потому что , ты их ровняла через паддинги. а надо было и для флекса задать gap : 120px; и выравнивание элементов по центру.  **минус 1**
  
![image](https://user-images.githubusercontent.com/1611438/164711147-4876ac32-22cf-450e-a7bf-151820b7c640.png)


- donation
  - бобик спозиционирован отлично, а вот текстовый блок уехал по вертикали на 10 пикс, и внутри него неверные промежутки между абзацами. не снижал.
  - неверный эффект при ховере над кнопкой с номером пластик.карты - нет изменения фона кнопки, есть изменени размера. не снижал 

- footer
  - неправильно выровнены блоки по высоте отнсительно друг друга,  внутри блоков не совпадают отступы между текстовыми блокаами по вертикали. то и то  - в пределах 10 пикс - не снижал.
  - ссылки на карты должны по ТЗ открываться в новом окне
		

### итого за Main 60 - 6 = 54 балла


## страница Pets

- header
  - лого - из за того , что оно поворачивается - нижний левый угол получается не кликабельный. курсор все еще Pointer, но так как лого повернулось - то под курсором ссылки уже нет. это сбивает с толку, так не надо делать интерфейсы ) . не снижал
  - меню - при ховере подсветка не тем цветом, на этой странице наоборот более темным нужно подсвечивать. не снижал
  - хедер липкий , но, так как ты ему не прописала фон - то над остальной страницей висят только буквы. так тоже делать  не надо). не снижал.
  
  
- our friends
  - по самим карточкам - все замечания см выше. второй раз не снижал. 
  - позиционирование сетки и пагинации - почтибез расхождений
  - кнопки пагинации - ошибки интерактивности. кнопки влево должны быть disabled (без эффектов при ховере), кнопка с номером страницы - тоже не долдна менятся. 
  - Кнопки "влево" интерактивные: **минус 1**.
  - Кружочек страницы интерактивный: **минус 1**.
  
  

- footer
  - аналогично main. не снижал

### итого за Pets 40 - 2 = 38 баллов

**Comment by valerydluski** [comment]
выставил оценку
