### ISSUE TITLE
Cross-Check '6 - Feature Engineering and Selection' - 'alsing'

### ISSUE THREAD

**Issue by alsing** [rolling-scopes-school/support#508]
Ссылка на репозиторий с проектом на GitHub: https://github.com/alsing/ml-intro-rs-school/tree/main/6%20-%20Feature%20Engineering%20and%20Selection
Ссылка на задание: https://github.com/rolling-scopes-school/ml-intro/tree/2022/6_feature_engineering_selection
Скриншот с оценками за cross-check: 
![Screenshot (260)_LI](https://user-images.githubusercontent.com/90086293/164025766-b15ec0de-d0e7-4148-9de8-9cfc60c1d37c.jpg)
Оценка в результате самопроверки с ее аргументацией: работа была выполнена в полном объеме на максимальный балл (15), но анонимный проверяющий решил снять целую треть баллов, абсолютно не аргументируя это.
Балл за cross-check из вашего Score: 14.
Честно говоря, вопросы возникают не из-за меньшей итоговой оценки, а из-за факта такой проверки, так как снимать треть баллов за просто так - совсем ни в какие ворота не лезет...

**Comment by UladzislauSakalou** [comment]
ex 1 - 2 points.
ex 2 - 3 points.
ex 3 - 2 points
ex 4 - 5 points
ex 5 - 3 points
Total: 15 points

Небольшие замечания:
В задании 1 для CustomStandardScaler можно было бы реализовать обработку параметров with_mean, with_std, copy. Так как этого явно не указано в задании, то и баллов за это я не снижал)

В 5 задании лучше выставлять random_state для random_forrest чтобы результат был детерминирован. Иначе ассерт на accuracy будет проходить не при каждом запуске.

**Comment by dr-leto** [comment]
Updated in Scores
