### ISSUE TITLE
Cross-Check Shelter. Adaptive - kybikn

### ISSUE THREAD

**Issue by kybikn** [rolling-scopes-school/support#509]
Ссылка на деплой: https://rolling-scopes-school.github.io/kybikn-JSFE2022Q1/shelter/pages/main/index.html
Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/kybikn-JSFE2022Q1/tree/shelter
Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/README.md#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2
Ссылка на форму для проверки проекта (если такая есть): официальной нет, критерии описаны в задании.
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты):
![proveryaet-shalopay](https://user-images.githubusercontent.com/82117054/164500258-22f80b18-4c38-4770-8b01-c2dea771f19b.jpg)
Оценка в результате самопроверки с ее аргументацией: Оценка 100 баллов. Все сделано корректно, страницы полностью совпадают с макетами на всех разрешениях. Проверки на разных компьютерах и другие оценки это подтверждают. Даже работает мобильное меню и модальные окна.
Балл за cross-check из вашего Score: 80 от данного индивида.
Комментарий: у человека даже нет ни строчки в самой первой работе - CV. Его оценка моей работы - как раз в стиле описанных в документации наказуемых вариантов: https://docs.rs.school/#/cross-check-flow?id=%d0%9e%d1%82%d0%b2%d0%b5%d1%82%d1%81%d1%82%d0%b2%d0%b5%d0%bd%d0%bd%d0%be%d1%81%d1%82%d1%8c-%d0%b7%d0%b0-%d0%be%d1%82%d1%81%d1%83%d1%82%d1%81%d1%82%d0%b2%d0%b8%d0%b5-%d0%ba%d0%be%d0%bc%d0%bc%d0%b5%d0%bd%d1%82%d0%b0%d1%80%d0%b8%d1%8f-%d0%bf%d0%be%d1%8f%d1%81%d0%bd%d1%8f%d1%8e%d1%89%d0%b5%d0%b3%d0%be-%d0%bf%d1%80%d0%b8%d1%87%d0%b8%d0%bd%d1%83-%d1%81%d0%bd%d0%b8%d0%b6%d0%b5%d0%bd%d0%b8%d1%8f-%d0%b1%d0%b0%d0%bb%d0%bb%d0%be%d0%b2-%d0%b2%d0%be-%d0%b2%d1%80%d0%b5%d0%bc%d1%8f-cross-check-%d0%bf%d1%80%d0%be%d0%b2%d0%b5%d1%80%d0%ba%d0%b8

**Comment by igorlyatskiy** [comment]
Разница в баллах недостаточна, человека проверим
