### ISSUE TITLE
Mentoring issues

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/support#51]
Этот тред создан для решения проблем возникающих в процессе менторинга. Например
1) Не могу связаться с ментором для прохождения technical screening, так как в его профиле не указаны контакты 
2) Контакты есть, но ментор не отвечает более 3х дней
3) Ментор не может больше менторить
4) ...

**Comment by AlexGabrielov** [comment]
Не дали нового ментора. После регистрации на собеседование мне присвоили ментора, я ему написал, и он сказал что произошла ошибка и мне должны дать другого, если не дадут до 28го то написать в суппорт

**Comment by AlexeyTeterin** [comment]
У меня такая же ситуация как у @AlexGabrielov. Не назначен новый ментор после того, как предыдущий сказал что был назначен по ошибке.

**Comment by orangetomato** [comment]
Связался со своим ментором - он сказал, что будет отказываться от менторства. Будет ли замена?

**Comment by dreadwood** [comment]
Точно такая же проблема как у @AlexGabrielov и  @AlexeyTeterin: 26 марта написал ментору, он сообщил 

> небольшая ошибка произошла, проверь сервис, тебе должны были назначить другого ментора. Если до завтра не будет - напиши в саппорт

На текущий момент в ЛК ментор не появился

**Comment by alexeyvalko** [comment]
у меня такая же проблема, связался с ментором, а он сказал, что отказался от менторинга.

**Comment by VVMig** [comment]
Здравствуйте, такая проблема: мой ментор не отвечает более 3-х дней (написал ему на почту, так как по номеру телефона не нашел его в телеграмме)

**Comment by dzmitry-varabei** [comment]
@VVMig попробуй позвонить по телефону

**Comment by rsodst** [comment]
Здравствуйте, ментор не отвечает более недели. https://github.com/alexeysych как быть?

**Comment by Krudda** [comment]
Добрый день. Назначенный мне ментор сказала что хотела взять не более 3-х студентов. Трое у неё уже записаны в Score, я получаюсь четвертым. Интервью с этим ментором прошел. Как мне быть в данной ситуации, как продолжить обучение с ментором?

**Comment by dzmitry-varabei** [comment]
@rsodst будет другой ментор
@Krudda ждать другого ментора

**Comment by KonstantinMinsk** [comment]
Добрый день! Помогите плиз! в разделе  Interviews у меня отображался ментор, я написал ему в скайп в пятницу, сейчас ментора нету в разделе  Interviews, в скайп он не выходит, контакты я не сохранял, что делать???
и в score меня тоже нету, я просто не могу понять причину!)

**Comment by SkulOne** [comment]
Здравствуйте, связался с назначенным мне ментором по контакту который он оставил, однако мне ответили, что я ошибся. Как быть? Ссылка гитхаб ментора: https://github.com/inxhale1

**Comment by dzmitry-varabei** [comment]
@KonstantinMinsk теперь все хорошо?

**Comment by dzmitry-varabei** [comment]
@SkulOne По распределению ты попал к @inxhale1. Если ментор тебе не отвечает, могу направить тебя в waitlist

**Comment by SkulOne** [comment]
@dzmitry-varabei Он не то что не отвечает, видимо он оставил некорректные данные для связи и я просто не могу с ним связаться. Давайте попробуем подождать пока тут, если уж совсем не отзовётся то перенаправляйте в waitlist.

**Comment by dzmitry-varabei** [comment]
@SkulOne Проверил. Он мне тоже не отвечает с 26 марта. Ментора отчислил. Ты в waitlist

**Comment by inxhale1** [comment]
Привет ребята, мой телеграм -https://t.me/aexhalex

**Comment by inxhale1** [comment]
@dzmitry-varabei @SkulOne привет ребята, мой телеграм - https://t.me/aexhalex

**Comment by dzmitry-varabei** [comment]
@inxhale1 спасибо! @SkulOne свяжись плиз с Александром. В RS APP интервью создал.

**Comment by dreadwood** [comment]
Появился новый ментор  ~ 31 марта (Yevgeny Yakushev, https://t.me/emworkss), списался с ним, договорились на интервью на 6 апреля. 6 апреля не доступен ни в телеге, ни в скайпе. Ждал сутки, что объявится. Сейчас захожу в интерфейс app.rs.school, ментора там нет. Походу это значит, что я остался без ментора, да?)

**Comment by Dalnogirl** [comment]
Назначенный мне ментор Eugene Litvinchuk оставил из контактов только скайп, сколько я ни пытался, связаться с ним у меня не получилось. Хотелось бы получить еще какие-нибудь контакты этого человека, ссылки на его социальные сети. Спасибо.

**Comment by dzmitry-varabei** [comment]
@dreadwood да :( c менторами пока напряг, waitlist разбирают медленно, но разбирают. Так что жди

**Comment by dzmitry-varabei** [comment]
@Dalnogirl попросил ментора самому тебе написать

**Comment by HalimHamidov** [comment]
I can't figure out what is going with mentor screening . Help me please
I have several times contacted 
@vadzim @taroxlin but they didn't response properly and didn't solve my problems.

Here I had an interview with automatically chosen mentor  but he didn't choose me & he replied very late. 
``
Interviewer    
Status    Result
 ashurbeyli     Completed    No, but good student
```
What should I do then? First time it was like this

> Hej, what's up? I've got the updated information regarding the interview.
> But I've seen that you are no longer in my interviews list, so I don't know what's going on.
> Have you passed interview already?

BitHulk30.03.2020
hello
BitHulk30.03.2020
Start Date: 2020-04-07
Description: Link
postponed

**Comment by AlinaSuhorebraya** [comment]
Здравствуйте! связалась с ментором, а он сказал, что не записывался сюда и что не может менторить

**Comment by dzmitry-varabei** [comment]
@AlinaSuhorebraya подскажи, пожалуйста, github ментора которому ты писала

**Comment by AlinaSuhorebraya** [comment]
astarovojtov

**Comment by AlinaSuhorebraya** [comment]
Подскажите, сейчас ждать нового ментора, если произошла такая ситуация?

**Comment by dmitriy-homza** [comment]
Здравствуйте. Сегодня после обеда и перераспределения появился новый ментор. Спустя какое-то время этот ментор исчез и там по-прежнему пусто. Спросил у своего знакомого, у него остался его прежний ментор, который был назначен после обеда. 
Извините, если беспокою попросту, пытался найти ответ, появится ли новый ментор, но нашел лишь ещё одного человека с аналогичной проблемой.

**Comment by RomanGovor** [comment]
Аналогичная ситуация с комментирующим выше(днем был ментор, потом произошло перераспределение и ментора нового не поставили)

**Comment by dzmitry-varabei** [comment]
@AlinaSuhorebraya у тебя новый ментор после повторного распределения
@dmitriy-homza @RomanGovor у вас тоже будет ментор, только чуть позже

**Comment by Eansable** [comment]
Добрый день! Написал ментору, он сказал что: "Мне просто двоих закинул рм, а больше я брать не планировал."
Как я понял, что по ошибке попал к нему

**Comment by VZaleski** [comment]
Добрый день! Подскажите, пожалуйста, если в списке interviews нет ментора( хотя по баллам я вроде как проходил к кому-то на интервью), то я попадаю в следующую партию для прохождения интервью или ментора вовсе не будет?

**Comment by dzmitry-varabei** [comment]
@Eansable понял :( надежда на вторую волну
@VZaleski сейчас не скажу, надо ждать минимум понедельника

**Comment by KantyshVitali** [comment]
вчера в rsapp записался на интервью + указал контакты в профиле, но со мной никто не связался( подскажите что делать в таком случае?

**Comment by dzmitry-varabei** [comment]
@KantyshVitali ты в waitlist, остается ждать и надеяться

**Comment by spoonya** [comment]
Здравствуйте. Можно узнать почему у меня уже второй раз просто так пропадает собеседование?

**Comment by MikhailBiltsevich** [comment]
При распределении 9 и 10 ноября ментор не был назначен. Дня два назад увидел, что назначили, однако ментор ответил, что группу уже набрал. Стоит ли ещё на что-то надеяться или нет? (Потенциальный ментор  bahaakhm)

**Comment by cekip88** [comment]
Здравствуйте, ментор написал что я хорошо прошел интервью, но он уже набрал нужное количество студентов, и мое дело передаст в координационный центр, чтобы меня взял другой ментор, но никакой информации я больше не получил, что делать?

**Comment by iliyaking46** [comment]
новое обсуждение - https://github.com/rolling-scopes-school/support/issues/243

**Comment by Sia0Pol** [comment]
Здравствуйте, мой ментор сегодня отказался от менторства вообще, мне нужен новый чтобы пройти интервью
он: [daniglyk](https://app.rs.school/profile?githubId=daniglyk)
я: sia0pol (SiaPolischuk#1600 в дискорде)

**Comment by dzmitry-varabei** [comment]
@Sia0Pol понял, ты в waitlist

**Comment by TakeFives** [comment]
Добрый вечер,
мой ментор не отвечает более 3х дней 
менор: detonatorx#2691
Что делать в этом случае?

**Comment by shalick** [comment]
Добрый день. 
Мой интервьювер Stanislau Kashenkou долго не указывал контакты, на дискорд который был указан в rsschool-cv не отвечал. Позже указал контакты с новым дискордом, удалось с ним связатся и пройти собеседование за несколько дней до дедлайна. Во время собеседования многие вопросы указаные в заданий, например: структуры данных, вес селекторов и т.д. не спрашивал, не задал практическую задачу. Из того что он спрашивал я плохо ответил ему только на вопрос о промисах и асинк авэйтах (которые так понимаю должны спрашивать на следующем собеседовании). Получил 35 баллов и результат No. Когда я спросил его в чём дело он сказал, что: 
"Я дальше курс вести не буду, студентов не осталось
пойду на новый
Скинул рекомендацию твою, там нормально рекомендовал, может кто возьмет". 
Так понимаю он поставил мне No так как больше не будет вести курс и с расчётом на то что по его рекомендации меня кто-то дожен взять. Прошла неделя. Так понимаю меня никто не взял из wait list и ментора у меня нет. 
Это означает что я не смогу успешно закончить курс из-за решения интервьювера больше не продолжать этот набор.

**Comment by dzmitry-varabei** [comment]
> TakeFives
@coolmanben
@coolmanben @TakeFives @shalick  Вы в waitlist, продолжайте учиться и готовьтесь к следующему интервью по corejs (его проводят для всех студентов, вне зависимости от наличия ментора)

**Comment by shalick** [comment]
> @coolmanben @TakeFives @shalick Вы в waitlist, продолжайте учиться и готовьтесь к следующему интервью по corejs (его проводят для всех студентов, вне зависимости от наличия ментора)

я уже вторую неделю в wait list. уже один дедлайн профукал. 
если у меня нет ментора - мне не поставят оценки за задания и у меня нет шансов получить нужные баллы для окончания курса.  
почему вы ставите в конце смайл? находите смешной ситуацию? 
если интервьювер не взял никого из тех кого собеседовал и не продолжает этот курс, а я вам сообщаю что он сам мне говорит, что специально поставил No и отправил в wait list не думаете что с этим что-то нужно сделать?

**Comment by Kotkiller** [comment]
Добрый день. Мне назначили ментора для проведения technical screening, я с ним связался, но он ответил, что не будет проводить интервью. Как мне быть? Вот его контакты: 
E-mail: viachaslau.latushkin@gmail.com
Telegram: viachaslaulatushkin
Skype: viachaslau.latushkin
Notes: Skype: viachaslau.latushkin Tg: viachaslaulatushkin
LinkedIn: https://www.linkedin.com/in/viachaslau-latushkin/

**Comment by liestreadt** [comment]
Добрый день. Мне назначили ментора на интервью CoreJS 1 и я написал ему ещё 4-го января, но до сих пор он даже не прочитал мои сообщения (ни в ТГ, ни в дискорде). Я даже написал СМС по номеру, который указан в его аккаунте RSS, но тоже никакой реакции. Также я попытался связаться с его студентами, но они тоже не отвечают. Подскажите пожалуйста, как мне пройти это обязательное интервью?  
Контакты интервьюера:  
- RSS: https://app.rs.school/profile?githubId=yuriiboltukov
- Telegram: YuriiBol
- Notes: +79667490502
- GitHub: [yuriiboltukov](https://github.com/yuriiboltukov)
- Discord: @kolomiha(YuriiBoltukov)#4088

**Comment by Mardon07** [comment]
Здравствуйте, мне назначили ментора, но его контакты не работают, что мне делать? Вот его github https://github.com/yurakuzmich

**Comment by maxvy50rs** [comment]
Здравствуйте 
Написал назначенному ментору, но он не отвечает более 3 дней.

**Comment by DenWouk** [comment]
Добрый день! Распределён на интервью к ментору https://github.com/pavelpronchatov. Связался с ним, он сказал что у него сейчас много работы и не сможет провести интервью. 
![IMG_6469](https://github.com/rolling-scopes-school/support/assets/126710400/461e741c-5448-4e1e-a809-0e7a47295059)
![IMG_6470](https://github.com/rolling-scopes-school/support/assets/126710400/fb7521ff-67e3-4ad1-b19a-fbf4b76193de)
(В первый раз написал ему в дискорд 31 мая, но ответа не было, повторно написал в телеграм 2 июня и получил этот ответ).
Что я должен или могу сделать для того чтобы пройти интервью у другого ментора? (позиция на момент распределения 184).
Спасибо.

**Comment by juli-ko** [comment]
Добрый день. Назначенный ментор не отвечает более 3 дней.

**Comment by maxvy50rs** [comment]
Здравствуйте. Дедлайн по Technical Screening через 3 часа от настоящего момента, 9.06.23 я проходил интервью с назначенным ментором, но он до сих пор не выставил оценку (и я так и не понял, собирается ли он быть мне ментором). Фиксирую это здесь на всякий случай.
