### ISSUE TITLE
Cross-Check 'Shelter. Adaptive - 'polinagrits' 

### ISSUE THREAD

**Issue by PolinaGrits** [rolling-scopes-school/support#511]
1. https://rolling-scopes-school.github.io/polinagrits-JSFE2022Q1/shelter/pages/main/
2. https://github.com/rolling-scopes-school/polinagrits-JSFE2022Q1/tree/gh-pages
3. https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2
4. https://shelter-adaptive.netlify.app/
5. 
![image](https://user-images.githubusercontent.com/92051235/164614874-252f2a58-3f3a-4a29-8384-2e46a29229b5.png)
![image](https://user-images.githubusercontent.com/92051235/164614922-9e6e2ac7-cdd2-4688-9baf-d122d1f1b5bb.png)
6. В результате самопроверки я ставлю себе 100 баллов, т.к. все выполнено согласно требованиям. С макетом может быть расхождение на 1-2 пикселя. По поводу пагинации и ее смещения влево могу сказать, что проверка проводится на контрольных точках, но на всех промежуточных величинах **рекомендуется** следовать принципам расположения тех или иных элементов, не отмеченных в конкретных требованиях, так что и здесь ошибки я не вижу.
7. 88/100

**Comment by WiiJoy** [comment]
Ваша отметка - **97 балла(ов)**
Отзыв по пунктам ТЗ:

Частично выполненные пункты:
1) На странице main для ширины страницы 768px <= width < 1280px выполняются необходимые условия, нет нарушений отступов или размеров при проверке соответствию макету main-768 на ширине экрана 768px — 3 балл(а)
Комментарий проверяющего: Ухо у картинки с собакой отличается на 21px: https://imageup.ru/img10/3958530/snimok-ekrana-2022-06-20-v-145825.jpg


Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.
