### ISSUE TITLE
Cross-Check 'Shelter. Adaptive' - 'Voojin'

### ISSUE THREAD

**Issue by Voojin** [rolling-scopes-school/support#515]
1. https://rolling-scopes-school.github.io/voojin-JSFE2022Q1/shelter
2. https://github.com/rolling-scopes-school/voojin-JSFE2022Q1/tree/shelter
3. https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter
4. https://shelter-adaptive.netlify.app/
5. 
![score](https://user-images.githubusercontent.com/59932451/164645533-6c6a6ecc-bed2-480c-91c0-f237a6fa1291.jpg)
6. У меня выходило 100\100. Если смотреть верстку как указано в таске https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream1/shelter/responsive.png?raw=true то горизонтальной прокрутки нет, а если и появляется после смены размера через ввод значения px, то после обновления страницы все встает на место. 
С фоном блоков "На странице our pets допускается:
1) фоны блоков растягиваются на всю ширину окна, при этом сам контент находится в центре экрана и соответствует макету;
2) верстка занимает максимальную ширину 1280px и соответствует макету, центрируется с равными отступами слева и справа, свободное пространство заполнено любым цветом;"
На 1280 вроде не всю страницу, а про дальнейшие разрешения экрана в условиях только про "Фон растянут на Header и блок Not only." Тут или я завтыкал и не так понял или так)
7. 59 / 100  работу проверили 3 человека
Заранее спасибо!

**Comment by valerydluski** [comment]
студент не активен закрываю
