### ISSUE TITLE
Cross-Check 'Shelter. Adaptive' - 'alexej-ilyutik'

### ISSUE THREAD

**Issue by Alexej-Ilyutik** [rolling-scopes-school/support#516]
1. https://rolling-scopes-school.github.io/alexej-ilyutik-JSFE2022Q1/SHELTER/pages/main/
2. https://github.com/rolling-scopes-school/alexej-ilyutik-JSFE2022Q1/tree/shelter
3. https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter
4. https://shelter-adaptive.netlify.app/
5.
![Screenshot_1](https://user-images.githubusercontent.com/77629253/164650167-06b222e4-045c-4ba9-a198-f216cff2e2d4.png)
6.  Свою работу оцениваю на 80 баллов. Т.к. из недочетов только появление нижнего скролла в браузере Mozilla. В Chrome все сделано хорошо.
7. На данный момент за это задание у меня 50 баллов.
Спасибо за проверку моей работы!

**Comment by valerydluski** [comment]
баллы в скор
