### ISSUE TITLE
Cross-Check 'Shelter. Adaptive' - 'Jafr0'

### ISSUE THREAD

**Issue by Jafr0** [rolling-scopes-school/support#519]
Ссылка на деплой: https://rolling-scopes-school.github.io/jafr0-JSFE2022Q1/shelter/pages/main/index.html
Ссылка на репозиторий с проектом на GitHub: https://github.com/rolling-scopes-school/jafr0-JSFE2022Q1
Ссылка на задание: https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter
Ссылка на форму для проверки проекта: https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter#%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8-cross-check-%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2
Скриншот с оценками за cross-check:
![image](https://user-images.githubusercontent.com/87328407/164689608-7eac90ec-dd9d-41a0-a438-64e076329742.png)

Здравствуйте. Проверило 3 из 4.
Student 2 поставил оценку 0 и сказал, что ничего не уменьшается и вся верстка просто рушится даже в хроме. Можно ли это перепроверить? Потому что у меня и у двух остальных вроде бы все хорошо.

**Comment by igorlyatskiy** [comment]
Невозможно проверить когда был последний коммит, задание выполняется в одной ветке
