### ISSUE TITLE
Cross-Check 'Shelter.Adaptive'-'VladZhmyshenko'

### ISSUE THREAD

**Issue by ghost** [rolling-scopes-school/support#521]
1. Ссылка на деплой:  https://rolling-scopes-school.github.io/vladzhmyshenko-JSFE2022Q1/shelter
2. Ссылка на репозиторий с моим выполненным заданием: https://github.com/rolling-scopes-school/vladzhmyshenko-JSFE2022Q1/tree/gh-pages/shelter
3. Ссылка на задание: https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2
4. Скриншоты с оценками проверяющих:
![1](https://user-images.githubusercontent.com/91334001/164766317-0e7c02d1-1093-42f3-976e-71470b7292fa.png)
![2](https://user-images.githubusercontent.com/91334001/164766330-d1e4d786-a7ef-459e-895a-06740aeca881.png)
5. Самооценка моей работы:  62 балла. У меня лишь не был сделан адаптив на 320px. Я никаких претензий к этому человеку не имею(проверяющий №3). Не знаю, каким образом он проверял.
6. По итогам кросс-чека я получил 35 баллов

**Comment by igorlyatskiy** [comment]
Коммиты после дедлайна
