### ISSUE TITLE
Cross-Check 'Shelter.Adaptive' - 'IvanMakarishchev'

### ISSUE THREAD

**Issue by IvanMakarishchev** [rolling-scopes-school/support#522]
[Ссылка на деплой вашего проекта.](https://rolling-scopes-school.github.io/ivanmakarishchev-JSFE2022Q1/shelter/pages/main/index.html)
[Ссылка на репозиторий с проектом на GitHub.](https://github.com/rolling-scopes-school/ivanmakarishchev-JSFE2022Q1/tree/shelter-part2)
[Ссылка на задание.](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2)
[Ссылка на форму для проверки проекта (если такая есть).](https://shelter-adaptive.netlify.app/)
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
![image](https://user-images.githubusercontent.com/95377483/164878890-f4dfccec-f24c-4789-a865-a1283c06e5ce.png)
![image](https://user-images.githubusercontent.com/95377483/164878897-66366f65-9496-497e-984b-8e9778396e63.png)
![image](https://user-images.githubusercontent.com/95377483/164878906-548513b7-17d4-4ea0-83e5-6f86e8d8500d.png)

Оценка в результате самопроверки с ее аргументацией.
Не проверял, пока делал казалось что все условия выполнены, с оценкой проверяющих спорить не буду. Аппеляцию подаю только для начисления балла, так как видимо не засчитало из за не полностью выполненной проверкой с моей стороны. Мне нужно было срочно выезжать из города. Перед выездом успел проверить только 2 работы, оставшиеся две работы проверил после переезда, но видимо уже было поздно. Переезжали по причине постоянных обстрелов моего города, я из Николаева (Украина).

Балл за cross-check из вашего Score.
0

**Comment by ipipka** [comment]
### Итоговый балл: 100
Замечаний нет, все требования задания Shelter.Adaptive выполняются, расхождений с макетом на контрольных точках нет

**Comment by valerydluski** [comment]
updated scores for the task
