### ISSUE TITLE
Cross-Check 'Shelter.Adaptive' - 'VanDanya'

### ISSUE THREAD

**Issue by VanDanya** [rolling-scopes-school/support#524]
1. Ссылка на деплой: https://rolling-scopes-school.github.io/vandanya-JSFE2022Q1/shelter/pages/main/index.html
2. Ссылка на репозиторий с моим выполненным заданием: https://github.com/rolling-scopes-school/vandanya-JSFE2022Q1/tree/gh-pages/shelter
3. Ссылка на задание: https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2
4. Скриншоты с оценками проверяющих:
![1](https://user-images.githubusercontent.com/95961117/164896636-8b42f09b-0567-4cda-b929-22b36d46cc37.jpg)
![2](https://user-images.githubusercontent.com/95961117/164896637-4b15cc23-3249-491d-99c2-a39d235e9903.jpg)
![3](https://user-images.githubusercontent.com/95961117/164896640-adcf8d8d-e2df-44d4-a658-b4f2026ca781.jpg)
![4](https://user-images.githubusercontent.com/95961117/164896643-cc0cc6f0-5c22-4156-8eed-f37f8069ea9a.jpg)
5. Самооценка моей работы: не менее 56.
6. По итогам кросс-чека я получил 25 баллов.

**Comment by igorlyatskiy** [comment]
Коммиты после дедлайна

**Comment by VanDanya** [comment]
> Коммиты после дедлайна

4 буквы добавил
