### ISSUE TITLE
Cross-Check Shelter. DOM - MaxNotDead#1376

### ISSUE THREAD

**Issue by MaxKnyazev** [rolling-scopes-school/support#529]
A link to your deployed project: https://rolling-scopes-school.github.io/maxknyazev-JSFE2022Q1/shelter/pages/main/
A link to the project repository on Github: https://github.com/rolling-scopes-school/maxknyazev-JSFE2022Q1/tree/shelter
A link to the task: https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter
A link to the assessment form (if there is any): https://shelter-dom.netlify.app/
A screenshot of cross-checking marks (reviewers' contacts must be hidden):
![image](https://user-images.githubusercontent.com/44132686/165751496-611d7b4e-42b3-4a01-b96b-ea9180a9238f.png)

Student 1
Score: 95
Отзыв по пунктам ТЗ:
Частично выполненные пункты:
1) Проверка выполнения указанных для Carousel требований — 5 балл(а)
Комментарий проверяющего: при 768px <= width < 1280px и  width < 768px формируется по 3 карточки, но видно только нужное количество. 

*Не совсем понятно замечание проверяющего. Возможно при переходе на новое разрешение экрана страница не была перезагружена.*

Student 2
Score: 90
- При открытии модального окна на меньшем размере крестик не доступен, поэтому закрыть модальное окно не представляется возможным. Скролл может быть в самом попапе, если по высоте он больше, чем окно браузера 
- При уменьшении экрана пункты навигации в бургер меню не центрированы, верхний пункт залазит на логотип.  
- При размере 768 карточки слайдера пролистываются пропуская некоторых питомцев 
- В модальном окне текст не соответствует размерам в макете
- Высота самого модального окна при 320px больше, чем на макете
- Странно ведет себя кнопка пролистывания в слайдере, становиться ненадолго не активной, пропадает ховер и курсор
- Кнопки в слайдер при ховере не того цвета, более темного
- При нажатии на About the shelter в навигации не должна быть якорная ссылка к одноименному блоку
- Бургер меню на второй странице должно быть белого цвета, ссылки навигации и логотип черные, в соответствии со стилем страницы
- Ссылка кредитной карты не должна скроллиться на верх
Итого: -10 баллов

*Не согласен с оценкой проверяющих, так как в условиях проверки на этом этапе нет ни одного пункта, за которые можно снизить баллы из вышеперечисленных. Связаться со студентами не получилось, так как они решили остаться анонимными.*

**Comment by valerydluski** [comment]
не правильное оформление
