### ISSUE TITLE
Cross-Check 'Shelter. DOM' - 'dzinakor'

### ISSUE THREAD

**Issue by DzinaKor** [rolling-scopes-school/support#536]
Deploy: https://rolling-scopes-school.github.io/dzinakor-JSFE2022Q1/shelter/pages/main/index.html

RepoGit: https://github.com/rolling-scopes-school/dzinakor-JSFE2022Q1

Task: https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter

Check form: https://shelter-dom.netlify.app/

Screenshots: 
![image_2022-04-29_20-49-53](https://user-images.githubusercontent.com/90131387/165989024-3707b034-ad2b-43c2-9b9f-f9b91f314cd7.png)
![image_2022-04-29_20-50-10](https://user-images.githubusercontent.com/90131387/165989030-de89c66c-f2e6-41a3-9fdc-11dddeec1aa7.png)

Score after self-test: 94/100 с оценкой проверяющих преимущественно согласна.
2 студента из 4 в проверке кросс-чек попросили проверить их работу в четверг. Сдуру не поставила для начала хоть что-то, думала проверю всё залпом в четверг, а вчера совсем слегла, было очень плохо, проспала весь день и до утра. Сегодня утром проверила, но уже прошёл дедлайн. По итогу  и свои 94 балла не получила за шелтер.дом и ребят по кросс-чеку подвела.  Задание было сложным, очень много сил потратила, чтобы вытянуть. Всегда стараюсь относиться к сокурсникам с пониманием, поэтому решила попробовать попросить понять и простить меня на первый раз.

Score: 0/100

**Comment by WiiJoy** [comment]
Привет!

**Итог: 82 балла**

1. Иконка бургера вместо меню должна появляться на 767px (<768px), но у тебя это происходит только на 750px
<img width="802" alt="Снимок экрана 2022-05-08 в 10 41 36" src="https://user-images.githubusercontent.com/73646765/167286875-c069babd-77d1-4191-acfe-3c06c192bbb2.png">
В остальном к бургеру не придраться - идеальное исполнение :)

2. Без снятия баллов: стоит немного посидеть и поразбираться с попапом, тк при закрытии он периодически выбивает ошибку привязки цвета бэкграунда через js. Это не очень круто и требует решения :)

3. А вот такого быть не должно (-1)
<img width="374" alt="Снимок экрана 2022-05-08 в 11 02 27" src="https://user-images.githubusercontent.com/73646765/167287251-64bf3593-bf8c-4bed-a51b-f5357beb8df4.png">

4. Картинка питомца в попапе должна отсутствовать на любой ширине, меньшей 768px. По аналогии с меню, у тебя перестройка осуществляется только на 750, что не есть хорошо и нарушает конкретное требование. (-2)

5. Нет анимации карусели (-3)

6. В карусели в двух соседних слайдах не должно быть повторяющихся питомцев. У тебя это требование не выполняется. (-3)

7. На ширине в 1279px уже должно быть 2 карточки питомцев, а не 3. На ширине в 767px должна быть одна карточка, а не 2. (-3)
<img width="1314" alt="Снимок экрана 2022-05-08 в 11 13 01" src="https://user-images.githubusercontent.com/73646765/167287643-eb45b3fd-5168-4711-9c50-95e58dd09e65.png">
<img width="808" alt="Снимок экрана 2022-05-08 в 11 12 32" src="https://user-images.githubusercontent.com/73646765/167287642-cfaaab3c-c089-4e00-9231-8f885889fb76.png">

8. При перезагрузке страницы не меняется порядок карточек на первой странице. (-3)

9. На ширине в 1279px уже должно быть 6 карточек питомцев, а не 8. На ширине в 767px должно быть 3 карточки, а не 6. (-3)
<img width="686" alt="Снимок экрана 2022-05-08 в 11 18 02" src="https://user-images.githubusercontent.com/73646765/167287827-312c9f9c-6d69-4e12-8440-21677b596511.png">
<img width="481" alt="Снимок экрана 2022-05-08 в 11 18 20" src="https://user-images.githubusercontent.com/73646765/167287826-b1a45840-6bad-444d-83f0-465134771aaf.png">

**Comment by DzinaKor** [comment]
Привет!

Ура!
Спасибо за проверку🙏🏻

нд, 8 мая 2022, 12:22 карыстальнік Vitaliy Rogozin ***@***.***>
напісаў:

**Comment by valerydluski** [comment]
updated scores for the task
