### ISSUE TITLE
Cross-Check 'Shelter. DOM' - 'daniilfilipcenko382'

### ISSUE THREAD

**Issue by daniilfilipcenko382** [rolling-scopes-school/support#537]
Deploy: https://rolling-scopes-school.github.io/daniilfilipcenko382-JSFE2022Q1/shelter/pages/main/index.html 

RepoGit: https://github.com/rolling-scopes-school/daniilfilipcenko382-JSFE2022Q1

Task: https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter

Check form: https://shelter-dom.netlify.app/

![image](https://user-images.githubusercontent.com/39215365/165991194-5ba120fe-2908-4a75-bbc8-374c2ec89f53.png)
Score after self-test: 92/100 с оценкой проверяющих согласен.
проверил 4 работы, 1 не засчиталась(по невнимательности, внес 2 раза оценку 1му студенту). Я проверял в 23:00-00:00 часов. Правда, мне нет смысла обманывать, я старался сделать максимум. 2 ночи почти не спал. Очень прошу понять-простить, начислить баллы. Скрины, оценок
![image](https://user-images.githubusercontent.com/39215365/165991432-b0693231-a5d0-4fb9-ac33-1a4d172dbf04.png)
![image](https://user-images.githubusercontent.com/39215365/165991447-94b648d3-74c7-4157-82df-444bca8cc0a7.png)
![image](https://user-images.githubusercontent.com/39215365/165991461-4f71e4bf-dbb3-4c0e-ac9f-8815a8a183b5.png)
![image](https://user-images.githubusercontent.com/39215365/165991521-9842a193-67b5-40c3-a6f8-58d7ecdbcfff.png)
Больше не повторится.

**Comment by WiiJoy** [comment]
Деплой недоступен, лейбл накинул лейбл invalid

<img width="1679" alt="Снимок экрана 2022-05-08 в 11 25 08" src="https://user-images.githubusercontent.com/73646765/167287997-c027251b-bfb9-4d8b-81bb-20dcf72637fa.png">
