### ISSUE TITLE
Cross-Check 'Shelter. DOM' - kettl96

### ISSUE THREAD

**Issue by kettl96** [rolling-scopes-school/support#539]
Deploy: https://rolling-scopes-school.github.io/kettl96-JSFE2022Q1/shelter/pages/main/index.html

RepoGit: https://github.com/rolling-scopes-school/kettl96-JSFE2022Q1/tree/gh-pages

Task: https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-3

Check form: https://shelter-dom.netlify.app/

Screenshots
![check](https://user-images.githubusercontent.com/89872725/166095002-0dd5e348-716b-4b96-bad1-acb784a384be.jpg)
:

Добрый день. прошу перепроверить мою работу т.к попап полностью рабочий, возможно какая то была ошибка тк с первым проверяющим связались и он перепроверил все работает. ( и баллы за этот пункт 15, а не 60)

**Comment by WiiJoy** [comment]
Привет :)

**Итог: 79 баллов**

Итак, погнали:

1. Бургер меню появляется только на 760px, когда по ТЗ - с 767. Фиг с ним, но не очень хорошо :)
<img width="455" alt="Снимок экрана 2022-05-07 в 21 11 09" src="https://user-images.githubusercontent.com/73646765/167266642-1ee8ef03-10df-4716-bc65-1a9227debdc9.png">

2. На странице Pets нет затемнения при активном бургер меню (-3)
3. В догонку к предыдущему пункту - бургер меню не закрывается при кликах вне меню (-3)
<img width="331" alt="Снимок экрана 2022-05-07 в 21 13 57" src="https://user-images.githubusercontent.com/73646765/167266790-b1b0bf95-4070-499c-99bc-4e6a012c50f0.png">

4. Попап не открывается при клике на кнопку карточки, хотя должен открываться в любом месте клика (-3)
5. Прокрутка основной страницы при открытом попапе не отключена (-3)
6. При наведении на затемненную область у кнопки закрытия окна не появляется ховер-эффект (-3)
7. Анимация не карусельная, а fade. Фиг с ним, пропускаем
8. При листании карусели периодически выпадают дублирования питомцев на соседних слайдах, чего быть не должно (-3)
9. В пагинации при обновлении страницы не генерируется новая последовательность (-3)
