### ISSUE TITLE
Cross-Check 'Singolo DOM & Responsive' - 'ElfimovArtem'

### ISSUE THREAD

**Issue by ElfimovArtem** [rolling-scopes-school/support#54]
**Ссылка на работу** - https://github.com/ElfimovArtem/singolo

Добрый день! Я прекрасно понимаю, что баллы по данному заданию не сильно улучшат мое положение в таблице, но все же хочется справедливости и сразу благодарю за потраченное время.

**Оценка в результате самопроверки** - примерно 94 балла. Есть некоторые недочеты, которые я и сам знаю : 1. После клика по табам, в блоке Portfolio, перестает работать взаимодействие с картинкой в данном блоке, но изначально эта функция работает (соответственно минус 3 балла). 2. Переход по ссылке происходит не плавно в меню блока Header - тоже забыл это сделать, по этому тоже минус три балла.

**Балл за cross-check из вашего Score** - 57 баллов.

Дополнительно хочу заметить, что данная оценка просто испорчена по причине явного неуважения одним из проверяющих (Сергей (Hotja)). Изначально он создал конфликт на ровном месте - из-за того, что моя работа не была задеплоена (По этому факту проконсультировался с Админами и мне предоставили информацию о том, что обычная ссылка на репу на Гите имеет место быть). После разъяснительной беседы с данным проверяющим, он согласился все-таки проверить работу повторно, но слишком придирался ко всему и , как мне кажется, безосновательно. Многие минусы, которые он проставил, являются совершенно выдуманными. 

Например: 

1. "Header работает некорректно. Шапка не прилипла к верху экрана и при скроле не видна. Так же при скроле не меняется позиция активной ссылки а сохраняется тупо та на которую нажали. (-6)" - на сколько я знаю этого пункта не было в ТЗ к данной таске.

2. "Header Не соответствие макету, наличие старой навигационной панели и отсутствие новой (**например на 716px**) (-3)" - опять-таки, на сколько я понимаю, мы проверяем макет в нескольких контрольных точках (375рх и 768рх) - этот человек проверял совершенно в других контрольных точках. 

и тд... дальше не вижу смысла продолжать копировать данные комментарии, т.к. все остальные минусы выставлены исходя из неверных контрольных точек. 

**По данной ситуации прошу принять меры. Очень надеюсь, что данная оценка будет аннулирована и мой балл в таблице изменится в лучшую сторону. Заранее очень благодарен!**

**Comment by Student-Java** [comment]
Оценка в скоре 88 баллов, под условия апелляция твоя работа не подпадает. Извини
