### ISSUE TITLE
Cross-Check '8_clustering' DmitryShuvalov

### ISSUE THREAD

**Issue by DmitryShuvalov** [rolling-scopes-school/support#541]
1. [Ссылка на репозиторий с решением:](https://github.com/DmitryShuvalov/ml_intro-8clustering) 
2. [Ссылка на само задание](https://github.com/rolling-scopes-school/ml-intro/tree/2022/8_clustering)
3. Формы для оценки задания нет
4. Скриншоты оценок:
![screen1](https://user-images.githubusercontent.com/62016699/166268112-35b3abde-ba47-4175-9847-fab9b363b273.png)
)
![screen2](https://user-images.githubusercontent.com/62016699/166268337-8b49c533-9c63-4778-a841-5eb40329a6cc.png)

Описание проблемы: в submit вставил не ссылку на решение, а ссылку на само задание (ошибся вот-так глупо). Однако в дискорде сразу же после выявления проблемы отписался. На RS-SCHOOL в профиле подвязан мой github, так что найти было можно. Но сам виноват и вины с себя не снимаю ))

Оценка в результате самопроверки с ее аргументацией: работа была выполнена в полном объеме на максимальный балл (12),
Балл за cross-check из вашего Score: Расчётный cross-check будет 9, а хотелось бы 12

**Comment by wervlad** [comment]
Хорошая работа! Окончательное решение в таком случае за админами. Моя оценка следующая:
1. 0.75 / 0.75
2. 5.75 / 5.75
3. 2 / 2
4. 4 / 4

TOTAL 12.5 / 12.5

**Comment by UladzislauSakalou** [comment]
12.5. Все задания выполнены.(Максимум за модуль 12 баллов)
