### ISSUE TITLE
Cross-Check 'Shelter. Adaptive' - nick-2805

### ISSUE THREAD

**Issue by Nick-2805** [rolling-scopes-school/support#542]
1. Ссылка на деплой: https://rolling-scopes-school.github.io/nick-2805-JSFE2022Q1/shelter/pages/pets/index.html
2. Ссылка на репозиторий с моим выполненным заданием: https://github.com/rolling-scopes-school/nick-2805-JSFE2022Q1
3. Ссылка на задание: https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2
4. Оценка 0, так как забыл сделать сабмит виполненого задания вовремя

**Comment by Nick-2805** [comment]
Добрый вечер! Подскажите, почему мою аппеляцию отклонили?

**Comment by igorlyatskiy** [comment]
Не засабмиченные задание не проверяются
