### ISSUE TITLE
Cross-Check RSS Virtual Keyboard - evelin-mart

### ISSUE THREAD

**Issue by evelin-mart** [rolling-scopes-school/support#544]
1. Deploy: https://evelin-mart.github.io/rsschool-projects/virtual-keyboard/
2. Repo: https://github.com/evelin-mart/rsschool-projects/tree/virtual-keyboard
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/virtual-keyboard/virtual-keyboard-en.md
4. Form: https://virtual-keyboard-2022q1.netlify.app/
5. Screenshot: 
![image](https://user-images.githubusercontent.com/95069824/168221156-95d81730-43d2-4f77-8f47-b80d8e230f40.png)
6. Score: 110
  - the generation of DOM elements is implemented. body in the index.html is empty: 
![image](https://user-images.githubusercontent.com/95069824/168221563-2e56e9f5-d588-4860-a287-7f272f7d87c8.png)
  - animation of pressing a key is implemented: pressed key is highlighted by color and scale
![Снимок экрана (84)](https://user-images.githubusercontent.com/95069824/168222008-31f7255e-883b-4bee-922e-ceee51672c1f.png)
  - other criteria are implemented
7.  Current score: 102

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/174290940-897e4bf1-8b4d-4654-b534-35f861436e18.png)
