### ISSUE TITLE
Cross-Check 'RSS Virtual Keyboard' - 'vikuli'

### ISSUE THREAD

**Issue by vikuli** [rolling-scopes-school/support#545]
1. Deploy: https://vikuli.github.io/Virtual-Keyboard/keyboard/src/
2. Repo: https://github.com/vikuli/Virtual-Keyboard
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/virtual-keyboard/virtual-keyboard-en.md
4. Form: https://virtual-keyboard-2022q1.netlify.app/
5. Screenshot:
![score](https://user-images.githubusercontent.com/96022090/168234485-c5f26659-a38f-4411-9a19-ac692c0ed407.png)
6. Score: 110 баллов:
    1) body в index.html пустой, DOM-элементы генерируются из js (допускается наличие тега script внутри body)
    2) Нажатие клавиши на физической клавиатуре выделяют соответствующие клавиши на виртуальной. Проверяются нажатия букв, цифр, знаков препинания, backspace, del (если есть), enter, shift, alt, ctrl, caps lock, space, стрелки
    3) Реализовано переключение виртуальной клавиатуры между английским и другим языком. Выбранный язык сохраняется после перезагрузки страницы. На странице указана комбинация клавиш для смены языка
    4) В поле ввода (текстовое поле) вводятся символы при клике мышью по кнопкам виртуальной клавиатуры и при нажатии кнопок на физической клавиатуре
    5) Реализована анимация нажатия кнопок виртуальной клавиатуры
    6) В исходниках js используются функции ES6+ (classes, property destructuring, arrow function expressions, let/const, default parameters, rest, spread, etc)
    7) Используется ESLint
    8) Выполнены все требования к репозиторию: - работа выполнена в личном репозитории; - исходный код находится в отдельной ветке; - основная ветка (master/main) пустая, или содержит только файлы README.md и/или .gitignore - наименования коммитов выполнены согласно рекомендациям (содержат префиксы init, feat и т.д.) - Pull Request из ветки разработки в основную ветку (master/main) открыт и оформлен по установленной форме - Pull Request и, соответственно, ветка разработки не содержит закомментированного кода, автоматически сгенерированных файлов и папок сборки (в тч папки dist) или вашей операционной системы
7. Current score: 85

**Comment by WiiJoy** [comment]
Ваша отметка - **80.5 балла(ов)**

Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) В поле ввода (текстовое поле) вводятся символы при клике мышью по кнопкам виртуальной клавиатуры и при нажатии кнопок на физической клавиатуре
Комментарий проверяющего: Считаю условие невыполненным, тк ввод после обновления страницы возможен только либо с виртуальной клавиатуры, либо только с физической.
Ошибка, опять же, в обработке событий. Правильная логика: отслеживание событий нажатия физических кнопок и считывание значения соответствующей ей виртуальной, которое уже должно попадать в текстовую область.
Видео ошибки записано, при необходимости загружу

Частично выполненные пункты:
1) Нажатие клавиши на физической клавиатуре выделяют соответствующие клавиши на виртуальной.
Проверяются нажатия букв, цифр, знаков препинания, backspace, del (если есть), enter, shift, alt, ctrl, caps lock, space, стрелки — 8 балл(а)
Комментарий проверяющего: Выполнено частично, тк кнопки с буквами при вводе с физической клавиатуры не выделяются на виртуальной при определенных обстоятельствах
Видео ошибки записано, при необходимости загружу

2) Реализовано переключение виртуальной клавиатуры между английским и другим языком. Выбранный язык сохраняется после перезагрузки страницы. На странице указана комбинация клавиш для смены языка — 7 балл(а)
Комментарий проверяющего: Выполнено частично, тк не всегда отрабатывает смена языка при нажатиях комбинации клавиш. Решается отслеживанием правдивости модификаторов, например, ev.shiftKey && ev.altKey. При вводе с физическое клавиатуры язык не меняется - исправляется отслеживанием значения нажатой физической кнопки с ее виртуальной версии и выводом в текстовую область значения именно виртуальной кнопки

3) Выполнены все требования к репозиторию:
 - работа выполнена в личном репозитории;
 - исходный код находится в отдельной ветке;
 - основная ветка (master/main) пустая, или содержит только файлы README.md и/или .gitignore
 - наименования коммитов выполнены согласно рекомендациям (содержат префиксы init, feat и т.д.)
 - Pull Request из ветки разработки в основную ветку (master/main) открыт и оформлен по установленной форме
 - Pull Request и, соответственно, ветка разработки не содержит закомментированного кода, автоматически сгенерированных файлов и папок сборки (в тч папки dist) или вашей операционной системы — 5 балл(а)
Комментарий проверяющего: Папка node_modules не должна быть в репозитории :)


Комментарии к выполненным пунктам:

1) body в index.html пустой, DOM-элементы генерируются из js
(допускается наличие тега script внутри body)
Комментарий проверяющего: Ставлю выполненным, НО! Прописывать ручками структуру html в js - не очень крутая затея)


Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.

**Comment by valerydluski** [comment]
updated scores for the task
