### ISSUE TITLE
Cross-Check 'RSS Virtual Keyboard' - 'IhorNovikow'

### ISSUE THREAD

**Issue by IhorNovikow** [rolling-scopes-school/support#546]
1.Deploy: https://ihornovikow.github.io/RSS-Virtual-Keyboard/src/
2.Repo: https://github.com/IhorNovikow/RSS-Virtual-Keyboard
3.Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/virtual-keyboard/virtual-keyboard-en.md
4.Form: https://virtual-keyboard-2022q1.netlify.app/
5. Screenshot: ![skrin123](https://user-images.githubusercontent.com/94797785/168239615-dfac9cf6-3ea6-4d69-8310-762969e7e335.png)
7. Score: 110
Отзыв по пункам ТЗ:
Полностью выполненные пункты:

1) body в index.html пустой, DOM-элементы генерируются из js (допускается наличие тега script внутри body)

2) Нажатие клавиши на физической клавиатуре выделяют соответствующие клавиши на виртуальной. Проверяются нажатия букв, цифр, знаков препинания, backspace, del (если есть), enter, shift, alt, ctrl, caps lock, space, стрелки

3) Реализовано переключение виртуальной клавиатуры между английским и другим языком. Выбранный язык сохраняется после перезагрузки страницы. На странице указана комбинация клавиш для смены языка

4) В поле ввода (текстовое поле) вводятся символы при клике мышью по кнопкам виртуальной клавиатуры и при нажатии кнопок на физической клавиатуре

5) Реализована анимация нажатия кнопок виртуальной клавиатуры

6) В исходниках js используются функции ES6+ (classes, property destructuring, arrow function expressions, let/const, default parameters, rest, spread, etc)

7) Используется ESLint

8) Выполнены все требования к репозиторию: - работа выполнена в личном репозитории; - исходный код находится в отдельной ветке; - основная ветка (master/main) пустая, или содержит только файлы README.md и/или .gitignore - наименования коммитов выполнены согласно рекомендациям (содержат префиксы init, feat и т.д.) - Pull Request из ветки разработки в основную ветку (master/main) открыт и оформлен по установленной форме - Pull Request и, соответственно, ветка разработки не содержит закомментированного кода, автоматически сгенерированных файлов и папок сборки (в тч папки dist) или вашей операционной системы

9) Присутствуют ошибки, связанные с исполняемым кодом (НЕ УЧИТЫВАЮТСЯ ошибки типа "favicon.ico: Failed to load resource: the server responded with a status of 404" или "Error with Permissions-Policy header: Origin trial controlled not enabled: interest-cohort"), или ошибки и предупреждения при выполнении проверки eslint. Проверка линтером осуществляется следующим образом: 1. Репозиторий проверяемой работы клонируется к себе на компьютер. 2. В редакторе кода открывается директория склонированного репозитория, выполняется переключение на ветку разработки 3. Выполняется установка зависимостей командой npm i (или npm install) 4. Выполняется запуск проверки линтером соответствующей командой. НЕ УЧИТЫВАЮТСЯ ошибки типа "Expected linebreaks to be LF but found CRLF linebreak-style"

Все пункты выполнены полностью!
8. Current score: 96

**Comment by valerydluski** [comment]
updated scores for the task
