### ISSUE TITLE
Cross-Check 'Virtual Keyboard' - 'GodPFM'.

### ISSUE THREAD

**Issue by GodPFM** [rolling-scopes-school/support#547]
1.  Deploy: https://godpfm.github.io/Virtual-keyboard/task/index.html
2.  Repo: https://github.com/GodPFM/Virtual-keyboard
3. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/virtual-keyboard/virtual-keyboard-en.md
4. Form: https://virtual-keyboard-2022q1.netlify.app/
5. Screenshot: 
![image](https://user-images.githubusercontent.com/86543246/168328755-ad290c40-9151-4768-8678-f94f5a0eadf1.png)
6. Score: 110/110
[+] реализована генерация DOM-элементов и body в index.html пустой изначально (может находится только тег script): +20. В данном случае не было требования выполнения через webpack, а также то, что она должна быть полностью динамической. В моем случае body в index.html не содержит других тегов, кроме script. 
[+] использование в коде фишек стандарта ES6 и выше: +15.
7. Current scope: 98

**Comment by LidaChk** [comment]
### Ваша отметка - **103 балла(ов)**
Отзыв по пунктам ТЗ:

Частично выполненные пункты:
1) Нажатие клавиши на физической клавиатуре выделяют соответствующие клавиши на виртуальной.
Проверяются нажатия букв, цифр, знаков препинания, backspace, del (если есть), enter, shift, alt, ctrl, caps lock, space, стрелки — 8 балл(а)
Комментарий проверяющего: _нажатие правого альт вызывает одновременную анимацию его и левого ctrl;_

2) В поле ввода (текстовое поле) вводятся символы при клике мышью по кнопкам виртуальной клавиатуры и при нажатии кнопок на физической клавиатуре — 10 балл(а)
Комментарий проверяющего: _Backspase и del работают корректно только в конце строки. выделенные текст, удаление в слередине слов и строк работает некорректно.
А также символы добавляются только в конец строки - даже если курсор установлен в другом месте._


Комментарии к выполненным пунктам:

1) body в index.html пустой, DOM-элементы генерируются из js
(допускается наличие тега script внутри body)
Комментарий проверяющего: _такая реализация просто подгон под условие. формально все выполнено. Вы не генерите дом элементы, для этого вебак использовать необязательно. Целиком body запихивать в innnerHtml - это мягко говоря, не очень._


Все оставшиеся пункты выполнены и не имеют комментариев проверяющего.

**Comment by valerydluski** [comment]
updated scores for the task
