### ISSUE TITLE
Cross-Check Singolo. DOM & Responsive - RockStar666by

### ISSUE THREAD

**Issue by RockStar666by** [rolling-scopes-school/support#55]
Ссылка на деплой: https://rockstar666by.github.io/singolo/
Ссылка на репозиторий: https://github.com/RockStar666by/singolo
Оценка в результате самопроверки составляет 82 балла.

"Если нажимаем на область, где нет телефонов и их теней, а какой либо из экранов телефонов меняет свое состояние, ставим -3. Т.е. событие, которое происходит вне области, не должно срабатывать." ( При клике слева/справа от телефонов экран меняет состояние) -3

1020 px
"расстояния сильно отличаются от ожидаемых, больше чем на 5px (исключение - стрелки слайдера, они могут центрироваться по высоте)"
(в блоке слайдер расстояние в макете между телефонами 97px, у Вас же 104px) -3

768 px Portfolio
"Расстояние между элементами должно быть 20px. Если отступы отличаются больше, чем на 5px, ставим -3."
(Горизонтальный отступ между элементами 14px) -3

375 px Header
"Если задний фон прокручивается, несмотря на открытое меню, это не считается ошибкой. Однако, если будет происходить скролл заднего фона, то ссылки должны становиться актиынвми соотвественно. Если ссылки не подсвечиваются, ставим -3. Не обращаем внимание на этот пункт при выполнении пункта (3)."
(Ссылки не активны) -3

Portfolio
"Если сетка не двух-колоночная (2х4), ставим -3."
(Сетка 2*6) -3

Footer
"Если иконки соц сетей не центрируются в блоке footer, ставим -3."
(Из-за 'margin' отступ слева 91px cправа 130px) -3

Итого: 100 - 3 - 3 - 3 - 3 - 3 - 3 = 82

Балл за кросс-чек из Score: 61 балл. 
Оценка за кросс-чек не соответствует ожиданиям. Один из экзаменаторов поставил 0 баллов, мотивируя это тем, что ссылка на проект нерабочая. Хотя у других людей всё в порядке.
![Снимок](https://user-images.githubusercontent.com/52502654/78459769-07844d00-76c4-11ea-8f81-62319a7649d7.PNG)

**Comment by Student-Java** [comment]
Надо оформить заявку согласно правил: https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f

**Comment by RockStar666by** [comment]
Заявка откорректирована согласно правил

**Comment by Student-Java** [comment]
Я видел, начинал проверять твою работу - у меня было сильное несоответствие макету на 768 и 365, не уверен что будет 82 балла как ты себя оцениваешь. К сожалению, у меня сейчас нет времени на полноценную проверку - может кто-то другой из активистов тебя проверит.

**Comment by Alexey-Koren** [comment]
В течение двух часов всё проверю

**Comment by Alexey-Koren** [comment]
> Должно быть сделано меню с переключением. Активным становится выбранный элемент меню, предыдущий становится неактивным. Страница должна при этом переходить по якорям в заданную позицию с плавной анимацией. При переходе и скролле, активным должен становиться элемент меню того блока, на котором находится текущая позиция.

1. Элементы меню, при скролле не становятся активными. -3

> Если нажимаем на область, где нет телефонов и их теней, а какой-либо из экранов телефонов меняет свое состояние, ставим -3. Т.е. событие, которое происходит вне области, не должно срабатывать.

2. При клике слева/справа от телефонов экран меняет состояние. -3

> ❗ Хоть при растягивании экрана на 4k, хоть при уменьшении до 320px не должна теряться целостность приложения. При плавном изменении размера, мы не учитываем точных подсчетов расположения элементов. Однако, в первую очередь, не должен появляться горизонтальный скролл. Во-вторых, элементы ни при каких обстоятельствах не должны начать вылазить за рамки экрана. Если появляется горизонтальная полоса прокрутки, или контент начинает вылазить за пределы экрана, ставим -5.

3. На ширине в 320px вылезают за экран элементы (кнопки portfolio, фото и текст в about us, форма). -5
https://imgur.com/a/QYCjAYT

Плюс при ширине <1020px начинают ехать черные экраны телефонов, но за это баллы не снимаются.
https://imgur.com/a/z6tJw2n

768px:

> Расстояние между элементами должно быть 20px. Если отступы отличаются больше, чем на 5px, ставим -3.

4. Горизонтальный отступ между элементами 14px. -3

375px:

> Если задний фон прокручивается, несмотря на открытое меню, это не считается ошибкой. Однако, если будет происходить скролл заднего фона, то ссылки должны становиться активными соответственно. Если ссылки не подсвечиваются, ставим -3. Не обращаем внимание на этот пункт при выполнении пункта (3)."

5. Ссылки не активны -3

> Если сетка не двух-колоночная (2х4), ставим -3.

6. Сетка 2x6. -3

> Если иконки соц сетей не центрируются в блоке footer, ставим -3.

7. Ссылки не центрованы. -3

Итоговая оценка: 77

**Comment by dzmitry-varabei** [comment]
@Alexey-Koren спасибо!
