### ISSUE TITLE
 Cross-Check Virtual keyboard - firdavs-projects

### ISSUE THREAD

**Issue by firdavs-projects** [rolling-scopes-school/support#551]
1. Deploy: https://firdavs-projects.github.io/virtual-keyboard/
2. Link to the repository: https://github.com/firdavs-projects/virtual-keyboard
3. Link to the task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/virtual-keyboard/virtual-keyboard-en.md
4. Screenshot: ![image](https://user-images.githubusercontent.com/67782167/169195488-f8ea7b19-0721-4bdc-851b-263444b17c8a.png)
5. 95/110:
- eslint-config-airbnb-base warnings: -15
6. 0/110
- Не провел cross-chek вовремя
- Здравствуйте. Открыл апелляцию в надежде восстановить хоть частично свои баллы.
Я в данный момент работаю и на курс я трачу все свои выходные (Сб/Вс) и обычно с этим режимом справляюсь с задачами, но не хватает времени сидеть на дискорде. А именно там как я теперь понял указывались дедлайны по кросс-чекам (а не в расписании, та вещь по которой я планирую все свои задачи), а я как обычно думал что дедлайн кросс-чека как и других тасков общие во вторник 4:00AM. И с такими знаниями я проводил иногда кросс-чеки после работы лишь бы это не занимало время в выходные и было побольше времени на свои задачи. И благодаря этому я неоднократно выполнял кросс-чеки вовремя но теперь как я понял лишь из за удачи.. 
- В этот раз я провел кросс-чек 14-05-2022 в субботу (в свой выходной день рано утром) и даже не догадывался что дедлайн уже прошел:
![image](https://user-images.githubusercontent.com/67782167/169197622-95493b28-7050-4495-84b4-7b8a2bae365d.png)
- А дальше как обычно уже занимался своими задачами дедлайны которых во вторник.
Вывод. Ошибка с моей стороны, что я не был осведомлен по дедлайнам кросс-чеков из за своего плотного графика. Хочу чтобы хоть частично была возможность возместить свои потерянные баллы. Теперь я точно знаю дедлайны по кросс-чекам. Буду очень вам благодарен если возможно пересмотреть мои баллы за эту работу.

**Comment by dzmitry-varabei** [comment]
@igorlyatskiy Прими, пожалуйста эту апелляцию (по правилу "понять и простить один раз в течении курса").

**Comment by WiiJoy** [comment]
Привет!

Свои ошибки ты и так знаешь: eslint-config-airbnb-base warnings: -15 :)

Итоговая оценка - **95 баллов**

**Comment by valerydluski** [comment]
updated scores for the task
