### ISSUE TITLE
Cross-Check 'HTML builder' - KZhukow

### ISSUE THREAD

**Issue by KZhukow** [rolling-scopes-school/support#557]
1. Ссылка на деплой вашего проекта.
Данный проект не предусматривает деплой
2. Ссылка на репозиторий с проектом на GitHub.
https://github.com/KZhukow/HTML-builder
3. Ссылка на задание.
https://github.com/EvgeniiMal/HTML-builder
4. Ссылка на форму для проверки проекта (если такая есть).
Формы для проверки нет
Есть инструкция: https://github.com/EvgeniiMal/HTML-builder/wiki/HTML-builder-crosscheck
5. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
![app rs school_course_student_cross-check-submit_course=js-fe-2022Q1 taskId=1502](https://user-images.githubusercontent.com/99538672/170638849-c9ebed51-789d-4d3d-98bf-64139a90b388.png)

6. Оценка в результате самопроверки с ее аргументацией.
Оценка: 150.
Не согласен с выставленной оценкой второго проверяющего (который поставил 80 баллов (снял 20 баллов за третью и 50 баллов за шестую задачу))
Мой код хорошо отрабатывает на моём ноутбуке (os windows). Так же, судя по оценке первого проверяющего, у него тоже всё работает хорошо. Ещё я проверял работу приложения на двух других ноутбуках (так же os windows) - там тоже всё хорошо. Возможно проблема как раз в том, что у второго проверяющего os Linux, но возможности проверить, и узнать причину, почему на данной ОС приложение не работает не представляется возможным.
Буду рад обратной связи и объяснению кто прав в данной ситуации
Мой дискорд: Костя#1568
Прикладываю скриншот того, как выглядит выполнение кода обоих задач на моём ноутбуке:
![image](https://user-images.githubusercontent.com/99538672/170639834-732e4d51-bd8d-47d6-8ee8-7f46176702c2.png)

7. Балл за cross-check из вашего Score.
Score: 115

**Comment by XXXmez** [comment]
Здравствуй. Там же тебе сразу дали ответ "Используешь \\ а на линуксе //", поясняю, у каждой OS свой разделитель пути, то есть то, что ты используешь \ только для windows, в то время как у linux /, пример: win C:\github\HTML-builder, lin C:/github/HTML-builder. То есть у него os просто не понимает куда ты идешь. Там же тебе там дали совет, использовать path.join(), про него уж почитай сам)
