### ISSUE TITLE
Cross-Check HTML-Builder - MaxSettings

### ISSUE THREAD

**Issue by MaxSettingsRIP** [rolling-scopes-school/support#559]
1. Ссылка на деплой вашего проекта:
Для данного таска деплой не предусмотрен.
2. Ссылка на репозиторий с проектом на GitHub:
https://github.com/MaxSettings/HTML-builder
3. Ссылка на задание:
https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-builder
4. Ссылка на форму для проверки проекта (если такая есть):
Формы для проверки данного таска нет. Прилагаю ссылку на инструкцию проверки:
https://github.com/EvgeniiMal/HTML-builder/wiki/HTML-builder-crosscheck
5. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты):
![image](https://user-images.githubusercontent.com/26907855/170925976-992f0d52-ff6f-4ae2-a918-1c6b1efae429.png)
6. Оценка в результате самопроверки с ее аргументацией: 150
В документации сказано, что если работу проверило 4 человека, то наименьшая оценка отбрасывается. В моем же случае наименьшая оценка учитывается.
7. Балл за cross-check из вашего Score: 133

**Comment by igorlyatskiy** [comment]
Человек проверил после дедлайна
