### ISSUE TITLE
Cross-Check Singolo. DOM & Responsive - Stepbackru

### ISSUE THREAD

**Issue by Stepbackru** [rolling-scopes-school/support#56]
DELETED.

**Comment by Student-Java** [comment]
https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f

**Comment by Stepbackru** [comment]
> https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f

Боже я знаю и читал документацию неоднократно. Только вот за отсебятину терять баллы не собираюсь.

**Comment by Student-Java** [comment]
Если знаешь, то так же должен знать, что твоя работа не подподает под апелляцию

**Comment by Stepbackru** [comment]
> Если знаешь, то так же должен знать, что твоя работа не подподает под апелляцию

Значит будет. Потому что это бред.

**Comment by Student-Java** [comment]
Погоди, а как же
![image](https://user-images.githubusercontent.com/57161516/78499299-316e5b80-7726-11ea-924f-f782587230eb.png)
И ты правда думаешь, что ты исключение из правил? :)))

**Comment by Stepbackru** [comment]
> Погоди, а как же
> ![image](https://user-images.githubusercontent.com/57161516/78499299-316e5b80-7726-11ea-924f-f782587230eb.png)
> И ты правда думаешь, что ты исключение из правил? :)))
Именно так. Принципиально эти 2 балла.

**Comment by Student-Java** [comment]
Ты даешь себе отчет, что при апелляции оценка будет выставлена объективная и может быть как повышена так и понижена? :)

**Comment by Stepbackru** [comment]
> Ты даешь себе отчет, что при апелляции оценка будет выставлена объективная и может быть как повышена так и понижена? :)

Да мне плевать, я заодно докажу тот факт, что ко мне особое отношение в этой школе. Именно из-за такого отношения вот уже 2й набор подряд меня выводит из себя Ирина, но Дима прикрывал и будет прикрывать её, потому что она якобы много делает для школы. Да и вообще в этой школе чтобы не сделала представительница женского пола - все сойдет с рук, особенно если общаешься с администрацией. Человеческий фактор никуда не деть, увы.

**Comment by Student-Java** [comment]
Мда, ты конечно извини, но боюсь что ты не найдешь школы или ментора который осознает всю величину оказанной им чести и насколько им повезло учить тебя.

**Comment by Stepbackru** [comment]
> Мда, ты конечно извини, но боюсь что ты не найдешь школы или ментора который осознает всю величину оказанной им чести и насколько им повезло учить тебя.

Как-то находил и я отношусь к окружающим ровно так, как относятся ко мне. Даже проходя собес в mail.ru ко мне относились нормально, я не чувствовал себя извиняюсь говном, каким ощущаю себя здесь.

**Comment by Student-Java** [comment]
DOM
Слайдер:
при нескольких переключениях влево и потом одном вправо происходит переход на один и тот же слайд. -3
Галерея:
переключения между тагами не стабильные. Если переключаться несколько раз между Graphic Design и Artwork, то изображения начинают пропадать и получаем пустую галерею. -3
Rsponsive:
768
расхождения в блоке Get a Quote более чем на 5 пикселей -3
365
Заголовок смещен вправо на 7-8 пикселей -3
блок Get a Quote не соответствует макету на более чем 5 пикселей -3

При плавном изменении размеров в блоке слайдер начинает показывать оба слайда сразу, чего не должно происходить -3
К мелочам я не стал придираться

Итого: 100- (3 * 6) = 100 - 18 = 82 балла

**Comment by Stepbackru** [comment]
> DOM
> Слайдер:
> при нескольких переключениях влево и потом одном вправо происходит переход на один и тот же слайд. -3
> Галерея:
> переключения между тагами не стабильные. Если переключаться несколько раз между Graphic Design и Artwork, то изображения начинают пропадать и получаем пустую галерею. -3
> Rsponsive:
> 768
> расхождения в блоке Get a Quote более чем на 5 пикселей -3
> 365
> Заголовок смещен вправо на 7-8 пикселей -3
> блок Get a Quote не соответствует макету на более чем 5 пикселей -3
> 
> При плавном изменении размеров в блоке слайдер начинает показывать оба слайда сразу, чего не должно происходить -3
> К мелочам я не стал придираться
> 
> Итого: 100- (3 * 6) = 100 - 18 = 82 балла

Все перечисленное и есть мелочи. Собственно ЧТД. Я даже спорить не буду, просто знаю твоё отношение ко мне, мальчик.
