### ISSUE TITLE
Cross-Check 'clean-code-s1e1' - 'olvsivkov'.

### ISSUE THREAD

**Issue by olvsivkov** [rolling-scopes-school/support#560]
1.Ссылка на деплой вашего проекта: deploy: https://olvsivkov.github.io/clean-code-s1e1/index.html

2.Ссылка на репозиторий с проектом на GitHub: https://github.com/olvsivkov/clean-code-s1e1/tree/clean-code-s1e1

3.Ссылка на задание:  https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md

4.Ссылка на форму для проверки проекта (если такая есть): https://rolling-scopes-school.github.io/checklist/ (пункт "Clean code S1E1");

5.Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты):
![CleanCode](https://user-images.githubusercontent.com/77755630/171503751-e089932b-4bcc-4f8a-ba65-9aafef4e1da2.png)

6.Оценка в результате самопроверки с ее аргументацией: 40 из 45. т.к. не использовал БЭМ (-5 баллов)
Считаю, что штрафные баллы, которые применил проверяющий не соответствуют действительности.

7.Балл за cross-check из вашего Score: 0 баллов

**Comment by LidaChk** [comment]
### Ваша оценка - **0 баллов** 
Считаю оценку проверющего студента адекватной.
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Правило '2.1 БЭМ' из html-and-css-extended соблюдено: все классы именованы согласно БЭМ нотации 
Отзыв: не выполнено
Частично выполненные пункты:
1) Правило '1.2 Нижний регистр написания' из html-and-css выполняется во всем проекте: все HTML теги, атрибуты из значения, селекторы и их значения записаны в нижнем регистре 
Отзыв: цвета с иссольованием верхенго регистра: color: #3a3A3a; border: 1px solid #dDd; background: #FFF;
2) Правило '1.2 Альтернатива для мультимедиа' из html-and-css-extended соблюдено: каждый мультимедиа элемент (в данном задании img) имеет alt-атрибут с осмысленным содержанием, соответствующим контенту элементы. При этом чисто декоративные картинки имеют alt с пустым значением. 
Отзыв: Добавленные кнопки из js не имеют altб тогда как в html файле - они имеют alt 

Штрафы:
1) Формат коммит сообщений составлен вразрез указаным в задании требованиям 
Отзыв: Да, к сожалению, формат коммитов не соотвествует 
https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/materials/commits.md

![image](https://user-images.githubusercontent.com/20344968/174490009-0966a20b-bfe6-4ebe-a5d7-76a8af15470e.png)
2) Коммит содержит изменения по нескольким правилам, НЕ перекрывающим друг друга 
Отзыв: да, к сожалнию, некоторые коммиты содержат правки по нескольким пунктам неперекрывающимся.
Даже в названии коммита, не говоря, о содержании
449da4b: refactor: add margins and spaces in blocks. In one commit, I completed the tasks from rules 3.5, 3.6, 3.7
3.5: 3.5. Отступы в блоках., 
3.6: 3.6. Пробел после названий свойств,
3.7: 3.7. Точка с запятной после свойств
есть и другие правки в этом коммите
![image](https://user-images.githubusercontent.com/20344968/174490379-6b7a7351-2ae8-467f-b74b-8adcb0cc7166.png)
