### ISSUE TITLE
Cross-Check 'Clean Code S1E1' - 'Gorizontal'

### ISSUE THREAD

**Issue by Gorizontal** [rolling-scopes-school/support#563]
Ссылка на PR
https://github.com/Gorizontal/clean-code-s1e1/pull/1
Ссылка на репозиторий с проектом на GitHub
https://github.com/Gorizontal/clean-code-s1e1/tree/clean-code-s1e1
Ссылка на задание
https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md
Ссылка на форму для проверки проекта (если такая есть)
https://rolling-scopes-school.github.io/checklist/
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты)
![image](https://user-images.githubusercontent.com/92943869/171994311-d13f6e6f-2d0d-4b8f-b547-fa46629a23d7.png)

Оценка в результате самопроверки с ее аргументацией
Не сделано базовый 3.4 , продвинутый 2.1
Максимальный балл 38

Добрый день.
Выпал по болезни. Не было возможности проверить студентов во время. Если есть возможность проставить баллы, буду очень благодарен.

**Comment by igorlyatskiy** [comment]
Справку в лс
