### ISSUE TITLE
Cross-Check 'Node.js Basics' - Kritok-by

### ISSUE THREAD

**Issue by Kritok-by** [rolling-scopes-school/support#565]
- Данный проект не предусматривает deploy
- Ссылка на репозиторий с проектом на GitHub https://github.com/Kritok-by/node-nodejs-basics/pull/1
- Ссылка на задание https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md
- Скриншота с оценками на задание нету, это часть моей проблемы
- Оценка в результате самопроверки с ее аргументацией: Я выполнил все требования - 206
- Балл за cross-check из вашего Score: нет - так как у меня не получилось засабмитить задание, как видите на pull request я сделал раньше дедлайна, но не получилось сделать submit в приложении, скажите можно ли это как нибудь решить?

**Comment by ML6503** [comment]
[📝 review started](https://github.com/rolling-scopes-school/support/labels/%3Amemo%3A%20review%20started)

**Comment by ML6503** [comment]
is:open label:":memo: review started"

**Comment by AlreadyBored** [comment]
Unfortunately, you didn't submitted your work for review in time, this is not a basis for an appeal.

**Comment by ThorsAngerVaNeT** [comment]
@Kritok-by you should also set up git correctly, it seems your git config has wrong email, which is not the same as GitHub email
