### ISSUE TITLE
Cross-Check 'Nodejs-basics' - '@ed9n'

### ISSUE THREAD

**Issue by ed9n** [rolling-scopes-school/support#567]
Данный проект не предусматривает deploy.
Ссылка на репозиторий с проектом на GitHub: https://github.com/ed9n/Nodejs-basics 
Ссылка на задание: https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md
Скриншот с оценками за cross-check: 
1. <img width="1430" alt="Снимок экрана 2022-06-11 в 16 52 44" src="https://user-images.githubusercontent.com/70845848/173190881-0753526e-426b-447f-a9c4-05603224cb3f.png">
2. <img width="1440" alt="Снимок экрана 2022-06-11 в 17 01 45" src="https://user-images.githubusercontent.com/70845848/173191119-251e0ad1-d877-4b99-8337-70e41885a7ce.png">

Оценка в результате самопроверки с ее аргументацией: я выполнил все на 176 баллов использую где это надо Callback API, но на первом скриншоте мне поставили минус баллы и сказали что я использую синхронные функции, хотя в заданиях не предусматривались минус баллы за сихрнность, если даже я бы и использовал синхронные функции, так же я не смог найти этого человека, чтоб с ним лично связаться , так как он не указал кантактов.

**Comment by AlreadyBored** [comment]
The difference between the self-review score and the final score is not sufficient for an appeal.
