### ISSUE TITLE
Cross-Check Node.js Basics - anhelina-zhurauliova

### ISSUE THREAD

**Issue by anhelina-zhurauliova** [rolling-scopes-school/support#568]
Ссылка на репозиторий с проектом на GitHub - [repo](https://github.com/anhelina-zhurauliova/node-nodejs-basics)
Ссылка на задание - [assignment](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md)
Ссылка на форму для проверки проекта (если такая есть) - [score](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/score.md)
Скриншот с оценками за cross-check. -  Никто не проверил работу 🥲
<img width="653" alt="image" src="https://user-images.githubusercontent.com/56220481/173251379-6e85d684-f4b7-427f-884d-0004bf9676b2.png">
Оценка в результате самопроверки с ее аргументацией. - 200/206, выполнила всё, но в `cli env` не отформатировала output, как было необходимо в задании и в `modules`, не сделала динамический импорт для json  (как, возможно, предполагало задание) 
Балл за cross-check из вашего Score. - 0

**Comment by ML6503** [comment]
Серьёзных замечаний нет.
Оценка - 203
