### ISSUE TITLE
Cross-Check Node.js Basics - super-firefox

### ISSUE THREAD

**Issue by super-firefox** [rolling-scopes-school/support#569]
Ссылка на репозиторий с проектом на GitHub - [repo](https://github.com/super-firefox/node-nodejs-basics/tree/develop)
Ссылка на [pull requests](https://github.com/super-firefox/node-nodejs-basics/pull/1)
Ссылка на задание - [assignment](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md)
Ссылка на форму для проверки проекта (если такая есть) - [score](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/score.md)
Скриншот с оценками за cross-check. - Никто не проверил работу
Оценка в результате самопроверки с ее аргументацией. - 136/206, Выполнил все кроме Worker Threads и  Child Processes
Балл за cross-check из вашего Score. - 0

**Comment by ThorsAngerVaNeT** [comment]
**Оценка: 123 (206 - 3 - 10 - 70 (Advanced Scope))**

# Scoring: Node.js basics

## Basic Scope

- File system (src/fs)
  - [x] **+6** `create.js` implemented properly
  - [x] **+10** `copy.js` implemented properly
  - [x] **+10** `rename.js` implemented properly
  - [x] **+6** `delete.js` implemented properly
  - [x] **+6** `list.js` implemented properly
  - [x] **+6** `read.js` implemented properly
- Command line interface(src/cli)
  - [x] **+6** `env.js` implemented properly
  - [ ] **+6** `args.js` implemented properly -- -3 вывод в консоль должен быть в одну строку
- Modules(src/modules)
  - [x] **+20** `cjsToEsm.cjs` refactored properly
- Hash (src/hash)
  - [ ] **+10** `calcHash.js` implemented properly -- -10 некорректно формируется хеш, следовало использовать метод createHash
- Streams (src/streams)
  - [x] **+10** `read.js` implemented properly
  - [x] **+10** `write.js` implemented properly
  - [x] **+10** `transform.js` implemented properly
- Zlib (src/zip)
  - [x] **+10** `compress.js` implemented properly
  - [xc] **+10** `decompress.js` implemented properly

## Advanced Scope

- Worker Threads (src/wt)
  - [ ] **+10** `worker.js` implemented properly
  - [ ] **+30** `main.js` implemented properly
- Child Processes (src/cp)
  - [ ] **+10** spawns child process
  - [ ] **+10** child process `stdin` receives input from master process `stdin`
  - [ ] **+10** child process `stdout` sends data to master process `stdout`

## Forfeits

- [ ] **-95% of total task score** Any external tools/libraries are used
- [ ] **-30% of total task score** Commits after deadline (except commits that affect only Readme.md, .gitignore, etc.)
