### ISSUE TITLE
Cross-Check 'Singolo. DOM&Responsive' - 'Iamdii'

### ISSUE THREAD

**Issue by Iamdii** [rolling-scopes-school/support#57]
Ссылка на деплой проекта: https://iamdii.github.io/singolo/
Ссылка на репозиторий с проектом на GitHub: https://github.com/Iamdii/singolo
Оценка в результате самопроверки, с ее аргументацией: 91 балл.
 - На полях ввода name и email отсуствует базовая валидация -3
 - Поля не обнуляются после закрытия модального окна  -3
 - Вызов меню не работает  -3 (макет 375px)
Балл за cross-check из вашего Score: дедлайн по кроссчеку прошел, мой проект оценило три человека: первый проверяющий поставил 91 балл, второй - 86 баллов, а третий студент утверждает, что я списала(указывая ссылку на сайт, с которого я, по его мнению, скопировала работу; данный сайт упомянут в footer самого макета) и отнимает 62 балла, выставляя моей работе оценку в 36 баллов. Факт отсуствия списывания очень легко проверить, просто сравнив код проекта, написанного мной и код проекта с приведенного сайта.
Средняя оценка из трех выходит около 72 баллов. Прошу пересмотреть данный результат, очень хочется, чтобы усилия первого этапа не прошли даром, спасибо!

**Comment by Student-Java** [comment]
Перепроверил работу, 
Зачем на себя наговариваешь - базовая валидация присутствует :)
Поля не обнуляются и вызов меню не работает: -6
В остальном у меня претензий нет. В списках списавших либо признаков списывания я не нашел.

Итоговая оценка: 94 балла
