### ISSUE TITLE
Cross-Check Node.js Basics - Dipppp84

### ISSUE THREAD

**Issue by Dipppp84** [rolling-scopes-school/support#570]
Ссылка на репозиторий с проектом на GitHub - [repo](https://github.com/Dipppp84/node-nodejs-basics/tree/myBranch)
Ссылка на задание - [assignment](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md)
Ссылка на форму для проверки проекта (если такая есть) - [score](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/score.md)
Скриншот с оценками за cross-check 
1.
 ![image](https://user-images.githubusercontent.com/84383240/173228673-1382dc39-d1dc-42b1-b85f-376643782764.png)
2. 
![image](https://user-images.githubusercontent.com/84383240/173228711-9dc25319-528b-4745-8088-f73b0c56338e.png)
3. не проверил

Оценка в результате самопроверки с ее аргументацией. - 204/206, 
Ошибся:
args.js +5/6 (Вывод аргументов не по ТЗ: не убраны "--")
cjsToEsm.cjs +19/20  Некорректное расширение файла модуля - js вместо mjs)
Остальное сделано.

Балл за cross-check из вашего Score. - 180

**Comment by ML6503** [comment]
label:":memo: review started"

**Comment by ThorsAngerVaNeT** [comment]
**Оценка: 193 (206 - 3 - 5 - 5)

Замечания:
1) Modules - анонимный проверяющий явно прав, импортировать c.js так не стоит... Но как говорил Максим оцениваем функциональность, а не код.

# Scoring: Node.js basics

## Basic Scope

- File system (src/fs)
  - [x] **+6** `create.js` implemented properly
  - [x] **+10** `copy.js` implemented properly
  - [x] **+10** `rename.js` implemented properly
  - [x] **+6** `delete.js` implemented properly
  - [x] **+6** `list.js` implemented properly
  - [x] **+6** `read.js` implemented properly
- Command line interface(src/cli)
  - [x] **+6** `env.js` implemented properly
  - [ ] **+6** `args.js` implemented properly -- -3 некорректный вывод
- Modules(src/modules)
  - [ ] **+20** `cjsToEsm.cjs` refactored properly -- -5 некорректное наименование файла
- Hash (src/hash)
  - [x] **+10** `calcHash.js` implemented properly
- Streams (src/streams)
  - [x] **+10** `read.js` implemented properly
  - [x] **+10** `write.js` implemented properly
  - [x] **+10** `transform.js` implemented properly
- Zlib (src/zip)
  - [x] **+10** `compress.js` implemented properly
  - [x] **+10** `decompress.js` implemented properly

## Advanced Scope

- Worker Threads (src/wt)
  - [ ] **+10** `worker.js` implemented properly -- -5 после выполнения скрипта он не завершает свою работу
  - [x] **+30** `main.js` implemented properly
- Child Processes (src/cp)
  - [x] **+10** spawns child process
  - [x] **+10** child process `stdin` receives input from master process `stdin`
  - [x] **+10** child process `stdout` sends data to master process `stdout`

## Forfeits

- [ ] **-95% of total task score** Any external tools/libraries are used
- [ ] **-30% of total task score** Commits after deadline (except commits that affect only Readme.md, .gitignore, etc.)
