### ISSUE TITLE
Cross-Check Node.js Basics - karpinskaya

### ISSUE THREAD

**Issue by karpinskaya** [rolling-scopes-school/support#571]
**Ссылка на репозиторий с проектом на GitHub:** https://github.com/karpinskaya/node-nodejs-basics

 **Ссылка на задание:** https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md

**Скриншот с оценками за cross-check:**
![изображение](https://user-images.githubusercontent.com/39993454/173501820-53e71175-2ac7-42a5-a9d5-5e8739573549.png)

**Оценка в результате самопроверки с ее аргументацией:**
_src/cli_
-3 env.js (некорректный вывод: RSS_name1 = value1 RSS_name2 = value2 вместо RSS_name1=value1; RSS_name2=value2)
-3 args.js (некорректный вывод: propName is value prop2Name value2 вместо propName is value, prop2Name is value2)
_src/wt_
-15 (некорректный вывод)
_src/cp_
-5 (дополнена логика child process)
В дополнение -30% за коммит на следующий день после дедлайна.
**ИТОГО:** 206 - 3 - 3 - 15 - 5 - 30% = 126

**Балл за cross-check из вашего Score:** 94

**Comment by ThorsAngerVaNeT** [comment]
Оценка: 87 (206 - 3 - 3 - 5 - 5 - 15 - 88)

Замечания:
1) Пришлось самостоятельно во все файлы добавлять вызов функций.
2) Работает непосредственно только из папки со скриптами, из корневого каталога не работает.
Уже за это я бы снял половину.
3) Почти везде используется existsSync - это плохо. Обычный rename занял секунд 5.

# Scoring: Node.js basics

## Basic Scope

- File system (src/fs)
    - [x] **+6** `create.js` implemented properly
    - [x] **+10** `copy.js` implemented properly
    - [x] **+10** `rename.js` implemented properly
    - [x] **+6** `delete.js` implemented properly
    - [x] **+6** `list.js` implemented properly
    - [x] **+6** `read.js` implemented properly
- Command line interface(src/cli)
    - [ ] **+6** `env.js` implemented properly -- -3 за формат вывода в соответствии с самопроверкой
    - [ ] **+6** `args.js` implemented properly -- -3 за формат вывода в соответствии с самопроверкой
- Modules(src/modules)
    - [x] **+20** `cjsToEsm.cjs` refactored properly
- Hash (src/hash)
    - [ ] **+10** `calcHash.js` implemented properly -- -5 хеш высчитывается не файла, а строки с путём к файлу
- Streams (src/streams)
    - [x] **+10** `read.js` implemented properly
    - [x] **+10** `write.js` implemented properly
    - [x] **+10** `transform.js` implemented properly -- как то всё сложно `/./g[Symbol.match]` :-) Так же стоило добавить разрыв строки после вывода реверс строки, а то след. ввод слипается с предыдущим выводом
- Zlib (src/zip)
    - [-] **+10** `compress.js` implemented properly -- -5 имя файла заданно не в соответствии с ТЗ
    - [x] **+10** `decompress.js` implemented properly

## Advanced Scope

- Worker Threads (src/wt)
    - [x] **+10** `worker.js` implemented properly
    - [ ] **+30** `main.js` implemented properly -- -15 некорректный вывод
- Child Processes (src/cp)
    - [ ] **+10** spawns child process -- -5 функция берёт аргументы из аргументов запуска, а не массива, который передаётся в параметры функции
    - [x] **+10** child process `stdin` receives input from master process `stdin`
    - [x] **+10** child process `stdout` sends data to master process `stdout`

## Forfeits

- [ ] **-95% of total task score** Any external tools/libraries are used
- [x] **-30% of total task score** Commits after deadline (except commits that affect only Readme.md, .gitignore, etc.) -- -88 баллов штрафа
