### ISSUE TITLE
Cross-Check CV#3. CV. ViktorChekalov

### ISSUE THREAD

**Issue by ViktorChekalov** [rolling-scopes-school/support#572]
1. Ссылка на деплой: https://classy-beignet-350e8c.netlify.app/
2. Ссылка на репрозиторий: https://github.com/ViktorChekalov/rsschool-cv
3. Ссылка на задание: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
.
Здравствуйте!
Это был мой первый сабмит в кросс-чек проверку. Видимо, я оплошал, и сделал что-то не так. Сабмитил 08.06.2022, фиксил до дедлайна. На выполнение задания потратил много времени и хотелось бы, чтобы оно не осталось незамеченным. Прошу пойти на встречу и оценить задание. В следующие сабмиты обещаю быть более внимательным:) Заранее большое спасибо!
С уважением, Виктор Чекалов.

**Comment by AlreadyBored** [comment]
Unfortunately, you didn't submitted your work for review in time, this is not a basis for an appeal.
