### ISSUE TITLE
Cross-Check Node.js Basics - yuliya-v

### ISSUE THREAD

**Issue by yuliya-v** [rolling-scopes-school/support#573]
1. Репозиторий с проектом: https://github.com/yuliya-v/node-nodejs-basics
2. Задание: https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md
3. Форма для проверки: https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/score.md
4. Оценки проверяющих:
![](https://user-images.githubusercontent.com/86212613/174049384-ad6c67ac-332b-49f0-8d5a-7fa47a00c42c.png)
5. Своя оценка: 204 / 206
- copy.js - в случае отсутствия папки files ошибка выбрасывается, но создаётся пустая files_copy
- create.js  - вместо fresh.txt создаётся text.txt
Остальные требования выполнены.

* cjsToEsm.mjs - анонимный проверяющий отнял 20 баллов за использование функции require в задании о модулях, однако в видео с разбором задания (таймкод:  https://youtu.be/TmylgGP9QDk?t=4141) упоминалось, что для импорта json допустимо использование require в форме 
``` 
import { createRequire } from "module";
const require = createRequire(url);
```
6. Балл за cross-check из score: 183

**Comment by ThorsAngerVaNeT** [comment]
Серьёзных замечаний нет.
Оценка - 206
