### ISSUE TITLE
Cross-Check 'AWS_3_serverless_api' - iZamza

### ISSUE THREAD

**Issue by iZamza** [rolling-scopes-school/support#577]
CloudFront: https://d30a10x0kit4gv.cloudfront.net/
PR: https://github.com/iZamza/AWS-BE-RS-2022/pull/1
Task: https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/3_serverless_api/task.md
![image](https://user-images.githubusercontent.com/26019963/174730625-7d0af5c0-8630-4fb8-9295-72477d9fbff2.png)
![image](https://user-images.githubusercontent.com/26019963/174730747-f1a0861e-7723-43e5-9501-eced03c8df8f.png)
My PR just hasn't been evaluated by other

**Comment by Dmitry-White** [comment]
I'm looking into it. Will provide an update shortly.

**Comment by Dmitry-White** [comment]
@iZamza 
Your score has been updated.
