### ISSUE TITLE
 Cross-Check "Task 1. Caesar cipher CLI tool" "Vir45"

### ISSUE THREAD

**Issue by Vir45** [rolling-scopes-school/support#58]
1. Мой проект - https://github.com/Vir45/NodeJS/tree/task1/task1
Student №2 не смог запустить мой проект, поэтому не засчитал мне баллы.
2. Самооценка - 
1. в корне репозитория создана папка с произвольным названием (например caesar-cipher-cli, task1 и т.п.), в которой расположены файлы с кодом программы - 10
2. в README.md должно быть описано, как можно запустить программу из командной строки, описаны аргументы, которые можно передать приложению - 10
3. если переданы все аргументы, приложение читает из файла и записывает в файл зашифрованный/расшифрованный текст, при этом предыдущие записи не удаляются - 5 (удаляются предыдущие записи).
4. если не переданы обязательные аргументы, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 - 10
5. если переданы аргументы с путями к файлам, но файлы отсутствуют (или к ним невозможен доступ), приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 - 10
6. если не передан аргумент с путем до файла на чтение, то чтение осуществляется из process.stdin - 10.
7. если не передан аргумент с путем до файла на запись, то вывод осуществляется в process.stdout - 10.
8. шифруются/дешифруются только латинские буквы, регистр сохраняется, остальные символы не изменяются - 10
9. если текст вводится из консоли, то программа не должна завершаться после выполнения шифровки/дешифровки введенного текста, т.е. должна быть возможность ввести еще текст -10
10. кодовая база не находится в одном файле, а разделена на файлы в соответствии с выполняемыми задачами (например - функция, преобразующая строку, в отдельном файле, код, создающий tr 10
Итог - 95.
3. Балл за Cross-Check из cскора - 77.

**Comment by Student-Java** [comment]
По гитхаб нику найти в скоре не смог. Исправь данные в профиле rs.app

**Comment by Student-Java** [comment]
Сорян, не в том скоре смотрел. Если после дедлайна оценка не поменяется, то проверим

**Comment by Student-Java** [comment]
Описание в README не соответствует действительности - команды не работают. Когда запускаю `\task1\bin\index.js` опции не работают. Может я чего-то не понимаю?
![image](https://user-images.githubusercontent.com/57161516/78667250-fba8ae80-78ae-11ea-8ee6-341df4dcf7e5.png)

**Comment by Vir45** [comment]
У меня в ридми написано, что таск запускается командой:
$ task1 my_caesar_cli -a encode -s 7 -i "./input.txt" -o "./output.txt"
В package.json я  указал: "bin": {
    "task1": "./bin/index.js"
  },
Для того чтобы не писать node ./bin/ondex.js my_caesar_cli -a encode -s 7 -i "./input.txt" -o "./output.txt"

**Comment by Vir45** [comment]
В разделе usage указано какие команды вводить, в разделе Examples приведены примеры запуска программы

**Comment by Student-Java** [comment]
![image](https://user-images.githubusercontent.com/57161516/78701886-1fcfb400-78de-11ea-9205-6f321310a7a3.png)

**Comment by Student-Java** [comment]
![image](https://user-images.githubusercontent.com/57161516/78701984-455cbd80-78de-11ea-93a0-a78d1164a32c.png)

**Comment by Student-Java** [comment]
Что я делаю не так?

**Comment by Vir45** [comment]
по последнему скриншоту: забыли указать в команде на запуск my_caesar_cli
commander не понимает без этой записи.
то есть нужно node ./bin/index.js my_caesar_cli -a encode -s 7 -i "./input.txt" -o "./output.txt"

**Comment by Student-Java** [comment]
И где в ТЗ была такая команда или где в README указано, что эту команду надо использовать?

**Comment by Vir45** [comment]
для того чтобы заработало через команду task1 наверное нужно npm install перед запуском сделать

**Comment by Vir45** [comment]
в ТЗ вопрос обязательности (необязательности) команды оговорен не был

**Comment by Vir45** [comment]
в ридми я указал, что необходимо первоначально выполнить npm install, далее привел примеры команд. Наверное я намудрил немного с командами. Так как у одного из проверяющих также были вопросы с запуском моего приложения)

**Comment by Student-Java** [comment]
без npm install  не было бы ошибок, что нет такой опции от Commander, то что работало в твоей ОС, не факт что будет работать у другого человека.
Если добавляешь отсебятину, то надо указывать это явно в README. Если это будет человек который впервые увидел твою программу и не понимает в программировании, то он ее не запустит.

**Comment by Vir45** [comment]
Понял. Спасибо за совет

**Comment by Student-Java** [comment]
1. 10
2. Из документации сложно понять как запускать программу, по нормальному это 0, снимать не стал 10
3. Перетирает файл при каждом вызове 5
4. 10
5. Если в качестве файла передать директорию либо к файлу нет доступа, то выводится не дружелюбная ошибка, если отсуствуют оба файла, то exitCode выводит дважды. 10
6. если output файла не существует, то после ввода текста выдает ошибку и не выходит из программы. 7
7. 10
8. 10
9. 10
10. 10

Итого: 92

Комменты в коде, часть строк с ; часть без, неиспользуемые переменные
