### ISSUE TITLE
Пропал ментор из списка Interview без проведения собеседования

### ISSUE THREAD

**Issue by AnSaScience** [rolling-scopes-school/support#587]
Здраствуйте! В разделе Interview появился ментор. Я представился и спросил в телеграме когда будет удобно провести интерв'ю (23.06.2022). Не получил ответ и сегодня увидел что ментора больше нету в списке. Подскажите, как быть в такой ситуации?
Скрин:
![image](https://user-images.githubusercontent.com/92640061/175810895-610a3fc6-33d5-4282-8780-86b50c9403c5.png)

**Comment by valerydluski** [comment]
https://github.com/rolling-scopes-school/support/issues/576
