### ISSUE TITLE
Cross-Check 'Singolo. DOM & Responsive' - 'EugBulava'

### ISSUE THREAD

**Issue by EugBulava** [rolling-scopes-school/support#59]
1. https://eugbulava.github.io/singolo/
2. https://github.com/EugBulava
3. Оценка в результате самопроверки - 94 (отсуствует анимация в слайдере -3, если нажимаем на область, где нет телефонов и их теней, а какой либо из экранов телефонов меняет свое состояние, ставим -3)
4. Оценка в score - 69
P.S. один из студентов в комментариях к моей работе прикладывал скрины, где четко видно, что он проверял не мою работу(по url-адресу на скрине). Он снял 50 баллов с работы, т.к. он проверял чужую, а не мою работу. Прошу разобраться с этим. Заранее спасибо!

**Comment by Student-Java** [comment]
Привет,
-6 за DOM, причины те же, что ты указал.

Responsive
на 1020 уехало меню больше 5 пикселей - не снижаю, но это косяк 

768
картинки в портфолио смещены на 10px вверх и не соответсвуют размерам в макете не снижаю, хотя это косяк

375
боковое меню сломано - ссылки из него сразу присутствуют на экране, кнока отсутствует. Это происходит с начиная с 767 пикселей  -5
Весь макет плывет
![image](https://user-images.githubusercontent.com/57161516/78597506-09652200-7824-11ea-8ce2-3f75b484bb42.png)
![image](https://user-images.githubusercontent.com/57161516/78597510-0a964f00-7824-11ea-82e7-c3cb54052a9d.png)

Если логотип не центрирован, либо отсутствует иконка вызова меню, ставим -3.
Если вызов меню не работает, или не происходит перехода на нужную позицию в ссылке, ставим -3, и не проверяем оставшиеся 2 пункта.

За мелкие косяки в макете я снимать не стал как видишь, но и без этого моя оценка отличается от твоей.
Итого: 100 - 17 = 83 балла

**Comment by EugBulava** [comment]
Есть вопрос только по бургер-меню. В остальном со всем согласен.
Дело в том, что я делал медиа-запросы в js, и создавал сам блок бургер-меню через DOM-элементы. Я не смог решить эту проблему, но почему то бургер-меню появляется только при обновлении страницы на той ширине экрана, где оно должно присутствовать. То есть я его реализовал, проблема в том, что видимо его надо было реализовывать через CSS медиа-запросы, но в задании об этом не было сказано.
