### ISSUE TITLE
Cross-Check 'Caesar cipher CLI tool' - 'BeaRRRRR'

### ISSUE THREAD

**Issue by BeaRRRRR** [rolling-scopes-school/support#60]
[Мой проект](https://github.com/BeaRRRRR/rsschools-nodejs-course/tree/dev/caesar-cipher-cli)
Оценка проверяющего - Файлы имеют формат .ts, не смог проверить твою работу, ставлю половину
Оценка за кросс-чек из скора - 75 баллов
С оценкой проверяющего не согласен, 3 других человека смогли проверить и запустить программу по инструкциям из README 
Само-оценка: 93 балла

1. в корне репозитория создана папка с произвольным названием (например caesar-cipher-cli, task1 и т.п.), в которой расположены файлы с кодом программы
     +10
2. в README.md должно быть описано, как можно запустить программу из командной строки, описаны аргументы, которые можно передать приложению 
     +10
3. если переданы все аргументы, приложение читает из файла и записывает в файл зашифрованный/расшифрованный текст
     +10
4. если не переданы обязательные аргументы, приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0
     +10
5. если переданы аргументы с путями к файлам, но файлы отсутствуют (или к ним невозможен доступ), приложение передает соответствующее сообщение в process.stderr и прoцесс завершается с кодом, отличным от 0 
     +5 так как если файл отсутсвует, то он создаётся 
6. если не передан аргумент с путем до файла на чтение, то чтение осуществляется из process.stdin
    +10
7. если не передан аргумент с путем до файла на запись, то вывод осуществляется в process.stdout
     +10
8. шифруются/дешифруются только латинские буквы, регистр сохраняется, остальные символы не изменяются
     +7 Шифрует только lower-case латинские буквы(раньше в описании было такое условие, не заметил изменений)
9. если текст вводится из консоли, то программа не должна завершаться после выполнения шифровки/дешифровки введенного текста, т.е. должна быть возможность ввести еще текст
    +10
10. кодовая база не находится в одном файле, а разделена не файлы в соответствии с выполняемымы задачами (например - функция, преобразующая строку, в отдельном файле, код, создающий transform стрим, в отдельном файле, функция для парсинга и валидации аргументов в отдельном файле и т.п.)
   +10

**Comment by Student-Java** [comment]
По гитхаб нику найти в скоре не смог. Исправь данные в профиле rs.app
Добавь свою общую самооценку

**Comment by Student-Java** [comment]
Сорян, не там смотрел - нашел. Добавь общую оценку

**Comment by BeaRRRRR** [comment]
Привет, под общей оценкой ты имеешь в виду балл из скора(т.е. среднюю арифметическую 4 оценок), если да, то это 75 баллов.

**Comment by Student-Java** [comment]
Нет, мне нужна твоя общая самооценка, я могу сам все сложить, но чтобы не было недоразумений посчитай и добавь ее в свою апелляцию

**Comment by BeaRRRRR** [comment]
Добавил

**Comment by Student-Java** [comment]
1. 10
2. 10
3. 10
4. 10
5. 5 - создается файл на запись, чего не должно происходить
6. 10
7. 10
8. 5 - верхний регистр не шифруется/дешифруется. Следить за изменениями ТЗ и новостями обязанность студента, сорян.
9. 10
10. 10

Ввод опции --shift не валидируется должным образом. Числа + буквы преобразуются в числа
![image](https://user-images.githubusercontent.com/57161516/78668237-b38a8b80-78b0-11ea-9b8a-441a58ff7a2a.png)
Если к файлу нет доступа, то выдает ошибку "file not found" вместо соответствующей

Итого: 90 баллов

**Comment by BeaRRRRR** [comment]
Спасибо за оценку! А когда она изменится в скоре?

**Comment by Student-Java** [comment]
Привет, я дал информацию Сергею, как только он поменяет она появится. Если завтра не будет изменений, то пиши ему в дискорд либо здесь напиши и я его спрошу
