### ISSUE TITLE
Cross-Check Online store - al-r40

### ISSUE THREAD

**Issue by Al-r40** [rolling-scopes-school/support#606]
Deploy: https://rolling-scopes-school.github.io/al-r40-JSFE2022Q1/online-store/src/

Link to repository: https://github.com/rolling-scopes-school/al-r40-JSFE2022Q1/tree/online-store

Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md

Screenshots:
![image](https://user-images.githubusercontent.com/95902927/180366237-8bb4e3ec-d510-424c-9e5b-de9d26cebbaf.png)
![image](https://user-images.githubusercontent.com/95902927/180366496-f3f9a9e1-72bc-4646-a421-d66bd6b4efda.png)
![image](https://user-images.githubusercontent.com/95902927/180366601-1b1be8b1-ae87-4087-b226-536e560ca553.png)
![image](https://user-images.githubusercontent.com/95902927/180366862-399c030a-5e0e-43f0-bc03-a87b1ab581d2.png)

Self-examination with its arguments: 
138 / 200
 - [x] Главная страница содержит все товары магазина а также фильтры, строку поиска, поле для сортировки +10
 - [x] Карточка товара содержит его изображение, название, количество данного товара на складе, год выхода на рынок, цвет, производитель и т.д., находится ли товар в корзине +10
 - [x] Добавление товаров в корзину +20
 - кликая по карточке с товаром или по кнопке на нем, товар можно добавлять в корзину или удалять. Карточки добавленных в корзину товаров внешне отличаются от остальных +10
 - на странице отображается количество добавленных в корзину товаров. При попытке добавить в корзину больше 20 товаров, выводится всплывающее уведомление с текстом "Извините, все слоты заполнены" +10
 - [x] Сортировка +20
 - сортировка товаров по названию в возрастающем и убывающем порядке +10
 - сортировка товаров по году их выхода на рынок в возрастающем и убывающем порядке +10
 - [ ] Фильтры в указанном диапазоне от и до +0
 - [x] Фильтры по значению +10
 - фильтры по производителю (автору) +5
 - фильтры по цвету +0
 - фильтры по размеру  +0
 - можно отобразить только популярные товары +5
 - [x] Можно отфильтровать товары по нескольким фильтрам одного типа +10
 - [x] Можно отфильтровать товары по нескольким фильтрам разного типа +20
 - [x] Сброс фильтров +10
 - есть кнопка reset для сброса фильтров +10
 - при сбросе фильтров кнопкой reset, ползунки range slider сдвигаются к краям, значения ползунков возвращаются к первоначальным, range slider закрашивается одним цветом +0
 - [ ] Сохранение настроек в local storage +0
 - [x] Поиск +28
 - при открытии приложения курсор находится в поле поиска +2
 - автозаполнение поля поиска отключено +2
 - есть placeholder +2
 - в поле поиска есть крестик, позволяющий очистить поле поиска +0
 - если нет совпадения последовательности букв в поисковом запросе с названием товара, выводится уведомление в человекочитаемом формате, например "Извините, совпадений не обнаружено" +2
 - при вводе поискового запроса на странице остаются только те товары, в которых есть указанные в поиске буквы в указанном порядке. При этом не обязательно, чтобы буквы были в начале слова. Регистр символов при поиске не учитывается +10
 - если очистить поле поиска, на странице отображаются товары, соответствующие всем выбранным фильтрам и настройкам сортировки +10

Score: 114 / 200

**Comment by WiiJoy** [comment]
Привет!
**Итоговый балл: 158\220**

1. Если кликнуть в пределах карточки товара по пустому пространству, то итем не добавляется\удаляется из корзины, т.е. событие не отрабатывает
2. Невозможно проверить требование 20-ти товаров, тк у тебя их всего 12. Поэтому за "на странице отображается количество добавленных в корзину товаров. При попытке добавить в корзину больше 20 товаров, выводится всплывающее уведомление с текстом "Извините, все слоты заполнены"" получается только 5/10
3. Нет range-фильтров (0/30 за соответствующий пункт "Фильтры в указанном диапазоне `от и до`"):
  ![image](https://user-images.githubusercontent.com/73646765/187618863-90b4b39c-9964-43eb-98e5-d7f8ba3b8c4e.png)

4. Добавлено только 2 фильтра по значению ("Автор" и "Только популярные"). ТЗ предполагает добавление собственных фильтров взамен тем, что не подходят из критериев. Поэтому, раз в критериях описано 4 фильтра, а реализовано только 2 - то и оценить мы можем только эти 2.  20/30 за соответствующий пункт
  ![image](https://user-images.githubusercontent.com/73646765/187619602-948b7f32-97b8-4316-8584-55fe00ba7b63.png)

5. Сохранение в localStorage не реализовано (10/30, 10 есть тк есть кнопка, хоть ее назначение и не проверить, но надежда есть :) )
6. Поиск 28/30 - нет крестика для очистки поля
  ![image](https://user-images.githubusercontent.com/73646765/187621335-3a09d648-1974-4f4f-80af-0bdfeea24ae1.png)

  
  
Баги:
1. Добавить в корзину книжки - изменить фильтр или сортировку - корзина показывает все еще количество выбранных книг, но при этом сами книги оказываются не выделены
  ![image](https://user-images.githubusercontent.com/73646765/187620841-e056b906-f81d-4fd1-a1cf-650dc1dcd9f4.png)
2. Кнопка корзины не выполняет вообще никаких функций
