### ISSUE TITLE
Cross-Check 'Online store' - 'Nastik95'

### ISSUE THREAD

**Issue by Nastik95** [rolling-scopes-school/support#607]
1. Ссылка на деплой вашего проекта. https://rolling-scopes-school.github.io/nastik95-JSFE2022Q1/onlineStore/dist/
2. Ссылка на репозиторий с проектом на GitHub. https://github.com/rolling-scopes-school/nastik95-JSFE2022Q1/tree/online-store
3. Ссылка на задание. https://github.com/rolling-scopes-school/tasks/tree/master/tasks/online-store
4. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
<img width="1440" alt="Снимок экрана 2022-07-23 в 20 13 38" src="https://user-images.githubusercontent.com/96075534/180615679-0b674f59-0168-4bbb-9e3d-eb360af74ca7.png">

<img width="1440" alt="Снимок экрана 2022-07-23 в 20 15 29" src="https://user-images.githubusercontent.com/96075534/180615745-c97f17dd-c058-415f-8e52-4d4433caa16c.png">

<img width="1440" alt="Снимок экрана 2022-07-23 в 20 13 05" src="https://user-images.githubusercontent.com/96075534/180615887-0964f110-e4f0-434a-843f-35dff3ee1957.png">

5. Оценка в результате самопроверки с ее аргументацией:
Score: 145 / 200
Главная страница содержит все товары магазина а также фильтры, строку поиска, поле для сортировки. Выполняются + 10
Карточка товара содержит его изображение, название, количество данного товара на складе, год выхода на рынок, цвет, производитель и т.д., находится ли товар в корзине +10
кликая по карточке с товаром или по кнопке на нем, товар можно добавлять в корзину или удалять. Карточки добавленных в корзину товаров внешне отличаются от остальных +10
на странице отображается количество добавленных в корзину товаров. При попытке добавить в корзину больше 20 товаров, выводится всплывающее уведомление с текстом "Извините, все слоты заполнены" +10
сортировка товаров по названию в возрастающем и убывающем порядке +10
сортировка товаров по году их выхода на рынок в возрастающем и убывающем порядке +10
фильтры по количеству +10
фильтры по году выпуска на рынок +10
для фильтрации в указанном диапазоне используется range slider с двумя ползунками. При перемещении ползунков отображается их текущее значение, разный цвет слайдера до и после ползунка +10
фильтры по производителю +5
фильтры по цвету +5
фильтры по популярности +5
можно отфильтровать товары по нескольким фильтрам одного типа +10
Поиск +30

6. Балл за cross-check из вашего Score:
Баллов нет по причине опоздания проверки этого задания в  Cross-Check: Review

**Comment by ipipka** [comment]
### Итого: 132 балла
--------------
**Полностью выполненные требования:**
**[+10]** Карточка товара содержит его изображение, название, количество данного товара на складе, год выхода на рынок, цвет, производитель и т.д., находится ли товар в корзине +10
**[+20]** Добавление товаров в корзину +20
**[+30]** Фильтры в указанном диапазоне от и до +30

**Частично выполненные требования:**
**[+5]** Главная страница содержит все товары магазина а также фильтры, строку поиска, поле для сортировки. Выполняются требования к вёрстке +10
- Не выполняются требования к верстке 
  - горизонтальный скролл на любых экранах
  - нет адаптивности до 768 пикселей (фильтры наезжают друг на друга, карточки не переносятся)
  - нет интерактивности на элементах (кнопки-фильтры не подсвечиваются при выборе)
  - нет ссылки на гитхаб автора и ссылки на курс в подвале

**[+15]** Сортировка +20
- _Сортируются только те товары, которые в данный момент отображаются на странице_ — Если применить фильтры, а после отсортировать, то товаров становится больше (фильтры сбрасываются)

**[+15]** Фильтры по значению +30
- _Выбранные фильтры выделяются стилем_ — выбранные фильтры не выделяются цветом
- _По заданию должно быть 4 фильтра_, а у тебя только 3 
- _Можно отфильтровать товары по нескольким фильтрам одного типа (например: белые, синие и красные товары) +10_ — не выполнено, нельзя выбрать несколько фильтров в одном типе
	
**[+10]** Можно отфильтровать товары по нескольким фильтрам разного типа +20
- _Для нескольких фильтров разного типа отображаются только те товары, которые соответствуют всем выбранным фильтрам_ — Отдельно "Фильтры по значению" работают корректно, но если после фильтрации по значению применить "Фильтры в указанном диапазоне от и до", то фильтрация некорректная; невозможно выполнить фильтрацию по цене и количеству одновременно (аналогично предыдущему сбрасывается предыдущий фильтр)
- _Если товаров, соответствующих всем выбранным фильтрам нет, на странице выводится уведомление в человекочитаемом формате, например, "Извините, совпадений не обнаружено"_ — сообщения нет

**[+15]** Сброс фильтров +20
- _При сбросе фильтров кнопкой reset, ползунки range slider сдвигаются к краям, значения ползунков возвращаются к первоначальным, range slider закрашивается одним цветом +10_ — Ползунки обнуляются только у только Price slider. У Quantity slider остаются в прежнем положении (но значение обнуляется)

**[+12]** Поиск +30
- _при открытии приложения курсор находится в поле поиска +2_ — не выполнено
- _автозаполнение поля поиска отключено +2_ — не выполнено
- _в поле поиска есть крестик, позволяющий очистить поле поиска +2_ — не выполнено
- _если нет совпадения последовательности букв в поисковом запросе с названием товара, выводится уведомление в человекочитаемом формате, например "Извините, совпадений не обнаружено" +2_ — не выполнено
- _Поиск ведётся только среди товаров, которые в данный момент отображаются на странице. Если очистить поле поиска, на странице отображаются товары, соответствующие всем выбранным фильтрам и настройкам сортировки +10_ — не выполнено, при поиске не учитываются примененные фильтры

**Полностью не выполненные требования:**
**[+0]** Сохранение настроек в local storage +30

**Замечания и проблемы, за которые не снижала балл:**

- Невозможно проверить выполнение условия "При попытке добавить в корзину больше 20 товаров, выводится всплывающее уведомление с текстом "Извините, все слоты заполнены" из-за того, что товаров меньше 20
- На мой взгляд сортировка по наименованию работает некорректно (сначала заглавные, после строчные). Правильнее будет в функции сортировки перед сравнением приводить строки к единому регистру (toUpperCase() или toLowerCase())
- Range slider имеет нижнюю границу 0, логичнее было бы использовать меньшее из имеющихся значений 
- Range slider зачем-то отображает дробную часть (особенно странно это выглядит для количества товаров). Можно настроить шаг в единицу(то есть только по целым числам) и отображение значений в подсказках. В документации даже есть готовый пример
- После перерисовки списка товаров (сортировка списка, кнопка reset) теряется выделение для товаров, ранее добавленных в корзину (при этом добавление/удаление продолжает корректно работать)
- В карточках никак не помечены популярные и новые товары, пришлось искать данные в коде, чтобы оценить корректность работы фильтров
