### ISSUE TITLE
Cross-Check 'virtual keyboard' - 'ilichka'

### ISSUE THREAD

**Issue by ilichka** [rolling-scopes-school/support#61]
Ссылка на деплой - https://ilichka.github.io/Virtual-Keyboard/
Ссылка на репозиторий с проектом на GitHub - https://github.com/ilichka/Virtual-Keyboard
Оценка в ходе самопроверки: 64

Реализована генерация DOM-элементов и body в index.html пустой изначально (может находится только тег script)-20/20. В моем проекте все сгенерированно в js, но торопясь забыл убрать текстэриа из хтмл. На мой взгляд это нельзя считать ошибкой, т.к. кроме этого недочета в виде тега текстэриа у меня нет ничего, только скрипт.

Нажатие на кнопку на физической клавиатуре подсвечивает кнопку на виртуальной (проверять следуюет нажатие цифр, букв, знаков припинания, backspace, del(если она присутствует), enter, shift, alt, ctrl, tab, caps lock, space, стрелки вниз-вверх-влево-вправо)-7/10. У меня багуется алт и контрл и баг достаточно незначительный в виде срабатывания левого и правого контрола(альта) все время на левом. Небольшая недоработка

Есть переключение между русским и английским языком (сочетание клавиш для переключения языка должно быть указано на странице с клавиатурой), а так же сохранение выбранного языка-7/15. Переключение языка есть на ктрл, нет его сохранения.

Клики мышкой по кнопкам на виртуальной клавиатуре или нажатие на кнопки физической клавиатуры, выводят символы в инпут (textarea)-15/15. Это в работе все присутствует и работает исправно. Проверяющий придрался к тому, что у меня нет автофокуса на текстэриа и снял мне баллы непонятно за что...

Реализована анимация нажатия на кнопку-15/15. Анимация при нажатии на кнопки как на физической так и на виртуальной клавиатуре присутствует.

Ошибки в консоли, связанные с исполняемым кодом(ошибки типа favicon.ico: Failed to load resource: the server responded with a status of 404 не учитываются)-нет. Проверяющий снял мне баллы за такие ошибки как: выкидывает ошибку, когда нажимаешь на клавишу физической клавиатуры и ее нет на виртуальной. Тут достаточно логично, что никакого ивента не будет происходить, т.к. такой клавиши нет и поэтому это не ошибка

 
![цукцукцук](https://user-images.githubusercontent.com/60748637/79049920-29834f80-7c2f-11ea-9481-ae746bd42b43.PNG)

**Comment by Student-Java** [comment]
Согласно правил
- Производится только если разница между ожидаемым вами баллом и полученным по результатам шага#4 средним арифметическим баллом **- 15 или более**.
Даже если экстраполировать разницу в баллах, то
75 * 15/100 = 11.25
