### ISSUE TITLE
Cross-Check Online-Store - Albinous

### ISSUE THREAD

**Issue by Albinous** [rolling-scopes-school/support#611]
1. https://rolling-scopes-school.github.io/albinous-JSFE2022Q1/online-store/
2. https://github.com/rolling-scopes-school/albinous-JSFE2022Q1
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md
4. Извиняюсь, что так поздно пишу насчет этого таска. Только сейчас узнала, что можно подать на issue. Дело в том, что я забыла сделать сабмит ссылки вовремя, вспомнив про него в последнюю минуту. Да, моя вина, полностью признаю. просто обидно, что делала его очень долго и в итоге по своей глупости лишилась всех 200 баллов. Если найдется добрый человек, то прошу просмотреть мою работу. Буду очень при очень благодарна!!!

**Comment by valerydluski** [comment]
к сожалению. данная ситуация не попадает под требования к апеляциям
