### ISSUE TITLE
 corejs 2022q1 distribution

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/support#612]
Этот тред создан для решения проблем возникающих в процессе распределения CoreJS.

пример: 

> я забыл зарегистрироваться на интервью

**Comment by denisselet** [comment]
я забыл зарегистрироваться на интервью

**Comment by S4mm4ael** [comment]
я забыл зарегистрироваться на интервью :(

**Comment by AndreiChaika** [comment]
Забыл зарегистрироваться на интервью, аналогично. 

P.S. С ментором несколько дней назад проработал список вопросов, а самое элементарное не сделал :(

**Comment by valerydluski** [comment]
@denisselet тебе нашёл ментора для интервью

остальным буду искать менторов

**Comment by ichernous94** [comment]
Позже зарегистрировался на интервью

**Comment by valerydluski** [comment]
@shahzod222 и @jkhvatova найти для ментора на интервью в первую очередь

**Comment by alexbazhen** [comment]
Проглядел анонс про регистрацию на интервью, из-за отъезда по семейным обстоятельствам, не успел зарегистрироваться вовремя.

**Comment by AlexBob98** [comment]
Меня тоже плиз добавьте 🙏🏻 По-братски))
Забыл, замотался недоджун ;))

**Comment by Jkhvatova** [comment]
> 
Мне вроде со второго раза сегодня ментора назначили, будет опять меняться? Спасибо:))

**Comment by Nastik95** [comment]
Я забыла зарегистрироваться на интервью:(

**Comment by MatsurSviat** [comment]
Я забыл зарегистрироваться на интервью

**Comment by IvanMakarishchev** [comment]
Извиняюсь, был слишком сосредоточен на выполнении тасков, не посмотрел что регистрация открыта. Запишите меня пожалуйста!

**Comment by Mikkumo** [comment]
я забыла зарегистрироваться на интервью

**Comment by m208** [comment]
Привет! Связался с ментором, а он больше не менторит =(
я: m208
он: navipro70

**Comment by aiscodes** [comment]
здравствуйте, я тоже забыла зарегистрироваться на интервью

**Comment by rocks-py** [comment]
Я забыл зарегистрироваться на интервью.

**Comment by ry-ksu** [comment]
Я забыла зарегистрироваться на интервью.

**Comment by Axe11er** [comment]
не могу связаться с ментором @Oleg_Sergeichik#7843 (https://github.com/sojud)

**Comment by antiqqt** [comment]
Добрый день. Ментор не выходит на связь - @Bakhromjon#7894 (https://github.com/bakhromsadullaev)

**Comment by darap1** [comment]
я забыл зарегистрироваться на интервью

**Comment by Makeichyk** [comment]
я забыл зарегистрироваться на интервью

**Comment by Jik789** [comment]
Ментор не отвечает уже 2 дня, его студент сообщил, что ментор в отпуске.

**Comment by Anhubtech** [comment]
Здравствуйте, у меня нет записи на интервью, запишите меня, пожалуйста, если это возможно.

**Comment by ValentinSinyakin** [comment]
Добрый день.
не успел зарегистрироваться на интервью(

**Comment by Slanx** [comment]
Здравствуйте, извините, нет записи на интервью, помогите если это возможно.

**Comment by Weranika** [comment]
Привет, не зарегестрировалась на интервью, думала со 02.08 начало регистрации, ан нет...заявку подала уже

**Comment by DiffickMenLogo** [comment]
Подал заявку 2 числа, но не получил ментора(

**Comment by AsyaBukato** [comment]
Привет, извините не зарегистрировалась вовремя на интервью, решила, что со 2 по 23 регистрация, а не проведение.

**Comment by NikitosBarboc** [comment]
не зарегистрировалась вовремя на интервью

**Comment by kosta4310** [comment]
Извиняюсь, тоже вот не прочитал вовремя про запись на интервью.,

**Comment by voshodz** [comment]
Не успел зерагаться на интервью

**Comment by valerydluski** [comment]
@S4mm4ael добавил ментора для интервью

**Comment by valerydluski** [comment]
> > 
> 
> Мне вроде со второго раза сегодня ментора назначили, будет опять меняться? Спасибо:))

нет

**Comment by S4mm4ael** [comment]
> @S4mm4ael добавил ментора для интервью

Спасибо огромное!

**Comment by SashaJozwiak** [comment]
я забыл зарегистрироваться на интервью

**Comment by SteGlaset** [comment]
я забыл зарегистрироваться на интервью

**Comment by DimaTeniuta** [comment]
[интервьюер](https://app.rs.school/profile?githubId=amirkakdela)  сообщил, что больше не может менторить и не смог провести интервью.

**Comment by firdavs-projects** [comment]
## Ментор не выходит на связь
я: Firdavs Abdulloev#4427 (@firdavs-projects)
он: [solairedev](https://app.rs.school/profile?githubId=solairedev)

**Comment by StraightToJaneStreet** [comment]
Добавьте в очереднь, опоздал на регистрацию. [@StraighToJaneStreet](https://app.rs.school/profile?githubId=straighttojanestreet)

**Comment by AlexKul84** [comment]
Ментор сообщил, что " К сожалению, в виду некоторых технических моментов, интервьюер Вам будет назначен другой."

**Comment by zhentosmak** [comment]
Выдали ментора для CoreJS Interview но он отписал что не сможет меня проверить . 
Мое имя в скор zhentosmak
Имя ментора  alexk08  (@kapacuk#1498)
Добавьте пожалуйста в очередь на нового интервьера по  CoreJS

**Comment by pitbrest** [comment]
Я забыл вовремя записаться видимо, хотя регистрацию точно прошел но в соответствующем разделе пусто, внесите меня в список пжл!

**Comment by valerydluski** [comment]
> ### Интервьюер не провел интервью
> [интервьюер](https://app.rs.school/profile?githubId=amirkakdela) сообщил, что больше не может менторить и не смог провести интервью.

у тебя новый ментор на интервью

**Comment by pitbrest** [comment]
> > ### Интервьюер не провел интервью
> > [интервьюер](https://app.rs.school/profile?githubId=amirkakdela) сообщил, что больше не может менторить и не смог провести интервью.
> 
> у тебя новый ментор на интервью @DimaTeniuta

Я могу ему писать о дате договариваться? На страничке школы то в соответствующей графе пусто..

**Comment by mDjeee** [comment]
Ментор сказал, что дропается с курса и мне нужно искать другого ментора для интервью

**Comment by InnokentyKedrov** [comment]
Я пропустил регистрацию, зарегистрировался только вчера

**Comment by Aliseiko** [comment]
Здравствуйте.
Регистрировался на интервью, но распределение не получил...
![изображение](https://user-images.githubusercontent.com/86059997/183262817-4999d6ec-e9b2-42d4-ac7b-7d8c28632f86.png)

**Comment by PDmitryY** [comment]
Добрый день. Ментор не выходит на связь 
![image](https://user-images.githubusercontent.com/19780026/183265186-6ff91892-2fdd-404d-b90f-dce8f2d6ead0.png)
Кроме discord другого канала связи не нашел

**Comment by 2248lm** [comment]
Добрый день! Ментор отписался, что не сможет провести интервью. Прошу назначить другого на Core JS.
![image](https://user-images.githubusercontent.com/87799811/183276980-5af7884b-73e2-4101-bbda-d864f19de5e5.png)

**Comment by valerydluski** [comment]
всё что будет за пределами этого issue не будет рассматриваться (@2248lm)

**Comment by valerydluski** [comment]
@m208 у тебя новый ментор для интервью

**Comment by 2248lm** [comment]
> всё что будет за пределами этого issue не будет рассматриваться (@2248lm)

Не совсем поняла Ваш ответ, если честно. Если касательно того, что заявку нужно оставлять здесь.
![image](https://user-images.githubusercontent.com/87799811/183289436-45ec139e-3e82-42a5-8613-6bc5f5837bba.png)
Мой ментор отписался, что не может провести интервью по Core JS, прошу записать в очередь на распределение к другому ментору, если еще не поздно. Заранее спасибо.

**Comment by Elvira-g** [comment]
Добрый день! Не было возможности зарегистрироваться на интервью( Очень прошу дать шанс

**Comment by Verigota** [comment]
Здравствуйте! я забыла зарегистрироваться на интервью

**Comment by beaJeniuS** [comment]
Здравствуйте! Регистрацию выполнил, но распределения не получил.
![изображение](https://user-images.githubusercontent.com/90112147/183308592-4c56bf68-39eb-4f96-a28e-4ace174afe64.png)
Прошу дать распределение...

**Comment by zone0119** [comment]
Здравствуйте.
Регистрировался на интервью, но распределение не получил...

**Comment by anton-evol** [comment]
Здравствуйте, пропустил регистрацию на интервью - зарегистрировался 7 августа. Поставьте, пожалуйста, в очередь.

**Comment by valerydluski** [comment]
@AndreiChaika у тебя появился ментор для интервью

**Comment by valerydluski** [comment]
@vermilion2020 появился ментор для интервью

**Comment by alexOm98** [comment]
Ментор не отвечает уже более 3-х дней
Ментор: offtop1

**Comment by vermilion2020** [comment]
> @vermilion2020 появился ментор для интервью

Спасибо огромное!!!

**Comment by aleksa-mnk** [comment]
Здравствуйте! Забыла зарегистрироваться на интервью.

**Comment by Res1dentEvil** [comment]
Я забыл зарегистрироваться на интервью

**Comment by IvanSavDev** [comment]
Ментор не отвечает в течении 3 дней

**Comment by AlixandrN** [comment]
Здравствуйте. Забыл зарегистрироваться на интервью. Зарегистрировался только сейчас, поставьте пож-та в очередь.

**Comment by UserJah** [comment]
Ментор sojud не отвечает более 3х дней

**Comment by dmitriStpaniuk** [comment]
я забыл зарегистрироваться на интервью

**Comment by RomaaaK** [comment]
Здравствуйте! Регистрацию выполнил, но распределения не получил.

**Comment by Dimasv6s** [comment]
Добрый день! не зарегистрировался до 2-го числа.

**Comment by EvgeniyaDanilovich** [comment]
К сожалению, зарегистрировалась на интервью после 01.08

**Comment by kramans1990** [comment]
Добрый день ! Зарегистрировался на интервью 3.08.2022. Можно ли меня добавить

**Comment by BromBom** [comment]
Здравствуйте! Ментор не выходит на связь.
![Снимок](https://user-images.githubusercontent.com/87293734/183842167-033083e6-bbfa-4f21-99b8-483855f06cf3.PNG)
В Telegram не отвечает. В Discord отсутствует. Других контактных данных нет

**Comment by OldWhaler** [comment]
Болел ковидом, не зарегился на интервью:( Оч хочется пройти....

**Comment by romababok** [comment]
Добрый день зарегистрировался ,но не получил ментора,не написал раньше ибо думал ,что еще будет  распределение .

**Comment by pashkovichma** [comment]
Здравствуйте. Мой ментор https://github.com/omirbeck не выходит на связь. Писала ему в Телеграмм 3.08.22 (просмотрено, но ответа нет) и в скайпе (не ответил). Других контактов для связи нет

**Comment by Harleycat80** [comment]
Добрый день. Если есть возможность,  поставьте пожалуйста в очередь. Поздняя регистрация(((

**Comment by valerydluski** [comment]
> Добрый день. Ментор не выходит на связь ![image](https://user-images.githubusercontent.com/19780026/183265186-6ff91892-2fdd-404d-b90f-dce8f2d6ead0.png) Кроме discord другого канала связи не нашел

у твоего ментора указан телеграм.

**Comment by valerydluski** [comment]
@ichernous94 у тебя появился ментор для интервью

**Comment by valerydluski** [comment]
@alexbazhen у тебя появился ментор для интервью

**Comment by valerydluski** [comment]
@alexOm98  у тебя появился ментор для интервью

**Comment by valerydluski** [comment]
@Nastik95 @MatsurSviat @IvanMakarishchev у вас появился ментор для интервью

**Comment by valerydluski** [comment]
@SashaJozwiak у тебя появился ментор для интервью

**Comment by valerydluski** [comment]
@pashkovichma у тебя появился ментор для интервью

**Comment by valerydluski** [comment]
@Mikkumo у тебя появился ментор для интервью

**Comment by valerydluski** [comment]
@aiscodes  у тебя появился ментор для интервью

**Comment by valerydluski** [comment]
@ry-ksu у тебя появился ментор для интервью

**Comment by valerydluski** [comment]
@darap1 @Makeichyk у вас появился ментор для интервью

**Comment by SteGlaset** [comment]
Здравствуйте, пропустил регистрацию, хотел бы пройти интервью (

**Comment by valerydluski** [comment]
@DiffickMenLogo у тебя появился ментор для интервью

**Comment by RigelTLT** [comment]
Здравствуйте, записался вовремя, но ментор для интервью так и не появился.

**Comment by valerydluski** [comment]
@RigelTLT я проверю. если вовремя зарегистрировался найду ментора

**Comment by MaxNikitenok** [comment]
Здравствуйте, затупил, зарегистрировался на интервью после 2-го

**Comment by ValentinBrest** [comment]
Привет, нужен опыт для прохождения интерью. Найдите ментора пожалуйста

**Comment by valerydluski** [comment]
@Anhubtech @ValentinSinyakin  у вас появился ментор для интервью

**Comment by laiker** [comment]
Здравствуйте! Регистрацию выполнил, но распределения не получил.

**Comment by AlexBob98** [comment]
Доброго дня 
Писал выше, комментарий скрыт, но ментор не получен 🤔

**Comment by Alex-Artsymenya** [comment]
Записался во время, но ментор не нашелся на первое интервью.

**Comment by drEdisn** [comment]
Здравствуйте, вроде как записался вовремя, но ментора на 1 интервью не получил.

**Comment by Salladin95** [comment]
я вроде записался 2-го и думал, что я сделал этот вовремя но все обернулась не так как я ожидал))

**Comment by goldyukol** [comment]
Доброго дня. Записывался на интервью, но ментор до сих пор не нашелся.

**Comment by valerydluski** [comment]
@AlexBob98 моя вина, по ошибке скрыл. у тебя появился ментор для интервью

**Comment by kramans1990** [comment]
Добрый день! Я поздно зарегистрировался на интервью CoreJS#1 . Можно ли как то получить распределение?

**Comment by ValentinBrest** [comment]
[valerydluski](https://github.com/valerydluski) Есть еще возможность получить интервьюера?  На первое интервью

**Comment by valerydluski** [comment]
@ValentinBrest  если будут желающие провести то да

**Comment by Vladimir-Kozinsky** [comment]
Добрый день, поздно зарегистрировался на CoreJS Interview. У меня есть еще возможность получить интервьюера?

**Comment by valerydluski** [comment]
@Weranika @SteGlaset у вас появился ментор для интервью

**Comment by azozulya** [comment]
Мой ментор(ник в дискорде @ineg22) не выходит на связь на этой неделе. Второе собеседование должно было быть, договаривались на эту неделю,но без конкретной даты

**Comment by SEvk4a** [comment]
Не знал что на регистрацию есть дедлайн, зарегистрировался только 15 августа, дадут ли мне ментора?

**Comment by dimtim1992** [comment]
Зарегистрировался на CoreJS Interview в начале августа, но проверяющего пока нет. Учитывая, что дедлайн по первому интервью 23.08, есть ли вероятность, что сроки продлят, чтобы успеть пройти интервью??

**Comment by valerydluski** [comment]
@Slanx у тебя появился ментор для интервью

**Comment by valerydluski** [comment]
я уже писал, что буду добавлять менторов, как только будут появлятся менторажелающие провести интервью

**Comment by GeoBo** [comment]
Добрый день. Пожалуйста, распределите к ментору, записывался 9-го.

**Comment by dimtim1992** [comment]
Здравствуйте
Зарегистрировался на coreJS в начале августа, но до сих пор не получил интервьюера.
К кому обратиться, чтобы можно было уточнить этот вопрос?

**Comment by valerydluski** [comment]
> Здравствуйте Зарегистрировался на coreJS в начале августа, но до сих пор не получил интервьюера. К кому обратиться, чтобы можно было уточнить этот вопрос?

я уже не раз писал, что если будут желающие ментора, то я буду постепенно создавать пары для интервью

**Comment by Vladimir-Kozinsky** [comment]
Доброе утро, я нашел ментора, который может провести интервью (ментор участника по команде). Может ли он провести? Что для этого нужно сделать?

**Comment by valerydluski** [comment]
> Доброе утро, я нашел ментора, который может провести интервью (ментор участника по команде). Может ли он провести? Что для этого нужно сделать?

создал тебе пару на интервью с ментором

**Comment by Vladimir-Kozinsky** [comment]
> > Доброе утро, я нашел ментора, который может провести интервью (ментор участника по команде). Может ли он провести? Что для этого нужно сделать?
> 
> создал тебе пару на интервью с ментором

Спасибо!!!

**Comment by AndreyGudin** [comment]
Здравствуйте. Ментор, которого мне определило подбором, не может провести CoreJS#2 интервью. Что в этом случае делать?

**Comment by laiker** [comment]
@valerydluski @kolem1 готов провести интервью создайте пожалуйста пару если есть возможность

**Comment by PavelZabalotny** [comment]
Помогите с распределением, ментор на core js 2 interview ответил, что больше не менторит наш поток.

**Comment by valerydluski** [comment]
> kolem1

создал

**Comment by valerydluski** [comment]
> Помогите с распределением, ментор на core js 2 interview ответил, что больше не менторит наш поток.

@PavelZabalotny @AndreyGudin отпишите сюда, чтобы не потерялось

**Comment by PavelZabalotny** [comment]
Помогите с распределением, ментор на core js 2 interview ответил, что больше не менторит наш поток.

**Comment by AndreyGudin** [comment]
Здравствуйте. Ментор, которого мне определило подбором, не может провести CoreJS#2 интервью. Помогите с повторным распределением

**Comment by valerydluski** [comment]
https://github.com/rolling-scopes-school/support/issues/656 по coreJS2 давайте сюда https://github.com/rolling-scopes-school/support/issues/656 
@PavelZabalotny @AndreyGudin @PavelZabalotny @AndreyGudin

**Comment by zone0119** [comment]
Добрый день! Я зарегистрировался поздно на интервью CoreJS#1 . Можно интервью пройти?

**Comment by valerydluski** [comment]
Желающих провести coreJS#1 больше нету. Требования по обязательному прохождению для сертификата отменили. issue закрываю
