### ISSUE TITLE
Cross-Check 'virtual-keyboard' - 'katrin-kot'

### ISSUE THREAD

**Issue by katrin-kot** [rolling-scopes-school/support#62]
Ссылка на деплой вашего проекта: https://katrin-kot.github.io/virtual-keyboard/
Ссылка на репозиторий с проектом на GitHub: https://github.com/katrin-kot/virtual-keyboard
Оценка в результате самопроверки, с ее аргументацией: 75
Выполненные пункты:
1) Реализована генерация DOM-элементов и body в index.html пустой изначально (может находится только тег script)
2) Нажатие на кнопку на физической клавиатуре подсвечивает кнопку на виртуальной (проверять следуюет нажатие цифр, букв, знаков припинания, backspace, del(если она присутствует), enter, shift, alt, ctrl, tab, caps lock, space, стрелки вниз-вверх-влево-вправо)
3) Есть переключение между русским и английским языком (сочетание клавиш для переключения языка должно быть указано на странице с клавиатурой), а так же сохранение выбранного языка

4) Клики мышкой по кнопкам на виртуальной клавиатуре или нажатие на кнопки физической клавиатуры, выводят символы в инпут (textarea)

5) Реализована анимация нажатия на кнопку

Балл за cross-check из вашего Score 66

![image](https://user-images.githubusercontent.com/24757285/79053070-24300000-7c43-11ea-8789-87fd349729b5.png)

**Comment by Student-Java** [comment]
Согласно правил
- Производится только если разница между ожидаемым вами баллом и полученным по результатам шага#4 средним арифметическим баллом **- 15 или более**.
Даже если экстраполировать разницу в баллах, то
75 * 15/100 = 11.25
