### ISSUE TITLE
Cross-Check 'async-race' - Res1dentEvil

### ISSUE THREAD

**Issue by Res1dentEvil** [rolling-scopes-school/support#628]
- Ссылка на деплой вашего проекта - https://rolling-scopes-school.github.io/res1dentevil-JSFE2022Q1/async-race/
- Ссылка на репозиторий с проектом на GitHub - https://github.com/rolling-scopes-school/res1dentevil-JSFE2022Q1/tree/async-race
 - Ссылка на задание - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
- Ссылка на форму для проверки проекта (если такая есть) -
- Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты). - 
![111111111](https://user-images.githubusercontent.com/51916910/184330422-fd2669be-5da7-4fe4-9795-1cfb63e34f64.png)

- Оценка в результате самопроверки с ее аргументацией - Я засабмитил в форму кросс чека не ссылку на деплой, а ссылку на Пул Реквест. Я понимаю, что это моя ошибка, но исправить я ее уже не мог. Как видно из скрина - от Студента 1 я получил 0 и контактов для связи с ним у меня не было, что бы дать ссылку на деплой. По итогу, меня проверило только 2 студента и получил я (190 +190 + 0) / 3 = 127. Обидно. (Оценка в результате самопроверки - 190).
- Балл за cross-check из вашего Score - 127

**Comment by valerydluski** [comment]
к сожалению твой случай не подходит к требованиям апелляций
