### ISSUE TITLE
Cross-Check 'async-race' - vl-fom

### ISSUE THREAD

**Issue by vl-fom** [rolling-scopes-school/support#629]
Прошу активистов проверить мою работу. Проверял работы студентов в ночи и не уследил за временем. Одну оценку успел поставить, ещё 2 система поставить не дала (после 3:05), из-за чего баллы за мою работу не начислились.

1. Link to your deployed project https://rolling-scopes-school.github.io/vl-fom-JSFE2022Q1/async-race/index.html
2. Link to the project repository on Github https://github.com/rolling-scopes-school/vl-fom-JSFE2022Q1/tree/async-race/async-race
3. Link to the task https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
4. Screenshot of cross-checking marks 
![image](https://user-images.githubusercontent.com/79394177/184387623-0468a581-a879-449f-8480-5a9f4dc2422d.png)
![image](https://user-images.githubusercontent.com/79394177/184387662-b557c45a-37da-4f5a-b21d-29bc0102b770.png)
5. Final score after self-assessment, with comments: 175,

- (-5) There should be pagination (10 winners per one page).

- (-10) User should be able to sort cars by wins number and by best time (ASC, DESC).

6. Cross-check score of your Score: 0.

**Comment by valerydluski** [comment]
твой случай не попадает под требования к апелляции
