### ISSUE TITLE
Cross-Check 'virtual-keyboard' - 'katerinaromanova' 

### ISSUE THREAD

**Issue by KaterinaRomanova** [rolling-scopes-school/support#63]
Ссылка на деплой - https://KaterinaRomanova.github.io/virtual-keyboard/
Ссылка на репозиторий с проектом на GitHub - https://github.com/KaterinaRomanova/virtual-keyboard
Оценка в ходе самопроверки: 75
Кнопка шифт работает корректно, также в проверке не указано ничего про кнопку шифт и снятие баллов. 
Оценка одного из проверяющих (проверяющий не оставил контакта):
![image](https://user-images.githubusercontent.com/44569848/79069394-871ea700-7cd6-11ea-8ea2-75765a554b7b.png)

**Comment by Student-Java** [comment]
Согласно правил
- Производится только если разница между ожидаемым вами баллом и полученным по результатам шага#4 средним арифметическим баллом **- 15 или более**.
Даже если экстраполировать разницу в баллах, то
75 * 15/100 = 11.25
