### ISSUE TITLE
Cross-Check 'AWS - Task 9 - Backend For Frontend' - 'ThorsAngerVaNeT'

### ISSUE THREAD

**Issue by ThorsAngerVaNeT** [rolling-scopes-school/support#633]
1. A link to your deployed project
    - FE deploy - https://dkct2oxjblzy1.cloudfront.net/
    - BFF Service API URL - http://thorsangervanet-bff-api-dev.eu-west-1.elasticbeanstalk.com/
      - [/products](http://thorsangervanet-bff-api-dev.eu-west-1.elasticbeanstalk.com/products) - equivalent of Product Service API URL provided above
      - [/cart](http://thorsangervanet-bff-api-dev.eu-west-1.elasticbeanstalk.com/cart) - equivalent of Cart Service API URL 
2. A link to the project repository on Github.
    - BE repo - https://github.com/ThorsAngerVaNeT/nodejs-aws-shop-be
    - BE PR - https://github.com/ThorsAngerVaNeT/nodejs-aws-shop-be/pull/6
    - FE repo - https://github.com/ThorsAngerVaNeT/nodejs-aws-shop-fe
    - FE PR - https://github.com/ThorsAngerVaNeT/nodejs-aws-shop-fe/pull/9
3. A link to the task - https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/9_backend_for_frontend/task.md
4. A screenshot of cross-checking marks - There are no marks...
5. A final score after self-assessment, with comments - 7/7
    - [x] +3 A working and correct Express application should be in the bff-service folder. Reviewer can start this application locally with any valid configuration in the .env file and this application should works as described in the Task 9.1
    - [x] +2 The BFF Service should be deployed with Elastic Beanstalk. The BFF Service call should be redirected to the appropriate service : Product Service or Cart Service. The response from the BFF Service should be the same as if Product Service or Cart Service services were called directly.
    - [x] +1 Add a cache at the BFF Service level for a request to the getProductsList lambda function of the Product Service. The cache should expire in 2 minutes.
    - [x] +1 Use NestJS to create BFF Service instead of Express
6. A cross-check score of your Score - 0/7

**Comment by valerydluski** [comment]
score 7
