### ISSUE TITLE
News API - 'al-r40'

### ISSUE THREAD

**Issue by Al-r40** [rolling-scopes-school/support#634]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
2. Screenshot: 
![image](https://user-images.githubusercontent.com/95902927/177608130-c9ed443c-c649-4de7-959f-c40bc6f40a4d.png)
3. Deploy: https://rolling-scopes-school.github.io/al-r40-JSFE2022Q1/news-JS/
4. Done 06.07.2022 / deadline 05.07.2022
5. Score 150 / 170
 - [x] Репозиторий +20
    - pull request выполнен в соответствии с требованиями +10
    - ведётся история коммитов, названия коммитов даются согласно гайдлайну +10
 - [x] Качество кода +90
 - приложение полностью смигрированно на TypeScript +40:
    - используется Everyday Types + 10
    - используются Generics  + 0
    - использование Object Types +10
    - использование Classes +10
    - использование Function +10
 - ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки +10
 - Нигде не используется тип Any +10
 - В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
 - Webpack настроен и работает с TypeScript +10
 - [x] Оформление и функционал приложения +50
    - выполнена адаптивная верстка +10
    - добавлен свой собственный дизайн или улучшения (добавлена смена темы при клике на текст: News Portal) +20
PR: https://github.com/rolling-scopes-school/al-r40-JSFE2022Q1/pull/23

**Comment by sugarcrm-snesterov** [comment]
taken to review
