### ISSUE TITLE
Online-Store - 'al-r40'

### ISSUE THREAD

**Issue by Al-r40** [rolling-scopes-school/support#635]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md
2. Screenshot: 
![image](https://user-images.githubusercontent.com/95902927/180230033-250cd4c5-2ee6-4ef3-921a-c51baeedbe4d.png)
3. Deploy: https://rolling-scopes-school.github.io/al-r40-JSFE2022Q1/online-store/src/
4. Done 2022-07-18 / deadline 2022-07-19
5. Score: 80 / 200
 - Репозиторий +20
 - Качество кода +10
 - ESLinter настроен на TypeScript и отсутствуют ошибки +10
 - В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
 - Код разбит на модули +10
 - Карточки товаров добавляются динамически средствами JavaScript +10
PR: https://github.com/rolling-scopes-school/al-r40-JSFE2022Q1/pull/25

**Comment by valerydluski** [comment]
score: 40
