### ISSUE TITLE
async-race - 'al-r40'

### ISSUE THREAD

**Issue by Al-r40** [rolling-scopes-school/support#636]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
2. Screenshot: 
![image](https://user-images.githubusercontent.com/95902927/183294485-3011f0b8-28db-4295-abd2-313c465850b2.png)
3. Deploy: https://rolling-scopes-school.github.io/al-r40-JSFE2022Q1/async-race/
4. Done 2022-08-07 / deadline 2022-08-09
5. Score: 85 / 150
- (+40) Application is divided to logical modules / layers.
- (+20) Webpack or another bundler should be used. There should be one HTML-file, JS-file, and one CSS-file (or it can be embedded right in the HTML-file).
- (+5) There are not unnecessary code duplications.
PR: https://github.com/rolling-scopes-school/al-r40-JSFE2022Q1/pull/27

**Comment by valerydluski** [comment]
нет менторов, желающих проверять
