### ISSUE TITLE
Online Store - "alimbaeva"

### ISSUE THREAD

**Issue by alimbaeva** [rolling-scopes-school/support#638]
1. Task: https://github.com/rolling-scopes-school/tasks/tree/master/tasks/online-store#verstka
2. Screenshot:
  
![os1](https://user-images.githubusercontent.com/88249718/179390797-0cb4a289-ef71-4f59-bb9f-1c020253c2db.png)
![os2](https://user-images.githubusercontent.com/88249718/179390802-4665fd16-747c-4cb4-ad1b-f42d9e4d4e19.png)
![os3](https://user-images.githubusercontent.com/88249718/179390803-e8ec484c-ba16-4748-b012-a9e21e34aff7.png)

3. Deploy:  [alimbaeva-online-store.netlify.app](https://alimbaeva-online-store.netlify.app/)
4. Done 17.07.2022 / deadline 19.07.2022
5. Score: 150 / 200
6. Link to PR: https://github.com/rolling-scopes-school/alimbaeva-JSFE2022Q1/pull/17

**Comment by micolka** [comment]
taken to review

**Comment by micolka** [comment]
Done. 
Code duplications and other minor issues (-10). 
No Generics types (-10).
No unit tests (-20). 
Detailed commens left in student's PR.
160 points
