### ISSUE TITLE
Async Race Api - "alimbaeva"

### ISSUE THREAD

**Issue by alimbaeva** [rolling-scopes-school/support#639]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md#cross-check
2. Screenshot:
   
![__1](https://user-images.githubusercontent.com/88249718/183533631-f95a0068-433f-4b54-938e-a9073fbb66e6.png)
![__2](https://user-images.githubusercontent.com/88249718/183533646-dd3dc0c8-a7e9-4ba0-97ed-f41a726b76de.png)
![__3](https://user-images.githubusercontent.com/88249718/183533662-16fc0afd-4a8a-4c14-907c-7cfc0baff784.png)

3. Deployment: [https://alimbaeva-async-race-api.netlify.app/on](https://alimbaeva-async-race-api.netlify.app/)
4. Done 09.08.2022 / deadline 09.08.2022
5. Score: 
     1. Cross-check: 100 / 190
     2. Mentor's review 70 / 150
6. Link to PR: https://github.com/rolling-scopes-school/alimbaeva-JSFE2022Q1/pull/18

**Comment by micolka** [comment]
taken to review

**Comment by micolka** [comment]
Done. Code duplications and magic numbers were found. Detailed commens left in student's PR.
140 points.
