### ISSUE TITLE
Cross-Check ‘virtual-keyboard’ Shevel

### ISSUE THREAD

**Issue by Shevel** [rolling-scopes-school/support#64]
https://shevel.github.io/virtual-keyboard/

https://github.com/Shevel/virtual-keyboard

Оценка в ходе самопроверки ~~55 баллов 

Student 4 выставил 0 
Есть выполненные пункты , поэтому я с оценкой 0 категорически не согласен. 
![7F144F2B-654E-46A1-B123-39A02372D7C9](https://user-images.githubusercontent.com/53993384/79097217-d5c85180-7d67-11ea-97e2-71aeb0ef66e7.jpeg)

**Comment by Student-Java** [comment]
Согласно правил
- Производится только если разница между ожидаемым вами баллом и полученным по результатам шага#4 средним арифметическим баллом **- 15 или более**.
Даже если экстраполировать разницу в баллах, то
75 * 15/100 = 11.25
