### ISSUE TITLE
News API - "alimbaeva"

### ISSUE THREAD

**Issue by alimbaeva** [rolling-scopes-school/support#641]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
2. Screenshot:
   
![1 1](https://user-images.githubusercontent.com/88249718/176991793-a1d1d3a5-a4a3-4351-98a1-906021a02c3c.png)
![1 2](https://user-images.githubusercontent.com/88249718/176991796-ad3e99dd-795f-4d99-8b81-d9e0aa2a3c17.png)
![1 3](https://user-images.githubusercontent.com/88249718/176991799-7f622086-1d34-47d7-bc04-d93d11287e4b.png)

3. Deploy:  https://alimbaeva-news-api.netlify.app/
4. Done 02.07.2022 / deadline 05.07.2022
5. Link to PR:  https://github.com/rolling-scopes-school/alimbaeva-JSFE2022Q1/pull/15
6.  Score: 170 / 170
     - При ширине экрана 500px, меняется блок sources - ему применено position: absolut;
     - Появляется кнопка Sources , при нажатие на него выходит новостные блоки, но не горизонтально, а вертикальном виде.
     - При нажати и выборе блока новости , сам блок новостей скрывается и появляется новости.
     - Был включен новый класс: 
![2 1](https://user-images.githubusercontent.com/88249718/176992277-7c81c081-a1c2-4f3d-8653-03dcbca26a29.png)

     - были изменены следующие файлы: app.ts, index.ts
     - 
![2 2](https://user-images.githubusercontent.com/88249718/176992312-a55d30b5-0747-4e6c-b083-99bf8d68b92d.png)
![2 3](https://user-images.githubusercontent.com/88249718/176992320-238bf7b3-eecc-4ba0-93a6-6e87b5e5abdb.png)

    - Добавлены в html file изменения:  footer был добавлен ссылки 
    - 
![2 4](https://user-images.githubusercontent.com/88249718/176992625-4bf223fe-823e-4384-afa3-eff457e4d2ae.png)

**Comment by micolka** [comment]
taken to review

**Comment by micolka** [comment]
LGFM - 170 points
