### ISSUE TITLE
News API - "S4mm4ael"

### ISSUE THREAD

**Issue by S4mm4ael** [rolling-scopes-school/support#642]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
2. Screenshot: 
![image](https://user-images.githubusercontent.com/93945710/186090302-280a0102-28ee-4353-83af-5d52a915d66f.png)
3. Deploy: https://s4mm4el-ts-news-migration.netlify.app/
Done 11.07.2022 / deadline 05.07.2022
Link to PR: https://github.com/rolling-scopes-school/s4mm4ael-JSFE2022Q1/pull/29
Score: 150 / 170

- [x] Репозиторий +20
- - pull request выполнен в соответствии с [требованиями](https://docs.rs.school/#/pull-request-review-process?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr) +10
- - ведётся история коммитов, названия коммитов даются согласно [гайдлайну](https://docs.rs.school/#/git-convention) +10
- [ ] Качество кода +90/100
- -приложение полностью смигрированно на TypeScript:
- - используется Everyday Types + 10
- - используются Generics +0
- - использование Object Types +10
- - использование Classes +10
- - использование Function +10
- - [x] ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки +10
- - [x] нигде не используется тип Any +10
- - [x] В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
- - [x] webpack настроен и работает с TypeScript +10
- [x] Оформление и функционал приложения +40
-  выполнена адаптивная верстка +10
-  добавлен свой собственный дизайн или улучшения (CSS) +10/20
-  у ментора нет замечаний к оформлению +20

**Comment by Andrewel** [comment]
score 150

**Comment by valerydluski** [comment]
оценка в score
