### ISSUE TITLE
Async-race  ( reakz )

### ISSUE THREAD

**Issue by ReakZ** [rolling-scopes-school/support#643]
1.[Task:](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md)
[Pull request:](https://github.com/rolling-scopes-school/reakz-JSFE2022Q1/pull/21)
2.Screenshot:
![_G__js_curs_2021end_rs2022_front-ep1_round4_reakz-JSFE2022Q1_async-race_deploy_index html](https://user-images.githubusercontent.com/12774452/183465119-eaf2d969-fd72-4a9f-bdaf-629333090341.png)

3.[Deploy:](https://rolling-scopes-school.github.io/reakz-JSFE2022Q1/async-race/deploy/)
4. Done: 08.08.2022 / Deadline  09.08.2022
--------------------------------------
5. Score: 

 ## Functional requirements
1. Basic structure:
 - [x] (**+5**) There should be two views on the site: "Garage" and "Winners".
 - [x] (**+5**) "Garage" view should contain its name, page number, and the full amount of items in the database (how many car user has in his garage).
 - [x] (**+5**) "Winners" view should contain its name, page number, and the full amount of items in the database (how many records the winners table contains).
 - [x]  (**+10**) View state should be saved when user switches from one view to another. For example, page number shouldn't be reset, input controls should contain that they contained before switching, etc.
2. "Garage" view:
 - [x]  (**+15**) User should be able to create, update, delete a car, and see the list of the cars. Car has only two attributes: "name" and "color". For "delete"-operation car should be deleted from "garage" table as well as from "winners".
 - [x] (**+10**) User should be able to select any color from an RGB-Palete [like here](https://www.colorspire.com/rgb-color-wheel/) and see the picture of the car colored with the color selected and car's name.
 - [x] (**+5**) Near the car's picture should be buttons to update its attributes or delete it.
 - [x]  (**+10**) There should be pagination on the "Garage" view (7 cars per one page).
 - [x]  (**+10**) There should be a button to create random cars (100 cars per click). Name should be assembled from two random parts, for example "Tesla" + "Model S", or "Ford" + "Mustang" (At least 10 different names for each part). Color should be also generated randomly.
3. Car animation:
 - [x]  (**+5**) Near the car's picture should be buttons for starting / stoping the car engine.
 - [x]  (**+20**) User clicks to the engine start button -> UI is waiting for car's velocity answer -> animate the car and makes another request to drive. In case api returned 500 error car animation should be stopped.
  - [x]  (**+5**) User clicks to the engine stop button -> UI is waiting for answer for stopping engine -> car returned to it's initial place.
 - [x] (**+5**) Start engine button should be disabled in case car is already in driving mode. As well as stop engine button should be disabled when car is on it's initial place.
  - [x]  (**+15**) Car animation should work fine on any screen (smallest screen size is 500px).
4. Race animation:
 - [x]  (**+10**) There should be a button to start race. After user clicks this button all the cars on the current page start driving.
 - [x]  (**+10**) There should be a button to reset race. After user clicks this button all the cars return to it's initial places.
 - [x]  (**+10**) After some car finishes first user should see the message contains car's name that shows which one has won.
5. "Winners" view:
   - [x]  (**+10**) After some car wins it should be displayed at the "Winners view" table.
   - [x] (**+5**) There should be pagination (10 winners per one page).
 - [x]  (**+10**) Table should include the next culumns: "№", "Image of the car", "Name of the car", "Wins number", "Best time in seconds" (names of the columns can differ). If the same car wins more than once the number of wins should be incremented while best time should be saved only if it's better than the stored one.
    - [x] (**+10**) User should be able to sort cars by wins number and by best time (ASC, DESC).

**Comment by ReakZ** [comment]
> нету ссылки на pr

добавил ссылку на пр
[Pull request:](https://github.com/rolling-scopes-school/reakz-JSFE2022Q1/pull/21)

**Comment by valerydluski** [comment]
добавь гитхаб в название

**Comment by valerydluski** [comment]
нет ментора, желающего проверить
