### ISSUE TITLE
Online-store ( reakz )

### ISSUE THREAD

**Issue by ReakZ** [rolling-scopes-school/support#644]
1.[Task:](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md)
[Pull request:](https://github.com/rolling-scopes-school/reakz-JSFE2022Q1/pull/14)
2.Screenshot:
![_G__js_curs_2021end_rs2022_front-ep1_round3_reakz-JSFE2022Q1_online-store_deploy_index html](https://user-images.githubusercontent.com/12774452/179625960-4e2c66f2-6488-4377-a23e-82c32668bd22.png)
3.[Deploy:](https://rolling-scopes-school.github.io/reakz-JSFE2022Q1/online-store/deploy/)
4. Done: 18.07.2022 / Deadline  19.07.2022
--------------------------------------
5. Score: 
180 / 200

 - [x]  Главная страница содержит все товары магазина а также фильтры, строку поиска, поле для сортировки. Выполняются [требования к вёрстке](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md#verstka) +10
 - [x]  Карточка товара содержит его изображение, название, количество данного товара на складе, год выхода на рынок, цвет, производитель и т.д., находится ли товар в корзине +10
 - [x]  Карточки товаров добавляются динамически средствами JavaScript (на кросс-чеке этот пункт не проверяется)
 - [x]  Добавление товаров в корзину +20
кликая по карточке с товаром или по кнопке на нем, товар можно добавлять в корзину или удалять. Карточки добавленных в корзину товаров внешне отличаются от остальных +10
на странице отображается количество добавленных в корзину товаров. При попытке добавить в корзину больше 20 товаров, выводится всплывающее уведомление с текстом "Извините, все слоты заполнены" +10
 - [x]  Сортировка +20
- - [x]  Сортируются только те товары, которые в данный момент отображаются на странице
сортировка товаров по названию в возрастающем и убывающем порядке +10
- - [x]  сортировка товаров по году их выхода на рынок в возрастающем и убывающем порядке +10
 - [x]  Фильтры в указанном диапазоне от и до +30
- - [x] Фильтры по количеству +10
- - [x] Фильтры по году выпуска на рынок +10
- - [x] для фильтрации в указанном диапазоне используется range slider с двумя ползунками. При перемещении ползунков отображается их текущее значение, разный цвет слайдера до и после ползунка +10

 - [x] Фильтры по значению +30
Выбранные фильтры выделяются стилем.
- - [x] фильтры по производителю +5
- - [x] фильтры по цвету +5
- - [x] фильтры по  по количеству камер +5
- - [x] можно отобразить только популярные товары +5
- - [x] можно отфильтровать товары по нескольким фильтрам одного типа +10
- - [x] Если для выбранной Вами тематики интернет-магазина указанные выше фильтры неактуальны, Вы можете добавить свои фильтры в зависимости от категории товара. Для нескольких фильтров одного типа отображаются товары, которые соответствуют хоть одному выбранному фильтру. Например, можно отобразить Samsung и Apple; или белые, синие и красные товары; или товары с 2 и 3 камерами.
- - [x] Можно отфильтровать товары по нескольким фильтрам разного типа +20
Для нескольких фильтров разного типа отображаются только те товары, которые соответствуют всем выбранным фильтрам.
Например, можно отобразить только красные товары. Или популярные белые и красные товары поступившие на рынок в 2010-2020 годах.
Если товаров, соответствующих всем выбранным фильтрам нет, на странице выводится уведомление в человекочитаемом формате, например, "Извините, совпадений не обнаружено".
 - [x] Сброс фильтров +20
- - [x] Есть кнопка reset для сброса фильтров +10
- - [x] Кнопка reset сбрасывает только фильтры, не влияя на порядок сортировки или товары, добавленные в избранное.
После использования кнопки reset фильтры остаются работоспособными
при сбросе фильтров кнопкой reset, ползунки range slider сдвигаются к краям, значения ползунков возвращаются к первоначальным, range slider закрашивается одним цветом +10
 - [x] Сохранение настроек в local storage +30
выбранные пользователем фильтры, порядок сортировки, добавленные в избранное товары сохраняются при перезагрузке страницы. 
- - [x] Есть кнопка сброса настроек, которая очищает local storage +10
 - [x] Поиск +30
- - [x] при открытии приложения курсор находится в поле поиска +2
- - [x] автозаполнение поля поиска отключено (нет выпадающего списка с предыдущими запросами) +2
- - [x] есть placeholder +2
- - [x] в поле поиска есть крестик, позволяющий очистить поле поиска +2
если нет совпадения последовательности букв в поисковом запросе с названием товара, выводится уведомление в человекочитаемом формате, например "Извините, совпадений не обнаружено" +2
при вводе поискового запроса на странице остаются только те товары, в которых есть указанные в поиске буквы в указанном порядке. При этом не обязательно, чтобы буквы были в начале слова. 
- - [x] Регистр символов при поиске не учитывается +10
- - [x] Поиск ведётся только среди товаров, которые в данный момент отображаются на странице.
если очистить поле поиска, на странице отображаются товары, соответствующие всем выбранным фильтрам и настройкам сортировки +10

**Comment by valerydluski** [comment]
нету ссылки на pr

**Comment by ReakZ** [comment]
> нету ссылки на pr
Добавил ссылку на пр
[Pull request:](https://github.com/rolling-scopes-school/reakz-JSFE2022Q1/pull/14)

**Comment by valerydluski** [comment]
нет ментора, желающего проверять
