### ISSUE TITLE
News API - "makrakvladislav"

### ISSUE THREAD

**Issue by makrakvladislav** [rolling-scopes-school/support#645]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
2. Screenshot: ![image](https://user-images.githubusercontent.com/18256562/177430749-9bb08c3b-637e-4da8-9f17-7c70dd34026e.png)

3. Deploy: https://rolling-scopes-school.github.io/makrakvladislav-JSFE2022Q1/migration-newip-to-ts/
4. Done 06.07.2022 / deadline 05.07.2022
5. Score: 160/ 170
6. PR: https://github.com/rolling-scopes-school/makrakvladislav-JSFE2022Q1/pull/7
- [x] Репозиторий +20
  - [x] pull request выполнен в соответствии с [требованиями](https://docs.rs.school/#/pull-request-review-process?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr) +10
  - [x] ведётся история коммитов, названия коммитов даются согласно [гайдлайну](https://docs.rs.school/#/git-convention) +10
- [x] Качество кода +100
  - [x] приложение полностью смигрированно на TypeScript +50:
    - [x] используется Everyday Types + 10
    - [x] используются Generics +10
    - [x] использование Object Types +10
    - [x] использование Classes +10
    - [x] использование Function +10
  - [x] ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки +10
  - [x] нигде не используется тип Any +10
  - [x] В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
  - [x] webpack настроен и работает с TypeScript +10
- [x] Оформление и функционал приложения +50
  - [x] выполнена адаптивная верстка +10
  - [x] добавлен свой собственный дизайн или улучшения +20
    - [x] Поиск
    - [x] Выбор языка 
- [x] у ментора нет замечаний к оформлению +20
- [ ] -10 баллов к оценке при опоздании до 3 дней включительно

**Comment by valerydluski** [comment]
нет ментора, желающего проверить
