### ISSUE TITLE
News api "Elena-code-dev"

### ISSUE THREAD

**Issue by Elena-code-dev** [rolling-scopes-school/support#646]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
Screen: 
![Снимок](https://user-images.githubusercontent.com/85871139/186124811-53568042-1dfb-498b-8d6e-4d2246ebda8d.PNG)

Deploy: https://rolling-scopes-school.github.io/elena-code-dev-JSFE2022Q1/News%20API/
Pull requests: https://github.com/rolling-scopes-school/elena-code-dev-JSFE2022Q1/pull/20
Done 2022-06-28 03:00 / deadline 2022-07-05 02:59
Score: 170 / 170
Репозиторий +20
- pull request выполнен в соответствии с требованиями +10
- ведётся история коммитов, названия коммитов даются согласно гайдлайну +10
Качество кода +100
- приложение полностью смигрированно на TypeScript +50
- используется Everyday Types + 10
- используются Generics +10
- использование Object Types +10
- использование Classes +10
- использование Function +10
ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки
нигде не используется тип Any +10
В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
webpack настроен и работает с TypeScript +10
Оформление и функционал приложения +50
выполнена адаптивная верстка +10
изменена структура показа списка новостей и источников, в header добавлен фон в виде картинки, поставлена картинка заглушка на случай если в новостях она отсутствует, в footer добавлена анимация на логотип школы +20

**Comment by valerydluski** [comment]
добавь в название issue свой гитхаб

**Comment by Elena-code-dev** [comment]
Готово))

**Comment by aykuli** [comment]
начала проверять
