### ISSUE TITLE
Online store - "eremor"

### ISSUE THREAD

**Issue by Eremor** [rolling-scopes-school/support#648]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md

2. Screenshot:
![image](https://user-images.githubusercontent.com/14091202/179517179-bf522172-935d-427c-bf1c-6bfa7d05b180.png)

3. Deploy: https://rolling-scopes-school.github.io/eremor-JSFE2022Q1/online-store/

4. Done 18.07.2022 / deadline 19.07.2022

5. Score mentor: 180 / 200
- [x] Репозиторий +20
   - [x] pull request выполнен в соответствии с требованиями +10
   - [x] ведётся история коммитов, названия коммитов даются согласно гайдлайну +10
- [x] Качество кода +160
   - [x] используется Everyday Types +10
   - [x] используются Generics +10
   - [x] использование Object Types +10
   - [x] использование Classes +10
   - [x] использование Function +10
   - [x] нигде не используется тип Any +10
   - [x] ESLinter настроен на TypeScript (используется плагин typescript-eslint/recommended) и отсутствуют ошибки +10
   - [x] В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
   - [x] webpack настроен и работает с TypeScript +10
   - [x] код разбит на модули +10
   - [x] карточки товаров добавляются динамически средствами JavaScript +10
   - [x] у ментора нет замечаний к качеству кода, либо все замечания ментора исправлены +30 (надеюсь что нет)
- [ ] Тесты в приложении +20

6. Link to PR: https://github.com/rolling-scopes-school/eremor-JSFE2022Q1/pull/18

**Comment by valerydluski** [comment]
нет ментора, желающего проверить
