### ISSUE TITLE
Async race - "eremor"

### ISSUE THREAD

**Issue by Eremor** [rolling-scopes-school/support#649]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
2. Screenshot:
![image](https://user-images.githubusercontent.com/14091202/183087334-6609fa4d-28aa-44e3-9728-320f271efe81.png)
3. Deploy:  - https://rolling-scopes-school.github.io/eremor-JSFE2022Q1/async-race/
4. Done 05.08.2022 / deadline 09.08.2022
5. Score: - 340 / 340

- Basic structure:
  - [x] (+5) There should be two views on the site: "Garage" and "Winners".
  - [x] (+5) "Garage" view should contain its name, page number, and the full amount of items in the database (how many car user has in his garage).
  - [x] (+5) "Winners" view should contain its name, page number, and the full amount of items in the database (how many records the winners table contains).
  - [x] (+10) View state should be saved when user switches from one view to another. For example, page number shouldn't be reset, input controls should contain that they contained before switching, etc.
- "Garage" view:
  - [x] (+15) User should be able to create, update, delete a car, and see the list of the cars. Car has only two attributes: "name" and "color". For "delete"-operation car should be deleted from "garage" table as well as from "winners". (не удаляет из победителей)
  - [x] (+10) User should be able to select any color from an RGB-Palete like here and see the picture of the car colored with the color selected and car's name.
  - [x] (+5) Near the car's picture should be buttons to update its attributes or delete it.
  - [x] (+10) There should be pagination on the "Garage" view (7 cars per one page).
  - [x] (+10) There should be a button to create random cars (100 cars per click). Name should be assembled from two random parts, for example "Tesla" + "Model S", or "Ford" + "Mustang" (At least 10 different names for each part). Color should be also generated randomly.

- Car animation:
  - [x] (+5) Near the car's picture should be buttons for starting / stoping the car engine.
  - [x] (+20) User clicks to the engine start button -> UI is waiting for car's velocity answer -> animate the car and makes another request to drive. In case api returned 500 error car animation should be stopped.
  - [x] (+5) User clicks to the engine stop button -> UI is waiting for answer for stopping engine -> car returned to it's initial place.
  - [x] (+5) Start engine button should be disabled in case car is already in driving mode. As well as stop engine button should be disabled when car is on it's initial place.
  - [x] (+15) Car animation should work fine on any screen (smallest screen size is 500px).

- Race animation:
  - [x] (+10) There should be a button to start race. After user clicks this button all the cars on the current page start driving.
  - [x] (+10) There should be a button to reset race. After user clicks this button all the cars return to it's initial places.
  - [x] (+10) After some car finishes first user should see the message contains car's name that shows which one has won.

- "Winners" view:
  - [x] (+10) After some car wins it should be displayed at the "Winners view" table.
  - [x] (+5) There should be pagination (10 winners per one page).
  - [x] (+10) Table should include the next culumns: "№", "Image of the car", "Name of the car", "Wins number", "Best time in seconds" (names of the columns can differ). If the same car wins more than once the number of wins should be incremented while best time should be saved only if it's better than the stored one.
  - [x] (+10) User should be able to sort cars by wins number and by best time (ASC, DESC).

- Non-functional requirements
  - [ ] (-100% for not fulfillment) It's forbidden to use any libraries or frameworks, like JQuery, React, Angular, Lodash, Material Design, etc. But you can use CSS from Bootstrap (CSS only!) if you wish. Note: It may be allowed to use React or Angular, but only if you've already studied at previous RS-course and/or pretty understand how to work with a DOM Api (DOM modification, Event Delegation) and only after agrement with a mentor!
  - [ ] (-100% for not fulfillment) Typescript must be used. Types of input and output parameters of all the methods must be described. Using type "any" is strictly forbidden.
  - [x] (+40) Application is divided to logical modules / layers. Like working with api it's separate module, as well as working with UI rendering, or working with an application state, etc. Better discuss architecture with a mentor before implementing.
  - [x] (+30) All the HTML-content is generated by JavaScript (body contains only one tag script inside).
  - [x] (+25) Application is SPA.
  - [x] (+20) Webpack or another bundler should be used. There should be one HTML-file, JS-file, and one CSS-file (or it can be embedded right in the HTML-file).
  - [x] (+15) Eslint with Airbnb style guide should be used. Some paricular eslint-rules can be disabled or changed only after agrement with a mentor. There shouldn't be any eslint errors or warnings.
  - [x] (+10) Code divided to small functions with a clear names and purposes. Each function should be less or equal to 40 lines.
  - [x] (+5) There are not unnecessary code duplications.
  - [x] (+5) Code shouldn't contain magical numbers or strings.

6. Link to PR: https://github.com/rolling-scopes-school/eremor-JSFE2022Q1/pull/19

**Comment by KrohNic** [comment]
Taken for review

**Comment by KrohNic** [comment]
150 points
