### ISSUE TITLE
Presentation - "eremor"

### ISSUE THREAD

**Issue by Eremor** [rolling-scopes-school/support#650]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/presentation.md
2. Screenshot:
![image](https://user-images.githubusercontent.com/14091202/122771142-d420e480-d2ae-11eb-8ade-837ad6ef4cdd.png)

3. Deploy: 
 - https://eremor-presentation.netlify.app/
 - https://youtu.be/6Ufq4J8h08Y
4. Done 10.08.2022 / deadline 16.08.2022
5. Score: 120 / 120
6. Link to PR: https://github.com/rolling-scopes-school/eremor-JSFE2022Q1/pull/20

**Comment by valerydluski** [comment]
Презентация прошлогодняя. Закрываю issue.
