### ISSUE TITLE
Async Race - "makrakvladislav"

### ISSUE THREAD

**Issue by makrakvladislav** [rolling-scopes-school/support#651]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
2. Screenshot: 
![image](https://user-images.githubusercontent.com/18256562/186396453-aa6a1511-3c78-4e5a-89da-a96513486a1f.png)

3. Deploy: https://rolling-scopes-school.github.io/makrakvladislav-JSFE2022Q1/async-race/
4. Done 11.08.2022 / deadline 09.08.2022
5. Score: 85/ 150
6. PR: https://github.com/rolling-scopes-school/makrakvladislav-JSFE2022Q1/pull/9

Non-functional requirements:

- [x] (+30) All the HTML-content is generated by JavaScript (body contains only one tag script inside).
- [x] (+25) Application is SPA.
- [x] (+20) Webpack or another bundler should be used. There should be one HTML-file, JS-file, and one CSS-file (or it can be embedded right in the HTML-file).
- [x] (+15) Eslint with [Airbnb style guide](https://github.com/airbnb/javascript) should be used. Some paricular eslint-rules can be disabled or changed only after agrement with a mentor. There shouldn't be any eslint errors or warnings.
- [x] (+5) There are not unnecessary code duplications.
- [x] (+5) Code shouldn't contain magical numbers or strings.
- [x]  -10 баллов к оценке при опоздании до 3 дней включительно

**Comment by valerydluski** [comment]
нет ментора, желающего проверить
