### ISSUE TITLE
Migration news to ts "anvianvi"

### ISSUE THREAD

**Issue by anvianvi** [rolling-scopes-school/support#652]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
2. Screenshot:
![image](https://user-images.githubusercontent.com/18510538/177206866-de3a8613-8bc2-4e2a-a111-bc0a063f5a88.png)
3. https://rolling-scopes-school.github.io/anvianvi-JSFE2022Q1/migration-newip-to-ts/dist/
4. Done 05.07.2022 / deadline 06.07.2022
5. Score: 160/ 170
https://github.com/rolling-scopes-school/anvianvi-JSFE2022Q1/tree/migration-newip-to-ts
Репозиторий +20

- pull request выполнен в соответствии с [требованиями](https://docs.rs.school/#/pull-request-review-process?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr) +10
- ведётся история коммитов, названия коммитов даются согласно [гайдлайну](https://docs.rs.school/#/git-convention) +10

Качество кода +100

- приложение полностью смигрированно на TypeScript +50:
- используется Everyday Types + 10
- используются Generics +10
- использование Object Types +10
- использование Classes +10
- использование Function +10
- ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки +10
- нигде не используется тип Any +10
- В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
- webpack настроен и работает с TypeScript +10
- 
Оформление и функционал приложения +50

- выполнена адаптивная верстка +10
- добавлен свой собственный дизайн или улучшения (в ПР должно быть описано что именно) +20
- у ментора нет замечаний к оформлению +20

**Comment by Andrewel** [comment]
score 160
