### ISSUE TITLE
Online store "anvianvi"

### ISSUE THREAD

**Issue by anvianvi** [rolling-scopes-school/support#653]
https://github.com/rolling-scopes-school/anvianvi-JSFE2022Q1/pull/8

1. Task: https://github.com/rolling-scopes-school/tasks/tree/master/tasks/online-store
2. Screenshot:
  ![image](https://user-images.githubusercontent.com/18510538/179664500-637a1eb5-db19-47ff-beab-c24878270cba.png)
3. Deploy: https://rolling-scopes-school.github.io/anvianvi-JSFE2022Q1/
4. Done 19.07.2020 / deadline 19.07.2020
5. Score: 180/ 200
Репозиторий +20
pull request выполнен в соответствии с [требованиями](https://docs.rs.school/#/pull-request-review-process?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr) +10
ведётся история коммитов, названия коммитов даются согласно [гайдлайну](https://docs.rs.school/#/git-convention) +10
Качество кода +160
приложение написано на TypeScript.
используется Everyday Types +10
используются Generics +10
использование Object Types +10
использование Classes +10
использование Function +10
нигде не используется тип Any +10
ESLinter настроен на TypeScript (используется плагин typescript-eslint/recommended) и отсутствуют ошибки +10
В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
webpack настроен и работает с TypeScript +10
код разбит на модули +10
карточки товаров добавляются динамически средствами JavaScript +10
у ментора нет замечаний к качеству кода, либо все замечания ментора исправлены +30
Тесты в приложении 0/+20 
реализованы юнит-тесты, использующие различные методы jest – 2 балла за каждую покрытую функию/метод, но не более 20 баллов (процент покрытия каждой функции/метода не учитывается)

**Comment by Exedystyle** [comment]
@anvianvi could you please share actual "deploy" link?

**Comment by anvianvi** [comment]
@Exedystyle  updated https://rolling-scopes-school.github.io/anvianvi-JSFE2022Q1/

**Comment by Andrewel** [comment]
score 180
