### ISSUE TITLE
Asinc race "anvianvi"

### ISSUE THREAD

**Issue by anvianvi** [rolling-scopes-school/support#654]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md

Screenshot: 
![image](https://user-images.githubusercontent.com/18510538/186439693-adec158a-65c1-468d-b254-f6c50a1ab59d.png)

Deploy: https://anvianvi.github.io/async-race/dist/
repo: https://github.com/anvianvi/async-race
pull: https://github.com/rolling-scopes-school/anvianvi-JSFE2022Q1/pull/14
Done 08.08.2022 / deadline 09.08.2022

Score: 85/ 150

Non-functional requirements:
(+30) All the HTML-content is generated by JavaScript (body contains only one tag script inside).
(+25) Application is SPA.
(+15) Eslint with [Airbnb style guide](https://github.com/airbnb/javascript) should be used. Some paricular eslint-rules can be disabled or changed only after agrement with a mentor. There shouldn't be any eslint errors or warnings.

(+40) Application is divided to logical modules / layers. Like working with api it's separate module, as well as working with UI rendering, or working with an application state, etc. Better discuss architecture with a mentor before implementing.
(+20) Webpack or another bundler should be used. There should be one HTML-file, JS-file, and one CSS-file (or it can be embedded right in the HTML-file).
(+10) Code divided to small functions with a clear names and purposes. Each function should be less or equal to 40 lines.
(+5) There are not unnecessary code duplications.
(+5) Code shouldn't contain magical numbers or strings.

**Comment by valerydluski** [comment]
оценка в score
