### ISSUE TITLE
Presentation "anvianvi"

### ISSUE THREAD

**Issue by anvianvi** [rolling-scopes-school/support#655]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/presentation.md

Screenshot:
![image](https://user-images.githubusercontent.com/18510538/186449254-ebc2f4ad-36a2-40ee-aa88-f016572d71af.png)

Deploy:

https://anvianvi.github.io/Presientation/#/5 
https://youtu.be/O8c7zPLKdk8

Done 15.08.2022 / deadline 16.08.2022 +120 

Basic scope. 120 points. All steps below must be completed
Prepare your presentation using Reveal. Slides and speech transcript have to be in English
Record your speech in English. Two options are possible:
using a camera (webcam, phone, videocamera or so). Your face and your presentation's slides have to be in frame ([good example](https://www.youtube.com/watch?v=JezLAu4751Y&feature=youtu.be)).
using [OBS](https://obsproject.com/) or any other recording program. Your face and your presentation's slides have to be in frame.
Upload the resulting video to your YouTube account. You can set the unlisted property for your video if you wish for no one else to see it (unless they get provided a link to the video).
Add a link to your slides in the video description.
Make sure that the recording of the speech, the transcript of a presentation and any additional comments are in English
Create a presentation branch in your private school repository. Create a markdown file presentation.md and fill it with:
a link to your YouTube video;
a link to your Reveal presentation's deploy;
(optional) a link to the transcript of your presentation;
(optional) your comments;
Open a Pull Request. The title should be presentation. Do not merge it.

**Comment by Andrewel** [comment]
score 120
