### ISSUE TITLE
corejs2 2022q1

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/support#656]
Только для тех у кого ментор не может провести интервью.

тех кто забыл пройти регистрацию просьба не писать

**Comment by PavelZabalotny** [comment]
Получил распределение по core js 2 interview, но ментор отказывается проводить, помогите пожалуйста с перераспределением.

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/186881456-1986e057-01e6-4c5e-b94f-89548510215d.png)

**Comment by AndreyGudin** [comment]
Здравствуйте. Ментор, которого мне определило подбором, не может провести CoreJS#2 интервью. Помогите с повторным распределением

**Comment by PavelZabalotny** [comment]
Получил распределение по core js 2 interview, но ментор отказывается проводить, помогите пожалуйста с перераспределением.

**Comment by gremlin654** [comment]
Получил, распределения по core js 2 interview, но ментор не выходит на связь, не отвечает. Помогите пожалуйста с повторным распределением

**Comment by Cstrp** [comment]
Сап. https://github.com/valeryiachukovich по ласт core js interview, не выходит на связь, писал дискорд, скайп, телега - ответа нет. Хелп

**Comment by laiker** [comment]
Получил, распределения по core js 2 interview, но ментор @sojud не выходит на связь, не отвечает. Помогите пожалуйста с повторным распределением

**Comment by valerydluski** [comment]
@hanna-mamedova @mindr17 нашёл нового ментора для интервью

**Comment by SOjuD** [comment]
@valerydluski мы уже решили вопрос со студентом

**Comment by MaxNikitenok** [comment]
Здравствуйте) Ментор, которого мне назначили, не может провести CoreJS#2 интервью. Помогите с повторным распределением

**Comment by gremlin654** [comment]
@valerydluski удалось связаться с ментором, договорились о проведении интервью.

**Comment by dimtim1992** [comment]
Здравствуйте
Ментор не отвечает на сообщения.
Прошу помощи с повторным распределением
Спасибо

**Comment by maxomeleneckii** [comment]
Добрый день!
Интервьюер на ласт интервью CoreJS#2 не отвечает! Написал ему 24.08.22! Из контактов только дискорд! путём долгих поисков удалось найти его почту но результата ноль!
Прошу помощи с повторным распределением! Спасибо!

**Comment by rmnvch** [comment]
Привет! Ментор не вышел на связь. Просьба перераспределить. Спасибо

**Comment by kelzerock** [comment]
Привет. Учусь на js 2022q1. Пропустил регистрацию на js interview#2. Понимаю свою ошибку. Но очень, не очень впечатляет перспектива  не получить сертификат из-за одного таска. Остальное все реализовано и много сил потрачено. Неужели ничего нельзя сделать? Может быть можно как то помочь в такой ситуации? Готов поискать сам ментора который проведёт это интервью, из действующих на этом потоке.  Please help

**Comment by valerydluski** [comment]
@AndreyGudin у тебя новый ментор

**Comment by Elena-code-dev** [comment]
Ментор https://github.com/mikola-litvin,  по core js2 interview, не выходит на связь, писала дискорд - ответа нет. Что то можно сделать?

**Comment by rmnvch** [comment]
> Ментор https://github.com/mikola-litvin, по core js2 interview, не выходит на связь, писала дискорд - ответа нет. Что то можно сделать?

В скайп пишите, сегодня общался с ним

**Comment by valerydluski** [comment]
@varenik40000 у тебя новый ментор

**Comment by valerydluski** [comment]
@Elena-code-dev  связалась?

**Comment by malashonock** [comment]
@valerydluski, привет! я тоже не могу никак достучаться до своего интервьюера по CoreJS #2: https://app.rs.school/profile?githubId=tarasdemidovich1995 (пробовал discord, gmail, telegram - нет реакции). какие д.б. мои дальнейшие действия?

**Comment by varenik40000** [comment]
Должны поменять. Смотри свой профиль

чт, 1 сент. 2022 г., 14:42 Yan Malashonak ***@***.***>:

**Comment by valerydluski** [comment]
@malashonock @Cstrp написал вашим менторам я думаю в ближайшее время ваш вопрос решиться

**Comment by Pixel-King** [comment]
Привет! Ментор не отвечает, помогите пожалуйста

**Comment by Cstrp** [comment]
@valerydluski Большущая благодарность, ментор появилась

**Comment by FeuerImBlut** [comment]
Добрый день. Ментор Andrei Ulasau сообщил, что не может провести у меня интервью.

**Comment by pssofer** [comment]
Добрый день. Ментор(krllgranin), которого мне назначили, не может провести CoreJS#2 интервью. Помогите с повторным распределением

**Comment by vasily-mishanin** [comment]
Зарегался, писал везде, но интервьюер  https://github.com/omirbeck не отвечает

**Comment by valerydluski** [comment]
@PavelZabalotny у тебя новый ментор на интервью

**Comment by valerydluski** [comment]
@dimtim1992 связался с твоим ментором ответит тебе

**Comment by valerydluski** [comment]
@Elena-code-dev закрываю твой коммент, так как ты игноришь мои сообщения

**Comment by valerydluski** [comment]
@MaxNikitenok у тебя новый ментор на интервью

**Comment by valerydluski** [comment]
@maxomeleneckii у тебя новый ментор на интервью

**Comment by kettl96** [comment]
Добрый день. Был в командировке и забыл про регистрацию. Можно как то получить ментора для второго интервью. Заранее спасибо

**Comment by botino-k** [comment]
Добрый день! Интервьюер не отвечает. Нужна помощь. iZamza#9303

**Comment by antipachita** [comment]
Здравствуйте, записался на  core js 2 interview, но ментор не выходит на связь, писал повторно , однако ответа так и не получил. Помогите пожалуйста с повторным распределением. Dis : @yaemkashu#9556. Телеграм vlad strgn

**Comment by Lebedev-023046** [comment]
Здравствуйте, ментор в CoreJS#2 не отвечает с 23 августа. Как можно пройти повторное распределение? 
Discord: Lebedev-023046#9826
Telegram: https://t.me/swan_023046

**Comment by OOOO0000OOO0000OOO** [comment]
Здравствуйте! К сожалению, мне [ментор](https://app.rs.school/profile?githubId=alisheyx-life) не отвечает более трех суток.
Могу ли я получить нового? Спасибо.

**Comment by Elena-code-dev** [comment]
> @Elena-code-dev связалась?

Ооооо, нет он так и не отвечает

**Comment by sevc4ik** [comment]
Здравствуйте, ментор в CoreJS#2 не отвечает. 
Помогите пожалуйста с повторным распределением.
Discord: sevc4ik#4366
Telegram: https://t.me/sevc4ik

**Comment by npwsk** [comment]
Здравствуйте, [интервьюер](https://github.com/tropler) назначил дату собеседования, но не вышел в эту дату на связь, и уже три дня не отвечает. Помогите, пожалуйста

**Comment by pssofer** [comment]
> Добрый день. Ментор(krllgranin), которого мне назначили, не может провести CoreJS#2 интервью. Помогите с повторным распределением

Сам-но нашел себе ментора для интервью. Сможете мне его распределить
Вот он https://github.com/CatherineShemenkova

**Comment by valerydluski** [comment]
@Denhope @pssofer закинул

**Comment by npwsk** [comment]
> Здравствуйте, [интервьюер](https://github.com/tropler) назначил дату собеседования, но не вышел в эту дату на связь, и уже три дня не отвечает. Помогите, пожалуйста

Прошу прощения за панику, вопрос решился. Ментор был без связи, но сможет в другой день.

**Comment by rybamax23** [comment]
Здравствуйте, ментор сообщил, что не сможет провести интервью!

**Comment by rybakovmax23** [comment]
Здравствуйте, ментор сообщил, что не сможет провести интервью!

**Comment by tihohohodka** [comment]
Здравствуйте, ментор сегодня сообщил, что не сможет провести интервью.
Помогите с повторным распределением.
Telegram: https://t.me/BooleanN
Discord: iScream#5138

**Comment by kettl96** [comment]
Добрый день. Пропустил регистрацию, но нашёл ментора который согласен провести интервью. Можете его распределить мне? Заранее спасибо.
Его github:
https://github.com/andron13

**Comment by valerydluski** [comment]
@tihohohodka хакинул тебе нового ментора на интервью

**Comment by valerydluski** [comment]
@antipachita закинул тебе нового ментора на интервью

**Comment by valerydluski** [comment]
@FeuerImBlut закинул тебе ментора

**Comment by valerydluski** [comment]
@rybakovmax23 закинул

**Comment by valerydluski** [comment]
@Pixel-King закинул
