### ISSUE TITLE
migration-newip-to-ts (kasitsyn)

### ISSUE THREAD

**Issue by Kasitsyn** [rolling-scopes-school/support#657]
0. PR: https://github.com/rolling-scopes-school/kasitsyn-JSFE2022Q1/pull/49#issue-1361853603
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
2. Screenshot:
   ![image](https://user-images.githubusercontent.com/9220206/186419895-ce2bca91-3482-4f92-9259-b9af1810a1eb.png)
3. Deploy: https://rolling-scopes-school.github.io/kasitsyn-JSFE2022Q1/migration-newip-to-ts/
4. Done 2022-07-05 / deadline 2022-07-05
5. Score: 170 / 170
- Качество кода +100
  - [x] приложение полностью смигрированно на TypeScript +50
    * используется Everyday Types + 10
    * используются Generics +10
    * использование Object Types +10
    * использование Classes +10
    * использование Function +10
  - [x] ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки +10
  - [x] нигде не используется тип Any +10
  - [x] В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
  - [x] webpack настроен и работает с TypeScript +10
- Оформление и функционал приложения +50
  - [x] выполнена адаптивная верстка +10
  - [x] добавлен свой собственный дизайн или улучшения +20
  - [x] у ментора нет замечаний к оформлению +20

**Comment by helenakrasnova** [comment]
отсутствует история разработки 
![image](https://user-images.githubusercontent.com/44213581/189134171-87f08bab-7aa9-4098-aedf-bdf75ba48e3b.png)

**Comment by valerydluski** [comment]
@helenakrasnova  thanks
