### ISSUE TITLE
async-race

### ISSUE THREAD

**Issue by dsh91698** [rolling-scopes-school/support#659]
pr https://github.com/rolling-scopes-school/dsh91698-JSFE2022Q1/pull/33#issue-1332473576

1.Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md

2.Screenshot:
![Screenshot 2022-08-25 at 17-39-01 Async Race App](https://user-images.githubusercontent.com/56885229/186680808-9dcd32d0-ee80-427e-8e37-b2ed841d5af3.png)
3.Deploy: https://rolling-scopes-school.github.io/dsh91698-JSFE2022Q1/async-race/dist/index.html
4.Done 09.08.2022 / deadline 09.08.2022 23:59 UTC

5.Score: 5 (for Functional requirements)
Functional requirements
Basic structure:
[+](https://github.com/rolling-scopes-school/dsh91698-JSFE2022Q1/pull/+5) There should be two views on the site: "Garage" and "Winners".
Score: 110 (Non-functional requirements:)
Non-functional requirements:
[+](+30) All the HTML-content is generated by JavaScript (body contains only one tag script inside).
[+](+25) Application is SPA.
[+](+15) Eslint with [Airbnb style guide](https://github.com/airbnb/javascript) should be used. Some paricular eslint-rules can be disabled or changed only after agrement with a mentor. There shouldn't be any eslint errors or warnings.
[-](+40) Application is divided to logical modules / layers. Like working with api it's separate module, as well as working with UI rendering, or working with an application state, etc. Better discuss architecture with a mentor before implementing.
[+](+20) Webpack or another bundler should be used. There should be one HTML-file, JS-file, and one CSS-file (or it can be embedded right in the HTML-file).
[+](+10) Code divided to small functions with a clear names and purposes. Each function should be less or equal to 40 lines.
[+](+5) There are not unnecessary code duplications.
[+](+5) Code shouldn't contain magical numbers or strings.

**Comment by valerydluski** [comment]
добавь в название issue свой гитхаб

**Comment by valerydluski** [comment]
нет ответа. закрываю
