### ISSUE TITLE
Cross-Check 'Virtual Keyboard' - 'Ragneda'

### ISSUE THREAD

**Issue by Ragneda** [rolling-scopes-school/support#66]
Ссылка на деплой вашего проекта - https://ragneda.github.io/Virtual-keyboard/
Ссылка на репозиторий с проектом на GitHub - https://github.com/Ragneda/Virtual-keyboard
Оценка в результате самопроверки, с ее аргументацией : моя оценка - 60 баллов 

Выполненные пункты:
1) Реализована генерация DOM-элементов и body в index.html пустой изначально (может находится только тег script) +20

2) Нажатие на кнопку на физической клавиатуре подсвечивает кнопку на виртуальной (проверять следует нажатие цифр, букв, знаков препинания, backspace, del(если она присутствует), enter, shift, alt, ctrl, tab, caps lock, space, стрелки вниз-вверх-влево-вправо) +10

3) Клики мышкой по кнопкам на виртуальной клавиатуре или нажатие на кнопки физической клавиатуры, выводят символы в инпут (textarea) +15

4) Реализована анимация нажатия на кнопку +15

Балл за cross-check  Score - 32.

**Comment by Student-Java** [comment]
И зачем опять закрыла?

**Comment by Ragneda** [comment]
Я не ту заявку закрыла , сейчас открою . У меня их было две

вт, 14 апр. 2020 г. в 15:18, Student-Java <notifications@github.com>:

**Comment by Alexey-Koren** [comment]
В течение двух часов всё проверю

**Comment by Ragneda** [comment]
Заранее спасибо!

**Comment by Alexey-Koren** [comment]
Пока что предварительный результат такой:

Ваша оценка - 52.5 балла 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Есть переключение между русским и английским языком (сочетание клавиш для переключения языка должно быть указано на странице с клавиатурой), а так же сохранение выбранного языка 

Частично выполненные пункты:
1) Клики мышкой по кнопкам на виртуальной клавиатуре или нажатие на кнопки физической клавиатуры, выводят символы в инпут (textarea) 
Отзыв: На клики мыши клавиатура не реагирует

Выполненные пункты:
1) Реализована генерация DOM-элементов и body в index.html пустой изначально (может находится только тег script) 

2) Нажатие на кнопку на физической клавиатуре подсвечивает кнопку на виртуальной (проверять следует нажатие цифр, букв, знаков препинания, backspace, del(если она присутствует), enter, shift, alt, ctrl, tab, caps lock, space, стрелки вниз-вверх-влево-вправо) 
Отзыв: Ты не перехватываешь введенные символы. Выводит буквы текущего языка ОС.
3) Реализована анимация нажатия на кнопку

**Comment by Alexey-Koren** [comment]
Сейчас уточняю вопрос по 3-му пункту, насколько мне известно, надо было реализовывать работу вывода в textarea, как по нажатию с физ. клавиатуры, так и при клике мыши

**Comment by Ragneda** [comment]
Написано или, поэтому я считала что или то или то

**Comment by Ragneda** [comment]
Спасибо за проверку и потраченное время!

**Comment by Alexey-Koren** [comment]
[Ссылка на разбор клавиатуры создателем таска, таймкод 03:30](https://youtu.be/9xlASUb9tyo?t=171)

**Comment by Ragneda** [comment]
Понятно

**Comment by dzmitry-varabei** [comment]
@Alexey-Koren спасибо!
