### ISSUE TITLE
News API (migration to typescript) - "RTinIT"

### ISSUE THREAD

**Issue by RTinIT** [rolling-scopes-school/support#663]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
2. Screenshot:
![2022-07-04_18-48-11](https://user-images.githubusercontent.com/90758660/177187373-e5811693-8ce1-446e-a705-c5be7d9deea2.png)
3. Deploy: https://silver-monstera-af40a9.netlify.app/
4. Done 04.07.2022 / deadline 05.07.2022
5. Link to PR https://github.com/rolling-scopes-school/rtinit-JSFE2022Q1/pull/13
6. Score: 150 / 170
Репозиторий +20
    -pull request выполнен в соответствии с требованиями +10
    -ведётся история коммитов, названия коммитов даются согласно +10
Качество кода +100
    -приложение полностью смигрированно на TypeScript +50:
    -используется Everyday Types + 10
    -используются Generics +10
    -использование Object Types +10
    -использование Classes +0
    -использование Function + 0
    -ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки +10
    -нигде не используется тип Any +10
    -в конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
    -webpack настроен и работает с TypeScript +10
Оформление и функционал приложения +50
    -выполнена адаптивная верстка +10
    -добавлен свой собственный дизайн или улучшения (в ПР должно быть описано что именно) +10

Добавил картинку на background, согласен, что не лучшего качества.
Расположил блоки с новостями и ссылками горизонтально для desktop version.
Ссылки и новости обладают вертикально полосой прокрутки, а на mobile и tablet у ссылок имеется горизонтальная полоса прокрутки (контент не обрезается и не выходит за видимую область окна браузера).

**Comment by valerydluski** [comment]
добавь в название issue свой гитхаб

**Comment by valerydluski** [comment]
посмотри как оформляют другие студенты

**Comment by valerydluski** [comment]
нет ментора, желающего проверить
