### ISSUE TITLE
Online Store - "RTinIT"

### ISSUE THREAD

**Issue by RTinIT** [rolling-scopes-school/support#664]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md
2. Screenshot:
![2022-07-18_23-07-24](https://user-images.githubusercontent.com/90758660/179608276-3108bc8e-bf14-4061-830b-e8fc804e1d8a.png)
   
3. Deploy: https://rtinit.github.io/Online-Store/deploy/
4. Done 18.07.2022 / deadline 19.07.2022
5. Link to PR https://github.com/rolling-scopes-school/rtinit-JSFE2022Q1/pull/14
6. Score: 180 / 200
    6.1.Репозиторий +20
    pull request выполнен в соответствии с [требованиями](https://docs.rs.school/#/pull-request-review-process? 
    id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr) +10
    ведётся история коммитов, названия коммитов даются согласно [гайдлайну](https://docs.rs.school/#/git-convention) +10
    6.2.Качество кода +140
    приложение написано на TypeScript.
    используется Everyday Types +10
    используются Generics +10
    использование Object Types +10
    использование Classes +10
    использование Function +10
    нигде не используется тип Any +10
    ESLinter настроен на TypeScript (используется плагин typescript-eslint/recommended) и отсутствуют ошибки +10
    В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
    webpack настроен и работает с TypeScript +10
    код разбит на модули +20
    карточки товаров добавляются динамически средствами JavaScript +10
    у ментора нет замечаний к качеству кода, либо все замечания ментора исправлены +30

**Comment by valerydluski** [comment]
нет менторов, желающих проверить работы
