### ISSUE TITLE
Async Race - "RTinIT"

### ISSUE THREAD

**Issue by RTinIT** [rolling-scopes-school/support#665]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
2. Screenshot:
![2022-08-26_17-19-48](https://user-images.githubusercontent.com/90758660/186925907-19204b3e-d203-4a53-b478-9bb63646680e.png)
![2022-08-26_17-22-37](https://user-images.githubusercontent.com/90758660/186925971-a407962a-379a-45b8-9587-ed9a3cd86dbc.png)

3. Deploy: https://rtinit.github.io/async-race/deploy/
4. Done  08.08.2022 / deadline 09.08.2022
5. Link to PR https://github.com/rolling-scopes-school/rtinit-JSFE2022Q1/pull/15
6. Score: 100 / 150
     1.(+0) Application is divided to logical modules / layers. Like working with api it's separate module, as well as working with UI 
     rendering, or working with an application state, etc. Better discuss architecture with a mentor before implementing.
     2.(+30) All the HTML-content is generated by JavaScript (body contains only one tag script inside).
     3.(+25) Application is SPA.
     4.(+20) Webpack or another bundler should be used. There should be one HTML-file, JS-file, and one CSS-file (or it can be 
      embedded right in the HTML-file).
     5.(+15) Eslint with [Airbnb style guide](https://github.com/airbnb/javascript) should be used. Some paricular eslint-rules can be 
     disabled or changed only after agrement with a mentor. There shouldn't be any eslint errors or warnings.
     6.(+0) Code divided to small functions with a clear names and purposes. Each function should be less or equal to 40 lines.
     7.(+5) There are not unnecessary code duplications.
     8.(+5) Code shouldn't contain magical numbers or strings.

Надеюсь получить хоть какие -то баллы, так как во время выполнения задания я почему -то решил сделать в процедурном стиле, и по итогу не успел реализовать весь функционал(работа, что в PR), но я очень хотел разобраться и написать в ооп стиле(если мою попытку так можно назвать). Я переделал, и прошу проверить эту работу https://github.com/RTinIT/async-race/tree/gh-pages, если это возможно, если нет -  то поделом мне. Могу лишь сказать, что я не ленился, и уделял по 8-10 часов в день, но есть у меня "способность" все переусложнять и долго тупить. Спасибо за понимание, и помощь!

**Comment by valerydluski** [comment]
нет менторов, желающих проверить работы
