### ISSUE TITLE
Migration newip to ts (matou-de-lune)

### ISSUE THREAD

**Issue by matou-de-lune** [rolling-scopes-school/support#666]
PR: https://github.com/rolling-scopes-school/matou-de-lune-JSFE2022Q1/pull/24

1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
2. Screenshot:
![Migration](https://user-images.githubusercontent.com/101355545/186982940-6e6a4e9d-b8c3-447a-a462-548abd481576.png)

3. Deploy: https://rolling-scopes-school.github.io/matou-de-lune-JSFE2022Q1/migration-newip-to-ts/
4. Done 04.07.2022 / deadline 05.07.2022
5. Score: 170 / 170
Репозиторий +20
pull request выполнен в соответствии с требованиями +10
ведётся история коммитов, названия коммитов даются согласно гайдлайну +10

Качество кода +100

приложение полностью смигрированно на TypeScript +50:

используется Everyday Types + 10
используются Generics +10
использование Object Types +10
использование Classes +10
использование Function +10
ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки +10
нигде не используется тип Any +10
В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
webpack настроен и работает с TypeScript +10

Оформление и функционал приложения +50
выполнена адаптивная верстка +10
добавлен свой собственный дизайн или улучшения (в ПР должно быть описано что именно) +20
Добавлена возможность выбора языка источника.
у ментора нет замечаний к оформлению +20

**Comment by valerydluski** [comment]
добавь в название issue свой гитхаб

**Comment by matou-de-lune** [comment]
Сделано

**Comment by valerydluski** [comment]
нет менторов, желающих проверять
