### ISSUE TITLE
Online store (matou-de-lune)

### ISSUE THREAD

**Issue by matou-de-lune** [rolling-scopes-school/support#667]
PR: https://github.com/rolling-scopes-school/matou-de-lune-JSFE2022Q1/pull/25

1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md

2. Screenshot:
![Снимок экрана](https://user-images.githubusercontent.com/101355545/186983633-ec91ea00-a9ce-4cfa-814c-dbdaa3f3489c.png)

3. Deploy: https://rolling-scopes-school.github.io/matou-de-lune-JSFE2022Q1/online-store/

4. Done 19.07.2022 / deadline 19.07.2022

5. Score: 180/ 200
Репозиторий +20
pull request выполнен в соответствии с [требованиями](https://docs.rs.school/#/pull-request-review-process?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr) +10
ведётся история коммитов, названия коммитов даются согласно [гайдлайну](https://docs.rs.school/#/git-convention) +10
Качество кода +160
приложение написано на TypeScript.
используется Everyday Types +10
используются Generics +10
использование Object Types +10
использование Classes +10
использование Function +10
нигде не используется тип Any +10
ESLinter настроен на TypeScript (используется плагин typescript-eslint/recommended) и отсутствуют ошибки +10
В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
webpack настроен и работает с TypeScript +10
код разбит на модули +20
карточки товаров добавляются динамически средствами JavaScript +10
у ментора нет замечаний к качеству кода, либо все замечания ментора исправлены +30
Тесты в приложении +0 (не реализовано)

**Comment by valerydluski** [comment]
добавь в название issue свой гитхаб

**Comment by valerydluski** [comment]
нет менторов, желающих проверять
