### ISSUE TITLE
Async race (matou-de-lune)

### ISSUE THREAD

**Issue by matou-de-lune** [rolling-scopes-school/support#668]
PR: https://github.com/rolling-scopes-school/matou-de-lune-JSFE2022Q1/pull/26

1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md

2. Screenshot:
![asyncrace](https://user-images.githubusercontent.com/101355545/186984066-0b6b79c5-c7f1-4346-85a1-3b6ebc3ca6af.png)

3. Deployment: https://rolling-scopes-school.github.io/matou-de-lune-JSFE2022Q1/async-race/

4. Done 08.08.2022 / deadline 09.08.2022

5. Score: 150 / 150

(+40) Application is divided to logical modules / layers. Like working with api it's separate module, as well as working with UI rendering, or working with an application state, etc. Better discuss architecture with a mentor before implementing.
(+30) All the HTML-content is generated by JavaScript (body contains only one tag script inside).
(+25) Application is SPA.
(+20) Webpack or another bundler should be used. There should be one HTML-file, JS-file, and one CSS-file (or it can be embedded right in the HTML-file).
(+15) Eslint with [Airbnb style guide](https://github.com/airbnb/javascript) should be used. Some paricular eslint-rules can be disabled or changed only after agrement with a mentor. There shouldn't be any eslint errors or warnings.
(+10) Code divided to small functions with a clear names and purposes. Each function should be less or equal to 40 lines.
(+5) There are not unnecessary code duplications.
(+5) Code shouldn't contain magical numbers or strings.

**Comment by valerydluski** [comment]
добавь в название issue свой гитхаб

**Comment by matou-de-lune** [comment]
Сделано

**Comment by valerydluski** [comment]
нет менторов, желающих проверять
