### ISSUE TITLE
Migration newip to ts "Andreyjkov"

### ISSUE THREAD

**Issue by Andreyjkov** [rolling-scopes-school/support#669]
1. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
2. ![image](https://user-images.githubusercontent.com/99070025/177193393-83037527-9229-4e41-b10a-90125a54921e.png)
3. https://rolling-scopes-school.github.io/andreyjkov-JSFE2022Q1/migration-newip-to-ts/
4. Done 04.07.22 (deadline 05.07.22)
5. Score  120/170
  - Репозиторий +20
    - [x] pull request выполнен в соответствии с требованиями +10
    - [x] ведётся история коммитов, названия коммитов даются согласно гайдлайну +10 
  - Качество кода +100
     - [x] приложение полностью смигрированно на TypeScript +50
     - [x] используется Everyday Types + 10
     - [x] используются Generics +10
     - [x] использование Object Types +10
     - [x] использование Classes +10
     - [x] использование Function +10
    - [x] ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки +10
    - [x] Нигде не используется тип Any +10
    - [x] В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
    - [x] webpack настроен и работает с TypeScript +10
  - Оформление и функционал приложения +0
    - [ ] выполнена адаптивная верстка +10
    - [ ] добавлен свой собственный дизайн или улучшения (в ПР должно быть описано что именно) +20
    - [ ] у ментора нет замечаний к оформлению +20
6. https://github.com/rolling-scopes-school/andreyjkov-JSFE2022Q1/pull/17

**Comment by valerydluski** [comment]
**добавь в название issue свой гитхаб**

**Comment by Andreyjkov** [comment]
Добавил.

**Comment by SOjuD** [comment]
some issues with TS code and project structure, my mark: 110

**Comment by valerydluski** [comment]
оценка в score
