### ISSUE TITLE
Cross-Check 'virtual-keyboard' - 'iskonplus'

### ISSUE THREAD

**Issue by iskonplus** [rolling-scopes-school/support#67]
Ссылка на деплой проекта - https://iskonplus.github.io/virtual-keyboard/ 
Ссылка на репозиторий с проектом на GitHub - https://github.com/iskonplus/virtual-keyboard
Оценка в результате самопроверки, с ее аргументацией : моя оценка - 70 баллов

Выполненные пункты:

1. Реализована генерация DOM-элементов и body в index.html пустой изначально (может находится только тег script) +20

2. Нажатие на кнопку на физической клавиатуре подсвечивает кнопку на виртуальной (проверять следует нажатие цифр, букв, знаков препинания, backspace, del(если она присутствует), enter, shift, alt, ctrl, tab, caps lock, space, стрелки вниз-вверх-влево-вправо) +10

3. Есть переключение между русским и английским языком (сочетание клавиш для переключения языка должно быть указано на странице с клавиатурой), а так же сохранение выбранного языка +15

4. Клики мышкой по кнопкам на виртуальной клавиатуре или нажатие на кнопки физической клавиатуры, выводят символы в инпут (textarea) +10

5. Реализована анимация нажатия на кнопку +15

Student 1 выставил мне - 52.5 балла . На момент проверки были сделаны пункты 1,2,3,4,5. 
Student 1 не  учитывает пункты 4,5

4 п. (у меня не корректно срабатываю клики по ВК, но корректно работает  нажатие на кнопки физической клавиатуры ) Студент отказался засчитывать этот пункт не смотря на то, что в ТЗ указано или.

5 п. (при нажатии у меня меняется  цвет кнопки, цвет шрифта и уберется тень, что дает эффект нажатия + при смене раскладки меняется положение символов). Студент отказался засчитывать этот пункт.
![Student 1](https://user-images.githubusercontent.com/58971909/79134029-b526e880-7db5-11ea-88bf-d0bb7997fc4f.png)

**Comment by Student-Java** [comment]
Согласно правил

Производится только если разница между ожидаемым вами баллом и полученным по результатам шага#4 средним арифметическим баллом - 15 или более.
Даже если экстраполировать разницу в баллах, то
75 * 15/100 = 11.25

**Comment by iskonplus** [comment]
Я может чего то не понимаю но между 70  и 52,5  разница 17,5 балов, что превышает  15 балов по условию.

**Comment by Student-Java** [comment]
![image](https://user-images.githubusercontent.com/57161516/79172279-a4cd3880-7dca-11ea-938c-a603edd74941.png)
![image](https://user-images.githubusercontent.com/57161516/79172356-de05a880-7dca-11ea-9656-fd205edb8323.png)

**Comment by iskonplus** [comment]
Спасибо за оперативность и исчерпывующее разъяснение.

**Comment by Student-Java** [comment]
не за что
