### ISSUE TITLE
Online store "Andreyjkov"

### ISSUE THREAD

**Issue by Andreyjkov** [rolling-scopes-school/support#670]
1. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md#verstka
2. ![image](https://user-images.githubusercontent.com/99070025/179424100-7539ce75-b654-4edc-8ac3-cefcaf78007b.png)
3.  https://rolling-scopes-school.github.io/andreyjkov-JSFE2022Q1/online-store/
4. Done 18.07.22 (deadline 19.07.22)
5. Score 150 / 220
 - pull request выполнен в соответствии с требованиями
 - ведётся история коммитов, названия коммитов даются согласно гайдлайну
 -  Главная страница содержит все товары и т.д +10
 - Карточка товара содержит его изображение, название  и т.д +10
 - Добавление товаров в корзину +20
 - Сортировка +0
 - Фильтры в указанном диапазоне от и до +30
   - фильтры по количеству +10
   - фильтры по году выпуска на рынок +10
   - для фильтрации в указанном диапазоне используется range slider с двумя ползунками и т.д +10
 - Фильтры по значению +20 из 30
   - фильтры по производителю +5
   - фильтры по цвету +5
   - фильтры по размеру  +5
   - можно отобразить только популярные товары +5
   - можно отфильтровать товары по нескольким фильтрам одного типа + 0
 - Можно отфильтровать товары по нескольким фильтрам разного типа + 0
 - Сброс фильтров - выполнено частично  + (5-10) из 20 
 - Сохранение настроек в local storage  + 0
 - Поиск + 0
6. https://github.com/rolling-scopes-school/andreyjkov-JSFE2022Q1/pull/18

**Comment by valerydluski** [comment]
добавь в название issue свой гитхаб

**Comment by SOjuD** [comment]
innerHTML it's not safety method, the main goal of this task not achieved, a lot of strange code like: `value.favorite == true? value : ''`
**My mark: 125**
