### ISSUE TITLE
Async race  "Andreyjkov"

### ISSUE THREAD

**Issue by Andreyjkov** [rolling-scopes-school/support#671]
1. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
2. 
![image](https://user-images.githubusercontent.com/99070025/183262127-33fe08c3-d5f7-4a7f-a1dd-14c0e0ef7b35.png)

3. Диплой  https://rolling-scopes-school.github.io/andreyjkov-JSFE2022Q1/async-race/
4. Done 08.08.22 (deadline 09.08.22)
5. Score: 145/190
- ✔️Репозиторий
  - [+] pull request выполнен в соответствии с требованиями
  - [+] ведётся история коммитов, названия коммитов даются согласно гайдлайну 
- ✔️Базовая структура:
    - ( +5 ) На сайте должно быть два вида: "Гараж" и "Победители".
    - ( +5 ) Представление "Гараж" должно содержать его название, номер страницы и полное количество объектов в базе данных.
    - ( +5 ) Представление «Победители» должно содержать его название, номер страницы и полное количество элементов в базе данных.
    - ( +10 ) Состояние просмотра должно сохраняться, когда пользователь переключается с одного представления на другое.
- ✔️Вид "Гараж":
    - ( +15 ) Пользователь должен иметь возможность создавать, обновлять, удалять автомобили и просматривать список автомобилей и.д
    - ( +10 ) Пользователь должен иметь возможность выбрать любой цвет из палитры RGB и.д
    - ( +5 ) Рядом с изображением автомобиля должны быть кнопки для обновления его атрибутов или удаления.
    - ( +10 ) На виде "Гараж" должна быть пагинация (7 машин на одной странице).
    - ( +10 ) Должна быть кнопка для создания случайных машин и т.д.
- ✔️Автомобильная анимация:
    - ( +5 ) Рядом с изображением автомобиля должны быть кнопки запуска/остановки двигателя автомобиля.
    - ( +20 ) Пользователь нажимает кнопку запуска двигателя и т.д
    - ( +5 ) Пользователь нажимает кнопку остановки двигателя и т.д
    - ( +5 ) Кнопка запуска двигателя должна быть отключена, если автомобиль уже находится в режиме движения и т.д
    - ( +15 ) Автомобильная анимация должна нормально работать на любом экране и т.д
- ✔️Анимация гонки:
    - ( +10 ) Должна быть кнопка для начала гонки. и т.д
    - ( +10 ) Должна быть кнопка для сброса трасы. и т.д
    - ✖️ ( 0 ) После того, как какая-то машина финиширует, первый пользователь должен увидеть сообщение и т.д
- ✖️ Представление «Победители»:
    - ✖️ ( 0 ) После того, как какая-то машина выиграла, она должна отображаться в таблице "Просмотр победителей".
    - ✖️ ( 0 ) Должна быть нумерация страниц (10 победителей на одной странице).
    - ✖️ ( 0 ) Таблица должна содержать следующие столбцы: «№», «Изображение автомобиля», «Название автомобиля», «Количество побед», «Лучшее время в секундах» и т.д
    - ✖️ ( 0 ) Пользователь должен иметь возможность сортировать автомобили и т.д.
6. https://github.com/rolling-scopes-school/andreyjkov-JSFE2022Q1/pull/19

**Comment by valerydluski** [comment]
добавь в название issue свой гитхаб

**Comment by Andreyjkov** [comment]
Добавил.
