### ISSUE TITLE
Async race  'omkavtanke'

### ISSUE THREAD

**Issue by omkavtanke** [rolling-scopes-school/support#672]
1. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
2. 
![Snapshot_22-08-27_11-57-59](https://user-images.githubusercontent.com/96553561/187008021-a174995a-b099-477b-8134-df2078647ae6.jpg)
3. Deploy( ttps://rolling-scopes-school.github.io/omkavtanke-JSFE2022Q1/async-race/ )
4. Done 09.08.22 deadline 09.08.22
5. Score 80 / 190
#### Базовая структура:
* (+5) На сайте должно быть два вида: "Гараж" и "Победители".
* (+5) Представление "Гараж" должно содержать его название, номер страницы и полное количество объектов в базе (сколько машин у пользователя в гараже).
* (+5) Представление «Победители» должно содержать его название, номер страницы и полное количество элементов в базе данных (сколько записей содержит таблица победителей).
* (+10) Состояние просмотра должно сохраняться, когда пользователь переключается с одного представления на другое. Например, номер страницы не должен сбрасываться, элементы управления вводом должны содержать то, что они содержали до переключения и т. д.
#### Вид "Гараж":
* (+10 (-5 баллов - не удаляется автомобиль)) Пользователь должен иметь возможность создавать, обновлять, удалять автомобили и видеть список автомобилей. У автомобиля всего два атрибута: «имя» и «цвет». Для операции "удалить" автомобиль должен быть удален как из таблицы "гараж", так и из таблицы "победителей".
* (+10) Пользователь должен иметь возможность выбрать любой цвет из палитры RGB, как здесь, и увидеть изображение автомобиля, окрашенного выбранным цветом и названием автомобиля.
* (+5 (было бы неплохо добавить при обновлении в инпуте наименование автомобиля который изменяется, на баллы, естественно, не повлияло)) Рядом с изображением автомобиля должны быть кнопки для обновления его атрибутов или удаления.
* (+10) На виде "Гараж" должна быть пагинация (7 машин на одной странице).
* (+10) Должна быть кнопка создания случайных машин (100 машин за клик). Название должно быть собрано из двух случайных частей, например "Tesla" + "Model S" или "Ford" + "Mustang" (не менее 10 разных названий для каждой части). Цвет также должен генерироваться случайным образом.
#### Автомобильная анимация:
* (+5) Рядом с изображением автомобиля должны быть кнопки запуска/остановки двигателя автомобиля.
* (+0 (при нажатии на кнопку старт ничего не происходит)) Пользователь нажимает кнопку запуска двигателя -> пользовательский интерфейс ожидает ответа о скорости автомобиля -> анимирует автомобиль и делает еще один запрос на вождение. В случае, если API вернуло ошибку 500, анимацию автомобиля следует остановить.
* (+0 (невозможно проверить, т.к. не работает старт)) Пользователь нажимает на кнопку остановки двигателя -> интерфейс ожидает ответа на остановку двигателя -> машина возвращается на исходное место.
* (+0 (невозможно проверить, т.к. не работает старт)) Кнопка запуска двигателя должна быть отключена, если автомобиль уже находится в режиме движения. Так же как и кнопка остановки двигателя должна быть отключена, когда автомобиль стоит на исходном месте.
* (+0 (невозможно проверить, т.к. не работает старт)) Автомобильная анимация должна нормально работать на любом экране (наименьший размер экрана — 500 пикселей).
#### Анимация гонки:
* (+0 (невозможно проверить, т.к. не работает старт)) Должна быть кнопка для запуска гонки. После того, как пользователь нажмет эту кнопку, все автомобили на текущей странице начнут движение.
* (+0 (невозможно проверить, т.к. не работает старт)) Должна быть кнопка сброса гонки. После того, как пользователь нажмет эту кнопку, все машины вернутся на исходные места.
* (+0 (невозможно проверить, т.к. не работает старт)) После того, как какая-то машина финиширует, первый пользователь должен увидеть сообщение, содержащее название машины, которое показывает, какая из них выиграла.
#### Представление «Победители»:
* (+0 (невозможно проверить, т.к. не работает старт)) После победы какой-либо машины она должна отображаться в таблице "Просмотр победителей".
* (+0 (нумерация отсутствует)) Должна быть нумерация страниц (10 победителей на одной странице).
* (+5 (Таблица присутствует, но невозможно проверить увеличение количества побед)) Таблица должна содержать следующие столбцы: «№», «Изображение автомобиля», «Название автомобиля», «Количество побед», «Лучшее время в секундах» (названия столбцов могут отличаться). Если один и тот же автомобиль выигрывает более одного раза, количество побед должно быть увеличено, а лучшее время должно быть сохранено, только если оно лучше сохраненного.
* (+0 (невозможно проверить, т.к. не работает старт)) Пользователь должен иметь возможность сортировать автомобили по количеству побед и лучшему времени (ASC, DESC).

**Comment by valerydluski** [comment]
это issue на менторскую проверку или на cross-check?

**Comment by valerydluski** [comment]
нет ответа. закрываю

**Comment by omkavtanke** [comment]
извините я не успел ответить (
это было на менторскую проверку

вс, 11 сент. 2022 г. в 18:16, Valery ***@***.***>:
