### ISSUE TITLE
News API (zone0119)

### ISSUE THREAD

**Issue by zone0119** [rolling-scopes-school/support#673]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
Screenshot:
https://raw.githubusercontent.com/zone0119/photp/main/migration/migration.png 
Deploy: https://rolling-scopes-school.github.io/zone0119-JSFE2022Q1/migration-newip-to-ts
Done 05.07.2022 / deadline 05.07.2022
Score: 60/ 170
Вёрстка, дизайн, UI (50)
 Burger меню сделал для смартфонов и других меньших экранов
 внешний вид приложения поменял улучшил и переместил меню влево сделал адаптивное +20
 выполнена адаптивная верстка +10

Репозиторий +20
pull request выполнен в соответствии с требованиями +10
ведётся история коммитов, названия коммитов даются согласно гайдлайну +10
Качество кода +90
приложение полностью мигрировано на TypeScript +40:
ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки +10
Нигде не используется тип Any +10
В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
Webpack настроен и работает с TypeScript +10
Оформление и функционал приложения +50
Если возможно прошу сообщить где приложение сломалось
PR: https://github.com/rolling-scopes-school/zone0119-JSFE2022Q1/pull/34

мой Github: https://github.com/zone0119

**Comment by valerydluski** [comment]
добавь в название issue свой гитхаб

**Comment by zone0119** [comment]
https://github.com/rolling-scopes-school/zone0119-JSFE2022Q1/tree/migration-newip-to-ts

**Comment by zone0119** [comment]
https://github.com/zone0119

добавил

**Comment by valerydluski** [comment]
посмотри как другие оформляют

**Comment by zone0119** [comment]
Привет! исправил на News API (zone0119)

**Comment by valerydluski** [comment]
нет менторов, желающих проверять работу
