### ISSUE TITLE
CoreJS 2 Interview

### ISSUE THREAD

**Issue by Elena-code-dev** [rolling-scopes-school/support#674]
Ментор не отвечает более 5 дней

**Comment by valerydluski** [comment]
отпиши сюда
https://github.com/rolling-scopes-school/support/issues/656

**Comment by Elena-code-dev** [comment]
Глупо оправдываться, виновата,  упустила этот момент зарывшись на финальной задаче, все понимаю, самой стремно, но все таки.................. плиз, плиз, плиз.........................
