### ISSUE TITLE
Presentation (recorded) tabarzin

### ISSUE THREAD

**Issue by Tabarzin** [rolling-scopes-school/support#675]
1. Task https://github.com/rolling-scopes-school/tasks/blob/master/tasks/presentation.md
2. Screenshot:
![image](https://user-images.githubusercontent.com/38633095/187646563-d47caa65-a3ee-46e9-b64b-9597ebeb22ca.png)
3. Deploy:
- video https://www.youtube.com/watch?v=xPWVI_Hs8NA
- slides https://tabarzin.github.io/os-presentation/
4. Done: 14.08.22 / deadline 16.08.22
5. Score: 120

+ Prepare your presentation using Reveal. Slides and speech transcript have to be in English
+ Record your speech in English. Two options are possible:
+ Upload the resulting video to your YouTube account. 
+ Add a link to your slides in the video description.
+ Make sure that the recording of the speech, the transcript of a presentation and any additional comments are in English
+ Create a presentation branch in your private school repository. Create a markdown file presentation.md and fill it with:
   a link to your YouTube video;
+ a link to your Reveal presentation's deploy;
+ Open a Pull Request. The title should be presentation. Do not merge it.

**Comment by Tabarzin** [comment]
PR https://github.com/rolling-scopes-school/tabarzin-JSFE2022Q1/compare/main...presentation

**Comment by valerydluski** [comment]
ментор проверяет только запись и максимальный балл может быть только 120

**Comment by Tabarzin** [comment]
> ментор проверяет только запись и максимальный балл может быть только 120

А кого просить, чтобы проставили за live? Jury?
Мне отредактировать issue или новый создать?

**Comment by valerydluski** [comment]
отредактировать. за live оценки будут в ближайшее время выставлены всем кто выступал

**Comment by Tabarzin** [comment]
Исправил

**Comment by valerydluski** [comment]
добавь свой гитхаб в название issue

**Comment by Tabarzin** [comment]
добавил

**Comment by valerydluski** [comment]
нет менторов, желающих проверять работу
