### ISSUE TITLE
Online Store (4Quark)

### ISSUE THREAD

**Issue by 4Quark** [rolling-scopes-school/support#676]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md

Screenshot:
<img width="1070" alt="Снимок экрана 2022-09-01 в 01 01 22" src="https://user-images.githubusercontent.com/100227589/187793118-92803a36-16d5-49f6-9cff-647269c700c1.png">

Deploy: https://rolling-scopes-school.github.io/4quark-JSFE2022Q1/Online-Store/

Done 18.07.2022 / deadline 19.07.2022

**Comment by valerydluski** [comment]
нет ответа на коммент 6 дней закрываю
