### ISSUE TITLE
Async Race (4Quark)

### ISSUE THREAD

**Issue by 4Quark** [rolling-scopes-school/support#677]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md

Screenshot:
<img width="834" alt="Снимок экрана 2022-09-01 в 01 08 29" src="https://user-images.githubusercontent.com/100227589/187794005-80656532-6b54-4455-b810-73a3178bb0ef.png">

Deploy: https://4quark.github.io/async-race/
Made in RSS repository https://github.com/rolling-scopes-school/4quark-JSFE2022Q1/tree/async-race 

Done 08.08.2022 / deadline 09.08.2022

**Comment by valerydluski** [comment]
нет менторов, желающих проверять работу
