### ISSUE TITLE
Presentation (recorded) S4mm4ael

### ISSUE THREAD

**Issue by S4mm4ael** [rolling-scopes-school/support#678]
1. Task https://github.com/rolling-scopes-school/tasks/blob/master/tasks/presentation.md
2. Screenshot:
![image](https://user-images.githubusercontent.com/93945710/188067080-d2386658-3b99-46eb-a047-38721b462eb7.png)

3. Deploy:
video https://youtu.be/KcjHbSYXaEo
slides https://github-features-s4mm4el.netlify.app/
4. Done: 15.08.22 / deadline 16.08.22
5. Score: 120
- Prepare your presentation using Reveal. Slides and speech transcript have to be in English
- Record your speech in English. Two options are possible:
- Upload the resulting video to your YouTube account.
- Add a link to your slides in the video description.
- Make sure that the recording of the speech, the transcript of a presentation and any additional comments are in English
- Create a presentation branch in your private school repository. Create a markdown file presentation.md and fill it with:
  - a link to your YouTube video;
  - a link to your Reveal presentation's deploy;
- Open a Pull Request. The title should be presentation. Do not merge it.

**Comment by S4mm4ael** [comment]
Link to PR
https://github.com/rolling-scopes-school/s4mm4ael-JSFE2022Q1/pull/30

**Comment by valerydluski** [comment]
score 120

**Comment by Andrewel** [comment]
score 120
