### ISSUE TITLE
online-store (kasitsyn)

### ISSUE THREAD

**Issue by Kasitsyn** [rolling-scopes-school/support#679]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md
PR-link: https://github.com/rolling-scopes-school/kasitsyn-JSFE2022Q1/pull/48#issue-1361496446
![image](https://user-images.githubusercontent.com/9220206/188262000-9181a13c-a9a7-427e-a509-e679bfa134b3.png)
Deploy: https://rolling-scopes-school.github.io/kasitsyn-JSFE2022Q1/online-store/
Done 18.07.2022 / deadline 19.07.2022
Score: 120/ 200
- Репозиторий +20
  - [x] pull request выполнен в соответствии с [требованиями](https://docs.rs.school/#/pull-request-review-process?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr) +10
  - [x] ведётся история коммитов, названия коммитов даются согласно [гайдлайну](https://docs.rs.school/#/git-convention) +10
- Качество кода +100
  - [x] приложение написано на TypeScript.
  - [x] используется Everyday Types +10
  - [x] используются Generics +10
  - [x] использование Object Types +10
  - [x] использование Classes +10
  - [x] использование Function +10
  - [ ] нигде не используется тип Any  + 0
  - [ ] ESLinter настроен на TypeScript (используется плагин typescript-eslint/recommended) и отсутствуют ошибки +0
  - [ ] В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true  + 0
  - [x] В конфигурационном файле TypeScript стоят флаги "strict": true + 10
  - [x] webpack настроен и работает с TypeScript +10
  - [x] код разбит на модули +20
  - [x] карточки товаров добавляются динамически средствами JavaScript +10
  - [ ] у ментора нет замечаний к качеству кода, либо все замечания ментора исправлены +0
  - [ ] Тесты в приложении +0 (не реализовано)

**Comment by helenakrasnova** [comment]
отсутствует история разработки 
![image](https://user-images.githubusercontent.com/44213581/189133801-23fbbb50-da70-4d48-b835-9b2363272680.png)
