### ISSUE TITLE
Interviewer по  CoreJS 2 Interview не выходит на связь

### ISSUE THREAD

**Issue by First-quantum-mind** [rolling-scopes-school/support#681]
Добрый день, мой интервьюер по CoreJS 2 Interview не выходит на связь. Пробовал все способы, в том числе, звонил на моб. телефон, ответил совершенно другой человек. 

Помогите найти другого интервьюера, если это возможно, 

спасибо,

**Comment by valerydluski** [comment]
связался с ментором который тебе назначен, ты ему ни где не писал.

**Comment by First-quantum-mind** [comment]
Да, он со мной связался, 
спасибо, только почему то он не выходил на связь.
