### ISSUE TITLE
async-race (kasitsyn)

### ISSUE THREAD

**Issue by Kasitsyn** [rolling-scopes-school/support#684]
0. PR-link: https://github.com/rolling-scopes-school/kasitsyn-JSFE2022Q1/pull/50#issue-1363436020
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md#cross-check
2. Screenshot:
   ![image](https://user-images.githubusercontent.com/9220206/183446807-6bb36cdf-0ecc-4b7e-84d3-211e80b87da1.png)
3. Deployment: https://rolling-scopes-school.github.io/kasitsyn-JSFE2022Q1/async-race/
4. Done 08.08.2022 / deadline 09.08.2022
5. Score: 150\150
(-100% for not fulfillment) It's forbidden to use any libraries or frameworks, like JQuery, React, Angular, Lodash, Material Design, etc. But you can use CSS from Bootstrap (CSS only!) if you wish. Note: It may be allowed to use React or Angular, but only if you've already studied at previous RS-course and/or pretty understand how to work with a DOM Api (DOM modification, Event Delegation) and only after agrement with a mentor!
(-100% for not fulfillment) Typescript must be used. Types of input and output parameters of all the methods must be described. Using type "any" is strictly forbidden.
(+40) Application is divided to logical modules / layers. Like working with api it's separate module, as well as working with UI rendering, or working with an application state, etc. Better discuss architecture with a mentor before implementing.
(+30) All the HTML-content is generated by JavaScript (body contains only one tag script inside).
(+25) Application is SPA.
(+20) Webpack or another bundler should be used. There should be one HTML-file, JS-file, and one CSS-file (or it can be embedded right in the HTML-file).
(+15) Eslint with [Airbnb style guide](https://github.com/airbnb/javascript) should be used. Some paricular eslint-rules can be disabled or changed only after agrement with a mentor. There shouldn't be any eslint errors or warnings.
(+10) Code divided to small functions with a clear names and purposes. Each function should be less or equal to 40 lines.
(+5) There are not unnecessary code duplications.
(+5) Code shouldn't contain magical numbers or strings.

**Comment by valerydluski** [comment]
добавь свой гитхаб в название
