### ISSUE TITLE
Async race (YAsereb)

### ISSUE THREAD

**Issue by YAsereb** [rolling-scopes-school/support#685]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md.
2. ScreenShot 
![image](https://user-images.githubusercontent.com/98219090/183506432-6b7d1efa-fc02-4266-97b6-167fa4dbb1b8.png)
3. Deployment: https://async-race-yasereb.netlify.app/
4. Done 08.08.2022 / deadline 09.08.2022.
5. Score 180/190.
1) Basic structure: 25/25
2) "Garage" view 50/50
3) Car animation 50/50
4) Race animation 30/30
5) "Winners" view 25/35 (-10 User should be able to sort cars by wins number and by best time (ASC, DESC)

**Comment by valerydluski** [comment]
добавь свой гитхаб в название

**Comment by valerydluski** [comment]
нет менторов, желающих проверять работу
