### ISSUE TITLE
migration-newip-to-ts (YAsereb)

### ISSUE THREAD

**Issue by YAsereb** [rolling-scopes-school/support#686]
1. Taskl: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
2.  Screenshot: 
![image](https://user-images.githubusercontent.com/98219090/177200917-7cb4dcb4-05d7-4168-9058-0d6f12e0fd21.png)
3. Deploy: https://rolling-scopes-school.github.io/yasereb-JSFE2022Q1/News-API/
4. Done: 04.07.2022,  Deadline: 05.07.2022
5. Score: 170/170
**Репозиторий +20**
pull request выполнен в соответствии с требованиями +10;
ведётся история коммитов, названия коммитов даются согласно [гайдлайну](https://docs.rs.school/#/git-convention) +10;
**Качество кода +100**
приложение полностью смигрированно на TypeScript +50;
используется Everyday Types + 10;
используются Generics +10;
использование Object Types +10;
использование Classes +10;
использование Function +10;
ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки +10;
нигде не используется тип Any +10;
В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20;
webpack настроен и работает с TypeScript +10;
**Оформление и функционал приложения +50**
выполнена адаптивная верстка +10
добавлен свой собственный дизайн или улучшения (+добавил вторую колонку новостей при ширине экрана больше 1080px) +10
у ментора нет замечаний к оформлению +20?

**Comment by valerydluski** [comment]
нет менторов, желающих проверять работу
