### ISSUE TITLE
mentoring Angular

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/support#689]
Это ишью создано для студентов из топ 200 JavaScript/Front-end 2022Q1, которые идут на курс Angular 2022 Q3 без своего ментора.

**Comment by AlexanderKrasovskiy** [comment]
Иду без своего ментора - буду в топ-200

**Comment by ALLaTk** [comment]
Иду без ментора

**Comment by YuliyaShu** [comment]
Ищу ментора Angular 2022 Q3

**Comment by Svt1108** [comment]
Иду без ментора. После проверки ментором оставшихся тасков должна быть в топ-200

**Comment by v-yelina** [comment]
Иду без ментора, буду в топ-200

**Comment by Diana2886** [comment]
Ищу ментора, по окончании курса надеюсь быть в топ-200

**Comment by ThorsAngerVaNeT** [comment]
Иду без ментора

**Comment by AlishNematov** [comment]
Иду без ментора

**Comment by Andronio2** [comment]
Иду без ментора

**Comment by anna-tanisheva** [comment]
Иду без ментора

**Comment by sokolw** [comment]
Иду без ментора

**Comment by Ogimly** [comment]
Иду без ментора, нахожусь в топ 200

**Comment by AibekKen** [comment]
Ищу ментора по Ангуляр. По итогу курса 62. 
TG/GitHub: @AibekKen,
Discord: Aibek#9989

UPD: Ментор есть

**Comment by fromarys** [comment]
Ищу ментора. На дату 08.09.2022 без оценок за Core JS#2 и RSLang нахожусь в ТОП 200 (98 место в рейтинге).

**Comment by IrynaKolh** [comment]
Здравствуйте) ищу ментора по Ангуляр. Надеюсь, что окажусь в топ-200. Обещаю быть максимально самостоятельной, поэтому соглашусь даже на чисто формальное менторство.

**Comment by svetarachok** [comment]
Привет, ищу ментора. Пока в топ 100, по итогам курса думаю, что останусь в топ 200. Очень надеюсь на код ревью (даже если после сдачи задания))).

**Comment by alex-bars25** [comment]
Иду без своего ментора.

**Comment by m9t3zhn1k** [comment]
Здравствуйте. Иду на курс без ментора.

**Comment by Parxommm** [comment]
Привет, ищу ментора. Текущий на фреймворк не идет. ТОП 200
Discord: @Evgeny Parkhomenko#3681
Telegram: https://t.me/parxommm

**Comment by nina-si** [comment]
Иду без ментора, буду в топ-200

**Comment by udushanov** [comment]
Иду на курс Angular 2022Q3 без ментора, буду в топ 200

**Comment by SmSka2021** [comment]
Добрый день. Ищу ментора, по окончанию stage#2  занимаю 144 позицию. Мой ментор релоцируется и не может взять студентов на stage#3,  GitHub:  https://github.com/smska2021    E-mail: Sve-Mac@yandex.ru   Дискорд Sviatlana(github.com/SmSka2021)#9617

**Comment by sthm23** [comment]
Иду без ментора
По итогу курса в топ 50

**Comment by 022022** [comment]
Иду без ментора

**Comment by marat1000** [comment]
Ищу ментора, нахожусь на 166 месте. Много свободного времени, должно хватить на оба курса, поэтому оставил заявку одновременно на Реакт и Ангуляр, но, если нельзя на оба, то Реакт в приоритете

Telegram:  https://t.me/Marat10008
Discord: Marat#2357
Marat (@marat1000)

![2022-09-22 150430](https://user-images.githubusercontent.com/36643317/191744953-7243fdb6-6d77-41ad-baaa-176b5ad3f2b7.png)

**Comment by dokahp** [comment]
Иду без ментора. Позиция в score 173

**Comment by Rakhymbek** [comment]
Иду без ментора. Позиция - 170. Есть опыт на реакте.
Discord: @R.Sagyn#3130,
E-mail: sagrakha@gmail.com
Telegram: https://t.me/R_Sagyn

**Comment by valerydluski** [comment]
@marat1000 
выбирай реакт или ангуляр?

**Comment by marat1000** [comment]
@valerydluski 
реакт

**Comment by valerydluski** [comment]
@022022 react или angular?

**Comment by 022022** [comment]
> @022022 react или angular?

@valerydluski both of them

**Comment by valerydluski** [comment]
@022022 у нас не хватает менторов, у тебя есть ментор на курсе по angular, на курсе по реакту тебе не буду искать ментора
