### ISSUE TITLE
Cross-Check english-for-kids - Toffifi

### ISSUE THREAD

**Issue by Toffifi** [rolling-scopes-school/support#69]
Ссылка на деплой проекта - https://toffifi-english-for-kids.netlify.app/
Ссылка на репозиторий с проектом на GitHub - https://github.com/rolling-scopes-school/toffifi-RS2020Q1/tree/english-for-kids
Оценка в результате самопроверки, с ее аргументацией - 170 баллов. Выполнено всё, один студент из трех проверяющих не нашел страницу статистики.
Балл за cross-check - 155

**Comment by valerydluski** [comment]
Ваша оценка - 170 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) реализован дополнительный, не предусмотренный заданием функционал 

Выполненные пункты:
1) Вёрстка, дизайн, UI главной страницы приложения 

2) Вёрстка, дизайн, UI выезжающего меню 1) ссылки в меню рабочие и ведут на страницы с категориями слов 2) ссылка на текущую страницу внешне отличается от остальных 3) выезжающее меню присутствует на всех страницах приложения 4) плавная анимация, меню закрывается как кликом по крестику, так и кликом на любом элементе приложения (кроме самого меню), и кликом по ссылке в самом меню 

3) Вёрстка, дизайн, UI страницы категории 

4) при клике по карточке звучит произношение слова на английском языке 

5) на каждой карточке есть кнопка, при клике по которой карточка поворачивается, на обратной стороне указан перевод слова. Когда курсор мыши перемещается за границы карточки, она автоматически поворачивается на лицевую сторону 

6) кликом по переключителю Train/Play включается режим игры. В режиме игры указанные выше возможности режима тренировки отключаются, кнопка, при клике по которой карточка переворачивалась, и текст на карточке скрываются. Появляется кнопка Start game. На карточке остаётся только изображение, которое занимает всю её площадь (если это не противоречит вашему дизайну) 

7) после клика по кнопке Start game звучит английское произношение рандомного слова из тех, что находятся на странице. Для каждой страницы и для каждой игры рандомные слова генерируются по-новой 

8) после первого клика по кнопке Start game надпись на ней меняется на иконку Repeat, меняется внешний вид кнопки. При клике по кнопке Repeat произношение слова звучит ещё раз 

9) если пользователь кликнул по активной карточке с неправильным ответом, раздаётся звуковой сигнал error 

10) если пользователь кликнул по активной карточке с правильным ответом, раздаётся звуковой сигнал correct и после него звучит произношение рандомного слова из тех, которые ещё не звучали 

11) карточка с угаданным словом становится неактивной, при этом изменяется её внешний вид. Клики по неактивной карточке звуковыми эффектами не сопровождаются, на счёт игры не влияют 

12) после начала игры каждый клик по активной карточке является правильным или неправильным ответом. Эти ответы отображаются в виде звёздочек (или других символов) разного цвета в шкале с рейтингом, которая появляется в режиме игры. Если звёздочек слишком много и шкала заполнена ими полностью, предыдущие звёздочки скрываются, а новые продолжают добавляться 

13) когда угаданы все слова в категории 1) если все слова угаданы правильно, звучит сигнал success, карточки со словами скрываются, на странице отображается радостный смайлик (или другая картинка) 2) если при угадывании слов были ошибки, звучит сигнал failure, карточки со словами скрываются, на странице отображается грустный смайлик (или другая картинка) и количество допущенных ошибок 3) приложение автоматически перенаправляет на главную страницу со списком категорий 

14) страница со статистикой содержит перечень всех категорий, всех слов в каждой категории, перевод каждого слова. На мобильных разрешенияк в таблице со статистикой может присутствовать полоса прокрутки 

15) возле каждого слова указывается статистика - сколько раз по карточки с данным словом кликали в режиме тренировки, сколько раз данное слово угадывали в режиме игры, сколько ошибок при этом допустили, процент ошибок по каждому слову, или процент правильных ответов по каждому слову. Оба варианта подсчёта являются равноценными и правильными. После перезагрузки приложения статистика сохраняется. 

16) есть возможность сортировки данных по алфавиту, для числовых значений - по их величине. Сортировка может происходить в прямом и обратном порядке и должна охватывать весь диапазон данных 

17) на странице со статистикой размещены кнопки Repeat difficult words и Reset. Кнопка Reset обнуляет статистику. При клике по кнопке Repeat difficult words открывается страница изучения слов с наибольшим процентом ошибок аналогичная странице категории. На странице Repeat difficult words может размещаться от нуля до восьми слов, в зависимости от того сколько слов угадывалось в режиме игры и при их угадывании были допущены ошибки. После нажатия на кнопку Reset количество слов на странице Repeat difficult words равно нулю

**Comment by dzmitry-varabei** [comment]
@valerydluski спасибо!
