### ISSUE TITLE
Cross-Check "RS Lang" - MatsurSviat

### ISSUE THREAD

**Issue by MatsurSviat** [rolling-scopes-school/support#690]
1. ссылка на деплой - https://matsursviat.github.io/rslang/
2. ссылка на репозиторий - https://github.com/MatsurSviat/rslang
3. ссылка на задание - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-2/rs-lang/rslang.md
4. скриншот с оценками - ![Screenshot 2022-09-07 at 22 26 34](https://user-images.githubusercontent.com/51188068/188961213-05e3fb8b-d3ae-4d88-ac71-b813f775bfc0.png)
5.  - Главная страница приложения - 30 баллов;
     - Авторизация - 30 баллов;
     - Электронный учебник - 60 баллов;
     - Список слов - 60 баллов;
     - Мини-игры "Аудиовызов" и "Спринт" - 200 баллов;
     ИТОГО: 380 баллов
6. Баллов нет по причине того, что выбрал для сабмита "RS Clone", а не "RS Lang"

**Comment by ipipka** [comment]
### Итого 252 балла
___
К сожалению, в ПР https://github.com/MatsurSviat/rslang/pull/10 не расписаны критерии оценки по вашей реализации
Поэтому буду руководствоваться ТЗ и своими представлениями о сложности реализации того или иного поведения.

**+30 баллов** (из 40) — Главная страница 
 - [-5 баллов] — отсутствует описание возможностей и преимуществ приложения
 - [-5 баллов] — отсутствует раздел о команде с вкладом каждого из участников


**+12 баллов** (из 50) — Авторизация
 - [-8 баллов] — Форма регистрации есть, но не дает никакой обратной связи пользователю (вижу, что запрос на сервер при регистрации есть). Создан пользователь или не создан абсолютно непонятно, в консоль падают необработанные ошибки. Авторизация не работает (запроса в девтулс так же не вижу)
 - [-10 баллов] — не реализовано требование "при перезагрузке приложения данные о пользователе и полученный при авторизации токен сохраняются в localStorage"
 - [-10 баллов] — не реализовано требование  "у авторизованных пользователей отображается раздел "Сложные слова", прогресс изучения слов, изученные слова и статистика"
 - [-10 баллов] — не реализовано требование  "при логауте данные пользователя и токен удаляются из localStorage, а пользователь становится анонимным"


**+40 баллов** (из 80) — Электронный учебник
 - [-15 баллов] — отсутствует реализация 7 раздела (сложные слова)
 - [-5 баллов] — отсутствуют ссылки на мини-игры "Аудиовызов" и "Спринт" со страницы учебника
 - [-5 балла] — ошибки в навигации по страницам - при переходе с 29 страницы по кнопке Next на 30 странице пустота. При переходе по страницам теряются надписи на кнопках. Навигация по разделам учебника только через главное меню
 - [-5 баллов] — отсутствуют отличия в оформлении разных глав учебника
 - [-10 баллов] — отсутствует реализация требования "при перезагрузке страницы открывается последняя открытая страница приложения"

 
**+30 баллов (из 80)** — Список слов
 - [-10 баллов] — не реализовано требование "кнопка, при клике по которой слово можно отметить как сложное (в разделе "Сложные слова" на её месте отображается кнопка, снимающая отметку что это сложное слово и удаляющая его из данного раздела)"
 - [-10 баллов] — не реализовано требование "кнопка, при клике по которой слово можно отметить как изученное"
 - [-10 баллов] — не реализовано требование "если слово отмечено как сложное, оно остаётся на странице учебника и выделяется стилем, указывающим, что данное слово относится к сложным словам. Также данное слово добавляется в раздел "Сложные слова""
 - [-10 баллов] — не реализовано требование "если слово отмечено как изученное, оно остаётся на странице учебника и выделяется стилем, указывающим, что данное слово относится к изученным словам"
 - [-10 баллов] — не реализовано требование "если все слова на странице относятся к изученным словам или к изученным и сложным словам, такая страница считается полностью изученной и выделяется стилем. Также стилем выделяется соответствующая ей кнопка навигации по страницам учебника. Ссылки на мини-игры на этой странице становятся неактивными."
 

**+70 баллов** (из 100) — Мини-игра "Аудиовызов"
 - [-15 баллов] — не реализовано требование "управлять игрой можно как мышкой, так и клавишами на клавиатуре, как это реализовано в оригинальных играх"
 - [-15 баллов] — не реализовано требование "если мини-игра запускается со страницы учебника, в ней используются слова из той страницы учебника, на которой размещена ссылка на игру. Если размещённых на странице слов для игры недостаточно, задействуются слова с предыдущих страниц. Если предыдущих страниц нет или недостаточно, игра завершается досрочно, когда закончатся все доступные слова"


**+80 баллов** (из 100) — Мини-игра "Спринт"
 - [-5 баллов] — по окончанию игры необработанная ошибка в консоли, нет полного списка слов и возможности прослушать их (как в оригинале)
 - [-15 баллов] — не реализовано требование "если мини-игра запускается со страницы учебника, в ней используются слова из той страницы учебника, на которой размещена ссылка на игру. Если размещённых на странице слов для игры недостаточно, задействуются слова с предыдущих страниц. Если предыдущих страниц нет или недостаточно, игра завершается досрочно, когда закончатся все доступные слова"

**0 баллов** (из 50) — Прогресс изучения
Не реализовано


**0 баллов** (из 60) — Изученные слова
Не реализовано


**0 баллов** (из 60) — Страница статистики
Не реализовано


**0 баллов** (из 80) — Дополнительный функционал
Не реализовано


Прочее:
 - [-10 баллов] - Не выполнены требования к репозиторию проекта
Не понятно почему вы для проекта использовался форк репозитория rolling-scopes-school/react-rslang-be
Приложение из этого репозитория нужно было задеплоить на heroku и в последствии обращаться к нему как к серверной части приложения.
Для вашего же проекта нужно было создать отдельный (новый) репозиторий. И в нем уже разрабатывать фронтенд-приложение.
