### ISSUE TITLE
Cross-Check 'Migration newip to ts'

### ISSUE THREAD

**Issue by StanislavMelnik1991** [rolling-scopes-school/support#691]

**Comment by StanislavMelnik1991** [comment]
Migration newip to ts
https://github.com/rolling-scopes-school/stanislavmelnik1991-JSFE2022Q1/pull/25

**Comment by StanislavMelnik1991** [comment]
1. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
2. ![image](https://user-images.githubusercontent.com/95521674/189186987-c55e0ad9-ebbf-4395-87e7-082450295e25.png)
3. [deploy](https://rolling-scopes-school.github.io/stanislavmelnik1991-JSFE2022Q1/news-JS-main/)
4. 06.07.2022/06.07.2022
5. score: 150/170

**Comment by valerydluski** [comment]
не правильное оформление
