### ISSUE TITLE
Online store

### ISSUE THREAD

**Issue by StanislavMelnik1991** [rolling-scopes-school/support#692]

**Comment by StanislavMelnik1991** [comment]
https://github.com/rolling-scopes-school/stanislavmelnik1991-JSFE2022Q1/pull/26

**Comment by StanislavMelnik1991** [comment]
1.[Task:](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md)
2.![image](https://user-images.githubusercontent.com/95521674/189186717-c1d48038-a4c6-4b6f-9826-64bf46abf009.png)
3.[Deploy:](https://rolling-scopes-school.github.io/stanislavmelnik1991-JSFE2022Q1/Online-Store/)
4.Done: 19.07.2022/19.07.2022
5.Score 200/200

**Comment by manovik** [comment]
I'll check it

**Comment by manovik** [comment]
total 187
-3 for commit history (missed colons, one-word commits)
-10 for commented lines, missed empty lines in the end of files (EOL) and some other notes

I'm not sure if you were approved to use the React, but let it be
nice job

**Comment by StanislavMelnik1991** [comment]
> I'm not sure if you were approved to use the React, but let it be nice job

The mentor could prohibit the use of a reactor
There was no mentor, no one to forbid it.

**Comment by valerydluski** [comment]
не правильное оформление
