### ISSUE TITLE
Cross-Check 'Async race'

### ISSUE THREAD

**Issue by StanislavMelnik1991** [rolling-scopes-school/support#693]

**Comment by StanislavMelnik1991** [comment]
https://github.com/rolling-scopes-school/stanislavmelnik1991-JSFE2022Q1/pull/27

**Comment by StanislavMelnik1991** [comment]
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
![Uploading image.png…]()
[Deploy:](https://rolling-scopes-school.github.io/stanislavmelnik1991-JSFE2022Q1/async-race/)

**Comment by valerydluski** [comment]
не правильное оформление

**Comment by StanislavMelnik1991** [comment]
1. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
2. ![image](https://user-images.githubusercontent.com/95521674/189498588-9ec9f93d-01f6-4a4b-a917-f74645d2def1.png)
3. [Deploy: ](https://rolling-scopes-school.github.io/stanislavmelnik1991-JSFE2022Q1/async-race/)
4. Score: 167/190
5. 2022-08-09/2022-08-09

**Comment by valerydluski** [comment]
всё равно не правильно

**Comment by StanislavMelnik1991** [comment]
> всё равно не правильно

а что не так?
![image](https://user-images.githubusercontent.com/95521674/189502974-c8ca86ba-1b8c-406f-89b6-d86c2b180287.png)
![image](https://user-images.githubusercontent.com/95521674/189502983-5b6cb014-01d0-47ae-9bc6-c1ed319f64e9.png)

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/189516691-530e03a2-ac0d-4871-b213-77eecb7be7af.png)

**Comment by StanislavMelnik1991** [comment]
> ![image](https://user-images.githubusercontent.com/57412523/189516691-530e03a2-ac0d-4871-b213-77eecb7be7af.png)

исправил
а откуда этот скрин?
просто оформлять issue аналогично PR говорили в официальном discord:
![image](https://user-images.githubusercontent.com/95521674/189517118-a4385b98-7710-4702-b118-b72213bc5f32.png)

**Comment by valerydluski** [comment]
ну если ты подаешь апелляцию на кросс-чек то оформлять по требованиям из документации, но в любом случае название issue должно соответсвовать требованиям к оформлению issue

**Comment by valerydluski** [comment]
нет менторов, желающих проверять работы
