### ISSUE TITLE
Presentation (recorded)

### ISSUE THREAD

**Issue by Tanik-sam** [rolling-scopes-school/support#694]
1. Task: 
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/presentation.md
2. Screenshot:
![presentation](https://user-images.githubusercontent.com/60299432/184639135-3ba0c07c-8a2b-453d-a70f-cf29ea6375e2.jpg)

3. Deploy: 
* video * https://rolling-scopes-school.github.io/tanik-sam-JSFE2022Q1/presentation
* slides * https://github.com/Tanik-sam/reveal.js
4. Done: 15.08.2022 / deadline 16.08.2022
5. Score: 120/120

- Prepare your presentation using Reveal. Slides and speech transcript have to be in English
- Record your speech in English. Two options are possible:
- Upload the resulting video to your YouTube account.
- Add a link to your slides in the video description.
- Make sure that the recording of the speech, the transcript of a presentation and any additional comments are in English
- Create a presentation branch in your private school repository. Create a markdown file presentation.md and fill it with:
-- a link to your YouTube video;
-- a link to your Reveal presentation's deploy;
- Open a Pull Request. The title should be presentation. Do not merge it.

**Comment by valerydluski** [comment]
не правильное оформление

**Comment by Tanik-sam** [comment]
> не правильное оформление

Добрый день. Исправила.

**Comment by valerydluski** [comment]
оценка в score

**Comment by Tanik-sam** [comment]
Добрый вечер, большое спасибо!
