### ISSUE TITLE
Online-shop

### ISSUE THREAD

**Issue by varenik40000** [rolling-scopes-school/support#695]
Task: https://github.com/rolling-scopes-school/tasks/tree/master/tasks/online-store
App screenshot:  ![image](https://i.ibb.co/r7MLVsR/online-store.jpg)
Deploy: https://rolling-scopes-school.github.io/varenik40000-JSFE2022Q1/Online-shop/
Done 18.07.22 (deadline 19.07.22)
Score: 50 / 200

**Comment by valerydluski** [comment]
не правильное оформление
