### ISSUE TITLE
Async-race-api

### ISSUE THREAD

**Issue by varenik40000** [rolling-scopes-school/support#696]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
App screenshot:  ![image](https://i.ibb.co/qBhn0Kv/async.jpg)
Deploy: https://rolling-scopes-school.github.io/varenik40000-JSFE2022Q1/async-race-api/
Done 7.08.22 (deadline 9.08.22)
Score: 50 / 190

**Comment by valerydluski** [comment]
не правильное оформление
