### ISSUE TITLE
Migration-newip-to-ts

### ISSUE THREAD

**Issue by varenik40000** [rolling-scopes-school/support#697]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
App screenshot:  ![image](https://i.ibb.co/t3h6knt/bundle.png)
Deploy: https://rolling-scopes-school.github.io/varenik40000-JSFE2022Q1/news-JS-main/
Done 04.07.22 (deadline 05.07.22)
Score: 100 / 100

**Comment by valerydluski** [comment]
не правильное оформление
