### ISSUE TITLE
presentation (bongoman-by)

### ISSUE THREAD

**Issue by bongoman-by** [rolling-scopes-school/support#699]
1. [Task](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/presentation.md)
2. ![image](https://user-images.githubusercontent.com/60322722/184698512-5cbd2d80-8b18-4391-b17c-ab1601a5c26b.png)
3. [Deploy](https://bongoman-by-presentation.netlify.app/)
4. [Video](https://youtu.be/c0BRQMeAzYA)
5. Done 15.08.2022 / deadline 16.08.2022
6.  Score: 110 / 120  (The video is less than 8 minutes long)
7. [PR](https://github.com/rolling-scopes-school/bongoman-by-JSFE2022Q1/pull/8)

**Comment by valerydluski** [comment]
нет менторов, желающих проверить работы
