### ISSUE TITLE
online-store (bongoman-by)

### ISSUE THREAD

**Issue by bongoman-by** [rolling-scopes-school/support#700]
1. [Task https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/online-store/README.md)
2. Screenshot:
![image](https://user-images.githubusercontent.com/60322722/179599891-92839473-f4ee-4b4d-81f8-817795c1874a.png)
3. [Deploy: https://bongoman-by-online-store.netlify.app/](https://bongoman-by-online-store.netlify.app/)
4. Done 18.07.2022 / deadline 19.07.2022
5. Score: 170 / 200
6.  Comments
    [x] Репозиторий +20
    [x] pull request выполнен в соответствии с требованиями+10
    [x] ведётся история коммитов, названия коммитов даются согласно гайдлайну +10
    [x] Качество кода +10 (добавлена опция ИЗБРАННОЕ помимо КОРЗИНЫ)
    [x] приложение написано на TypeScript. =10
    [x] используется Everyday Types +10
    [x] используются Generics +10
    [x] использование Object Types +10
    [x] использование Classes +10
    [x] использование Function +10
    [x] нигде не используется тип Any +10
    [x] ESLinter настроен на TypeScript (используется плагин typescript-eslint/recommended) и отсутствуют ошибки +10
    [x] В конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
    [x] webpack настроен и работает с TypeScript +10
    [x] код разбит на модули +10
    [x] карточки товаров добавляются динамически средствами JavaScript +10
    [ ] у ментора нет замечаний к качеству кода, либо все замечания ментора исправлены +30
    [ ] Тесты в приложении +20
    [ ] реализованы юнит-тесты, использующие различные методы jest – 2 балла за каждую покрытую функцию/метод, 
         но не более 20 баллов (процент покрытия каждой функции/метода не учитывается)
8. [PR](https://github.com/rolling-scopes-school/bongoman-by-JSFE2022Q1/pull/6)

**Comment by valerydluski** [comment]
не правильное оформление

**Comment by bongoman-by** [comment]
а точнее?

**Comment by bongoman-by** [comment]
> не правильное оформление

посмотрел как у других, добавил ссылку на гитхаб в название. Что еще не так?
