### ISSUE TITLE
Migration-newip-to-ts

### ISSUE THREAD

**Issue by varenik40000** [rolling-scopes-school/support#701]
Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md
App screenshot:  ![image](https://i.ibb.co/t3h6knt/bundle.png)
Deploy: https://rolling-scopes-school.github.io/varenik40000-JSFE2022Q1/news-JS-main/
Done 04.07.22 (deadline 05.07.22)
Score: 110 / 170
Репозиторий +20
  -pull request выполнен в соответствии с требованиями +10
  -ведётся история коммитов, названия коммитов даются согласно +10
Качество кода +100
-приложение полностью смигрированно на TypeScript +50:
  -используется Everyday Types + 10
  -используются Generics +10
  -использование Object Types +10
  -использование Classes +0
  -использование Function + 0
-ESLinter настроен на TypeScript, включено правило no-explicit-any и отсутствуют ошибки +10
-нигде не используется тип Any +10
-в конфигурационном файле TypeScript стоят флаги "noImplicitAny": true и "strict": true + 20
-webpack настроен и работает с TypeScript +10
Оформление и функционал приложения +50
  -выполнена адаптивная верстка +10
  -добавлен свой собственный дизайн или улучшения (в ПР должно быть описано что именно) +10

**Comment by valerydluski** [comment]
не правильное оформление
