### ISSUE TITLE
presentation (zone0119)

### ISSUE THREAD

**Issue by zone0119** [rolling-scopes-school/support#702]
1) Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/presentation.md
2) Screenshot: https://raw.githubusercontent.com/zone0119/photp/Presentation/presentation.png
3) Deploy: https://github.com/rolling-scopes-school/zone0119-JSFE2022Q1/blob/presentation/presentation.md
3.1) link to YouTube video: https://youtu.be/2HRl_CKSog4 
3.2) link to your Reveal presentation's deploy: [https://github.com/rolling-scopes-school/zone0119-JSFE2022Q1/blob/presentation/reveal_presentation.zip](https://bit.ly/3QsO73x)
4) Done 16.08.2022 / deadline 16.08.2022
5) Link to PR: https://github.com/rolling-scopes-school/zone0119-JSFE2022Q1/pull/35
6) Score: 160 / 170

**Comment by valerydluski** [comment]
нет менторов, желающих проверить работы
