### ISSUE TITLE
migration-newip-to-ts (bongoman-by)

### ISSUE THREAD

**Issue by bongoman-by** [rolling-scopes-school/support#707]
1.  [Task](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/migration-newip-to-ts.md)
2. 
![image](https://user-images.githubusercontent.com/60322722/177043265-0ea8bc3d-9799-488e-8921-dde10a5e461f.png)
3. [Deploy on netlify](https://bongoman-by-migration-newip-to-ts.netlify.app/#)
4. Done 03.07.2022 / deadline 05.07.2022
5. Score: 170 / 170
- [x] pull request according to requirements +10 
- [x] commit history is maintained, commit names are given according to the guideline +10 
application is fully migrated to TypeScript: 
- [x] Everyday Types is used + 10 
- [x] Generics is used +10 
- [x] Object Types is used +10 is used 
- [x] Classes +10 use of Function +10 
- [x] ESLinter is set to TypeScript, no-explicit-any rule is enabled and no errors +10 
- [x] type Any is not used anywhere +10 
- [x] TypeScript config file has 'noImplicitAny': true and 'strict': true flags + 20 
- [x] webpack is set up and works with TypeScript +10 
- [x] The design and functionality of the application +50 
- [x] adaptive layout is completed +10 
- [x] the mentor has no comments on the design+20
6. my own improvements are added: 
   - [x] carousel of sources with buttons begin, left, right, end
   - [x] choose of category
   - [x] choose languages
   - [x] filtering sources and articles when switching language or category
**instead [newsapi.org](https://newsapi.org/) was used [newsdata.io/](https://newsdata.io/)** (newsapi.org does not work with deploy version of app)
6. [PR](https://github.com/rolling-scopes-school/bongoman-by-JSFE2022Q1/pull/5)

**Comment by valerydluski** [comment]
нет менторов, желающих проверить работы
