### ISSUE TITLE
Async-race - S4mm4ael

### ISSUE THREAD

**Issue by S4mm4ael** [rolling-scopes-school/support#708]
1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md#non-functional-requirements
2. Screenshot:
![image](https://user-images.githubusercontent.com/93945710/190850090-e36b3516-2dc1-44f7-95b7-c7607389b6fe.png)

3. Deploy: https://async-race-s4mm4el-rss.netlify.app/
4. Done 09.08.2022 / deadline 09.08.2022
5. Score:

Mentor's review 150 / 150

## Non-functional requirements
- (**-100%** for not fulfillment) It's forbidden to use any libraries or frameworks, like JQuery, React, Angular, Lodash, Material Design, etc. But you can use CSS from Bootstrap (**CSS only!**) if you wish. **Note:** It may be allowed to use React or Angular, but only if you've already studied at previous RS-course and/or pretty understand how to work with a DOM Api (DOM modification, Event Delegation) and only after agrement with a mentor!
- (**-100%** for not fulfillment) Typescript must be used. Types of input and output parameters of all the methods must be described. Using type "any" is strictly forbidden.
- (**+40**) Application is divided to logical modules / layers. Like working with api it's separate module, as well as working with UI rendering, or working with an application state, etc. Better discuss architecture with a mentor before implementing.
- (**+30**) All the HTML-content is generated by JavaScript (body contains only one tag script inside).
- (**+25**) Application is SPA.
- (**+20**) Webpack or another bundler should be used. There should be one HTML-file, JS-file, and one CSS-file (or it can be embedded right in the HTML-file).
- (**+15**) Eslint with [Airbnb style guide](https://github.com/airbnb/javascript) should be used. Some paricular eslint-rules can be disabled or changed only after agrement with a mentor. There shouldn't be any eslint errors or warnings.
- (**+10**) Code divided to small functions with a clear names and purposes. Each function should be less or equal to 40 lines.
- (**+5**) There are not unnecessary code duplications.
- (**+5**) Code shouldn't contain magical numbers or strings.

6. Link to PR https://github.com/S4mm4ael/async-race-for-review/pull/1

**Comment by rabsterby** [comment]
Проверяю

**Comment by valerydluski** [comment]
оценка в score

**Comment by rabsterby** [comment]
Студент поправил, сейчас можно 150 поставить
