### ISSUE TITLE
Cross-Check 'Online-zoo. week1' - 'FazaR (@faz-r) FazaR#5886'.

### ISSUE THREAD

**Issue by Faz-R** [rolling-scopes-school/support#710]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/faz-r-JSFE2022Q3/pages/main/index.html
2. A link to the project repository on Github.
    - https://rolling-scopes-school.github.io/faz-r-JSFE2022Q3
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo
4. A Link to the checklist for evaluating the task (if it exists)
    - https://app.rs.school/course/student/cross-check-submit?course=js-fe-2022Q3&taskId=2170
5. ![image](https://user-images.githubusercontent.com/98161217/193112620-09cb8e06-1c5b-495d-9b7a-b56a074239ee.png)

6. По моему мнению работа выполнена на максимальное количество баллов. Снятие баллов двумя студентами за несуществующие пункты считаю необоснованным.

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/193450967-68ef2435-0b49-40ff-9211-f03f087bf21e.png)

**Comment by Faz-R** [comment]
> ![image](https://user-images.githubusercontent.com/57412523/193450967-68ef2435-0b49-40ff-9211-f03f087bf21e.png)

Т.е. если баллы снижаются ни за что - это нормально? Таких пунктов даже нет, чтобы занижать оценку. Но из-за того, что это меньше 10% от оценки - то мне можно это только принять. В таком случае - баллы вообще имеют смысл или они просто для того, чтобы потешить самолюбие? 
Не хочу раздувать конфликт, просто объясните - есть ли смысл так запариваться с подгонкой под макет, если любой может на ровном месте придраться и поставить оценку на 10% ниже без ущерба для себя.

**Comment by valerydluski** [comment]
есть форма для жалоб на плохие оценки, но перепроверять, все работы активисты не смогут, на курсе тысячи студентов. для это и есть такие правила для апелляций

**Comment by Faz-R** [comment]
> есть форма для жалоб на плохие оценки, но перепроверять, все работы активисты не смогут, на курсе тысячи студентов. для это и есть такие правила для апелляций

Спасибо за ответ!
А форма жалоб на оценки может как-то в итоге повлиять на полученный бал? Или это просто "стена плача"?

**Comment by valerydluski** [comment]
если там совсем плохая проверка, то оценку отбросим
