### ISSUE TITLE
Cross-Check 'Online-zoo' - 'lenaparkhats'.

### ISSUE THREAD

**Issue by lenaparkhats** [rolling-scopes-school/support#711]
1. A link to your deployed project
    - [[link](https://github.com/)](https://rolling-scopes-school.github.io/lenaparkhats-JSFE2022Q3/online-zoo/index.html)
2. A link to the project repository on Github.
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/lenaparkhats-JSFE2022Q3/tree/online-zoo)
3. A link to the task
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![scrin](https://user-images.githubusercontent.com/36630626/193176605-31aaa3d5-dc51-413c-99cd-a72e56197717.png)
6. A final score after self-assessment, with comments
                          82 
Снимаю балы за About не подсвечен -2
Снимаю балы за соц сети не интерактивны -2
Зона в радиусе 20px хотя бы от одной желтой точки не интерактивная: -5
Поле <input>  не указан тип number: -2.
не указан тип radio, или оно не выбрано как значение по умолчанию: -2.
Есть поля "Monthly" и "Once", но они не взаимоисключающие: -5.
7. A cross-check score of your Score 
                         69

**Comment by ghost** [comment]
Landing +70, страница создана. Страница смещена начиная с хедера, и чем ниже, тем больше это смещение растет
1. Блок Header есть
1.1 Логотип есть, работает как ссылка.
1.2 Меню навигации есть, интерактивное. (желательно делать через nav)
1.1 About есть, не подсвечен, остался интерактивным (-2)
1.2 Map, Zoos, Donate, Contact Us есть, интерактивные. 
1.3 Donate работает как ссылка.
1.4 Designed работает как ссылка (интерактивность есть, желательно сделать как в стайл-гайде)
1.5 h1 есть. Один на странице. 
2. Блок Watch есть
2.1 Кнопка есть, интерактивная. (интерактивность желательно сделать как в стайл-гайде)
2.2 Фоновая картинка есть.
3.  Блок Backstage есть.
3.1 Есть картинка растения справа.
4. Блок Pets есть. 
4.1 Кнопки вправо, влево есть, интерактивные.
4.2 Карточки животных есть, но анимация не соответствует ТЗ (-2*6 = -12).
4.3 Кнопка есть, интерактивная (за отсутствие ссылки на Map не снижаю, поскольку никакой страницы Map у нас нет).
5. Блок Pick есть. 
5.1 Кнопка есть, интерактивная
5.2 Текст является ссылкой, работает как ссылка на Donate
6. Блок Testimonials есть. 
6.1 Есть кнопка, интерактивная. 
6.2 Есть полоска прогресса, дизайн нарушен (-2)
6.3 Картинка растения есть. 
7. Блок Footer есть. 
7.1 Логотип есть, работает как ссылка, 
7.2 Есть кнопка Donate, интерактивная, работает как ссылка на Donate
7.3 Есть иконки соцсетей, интерактивность минимальная. (интерактивность лучше сделать как на стайл-гайде)
7.4 Поле input есть, тип email.
7.5 Кнопка submit есть, интерактивная (интерактивность лучше сделать как на стайл-гайде)
7.6 Элемент About не подсвечен. (-2)
7.7 Остальные элементы меню присутствуют, интерактивные

##### Снимаю так же за смещение блоков единожды (-5)
#### Итого 70 -  2 - 12 - 2 - 2 = 52

Donate +30, страница создана. Страница тоже смещена, но в меньше мере.

1. Блок Header есть
1.1 Логотип есть, работает как ссылка.
1.2 Меню навигации есть, интерактивное. (желательно делать через nav)
1.1 About есть, работает как ссылка. 
1.2 Map, Zoos, Contact Us есть, интерактивные. 
1.3 Donate есть, но не подсвечен (-2)
1.4 Designed работает как ссылка (интерактивность есть, желательно сделать как в стайл-гайде)
1.5 h1 есть. Один на странице. 
2. Блок Pick есть
2.1 Зона не интерактивная (-5)
2.2 Поле input есть, не указан тип number (-2)
2.3 Поле Monthly есть, тип radio
2.4 Поле Once есть, тип radio, не выбрано по умолчанию (-2)
2.5 Поля взаимоисключающие.
2.6 Есть кнопка feed.
3. Блок Footer есть. 
3.1 Логотип есть, работает как ссылка, 
3.2 Есть кнопка Donate, интерактивная, не работает как ссылка на Donate (-2)
3.3 Есть иконки соцсетей, интерактивность минимальная. (интерактивность лучше сделать как на стайл-гайде)
3.4 Поле input есть, тип email.
3.5 Кнопка submit есть, интерактивная (интерактивность лучше сделать как на стайл-гайде)
3.7 Остальные элементы меню присутствуют, интерактивные, About работает как ссылка 


##### Снимаю так же за смещение блоков единожды (-5)
#### Итого 30 -  2 - 5 - 2 - 2 - 2 = 17

### Итого за работу: 52 + 17 = 69

**Comment by helenakrasnova** [comment]
оценка совпадает с оценкой кросс-чека
