### ISSUE TITLE
Cross-Check 'online-zoo. week-1' - 'AlexTemp2019'.

### ISSUE THREAD

**Issue by AlexTemp2019** [rolling-scopes-school/support#712]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/alextemp2019-JSFE2022Q3/online-zoo/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/alextemp2019-JSFE2022Q3/tree/gh-pages/online-zoo)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link]
5. A screenshot of cross-checking marks   
![image](https://user-images.githubusercontent.com/48851159/193209053-980180a8-7507-4c15-980c-0a0338d9fce0.png)

6. A final score after self-assessment, with comments
    Самооценка задания 88. Не согласен с оценкой Student 3 в части отклонения размеров и дизайна.
    Перед сдачей работы проверял на разрешении 1600 через Pixel Perfect Pro. 
7. A cross-check score of your Score - 74.
 

![image](https://user-images.githubusercontent.com/48851159/193206613-b3ae86c8-dd01-46c1-881d-7a9b396e04a7.png)
![image](https://user-images.githubusercontent.com/48851159/193206792-16c2f732-3f2c-465b-9968-88934fe4a5ae.png)
![image](https://user-images.githubusercontent.com/48851159/193206934-195390fa-0c7f-4d04-9462-bd4725d69637.png)

6. A final score after self-assessment, with comments

7. A cross-check score of your Score

**Comment by ghost** [comment]
### Порядок оценки [подробнее](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md#%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8-cross-check-%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1)

Landing: +70

1. Есть блок Header  
	1.1 Есть логотип, работает как ссылка, ведет на Landing.
	1.2 Есть панель навигации, интерактивная. (Желательно использовать тег nav)   
	1.3 Есть элементы (Map, Zoos, Donate..), интерактивные.  
	1.4 Есть элемент About, подсвечен, перестал быть интерактивным.  
	1.5 Designed есть, работает как ссылка на фигму.  
	1.6 H1 есть, один на странице.  
2. Есть блок Watch  
	2.1 Есть кнопка, интерактивная. (желательно сделать интерактивность согласно стайл-гайду)  
	2.2 Фоновая картинка есть.  
3. Есть блок Backstage  
	3.1 Есть картинка растения справа.  
4. Есть блок Pets  
	4.1 Есть кнопки вправо/влево.  
	4.2 Карточки есть, интерактивные, анимация по ТЗ  
	4.3 Есть кнопка, интерактивная, растения на своих местах.  
5. Есть блок Pick  
	5.1 Кнопка есть, интерактивная.  
	5.2 Текст есть, работает как ссылка, ведет на donate.  
6. Блока Testimonials не было (-10)  
7. Есть блок Footer  
	7.1 Есть логотип, работает как ссылка на Lending.  
	7.2 Есть кнопка Donate, интерактивная, ссылка ведет на Donate  
	7.3 Иконки есть, интерактивные. (желательно сделать интерактивность согласно стайл-гайду)   
	7.4 Есть Input, тип Email  
	7.5 Есть кнопка Submit, интерактивная. (желательно сделать интерактивность согласно стайл-гайду)    
	7.6 Есть элементы меню Map, Zoos, Contact Us. About не подсвечен, не перестал быть интерактивным. (-2)  

В футере у меню присутвуют элементы которых нет ни на макете не в стайл-гайде (точки text-decoration) (-2)  

#### Итого за Landing: 70 - 10 - 2 - 2 = 56  

Donate: +30 (Блок с пандой незначительно смещен вниз)

1. Есть блок Header  
	1.1 Логотип есть, работает как ссылка на Lending.  
	1.2 Есть панель навигации, интерактивная.  
	1.3 Есть элемент About, работает как ссылка на Landing.  
	1.4 Есть элементы (Zoos, Donate..), интерактивные.  
	1.5 Есть Donate, но он не подсвечен. (-2)  
	1.6 Есть H1, один на странице.  
2. Есть блок Pick   
	2.1 Зона слева от точки интерактивная только максимум в 10px, требуется 20px. (-5)  
	2.2 Есть Input, тип Number  
	2.3 Есть Input'ы Monthly, Once. Взаимоисключающие, по умолчанию Once.  
	2.4 Есть кнопка Feed, интерактивная.  
3. Есть блок Footer   
	3.1 Логотип есть, работает как ссылка на Landing.  
	3.2 Кнопка Donate есть, интерактивная, ведет на Donate.  
	3.3 Есть иконки соцсетей, интерактивные.   
	3.4 Есть поле Input, тип Email.  
	3.5 Есть кнопка Submit, интерактивная   
	3.6 Есть элементы меню (Map, Zoos..), интерактивные.   
	3.7 Есть About, работает как ссылка на Landing.  
	
#### Итого за Donate: 30 - 2 - 5 = 23      

### Итого за работу: 56 + 23 = 79

**Comment by Elijah-I** [comment]
Landing: +70

1. Есть блок Header
1.1 Есть логотип, работает как ссылка, ведет на Landing.
1.2 Есть панель навигации, интерактивная. (Желательно использовать тег nav)
1.3 Есть элементы (Map, Zoos, Donate..), интерактивные.
1.4 Есть элемент About, подсвечен, перестал быть интерактивным.
1.5 Designed есть, работает как ссылка на фигму.
1.6 H1 есть, один на странице.

2. Есть блок Watch
2.1 Есть кнопка, интерактивная. (желательно сделать интерактивность согласно стайл-гайду)
2.2 Фоновая картинка есть.
3. Есть блок Backstage
3.1 Есть картинка растения справа.

4. Есть блок Pets
4.1 Есть кнопки вправо/влево.
4.2 Карточки есть, интерактивные, анимация по ТЗ
4.3 Есть кнопка, интерактивная, растения на своих местах.

5. Есть блок Pick
5.1 Кнопка есть, интерактивная.
5.2 Текст есть, работает как ссылка, ведет на donate.

6. Есть блок Testimonials
6.1 Полоска прогресса интерактивная, в левой позиции.
6.2 Кнопка Leave feedback интерактивная.
_карточки немного кривоваты (в том смсле, что градиентная обводка слева и сверху не видна)_

7. Есть блок Footer
7.1 Есть логотип, работает как ссылка на Lending.
7.2 Есть кнопка Donate, интерактивная, ссылка ведет на Donate
7.3 Иконки есть, интерактивные. (желательно сделать интерактивность согласно стайл-гайду)
7.4 Есть Input, тип Email
7.5 Есть кнопка Submit, интерактивная. (_желательно сделать интерактивность согласно стайл-гайду_)
7.6 Есть элементы меню Map, Zoos, Contact Us.
_В футере у меню присутвуют элементы которых нет ни на макете не в стайл-гайде (точки text-decoration) (-2)_

**Итого за Landing: 70 - 2  = 68**

Donate: +30 (Блок с пандой незначительно смещен вниз)

1. Есть блок Header
1.1 Логотип есть, работает как ссылка на Lending.
1.2 Есть панель навигации, интерактивная.
1.3 Есть элемент About, работает как ссылка на Landing.
1.4 Есть элементы (Zoos, Donate..), интерактивные.
1.5 Есть Donate не подсвечен. (-2)
1.6 Есть H1, один на странице.

2. Есть блок Pick
2.1 Зона слева от точки интерактивная только максимум в 7px, требуется 20px. (-5)
2.2 Есть Input, тип Number
2.3 Есть Input'ы Monthly, Once. Взаимоисключающие, по умолчанию Once.
2.4 Есть кнопка Feed, интерактивная.

3. Есть блок Footer
3.1 Логотип есть, работает как ссылка на Landing.
3.2 Кнопка Donate есть, интерактивная, ведет на Donate.
3.3 Есть иконки соцсетей, интерактивные.
3.4 Есть поле Input, тип Email.
3.5 Есть кнопка Submit, интерактивная
3.6 Есть элементы меню (Map, Zoos..), интерактивные.
3.7 Есть About, работает как ссылка на Landing.

**Итого за Donate: 30 - 2 - 5 = 23**

### Итого за работу: 68 + 23 = 91

**Comment by helenakrasnova** [comment]
средний балл 85.
Выставлено
