### ISSUE TITLE
Cross-Check 'online-zoo. week-1' - vera0708 (Ответственность за отсутствие комментария...)

### ISSUE THREAD

**Issue by vera0708** [rolling-scopes-school/support#713]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/vera0708-JSFE2022Q3/online-zoo/pages/main/index.html
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/vera0708-JSFE2022Q3/blob/gh-pages/online-zoo/pages/main/index.html
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo
4. A Link to the checklist for evaluating the task (if it exists)
    - https://app.rs.school/course/student/cross-check-submit?course=js-fe-2022Q3&taskId=2170
5. A screenshot of cross-checking marks
[nsobolev](https://app.rs.school/profile?githubId=nsobolev) 
2022-09-29 19:54
10
### _Добрый день! Посмотрел, задача не выполнена до конца, а что сделано, не совсем соответствует макету, все очень едет в браузере!

Student Discord: unknown
6. A final score after self-assessment, with comments
 I don't want to debate about with the score. I consider that according the rules the reviewer should be  noticed about the incorrect cross check.
7. A cross-check score of your Score 
![BAd review](https://user-images.githubusercontent.com/111682119/193211176-a40543f2-88db-43d5-8f8c-95bf20aa4029.png)

**Comment by vera0708** [comment]
Я считаю, что к данному рецензенту необходимо применить пункт об Ответственности за отсутствие комментария, поясняющего причину снижения баллов во время cross-check проверки согласно правилам. Человек явно потратил не более 1 минуты времени...

**Comment by igorlyatskiy** [comment]
Студент оставил свой гитхаб и написал, почему поставил столько баллов. По вопросам оценки можно связаться с ним в лс. На проверку он потратил достаточно времени

**Comment by vera0708** [comment]
Почитайте, пожалуйста, правила по Cross-Check RSschool, где абсолютно чётко написано, как нужно писать рецензию. И приведены примеры неправильных и наказуемых. Сделанная рецензия на мою работу, на которую я жалуюсь, - точный пример, как НЕЛЬЗЯ делать!  И связывать по вопросам оценки с рецензентом есть смысл, когда можно обсуждать какой-то пункт. Считаю, что вы не квалифицированно подошли к ответу на мой запрос.

**Comment by helenakrasnova** [comment]
Жалоба на проверющего подается через форму https://docs.google.com/forms/d/e/1FAIpQLSc9su27qv3CzpkWQNRP2RsHCgjw0NFsmRT0fQgHA3ccN08vwA/viewform
Апелляцию создавать для этого не нужно
