### ISSUE TITLE
Cross-Check online-zoo week 1 - olmeor

### ISSUE THREAD

**Issue by Olmeor** [rolling-scopes-school/support#714]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/olmeor-JSFE2022Q3/online-zoo/)
    - copy [link](https://olmeor-online-zoo.netlify.app/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/olmeor-JSFE2022Q3/tree/gh-pages)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo)
4. A Link to the checklist for evaluating the task (if it exists)
    - none
5. A screenshot of cross-checking marks
![Без имени-1](https://user-images.githubusercontent.com/106018937/193209840-dc848a33-10fe-43ff-878c-b7a0410a0ad9.jpg)
6. A final score after self-assessment, with comments
  100
  Есть сдвиг на странице доната, но он 12 пикселей, что менее 20 по ТЗ.
  Придирка - наличие transform: scale на ховерах. Это допускается в требованиях ТЗ - "на ваше усмотрение и исходя из макета", сами требования по цветам к действиям и раpмерам кнопок по макету соблюдены.
  Ошибки по отсутствию интерактивности в лого - такого требования нет ни в ТЗ, ни в макете.
  Ошибка, что ссылка на соцсети д.б. оранжевая - в макете она зеленая.

7. A cross-check score of your Score 
  - 99

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/193451145-c4f0bf54-4f6c-4230-a85a-24005d51ced5.png)
