### ISSUE TITLE
Cross-Check 'online-zoo. week-1' - 'ShiraseAkira'. 

### ISSUE THREAD

**Issue by ShiraseAkira** [rolling-scopes-school/support#715]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/shiraseakira-JSFE2022Q3/online-zoo/pages/main/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/shiraseakira-JSFE2022Q3)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1)    
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/20154948/193220958-ffffccaa-7e04-457b-8a73-bd56e5541da4.png)
6. A final score after self-assessment, with comments
Полностью согласен с оценкой Student 3
Страница Landing: 70 -2 - 2 - 2 = 64
Testimonials: полоска прогресса должна быть цветная с градиентом (как рамки вокруг комментов) Нарушен цветовой дизайн полоски -2
Footer: нарушен дизайн поля <input> (рамка красная, как для состояния mistake) - 2 снижаю один раз только в лэндинге
кнопка Submit: Кнопка есть, но не интерактивная -2
страница donate: 30 — 2 = 28
Footer: кнопка Submit: Кнопка есть, но не интерактивная -2
8. A cross-check score of your Score 
62

**Comment by valerydluski** [comment]
средний балл по двум оценкам **94**

**Comment by helenakrasnova** [comment]
выставлено
