### ISSUE TITLE
Cross-Check: online-zoo. week-1. trenkenshu

### ISSUE THREAD

**Issue by trenkenshu** [rolling-scopes-school/support#716]
1. A link to your deployed project
    [link](https://github.com/)](https://rolling-scopes-school.github.io/trenkenshu-JSFE2022Q3/online-zoo)
2. A link to the project repository on Github.
   [link](https://github.com/)](https://github.com/rolling-scopes-school/trenkenshu-JSFE2022Q3/tree/gh-pages)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md#порядок-оценки-cross-check-неделя-1)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/16839388/193241111-446b2bc8-af2b-499e-91ac-30ca35dc81b0.png)
![image](https://user-images.githubusercontent.com/16839388/193241240-9281567a-f056-4be0-bd62-98e4ee9fafc8.png)
6. A final score after self-assessment, with comments
С учетом всех недочетов, которые фактически присутствуют в моей реализации, считаю вполне возможным оценить работу в 85 баллов или выше. Существующие недочеты не носят системный характер и продиктованы ограниченным на реализацию временем, а не неумением. Комментарии:
- Наличие нескрытого h1 обусловлено опытом: во всех проекты, в которых я принимал участие, СЕОшники ругались на любой скрытый текст, а спрятать h1 в логотип не давал ни один логотип (в текущем задании я с этим столкнулся впервые), поэтому я на автомате сделал, как написано - просто проставил тег h1 в тело. Каюсь, не понял, что конкретно требуется в данном случае.
- У обоих моих проверяющих большинство указанных ошибок не соответствуют действительности. Это без придирок с моей стороны.
7. A cross-check score of your Score 
70 баллов

**Благодарю за помощь!**

**Comment by valerydluski** [comment]
не правильно заполнено, нету сылок на деплой и репозиторий

**Comment by Singlelol** [comment]
в работе

**Comment by Singlelol** [comment]
Порядок проверки [https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md#%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8-cross-check-%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-1](url)

Landing: +70

Есть блок Header
1.1 Есть логотип, работает как ссылка, ведет на Landing.
1.2 Есть панель навигации, интерактивная. (Желательно использовать тег nav)
1.3 Есть элементы (Map, Zoos, Donate..), интерактивные.
1.4 Есть элемент About, подсвечен, перестал быть интерактивным.
1.5 Designed есть, работает как ссылка на фигму.
1.6 Нет H1. -5
Есть блок Watch
2.1 Есть кнопка, интерактивная. (желательно сделать интерактивность согласно стайл-гайду)
2.2 Фоновая картинка есть.
2.3. Отступы от границ элементов не соответствуют макету более чем на 10px (нижний отступ блока) -5
Есть блок Backstage
3.1 Есть картинка растения справа.
3.2 Отступы от границ элементов не соответствуют макету более чем на 10px (цветок) -5
Есть блок Pets
4.1 Есть кнопки вправо/влево.
4.2 Карточки есть, интерактивные, анимация по ТЗ
4.3 Есть кнопка, интерактивная, растения на своих местах.
Есть блок Pick
5.1 Кнопка есть, интерактивная.
5.2 Текст есть, работает как ссылка, ведет на donate.
5.3 Отступы между элементами не соответствуют макету более чем на 10px (How it works) -5
Есть блока Testimonials
6.1 Нарушен дизайн полоски: -2.
6.2 Отступы от границ элементов не соответствуют макету более чем на 10px (кнопка) -5
Есть блок Footer
7.1 Есть логотип, работает как ссылка на Lending.
7.2 Есть кнопка Donate, интерактивная, ссылка ведет на Donate
7.3 Иконки есть, интерактивные.
7.4 Есть Input, тип Email
7.5 Есть кнопка Submit, интерактивная.
7.6 Есть элементы меню Map, Zoos, Contact Us.
7.7 Отступы от границ элементов не соответствуют макету более чем на 10px (кнопка) -5

Итого за Landing: 70 - 37 = 33 
Donate: +30

Есть блок Header
1.1 Логотип есть, работает как ссылка на Lending.
1.2 Есть панель навигации, интерактивная.
1.3 Есть элемент About, работает как ссылка на Landing.
1.4 Есть элементы (Zoos, Donate..), интерактивные.
1.5 Есть Donate
1.6 Нет H1. -5
Есть блок Pick
2.1 Зона слева от точки интерактивная
2.2 Есть Input, тип Number
2.3 Есть Input'ы Monthly, Once. Взаимоисключающие, по умолчанию Once.
2.4 Есть кнопка Feed, интерактивная.
2.5 Отступы между элементами не соответствуют макету более чем на 10px (Donation information) -5
Есть блок Footer
3.1 Логотип есть, работает как ссылка на Landing.
3.2 Кнопка Donate есть, интерактивная, ведет на Donate.
3.3 Есть иконки соцсетей, интерактивные.
3.4 Есть поле Input, тип Email.
3.5 Есть кнопка Submit, интерактивная
3.6 Есть элементы меню (Map, Zoos..), интерактивные.
3.7 Есть About, работает как ссылка на Landing.
3.8 Отступы от границ элементов не соответствуют макету более чем на 10px (кнопка) -5
Итого за Donate: 30 - 15 = 15
Итого за работу: 33 + 15 = 48

**Comment by helenakrasnova** [comment]
оценка выставлена

**Comment by trenkenshu** [comment]
> оценка выставлена

Спасибо, что уделили время моей работе, но дело в том, что первый проверяющий сообщил о том, что неправильно заполнено обращение лэйбл `invalid`. Я его специально не обновлял, чтобы рассмотрения не было, так как понял, в чем заключались ошибки, и апелляция стала неактуальной для меня. 

О том, что нужно удалять апелляцию самостоятельно, я не знал. Не нашел упоминаний на этот счет. Поэтому прошу отменить решение и сохранить прежнюю оценку.

Благодарю.

**Comment by helenakrasnova** [comment]
-  вы обновили свое ишью о чём свидетельствует edited вверху
-  теперь уже активист потратил время и силы на то, чтобы проверить вашу работу и оценка была выставлена, в доке подробно описан процесс подачи апелляций - **Оценка может быть, как понижена, так и повышена без дальнейшего обсуждения.**

**Comment by trenkenshu** [comment]
> * вы обновили свое ишью о чём свидетельствует edited вверху
> * теперь уже активист потратил время и силы на то, чтобы проверить вашу работу и оценка была выставлена, в доке подробно описан процесс подачи апелляций - **Оценка может быть, как понижена, так и повышена без дальнейшего обсуждения.**

Доброго дня!

Ссылки вначале были ровно в том же виде, в котором сейчас (сломанный маркдаун). Мне указали на проблему,  попробовал их исправить, они не изменились - маркдаун не подхватился (до сих пор не понимаю, в чем ошибка). Я оставил эту затею и не редактировал больше этот ишью, приняв свой результат и оставив всё в том же состоянии и с лэйбом `invalid`. Я исходил из того, что `invalid` не проверяется. Спустя неделю мой неправильный ишью становится `help needed`. Таким образом, это скорее недоразумение, чем умысел с моей стороны. 

То, что я потратил время активиста, я согласен. А так же согласен его компенсировать, но не снижением оценки, а полезной работой (например, привести ТЗ и чек-листы к одному знаменателю, а то они не в полной мере соответствуют друг другу местами, вызывая недопонимание студентов). 

Более того, мной совершенные ошибки я осознал и исправился. Об этом, к примеру, свидетельствует оценка за вторую неделю - 100. Я готов понести ответственность, но не по принципу "наказание ради наказания" (очень уж сильно напоминает страну, в которой я живу), а выполнением полезной работы.

Что скажете?

**Comment by helenakrasnova** [comment]
Ссылки в ишью работают и ведут на репозиторий и на деплой
Никто не пытается вас наказывать, подавая работу на апелляцию вы соглашаетесь с пунктами документации, правила для всех одинаковы:
![image](https://user-images.githubusercontent.com/44213581/195094223-508194a7-3283-498b-82ec-ed2828e85d52.png)

**Comment by trenkenshu** [comment]
Спасибо за ответ!

Будь по-вашему, без проблем, я благодарю вас за принятое решение и принимаю его. Только вот мой ишью не был валидным.
![image](https://user-images.githubusercontent.com/16839388/195144689-2a84ccfc-34af-42fb-b8e0-7300b866909f.png)

Успехов вам.
