### ISSUE TITLE
task : online-zoo 1 github account :isroil07

### ISSUE THREAD

**Issue by isroil07** [rolling-scopes-school/support#717]
1. A link to your deployed project
  https://rolling-scopes-school.github.io/isroil07-JSFE2022Q3/zoo-task/
2. A link to the project repository on Github.
   https://github.com/rolling-scopes-school/isroil07-JSFE2022Q3/tree/zoo-task
3. A link to the task
 https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![score](https://user-images.githubusercontent.com/86710020/193274700-e9ca179f-1e8c-424c-a4f4-2ea7c030aada.jpg)

6. A final score after self-assessment, with comments
Страница Landing:
Элемент <h1> есть, но в количестве больше одного: -2.
Cтраница donate:
Зона в радиусе 20px хотя бы от одной желтой точки не интерактивная: -5 за весь блок.
Не верно указано имя кнопки FEED A FRIEND NOW
Общий 93
7. A cross-check score of your Score 
 84

**Comment by igorlyatskiy** [comment]
Разница менее 10%
