### ISSUE TITLE
Cross-Check 'online-zoo. week-1' - maslik001

### ISSUE THREAD

**Issue by Maslik001** [rolling-scopes-school/support#718]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/maslik001-JSFE2022Q3/online-zoo/pages/main/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/maslik001-JSFE2022Q3/tree/gh-pages)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](---------)
5. A screenshot of cross-checking marks
![review](https://user-images.githubusercontent.com/93345636/193277173-8cffb628-66ad-406e-9f74-944197f751fe.jpg)
6. A final score after self-assessment, with comments
    67

7. A cross-check score of your Score 
    22

**Comment by Maslik001** [comment]
И у меня проверили работу только 2 человека из 4 возможных. Что не совсем позволяет выставить средний балл

**Comment by helenakrasnova** [comment]
нет скриншота оценки второго проверяющего

**Comment by Maslik001** [comment]
Со вторым все ок, там по делу оценки. 



Отправлено из мобильной Почты Mail.ru


понедельник, 10 октября 2022 г., 15:29 +0200 от ***@***.***  ***@***.***>:

**Comment by helenakrasnova** [comment]
> Со вторым все ок, там по делу оценки.  Отправлено из мобильной Почты Mail.ru понедельник, 10 октября 2022 г., 15:29 +0200 от ***@***.*** ***@***.***>:
> […](#)
> нет скриншота оценки второго проверяющего — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: <rolling-scopes-school/support/issues/718/1273315007 @ github . com>

нужно прикладывать к ишью все оценки какие есть
