### ISSUE TITLE
Cross-Check 'Online-zoo . week-1' - IuliiaPi

### ISSUE THREAD

**Issue by IuliiaPi** [rolling-scopes-school/support#719]
1. A link to your deployed project
    - [link]( https://rolling-scopes-school.github.io/iuliiapi-JSFE2022Q3/online-zoo/pages/main/index.html )
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/iuliiapi-JSFE2022Q3/tree/online-zoo)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md#порядок-оценки-cross-check-неделя-1)
5. A screenshot of cross-checking marks
<img width="982" alt="Screen Shot 2022-10-01 at 11 22 21 AM" src="https://user-images.githubusercontent.com/94296588/193416495-7bb3ff68-a832-4d95-883a-27836f3b831a.png">

6. A final score after self-assessment, with comments
83

 блок Pets: 
* Карточка животного есть, но не интерактивная, или нет анимации текста на затемненном фоне: -2 за каждую. 
(-12)

страница donate:
блок Pick and feed a friend:
- Отсутствует элемент или картинка, как фоновая, так и картинка элемента: -5 единожды за каждый блок. Если картинка или элемент присутствует на странице, имеет правильные размеры и отступы, но нарушен дизайн: -2 единожды за каждый блок.
или
-  Зона в радиусе 20px хотя бы от одной желтой точки не интерактивная: -5 за весь блок.
(-5)

7. A cross-check score of your Score 
75

Апелляция подана не с желанием изменения баллов, а как жалоба на не объективную проверку. - с последующей ответственностью (предупреждение в канале #moderation, обнуление баллов за task). Так как проверяющий студент не подошёл ответственно к проверке и при этом остался анонимом - видимо думая, что анонимность спасает. Выставил баллы сразу же через несколько часов как появилась такая возможность на сайте школы. При этом прописана чёткая инструкция порядка оценки cross-check. И на сайте школы всё указано в деталях. 
Например: 
- что такое интерактивность («Интерактивный» означает, что у кнопки или элемента появляется визуальный эффект или анимация (на ваше усмотрение и исходя из макета: анимация курсора, изменение цвета заднего фона, затемнение, нижнее подчеркивание, изменение шрифта) при каких-либо действиях пользователя, например, при наведении курсора.).
- h1 (На странице обязательно должен присутствовать один элемент < h1 > . В нем должен быть текст PetStory Online.)

Как можно было не найти h1 - я не понимаю.

Если за халатность к проверкам будет применяться наказание, то все студенты начнут ответственно подходить к cross-check.

**Comment by helenakrasnova** [comment]
Жалоба на проверющего подается через форму https://docs.google.com/forms/d/e/1FAIpQLSc9su27qv3CzpkWQNRP2RsHCgjw0NFsmRT0fQgHA3ccN08vwA/viewform
Апелляцию создавать для этого не нужно
