### ISSUE TITLE
Cross-Check english-for-kids - Soullnik

### ISSUE THREAD

**Issue by Soullnik** [rolling-scopes-school/support#72]
Ссылка на деплой проекта - https://soullnik-english-for-kids.netlify.app/
Ссылка на репозиторий с проектом на GitHub - https://github.com/rolling-scopes-school/soullnik-RS2020Q1/tree/English-for-kids
Оценка в результате самопроверки, с ее аргументацией - Оценка в результате самопроверки, с ее аргументацией - 115 . Потому что отсутствует hacher scope полностью и Ui требования выполнены не полностью.
Балл за cross-check из вашего Score - не проверил не один из кроссчекеров

**Comment by Musmen** [comment]
Оценка по позиции "кросс-чек" соответствует **70 баллам** = 170 - 100.

**Вёрстка, дизайн, UI главной страницы приложения**
На главной странице при переключении в режим игры присутствует кнопка начала игры, которая по клику меняется на кнопку повтора **-2 балла**

**Вёрстка, дизайн, UI выезжающего меню**
Упрощенное исполнение кнопки бургер-меню (отсутствует анимация, неуместный outline)  **-1 балл** (https://imgur.com/hWdA6s4)
Не реализовано «ссылка на текущую страницу внешне отличается от остальных» **-1 балл**
После нескольких действий клик на иконке бургер-меню не открывает его с первого раза. Требуется второе нажатие **-1 балл**
Ссылка "Emotion" бургер-меню не ведет на желаемую страницу **-1 балл**
Меню не закрывается кликом на любом элементе приложения **-1 балл**

**Вёрстка, дизайн, UI страницы категории**
страница категории не содержит название категории **-1 балл**

**Режим тренировки**
произношение слова на английском языке звучит при клике только по части карточки с изображением **-2 балла**
при клике точно на знаке “?” кнопки поворота карточки поворот не происходит. Автоматический поворот карточки на лицевую сторону осуществляется и до выхода курсора мыши за пределы карточки **-4 балла**

**Режим игры**
Не проработано положение текста в кнопке старта игры **- 1 балл** (https://imgur.com/fDpBJpF)
В режиме игры по клику на карточке остается проигрывание произношения слова, в т.ч. и во время игры, что серьезно отвлекает **-5 баллов**
При клике по кнопке Repeat звучат произношения разных слов, в т.ч. уже выбранных ранее и ставших якобы "неактивными" **-5 баллов**
После клика по активной карточке с правильным ответом не звучит произношение рандомного слова из тех, которые ещё не звучали. Слова не озвучиваются. Рандомный выбор очередного слова происходит (если кликать на кнопке repeat) из тех, которые уже отыграны **-5 баллов**
Карточка с угаданным словом не становится неактивной. Клики по ней вызывают звуки произношения и правильных/неправильных ответов. Пункт реализован только в части наложения визуального эффекта неактивности  **-5 баллов**
Шкала с рейтингом не реализована **-10 баллов**
Логика игры и ее завершения не реализованы (нет звучания успеха/проигрыша, отображения результата) **-10 баллов**

**Страница статистики**
Не реализовано **-40 баллов**

**Штрафы**
ошибки в работе приложения:
- в режиме игры, если перейти в другую категорию, то игра якобы продолжится там. Но не одно слово нельзя угадать, пока не нажмешь на кнопку repeat **-10 баллов**

**Замечания без оценки:**
 в консоль регулярно выводится ошибка bundle.js:1 Uncaught TypeError: Cannot read property 'firstElementChild' of nullat HTMLDivElement.M (bundle.js:1)
Верстка главной страницы содержит 9 ошибок валидации
Верстка страница категории содержит 8 ошибок и 7 предупреждений валидации

**Comment by dzmitry-varabei** [comment]
@Musmen спасибо!
