### ISSUE TITLE
Online zoo week 1, low mark

### ISSUE THREAD

**Issue by voshodz** [rolling-scopes-school/support#720]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/voshodz-JSFE2022Q3/online-zoo/pages/main/index.html
2. A link to the project repository on Github.
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/voshodz-JSFE2022Q3)
3. A link to the task
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![Screenshot_2](https://user-images.githubusercontent.com/96001342/193421545-1f802bbd-ea8f-46cb-9433-de9103ce44d7.png)

6. A final score after self-assessment, with comments
i guess, my work for 94 - (-2 testimonials was not white color, -2 about in foooter not orange, -2 i dont remember.
I commited, because cross checker(adequare cross ckecker) said me to fix interactive of elements as in figma, of course i could dont do that, because cursor point enough for interactive meaining by cross check rules.
Finally i got 70 and 76 marks, and i think its very low
7. A cross-check score of your Score 
final scrore after cross check - 82

**Comment by valerydluski** [comment]
не правильное оформление

**Comment by valerydluski** [comment]
плюс были коммиты после дедлайна

**Comment by voshodz** [comment]
ну ладно, но  проверяющие занизили оценку, хотел обратить на это внимание

**Comment by voshodz** [comment]
> плюс были коммиты после дедлайна

на аппеляцию не претендую, просто, к вниманию
