### ISSUE TITLE
Cross-Check Node.js & AWS 'Task 4 (Integration with NoSQL Database)' - 'dimonlev'

### ISSUE THREAD

**Issue by mrCrab2024** [rolling-scopes-school/support#721]
I have submitted my PR for task 4 to the field for task 5, so I can't review others PRs and noone can see my, so please review my PR for Task 4 (Integration with NoSQL Database)

1. A link to your deployed project
    - Link to lambda using DB -  [link](https://cm3jpo1x3b.execute-api.eu-west-1.amazonaws.com/dev/productsPG/76ae7532-8f5d-4ee7-8ffe-dfaf077925af)
     - Link to FE PR -  [link](https://github.com/dimonlev/shop-angular-cloudfront/pull/3)
     - Link to FE using DB - [linkt](https://d3pqms05kkm99n.cloudfront.net/)
     - Link to BE PR - [link](https://github.com/dimonlev/shop-angular-be/pull/3)
2. A link to the project repository on Github.
    - [link](https://github.com/dimonlev/shop-angular-be)
3. A link to the task
    - [link](https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/4_integration_with_nosql_database/task.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link][(https://github.com/](https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial/blob/main/4_integration_with_nosql_database/task.md#evaluation-criteria-each-mark-includes-previous-mark-criteria))
5. A screenshot of cross-checking marks
  - not exist
7. A final score after self-assessment, with comments
 
1 - Task 4.1 is implemented
3 - Task 4.2 is implemented lambda links are provided and returns data
4 - Task 4.3 is implemented lambda links are provided and products is stored in DB (call Task 4.2 to see the product)
5 - Your own Frontend application is integrated with Product Service (/products API) and products from Product Service are represented on Frontend. Link to a working Frontend application is provided for cross-check reviewer.
Additional 
+1 (All languages) - Use RDS instance instead fo DynamoDB tables (implemented RDS, but not implemented DynamoDB)
so I think not include this to the final score will be fair

I was hoping to add Dynamo and most of the additional task today, but using appeal I can't do that, so please review as is.

total self-check score 5/10

9. A cross-check score of your Score 
 - not exist

**Comment by ThorsAngerVaNeT** [comment]
**Your score is 4**
- [x] Task 4.1 is implemented **+1**
- [x] Task 4.2 is implemented lambda links are provided and returns data **+2**
- [ ] Task 4.3 is implemented lambda links are provided and products is stored in DB (call Task 4.2 to see the product)
    - Task 4.3 is not implemented, because createProduct lambda was not created
- [x] Your own Frontend application is integrated with Product Service (/products API) and products from Product Service are represented on Frontend. Link to a working Frontend application is provided for cross-check reviewer. **+1**
