### ISSUE TITLE
Cross-Check 'React Component /React2022Q3 ' iammurad'

### ISSUE THREAD

**Issue by iammurad** [rolling-scopes-school/support#722]
1. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/iammurad-REACT2022Q3/tree/react-components)
2. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/react/modules/module01)
3. Project screenshoot
![Screenshot (41)](https://user-images.githubusercontent.com/64166663/193920878-9bdce32d-9fc6-40ef-99e2-dc6b3916aca3.png)
4. A screenshot of cross-checking marks
![Screenshot (44)](https://user-images.githubusercontent.com/64166663/193921175-668a4d39-99d5-4161-9b5f-b4bd64fb8b86.png)

5. A cross-check score of your Score

**Comment by iammurad** [comment]
> 1. A link to the project repository on Github.
>    
>    * [link](https://github.com/rolling-scopes-school/iammurad-REACT2022Q3/tree/react-components)
> 2. A link to the task
>    
>    * [link](https://github.com/rolling-scopes-school/tasks/tree/master/react/modules/module01)
> 3. Project screenshoot
>    ![Screenshot (41)](https://user-images.githubusercontent.com/64166663/193920878-9bdce32d-9fc6-40ef-99e2-dc6b3916aca3.png)
> 4. A screenshot of cross-checking marks
>    ![Screenshot (44)](https://user-images.githubusercontent.com/64166663/193921175-668a4d39-99d5-4161-9b5f-b4bd64fb8b86.png)
> 5. A cross-check score of your Score

@iammurad -github
t.me/justalien -telegram
murad.theynalli@gmail.com -mail

**Comment by helenakrasnova** [comment]
There is no cross-check on current task
