### ISSUE TITLE
Cross-Check 'online-zoo.week-2' 'sanyape'

### ISSUE THREAD

**Issue by SanyaPE** [rolling-scopes-school/support#724]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/sanyape-JSFE2021Q3/online-zoo/pages/main/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/sanyape-JSFE2021Q3/tree/online-zoo-part2)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://online-zoo-week-2-2022q3.netlify.app/)
5. A screenshot of cross-checking marks
![изображение](https://user-images.githubusercontent.com/69213734/194724110-61dfb4a7-9220-4970-95c2-a70d607c5216.png)

6. A final score after self-assessment, with comments
Жалоба на проверяющего.
Ответственность за отсутствие комментария, поясняющего причину снижения баллов во время cross-check проверки.

7. A cross-check score of your Score

**Comment by helenakrasnova** [comment]
Жалоба на проверющего подается через форму https://docs.google.com/forms/d/e/1FAIpQLSc9su27qv3CzpkWQNRP2RsHCgjw0NFsmRT0fQgHA3ccN08vwA/viewform
Апелляцию создавать для этого не нужно
