### ISSUE TITLE
Cross-Check 'Online-zoo. week-2' - Win4esterD

### ISSUE THREAD

**Issue by Win4esterD** [rolling-scopes-school/support#725]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/win4esterd-JSFE2022Q3/online-zoo/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/win4esterd-JSFE2022Q3/tree/gh-pages)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2)
4. A Link to the checklist for evaluating the task (if it exists)

5. A screenshot of cross-checking marks

![Screenshot_1](https://user-images.githubusercontent.com/85812541/194730845-14ba73eb-0cb0-4120-8ff7-8af596fa6092.jpg)

7. A final score after self-assessment, with comments
 45

9. A cross-check score of your Score 
35

От себя:

Прошу обратить внимание что пользователь поставил 0 вообще без объяснения причины. В то же время прошу поднять балл. Да, знаю, много накосячил потому что совершил ошибку при разработке, хотя я всё равнял при помощи Perfect Pixel, я не знал что нужно разрабатывать сайт переведя его в режим "Adaptive",верстал просто закрыв часть экрана инструментами разработчика. Потратил много сил, работал по 10 часов в день целую неделю, обидно столь низкий балл получать.

**Comment by helenakrasnova** [comment]
Жалоба на проверющего подается через форму https://docs.google.com/forms/d/e/1FAIpQLSc9su27qv3CzpkWQNRP2RsHCgjw0NFsmRT0fQgHA3ccN08vwA/viewform
Апелляцию создавать для этого не нужно
