### ISSUE TITLE
Cross-Check 'Online-zoo. week-2' - sleepyComrade

### ISSUE THREAD

**Issue by sleepyComrade** [rolling-scopes-school/support#726]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/sleepycomrade-JSFE2022Q3/online-zoo/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/sleepycomrade-JSFE2022Q3/tree/online-zoo)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://online-zoo-week-2-2022q3.netlify.app/)
5. A screenshot of cross-checking marks
![cross-check](https://user-images.githubusercontent.com/91453198/194735608-d5b975b0-1354-4e71-8dd8-ff0fa3f5af02.png)

6. A final score after self-assessment, with comments
  My final score after self-assessment is 100/100 because all requirements are met.
7. A cross-check score of your Score 
 My cross-check score is 75

**Comment by helenakrasnova** [comment]
A cross-check score of your Score - **Балл за cross-check из вашего Score.**

**Comment by sleepyComrade** [comment]
Исправлен седьмой пункт.

**Comment by YuliDemins** [comment]
Все пункты выполнены согласно Требованиям. Замечаний нет. Адаптивы на всех разрешениях по ТЗ соответствуют макету Пиксель Перфект, на остальных адаптируются по размеру окна

Score: 100

**Comment by helenakrasnova** [comment]
оценка выставлена
