### ISSUE TITLE
Cross-Check 'online-zoo, week 2' - 'darzox'.

### ISSUE THREAD

**Issue by darzox** [rolling-scopes-school/support#727]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/darzox-JSFE2022Q3/online-zoo/pages/main/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/darzox-JSFE2022Q3/tree/online-zoo-part2)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-3)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8-cross-check-%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-3)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/36892362/194737259-a89af217-9f33-4a25-b788-b0f0611d0929.png)

6. A final score after self-assessment, with comments
Я не согласен, что у меня 0 за второй, изз-за этого изменился средний бал( Я оцениваю свою работу на 90
7. A cross-check score of your Score 
58/100

**Comment by helenakrasnova** [comment]
Скриншот с оценками за cross-check **(контакты проверяющих должны быть скрыты).** - не выполнено требование к оформлению
