### ISSUE TITLE
Cross-Check 'online-zoo. week-2' - 'mgovoru'

### ISSUE THREAD

**Issue by mgovoru** [rolling-scopes-school/support#728]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/mgovoru-JSFE2022Q3/online-zoo/pages/main/index.html )
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/mgovoru-JSFE2022Q3/tree/gh-pages)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#неделя-2)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://online-zoo-week-2-2022q3.netlify.app)
5. A screenshot of cross-checking marks
![Opera Снимок_2022-10-09_090221_app rs school](https://user-images.githubusercontent.com/98209094/194737411-fc712354-d6ec-44e6-9c8c-ffd281b83825.png)

6. A final score after self-assessment, with comments
Проверяла свою работу очень пристально, используя pixel perfect  и не нашла расхождений, за которых можно снимать баллы, причем столько. Возможно есть какие-то нюансы, которые я не вижу, но с оценкой в 30 баллов одного из проверяющих я точно не согласна. Сама оцениваю на 100, но понимаю, что могла что-то не заметить. 
7. A cross-check score of your Score 
70

**Comment by helenakrasnova** [comment]
ссылка на форму для проверки проекта неверная

**Comment by mgovoru** [comment]
Добрый день! Формы оценки нет, есть порядок проверки с баллами. Ссылку поправила. Пожалуйста, обратите внимание, что ссылка сейчас идет на третью часть работы, в которой дизайн мной частично менялся. Куратор ответил на вопрос и сказал, что будет рассматривать версию на дату дедлайна второй недели. Спасибо.

**Comment by helenakrasnova** [comment]
форма оценки - https://online-zoo-week-2-2022q3.netlify.app/

**Comment by mgovoru** [comment]
Спасибо.

**Comment by helenakrasnova** [comment]
Cделай, пожалуйста, деплой по последнему коммиту второй недели задания
