### ISSUE TITLE
Cross-Check "online zoo. week-2" - merumerum

### ISSUE THREAD

**Issue by merumerum** [rolling-scopes-school/support#729]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/merumerum-JSFE2022Q3/online-zoo/pages/main/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/merumerum-JSFE2022Q3)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://online-zoo-week-2-2022q3.netlify.app/)
5. A screenshot of cross-checking marks
<img width="545" alt="Снимок экрана 2022-10-10 в 19 39 24" src="https://user-images.githubusercontent.com/112607093/194891840-b94fe469-edb8-4f90-a532-98fa2f29cbfd.png">

6. A final score after self-assessment, with comments

По данному кросс-чеку у меня итоговый балл 50. Проверили меня два человека, второй оценил на 100 баллов. (до оценки человека, который поставил 0.) Такое ощущение, что человек с 0, перепутал работы или не смог как положено проверить. После дедлайна я продолжала заниматься отзывчивостью сайта, ранее делала только адаптивные страницы, потому надо было больше времени. Совмещая учебу с работой, так же помощью с ремонтом... мне не хватает времени в сутках. Моя работа по моему мнению и мнению сокурсников rs сделано на 100. По пиксель перфект идеально. Первый кросс чек все 4 человека оценили на 100. Прошу понимания и справедливой оценки. Спасибо! 

7. A cross-check score of your Score: 50 балл. 

8. Мой дискорд: Meruert (@merumerum), Meruert#3298

9. телеграм: merumerum

**Comment by helenakrasnova** [comment]
A cross-check score of your Score - **Балл за cross-check из вашего Score.**
криншот с оценками за cross-check **(контакты проверяющих должны быть скрыты).**

**Comment by merumerum** [comment]
Здравстуйте, исправила

**Comment by EternalRival** [comment]
## 90/100

[Общие обозначения, указанные в задании.](https://i.imgur.com/ApQNmtH.png)

### Страница [Landing](https://rolling-scopes-school.github.io/merumerum-JSFE2022Q3/online-zoo/pages/main/) +60

#### Проверяем на соответствие общим требованиям дизайна и снимаем баллы (но не более -30), если нарушены следующие пункты:

- В какой-либо момент элементы, кроме **указанных** или фоновых элементов, наезжают на другие элементы, хотя во всех дизайнах между ними есть отступ: **-5** единожды за каждый промежуток.

  > При ширине 321-335 блок `Designed by Alisa Samborskaya ©RSSchool & ©Yem Digital 2021` заходит на кнопку `Donate` ![pic](https://i.imgur.com/ucRlthd.png)

### Страница [Donate](https://rolling-scopes-school.github.io/merumerum-JSFE2022Q3/online-zoo/pages/donate/) +40

#### Donate на 640px:

- Расположение элементов в блоке `Pick and feed a friend`: **-5**.

  > Расположение центральной полосы в блоке с желтыми кругами отличается на ~17px по оси X с обеих сторон ![pic](https://i.imgur.com/foOPpD7.png)

  > Расположение этой кнопки отличается на 10px по оси X и 3px по оси Y (в пределах нормы) ![pic](https://i.imgur.com/ef1y9H4.png)

#### Donate на 320px:

- Расположение элементов в блоке `Pick and feed a friend`
  > Та же проблема, что и на 640.

#### Итог:

> +60-5 +40-5 = 90

@helenakrasnova

**Comment by helenakrasnova** [comment]
выставлено
