### ISSUE TITLE
Cross-Check 'online-zoo, week-2' - 'andrey1486'

### ISSUE THREAD

**Issue by andrey1486** [rolling-scopes-school/support#730]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/andrey1486-JSFE2022Q3/online-zoo/pages/main/ 
    
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/andrey1486-JSFE2022Q3/tree/main/online-zoo
    
3. A link to the task
    -  https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2
    
4. A Link to the checklist for evaluating the task (if it exists)
    - https://online-zoo-week-2-2022q3.netlify.app/
    
5. A screenshot of cross-checking marks
https://user-images.githubusercontent.com/88458447/194899782-3416b35d-c24d-40af-a8b0-2dd68d8e1332.png
 

6. A final score after self-assessment, with comments
 - score: 100.
  all points are completed in full.

7. A cross-check score of your Score 
 -  score: 73
 
p.s: Thanks)

**Comment by helenakrasnova** [comment]
ссылка не открывается

**Comment by andrey1486** [comment]
https://user-images.githubusercontent.com/88458447/194741518-2766d8ea-43bf-43ca-afe3-85bb54998dd4.png

Прошу прощения! в конце букву g не выделил при копирование

**Comment by helenakrasnova** [comment]
Скриншот с оценками за cross-check **(контакты проверяющих должны быть скрыты).** - не выполнено

**Comment by andrey1486** [comment]
![image](https://user-images.githubusercontent.com/88458447/194899782-3416b35d-c24d-40af-a8b0-2dd68d8e1332.png)

**Comment by helenakrasnova** [comment]
> ![image](https://user-images.githubusercontent.com/88458447/194899782-3416b35d-c24d-40af-a8b0-2dd68d8e1332.png)

нужно прилинковать картинку к самому ишью и удалить предыдущую ссылку т к она всё также ведет на картинку с контактами проверяющих (не скрытыми)

**Comment by andrey1486** [comment]
Понял, сделал, извините. Первый раз)

**Comment by evg-zlg** [comment]
Для проверки задания "online-zoo, week-2" нужно сделать деплой задания по последнему коммиту второй недели, без изменений третьей недели. 

Например, так:

1. Отыскать нужный коммит в истории коммитов на гитхабе. 
1.1. Открыть приватный репозиторий. 
1.2. Выбрать ветку gh-pages
1.3. Зайти в папку с проектом online-zoo
1.4. Справа нажать History
![image](https://user-images.githubusercontent.com/85534817/203719847-cab8a6cf-8ed6-4b0f-bff7-827b73ee1fac.png)

2. Скопировать хеш нужного коммита (это должен быть последний коммит до наступления дедлайна по заданию). 
![image](https://user-images.githubusercontent.com/85534817/203722852-8da4aa95-c7ea-4407-b105-6a698ff9d572.png)

3. Открыть git (или запустить терминал в vscode), перейти в папку проекта. 

4. Выполнить команды:
`git checkout gh-pages`
`git branch gh-pages-backup`
`git reset <hash> --hard`  // _тут вместо `<hash>` вставить скопированный в п.2 хеш._ 
**Перед тем как ввести следующую команду убедись, что кросс-чек текущего задания закончен и деплой по другим работам никому не нужен.** 
`git push --force`

5. Проверить, что в gh-pages изменилась история коммитов, последний коммит - это тот, хеш которого ты копировал в п.2. **В ветке gh-pages нет других проектов, которые были заплоены после даты выбранного коммита. Так и должно быть, они потом вернутся.** 
6. Сообщить проверяющему, что можно проверять. 
7. После окончания проверки выполнить следующие команды в git:
`git checkout gh-pages`
`git merge gh-pages-backup`
`git push --force`
8. Через несколько минут история коммитов подтянется в гитхаб и всё вернётся как было.
