### ISSUE TITLE
Cross-Check 'Online-zoo. Week 2' - nastya36f

### ISSUE THREAD

**Issue by nastya36f** [rolling-scopes-school/support#731]
1. A link to my deployed project
    https://rolling-scopes-school.github.io/nastya36f-JSFE2022Q3/online-zoo/pages/main/index.html
2. A link to the project repository on Github.
    https://github.com/rolling-scopes-school/nastya36f-JSFE2022Q3/tree/gh-pages
3. A link to the task
    https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2
4. A Link to the checklist for evaluating the task (if it exists)
    https://online-zoo-week-2-2022q3.netlify.app/
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/106675679/194743155-21a5d845-0956-4dfd-a1e8-a3d8fe0043ed.png)
![image](https://user-images.githubusercontent.com/106675679/194743182-549b443a-e64b-4b96-a09b-b38eca3abed0.png)

6. A final score after self-assessment, with comments: 85

Страница Landing ведет себя адаптивно при изменении размера (меняет дизайн и расположение элементов) + 60

Проверка выполнения указанных для Landing на 1000px требований : выполнено полностью.
Проверка выполнения указанных для Landing на 640px требований: выполнено полностью.
Проверка выполнения указанных для Landing на 320px требований: выполнено полностью.
Проверка выполнения указанных для Landing требований резинового дизайна (Responsive): выполнено полностью.

Страница Donate ведет себя адаптивно при изменении размера (меняет дизайн и расположение элементов) + 40

Проверка выполнения указанных для Donate на 1000px требований:
	- расположение элементов в блоке Pick and feed a friend: -5.
Проверка выполнения указанных для Donate на 640px требований:
	- расположение элементов в блоке Pick and feed a friend: -5.
Проверка выполнения указанных для Donate на 320px требований:
	- расположение элементов в блоке Pick and feed a friend: -5.
Проверка выполнения указанных для Donate требований резинового дизайна (Responsive):
выполнено полностью.

8. A cross-check score of your Score: 62

**Comment by Musmen** [comment]
### Страница Landing

#### Landing на 1000px

Расположение элементов в блоке `The Backstage`: **-5 баллов**

![image](https://user-images.githubusercontent.com/50077360/200313067-0a558949-5928-42c3-8808-b33b7a241c32.png)

- Расположение или отступы между карточками животных в блоке `Pets`: **-5  баллов**. При этом последовательность (очередность) карточек не учитываем.
- Расположение или отступы между кнопками вправо/влево в блоке `Pets`: **-5  баллов**
- Расположение или вид растений справа или слева в блоке `Pets`: **-5  баллов**

![image](https://user-images.githubusercontent.com/50077360/200313450-56a4e491-34f7-450f-a5ac-ce6e6e156d19.png)

- Количество, расположение или отступы между отзывами в блоке `Testimonials`: **-5  баллов**. При этом то, какой именно текст в отзывах - не учитываем.
- Расположение кнопки `leave feedback` в блоке `Testimonials`: **-5  баллов**.
- Расположение или вид растения справа в блоке `Testimonials`: **-5  баллов**.

![image](https://user-images.githubusercontent.com/50077360/200314040-7c96a94d-a29f-4c24-bf1a-7d8bd1eb8dc0.png)

### Итого за `Landing на 1000px` превышен максимальный штраф `-30 баллов`.

#### Landing на 640px

Существенных расхождений нет

#### Landing на 320px

Существенных расхождений нет

Из общих требований дизайна - не на всех размерах экрана корректно проработано расположение кнопок

![image](https://user-images.githubusercontent.com/50077360/200318417-1e1fc39c-d6c2-44bf-9f95-ef073da82b7a.png)

и фоновых элементов

![image](https://user-images.githubusercontent.com/50077360/200318886-3350f790-2573-40aa-b971-b691e185707f.png)

Штраф `-5 баллов`.

## Итого за `Landing`  штраф `-35 баллов`.

### Страница Donate

#### Donate на 1000px

- Отступы между элементами меню в хедере: **-5  баллов**.

![image](https://user-images.githubusercontent.com/50077360/200319595-3d206f87-b596-41fb-81a7-e4010076597c.png)

- Расположение элементов в блоке `Pick and feed a friend`: **-5  баллов**.

![image](https://user-images.githubusercontent.com/50077360/200319932-d736ccaa-38ac-4dd1-aa91-fdc139fac04d.png)

- Расположение элементов внутри формы `Subscribe to our news` в футере: **-5  баллов**.
- Расположение кнопки `donate for volunteers` в футере: **-5  баллов**.
- Отступы между элементами меню в футере: **-5  баллов**.

![image](https://user-images.githubusercontent.com/50077360/200320287-5d26eb46-097b-40fd-82e6-b443be553d4d.png)

### Итого за `Donate на 1000px` превышен максимальный штраф `-20 баллов`.

#### Donate на 640px

Ошибки повторяются по тем же элементам, баллов повторно не снимаем

#### Donate на 320px

Ошибки повторяются по тем же элементам, баллов повторно не снимаем

Из общих вопросов дизайна - шрифт страницы Donate (Times New Roman) не соответствует макету

## Итого за `Donate`  штраф `-20 баллов`.

# Итоговая оценка: 100 - 35 - 20 = 45 баллов

P. S.: 

- Для разметки страницы Landing валидатор обнаружил `16 ошибок` (в т.ч. закрывающие теги для img, отсутствие alt у img, вложенный button в тег <a> и т.д.) и `2 предупреждения`.

- Для разметки страницы Donate валидатор обнаружил `14 ошибок` (в т.ч. закрывающие теги для input, некорректные значения для атрибутов, вложенный button в тег <a> и т.д.) и `1 предупреждение` (пустой `<section class="subheader"></section>`)

Рекомендуется самостоятельно проверять валидность верстки, устранять ошибки и предупреждения.

**Comment by helenakrasnova** [comment]
выставлено

**Comment by nastya36f** [comment]
Здравствуйте! Подскажите, пожалуйста, откуда могут взяться такая разница: у меня нет таких расхождений в Pixel Perfect  как у вас на первых трех скринах, которые относятся к главной странице:
![image](https://user-images.githubusercontent.com/106675679/200419750-d3845e14-8819-434b-906a-f7235facddce.png);
![image](https://user-images.githubusercontent.com/106675679/200419831-6a16a759-1c1a-4803-ae3d-aa3cdaedb378.png);
![image](https://user-images.githubusercontent.com/106675679/200419931-1105d03e-5e47-4890-b5a1-33ac55a07581.png)
 и на первом, относящемся к странице Donate:
![image](https://user-images.githubusercontent.com/106675679/200420540-73204277-84e8-4b8a-8182-e7bf744bed5f.png)

С остальными замечаниями согласна.

**Comment by nastya36f** [comment]
Здравствуйте!

Подскажите, пожалуйста, откуда могут взяться такая разница: у меня нет
таких расхождений в Pixel Perfect как у вас на первых трех скринах, которые
относятся к главной странице:


[image: image]
<https://user-images.githubusercontent.com/106675679/200419750-d3845e14-8819-434b-906a-f7235facddce.png>
;
[image: image]
<https://user-images.githubusercontent.com/106675679/200419831-6a16a759-1c1a-4803-ae3d-aa3cdaedb378.png>
;
[image: image]
<https://user-images.githubusercontent.com/106675679/200419931-1105d03e-5e47-4890-b5a1-33ac55a07581.png>

и на первом, относящемся к странице Donate:


[image: image]
<https://user-images.githubusercontent.com/106675679/200420540-73204277-84e8-4b8a-8182-e7bf744bed5f.png>

С остальными замечаниями согласна.

пн, 7 нояб. 2022 г. в 18:15, helenakrasnova ***@***.***>:

**Comment by Musmen** [comment]
Здравствуйте. Попробуйте обновить Google Chrome. Если вопросы останутся - можно в личку Discord @Musmen
