### ISSUE TITLE
Cross-Check 'online-zoo. Week-2' - 'shish-ko'

### ISSUE THREAD

**Issue by shish-ko** [rolling-scopes-school/support#732]
1. A link to your deployed project
    - [https://rolling-scopes-school.github.io/shish-ko-JSFE2022Q3/online-zoo/pages/main/index.html](https://rolling-scopes-school.github.io/shish-ko-JSFE2022Q3/online-zoo/pages/main/index.html)
2. A link to the project repository on Github.
    - [https://github.com/rolling-scopes-school/shish-ko-JSFE2022Q3/tree/gh-pages/online-zoo](https://github.com/rolling-scopes-school/shish-ko-JSFE2022Q3/tree/gh-pages/online-zoo)
3. A link to the task
    - [https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2)
4. A Link to the checklist for evaluating the task (if it exists)
    - [https://online-zoo-week-2-2022q3.netlify.app/](https://online-zoo-week-2-2022q3.netlify.app/)
5. A screenshot of cross-checking marks
![Снимок экрана от 2022-10-09 12-25-13](https://user-images.githubusercontent.com/107854857/194749086-ac73737e-4910-4d5d-bcdf-cd1c99fcde43.png)
![Снимок экрана от 2022-10-09 12-26-07](https://user-images.githubusercontent.com/107854857/194749089-8c901867-6d8a-4bb7-b785-f132962535c0.png)
![Снимок экрана от 2022-10-09 12-26-56](https://user-images.githubusercontent.com/107854857/194749090-f9bf513e-75bc-43bb-84f1-d75c78fe6fdb.png)

6. A final score after self-assessment, with comments
95 на 320 зpx Расположение или отступы между отзывами в блоке Testimonials: -5. (размер заголовка)
7. A cross-check score of your Score 77

**Comment by helenakrasnova** [comment]
ссылки прилинкованы неправильно, ведут на главную гитхаба

**Comment by shish-ko** [comment]
Сорри, поправил

**Comment by TrickyPie** [comment]
@shish-ko Привет, сделай, пожалуйста, деплой по последнему коммиту второй недели задания, чтобы я могла проверить работу без изменений третьей недели.

**Comment by shish-ko** [comment]
@TrickyPie как это сделать? Попытался откатить назад ветку online-zoo и сделать PR в gh-pages: не даёт это сделать. Или откатить всю ветку gh-pages назад? 
P.S. после второй недели стили не трогал

**Comment by TrickyPie** [comment]
Со студентом все решили и договорились об откате ветки. Постараюсь на следующей неделе или, если не выйдет, через неделю проверить.

**Comment by TrickyPie** [comment]
Оценка: 85 баллов

**Landing 320px**
1. Шрифт заголовка отличается от того, что в макете, из-за этого при выравнивании блока по левому верхнему краю от его начала смещение выходит в 24 пикселя. 
- Расположение кнопки leave feedback в блоке Testimonials: -5.
- Расположение или вид растения справа в блоке Testimonials: -5.
![image](https://user-images.githubusercontent.com/103384834/204135429-07c973f7-0697-4a6e-9bd3-1683202e844f.png)

**Donate 1000px**
1. Тут разница большая, но в требованиях не отнимаются за этот блок баллы.
![image](https://user-images.githubusercontent.com/103384834/204135874-138cb683-b857-4dad-bf4e-a5ea75f2b5cf.png)

2. В футере 15px разница с макетом у элементов About, Map и т.д. 
- Отступы между элементами меню в футере: -5.
![image](https://user-images.githubusercontent.com/103384834/204135986-7f1838c6-fd90-4069-b674-81f30ec0c659.png)

Остальное сделано хорошо!
Удачи в учебе!)

**Comment by helenakrasnova** [comment]
разница баллов с кросс-чеком менее 10 процентов
