### ISSUE TITLE
Cross-Check 'online-zoo. Week-2' - 'LineCoran'

### ISSUE THREAD

**Issue by LineCoran** [rolling-scopes-school/support#733]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/linecoran-JSFE2022Q3/online-zoo/pages/main/
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/linecoran-JSFE2022Q3/tree/gh-pages/online-zoo
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#неделя-2
4. A Link to the checklist for evaluating the task (if it exists)
    - https://online-zoo-week-2-2022q3.netlify.app/
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/104069255/194754606-49361b6a-05f9-4e0d-89cf-ca1b87a30df8.png)

6. A final score after self-assessment, with comments
- Страница Landing ведет себя адаптивно при изменении размера (меняет дизайн и расположение элементов) +60
- Страница Donate ведет себя адаптивно при изменении размера (меняет дизайн и расположение элементов) +40
- Final score: 100
7. A cross-check score of your Score 
- 88

**Comment by TrickyPie** [comment]
@LineCoran Привет, сделай, пожалуйста, деплой по последнему коммиту второй недели задания, чтобы я могла проверить работу без изменений третьей недели.
