### ISSUE TITLE
Cross-Check 'online-zoo. week-2' - 'mvttsun'

### ISSUE THREAD

**Issue by MVTTSUN** [rolling-scopes-school/support#734]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/mvttsun-JSFE2022Q3/online-zoo/pages/main/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/mvttsun-JSFE2022Q3)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://online-zoo-week-2-2022q3.netlify.app/)
5. A screenshot of cross-checking marks
![Screenshot_2022-10-09-16-39-45-551_com.android.chrome.jpg](https://user-images.githubusercontent.com/24241423/194760669-5fcd6ede-d3c6-48f6-8f55-2227db700ad2.jpg)![Screenshot_2022-10-09-16-39-55-649_com.android.chrome.jpg](https://user-images.githubusercontent.com/24241423/194760675-9bf357c8-2c8b-4d41-a7b3-d9f100305310.jpg)![Screenshot_2022-10-09-16-40-05-338_com.android.chrome.jpg](https://user-images.githubusercontent.com/24241423/194760679-1723ddbc-cc6c-49ee-8ea1-56b735004be0.jpg)
6. A final score after self-assessment, with comments
Самооценка 80 баллов. Последний студент, который поставил 10 баллов, с ним не согласен с оценкой. Responsive - полоса прокрутки не появляется. При 320px блоки у меня не едут. В девтулс в режиме телефона все нормально, по нему и делал. Браузерный режим из за скролла конечно смещает блоки. После оценки всеми тремя проверяющими я исправил фиксацию хедера, смещение навигации с 58 до 48 ps на 1000px и смещение кнопок в блоке pets на 640px. И мне последние два выставили оценку повыше, была 75 баллов от двух, от одного 10.
7. A cross-check score of your Score - 67

**Comment by helenakrasnova** [comment]
A Link to the checklist for evaluating the task (if it exists) - ссылка неверная

**Comment by MVTTSUN** [comment]
> A Link to the checklist for evaluating the task (if it exists) - ссылка неверная

Она и должна быть неверная, потому что ее нет)

**Comment by MVTTSUN** [comment]
> A Link to the checklist for evaluating the task (if it exists) - ссылка неверная

Удалил вообще эту ссылку

**Comment by helenakrasnova** [comment]
> > A Link to the checklist for evaluating the task (if it exists) - ссылка неверная
> 
> Удалил вообще эту ссылку

https://online-zoo-week-2-2022q3.netlify.app/ - вот верная ссылка

**Comment by MVTTSUN** [comment]
> > > A Link to the checklist for evaluating the task (if it exists) - ссылка неверная
> > 
> > 
> > Удалил вообще эту ссылку
> 
> https://online-zoo-week-2-2022q3.netlify.app/ - вот верная ссылка

Спасибо, добавил

**Comment by helenakrasnova** [comment]
фикс-коммит во время кросс-чека
