### ISSUE TITLE
 Cross-Check 'online-zoo. week-2' - 'titmouse2797'

### ISSUE THREAD

**Issue by titmouse2797** [rolling-scopes-school/support#735]
1. A link to my deployed project
    - https://rolling-scopes-school.github.io/titmouse2797-JSFE2022Q3/online-zoo/pages/main/ 
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/titmouse2797-JSFE2022Q3/tree/online-zoo
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-2
4. A Link to the checklist for evaluating the task (if it exists) (there is no such form)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/57391992/194775471-13594d00-a59a-4b90-9984-79eebe149123.png)

6. A final score after self-assessment, with comments

 **95 баллов. Все требования выполнены. -5 баллов за полосу доната (page Donate) считаю справедливой , иногда она ломается на 640px, раз на раз не приходится...**

8. A cross-check score of your Score 
 78

**Comment by gentoosiast** [comment]
Взял в работу.

**Comment by gentoosiast** [comment]
# Ваша оценка: 60 баллов

## Страница Landing (60 баллов за адаптивность - 35 штрафных баллов = 25 баллов)

### 1000px

Недочеты, за которые не стал снимать баллы:

- В Backstage изображение крестьянина имеет правильные размеры, но отличается от версии на макете для этого разрешения. Нужно было не переиспользовать изображение для версии на 1600px, а скачать с макета версию на 1000px и с помощью тега `picture` предоставлять пользователю разные версии изображения в зависимости от ширины экрана. Подробнее: <https://web.dev/learn/design/picture-element/#image-sizes>

![скриншот с расхождением](https://i.imgur.com/RoPhgDw.png)

- В Pick and feed a friend заметил некорректно экспортированную иллюстрацию. В Figma при экспорте векторных изображений в таких случаях нужно снять флажок с опции "Simplify Stroke"

![скриншот](https://i.imgur.com/bmBHOLN.png)

![скриншот интерфейса Figma](https://i.imgur.com/7ePzUdL.png)

### 640px

- -5 баллов В footer'е отсутствует блок с копирайтом _Designed by_. Проблема возникает и на 320px, а также на странице Donate на тех же медиазапросах. Снимаю баллы однократно.

Небольшие помарки:

- В секции Backstage. Заголовок "The Backstage of the Wilderness World" и подзаголовок "How it works" на макете имеют небольшой отступ слева. В работе его нет. Разница менее 10px.

### 320px

Небольшие помарки:

- Блок Pick and feed a friend. Размер шрифта подзаголовка "How it works" отличается от макета: 23px вместо положенных 24px.

## Другое

- -30 баллов Горизонтальный скролл, как минимум, на 640px и 320px. Мало того, что фоновое изображение вставлено с помощью тега `picture`, так еще и используется версия изображения для разрешения 1600px. Для вставки фоновых изображений нужно использовать только теги `background-image` и `background-position`. На странице Donate нет фоновых изображений и поэтому нет такой проблемы.

![скриншот](https://i.imgur.com/OeHfAW3.png)

Видео с иллюстрацией проблемы: <https://i.imgur.com/FptHw1x.mp4>

- Ширина экрана 750px. За такое по ТЗ не положено снимать баллы т.к. цветок считается фоновым элементом, но выглядит подобное реально плохо

![скриншот](https://i.imgur.com/ElNDXDK.png)

- Ширина экрана 600px. Развалился логотип в footer'е.

![скриншот](https://i.imgur.com/9PvyIn8.png)

- Тоже 600px. Декоративные стрелки в блоке карточек с шагами лучшее вообще было спрятать, чем показывать такое

![скриншот](https://i.imgur.com/hLVbocR.png)

## Страница Donate (40 баллов за адаптивность - 5 штрафных баллов = 35 баллов)

### 1000px

- -5 баллов. Шкала не соответствует макету. Проблема есть и на меньших медиа-запросах. Снимаю баллы однократно

![скриншот](https://i.imgur.com/BWm0DjY.png)

Мелкие помарки:

- Изображение панды имеет правильные размеры, но немного приближено к зрителю по сравнению с версией на макете

- В параграфе "Even though the Zoo has been able to reopen..." на макете часть текста жирная (`font-weight: 500`), а несколько предложений имеют стандартную жирность (`font-weight: 400`). Автор работы это не заметила и весь текст сделала жирным. Нужно было использовать `span` внутри `p` и задать отдельный класс для текста с другой жирностью. Проблема есть и на меньших медиа-запросах.

### 640px

Мелкие помарки:

- Изображение панды имеет правильные размеры, но находится чуть дальше от зрителя по сравнению с версией на макете

### 320px

Мелкие помарки:

- Изображение панды имеет правильные размеры, но находится чуть дальше от зрителя по сравнению с версией на макете

- Подзаголовок "We know the animals bring you joy" имеет меньший `line-height` по сравнению с макетом: (1.2 вместо 1.4)

- "Panda diet for the day" сделан отступ от края, которого нет на макете, из-за чего подпись переносится на вторую строчку

![скриншот](https://i.imgur.com/1nKXJdw.png)

**Comment by helenakrasnova** [comment]
оценка выставлена
