### ISSUE TITLE
Cross-Check 'online-zoo. week-2' - 'mvttsun'

### ISSUE THREAD

**Issue by MVTTSUN** [rolling-scopes-school/support#736]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/mvttsun-JSFE2022Q3/online-zoo/pages/main/)

2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/mvttsun-JSFE2022Q3)

3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/stream2/online-zoo/README.md)

4. A Link to the checklist for evaluating the task (if it exists)

5. A screenshot of cross-checking marks
![Screenshot_2022-10-09-16-39-45-551_com.android.chrome.jpg](https://user-images.githubusercontent.com/24241423/194884562-e93b7b7d-7112-40bc-bead-c6c74661d85c.jpg)![Screenshot_2022-10-09-16-39-55-649_com.android.chrome.jpg](https://user-images.githubusercontent.com/24241423/194884582-60554f70-f572-42ab-beeb-b3dcdee70af2.jpg)![Screenshot_2022-10-09-16-40-05-338_com.android.chrome.jpg](https://user-images.githubusercontent.com/24241423/194884604-b7114d03-25fc-4b46-b203-95affbbd6247.jpg)

6. A final score after self-assessment, with comments
Самооценка 80 баллов. Последний студент, который поставил 10 баллов, с ним не согласен с оценкой. Responsive - полоса прокрутки не появляется. При 320px блоки у меня не едут. В девтулс в режиме телефона все нормально, по нему и делал. Браузерный режим из за скролла конечно смещает блоки. После оценки всеми тремя проверяющими я исправил фиксацию хедера, смещение навигации с 58 до 48 ps на 1000px и смещение кнопок в блоке pets на 640px. И мне последние два выставили оценку повыше, была 75 баллов от двух, от одного 10.

7. A cross-check score of your Score - 67

**Comment by helenakrasnova** [comment]
Дублирование https://github.com/rolling-scopes-school/support/issues/734
