### ISSUE TITLE
Cross-Check 'online-zoo. week-3' - 'soblvsk'

### ISSUE THREAD

**Issue by soblvsk** [rolling-scopes-school/support#739]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/soblvsk-JSFE2022Q3/online-zoo/pages/main/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/soblvsk-JSFE2022Q3/tree/gh-pages)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-3)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://online-zoo-week3-2022q3.netlify.app/)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/81454805/195756997-51a7ce2d-e51d-45c3-bc62-74d6de56a59f.png)
![image](https://user-images.githubusercontent.com/81454805/195757038-c0c0d5f3-6131-4d1d-a918-4c240d404825.png)
![image](https://user-images.githubusercontent.com/81454805/195757076-5d3990bb-89c5-4d8a-a51a-b9ab4efe2237.png)

6. A final score after self-assessment, with comments
Оценка 100, все пункты были выполнены. Почему то многие студенты придумывают свое ТЗ либо не перезагружают страницу.
Второй скриншот:
У меня от 0 до 7;
В ТЗ не было прописано, что если уже после четырех вводишь, то кружочек остается(Многие работы сделаны без этого)
Обидно, что многие студенты не ответственно подходят к проверке или нельзя связаться с ними
7. A cross-check score of your Score 
97

**Comment by helenakrasnova** [comment]
разница в баллах меньше 10%

**Comment by soblvsk** [comment]
А почему нельзя, если человек сам придумал ТЗ, и из-за этого получил не 100 баллов?

**Comment by helenakrasnova** [comment]
Жалоба на проверющего подается через форму https://docs.google.com/forms/d/e/1FAIpQLSc9su27qv3CzpkWQNRP2RsHCgjw0NFsmRT0fQgHA3ccN08vwA/viewform
Что касается апелляции, в правилах описано, что апелляция рассматривается только в случае расхождения более 10%
![image](https://user-images.githubusercontent.com/44213581/195842727-86317230-afa5-45b7-b993-c1884abb4f71.png)
