### ISSUE TITLE
Cross-Check 'Movie Search' - 'DmitryLebetsky'.

### ISSUE THREAD

**Issue by DmitryLebetsky** [rolling-scopes-school/support#74]
Демо - https://dmitrylebetsky-movie-search.netlify.app/
Проект на гитхабе - https://github.com/rolling-scopes-school/dmitrylebetsky-RS2020Q1/tree/movie-search
Оценка в результате самопроверки: 180 
Выполненные пункты:
1) вёрстка. Минимальная ширина, при которой приложение отображается корректно – 320 рх. На разрешениях меньше десктопного виртуальная клавиатура может скрываться 

2) дизайн, UI. Выполняются требования к оформлению приложения 

3) поиск: при открытии приложения курсор находится в строке поиска; автозаполнение поля ввода отключено (нет выпадающего списка с предыдущими запросами); есть placeholder; поисковый запрос можно ввести как нажатием клавиши Enter, так и кликом по кнопке Search или аналогичной; после ввода поискового запроса и отображения результатов поиска, набранный запрос отображается в поле поиска, в поле ввода есть кнопка Очистить, которая визуально представлена в виде крестика. При клике по кнопке Очистить поле ввода очищается 

4) при отправке запроса и ожидания ответа от сервера присутствует индикация процесса загрузки 

5) при вводе в поле поиска корректного поискового запроса, по которому API возвращает результат, обновляются данные о фильмах 

6) при вводе некорректного запроса, по которому API возвращает ошибку, приложение не ломается, выводится уведомление 'No results were found for … ' 

7) ошибки, возникающие во время выполнения запросов к API, обрабатываются и выводятся в область уведомления об ошибках 

8) при вводе запроса на русском языке поисковый запрос переводится на английский язык, выводится уведомление 'Showing results for … '. **Если у вас не отображаются переводы слов, проверьте, не связано ли это с блокировкой Яндекса 

9) на карточке с фильмом указывается рейтинг IMDb 

10) название фильма является ссылкой на видеогалерею даного фильма на сайте https://www.imdb.com 

11) реализован адаптивный слайдер/свайпер, карточки с фильмами можно перелистывать как кликами по стрелкам, так и пролистывать пальцем или мышкой 

12) при достижении конца слайдера/свайпера происходит загрузка следующей страницы поискового запроса 

13) слайды меняются плавно, без рывков и проскакиваний нескольких слайдов, при смене поискового запроса данные сначала загружаются, потом отображаются, плавная смена фонового изображения 

14) карточки с фильмами отображаются на странице только после полной загрузки контента (нет постепенной подгрузки картинок) 

15) реализован дополнительный, не предусмотренный заданием функционал. Дополнительный функционал оценивается с точки зрения его уместности и соответствия задачам приложения, сложности реализации, полезности для пользователя 

16) поисковый запрос можно набирать на виртуальной клавиатуре. Есть возможность переключения языка клавиатуры кликом мышки 

17) поисковый запрос можно отправить, кликая мышкой по кнопке Enter на виртуальной клавиатуре. Поисковый запрос можно редактировать при помощи виртуальной клавиатуры перемещаясь стрелками вправо-влево и вводя текст на позицию курсора 

Баллы за crosscheck из Score:
### Student3: 150, отзыв: 
Score: 150

Basic scope +60

Выполнено все.

Advanced scope +50

не выполнено - карточки с фильмами отображаются на странице только после полной загрузки контента (нет постепенной подгрузки картинок)

Hacker scope +10

клава так и не появилась при нажатии на иконку
### ИТОГОВЫЙ БАЛЛ ЗА CROSSCHECK: 170

**Comment by hallovarvara** [comment]
Проверила, согласна с самопроверкой. По спорным моментам:

- [x] Клавиатура работает, скринкаст с проверкой необходимых пунктов задания:
https://monosnap.com/file/TyznnR2KtrILbqAEBIbdUKQoB6u1Gt

- [x] Карточки появляются после полной загрузки контента, нет постепенной подгрузки картинок, скринкаст:
https://monosnap.com/file/NSoI3SKtN2subcTfpE2NJ183xuPqZj

Оценка: 180 баллов.

**Comment by Student-Java** [comment]
Закрыл за давностью проблемы
