### ISSUE TITLE
Cross-Check 'online-zoo. week-3' - 'strei-foxflashbacks'

### ISSUE THREAD

**Issue by strei-foxflashbacks** [rolling-scopes-school/support#740]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/strei-foxflashbacks-JSFE2022Q3/online-zoo/pages/main/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/strei-foxflashbacks-JSFE2022Q3/tree/online-zoo)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-3)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://online-zoo-week3-2022q3.netlify.app/)
5. A screenshot of cross-checking marks
<img width="1440" alt="Screenshot 2022-10-14 at 10 57 31" src="https://user-images.githubusercontent.com/73337918/195806697-a3a90c86-5470-4ad6-8a17-55213b1bb8e6.png">

6. A final score after self-assessment, with comments
Ваша отметка - 100 балла(ов)
Отзыв по пунктам ТЗ:

*Сделано шероховато, так и не разобрался в причине слегка дёрганой анимации ползунка карусели в блоке testimonials, но анимация присутствует и карусель реагирует правильно на движение ползунка, так что технически всё выполнено. Кстати, карусель так же можно двигать скроллом и ползунок тоже будет реагировать. Это не связано с требованиями, но мне было именно интересно сделать это таким способом.*

Все пункты выполнены полностью!

7. A cross-check score of your Score 
90

**Comment by ipipka** [comment]
## Итого: 89 баллов

### Карусель на странице Landing в блоке Pets

- **[-5 баллов]** _Пробуем нажать на кнопку очень быстро несколько раз так, чтобы нажатия уместились в момент, пока происходит анимация. Если при этом начинается новая анимация посреди текущей, или следующая анимация начинается без нажатия на кнопку: -5_ — Первая анимация не завершается, "поверх" нее начинается следующая анимация

- **[-3 балла]** _При ширине экрана 1000px должно отображаться 6 карточек, стрелки находиться между верхним и нижним рядами_ — положение кнопок для размеров экрана 1000px и 640px зависит от высоты экрана, то есть кнопки-стрелки не находятся между верхними и нижними рядами, а находятся в произвольном месте, поэтому частично снижаю (единожды, так как ошибка по сути одна)

- **[без штрафа]** — Я вижу как при анимации изменяются карточки на старом (изначальном) слайде, в карусели такого быть не должно. Старый слайд должен оставаться неизменным, а на его место должен "приезжать" новый набор

- **[без штрафа]** — Первое нажатие кнопки вправо/влево не меняет направление. Корректное направление анимации только со второго нажатия одной и той же кнопки 

Видео (положение кнопок, изменения карточек, направление анимации) https://dropmefiles.com/3r41J


### Карусель на странице Landing в блоке Testimonials
- **[без штрафа]** — На ширине 1000px в крайнем правом положении ползунка последний отзыв обрезается (если для перемещения использовать именно ползунок)
![image](https://user-images.githubusercontent.com/57938417/196445392-c2410e2c-09cf-47da-88aa-d6c70ae7a84e.png)

- **[без штрафа]** — Некомфортное перетягивание ползунка


### Popup на странице Landing в блоке Testimonials
- **[-3 балла]** _Отсутствует внешняя (затемненная) область или крестик_ — Отсутствует крестик


### Панель Amount в блоке Pick and feed a friend на странице Donate
- **[без штрафа]** — При переходе на страницу "Donate" в консоль падают две ошибки 
![image](https://user-images.githubusercontent.com/57938417/196446532-cb8f5994-eca8-4a82-ada3-1ac7f54f0fb0.png)

### Комментарий
На мой взгляд, если студент притендует на максимальный балл, то не должно быть очевидных проблем, в том числе с версткой. Но это мои мысли, за верстку не снижала (кроме того момента, где в требованиях описано конкретное положение кнопок)
В подвале вообще беда - ссылка About куда-то улетает на 640 и 320, сначала пустота, а потом только ссылки
![image](https://user-images.githubusercontent.com/57938417/196447577-1f122b07-a8f5-443c-b832-1b35c2cfcd08.png)
![zoo320](https://user-images.githubusercontent.com/57938417/196447613-a78ecb2e-8cfb-4baf-a243-7e6508b569df.jpg)
![zoo640](https://user-images.githubusercontent.com/57938417/196447619-7d778e58-a0ae-48ad-a7c7-f1ebbcb22029.jpg)

**Comment by helenakrasnova** [comment]
выставлено
