### ISSUE TITLE
Cross-Check Online-zoo.week-3 - PavelArabei.

### ISSUE THREAD

**Issue by PavelArabei** [rolling-scopes-school/support#741]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/pavelarabei-JSFE2022Q3/online-zoo/pages/main/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/pavelarabei-JSFE2022Q3)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-3)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8-cross-check-%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-3)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/109901811/195872662-c5cfb1aa-d15d-43ac-80e9-f248d8622750.png)
6. A cross-check score of your Score 
Все выполнено согласно заданию - 100
8. A final score after self-assessment, with comments
90

**Comment by ipipka** [comment]
## Итог: 100 баллов

**Хорошая работа, все соответствует ТЗ** 
Хотя, конечно, крестик закрытия попапа внутри - это легкий путь (понятно, что причина такого решения overflow: hidden). Но все же советую научиться решать такие проблемы - думаю пригодится в дальнейшем :)

**Comment by helenakrasnova** [comment]
выставлено
