### ISSUE TITLE
Cross-Check 'online-zoo-week-3' 'elenadatso'

### ISSUE THREAD

**Issue by ElenaDatso** [rolling-scopes-school/support#742]
Приветствую! Живу в Украине. Буду благодарна за перепроверку моего задания , так как по причине отстутствия электричества после понедельничных "прилетов", в моем городе электричество отсутствовало и  я не смогла в крайний день, 10 октября, задеплоить крайние правки кода... Gratitude garantied! 
P.S. Крайняя версия задания задеплоина в моем приватном репо, т.к. после дедлайна я не могу вносить изменения в свой репо на rs...

1. A link to your deployed project
    - [link](https://elenadatso.github.io/online-zoo/online-zoo/pages/main/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/elenadatso-JSFE2022Q3/tree/main/online-zoo)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-3)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8-cross-check-%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-3)
5. A screenshot of cross-checking marks
![скриншот оценок](https://snipboard.io/PrnAqo.jpg)
6. A final score after self-assessment, with comments
Все пункты в соответствии с требаниями в задании выполены в полном обьеме. На мой взгляд оценка должна быть 100.
7. A cross-check score of your Score 
Моя финальная оценка получилась 77, но она не обьективна, так как к деплое не было последних правок, котрые устраняли причину отсутствий (не отображения) хедера и карусели в секции Pets

**Comment by helenakrasnova** [comment]
A final score after self-assessment, with comments - оценка как вы себя оцениваете
имена проверябщих не скрыты

**Comment by ElenaDatso** [comment]
Да, спасибо за комментарий. Я исправила пункт 6 в шаблоне. По поводу имен проверяющих, да они не скрыты. Так что, мне к ним обращаться? Простите, я просто не очень понимаю какие должны быть мои действия. Я оформила запрос именно сюда, так как предварительно в discord уточнила как мне действовать в моей ситуации и мне админы написали оформить аппеляцию. ![скринфот из чата](https://snipboard.io/RxClHW.jpg)

> A final score after self-assessment, with comments - оценка как вы себя оцениваете имена проверябщих не скрыты

**Comment by helenakrasnova** [comment]
Ознакомьтесь пожалуйста еще раз с документацией, проверьте и исправьте пункты которые заполнены неверно:
![image](https://user-images.githubusercontent.com/44213581/195976914-f723b434-e5f3-41dc-876f-27a11411f7f7.png)

**Comment by ElenaDatso** [comment]
> Ознакомьтесь пожалуйста еще раз с документацией, проверьте и исправьте пункты которые заполнены неверно: ![image](https://user-images.githubusercontent.com/44213581/195976914-f723b434-e5f3-41dc-876f-27a11411f7f7.png)

Я поняла свою ошибку, исправила. Хотя почему то в английском описании требования не указано что контакты проверяющих должны быть скрыть (ниже приклепляю скрин). Скриншот в п. 5 переделала. Пункт 6 с самооценкой переписала. 
![screenshot](https://snipboard.io/6oM4Df.jpg)

**Comment by YuliDemins** [comment]
меню в хедере +10
карусель в блоке петс +30
карусель в блоке Testimonials +20
попап в блоке Testimonials +10 немного странный дизайн попапа - как будто со страницы пропадает весь контент (возможно стоит добавить прозрачности в поле вокруг попапа (не снижено))
Панель Amount в блоке Pick and feed a friend +30 . не подсвечивается активный кружок при нажатии на цифру. на мой взгляд не очень удобно нажимать еще и на точку, чтобы сделать сумму активной (не снижено) немного не понятно, почему в поле можно ввести все нули - нельзя же отправить пожертвование ноль долларов (не снижено). съезжает кнопка внизу блока около 320пикс и выше (не снижено, нет требования по верстке, оценивали ранее)

итоговый скор 100
