### ISSUE TITLE
Cross-Check online-zoo-3 Doroshkeviches

### ISSUE THREAD

**Issue by Doroshkeviches** [rolling-scopes-school/support#743]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/doroshkeviches-JSFE2022Q3/online-zoo/
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/doroshkeviches-JSFE2022Q3/tree/main/online-zoo
3. A link to the task
    -https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F-3
4. A Link to the checklist for evaluating the task (if it exists)
    - 

5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/110036197/195939183-fb87cdab-08a5-416d-9360-df7e87f9d89b.png)
![image](https://user-images.githubusercontent.com/110036197/195939218-8d59ed37-dfbf-47d6-93ff-4874b0792f33.png)
![image](https://user-images.githubusercontent.com/110036197/195939238-ef066018-3665-46fe-a643-c2f7658542a1.png)
6. A final score after self-assessment, with comments
https://www.youtube.com/watch?v=QGvlHQOk3QY     <-- ссылка на видео , как у меня открывается мой проект и я там показал что все работает ))
сейчас распишу текстом ошибки которые у меня есть 
бургер-меню : 
При нажатии на кнопку закрытия (крестик или другой визуальный элемент) или затемненную область меню не закрывается: -5.
карусель pets:
Мини-уточнение (в этой оценке не учитывается дизаин ) {
при разрешении 1600px стрелочки немного поехали, они будут реагировать на нажатие если :
левая - нажимать в самую левую часть стрелочки ( тк див со стрелкой немного поехал в дизаине)
права - нажимать в левую часть стрелки ( тк див немного поехал при дизаине)
так же можно открыть dev tools и увидеть эти дивы наглядно, заранее спасибо ) 
}
Проверяем условие случайной генерации. При нажатии на кнопку влево и вправо, или наоборот, будет каждый раз генерироваться новый набор карточек. Если их состояние сохраняется: -5.
Попробуйте перезагрузить страницу, можно пару раз, и полистать влево и врпаво. Если после перезагрузки вы видите справа или слева такой же порядок карточек, как до перезагрузки: -5. Стартовый (самый первый) набор карточек может оставаться одинаковым.
Popup : 
При нажатии на внешнюю (затемненную) область или крестик попап не закрывается: -5
donate : 
Если в поле Another amount ввести число, которое не совпадает ни с одной из сумм в Amount сверху, ни один кружок не должен быть подсвеченным. Если нет: -5.
Итого  100 - 5-5-5-5-5 = 75

7. A cross-check score of your Score 
![image](https://user-images.githubusercontent.com/110036197/195940526-d4532b3f-e038-4236-8748-354e3b202606.png)

**Comment by helenakrasnova** [comment]
пункт 6 - всё то что после _Итого 100 - 5-5-5-5-5 = 75_ - удалить

**Comment by Doroshkeviches** [comment]
Сделал, немного добавил описание  в "карусель pets" тк у меня из-за дизаина немного поехали стрелочки, и не вся стрелочка реагирует на нажатие а только ее часть))

**Comment by evg-zlg** [comment]
Взял на проверку

**Comment by evg-zlg** [comment]
# Оценка - 60 баллов. 


# Меню (бургер-меню) в хедере - 0 из 10 баллов

## Пункт кросс-чека: 
При нажатии на кнопку закрытия (крестик или другой визуальный элемент) или затемненную область меню не закрывается: -5.
### Что не так:
При нажатии на затемнённую область меню не закрывается. 

## Пункт кросс-чека:
"Отсутствует затемнение или кнопка закрытия (крестик или другой визуальный элемент): -5"
### Что не так:
Затемнение отображается в верхней части страницы, в нижней части страницы - не отображается. 

## Ещё замечания по бургеру:
- бургер меню прилипает к хедеру, т.е. если прокрутить страницу чуть ниже, кнопка бургера нажимается, но ничего не появляется - ни затемнения, ни пунктов меню. 
![image](https://user-images.githubusercontent.com/85534817/203530331-05706735-a2f0-47a8-bd06-c7200ac2006d.png)

- на странице Donate бургер меню не работает

# Карусель в блоке Pets - 20 из 30 баллов
## Не выполнены пункты:
Проверяем условие случайной генерации. При нажатии на кнопку влево и вправо, или наоборот, будет каждый раз генерироваться новый набор карточек. Если их состояние сохраняется: -5.

Попробуйте перезагрузить страницу, можно пару раз, и полистать влево и врпаво. Если после перезагрузки вы видите справа или слева такой же порядок карточек, как до перезагрузки: -5. Стартовый (самый первый) набор карточек может оставаться одинаковым.

# Карусель в блоке Testimonials - 10 из 20 баллов
### Не выполнен пункт:

Анимации нет или время анимации равно 0: -10

# Попап при нажатии на отзыв в блоке Testimonials - 5 из 10 баллов
## Пункт кросс-чека:
Отсутствует внешняя (затемненная) область или крестик: -5
### Что не так:
Внешняя затемнённая область появляется только в блоке "Pick and feed a friend", в блоке "Testimonials" затемнения не появляется. Какое-то затемнение пусть и не там - всё же есть, поэтому штраф не начисляю. 
![image](https://user-images.githubusercontent.com/85534817/203533882-6c627f67-661b-4d95-8477-8ae7dbb4c839.png)
## Пункт кросс-чека:
При нажатии на внешнюю (затемненную) область или крестик попап не закрывается: -5
### Что не так:
Пункт не выполнен

## Ещё замечание по Popup:
При клике на отзыв открывается popup с заранее заданным контентом, не соответствующим контенту отзыва, по которому был клик. 

# Панель Amount в блоке Pick and feed a friend - 25 из 30 баллов
## Не выполнен пункт:
Если в поле Another amount ввести число, которое не совпадает ни с одной из сумм в Amount сверху, ни один кружок не должен быть подсвеченным. Если нет: -5.

**Comment by Doroshkeviches** [comment]
Я прошу прощения конечно но блок Testimonades реализован , если можно перепроверить , могу даже прикрепить видео с тем как все работает

**Comment by evg-zlg** [comment]
Карусель в блоке Testimonials. 
Исправил, добавил баллы.

**Comment by helenakrasnova** [comment]
выставлено
