### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'denis-dev1'

### ISSUE THREAD

**Issue by Denis-dev1** [rolling-scopes-school/support#744]
Related with the existing misunderstandings and disagreements in task requirements and their description, and also due to the fact I did not read all the info in the announcement channel.
Is it possible to check my work separately? or give an apportunity to Submit it?
Thanks in advance 😉

1. A link to your deployed project
    - [link](https://denis-dev1.github.io/rsschool-cv//)
2. A link to the project repository on Github.
    - [link](https://github.com/Denis-dev1/rsschool-cv/tree/main)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - do not exist
5. A screenshot of cross-checking marks
    - do not exist
6. A final score after self-assessment, with comments
    - 120
    (meets all scoring criteria)
7. A cross-check score of your Score 
    - 0

**Comment by Denis-dev1** [comment]
![image](https://user-images.githubusercontent.com/60603557/196474928-b343cd9d-fa11-46a1-8759-043085eb14c6.png)

**Comment by Anik188** [comment]
![image](https://user-images.githubusercontent.com/8234670/196610292-1460f759-fc78-4ee0-8bc5-0d4f5035859e.png)
The deadline updated in consistency to schedule

**Comment by Anik188** [comment]
Total: 120
All requirements are met
