### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics' 'olyalass'

### ISSUE THREAD

**Issue by o-lss** [rolling-scopes-school/support#745]
1. A link to your deployed project
    - [link](https://olyalass.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/olyalass/rsschool-cv/)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
<img width="825" alt="Screenshot 2022-10-18 at 12 17 46" src="https://user-images.githubusercontent.com/101867037/196403816-53b07dd7-b677-4ef3-bd7f-579cb8251a96.png">

6. A final score after self-assessment, with comments
120
7. A cross-check score of your Score 
none

NOTE: I didn't submitted task before deadline because of misunderstanding. Hanna Pratasevich proposed (to those who didn't understand the deadline trick) to make an appeal, so I do so. Thank you, dear activist, if you read this!)

**Comment by Anik188** [comment]
All requirements are met.
Total: 120
