### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics.' 'ikoroleva'

### ISSUE THREAD

**Issue by ikoroleva** [rolling-scopes-school/support#746]
I haven't submitted the task before the deadline, because of a misunderstanding. Thanks the activists for reviewing my task, I appreciate it a lot.

1. A link to your deployed project
    - [link](https://ikoroleva.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/ikoroleva/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/23174097/196413527-7563e603-4c29-46a4-a47e-ce9a1f99e94c.png)

6. A final score after self-assessment, with comments
115, no project examples
7. A cross-check score of your Score 
None

**Comment by Anik188** [comment]
Good job!
Project examples ( if you have no, add the link to CV task) - -5

Total:  115

**Comment by ikoroleva** [comment]
Thank you for the review!
