### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' '777-blue'

### ISSUE THREAD

**Issue by 777-blue** [rolling-scopes-school/support#747]
deadline changed in the schedule, could not submit via cross-check

1. A link to your deployed project
    - [CV](https://777-blue.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [GitHub](https://github.com/777-blue/rsschool-cv)
3. A link to the task
    - [CV. HTML,CSS & Git. Cross-check (EN)](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [CV. HTML,CSS & Git. Cross-check (EN)](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
5. A screenshot of cross-checking marks
n/a
6. A final score after self-assessment, with comments
n/a
7. A cross-check score of your Score 
n/a

**Comment by Anik188** [comment]
"Document checking completed. No errors or warnings to show." - -10
Code examples ( using appropriate symbols or tags) - -1 ( no need to use span inside code tag)
Project examples ( if you have no, add the link to CV task) - -2 ( you should add link to projects, not to github)


Total: 107

**Comment by 777-blue** [comment]
wow=) thank you so much! <3
