### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics' 'annantonenko'

### ISSUE THREAD

**Issue by AnnAntonenko** [rolling-scopes-school/support#748]
A link to your deployed project
[link](https://annantonenko.github.io/rsschool-cv/)
A link to the project repository on Github.
[link](https://github.com/annantonenko/rsschool-cv/)
A link to the task
[link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
A Link to the checklist for evaluating the task (if it exists)
[link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/43850568/196416478-fe410716-faf2-46b8-82d9-2b29d8301871.png)

A final score after self-assessment, with comments
120, I suppose I did everything from the task

A cross-check score of your Score
None

**Comment by AnnAntonenko** [comment]
missed the deadline
I have missed it because I didnt catch I need it do this week. I thought the deadline 24.10. My work was ready on Sunday. I checked tthe schedule in rs app and was sure I did everything for this week. It is my misunderstanding, but I kindly ask you to check it as exception.
Thank you!

**Comment by Anik188** [comment]
Good job!
All requirements are met
Total: 120
