### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics' 'githubtgawlik'

### ISSUE THREAD

**Issue by Githubtgawlik** [rolling-scopes-school/support#749]
1. A link to your deployed project
    - [link](https://githubtgawlik.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/Githubtgawlik/rsschool-cv/)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/77897496/196415243-d4befc37-d22a-49af-a95b-4453a76ea8b9.png)

6. A final score after self-assessment, with comments

7. A cross-check score of your Score 

The resume was created as well as checked as you can see ahead of time. All that remained was to upload them to submite. I simply misunderstood this task. As a working man, I don't visit Discord every now and then and there was information about the submission date for this task. There was some confusion with the deadlines to do the submit for this task not by 25 but by October 18. Hanna Pratasevich recommended making a case, an appeal for this task. I am ready and it will only take a moment. Please consider my request. 

Thank you and best regards
Tomasz Gawlik

**Comment by Anik188** [comment]
header, main, footer - -3 ( forgot about main tag)
Navigation (contacts and skills) did with ul > li or ul > li > a - -10
Contacts - -5
Project examples ( if you have no, add the link to CV task) - -5

Total: 97

**Comment by Githubtgawlik** [comment]
Thanks a lot for checking my Cross-Check assignment 'CV. HTML, CSS & Git Basics'

Best regards
Tomasz Gawlik
