### ISSUE TITLE
Cross-Check 'Fancy Weather' - 'Zhenikusss'

### ISSUE THREAD

**Issue by Zhenikusss** [rolling-scopes-school/support#75]
Здравствуйте. по своей ошибке забыл сабмитнуть работу по fancy-weather и по согласованию с администрацией школы выкладываю свою работу на проверку активистами.
- Ссылка на деплой проекта - https://zhenikusss-fancy-weather.netlify.app/
- Ссылка на репозиторий с проектом на GitHub - https://github.com/rolling-scopes-school/zhenikusss-RS2020Q1/tree/fancy-weather
- Оценка в результате самопроверки: 140.

Частично выполненные пункты:
1) координаты в градусах и минутах
2) при вводе в поле поиска некорректных запросов приложение не ломается, пользователю выводится уведомление об ошибке

Выполненные пункты:
1) минимальная ширина страницы, при которой она отображается корректно – 320 рх. Все указанные в задании элементы присутствуют как на десктопной, так и на мобильной версии
2) приложение корректно отображается для любого выбранного языка, единиц измерения температуры, указанного в поиске населённого пункта
3) внешний вид приложения внешне соответствует макету или является его улучшенной версией
4) данные о погоде и местоположении пользователя
5) дата в указанном в описании задания формате, часы, обновляющие время каждую секунду
6) В блоке Прогноз погоды на три дня корректно отображаются данные, относящиеся к текущему местоположению пользователя
7) карта с маской (форма карты отличная от прямоугольной) и маркером населённого пункта
8) поиск работает как при нажатии на клавишу Enter в поле поиска, так и при клике на кнопку Поиск
9) поиск корректно работает для разных населённых пунктов - больших и маленьких, столиц и посёлков
10) дата и время указываются для того часового пояса, в котором находится указанный в поле поиска населённый пункт
11) одновременное обновление всех элементов страницы при вводе нового населенного пункта после получения успешного ответа по каждому из запросов (название по локации приходит быстро, а погода, иконки ее и т.п. - медленно). В случае возникновения ошибки по одному из запросов данные не обновляются
12) фоновое изображение генерируется с учётом поры года и времени суток указанного в поле поиска населённого пункта (по желанию можно добавлять и другие параметры поиска). Если возникла ошибка в ходе получения картинки, использовать любое стандартное фоновое изображение. Так как API для картинок не всегда возвращает правильный результат, данные о параметрах запроса фонового изображения для удобства в ходе проверки ментором или в процессе кросс чека выведите в консоль
13) плавная смена фонового изображения, изображение сначала загружается и только потом меняется, у изображения есть полупрозрачный оверлей или используется другой способ, обеспечивающий чёткость и контрастность надписей
14) при смене шкалы отображения температур происходит пересчёт температур в соответствии с выбранной шкалой и меняется отображение активной кнопки, позволяющей определить, какая шкала сейчас активна. При перезагрузке страницы сохраняется выбранная пользователем шкала отображения температур

**Comment by hallovarvara** [comment]
**Ваша оценка — 145 баллов.**
Отзыв по пунктам ТЗ:

Частично выполненные пункты:
1) минимальная ширина страницы, при которой она отображается корректно – 320 рх. Все указанные в задании элементы присутствуют как на десктопной, так и на мобильной версии 
`feedback: Иконка наползает на текст, когда температура из 1 символа. Также, при уменьшении экрана в блоке погоды на 3 дня дочерние элементы пересекаются:`  
[Скриншот](https://monosnap.com/file/lgrhAHGjFnfgfZuZlnQ5Bav5V2XP2K)

2) при вводе в поле поиска некорректных запросов приложение не ломается, пользователю выводится уведомление об ошибке 
`feedback: Приложение не ломается, но уведомление не выводится.`

3) одновременное обновление всех элементов страницы при вводе нового населенного пункта после получения успешного ответа по каждому из запросов (название по локации приходит быстро, а погода, иконки ее и т.п. - медленно). В случае возникновения ошибки по одному из запросов данные не обновляются 
`feedback: Не одновременное — сначала меняются текстовые данные, затем изображение.`

4) при смене шкалы отображения температур происходит пересчёт температур в соответствии с выбранной шкалой и меняется отображение активной кнопки, позволяющей определить, какая шкала сейчас активна. При перезагрузке страницы сохраняется выбранная пользователем шкала отображения температур 
`feedback: При перезагрузке страницы выбранная пользователем шкала отображения температур не сохраняется.`

5) оригинальный интересный качественный дизайн приложения, иконки погоды и кнопки анимированы, для анимации используются ключевые кадры или svg-анимация 
`feedback: Иконки погоды и кнопки не анимированы, но дизайн очень качественный и красивый. Особенно иконки.`

Выполненные пункты:
1) приложение корректно отображается для любого выбранного языка, единиц измерения температуры, указанного в поиске населённого пункта 
2) внешний вид приложения внешне соответствует макету или является его улучшенной версией 
3) данные о погоде и местоположении пользователя 
4) дата в указанном в описании задания формате, часы, обновляющие время каждую секунду 
5) В блоке Прогноз погоды на три дня корректно отображаются данные, относящиеся к текущему местоположению пользователя 
6) карта с маской (форма карты отличная от прямоугольной) и маркером населённого пункта 
7) координаты в градусах и минутах 
8) поиск работает как при нажатии на клавишу Enter в поле поиска, так и при клике на кнопку Поиск 
9) поиск корректно работает для разных населённых пунктов - больших и маленьких, столиц и посёлков 
10) дата и время указываются для того часового пояса, в котором находится указанный в поле поиска населённый пункт 
11) если у координаты есть знак минус, он тоже выводится, или возле координаты выводится буква, обозначающая широту (северная (N), южная (S)) и долготу (восточная (E), западная (W)) 

12) фоновое изображение генерируется с учётом поры года и времени суток указанного в поле поиска населённого пункта (по желанию можно добавлять и другие параметры поиска). Если возникла ошибка в ходе получения картинки, использовать любое стандартное фоновое изображение. Так как API для картинок не всегда возвращает правильный результат, данные о параметрах запроса фонового изображения для удобства в ходе проверки ментором или в процессе кросс чека выведите в консоль 
`feedback: Запрос в консоль не выводится, но, по-моему, это некритично, потому что фон меняется на уместное для локации изображение.`

13) плавная смена фонового изображения, изображение сначала загружается и только потом меняется, у изображения есть полупрозрачный оверлей или используется другой способ, обеспечивающий чёткость и контрастность надписей
