### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'ElenaCoder'

### ISSUE THREAD

**Issue by ElenaCoder** [rolling-scopes-school/support#750]
"Missed the deadline"

1. A link to your deployed project
    -  https://elenacoder.github.io/rsschool-cv/
2. A link to the project repository on Github.
    - https://github.com/ElenaCoder/rsschool-cv/tree/gh-pages
3. A link to the task
    -  https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md
4. A Link to the checklist for evaluating the task (if it exists)
     n/a
5. A screenshot of cross-checking marks
     n/a
6. A final score after self-assessment, with comments
     n/a
7. A cross-check score of your Score 

Situation description:
During all week the deadline for submitting this task was displayed until 25.10 in the system. The max score for this task was 120p. Everything looked logical to me. On week 4 you needed to make your CV and get the score and on week 5 you should submit the task for cross checking and could get up to 120 points. Therefore, I was pretty sure that I could submit this second task and start cross checking today. But as it turned out the deadline in the system was suddenly changed to 2022-10-18 02:59  without any notification and now I am not able to continue my work this week. I guessed I could rely on the deadline data in the RS platform. Or at least the first deadline date in the beginning of the week should be not changeable. It looks like it was some technical fault.

What I want:
It would be nice to get access to submit this task. This task is just a formal way to get access for the further tasks. All needed work (CV on gitHub and JS test) was performed  by me in time.

**Comment by ElenaCoder** [comment]
![image](https://user-images.githubusercontent.com/97116051/196456334-e00e5c5b-1779-4178-a9a6-07a2e132caa2.png)

**Comment by ElenaCoder** [comment]
Please see the snapshot below which proves that the deadline was changed in the last moment:
![image](https://user-images.githubusercontent.com/97116051/196441836-acd0fb7b-e527-4e98-9b60-4e6aa107d29a.png)

**Comment by ElenaCoder** [comment]
Here is another proof that the deadline was changed:
![image](https://user-images.githubusercontent.com/97116051/196455625-390bafd5-952e-47a5-8f4e-0c67866d433a.png)

**Comment by Anik188** [comment]
![image](https://user-images.githubusercontent.com/8234670/196608459-ca7b3b05-ad46-466b-a14f-caf54514f388.png)
The deadline update in consistency to schedule

**Comment by Anik188** [comment]
Project examples ( if you have no, add the link to CV task) - -5
Total: 115

**Comment by ElenaCoder** [comment]
Hi @Anik188! Thank you very much for the answer. 

On the previous week there were moments when the information in the README.md distinguished with info in RS platform and the rules were applied accordingly to RS system information. And for this reason this week I didn't pay careful attention to the README.md file and relied on the RS system deadlines. Anyway, next time I'll ask if I notice some odd things.

Do I understand correctly that I got 115 points as evaluation for this task?

BR, Elena
