### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics'- 'Rasmiyya-Mammadli'

### ISSUE THREAD

**Issue by Rasmiyya-Mammadli** [rolling-scopes-school/support#751]
1. https://github.com/Rasmiyya-Mammadli/rsschool-cv.git
2. https://rasmiyya-mammadli.github.io/rsschool-cv/
3. https://github.com/Rasmiyya-Mammadli/rsschool-cv/tree/rsschool-cv-html
- Because of missing deadline I have to make an appeal. Unfortunately I thought I should upload once for auto-test but I had to twice also for cross-check yesterday. I have finished my task already but I have uploaded for 'auto-test' not for 'cross-check', that's why I ask a favor to control my appeal and give an answer, thanks for your appreciation.

**Comment by Anik188** [comment]
Deployed on gh-pages, the link is submitted - -5 ( not working link )
There are semantic tags in the code - -5 ( no nav)
The photo exist, the alt attribute is present - -10
Code examples ( using appropriate symbols or tags) - -5 ( you should use pre, code tags)

Total: 95

**Comment by Rasmiyya-Mammadli** [comment]
thank you
