### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics  breath-out

### ISSUE THREAD

**Issue by breath-out** [rolling-scopes-school/support#753]
1. A link to your deployed project
https://github.com/)](https://breath-out.github.io/rsschool-cv/
2. A link to the project repository on Github.
   https://github.com/)](https://github.com/breath-out?tab=repositories
3. A link to the task
 https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md

Hello! 
Due to the unpredictable changes and misunderstanding about that in the schedule (Yesterday when I sent the coding task CV. HTML,CSS & Git (EN) the deadline of its cross-check was shown as 25/10/2022) I would like to ask you about the opportunity to submit the task. Even though I got just 25 points for this task of coding, it had been hard work for me. And definitely, I would submit it if I have known that the schedule suddenly will be changed.
Thanks for your comprehension.
Best regards, Iuliia Chupina.

**Comment by Anik188** [comment]
Deployed on gh-pages, the link is submitted - -1 (incorrect link)
There are semantic tags in the code - -3(forgot about nav)
The photo exist, the alt attribute is present - -10
Code examples ( using appropriate symbols or tags) - -5

Total: 101

**Comment by breath-out** [comment]
Hello! 
Thank you for checking my task. I appreciate it a lot.
I would like to notice that I have the photo of logo RS School with the alt attribute in my cv (  a tag img with alt attribute). And in your check, you gave me -- 10 for that. Sorry, maybe I didn't get the idea right but what is wrong with this example of using img + alt?
Thank you one more time. Have a nice day!
