### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics' 'kruchkou'

### ISSUE THREAD

**Issue by kruchkou** [rolling-scopes-school/support#754]
1. A link to your deployed project
    - [deployed project](https://kruchkou.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [repository](https://github.com/kruchkou/rsschool-cv)
3. A link to the task
    - [task](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(HTML+CSS+Markdown).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [checklist](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
5. A screenshot of cross-checking marks
<img width="1440" alt="Screenshot 2022-10-18 at 14 06 34" src="https://user-images.githubusercontent.com/45610004/196424875-eba8506c-8fc5-4350-91a6-6709b8ff4071.png">

6. A final score after self-assessment, with comments
    -  120 points, all requirements are met
7. A cross-check score of your Score
    -  120 points

As many other students, I was relying on online schedule on RS app and missed the deadline for cross-check submitting (there was a deadline shift from 24.10 to 17.10). As seen on screenshot above, I've submitted the auto-test part and haven't submitted the cross-check link.
Could you let me pass the task properly?
Thanks in advance.

**Comment by HopelessJu** [comment]
<html>
<body>


Criteria | Points
-- | --
Deployed on gh-pages, the link is submitted | 10
The layout pass the validation (https://validator.w3.org/)."Document checking completed. No errors or warnings to show."in case no errors, but exist warning | 10 
There are semantic tags in the code (pay attention, they should be logically used, not just for points): |
header, main, footer | 5
nav | 5  
only one h1 for page | 5
several h2 | 5 
Footer contains link to your github , date (month, year), course logo with the link | 10
Present css styles | 10
Horizontal centered layout (decreasing the browser width - the layout still in the center) | 10
The photo exist, the alt attribute is present | 10
Navigation (contacts and skills) did with ul > li or ul > li > a | 7
Brief information about yourself | 5
Contacts | 5
Skills | 5
Code examples ( using appropriate symbols or tags) | 5
Project examples ( if you have no, add the link to CV task) | 5
Education and English level | 5


</body>
</html>

The criteria that are not fully met : Navigation (contacts and skills) did with ul > li or ul > li > a - skills did with `<p>.`

Total score points **117/120**

**Comment by kruchkou** [comment]
@HopelessJu Big thanks for your review!

**Comment by HopelessJu** [comment]
@Anik188 review completed
