### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics. Cross-check' 'Helgako-123'

### ISSUE THREAD

**Issue by Helgako-123** [rolling-scopes-school/support#755]
1. A link to your deployed project
    - [link](https://helgako-123.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/Helgako-123/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)

Hello! 
Due to my inattentiveness, I missed the deadline for submitting the project for review. I pushed the button in the auto-test section and thought that I've completed the task. However, since I'm just a beginner I would really appreciate it if someone could give me feedback in respect of my coding. I want to improve my skills so I really need that someone told me how it should be adjusted. Thank you in advance!

**Comment by HopelessJu** [comment]
A link to your deployed project should look like `https://GITHUB-USERNAME.github.io/rsschool-cv/` 
https://helgako-123.github.io/rsschool-cv/ - This is the link to your deployed project.

**Comment by Helgako-123** [comment]
> A link to your deployed project should look like `https://GITHUB-USERNAME.github.io/rsschool-cv/` https://helgako-123.github.io/rsschool-cv/ - This is the link to your deployed project.

Thank you! I've just changed it accordingly.

**Comment by HopelessJu** [comment]
The criteria that were not met: 

The layout pass the validation (https://validator.w3.org/)."Document checking completed. No errors or warnings to show." **-10**
 there are errors and warnings (https://validator.w3.org/nu/?doc=https%3A%2F%2Fhelgako-123.github.io%2Frsschool-cv%2F) 
![Screenshot (95)](https://user-images.githubusercontent.com/106112358/196677729-57c2e950-5244-4dc5-a1b7-2b808339e768.png)

Criteria that were partially met: 

Navigation (contacts and skills) did with ul > li or ul > li > a - contacts did with `<p>` **-3**

Footer contains link to your github , date (month, year), course logo with the link  **-1.5** 
- there is some problem with logo path, and as a result it didn't load
![image](https://user-images.githubusercontent.com/106112358/196679443-67517689-ef79-4842-9f52-0eee0b2712b3.png)

Total score: ***106/120***

**Comment by HopelessJu** [comment]
@Anik188 review completed

**Comment by Helgako-123** [comment]
> The criteria that were not met:
> 
> The layout pass the validation ([https://validator.w3.org/)."Document](https://validator.w3.org/).%22Document) checking completed. No errors or warnings to show." **-10** there are errors and warnings (https://validator.w3.org/nu/?doc=https%3A%2F%2Fhelgako-123.github.io%2Frsschool-cv%2F) ![Screenshot (95)](https://user-images.githubusercontent.com/106112358/196677729-57c2e950-5244-4dc5-a1b7-2b808339e768.png)
> 
> Criteria that were partially met:
> 
> Navigation (contacts and skills) did with ul > li or ul > li > a - contacts did with `<p>` **-3**
> 
> Footer contains link to your github , date (month, year), course logo with the link **-1.5**
> 
> * there is some problem with logo path, and as a result it didn't load
>   ![image](https://user-images.githubusercontent.com/106112358/196679443-67517689-ef79-4842-9f52-0eee0b2712b3.png)
> 
> Total score: _**106/120**_

Thank you very much for your time! It was very important for me to receive feedback.
