### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics' 'andreytodd'

### ISSUE THREAD

**Issue by andreytodd** [rolling-scopes-school/support#756]
1. A link to your deployed project
    - [link](https://andreytodd.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/andreytodd/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
5. A screenshot of cross-checking marks
<img width="1427" alt="Screenshot 2022-10-18 at 14 40 29" src="https://user-images.githubusercontent.com/100035313/196431921-30e747d6-10c7-48ff-966c-14db84162818.png">

6. A final score after self-assessment, with comments
N/A
7. A cross-check score of your Score 
N/A

Hello, as many of the students here, I have missed the deadline due to misunderstanding and deadlines were not too clear for me. As you can see, I have completed the task itself with 100 points but missed the cross-check submit deadline (which I thought is on 25.10). Can you please let me submit my project for cross-check?

Thank you in advance and kind regards,
Andrey

**Comment by HopelessJu** [comment]
**Criteria that were not met:**

`Code examples ( using appropriate symbols or tags)`  **-5**

`Project examples ( if you have no, add the link to CV task)`  **-5**

**Criteria that were met partially :**

 `Navigation (contacts and skills) did with ul > li or ul > li > a` - navigation is not made with `ul > li or ul > li > a`, but the contacts and skills are. **-3** (7/10)
 
 `There are semantic tags in the code (pay attention, they should be logically used, not just for points)
header, main, footer` - no `<main>` tag is present **-1.5** (3.5/5)

`Education and English level` - no English level is present **-2.5** (2.5/5)

Total score: **103/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
