### ISSUE TITLE
'Cross-Check 'CV. HTML, CSS & Git Basics' 'darogawlik'

### ISSUE THREAD

**Issue by DaroGawlik** [rolling-scopes-school/support#757]
1. A link to your deployed project
    - [link](https://darogawlik.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/DaroGawlik/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/97292765/196434515-5304e692-528d-456b-b4da-a745777d34c3.png)

6. A final score after self-assessment, with comments
- I think 120 becouse i have fulfiled all recommendations.

7. A cross-check score of your Score 
n/a

Please allow me to submit my task becouse i thought deadline is 25 ocotber. I did everything for this week just only didin't send my task to cross-check.  Hanna Pratasevich proposed to make an appeal to everyone who didn't understand.

Thanks.

**Comment by o-lss** [comment]
Code example presented with no appropriate tags (`<pre> or <code>`), but with` <p>` tag. **-5 points** 

**Score**: 115/120

**Comment by o-lss** [comment]
@Anik188 review completed
