### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics' 'ralo44'

### ISSUE THREAD

**Issue by ralo44** [rolling-scopes-school/support#758]
1. A link to your deployed project
    - [link](https://ralo44.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/ralo44/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/15311173/196439880-3466a94e-8bc9-4585-8a07-9cfd1182947b.png)

6. A final score after self-assessment, with comments
N/A
7. A cross-check score of your Score 
N/A

Sorry about the issue, i misunderstood the assignment , Would it be possible to allow me submit it ?
Thank you
Omar Rangel

**Comment by o-lss** [comment]
According to criteria, you have no mistakes. 

**Score**: 120/120

**Comment by o-lss** [comment]
@Anik188 review completed
