### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics' 'SiarheiPalavets'

### ISSUE THREAD

**Issue by SiarheiPalavets** [rolling-scopes-school/support#759]
1. A link to your deployed project
    - [link](https://siarheipalavets.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://https://github.com/SiarheiPalavets/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/100991316/196442168-4e4859bf-c41b-4486-8e11-c24c2acf47d0.png)

6. A final score after self-assessment, with comments
50, Failed commit requirements: Commits do no follow guideline
7. A cross-check score of your Score 
none, i missed the deadline, because on the app.rs.school was a deadline by 25.10

**Comment by o-lss** [comment]
No `<nav>` tags **-5 points**

No `<h2>` tags, but there're many `<h3>` so I suggest not to reduce points. 

No photo **-10 points**

No` ul > li ` **-10 points**

Code examples are provided with links, not as text in appropriate tags (`<pre>` or `<code>`) **-5 points**

Projects mentioned in code example section, but they exist. 


**Total score:** 90

**Comment by o-lss** [comment]
@Anik188 review completed
