### ISSUE TITLE
Cross-Check 'Fancy Weather' - 'GanulAnton'.

### ISSUE THREAD

**Issue by GanulAnton** [rolling-scopes-school/support#76]
Демо - https://ganulanton-fancy-weather.netlify.app
Проект на гитхабе - https://github.com/rolling-scopes-school/ganulanton-RS2020Q1/tree/fancy-weather/fancy-weather
Оценка в результате самопроверки: 235, я успел реализовать все пункты по заданию кроме дополнительного дизайна.

Ниже предоставляю результат проверки анонимного проверяющего с Cross-Check: 

Ваша оценка - 185 баллов 

Отзыв по пунктам ТЗ:

Не выполненные/не засчитанные пункты:

1) дата в указанном в описании задания формате, часы, обновляющие время каждую секунду 

2) дата и время указываются для того часового пояса, в котором находится указанный в поле поиска населённый пункт 

3) оригинальный интересный качественный дизайн приложения, иконки погоды и кнопки анимированы, для анимации используются ключевые кадры или svg-анимация 

4) продуман и реализован не предусмотренный заданием дополнительный функционал 

Частично выполненные пункты:

1) внешний вид приложения внешне соответствует макету или является его улучшенной версией 

2) поиск корректно работает для разных населённых пунктов - больших и маленьких, столиц и посёлков 

3) есть индикация активного и неактивного состояния микрофона, активное и неактивное состояние переключаются по клику 

4) после того, как название населённого пункта произнесено, поиск срабатывает автоматически, без необходимости кликать на кнопку 

5) поиск ведётся на языке отображения страницы, если срабатывает поиск и на другом языке тоже, это не является ошибкой 

6) голосовое уведомление о прогнозе погоды можно запустить произнеся кодовую фразу. Также голосом можно регулировать громкость уведомления. Обратите внимание, голосовое управление работает только при включенном микрофоне

**Comment by hallovarvara** [comment]
**Ваша оценка - 197.5 баллов** 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) при перезагрузке страницы сохраняется выбранный пользователем язык 

2) продуман и реализован не предусмотренный заданием дополнительный функционал 

Частично выполненные пункты:
1) приложение корректно отображается для любого выбранного языка, единиц измерения температуры, указанного в поиске населённого пункта 

2) поиск корректно работает для разных населённых пунктов - больших и маленьких, столиц и посёлков 

3) одновременное обновление всех элементов страницы при вводе нового населенного пункта после получения успешного ответа по каждому из запросов (название по локации приходит быстро, а погода, иконки ее и т.п. - медленно). В случае возникновения ошибки по одному из запросов данные не обновляются 

4) есть индикация активного и неактивного состояния микрофона, активное и неактивное состояние переключаются по клику 

5) голосовое уведомление о прогнозе погоды можно запустить произнеся кодовую фразу. Также голосом можно регулировать громкость уведомления. Обратите внимание, голосовое управление работает только при включенном микрофоне 

6) переводится весь текст страницы. Не является ошибкой отсутствие перевода карты 

7) оригинальный интересный качественный дизайн приложения, иконки погоды и кнопки анимированы, для анимации используются ключевые кадры или svg-анимация 

Выполненные пункты:
1) минимальная ширина страницы, при которой она отображается корректно – 320 рх. Все указанные в задании элементы присутствуют как на десктопной, так и на мобильной версии 

2) внешний вид приложения внешне соответствует макету или является его улучшенной версией 

3) данные о погоде и местоположении пользователя 

4) дата в указанном в описании задания формате, часы, обновляющие время каждую секунду 

5) В блоке Прогноз погоды на три дня корректно отображаются данные, относящиеся к текущему местоположению пользователя 

6) карта с маской (форма карты отличная от прямоугольной) и маркером населённого пункта 

7) координаты в градусах и минутах 

8) поиск работает как при нажатии на клавишу Enter в поле поиска, так и при клике на кнопку Поиск 

9) при вводе в поле поиска некорректных запросов приложение не ломается, пользователю выводится уведомление об ошибке 

10) дата и время указываются для того часового пояса, в котором находится указанный в поле поиска населённый пункт 

11) если у координаты есть знак минус, он тоже выводится, или возле координаты выводится буква, обозначающая широту (северная (N), южная (S)) и долготу (восточная (E), западная (W)) 

12) фоновое изображение генерируется с учётом поры года и времени суток указанного в поле поиска населённого пункта (по желанию можно добавлять и другие параметры поиска). Если возникла ошибка в ходе получения картинки, использовать любое стандартное фоновое изображение. Так как API для картинок не всегда возвращает правильный результат, данные о параметрах запроса фонового изображения для удобства в ходе проверки ментором или в процессе кросс чека выведите в консоль 

13) плавная смена фонового изображения, изображение сначала загружается и только потом меняется, у изображения есть полупрозрачный оверлей или используется другой способ, обеспечивающий чёткость и контрастность надписей 

14) при смене шкалы отображения температур происходит пересчёт температур в соответствии с выбранной шкалой и меняется отображение активной кнопки, позволяющей определить, какая шкала сейчас активна. При перезагрузке страницы сохраняется выбранная пользователем шкала отображения температур 

15) после того, как название населённого пункта произнесено, поиск срабатывает автоматически, без необходимости кликать на кнопку 

16) поиск ведётся на языке отображения страницы, если срабатывает поиск и на другом языке тоже, это не является ошибкой 

17) при клике по кнопке проигрывания звука есть возможность прослушать звуковое уведомление о прогнозе погоды 

18) перевод на белорусский язык названий дней недели и месяцев

### Обратная связь

Speech recognition работает странно:
- говорю Sydney, мне показывает New whales, хотя в строке поиска и в консоли Sydney
- Tokyo не нашел вообще
- На название отеля Mariott выдал Toronto (пыталась разобраться, в чем проблема) https://monosnap.com/file/DtCSUaAN4UfC7RDElhtCReTz4Mu1MD 

Ввожу название маленького города, приложение выводит область:
https://monosnap.com/file/dTeRx6WKldtMfXWBK4Gj28CMsCym5F

При переключении языка ничего не произошло (ждала несколько минут):
https://monosnap.com/file/N3xzZ3wAo0HAJr2G7ZGTaxy6PHntcZ
Во второй раз получилось, но никакой индикации, что что-либо происходит (прелоадера, например), не было.

Меняю на русский с белорусского, язык контента не сменился и через 3 минуты:
https://monosnap.com/file/jiJcQpgl6wc6Qyi4vnBjbq3MKqjCJD 
В итоге, без очистки Local Storage в консоли на русский не смогла переключиться. Постоянно оставался белорусский, при перезагрузке тоже он.

Погода в этом случае читает что-то такое очень долго:
Zero ... small letter b, zero ... small letter ...

Иконки и кнопки не анимированные.

Дополнительный функционал не вижу. Укажи, пожалуйста, где он, если он есть.

**Comment by hallovarvara** [comment]
@valerydluski, прошу тебя проверить работу, Антон говорит, что проблема может быть локально у меня на маке. Если будет время, сделай, пожалуйста.

**Comment by valerydluski** [comment]
@hallovarvara Хорошо. Я сегодня проверю.

**Comment by valerydluski** [comment]
Не выполненные/не засчитанные пункты:

1) продуман и реализован не предусмотренный заданием дополнительный функционал

Частично выполненные пункты:

1) приложение корректно отображается для любого выбранного языка, единиц измерения температуры, указанного в поиске населённого пункта

2) поиск корректно работает для разных населённых пунктов - больших и маленьких, столиц и посёлков

3) одновременное обновление всех элементов страницы при вводе нового населенного пункта после получения успешного ответа по каждому из запросов (название по локации приходит быстро, а погода, иконки ее и т.п. - медленно). В случае возникновения ошибки по одному из запросов данные не обновляются

4) фоновое изображение генерируется с учётом поры года и времени суток указанного в поле поиска населённого пункта (по желанию можно добавлять и другие параметры поиска). Если возникла ошибка в ходе получения картинки, использовать любое стандартное фоновое изображение. Так как API для картинок не всегда возвращает правильный результат, данные о параметрах запроса фонового изображения для удобства в ходе проверки ментором или в процессе кросс чека выведите в консоль

5) при клике по кнопке проигрывания звука есть возможность прослушать звуковое уведомление о прогнозе погоды

6) оригинальный интересный качественный дизайн приложения, иконки погоды и кнопки анимированы, для анимации используются ключевые кадры или svg-анимация

Оценка: 210.

**Comment by hallovarvara** [comment]
> @hallovarvara Хорошо. Я сегодня проверю.

Спасибо тебе большое.

**Comment by dzmitry-varabei** [comment]
@hallovarvara @valerydluski спасибо!
