### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'ayazhm'

### ISSUE THREAD

**Issue by ayazhm** [rolling-scopes-school/support#760]
I missed the cross-check deadline as it was suddenly changed to this week.
1. A link to your deployed project
    - [link](https://ayazhm.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/ayazhm/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(HTML+CSS+Markdown).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
5. A screenshot of cross-checking marks
n/a
6. A final score after self-assessment, with comments
n/a
7. A cross-check score of your Score 
n/a

**Comment by HopelessJu** [comment]
**Criteria that were not met:** 

- `The layout passes the validation (https://validator.w3.org/)."Document checking completed. No errors or warnings to show."` **-10**

![Screenshot (96)](https://user-images.githubusercontent.com/106112358/196684359-acf5ac91-71b9-41bd-af41-661115cd8d9d.png)

- There is no `<nav>` **-5**

- `Project examples ( if you have no, add the link to CV task)` **-5**

**Criteria that were met partially:** 

- `Footer contains link to your github , date (month, year), course logo with the link` - there is no link in the footer to the author's github (though it is in contacts, but regarding the criteria it also should be in the footer) **-3** (7/10)

Total score: **97/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
