### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'Ajronic'

### ISSUE THREAD

**Issue by Ajronic** [rolling-scopes-school/support#761]
1. A link to your deployed project
    - [link](https://ajronic.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://ajronic.github.io/rsschool-cv/)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/57682372/196457509-5471510e-78a2-4701-a6d6-d1dccadd7a20.png)

6. A final score after self-assessment, with comments
120 - it meets all the criteria.
7. A cross-check score of your Score 
N/A

I have missed the deadline for submitting cv page for cross-check. I have completed the task, but like many other students I was sure that the deadline for submitting for cross-check was 25/10/2022.

**Comment by o-lss** [comment]
`<main> <header> </header> </main> ` is not a correct form, `<main>` and `<header>` are different parts of` <body>`, but according to criteria, **no points reduced**. 

Navigation and contacts are not provided with` ul>li` **-10 points**

Code example with `<p> `tag, not `<pre>` or `<code>` **-5 points**

**Total score: 105/120**

**Comment by o-lss** [comment]
@Anik188 review completed
