### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'va259'

### ISSUE THREAD

**Issue by va259** [rolling-scopes-school/support#762]
1. A link to your deployed project
    - [link](https://va259.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/va259/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
<img width="949" alt="Screenshot 2022-10-18 at 18 02 32" src="https://user-images.githubusercontent.com/106439920/196483403-409b2721-8144-4950-add4-f5ae17d807dd.png">

6. A final score after self-assessment, with comments
120 out of total 120 points
7. A cross-check score of your Score 
N/A

I missed the cross-check deadline as I was a bit confused, sorry about this issue. Thank you!

**Comment by HopelessJu** [comment]
Good work! All criteria were met.

Total score: **120/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
