### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'Vikkadin'

### ISSUE THREAD

**Issue by Vikkadin** [rolling-scopes-school/support#763]
1. A link to your deployed project
    - [link](https://vikkadin.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/Vikkadin/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)

Hello, 
I have a problem with submitting a CV HTML,CSS & Git cross-check task. I'm sure the deadline was to October 24, but today I got a notification that the deadline has been changed to yesterday. In the schedule, the deadlines for submitting and checking were not separated. I have only seen one deadline date, October 24th. I know that many students had the same problem. I put my Telegram for warnings about approaching deadlines. I didn't get such notifications about the mentioned task. 
Please open access for me to submit the task. 
Thank you!

![deadline-changed](https://user-images.githubusercontent.com/104149770/196505183-57b1cff1-0836-46db-9383-4c9fdd210e70.jpg)

![deadline-notification](https://user-images.githubusercontent.com/104149770/196505303-1d3230e2-770e-438b-a152-5edefe6a95d7.jpg)

![schedule](https://user-images.githubusercontent.com/104149770/196505336-8d406088-3099-4f45-971d-768b7bd4c704.png)

**Comment by o-lss** [comment]
You won't need to submit task, as this appeal'll bring you all the points deserved. 

There're some little mistakes, which are mentioned in criteria as reducing points: 
there're no `<h2>` tags, but you have `<h3>` instead 
there's no` <ul>` in contacts section, but you proved you can use `<ul> `in navigation and skills sections.
I don't see any of these mistakes as crucial, so I propose not to reduce any points at all! Your project is great :)

You also have some typos in English words, but it's just for you to know.


**Total score: 120/120**

**Comment by o-lss** [comment]
@Anik188 review completed

**Comment by Vikkadin** [comment]
@olyalass Thank you for your time and your review. I will definitely fix the mistakes you mentioned. Thank you for being so kind!
