### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'pokemondeveloper'

### ISSUE THREAD

**Issue by pokemondeveloper** [rolling-scopes-school/support#764]
1. A link to your deployed project
    - [link](https://pokemondeveloper.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/pokemondeveloper/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
n/a

6. A final score after self-assessment, with comments
n/a

7. A cross-check score of your Score 
n/a

Situation description:
During all week the deadline for submitting this task was displayed until 25.10 in the system (RS APP). The max score for this task was 120 points. Everything looked logical to me. On week 4 you needed to make your CV and get the score and on week 5 you should submit the task for cross checking and could get up to 120 points. Therefore, I was pretty sure that I could submit this second task and start cross checking today. But as it turned out the deadline in the system was suddenly changed to 2022-10-18 02:59 without any notification and now I am not able to continue my work this week. I guessed I could rely on the deadline data in the RS platform. Or at least the first deadline date in the beginning of the week should be not changeable. It looks like it was some technical fault.

What I want:
As you can see, I have completed the task itself with 100 points but missed the cross-check submit deadline (which I thought is on 25.10). It would be nice to get access to submit this task. This task is just a formal way to get access for the further tasks. All needed work (CV on GitHub and JavaScript test) was performed by me in time.

NOTE: I didn't submitted task before deadline because of misunderstanding. Hanna Pratasevich proposed (to those who didn't understand the deadline trick) to make an appeal, so I do so. Thank you, dear activist, if you read this!)

(AFTER:)
![before date changing](https://user-images.githubusercontent.com/112588599/196512428-09834e51-f5bb-4b36-beca-86380cac4398.png)

Here is another proof that the deadline was changed (BEFORE screenshot):
![196456334-e00e5c5b-1779-4178-a9a6-07a2e132caa2](https://user-images.githubusercontent.com/112588599/196512481-6541ed9d-b17d-4dfb-964d-191657851d11.png)

**Comment by HopelessJu** [comment]
Good work! All criteria were met. 

Total score: **120/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
