### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'Hurado'

### ISSUE THREAD

**Issue by Hurado** [rolling-scopes-school/support#765]
1. A link to your deployed project
    - [link](https://hurado.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/Hurado/rsschool-cv/tree/gh-pages)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/74832375/196515054-b1dc5b1e-836a-4c2e-9e2e-5b41b1819678.png)

6. A final score after self-assessment, with comments
0
7. A cross-check score of your Score 
Confused of Schedule deadline of Cross-check Submit HTML CSS CV task. First time doing cross-check and a lot of people cant understood properly requirements. Something is missed..

**Comment by HopelessJu** [comment]
Criteria that were not met:
`Education and English level` **-5**

Criteria that were met partially:

`Footer contains a link to your github , date (month, year), course logo with the link` - there is no date in the footer **-3** (7/10)

Total score: **112/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
