### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics.' 'DSMNow'

### ISSUE THREAD

**Issue by DSMNow** [rolling-scopes-school/support#766]
1. A link to your deployed project
    - [link](https://dsmnow.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/DSMNow/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
<img width="825" alt="task_message" src="https://user-images.githubusercontent.com/61952203/196571242-5e854c67-914a-4fce-adb9-d4fc9b16d8b7.png">
6. A final score after self-assessment, with comments

120
7. A cross-check score of your Score 
None

NOTE: I didn't submit the task before the deadline because the deadline on the RSS App Website suddenly changed from 25th to the 18th. I hope we, students, don't have to suffer from this strange misunderstanding. I am now following Hanna Pratsevich's suggestion to make an appeal. 
Just in case you need proof that I finished the Git-HTML-CSS task itself before the deadline, I am attaching a screenshot from the RSS App where it's marked as Done. I am only writing this appeal because I didn't submit it for cross-checking. If whoever reading this has the power, you may check this for yourself on the RSS App.
![task_done](https://user-images.githubusercontent.com/61952203/196571769-35b49ebe-66f4-4004-9c4e-c497f2abac27.png)
Therefore, I would like to either get access to submit this task or for it to be checked & counted toward my overall score. Hopefully, something like this is possible and we aren't going to get expelled over this misunderstanding. 
Sorry if I'm writing too much, I just want to clarify my situation. Thank you for your attention.

**Comment by o-lss** [comment]
Great project! 
The only crucial mistake is that there's no horizontal centered layout. The point of these criteria was to show you can use `margin-left/right: auto` to center the layout, but you just have margin:0 instead. **-10 points** 

**Total score: 110/120**

**Comment by o-lss** [comment]
@Anik188 review completed
