### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics' 'softXengineer'

### ISSUE THREAD

**Issue by softXengineer** [rolling-scopes-school/support#767]
1. A link to your deployed project
    - [link](https://softxengineer.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/softXengineer/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
![Screenshot_1](https://user-images.githubusercontent.com/80141037/196598442-93c31b03-e16a-4377-934a-dc25e7591f75.png)

6. A final score after self-assessment, with comments
n/a
7. A cross-check score of your Score 
n/a 

NOTE: I didn't submitted task before deadline because of misunderstanding. Hanna Pratasevich proposed (to those who didn't understand the deadline trick) to make an appeal, so I do so. Thank you, dear activist, if you read this!)

**Comment by HopelessJu** [comment]
@Anik188 suspicious activity found here :)

**Comment by HopelessJu** [comment]
Copy-paste - score 0.

**Comment by HopelessJu** [comment]
@Anik188 review completed
