### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics' 'afzalbekpulatov7'

### ISSUE THREAD

**Issue by afzalbekpulatov7** [rolling-scopes-school/support#768]
1. A link to your deployed project
    - [link](https://afzalbekpulatov7.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/afzalbekpulatov7/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
n/a
6. A final score after self-assessment, with comments
n/a
7. A cross-check score of your Score 
n/a

What I want:
As you can see, I have completed the task itself with 100 points but missed the cross-check submit deadline (which I thought is on 25.10). It would be nice to get access to submit this task. This task is just a formal way to get access for the further tasks. All needed work (CV on GitHub and JavaScript test) was performed by me in time.

NOTE: I didn't submitted task before deadline because of misunderstanding. Hanna Pratasevich proposed (to those who didn't understand the deadline trick) to make an appeal, so I do so. Thank you, dear activist, if you read this!)

**Comment by Aliaksandr-Bychyk** [comment]
Deployed on gh-pages, the link is submitted **[+10]**
The layout pass the validation (https://validator.w3.org/) **[+10]**
There are semantic tags in the code (header ✔, main ✔, footer ✔, nav ✔, one h1 ✔, several h2 ✔) **[+20]**
Footer contains link to your github , date (month, year), course logo with the link **[+10]**
Present css styles **[+10]**
Horizontal centered layout (decreasing the browser width - the layout still in the center) **[+10]**
The photo exist, the alt attribute is present **[+10]**
Navigation (contacts and skills) did with ul > li or ul > li > a **[+7]**
- _Contacts and skills did with ul > li, but Navigation did not (nav > a)_

Brief information about yourself **[+5]**
Contacts **[+5]**
Skills **[+5]**
Code examples (using appropriate symbols or tags) **[+5]**
Project examples (if you have no, add the link to CV task) **[+5]**
Education and English level **[+5]**

**Total score:** 117 / 120 points
