### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'muhammaddiyor-dev'

### ISSUE THREAD

**Issue by muhammaddiyor-dev** [rolling-scopes-school/support#769]
1. A link to your deployed project
    - [link](https://muhammaddiyor-dev.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/muhammaddiyor-dev/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
![196598442-93c31b03-e16a-4377-934a-dc25e7591f75](https://user-images.githubusercontent.com/74320737/196628776-8c998a3e-0610-43b4-b8b7-26e94397b7b1.png)

6. A final score after self-assessment, with comments

7. A cross-check score of your Score 

I have missed the deadline for submitting cv page for cross-check. I have completed the task, but like many other students I was sure that the deadline for submitting for cross-check was 25/10/2022.

**Comment by HopelessJu** [comment]
Good work! All criteria are met. 
p.s. instead of h2 there are a bunch of h4 (I think it can be counted)

Total score: **120/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
