### ISSUE TITLE
Cross-Check 'Fancy Weather' - 'Behemoth86'.

### ISSUE THREAD

**Issue by Behemoth86** [rolling-scopes-school/support#77]
Демо - https://behemoth86-fancy-weather.netlify.app/
Проект на гитхабе - https://github.com/rolling-scopes-school/behemoth86-RS2020Q1/tree/fancy-weather
Оценка в результате самопроверки: 200, я успел реализовать все пункты по заданию кроме дополнительного пункта и обнаружил ошибку при использовании белорусского языка.
Получил вот такой отзыв от одного из студентов, решившего остаться анонимным.

Student 1
Ваша оценка - 45 баллов 

Отзыв по пунктам ТЗ:

Не выполненные/не засчитанные пункты:

1) приложение корректно отображается для любого выбранного языка, единиц измерения температуры, указанного в поиске населённого пункта 

2) внешний вид приложения внешне соответствует макету или является его улучшенной версией 

3) данные о погоде и местоположении пользователя 

4) дата в указанном в описании задания формате, часы, обновляющие время каждую секунду 

5) В блоке Прогноз погоды на три дня корректно отображаются данные, относящиеся к текущему местоположению пользователя 

6) карта с маской (форма карты отличная от прямоугольной) и маркером населённого пункта 

7) координаты в градусах и минутах 

8) поиск корректно работает для разных населённых пунктов - больших и маленьких, столиц и посёлков 

9) дата и время указываются для того часового пояса, в котором находится указанный в поле поиска населённый пункт 

10) если у координаты есть знак минус, он тоже выводится, или возле координаты выводится буква, обозначающая широту (северная (N), южная (S)) и долготу (восточная (E), западная (W)) 

11) одновременное обновление всех элементов страницы при вводе нового населенного пункта после получения успешного ответа по каждому из запросов (название по локации приходит быстро, а погода, иконки ее и т.п. - медленно). В случае возникновения ошибки по одному из запросов данные не обновляются 

12) фоновое изображение генерируется с учётом поры года и времени суток указанного в поле поиска населённого пункта (по желанию можно добавлять и другие параметры поиска). Если возникла ошибка в ходе получения картинки, использовать любое стандартное фоновое изображение. Так как API для картинок не всегда возвращает правильный результат, данные о параметрах запроса фонового изображения для удобства в ходе проверки ментором или в процессе кросс чека выведите в консоль 

13) плавная смена фонового изображения, изображение сначала загружается и только потом меняется, у изображения есть полупрозрачный оверлей или используется другой способ, обеспечивающий чёткость и контрастность надписей 

14) при смене шкалы отображения температур происходит пересчёт температур в соответствии с выбранной шкалой и меняется отображение активной кнопки, позволяющей определить, какая шкала сейчас активна. При перезагрузке страницы сохраняется выбранная пользователем шкала отображения температур 

15) при клике по кнопке проигрывания звука есть возможность прослушать звуковое уведомление о прогнозе погоды 

16) голосовое уведомление о прогнозе погоды можно запустить произнеся кодовую фразу. Также голосом можно регулировать громкость уведомления. Обратите внимание, голосовое управление работает только при включенном микрофоне 

17) переводится весь текст страницы. Не является ошибкой отсутствие перевода карты 

18) перевод на белорусский язык названий дней недели и месяцев 

19) при перезагрузке страницы сохраняется выбранный пользователем язык 

20) оригинальный интересный качественный дизайн приложения, иконки погоды и кнопки анимированы, для анимации используются ключевые кадры или svg-анимация 

21) продуман и реализован не предусмотренный заданием дополнительный функционал 

Выполненные пункты:

1) минимальная ширина страницы, при которой она отображается корректно – 320 рх. Все указанные в задании элементы присутствуют как на десктопной, так и на мобильной версии 

2) поиск работает как при нажатии на клавишу Enter в поле поиска, так и при клике на кнопку Поиск 

3) при вводе в поле поиска некорректных запросов приложение не ломается, пользователю выводится уведомление об ошибке 

4) есть индикация активного и неактивного состояния микрофона, активное и неактивное состояние переключаются по клику 

5) после того, как название населённого пункта произнесено, поиск срабатывает автоматически, без необходимости кликать на кнопку 

6) поиск ведётся на языке отображения страницы, если срабатывает поиск и на другом языке тоже, это не является ошибкой

**Comment by valerydluski** [comment]
У меня ваше приложение умерло полностью на середине проверки 
![image](https://user-images.githubusercontent.com/57412523/84029011-62734280-a99a-11ea-8c42-15e941e71072.png)
