### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics. Cross-check' 'SzymonSurowka-Course'

### ISSUE THREAD

**Issue by SzymonSurowka-Course** [rolling-scopes-school/support#770]
1. A link to your deployed project
    - [link](https://SzymonSurowka-Course.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/SzymonSurowka-Course/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/113858501/196681046-9aba35dd-e726-4190-a926-ee0e76fef523.png)

6. A final score after self-assessment, with comments
N/A

7. A cross-check score of your Score 
N/A

As many other students, I was relying on online schedule on RS app and missed the deadline for cross-check submitting (17.10 - 24.10). Would it be possible to allow me submit it? Sorry for the issue and misunderstanding.
Thank you in advance.

Szymon Surówka

**Comment by o-lss** [comment]
No `<nav>` tag  **-5 points** 

No code examples **-5points**

Great job!

**Total score: 110/120**

**Comment by o-lss** [comment]
@Anik188 review completed
