### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics. Cross-check' 'sarvarbobobekov'

### ISSUE THREAD

**Issue by sarvarbobobekov** [rolling-scopes-school/support#771]
1. A link to your deployed project
    - [link](https://sarvarbobobekov.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/sarvarbobobekov/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)

NOTE: I didn't submitted task before deadline because of misunderstanding. Hanna Pratasevich proposed (to those who didn't understand the deadline trick) to make an appeal, so I do so. Thank you, dear activist, if you read this!)

**Comment by Aliaksandr-Bychyk** [comment]
Deployed on gh-pages, the link is submitted **[+10]**
The layout pass the validation (https://validator.w3.org/) **[+5]**
- _Warning: Section lacks heading. Consider using h2-h6 elements to [add identifying headings to all sections](https://www.w3.org/wiki/HTML/Usage/Headings/Missing), or else use a div element instead for any cases where no heading is needed_

There are semantic tags in the code (header ✔, main ✔, footer ✔, nav ✔, one h1 ✔, several h2 (one, but several h3) ✔) **[+20]**
Footer contains link to your github , date (month, year), course logo with the link **[+10]**
Present css styles **[+10]**
Horizontal centered layout (decreasing the browser width - the layout still in the center) **[+10]**
The photo exist, the alt attribute is present **[0]**
- _There is no photo_

Navigation (contacts and skills) did with ul > li or ul > li > a **[+10]**
Brief information about yourself **[+5]**
Contacts **[+5]**
Skills **[+5]**
Code examples (using appropriate symbols or tags) **[+5]**
Project examples (if you have no, add the link to CV task) **[+5]**
Education and English level **[+5]**

**Total score:** 105 / 120 points

**Comment by HopelessJu** [comment]
@Anik188 review completed (by @AlexanderBychyk)
