### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'abulkosim'

### ISSUE THREAD

**Issue by Abulkosim** [rolling-scopes-school/support#773]
1. A link to your deployed project
    - [link](https://abulkosim.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/Abulkosim/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks

![image_2022-10-19_21-38-39](https://user-images.githubusercontent.com/72679180/196752111-1f595830-78e6-471f-aa3d-4ea40a9396a1.png)

6. A final score after self-assessment, with comments

7. A cross-check score of your Score 

I missed the deadline for submitting CV for cross-check. I finished the task on time, but, like many other participants I thought that the deadline was 25 October 2022.

**Comment by HopelessJu** [comment]
Good work! 

Criteria that were not met: 

- There is no `<nav>` **-5**

Total score: **115/120**

P.s. There are no several h2, but there are several h3.

**Comment by HopelessJu** [comment]
@Anik188 review completed
