### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics.' 'Alexlions310'  

### ISSUE THREAD

**Issue by Alexlions310** [rolling-scopes-school/support#774]
1. A link to your deployed project
    - [link](https://alexlions310.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/Alexlions310/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
  
![missed](https://user-images.githubusercontent.com/63205804/196754764-43bfc541-4677-44cd-997e-eb9ab8eba8de.PNG)

# Please help me I missed the deadline because there was some misunderstanding about the schedule it was written till the 24th, and because of not having much time I didn`t see the main doc of RS school, I just tried to follow the deadline, please give me some chance

**Comment by HopelessJu** [comment]
#### Criteria that were not met:

- `The layout pass the validation (https://validator.w3.org/)."Document checking completed. No errors or warnings to show."` **-10**
![image](https://user-images.githubusercontent.com/106112358/196812530-4535beb0-ec42-444d-b051-569525d5549a.png)

#### Criteria that were met partially:


- `Education and English level` - there is no English level **-2**

Total score: 108/120

**Comment by HopelessJu** [comment]
@Anik188 review completed
