### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'tkopadze'

### ISSUE THREAD

**Issue by Tkopadze** [rolling-scopes-school/support#775]
1. A link to your deployed project
    - [link](https://tkopadze.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/Tkopadze/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
N/A
6. A final score after self-assessment, with comments
N/A
7. A cross-check score of your Score 
N/A

NOTE: I was not able to  submit task before deadline because of misunderstanding. There were different deadlines shown on github and RsSchool page. I thought the deadline was till 24th of october because it was shown on RsSchool! Hanna Pratasevich proposed (to those who didn't understand the deadline trick) to make an appeal, so I do so. Thank you very much in advance for your time and effort!

**Comment by HopelessJu** [comment]
Good work! All criteria were met.

Total score **120/120.**

**Comment by HopelessJu** [comment]
@Anik188 review completed
