### ISSUE TITLE
Cross-Check 'Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'squirelJr'

### ISSUE THREAD

**Issue by squirelJr** [rolling-scopes-school/support#776]
1. A link to your deployed project
    - [link](https://github.com/squirelJr/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/squirelJr/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    n/a
5. A screenshot of cross-checking marks

6. A final score after self-assessment, with comments
n/a
7. A cross-check score of your Score 
n/a

NOTE: I couldn't submit task before deadline because of misunderstanding.  I thought the deadline was till 24th of october because it was shown on RsSchool! Hanna Pratasevich proposed (to those who didn't understand the deadline trick) to make an appeal, so I do so. Thank you very much in advance for your time and effort!

**Comment by HopelessJu** [comment]
A link to your deployed project - https://squireljr.github.io/rsschool-cv/

**Comment by HopelessJu** [comment]
#### Criteria that were met partially:
- `The layout pass the validation (https://validator.w3.org/).
"Document checking completed. No errors or warnings to show."` **-5**
![image](https://user-images.githubusercontent.com/106112358/196815125-b6039293-67a6-45b4-a55d-7469b9ac16cb.png)

- `Navigation (contacts and skills) did with ul > li or ul > li > a` - contacts and skills aren't made with ul>li or ul>li>a **-5** (5/10)
- `Education and English level` - there is no English level -**2.5**

Total score: **108/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
