### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'duka221'

### ISSUE THREAD

**Issue by duka221** [rolling-scopes-school/support#778]
1. A link to your deployed project
    - [link](https://duka221.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/duka221/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
n/a
6. A final score after self-assessment, with comments
n/a
7. A cross-check score of your Score 
n/a
NOTE: I missed the deadline for submitting CV for cross-check. I finished the task on time, but I thought that the deadline was 25 October 2022.

**Comment by HopelessJu** [comment]
Good work. All criteria were met.

Total score: 120/120

**Comment by HopelessJu** [comment]
@Anik188 review completed
