### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics. Cross-check' 'marduda'

### ISSUE THREAD

**Issue by marduda** [rolling-scopes-school/support#779]
1. A link to your deployed project
    - [link](https://marduda.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/marduda/rsschool-cv/)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
5. A screenshot of cross-checking marks
![obraz](https://user-images.githubusercontent.com/51291664/196784569-856c946b-2252-4844-9179-e645fe992f01.png)
6. A final score after self-assessment, with comments
   n/a
7. A cross-check score of your Score 
   n/a

I missed the deadline for submitting my CV to cross-check due to missunderstanding. 

Regards,
Marcin

**Comment by HopelessJu** [comment]
### Criteria that were not met: 

 - There is no `<nav> ` **-5**

Total score: **115/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
