### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics. Cross-check' 'khatiachub'

### ISSUE THREAD

**Issue by khatiachub** [rolling-scopes-school/support#780]
1. A link to your deployed project
    - [link](https://khatiachub.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/khatiachub/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
5. 
![Screenshot_20221020-001646~2](https://user-images.githubusercontent.com/101997849/196795542-28053075-7f44-49b5-a459-bc86a6f0b361.png)

6.A final score after self-assessment, with comments
n/a

7. A cross-check score of your Score
n/a

I  missed crosscheck task because of misunderstanding, I was thinking that deadline was till 25th October.

**Comment by HopelessJu** [comment]
### Criteria that were met: 

 - `Deployed on gh-pages, the link is submitted` **+10**
- `The layout pass the validation (https://validator.w3.org/).
"Document checking completed. No errors or warnings to show."` **+10**
- `Contacts` **+5**
- `Present css styles` **+10**

### Criteria that were met partially: 
- `English level` **+2.5**

Total score **37.5/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
