### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics. Cross-check'  'olgamrrz'

### ISSUE THREAD

**Issue by olgamrrz** [rolling-scopes-school/support#781]
1. A link to your deployed project
    - [link](https://olgamrrz.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/olgamrrz/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
![missed deadline](https://user-images.githubusercontent.com/101380497/196792533-f4121299-54a9-48b1-a65f-0039bbbb84ec.jpg)
6. A final score after self-assessment, with comments

7. A cross-check score of your Score
NOTE: Unfortunately, I've missed the deadline for submitting CV for cross-check.  The deadline on the RSS App somehow changed from 25 of October to the 18. I would be very grateful for checking my work.

**Comment by HopelessJu** [comment]
Good work. All criteria were met.

Total score **120/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
