### ISSUE TITLE
Cross-Check 'online-zoo. week-3' - 'AialProkopev'

### ISSUE THREAD

**Issue by prokaidev** [rolling-scopes-school/support#782]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/aialprokopev-JSFE2022Q3/online-zoo/pages/main/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/aialprokopev-JSFE2022Q3)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#неделя-3)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#неделя-3)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/94171040/196886263-f4aff854-e436-4454-8b6d-f7a737a8fff2.png)

6. A final score after self-assessment, with comments
95/100 (во время крос-чек я все сделал, но не смог найти первого человека, чтобы он перепроверил. А 4-ый не поставил мне оценку)
7. A cross-check score of your Score 
68/100

**Comment by helenakrasnova** [comment]
коммиты после дедлайна
