### ISSUE TITLE
 Cross-Check 'online-zoo. week-1' - 'AialProkopev'

### ISSUE THREAD

**Issue by prokaidev** [rolling-scopes-school/support#783]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/aialprokopev-JSFE2022Q3/online-zoo/pages/main/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/aialprokopev-JSFE2022Q3)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#неделя-1)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream2/online-zoo#неделя-1)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/94171040/196888141-c8dcedec-b686-443e-8f8c-5f36573c3665.png)

6. A final score after self-assessment, with comments
100/100 (Соре, в то время не знал что можно перепроверять работы, и не знал что можно апеллировать)
7. A cross-check score of your Score 
69/100

**Comment by helenakrasnova** [comment]
коммиты после дедлайна
