### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & Git Basics. Cross-check' 'AleksandreAM'

### ISSUE THREAD

**Issue by ghost** [rolling-scopes-school/support#784]
1. A link to your deployed project
    - [link](https://aleksandream.github.io/rsschool-cv/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/AleksandreAM/rsschool-cv/tree/gh-pages)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks

6. A final score after self-assessment, with comments

7. A cross-check score of your Score 

Hello, I was told to make an appeal to my situation trough here. This is something that many students have faced. This is regarding the sudden deadline change from 25 to 18 for submitting our CV HTML project for cross-check. Due to work on 18th of October, I was unable to log into discord to view the updates or on the main website to submit the project or update it. 

Also, till this day, I do not see any names of students appearing in the Cross-Check review section so I can evaluate their work. In other words, I am missing two tasks due to these 2 issues.

I would be glad if you could assist me on this.

**Comment by o-lss** [comment]
There's no` <main>` tag, only class "main" **-5 points**
No `<nav>` tag **-5points**
No `<h1> ` tag **-5 points**
No `<ul>` and `<li>` tags at all **-10 points**
No code examples  **-5 points** 
No projects mentioned **-5 points** 

You made a great design and realised it, but the layout is very unusual and I hope, you'll learn a bit more about semantic tags and layout rules for your future projects. Good luck!

**Total points: 85/120**

**Comment by o-lss** [comment]
@Anik188 review completed
