### ISSUE TITLE
Cross-Check 'CV. HTML, CSS & and Git. Cross-check (EN)' 'hannaIl'

### ISSUE THREAD

**Issue by hannaIl** [rolling-scopes-school/support#785]
1. A link to your deployed project:
    - [https://hannail.github.io/rsschool-cv/](https://hannail.github.io/rsschool-cv/)
2. A link to the project repository on Github:
    - [https://github.com/hannaIl/rsschool-cv](https://github.com/hannaIl/rsschool-cv/tree/gh-pages)
3. A link to the task:
    - ["CV. HTML, CSS & Git Basics. Cross-check"](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)

5. A screenshot of cross-checking marks

6. A final score after self-assessment, with comments

7. A cross-check score of your Score 

The cross-check submit deadline missed. Is there any chance to still submit this?  The ["CV. HTML, CSS & Git Basics" task](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(HTML+CSS+Markdown).md) was submitted without delay. Thanks in advance.

**Comment by o-lss** [comment]
No `<h1>` tag **-5 points** 
No project links **-5 points** 

Good job! 

Total points: 110/120

**Comment by o-lss** [comment]
@Anik188 review completed

**Comment by hannaIl** [comment]
@olyalass , @Anik188 thank you!
