### ISSUE TITLE
Cross-check 'HTML, CSS & Git Basics.Cross-check' "https://github.com/maksimakulka"

### ISSUE THREAD

**Issue by maksimakulka** [rolling-scopes-school/support#786]
1. [A link to your deployed project
    - [link](https://harmonious-sawine-852635.netlify.app/)
2. A link to the project repository on Github.
    - [link](https://github.com/maksimakulka/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)

Hi guys!
Sorry I missed the deadline, I was guided by the schedule.
I will be more careful.
Thanks for your work, you are awesome!

**Comment by HopelessJu** [comment]
Great job. All criteria were met. 

Keep up the good work.

Total score: **120/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed

**Comment by HopelessJu** [comment]
@Anik188 review completed
