### ISSUE TITLE
Cross-Check 'HTML, CSS & Git Basics. Cross-check' 'https://github.com/Vs-elen'

### ISSUE THREAD

**Issue by Vs-elen** [rolling-scopes-school/support#788]
1. A link to your deployed project
    - [link](https://vs-elen.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/Vs-elen/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)

Hello! 
Unfortunately I missed deadline to submit my page for cross-check although it was created and auto-tested on time. Could you please check it? Next time I'll read the task more careful. Thank you!

**Comment by HopelessJu** [comment]
### Criteria that were not met:

- There is no `nav` **-5**
- `Code examples ( using appropriate symbols or tags)` - instead of code examples there are links to the projects (which is another requirement) **-5**

Total score: **110/120**
Good work.

**Comment by HopelessJu** [comment]
@Anik188 review completed
