### ISSUE TITLE
Cross-Check 'HTML, CSS & Git Basics. Cross-check' 'https://github.com/UmarjonRajabov'

### ISSUE THREAD

**Issue by UmarjonRajabov** [rolling-scopes-school/support#789]
1. A link to your deployed project
    - [link](https://umarjonrajabov.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/UmarjonRajabov/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)

Hello!
Unfortunately, I missed the deadline although it was auto-tested on time. I have a full-time job, that's why I didn't see new deadline. Could you check it? The next time, I will be more careful. 

I'm looking forward to hearing from you!

**Comment by HopelessJu** [comment]
Good work. Almost all criteria were met, except for the `nav` tag, because it doesn't have any functions - it has no style properly applied, and you cannot interact with it, nor it is visible. **-5**

Total score **115/120.**

**Comment by HopelessJu** [comment]
@Anik188 review completed
