### ISSUE TITLE
Cross-Check 'HTML, CSS & Git Basics. Cross-check' 'https://github.com/wizzdacoder'

### ISSUE THREAD

**Issue by wizzdacoder** [rolling-scopes-school/support#790]
1. A link to your deployed project
    - [link](https://wizzdacoder.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/wizzdacoder/rsschool-cv/)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)

Good evening!
I couldn't submit my task for cross-check on time, because of misunderstanding on schedule dates.
Please consider reviewing my task!! This way, I hope I am able to keep on track!
THANKS in advance!!!
Alan

**Comment by HopelessJu** [comment]
Criteria that were not met: 

- `The layout pass the validation (https://validator.w3.org/).
"Document checking completed. No errors or warnings to show."` **-10**
![Screenshot (99)](https://user-images.githubusercontent.com/106112358/197640105-52511342-f535-4d3b-bed4-c96b911bfe88.png)

All other criteria were met.

Total score **110/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
