### ISSUE TITLE
Cross-Check 'HTML, CSS & Git Basics. Cross-check' 'https://github.com/matiasgombon'

### ISSUE THREAD

**Issue by matiasgombon** [rolling-scopes-school/support#791]
1. A link to your deployed project
    - [link](https://matiasgombon.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/matiasgombon/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)

Hello, I missed the deadline because my dog ate my homework... Jk, because of a missunderstanding with the schedule. Please, I would appreciate if you could review the task.

**Comment by HopelessJu** [comment]
- There is no `main` **-5**
- `Navigation (contacts and skills) did with ul > li or ul > li > a` - skills are done with `<p>` **-5**
- `Code examples ( using appropriate symbols or tags)` - code example is done with `<p>` **-5** 

Total score **105/120**

How to use code examples in html: https://www.geeksforgeeks.org/html-code-tag/

**Comment by HopelessJu** [comment]
@Anik188 review completed
