### ISSUE TITLE
Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'cskubra'

### ISSUE THREAD

**Issue by cskubra** [rolling-scopes-school/support#792]
1. A link to your deployed project
    - [link](https://cskubra.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/cskubra/rsschool-cv/)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md#scoring-criteria)
5. A screenshot of cross-checking marks
![rsschool](https://user-images.githubusercontent.com/96026618/197631304-10cdd3d3-5960-4da6-a7b0-de1d53931b86.png)

6. A final score after self-assessment, with comments
120
7. A cross-check score of your Score 
n/a

**Comment by cskubra** [comment]
Please I had an emergency so I missed the cross-check deadline. Kindly review my appeal thanks.

**Comment by HopelessJu** [comment]
Criteria that were not met: 
- `The layout pass the validation (https://validator.w3.org/).
"Document checking completed. No errors or warnings to show."` **-10**
![Screenshot (100)](https://user-images.githubusercontent.com/106112358/197643276-294adfd5-01e9-4f02-a965-d1df9e45a6c8.png)

- `Project examples ( if you have no, add the link to CV task)` **-5**

All other criteria were met. Nice beautiful work!

**Total score: 105/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed

**Comment by cskubra** [comment]
thank you so much :)
