### ISSUE TITLE
Cross-check Gem-puzzle   (-20 points for completed tasks)

### ISSUE THREAD

**Issue by serhiishf** [rolling-scopes-school/support#793]
1. A link to your deployed project
    - [link](https://github.com/)](https://rolling-scopes-school.github.io/serhiishf-JSFE2022Q3/gem-puzzle/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/)](https://github.com/rolling-scopes-school/serhiishf-JSFE2022Q3/tree/gem-puzzle)
3. A link to the task
    - [link](https://github.com/)](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-1/dom-api/codejam-the-gem-puzzle.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - none
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/96074253/197811816-c77ae69f-d704-4fee-afbc-62b8dd5d9f4b.png)

6. A final score after self-assessment, with comments
120
7. A cross-check score of your Score 
113 in this moment. 

I know I can't appeal because I made changes after the deadline. Most likely, the 4th person will check me and give a fair assessment. However, I think that it's unfair to lower the rating like this. For someone, 20 points can be extremely critical. Please convey to the student that it is not fair to assert oneself at the expense of others.  You don't have to worry about changing my score.

**Comment by helenakrasnova** [comment]
Жалоба на проверющего подается через форму https://docs.google.com/forms/d/e/1FAIpQLSc9su27qv3CzpkWQNRP2RsHCgjw0NFsmRT0fQgHA3ccN08vwA/viewform
Апелляция подается только после дедлайна и только если оценка отличается более чем на 10% от ожидаемой
