### ISSUE TITLE
Cross-Check 'Cross-Check 'CV. HTML,CSS & Git. Cross-check (EN)' 'mishajan'

### ISSUE THREAD

**Issue by mishajan** [rolling-scopes-school/support#795]
1. A link to your deployed project
    - https://mishajan.github.io/rsschool-cv/
2. A link to the project repository on Github.
    - https://github.com/)](https://github.com/mishajan/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task
    - https://mishajan.github.io/rsschool-cv/cv
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/77223803/197839349-fbf09ec2-0a50-43ea-9f5c-4ef3040ae990.png)
7. A final score after self-assessment, with comments
120
8. A cross-check score of your Score
n/a

**Comment by mishajan** [comment]
Please I had an emergency so I missed the cross-check deadline. Kindly review my appeal thanks.

**Comment by HopelessJu** [comment]
### Criteria that were met partially:

- `The photo exist, the alt attribute is present` - there is  an `<img>` and `alt` attr is present, but the photo is not loaded (error 404)  **-5** (5/10)
![image](https://user-images.githubusercontent.com/106112358/197951555-ba97a2aa-1ea6-4405-a59b-b2759ed46f06.png)

Total score: **115/120**

**Comment by HopelessJu** [comment]
@Anik188 review completed
