### ISSUE TITLE
Cross-Check 'Codejam 2022Q3' - 'bedunkevichaa'

### ISSUE THREAD

**Issue by bedunkevichaa** [rolling-scopes-school/support#796]
1. A link to your deployed project
https://rolling-scopes-school.github.io/bedunkevichaa-JSFE2022Q3/gem-puzzle/
2. A link to the project repository on Github.
   https://github.com/rolling-scopes-school/bedunkevichaa-JSFE2022Q3/tree/gem-puzzle/gem-puzzle
3. A link to the task
    https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-1/dom-api/codejam-the-gem-puzzle.md
4. A Link to the checklist for evaluating the task (if it exists)
    https://rolling-scopes-school.github.io/checklist/
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/75007353/198534979-0c1c38f9-815d-4cbd-b185-2c5dac8001f3.png)
![image](https://user-images.githubusercontent.com/75007353/198535190-eea5d5fa-638c-4347-b1c4-6b93b8ea8d28.png)
6. A final score after self-assessment, with comments
90 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) реализован выбор размера поля (от 3х3 до 8х8) 
2) плитки можно перетаскивать с помощью мыши 
Частично выполненные пункты:
1) реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 
Отзыв: нет созранения 10 лучших результатов
7. 68 / 120

**Comment by helenakrasnova** [comment]
Название ишью неправильное

**Comment by bedunkevichaa** [comment]
> Название ишью неправильное

Исправил.

**Comment by helenakrasnova** [comment]
> > Название ишью неправильное
> 
> Исправил.

Cross-Check 'Codejam 2022Q3' - 'bedunkevichaa'

**Comment by bedunkevichaa** [comment]
> > > Название ишью неправильное
> > 
> > 
> > Исправил.
> 
> Cross-Check 'Codejam 2022Q3' - 'bedunkevichaa'

Исправил.

**Comment by Elijah-I** [comment]
**Ваша оценка - 70 баллов** 

**Отзыв по пунктам ТЗ:**

**Не выполненные/не засчитанные пункты:**

1. реализован выбор размера поля (от 3х3 до 8х8) 
2. анимация движения плитки по игровому полю 
3. плитки можно перетаскивать с помощью мыши 
4. реализовано сохранение состояния игры и сохранение 10 лучших результатов с иcпользованием LocalStorage 

_Сохранение игра сделано, но не явно. Она сама сохраняет каждый ход и после f5 восстанавливает последнее состояние. При этом теряется количество ходов и таймер перестает работать. ТОР-10 результатов не сохраняются. Я бы не засчитывал этот пункт._

**Итого за невыполненные пункты -50.**

### 120 - 50 = 70

**Comment by helenakrasnova** [comment]
В случае, когда полученная во время апелляции оценка отличается от оценки, полученной в шаге #4, менее чем на 10%, итоговая оценка повышаться не будет.
