### ISSUE TITLE
Cross-Check 'Codejam 2022Q3' - 'gomalp'.

### ISSUE THREAD

**Issue by gomalp** [rolling-scopes-school/support#799]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/gomalp-JSFE2022Q3
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/gomalp-JSFE2022Q3/tree/codejam-the-gem-puzzle
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-1/dom-api/codejam-the-gem-puzzle.md
4. A Link to the checklist for evaluating the task (if it exists)
    - https://rolling-scopes-school.github.io/checklist/
5. A screenshot of cross-checking marks
![screen](https://user-images.githubusercontent.com/84232252/199817506-4af9b5eb-3573-4edd-bc95-8596ead90e48.png)

6. A final score after self-assessment, with comments
my assessment of myself is 60-65
7. A cross-check score of your Score 
my score 65

**Comment by gomalp** [comment]
суть проблемы, в том что мне поставили 0. Т.к. получилось недоразумение. каким то образом не отправились мои оценки троим студентам из четырех. За это получил ноль. Это был мой первый кросс чек.  Я не сразу разобрался как проверить прошла оценка или нет. Теперь понимаю. Но я старался - что то получилось. И это совсем не ноль.

**Comment by helenakrasnova** [comment]
работы других студентов вовремя не были проверены, засабмитить оценку без комментария невозможно - будет ошибка
![image](https://user-images.githubusercontent.com/44213581/199990864-fb3bdc78-f7ce-41d6-b688-7832d29e1512.png)
