### ISSUE TITLE
За работу поставили 0 баллов. Проверяющий был аноним, связаться не смогла. 

### ISSUE THREAD

**Issue by IrinaPIka** [rolling-scopes-school/support#800]
1. A link to your deployed project
    - [clean-code-s1e1](https://github.com/IrinaPIka/clean-code-s1e1/pull/1)
2. A link to the project repository on Github.
    - [clean-code-s1e1](https://github.com/IrinaPIka/clean-code-s1e1)
3. A link to the task
    - [task](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - description is situated in the end of task 
5. A screenshot of cross-checking marks
![screen](https://user-images.githubusercontent.com/112224011/199890925-5ecd05e6-f2e7-48c4-9b72-ad028f2054f3.png)

6. A final score after self-assessment, with comments
45 - I made all points.   
Проверяющий поставил 0 баллов работе за то, что она была замержена. Что я завершила Pull request в свою ветку master. 
Этот пункт в ТЗ не проговаривается, как уточнила в [дискорде](https://discord.com/channels/516715744646660106/604238535502856194/1037035246492848179),  можно и мержить и не мержить PR.

7. A cross-check score of your Score 
30 (из трех оценок - 0, 44,45)

**Comment by helenakrasnova** [comment]
оформите пожалуйста ишью согласно требованиям

**Comment by IrinaPIka** [comment]
Буду благодарна, если скажите что именно не так....
Вроде бы старалась четко и точно отвечать на все пункты. 
Повторяю попытку. 

1. A link to your deployed project
  [clean-code-s1e1 gh-pages](https://irinapika.github.io/clean-code-s1e1/)   
2. A link to the project repository on Github.
  [clean-code-s1e1 - ветка master](https://github.com/IrinaPIka/clean-code-s1e1)  
  [clean-code-s1e1 - Pull Request](https://github.com/IrinaPIka/clean-code-s1e1/pull/1) - по условиям задачи его нужно было предоставить для проверки  
3. A link to the task
  [task](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md)
4. A Link to the checklist for evaluating the task (if it exists)  
  [checklist](https://rolling-scopes-school.github.io/checklist/), point CLEAN CODE S1E1  
5. A screenshot of cross-checking marks
![app rs school_course_student_cross-check-submit_course=js-fe-2022Q3 taskId=2092](https://user-images.githubusercontent.com/112224011/200046955-f0a380b4-9359-4f2d-819d-0eaccd2d06bc.png)

6. A final score after self-assessment, with comments
  -45. I made all points from checklist.   

7. A cross-check score of your Score 
  30 (average from  0, 44, 45)

**Comment by valerydluski** [comment]
https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f

**Comment by IrinaPIka** [comment]
Спасибо. Создала новый запрос, с правильным заголовком.
