### ISSUE TITLE
 Cross-Check Clean-code-s1e1 - IrinaPika

### ISSUE THREAD

**Issue by IrinaPIka** [rolling-scopes-school/support#801]
1. A link to your deployed project
  [clean-code-s1e1 gh-pages](https://irinapika.github.io/clean-code-s1e1/)   
2. A link to the project repository on Github.
  [clean-code-s1e1 - ветка master](https://github.com/IrinaPIka/clean-code-s1e1)  
  [clean-code-s1e1 - Pull Request](https://github.com/IrinaPIka/clean-code-s1e1/pull/1) - по условиям задачи его нужно было предоставить для проверки  
3. A link to the task
  [task](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md)
4. A Link to the checklist for evaluating the task (if it exists)  
  [checklist](https://rolling-scopes-school.github.io/checklist/), point CLEAN CODE S1E1  
5. A screenshot of cross-checking marks
![app rs school_course_student_cross-check-submit_course=js-fe-2022Q3 taskId=2092](https://user-images.githubusercontent.com/112224011/200046955-f0a380b4-9359-4f2d-819d-0eaccd2d06bc.png)

6. A final score after self-assessment, with comments
  -45. I made all points from checklist.   

7. A cross-check score of your Score 
  30 (average from 0, 44, 45)

**Comment by TrickyPie** [comment]
Доброй ночи, проверила твою работу. 
Мне жаль, но по итогу проверки, я считаю оценку проверяющего адекватной. 
Твоя оценка 0 баллов.

В работе действительно изменилась визуальная составляющая, что противоречит пункту:
![image](https://user-images.githubusercontent.com/103384834/200452764-3c8c7377-a61d-4c45-b71d-1187b5c545c2.png)
Изменено визуальное отображение сохраненных заданий. Они выглядят аналогично заданиям в формате редактирования - имеют border и серый цвет текста, что не соответствует макету. Это затрудняет ориентацию в приложении, так как редактируемые и сохраненные задания отличаются только незаметной кнопкой Save/Edit. Также изменен размер кнопок с удалением задания - они стали меньше. Штраф - 45 баллов.
![image](https://user-images.githubusercontent.com/103384834/200452865-3fd3d4cb-0188-4598-a2d1-d882131de402.png)

Отсутствуют коммиты по пунктам 3.2, 3.3 и 3.5. Предполагаю, что они были сделаны вместе с другими пунктами, но не были прописаны в сообщении коммита. Этого пункта нет в штрафных баллах, но это одно из условий принятия работы на проверку.
![image](https://user-images.githubusercontent.com/103384834/200454433-98f3221e-4f3f-4f00-8a0b-554aee11ddda.png)

Несмотря на штрафы, я решила посмотреть и другие пункты и дать дополнительные комментарии:

Частично выполненные пункты:

1) Правило '2.1 БЭМ' из html-and-css-extended .

Отзыв: Ты молодец, что постаралась использовать БЭМ в проекте. Обрати внимание, что в БЭМ не может быть элемента у элемента: tasks__item__checkbox или tasks__item__label.

2) Правило '1.2 Альтернатива для мультимедиа' из html-and-css-extended соблюдено: каждый мультимедиа элемент (в данном задании img) имеет alt-атрибут с осмысленным содержанием, соответствующим контенту элементы. При этом чисто декоративные картинки имеют alt с пустым значением.

Отзыв: Обрати внимание, что альтернативный текст к изображениям указан малоинформативно. При использовании скринридера, слабовидящему пользователю зачитываются альтернативные тексты картинок, так как он не может их увидеть. Если не знать, что такое eisenhower matrix - невозможно понять, что это за картинка. Также на кнопках удаления не декоративные картинки в данном случае, так как если изображение не прогрузится, а альтернативного текста не будет, пользователь не найдёт, как удалить задание из списка.

Остальные пункты я считаю выполненными и в целом считаю, что работа сделана хорошо. Но не хватило немного внимательности. Очень жаль, что не получилось исправить оценку на более хорошую из-за штрафных баллов. 

Желаю удачи в учебе!

**Comment by helenakrasnova** [comment]
выставлено

**Comment by IrinaPIka** [comment]
Спасибо. 
Смотрю, мне обнулили все оценки, а не только "спорную" подтвердили. 
Ничего себе : (((

Понятно, за помощью и с вопросами  лучше не обращаться.
