### ISSUE TITLE
Cross-Check 'online-zoo week 1' 'eratiani'

### ISSUE THREAD

**Issue by eratiani** [rolling-scopes-school/support#802]
1. A link to your deployed project
    - [link] https://eratiani.github.io/Online-zoo/
2. A link to the project repository on Github.
    - [link] https://github.com/eratiani/Online-zoo
3. A link to the task
    - [link] https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/online-zoo/online-zoo.md#week-1
4. A Link to the checklist for evaluating the task (if it exists)
    - [link] https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/online-zoo/online-zoo.md#week-1
5. A screenshot of cross-checking marks
![Screenshot_20221108-102540](https://user-images.githubusercontent.com/62502052/200490681-ed245144-58bc-4147-af7d-071a8b3a7a57.png)
![Screenshot_20221108-102533](https://user-images.githubusercontent.com/62502052/200490715-8c77efc2-4fc4-429b-ba39-e9c209e1b5b2.png)
![Screenshot_20221108-102523](https://user-images.githubusercontent.com/62502052/200490759-b26ff261-e792-4fc7-9268-d275db187b53.png)

6. A final score after self-assessment, with comments
I consider my work to be close to 100% done. Even pix perf is close. As for second evaluators remarks non of tham is viable
7. A cross-check score of your Score 
His score is 57/70

**Comment by Anik188** [comment]
Total score is 66 points, the maximum is 70. So the difference is lower than 10% (https://docs.app.rs.school/#/platform/cross-check-flow?id=appeal)
The appeal rules are not met
