### ISSUE TITLE
Cross-Check Stage#1. HTML Builder - DeFranS325

### ISSUE THREAD

**Issue by DeFranS325** [rolling-scopes-school/support#803]
1. A link to your deployed project
    - [link](https://github.com/DeFranS325/HTML-builder)
2. A link to the project repository on Github.
    - [link](https://github.com/DeFranS325/HTML-builder)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-builder)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![Апелляция](https://user-images.githubusercontent.com/107042059/201270919-7ee496a1-f8f6-4cc4-85d9-46c41b3883d5.png)

6. A final score after self-assessment, with comments
150 - На компьютере с Windows - все работает. Вероятно ошибка связана с тем, что у проверяющая MacOS или Linux, но кроссплатформенность не была заявлена и проверить нет возможности, что мой код не работает на другой операционной системе.
7. A cross-check score of your Score 
113

**Comment by helenakrasnova** [comment]
коммит после дедлайна

**Comment by DeFranS325** [comment]
Так там функционала нового нет. Только рефакторинг, чтобы на маке и линуксе
работало. Проверьте предпоследний сабмит

пт, 11 нояб. 2022 г., 17:48 helenakrasnova ***@***.***>:

**Comment by DeFranS325** [comment]
Не было в тех.задании кроссплатформенность. Было сделано под Винду. На
Винде работало. Если у меня нет мака под рукой, я на чем проверять должен?
На ладошек?

пт, 11 нояб. 2022 г., 17:50 Алексей Сергеев ***@***.***>:

**Comment by DeFranS325** [comment]
Из-за отсутствия указания на кросс-платформенность, считаю, что снижение за это баллов - не обоснованно.

**Comment by DeFranS325** [comment]
Так же хочу отметить, что увиденный @[helenakrasnova](https://github.com/helenakrasnova) helenakrasnova коммит был сделан сегодня, когда проверка закончилась. Считаю, что учитывать его не корректно.

**Comment by helenakrasnova** [comment]
![image](https://user-images.githubusercontent.com/44213581/201384348-65e50c11-ad3f-4288-9fa2-13414ed76f20.png)

**Comment by DeFranS325** [comment]
Так изменения были уже даже после дедлайна проверки! Это на оценку даже не
может повлиять. Больше для себя сделал, чтобы было как закрепление
пройденного.

пт, 11 нояб. 2022 г., 20:20 helenakrasnova ***@***.***>:

**Comment by helenakrasnova** [comment]
> Так изменения были уже даже после дедлайна проверки! Это на оценку даже не может повлиять. Больше для себя сделал, чтобы было как закрепление пройденного. пт, 11 нояб. 2022 г., 20:20 helenakrasnova ***@***.***>:

в правилах подачи апелляции не указано, что коммитов не должно быть во время кросс-чека
коммитов не должно быть пока работу не проверит активист на апелляции
