### ISSUE TITLE
Cross-Check 'HTML-builder' - 'iagasi'

### ISSUE THREAD

**Issue by iagasi** [rolling-scopes-school/support#805]
1. A link to your deployed project
    - [link](https://github.com/iagasi/HTML-builder)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-builder)
3. A link to the task
    - [link](https://github.com/EvgeniiMal/HTML-builder)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/EvgeniiMal/HTML-builder/wiki/HTML-builder-crosscheck)
5. A screenshot of cross-checking marks
![CHECK](https://user-images.githubusercontent.com/88037128/201408889-7bc3295f-d53f-4d4c-a3a4-f1fa74dbb204.png)

6. A final score after self-assessment, with comments:150 self check

8. A cross-check score of your Score :105

**Comment by helenakrasnova** [comment]
- изменить название ишью согласно требованиям
- скрыть гитхабы проверяющих из скриншота

**Comment by helenakrasnova** [comment]
Cross-Check 'HTML-builder' - 'iagasi'

**Comment by jewelhux** [comment]
Возьму работу на проверку.

**Comment by jewelhux** [comment]
**Итоговая оценка 150 баллов.**

В 4-м задании иногда выскакивает ошибка, но на результат работы не влияет.
Все остальное работает корректно, порой бывают странные выводы в консоль при выполнении, которые стоило бы убрать или оформить корректно, но это мелочи.

**Comment by helenakrasnova** [comment]
выставлено
