### ISSUE TITLE
Cross-Check 'HTML-Builder' 'HunterTigerX'

### ISSUE THREAD

**Issue by HunterTigerX** [rolling-scopes-school/support#806]
1. A link to your deployed project
    - [link](https://github.com/HunterTigerX/HTML-builder/tree/HTML-builder)
2. A link to the project repository on Github.
    - [link](https://github.com/HunterTigerX/HTML-builder/tree/HTML-builder)
3. A link to the task
    - [link](https://github.com/EvgeniiMal/HTML-builder)
4. A Link to the checklist for evaluating the task (if it exists)

5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/19664739/201373140-8141b4e7-8427-4820-9ae1-b4fe1d8ea6d0.png)

6. A final score after self-assessment, with comments
  Score: 150 / 150
 - [+] task 01 (20)
   - [х] Внутри папки 01-read-file находятся 2 файла index.js и text.txt
   - [х] При выполнении команды node 01-read-file в корневом каталоге репозитория в консоль выводится содержимое файла text.txt.
   - [х] Чтение файла происходит с помощью ReadStream.
 
 - [+] task 02 (20)
   - [х] Внутри папки 02-write-file находится 1 файл index.js
   - [х] При выполнении команды node 02-write-file в папке 02-write-file создаётся текстовый файл, а в консоль выводится приглашение на ввод текста(На ваш выбор)
   - [х] После ввода текста в каталоге 02-write-file введённый текст должен быть записан в созданный ранее файл. Процесс не завершается и ждёт нового ввода.
   - [х] После следующего ввода созданный изначально текстовый файл дополняется новым текстом, процесс продолжает ждать ввод.
   - [х] При нажатии сочетания клавиш ctrl + c или вводе exit в консоль выводится прощальная фраза и процесс завершается.
 
 - [+] task 03 (20)
   - [х] При выполнении команды node 03-files-in-folder в корневом каталоге репозитория в консоль выводится информация о файлах содержащихся непосредственно внутри 03-files-in-folder/secret-folder. Данные выведены в формате <имя файла>-<расширение файла>-<вес файла>.
   - [х] Информация выводится только для файлов содержащихся в 03-files-in-folder/secret-folder.
 
 - [+] task 04 (20)
   - [х] После завершения работы функции создаётся папка files-copy содержимое которой является точной копией исходной папки files.
   - [х] При добавлении/удалении/изменении файлов в папке files и повторном запуске node 04-copy-directory содержимое папки files-copy актуализируется.
 
 - [+] task 05 (20)
   - [х] После завершения работы скрипта в папке project-dist находится файл bundle.css содержащий стили из всех файлов папки styles.
   - [х] При добавлении/удалении/изменении файлов стилей в папке styles и повторном запуске скрипта файл bundle.css перезаписывается и содержит актуальные стили.
   - [х] Любые файлы имеющие расширение отличное от css или директории игнорируются.
   - [х] Стили находящиеся в файле bundle.css созданном в процессе сборки не повреждаются.
 
 - [+] task 06 (50)
   - [х] После завершения работы скрипта создаётся папка project-dist
   - [х] В папке project-dist находятся файлы index.html и style.css
   - [х] В папке project-dist находится папка assets являющаяся точной копией папки assets находящейся в 06-build-page
   - [х] Файл index.html содержит разметку, являющуюся результатом замены шаблонных тегов в файле template.html
   - [х] Файл style.css содержит стили, собранные из файлов папки styles
   - [х] При добавлении компонента в папку и соответствующего тега в исходный файл template.html повторное выполнение скрипта приведёт файл index.html в папке project-dist в актуальное состояние перезаписав его. Файл style.css и папка assets поддерживают актуальное состояние
   - [х] Исходный файл template.html не изменяется в ходе выполнения скрипта  

    Если судить по коду до коммитов после дедлайна, то с 1 раза могло не сработать 6 задание, если проект никогда не собирался и в зависимости от ОС, мог не сработать 4 таск, во 2 задании коммит косметический, чтобы файл создавался не после ввода текста, а при запуске команды, но первые 2 проверяющих за это баллы не снижали, коммит был сделан после их проверок, а в 5 задании только утром заметил, что css файл по ТЗ надо создавать не в папку к остальным CSS, а в папку dist, тогда баллы могли быть от 60 до 150, в зависимости от проверяющего, но никак не 0.

7. A cross-check score of your Score 
100

**Comment by helenakrasnova** [comment]
коммиты после дедлайна

**Comment by HunterTigerX** [comment]
![image](https://user-images.githubusercontent.com/19664739/201386954-933d958b-abd6-4047-a77a-59986370d4d8.png)
Ага, но меня попросили её написать, зная, что коммиты после дедлайна. Пишу просто чтобы не удалили, на всякий случай, так как не знаю, как тут у вас работает всё.

**Comment by valerydluski** [comment]
Правила для всех одинаковые
