### ISSUE TITLE
Cross-Check 'HTML-builder' - 'Zelenevskayamarina'

### ISSUE THREAD

**Issue by Zelenevskayamarina** [rolling-scopes-school/support#807]
A link to your deployed project

[link](https://github.com/Zelenevskayamarina/HTML-builder)
A link to the project repository on Github.

[link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-builder)
 A link to the task

[link](https://github.com/EvgeniiMal/HTML-builder)
4A Link to the checklist for evaluating the task (if it exists)

[link](https://github.com/EvgeniiMal/HTML-builder/wiki/HTML-builder-crosscheck)
A screenshot of cross-checking marks

![image](https://user-images.githubusercontent.com/96020253/201473146-ec6bf6a8-4b54-4bb6-8f2a-5682c1f287db.png)

 A final score after self-assessment, with comments
Все условия данного задания выполнены полностью, общий балл - 150.
01 read file - 20 баллов
02 write file - 20 баллов
03 files in folder - 20 баллов
04 copy directory - 20 баллов
05 merge styles - 20 баллов
06 build page - 50 баллов

A cross-check score of your Score - 133

**Comment by helenakrasnova** [comment]
1. поправить название ишью согласно требованиям
2. поправить ссылки чтобы отоброжались корректно
3. добавить Link to the checklist for evaluating the task

**Comment by Zelenevskayamarina** [comment]
Добрый день. Все указанные замечания исправила. Буду очень благодарна, если Вы повторно посмотрите.

**Comment by TrickyPie** [comment]
Я возьму эту работу на проверку, т.к. я уже частично проверяла ее, когда Марина писала в чат о заниженной оценке с просьбой посмотреть.

**Comment by TrickyPie** [comment]
**Итоговая оценка 150 баллов.** 

Проверила работу, все отлично работает, копируется, открывается и заменяется. Все пункты требований выполнены. 

P.S. Из того, что улучшить, в 6 задании можно заменить replace на replaceAll. Тогда при добавлении нескольких {{about}} они все будут заменяться, а не только первый. 

Удачи в учебе! :)

**Comment by helenakrasnova** [comment]
выставлено
