### ISSUE TITLE
Cross-Check 'songbird' - 'maxxxer' 

### ISSUE THREAD

**Issue by Maxxxer** [rolling-scopes-school/support#808]
Добрый день. Вынужден обратиться к вам за помощью, т.к. не успел проверить работы студентов по кросс-чеку song-bird по семейным обстоятельствам. Ребенку 7 дней и все внимание и время, вынужденно, приковано к нему. (если требуются доказательства могу предоставить в личной переписке). -245 баллов это сильнейший удар по результатам и мотивации. Прошу войти в положение и дать проверить работы выданные заранее и зачесть мои баллы. В надежде на понимание, Максим.

1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/maxxxer-JSFE2022Q3/song-bird/dist/index)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/maxxxer-JSFE2022Q3/tree/songbird)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/songbird/songbird-2022q3.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
6. 
![image](https://user-images.githubusercontent.com/102784861/203932513-07327316-ce47-42b3-acc1-cd7f3427ace0.png)
![image](https://user-images.githubusercontent.com/102784861/203932692-612578b2-ffb3-49d2-9de0-3f4ec45ef1e9.png)
![image](https://user-images.githubusercontent.com/102784861/203934050-33742218-eab5-44b6-a44e-bdbaea12ca36.png)
![image](https://user-images.githubusercontent.com/102784861/203934187-613c7daa-1d8f-4f35-bb22-2f486b65f454.png)

7. A final score after self-assessment, with comments. 245

8. A cross-check score of your Score 245

**Comment by helenakrasnova** [comment]
коммиты после дедлайна, во время кросс-чека
