### ISSUE TITLE
Cross-Check 'Books shop' 'eratiani'

### ISSUE THREAD

**Issue by eratiani** [rolling-scopes-school/support#809]
1. A link to your deployed project
    - [link](https://eratiani.github.io/Books-shop/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/eratiani/Books-shop)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/books-shop/books-shop.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/books-shop/books-shop.md)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/62502052/204409204-5213e383-00da-4440-a43b-ed84549ccd4a.png)
![image](https://user-images.githubusercontent.com/62502052/204409262-46a83b3a-46ea-4644-992b-f24449797136.png)

6. A final score after self-assessment, with comments
100 i fulfiled every criteria for the task
7. A cross-check score of your Score 
90

**Comment by eratiani** [comment]
no commits made after deadline that are connected to the mark taken

**Comment by Anik188** [comment]
![image](https://user-images.githubusercontent.com/8234670/204733120-309f502f-8861-4e87-8b9e-f1f8d95609ea.png)

**Comment by o-lss** [comment]
Hi, Erekle! I've checked your work again and you have mistakes in validation form (surname should be min 5 chars (you set min 4 as in name) and gifts should be optional (yours are obligatory 2 at the same time) - it's 5 penalty points (20 points for 8 sub-tasks, so it's 5 for 2). 
If we check ignoring commits after deadline, you get additional penalty for flat number validation -2.5 point. 

By this review you could get 92.5 points, but you can't appeal, if you committed to deployed branch after deadline (and yes, your commits are about fixing mistake, which was important for the score).

Anyway, difference is only 2.5 points, so don't worry! Good luck!

**Comment by o-lss** [comment]
@Anik188 review completed

**Comment by eratiani** [comment]
Hello i don't know where u get2.5 points from 70 to 92 it is 22 points and again if i make commits for online zoo week 4 i can't appeal for week 3? What logic is that or should i make new repo for every week? Or the rule works here but not on other tasks??

**Comment by o-lss** [comment]
You appeal not for one review, but for the whole bunch of them. You have 90 points for this task, not 70. 70 is a mark from only one student. 92,5-90=2,5 🙂

**Comment by Anik188** [comment]
@olyalass  Thank you for review!
