### ISSUE TITLE
Cross-Check 'Book shop' 'githubtgawlik'

### ISSUE THREAD

**Issue by Githubtgawlik** [rolling-scopes-school/support#811]
1. A link to your deployed project
    - (https://githubtgawlik.github.io/Book_shop/)
2. A link to the project repository on Github.
    - (https://github.com/Githubtgawlik/Book_shop)
3. A link to the task
    - (https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/books-shop/books-shop.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/77897496/205042080-837c6190-3fcd-4270-8b3c-65b8ebd8d219.png)

6. A final score after self-assessment, with comments
![image](https://user-images.githubusercontent.com/77897496/205042293-f371d4ad-7fa7-4594-b247-da9a4f59ef88.png)

7. A cross-check score of your Score 

I turned in my work on time and the message displayed is that the task is Missed. Actually the page is not finished but it should not affect whether it was handed in or not

Best Regards
Tomasz Gawlik

**Comment by Githubtgawlik** [comment]
no one will respond to my request?

**Comment by Anik188** [comment]
Hello.
Pay attention on the rules https://docs.app.rs.school/#/platform/cross-check-flow?id=step-4-receiving-the-score-and-the-comment
"If you do not check all 4 assignments before the deadline, your own assignment gets a score of 0."
You didn't check any tasks. That's why you got 0
