### ISSUE TITLE
Cross-Check Project Management App - Tihohohodka

### ISSUE THREAD

**Issue by tihohohodka** [rolling-scopes-school/support#813]
1. A link to your deployed project
    - [Deploy](https://cute-cuchufli-4a7585.netlify.app/)
2. A link to the project repository on Github.
    - [GitHub repository](https://github.com/tihohohodka/project-management-app/)
3. A link to the task
    - [Task](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/react/project-management-system-EN.md)
4. A Link to the checklist for evaluating the task (if it exists)
 -
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/65382605/206738428-949f9730-5af2-4912-8acc-305b736d4a25.png)
![image](https://user-images.githubusercontent.com/65382605/206738493-4f1edab4-b501-4d9c-93c4-6d64ece190bf.png)
![image](https://user-images.githubusercontent.com/65382605/206738584-acdb8df8-10f6-44b7-be82-74bd9f607929.png)
![image](https://user-images.githubusercontent.com/65382605/206738640-1c5d2442-a144-4fb9-94c3-4d01448dfa72.png)

6. A final score after self-assessment, with comments
We don't have a problem with assessment, but we missed a cross-check, so we got zero. Initially, we looked in schedule, where the deadline was set for December 16, which seemed very lucky since I would be hospitalized on December 7. We made our plans based on the fact that I could't participate on December 7-8 and decided to check works during weekend, so the changed deadline put us in an untenable position.
I ask, at least, to count the assessment to my partner (alekprogrammer), who is absolutely not guilty and could not influence on this situation.
7. A cross-check score of your Score 
0 (35)

**Comment by valerydluski** [comment]
36 points

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/207413884-3ed851a8-ac92-47a0-a74f-4e47e8273f31.png)
I didn't find a student with github alegra12
@tihohohodka

**Comment by tihohohodka** [comment]
> ![image](https://user-images.githubusercontent.com/57412523/207413884-3ed851a8-ac92-47a0-a74f-4e47e8273f31.png) I didn't find a student with github alegra12 @tihohohodka

He didn't participate. We don't know who it is. We found it in this table and didn't find him as well.
