### ISSUE TITLE
Cross-Check 'Node.js basics' - svinohryak

### ISSUE THREAD

**Issue by svinohryak** [rolling-scopes-school/support#814]
1. A link to your deployed project
    - [link](https://github.com/svinohryak/node-nodejs-basics/pull/1)
2. A link to the project repository on Github.
    - [link](https://github.com/svinohryak/node-nodejs-basics)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/score.md)
5. A screenshot of cross-checking marks
It hasn't been checked
<img width="909" alt="image" src="https://user-images.githubusercontent.com/38936621/207026642-f88038f2-d97b-40d1-9f23-8f3d39520927.png">

6. A final score after self-assessment, with comments
206 - all tasks are done
7. A cross-check score of your Score 
0 (it hasn't been checked)

**Comment by adelinyshka** [comment]
Task is done quite good.
My score is 206.

**Comment by svinohryak** [comment]
> Task is done quite good. My score is 206.

Thank you for checking my task.

**Comment by ThorsAngerVaNeT** [comment]
Score is updated
