### ISSUE TITLE
Cross-Check 'Node.js Basics' - 'zzhanna'

### ISSUE THREAD

**Issue by zzhanna** [rolling-scopes-school/support#815]
1. A link to your deployed project (PR)
   - [link](https://github.com/zzhanna/node-nodejs-basics/pull/1)
2. A link to the project repository on Github.
    - [link](https://github.com/zzhanna/node-nodejs-basics/tree/basic)
4. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md)
5. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/score.md)
6. A screenshot of cross-checking marks
   **Студент проверил, но к сожалению после редактирования комментария, не обратил внимания на 0 баллов**
![image](https://user-images.githubusercontent.com/71936527/207068974-bfcf4cde-3211-477b-a999-aab8c830fbf3.png)

7. A final score after self-assessment, with comments
 **Score**:  206 / 206

**Basic Scope**

☑️ *File system (src/fs)*
+6 create.js implemented properly
+10 copy.js implemented properly
+10 rename.js implemented properly
+6 delete.js implemented properly
+6 list.js implemented properly
+6 read.js implemented properly

☑️*Command line interface(src/cli)*
+6 env.js implemented properly
+6 args.js implemented properly

☑️*Modules(src/modules)*
+20 cjsToEsm.cjs refactored properly

☑️*Hash (src/hash)*
+10 calcHash.js implemented properly

☑️*Streams (src/streams)*
+10 read.js implemented properly
+10 write.js implemented properly
+10 transform.js implemented properly

☑️*Zlib (src/zip)*
+10 compress.js implemented properly
+10 decompress.js implemented properly

**Advanced Scope**

☑️*Worker Threads (src/wt)*
+10 worker.js implemented properly
+30 main.js implemented properly

☑️*Child Processes (src/cp)*
+10 spawns child process
+10 child process stdin receives input from master process stdin
+10 child process stdout sends data to master process stdout

8. A cross-check score of your Score - **96**

**Comment by AV-Shell** [comment]
##  **Оценка 206 баллов. **

Замечания:

Create.js лучше обернуть в трай кэтч чтобы если вдруг файл создастся другим процессом после окончания проверки и началом записи, словить ошибку и обработать (в нашем случае выкинуть нужную ошибку )

Copy.js надо было в блоке кэтч выбрасывать ошибку new Error("FS operation failed"); а не ту, которая туда пришла. Иначе какой смысл ловить ту что возникла и её же выкидывать.  Если папки 'files' не будет, а будет файл 'files' то упадёт другая ошибка.

rename.js если не будте файла `wrongFilename.txt` а будет папка `wrongFilename.txt`  то ошибка не выкинется, а переименует папку.

delete.js - нужную ошибку нужно выбрасывать в блоке кэтч.  Если не будет файла `fileToRemove.txt`  а будет папка `fileToRemove.txt`  то выбрасывается ошибка с другим сообщением.

list.js - аналогично delete.js

read.js - аналогично delete.js

modules: нужно было загружать только один файл  или  `"./files/a.json"` или `./files/b.json`

cp.js полностью правильно реализовано.

**Comment by ThorsAngerVaNeT** [comment]
Score is updated
