### ISSUE TITLE
 Cross-Check 'Node.js basics' - 'EugeneKovgan'.

### ISSUE THREAD

**Issue by EugeneKovgan** [rolling-scopes-school/support#816]
1. A link to your deployed project
    - [link](https://github.com/EugeneKovgan/NodeJs_2022_Q3/pull/1)
2. A link to the project repository on Github.
    - [link](https://github.com/EugeneKovgan)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md/)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/cross-check-manual.md)
5. A screenshot of cross-checking marks
![Screenshot_16](https://user-images.githubusercontent.com/56769548/207156304-10a20130-bd52-4fc1-afd1-d22451505c3d.png)
6. A final score after self-assessment, with comments
206 /206 
My task was checked only by two students.
7. A cross-check score of your Score 
 Score Points 186
My task was checked only by two students.

**Comment by adelinyshka** [comment]
output in this task has to be without '--' before key;

- `args.js` - implement function that parses command line arguments (given in format `--propName value --prop2Name value2`, you don't need to validate it) and prints them to the console in the format `propName is value, prop2Name is value2`

![1](https://user-images.githubusercontent.com/35169516/207354483-20ed0f23-aea5-43fa-9906-0dec5474c899.png)

**Comment by adelinyshka** [comment]
The result of function is wrong.

![hash](https://user-images.githubusercontent.com/35169516/207354927-d12e2259-c73a-4421-8491-0c7f64c3599f.png)

Tha right answer is on the screenshot

![image](https://user-images.githubusercontent.com/35169516/207355748-ab889d8c-f058-45eb-9417-0dc5ecdf75f8.png)

Class Hash has to be used [link to Node.js doc](https://nodejs.org/dist/latest-v18.x/docs/api/crypto.html#class-hash), not Hmac.

**Comment by adelinyshka** [comment]
Maximum score is 206
minus 2 points for wrong output in cli/args
minus 10 hash was not implemented properly

**Total: 194**

**Comment by ThorsAngerVaNeT** [comment]
Score is updated
