### ISSUE TITLE
Cross-Check "Node.js Basics" - mishaplx

### ISSUE THREAD

**Issue by mishaplx** [rolling-scopes-school/support#817]
1. A link to your deployed project
    - [link](https://github.com/mishaplx/node-js/pull/6)
2. A link to the project repository on Github.
    - [link](https://github.com/mishaplx/node-js)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/score.md)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/75118862/207236805-e1786ae8-202a-42bf-be64-fc1ddcf6e26e.png)

6. A final score after self-assessment, with comments
206/206 - I completed all tasks
7. A cross-check score of your Score - 0

**Comment by adelinyshka** [comment]
in task cli/env output should be in 1 line with `;` separator
Task: 
- `env.js` - implement function that parses environment variables with prefix `RSS_` and prints them to the console in the format `RSS_name1=value1; RSS_name2=value2`

student output:

![image](https://user-images.githubusercontent.com/35169516/207382177-08812c2d-c5e7-4db2-9c5e-ab384f2c045a.png)

**Comment by adelinyshka** [comment]
In task Modules was used `require` sometimes, not `import `, missed `console.log` with json file, so output is wrong.

Student output:

![image](https://user-images.githubusercontent.com/35169516/207407320-a2419536-3421-4d6c-b09d-ba1d4b5b0808.png)

Right output:

![image](https://user-images.githubusercontent.com/35169516/207410353-b67db34b-ea08-4d00-ba3c-b987ae4895da.png)

**Comment by adelinyshka** [comment]
This task was originally made in June, then it was added few fixes and submitted. But not all differences in tasks were taken into account

Maximum score is 206, minus 2 points for cli/env, minus 20 for modules because was not implemented properly.
206 - 22 = 184

**Total: 184**

**Comment by mishaplx** [comment]
Thanks

**Comment by AV-Shell** [comment]
issue закрывает модератор курса

**Comment by ThorsAngerVaNeT** [comment]
Score is updated
