### ISSUE TITLE
Cross-Check 'online zoo week 4' 'eratiani'

### ISSUE THREAD

**Issue by eratiani** [rolling-scopes-school/support#818]
1. A link to your deployed project
    - [link](https://eratiani.github.io/Online-zoo/)
2. A link to the project repository on Github.
    - [link](https://github.com/eratiani/Online-zoo/tree/Online-zoo)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/online-zoo/online-zoo.md#week-4)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/online-zoo/online-zoo.md#week-4)
5. A screenshot of cross-checking marks
6. 
![image](https://user-images.githubusercontent.com/62502052/209141887-02a3e765-85df-49a1-ad22-893c46293d19.png)
![image](https://user-images.githubusercontent.com/62502052/209141945-958826ad-46d8-41bf-8697-48b71605bd92.png)

7. A final score after self-assessment, with comments
95 or 100 depending how u understand that one requirement 

8. A cross-check score of your Score 
78.
Please punish those that evaluate on last second and do bad job at it. Thank god this is last task with student evaluators

**Comment by HopelessJu** [comment]
![image](https://user-images.githubusercontent.com/106112358/209139196-a1ca0118-2353-4294-bfd5-f72efad61ca4.png)

Reviewers' contacts are not hidden.

**Comment by eratiani** [comment]
ohh sorry forgot about that can i resubmit screens?

**Comment by eratiani** [comment]
> ![image](https://user-images.githubusercontent.com/106112358/209139196-a1ca0118-2353-4294-bfd5-f72efad61ca4.png)
> 
> Reviewers' contacts are not hidden.

sorry forgot about that rule i resubmitted screens

**Comment by HopelessJu** [comment]
#### Criteria that were not met: 
***Landing***
- `There is no animation or the animation time is 0: -10 . Its appearance is a smooth flipping of the image from right to left, or from left to right. In this case, the animation speed is not regulated, but it must be non-zero. ❗For the lack of animation on smaller screen sizes, we do not take points again!` - The animation's appearance is not flipping of the image from left to right and from right to left. There also is no difference in animation when clicking the right and left buttons.  **-5**

***Donate***
- `At the start of the page display, the number 100 should be entered, and the corresponding element (3rd from the right) should be highlighted. If not: -5 .` **-5**
- ----

![image](https://user-images.githubusercontent.com/106112358/209178406-8d9c5004-60ad-4ef9-942a-f2e4619e66b1.png)

▲ these criteria were not met, though there is no any points deduction for that.

***Ps.*** *The animation of the arrows on buttons in the pet slider works only when you alternate right and left buttons, if you click on the same one multiple times - the animation works only once. It's, of course, outside of the evaluation criteria, Just noticed :)*

----
***Total Score:*** **90/100** 
#### ***Good job!***

**Comment by HopelessJu** [comment]
@Anik188 review complited

**Comment by pavelrazuvalau** [comment]
@HopelessJu Thank you so much. Updated the final score and closing the issue
