### ISSUE TITLE
Cross-Check "CV#3. CV. Cross-Check" - denis-dev1

### ISSUE THREAD

**Issue by Denis-dev1** [rolling-scopes-school/support#819]
1. A link to your deployed project
    - [Link](https://denis-dev1.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [Link](https://github.com/Denis-dev1/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
 - do not exist
6. A final score after self-assessment, with comments
**Ваша оценка - 120 баллов** 
> Отзыв по пунктам ТЗ:
> Не выполненные/не засчитанные пункты:
> 1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 
> 
> Выполненные пункты:
> 1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 
> 
> 2) header, main, footer 
> 
> 3) элемент nav 
> 
> 4) только один заголовок h1 
> 
> 5) заголовки h2 
> 
> 6) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 
> 
> 7) для оформления СV используются css-стили 
> 
> 8) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 
> 
> 9) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 
> 
> 10) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 
> 
> 11) краткую информацию о себе 
> 
> 12) контакты для связи 
> 
> 13) перечень навыков 
> 
> 14) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 
> 
> 15) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 
> 
> 16) информацию об образовании и уровне английского 
> 
> 17) CV выполнено на английском языке 

7. A cross-check score of your Score 
- do not exist

Yes I've done this task a while ago, but haven't submitted the solution( You should be able to see that **last changes were made 5 days ago**...
If that is possible to have my task checked it would be great. Otherwise, it's my fault and thanks anyway. 😭

**Comment by Denis-dev1** [comment]
That is me sad waiting for you to help me and let me get this 60 points added to my score and be finally happy Lol

![image](https://user-images.githubusercontent.com/60603557/208481130-02ddb4a3-39f1-4c42-9db3-d9ef63ea7dc4.png)

**Comment by lyutails** [comment]
puppy is pretty of course :)
but if task wasn't submitted in time
for that was given a week
![image](https://user-images.githubusercontent.com/101958335/217057426-9dc8af3c-596a-48d7-beb4-0dc613b07e21.png)
there is only one reason for such cases, from what i know, to be rechecked - if you were in a hospital when deadline happened and have medical confirmation from there

**Comment by Luffi2539** [comment]
Forgot to submit is not a valid reason for review :( Please next time be more punctual
