### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross Check' - 'hrom19'.

### ISSUE THREAD

**Issue by hrom19** [rolling-scopes-school/support#820]
1. A link to your deployed project
    - https://hrom19.github.io/rsschool-cv/
2. A link to the project repository on Github.
    - https://github.com/hrom19/rsschool-cv
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. A Link to the checklist for evaluating the task (if it exists)
    - https://rolling-scopes-school.github.io/checklist/
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/119871614/208797535-2864f241-282b-42b2-910e-484e45fc92a5.png)
6. A final score after self-assessment, with comments
Total points: 115 
1. Работоспособность меню навигации на данном этапе не проверяется, а проверяется сам факт его наличия (элемента nav) в верстке и оформления навигации в виде списка lu>li>a.
2. При уменьшении масштаба страницы браузера вёрстка размещается, а не сдвигается в сторону
7. A cross-check score of your Score 
пока в Score нет оценки

**Comment by hrom19** [comment]
Навигационное меню по факту присутствует и оформлено в виде списка по форме lu-li-a
При уменьшении масштаба страницы браузера вёрстка размещается по центру, а не сдвигается в сторону

**Comment by Denis-dev1** [comment]
В помощь активистам😁: 
при проверке получилось 110 баллов.

автор прав по поводу навигации и размещения верстки при изменении масштаба:
 - навигация есть, а работоспособность не проверяется;
 - верстка остается по центру при уменьшении масштаба;

> Отзыв по пунктам ТЗ:
> * Не выполненные/не засчитанные пункты:
> 1) Есть вопросы по валидности верстки - присутствуют ошибки;
> 2) на странице более одного заголовка h1
> 
> * Частично выполненные пункты:
> 
> 1) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения
> Отзыв: нет ссылок на исходный код или страницу приложения.
> 
> 2) информацию об образовании и уровне английского
> Отзыв: есть инфа только по пройденным курсам, не уверен можно ли это считать о образовании; нет информации об уровне английского

По остальному ОК.

Для автора issue:
возможно финальная оценка вашей работы вас более чем устроит и актуальность данного issue пропадёт. 
Скорее всего стоило дождаться окончания всех проверок вашей работы _(из требований к подаче аппеляции)_ , в любом случае удачи в дальнейшем. ☺️

**Comment by hrom19** [comment]
Благодарю за помощь

**Comment by lyutails** [comment]
hey there o/

max score for this task is 120
you got 113
![image](https://user-images.githubusercontent.com/101958335/217059303-73bd4142-90c6-4737-b947-c70add1d9a0b.png)

difference in score should be >= 10% for appeal to happen
from here it doens't fit one of the requirements

**Comment by Luffi2539** [comment]
@lyutails agreed. No need for appeal
