### ISSUE TITLE
Cross-Check 'CV#3. CV. Cross-Check' - 'andreidrugomilov'

### ISSUE THREAD

**Issue by andreidrugomilov** [rolling-scopes-school/support#821]
Добрый день!
Обращаюсь к вам с просьбой принять мою работу после окончания срока подачи. Не знал, что можно обратиться с такой просьбой, но вчера на лекции Q&A sessions от вас услышал, что вы можете войти в положение.
Я не успел податься в срок, т.к. прошлая неделя была очень загруженной по моей основной работе, также у меня есть семья и ребёнок, учусь в основном вечером и ночью, и на прошлой неделе надо было уехать в командировку в Вильнюс, рассчитывал делать задание в выходные, но нам очень не повезло с границей, дорога назад заняла 11 часов.  По приезду я занялся моим CV, но, к сожалению, не успел.
На самом деле очень хочется научиться, но немного не хватает времени, и немного обидно смотреть на 0, т.к. это совсем не отражает моего желания учиться.
В любом случае, спасибо!

1. A link to your deployed project
    - [[link](https://github.com/)](https://andreidrugomilov.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [[link](https://github.com/)](https://github.com/andreidrugomilov/rsschool-cv)
3. A link to the task
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md)
4. (https://rolling-scopes-school.github.io/checklist/)
5.  скриншот отсутствует, т.к. вовремя не сдал CV
6. 120
7. 0

**Comment by Luffi2539** [comment]
Добрый день, сабмит задания открыт в момент его выдачи, то есть на сабмит ссылки (около 3 минут времени дается примерно 10 дней) и к сожалению это не является причиной для аппеляции
