### ISSUE TITLE
Апелляция со Stage0 перекрестной проверки на CV

### ISSUE THREAD

**Issue by ptk13074** [rolling-scopes-school/support#822]
1. A link to your deployed project
    [- [link](https://github.com/)](https://ptk13074.github.io/rsschool-cv/cv)
2. A link to the project repository on Github.
    [- [link](https://github.com/)](https://github.com/ptk13074?tab=repositories)
3. A link to the task
    [- [link](https://github.com/)](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md)
4. A Link to the checklist for evaluating the task (if it exists)
    
5. A screenshot of cross-checking marks
![qwe](https://user-images.githubusercontent.com/116688598/209256192-c090917d-c3ad-41b1-b550-07de717bb7f9.png)
![qwert](https://user-images.githubusercontent.com/116688598/209256196-baa99f00-19ea-45f6-b046-94d234fffd90.png)
![qwer](https://user-images.githubusercontent.com/116688598/209256197-e1b8fed3-6f50-4023-acaf-60d6045170a9.png)
6. A final score after self-assessment, with comments
Доброго времени суток! Я знаю, что оценки за нулевой этап особой роли не играют. Просто хочу посмотреть как работает апелляция, т.к. с оценкой в 20 баллов одного из проверяющих не согласен. На мой взгляд, результат можно оценить ну баллов в 100 в крайнем случае, если придираться к навигации в хедаре с белым цветом и отсутствием блока про доп проекты, если они есть и блок про образование. Ну может еще что то есть... Но не 20 балов же =)
7. A cross-check score of your Score 
87 баллов

**Comment by lyutails** [comment]
hey there o/

1. link is submitted to rsapp deployed on gh-pages +10
2. layout is valid +10
3. semantic
- header, main, footer +5
- nav +5
- h1 +5
- h2 +5
4. there are author's github, year of creating, school's logo in footer +10
5. used css for styling +10
6. layout stays in the middle of the page when size / width is decreased +10
7. ava + alt attribute +10
8. lists and nav follow structure ul > li или ul > li > a +10
9. CV contains
- short info about author +5
- contacts +5
- skillset +5
- code, added with tags +5
- **no done projects mentioned** +0
- info about finished courses and language level +5
10. CV is created in english +10
yeah worth changing white colour for nav items to somewhat more visible :)

to avoid misunderstandings during cross-check - we subtract from 130, then result is 130 - 5, though maximum score for the task is 120

**Final score: 120**

@helenakrasnova
check please
@Luffi2539
check please

**Comment by valerydluski** [comment]
invalid issue name
