### ISSUE TITLE
Cross-Check "CV#3. CV. Cross-Check" - tanchick007

### ISSUE THREAD

**Issue by tanchick007** [rolling-scopes-school/support#823]
1. A link to your deployed project
    - [link](https://tanchick007.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/tanchick007/rsschool-cv)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/77984316/209302894-9b1e897e-926b-4ba5-a155-24db8dd5deae.png)
![image](https://user-images.githubusercontent.com/77984316/209302932-ee975d00-d986-4998-80c6-a51f54fa873c.png)
6. A final score after self-assessment, with comments
Как видно из скриншотов, последний человек расписал всё по пунктам, но из-за невнимательности не указал количество баллов для оценки, из-за чего в финальном подсчёте я потеряла 20 баллов(итоговая оценка 40 из 60 баллов).

Ваша оценка - 125 баллов 
Отзыв по пунктам ТЗ:
Частично выполненные пункты:
1) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 
Отзыв: Неверна указана ссылка на курс.

Выполненные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) для оформления СV используются css-стили 

8) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

9) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

10) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a 

11) краткую информацию о себе 

12) контакты для связи 

13) перечень навыков 

14) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

15) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

16) информацию об образовании и уровне английского 

17) CV выполнено на английском языке 

7. A cross-check score of your Score 
80

**Comment by lyutails** [comment]
hey there o/

1. link is submitted to rsapp deployed on gh-pages +10
2. layout is valid +10
3. semantic
- header, main, footer +5
- nav +5
- h1 +5
- h2 +5
4. there are author's github, year of creating, school's logo in footer +10
5. used css for styling +10
6. layout stays in the middle of the page when size / width is decreased +10
7. ava + alt attribute +10
8. lists and nav follow structure ul > li или ul > li > a +10
9. CV contains
- short info about author +5
- contacts +5
- skillset +5
- code, added with tags +5
- done projects mentioned +5
- info about finished courses and language level +5
10. CV is created in english +10

to avoid misunderstandings during cross-check - we subtract from 130, then result is 130 - 0, though maximum score for the task is 120

**Final score: 120**

@helenakrasnova
check please
@Luffi2539
check please

**Comment by valerydluski** [comment]
score updated
