### ISSUE TITLE
Cross-Check CV#3. CV. Cross-Check - 'varchoon'.

### ISSUE THREAD

**Issue by varchoon** [rolling-scopes-school/support#824]
1. A link to your deployed project
    https://varchoon.github.io/rsschool-cv/
2. A link to the project repository on Github.
    https://github.com/varchoon/rsschool-cv
3. A link to the task
    https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md
4. A Link to the checklist for evaluating the task (if it exists)
    https://rolling-scopes-school.github.io/checklist/
5. A screenshot of cross-checking marks
    ![image](https://user-images.githubusercontent.com/115428436/209338433-07844643-ada4-4d6d-aa97-2100a6814d69.png)
    ![image](https://user-images.githubusercontent.com/115428436/209338533-2fe5270a-6550-424d-b36a-b96e839c34ef.png)
6. A final score after self-assessment, with comments
    120. Becouse all done accordin to the task.
7. A cross-check score of your Score 
    59

**Comment by lyutails** [comment]
hey there o/

your final score for this task is 118 (maximum 120)![image](https://user-images.githubusercontent.com/101958335/218111637-dc5c93c1-69d0-4698-bf5c-5ad2a5225cd3.png)
![image](https://user-images.githubusercontent.com/101958335/218113289-7a3df88e-0efe-479a-adec-df3ce57deb9c.png)

one of the criteria for appeal to happen - difference from maximum score to be 10%, therefore appeal cannot be performed

i assume you were checked by 4 reviewers, three of whom rated you quite high (as you got 118), and one forgot to change 0

59 is correct score - coefficient for this task is 0.5 (118 / 2)

@Luffi2539
check please

**Comment by valerydluski** [comment]
@lyutails thank you
