### ISSUE TITLE
 CV#3.Cross-Check

### ISSUE THREAD

**Issue by Sollar2022** [rolling-scopes-school/support#825]
1. A link to your deployed project
    [- [link](https://storied-youtiao-94d483.netlify.app/)
2. A link to the project repository on Github.
    - [link](https://github.com/Sollar2022/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link]( https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks

![Снимок экрана (392)](https://user-images.githubusercontent.com/119854761/209463231-b525f9d7-9814-4b5a-883f-dbe995ea24d1.png)
![Снимок экрана (393)](https://user-images.githubusercontent.com/119854761/209463244-8284723e-8de7-46c0-ab42-b616cc01d1cf.png)

7. A final score after self-assessment, with comments
Единственное, что было не выполнено, так это - задеплоить сайт на gh-pages. Это по методике минус 10 очков.
Он был задеплоин на: Netlify/ Ссылка при  merge указана.
Остальное проверяется при анализе кода: валидация, ссылки, сжимаемость и центрирование страницы при уменьшении масштаба и остальные пункты задания.

9. A cross-check score of your Score : 
Моя оценка 110 баллов, а не 0 и 80 как дали проверяющие

**Comment by lyutails** [comment]
hey there o/

1. link is submitted to rsapp, but **deployed not on gh-pages** (max 10) +5
2. layout is valid +10
3. semantic
- header, main, footer +5
- nav +5
- h1 +5
- h2 +5
4. there are author's github, year of creating, school's logo in footer +10
5. used css for styling +10
6. layout stays in the middle of the page when size / width is decreased +10
7. ava + alt attribute +10
8. lists and nav follow structure ul > li или ul > li > a +10
9. CV contains
- short info about author +5
- contacts +5
- skillset +5
- code, added with tags +5
- done projects mentioned +5
- info about finished courses and language level +5
10. CV is created in english +10

to avoid misunderstandings during cross-check - we subtract from 130, then result is 130 - 5, though maximum score for the task is 120

**Final score: 120**

@helenakrasnova
check please
@Luffi2539
check please

**Comment by valerydluski** [comment]
invalid issue name

**Comment by lyutails** [comment]
stage#0 is over
