### ISSUE TITLE
Cross-Check 'CV#3. CV' - 'JaneLane1704'

### ISSUE THREAD

**Issue by JaneLane1704** [rolling-scopes-school/support#826]
1. A link to your deployed project
    - [link](https://celebrated-pony-8c2f7d.netlify.app/)
2. A link to the project repository on Github.
    - [link](https://github.com/JaneLane1704/rsschool-cv.git)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md)
4. A Link to the checklist for evaluating the task (if it exists) -
    
5. A screenshot of cross-checking marks

![Снимок экрана (6)](https://user-images.githubusercontent.com/81980528/209529030-a9143ad2-9e8b-4738-97db-24f9ed800190.png)

6. A final score after self-assessment, with comments

    - [link](https://github.com/JaneLane1704/rsschool-cv/pull/3)

8. A cross-check score of your Score 

![Снимок экрана (7)](https://user-images.githubusercontent.com/81980528/209529540-9b92b3f9-4c4b-497c-8ca7-61069bc809db.png)

**Comment by lyutails** [comment]
hey there o/

1. link is submitted to rsapp, but **deployed not on gh-pages** (max 10) +5
2. **layout is not valid** (max 10) +0
![image](https://user-images.githubusercontent.com/101958335/218133631-29d813ac-e27e-4ab7-bad1-c0ebff15c460.png)
both errors and warnings are present
3. semantic
- header, main, footer +5
- nav +5
- h1 +5
- h2 +5
4. there are author's github, year of creating, school's logo in footer +10
5. used css for styling +10
6. **layout doesn't stay in the middle of the page when size / width is decreased** (max 10) +0
7. ava + alt attribute +10
8. lists and nav follow structure ul > li или ul > li > a +10
9. CV contains
- short info about author +5
- contacts +5
- skillset +5
- code, added with tags +5
- **done projects are not mentioned** +0
- info about finished courses and language level +5
10. CV is created in english +10

to avoid misunderstandings during cross-check - we subtract from 130, then result is 130 - 30, maximum score for the task is 120

**Final score: 100**

@helenakrasnova
check please
@Luffi2539
check please

**Comment by valerydluski** [comment]
score updated
