### ISSUE TITLE
Cross-Check 'File Manager' - 'Vanya1000'.

### ISSUE THREAD

**Issue by ivanzakharanka** [rolling-scopes-school/support#827]
1. A link to your deployed project
    - [link](https://github.com/Vanya1000/File-Manager/tree/develop)
2. A link to the project repository on Github.
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/score.md)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/25255889/209541134-d5640d4d-04fc-499d-bb8b-f099853d8195.png)

6. A final score after self-assessment, with comments
330 Here is the link to the self-test: - [link](https://github.com/Vanya1000/File-Manager/pull/1)

7. A cross-check score of your Score 316

**Comment by ThorsAngerVaNeT** [comment]
Expected score and obtained average score differ less than 10 percent.
