### ISSUE TITLE
Cross-check appeal for unresponsible checking

### ISSUE THREAD

**Issue by OnlyTryHard** [rolling-scopes-school/support#828]
1. A link to your deployed project
https://rolling-scopes-school.github.io/onlytryhard-JSFEPRESCHOOL2022Q4/Plants/
2. A link to the project repository on Github.
https://github.com/rolling-scopes-school/onlytryhard-JSFEPRESCHOOL2022Q4/tree/gh-pages
3. A link to the task
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md
4. A Link to the checklist for evaluating the task (if it exists)
https://rolling-scopes-school.github.io/checklist/
5. A screenshot of cross-checking marks
![photo_2023-01-10_10-36-12](https://user-images.githubusercontent.com/90132188/211594532-de6b6d03-9915-42fd-a5e8-4acce713da99.jpg)
![photo_2023-01-10_10-36-15](https://user-images.githubusercontent.com/90132188/211594541-ca2e20d6-1b84-4c70-a9f4-c3d2d458831d.jpg)
6. A final score after self-assessment, with comments
- Score has to be around 95-90 minimum.
- Even if my fonts are not 700 weight, the style is normal, thus if they are under 10px fitting requirement, that should be okey.
- CSS animations are preferable, not a must. I have all middle images with animations while person telling that "there is no animation with links in footer".
- Person is telling that my image in Contact Us are is not sticked to the footer, while 10px is allowed.
- Another guy telling that i failed PP totally, but i noted in Console, that i have screen wider then 1440, thus to check the PP correctly need to adjust PP by left top angle (or buy word PLANTS in the left top logo)
7. A cross-check score of your Score 
-Scores which they gave me are 78 and 84, what is not okey totally.

**Comment by turn2river** [comment]
Апелляция подаётся после дедлайна проверки, при соблюдении условий:
- После дедлайна не было коммитов
- Итоговая оценка отличается более чем на 10% от ожидаемой
- Оформление должно соответствовать шаблону (название неправильно)

**Comment by OnlyTryHard** [comment]
понял. Спасибо. Переделаю новую апелляцию после окончания кросс чека
