### ISSUE TITLE
Plants #1	Cross-Check: Submit

### ISSUE THREAD

**Issue by omcmail** [rolling-scopes-school/support#829]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/omcmail-JSFEPRESCHOOL2022Q4/plants/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/omcmail-JSFEPRESCHOOL2022Q4)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![plants1-pp](https://user-images.githubusercontent.com/116748219/211726551-389e4ab0-97ff-45ff-b96d-f67d4c257e82.png)
7. A final score after self-assessment, with comments: 100.
8. A cross-check score of your Score: 100.
9. Certificate of illness, was in the hospital from 12/23/2022 to 01/06/2023. I felt bad and couldn't do it.
![DSC_0205](https://user-images.githubusercontent.com/116748219/211727621-581dc3c1-c018-4e66-8ca5-d64f028f1174.JPG)

**Comment by Luffi2539** [comment]
Sorry, but submit was opened while you were not ill 
![image](https://user-images.githubusercontent.com/43149261/218057123-06289f58-2e83-4fce-8c25-969feb34a9a9.png)
