### ISSUE TITLE
Corejs 2022Q3

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/support#831]
Этот тред создан для решения проблем возникающих в процессе прохождения coreJS интервью.

Например:

Не могу связаться с ментором для прохождения coreJS , так как в его профиле не указаны контакты
Контакты есть, но ментор не отвечает более 3х дней
Ментор не может больше менторить

**Comment by liestreadt** [comment]
Добрый день. Мне назначили интервьюера на интервью CoreJS 1 и я написал ему ещё 4-го января, но до сих пор он даже не прочитал мои сообщения (ни в ТГ, ни в дискорде). Я даже написал СМС по номеру, который указан в его аккаунте RSS, но тоже никакой реакции. Также я попытался связаться с его студентами, но они тоже не отвечают. Подскажите пожалуйста, как мне пройти это обязательное интервью?  
Контакты интервьюера:  
- RSS: https://app.rs.school/profile?githubId=yuriiboltukov
- Telegram: YuriiBol
- Notes: +79667490502
- GitHub: [yuriiboltukov](https://github.com/yuriiboltukov)
- Discord: @kolomiha(YuriiBoltukov)#4088

**Comment by zhony94** [comment]
Не могу связаться с ментором для прохождения coreJS (ментор не отвечает более 3х дней)

RSS: https://app.rs.school/profile?githubId=dreameraleksey
Telegram: Dreamer_Al
GitHub: https://github.com/dreameraleksey
Discord: @Dreamer#5966

**Comment by D1van007** [comment]
Зарегистрировался на прохождение интервью coreJS, но до сих пор пустая колонка - нет никого для связи.
![Снимок экрана 2023-01-13 в 20 34 57](https://user-images.githubusercontent.com/106621724/212384728-ea6b9ac2-5ad6-47d0-82bf-450f1cbe76f7.png)
mail: aliaksandr.dzivin@gmail.com
GitHub: https://https://github.com/D1van007
Discord: @D1van#6876

**Comment by valerydluski** [comment]
@zhony94 буду искать тебе другого ментора

**Comment by valerydluski** [comment]
@D1van007 ты зарегистрировался после распределения. так что только если найдётся ментор доброволец провести интервью

**Comment by BrBrov** [comment]
Ментор не отвечает.
![image](https://user-images.githubusercontent.com/95406843/212487938-46cdf90b-0c56-4e5c-8787-37ad488f7619.png)
Писал в discord 05.01.2023
![image](https://user-images.githubusercontent.com/95406843/212487998-01a99a6e-a43b-4834-a116-9830e3a8d2f3.png)
Писал в телеграм 13.01.2023
![image](https://user-images.githubusercontent.com/95406843/212488157-4cd2a9f7-96cf-4315-b3d5-495a8d952ac5.png)
Ментор всёравно не отвечает, хотя в телеграме был недавно (написано сверху).
Что делать?

**Comment by DmitriyRim** [comment]
![image](https://user-images.githubusercontent.com/74590404/212556281-b9648b51-811f-404f-8417-165bf40a94a6.png)
Ментор не отвечает в discord и tg.

**Comment by Shemet21-art** [comment]
так и не пришло подтверждение по прохождению интервью 
  shemet21-art
ihor shemet
https://user-images.githubusercontent.com/61664799/212557233-ed07c74a-edc3-4485-b420-c2f913958d4b.png
shiv.engin@gmail.com
@ShemetIhor#8462

**Comment by AlexGorSer** [comment]
![изображение](https://user-images.githubusercontent.com/88935233/212560114-df9336e6-3b30-431d-bf14-24687d76dfa4.png)
ментор не ответил не в ТГ не в Дискорде

**Comment by CosmoBoyMe** [comment]
Не получается найти ментора через телеграмм и через discord
discrod: @CosmoboyMe#634
github: https://github.com/cosmoboyme
telegram: https://t.me/CosmoboyMe 

UPD: получилось связаться с ментором!

**Comment by DeguzBelarus** [comment]
Зарегистрировался на прохождение интервью несколько дней назад (coreJS), но до сих пор пустая колонка с интервьювером - нет никого для связи, ситуация аналогична с D1van007 (пост выше).

mail: [deguz@mail.ru](mailto:deguz@mail.ru)
GitHub: [https://github.com/DeguzBelarus](https://github.com/DeguzBelarus)
Discord: Deguz#3354

UPD: интервьювер нашёлся!

**Comment by valerydluski** [comment]
@zhony94 у тебя новый ментор для прохождения интервью

**Comment by valerydluski** [comment]
@BrBrov у тебя новый ментор для прохождения интервью

**Comment by vKuptsova** [comment]
Не могу связаться с ментором для прохождения coreJS (ментор не отвечает более 3х дней)

**Comment by omcmail** [comment]
Здравствуйте, письма пришли в рассылки - только увидел, я так понял все глухо. 16.01.2023, 22:39, "Valery" ***@***.***>***@***.*** у тебя новый ментор для прохождения интервью—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by GodPFM** [comment]
Здравствуйте, ментор перестал выходить на связь, хоть и читает все сообщения.
![image](https://user-images.githubusercontent.com/86543246/213993913-7f6100b1-9d37-4134-aee7-d8db8a2363f6.png)

**Comment by LetoCode** [comment]
Добрый день! 
Зарегистрировался на интервью.
![23 01](https://user-images.githubusercontent.com/92261662/214020857-da3efd7e-7003-43d6-9650-74bff7b45751.png)


Но до сих пор не назначен ментор.

В Дискорде сказали, что меня даже в wait-листе нет.

RSS: https://app.rs.school/profile?githubId=letocode
Telegram: https://t.me/PavlovEghor
GitHub: https://github.com/LetoCode
Discord: Egor_#1806

**Comment by sesychev** [comment]
Привет!
Зарегистрировался 03.01.2023, но судя по всему поздно
![image](https://user-images.githubusercontent.com/81991201/214145600-eb2b4cad-6f78-4bb9-a3b7-2f00a052ee59.png)
Github: https://github.com/sesychev
Discord: Mint#2531

**Comment by valerydluski** [comment]
@vKuptsova у тебя новый ментор

**Comment by valerydluski** [comment]
@LetoCode у тебя появился ментор для прохождения интервью

**Comment by LetoCode** [comment]
Спасибо!

**Comment by wowblvck** [comment]
Связывался с ментором 5 января и определились, что интервью будет после 20 января (с 23 по 27). 24 января спросил о возможности провести интервью 27 января. Пока что ответа нет (у сообщений статус "не прочитан", но и 3 дня не прошло (переживаю, что 31 января близко и могу не успеть пройти). Для связи используется один канал - телеграм (@agentumbrella). Не настаиваю на смене ментора для интервью, но может случилось что-то.

**Comment by fedormalinin** [comment]
Ментор сообщил, что не может принять у меня интервью и сказал, что передаст другому
В данный момент нет ментора для corejs интервью

**Comment by AlexGorSer** [comment]
![изображение](https://user-images.githubusercontent.com/88935233/215284670-8a95e641-f3ee-410a-95b9-b185631db9df.png)
опять пропал ментор, хотел договориться на 29 число, написал 27 так и не ответил

**Comment by AlexGorSer** [comment]
Ментор написал что может не получиться принять интервью  
![изображение](https://user-images.githubusercontent.com/88935233/215469017-28a57122-7339-4844-890c-ecb6b500351e.png)

**Comment by AndreiArtsiomenko** [comment]
Здравствуйте, ментор написал, что скорее всего не сможет провести интервью. 
![IMG_20230208_094959](https://user-images.githubusercontent.com/75216038/217455765-9580f5ee-921b-41e1-94b9-fcf1670d3d2c.jpg)

**Comment by ViktoriaKondrashova1** [comment]
Добрый день, ментор написал, что не сможет провести интервью.
![2023-02-08_115647](https://user-images.githubusercontent.com/106308348/217482332-a78ae8ae-84da-45d9-a07b-4a22c1732b7d.jpg)

**Comment by valerydluski** [comment]
@ViktoriaKondrashova1 у тебя новый ментор

**Comment by valerydluski** [comment]
@AndreiArtsiomenko у тебя новый ментор для интервью

**Comment by AndreiArtsiomenko** [comment]
Спасибо

**Comment by elukashova** [comment]
Добрый вечер! К сожалению, ментор, к которому меня распределили для corejs 2, сказал, что вряд ли сможет его провести, и что лучше найти другого.
Спасибо!
<img width="577" alt="Screenshot 2023-02-09 alle 14 34 33" src="https://user-images.githubusercontent.com/102854917/217827132-5c234a07-0b84-4316-b56d-a01f4aab561b.png">

**Comment by h1stil** [comment]
Добрый вечер, столкнулся с такой проблемой. Я студент из России, ментор - из Украины. Ментор не проводит интервью со студентами из России.
Discord: i_kavyev#9470

**Comment by Elijah-I** [comment]
Не могу связаться с ментором для прохождения coreJS (ментор не отвечает более 3х дней)

RSS: https://app.rs.school/profile?githubId=sharovskiye
Discord: @Yevhenii#5335

**Comment by Luferov1** [comment]
Не могу связаться с ментором для прохождения coreJS (ментор не отвечает более 3х дней). Ментор прочитал сообщения на второй день, но не отвечает
RSS: https://app.rs.school/profile?githubId=alexey221284
TG: AlexeyZhumaev

**Comment by jewelhux** [comment]
Не могу связаться с ментором для прохождения coreJS (ментор не отвечает более 3х дней)
yuriiboltukov

**Comment by Nimboo1** [comment]
Добрый вечер.
Связался с ментором, он сказал, что скорее всего не сможет провести интервью и спросил, можно ли дать мне другого интервьюера.
![image](https://user-images.githubusercontent.com/43417650/218123803-f856c6d9-1779-4f83-a100-3a2985477874.png)

**Comment by qwertytr1** [comment]
Здравствуйте, ментор не отвечает более 3 дней 
![Screenshot_20230211-124059_Chrome](https://user-images.githubusercontent.com/105173209/218251387-7fe03745-b0af-4575-9437-0d1eb0c75b54.jpg)

**Comment by RallyZK** [comment]
Здравствуйте,  прошу назначить мне другого ментора для прохождения интервью Core JS 2, т.к. ментор, попавшийся по распределению,  не проводит интервью со студентами из России.

Контакты ментора:
Telegram: buiiz
@buii#9250

**Comment by rusland251** [comment]
Здравствуйте.не могу связаться с ментором более 3-х дней


Контакты ментора:
Telegram: igoradev
@AI#2787

**Comment by Angelica-zb** [comment]
Не могу связаться с ментором для прохождения coreJS  (ментор не отвечает более 3х дней)
![image](https://user-images.githubusercontent.com/99465949/218468328-8a3a50ac-8360-4c9e-9f3a-7139c081ebdd.png)

**Comment by Morsul** [comment]
не получилось выйти на свзяь с ментором для прохождения coreJS 2, связался с его студентами, один сказал что уже недели 2 его не видел.
контакты интервьювера
![image](https://user-images.githubusercontent.com/81906186/218435559-5057510b-067b-480e-aac6-bbd0eae48f40.png)

**Comment by ivan52945** [comment]
не могу связаться с ментором
вот его данные:
![image](https://user-images.githubusercontent.com/33607454/218449593-b3c4b47c-05dc-4c3b-b8aa-9c528bd920c5.png)
писал ему в ДС и скайпе

**Comment by Cibulya** [comment]
Добрый день! Ментор к которому распределило на интервью не отвечает с 7 февраля.
![0021C5D9-6A1F-468A-B803-E886D94FA5D9](https://user-images.githubusercontent.com/108197413/218457499-3f19166e-fc49-4e21-8299-cad68a1f7270.jpeg)

**Comment by nike93** [comment]
![image](https://user-images.githubusercontent.com/78583165/218457913-3763990e-14c3-41e0-8094-de183b1fadbd.png)
Здравствуйте! Ментор не выходит на связь более 3-х дней. Его студенты общаются с ним по телеграму, но там он молчит. Также пытался связаться через Discrord, mail и VK, везде тихо

**Comment by natein** [comment]
> Cibulya

Свяжись с ментором в телеграме, он быстро отвечает.

**Comment by natein** [comment]
> Не могу связаться с ментором для прохождения coreJS (ментор не отвечает более 3х дней). Ментор прочитал сообщения на второй день, но не отвечает RSS: https://app.rs.school/profile?githubId=alexey221284 TG: AlexeyZhumaev

@Luferov1 Обещал провести интервью. Свяжись с ним в телеграме.

**Comment by valerydluski** [comment]
@RallyZK у тебя новый ментор для интервью

**Comment by natein** [comment]
> Не могу связаться с ментором для прохождения coreJS (ментор не отвечает более 3х дней)

@Elijah-I Ментор отвечает в телеграме

**Comment by natein** [comment]
> К сожалению, ментор, к которому меня распределили для corejs 2, сказал, что вряд ли сможет его провести, и что лучше найти другого.

@elukashova Ментор пообещал провести интервью до 2023-03-06. Свяжись с ним.

**Comment by natein** [comment]
> не получилось выйти на свзяь с ментором для прохождения coreJS 2, связался с его студентами, один сказал что уже недели 2 его не видел.

@Morsul Пиши ментору в телеграм, он там быстро отвечает.

**Comment by Morsul** [comment]
> > не получилось выйти на свзяь с ментором для прохождения coreJS 2, связался с его студентами, один сказал что уже недели 2 его не видел.
> 
> @Morsul Пиши ментору в телеграм, он там быстро отвечает.

![image](https://user-images.githubusercontent.com/81906186/218491658-4fc5381c-104a-4bc9-944f-d6fc512ac4a4.png)
ну если это он, сейчас попробуем )

**Comment by natein** [comment]
@nike93 и @qwertytr1 Ментор сказал, что проведёт вам интервью. Свяжитесь с ним в телеграме.

**Comment by AnastasiaSyt** [comment]
Не получается связаться с ментором(
![image 1](https://user-images.githubusercontent.com/105282492/218513278-3823ba97-3438-4d74-966d-0663c0bb21e8.jpg)

Писала в дискорд, скайп и писала на почту.

**Comment by valerydluski** [comment]
@h1stil @Jik789 @Nimboo1 у вас новые ментора на интервью

**Comment by valerydluski** [comment]
@rusland420 @Angelica-zb у вас новый ментор для интервью

**Comment by Siaw4ik** [comment]
Здравствуйте, не получилось выйти на свзязь с интервьюером для прохождения coreJS 2, написал ему 11 числа в телегу(дискорда нет) - ответа нет... Zhan Zhuridov
 (https://github.com/inikonzs)

**Comment by Veronchi** [comment]
Здравствуйте, не смогла связаться с ментором([alyanoyigor](https://github.com/alyanoyigor)). В дискорде его почему-то нет, в телеграме не отвечает

**Comment by Veronchi** [comment]
> Здравствуйте, не смогла связаться с ментором([alyanoyigor](https://github.com/alyanoyigor)). В дискорде его почему-то нет, в телеграме не отвечает

Ментор ответил, что не сможет провести интервью. Сказал, что о нём знают

**Comment by helenakrasnova** [comment]
@Veronchi у тебя новый ментор для интервью

**Comment by Nebesnaya94** [comment]
Здравствуйте. Я не получила ментора для coreJS2. Распределите пожалуйста.

**Comment by helenakrasnova** [comment]
@Siaw4ik ментор отписал что вышел на связь

**Comment by helenakrasnova** [comment]
@Angelica-zb @Nebesnaya94 назначены новые ментора

**Comment by wowblvck** [comment]
Договорились с ментором провести интервью, но, к сожалению, из-за большой нагрузки, у неё не получается. Мой ментор (telegram @agentumbrella).

**Comment by vberezhnykh** [comment]
Добрый день!
Назначенный для прохождения интервью ментор сказала, что не сможет провести интервью. 
Что можно с этим сделать?
Спасибо!

**Comment by yal0** [comment]
Добрый день! Ментор не сможет провести со мной интервью из-за большой загрузки на работе. Можно назначить другого проверяющего?

**Comment by helenakrasnova** [comment]
@vberezhnykh у тебя новый ментор

**Comment by helenakrasnova** [comment]
@wowblvck 
@yal0
у вас новый ментор

**Comment by helenakrasnova** [comment]
@wowblvck
@yal0
у вас новый ментор

**Comment by KuniLee** [comment]
Здравствуйте,  [ментор](https://app.rs.school/profile?githubId=cooler2012) написал что не может провести интервью по состоянию здоровья, можно ли назначить мне другого?

**Comment by helenakrasnova** [comment]
@KuniLee у тебя новый ментор на интервью

**Comment by AntonSkalaban** [comment]
Здравствуйте, не распределило на интервью, в чем может быть причина
![DD484CC1-4EB6-44B7-8D6F-FBF2BE649073](https://user-images.githubusercontent.com/112729189/221273907-83720338-115d-44df-80bb-ce230aaf992c.png)

**Comment by Kavume** [comment]
Добрый день! 
Ментор (github dastan95kg) перенес день сдачи интервью из-за того, что приболел по его словам.
24 числа должно было быть интервью, но человек нигде не выходит на связь (возможно по той самой причине болезни)


В итоге ответил, что НЕ может провести интервью до 6го числа. Что делать в этой ситуации?

**Comment by DaniyarKulov** [comment]
Я договорился с ментором на 25 или 26 число провести интервью, в пятницу ему написал для уточнения даты и времени, но он так и не ответил. Хотелось бы желательно провести 26 числа, т.к потом у меня не будет времени.
p.s ответил сказал что он в отпуске и не сможет провести.
p.s Договорился с другим ментором его github qeteq.

**Comment by valerydluski** [comment]
@Kavume создал новую пару для интервью

**Comment by AlexGorSer** [comment]
![изображение](https://user-images.githubusercontent.com/88935233/221677756-7456a968-7dcf-4aa2-88c0-b04b593ada70.png)
Ментор уехал, не смог принять интервью
