### ISSUE TITLE
Cross-Check 'Plants#1 - Фиксированная вёрстка' - 'katriniti'.

### ISSUE THREAD

**Issue by katriniti** [rolling-scopes-school/support#832]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/katriniti-JSFEPRESCHOOL2022Q4/plants/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/katriniti-JSFEPRESCHOOL2022Q4)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![scores-plants#1](https://user-images.githubusercontent.com/117212861/211913475-f0d377e5-bcb5-4d64-a08b-1e225860e212.png)
6. A final score after self-assessment, with comments: В результате самопроверки получено 110 баллов. Все критерии соблюдены.
7. A cross-check score of your Score: оценка за CrossCheck Plants#1 еще не выставлена

**Comment by lyutails** [comment]
katriniti получила за кроссчек Плантсов первых 100 баллов - максимум (для проведения апелляции нужна разница >=10%)
форма жалоб https://docs.google.com/forms/d/e/1FAIpQLSc9su27qv3CzpkWQNRP2RsHCgjw0NFsmRT0fQgHA3ccN08vwA/viewform

**Comment by katriniti** [comment]
Всем спасибо!
