### ISSUE TITLE
Cross-Check Plants#1

### ISSUE THREAD

**Issue by IlyasPcn** [rolling-scopes-school/support#834]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/ilyaspcn-JSFEPRESCHOOL2022Q4/plants/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/ilyaspcn-JSFEPRESCHOOL2022Q4/tree/plants/plants)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks

<img width="1722" alt="Screenshot 2023-01-13 at 12 05 04" src="https://user-images.githubusercontent.com/113451196/212214474-57d55bde-ecd9-40c8-9132-f87946c45ceb.png">

7. A final score after self-assessment, with comments -100/100 моя верстка ( за которую мне неизвестный поставил 13 из 48) полностью удовлетворяет требованиям ТЗ. Если не можете исправить баллы, то хотя бы накажите проверяющего, чтобы он не портил учебу другим студентам.

8. A cross-check score of your Score - 92/100

**Comment by lyutails** [comment]
IlyasPcn получил за таск 92 - недостаточная разница от максимального балла для проведения апелляции
