### ISSUE TITLE
Cross-Check 'Plants#1. Фиксированная вёрстка' - tatiana-kasiyanik

### ISSUE THREAD

**Issue by tatiana-kasiyanik** [rolling-scopes-school/support#835]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/tatiana-kasiyanik-JSFEPRESCHOOL2022Q4/plants/)
  
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/tatiana-kasiyanik-JSFEPRESCHOOL2022Q4/tree/plants)
   
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md)
   
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
  
5. A screenshot of cross-checking marks
 ![image](https://user-images.githubusercontent.com/114995299/212215612-2fdd96ef-1bab-4ec3-b362-dbc24eb9f37b.png)
 ![image](https://user-images.githubusercontent.com/114995299/212216245-714c8718-8b1f-4bf8-9e20-f16cc1bd8c9f.png)
 ![image](https://user-images.githubusercontent.com/114995299/212217755-72c28f69-f584-4427-a8e5-1f38704a62aa.png)
 ![image](https://user-images.githubusercontent.com/114995299/212217766-de5cf591-bc7b-41c3-8777-43862ffdc801.png)

6. A final score after self-assessment, with comments: 100 
Вёрстка валидная 10/10
Вёрстка семантическая 18.5/20
(Частично выполненные пункты: два списка ul > li > a (панель навигации, ссылки на соцсети)
Отзыв: Список присутствует только в навигации.  -1,5 балла)
Вёрстка соответствует макету 48/48
Требования к css 12/12
Интерактивность, реализуемая через css 20/20
108.5/110 (max 100)
Считаю, что оба проверяющих занизили оценку по пункту «Верстка соответствует макету», 
поскольку отклонения верстки от макета не составляют более 10px, что допустимо. Просьбы 
о пересмотре работы по данному критерию были проигнорированы.

8. A cross-check score of your Score: 87

**Comment by lyutails** [comment]
hey there o/

good job

1. Valid layout 
- no errors or / and warnings +10
2. Semantic layout
- header, main, footer +3
- five sections +3
- one h1 +3
- four h2 +3
- one nav that is in navigation +3
-  should be two ul > li > a in nav panel and **for social media links - in your case created with spans** (max 3) +2
![image](https://user-images.githubusercontent.com/101958335/218278772-d853007f-236a-4c12-8048-2dbd25f04f50.png)
- five buttons +2
3. Layout follows design... yeah closely to being perfect in all the sections
- in header +6
- in welcome section +7
- about section +7
- service section +7
- prices section +7
- contacts +7
- footer +7
![image](https://user-images.githubusercontent.com/101958335/218320585-10756e06-010d-4fbe-94f3-1a18f584afa0.png)
4. CSS
- flex is used +2
- when decreasing width layout stays in the middle of the page +2
- background color covers whole screen's width for sections +2
- icons are added as .svg +2
- pics are added in .jpg / .png format +2
- site does have favicon +2
5. Interactivity
- smooth scrolling from anchor to anchor +5
- links in footer leads to author's github and rsschool +5
- buttons change color smoothly on hover and nav menus +5
- interactive changes for one element doesn't affect neighbour elements +5

final score for this task is 100, though to remove misunderstandings we subtract from 110
110 - 1 = 109

**Final score: 100**

@helenakrasnova
check please
@Luffi2539
check please

**Comment by valerydluski** [comment]
task points updated
