### ISSUE TITLE
Cross-Check 'Plants#1 - Фиксированная вёрстка' - 'andrplko'

### ISSUE THREAD

**Issue by andrplko** [rolling-scopes-school/support#836]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/andrplko-JSFEPRESCHOOL2022Q4/plants/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/andrplko-JSFEPRESCHOOL2022Q4/tree/gh-pages/plants)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![](https://user-images.githubusercontent.com/118306084/212228764-ccaebb5f-5f71-4d6d-94a2-5896922322b2.png)
6. A final score after self-assessment, with comments
Считаю, что мною выполнены все пункты критериев оценки и моя работа может получить максимальный балл, а именно 110 баллов. Один из проверяющих, расписал по пунктам выполненные критерии оценки, но забыл указать правильный балл в поле и из-за этого его оценка моей работы равна нулю. Второй проверяющий сначала оценил работы в 0 баллов, подумав о том, что на данном этапе нужно выполнить все три части задания plants. Позже прочитав мой комментарий, исправил на неправильную оценку равную 90 баллов, написав какое-то выдуманное несоответствие одному из пунктов критерия оценки. Пожалуйста, пойдите мне навстречу, потому я оч сильно старался, несмотря на то, что у меня такой балл в score.
7. A cross-check score of your Score: 97/100

**Comment by lyutails** [comment]
andrplko получил 97 за кросс-чек что недостаточно мало от максимального балла для проведения апелляции
подал жалобу на проверяющего за неадекватную оценку
