### ISSUE TITLE
Cross-Check 'Plants #1 ' - 'Oleksandr-Orzul'.

### ISSUE THREAD

**Issue by Oleksandr-Orzul** [rolling-scopes-school/support#837]
1. A link to your deployed project
    - [link]( https://oleksandr-orzul.github.io/rsschool-cv/plants/)
2. A link to the project repository on Github.
    - [link](https://github.com/Oleksandr-Orzul/rsschool-cv/tree/gh-pages/plants)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](-)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/120033424/212268520-ea56ec02-e04d-4700-8988-f8685af1ffc2.png)
![image](https://user-images.githubusercontent.com/120033424/212268764-71105264-a95a-4baa-b4c7-9baa8cf1e14e.png)
![image](https://user-images.githubusercontent.com/120033424/212268826-a511fb88-432c-4472-afa9-e6a0b0ca50df.png)

6. A final score after self-assessment, with comments
 Вёрстка валидная 10/10
Вёрстка семантическая 20/20
Вёрстка соответствует макету 48/48
Требования к css 10/12
Интерактивность, реализуемая через css 20/20
100/100
7. A cross-check score of your Score 
67

**Comment by lyutails** [comment]
hey there o/

good job

1. Valid layout 
- no errors or warnings +10
2. Semantic layout
- header, main, footer +3
- five sections +3
- one h1 +3
- four h2 +3
- one nav that is in navigation +3
- should be two ul > li > a in nav panel and for social media links +3
- five buttons +2
3. Layout follows design... closely to being perfect in all the sections
- in header +6
- in welcome section +7
- about section +7
- service section +7
- prices section +7
- contacts +7
- footer +7
![image](https://user-images.githubusercontent.com/101958335/218328295-dd873357-f06f-4c03-a488-bdd47d2b4b0f.png)
![image](https://user-images.githubusercontent.com/101958335/218328349-e16f1aba-f2d1-4a55-a405-ebd8095310f4.png)
4. CSS
- flex is used +2
- when decreasing width layout stays in the middle of the page +2
- **background color covers whole screen's width for sections** (max 2) +0
![image](https://user-images.githubusercontent.com/101958335/218329056-d4a6ef33-dd2a-4229-8bef-a3d60a7a027c.png)
- icons are added as .svg +2
- pics are added in .jpg / .png format (max 2) +1
**except image in welcome section**
![image](https://user-images.githubusercontent.com/101958335/218328636-d6f9c437-2f0b-493a-99a6-93d8ab6fd41d.png)
- site does have favicon +2
5. Interactivity
- smooth scrolling from anchor to anchor +5
- links in footer leads to author's github and rsschool +5
- buttons change color smoothly on hover and nav menus (max 5) +4
**though one of the buttons somewhy doesn't follow design on hover**
![prices_button_hover_1](https://user-images.githubusercontent.com/101958335/218328948-9fdc72dc-161f-4ad3-9b4f-b46a68e4f58f.gif)
- interactive changes for one element doesn't affect neighbour elements +5

final score for this task is 100, though to remove misunderstandings we subtract from 110
110 - 4 = 106

**Final score: 100**

@helenakrasnova
check please
@Luffi2539
check please

**Comment by valerydluski** [comment]
task points updated
