### ISSUE TITLE
Cross-Check 'Online-store' - 'Arantola'

### ISSUE THREAD

**Issue by Arantola** [rolling-scopes-school/support#838]
1. A link to your deployed project
    - [link](https://jade-platypus-609af0.netlify.app/)
2. A link to the project repository on Github.
    - [link](https://github.com/MonstersBY/online-store/)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/tasks/online-store-team)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/tasks/online-store-team#%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/69305397/212292295-f5ee91bf-9a8d-4d34-ab23-2bab325a8f90.png)
![image](https://user-images.githubusercontent.com/69305397/212292369-43110b05-ac08-44ba-a68e-1b9b06c836a4.png)
![image](https://user-images.githubusercontent.com/69305397/212292433-5266a968-482d-4273-9a24-4e5406027e98.png)
![image](https://user-images.githubusercontent.com/69305397/212292460-1e6ef494-37da-4451-b051-2d787a2b2450.png)

6. A final score after self-assessment, with comments
[300] Есть некоторые баги (с пагинацией и range input), но неясно сколько за это снимать
7. A cross-check score of your Score 
[0] (проверил только 2 чужие работы)

**Comment by lyutails** [comment]
hey there o/

good job

Filters (max score 120)
1. two fillters' blocks (theme, publishers) +10
2. two dual-slider filters (three actually) +10
3. query works, also on page reset +10
4. filters cross count each other on change +10
**dual sliders don't reflect applied filters -2**
6. two sort (price, rating) +10
7. copied link with query after sort shows the same result +5
8. opening in new window shows which sort is selected +5
9. input for filter search +5
10. input search works alongside with other filters +5
11. after page reboot input filters plus others stay on place +5
12. different look for cards in catalog +5
13. cards look saves to query and remains the same after F5 +5
14. routing with query works +10
15. filters reset works +3
16. url copy works +4
17. copy link button changes it's view after being clicked +3
18. correct counts number of found products on catalog page +3
19. appears info if no products found +2
20. cards contain 'add to cart' button +5
21. by click on card we go to the card's page +5
Result: 118

Cart (max score 60)
1. list of products with products data plus ability to add more +5
2. increasing number of product changes price in header and in cart, cannot add more than available, how much available is shown +5
3. decreasing number of product changes price in header and in cart, if less than 1 - item removed +5
4. we can change number of products per page + number of pagination pages changes +8
5. each product has order number, correct for pages +2
6. message for cart empty when there are no products +5
7. products saves to local storage, same result after page reset +5
8. saving to local storage works from card page, catalog page, cart page +5
9. two promocodes, can be applied both also removed, sum in cart recounts after each one applied +5
10. previous sum is crossed after promos applied and new price is shown +5
11. 'buy now' opens modal for product purchase +5
12. there is block with total sum and price +5
Result: 60

Popup for product purchase in Cart (max score 50)
1. name surname input (two words at least three symbols) +5 
2. phone input (auto + and limit for 9 numbers, no letters allowed) +5
3. delivery address (three words >= than 5 symbols) +5
4. email address +5
5. for card number only numbers allowed and 16 is required +5
6. **when the first number for card number is 4 - Visa logo appears, for all other numbers at first position no payment systems logo automatically appears - requires at least two numbers for MasterCard logo to appear, same accidentally found out for Maestro after randomly pressed on keyboard 67 - probably correct for bank systems but not checkable for cross-check and doesn't fit requirements for logo system to show up after first number is added (max 5) +3**
![image](https://user-images.githubusercontent.com/101958335/216679394-e08c9ec6-41d3-435a-995f-8b5506c1e006.png)
![image](https://user-images.githubusercontent.com/101958335/216679529-bb8c1172-da60-410e-8787-3c5963aeb94b.png)
![image](https://user-images.githubusercontent.com/101958335/216679583-72d8a6ee-1f17-47a6-af60-ee35e5b87092.png)
8. validation allows only numbers, automatically adds '/', month is not allowed more than 12 and automatically changes to it +5
9. CVV only numbers limited to three of them +5
10. by click on 'order' all input fields are checked for errors +5
11. after validation is successful - appears message and then redirects us to catalog page, cart is empty +5
Result: 48

Product page (max score 40)
1. breadcrumb trail is released +5
2. several products photo, zoom by click, no dupes +10
3. there product's name, category, price, description on page +5
4. button add to cart, if already added in catalog - text on button changed +5
5. quick buy button redirects to cart page with opened purchase modal window +5
6. page opens in new window with product's id +10
Result: 40

Header (max score 20)
1. contains cart image with amount of added products +5
2. amount of added products changes dynamically when items added / removed +5
3. total cost +10
4. sum changes dynamically +5
Result: 20

404 page (max score 10)
1. page exists for not valid address +6
2. incorrect query keeps on page +4
Result: 10

**Final score: 296**

@DimaBLR 
take a look at please

**Comment by helenakrasnova** [comment]
выставлено
