### ISSUE TITLE
Cross-Check 'Online-Store' - RallyZK

### ISSUE THREAD

**Issue by RallyZK** [rolling-scopes-school/support#839]
**Примечание:**
У меня нет претензий к оценкам проверяющих.
Дело в том, что я проверила всех 4х стундентов, всю проверку вела в гугл таблицах, можете ознакомиться с моими оценками и комментариями: https://docs.google.com/spreadsheets/d/14W3tLksXmkv0Au2rWyYQswyif-QZ9AC0K9uUnwEfQNY/edit#gid=0

Потом выставила оценку двум студентам, у которых было 0 и 300, а остальных хотела еще раз перепроверить, т.к. задание очень объемное и, в итоге, забыла внести оценки в Review. 

Прошу позволить получить свою оценку за это задание, т.к. баллы очень существенные, я старалась над этим заданием как могла. Признаю свою ошибку, в следующие разы буду сразу выставлять оценки в 1 день (как раньше и делала)
Спасибо за понимание

1. A link to your deployed project
    - [[link](https://github.com/)](https://rallyzk.github.io/online-store/online-store/)
2. A link to the project repository on Github.
    - [[link](https://github.com/)](https://github.com/RallyZK/online-store/pull/8)
3. A link to the task
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/tasks/tree/master/tasks/online-store-team)
4. A Link to the checklist for evaluating the task (if it exists)
    - [[link](https://github.com/)](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks:
меня оценили на 236, 282 и 226
![a1](https://user-images.githubusercontent.com/106692279/212297592-df02eed1-eb21-4c65-b7a8-2522d5051e81.JPG)
![a2](https://user-images.githubusercontent.com/106692279/212297802-3e14991c-7582-4983-9546-c8ead0fcd08b.JPG)
![a3](https://user-images.githubusercontent.com/106692279/212297839-7bf8a621-8c19-434f-aaaa-cad88bcc4f7e.JPG)

6. A final score after self-assessment, with comments: 236
Самопроверку вели в гугл таблицах:
https://docs.google.com/spreadsheets/d/1OniiOOXWMxRJRMUGotm9dS8vVS3yEVD2/edit#gid=1584390175

7. A cross-check score of your Score:  0 (я выставила оценки только 2м студентам из 4х)

**Comment by helenakrasnova** [comment]
Исправить пункт A cross-check score of your Score - указать балл за cross-check из вашего Score.

**Comment by RallyZK** [comment]
> Исправить пункт A cross-check score of your Score - указать балл за cross-check из вашего Score.

исправлено

**Comment by lyutails** [comment]
hey there o/

good job

Filters (max score 120):
1. two filter blocks (category, brand) +10
2. two dual-sliders (price, rating) +10
3. **query is not implemented and page doesn't keep applied filters after reset** +0
4. filters dynamically recount when others applied +10
5. products sort is done by three parameters (price, rating, alphabet) +10
6. **sort parameters don't appear in query** +0
7. selected sort is not shown if opened in new window +0
8. input search +5
9. input search works alonside with other filters +5
10. **input search is not saved after page reset** +0
11. different product view +5
12. **different product view not saving to query and becomes default after page reset** +0
13. **routing with query is not implemented** +0
14. reset filters +3
15. copy current search +4
16. copy link button changes it's look when pressed +3
17. after filters are applied total amount of found is shown +3
18. if no products found it's shown +2
19. product's card contains 'add to cart' (buy) button +5
20. click on card redirects to product's page +5
Result 80

Cart page (max score 60):
1. products show up as a list with names, price, category etc. plus ability to add / remove product +5
2. amount of each product can be increased, total amount and total sum reacts to changes, cannot be added more than in stock +5
3. amount of each product can be decreased, when number is less than 1 - item automatically disappears from cart, total sum and amount reacts to changes +5
4. **pagination is not implemented** +0
5. **products' data is not stored in local storage** +0
6. if there are no products in cart shows 'cart is empty' +5
7. promocodes are imlemented - old price is crossed and new one appears, can be applied more than one, total discount sums and reflects final sum of purchase, can be removed +5
8. block with each promo discount and new price +5
9. 'buy now' button redirects to purchase popup +5
10. total sum of purchase with applied promos is shown +5
Result 40

Purchase popup (max score 50):
1. name / surname requires at least two words >= 3 chars +5
2. phone validation should be correct if starts with '+' (here **just numbers without plus in front of them are allowed and give no error - should start with '+'**), letters are not allowed, length is limited to 16 symbols (max 5) +4
![image](https://user-images.githubusercontent.com/101958335/216787654-db0a5e22-86d2-45cf-b972-e872e67ada13.png)
3. delivery address is waiting for three words not shorter than five letters each +5
4. email input checks if text is valid email address +5
5. only numbers are allowed for bank's card number, limited to 16 +5
6. payment system automatically changes reacting to first number typed (implemented >= 3 payment systems) +5
7. validation thru allows only numbers, requires four numbers, month can't be more than 12 +5
8. CVV allows only numbers, three of them required +5
9. submit buttons shows if there are errors +5
10. message appears on success, redirects to catalog page, cart becomes empty +5
Result 49

Product's page (max score 40):
1. breadcrumb trail +5
2. several products' pics, no dupes, **can't zoom by click / hover**  (max 10) +8
3. there is block with product's name, brand, price etc. +5
4. page contains button 'buy' adding item to cart, button's state shows if product was added +5
5. quick buy button implemented and leads to cart page with modal opened +5
6. page opens in a new window with product's id +10
Result 38 

Header (max score 20):
1. contains cart's image with number of added products +5
45. number of products dynamically changes when removed on all pages +5
46. shows total sum of added items +5
47. sum dynamically changes when product is removed, on all pages +5
Result 20

404 page (max score 10):
not implemented and shows default +0
![image](https://user-images.githubusercontent.com/101958335/216787509-6bd20cc1-c5fb-41d2-a7d4-e74a15c5231f.png)
Result 0

**Final score is 227**

@DimaBLR
take a look at please

**Comment by helenakrasnova** [comment]
выставлено
