### ISSUE TITLE
Markdown & Git

### ISSUE THREAD

**Issue by Binetsky** [rolling-scopes-school/support#84]
Hello, my name in Aleksei Binetsky, i want to find out why i have only 50/100 in "Markdown & Git"

**Comment by Iriyamak** [comment]
> Hello, my name in Aleksei Binetsky, i want to find out why i have only 50/100 in "Markdown & Git"

Hello. in Rs-app https://app.rs.school/course/student/auto-test?course=js-2020-q3 on the right side there are the table with your score for each test and comment with description of your mistakes.

**Comment by Binetsky** [comment]
Thank's)
