### ISSUE TITLE
Cross-Check Plants#1 - arseil.

### ISSUE THREAD

**Issue by arseil** [rolling-scopes-school/support#840]
1. A link to your deployed project
   - [link](https://rolling-scopes-school.github.io/arseil-JSFEPRESCHOOL2022Q4/plants/)
2. A link to the project repository on Github.
   - [link](https://github.com/rolling-scopes-school/arseil-JSFEPRESCHOOL2022Q4/tree/plants)
3. A link to the task
   - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md)
4. A Link to the checklist for evaluating the task (if it exists)
   - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/84498832/212334800-c854a587-3a88-436a-a118-fc4ffa8d74e4.png)

6. A final score after self-assessment, with comments
![image](https://user-images.githubusercontent.com/84498832/212335073-328e9b24-fd49-48f2-a632-ddda284c44f0.png)

7. A cross-check score of your Score 
67 / 100

**Comment by lyutails** [comment]
hey there o/

good job

1. Valid layout 
- no errors or / and warnings +10
2. Semantic layout
- header, main, footer +3
- five sections +3
- one h1 +3
- four h2 +3
- nav tag for navigation +3
- should be two ul > li > a in nav panel and for social media links +3
- five buttons +2
3. Layout follows design... closely to being perfect
![image](https://user-images.githubusercontent.com/101958335/218329925-1b4e138c-a4b9-4570-8edc-03e3298c8014.png)
- in header +6
- in welcome section +7
- about section +7
- service section +7
- **prices section** (max 7) +6
only here some distortion
![image](https://user-images.githubusercontent.com/101958335/218329980-7500870b-5724-4517-b14d-6c8a09d5b4d1.png)
- contacts +7
- footer +7
5. CSS
- flex is used +2
- when decreasing width layout stays in the middle of the page +2
- background color covers whole screen's width for sections +2
- icons are added as .svg +2
- pics are added in .jpg / .png format +2
- site does have favicon +2
6. Interactivity
- smooth scrolling from anchor to anchor +5
- links in footer leads to author's github and rsschool +5
- buttons change color smoothly on hover and nav menus +5
- interactive changes for one element doesn't affect neighbour elements +5

final score for this task is 100, though to remove misunderstandings we subtract from 110
110 - 1 = 109

**Final score: 100**

@helenakrasnova
check please
@Luffi2539
check please

**Comment by valerydluski** [comment]
task points updated
