### ISSUE TITLE
Cross-Check  Plants#1 - Фиксированная вёрстка - anyhhope

### ISSUE THREAD

**Issue by anyhhope** [rolling-scopes-school/support#841]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/anyhhope-JSFEPRESCHOOL2022Q4/plants/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/anyhhope-JSFEPRESCHOOL2022Q4)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![photo1673652225](https://user-images.githubusercontent.com/101920435/212436558-00ce24dd-eecf-40ff-821f-2c52a3d77946.jpeg)

6. A final score after self-assessment, with comments
110/110

1. Вёрстка валидная +10
2. Вёрстка семантическая +20
3. Вёрстка соответствует макету +48
4. Требования к css + 12
5. Интерактивность, реализуемая через css +20
110/110.

Недобросовестный ученик оценил мою работу в 0 баллов
7. A cross-check score of your Score 67

**Comment by lyutails** [comment]
hey there o/

good job

1. Valid layout 
- **some errors are present** (max 10) +0
![image](https://user-images.githubusercontent.com/101958335/218326219-5bc7f03c-e985-4553-8aae-7efcdb50e639.png)
2. Semantic layout
- header, main, footer +3
- five sections +3
- one h1 +3
- four h2 +3
- one nav that is in navigation +3
-  should be two ul > li > a in nav panel and for social media links +3
- five buttons +2
3. Layout follows design... closely to being perfect in all the sections
- in header +6
- in welcome section +7
- about section +7
- service section +7
- prices section +7
- contacts +7
- footer +7
![image](https://user-images.githubusercontent.com/101958335/218326522-541c0842-07d6-446b-8235-46961c7bd330.png)
4. CSS
- flex is used +2
- when decreasing width layout stays in the middle of the page +2
- background color covers whole screen's width for sections +2
- icons are added as .svg +2
- pics are added in .jpg / .png format +2
- site does have favicon +2
5. Interactivity
- smooth scrolling from anchor to anchor +5
- links in footer leads to author's github and rsschool +5
- buttons change color smoothly on hover and nav menus (max 5) +4
though you do have 🐞 for button in prices section
![prices_button_hover](https://user-images.githubusercontent.com/101958335/218326877-e181e453-0825-4e1e-a584-235454b40b05.gif)
![image](https://user-images.githubusercontent.com/101958335/218326955-a0dd4bb4-fade-4faa-a3f8-c874706693fb.png)
- interactive changes for one element doesn't affect neighbour elements +5

final score for this task is 100, though to remove misunderstandings we subtract from 110
110 - 11 = 99

**Final score: 99**

@helenakrasnova
check please
@Luffi2539
check please

**Comment by valerydluski** [comment]
task points updated
