### ISSUE TITLE
Cross-Check 'Plants#2' - 'eugenepushkin'

### ISSUE THREAD

**Issue by eugenepushkin** [rolling-scopes-school/support#845]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/eugenepushkin-JSFEPRESCHOOL2022Q4/plants/
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/eugenepushkin-JSFEPRESCHOOL2022Q4
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part2.md
4. A Link to the checklist for evaluating the task (if it exists)
    - https://rolling-scopes-school.github.io/checklist/    ---> Plants#2
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/56837635/215014905-fa40fb9b-83b8-42f2-990b-cf421a0cc801.png)
![image](https://user-images.githubusercontent.com/56837635/215014956-189b2691-c93e-47b7-ba43-341df7885fac.png)
6. A final score after self-assessment, with comments
  Полосы прокрутки нету, баллы сняты несправедливо.
  Соответсвие цветовой схеме: субъективное мнение каждого. Мне казалось, что оно подходит. Почему сняты все баллы?) 
  При клике вне меню всё пропадает, только если не жать на шапку, считаю, что должна быть половина в худшем случае) 
7. A cross-check score of your Score
  Считаю что выполнил все условия, для получения максимальной оценки) Не идеально конечно, но и не так всё плохо)
  73/75

**Comment by lyutails** [comment]
hey there o/

you got 73 of 75 possible for this task
![image](https://user-images.githubusercontent.com/101958335/217064584-81fac616-5d82-4234-9daa-5534568b21d3.png)

one of the necessary criterita to fit for appeal to happen - difference in score should be >= 10% from maximum
from here you don't fit this requirement
