### ISSUE TITLE
Cross-Check Plant #2 Mikhail Zajkov Diskantis ( diskantis-JSFEPRESCHOOL2022Q4 )

### ISSUE THREAD

**Issue by Diskantis** [rolling-scopes-school/support#847]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/diskantis-JSFEPRESCHOOL2022Q4/PLANTS/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/diskantis-JSFEPRESCHOOL2022Q4/tree/plants-part2)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![#1](https://user-images.githubusercontent.com/52001452/215027402-de823cfb-8dd3-42af-8f9d-dae8ff8dce77.png)
![#2](https://user-images.githubusercontent.com/52001452/215027404-7722e84a-edb4-4608-bce8-d194d4f16c90.png)
![#3](https://user-images.githubusercontent.com/52001452/215027406-58ec3532-99aa-4785-a024-77652c1cefca.png)
6. A final score after self-assessment, with comments
Оценка: 75 баллов. Все проверочные критерии соблюдены. 
7. A cross-check score of your Score 
70 / 75

**Comment by lyutails** [comment]
hey there o/

you got 70 of 75 possible for this task
![image](https://user-images.githubusercontent.com/101958335/217062838-8053052d-d726-4eaa-bcd8-d15d8d5447bb.png)

one of the criteria for task to be reviewed - is 10% difference from the maximum score, 70 doesn't fit this requirement

**Comment by Diskantis** [comment]
Understood. Thanks for the help. Sorry to bother you.
