### ISSUE TITLE
Cross-Check 'async-race' - 'mclakov'

### ISSUE THREAD

**Issue by mclakov** [rolling-scopes-school/support#849]
1. A link to your deployed project
 https://playful-praline-737040.netlify.app/
https://github.com/rolling-scopes-school/mclakov-JSFE2022Q3/pull/45
2. A link to the project repository on Github
https://github.com/rolling-scopes-school/mclakov-JSFE2022Q3/tree/async-race
3. A link to the task
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md
4. A Link to the checklist for evaluating the task (if it exists)
https://rolling-scopes-school.github.io/checklist/
5. A screenshot of cross-checking marks
<img width="153" alt="image" src="https://user-images.githubusercontent.com/40365971/215276572-25690e00-cd1f-46be-9904-e3beb47c1ae1.png">
<img width="142" alt="image" src="https://user-images.githubusercontent.com/40365971/215276578-e0630555-235c-4ea1-840b-4c60a7a35f05.png">
<img width="148" alt="image" src="https://user-images.githubusercontent.com/40365971/215276596-487e42a6-0fe0-4f87-b308-52724954cc1c.png">
6. A final score after self-assessment, with comments
190 все пункты задания выполнены 
7. A cross-check score of your Score 
118

**Comment by lyutails** [comment]
hey there o/

good job

1. 
- there are two views 'garage' and 'winners' +5
- garage contains page number, name, amount of items +5
- winners contains name, page number, amount of items +5
- view state saved, **but switching between pages and going back and forth works as reset and doesn't save current state of cars on the page where race was** (max 10)  +8
![cars_state_pagination](https://user-images.githubusercontent.com/101958335/217054264-576c9dee-5115-41b8-b969-1e64bf59a32a.gif)
2.
- able to create, update, delete car, has 'color' and 'name', also deletes from winners +15
- able to select color from rgb palette +10
- near car buttons to delete / update +5
- pagination (7 per page) +10
- button for creating 100 random cars +10
3.
- buttons to start / stop car's engine +5
- car stops when engine get 500 from server +20
- car returns to it's place when press on 'b' button +5
- start button disabled when already in driving mode +5
- animation should work fine on any screen (smallest 500px) +15
4.
- button to start race works correctly +10
- button to reset race works correctly +10
- win message for first finished car +10
5.
- after car wins it's result added to winners +10
- pagination and 10 winners per page +5
- order number, pic, name, wins, best time +10
- sort is implemented but **no sort images / indicators are visible, you would not know where to click and if to click or not unless it's written in task** (max 10) +8
![image](https://user-images.githubusercontent.com/101958335/217053530-f8a72df4-6369-46ec-9daf-ecd8e86c6ed2.png)

**Final score: 186**

@helenakrasnova
take a look at please

**Comment by helenakrasnova** [comment]
выставлено
