### ISSUE TITLE
Проблемы с личными приватными репо и теми которые выдает школа у резидентов Крыма

### ISSUE THREAD

**Issue by Student-Java** [rolling-scopes-school/support#85]
GitHub блочит аккаунт и не дает использовать приватные репо, если у пользователя Крымский IP. Блокировка распространяется на сам аккаунт пользователя, поэтому использование VPN после блокировки не поможет.
Я проверял такой аккаунт используя свой доступ в интернет и результат тот же.
![image](https://user-images.githubusercontent.com/57161516/93715864-545cc280-fb42-11ea-9383-d7d9129925ad.png)
Сейчас в наборе около 10-ти человек с Крыма, вот часть из них
![image](https://user-images.githubusercontent.com/57161516/93715877-6a6a8300-fb42-11ea-8af0-a49e365d97bb.png)

Как вариант можно разрешить им сдавать работы с личными неприватными репо. Еще вариант попробовать удалить пользователя с гитхаб и создать нового с тем-же логином, но уже используя VPN и в дальнейшем студенту все время придется работать с гитом через VPN.

**Comment by hallovarvara** [comment]
По-моему, оптимально делать в личном приватном репозитории в случае лоцирования в Крыму. Сдавать через нетлифай. В правила добавить это исключение, чтобы кроссчекеры не подумали баллы снимать. Ментора добавить в коллабораторы.

**Comment by Student-Java** [comment]
@hallovarvara 
![image](https://user-images.githubusercontent.com/57161516/93718330-cab4f100-fb51-11ea-9e0b-b696e7596e7f.png)

**Comment by hallovarvara** [comment]
@Student-Java тогда остаются публичные репозитории 😕 И придется позаботиться о регулярных проверках на плагиат кода.
