### ISSUE TITLE
Cross-Check 'plants-part3' - 'VitaliKozhurov'.

### ISSUE THREAD

**Issue by VitaliKozhurov** [rolling-scopes-school/support#850]
1. A link to your deployed project
https://rolling-scopes-school.github.io/vitalikozhurov-JSFEPRESCHOOL2022Q4/plants/
2. A link to the project repository on Github.
https://github.com/rolling-scopes-school/vitalikozhurov-JSFEPRESCHOOL2022Q4/tree/plants-part3
3. A link to the task
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part3.md
4. A Link to the checklist for evaluating the task (if it exists)
https://rolling-scopes-school.github.io/checklist/
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/110495939/218016891-b5522681-c05e-41f3-9619-d0427784addb.png)
6. A final score after self-assessment, with comments
100 баллов, функционал, указанный в задании выполнен.
7. A cross-check score of your Score 
75 баллов

**Comment by VitaliKozhurov** [comment]
Я считаю, что итоговая оценка выставленная проверяющим не верна, другой проверяющий оценил работу на 100 баллов.

**Comment by lyutails** [comment]
hey there o/

1. блюр в секции сервис (max score 50)
- при нажатии одной из трёх кнопок, относящиеся к ней услуги не заблюрены, остальные заблюрены +20
- при нажатии двух кнопок, относящиеся к ним услуги не заблюрены, остальные заблюрены, третья кнопка блочится +20
- кнопки плавно анимируются +10
2. аккордеон (max score 50)
- **при открытии одного из меню раздвигается фон всей секции - ломает макет и не соответствует ему визуально -2**
![accordion_section_1](https://user-images.githubusercontent.com/101958335/218102568-7c84e8ab-db2b-4cf0-b17c-f00818420871.gif)
- в остальном прекрасно - плавные красивые анимации, каждое меню можно открыть и закрыть кнопкой дроап /дропдаун, информация в меню корректная и соответствует макету, при открытом одном меню - нажатие на другое закрывает открытое +48
3. селект в городах (max score 25)
- тоже красивые плавные анимации, интересно появляется блок с выбранным городом, внешне соответствует макету (max score 25) +17
- **есть небольшой баг - повторное нажатие на город или выбор следующего города через раз меняет цвет меню на бледно зелёный, который на макете соответствует ни одному не выбранному городу и после того, как город выбран - открытие меню без выбора города и его закрытие - красит меню в зелёный цвет, но блок с информацией о городе исчезает -3**
![select_color](https://user-images.githubusercontent.com/101958335/218034841-4f07bb10-c313-4f25-8101-df8905cdc8ff.gif)
![select_no_city](https://user-images.githubusercontent.com/101958335/218035375-b8ee50f1-8da7-464c-9637-7a8693d2772e.gif)
- **нажатие на Call us работает как вызов по телефону, но звонит не туда - для всех номеров один и тот же -5**
![image](https://user-images.githubusercontent.com/101958335/218034027-97db450c-7b69-4f5f-b110-b7463a59fe58.png)

для этого задания дали люфт по баллам - вычитали из 125, максимальный скор 100, поэтому результат 125 - 10 = 115

**Final score: 100**

@helenakrasnova
check please
@Luffi2539
check please

**Comment by helenakrasnova** [comment]
оценка выставлена
