### ISSUE TITLE
 Cross-Check Plants #3 - Sobyt483.

### ISSUE THREAD

**Issue by Sobyt483** [rolling-scopes-school/support#852]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/sobyt483-JSFEPRESCHOOL2022Q4/plants/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/sobyt483-JSFEPRESCHOOL2022Q4)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part3.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/) PLANTS#3
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/117839500/218041292-c33ff7b0-6847-4f5b-b46d-648cd739f59f.png)
Писал проверяющему, он не отвечает.
6. A final score after self-assessment, with comments 125/125, but max 100. All requirements are met

8. A cross-check score of your Score: 83

**Comment by lyutails** [comment]
hey there o/

good job

1. Blur in Service section (max score 50)
- if one of three buttons is pressed - all cards associated with it are blurred, also by second click blur is removed +20
- if two buttons are pressed - related to them cards are not blurred, others are blurred, third button remains disabled +20
- smooth animations for buttons +10
2. Accordion (max score 50)
- pressing on drop down makes related menu open / drop up closes, clicking on order redirects to contacts section, accordion's menu remains opened +25
- accordion's menu can be closed by clicking on drop up button, also clicking on other's menu drop down button closes currently opened +25
3. City select in contacts section (max score 25)
- by click on city appears block with info related to that city +15
- by clicking on Call us works tel: option calling to the phone number as in info block +10

for this task to avoid misunderstandings we subtract from 125, though maximum score is 100

**Final score: 100**

@helenakrasnova
check please
@Luffi2539
check please

**Comment by helenakrasnova** [comment]
оценка выставлена
