### ISSUE TITLE
Cross-Check 'PLANTS#3' - SmileyRed.

### ISSUE THREAD

**Issue by SmileyRed** [rolling-scopes-school/support#853]
1. A link to your deployed project
    - [[link](https://github.com/)](https://rolling-scopes-school.github.io/smileyred-JSFEPRESCHOOL2022Q4/plants/)
2. A link to the project repository on Github.
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/smileyred-JSFEPRESCHOOL2022Q4)
3. A link to the task
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part3.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![Снимок](https://user-images.githubusercontent.com/94817202/218054005-424b5050-488a-4c76-859f-64560b1fb6c6.PNG)

6. A final score after self-assessment, with comments
100
7. A cross-check score of your Score 
100

**Comment by Luffi2539** [comment]
Dont see an issue here

**Comment by Luffi2539** [comment]
Student got 0 becuase didnt review other students because of app malfunction

**Comment by lyutails** [comment]
hey there o/

good job

1. Blur in service section (max score 50)
- click on one of three buttons makes related cards not blurred, other cards remain blurred +20
- click on two buttons makes related to them cards not blurred, others blurred, though **user shouldn't be able to press simultaneously all three buttons (third should be disabled or pressing on third when two are already pressed should make one of already pressed inactive) - doing so in your case makes all cards not blurred -5** (max score +20) +15
![blur_third_disable](https://user-images.githubusercontent.com/101958335/218099780-a6174f14-8a6d-41c6-a855-f76a4c7cd231.gif)
- smooth animation +10
2. Accordion in prices (max score 50)
- clicking on dropdown / dropup in accordion sections open / closes related menu, **though opening menus makes the whole section background wider - breaks design layout -2** (max score 25) +23
![accordion_section](https://user-images.githubusercontent.com/101958335/218101269-ba35faef-8240-4f3d-b4c2-80f939c51e94.gif)
- user can close menu by clicking on dropup, also already opened menu closes when another one is clicked  +25
3. City select in contacts section (max score 25)
- appears block with info related to selected city +15
- clicking on Call us should work as call to it's related phone number - **not implemented and leads to emplty tel: (not assigned correct phone number) -8** (max score 10) +2
![image](https://user-images.githubusercontent.com/101958335/218089846-fbf3c602-002e-45e1-acf0-92bc38ff11a0.png)

for this task we subtract from 125, so final score is 125 - 15 = 110, though max score is 100

**Final score: 100**

@helenakrasnova
check please
@Luffi2539
check please

**Comment by helenakrasnova** [comment]
оценка выставлена
