### ISSUE TITLE
Cross-Check 'Plants#3' 'vadimderyugin'

### ISSUE THREAD

**Issue by vadimderyugin** [rolling-scopes-school/support#854]
1. A link to your deployed project
  https://rolling-scopes-school.github.io/vadimderyugin-JSFEPRESCHOOL2022Q4/plants/
2. A link to the project repository on Github.
   https://github.com/rolling-scopes-school/vadimderyugin-JSFEPRESCHOOL2022Q4
3. A link to the task
    https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part3.md
4. A Link to the checklist for evaluating the task (if it exists)
    https://app.rs.school/course/student/cross-check-submit?course=js-fe-preschool-2022q4&taskId=2242
5. A screenshot of cross-checking marks
6. ![Desktop Screenshot 2023 02 10 - 19 21 54 53](https://user-images.githubusercontent.com/77327761/218102449-6eb297bf-44c0-4b12-b294-f461acc42b75.png)
7. A final score after self-assessment, with comments
100
8. A cross-check score of your Score 
100

**Comment by vadimderyugin** [comment]
анонимный студент поставил мне 80 баллов, когда остальные поставили максимальный балл, оценка явно занижена, указаны не выполненные пункты, хотя они выполнены.

**Comment by lyutails** [comment]
hey there o/

your final score after cross-check is 100 (maximum for this task)
![image](https://user-images.githubusercontent.com/101958335/218105715-8e3fb19b-af8f-4a1c-862c-e0c7e4cc1f9d.png)

one of the criteria for appeal to happen - difference in score >= 10% from maximum score, therefore appeal cannot be performed

if you think cross check was inadequate / breaking code-of-conduct whatsoever - use the form for complaints
https://docs.google.com/forms/d/e/1FAIpQLSc9su27qv3CzpkWQNRP2RsHCgjw0NFsmRT0fQgHA3ccN08vwA/viewform

@Luffi2539
take a look at please
