### ISSUE TITLE
Cross-Check 'RSclone' - 'lanavladi'

### ISSUE THREAD

**Issue by LanaVladi** [rolling-scopes-school/support#855]
1. A link to your deployed project
    - [link](https://rs-clone-weather-app-2.netlify.app/)
2. A link to the project repository on Github.
    - [link](https://github.com/LanaVladi/rs-clone/pull/42)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rsclone/rsclone.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)  Формы для проверки проекта rs-clone нет в данном задании
5. A screenshot of cross-checking marks
Скриншот с оценками за cross-check отсутствует.

Доброго времени суток! Произошла следующая ситуация. Из-за отсутствия сна в течение 24 часов мозг дал сбой, и я забыла сделать сабмит ссылки на ПР, осознание пришло ровно в дедлайн. Это не оправдание, но описание ситуации как есть.
 Ссылка на деплой была скорректирована, потому что изначальная приводила к ошибке 404, и открывалась после нажатия на кнопку back to our site, но потом опять ломалась из-за того несоответствия, что страница, загруженная по протоколу HTTPS, запрашивала некоторые данные с apiOpenWeather по HTTP.
Также после деплоя были обнаружены следующие баги: 
а). При нажатии кнопки полноэкранного режима карта ограничивается в ширину
б) При голосовом поиске, если город не был распознан и при введении в строку поиска неправильного города, выходит ошибка 404. Если это последний вызванный город и пользователь перезагрузил страницу, то сайт переходит на страницу 404.
Прошу по возможности проверить нашу работу. Очень много труда было вложено. Благодарю. 

6. A final score after self-assessment, with comments
Реализовано   505 из 620, до выявленных ошибок приложения после деплоя
Использован   MVC паттерн +30
Для   сборки приложения использован Webpack +10
Для   работы с данными использован паттерн Observer +30
Приложение   реализовано на TypeScript +30
Использован   SPA паттерн +30
Локализация   приложения RU/EN +20
Сохранение   в LocalStorage настроек локализации при перезагрузке приложения +20
Сохранение   в LocalStorage последнего выбранного города при перезагрузке приложения  +10
Использование   API OpenWeather для работы страниц Today, 5 days, Air quality +30
Использование   API Windy.com для работы страницы Map +30
Использование   библиотеки Leaflet для отображения карты +30
Приложение   адаптировано для телефона, планшета и десктопа +20
Реализовано   не менее 2-х модальных окна +20
Реализовано   не менее 2-х анимаций +15
Реализовано   переключение цвета фона и блока страницы на сегодня в зависимости от погоды и   времени суток +30
Корректная   обработка даты в формате UNIX +5
Карта с   анимацией ветра:
Добавлена   карта, работает анимация, отображаются данные от ветре, температуре, давлении   +15
Управление   картой:
масштабирование   карты при помощи колеса мыши, а также с помощью кнопок +5
изменение   отображаемого слоя (ветер, температура, давление) +5
изменение   высоты, для которой отображаются данные (горизонтальный range-input) +10
изменение   единиц измерения данных (dropbox) +10
поле для   ввода города +10
шкала с   легендой для отображаемых данных +5
отключение/включение   анимации ветра (checkbox) +5
прогнозирование   погоды в течение суток +5
Голосовой   поиск +15
Погода   на сегодня +20
Прогноз   на 5 дней +20
Прогноз   качества воздуха +20

Не   реализовано:
Выпадающий список со списком   городов, сохраняющий 5 последних вызовов      +20
Отображение   температуры при наведении курсора на область +5
Возможность   подключиться к веб-камерам в городе +15
Озвучивание   погоды +20
Живой   поиск +15
Код страны,   преобразованный в страну по ISO 3166-1 +10
Пагинация в хедере (Добавление 5 городов для просмотра погоды   во вкладки) +15
Добавление   всех параметров в URL +15

7. A cross-check score of your Score 
Балл за cross-check из Score отсутствуют по причине, описанной в пункте 6

**Comment by helenakrasnova** [comment]
Ссылка на деплой не работает - нужно исправить на https://rs-clone-weather-app-2.netlify.app/  
название ишью должно быть Cross-Check 'RSclone - lanavladi'

**Comment by LanaVladi** [comment]
> Ссылка на деплой не работает - нужно исправить на https://rs-clone-weather-app-2.netlify.app/ название ишью должно быть Cross-Check 'RSclone - lanavladi'

Добрый день. поправила название ишью и скорректировала ссылку. Посмотрите пожалуйста

**Comment by lyutails** [comment]
привет :)

1. Использован MVC паттерн +30
2. Для сборки приложения использован Webpack +10
3. Для работы с данными использован паттерн Observer +30
4. Приложение реализовано на TypeScript +30
5. Использован SPA паттерн +30
6. Локализация приложения RU/EN +20
7. Сохранение в LocalStorage настроек локализации при перезагрузке приложения +20
8. Сохранение в LocalStorage последнего выбранного города при перезагрузке приложения +10
9. Использование API OpenWeather для работы страниц Today, 5 days, Air quality +30
10. Использование API Windy.com для работы страницы Map +30
11. Использование библиотеки Leaflet для отображения карты +30
12. Приложение адаптировано для телефона и десктопа +20
13. Реализовано не менее 2-х модальных окон +20
14. Реализовано не менее 2-х анимаций +15
15. Реализовано переключение цвета фона и блока страницы на сегодня в зависимости от погоды и времени суток +30
красиво, что фон зависит от времени суток ^^
16. Корректная обработка даты в формате юникс +5
Карта с анимацией ветра:
17. Добавлена карта, работает анимация, отображаются данные от ветре, температуре, давлении +15
карта класс залипательно смотреть :)
Управление картой:
18. масштабирование карты при помощи колеса мыши, а также с помощью кнопок +5
19. изменение отображаемого слоя (ветер, температура, давление) +5
20. изменение высоты, для которой отображаются данные (горизонтальный рэндж-инпут) +10
21. изменение единиц измерения данных (дропбоксы) +10
22. поле для ввода города +10
23. шкала с легендой для отображаемых данных +5
24. отключение/включение анимации ветра (чекбокс) +5
25. прогнозирование погоды в течение суток +5
26. Голосовой поиск +15
побаловалась голосом, правильно слышит :)
27. Погода на сегодня +20
28. Прогноз на 5 дней +20
29. Прогноз качества воздуха +20

🐞 каждый раз при перезагрузке страницы вылазит такой баг, Back to our site - возвращает на сайт **-2**
![image](https://user-images.githubusercontent.com/101958335/222872279-42e324c0-333b-4a31-b1d6-022e82caf02c.png)

остальное, за что просят баллы - есть и работает

505 - 2 = 503

Final Score: 503

@helenakrasnova take a look at please
@valerydluski take a look at please
