### ISSUE TITLE
Momentum review

### ISSUE THREAD

**Issue by aurewa** [rolling-scopes-school/support#856]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/aurewa-JSFEPRESCHOOL2022Q4/momentum/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/aurewa-JSFEPRESCHOOL2022Q4)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/momentum/momentum-stage1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/4935864/222096709-272f796d-deac-49a5-9daf-ddf0404e9232.png)
6. A final score after self-assessment, with comments  **150**
7. A cross-check score of your Score  **140**

Добрый день. При оценке моего задания ревьювер снизил оценку, при этом не указал за какие пункты это было сделано. Складывается ощущение, что человек не понял принцип оценки задания. Связаться с человеком не представляется возможным, т.к. не указан Discord и имя пользователя. Если это возможно, хотелось бы провести повторное ревью или попросить моего ревьювера описать пункты из-за которых была снижена оценка.

**Comment by lyutails** [comment]
Привет :)
апелляции проводятся, если сумма баллов за задание **после** (он до 03.03) кроссчека меньше на 10% или более от максимального
форма для жалоб на проверяющих тут: https://docs.google.com/forms/d/e/1FAIpQLSc9su27qv3CzpkWQNRP2RsHCgjw0NFsmRT0fQgHA3ccN08vwA/viewform
плюс имя ишшью написано не по требуемой форме
![image](https://user-images.githubusercontent.com/101958335/222105394-9e1591fa-2ad0-4595-92bc-a0c107d3cc15.png)

**invalid issue name**

**Comment by aurewa** [comment]
Привет! Спасибо за ответ и разъяснения. Я видел этот пункт, про условия
апелляции, но надеялся, что с этим можно что-то сделать.

**Comment by lyutails** [comment]
stage#0 is over
