### ISSUE TITLE
Cross-Check 'Momentum' 'burakyauhen'

### ISSUE THREAD

**Issue by burakyauhen** [rolling-scopes-school/support#857]
Добрый день. Меня зовут Евгений. Я не прошу пересмотра моей оценки, так как количество проверяющий у меня было 4 человека и эта оценка никак не повлияла на мой итоговый бал. Но человек негативно подошел к проверке моей работы. Бал занижен примерно на 30 пунктов. Человек в отзыве на работу явно указывает рабочие пункты как не выполненные. 9 и 10 пункты не оценивает вообще (9 выполнен полностью, 10 - частичные пункты, некоторые на усмотрение проверяющего).  Цель моего обращения -  улучшение работы  cross-check-review. Возможно человек относится так к проверкам всех работ, что дополнительно создает затраты времени для остальных участников. Работа была проверена за несколько часов до окончания review, discord - отсутствует, не комментарии к отзыву человек не ответил. Спасибо.

1. A link to your deployed project
https://rolling-scopes-school.github.io/burakyauhen-JSFEPRESCHOOL2022Q4/momentum/
2. A link to the project repository on Github.
   [burakyauhen-JSFEPRESCHOOL2022Q4](https://github.com/rolling-scopes-school/burakyauhen-JSFEPRESCHOOL2022Q4)
3. A link to the task
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/momentum/momentum-stage1.md
4. A Link to the checklist for evaluating the task (if it exists)
https://app.rs.school/course/student/cross-check-submit?course=js-fe-preschool-2022q4&taskId=2146
5. A screenshot of cross-checking marks
![app rs school_course_student_cross-check-submit_course=js-fe-preschool-2022q4 taskId=2146](https://user-images.githubusercontent.com/119586961/222664814-d2b1d9bc-f603-4207-9880-6e64137c5175.png)

6. A final score after self-assessment, with comments
140 баллов, не учтены следующие пункты:
 - Пункт плавного изменения реализован (+5)
 - Город в погоде также сохраняется при перезагрузке (+5)
 - Есть кнопка "mute" для отключения/включения звука (+3)
 - Трек запускается при нажатии на строку с треком(пункт 7.1 - примерный внешний вид) -функция переключения реализована. (+3) 
 - Не посчитан 9 пункт - работает unsplash и flicker (+10)
 Пункт 10.1, 10.2, 10.3 выполнены полностью +9
 Пункт 10.4 - выполнен частично
7. A cross-check score of your Score 
= 144 балла.

**Comment by lyutails** [comment]
привет :)
сюда только по апелляциям :Р
по неадекватной оценке - в форму для жалоб на кросс-чек
https://docs.google.com/forms/d/e/1FAIpQLSc9su27qv3CzpkWQNRP2RsHCgjw0NFsmRT0fQgHA3ccN08vwA/viewform
за отсутствие комментариев, поясняющих снятие баллов, или несправедливое их занижение можно получить предупреждение или даже бан (если не в первый раз), что появится в канале #moderation после рассмотрения жалобы

и спасибо - есть действительно те, кто из раза в раз халатно относится к проведению проверок и портит жизнь и нервы другим обучающимся и администрации

💓

**Comment by burakyauhen** [comment]
Спасибо!
