### ISSUE TITLE
Cross-Check Momentum - Kharsaeva

### ISSUE THREAD

**Issue by Kharsaeva** [rolling-scopes-school/support#858]
1. A link to your deployed project
    - [link](https://kharsaeva-momentum.netlify.app/)
2. A link to the project repository on Github.
    - [link](https://github.com/Kharsaeva/momentum)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/momentum/momentum-stage1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![Без имени](https://user-images.githubusercontent.com/72945047/222668404-840fa0e6-7965-4e1e-9547-625e60d8fac2.png)

6. A final score after self-assessment, with comments
140 из 160 баллов, не выполнено : 
-15 перевод приложения
- в качестве источника изображений может использоваться Flickr API -5

8. A cross-check score of your Score 116

Добрый день, двое из из проверяющих поставили баллы еще в начале кросс-чека, после доработки задания попросила их перепроверить, писала им в дискорд и под их оценкой в комментариях, ответа не последовало как и самой перепроверки, третий же ревьювер перепроверил, но бал ниже чем ожидалось, в качестве комментария оставил старый и мне не понятно за что снижена оценка. Буду благодарна за помощь

**Comment by lyutails** [comment]
привет :)
если была доработка задания - значит были коммиты после дедлайна - одно из условий проведения апелляции (помимо разницы от максимального балла более чем на 10%)
![image](https://user-images.githubusercontent.com/101958335/222680292-25bd4dd5-35e8-47a6-8b0a-dc80b7b8b9b0.png)
https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f
![image](https://user-images.githubusercontent.com/101958335/222682798-941ecd41-4a7b-44e0-9751-a4574f7723e4.png)

**Comment by Kharsaeva** [comment]
Доработка была до дедлайна, засабмичена была работа не доделанная, один ревьювер проверил работу сразу как начался кросс-чек, на сообщение с просьбой о перепроверке не ответил, остальные проверили позже, но перепроверил только один с заниженной оценкой

**Comment by Kharsaeva** [comment]
Складывается впечатление, что проверка была проведена теми кто прочитал сообщение, но не перепроверил, только ради получения оценки за свою работу - «Если вы проверили не все работы, из распределенных вам работ других студентов, до наступления дедлайна по кроссчеку, то ваша оценка за работу будет 0 баллов.»

**Comment by lyutails** [comment]
почему тогда последний коммит 14 часов назад :?
перепроверять или нет работы - это добровольно и по желанию студентов

**Comment by lyutails** [comment]
и или мне совсем отказывает логика или - работа доделывалась **после** дедлайна
или зачем была просьба перепроверить если работа не доделывалась О_о

![image](https://user-images.githubusercontent.com/101958335/222697210-ce428f0e-4a83-40cf-b1bc-7d33174b93f2.png)

**Comment by Kharsaeva** [comment]
время последнего коммита 21:32, если навести курсор на "16 hours ago" он показывает точное время
наверное я непонятно объясняю, я не успела закончить работу до Cross-Check: Submit - 2023-02-27 03:00 и засабмитила деплой с тем что успела сделать до дедлайна Cross-Check: SUBMIT
Во время уже Cross-Check: REVIEW доделала остальное и выложила изменения до дедлайна Cross-Check: REVIEW в 9:32

**Comment by lyutails** [comment]
наоборот всё очень понятно, но спасибо за пояснения а то вдруг что не так :)

если сабмиттишь незаконченную работу - и вносишь правки после дедлайна - автоматически соглашаешься, что теряешь право на апелляцию

если хочешь чтобы апелляция могла быть проведена - во время кросс-чека и после - никаких правок не вносишь

дедлайн Cross-Check: REVIEW - это время окончания кросс-чека, в течении кросс-чека (обычно 3 дня) ты правки уже не вносишь (если хочешь апелляцию) или если вносишь правки - общаешься с ревьюерами с надеждой на перепроверку :)

если тебе кажется, что оценка ревьюерами была неадекватно занижена - форма для жалоб на кросс-чек
https://docs.google.com/forms/d/e/1FAIpQLSc9su27qv3CzpkWQNRP2RsHCgjw0NFsmRT0fQgHA3ccN08vwA/viewform
