### ISSUE TITLE
2022Q3 students without mentor

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/support#859]
Это issue созданно для студентов которые учились без ментора и дошли до конца курса (сдача 2-х последних интервью на оценку 4 и выше, выполнен финальный таск).
Отпишитесь какие работы вы бы хотели чтобы у вас проверили ментора и сколько баллов примерно вам не хватает до сертификата.
Обязательно оставить ссылки на pr тех задания которые вы бы хотели чтобы у вас проверилм

**Comment by Danil336** [comment]
Добрый вечер, мне не хватает 200-300 баллов для получения сертификата.
Все нужные для получения сертификата условия соблюдены.
Если есть возможность проверить мои работы - буду признателен.
1) Async race: https://github.com/rolling-scopes-school/danil336-JSFE2022Q3/pull/8
2) Online store: https://github.com/rolling-scopes-school/danil336-JSFE2022Q3/pull/7
3) Migration to ts: https://github.com/rolling-scopes-school/danil336-JSFE2022Q3/tree/migration-newip-to-ts
Заранее спасибо!

**Comment by evakerrigan** [comment]
Добрый вечер ! Мне не хватает баллов для получения сертификата. 
Все нужные для получения сертификата условия соблюдены.
Если есть возможность проверить мою работу - буду признательна. 

Не проверена только 1 работа. 

Асинки. https://github.com/rolling-scopes-school/evakerrigan-JSFE2022Q3/pull/63

Ментор @Cstrp согласен проверить мою работу )

Спасибо !)

**Comment by shzFas** [comment]
Добрый день! Мне не хватает баллов для получения сертификата.

Сдал CoreJS Interview на 7 из 10
![изображение](https://user-images.githubusercontent.com/63981542/222949850-64429262-2448-4855-ad7c-9f555de6854e.png)


Буду рад если проверите работы:
1. https://github.com/shzFas/online-store/pull/1 - Online Store
2. https://github.com/shzFas/async-race/pull/1 - async race 
3. https://github.com/rolling-scopes-school/shzfas-JSFE2022Q3/tree/gh-pages/news-js - Migration typescript

**Comment by Cstrp** [comment]
> Добрый вечер ! Мне не хватает баллов для получения сертификата. Все нужные для получения сертификата условия соблюдены. Если есть возможность проверить мою работу - буду признательна.
> 
> Не проверена только 1 работа.
> 
> Асинки. [rolling-scopes-school/evakerrigan-JSFE2022Q3#63](https://github.com/rolling-scopes-school/evakerrigan-JSFE2022Q3/pull/63)
> 
> Ментор @Cstrp согласен проверить мою работу )
> 
> Спасибо !)

Проверил, выход 105 баллов из 150 по менторским критериям. Фид бек оставил.

**Comment by MikAleinik** [comment]
> Добрый вечер, мне не хватает 200-300 баллов для получения сертификата. Все нужные для получения сертификата условия соблюдены. Если есть возможность проверить мои работы - буду признателен.
> 
>     1. Async race
>     2. Online store
>     3. Migration to ts

Async race - ревью сделал, оценка по баллам 90
Online store - ревью сделал, оценка по баллам 165
Migration to ts - нет ПР, оценка по баллам 90

 @Danil336 отправьте работу Online store на менторскую проверку в приложении RS

**Comment by valerydluski** [comment]
@shzFas твои работы обещали проверить

**Comment by Clou2Dy** [comment]
Добрый вечер ! Не хватает 180 баллов для получения сертификата.
Все требования для получения выполнены.

Online Store: https://github.com/DocSkullka/online-store/pull/21

**Comment by dzmitryNz** [comment]
> Добрый вечер ! Не хватает 180 баллов для получения сертификата. Все требования для получения выполнены.
> 
> Online Store: [DocSkullka/online-store#21](https://github.com/DocSkullka/online-store/pull/21)

Проверю, но PR не оформлен, уже минус 10 баллов

**Comment by julia-mironova** [comment]
> @shzFas твои работы обещали проверить:
160
150
150
видно - что прогресс есть от таски к таске, знания тоже есть

**Comment by dzmitryNz** [comment]
> > Добрый вечер ! Не хватает 180 баллов для получения сертификата. Все требования для получения выполнены.
> > Online Store: [DocSkullka/online-store#21](https://github.com/DocSkullka/online-store/pull/21)
> 
> Проверю, но PR не оформлен, уже минус 10 баллов

180
