### ISSUE TITLE
Cross-Check 'webdev' - 'SuzyGRBT'.

### ISSUE THREAD

**Issue by SuzyGRBT** [rolling-scopes-school/support#86]
1. Ссылка на деплой проекта https://rolling-scopes-school.github.io/suzygrbt-JS2020Q3/webdev/
2. Ссылка на репозиторий https://github.com/rolling-scopes-school/suzygrbt-JS2020Q3
3. Самопроверка: (-2)  нет интерактивной навигации, (-2) кнопка get started (your life) не интерактивная, (-2)кнопка get started (rappresent) не интерактивная, (-2) 1/5 отсутствует, (-2) кнопки не интерактивные, (-2) текст в Implement не выделен жирным, (-2) кнопка не интерактивная, (-2) signup кнопка не интерактивная, (-9) в блоках Our Community, Implement и Sign up элементы отклоняются на более чем 5px, (-20) download и footer отсутствуют. Итого: 55 баллов.
4. Оценка из Cross check: 50+46+44+32. Итого средняя 43

P.S. Добавлю, что из 4 проверяющих контакты оставили только двое. Обратиться хотелось как раз к тем, кто пожелал остаться анонимом.

**Comment by Alexey-Koren** [comment]
Оформите апелляцию по шаблону, апелляция оформляется на всю оценку целиком. А не на каждый полученный ревью
https://docs.rs.school/#/cross-check-flow

**Comment by SuzyGRBT** [comment]
> Оформите апелляцию по шаблону, апелляция оформляется на всю оценку целиком. А не на каждый полученный ревью
> https://docs.rs.school/#/cross-check-flow

Сделано

**Comment by valerydluski** [comment]
1. Если страница открывается по указанной ссылке, и она не пустая, то ставим +20. Это означает что деплой и условия использования репозитория сделаны верно. (+20)
2. Heder: (+6)
    Панель не интерактивная (-2)
    Подсветка первой ссылки в панель не соответсвует макету (-2)
3. Your Life(+3)
    Кнопка get started должна быть интерактивной. (-2)
    Кнопки (иконки) соц. сетей должны быть интерактивными.(-2)
    Все элементы блока поплыли и но новому макету и по старому(-3)
4.Rappresent(+8)
    Кнопка get started должна быть интерактивной.(-2)
    Все элементы плывут, но в пределах 5px.
5. Our Community(+3)
  1, /, 5 должны быть раздельными элементами.(-2)
   Стрелки должны быть интерактивными.(-2)
   Все элементы блока поплыли и но новому макету и по старому(-3)
6.Implement(+1)
    В текстовом блоке есть важный текст, который выделен жирным. Для него нужно использовать логический элемент.(-2)
    Кнопка learn more должна быть интерактивной.(-2)
    Картинка не на своем месте (-2)
    Существенные отклонения всех блоков от макета (-3)
7.Sign Up(+3)
   Изображение должно быть подложено под текст.(-2)
   Галочка на зеленом фоне должна быть интерактивной.(-2)
   Ну прям со всем не как на макете(-3)
8. Download (0)
9. Footer(0)

За шрифты снимать не стал

Итого: 44 балла
