### ISSUE TITLE
 Cross-Check 'CSS-Bayan-task' - 'Alenasport'

### ISSUE THREAD

**Issue by Alenasport** [rolling-scopes-school/support#861]
Здравствуйте! Вчера при сабмите задания оказалось, что я не могу уже этого сделать, в то время как у других студентов был еще один час. Не понимаю почему мое время не совпадает с остальными, так и не разобралась. Но очень ваш прошу дать возможность все-таки получить оценку, так как это не моя вина абсолютно. Все предыдущие задания мною были выполнены. Скрины о том, что я пыталась сдать работу вовремя прилагаю. Я не самым лучшим образом справилась с заданием, но все таки это не 0 и не пропущенное задание. Зарание спасибо!
![image](https://user-images.githubusercontent.com/116220949/224841669-e47bb6c4-7c46-486a-9bc3-3a3d527e253d.png)
![image](https://user-images.githubusercontent.com/116220949/224844279-11d57ec7-9bd1-483f-b40e-0f6e72f39954.png)
![image](https://user-images.githubusercontent.com/116220949/224844655-d26dcef5-a318-4f06-9367-a34cdd200bfd.png)
![image](https://user-images.githubusercontent.com/116220949/224844708-47dc0151-f74a-4b53-a6a0-9e19c38cf3c2.png)
![image](https://user-images.githubusercontent.com/116220949/224845029-cf9130e2-f752-4493-a150-447a7b673db1.png)
![image](https://user-images.githubusercontent.com/116220949/224845153-c4c4941e-e641-44cc-bdd4-f539ec1a7c3a.png)

**Comment by valerydluski** [comment]
@Alenasport оформи issue как написано в документации

**Comment by Alenasport** [comment]
1. https://github.com/Alenasport/cssBayan/pull
2. https://github.com/alenasport
3. https://github.com/DrDiman/CSS-Bayan-task
4. https://rolling-scopes-school.github.io/checklist/
5. -
6. Ваша оценка - 97.5 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) Smooth change (transition) of the meme images and icons is done 
Отзыв: **Нет плавной смены (переходов) изображений и иконок мема**.
2) All visual effects when the cursor is hovering over the memes, when the mouse is down on a meme, and when a meme is selected are implemented 
Отзыв: **Не реализованы все визуальные эффекты при наведении курсора на мемы, при наведении мыши на мем и при выборе мема.**
3) Initially, the first meme should be expanded 
Отзыв: **Не раскрыт первый мем.**

Частично выполненные пункты:
1) The entire row (text, icon, and meme image) clickable 
Отзыв: **Кликабельный только текст.**
2) Only flexible dimensions are used (rem, em, %, vh, vw, fr and etc.). The accordion is responsive 
Отзыв: **Only flexible dimensions are used используются частично.**
Выполненные пункты:
1) Public repository with name "cssBayan" created 
Отзыв: +
2) Branch gh-pages created 
Отзыв: +
3) The "cssBayan" folder has been created in the gh-pages branch. Deploy is available via link, link example: https://${YOUR_GITHUB_NAME}.github.io/cssBayan/cssBayan/index.html 
Отзыв: +
4) There are at least 5 commits in the gh-pages branch with the history of the project development 
Отзыв: +
5) The commits are called accordingly to the guideline (https://docs.rs.school/#/git-convention), each commit contains a time-stamp. Time-stamp can be at any language. Accordingly to your time-stamp should be clear, when this commit was done: day of the week, month, day, year, time with seconds (the order can vary) e.g. Commit message example: feat: add basic page layout (Mon, Sep 13, 2021 10:25:24 PM) 
Отзыв: +
6) Pull Request from gh-pages branch to main branch is open. Pull Request name is equal to the task name. Description of the Pull Request was done accordingly to the guideline (https://docs.rs.school/#/pull-request-review-process?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr). The link to this Pull Request was submitted to the cross check form. This Pull Request was NOT merged 
Отзыв: +
7) The accordion component is centered on the screen, with equal indents on the left and right 
Отзыв: +
8) Icons, meme texts and meme images are exist 
Отзыв: +
9) Placement of the meme, icons and meme text are the same as in provided example gif images 
Отзыв: +
10) Responsive design with three breakpoints for mobile, tablet, and desktop exist. Accordion is displayed correctly at mobile 320x568, tablet 820x1180, desktop 1920x1080. (Note: breakpoints don't have to be 320x568, 820x1180, 1920x1080) 
Отзыв: +
11) Cursor over the memes (hover) effect only exists for devices that can support hover. This means that the touch device (phone, tablet) doesn't have hover effects, and desktop does have hover effects 
Отзыв: +
12) The cursor when it is hovering over the rows of the accordion is changing 
Отзыв: +
13) All blocks/parts of the accordion are in base flow of the dom elements. All elements are not positioned with top, left, right, bottom. float is not used. The value of position is only static. Note: usage of display: none is ALLOWED 
Отзыв: +
14) Pseudo-elements are not used (note 1: pseudo-classes are ALLOWED; note 2: pseudo-elements ONLY from FontAwesome are allowed) 
Отзыв: +
15) Font size is changed at each device (mobile, tablet, desktop) 
Отзыв: +

7. -

**Comment by lyutails** [comment]
@Alenasport
hey there o/
a bit incorrectly still
1. - should be the link to your deploy, not to pr (actual bayan's site url)
![image](https://user-images.githubusercontent.com/101958335/225173105-d10d4624-830f-4f41-957f-89d91bc6f809.png)
2. - should be the link to repository with the task, not to just your github
![image](https://user-images.githubusercontent.com/101958335/225173329-5f3da0df-a35e-48ff-9183-effaac61956c.png)

![image](https://user-images.githubusercontent.com/101958335/225173439-b2df7ded-e8a6-4635-9c9c-e8a1a5f369e0.png)

**Comment by Alenasport** [comment]
1. https://alenasport.github.io/cssBayan/cssBayan/index.html
2. https://github.com/Alenasport/cssBayan
3. https://github.com/DrDiman/CSS-Bayan-task
4. https://rolling-scopes-school.github.io/checklist/
5. -
6. Ваша оценка - 97.5 баллов
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
Smooth change (transition) of the meme images and icons is done
Отзыв: Нет плавной смены (переходов) изображений и иконок мема.
All visual effects when the cursor is hovering over the memes, when the mouse is down on a meme, and when a meme is selected are implemented
Отзыв: Не реализованы все визуальные эффекты при наведении курсора на мемы, при наведении мыши на мем и при выборе мема.
Initially, the first meme should be expanded
Отзыв: Не раскрыт первый мем.
Частично выполненные пункты:

The entire row (text, icon, and meme image) clickable
Отзыв: Кликабельный только текст.
Only flexible dimensions are used (rem, em, %, vh, vw, fr and etc.). The accordion is responsive
Отзыв: Only flexible dimensions are used используются частично.
Выполненные пункты:
Public repository with name "cssBayan" created
Отзыв: +
Branch gh-pages created
Отзыв: +
The "cssBayan" folder has been created in the gh-pages branch. Deploy is available via link, link example: https://${YOUR_GITHUB_NAME}.github.io/cssBayan/cssBayan/index.html
Отзыв: +
There are at least 5 commits in the gh-pages branch with the history of the project development
Отзыв: +
The commits are called accordingly to the guideline (https://docs.rs.school/#/git-convention), each commit contains a time-stamp. Time-stamp can be at any language. Accordingly to your time-stamp should be clear, when this commit was done: day of the week, month, day, year, time with seconds (the order can vary) e.g. Commit message example: feat: add basic page layout (Mon, Sep 13, 2021 10:25:24 PM)
Отзыв: +
Pull Request from gh-pages branch to main branch is open. Pull Request name is equal to the task name. Description of the Pull Request was done accordingly to the guideline (https://docs.rs.school/#/pull-request-review-process?id=%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-pull-request-pr). The link to this Pull Request was submitted to the cross check form. This Pull Request was NOT merged
Отзыв: +
The accordion component is centered on the screen, with equal indents on the left and right
Отзыв: +
Icons, meme texts and meme images are exist
Отзыв: +
Placement of the meme, icons and meme text are the same as in provided example gif images
Отзыв: +
Responsive design with three breakpoints for mobile, tablet, and desktop exist. Accordion is displayed correctly at mobile 320x568, tablet 820x1180, desktop 1920x1080. (Note: breakpoints don't have to be 320x568, 820x1180, 1920x1080)
Отзыв: +
Cursor over the memes (hover) effect only exists for devices that can support hover. This means that the touch device (phone, tablet) doesn't have hover effects, and desktop does have hover effects
Отзыв: +
The cursor when it is hovering over the rows of the accordion is changing
Отзыв: +
All blocks/parts of the accordion are in base flow of the dom elements. All elements are not positioned with top, left, right, bottom. float is not used. The value of position is only static. Note: usage of display: none is ALLOWED
Отзыв: +
Pseudo-elements are not used (note 1: pseudo-classes are ALLOWED; note 2: pseudo-elements ONLY from FontAwesome are allowed)
Отзыв: +
Font size is changed at each device (mobile, tablet, desktop)
Отзыв: +
7. -

**Comment by helenakrasnova** [comment]
коммиты после дедлайна

**Comment by Alenasport** [comment]
Да. Я пробую еще доделать до конца, когда есть время. Но тут же суть в том, что у меня не было возможности сдать по времени как у всех, а не в моей неудовлетворенности в оценке за кросс-чек. И там ничего не изменилось, кроме медиа и свг. Если бы мое время не было сокращено на час, я бы учавствовала в кросс-чеке, а может быть и с разрешения проверяющих заканчивала бы работу до 17 числа.

**Comment by helenakrasnova** [comment]
для того чтобы апелляция была рассмотрена должно быть соблюдено правило - отсутствие коммитов после дедлайна
![image](https://user-images.githubusercontent.com/44213581/225379539-b4a0bfa7-5dca-4c4e-aa16-5dc59ae85691.png)

**Comment by Alenasport** [comment]
Это ведь инструкция и апелляция касаемо полученных низких баллов. У меня же совсем другая ситуация. Это нечестно. Ок. спасибо. Очень жаль.

**Comment by helenakrasnova** [comment]
> Это ведь инструкция и апелляция касаемо полученных низких баллов. У меня же совсем другая ситуация. Это нечестно. Ок. спасибо. Очень жаль.

Это инструкция к любой апелляции, не зависимо от причины подачи, в т. ч. на будущее - если коммитаете после дедлайна - лишаетесь возможности подать апелляцию.
