### ISSUE TITLE
Cross-Check "Css Bayan" - 'KramnKat'

### ISSUE THREAD

**Issue by KramnKat** [rolling-scopes-school/support#863]
1. A link to your deployed project
    - [[link](https://github.com/)](https://kramnkat.github.io/cssBayan/cssBayan/)
2. A link to the project repository on Github.
    - [[link](https://github.com/)](https://github.com/KramnKat/cssBayan/tree/gh-pages)
3. A link to the task
    - [[link](https://github.com/)](https://github.com/DrDiman/CSS-Bayan-task)
4. A Link to the checklist for evaluating the task (if it exists)
    - [[link](https://github.com/)](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![marck 1](https://user-images.githubusercontent.com/96074077/225855846-ce7bb46c-b906-4bc2-8c7c-57ff9c79b9f1.png)
![marck 2](https://user-images.githubusercontent.com/96074077/225855891-d18919ff-187f-47a7-adc1-c6c4cf064768.png)
![mark 3](https://user-images.githubusercontent.com/96074077/225855863-b349799b-3282-4e7c-b48f-550022ee4443.png)

6. A final score after self-assessment, with comments
Score 135/140
Все пункты ТЗ  выполнены, за исключением пункта  7: All visual effects when the cursor is hovering over the memes, when the mouse is down on a meme, and when a meme is selected are implemented. Он выполнен частично (+5 баллов вместо +10).
Я не согласна с баллами проверяющего №1. Иконки у меня есть на разрешении от 1920пикселей, они появляются, когда навести на блок аккордеона (если они не появляются при разрешении 1920 необходимо выставить настройки параметра экрана в 100%, а не в 125%). Так как я выстраивала верстку по принципу mobile first эффект ховера настроен только для descktop версии, и иконки не появляются до разрешения 1920 пикселей. По пункту 8 - у меня в работе весь ряд, в том числе картинка кликлабельна.
7. A cross-check score of your Score 
128/140

**Comment by lyutails** [comment]
hey there o/
one of the criteria for an appeal to happen is a difference of 10% or more from your selfcheck
![image](https://user-images.githubusercontent.com/101958335/225917791-420f6515-f006-4d3d-a44f-4f4c1a764465.png)
your final score is 128 that is higher than 126 (140-14) (maximum score - 10%) and higher than selfcheck -10% (135 -13 = 122)
![image](https://user-images.githubusercontent.com/101958335/225919215-f1c1e276-0692-4d21-8395-9050532abd8d.png)

**Comment by helenakrasnova** [comment]
Апелляция производится только если ожидаемый вами балл и полученный по результатам кросс-чека средний балл отличаются на 10 и более процентов от максимального балла за задание.
