### ISSUE TITLE
Сross-check 'CSS-Bayan-task' 'Takethisworld'

### ISSUE THREAD

**Issue by Takethisworld** [rolling-scopes-school/support#864]
1. A link to your deployed project
    - [link]( https://takethisworld.github.io/cssBayan/)
2. A link to the project repository on Github.
    - [link](https://github.com/Takethisworld/cssBayan)
3. A link to the task
    - [link][(https://github.com/](https://github.com/DrDiman/CSS-Bayan-task))
4. A Link to the checklist for evaluating the task (if it exists)
    - Everything is done from Repository requirements and how to submit task section +30
The accordion component is centered on the screen, with equal indents on the left and right +10
Icons, meme texts and meme images are exist +5
Placement of the meme, icons and meme text are the same as in provided example gif images +5
Smooth change (transition) of the meme images and icons is done +20
Responsive design with three breakpoints for mobile, tablet, and desktop exist. Accordion is displayed correctly at mobile 320x568, tablet 820x1180, desktop 1920×1080. (Note: breakpoints don't have to be 320x568, 820x1180, 1920x1080). +10
All visual effects when the cursor is hovering over the memes, when the mouse is down on a meme, and when a meme is selected are implemented +10
The entire row (text, icon, and meme image) clickable +5
Cursor over the memes (hover) effect only exists for devices that can support hover. +10
The cursor when it is hovering over the rows of the accordion is changing +5
Only flexible dimensions are used rem, em, %, vh, vw, fr and etc... The accordion is responsive +10
All blocks/parts of the accordion are in base flow of the dom elements. All elements are not positioned with top, left, right, bottom. float is not used. The value of position is only static +5
Pseudo-elements are not used (note 1: pseudo-classes are allowed; note 2: pseudo-elements only from FontAwesome are allowed) +5
Initially, the first meme should be expanded +5
Font size is changed at each device (mobile, tablet, desktop) +5

5. A screenshot of cross-checking marks
![issue](https://user-images.githubusercontent.com/62119373/225865497-6a8f53c1-17e7-4cb1-bf9d-ca70463f0652.png)
![issue2](https://user-images.githubusercontent.com/62119373/225865502-793619ef-2614-4461-b5c2-9d64b2c331d9.png)

6. A final score after self-assessment, with comments
 135
7. A cross-check score of your Score 
135

**Comment by lyutails** [comment]
hey there o/
seems you do have commits after cross-check submit deadline
![image](https://user-images.githubusercontent.com/101958335/225910098-ba859da0-03d7-4eea-b80f-adcc557e89b3.png)
highlighted last commit time
![image](https://user-images.githubusercontent.com/101958335/225910895-8d16ea06-8bd2-46af-831d-831b9e15f68c.png)
deadline was 13.03 at 3am
![image](https://user-images.githubusercontent.com/101958335/225913141-aa2b6dfb-c65b-4b64-90d9-4e6345934f80.png)
one of the requirements for appeal to be performed
![image](https://user-images.githubusercontent.com/101958335/225913608-efa25b64-42ab-48a2-a5fe-b991fca8136e.png)

**Comment by Takethisworld** [comment]
yeah i see this task too late

**Comment by helenakrasnova** [comment]
коммиты после дедлайна

**Comment by Takethisworld** [comment]
последний проверяющий поздно поставил оценку она могла не засчитаться?

**Comment by helenakrasnova** [comment]
я не понимаю вопрос
