### ISSUE TITLE
Angular mentoring

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/support#867]
example message
your github nickname (valerydluski)
[link profile in rs-app](https://app.rs.school/profile?githubId=valerydluski)
Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) (1)

**Comment by ViktorElenich** [comment]
viktorelenich
https://app.rs.school/profile?githubId=viktorelenich
Score: 227

**Comment by Yarkin13** [comment]
Yarkin13
[link profile in rs-app](https://app.rs.school/profile?githubId=yarkin13)
Position 214 in [RS 2020 Q1](https://app.rs.school/course/score?course=rs-2020-q1)
Position 35 RSS React 2020 Q3
Position 84 NodeJS 2020 Q3

Was a mentor RS2021Q3

Have 2+ years frontend development experience

I decided most of the course myself before it started.

**Comment by Darkonic10** [comment]
1. Github nickname: [darkonic10](https://github.com/darkonic10)
2. Profile rs-app: https://app.rs.school/profile?githubId=darkonic10
3. Score: 228 after completing [stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3)

**Comment by UlianaSavi** [comment]
Hi! 
Github nickname - [UlianaSavi](https://github.com/darkonic10)
I graduated the JavaScript/Front-end course (position `130`). 
Was the lead of a team whose work is in the top of the best. 
Now I am looking for a mentor for the current course.
Three tasks are already ready for checking :)
rs app profile - [my profile](https://app.rs.school/profile?githubId=ulianasavi)
my discord - `@UlianaSavi `

**Comment by AndreiZaretski** [comment]
1. Github nickname: [andreizaretski](https://github.com/andreizaretski)
2. [link profile in rs-app](https://app.rs.school/profile?githubId=andreizaretski)
3. Position in the score: 163 in [Stage2](https://app.rs.school/course/score?course=js-fe-2022Q3)

**Comment by GuschinS** [comment]
[guschins](https://github.com/GuschinS)
[link profile in rs-app](https://app.rs.school/profile?githubId=guschins)
Position: 442 JavaScript/Front-end 2022Q3

**Comment by Sansrona** [comment]
Sansrona
https://app.rs.school/profile?githubId=sansrona
356 (JavaScript/Front-end 2022Q3)

**Comment by MarinaFando** [comment]
github: MarinaFando
rss-app: https://app.rs.school/profile?githubId=marinafando
position after stage2: 33

**Comment by Arclett** [comment]
Arclett
https://app.rs.school/profile?githubId=arclett
Position (2022Q3): 141

**Comment by Arantola** [comment]
Github nickname: Arantola
[Link profile in rs-app](https://app.rs.school/profile?githubId=arantola)
Position 251 in the score after completing [Stage2](https://app.rs.school/course/score?course=js-fe-2022Q3)

**Comment by nan0001** [comment]
github nickname - nan0001
https://app.rs.school/profile?githubId=nan0001
Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) : 223

**Comment by existanz** [comment]
existanz
https://app.rs.school/profile?githubId=existanz
237

**Comment by 9fogel** [comment]
github: [9fogel](https://github.com/9fogel) 
rs-app profile: https://app.rs.school/profile?=githubId=9fogel
score position after stage2 (2022Q3): 97

**Comment by inanimate631** [comment]
inanimate631
https://app.rs.school/profile?githubld=inanimate631
Score: 543

**Comment by BatBB** [comment]
github: [batbb](https://github.com/batbb)
rs-app profile: https://app.rs.school/profile?=githubId=batbb
Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) (525)

**Comment by AnastasiyaPoleshuk** [comment]
github: AnastasiyaPoleshuk
(https://app.rs.school/profile?githubld=AnastasiyaPoleshuk)
I finish RS React 2022 Q1 with Score: 202 and Position: 137

**Comment by sharovskiye** [comment]
github: [sharovskiye](https://github.com/sharovskiye)
https://app.rs.school/profile?githubId=sharovskiye
**JavaScript/Front-end 2021Q3** Position: 228
**React 2022 Q1** Position: 14

**Comment by multeng** [comment]
github: [multeng](https://github.com/multeng)
[https://app.rs.school/profile?githubId=multeng](https://app.rs.school/profile?githubId=multeng)
**RS 2020 Q1** Position: 235

**Comment by webbomj** [comment]
github [webbomj](https://github.com/webbomj)
[link profile in rs-app](https://app.rs.school/profile?githubId=webbomj)
RS 2022 Q3 position: 449
my [discord](@webbomj#9323)
Have a lot of work on React.

**Comment by AnnaFeona** [comment]
Github: AnnaFeona [github](https://github.com/AnnaFeona)
RSApp: [AnnaFeona](https://app.rs.school/profile?githubId=annafeona)
JavaScript/Front-end 2022Q3 position: 184

**Comment by Nikozyrev** [comment]
github nickname - nikozyrev
[link profile in rs-app](https://app.rs.school/profile?githubId=nikozyrev)
Position in the score after completing stage 2 - 355

**Comment by MonstersBY** [comment]
Github:  [monstersby](https://github.com/monstersby)
RSApp: [link](https://app.rs.school/profile?githubId=monstersby)
Position: 262

**Comment by KirillDemyanenko** [comment]
Github: KirillDemyanenko
[link profile in rs-app](https://app.rs.school/profile?githubId=kirilldemyanenko)
Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) (481)

    Missed several assignments due to a session at the university

**Comment by gutsstas** [comment]
Github: gutsstas
Profile RSApp: [gutsstas](https://app.rs.school/profile?githubId=gutsstas)
Position in the score after completing stage2: **76**

**Comment by LilithPrimary** [comment]
Github: lilithprimary
Profile: [lilithprimary](https://app.rs.school/profile?githubId=lilithprimary)
Score: 36 (but previous course)

**Comment by ShArPman13** [comment]
Github: ShArPman13
Profile RSApp: [ShArPman13](https://app.rs.school/profile?githubId=sharpman13)
Position in the score after completing stage2: 18

**Comment by YuliaSavchik** [comment]
Github: YuliaSavchik
Profile in rs-app: [yuliasavchik](https://app.rs.school/profile?githubId=yuliasavchik)
Position in the score after completing stage2: 257

**Comment by jsonstathem** [comment]
[tauadam](https://github.com/tauadam)
[link profile in rs-app](https://app.rs.school/profile?githubId=tauadam)
532

**Comment by binary-apple** [comment]
github nickname: [binary-apple](https://github.com/binary-apple)
[link profile in rs-app](https://app.rs.school/profile?githubId=binary-apple)
Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3): 219

**Comment by nike93** [comment]
GitHub: nike93
[Profile in RS-App](https://app.rs.school/profile?githubId=nike93)
Score: 142

**Comment by Dobruan** [comment]
1.Github nickname Dobruan
2. Profile rs-app - [link](https://app.rs.school/profile?githubId=dobruan)
3. I would like to have a mentor on this course, I didn't participate in JavaScript/Front-end, but have production experience.

**Comment by reznikovAndrey** [comment]
- Github: reznikovAndrey
- [Profile in RS-App](https://app.rs.school/profile?githubId=valerydluski)
- I would like to have a mentor. I didn't participate in JavaScript/Front-end course. 

P.S. Currently I work as a React developer. Experience > 1.5 years. I start study Angular, because I want to expand my vision on other frontend technologies.

**Comment by zole123** [comment]
1. Github: zole123
2. Profile in RS-App: https://app.rs.school/profile
3. I haven't participated in the latest JS course, but I have completed full JS course last year. I would like to have a mentor in Angular course.

**Comment by likurg42** [comment]
Github: @likurg42
Profile in rs-app: [rs school profile](https://app.rs.school/profile?githubId=likurg42)
Position in the score after completing stage2: 441

**Comment by Iogsotot** [comment]
Hi there,
github: [Iogsotot](https://github.com/Iogsotot)
rs-app profile: : [iogsotot](https://app.rs.school/profile?githubId=iogsotot)
Position in the score after completing[ 2020Q3 stage 2](https://app.rs.school/course/score?course=js-2020-q3) (136)

**Comment by maksim-volkmann** [comment]
Github: @maksim-volkmann
[Profile in RS-App](https://app.rs.school/profile?githubId=maksim-volkmann)
[I completed the course in early 2022, but didn't go for angular that time. ](https://app.rs.school/course/score?course=js-fe-lt)

**Comment by user-of-github** [comment]
[Updated: Mentor from stage 2 agreed to work with me]

GitHub: @user-of-github
RS App profile: https://app.rs.school/profile?githubId=user-of-github
Position in the score after completing stage 2 (2022Q3): **272**

**Comment by jerubrin** [comment]
github nickname: **jerubrin**
[link profile in rs-app](https://app.rs.school/profile?githubId=jerubrin)
Position in the score after completing stage 2 (2022Q3): 11

**Comment by Quarro42** [comment]
Github: quarro42
[RS-App Profile](https://app.rs.school/profile?githubId=quarro42)
JavaScript/Front-end 2021Q1 position: 354

**Comment by ltidin** [comment]
Github: ltidin
[Profile in RS-App](https://app.rs.school/profile?githubId=ltidin)
I would like to have a mentor. I didn't participate in JavaScript/Front-end course. Working as an ABAP developer

**Comment by amgSTRIDeR** [comment]
github nickname [amgstrider](https://github.com/amgSTRIDeR)
[link profile in rs-app](https://app.rs.school/profile?githubId=amgstrider)
Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) (275)

**Comment by PavelArabei** [comment]
Github: pavelarabei
RS App profile:  https://app.rs.school/profile?githubId=pavelarabei
JavaScript/Front-end 2022Q3 position: 365

**Comment by Baxromxoja16** [comment]
Github: [baxromxoja16](https://github.com/baxromxoja16)
RS App profile: https://app.rs.school/profile?githubId=baxromxoja
JavaScript/Front-end 2022Q3 position: 506

**Comment by AndrewMotevich** [comment]
github: [AndrewMotevich](https://github.com/AndrewMotevich)
[rs-app-profile](https://app.rs.school/profile?githubId=andrewmotevich)
JavaScript/Front-end 2021Q3 (position: 335)

**Comment by tedgregory** [comment]
github [tedregory](https://github.com/tedgregory)
[Rs App link](https://app.rs.school/profile?githubid=tedgregory)

Rs js2022q1 **188** (3453pts)

I'd be glad to get a feedback on my tasks and some advise, just that. I don't feel getting a cert this time

**Comment by AV-Shell** [comment]
github: [AV-Shell](https://github.com/AV-Shell)
[link profile in rs-app](https://app.rs.school/profile?githubId=av-shell)
Position 16 in [JS/FE 2020 Q3](https://app.rs.school/course/score?course=js-2020-q3)

**Comment by aleshkinpaul** [comment]
1. [aleshkinpaul](https://github.com/aleshkinpaul)
2. [link profile in rs-app](https://app.rs.school/profile?githubId=aleshkinpaul)
3. Position in the score after completing 2021Q3 [stage 2](https://app.rs.school/course/score?course=js-fe-2021Q3) (262)

**Comment by SergeyMikhalkin** [comment]
Github nickname: [sergeyMikhalkin](https://github.com/SergeyMikhalkin)
RS school account: [link](https://app.rs.school/profile?githubId=sergeymikhalkin)
Position in the score after completing[ stage 2 (2022 Q1)](https://app.rs.school/course/score?course=js-fe-2022Q1) (525)

**Comment by JustinReed713** [comment]
1. Github nickname: [justinreed713](https://github.com/JustinReed713);
2. [RS School profile link](https://app.rs.school/profile?githubId=justinreed713);
3. I didn't participate in JavaScript/Front-end course;

**Comment by anjinsan132131** [comment]
Github nickname: [anjinsan132131](https://github.com/anjinsan132131)
RS school account: [link](https://app.rs.school/profile?githubId=anjinsan132131)
Position in the score after completing stage 2 (JavaScript/Front-end 2022Q3):  547

**Comment by clymenul** [comment]
github: [clymenul](https://github.com/clymenul)
[rss profile](https://app.rs.school/profile?githubId=clymenul)
this is my first course, but I have some frontend experience

**Comment by danikman89** [comment]
1. danikman89
2. https://app.rs.school/profile
3. 2022Q1 (393)

**Comment by stealthybunny** [comment]
1. GIthub nickname:   _**[stealthybunny](https://github.com/stealthybunny)**_
2. RS School profile:   _**[Link](https://app.rs.school/profile?githubId=stealthybunny)**_
3. Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) --- _**[351](https://app.rs.school/certificate/mw33cc2g)**_

**Comment by ankhly** [comment]
Github nickname: ankhly
https://app.rs.school/profile?githubId=ankhly
Position in the score after completing stage 2 - JavaScript/Front-end 2022Q3  (372)

**Comment by AxelKhr** [comment]
1. Github nickname: axelkhr
2. [Link profile in rs-app
](https://app.rs.school/profile?githubId=axelkhr)
3. Position in the score after completing [stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) (72)

**Comment by Guramiart** [comment]
Github: [guramiart](https://github.com/Guramiart)
[link profile in rs-app](https://app.rs.school/profile?githubId=guramiart)
Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) (226)

**Comment by webkwondo** [comment]
webkwondo
https://app.rs.school/profile?githubId=webkwondo
Position: 81

**Comment by top-aleksei** [comment]
top-aleksei
Profile rs-app: https://app.rs.school/profile?githubId=top-aleksei
position: 16

**Comment by Yura703** [comment]
1. Github: [yura703](https://github.com/Yura703)
2. [Link profile in rs-app](https://app.rs.school/profile?githubId=yura703)
3.  JavaScript/Front-end 2022Q1 - Position: 129

**Comment by svetulka** [comment]
1. Github: [svetulka](https://github.com/svetulka)
2. [Link profile in rs-app](https://app.rs.school/profile?githubId=svetulka)
3. JS/FE 2020 Q3 - Position: 1129

**Comment by hel-sidoruk** [comment]
1. Github: https://github.com/hel-sidoruk/
2. Profile: https://app.rs.school/profile?githubId=hel-sidoruk
3. Position: 77

**Comment by ZhEkA717** [comment]
1. Github: https://github.com/zheka717
2. Profile: https://app.rs.school/profile?githubld=zheka717
3. Position: 101

**Comment by sqwezzy33333** [comment]
Github: https://github.com/sqwezzy33333
Profile: https://app.rs.school/profile?githubld=sqwezzy33333
Position: JavaScript/Front-end 2022Q3 - 562

**Comment by bvfromru** [comment]
**bvfromru**
https://app.rs.school/profile?githubId=bvfromru
JavaScript/Front-end 2021Q3: Position: **73**
React 2022 Q3: Position: **115**
NodeJS 2022 Q4: Position: **31**

Currently working as a React developer, but curious to study Angular as well. Please, be my mentor! ;)

**Comment by MikAleinik** [comment]
1. Git nickname: mikaleinik
2. RS profile: https://app.rs.school/profile?githubId=mikaleinik
3. Position: 401 (JavaScript/Front-end 2022Q1)

**Comment by mlatysheva** [comment]
Hi, dear mentor!
1. My git profile is: https://github.com/mlatysheva
2. RS profile is: https://app.rs.school/profile?githubId=mlatysheva
3. Position in Frontend stage 2 (Q3-2021): 296
4. Position in Node.js (Q4-2022): 55

**Comment by behzodjon** [comment]
Hi, dear mentor!

1. My GitHub profile: https://github.com/behzodjon
2. RS profile: https://app.rs.school/profile?githubId=behzodjon
3. Position in JS/FE Course EN 2022 - 41
4. My discord: Behzodjon(behzodjon)#0337

I work as a Vue js developer, but I'm really interested in learning Angular. Please, be my mentor!

**Comment by Zmicer-Yafremau** [comment]
1. My GitHub profile: [Zmicer-Yafremau](https://github.com/Zmicer-Yafremau)
2. RS profile: [https://app.rs.school/profile?githubId=Zmicer-Yafremau](https://app.rs.school/profile?githubId=Zmicer-Yafremau)

3. Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) : **51**

**Comment by KarimKoshmagambetov** [comment]
Github: KarimKoshmagambetov
Profile: [https://app.rs.school/profile?githubld=karimkoshmagambetov](url)
Position: n/a

**Comment by andreiChabatul** [comment]
Github: https://github.com/andreiChabatul
Profile: https://app.rs.school/profile?githubId=andreichabatul
Position: 148

**Comment by AnnaKolesnikova** [comment]
AnnaKolesnikova
https://app.rs.school/profile?githubId=annakolesnikova
Position: 57

**Comment by proboynick** [comment]
github nickname: proboynick
[link profile in rs-app](https://app.rs.school/profile?githubId=proboynick)
Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) (366)

**Comment by PartyZzzan77** [comment]
🧑🏻‍💻 **GitHub nickname:** Mitya#1073
👨🏻‍🎓 [**Profile**](https://app.rs.school/profile)
🔝 **Position stage 2:** (100)

**Comment by vladislava96** [comment]
**Github:** https://github.com/vladislava96
**Profile:** https://app.rs.school/profile?githubId=vladislava96
**Position:** 253

**Comment by TerebinovSergey** [comment]
Github: https://github.com/terebinovsergey
Profile: https://app.rs.school/profile?githubId=terebinovsergey
Position: 296 (JavaScript/Front-end 2022Q3)

**Comment by AYaki-coder** [comment]
github: [ayaki-coder](https://github.com/ayaki-coder)
[link profile in rs-app](https://app.rs.school/profile?githubId=ayaki-coder)
Position 14 in [JS/FE 2020 Q3](https://app.rs.school/course/score?course=js-2020-q3)

**Comment by Arina2246** [comment]
Arina2246
https://app.rs.school/profile?githubId=arina2246
Position: 354 in JS/FE 2022Q1

**Comment by alexbrestby** [comment]
Github: https://github.com/alexbrestby
Profile: https://app.rs.school/profile?githubId=alexbrestby
JavaScript/Front-end 2022Q3 Position: 350

**Comment by azozulya** [comment]
GitHub: https://github.com/azozulya
https://app.rs.school/profile?githubId=azozulya
JavaScript/Front-end 2022Q1 Position 190

**Comment by Olena-web** [comment]
Olena - web.            GitHub - https://github.com/rolling-scopes-school/olena-web-ANGULAR2023Q1.   JavaScript/Front-end 2021Q3 position 291  
 React 2022 Q1 position 200

**Comment by KirillMalko** [comment]
- My github [KirillMalko]( https://github.com/KirillMalko )
- RS profile: [KIRILL MALKO](https://app.rs.school/profile?githubId=kirillmalko)
- Position in the score: 314
- I really want to get a mentor who, based on his experience, will help to master a new skill. Ready to work hard

**Comment by Milena-Belianova** [comment]
Github: [milena-belianova](https://github.com/milena-belianova)
RS profile: https://app.rs.school/profile?githubId=milena-belianova
JavaScript/Front-end 2022Q1 position: 132
React 2022 Q3 position: 230

**Comment by tyronmaster** [comment]
tyronmaster
- [x] [Rs-app Profile](https://app.rs.school/profile?githubId=tyronmaster)
- [x] Position in the score after completing[ stage 2](https://app.rs.school/course/student/dashboard?course=js-fe-en-2022q3) (27)

**Comment by LoginovskyMax** [comment]
Github: [LoginovskyMax](https://github.com/loginovskymax)
RS profile: https://app.rs.school/profile?githubId=LoginovskyMax 
JavaScript/Front-end 2022Q3 position: 22

**Comment by KarUladz** [comment]
Github: [Kornull](https://github.com/Kornull)
RS Profile: [link](https://app.rs.school/profile?githubId=kornull)
JavaScript/Front-end 2022Q1 position: 249
React 2022 Q3 position 101

**Comment by mironovahl** [comment]
Github: [mironovahl](https://github.com/mironovahl)
RS Profile: [mironovahl](https://app.rs.school/profile?githubId=mironovahl)
RS 2020 Q1 position 300
RSS React 2020 Q3 position 12

**Comment by yuliya-kopichenko** [comment]
- [My github](https://github.com/Julia-Kopichenko)

- [My RS school private repository](https://github.com/rolling-scopes-school/julia-kopichenko-JSFEEN2022Q3)

- [My profile in rs-app](https://app.rs.school/profile)

- JS/FE Course EN 2022Q3 posision **4**

**Comment by Alexkhokhlow** [comment]
Github nickname: [Alexkhokhlow](https://github.com/Alexkhokhlow)
Profile rs-app: [alexkhokhlow](https://app.rs.school/profile?githubId=alexkhokhlow)
Score: 84 after completing [JavaScript/Front-end 2022Q3](https://app.rs.school/course/score?course=js-fe-2022Q3)

**Comment by Nebesnaya94** [comment]
Github: [Nebesnaya94](https://github.com/nebesnaya94)
RS Profile: [nebesnaya94](https://app.rs.school/profile?githubId=nebesnaya94)
JavaScript/Front-end 2022Q3 position: 539

**Comment by Grif-Rift-BY** [comment]
Github: [Grif-Rift-BY](https://github.com/Grif-Rift-BY)
RS Profile: [Grif-Rift-BY](https://app.rs.school/profile?githubId=grif-rift-by)
JavaScript/Front-end 2022Q3 position: 149.

**Comment by tokensm1x** [comment]
[GIT PROFILE](https://github.com/tokensm1x)
[RS PROFILE](https://app.rs.school/profile)
JS/FE 2020 Q3 position: 423
NodeJS 2022 Q4 position: 23

**Comment by shamkolovich95** [comment]
Github: shamkolovich95
RS Profile: https://app.rs.school/profile
JavaScript/Front-end 2022Q3 position: 340.

**Comment by shtag** [comment]
Github: [shtag](https://github.com/shtag)
RS Profile: [RS profile](https://app.rs.school/profile?githubId=shtag)
JS/FE 2022Q3 position: 389.

**Comment by sensaur** [comment]
Github: [sensaur](https://github.com/sensaur)
RS Profile: [sensaur](https://app.rs.school/profile?githubId=sensaur)
JS/FE 2022Q3 position: 357.

**Comment by Sid-inc** [comment]
Github: [Sid-inc](https://github.com/sid-inc)
RS Profile: [Nikolay Ionov](https://app.rs.school/profile?githubId=sid-inc)
JS/FE 2022Q3 position: 442.

**Comment by andreevgs** [comment]
RS Profile: [andreevgs](https://app.rs.school/profile?githubId=andreevgs)

**Comment by Philonena** [comment]
Github: [Philonena](https://github.com/Philonena)
RS Profile: [Natalia Chinarova](https://app.rs.school/profile?githubId=philonena)
JS/FE 2022Q1 position: 51.

**Comment by milana1726** [comment]
Github: [milana1726](https://github.com/milana1726)
RS Profile: [milana1726](https://app.rs.school/profile)
JS/FE Course EN 2022Q3: position 6

**Comment by Pavlkan** [comment]
Github: [ Pavlkan ](https://github.com/Pavlkan)
RS Profile: https://app.rs.school/profile?githubld=inanimate631
Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) (48)

**Comment by max-romanov** [comment]
My github nickname (max-romanov)
[link profile in rs-app](https://app.rs.school/profile?githubId=max-romanov)
Position in the score after completing [stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) (570)

**Comment by viktoridanilova** [comment]
My github nickname (viktoridanilova)
https://app.rs.school/profile
Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) (414)

**Comment by viktoridanilova** [comment]
My github nickname (viktoridanilova)
https://app.rs.school/profile
Position in the score after completing[ stage 2](https://app.rs.school/course/score?course=js-fe-2022Q3) (414)

**Comment by voganame** [comment]
Need a mentor please!
https://app.rs.school/profile?githubId=voganame
Score: 0

**Comment by Madina1408** [comment]
I am new to angular, a mentor would be very helpful!
my github nickname (madina1408)
[link profile in rs-app](https://app.rs.school/profile?githubId=madina1408)
newly joined to the course: score:75
position:158

**Comment by dveever** [comment]
My GitHub nickname (dveever)
[https://app.rs.school/profile?githubId=dveever](https://app.rs.school/profile?githubId=dveever)
score: 138
position: 75

**Comment by zole123** [comment]
Github: zole123
Profile in RS-App: https://app.rs.school/profile
I haven't participated in the latest JS course, but I have completed full JS course last year. I would like to have a mentor in Angular course.

**Comment by redsnst** [comment]
[link profile in gitHub](https://github.com/redsnst)
[link profile in rs-app](https://app.rs.school/profile?githubId=redsnst)
Position in the score after completing (--)
