### ISSUE TITLE
Cross-Check Shelter - yury0605-JSFE2023Q1

### ISSUE THREAD

**Issue by yury0605** [rolling-scopes-school/support#869]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/yury0605-JSFE2023Q1/shelter/main.html)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/yury0605-JSFE2023Q1/pull/3)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md)

Здравствуйте!
Моя проблема в том, что я делал сабмит вовремя, но он не попал в систему. Хотя я видел сообщение что сабмит отправлен (это было в пятницу). Сегодня зашел делать кросс-чек, то не обнаружил работ на проверку, и соответственно увидел что сабмит пропущен.
Не знаю в чем проблема: системе, моем браузере или интернет-соединении. В любом случае так получилось.
Могли бы вы проверить мою работу и выставить хотя бы половину баллов за нее? Буду очень признателен.

**Comment by lyutails** [comment]
hey there o/

change please your issue's name to the required
Cross-Check 'название таска' - 'Ваше имя на Github'
https://docs.rs.school/#/cross-check-flow?id=Апелляция

also make sure you doesn't have commits after deadline

**Comment by yury0605** [comment]
Hello!
Done!
thank you for  your attention
yes, i haven't commits after deadline

**Comment by helenakrasnova** [comment]
отредактируйте ишью согласно правилам в документации [https://docs.rs.school/#/cross-check-flow?id=Апелляция](https://docs.rs.school/#/cross-check-flow?id=%D0%90%D0%BF%D0%B5%D0%BB%D0%BB%D1%8F%D1%86%D0%B8%D1%8F)

**Comment by yury0605** [comment]
Прошу проверить мою работу, так как пропустил сабмит по технической причине (не сработал). Последний коммит ветки с деплоем был выполнен до дедлайна. Спасибо.

1. Ссылка на деплой проекта:
    - [link](https://rolling-scopes-school.github.io/yury0605-JSFE2023Q1/shelter/main.html)
2. Ссылка на репозиторий с проектом на GitHub:
     - [link](https://github.com/rolling-scopes-school/yury0605-JSFE2023Q1)
3. Ссылка на задание:
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md)
4. Скриншот с оценками за cross-check: не проверял, так как пропустил сабмит.
5. Оценка в результате самопроверки с ее аргументацией (есть в Pull-Request):
  - [link](https://github.com/rolling-scopes-school/yury0605-JSFE2023Q1/pull/3)
6. Балл за cross-check из вашего Score: отсутствует, так как пропустил сабмит.

**Comment by helenakrasnova** [comment]
1) перенести описание из комментария в описание ишью
2) отредактировать название ишью согласно документации
3) Оценка в результате самопроверки с ее аргументацией (есть в Pull-Request): - описать в ишью, т к активисты не имеют доступа к вашему приватному репозиторию

**Comment by yury0605** [comment]
Здравствуйте!
1. Описание из комментария в пулл-реквесте, если правиьлно понял?
2. Правильно ли понял, что название ишью неправильно в том что нужно добавить к имени на Github название курса? Если нет, то поясните пожалуйста

Обновленное описание ишью делаю отдельным комментом

**Comment by yury0605** [comment]
1. Ссылка на деплой проекта:
    - [link](https://rolling-scopes-school.github.io/yury0605-JSFE2023Q1/shelter/main.html)
2. Ссылка на репозиторий с проектом на GitHub:
     - [link](https://github.com/rolling-scopes-school/yury0605-JSFE2023Q1)
3. Ссылка на задание:
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md)
4. Скриншот с оценками за cross-check: не проверял, так как пропустил сабмит.
5. Оценка в результате самопроверки с ее аргументацией (есть в Pull-Request):
  - [link](https://github.com/rolling-scopes-school/yury0605-JSFE2023Q1/pull/3)
6. Балл за cross-check из вашего Score: 

- Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md
- Screenshot:
![Screenshot_33443](https://user-images.githubusercontent.com/122359936/227460414-5d73d54e-539c-41de-a103-a0ccbd42eb65.jpg)   
- Deploy: https://rolling-scopes-school.github.io/yury0605-JSFE2023Q1/shelter/main.html
- Done 24.03.2023 / deadline 28.03.2023
- Score: 100 / 100

- Страница Main (60)
- [x] Проверка верстки +7
- [x] верстка страницы валидная: для проверки валидности вёрстки используйте сервис https://validator.w3.org/ . +4
- [x] Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
- [x] логотип в хедере состоит из текстовых элементов +1
- [x] страница содержит ровно один элемент <h1> +1
- [x] добавлен favicon +1
- [x] Вёрстка соответствует макету +35
- [x] блок <header> +5
- [x] блок Not only +5
- [x] блок About +5
- [x] блок Our Friends +5
- [x] блок Help +5
- [x] блок In addition +5
- [x] блок <footer> +5
- [x] Требования к css +6
- [x] для позиционирования элементов блока Help использована сеточная верстка (flexbox или grid) +2
- [x] при уменьшении масштаба страницы браузера или увеличении ширины страницы (>1280px) - [x] вёрстка размещается по центру, а не сдвигается в сторону и не растягивается по всей ширине +2
- [x] фоновый цвет тянется на всю ширину страницы +2
- [x] Интерактивность элементов +12
- [x] элемент About the Shelter в навигации подсвечен и неинтерактивен, остальные элементы навигации интерактивны +2
- [x] каждая карточка с питомцем в блоке Our Friends интерактивна при наведении на любую область этой карточки +2
- [x] плавная прокрутка по якорям +2
- [x] выполняются все ссылочные связи согласно Перечню ссылочных связей для страницы Main +2
- [x] выполнена интерактивность ссылок и кнопок. Интерактивность заключается не только в - [x] изменении внешнего вида курсора, например, при помощи свойства cursor: pointer, но и в использовании и других визуальных эффектов, например, изменение цвета фона или цвета шрифта, согласно стайлгайду в макете. Если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета +2
- [x] обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике, не влияющее на соседние элементы +2

- Страница Pets (40)
- [x] Проверка верстки +7
- [x] верстка страницы валидная: для проверки валидности вёрстки используйте сервис https://validator.w3.org/ . +4
- [x] Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
- [x] логотип в хедере состоит из текстовых элементов +1
- [x] страница содержит ровно один элемент <h1> +1
- [x] добавлен favicon +1
- [x] Вёрстка соответствует макету +15
- [x] блок <header> +5
- [x] блок Our Friends +5
- [x] блок <footer> +5
- [x] Требования к css +4
- [x] при уменьшении масштаба страницы браузера или увеличении ширины страницы (>1280px) вёрстка размещается по центру, а не сдвигается в сторону и не растягивается по всей ширине +2
фоновый цвет тянется на всю ширину страницы +2
- [x] Интерактивность элементов +14
- [x] элемент Our pets в навигации подсвечен и неинтерактивен, остальные элементы навигации интерактивны +2
- [x] доступные кнопки пагинации (вправо) активны, недоступные (влево) - неактивны (disabled) +2
- [x] каждая карточка с питомцем в блоке Our Friends интерактивна при наведении на любую область этой карточки +2
- [x] плавная прокрутка по якорям +2
- [x] выполняются все ссылочные связи согласно Перечню ссылочных связей для страницы Pets +2
- [x] выполнена интерактивность ссылок и кнопок. Интерактивность заключается не только в изменении внешнего вида курсора, например, при помощи свойства cursor: pointer, но и в - [x] - - [x] использовании и других визуальных эффектов, например, изменение цвета фона или цвета шрифта, согласно стайлгайду в макете. Если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета +2
- [x] обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике, не влияющее на соседние элементы +2

**Comment by helenakrasnova** [comment]
посмотрим логи, действительно ли был сабмит

**Comment by yury0605** [comment]
ок спасибо
также я не утверждаю что проблема в аппе, возможно дело в браузере, или интернет-соединении.. потому что на офисе где сабмитил слезы а не интернет, но нет другого тут 
![Screenshot_36](https://user-images.githubusercontent.com/122359936/229084466-3c83d580-d364-449a-b6fa-b952217971d9.jpg)

помню что заходил его делал) теперь буду заходить проверять, или скринить.. 
буду признателен хотя бы за половину баллов, учитывая что кросс-чек пропустил.

**Comment by yury0605** [comment]
Также хочу уточнить, могу ли вторую часть замержить не в Shelter, а создать отдельную ветку, например Shelter-2-Merge? Чтобы засабмитить вторую часть, и оставалась возможность проверить первую. После проверки сделаю мерж в Shelter, как это требуется в задании. Спасибо

**Comment by valerydluski** [comment]
сабмита не было
