### ISSUE TITLE
Cross-Check 'webdev' - 'Dmitry-Sokolovsky'

### ISSUE THREAD

**Issue by Dmitry-Sokolovsky** [rolling-scopes-school/support#87]
Ссылка на деплой проекта https://rolling-scopes-school.github.io/dmitry-sokolovsky-JS2020Q3/webdev/
Ссылка на репозиторий https://github.com/rolling-scopes-school/dmitry-sokolovsky-JS2020Q3

Оценка согласно самопроверке 100. Все требования к таску выполнены в полном объеме, все блоки совпадаю с макетом согласно PerfectPixel.

**Первая апелляция
 coolcooo 
Score: 94**
Деплой выполнен верно +20
header: +6
Заголовок webdev не в хедере, на макете он должен быть скрыт -2балла
Первый элемент не подсвечен -2балла
Остальные отклонения укладываются в 5px
Your Life: +8
h1 заголовок виден, не на том месте -2 балла
Rappresent+10
Our Community:+10
Implement:+10
Sign Up: +10
Download: +10
Footer:+10
**Мой комментарий:** в задании сказано что: На странице обязательно должен присутствовать один элемент h1. Расположите его на свое усмотрение. Внутри должен быть текст webdev.  элемент h1 и расположен на мое усмотрение с нужным содержимым. Ни где не сказано что он должен быть скрытым.

**Втора апелляция 
maxroker 
Score: 90**
Цвет  ВСЕХ кнопок при наведении не соответстует шаблону. 
Стрелочки в слайдере должны менять опасити на 0.5, а не цвет заднего фона. 
Фраза "YOUR LIFE IS WEBDEV" уже содержит в себе слово "WEBDEV", ее и нужно было взять в элемент h1 (не добавляя при этом дополнительный элемент на страницу).
**Мой комментарий:** в задании не сказано что интерактивные элементы должны строго соответствовать шаблону а сказано что: "Интерактивный» означает, что у элемента появляется визуальный эффект или анимация (**на ваше усмотрение**: анимация курсора, изменение цвета заднего фона, затемнение, нижнее подчеркивание, изменение шрифта) при каких-либо действиях пользователя, например, при наведении курсора. " Четко прописано что вид анимации, а значит и цвета на наше усмотрение.
Замечание по элементу h1 описал в первой апелляции.

**Третья апелляция 
 fourlena 
Score: 83**
+ 20: сайт есть и он открывается;
+ 10: блок header есть;
(- 2: цвет подчёркивания интерактивного меню не соответствует макету)
+ 10: блок your-life есть;
(- 2: цвет кнопки не соответствует макету)
+ 10: блок rappresent есть;
(- 2: цвет кнопки не соответствует макету)
+ 10: блок our-community есть;
(- 2: нет opacity на стрелках при наведении)
+ 10: блок implement есть;
(- 2: цвет кнопки не соответствует макету)
+ 10: блок subscribe есть;
(- 2: цвет кнопки не соответствует макету)
+ 10: блок download есть;
(- 2: цвет кнопки не соответствует макету)
+ 10: блок footer есть;
(- 3: размер вертикальной полосы  не соответствует )
**Мой комментарий:** в задании не сказано что интерактивные элементы должны строго соответствовать шаблону а сказано что: "Интерактивный» означает, что у элемента появляется визуальный эффект или анимация (**на ваше усмотрение**: анимация курсора, изменение цвета заднего фона, затемнение, нижнее подчеркивание, изменение шрифта) при каких-либо действиях пользователя, например, при наведении курсора. " Четко прописано что вид анимации, а значит и цвета на наше усмотрение.
Замечание по элементу h1 описал в первой апелляции.

**Comment by Alexey-Koren** [comment]
Нашёл ваш балл в скоре. У вас 91 балл.
Ваша апелляция не подходит под правила, прочитайте пункт 4.
В разделе про апелляции https://docs.rs.school/#/cross-check-flow

Закрываю
