### ISSUE TITLE
Cross-Check "React. Forms" - kkolite

### ISSUE THREAD

**Issue by kkolite** [rolling-scopes-school/support#870]
1. A link to your deployed project
    - [PR](https://github.com/kkolite/react-task/pull/2)
2. A link to the project repository on Github.
    - [Repo](https://github.com/kkolite/react-task/tree/form)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/react/modules/module02)
4. A Link to the checklist for evaluating the task (if it exists)
    - No
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/102036252/228942237-17e8f3e1-e946-4484-bd1c-e43242f7a3c7.png)
![image](https://user-images.githubusercontent.com/102036252/228942257-a5c6fb46-a8b1-42e0-b371-93a77e618577.png)
![image](https://user-images.githubusercontent.com/102036252/228942273-bfcac602-2d08-4359-9c85-fce6b26ac0e0.png)
![image](https://user-images.githubusercontent.com/102036252/228942398-f8f67a29-651e-44b2-94cf-ef2d8ad595e7.png)

6. A final score after self-assessment, with comments
- 15, все пункты по тз выполнены. Основная проблема в том, что проверяющий находил ошибки откуда только можно. Признаю, работа местами неидеальная, например, я сам себе сделал подставу с тестами апишки. Но снимать баллы за закомментированный onChange (хотя за них снимать не надо, у меня все на рефах), валидацию на первую большую букву и прочее не уместно в данной работе. 
7. A cross-check score of your Score
- 14

**Comment by helenakrasnova** [comment]
1) жалобы на кросс-чек реакта: https://forms.gle/RyBbCH8qoBJfVBEp6
2) Апелляция производится только если ожидаемый вами балл и полученный по результатам шага 4 средний балл отличаются на 10 и более процентов от максимального балла за задание
