### ISSUE TITLE
Cross-Check shelter. week-1 - makishimago-JSFE2023Q1

### ISSUE THREAD

**Issue by MakishimaGo** [rolling-scopes-school/support#872]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/makishimago-JSFE2023Q1/Shelter/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/makishimago-JSFE2023Q1)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://app.rs.school/course/student/cross-check-submit?course=js-fe-2023Q1&taskId=2533)
5. A screenshot of cross-checking marks:
![image](https://user-images.githubusercontent.com/105166989/229029887-804a7ea0-d6d3-4e41-a65e-a0a2990f9216.png)
![image](https://user-images.githubusercontent.com/105166989/229030544-a41ab297-6f5b-4145-8365-a95613508a3c.png)
![image](https://user-images.githubusercontent.com/105166989/229030574-729644c6-b27f-4d1e-bfd9-ca1f9b6fc126.png)
![image](https://user-images.githubusercontent.com/105166989/229030605-bd22f8a5-d624-4066-ba13-4173d9c2203f.png)

6. A final score after self-assessment, with comments: 100/100

7. A cross-check score of your Score: 85/100

**Comment by helenakrasnova** [comment]
коммиты после дедлайна
