### ISSUE TITLE
Cross-Check 'Shelter.Desktop' 'maxonchikoni'

### ISSUE THREAD

**Issue by maxonchikoni** [rolling-scopes-school/support#873]
1. https://rolling-scopes-school.github.io/maxonchikoni-JSFE2023Q1/shelter/index.html
2. https://github.com/rolling-scopes-school/maxonchikoni-JSFE2023Q1/pull/2
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md
4. https://rolling-scopes-school.github.io/checklist/
5. ![image](https://user-images.githubusercontent.com/124879785/229064817-548073d1-9c72-4776-8f4f-c7e5a2a60332.jpeg)![image](https://user-images.githubusercontent.com/124879785/229064509-f1893bb7-16a6-4cba-9ecc-afbe4058398e.jpeg)

6. Кнопка Get to know the rest должна вести на страницу Pets, сейчас ведет на главную ; на элемент 'Our pets' навешана ссылка, ее там не должно быть 97/100  

7. ![image](https://user-images.githubusercontent.com/124879785/229066469-c4f10e06-8939-43d9-b9a5-7a8e02becdf6.jpeg)

**Comment by maxonchikoni** [comment]
В 5 пункте случайно прикрепил 2 одинаковых фото, вот недостающее: 

![image](https://user-images.githubusercontent.com/124879785/229067084-31c42f37-21b8-47cd-9fac-6b7f5d539760.jpeg)

**Comment by helenakrasnova** [comment]
В требованиях к заданию сказано что необходимо засабмитить ссылку на деплой а не на пулл реквест
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter.md
<img width="553" alt="Screenshot_3" src="https://user-images.githubusercontent.com/44213581/229091434-46acb634-cd47-4e5b-9cca-10f59f828b91.png">
Балл за cross-check из вашего Score. - балл который вы получили за текущее задание, пункт 7
