### ISSUE TITLE
Cross-Check 'Shelter. Desktop' - 'Lina0906'.

### ISSUE THREAD

**Issue by Lina0906** [rolling-scopes-school/support#874]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/lina0906-JSFE2023Q1/shelter/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/lina0906-JSFE2023Q1)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/117985186/229104393-0b73bd7c-f137-4fb7-abe5-dc64f6f330f3.png)
![Rew2](https://user-images.githubusercontent.com/117985186/229105295-5c0b679e-24db-48de-8510-dc5c4f8b9e15.png)
![Rew3](https://user-images.githubusercontent.com/117985186/229105666-8fba1968-63be-45af-a68c-49aa22886b13.png)

6. A final score after self-assessment, with comments
Self-assessment 56
Comments:
Выполнена только страница Main

Страница Main (60)
Невыполненные пункты:
1. Элемент About the Shelter в навигации подсвечен и неинтерактивен, остальные элементы навигации интерактивны +2/0
Отзыв: coursor: pointer

Частично выполненные пункты:
2. Выполняются все ссылочные связи согласно [Перечню ссылочных связей] для страницы Main +2/1
Отзыв: Кнопка Make a friend никуда не ведет
3. Выполнена интерактивность ссылок и кнопок. Интерактивность заключается не только в изменении внешнего вида курсора, например, при помощи свойства cursor: pointer, но и в использовании и других визуальных эффектов, например, изменение цвета фона или цвета шрифта, согласно стайлгайду в макете. Если в макете стили не указаны, реализуете их по своему усмотрению, руководствуясь общим стилем макета +2/1
Отзыв: Ссылки в футере и лого не интерактивны

Выполненные пункты:
Проверка верстки +7:

- верстка страницы валидная: для проверки валидности вёрстки используйте сервис https://validator.w3.org/ . +4/4
Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
- логотип в хедере состоит из текстовых элементов +1/1
- страница содержит ровно один элемент <h1> +1/1
- добавлен favicon +1/1
Вёрстка соответствует макету +35:

блок <header> +5/5
блок Not only +5/5
блок About +5/5
блок Our Friends +5/5
блок Help +5/5
блок In addition +5/5
блок <footer> +5/5
Требования к css +6
- для позиционирования элементов блока Help использована сеточная верстка (flexbox или grid) +2/2
- при уменьшении масштаба страницы браузера или увеличении ширины страницы (>1280px) вёрстка размещается по центру, а не сдвигается в сторону и не растягивается по всей ширине +2/2
- фоновый цвет тянется на всю ширину страницы +2/2
Интерактивность элементов +12:
- каждая карточка с питомцем в блоке Our Friends интерактивна при наведении на любую область этой карточки +2
- плавная прокрутка по якорям +2/2
- обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике, не влияющее на соседние элементы +2/2

8. A cross-check score of your Score 
48 
![image](https://user-images.githubusercontent.com/117985186/229109293-d247fc88-d4af-4802-afff-be6b26eafd8d.png)

**Comment by helenakrasnova** [comment]
Апелляция производится только если ожидаемый вами балл и полученный по результатам шага 4 средний балл отличаются на 10 и более процентов от максимального балла за задание
