### ISSUE TITLE
 Cross-Check 'Shelter. Desktop'

### ISSUE THREAD

**Issue by Sobyt483** [rolling-scopes-school/support#875]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/sobyt483-JSFE2023Q1/shelter/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/sobyt483-JSFE2023Q1)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/) Shelter. Week-1
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/117839500/229133831-96222393-238a-42f1-abfd-0c9279e4b099.png)

6. A final score after self-assessment, with comments
100/100 Все требования выполнены

7. A cross-check score of your Score 67

**Comment by Sobyt483** [comment]
Ещё хочу узнать как мне поступать, ведь мне надо задание 2 недели замержить в gh-pages. Я могу это делать сейчас или подождать и мержить уже прям перед дедлайном?

**Comment by helenakrasnova** [comment]
коммиты после дедлайна

**Comment by Sobyt483** [comment]
Да, но всего час прошёл после дедлайна. Там мелкий фикс ховер эффекта. Пожалуйста проведите апелляцию. Я старался, а в итоге получил намного меньше баллов. Из-за 1 человека и его несправедливой оценки. Ну разве это честно?

**Comment by helenakrasnova** [comment]
![изображение](https://user-images.githubusercontent.com/44213581/229147243-2eff4df9-ff5a-4153-95f1-41c4f5e146df.png)
коммиты после дедлайна

**Comment by Sobyt483** [comment]
Вы не то смотрите. Только 1 коммит был в gh-pages после срока и то всего на час опоздал, прошу войдите в положение. А эти только в ветку Shelter, это задания 2 недели с адаптивной версткой.
![image](https://user-images.githubusercontent.com/117839500/229147767-490887b7-2223-4586-9d41-de291072aacf.png)

**Comment by helenakrasnova** [comment]
я не то смотрю?) ветка shelter, коммиты:
![изображение](https://user-images.githubusercontent.com/44213581/229149718-261e3122-ea0d-4d32-887b-6da6b3249115.png)
вы не разобрались с ветками и репозиторием, как нужно выполнять задание, плюс коммитнули после дедлайна что запрещено правилами школы. Правила одинаковы для всех


![изображение](https://user-images.githubusercontent.com/44213581/229150436-bbfa24df-049d-4801-b3c8-6d3e764203b1.png)
для второй части задания создается отдельная ветка и в ветку с первой частью задания ничего не коммитается и не мержится, благодаря чему ветка shelter остаётся "чистой", с коммитами только 1й части

**Comment by Sobyt483** [comment]
Так а зачем, вы смотрите ветку shelter если деплой проекта идет через gh-pages. И следовательно изменения будут применены, если их замержить в gh-pages. В дополнение моим словам скрин с описанием задания пункт 7 и 8
![image](https://user-images.githubusercontent.com/117839500/229150691-40bfa812-5a0f-47a7-9f4e-a049020b1e49.png)

**Comment by helenakrasnova** [comment]
я смотрю в ветку shelter в который ведется разработка 1й части задания и в которой не должно быть коммитов после дедлайна, скрин выше в дополнение к моим словам

**Comment by Sobyt483** [comment]
Я правда вас не понимаю. В 7 пункте четко написано. Что можно мержить в шелтер задание 2 недели. А вот в гх-пагес только после кросс-чека.

**Comment by helenakrasnova** [comment]
у вас коммиты после дедлайна, по правилам школы апелляция не рассматривается
остальные вопросы и обсуждения по поводу веток и работы с репозиторием предлагаю задавать в дискорде в соответствующем канале

**Comment by Sobyt483** [comment]
Жаль, что из-за вредности человека, который проверял мою работу, я получил меньше баллов. Обидно конечно, но правила есть правила, понимаю.
