### ISSUE TITLE
Cross-Check 'Shelter. Adaptive' - 'vladkobrusev'.

### ISSUE THREAD

**Issue by vladkobrusev** [rolling-scopes-school/support#876]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/vladkobrusev-JSFE2023Q1/shelter/
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/vladkobrusev-JSFE2023Q1
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part2.md
4. A Link to the checklist for evaluating the task (if it exists)
    - ---
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/114438901/230458881-a4bb2a40-5eef-4b2d-b80b-3b9fe45e955e.png)

6. A final score after self-assessment, with comments
Около 40 баллов. Сделана адаптивная верстка main при ширине 768 px. Верстка не резиновая, но некоторые пункты выполнены правильно. Верстка валидная (была одна ошибка при проверки валидности (+7 баллов).
7. A cross-check score of your Score

**Comment by lyutails** [comment]
привет o/

укажи, пожалуйста, в 7м пункте
![image](https://user-images.githubusercontent.com/101958335/230539012-c1632009-5b12-46f9-b048-1433ce2b2454.png)

**Comment by helenakrasnova** [comment]
Апелляция производится только если ожидаемый вами балл и полученный по результатам кросс-чека средний балл отличаются на 10 и более процентов от максимального балла за задание.
