### ISSUE TITLE
I do not agree with the assessment on this task. Since my task was checked by only three inspectors

### ISSUE THREAD

**Issue by potopus** [rolling-scopes-school/support#877]
1. A link to your deployed project
    [- [link](https://github.com/)](https://rolling-scopes-school.github.io/potopus-JSFE2023Q1/shelter/pages/main/index.html)
2. A link to the project repository on Github.
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/potopus-JSFE2023Q1)
3. A link to the task
   [ - [link](https://github.com/)](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link][(https://github.com/)]
5. A screenshot of cross-checking marks
http://joxi.ru/Drl51zPHd6P90m
6. A final score after self-assessment, with comments
100/100
8. A cross-check score of your Score 
76

**Comment by potopus** [comment]
Здравствуйте. я не соглсен с оценкой. считаю её несправдливой. 
Ведь при крос чеке обязательно от ревьювера обратная связь. 
Один из моих ревьюверов меня проверил указал на ошибки скрыл свое имя и больше не вышел на связь.
Остальные ребята как и я помогали как мне так и я у кого проверял.  А это ЧЕРЫРЕ работы, а не три.
Прошу пересмотреть мою работу четвертым ревьювером и скорректировать оценку.

**Comment by lyutails** [comment]
привет o/

обратная связь от ревьюера во время кросс-чека - на усмотрене ревьюера 

для получения оценки за кросс-чек достаточно даже одной оценки - тогда она и будет выставлена в скор, при количестве оценок меньше 4х, но больше одной - берётся среднее по ним, а если выставлено 4 оценки - меньшая отбрасывается и считается среднее

оценка конкретного студента не пересматривается - выставляется та, которую ставит проверяющий апелляцию

тем не менее, если у тебя не было коммитов после дедлайна - разница больше 10% достаточна

обо всём этом говорится в документации https://docs.rs.school/#/cross-check-flow по которой каждый студент сдаёт RSS Test на первой неделе курса во избежание таких вопросов

условия для подачи апелляции https://docs.rs.school/#/cross-check-flow?id=Апелляция

прочитай, пожалуйста, внимательно и оформи название ишшью как указано в ссылке выше

**Comment by helenakrasnova** [comment]
> Ведь при крос чеке обязательно от ревьювера обратная связь.   

**нет, не обязательна**

коммиты после дедлайна

**Comment by potopus** [comment]
и что теперь делать?

**Comment by potopus** [comment]
а как проверять ошибки до кросчека?

**Comment by potopus** [comment]
Или на кросчекке ошибки исравлять и добавлять коммиты нельзя?

**Comment by potopus** [comment]
А почему меня тогда провелили 3 ревьювера а не четыре, как я проверял?

**Comment by helenakrasnova** [comment]
если вы коммитаете после дедлайна задания - лишаетесь возможности подавать апелляцию  
Ваша работа была отправлена на проверку 4м проверяющим. Один из них не проверил работу и соответственно сам не получил баллы за задание
