### ISSUE TITLE
shelter-part2__makcim80

### ISSUE THREAD

**Issue by makcim80** [rolling-scopes-school/support#878]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/makcim80-JSFE2023Q1/shelter/
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/makcim80-JSFE2023Q1/tree/shelter-part2
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part2.md
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![](https://user-images.githubusercontent.com/116890666/230521569-41c6eec7-7fdd-432c-9397-a7533cccdae8.png)
6. A final score after self-assessment, with comments
100 баллов, требованиям к заданию соответствуют: отклонение от макета, отсутствие горизонтальной полосы прокрутки, верстка резиновая, появление иконки бургер-меню, валидность
7. A cross-check score of your Score 
97 
Последний проверяющий 8 баллов снял за не соответствие макету, хотя у меня даже 5px расхождения нет, 2 балла снял за появление бургер-меню на 766px, но у меня заложено появление на 767px. Все замечания не соответствуют действительности, попробую связаться с коллегой, что бы в будущем проверял по ТЗ и может вы возьмите его на заметку (проверил за 2 часа до дедлайна, попробовал сразу связаться в дискорде, не получилось). Т. к. меня проверило только трое прошу проверить работу, хотя и общий бал не ниже 10% от max, и по возможности заменить оценку (понимаю что баллы не самый важный критерий, но для меня, для внутреннего спокойствия, важно). Заранее благодарен. Надеюсь найдутся отзывчивые активисты.

**Comment by lyutails** [comment]
привет o/

название ишшью должно выглядеть так 
![image](https://user-images.githubusercontent.com/101958335/230538521-737c9df0-04aa-4148-9d19-6ab1d5e079a2.png)

условия, при которых возможна подача апелляции здесь https://docs.rs.school/#/cross-check-flow?id=Апелляция

![image](https://user-images.githubusercontent.com/101958335/230538653-9db8ef31-23d1-4a8c-963c-b9e4bf1eac68.png)

при финальной оценки 97 баллов из 100 возможных максимальных апелляция не может быть проведена, так как не соблюдается одно из условий

**Comment by helenakrasnova** [comment]
Апелляция производится только если ожидаемый вами балл и полученный по результатам кросс-чека средний балл отличаются на 10 и более процентов от максимального балла за задание.
