### ISSUE TITLE
Cross-Check 'shelter. week-2 - Адаптивная вёрстка' - 'Yakubovich-siarhei'.

### ISSUE THREAD

**Issue by Yakubovich-siarhei** [rolling-scopes-school/support#879]
1. A link to your deployed project
    (https://rolling-scopes-school.github.io/yakubovich-siarhei-JSFE2023Q1/shelter)
2. A link to the project repository on Github.
    (https://github.com/rolling-scopes-school/yakubovich-siarhei-JSFE2023Q1/tree/shelter-part2)
3. A link to the task
    https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part2.md
4. A Link to the checklist for evaluating the task (if it exists)
   https://app.rs.school/course/student/cross-check-submit?course=js-fe-2023Q1&taskId=2534
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/52545914/230545404-68b75ddc-409c-42f9-a3dc-5bf2aadb0237.png)

6. A final score after self-assessment, with comments
  100/100   С предыдущими двумя проверяющими, устранил незначительные расхождения 5-10px padding.  с учетом допустимых расхождений (по моему мнению - работа была и до исправлений = 100 )
7. A cross-check score of your Score 
85/100

**Comment by lyutails** [comment]
привет o/

если были коммиты после дедлайна - апелляция не может быть проведена

![image](https://user-images.githubusercontent.com/101958335/230554125-aa352b40-dffd-4d97-b7e0-4a3d4a17fe56.png)

**Comment by helenakrasnova** [comment]
коммиты после дедлайна

**Comment by Yakubovich-siarhei** [comment]
С мной понятно,  но хотя бы этому "проверяющему"  можно предупреждение  какое-то,  он же дальше будет занижать  "оценки" за пару часов до дедлайна.? 
--
Отправлено из Mail.ru для Android пятница, 07 апреля 2023г., 10:34 +03:00 от helenakrasnova  ***@***.*** :

**Comment by helenakrasnova** [comment]
> С мной понятно,  но хотя бы этому "проверяющему"  можно предупреждение  какое-то,  он же дальше будет занижать  "оценки" за пару часов до дедлайна.? -- Отправлено из Mail.ru для Android пятница, 07 апреля 2023г., 10:34 +03:00 от helenakrasnova ***@***.*** :
> […](#)
> коммиты после дедлайна — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: @ github . com>

апелляция не является средством жалобы на проверяющего
