### ISSUE TITLE
Cross-Check 'webdev' - 'DmitrijStr'

### ISSUE THREAD

**Issue by DmitrijStr** [rolling-scopes-school/support#88]
https://rolling-scopes-school.github.io/dmitrijstr-JS2020Q3/webdev/
Ссылка на репозиторий с проектом на GitHub
Ревьюер ошибся в своих же подсчетах на 20 баллов. Плюс логический элемент h1 на странице все-же присутсвует. В итоге 72
49

##########
Страница открывается - ( +20 )
1. Header
Интерактивная панель навигации +
Логотип находится по центру -
Наличие h1 -
Не липкий хедер +
Изображение должно быть подложено под текст +
Большие различия от perfect pixel
10 - 4 - 3 = 3
2.  Your life
Кнопка get started должна быть интерактивной + 
Кнопки (иконки) соц. сетей должны быть интерактивными +
Изображение должно быть подложено под текст +
Большие различия от perfect pixel
10 - 3 = 7
3. Rappresent
В текстовом блоке есть важный текст, который выделен жирным. Для него нужно использовать логический элемент (но у тебя span, это не логический элемент) -
Кнопка get started должна быть интерактивной +
Картинка должна быть на своем месте ( на 3px не совпадает, но вроде порог это 5, поэтому всё хорошо ) +
Кнопка и текст не попадают в perfect pixel
10 - 2 - 3 = 5
4. Our Community
1, /, 5 должны быть раздельными элементами +
Стрелки должны быть интерактивными +
Конструкция представляет из себя 2 многоколоночных макета +
Сильно не попадаешь в pirfect pixel
10 - 3 = 7
5. Implement
В текстовом блоке есть важный текст, который выделен жирным. Для него нужно использовать логический элемент -
Кнопка learn more должна быть интерактивной ( не span, а strong должен быть ) -
Картинка должна быть на своем месте +
Текст который должен быть капсом у тебя обычными
10 - 4 - 3 = 3
6. Sign Up
Изображение должно быть подложено под текст +
Галочка на зеленом фоне должна быть интерактивной +
Поле your email должно иметь валидацию на тип email +
В принципе попал в pirfect pixel
10
7. Download
apple store, play store и их иконки должны быть интерактивными +
текст Download the App не капсом у тебя
10 - 3 = 7
8. Footer 
Между элементами меню есть разделители +
Интерактивная панель навигации + 
логотип сильно не по центру
10 - 3 = 7
Итого: 49)

**Comment by valerydluski** [comment]
Оценка полученная в результате кросс-чека отличается от максимального балла менее чем на 15%
