### ISSUE TITLE
Cross-Check 'task-name' 'github nickname'

### ISSUE THREAD

**Issue by maxsimusprime** [rolling-scopes-school/support#880]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/maxsimusprime-JSFE2023Q1/shelter/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/maxsimusprime-JSFE2023Q1/tree/shelter)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/96006023/230558101-3f6c6fd3-2ddb-4a42-b849-30178385e777.png)
![image](https://user-images.githubusercontent.com/96006023/230558133-578b4eda-8d00-4e21-bd77-75422d8a117e.png)
![image](https://user-images.githubusercontent.com/96006023/230558166-8baeb916-21da-4491-bfed-53296d1f2a53.jpeg)

6. Оцениваю себя в 98 баллов, так как возможны небольшие погрешности с макетом

7. A cross-check score of your Score 
94

**Comment by lyutails** [comment]
привет o/

в названии ишшью 'task-name' - должно быть названием таска, а 'github nickname' - твоим ником на гитхабе

условия, при которых возможна подача апелляции здесь [https://docs.rs.school/#/cross-check-flow?id=Апелляция](https://docs.rs.school/#/cross-check-flow?id=%D0%90%D0%BF%D0%B5%D0%BB%D0%BB%D1%8F%D1%86%D0%B8%D1%8F)

![image](https://user-images.githubusercontent.com/101958335/230561103-ac28e0e2-88da-4237-b73a-3469eb14c93a.png)

при финальной оценки 94 баллов из 98 максимальных от селфчека апелляция не может быть проведена, так как не соблюдается одно из условий

**Comment by helenakrasnova** [comment]
Апелляция производится только если ожидаемый вами балл и полученный по результатам кросс-чека средний балл отличаются на 10 и более процентов от максимального балла за задание.
