### ISSUE TITLE
Cross-Check 'shelter-part2' - Alexandra376

### ISSUE THREAD

**Issue by Alexandra376** [rolling-scopes-school/support#881]
1. A link to your deployed project
    https://rolling-scopes-school.github.io/alexandra376-JSFE2023Q1/shelter/
2. A link to the project repository on Github.
    https://github.com/rolling-scopes-school/alexandra376-JSFE2023Q1/tree/shelter-part2
3. A link to the task
    https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part2.md
4. A Link to the checklist for evaluating the task (if it exists)
    -
5. A screenshot of cross-checking marks
<img width="1046" alt="Снимок экрана 2023-04-07 в 14 04 13" src="https://user-images.githubusercontent.com/119896011/230589975-061798aa-6ec8-4617-9571-fc11ee7639c4.png">

6. A final score after self-assessment, with comments:
A final score is 97 points. Self-assessment, with comments attached.
1)  <img width="729" alt="Part 1" src="https://user-images.githubusercontent.com/119896011/230596642-36a1ed43-a010-46a6-88e8-59ac7ea69c51.png">

2)  <img width="727" alt="Part 2" src="https://user-images.githubusercontent.com/119896011/230596790-92b34d4e-5887-4e64-957e-3615ab54d7d2.png">

3)  <img width="726" alt="Part 3" src="https://user-images.githubusercontent.com/119896011/230596820-f940b323-52db-44a5-ad41-6a84e2f55e66.png">

4)  <img width="727" alt="Part 4" src="https://user-images.githubusercontent.com/119896011/230596860-7317fb87-5566-4606-a79d-de4499b8daa3.png">

5)  <img width="725" alt="Part 5" src="https://user-images.githubusercontent.com/119896011/230596898-4df545b9-583e-4bd3-9cc4-ee98453d6845.png">

7. A cross-check score of your Score 
<img width="945" alt="Снимок экрана 2023-04-07 в 14 18 12" src="https://user-images.githubusercontent.com/119896011/230591985-fb15773c-907c-4512-afa2-3a252ad4a5e9.png">

<img width="545" alt="Снимок экрана 2023-04-07 в 14 18 35" src="https://user-images.githubusercontent.com/119896011/230592042-ae4982b4-4f16-4d67-82f8-fe6225c5ecda.png">

**Comment**

Добрый день! 
Я знаю, что не заслуживаю пересмотра оценки, так как внесла правку в работу после начала crosscheck Tue Apr 4 04:23:58 2023 - по Минскому времени. 
Но ввиду того, что работа была проверена с занижением балла более, чем на 30% без адекватного аргументирования, прошу все же рассмотреть данную апелляцию. 
Хотелось бы, чтобы проверки со стороны reviewers проводились более тщательно, согласно критериям, а не анонимными лицами, которые полагают, что могут ставить баллы не имеющие под собой никакого логического обоснования. 
Заранее благодарю!

**Comment by helenakrasnova** [comment]
коммиты после дедлайна
