### ISSUE TITLE
Cross-Check “Shelter. Part 1” & “Shelter. Part 2” - InventiveSpark

### ISSUE THREAD

**Issue by InventiveSpark** [rolling-scopes-school/support#882]
Здравствуйте!

В связи с исключительными обстоятельствами (внезапной кончиной моего отца) я пропустил полторы недели занятий, не смог выполнить вовремя задания “Shelter. Part 1” / “Shelter. Part 2” и задеплоить ссылки на них. На канале questions-to-admins мне посоветовали сделать задания и подать апелляцию, не участвуя в перекрестной проверке. Пытаясь успеть к дедлайну второго задания, выполнял оба задания одновременно.

Прошу кого-нибудь из активистов проверить и оценить выполнение этих заданий. Буду признателен.

1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/inventivespark-JSFE2023Q1/shelter/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/inventivespark-JSFE2023Q1/tree/shelter/shelter)
3. A links to the tasks
    - [Shelter. Part 1](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md)
    - [Shelter. Part 2](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [RSS Tasks Checklist](https://rolling-scopes-school.github.io/checklist/), then select “Shelter Week-1” / “Shelter Week-2”
6. A final score after self-assessment, with comments
    - Требования “Shelter Week-1” выполнены в полном объеме. Оценка в результате самопроверки - 100 баллов.
    - Требования “Shelter Week-2” выполнены в полном объеме. Оценка в результате самопроверки - 100 баллов.

Примечание:
- Пустая ссылка добавлена посредством “[javascript:void(0);](https://htmlacademy.ru/blog/html/empty-links)”. Ссылка в этом случае никуда не прокручивается, страница не перезагружается.
- Иконка для сайта позаимствована [отсюда](https://www.istockphoto.com/vector/veterinary-clinic-vector-logo-gm1148570769-310212259).

P.S. [Некролог](https://ufaart.ru/news/pamyati-vyidayushhegosya-pedagoga-rezhissera-loshhenkova-anatoliya-korneevicha).

P.P.S. Подтверждение моих ФИО можно найти в моём [CV на GitHub](https://inventivespark.github.io/rsschool-cv/cv), выбрав любой диплом из раздела “Education” или любой сертификат из раздела “University Courses”.

**Comment by haslie22** [comment]
## Shelter. Part 1

### Страница Main `60/60`
#### Проверка верстки `6/6`
- [x] верстка страницы валидная `4/4`
- [x] логотип в хедере состоит из текстовых элементов `1/1`
- [x] страница содержит ровно один элемент `<h1>` `1/1`

#### Верстка соответствует макету `35/35`
- [x] блок `<header>` `5/5`
- [x] блок `Not only` `5/5`
- [x] блок `About` `5/5`
- [x] блок `Our Friends` `5/5`
- [x] блок `Help` `5/5`
- [x] блок `In addition` `5/5`
- [x] блок `<footer>` `5/5`

#### Требования к CSS `7/7`
- [x] для позиционирования элементов блока `Help` использована сеточная верстка (`flexbox` или `grid`) `2/2`
- [x] при уменьшении масштаба страницы браузера или увеличении ширины страницы (`>1280px`) вёрстка размещается по центру, а не сдвигается в сторону и не растягивается по всей ширине `2/2`
- [x] фоновый цвет тянется на всю ширину страницы `2/2`
- [x] добавлен favicon `1/1`

#### Интерактивность элементов `12/12`
- [x] элемент `About the Shelter` в навигации подсвечен и неинтерактивен, остальные элементы навигации интерактивны `2/2`
- [x] каждая карточка с питомцем в блоке Our Friends интерактивна при наведении на любую область этой карточки `2/2`
- [x] плавная прокрутка по якорям `2/2`
- [x] выполняются все ссылочные связи согласно [Перечню ссылочных связей](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md#%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B5%D0%BD%D1%8C-%D1%81%D1%81%D1%8B%D0%BB%D0%BE%D1%87%D0%BD%D1%8B%D1%85-%D1%81%D0%B2%D1%8F%D0%B7%D0%B5%D0%B9) для страницы `Main` `2/2`
- [x] выполнена интерактивность ссылок и кнопок `2/2`
- [x] обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике, не влияющее на соседние элементы `2/2`

### Страница Pets `40/40`
#### Проверка верстки `6/6`
- [x] верстка страницы валидная `4/4`
- [x] логотип в хедере состоит из текстовых элементов `1/1`
- [x] страница содержит ровно один элемент `<h1>` `1/1`

#### Верстка соответствует макету `15/15`
- [x] блок `<header>` `5/5`
- [x] блок `Our Friends` `5/5`
- [x] блок `<footer>` `5/5`

#### Требования к CSS `7/7`
- [x] для позиционирования элементов блока `Help` использована сеточная верстка (`flexbox` или `grid`) `2/2`
- [x] при уменьшении масштаба страницы браузера или увеличении ширины страницы (`>1280px`) вёрстка размещается по центру, а не сдвигается в сторону и не растягивается по всей ширине `2/2`
- [x] фоновый цвет тянется на всю ширину страницы `2/2`
- [x] добавлен favicon `1/1`

#### Интерактивность элементов `12/12`
- [x] элемент `Our pets` в навигации подсвечен и неинтерактивен, остальные элементы навигации интерактивны `2/2`
- [x] доступные кнопки пагинации (вправо) активны, недоступные (влево) - неактивны (disabled) `2/2`
- [x] каждая карточка с питомцем в блоке Our Friends интерактивна при наведении на любую область этой карточки `2/2`
- [x] плавная прокрутка по якорям `2/2`
- [x] выполняются все ссылочные связи согласно [Перечню ссылочных связей](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md#%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B5%D0%BD%D1%8C-%D1%81%D1%81%D1%8B%D0%BB%D0%BE%D1%87%D0%BD%D1%8B%D1%85-%D1%81%D0%B2%D1%8F%D0%B7%D0%B5%D0%B9) для страницы `Pets` `2/2`
- [x] выполнена интерактивность ссылок и кнопок `2/2`
- [x] обязательное требование к интерактивности: плавное изменение внешнего вида элемента при наведении и клике, не влияющее на соседние элементы `2/2`

### Итоговый балл: 100/100

@helenakrasnova check please

**Comment by haslie22** [comment]
## Shelter. Part 2

##### Вёрстка страницы `Main` соответствует макету при ширине экрана `1280px` `14/14`
- [x] блок `<header>` `2/2`
- [x] блок `Not only` `2/2`
- [x] блок `About` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `Help` `2/2`
- [x] блок `In addition` `2/2`
- [x] блок `<footer>` `2/2`

##### Вёрстка страницы `Main` соответствует макету при ширине экрана `768px` `14/14`
- [x] блок `<header>` `2/2`
- [x] блок `Not only` `2/2`
- [x] блок `About` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `Help` `2/2`
- [x] блок `In addition` `2/2`
- [x] блок `<footer>` `2/2`

##### Вёрстка страницы `Main` соответствует макету при ширине экрана `320px` `14/14`
- [x] блок `<header>` `2/2`
- [x] блок `Not only` `2/2`
- [x] блок `About` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `Help` `2/2`
- [x] блок `In addition` `2/2`
- [x] блок `<footer>` `2/2`

##### Вёрстка страницы `Pets` соответствует макету при ширине экрана `1280px` `6/6`
- [x] блок `<header>` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `<footer>` `2/2`

##### Вёрстка страницы `Pets` соответствует макету при ширине экрана `768px` `6/6`
- [x] блок `<header>` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `<footer>` `2/2`

##### Вёрстка страницы `Pets` соответствует макету при ширине экрана `320px` `6/6`
- [x] блок `<header>` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `<footer>` `2/2`

##### Ни на одном из разрешений до `320px включительно` не появляется горизонтальная полоса прокрутки, справа от отдельных блоков не появляются белые поля. Весь контент страницы при этом сохраняется: не обрезается и не удаляется `20/20`
- [x] нет полосы прокрутки при ширине страницы `Main` от `1280рх` до `768рх` `5/5`
- [x] нет полосы прокрутки при ширине страницы `Main` от `768рх` до `320рх` `5/5`
- [x] нет полосы прокрутки при ширине страницы `Pets` от `1280рх` до `768рх` `5/5`
- [x] нет полосы прокрутки при ширине страницы `Pets` от `768рх` до `320рх` `5/5`

#### Верстка резиновая: при плавном изменении размера экрана от 1280px до 320px верстка подстраивается под этот размер, элементы верстки меняют свои размеры и расположение, не наезжают друг на друга, изображения могут менять размер, но сохраняют правильные пропорции ([Примеры неправильной и правильной реализации](https://www.youtube.com/watch?v=dRNc0l4s8sE&ab_channel=SoCrazySky)) `8/8`
- [x] на странице Main `4/4`
- [x] на странице Pets `4/4`

- [x] При ширине экрана `меньше 768px` на обеих страницах меню в хедере скрывается, появляется иконка бургер-меню `4/4`
- [x] Верстка обеих страниц валидная `8/8`

### Итоговый балл: 100/100

@helenakrasnova check please
