### ISSUE TITLE
Cross-Check 'shelter. week-2 - Адаптивная вёрстка' - 'l3elk4'

### ISSUE THREAD

**Issue by l3elk4** [rolling-scopes-school/support#883]
Добрый вечер!
Не согласен с оценкой полученной от одного проверяющего, а так как работу проверило всего два человека, данное снижение итоговой оценки считаю критичным.
Прошу проверить работу.

1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/l3elk4-JSFE2023Q1/shelter/pages/main/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/l3elk4-JSFE2023Q1/tree/gh-pages)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)  then select “Shelter Week-2”
5. A screenshot of cross-checking marks
<img width="1280" alt="Снимок экрана 2023-04-07 в 21 35 05" src="https://user-images.githubusercontent.com/119819542/230660197-110bc063-3c13-42ae-989b-14d0bb254c0a.png">

6. A final score after self-assessment, with comments
Ваша оценка - 92 балла 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) на странице 'Main', при плавном изменении размера экрана от 1280px до 320px верстка подстраивается под этот размер, элементы верстки меняют свои размеры и расположение, не наезжают друг на друга, изображения могут менять размер, но сохраняют правильные пропорции 

2) на странице 'Pets', при плавном изменении размера экрана от 1280px до 320px верстка подстраивается под этот размер, элементы верстки меняют свои размеры и расположение, не наезжают друг на друга, изображения могут менять размер, но сохраняют правильные пропорции 

Выполненные пункты:
1) блок 'header' 

2) блок 'Not only' 

3) блок 'About' 

4) блок 'Our Friends' 

5) блок 'Help' 

6) блок 'In addition' 

7) блок 'footer' 

8) блок 'header' 

9) блок 'Not only' 

10) блок 'About' 

11) блок 'Our Friends' 

12) блок 'Help' 

13) блок 'In addition' 

14) блок 'footer' 

15) блок 'header' 

16) блок 'Not only' 

17) блок 'About' 

18) блок 'Our Friends' 

19) блок 'Help' 

20) блок 'In addition' 

21) блок 'footer' 

22) блок 'header' 

23) блок 'Our Friends' 

24) блок 'footer' 

25) блок 'header' 

26) блок 'Our Friends' 

27) блок 'footer' 

28) блок 'header' 

29) блок 'Our Friends' 

30) блок 'footer' 

31) нет полосы прокрутки при ширине страницы 'Main' от 1280рх до 768рх 

32) нет полосы прокрутки при ширине страницы 'Main' от 768рх до 320рх 

33) нет полосы прокрутки при ширине страницы 'Pets' от 1280рх до 768рх  

34) нет полосы прокрутки при ширине страницы 'Pets' от 768рх до 320рх 

35) При ширине экрана меньше 768px на обеих страницах меню в хедере скрывается, появляется иконка бургер-меню. Открытие меню при клике на иконку бургер-меню на текущем этапе не проверяется 

36) Верстка обеих страниц валидная: для проверки валидности вёрстки используйте сервис https://validator.w3.org/  

7. A cross-check score of your Score 
84

--

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

**Comment by helenakrasnova** [comment]
Апелляция производится только если ожидаемый вами балл и полученный по результатам кросс-чека средний балл отличаются на 10 и более процентов от максимального балла за задание.

**Comment by l3elk4** [comment]
Спасибо за ответ и Вашу работу даже в выходные)
