### ISSUE TITLE
Cross-Check: Shelter. Adaptive  - Harapuchyk

### ISSUE THREAD

**Issue by Harapuchyk** [rolling-scopes-school/support#884]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/harapuchyk-JSFE2023Q1/shelter/main.html
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/harapuchyk-JSFE2023Q1/tree/shelter-part2
3. A link to the task
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - 
5. A screenshot of cross-checking marks
![123](https://user-images.githubusercontent.com/106514759/230731563-bfd747bf-0d1f-4a49-bed4-1fb47b7ce6b2.jpg)

6. A final score after self-assessment, with comments
Score: 100 / 100:
*Вёрстка страницы Main соответствует макету при ширине экрана 1280px: +14
*Вёрстка страницы Main соответствует макету при ширине экрана 768px: +14
*Вёрстка страницы Main соответствует макету при ширине экрана 320px: +14
*Вёрстка страницы Pets соответствует макету при ширине экрана 1280px: +6
*Вёрстка страницы Pets соответствует макету при ширине экрана 768px: +6
*Вёрстка страницы Pets соответствует макету при ширине экрана 320px: +6
*Ни на одном из разрешений до 320px включительно не появляется горизонтальная полоса прокрутки: +20
*Верстка резиновая: +8
*При ширине экрана меньше 768px на обеих страницах меню в хедере скрывается, появляется иконка бургер-меню: +4
*Верстка обеих страниц валидная: +8
Итоговая самооценка: 100 баллов

7. A cross-check score of your Score 
89

**Comment by haslie22** [comment]
#### Вёрстка страницы `Main` соответствует макету при ширине экрана `1280px` `14/14`
- [x] блок `<header>` `2/2`
- [x] блок `Not only` `2/2`
- [x] блок `About` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `Help` `2/2`
- [x] блок `In addition` `2/2`
- [x] блок `<footer>` `2/2`

#### Вёрстка страницы `Main` соответствует макету при ширине экрана `768px` `14/14`
- [x] блок `<header>` `2/2`
- [x] блок `Not only` `2/2`
- [x] блок `About` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `Help` `2/2`
- [x] блок `In addition` `2/2`
- [x] блок `<footer>` `2/2`

#### Вёрстка страницы `Main` соответствует макету при ширине экрана `320px` `14/14`
- [x] блок `<header>` `2/2`
- [x] блок `Not only` `2/2`
- [x] блок `About` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `Help` `2/2`
- [x] блок `In addition` `2/2`
- [x] блок `<footer>` `2/2`

#### Вёрстка страницы `Pets` соответствует макету при ширине экрана `1280px` `6/6`
- [x] блок `<header>` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `<footer>` `2/2`

#### Вёрстка страницы `Pets` соответствует макету при ширине экрана `768px` `6/6`
- [x] блок `<header>` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `<footer>` `2/2`

#### Вёрстка страницы `Pets` соответствует макету при ширине экрана `320px` `6/6`
- [x] блок `<header>` `2/2`
- [x] блок `Our Friends` `2/2`
- [x] блок `<footer>` `2/2`

#### Ни на одном из разрешений до `320px включительно` не появляется горизонтальная полоса прокрутки, справа от отдельных блоков не появляются белые поля. Весь контент страницы при этом сохраняется: не обрезается и не удаляется `20/20`
- [x] нет полосы прокрутки при ширине страницы `Main` от `1280рх` до `768рх` `5/5`
- [x] нет полосы прокрутки при ширине страницы `Main` от `768рх` до `320рх` `5/5`
- [x] нет полосы прокрутки при ширине страницы `Pets` от `1280рх` до `768рх` `5/5`
- [x] нет полосы прокрутки при ширине страницы `Pets` от `768рх` до `320рх` `5/5`

#### Верстка резиновая: при плавном изменении размера экрана от 1280px до 320px верстка подстраивается под этот размер, элементы верстки меняют свои размеры и расположение, не наезжают друг на друга, изображения могут менять размер, но сохраняют правильные пропорции ([Примеры неправильной и правильной реализации](https://www.youtube.com/watch?v=dRNc0l4s8sE&ab_channel=SoCrazySky)) `8/8`
- [x] на странице Main `4/4`
- [x] на странице Pets `4/4`

- [x] При ширине экрана `меньше 768px` на обеих страницах меню в хедере скрывается, появляется иконка бургер-меню `4/4`
- [x] Верстка обеих страниц валидная `8/8`

### Итоговый балл: 100/100

@helenakrasnova check please
