### ISSUE TITLE
Cross-Check Shelter. DOM - seger-k

### ISSUE THREAD

**Issue by seganych** [rolling-scopes-school/support#885]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/seger-k-JSFE2023Q1/shelter/pages/main/
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/seger-k-JSFE2023Q1
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part3.md
4. A Link to the checklist for evaluating the task (if it exists)
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part3.md#%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%83
5. A screenshot of cross-checking marks

![dgfdfgdg](https://user-images.githubusercontent.com/113037321/232057685-6a6ca52c-2d83-4eb1-bd63-a39ddc650280.png)
![sfdsfsdfsfds](https://user-images.githubusercontent.com/113037321/232057696-e52bc455-5e39-4ad7-98c2-f2089c0e03bc.png)

6. A final score after self-assessment, with comments
Сделан бургер, с одной лишь ошибкой (-1 балл) => При клике на ссылку About the Shelter на главной странице и Our Pets на странице Pets меню не скрывается, иконка не разворачивается. Получается 25 баллов за бургер должно быть 
7. A cross-check score of your Score 
21 / 110

**Comment by helenakrasnova** [comment]
Апелляция производится только если ожидаемый вами балл и полученный по результатам кросс-чека средний балл отличаются на 10 и более процентов от максимального балла за задание.
