### ISSUE TITLE
Cross-Check 'React. API' - 'bloodsuckers-spb'.

### ISSUE THREAD

**Issue by bloodsuckers-spb** [rolling-scopes-school/support#886]
1. A link to your deployed project
    - [link](https://keen-scone-d756a7.netlify.app/)
2. A link to the project repository on Github.
    - [link](https://github.com/bloodsuckers-spb/rss-react/tree/develop)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/react/modules/module04)
4. A Link to the checklist for evaluating the task (if it exists)
     Not Exist
5. A screenshot of cross-checking marks
![изображение](https://user-images.githubusercontent.com/90127354/232429881-2338ec74-5c5c-4b7b-8877-6e9645e3a0f2.png)
6. A final score after self-assessment, with comments  - 15/15
    - Linting can be run and doesn't produce any errors or warnings 2/2
    - Tests can be run and the test coverage is equal or higher than 60% 3/3
    - When value is entered into the search bar and submitted, the call will be send to an api with an entered value 2/2
    - If the value has been entered previoulsy, search should restore it from the LS and make a call to an api with this previoulsy entered value next time page is opened 1/1
    - When response is received, the data should be displyed on the main page using tiles  3/3
    - More details for each item are displayed using modal 3/3
    - While request is being made, loading indicator is shown to an user  1/1
7. A cross-check score of your Score - 14

**Comment by valerydluski** [comment]
Your score is 15 points
