### ISSUE TITLE
Cross-Check 'Clean-code' - Marina-tech-dot

### ISSUE THREAD

**Issue by Marina-tech-dot** [rolling-scopes-school/support#888]
1. A link to your deployed project
    - https://marina-tech-dot.github.io/clean-code-s1e1/
2. A link to the project repository on Github.
    - https://github.com/Marina-tech-dot/clean-code-s1e1/pull/1
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md
4. A Link to the checklist for evaluating the task (if it exists)
    - https://rolling-scopes-school.github.io/checklist/
5. A screenshot of cross-checking marks
![Screenshot 2023-04-28 at 07 48 43](https://user-images.githubusercontent.com/85888955/235069331-1ad828cd-1bdb-4e2b-aa29-aea1a6a6694f.png)

6. A final score after self-assessment, with comments
Я считаю, что выполнила задание полностью 45 / 45. В комментарии к оценке 43 балла написано "Одно требование не выполнено, по теговым селекторам, в остальном все хорошо, молодец."
При этом это правило выполнено в коммите af8d7e0. 
Мне снято меньше 10%. Но проверяющий выполнил проверку глубокой ночью перед дедлайном - это либо недобросовестная проверка, либо злой умысел. Прошу восстановить справедливость и пресечь возможность проверяющему делать аналогичные действия в будущем.
7. A cross-check score of your Score 
44

**Comment by helenakrasnova** [comment]
Апелляция производится только если ожидаемый вами балл и полученный по результатам кросс-чека средний балл отличаются на 10 и более процентов от максимального балла за задание.
