### ISSUE TITLE
Cross-Check 'Clean-code-s1e1' 'DmitruKudr'

### ISSUE THREAD

**Issue by DmitruKudr** [rolling-scopes-school/support#889]
1. A link to your deployed project
    - [link](https://dmitrukudr.github.io/clean-code-s1e1/)
2. A link to the project repository on Github.
    - [link](https://github.com/DmitruKudr/clean-code-s1e1)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md)
5. A screenshot of cross-checking marks
![image](https://user-images.githubusercontent.com/114616943/235183066-7d44f8b4-748b-47ce-bbe3-860744c4c689.png)
![image](https://user-images.githubusercontent.com/114616943/235179442-1ae02899-ed60-46cc-8a73-c81b37350237.png)

6. A final score after self-assessment, with comments
    - Final score: 40. Everything is done except for the extended-2.1 rule (BEM)

8. A cross-check score of your Score 
    - Cross-check score: 37
 
I don't agree with the mark of Reviewer 3 and his points. I find them (points) unreasonable and picky. Also I tried to contact using RS  App (no discord links were provided due to anonymous status), didn't recieve any responce :( My comments in RS App:

Привет! Я подправил точки с запятой, пробелы, атрибут type, теговые селекторы. Но в остальном по многим пунктам я не согласен. Например объединение имен в один общий класс (button edit), тут button используется для задания стиля а edit указывает на то, что кнопку для редактирования, писать отдельные стили для button__edit и button__delete неблагоразумно. Или пример с названиями стилей как у тегов, как назвать стиль для кнопки как не 'button'?). Еще по поводу разделения блока main.

Main - это основная часть, это не означает, что это должен быть какой-то отдельный главный элемент на странице. В том числе main у меня разделен на секции. В общем это как по мне ооочень субъективно с твоей стороны, причем подкрепляется это сильным отбиранием балла (с чем я не согласен :). А по поводу много лишних переносов, был опциональный пункт basic 2.5 (нет длинных строк на весь экран). Надеюсь, мы еще подискутируем по этому поводу, и буду благодарен, если перепроверишь мою работу). Удачи в дальнейшем!

**Comment by helenakrasnova** [comment]
Апелляция производится только если ожидаемый вами балл и полученный по результатам кросс-чека средний балл отличаются на 10 и более процентов от максимального балла за задание.
