### ISSUE TITLE
Cross-Check HTML Builder - istiniel

### ISSUE THREAD

**Issue by Istiniel** [rolling-scopes-school/support#891]
1. A link to your deployed project
    - no deploy for this task
2. A link to the project repository on Github.
    - [link](https://github.com/Istiniel/HTML-builder)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-builder)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/EvgeniiMal/HTML-builder/wiki/HTML-builder-crosscheck)
5. A screenshot of cross-checking marks
    ![img](https://i.ibb.co/2gy23vH/image.png)
    ![img](https://i.ibb.co/QNvygMV/image.png)
    ![img](https://i.ibb.co/8bb9gVh/image.png)
6. A final score after self-assessment, with comments
01 read file: 20 баллов
02 write file: 20 баллов
03 files in folder: 20 баллов
04 copy directory: 20 баллов
05 merge styles: 20 баллов
06 build page: 50 баллов

Total: 150 баллов
    -150
7. A cross-check score of your Score 
    -113
Подозреваю что у ревьюера старая версия Node, потому что fs.rm is not a function однозначно не ошибка логики приложения, у всех остальных проверяющих ошибок при проверке нет. На связь ревьюер не вышел, проверял в последний момент, последний день.

**Comment by helenakrasnova** [comment]
Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).

**Comment by haslie22** [comment]
#### 01-read-file: 20/20
- [x] Отсутствие синхронных методов модуля `fs` и `setTimeout()`
- [x] Для чтения файла используется ReadStream
- [x] При выполнении команды `node 01-read-file` в консоль выводится содержимое файла text.txt
- [x] При изменении файла text.txt и выполнении команды `node 01-read-file` результат соответствует текущему состоянию text.txt

#### 02-write-file: 20/20
- [x] Отсутствие синхронных методов модуля `fs` и `setTimeout()`
- [x] При выполнении команды `node 02-write-file` в консоли появляется приглашение на ввод текста, а в каталоге 02-write-file создается текстовый файл
- [x] Ввод текста корректно записывается в созданный текстовый файл
- [x] При использовании сочетания `ctrl + c` в консоль выводится прощальная фраза с последующим завершением процесса
- [x] При вводе слова `exit` в консоль выводится прощальная фраза с последующим завершением процесса

#### 03-files-in-folder: 20/20
- [x] Отсутствие синхронных методов модуля `fs` и `setTimeout()`
- [x] При выполнении команды `node 03-files-in-folder` в консоль выводится информация о файлах, содержащихся внутри `secret-folder` (информация о файлах, находящихся в подпапках, выводиться не должна)
- [x] При дополнении папки `secret-folder` одним или несколькими файлами разного размера и несколькими папками (в том числе с фальшивым названием вроде `my-folder.js`) при выполнении команды `node 03-files-in-folder` в консоль выводится корректная информация о файлах

#### 04-copy-directory: 20/20
- [x] Отсутствие синхронных методов модуля `fs` и `setTimeout()`
- [x] Отсутствие функции `fsPromises.cp()`
- [x] После завершения выполнения скрипта в папке `04-copy-directory` содержится созданная папка `files-copy` с точной копией содержимого исходной папки `files`
- [x] После добавления и удаления нескольких файлов в папке `files` и выполнения скрипта содержимое папки `files-copy` обновлено и соответствует содержимому папки `files`

#### 05-merge-styles: 20/20
- [x] Отсутствие синхронных методов модуля `fs` и `setTimeout()`
- [x] Cодержимое файла `bundle.css` и форматирование стилей в нем соответствует файлам-исходникам, стили не сливаются
- [x] При изменении содержимого папки `styles` (удаление файлов стилей или замена папки `styles` и `project-dist/index.html` на содержимое папки `test-files`) файл `bundle.css` перезаписывается и содержит актуальные и корректные стили
- [x] При добавлении в папку `styles` файла с расширением, отличным от css, этот файл не попадает в `bundle.css`

#### 06-build-page: 50/50
- [x] Отсутствие синхронных методов модуля `fs` и `setTimeout()`
- [x] Отсутствие функции `fsPromises.cp()`
- [x] После завершения работы скрипта в директории `06-build-page` создается папка `project-dist`, содержащая в себе файлы `index.html` и `style.css`, а также папку `assets`
- [x] файл `index.html` содержит разметку из файла `template.html` с заменой шаблонных тегов разметкой одноимённых файлов-компонентов из папки `components`
- [x] Разметка файлов-компонентов находится строго на местах соответствующих шаблонных тегов. Самих тегов в файле `index.html` нет
- [x] В файле `style.css` стили сохраняют форматирование и не вклиниваются друг в друга
- [x] В папке `assets` её содержимое и содержимое подпапок, находящихся внутри, точно соответствует содержимому папки `assets`, находящейся в `06-build-page/assets`
- [x] При добавлении в проект тестовых файлов из папки `test-files` предыдущшие пункты выполняются

#### Итого: 150 баллов

@helenakrasnova check please :eyes:
