### ISSUE TITLE
Cross-Check 'HTML-builder' - 'iSaklov'

### ISSUE THREAD

**Issue by iSaklov** [rolling-scopes-school/support#893]
1. A link to your deployed project
    - [link](https://github.com/iSaklov/HTML-builder)
2. A link to the project repository on Github.
    - [link](https://github.com/iSaklov/HTML-builder)
3. A link to the task
    - [link](https://github.com/EvgeniiMal/HTML-builder)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/EvgeniiMal/HTML-builder/wiki/HTML-builder-crosscheck)
5. A screenshot of cross-checking marks
![Capture d’écran 2023-05-15 à 11 37](https://github.com/rolling-scopes-school/support/assets/64387265/6929476b-ef3d-4ea9-be6d-ea9f4992a69c)

6. A final score after self-assessment, with comments
  Self-assessment - 150,
  because all points are excellent.
  
  Two reviewers gave the maximum score, the third one did not enter the development branch with the solution of the task and rated the work at 0.
  
  I, according to the established tradition of RSSchool, developed on the 'dev' branch, followed by a request to 'main'.
  
7. A cross-check score of your Score 

  Accordingly, the final score for the completed task is 100.
  
  150 + 150 + 0 / 3 = 100
  
  I would be extremely grateful to all recheckers.

**Comment by helenakrasnova** [comment]
коммиты после дедлайна

**Comment by iSaklov** [comment]
> коммиты после дедлайна

Приветствую. Хотел бы обратить внимание, что по местному времени дедлайн был соблюдён. У меня в расписании до 2:00 включительно. 

![Capture d’écran 2023-05-16 à 13 52 01](https://github.com/rolling-scopes-school/support/assets/64387265/fdacbe4e-4ebc-4bf7-a4bb-a7150ea4df97)

В противном случае, я никого бы не беспокоил, так как ознакомился с требованиями issue.

**Comment by helenakrasnova** [comment]
все верно, дедлайн 9 числа, в  01.59 **AM**
у вас есть 2 коммита после этого времени - 4.27 **PM**, 4.50 **PM**
![image](https://github.com/rolling-scopes-school/support/assets/44213581/a725edff-75a3-4bd9-9543-dc28ca85887e)

**Comment by iSaklov** [comment]
> все верно, дедлайн 9 числа, в 01.59 **AM**
> у вас есть 2 коммита после этого времени - 4.27 **PM**, 4.50 **PM**
> ![image](https://user-images.githubusercontent.com/44213581/238641935-a725edff-75a3-4bd9-9543-dc28ca85887e.png)

Понял. Подчищал dist видимо. Спасибо за внимание.
