### ISSUE TITLE
Cross-Check 'Self-introduction' - lazy-goose

### ISSUE THREAD

**Issue by lazy-goose** [rolling-scopes-school/support#894]
У меня День Рождения буквально через два дня и **Reviewer2** решил подарить мне новых эмоций.

1. A link to your deployed project
    - [Self-introduction YouTube video](https://youtu.be/V8BL5Zmlyww)

2. A link to the project repository on Github.
    - [Private repository: https://github.com/rolling-scopes-school/lazy-goose-JSFE2023Q1/tree/self-introduction](https://github.com/rolling-scopes-school/lazy-goose-JSFE2023Q1/tree/self-introduction)

3. A link to the task
    - [Self-introduction task link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/self-introduction)

4. A screenshot of cross-checking marks
![Karl Marx](https://github.com/rolling-scopes-school/support/assets/119844669/219a2dea-ddbf-42e2-8377-78dbab6131f0)

5. A final score after self-assessment, with comments

---

- [x] Есть ссылка на видеозапись выступления. В видео автор рассказывает о себе на английском языке, видео имеет длительность около 3–5 минут (отклонение в пределах 15 секунд ошибкой считать не нужно) — +50 баллов
- [x] Есть транскрипт выступления. Транскрипт на английском языке и содержит полный текст выступления (может быть незначительно отредактирован) — +50 баллов

**Итого**: 50 + 50 = 100

---

Ситуация не из приятных. Записал видео, приложил транскрипт, но человек в описании не заметил ссылку на Github Gist, в который я вложил транскрипт. Я попытался ему отписать, но он решил мне не отвечать. Честно, просто очень обидно, блин. Если бы нашёлся четвёртый проверяющий на это задание, то здесь не было бы лишней Issue.

Также хотелось бы, чтобы разработчики RSSApp сделали возможным получение уведомлений от проверяемых студентов не только в форме Cross-Сheck отдельного студента, но и общей странице приложения.

Картинка того самого Gist файла.
![image](https://github.com/rolling-scopes-school/support/assets/119844669/b9402043-55f3-4dea-8dc1-34069101d29b)

6. A cross-check score of your Score
![image](https://github.com/rolling-scopes-school/support/assets/119844669/a1ae89dc-6e25-40c2-9a01-067b1bb95537)

Был бы очень благодарен, если поможете. Заранее спасибо.

**Comment by helenakrasnova** [comment]
отсутствует A final score after self-assessment

**Comment by lazy-goose** [comment]
To @helenakrasnova, Исправил

**Comment by lyutails** [comment]
hey there o/
all good

- [x] video with speech about author +50
- [x] speech transcript (text) +50

final score: **100**

@helenakrasnova take a look at please

**Comment by lazy-goose** [comment]
To @helenakrasnova

Что нужно делать дальше, чтобы обновился Score?

**Comment by helenakrasnova** [comment]
подождать пока у меня будет время обновить скор

**Comment by lazy-goose** [comment]
Выражаю вам огромную благодарность:
- Спасибо @lyutails за то, что самоотверженно вызвались помочь перепроверять задание.
- Спасибо @helenakrasnova за качественную модерацию.

<img width="75%" height="auto" src="https://github.com/rolling-scopes-school/support/assets/119844669/42f5a4c0-7e8b-46b7-9b43-5e55c11123f6" />
