### ISSUE TITLE
Cross-Check Node.js Basics - larisagonchar

### ISSUE THREAD

**Issue by larisagonchar** [rolling-scopes-school/support#897]
1. A link to the project repository on Github.
    - [(https://github.com/larisagonchar/node-nodejs-basics/tree/nodejs-basics)](https://github.com/larisagonchar/node-nodejs-basics/tree/nodejs-basics)
    - PR: https://github.com/larisagonchar/node-nodejs-basics/pull/1
2. A link to the task
    - [(https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md)](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md)
3. A Link to the checklist for evaluating the task (if it exists)
    - [(https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/score.md)](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/score.md)
4. A screenshot of cross-checking marks
- No marks 
<img width="406" alt="image" src="https://github.com/rolling-scopes-school/support/assets/70719390/7aebd6d8-68f4-497f-b378-de3ea4902b4b">

6. A final score after self-assessment, with comments
- 206 / 206 all tasks completed

**Comment by helenakrasnova** [comment]
привет, а где история разработки? задание сделано одним коммитом

**Comment by larisagonchar** [comment]
@helenakrasnova Привет, я уже после задания увидела, что нужна история коммитов, поэтому во второй таске уже все гуд, а тут так. У нас просто на проекте в одном мре старались делать один коммит, поэтому по привычке сделала так.

**Comment by AlreadyBored** [comment]
Cross-check score: 206
