### ISSUE TITLE
Cross-Check 'Node.js Basics' - 'allerk'

### ISSUE THREAD

**Issue by allerk** [rolling-scopes-school/support#898]
Forgot commit each solution one by one. Remembered only after deadline :(
1. A link to your deployed project
    - [https://github.com/allerk/node-nodejs-basics/pull/7](https://github.com/allerk/node-nodejs-basics/pull/7)
2. A link to the project repository on Github.
    - [https://github.com/allerk/node-nodejs-basics](https://github.com/allerk/node-nodejs-basics)
3. A link to the task
    - [https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/score.md](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/score.md)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/57296937/7c326eed-3f89-431f-ac57-53ab731a2f51)

6. A final score after self-assessment, with comments
## Basic Scope

- File system (src/fs)
    - **+6** `create.js` implemented properly 6/6
    - **+10** `copy.js` implemented properly 6/6
    - **+10** `rename.js` implemented properly 6/6
    - **+6** `delete.js` implemented properly 6/6
    - **+6** `list.js` implemented properly 6/6
    - **+6** `read.js` implemented properly 6/6
- Command line interface(src/cli)
    - **+6** `env.js` implemented properly 6/6
    - **+6** `args.js` implemented properly 6/6
- Modules(src/modules)
    - **+20** `cjsToEsm.cjs` refactored properly 20/20
- Hash (src/hash)
    - **+10** `calcHash.js` implemented properly 10/10
- Streams (src/streams)
    - **+10** `read.js` implemented properly 10/10
    - **+10** `write.js` implemented properly 10/10
    - **+10** `transform.js` implemented properly 10/10
- Zlib (src/zip)
    - **+10** `compress.js` implemented properly 10/10
    - **+10** `decompress.js` implemented properly 10/10

## Advanced Scope

- Worker Threads (src/wt)
    - **+10** `worker.js` implemented properly 10/10
    - **+30** `main.js` implemented properly 20/30 (the result in the array is not in the same order that workers were created)
- Child Processes (src/cp)
    - **+10** spawns child process 5/10 (not included in spawn method options that create ipc channel)
    - **+10** child process `stdin` receives input from master process `stdin` 10/10
    - **+10** child process `stdout` sends data to master process `stdout` 10/10
   
Total: 183/206

**Comment by helenakrasnova** [comment]
название ишью должно быть в виде `Cross-Check 'название таска' - 'Ваше имя на Github'`

**Comment by allerk** [comment]
Исправил

**Comment by AlreadyBored** [comment]
## Basic Scope

- File system (src/fs)
    - **+6** `create.js` implemented properly **0/6 does not create file, does not throws error**
    - **+10** `copy.js` implemented properly **6/6**
    - **+10** `rename.js` implemented properly **0/6 does not rename file, throws error**
    - **+6** `delete.js` implemented properly **0/6 does not delete file, throws error**
    - **+6** `list.js` implemented properly **6/6**
    - **+6** `read.js` implemented properly **0/6 does not read file, throws error**
- Command line interface(src/cli)
    - **+6** `env.js` implemented properly **6/6**
    - **+6** `args.js` implemented properly **6/6**
- Modules(src/modules)
    - **+20** `cjsToEsm.cjs` refactored properly **10/20 throws error on running**
- Hash (src/hash)
    - **+10** `calcHash.js` implemented properly **10/10**
- Streams (src/streams)
    - **+10** `read.js` implemented properly **10/10**
    - **+10** `write.js` implemented properly **10/10**
    - **+10** `transform.js` implemented properly **10/10**
- Zlib (src/zip)
    - **+10** `compress.js` implemented properly **10/10**
    - **+10** `decompress.js` implemented properly **5/10 does not decompress compressed file to initial, creates different instead**

## Advanced Scope

- Worker Threads (src/wt)
    - **+10** `worker.js` implemented properly **0/10 error on running code**
    - **+30** `main.js` implemented properly **0/30 error on running code**
- Child Processes (src/cp)
    - **+10** spawns child process **10/10**
    - **+10** child process `stdin` receives input from master process `stdin` **10/10**
    - **+10** child process `stdout` sends data to master process `stdout` **0/10 it’s not logged into master process stdout**

## Forfeits

- **-95% of total task score** Any external tools/libraries are used **N/A**
- **-30% of total task score** Commits after deadline (except commits that affect only Readme.md, .gitignore, etc.) **N/A**

Total score: **109**
