### ISSUE TITLE
Cross-Check 'File Manager' 'ylepner'

### ISSUE THREAD

**Issue by ylepner** [rolling-scopes-school/support#899]
1. A link to your deployed project
    - [deploy](https://github.com/ylepner/file-manager/pull/1)
2. A link to the project repository on Github.
    - [repository](https://github.com/ylepner/file-manager)
3. A link to the task
    - [task](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [checklist](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/score.md)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/49253211/0f9bf8f3-2920-43de-bcb5-d1e35f9a7242)

7. A final score after self-assessment, with comments
310 / 330
Brotli algorithm wasn't used for compress and decompress operations -20 points

9. A cross-check score of your Score
No checked

**Comment by helenakrasnova** [comment]
кросс-чек по file manager еще не закончился, вас все еще могут проверить
cross check deadline: 2023-07-03 01:59

**Comment by ylepner** [comment]
Поняла, извините:( Жду тогда дальше. Удалите мой issue?

**Comment by helenakrasnova** [comment]
подождите дедлайн, если никто не оценит - я переведу в help wanted

**Comment by ylepner** [comment]
Все в порядке, работу оценили, спасибо!
