### ISSUE TITLE
Cross-Check 'Webdev' - Ortophius

### ISSUE THREAD

**Issue by ortophius** [rolling-scopes-school/support#90]
1. **Ссылка на деплой вашего проекта**: https://ortophius-webdev.netlify.app/
2. **Ссылка на репозиторий с проектом на GitHub**: https://github.com/rolling-scopes-school/ortophius-JS2020Q3/
3. **Оценка в результате самопроверки**:
При проверке на 1600px страница полностью соответствует макету, поэтому моя оценка - 95, так как единственная проблема - это отсутствие валидации в поле your email.
  **Аргументация оценки**: 
Макет верстался в соответствии со старой версией [макета](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/markups/level-1/webdev/webdev.jpg) , в описании задания было указано, что это не критично. 
Более того, создатель макета [сообщил](https://youtu.be/mkttCkHiYck?t=43), что первый экран (your life) необходимо сделать во всю высоту экрана и порекомендовал адаптивную, а не фиксированную верстку, однако все проверяющие сняли баллы за каждую секцию, так как проверяли на разрешении выше, чем 1600px, из-за чего содержимое секций было размещено более широко в отличие от макета на родном разрешении. В условиях описано, что проверка обязательно должна проводиться на разрешении 1600px.
4. **Оценка cross-check**:  84 / 100 | *0.5 = **42.00**

**Оценки**:

1. **Score: 88**
1.1 **Комментарий проверяющего**: Визуальные отклонения в блоках: Your Life, Rappresent, Our Community, Footer.
1.2 **Мой комментарий**: На разрешении 1600px со старым макетом отклонений от pp нет.

2. **Score: 20**
2.1 **Комментарий проверяющего**: Your work doesn't fit task requirements. The block, image, and text element in each block violate dimensions in width and height by more than 5px.You have violated the full list of possible errors.
2.2 **Мой комментарий**: Пропорции всех элементов соответствуют макету, комментарий проверяющего не содержит никакой конкретики и примеров. Могу предположить, что этот студент просто ставит 20 баллов всем с одинаковым комментарием.

3. **Score: 77**
3.1 **Комментарий проверяющего**: 
Страница открывается по указанной ссылке - 20
Header - 7 (-3 балла, т.к. расположение всего блока отличаются более чем на 5px от макета)
Your Life - 7 (-3 балла, т.к. расположение всего блока отличаются более чем на 5px от макета)
Rappresent - 7 (-3 балла, т.к. расположение картинки, кнопки и текста отличается более чем на 5px от макета)
Our Community - 7 (-3 балла, т.к. расположение содержимого отличается более чем на 5px от макета)
Implement - 7 (-3 балла, т.к. расположение содержимого отличается более чем на 5px от макета)
Sign Up - 8 (-2 балла, т.к. поле your email должно иметь валидацию на тип email)
Download - 7 (-3 балла, т.к. расположение содержимого отличается более чем на 5px от макета)
Footer - 7 (-3 балла, т.к. расположение содержимого отличается более чем на 5px от макета)
3.2 **Мой комментарий**: Проверка явно была не на ширине экрана 1600px, в большинстве пунктов баллы сняты из-за первой секции, которая была во весь экран, в остальных случаях отклонений от pp на исходном разрешении нет.

4. **Score: 77**
4.1 **Комментарий проверяющего**: 
Деплой 20 / 20
Header:   10 / 10
Блок Your Life  7 / 10. Несовпадение размера с макетом
Блок Rappresent   7 / 10. Отклонение теста и картинки больше чем на 5px относительно макета
Блок Our Community    7 / 10. Картинка мало обрезана  
Блок Implement  10  / 10 
Блок Sign Up   7  / 10. Несовпадение размера блока 
Блок Download  10 / 10
Footer   10 / 10
4.2 **Мой комментарий**:
Блок your life: Полное совпадение всех отдельных элементов по pp: https://prnt.sc/uopm80
Блок rappresent: Полное совпадение с учетом погрешностей на разрешении 1600px: https://prnt.sc/uopmpp
Блок Our Community: Абсолютно не ясно, о чем речь, картинка обрезана ровно в соответствии с макетом: https://prnt.sc/uopn1l
Блок Sign Up: Всё верно, размер блока не совпадает с новым макетом: https://prnt.sc/uopnky , однако страница версталась по [старому макету](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/markups/level-1/webdev/webdev.jpg)
Данный комментарий можно отнести ко всем остальным оценкам.

**Comment by alexk08** [comment]
Доброго времени суток. У меня очень похожая история, также блок your-life 100vh, и такой же таинственный проверяющий с комментарием in english. Есть мнение, что это один человек, ну либо поразительное совпадение)

Score: 20
-10, it's not 1600px, it uses full width.
It doesn't match the layout completely (look with pixel perfect) 

вот моя реализация верстки https://rolling-scopes-school.github.io/alexk08-JS2020Q3/webdev/

**Comment by Alexey-Koren** [comment]
@ortophius Оформите заявку по шаблону https://docs.rs.school/#/cross-check-flow

**Comment by ortophius** [comment]
> @ortophius Оформите заявку по шаблону https://docs.rs.school/#/cross-check-flow
Готово, нужно ещё что-то изменить?

**Comment by Alexey-Koren** [comment]
@ortophius Укажите в самом начале 4-м пунктом итоговую оценку

**Comment by ortophius** [comment]
> @ortophius Укажите в самом начале 4-м пунктом итоговую оценку

Добавил

**Comment by valerydluski** [comment]
1. Деплой (+20)
  Если страница открывается по указанной ссылке, и она не пустая, то ставим +20. Это означает что деплой и условия использования репозитория сделаны верно.
2. Header (+10)
3. YourLife
  Весь блок уплыл высота стоит 100vh. Не соответствует  макету (-3)
4. Rappresent (+10)
5. Our Community (+10)
6. Implement (+10)
7. Sign Up (+8)
  нет валидации (-2)
8. Download(+10)
9. Footer (+10)

Итого: 95 баллов

**Comment by ortophius** [comment]
@valerydluski Спасибо, но в аппе оценка не изменилась. Нужно подождать, или что-то пошло не так?

**Comment by valerydluski** [comment]
Ждите, оценки я менять не могу.
