### ISSUE TITLE
Cross-Check 'File Manager' 'gadkiyabram'

### ISSUE THREAD

**Issue by GadkiyAbram** [rolling-scopes-school/support#900]
1. A link to your deployed project
    [- [link](https://github.com/)](https://github.com/GadkiyAbram/rss23-file-manager/pull/1)
2. A link to the project repository on Github.
    [- [link](https://github.com/)](https://github.com/GadkiyAbram/rss23-file-manager/tree/rss23-file-manager-feature)
3. A link to the task
    [- [link](https://github.com/)](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    [- [link](https://github.com/)](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/score.md)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/20631015/3979d416-61ff-43ee-a868-dfce59bd8106)

6. A final score after self-assessment, with comments
Total Score: 330 from 330, all points implemented and working 

Kindly ask to check my PR. Because of my mistake, I forgot to change the repository from 'private' to 'public', that is why guys could not perform the Cross-check review.
7. A cross-check score of your Score 
0

**Comment by helenakrasnova** [comment]
У вас была неделя на сабмит таска и еще 6 дней на кросс-чек
