### ISSUE TITLE
CoreJS#1 issue

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/support#901]
Этот тред создан для решения проблем возникающих в процессе прохождения coreJS#1 интервью.
Если не зарегистрировались во время это issue не для вас

Например:

- Не могу связаться с ментором для прохождения  coreJS#1, так как в его профиле не указаны контакты
- Контакты есть, но ментор не отвечает более 3х дней
- Ментор отказывается проводить интервью

**Comment by ashtotakoe** [comment]
Здравствуйте, ментор отказывается проводить интервью

<img width="1004" alt="Снимок экрана 2023-07-06 в 17 03 21" src="https://github.com/rolling-scopes-school/support/assets/101500044/325a570b-dfc5-4bcb-8256-8060739fe1e8">

**Comment by maxsimusprime** [comment]
Мой ментор в течении 3-х дней не вышел на связь(не ответил на сообщения) по всем предоставленным контактам

**Comment by Zhiznevski** [comment]
Ментор не выходит на связь. Написал ему в телеграмм и на почту во вторник

**Comment by kontinentkm** [comment]
мой ментор тоже не выходит на связь

**Comment by fasty86** [comment]
У меня тоже **второй** пункт, пробовал связаться по всем контактам указанным.

**Comment by ghost** [comment]
Я зарегистрировалась для участия в CoreJS Interview, но мне не назначили ментора. Есть ли у CoreJS Interview список waitlist? Если его нет имеет ли это какое-либо влияние на получение сертификата?

**Comment by natein** [comment]
@rikkimonti1984 
Waitlist есть и ты там. На сертификат нужно набрать 70% от максимума. У тебя пока очень мало баллов.

**Comment by iradzh** [comment]
и мой ментор не выходит на связь

**Comment by toma-fedyanova** [comment]
Здравствуйте Контакты есть, но ментор  не отвечает более 3х дней

**Comment by SoloSoft2000** [comment]
Здравствуйте Контакты есть, но ментор не отвечает более 3х дней

**Comment by ForsyteRun** [comment]
Здравствуйте Контакты есть, но ментор не отвечает более 3х дней

**Comment by DanilBogdanov** [comment]
Добрый день! Назначенному ментору написал в телеграмм сразу как появились контакты, сообщение дошло но ментор не отвечал. Затем сообщение продублировал в дискорд и на почту с отслеживанием письма, в течении нескольких минут пришло уведомление, что письмо было прочитано. Ответа также не последовало.

**Comment by majustman** [comment]
Дд! Ментор не выходит на связь! Написал в дискорде 4 июля.

**Comment by dima92** [comment]
Добрый день! Ментор не выходит на связь. 
![image](https://github.com/rolling-scopes-school/support/assets/9913325/03f7c74f-de10-400c-b0c1-98aaa947990f)
Ментор ответил по почте

**Comment by valerydluski** [comment]
@ashtotakoe у тебя новый ментор для прохождения интервью

**Comment by valerydluski** [comment]
@kontinentkm ментор сказал, что с ним связались 3 студента из 4-х подтверди что ты связался

**Comment by valerydluski** [comment]
@iradzh Твой ментор в отпуске до 10-го июля, напиши ему 10-го числа

**Comment by valerydluski** [comment]
@toma-fedyanova у тебя новый ментор для прохождения интервью

**Comment by TatsianaSauko** [comment]
Мой ментор ответил, что у него много работы и Rolling School не занимается.

**Comment by valerydluski** [comment]
@fasty86 ментор сказал, что ответил тебе

**Comment by fasty86** [comment]
> @fasty86 ментор сказал, что ответил тебе

Ага, только что списались.

**Comment by Volasau** [comment]
Ментор не выходит на связь. Сообщение, мною отправленное на телеграм,  он удалил, в дискорте не откликается.

**Comment by lidasharova** [comment]
Мой ментор не отвечает с 4 июля.

**Comment by svk-man** [comment]
Интервьюер на CoreJS Interview 1 не выходит на связь, написал по нескольким контактам:
discord: > 3 дней
tlg: со вчера
почта: около трёх часов

**Comment by DIvanov1ch** [comment]
Ментор не выходит на связь . Писал в Telegram, Skype и на почту. Нигде нет ответа.

**Comment by capapa** [comment]
Написал в телеграмме своему ментору 05.07.2023, но он не ответил, потом я не смог найти это сообщение, похоже что он удалил его. Сейчас написал повторно, но пока молчит. Все контакты которые были указаны в его профиле теперь отсутствуют.

**Comment by valerydluski** [comment]
@Zhiznevski твой ментор до понедельника в отпуске, попробуй связаться после понедельника

**Comment by aliakseidomut** [comment]
Написал ментору 5 июля, но он до сих пор не вышел на связь

**Comment by intelligentRaji** [comment]
Мой ментор не выходит на связь

**Comment by ostandrey** [comment]
Не могу связаться с ментором для прохождения coreJS#1, так как не отображаются данные о менторе

**Comment by lidrail35** [comment]
Ментор по почте не отвечает, в дискорде не ищется. Другие контакты не указаны.

**Comment by valerydluski** [comment]
@Volasau у тебя новый ментор

**Comment by anastakozz** [comment]
ментор ответил в телеграме 4 июля, но пока не назначил дату интервью и не подтвердил, что проведет его. С тех пор на связь не выходит UPD: ура, связались!

**Comment by valerydluski** [comment]
@capapa у тебя новый ментор для прохождения интервью

**Comment by MashaBogdanova** [comment]
Привет, мой интервьювер не вышел на связь в течение трех дней, есть только контакт в телеграмм, сообщения не прочитаны

**Comment by svk-man** [comment]
> Интервьюер на CoreJS Interview 1 не выходит на связь, написал по нескольким контактам: discord: > 3 дней tlg: со вчера почта: около трёх часов

Интервьюер вышел на связь в тлг

**Comment by valerydluski** [comment]
@maxsimusprime ты связался с ментором?

**Comment by valerydluski** [comment]
@majustman @AliakseiDonut у вас новый ментор для прохождения интервью

**Comment by DanilBogdanov** [comment]
> Добрый день! Назначенному ментору написал в телеграмм сразу как появились контакты, сообщение дошло но ментор не отвечал. Затем сообщение продублировал в дискорд и на почту с отслеживанием письма, в течении нескольких минут пришло уведомление, что письмо было прочитано. Ответа также не последовало.

Ментор ответил.

**Comment by valerydluski** [comment]
@TatsianaSauko у тебя новый ментор для прохождения интервью

**Comment by maxsimusprime** [comment]
> @maxsimusprime ты связался с ментором?

Все ОК, созвонились! Спасибо!

**Comment by Zhiznevski** [comment]
> @Zhiznevski твой ментор до понедельника в отпуске, попробуй связаться после понедельника

Ментор вышел на связь, договорились о проведении интервью на следующей неделе, спасибо!)

**Comment by valerydluski** [comment]
@intelligentRaji получилось связаться с ментором?

**Comment by valerydluski** [comment]
@ostandrey тебе не хватило ментора, ты в wait list

**Comment by valerydluski** [comment]
@DIvanov1ch ментор сказал, что ответил тебе

**Comment by MashaBogdanova** [comment]
Ментор вышел на связь, все ок

**Comment by DIvanov1ch** [comment]
> @DIvanov1ch ментор сказал, что ответил тебе

Да. Ответила сегодня. Но время ещё не согласовали

**Comment by valerydluski** [comment]
@lidrail35 я без проблем нашёл ментора в дискорде

**Comment by lidrail35** [comment]
UPD: Ментор отозвался, договорились о дате интервью.

Теперь и у меня нашелся, а тогда ни в какую, чудно. Написал еще и в дискорд, жду ответа.

**Comment by whiterabbit8** [comment]
Ментор не явился на интервью, на сообщения либо отвечает долго, либо вообще может прочитать и не ответить, надо дергать постоянно. Отвечает однословно. Подозрительный какой-то в общем.

**Comment by natein** [comment]
@whiterabbit8 
Я поговорила с ментором и он обещал с тобой связаться.
