### ISSUE TITLE
 Cross-Check 'CV#3. CV. Cross-Check' - 'Elena Zimakova'.

### ISSUE THREAD

**Issue by nestoflaziness** [rolling-scopes-school/support#902]
1. A link to my deployed project:
    - [https://nestoflazy.github.io/rsschool-cv](https://nestoflazy.github.io/rsschool-cv/)
2. A link to the project repository on Github:
    - [https://github.com/nestoflazy/rsschool-cv/tree/rsschool-cv-html](https://github.com/nestoflazy/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task:
    - [https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md)
4. A Link to the checklist for evaluating the task (CV#3. CV. CROSS-CHECK):
    - [https://rolling-scopes-school.github.io/checklist/](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks:
![rs-submit](https://github.com/rolling-scopes-school/support/assets/44233799/4b703198-ba61-4e67-ba34-ce4e8497f222)
6. A final score after self-assessment 120 (130): because all the requirements for the checklist "CV#3. CV. CROSS-CHECK" are met
7. A cross-check score: 112

**Comment by helenakrasnova** [comment]
Апелляция производится только если ожидаемый вами балл и полученный по результатам кросс-чека балл отличаются на 10 и более процентов от максимального балла за задание.
Отличие менее 10%
