### ISSUE TITLE
Cross-Check 'Battleship' - 'shopot'

### ISSUE THREAD

**Issue by shopot** [rolling-scopes-school/support#903]
1. A link to your deployed project
    - [Link to PR](https://github.com/shopot/battleship/pull/1)
2. A link to the project repository on Github.
    - [Link to PR](https://github.com/shopot/battleship/pull/1)
3. A link to the task
    - [battleship](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/battleship/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [https://rsschool-check-loader.netlify.app](https://rsschool-check-loader.netlify.app/)
5. A screenshot of cross-checking marks
![screen-01](https://github.com/rolling-scopes-school/support/assets/1072928/5a5315ab-de40-4c5e-924e-8a498ed5c689)
![screen-02](https://github.com/rolling-scopes-school/support/assets/1072928/0d05d1a6-1e77-47e4-b51b-0a4f908bf9e9)

6. A final score after self-assessment, with comments
188
Everything is done and everything works

7. A cross-check score of your Score 
154

**Comment by helenakrasnova** [comment]
To fix:
1. Название ишью должно быть по шаблону Cross-Check 'название таска' - 'Ваше имя на Github'.
2. Скриншот с оценками всех проверяющих за cross-check (контакты проверяющих должны быть скрыты). - пункт 5
3. Балл за cross-check из вашего Score. - пункт 7

**Comment by shopot** [comment]
Fixed

**Comment by kele6ra** [comment]
Score 188/188
Basic Scope

Websocket
+6 Implemented workable websocket server  6/6
+6 Handle websocket clients connection/disconnection properly  6/6
+10 Websocket server message handler implemented properly  10/10
+10 Websocket server message sender implemented properly  10/10

User
+5 Create user with password in temporary database  5/5
+5 User validation 5/5

Room
+6 Create game room  6/6
+6 Add user to game room  6/6
+6 Start game  6/6
+6 Finish game  6/6
+8 Update room's game state  8/8
+4 Update player's turn  4/4
+8 Update players winner table  8/8

Ships
+10 Locate ship to the game board   10/10

Game
+8 Attack 8/8
+4 Random attack  4/4

Advanced Scope
+30 Task implemented on Typescript   30/30
+20 Codebase is separated (at least 4 modules) 20/20
+30 Make bot for single play (optionally) 30/30

**Comment by ThorsAngerVaNeT** [comment]
@shopot your score is updated

**Comment by shopot** [comment]
Thanks a lot.
