### ISSUE TITLE
Cross-Check 'Async Race' - 'irinaenotova'

### ISSUE THREAD

**Issue by IrinaEnotova** [rolling-scopes-school/support#904]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/irinaenotova-JSFE2023Q1/async-race/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/irinaenotova-JSFE2023Q1/tree/async-race)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/async-race.md)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/102694649/ba97cb51-6e12-44ce-b446-8b747876d3cc)

![image](https://github.com/rolling-scopes-school/support/assets/102694649/70d0ad52-9ea9-43e6-9e8b-8bf52fd3f3ac)

![image](https://github.com/rolling-scopes-school/support/assets/102694649/03dcbdd6-7c0c-47dc-8381-6085496f2a68)

![image](https://github.com/rolling-scopes-school/support/assets/102694649/071c0b2e-2858-427b-984e-1b6ada6cb4ce)

7. A final score after self-assessment, with comments - I rate my work 180 points - I agree that you can catch a minor bag, but the rest part is hard to find a fault. The student who rate my work 105 points clearly checks works badly 

8. A cross-check score of your Score - 177

**Comment by helenakrasnova** [comment]
- Апелляция производится только если ожидаемый вами балл и полученный по результатам кросс-чека средний балл отличаются на 10 и более процентов от максимального балла за задание.
- Коммиты после дедлайна
