### ISSUE TITLE
Cross-Check 'GraphQL Basics' - 'AndreiZaretski'

### ISSUE THREAD

**Issue by AndreiZaretski** [rolling-scopes-school/support#905]
1. A link to your deployed project

    - [link to PR](https://github.com/AndreiZaretski/rsschool-nodejs-task-graphql/pull/1)
   
2. A link to the project repository on Github.

    - [link to PR](https://github.com/AndreiZaretski/rsschool-nodejs-task-graphql/pull/1)
  
3. A link to the task

    - [GraphQL Basics - assignment](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/graphql-service/assignment.md)
 
4. A Link to the checklist for evaluating the task (if it exists)

    - [GraphQL Basics - score ](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/graphql-service/score.md)
  
5. A screenshot of cross-checking marks

   ![изображение](https://github.com/rolling-scopes-school/support/assets/105275676/966513c3-437f-43fc-a073-5f2da9d58b51)

6. A final score after self-assessment, with comments

   252/360
  
  ![изображение](https://github.com/rolling-scopes-school/support/assets/105275676/7cc05460-34b1-4bb8-bdc4-268b56859828)

   1.1. npm run test-queries +144

   ![изображение](https://github.com/rolling-scopes-school/support/assets/105275676/313260a6-b299-4311-aca4-bcf902c2ce90)
   1.2 npm run test-mutations +90
    
   ![изображение](https://github.com/rolling-scopes-school/support/assets/105275676/4bf90b7c-4443-4341-84ed-79c56c53552f)
    
   2.1 npm run test-rule +18

   ![изображение](https://github.com/rolling-scopes-school/support/assets/105275676/d2081e27-000c-4756-a518-54f7d81d2ea9)

   3.1 npm run test-loader -80
   3.2 npm run test-loader-prime  -28
   
7. A cross-check score of your Score 
   
    135

**Comment by nosbog** [comment]
Принимаю апелляцию с повышенем оценки до 252

**Comment by ThorsAngerVaNeT** [comment]
Выставил оценку
