### ISSUE TITLE
Cross-Check GraphQL Basics - UlianaSavi.

### ISSUE THREAD

**Issue by UlianaSavi** [rolling-scopes-school/support#906]
1. A link to your deployed project
    - [-](-)
2. A link to the project repository on Github.
    - [link](https://github.com/UlianaSavi/rsschool-nodejs-task-graphql)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/graphql-service/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/graphql-service/score.md)
5. A screenshot of cross-checking marks
![изображение](https://github.com/rolling-scopes-school/support/assets/105851981/7ba5723c-fed7-49f4-8c93-b2c55a07b981)
6. A final score after self-assessment, with comments - `332 / 360` (comments in my [PR](https://github.com/UlianaSavi/rsschool-nodejs-task-graphql/pull/1))
7. A cross-check score of your Score - `175 / 360`

**Comment by helenakrasnova** [comment]
п. 5. Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).

**Comment by UlianaSavi** [comment]
@helenakrasnova  - замазала контакты проверяющих

**Comment by nosbog** [comment]
Здесь не может быть и речи о повышении балла. Везде, где были дыры в тестах, вы там пролезли.
Нет типизации, нет форматирования кода. Много ошибок:
Лоудеры должны создаваться под каждый запрос
Нет лоудера для подписчиков
Неправильно сделанная логика для подписчиков внутри resolver. Во-первых, их может быть >1. Во-вторых, используется неправильная таблица и вы просто переименовываете поле с authorId на id...
Поля, которые должны быть nonNull, все опциональные
Есть места, где UUIDType не используется, например, в Inputs
Нет всех необходимых полей для changeInput-ов

**Comment by nosbog** [comment]
Я принимаю апелляцию, но только с повышением до 252 (без учета баллов за test-loader).

**Comment by ThorsAngerVaNeT** [comment]
Выставил оценку
