### ISSUE TITLE
 Cross-Check 'Library 1' - 'Suficks'

### ISSUE THREAD

**Issue by Suficks** [rolling-scopes-school/support#907]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/suficks-JSFEPRESCHOOL2023Q2/library/
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/suficks-JSFEPRESCHOOL2023Q2/tree/library
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/library/library-part1.md
4. A Link to the checklist for evaluating the task (if it exists)
    - 
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/134487538/085c048a-a877-4c76-b423-42f377751549)
![image](https://github.com/rolling-scopes-school/support/assets/134487538/29785b7d-f272-42b5-9860-51c0d1aa8c6a)
![image](https://github.com/rolling-scopes-school/support/assets/134487538/27b41a5f-e911-4bfa-bf23-9766e2f5d36c)

6. A final score after self-assessment, with comments
Результата самопроверки - 98 баллов. 2 балла снято за расхождение больше 10 пикселей по радиокнопкам в favorites.
7. A cross-check score of your Score 
93/100

**Comment by Suficks** [comment]
Третий проверяющий проверил работу за несколько часов до окончания кросс-чека, не оставил свои контакты, оценив работу максимально не объективно, с комментарием, не описывающим конкретное снижение, с комментарием по причинам, которые не оцениваются в задании. 
![image](https://github.com/rolling-scopes-school/support/assets/134487538/96f9bd10-b60c-49d4-a011-eb5edcd47814)
Верстка не съезжает нигде.
Учитывая, что остальные проверяющие адекватно оценили работу, очень надеюсь, что такое некрасивое поведение не будет поощряться на таком прекрасном курсе!

**Comment by Suficks** [comment]
Я сделала один коммит после дедлайна, исправила div на form, мне дали +2 балла. Это не связано с теми ошибками, которые якобы нашел третий проверяющий, очень прошу понять и простить!!

**Comment by helenakrasnova** [comment]
- Апелляция производится только если ожидаемый вами балл и полученный по результатам кросс-чека средний балл отличаются на 10 и более процентов от максимального балла за задание.
- Коммиты после дедлайна

**Comment by Suficks** [comment]
Ясно, можно ставить какие угодно баллы, лишь бы они входили в разницу 10%, которая получается благодаря другим адекватным оценкам. 
Все логично, спасибо большое!!
