### ISSUE TITLE
Cross-Check 'webdev' - 'Maxtadont'

### ISSUE THREAD

**Issue by Maxtadont** [rolling-scopes-school/support#91]
Ссылка на деплой проект: https://rolling-scopes-school.github.io/maxtadont-JS2020Q3/webdev
Ссылка на репозиторий: https://github.com/rolling-scopes-school/maxtadont-JS2020Q3

Оценка в ходе самопроверки: 100-9 = 91
(+20) Ссылка на деплой рабочая, страница не пустая
(+80) Все блоки присутствуют
(-2) Блок Rappresent. Для выделения важного текста должен использоваться тег strong у меня b
(-2) Блок Implement. Для выделения важного текста должен использоваться тег strong у меня b
(-2) Блок Sign Up. Нет анимации иконок
(-3) Не загрузился шрифт Roboto (из-за моей ошибки указал Robato) в результате мне снизили оценку по всем текстовым блокам на -24, хотя по сути это одна ошибка. 
Так же мне снизили оценку за валидацию email, хотя она присутствует.
Графические элементы и интерактивные элементы наложены по макету webdev. JPG (старая версия).
При загурженном шрифте Roboto текстовые блоки расходятся в пределах допустимых 5px.

Оценка в score 79.

Благодарю за внимание.

**Comment by valerydluski** [comment]
Апелляция производится только если ожидаемый вами балл и полученным по результатам кросс-чека средний балл отличаются на 15 и более процентов.
