### ISSUE TITLE
library 2

### ISSUE THREAD

**Issue by berstix** [rolling-scopes-school/support#910]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/berstix-JSFEPRESCHOOL2023Q2/library/)
2. A link to the project repository on Github.
    - [link](https://rolling-scopes-school.github.io/berstix-JSFEPRESCHOOL2023Q2/library/)
3. A link to the task
    - [link](https://rolling-scopes-school.github.io/berstix-JSFEPRESCHOOL2023Q2/library/)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/55834040/8cacc960-71aa-43e9-837c-49385c0784e4)

6. A final score after self-assessment, with comments
- нет полосы прокрутки при ширине страницы от 1440рх до 640рх +4. (минус 4 балла)
- вывалился контент (минус 4 балла)
- нет pixel perfect (минус 2 балла)
- burger не по размеру (минус 6 баллов)
Итог: 34

7. A cross-check score of your Score 
Добрый день! Проблема в том что у меня проверили работу только один человек. Один проверяющий не смог выставить оценку непонятно почему, хотя у другого ранее всё получилось. Другой проверяющий вообще не проверил работу. Спасибо!

**Comment by WiiJoy** [comment]
- название ишуса должно быть вида `Cross-Check 'название таска' - 'Ваше имя на Github'.`
- коммиты после дедлайна
