### ISSUE TITLE
Сross-Check Library #2

### ISSUE THREAD

**Issue by EdwardHushaleu** [rolling-scopes-school/support#911]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/edwardhushaleu-JSFEPRESCHOOL2023Q2/library/
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/edwardhushaleu-JSFEPRESCHOOL2023Q2
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/library/library-part2.md
4. A Link to the checklist for evaluating the task (if it exists)
    - 
5. A screenshot of cross-checking marks
file:///home/dell/%D0%98%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F/%D1%81%D0%BA%D1%80%D0%B8%D0%BD

6. A final score after self-assessment, with comments
я считаю , что за задание должен быть максимальный балл, все пункты выполнены 
7. A cross-check score of your Score 
50

**Comment by WiiJoy** [comment]
- нет скриншота
- оценка 50 из 50

Апелляция рассматривается только в случае, если ожидаемая оценка будет на 10%+ отличаться от итоговой, выставленной в score
