### ISSUE TITLE
Cross-Check Library #2 - EkaterinaPanasiuk

### ISSUE THREAD

**Issue by EkaterinaPanasiuk** [rolling-scopes-school/support#912]
1. A link to your deployed project
    -       https://ekaterinapanasiuk.github.io/rsSchool_Library1/library/ 
2. A link to the project repository on Github.
    -    [[link](https://github.com/)](https://github.com/EkaterinaPanasiuk/rsSchool_Library1)
3. A link to the task
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/library/library-part2.md)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/105225301/096581a0-7e08-4707-a05b-298669aba4db)
![image](https://github.com/rolling-scopes-school/support/assets/105225301/60cb82ec-4143-4235-b94c-ca0a57d39e2c)

6. A final score after self-assessment, with comments 👍 Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
Оценка в результате самопроверки с ее аргументацией:-----------
Общая оценка 48 баллов:
блок

+2
Welcome +2
About +4. (не понятно как должна выглядеть высота стрелок с учетом сохранения расстояния межд картинкой и точками(40пх) (+2) + 5точек кнопку own(+2)
CoffeShop +4
Contacts +4
LibraryCard +4
+ 2 не появляется горизонтальная полоса (+4) элементы не выходят за пределы окна(+4) элементы не наезжают друг на друга(+4) адаптивное меню +12 отступ иконки юзера от правого края - 105px(+2) иконка юзера не прыгает(+2) при нажатии на бургер-иконку плавно появляется адаптивное меню +4 фдаптивное меню скрывается резко(0) ссылки в адаптивном меню работают(+2) PixelPerfect (+2)

7. A cross-check score of your Score :    25

**Comment by helenakrasnova** [comment]
- Задание выполнено не в приватном школьном репозитории
- Отсутствует пулл реквест в ветку main
- Скриншот с оценками за cross-check (контакты проверяющих должны быть скрыты).
- A cross-check score of your Score  не соответствует баллам из скора
