### ISSUE TITLE
CoreJS#2 issue

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes-school/support#914]
Этот тред создан для решения проблем возникающих в процессе прохождения coreJS#2 интервью.
Если не зарегистрировались во время это issue не для вас

Например:

- Не могу связаться с ментором для прохождения  coreJS#2, так как в его профиле не указаны контакты
- Контакты есть, но ментор не отвечает более 3х дней
- Ментор отказывается проводить интервью

**Comment by ForsyteRun** [comment]
Ментор не отвечает более 5-ти дней

**Comment by duumbling** [comment]
Ментор не отвечает менее 3 дней, но сегодня, вроде бы, дедлайн.

**Comment by sbaumgertner** [comment]
Добрый день. Ментор не отвечает 4 дня. UPD: связались, собеседование уже прошло

**Comment by Vanyha010** [comment]
Написал ментору ещё 16.08, но не отвечает до сих пор

**Comment by massaracsh7** [comment]
Добрый день, написала ментору в телеграмм и дискорд 16 августа, до сих пор нет ответа.
Ментор ответил. Спасибо

**Comment by VikaLubenets** [comment]
Добрый день! Ментор не отвечает с 15.08 (15 написала в дискорд, 17 продублировала запрос на почту). Пока нет ответа

UPD: ментор ответил сегодня, точную дату пока не назначил, попросил написать ему на следующей неделе.

**Comment by IgnisVulpe** [comment]
Добрый день! Писала ментору в телеграм 17.08.23. Ответа нет

**Comment by 5kazo4nik** [comment]
Здравствуйте, написал ментору 15 августа в телеграмм и 19 августа в дискорд. Сообщение прочитано, ответа нет.

**Comment by kirich8** [comment]
Добрый день, назначенный мне ментор может провести интервью только на украинском языке, а я его не знаю, ментор сказал оставить тут комментарий для замены.

**Comment by natein** [comment]
@Kirich8 Я с этим ментором 19 разговаривала и он даже взял ещё одного студента. Возможно просто забыл ответить. Попробуй ещё раз о себе напомнить.

**Comment by natein** [comment]
> Здравствуйте, написал ментору 15 августа в телеграмм и 19 августа в дискорд. Сообщение прочитано, ответа нет.

@5kazo4nik Я с этим ментором 19-го общалась в телеграме и он даже взял ещё одного студента. Возможно он просто забыл ответить. Попробуй напомнить о себе ещё раз.

**Comment by zweroboy1** [comment]
Добрый день. Ментор не отвечает 3 дня.

UPD. Отбой тревоги, ментор ответил, про интервью договорились.

**Comment by kostik-omsk** [comment]
Здравствуйте! Назначенный ментор не отвечает, первое сообщение писал 17.08 в дискорд, сегодня продублировал в телеграм, сообщение прочитано, ответа нет.

**Comment by natein** [comment]
> 

@zweroboy1 В телеграм писал? Я с ним недавно общалась.

**Comment by SkarabeyDM** [comment]
Ментор не отвечает менее трёх дней, но т.к. сегодня дедлайн, прошу уведомить её или другого назначить

**Comment by Gladkaay** [comment]
Здравствуйте, у ментора нет дискорда, и телеграмм не нахожу, ответа на email нет, правда менее 3-х дней

**Comment by VladimirTrainee** [comment]
Ментор не отвечает более 3-х дней

**Comment by zweroboy1** [comment]
> > 
> 
> @zweroboy1 В телеграм писал? Я с ним недавно общалась.

Да, в телеграм.

**Comment by Kiteqx** [comment]
Доброго времени суток. 
Контакты есть, но ментор не отвечает более 3х дней (тг/дискорд).

UPD: Ментор ответил, спасибо.

**Comment by ForsyteRun** [comment]
> Ментор не отвечает более 5-ти дней

Ментор ответил... спасибо

**Comment by KateGoncharik** [comment]
Здравствуйте. Написала 19.08(сб),  уже 23.08 и до сих пор нет ответа от ментора. Продублировала сообщение сегодня.
30.08 - до сих пор не отвечает.

**Comment by SwallowOnes** [comment]
Добрый день, написал ментору 21.08, на указанные почты и в скайп, ответа все еще нет.

**Comment by valerydluski** [comment]
@Vanyha010 ментор обещал отписать тебе сегодня

**Comment by valerydluski** [comment]
@IgnisVulpe получилось связаться?
как я вижу ментор в отпуске до первого сентября

**Comment by valerydluski** [comment]
@5kazo4nik получилось связаться?

**Comment by CarphatianSnake** [comment]
Добрый день!
Связался с ментором в первый же день распределения, на что получил ответ - "Напиши через 2 недели".
Прошло 2 недели, написал, получил ответ - "Напиши через неделю, очень загружен".
Вижу что есть все шансы пролететь с интервью. Прошу назначить мне другого, менее загруженного ментора...

**Comment by AmsterGet** [comment]
> Ментор не отвечает менее 3 дней, но сегодня, вроде бы, дедлайн.

@duumbling 
Привет
напиши мне плиз в телеграм - amsterget

**Comment by 5kazo4nik** [comment]
> @5kazo4nik получилось связаться?
Да, все получилось, интервью прошел)
Спасибо @natein за ответ)

**Comment by Vanyha010** [comment]
> Написал ментору ещё 16.08, но не отвечает до сих пор

UPD: ответил)

**Comment by duumbling** [comment]
@AmsterGet

Привет, не могу найти по нику, напиши, пожалуйста, ты
@Thzhdr

**Comment by valerydluski** [comment]
@Kirich8 назначил тебе нового ментора

**Comment by valerydluski** [comment]
@SwallowOnes ментор с тобой свяжется в ближайшее время

**Comment by Ge1o1Ge** [comment]
Здравствуйте, не досталось ментора, подсказали, что в листе ожидания нет
![image](https://github.com/rolling-scopes-school/support/assets/118926055/5986d7a7-6927-4f29-97f7-a2739717fd63)

**Comment by natein** [comment]
> Здравствуйте, не досталось ментора, подсказали, что в листе ожидания нет ![image](https://user-images.githubusercontent.com/118926055/266437307-5986d7a7-6927-4f29-97f7-a2739717fd63.png)

@Ge1o1Ge Тебе назначен интервьюер

**Comment by kristilight** [comment]
Здравствуйте, ситуация следующая,  договорились с интервьюером на 8 сентября (пятница), но он не появился. О переносе до сих пор не сообщил (11 сентября понедельник).

**Comment by valerydluski** [comment]
@kristalik8 у тебя новый ментор для интервью

**Comment by mnmsvlw** [comment]
Здравствуйте, писал ментору в августе, договорились, что проведем интервью в сентябре. Я написал 6 сентября, ментор до сих пор не ответил

**Comment by gtailde** [comment]
Здравствуйте. У меня было запланировано интервью на 10 сентября но в связи с непридвиденными обстоятельствами, я не смог присутствовать, я предупредил ментора с просьбой перенести на следующий день (на 11 сентября (дедлайн 12 сентября)),  но ментор не смог.
