### ISSUE TITLE
Cross-Check Library#3 - cupchik1

### ISSUE THREAD

**Issue by cupchik1** [rolling-scopes-school/support#915]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/cupchik1-JSFEPRESCHOOL2023Q2/library/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/cupchik1-JSFEPRESCHOOL2023Q2/tree/library-part3)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/library/library-part3.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/121886295/31e41a4e-afcf-4eae-b359-2dc763f4c4c9)

6. A final score after self-assessment, with comments 82/200

- Этап 1: Пользователь не зарегистрирован

  - Ограниченная карусель в блоке About (0)

  - Слайдер в блоке Favorites (0)

  - До регистрации ()

  - До авторизации (2)

- Этап 2: Пользователь на этапе регистрации

   - Меню авторизации при нажатии на иконку пользователя (8)

   - Модальное окно REGISTER (28)

  - Окончание регистрации (4)

  - При наличии регистрации, но будучи не авторизованным (0)

- Этап 3: Пользователь на этапе входа в учётную запись после регистрации.

  - Модальное окно LOGIN (26)

  - Блок Favorites (2)

 - Этап 4: Пользователь после входа в учётную запись

   - Меню профиля при нажатии на иконку с инициалами пользователя (12)

  - Модальное окно MY PROFILE (0)

   - Блок Favorites (0)

   - Модальное окно BUY A LIBRARY CARD (0)

   - Блок Digital Library Cards (0)
7. A cross-check score of your Score 46/200

**Comment by helenakrasnova** [comment]
коммиты после дедлайна
