### ISSUE TITLE
Cross-Check Library#3 - Forlocks

### ISSUE THREAD

**Issue by Forlocks** [rolling-scopes-school/support#917]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/forlocks-JSFEPRESCHOOL2023Q2/library/
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/forlocks-JSFEPRESCHOOL2023Q2
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/library/library-part3.md
4. A Link to the checklist for evaluating the task (if it exists)
    - https://rolling-scopes-school.github.io/checklist/
5. A screenshot of cross-checking marks
![Screenshot_79](https://github.com/rolling-scopes-school/support/assets/106630486/1b3c37dd-231e-4d00-b6c8-48fd663199b8)
6. A final score after self-assessment, with comments
198 баллов
Не выполненные/не засчитанные пункты:
- Блок Digital Library Cards. Если введённые имя и номер карты совпадают с данными пользователя, то отображается панель с информацией, вместо кнопки Check the card на 10 секунд.
- Там же после отображения информации, кнопка возвращается в прежнее состояние, а поля в форме сбрасываются. 
- При наличии авторизации вместо кнопки Check the Card будут отображаться данные пользователя и бейджи, как на дизайне LibraryCard after login in account.
Остальные пункты ТЗ полностью выполнены
7. A cross-check score of your Score 
0

**Comment by Forlocks** [comment]
Причина подачи апелляции - никто не проверил работу во время cross-check'a.

**Comment by helenakrasnova** [comment]
коммиты после дедлайна
