### ISSUE TITLE
Cross-Check Library#3 - isolomadin

### ISSUE THREAD

**Issue by isolomadin** [rolling-scopes-school/support#918]
1. A link to your deployed project
    - https://rolling-scopes-school.github.io/isolomadin-JSFEPRESCHOOL2023Q2/library/
2. A link to the project repository on Github.
    - https://github.com/rolling-scopes-school/isolomadin-JSFEPRESCHOOL2023Q2
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/library/library-part3.md
4. A Link to the checklist for evaluating the task (if it exists)
    - https://rolling-scopes-school.github.io/checklist/
5. A screenshot of cross-checking marks
<img width="1440" alt="image" src="https://github.com/rolling-scopes-school/support/assets/136390027/8360a0eb-e6c8-4bc2-9469-ff65f69ffc5c">
<img width="1440" alt="image" src="https://github.com/rolling-scopes-school/support/assets/136390027/519979dd-32fb-4bd0-8aa6-1a327f595e34">
<img width="1440" alt="image" src="https://github.com/rolling-scopes-school/support/assets/136390027/3bea23de-a366-4f54-b78e-0b2fce5be581">
<img width="1440" alt="image" src="https://github.com/rolling-scopes-school/support/assets/136390027/5dd36f53-6944-41f0-b09c-9ad29021f039">
<img width="1440" alt="image" src="https://github.com/rolling-scopes-school/support/assets/136390027/06679df4-7804-48b4-b6f0-3ed656fe1401">
<img width="1440" alt="image" src="https://github.com/rolling-scopes-school/support/assets/136390027/d76bdfdd-74fc-4d4b-a026-584ab9864ef3">
<img width="1440" alt="image" src="https://github.com/rolling-scopes-school/support/assets/136390027/bdb5bcea-140b-4a5e-99b5-a2a0cc1ec319">
<img width="1440" alt="image" src="https://github.com/rolling-scopes-school/support/assets/136390027/627ea3c7-a4f7-4b65-8507-3ee8f47a90c1">

6. A final score after self-assessment, with comments
150 / 200
Частично выполненные пункты:

Карусель реагирует на нажатие кнопок (кнопки под каруселью и стрелочки слева и справа в мобильной версии) и происходит анимация перелистывания. (7,5/15)
Дизайн модального окна REGISTER соответствует макету. (13/15) // Высота блока 358px вместо 382px. Нет крестика.
Иконка пользователя меняется на заглавные буквы имени.(1/2) // Меняется не после регистрации, а после log in.
Отображение страницы приходит в состояние после авторизации (этап 4).(1/2) // Меняется не после регистрации, а после log in.
Дизайн модального окна LOG IN соответствует макету.(13/15) // Высота блока 246px вместо 262px. Нет крестика.
Счетчик для Visits отображает, сколько раз пользователь проходил процесс авторизации, включая самый первый - регистрацию. (1/2) // Не засчитывается регистрация.

Невыполненные пункты:

На экране шириной 768px проверяем, чтобы было доступно 4 других скрытых картинки. Для этого меняем разрешение и перезагружаем страницу. Теперь доступных перемещений становится 5.
Неактивными становятся не только выделенные кнопки, но и стрелочки на границах карусели. 
❗Панель навигации "слайдера" сделана по технологии "sticky" для разрешений с одним рядом книг (768px и меньше), т.е. опускается вниз вместе со скроллом страницы, прилипая к верхней части экрана, в рамках блока Favorites.
На разрешении 768px, при открытом бургер-меню, оно закрывается и открывается меню авторизации. 
То же верно и в обратную сторону, кнопка бургер-меню должна быть доступна при открытом меню авторизации.
Модальное окно REGISTER.
При нажатии на крестик в углу окна, или на затемнённую область вне этого окна, оно закрывается. //Нет крестика.
В данном случае, ограничения по полям - все поля должны быть не пустыми. 
Пароль должен быть не короче 8 символов.
Блок Digital Library Cards. Если введённые имя и номер карты совпадают с данными пользователя, то отображается панель с информацией, вместо кнопки Check the card на 10 секунд.
Там же после отображения информации, кнопка возвращается в прежнее состояние, а поля в форме сбрасываются.
Модальное окно LOGIN
При нажатии на крестик в углу окна, или на затемнённую область вне этого окна, оно закрывается. 
Пароль должен быть не короче 8 символов.
Меню профиля при нажатии на иконку с инициалами пользователя
На разрешении 768px, при открытом бургер-меню, оно закрывается и открывается меню авторизации.
То же верно и в обратную сторону, кнопка бургер-меню должна быть доступна при открытом меню авторизации. 
Модальное окно BUY A LIBRARY CARD
Модальное окно нужно сделать шириной 640px. Будет это обрезка по 5px по бокам, или просто уменьшение длины с сохранением сетки - значения не имеет, хотя при правильной сеточной структуре, сделать это будет намного проще. 
Блок Favorites
При нажатии на любую кнопку Buy, после покупки абонемента, меняет вид кнопки на неактивную Own, добавляя единицу к счетчику книг в профиле. 
Кроме того после нажатия обновляется не только счетчик, но и название книги должно отобразится в разделе Rented Books. Название формируется по принципу <название книги>, <автор книги>. В случае если название книги слишком длинное или список стал слишком большой список книг в блоке Rented Books становится скроллируемым (по необходимости горизонтально/ вертикально или оба скролла сразу) Тайтл Rented Books скроллироваться не должен
Модальное окно MY PROFILE
Счетчик для Books отображает, сколько у пользователя книг находятся в состоянии Own. Значение варьируется 0-16.
7. A cross-check score of your Score 
121 / 200

**Comment by helenakrasnova** [comment]
1. Ишью должно быть названо по шаблону: Cross-Check 'название таска' - 'Ваше имя на Github'
2. Баллы не могут быть дробными числами - исправить

**Comment by isolomadin** [comment]
> * Ишью должно быть названо по шаблону: Cross-Check 'название таска' - 'Ваше имя на Github'
> * Баллы не могут быть дробными числами - исправить

Исправил

**Comment by KristiBo** [comment]
Ваша оценка - 141 баллов 

Отзыв по пунктам ТЗ:
**Не выполненные/не засчитанные пункты:**
1) На экране шириной 768px проверяем, чтобы было доступно 4 других скрытых картинки. Для этого меняем разрешение и перезагружаем страницу. Теперь доступных перемещений становится 5. 
Отзыв: Карусель не перестраивается, остается 5 кнопок и 2 картинки. Одна из кнопок и одна картинка обрезаются.
2) Неактивными становятся не только выделенные кнопки, но и стрелочки на границах карусели. 
Отзыв: Стрелочки не появились, одна из кнопок обрезается.
3) ❗Панель навигации "слайдера" сделана по технологии "sticky" для разрешений с одним рядом книг (768px и меньше), т.е. опускается вниз вместе со скроллом страницы, прилипая к верхней части экрана, в рамках блока Favorites.  
Отзыв: sticky нет
4) На разрешении 768px, при открытом бургер-меню, оно закрывается и открывается меню авторизации. 
Отзыв: Открытое бургер-меню перекрывает иконку юзера, поэтому данный пункт проверить невозможно.
5) В данном случае, ограничения по полям - все поля должны быть не пустыми. 
Отзыв: Проходит регистрация с пустыми полями.
6) Пароль должен быть не короче 8 символов.  
Отзыв: Нет ограничения на минимальную длину пароля.
7) В поле E-mail должна быть валидация типа email.  
Отзыв: Валидация отсутствует.
8) Иконка пользователя меняется на заглавные буквы имени. 
9) Отображение страницы приходит в состояние после авторизации (этап 4). 
Отзыв: После окончания регистрации страница не меняется.
10) Блок Digital Library Cards. Если введённые имя и номер карты совпадают с данными пользователя, то отображается панель с информацией, вместо кнопки Check the card на 10 секунд.  
Отзыв: Поле ввода номера карты принимает только числа, поэтому невозможно ввести в него сгенерированный Card Number с буквой.
11) Там же после отображения информации, кнопка возвращается в прежнее состояние, а поля в форме сбрасываются. 
Отзыв: Невозможно проверить пункт.
12) Для авторизации все поля должны быть не пустыми. 
Отзыв: Т.к. допускается регистрация пользователя с пустыми полями, то и авторизация проходит. Кроме того, не работает авторизация по readers card. И нельзя авторизоваться с одной буквой в пароле, хотя регистрация проходит и данные сохраняются в ls.
13) Пароль должен быть не короче 8 символов. 
Отзыв: Т.к. при регистрации нет минимального количества символов, то и авторизация проходит.
14) На разрешении 768px при открытом бургер-меню, оно закрывается и открывается меню авторизации. 
Отзыв: Открытое бургер-меню перекрывает иконку юзера, поэтому данный пункт проверить невозможно.
15) Счетчик для Books отображает, сколько у пользователя книг находятся в состоянии Own. Значение варьируется 0-16.
16) При нажатии на любую кнопку Buy, после покупки абонемента, меняет вид кнопки на неактивную Own, добавляя единицу к счетчику книг в профиле. 
17) Кроме того после нажатия обновляется не только счетчик, но и название книги должно отобразится в разделе Rented Books. Название формируется по принципу <название книги>, <автор книги>. В случае если название книги слишком длинное или список стал слишком большой список книг в блоке Rented Books становится скроллируемым (по необходимости горизонтально/ вертикально или оба скролла сразу) Тайтл Rented Books скроллироваться не должен 
18) ❗Модальное окно нужно сделать шириной 640px. Будет это обрезка по 5px по бокам, или просто уменьшение длины с сохранением сетки - значения не имеет, хотя при правильной сеточной структуре, сделать это будет намного проще. 

**Частично выполненные пункты:**
1) Карусель реагирует на нажатие кнопок (кнопки под каруселью и стрелочки слева и справа в мобильной версии) и происходит анимация перелистывания. 
Отзыв: Карусель работает только на десктопной версии (1440px). Минус половина (7.5) баллов за пункт.
2) Анимация может быть прервана следующим нажатием на кнопку выбора поры года, но при этом анимация не должна застывать в промежуточном состоянии. Если анимация не была прервана следующим нажатием кнопки, то она должна отрабатывать до конца. 
Отзыв: При быстром переключении кнопок не всегда корректно отрабатывает отображение книг в соответствии с выбранным сезоном. Минус половина (1) баллов за пункт.
3) То же верно и в обратную сторону, кнопка бургер-меню должна быть доступна при открытом меню авторизации.  
Отзыв: Если открыто меню авторизации, то кнопка бургер-меню доступна, но при ее нажатии меню авторизации не закрывается, оно нависает над бургером. Минус половина (1) баллов за пункт.
4) Дизайн модального окна соответствует макету.  
Отзыв: Крестик отсутствует. Высота не соответствует макету. Снимаю 4 балла (по 2 за каждое).
5) При нажатии на крестик в углу окна, или на затемнённую область вне этого окна, оно закрывается. 
Отзыв: Крестик отсутствует, поэтому закрытие окна при нажатии на него проверить невозможно. Минус половина (1) баллов за пункт.
6) Будет сгенерирован девятизначный Card Number случайным образом в формате 16-ричного числа. 
Отзыв: Девятизначный Card Number генерируется, но не в формате 16-ричного числа (должны использоваться цифры от 0 до 9 и латинские буквы от A до F).
7) Дизайн модального окна соответствует макету.  
Отзыв: Крестик отсутствует. Высота не соответствует макету. Снимаю 4 балла (по 2 за каждое).
8) При нажатии на крестик в углу окна, или на затемнённую область вне этого окна, оно закрывается. 
Отзыв: Крестик отсутствует, поэтому закрытие окна при нажатии на него проверить невозможно. Минус половина (1) баллов за пункт.
9) То же верно и в обратную сторону, кнопка бургер-меню должна быть доступна. 
Отзыв: Если открыто меню авторизации, то кнопка бургер-меню доступна, но при ее нажатии меню профиля не закрывается, оно нависает над бургером. Минус половина (1) баллов за пункт.
10) Счетчик для Visits отображает, сколько раз пользователь проходил процесс авторизации, включая самый первый - регистрацию. 
Отзыв: Регистрация не засчитывается. Минус половина (1) баллов за пункт.
11) При нажатии на любую кнопку Buy, еще до покупки абонемента, открывается модальное окно BUY A LIBRARY CARD. 
Отзыв: Абонемент купить нельзя, окно будет открываться всегда. Минус половина (1) баллов за пункт.
12) Дизайн модального окна соответствует макету.  
Отзыв: Изначально бордер кнопки черный, а должен быть золотым. Минус 1 балл.
13) Bank card number должен содержать 16 цифр. С пробелами каждые 4 символа или нет - значения не имеет. 
Отзыв: Можно ввести даже одну, больше 16 ввести нельзя. Ошибки не выводятся, абонемент нельзя купить в любом случае, кнопка Buy становится активна хоть при 1 цифре, хоть при 16. Корректность работы поля проверить невозможно. Минус половина (1) баллов за пункт.
14) Expiration code содержит 2 поля с ограничением в 2 цифры. 
Отзыв: Можно ввести даже одну, больше 2 ввести нельзя. Ошибки не выводятся, абонемент нельзя купить в любом случае, кнопка Buy становится активна хоть при 1 цифре, хоть при 2. Корректность работы поля проверить невозможно. Минус половина (1) баллов за пункт.
15) CVC должен содержать 3 цифры. 
Отзыв: Можно ввести даже одну, больше 3 ввести нельзя. Ошибки не выводятся, абонемент нельзя купить в любом случае, кнопка Buy становится активна хоть при 1 цифре, хоть при 3. Корректность работы поля проверить невозможно. Минус половина (1) баллов за пункт.

**Выполненные пункты:**
1) На экране шириной 1440px проверяем, чтобы было доступно 2 других скрытых картинки. При каждом нажатии выезжает следующая, и так до границ справа и слева. 
2) Выделенная кнопка под каруселью (имеется ввиду кнопка соответствующая активному слайду и которая имеет коричневый цвет) - неактивная. 
3) Если анимация карусели не успела завершиться, при этом нажата была следующая кнопка, то картинка не должна зависнуть в промежуточном состоянии. 
4) "Слайдер" реагирует на нажатие кнопок панели навигации и происходит анимация затухания и проявления. 
5) На любой ширине экрана все 4 карточки с книгами одновременно будут плавно затухать, а затем плавно проявляться следующие. 
6) Во время анимаций высота блока Favorites не должна меняться. 
7) В блоке Favorites все кнопки должны иметь имя Buy, а не Own. 
8) Нажатие на иконку пользователя в хедере открывает меню, которое должно оказаться под иконкой таким образом, что правый верхний угол меню находится в той же точке, что и нижний правый угол контейнера с иконкой в хедере. Меню под иконкой. 
9) Нажатие на любую область или элемент вне меню приводят к закрытию меню авторизации. 
10) При нажатии на кнопку Register в открытом меню авторизации появляется модальное окно REGISTER, где есть поля First name, Last name, E-mail и Password. 
11) При нажатии кнопки Sign Up в блоке Digital Library Cards также появляется модальное окно REGISTER. 
Отзыв: Баллы не снимаю, но реализация странная. При нажатии на кнопку Sign Up происходит скролл страницы вверх и там появляется модальное окно. В идеале оно должно появляться в той же части сайта, где мы нажали на кнопку.
12) Окно центрировано, а область вокруг затемнена (насколько затемнена - не имеет значения).  
Отзыв: Необходимо блокировать скролл при открытом модальном окне, иначе оно остается висеть вверху, а мы можем спуститься в другую часть страницы и взаимодействовать с остальными элементами, при этом модальное окно будет висеть открытым все это время, пока мы специально не вернемся и не закроем его кликом по затемненной области.
13) Данные сохраняются в хранилище localStorage, в том числе и пароль, хотя в реальной жизни так делать нельзя. 
14) При нажатии на кнопку Log In появляется модальное окно LOGIN, где есть поля E-mail or readers card и Password. 
15) При нажатии кнопки Log In в блоке Digital Library Cards также появляется модальное окно LOGIN. 
16) Окно центрировано, а область вокруг затемнена (насколько затемнена - не имеет значения). 
Отзыв: Необходимо блокировать скролл при открытом модальном окне, иначе оно остается висеть вверху, а мы можем спуститься в другую часть страницы и взаимодействовать с остальными элементами, при этом модальное окно будет висеть открытым все это время, пока мы специально не вернемся и не закроем его кликом по затемненной области.
17) Если пользователь ещё не вошёл в учётную запись, то при нажатии на любую кнопку Buy открывается модальное окно LOGIN.  
Отзыв: Та же ситуация, что и с нажатием на Sign Up в блоке Digital Library Cards. При нажатии на кнопку Buy происходит скролл страницы вверх и там появляется модальное окно. В идеале оно должно появляться в той же части сайта, где мы нажали на кнопку.
18) При наведении курсором на иконку пользователя должно отображаться полное имя пользователя (атрибут title). 
19) Нажатие на иконку пользователя в хедере открывает меню, которое должно оказаться под иконкой таким образом, что правый верхний угол меню находится в той же точке, что и нижний правый угол контейнера с иконкой в хедере. Меню под иконкой. 
20) Нажатие на любую область или элемент вне меню приводят к закрытию меню профиля. 
21) ❗Вместо надписи Profile отображается девятизначный Card Number. Для Card Number можно использовать меньший шрифт чтобы надпись вметилась в контейнер. 
22) Нажатие на кнопку My Profile открывает модальное окно MY PROFILE. 
23) Нажатие на кнопку Log Out приводит к выходу пользователю из состояния авторизации, возвращаемся к этапу 1.
24) Рядом с Card Number есть кнопка, нажатие на которую копирует код карты клиента в буфер обмена. 
25) Окно центрировано, а область вокруг затемнена (насколько затемнена - не имеет значения). 
26) При нажатии на крестик в углу окна, или на затемненную область вне этого окна, оно закрывается. 
27) При нажатии на крестик в углу окна, или на затемнённую область вне этого окна, оно закрывается.  
28) Для того, чтобы кнопка Buy была активна, все поля должны быть не пустыми. 
29) При наличии авторизации вместо кнопки Check the Card будут отображаться данные пользователя и бейджи, как на дизайне LibraryCard after login in account.
30) Дизайн модального окна MY PROFILE соответствует макету.

**Comment by isolomadin** [comment]
[KristiBo](https://github.com/KristiBo), спасибо большое за проверку!)

**Comment by helenakrasnova** [comment]
@KristiBo спасибо!
Выставлено
