### ISSUE TITLE
Cross-Check 'webdev' - 'zoidbergWoopWoop'

### ISSUE THREAD

**Issue by zoidbergWoopWoop** [rolling-scopes-school/support#92]
Ссылка на деплой проект: https://rolling-scopes-school.github.io/zoidbergwoopwoop-JS2020Q3/webdev
Ссылка на репозиторий: https://github.com/rolling-scopes-school/zoidbergwoopwoop-JS2020Q3

Оценка в ходе самопроверки: 100-6 = 94
(+20) Ссылка на деплой рабочая, страница не пустая
(+80) Все блоки присутствуют
(-3) Блок Implement. Кнопка не интерактивна.
(-3) Блок Our Community. Стрелки не интерактивны.
Ширина страницы адаптивна, думаю в этом причина заниженной оценки.
Балл за cross-check: 77

**Comment by Alexey-Koren** [comment]
Укажите итоговый балл, как указано в шаблоне ишью в документации https://docs.rs.school/#/cross-check-flow

**Comment by bulbasaurustrololo** [comment]
Ссылка на деплой проект: https://rolling-scopes-school.github.io/zoidbergwoopwoop-JS2020Q3/webdev
Ссылка на репозиторий: https://github.com/rolling-scopes-school/zoidbergwoopwoop-JS2020Q3

Оценка в ходе самопроверки: 100-6 = 94
(+20) Ссылка на деплой рабочая, страница не пустая
(+80) Все блоки присутствуют
(-3) Блок Implement. Кнопка не интерактивна.
(-3) Блок Our Community. Стрелки не интерактивны.
Ширина страницы адаптивна, думаю в этом причина заниженной оценки.
Балл за cross-check: 77

**Comment by zoidbergWoopWoop** [comment]
Исправлено.

**Comment by Alexey-Koren** [comment]
Ждите, пока не закончился кросс-чек, апелляции не рассматриваются

**Comment by valerydluski** [comment]
1. Header +10
2. Your Life +7
  Иконки сильно уплыли вниз (-3)
3. Rappresent +10
4. Our Community +5
  Стрелки должны быть интерактивными. (-2)
  Сильное расхождение с макетом (-3)
5. Implement +8
  Кнопка learn more должна быть интерактивной.(-2)
6. Sign Up +10
7. Download +10
8. Footer  +10


Будем считать что ссылка рабочая +20

Итого: 90 баллов
