### ISSUE TITLE
Не засабмитил таск image gallery (Stage0)

### ISSUE THREAD

**Issue by shamrep** [rolling-scopes-school/support#923]
1. A link to your deployed project
    -[link](https://github.com/)](https://rolling-scopes-school.github.io/shamrep-JSFEPRESCHOOL2023Q2/image-gallery-js30/)
2. A link to the project repository on Github.
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/shamrep-JSFEPRESCHOOL2023Q2/tree/image-gallery-js30)
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/js30%23/js30-5.md
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
Извиняюсь, не засабмитил вовремя таск. Если есть возможность прошу проверить.

**Comment by helenakrasnova** [comment]
не является уважительной причиной для апелляцияя
