### ISSUE TITLE
Cross-Check React. Components - golubeva-webmaster.

### ISSUE THREAD

**Issue by golubeva-webmaster** [rolling-scopes-school/support#928]
1. [A link to deployed project](https://sparkling-semifreddo-b6d38b.netlify.app/)
2. [A link to the project repository on Github](https://github.com/golubeva-webmaster/react-st)
3. [A link to the task](https://github.com/rolling-scopes-school/tasks/tree/master/react/modules/module01)
4. [A Link to the checklist for evaluating the task](https://github.com/rolling-scopes-school/tasks/tree/master/react/modules/module02#cross-check-score-can-be-less-if-some-parts-of-the-functionality-dont-work)
5. 
- Eslint is set up, when lint command is run it doesn't produce any errors (if there are warnings score might be less) - 15 points
- Prettier is set up, format:fix command fixes issues - 15 points
- Husky is set up, linting is run on pre-commit - 10 points
- Page is split into 2 sections, top one has Search input and "Search" button, main section displays the list of results from the selected api when page is opened for the first time (loader should be shown while app makes a call to the api) - 20 points
- When user types something to the Search input and clicks "Search" button, a loader is displayed and the list is changed according to the response results for a provided search term - 15 points
- The search term typed into the Search input is saved in the local storage when user clicks on "Search" button (check it by closing the tab and open the app in the new one - the initial call should contain previously entered search term) - 15 points
- -Application is wrapped with ErrorBoundary, which logs error to a console and shows a fallback UI. There should be a button to throw an error - 10 points

6. A final score after self-assessment: Score: 90/100

7. A cross-check score of your Score: 0

**Reason for filing an appeal: I mixed up the deadline date. This is entirely my fault. And I hope that there will be an activist who can check my work. My mentor checked the work. All his comments were taken into account and corrected in the next branch of the project. Thank you.**

**Comment by lyutails** [comment]
- [x] Eslint is set up **15**
- [x] Prettier is set up **15**
- [x] Husky is set up **10**
- [x] Page has two sections: header and bottom one **20**
- [x]  Search works + Loader is spinning when data is not fetched yet **15**
- [x]  Search word is saved to local storage and stays on place after page reload **15**
- [ ] App is not wrapped into error boundary and there is no button for it **0** 

**Final score: 90**

@valerydluski take a look at please
