### ISSUE TITLE
Cross-Check 'React. Components' - 'DzmitrySm'

### ISSUE THREAD

**Issue by DzmitrySm** [rolling-scopes-school/support#929]
1. -
2.https://github.com/DzmitrySm/RS_Stage3_React_Q4
3. https://github.com/rolling-scopes-school/tasks/tree/master/react/modules/module01
4. -
5.
![points first task react](https://github.com/rolling-scopes-school/support/assets/89567746/68d2d968-be72-4847-a2bf-75bf74a4b09b)
6. 90 not installed husky
7. 68

**Comment by helenakrasnova** [comment]
Please edit information according to requirements.
Repository has to be public.
