### ISSUE TITLE
Cross-Check 'webdev' - 'AleksandroSN'

### ISSUE THREAD

**Issue by AleksandroSN** [rolling-scopes-school/support#93]
Ссылка на деплой проект: https://rolling-scopes-school.github.io/aleksandrosn-JS2020Q3/webdev/
Ссылка на репозиторий: https://github.com/rolling-scopes-school/aleksandrosn-JS2020Q3

Оценка в ходе самопроверки: 100
Балл за cross-check : 87 / 100

Комментарий проверяющей chernataly2020 
------------------------------------------------
+20 - страница открывается по указанной ссылке

Блоки нарушает размеры по ширине или высоте больше, чем на 5px:

1. Header (-3) (блок сдвинут влево)

2. Your Life (-3) (блок сдвинут влево)

3.  Rappresent (-3) (блок сдвинут влево)

4. Implement (-3) (блок с заголовком и кнопкой сдвинут вниз)

5. Sign Up (-3) (блок сдвинут вниз, кнопка с галочкой находится под текстовым полем)

6. Download (-3) (сдвинут вниз и влево)

7. Footer  (-3) (сдвинут вниз и влево)

Header +10:

- функциональность:+

Блок Your Life +10:

- функциональность:

(-2) Требование "Кнопки (иконки) соц. сетей должны быть интерактивными." не выполнено.

Блок Rappresent +10

- функциональность +

Блок Our Community +10

- функциональность:

(-2) Требование "Стрелки должны быть интерактивными." не выполнено

Блок Implement +10:

- функциональность +

Блок Sign Up +10

- функциональность: +

Блок Download +10

- фунциональность: 

(-1) Требование "apple store, play store и их иконки должны быть интерактивными." выполнено частично - иконки не интерактивны, интерактивность наложена на всю область кнопки

Footer +10

функциональность: +

Итого – 74 балла.
--------------------------------------------
Проверяющей была занижена оценка , так как проверяющий не верно использовала плагин PixelPerfect.
При мониторе 1280 и картинке 1600 , не был смещен центр , в счет чего мой макет на ее мониторе съехал.
Также я использовал при верстке относительные величины и отключил горизонтальный скролл (overflow-x: hidden).

Также не согласен с аргументацией проверяющей, что все мои кнопки не интерактивны.
По ТЗ указано , что для интерактивности используем :hover эффекты (cursor: pointer, text-decoration и т.д.).
Для проверяющей это не является интерактивностью, а анимации являются.
Переписка с проверяющей имеется в Discord.

**Comment by Alexey-Koren** [comment]
Нашёл ваш балл в скоре. У вас 90 баллов.
Ваша апелляция не подходит под правила, прочитайте пункт 4.
В разделе про апелляции https://docs.rs.school/#/cross-check-flow

Закрываю
