### ISSUE TITLE
Cross-Check 'AWS_3_serverless_api' 'pavel-sobchneko'

### ISSUE THREAD

**Issue by pavel-sobchenko** [rolling-scopes-school/support#930]
Hi! This is a not usual appeal. This is about the platform break right before the deadline. As a result I couldn't submit my final PR. I have an improvement that it is true:)

1. A link to the project repository on Github.
    - https://github.com/pavel-sobchenko/aws-shop-backend/pull/1
2. A link to the task
    - https://github.com/rolling-scopes-school/aws/blob/main/aws-developer/03_serverless_api/task.md
3. A screenshot of cross-checking marks
<img width="1748" alt="Screenshot 2023-11-20 at 00 57 57" src="https://github.com/rolling-scopes-school/support/assets/37002874/2c67c63f-a44e-44e3-9a4a-4a78eb2119f3">

**Comment by ThorsAngerVaNeT** [comment]
The task was implemented using wrong technology, so the score is 0 and appellation is not needed to be checked.
