### ISSUE TITLE
Cross-Check 'CV(HTML+CSS+Markdown).md Latest'-Farrukhjondev S_Farrukhjon

### ISSUE THREAD

**Issue by Farrukhjondev** [rolling-scopes-school/support#932]
1. A link to your deployed project
    - https://farrukhjondev.github.io/rsschool-cv/ 
2. A link to the project repository on Github.
    - https://github.com/Farrukhjondev/rsschool-cv/tree/gh-pages
3. A link to the task
    - https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(HTML+CSS+Markdown).md
4. A Link to the checklist for evaluating the task (if it exists)
    - https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/CV(markdown)/CV(cross-check).md

5. A screenshot of cross-checking marks
  1) <img width="1408" alt="Screenshot 2023-12-01 at 19 12 47" src="https://github.com/rolling-scopes-school/support/assets/93606012/69677c93-1cb2-4744-b381-a77d5f0eea4c">

  2) <img width="1399" alt="Screenshot 2023-12-01 at 19 14 54" src="https://github.com/rolling-scopes-school/support/assets/93606012/58f89cba-9687-42a1-b1ff-25b5148c1599">

  3) <img width="1416" alt="Screenshot 2023-12-01 at 19 15 04" src="https://github.com/rolling-scopes-school/support/assets/93606012/e5409996-6b98-4889-8abb-bd280685d4f5">

6. A final score after self-assessment, with comments
   For both reviewer situations, I would be glad to have 118 marks, as in reality, I missed the <header> tag which might be worth deducting 2-3 marks from the full mark.

7. A cross-check score of your Score 
   For both reviewer situation they put 110 mark

**Comment by helenakrasnova** [comment]
The difference between your expected score and cross-check score less than 10%
Appeal does not meet the requirements

**Comment by Farrukhjondev** [comment]
To be honest, requirement for appeal helps for participants to cheat the system and put a 10% lower mark even the task was successfully completed for total mark to outstand among other participants.You created such stupid requirement that ignores the Truth and unfair towards participants. It is your fault.Sent from my iPhoneOn 4 Dec 2023, at 17:28, helenakrasnova ***@***.***> wrote:﻿
The difference between your expected score and cross-check score less than 10%
Appeal does not meet the requirements

**Comment by helenakrasnova** [comment]
@Farrukhjondev 
From RSSchool rules:
The toxic behavour includes:
- unreasonable repetitive critic of the school, its program, mentors and students and supporting this critic
- rude language outside of random channel

_In case of repetitive unreasonable  critic of the school, you'll be dismissed from Rolling Scopes School._
**It's the first warning**
