### ISSUE TITLE
Coffee House. Week-2 - igoradjo

### ISSUE THREAD

**Issue by igoradjo** [rolling-scopes-school/support#934]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/igoradjo-JSFE2023Q4/coffee/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/igoradjo-JSFE2023Q4/tree/coffee-house/coffee)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/coffee-house/coffee-house-week2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/coffee-house/coffee-house-week2.md#crosscheck-criteria)
5. A screenshot of cross-checking marks

![Снимок экрана (1202)](https://github.com/rolling-scopes-school/support/assets/64511808/d7611642-bf37-4e38-a967-3ff8961da092)
![Снимок экрана (1203)](https://github.com/rolling-scopes-school/support/assets/64511808/41779bc8-eec1-4a73-90d9-3059b2abf438)
![Снимок экрана (1204)](https://github.com/rolling-scopes-school/support/assets/64511808/9e654ab4-8ec2-4adc-8f54-0162869a520d)

6. A final score after self-assessment, with comments

60/90

Не согласен с оценками двух проверяющих. Спросил у первого проверяющего чтобы тот расписал подробнее, что неправильно, на что получил ответ "Извиняюсь я этот проект вообще не разбирал, не могу ничего сказать увы. Самому стыдно.". Не знаю, как это расценивать. А второй проверяющий согласился проверить, но он оценил так, что если header по пикселям не подходит, то и все остальные блоки не подходят. Дальше я начал аргументировать, что надо каждый блок отдельно проверять, на что проверяющий отвечал, что так никогда не делалось. а в конце написал "у меня есть и другие дела. какой-то рандомный человек с потока отозвался предоставить свое мнение на твою работу. Проверять еще за ним это уже сверх моих полномочий и желания".

7. A cross-check score of your Score 

35/90

**Comment by helenakrasnova** [comment]
Есть коммиты после дедлайна

**Comment by igoradjo** [comment]
Последний коммит 5 декабр за 10 минут до дедлайна.

**Comment by igoradjo** [comment]
> Есть коммиты после дедлайна

Последний коммит 5 декабр за 10 минут до дедлайна.

**Comment by helenakrasnova** [comment]
да, прошу прощения, съехала таймзона

оформите ишью по требованиям:
название согласно шаблону, A final score after self-assessment, with comments - самопроверка
