### ISSUE TITLE
Coffee House. Week-2 - igoradjo

### ISSUE THREAD

**Issue by igoradjo** [rolling-scopes-school/support#935]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/igoradjo-JSFE2023Q4/coffee/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/igoradjo-JSFE2023Q4/tree/coffee-house/coffee)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/coffee-house/coffee-house-week2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/coffee-house/coffee-house-week2.md#crosscheck-criteria)
5. A screenshot of cross-checking marks

![Снимок экрана (1202)](https://github.com/rolling-scopes-school/support/assets/64511808/cc7854fb-796d-4b10-8b85-3edfd17a10db)
![Снимок экрана (1203)](https://github.com/rolling-scopes-school/support/assets/64511808/79ce7fe6-e609-4ecf-a6e5-cbdacd19d943)
![Снимок экрана (1204)](https://github.com/rolling-scopes-school/support/assets/64511808/1c2888d9-b552-4482-81ea-5c522fe143ac)

6. A final score after self-assessment, with comments

70/90

Не согласен с оценками двух проверяющих. Спросил у первого проверяющего чтобы тот расписал подробнее, что неправильно, на что получил ответ "Извиняюсь я этот проект вообще не разбирал, не могу ничего сказать увы. Самому стыдно.". Не знаю, как это расценивать. А второй проверяющий согласился проверить, но он оценил так, что если header по пикселям не подходит, то и все остальные блоки не подходят. Дальше я начал аргументировать, что надо каждый блок отдельно проверять, на что проверяющий отвечал, что так никогда не делалось. а в конце написал "у меня есть и другие дела. какой-то рандомный человек с потока отозвался предоставить свое мнение на твою работу. Проверять еще за ним это уже сверх моих полномочий и желания".

`header` block on each page 2/2
`Enjoy` block on `home` page 2/2
`Favourites Coffee` block on `home` page 2/2
`About` block on `home` page 2/2
`Mobile App` block on `home` page 2/2
`Menu` block on `menu` page 2/2
`footer` block on each page 2/2
`header` block on each page 2/2
`Enjoy` block on `home` page 2/2
`Favourites Coffee` block on `home` page 2/2
`About` block on `home` page 2/2
`Mobile App` block on `home` page 1/2
`Menu` block on `menu` page 2/2
`footer` block on each page 2/2
`header` block on each page 1/2
`Enjoy` block on `home` page 1/2
`Favourites Coffee` block on `home` page 2/2
`About` block on `home` page 2/2
`Mobile App` block on `home` page 2/2
`Menu` block on `menu` page 0/2
`footer` block on each page 1/2
`home` page: no horizontal scroll bar between 1440px and 768px widths 5/5
`home` page: no horizontal scroll bar between 768px and 380px widths 5/5
`menu` page: no horizontal scroll bar between 1440px and 768px widths
Points for criteria: 5/5
`menu` page: no horizontal scroll bar between 768px and 380px widths
Points for criteria: 5/5
On `home` page 4/4
On `menu` page 0/4
At screen widths of 768px and below, the menu and navigation buttons in the header are concealed on both pages, and a burger menu icon is displayed (Note: Activation of the burger menu icon is not evaluated at this stage.) 4/4
Hover effects are active on desktop devices (as per the `Desktop` device type in DevTools) and are disabled for mobile devices (as per the `Mobile` device type in DevTools) on both pages 0/4
The layout for both pages is validated and error-free according to the W3C Validator (https://validator.w3.org/) 6/12

7. A cross-check score of your Score 

35/90

**Comment by helenakrasnova** [comment]
Называем ишью его по шаблону: Cross-Check 'название таска' - 'Ваше имя на Github'.
