### ISSUE TITLE
Cross-Check 'Coffee House. Week-2' - 'igoradjo'

### ISSUE THREAD

**Issue by igoradjo** [rolling-scopes-school/support#936]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/igoradjo-JSFE2023Q4/coffee/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/igoradjo-JSFE2023Q4/tree/coffee-house/coffee)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/coffee-house/coffee-house-week2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/coffee-house/coffee-house-week2.md#crosscheck-criteria)
5. A screenshot of cross-checking marks

![Снимок экрана (1202)](https://github.com/rolling-scopes-school/support/assets/64511808/97a9a4d4-99c9-4528-af7f-2b7c5406f1e9)
![Снимок экрана (1203)](https://github.com/rolling-scopes-school/support/assets/64511808/c5af3b8b-16ec-482c-af9b-956ea108c1d1)
![Снимок экрана (1204)](https://github.com/rolling-scopes-school/support/assets/64511808/3a7a9892-7682-49c0-ac15-50fd2ac94981)

6. A final score after self-assessment, with comments

70/90

Не согласен с оценками двух проверяющих. Спросил у первого проверяющего чтобы тот расписал подробнее, что неправильно, на что получил ответ "Извиняюсь я этот проект вообще не разбирал, не могу ничего сказать увы. Самому стыдно.". Не знаю, как это расценивать. А второй проверяющий согласился проверить, но он оценил так, что если header по пикселям не подходит, то и все остальные блоки не подходят. Дальше я начал аргументировать, что надо каждый блок отдельно проверять, на что проверяющий отвечал, что так никогда не делалось. а в конце написал "у меня есть и другие дела. какой-то рандомный человек с потока отозвался предоставить свое мнение на твою работу. Проверять еще за ним это уже сверх моих полномочий и желания".

header block on each page 2/2
Enjoy block on home page 2/2
Favourites Coffee block on home page 2/2
About block on home page 2/2
Mobile App block on home page 2/2
Menu block on menu page 2/2
footer block on each page 2/2
header block on each page 2/2
Enjoy block on home page 2/2
Favourites Coffee block on home page 2/2
About block on home page 2/2
Mobile App block on home page 1/2
Menu block on menu page 2/2
footer block on each page 2/2
header block on each page 1/2
Enjoy block on home page 1/2
Favourites Coffee block on home page 2/2
About block on home page 2/2
Mobile App block on home page 2/2
Menu block on menu page 0/2
footer block on each page 1/2
home page: no horizontal scroll bar between 1440px and 768px widths 5/5
home page: no horizontal scroll bar between 768px and 380px widths 5/5
menu page: no horizontal scroll bar between 1440px and 768px widths
Points for criteria: 5/5
menu page: no horizontal scroll bar between 768px and 380px widths
Points for criteria: 5/5
On home page 4/4
On menu page 0/4
At screen widths of 768px and below, the menu and navigation buttons in the header are concealed on both pages, and a burger menu icon is displayed (Note: Activation of the burger menu icon is not evaluated at this stage.) 4/4
Hover effects are active on desktop devices (as per the Desktop device type in DevTools) and are disabled for mobile devices (as per the Mobile device type in DevTools) on both pages 0/4
The layout for both pages is validated and error-free according to the W3C Validator (https://validator.w3.org/) 6/12

7. A cross-check score of your Score 

35/90

**Comment by helenakrasnova** [comment]
не нужно каждый раз создавать новое ишью, текущее можно редактировать
название ишью должно быть Cross-Check 'Coffee House. Week-2' - 'igoradjo'

**Comment by KristiBo** [comment]
1. The layout of the pages aligns the design at a screen width of 1440px: **+13/14**
- [x] `<header>` block on each page: **+2**
- [x] `Enjoy` block on `home` page: **+2**
- [x] `Favourites Coffee` block on `home` page: **+2**
- [x] `About` block on `home` page: **+2**
- [ ] `Mobile App` block on `home` page: **+1/2**
Пункт засчитан частично, т.к. отклонение от макета больше 10px. Размер картинки в блоке не совпадает с макетом.
- [x] `Menu` block on `menu` page: **+2**
- [x] `<footer>` block on each page: **+2**
В целом, все блоки не идеально совпадают с макетом, но отклонение в пределах допустимых 10px, за исключением блока Mobile App. Возможно, ты не обновил свою копию макета после выдачи таска и поэтому так получилось с картинкой.

2. The layout of the pages aligns the design at a screen width of 768px: **+13/14**
- [x] `<header>` block on each page: **+2**
- [x] `Enjoy` block on `home` page: **+2**
- [x] `Favourites Coffee` block on `home` page: **+2**
- [x] `About` block on `home` page: **+2**
- [ ] `Mobile App` block on `home` page: **+1/2**
Пункт засчитан частично, т.к. отклонение от макета больше 10px. Размер картинки в блоке не совпадает с макетом.
- [x] `Menu` block on `menu` page: **+2**
- [x] `<footer>` block on each page: **+2**
Аналогичная ситуация, как и на ширине экрана 1440px.

3. The layout of the pages aligns the design at a screen width of 380px: **+8/14**
- [ ] `<header>` block on each page: **+1/2**
Засчитан только хедер на главной странице, хотя и он значительно отклоняется от макета.
- [ ] `Enjoy` block on `home` page: **+1/2**
Засчитан частично. Высота блока не соответствует макету, расхождение значительно больше допустимых 10px. Пришлось сдвинуть макет на 86px для проверки следующего блока.
- [x] `Favourites Coffee` block on `home` page: **+2**
- [x] `About` block on `home` page: **+2**
- [ ] `Mobile App` block on `home` page: **+1/2**
Засчитан частично. Картинка не совпадает с макетом.
- [ ] `Menu` block on `menu` page: **0/2**
Пункт не выполнен. Карточки должны были встать по одной в ряд, а у тебя их по 2. Элементы занимают 768px.
- [ ] `<footer>` block on each page: **1/2**
Пункт засчитан только для главной страницы. На странице меню элементы занимают 768px.
 
4. There is no horizontal scrollbar at all screen width up to 380px inclusive. All page content remains as per the design: it is not cropped, removed, or shifted to the side: **0/20**
- [ ] `home` page: no horizontal scroll bar between 1440px and 768px widths: **0/5**
- [ ] `home` page: no horizontal scroll bar between 768px and 380px widths: **0/5**
- [ ] `menu` page: no horizontal scroll bar between 1440px and 768px widths: **0/5**
- [ ] `menu` page: no horizontal scroll bar between 768px and 380px widths: **0/5**
Пункт не выполнен полностью. Горизонтальный скролл присутствует на всех промежутках до 380px, на обеих страницах. Например, ставим ширину 500px, смотрим на размер хедера, видим там 768px. И далее по аналогии.

5. During smooth resizing of the browser window from 1440px to 380px, the layout occupies the full width of the window (including specified margins), elements adjust their sizes and positions appropriately without full scaling, no elements overlap, and images maintain their correct aspect ratios: **0/8**
- [ ] On `home` page: **0/4**
- [ ] On `menu` page: **0/4**
Пункт не засчитан. У тебя стоит фиксированная ширина body 1440px, нужно было ставить max-width, это влияет и на скролл в том числе. Происходит масштабирование верстки в промежутках между контрольными точками перестроения. Можешь посмотреть стрим, который проводил автор таска, он там показывал поведение верстки с полным масштабированием.

6. At screen widths of 768px and below, the menu and navigation buttons in the header are concealed on both pages, and a burger menu icon is displayed: **+4/4**

7. Hover effects are active on desktop devices (as per the `Desktop` device type in DevTools) and are disabled for mobile devices (as per the `Mobile` device type in DevTools) on both pages: **0/4**
Пункт не выполнен.

9. The layout for both pages is validated and error-free according to the W3C Validator (https://validator.w3.org/): **+6/12**
Пункт засчитан частично, т.к. присутствуют ошибки валидации на главной странице.

Еще заметила, что переход на страницу меню возможен только с десктопной версии, т.к. не работает кнопка в блоке Enjoy. Это не оценивается в текущей части, но является ошибкой.

_**Итоговая оценка 44 балла.**_
_Успехов в дальнейшем обучении!_

**Comment by igoradjo** [comment]
Спасибо за проверку!
