### ISSUE TITLE
Cross-Check Coffee House.Part_2[EN] -  MariamKochadze

### ISSUE THREAD

**Issue by MariamKochadze** [rolling-scopes-school/support#939]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/mariamkochadze-JSFEEN2023Q4/coffee-house/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/mariamkochadze-JSFEEN2023Q4)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/coffee-house/coffee-house-week2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/js-fe-course-en/blob/main/tasks/coffee-house/coffee-house-week2.md#layout-requirements)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/126329090/071cbe44-1b96-4d36-8f29-3afc103fc279)

6. A final score after self-assessment, with comments
1. The layout of the pages matches the design at a screen width of 1440px: +14 
2. The layout of the pages matches the design at a screen width of 768px: +14 
3. The layout of the pages matches the design at a screen width of 380px: +14 
4. There is no horizontal scroll bar at all screen width up to 380px inclusive. All page content remains as per the design: it is not cropped, removed, or shifted to the side: +20 
5. During smooth resizing of the screen from 1440px to 380px, the layout takes up the full width of the window (including the margins specified in the layout), elements change their sizes and positions (but without full scaling), elements do not overlap, and images maintain their correct proportions: +8 
6. At screen widths of 768px and below on both pages, the menu and navigation buttons in the header are hidden, and a burger menu icon appears: +4 
7. Hover effects are enable on desktop devices (Desktop device type in DevTools) and disabled for mobile devices on both pages (Mobile device type in DevTools): +4 
8. The layout of both pages is valid: to check the validity of the layout, use the service https://validator.w3.org/ : +12 
total score: 90.
7. A cross-check score of your Score 
 avarage score - 71

**Comment by helenakrasnova** [comment]
A screenshot of cross-checking marks has to be with all marks and all comments  
A cross-check score of your Score is not 71 - should be fixed

**Comment by MariamKochadze** [comment]
![image](https://github.com/rolling-scopes-school/support/assets/126329090/66b88b86-9793-4971-ada5-eaed8211c0fe)
![image](https://github.com/rolling-scopes-school/support/assets/126329090/f411e452-a87e-4aed-9159-591d22d757ae)
![image](https://github.com/rolling-scopes-school/support/assets/126329090/0e247c90-8a76-4d70-ba7b-c37140f1c44b)
![image](https://github.com/rolling-scopes-school/support/assets/126329090/3cc16d9b-f74a-49c3-866a-8131d2196a21)
![image](https://github.com/rolling-scopes-school/support/assets/126329090/43e6a47e-f815-42e2-82db-787327471f43)

**Comment by helenakrasnova** [comment]
issue is not fixed according to rules
