### ISSUE TITLE
Cross-Check 'webdev' - 'vladstepway'

### ISSUE THREAD

**Issue by vladstepway** [rolling-scopes-school/support#94]
Ссылка на деплой проект: https://vladstepway-webdev.netlify.app/webdev/
Ссылка на репозиторий: https://github.com/rolling-scopes-school/vladstepway-JS2020Q3

Оценка в ходе самопроверки: 100
Балл за cross check: 100/100
(+20) Ссылка на деплой рабочая, страница не пустая
(+80) Все блоки присутствуют
Вёрстка не адаптивная, на мониторах с шириной менее 1600px содержимое едет. Работа не идеальная, но отклонения в пределах нормы. Два проверяющих поставили 100 баллов, а третий поставил 76, объяснив это так
![image](https://user-images.githubusercontent.com/36796951/94341165-03e8d780-0010-11eb-9624-58d8c6fd0b7a.png)
Найти проверяющего по нику в discord не получилось.

**Comment by Alexey-Koren** [comment]
Нашёл ваш балл в скоре. У вас 92 балла.
Ваша апелляция не подходит под правила, прочитайте пункт 4.
В разделе про апелляции https://docs.rs.school/#/cross-check-flow

Закрываю
