### ISSUE TITLE
Cross-Check Clean-code-s1e1 - VasilyeuUV

### ISSUE THREAD

**Issue by VasilyeuUV** [rolling-scopes-school/support#940]
1. A link to your deployed project
    - [deploy](https://vasilyeuuv.github.io/clean-code-s1e1/)
2. A link to the project repository on Github.
    - [github](https://github.com/VasilyeuUV/clean-code-s1e1)
3. A link to the task
    - [task](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - none
5. A screenshot of cross-checking marks
<img width="897" alt="image" src="https://github.com/rolling-scopes-school/support/assets/40467596/d6a1084a-2dfe-4484-8d92-fd6e7d39aba3">

6. A final score after self-assessment, with comments:  45.
<img width="467" alt="image" src="https://github.com/rolling-scopes-school/support/assets/40467596/5109a22d-b2bb-4cdc-a976-d0b374df3bfe">
<img width="451" alt="image" src="https://github.com/rolling-scopes-school/support/assets/40467596/4e3d0855-b932-429d-9f6f-d9563a2ee2bd">
<img width="468" alt="image" src="https://github.com/rolling-scopes-school/support/assets/40467596/79c898ae-81af-4721-8753-2e3e7aa41775">
<img width="471" alt="image" src="https://github.com/rolling-scopes-school/support/assets/40467596/70342105-a634-44c6-a02c-62b6464a66cb">
<img width="871" alt="image" src="https://github.com/rolling-scopes-school/support/assets/40467596/968c3e17-c3ca-46b9-9c93-b041203cd649">

7. A cross-check score of your Score: 42

**Comment by helenakrasnova** [comment]
почему создано 2 ишью?
A cross-check score of your Score: указана неверно, 
![image](https://github.com/rolling-scopes-school/support/assets/44213581/08d05943-a760-4935-b48d-260df779a101)

**Comment by VasilyeuUV** [comment]
1. Два ишью создано на две проверки: одно с оценкой 31 балл, второе с оценкой 38 баллов.
2. Со Score не разобрался (в первый раз оформляю аппеляцию). Исправил.
