### ISSUE TITLE
Cross-Check 'clean-code-s1e1' - 'ellenlis'.

### ISSUE THREAD

**Issue by EllenLis** [rolling-scopes-school/support#942]
1. A link to your deployed project
    - [link deploy](https://ellenlis.github.io/clean-code-s1e1/)
    - [link PR](https://github.com/EllenLis/clean-code-s1e1/pull/2)
2. A link to the project repository on Github.
    - [link](https://github.com/EllenLis/clean-code-s1e1/tree/clean-code-s1e1)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md)
4. A Link to the checklist for evaluating the task (if it exists) 
    - [link](https://rolling-scopes-school.github.io/checklist/) CLEAN CODE S1E1
5. A screenshot of cross-checking marks
<img width="390" alt="Снимок экрана 2024-01-15 в 20 43 40" src="https://github.com/rolling-scopes-school/support/assets/108792923/65025368-2041-4424-824e-1f822f1374fa">
<img width="295" alt="Снимок экрана 2024-01-15 в 20 44 35" src="https://github.com/rolling-scopes-school/support/assets/108792923/c5d0ccf9-f874-47c9-8401-be73eae935db">
<img width="328" alt="Снимок экрана 2024-01-15 в 20 44 55" src="https://github.com/rolling-scopes-school/support/assets/108792923/51c443cf-f204-4488-836f-313ee46f4437">

6. A final score after self-assessment, with comments
Не согласна с 0 баллов из-за ссылки на деплой (так как эта ссылка также нужна для проверки и через нее достаточно информации для просмотра PR), и остальные двое проверяющих работу проверили.
40/45 - так как не учла заголовки, сначала должен идти h1, у меня h3 (не исправлено). Это пункт: Extended rule 1.1. HTML. Semantics (за него выдается 5 баллов)
7. A cross-check score of your Score 
В PR указала 45/45

**Comment by helenakrasnova** [comment]
![image](https://github.com/rolling-scopes-school/support/assets/44213581/3e177e3c-83a2-488d-b87f-2babc1e4e4d1)
![image](https://github.com/rolling-scopes-school/support/assets/44213581/dad03692-143f-465d-990d-9414bc3c0d3d)
Я правильно понимаю, что была засабмичена ссылка на деплой (не на репозиторий)?

**Comment by EllenLis** [comment]
Да, все правильно

**Comment by helenakrasnova** [comment]
В таком случае проверяющие имели право поставить 0, это прописано в требованиях к заданию
