### ISSUE TITLE
Cross-Check 'Hangman' - 'grimpatron'

### ISSUE THREAD

**Issue by grimpatron** [rolling-scopes-school/support#943]
1. A link to your deployed project
    - [deploy](https://rolling-scopes-school.github.io/grimpatron-JSFE2023Q4/hangman/)
2. A link to the project repository on Github.
    - [repository](https://github.com/rolling-scopes-school/grimpatron-JSFE2023Q4/tree/hangman)
3. A link to the task
    - [task](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/tasks/hangman)
4. A Link to the checklist for evaluating the task (if it exists)
    - [crosscheck-criteria](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/tasks/hangman#crosscheck-criteria-150-points)
5. A screenshot of cross-checking marks
![Screenshot 2024-01-19 at 10-53-10 App _ The Rolling Scopes School](https://github.com/rolling-scopes-school/support/assets/43726927/0cd027cc-e6c4-4013-8a75-bb4fcdeb082f)

6. A final score after self-assessment, with comments => (150/150)
> Всё выполнено. Двое проверяющих написали что не открывается ссылка. Хотя у двух других она открылась и они проверили. Я пытался связаться с проверяющими, но безрезультатно.

8. A cross-check score of your Score => (100/150)

**Comment by helenakrasnova** [comment]
Вы засабмитали ссылку на пулл реквест, не на деплой, поэтому ваша работа не открывалась у других студентов

**Comment by grimpatron** [comment]
Я могу рассчитвать на изменение оценки? Что мне нужно сделать?

**Comment by helenakrasnova** [comment]
причина не является уважительной для пересмотра оценки - вы неправильно засабмитили ссылку
