### ISSUE TITLE
Cross-Check 'HTML-Builder' - 'vladdlevshuk'

### ISSUE THREAD

**Issue by vladdlevshuk** [rolling-scopes-school/support#944]
1. A link to your deployed project
    - отсутствует
2. A link to the project repository on Github.
    - [link](https://github.com/vladdlevshuk/HTML-builder)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/HTML-builder)
4. A Link to the checklist for evaluating the task (if it exists)
    - отсутствует
5. A screenshot of cross-checking marks
![Screenshot_2](https://github.com/rolling-scopes-school/support/assets/138326244/e20848fa-cf1c-4d4b-bf4c-035cc1547c51)

6. A final score after self-assessment, with comments
отсутствует
7. A cross-check score of your Score 
отсутствует

Меня по ошибке исключили из курса. После восстановления я не получил работы для перекрёстной проверки. Задание было засабмичено вовремя.
![Screenshot_3](https://github.com/rolling-scopes-school/support/assets/138326244/20d54133-119a-4af5-a892-59bd6d913254)
![Screenshot_4](https://github.com/rolling-scopes-school/support/assets/138326244/c192bf6b-ec76-4d44-84eb-658f93a1ab89)

**Comment by helenakrasnova** [comment]
переименуйте ишью по шаблону как здесь 
![image](https://github.com/rolling-scopes-school/support/assets/44213581/abe5c66e-a372-44f4-8438-3e95c749d843)

**Comment by lyutails** [comment]
hey there o/

1. 01-read-file:
- [x] no sync methods are used
- [x] ReadStream is used
- [x] correct output in console
![image](https://github.com/rolling-scopes-school/support/assets/101958335/3aab666e-18ee-4790-b258-bb7f3a5f08ec)
- [x] changed file's content shows corresponding resutl
![image](https://github.com/rolling-scopes-school/support/assets/101958335/0eb87ab3-ad7b-4a1c-9747-1c5ad68f2ff2)
**20 points**

2. 02-write-file:
- [x] no sync methods are used
- [x] text file has been created
- [x] after entering the text the input is correctly recorded in the created text file
- [x]  on ctrl + c key combination a farewell phrase displayed in the console with subsequent process termination
![image](https://github.com/rolling-scopes-school/support/assets/101958335/d83e0972-00c0-490b-803a-1fc019bda312)
![image](https://github.com/rolling-scopes-school/support/assets/101958335/a1c81057-e4e5-44d4-89a9-0aa71af6c6eb)
**20 points**

3. 03-files-in-folder:
- [x] no sync methods are used
- [x] information about files inside the secret-folder displayed in the console
![image](https://github.com/rolling-scopes-school/support/assets/101958335/9d59adfe-4bc3-4e19-87e1-81323eea8db7)
- [x] the information about added files is correct and the data about directories is not displayed
![image](https://github.com/rolling-scopes-school/support/assets/101958335/02b197f3-d265-435a-92a5-adf902ca333f)
![image](https://github.com/rolling-scopes-school/support/assets/101958335/526f047a-aa0e-4346-bdde-9a0f416cef9e)
**20 points**

4. 04-copy-directory:
- [x] no sync methods are used
- [x] no fsPromises.cp is used
- [x] created files-copy folder with an exact copy of the content of the original files folder
- [x] the content of the files-copy folder is updated and corresponds to the content of the files folder
![image](https://github.com/rolling-scopes-school/support/assets/101958335/aa79a16d-3d98-49ae-9b49-f8ceac10c37a)
![image](https://github.com/rolling-scopes-school/support/assets/101958335/db934db1-8b64-41cf-8af6-b0e8f10a3d50)
![image](https://github.com/rolling-scopes-school/support/assets/101958335/25b23e52-4885-414f-a8ce-927aeadc5895)
**20 points**

5. 05-merge-styles:
- [x] no sync methods are used
- [x] bundle is successfully created
![appeal_builder_05](https://github.com/rolling-scopes-school/support/assets/101958335/4a23c0e0-90cc-4114-9f53-05fea33e6004)
- [x] the bundle.css file is overwritten and contains up-to-date and correct styles
![image](https://github.com/rolling-scopes-school/support/assets/101958335/983a9ce4-2793-4ec3-876a-e36162ce811d)
- [x] the ext-test-string is not present in the file
![image](https://github.com/rolling-scopes-school/support/assets/101958335/a062a7e0-ed10-43b8-9dfa-c1472754d4ae)
![image](https://github.com/rolling-scopes-school/support/assets/101958335/97f52f10-4dd4-4568-8ad2-eae3221cb2b5)
**20 points**

6. 06-build-page:
- [x] no sync methods are used
- [x] no experimental function fsPromises.cp is used
- [x] project-dist folder should be created in the 06-build-page directory, containing the index.html and style.css files, as well as the assets folder
![image](https://github.com/rolling-scopes-school/support/assets/101958335/cb6ce83d-21cf-47e2-8f6a-3410cc46f828)
- [x] the index.html file contains markup from the template.html file with the replacement of template tags with the markup of similarly named component files from the components folder. The markup of component files should be strictly in the places corresponding to the template tags. There should be no template tags themselves in the index.html file
![image](https://github.com/rolling-scopes-school/support/assets/101958335/7006a580-9837-465a-aae4-b94b87171a48)
![image](https://github.com/rolling-scopes-school/support/assets/101958335/653e9ab2-5e8f-4684-aa9d-c3afd1d7dd82)
- [x] squirrel and others successfully added in folders as well as new {{about}} block
![image](https://github.com/rolling-scopes-school/support/assets/101958335/b163a7dc-f6aa-4fd9-be94-d08618d6afc7)
![image](https://github.com/rolling-scopes-school/support/assets/101958335/68cbf2e7-357e-42a7-9546-66d7967ed300)
**50 points**


_____________________________________________________

**final result and total points for the task: 150**

@helenakrasnova take a look at please

**Comment by helenakrasnova** [comment]
@lyutails thank you!
