### ISSUE TITLE
Cross-Check HTML-builder djpont

### ISSUE THREAD

**Issue by djpont** [rolling-scopes-school/support#945]
1. A link to your deployed project
    - no
2. A link to the project repository on Github.
    - https://github.com/djpont/HTML-builder
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/tree/master/stage1/tasks/html-builder
4. A Link to the checklist for evaluating the task (if it exists)
    - https://github.com/rolling-scopes-school/HTML-builder/wiki
5. A screenshot of cross-checking marks
<img width="760" alt="image" src="https://github.com/rolling-scopes-school/support/assets/34692754/4ac9cbda-9247-47ee-8422-2a3429843008">
<img width="760" alt="image" src="https://github.com/rolling-scopes-school/support/assets/34692754/d109bcb5-b3ac-4295-89f0-0bc4487f8c23">

7. A final score after self-assessment, with comments
    - 130
9. A cross-check score of your Score
    - 150, 150, 130, 130

Здравствуйте! Выполнил задачу HTML-builder, засабмитил до дедлайна, но из-за болезни не успел провести кросс-чек предоставленных работ, не было возможности, думал уже совсем покину этот мир, 5 дней с температурой 38+, скорую вызывал в последний день, сказали жить буду и кодить ещё смогу. Прошу засчитать оценку в общий зачёт.

**Comment by helenakrasnova** [comment]
@djpont пришлите мне в ДС справку о болезни

**Comment by mrHoft** [comment]
@helenakrasnova
Это мой друг, которого я пригласил на курс. И я же уговорил написать issue, переживая за него.
По ранее выполненным работам видно что он усердно проходил обучение пока не слёг.
Справку предоставит врядли: когда вызываешь скорую, то справки это последнее о чём думаешь. А бегать по поликлиникам, поднимать записи он врядли станет.
Учитывая ранее проявленное усердие в учёбе, прошу не обходиться с ним столь сурово.

**Comment by djpont** [comment]
> @djpont пришлите мне в ДС справку о болезни

Справки нет, скорая была, но они только у себя журнал заполнили, мне ничего не оставили, да я и не просил, я официально не работаю.

**Comment by helenakrasnova** [comment]
@djpont правила одинаковые для все студентов - для апелляции необходим документ подтверждающий болезнь. 
P.S. кросс-чек предыдущего задания вами тоже не был проведен.
В любом случае, продолжайте обучение и у вас все получится! :four_leaf_clover:
