### ISSUE TITLE
Cross-Check Node.js Basics - NikolayBV

### ISSUE THREAD

**Issue by NikolayBV** [rolling-scopes-school/support#946]
1. A link to your deployed project
    - [link](https://github.com/NikolayBV/node-nodejs-basics/tree/feat/nodejs-basics)
2. A link to the project repository on Github.
    - [link](https://github.com/AlreadyBored/node-nodejs-basics)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/nodejs-basics/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
<img width="1500" alt="Снимок экрана 2024-02-05 в 1 40 25 PM" src="https://github.com/rolling-scopes-school/support/assets/101508954/cad2c6b8-8795-437b-a198-8a99e7b76af2">
<img width="1500" alt="Снимок экрана 2024-02-05 в 1 40 40 PM" src="https://github.com/rolling-scopes-school/support/assets/101508954/c7fc684e-8627-4197-874d-48090e43e308">

6. A final score after self-assessment, with comments
156, The tasks that I did are working
7. A cross-check score of your Score 
146

**Comment by helenakrasnova** [comment]
балл полученный в результате кросс-чека отличается от ожидаемого менее чем на 10 процентов
