### ISSUE TITLE
Cross-Check 'webdev' - 'Kipris'

### ISSUE THREAD

**Issue by Kipris** [rolling-scopes-school/support#95]
Ссылка на деплой вашего проекта:
https://rolling-scopes-school.github.io/kipris-JS2020Q3/webdev/

Ссылка на репозиторий с проектом на GitHub:
https://github.com/rolling-scopes-school/kipris-JS2020Q3/tree/gh-pages

Оценка в результате самопроверки, с ее аргументацией:
100/100 - выполнены все условия задания, нет расхождения более чем в 5px (при масштабе картинки в расширении PixelPerfect = 1)

Балл за cross-check из вашего Score:
77

"К сожалению из-за height: 100hv на первом блоке, мне надо снять по -3 балла к каждому пункту"
- в критериях к проверке не запрещено использовать 100vh на блоке your life

"Кнопки не наследуют фонты.Надо напрямую font-family: inherit."
- Шрифт кнопки соответствует макету

"Почитай про БЭМ. Меня учили что задавать css свойства напрямую(h1, h4 или span и т.д.) плохая практика, каждому можно задать свой класс, ну а чтобы это было удобней, использовать БЭМ."
- причем БЭМ к оцениванию проекта, не понятно; не считаю, что если напрямую задавать стили для h1-h6 - это плохая практика, так реализовано во множестве css фреймворков и библиотек

"1 кривовато стал nav, но терпимо(может было бы лучше посмторить ее блок->левый-блок | лого | правый блок и работать с ним, а так получилось что левый попадает, а правый не сильно)"
- критерии оценки: Header ! Правила касательно горизонтальных отступов между элементами меню, а также логотипа, в этом блоке не учитываются. Отклонения могут варьироваться значительно. Оценку за это не снижаем.

"(блок our life)с height = 100vh слетает весь pixelperfect, но если вытавить высоту для блока, то все становиться отлично."
- в критериях к проверке не запрещено использовать 100vh на блоке your life

"P.S. так как у надо было проверить еще и на других браузерах в Edge все кнопки скругляються.мне хотели поставить - баллы, но само по себе все работает, это тольок стили.поэтому советую обнулять стили для других браузеров тоже(-webkit-border-radius: 0; -moz-border-radius: 0; (это чтобы убрать скругление у кнопок))"
- в указаниях по кроссчеку нужно было проверять в Google chrome, нормалайзер в макете использован был

"В блоке Rappresent  изображение смещено больше чем на 5пх - 3 балла. 
В блоке Implement тоже  изображение смещено больше чем на 5пх - 3 балла. 
В блоке Download кнопка андроид смещена больше чем на 5пх - 3 балла. Обе кнопки не меняют бекграунд при наведении - 4 балла. 
 В блоке Footer  текст "Our teams" смещен на 5пх - 3 балла. "
- если выставить масштаб картинки = 1 в расширении PixelPerfect и подогнать ширину браузера под эту картинку, то никаких смещений нет; интерактив на кнопке присутствует

"Цель этого задания научиться верстать пиксель перфект. Ты умеешь верстать, но конкретно требования этого задания ты не выполнила. Учитывая твои старания и то, что ты начинающий фронтенд девелопер, я поставил тебе 70. 
Ты большой молодец, не останавливайся!"
- нет никакой конструктивной критики, оценка поставлена наобум

**Comment by valerydluski** [comment]
Header +10
Your Life +7
  из-за высоты блока 100vh всё уплыло (-3)
Rappresent +10
Our Community +10
Implement +8
  Картинка поехала больше чем на 5px -2балла
Sign Up +10
Download +10
Footer +10
Deploy +20

Итого: 95 баллов
