### ISSUE TITLE
File Manager

### ISSUE THREAD

**Issue by KalmykovaElena** [rolling-scopes-school/support#951]
1. A link to your deployed project
    - not required
2. A link to the project repository on Github.
    - https://github.com/KalmykovaElena/file-manager/pull/1
3. A link to the task
    -https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md
4. A Link to the checklist for evaluating the task (if it exists)
    - 
5. A screenshot of cross-checking marks

![image](https://github.com/rolling-scopes-school/support/assets/95431691/ffe060ce-d7c5-43e5-b405-e23dc274e8f7)

6. A final score after self-assessment, with comments
the work has not been checked / 330
7. A cross-check score of your Score

**Comment by helenakrasnova** [comment]
wrong issue name
