### ISSUE TITLE
Restoring course participation

### ISSUE THREAD

**Issue by Anton-khm** [rolling-scopes-school/support#953]
1. A link to your deployed project
    - [link](https://github.com/Anton-khm/HTML-builder)
2. A link to the project repository on Github.
    - [link](https://github.com/Anton-khm/HTML-builder)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/tree/master/stage1/tasks/html-builder)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/rolling-scopes-school/HTML-builder/wiki)
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/70846201/d6ea8979-96a9-40ac-91f6-d6b4e9c458f5)
![image](https://github.com/rolling-scopes-school/support/assets/70846201/a91dddce-05b1-4f52-b348-d592cf67b9be)

6. A final score after self-assessment, with comments
150
7. A cross-check score of your Score 
150

I was expelled for cheating, but I didn’t cheat. I did everything myself. Please restore me. My ranking is top 500.

**Comment by helenakrasnova** [comment]
You have to ask moderator, who expelled you
