### ISSUE TITLE
Cross-Check 'File Manager' 'quasar3c273'

### ISSUE THREAD

**Issue by quasar3c273** [rolling-scopes-school/support#955]
1. A link to your deployed project
    - the task didn't involve a deployment
2. A link to the project repository on Github.
    - [file-system-rss pull](https://github.com/quasar3c273/file-system-rss/pull/1)
3. A link to the task
    - [Assignment: File Manager](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/assignment.md)
4. A Link to the checklist for evaluating the task
    - [checklist ](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/file-manager/score.md)
5. A screenshot of cross-checking marks
 I only had 2 checks
<img width="536" alt="cross-check" src="https://github.com/rolling-scopes-school/support/assets/48333089/6bd5c9fa-89f8-48e1-93ad-65c76d884d44">

6. A final score after self-assessment, with comments:
7. # Scoring: File Manager
## Basic Scope

- General
    - [x] **+6** Application accepts username and prints proper message
    - [ ] (+5 pressing `ctrl+c` does not display a message) **+10** Application exits if user pressed `ctrl+c` or sent `.exit` command and proper message is printed
- Operations fail
    - [x] **+20** Attempts to perform an operation on a non-existent file or work on a non-existent path result in the operation fail
    - [x] **+10** Operation fail doesn't crash application
- Navigation & working directory operations implemented properly
    - [x] **+10** Go upper from current directory
    - [x] **+10** Go to dedicated folder from current directory
    - [x] **+20** List all files and folders in current directory
- Basic operations with files implemented properly
    - [x] **+10** Read file and print it's content in console
    - [x] **+10** Create empty file
    - [x] **+10** Rename file
    - [x] **+10** Copy file
    - [x] **+10** Move file
    - [x] **+10** Delete file
- Operating system info (prints following information in console) implemented properly
    - [x] **+6** Get EOL (default system End-Of-Line)
    - [x] **+10** Get host machine CPUs info (overall amount of CPUS plus model and clock rate (in GHz) for each of them)
    - [x] **+6** Get home directory
    - [x] **+6** Get current *system user name* (Do not confuse with the username that is set when the application starts)
    - [x] **+6** Get CPU architecture for which Node.js binary has compiled
- Hash calculation implemented properly
    - [x] **+20** Calculate hash for file 
- Compress and decompress operations
    - [x] **+20** Compress file (using Brotli algorithm)
    - [x] **+20** Decompress file (using Brotli algorithm)

## Advanced Scope

- [x] **+30** All operations marked as to be implemented using certain streams should be performed using Streams API
- [x] **+20** No synchronous Node.js API with asynchronous analogues is used (e.g. not used `readFileSync` instead of `readFile`)  
- [x] **+20** Codebase is written in ESM modules instead of CommonJS
- [x] **+20** Codebase is separated (at least 7 modules)

## Forfeits

No external tools/libraries were used during the work!
___
  if you try to create an incorrect path where possible, and also use a non-existent file instead of a file and do not use spaces in the transition, then the application works
my errors: "after pressing '```ctrl + c```' no message is displayed" (5/10)
Copy file - works
so I'm counting on a higher score of  ``` 325/330 ```
  https://github.com/quasar3c273/file-system-rss/blob/master/README.md
7. A cross-check score of your Score 
303/330

**Comment by helenakrasnova** [comment]
_A cross-check score of your Score_ should contain you final score from score-table
_A screenshot of cross-checking marks_ means all marks with comments from cross-checkers
Issue naming should be via rules: Cross-check 'name of task' - 'github'

**Comment by quasar3c273** [comment]
@helenakrasnova , description updated

**Comment by helenakrasnova** [comment]
Appeal takes place if your expected score and obtained average score (step 4) differ by 10 or more percent.
Average score less than 10% - in your case 6.7%
