### ISSUE TITLE
Cross-Check 'Simple CRUD AI'  'YauheniMel'

### ISSUE THREAD

**Issue by EugeneMelnik** [rolling-scopes-school/support#959]
1. A link to your deployed project
    - not reqired
2. A link to the project repository on Github.
    - https://github.com/YauheniMel/CRUD-NodeJS
3. A link to the task
    - https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/crud-api/assignment.md
4. A Link to the checklist for evaluating the task (if it exists)
    - https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/crud-api/score.md
5. A screenshot of cross-checking marks
![Screenshot_2024-02-21-10-57-58-502_com android chrome](https://github.com/rolling-scopes-school/support/assets/86552985/ee36574a-9c56-4e1e-b62a-091fb8c0a478)

6. A final score after self-assessment, with comments
I think the score should be 140. I agree with the first reviewer, but the cluster part I think is underestimated. I actually did some initial implementation. And the second reviewer gave me 0 points, which is definitely unfair. 

7. A cross-check score of your Score 
65

**Comment by helenakrasnova** [comment]
Почему отсутствует история разработки?

**Comment by EugeneMelnik** [comment]
> Почему отсутствует история разработки?

Впредь буду делать историю. Просто не хватает времени. За это согласен нужно отнимать баллы. Полагаю, первый reviewer это учёл.

**Comment by helenakrasnova** [comment]
я дико извиняюсь, но отсутствует 5-10 секунд времени по завершению работы сделать git add -a, git commit, git push, возможно ли это?

**Comment by EugeneMelnik** [comment]
> я дико извиняюсь, но отсутствует 5-10 секунд времени по завершению работы сделать git add -a, git commit, git push, возможно ли это?

Вы абсолютно правы. Но у меня не хватило времени прочитать правила. Я просто взял и начал делать таску.
