### ISSUE TITLE
Cross-Check webdev - MaximSamorukov 

### ISSUE THREAD

**Issue by MaximSamorukov** [rolling-scopes-school/support#96]
1. https://maximsamorukov.github.io/webdev/
2. https://github.com/MaximSamorukov/webdev
3. 
    3.1. Проверяющим (Student 2) было выставлено 69 баллов. Среди прочего, 20 баллов было снято за то, что проект выполнен в собственном репозитории и 7 баллов (3 балла и 4 балла) было снято за несоответствие макету.

    3.2. В документации к заданию было сказано, что репозиторий может быть использован любой (как личный, так и школьный). Кроме того, выполненное задание загружается, поэтому считаю, что 20 баллов снято неправомочно.

    3.3. Мое задание соответствует изначальному макету. Так как к моменту появления исправленного макета, я уже проделал основную часть верстки, то переверствовать не стал, к тому же такого требования не обозначалось. Поэтому, считаю, что 7 баллов было снято неправомочно.

    3.4. Итого. Считаю, что адекватной оценкой в данном случае будет: 96 баллов (69 + 20 + 7).

4. 69

**Comment by Alexey-Koren** [comment]
Апеллируется итоговая оценка за задание.
Ваша апелляция не подходит под правила, прочитайте пункт 4.
В разделе про апелляции https://docs.rs.school/#/cross-check-flow

Закрываю
