### ISSUE TITLE
Cross-Check GraphQL-Basics - zzVIPz

### ISSUE THREAD

**Issue by zzVIPz** [rolling-scopes-school/support#960]
1. A link to your deployed project
    - NA
2. A link to the project repository on Github.
    - [link](https://github.com/zzVIPz/rsschool-nodejs-task-graphql/pulls)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/graphql-service/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - NA
5. A screenshot of cross-checking marks
![image](https://github.com/rolling-scopes-school/support/assets/43119686/8afb5562-6446-4483-9e94-b6efc87b6961)

6. A final score after self-assessment, with comments
Score 360/ 360 All requirements were implemented

7. A cross-check score of your Score 
(360 + 0)  / 2= 180

Some additional information to run the project (just in case :))
1. clone the repo above
2. switch to develop branch
3.  Steps to get started:
        1. Install dependencies: npm ci
        2. Create .env file (based on .env.example): ./.env
        3. Create db file: ./prisma/database.db
        4. Apply pending migrations: npx prisma migrate deploy
        5. Seed db: npx prisma db seed
        6. Start server: npm run start
4. run all the tests from package.json

Thank you very much in advance!

Kind regards,
Sergey

**Comment by nosbog** [comment]
lgtm, final score is 360

**Comment by zzVIPz** [comment]
@nosbog Thank you very much for your quick consideration and help!

**Comment by ThorsAngerVaNeT** [comment]
Score is updated
