### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by mrHoft** [rolling-scopes-school/support#961]
Faced the issue with the Web Security test on 2023q4:
![image](https://github.com/rolling-scopes-school/support/assets/51874769/2ecac9b3-f7af-4327-a361-d95cb46a9932)
And i have 0 point for now.

**Comment by haslie22** [comment]
@mrHoft, please attach a full screenshot that will cover all of your attempts and display the scores for each attempt.

**Comment by mrHoft** [comment]
@haslie22, sure:
![image](https://github.com/rolling-scopes-school/support/assets/51874769/a7507a78-df3a-4707-a4a0-44d69bf8ff7a)

**Comment by haslie22** [comment]
@mrHoft, above your test results table, you can see the subscription, "You must score at least 70% of points to pass." It means that each time your test result is less than 70% of the maximum result (meaning less than 70 points in your case), your score will be zero, regardless of whether you gained 69% of points or only 5%.
So, it's more of a feature than a bug in RS App 😄

In your case, you've made 2 attempts, and for every new attempt, your score will be divided by 2. So, if you gain 90 points, you'll only receive 45 of them in the score. However, it's always better than 0 in your case. Therefore, I'd recommend you to take this test a couple more times to increase your score.

**Comment by mrHoft** [comment]
@haslie22
1. It was a system bug with the test cause i can not made so many wrong answers after the first successful attempt.
2. The test is closed for the new attempts.
Please delete this bugged attempt.
I was counting to receive a minimum 94 at my last attempt, but in this situation 85 (confirmed result) will be enough.

**Comment by helenakrasnova** [comment]
@mrHoft здесь репозиторий с апелляциями
ишью по приложению рсапп вносятся [в этот репозиторий](https://github.com/rolling-scopes-school/tasks/issues) или [в этот](https://github.com/rolling-scopes/rsschool-app/issues) 
данная проблема с тестом уже устранена
