### ISSUE TITLE
Cross-Check 'React. Task #1 React project setup. Class components. Error boundary.' 'guranda26'

### ISSUE THREAD

**Issue by guranda26** [rolling-scopes-school/support#965]
1. A link to your deployed project
- [deployed project](https://star-wars-character-finder-ak0oryk2t-guranda26s-projects.vercel.app/)
2. A link to the project repository on Github.
- [project repository](https://github.com/guranda26/star-wars-character-finder/)
3. A link to the task
- [Task Link](https://github.com/rolling-scopes-school/tasks/blob/master/react/modules/tasks/class-components.md)
4. A Link to the checklist for evaluating the task (if it exists)
- [Checklist](https://github.com/rolling-scopes-school/tasks/blob/master/react/modules/tasks/class-components.md)
5. A screenshot of cross-checking marks
- 
<img width="1052" alt="Screenshot " src="https://github.com/user-attachments/assets/f7a1c351-4c33-4826-b378-c6a8dc8dea94">
- <img width="806" alt="Screenshot 1" src="https://github.com/user-attachments/assets/f2851cce-8326-4f8d-8435-cad9e63164d3">
6. A final score after self-assessment, with comments.

- Score: 94 / 100.    

- [x] Eslint is set up, when lint command is run it doesn't produce any errors (if there are warnings score might be less) - (15/15) 
- [x] Prettier is set up, format:fix command fixes issues - (15/15). 
- [x] Husky is set up, linting is run on pre-commit - (10/10). 
- [x] Page is split into 2 sections, top one has Search input and "Search" button, main section displays the list of results from the selected api when page is opened for the first time (loader should be shown while app makes a call to the api) - (20/20). 
- [x] When user types something to the Search input and clicks "Search" button, a loader is displayed and the list is changed according to the response results for a provided search term - (15/15).    
- [x] The search term typed into the Search input is saved in the LS when user clicks on "Search" button (check it by closing the tab and open the app in the new one - the initial call should contain previously entered search term) - (15/15). 
- [ ] Application is wrapped with ErrorBoundary, which logs error to a console but doesn't show a fallback UI. There should be a button to throw an error - (6/10).   
7. A cross-check score of your Score:
71

**Comment by helenakrasnova** [comment]
Please, fix your appeal according to rules: https://docs.rs.school/#/en/cross-check-flow?id=appeal

**Comment by guranda26** [comment]
Hello. is it correct now?

**Comment by helenakrasnova** [comment]
Point _Screenshot of the cross-check grades (the reviewers' contact information should be hidden)._ should be fixed as well
Please fix 6 point using markdown syntax properly

**Comment by guranda26** [comment]
Thank you. I have fixed it

**Comment by andron13** [comment]
1. Branch **Main** should have been clean (only readme and, for example, gitignore) and the work should have started in the task branch.
2. vite.svg remained in the standard favicon.

Regarding the task points:

1. [x] Eslint is set up; when the lint command is run, it doesn't produce any errors (if there are warnings, the score might be less).
2. [x] Prettier is set up; format:fix command fixes issues.
3. [x] Husky is set up; linting is run on pre-commit.
4. [x] Page is split into 2 sections.
5. [x] When the user types something into the Search input and clicks the 'Search' button.
6. [x] The search term typed into the Search input is saved in the LS.
7. [ ] Application is wrapped with ErrorBoundary.

Only the seventh point is not done. The button didn't work for me. The ErrorBoundary.tsx is present in the code.
There can be a debate about how many out of 10 points should be given for this. I estimate it at half - 5 points.

My total is 94 points. I deduct one point for working in the main branch.

@helenakrasnova could you take a look?

**Comment by helenakrasnova** [comment]
@andron13 thank you!

**Comment by helenakrasnova** [comment]
score is updated

**Comment by guranda26** [comment]
Thank you very much
