### ISSUE TITLE
Cross-Check 'CV#3.' - 'morozksenia'.

### ISSUE THREAD

**Issue by morozksenia** [rolling-scopes-school/support#966]
1. A link to your deployed project
    - [https://morozksenia.github.io/rsschool-cv/]
2. A link to the project repository on Github.
    - [https://github.com/morozksenia/rsschool-cv]
3. A link to the task
    - [https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md]
4. A Link to the checklist for evaluating the task (if it exists)
    - [https://rolling-scopes-school.github.io/checklist/]
5. A screenshot of cross-checking marks
<img width="1092" alt="Снимок экрана 2024-07-12 в 3 56 06 PM" src="https://github.com/user-attachments/assets/f6a80b45-1889-4acb-bed3-eed5c5a01ddb">

6. A final score after self-assessment, with comments
 110 (навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a ( 0 баллов - Контакты выполнены не списком )
8. A cross-check score of your Score 120

**Comment by helenakrasnova** [comment]
Апелляция производится только если ожидаемый вами балл и полученный на кросс-чеке средний балл отличаются на 10 и более процентов от максимального балла за задание., отличие 8%
