### ISSUE TITLE
Cross-Check 'CV#3.' - 'aozubrilin'.

### ISSUE THREAD

**Issue by aozubrilin** [rolling-scopes-school/support#967]
1. A link to your deployed project
    - [link](https://aozubrilin.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [link](https://github.com/aozubrilin/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![app rs school_course_student_cross-check-submit_course=js-fe-preschool-2024q2 taskId=3104 (1)](https://github.com/user-attachments/assets/9f9ab188-8970-416c-8ffc-70f641c7a250)
6. A final score after self-assessment, with comments
 120 баллов

Не выполненные/не засчитанные пункты:
1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages

Выполненные пункты:
1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований
2) header, main, footer
3) элемент nav
4) только один заголовок h1
5) заголовки h2
6) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка.
7) для оформления СV используются css-стили
8) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону
9) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt.
10) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованого списка ol > li или ol > li > a
11) краткую информацию о себе
12) контакты для связи
13) перечень навыков
14) пример кода. Код добавляется при помощи символов и тегов, а не картинкой
15) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения
16) информацию об образовании и уровне английского
17) CV выполнено на английском языке

7. A cross-check score of your Score 
![app rs school_course_score_course=js-fe-preschool-2024q2](https://github.com/user-attachments/assets/a4473424-de1a-4678-9816-ac1c473229ca)

**Comment by anthony-th** [comment]
Ваша оценка - **120** баллов

_Отзыв по пунктам ТЗ:_

### Не выполненные/не засчитанные пункты:

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

### Выполненные пункты:

1) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

2) header, main, footer 

3) элемент nav 

4) только один заголовок h1 

5) заголовки h2 

6) в footer есть ссылка на github автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

7) для оформления СV используются css-стили 

8) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

9) на странице СV есть фото или аватар автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

10) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованного списка ol > li или ol > li > a 

11) краткую информацию о себе 

12) контакты для связи 

13) перечень навыков 

14) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

15) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

16) информацию об образовании и уровне английского 

17) CV выполнено на английском языке

**Comment by helenakrasnova** [comment]
@anthony-th thank you!
