### ISSUE TITLE
Cross-Check 'CV#3' - 'ynagay-js'

### ISSUE THREAD

**Issue by ynagay-js** [rolling-scopes-school/support#969]
1. A link to your deployed project
    - [CV Page](https://ynagay-js.github.io/rsschool-cv/)
2. A link to the project repository on Github.
    - [Project Repository](https://github.com/ynagay-js/rsschool-cv/tree/rsschool-cv-html)
3. A link to the task
    - [CV#3](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/cv-stage0.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [CV#3. CV. Cross-Check](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![image](https://github.com/user-attachments/assets/00a0ed93-586c-4317-9ee8-b20463bd09b2)
6. A final score after self-assessment, with comments
Score: 130 / 120
- Валидность (20/20)
  - [x] сабмит и деплой на gh-pages (10)
  - [x] верстка валидная (10)   
- Верстка семантическая (70/70)
  - [x] header, main, footer (5)
  - [x] элемент nav (5)
  - [x] только один заголовок h1 (5)
  - [x] заголовки h2 (5)
  - [x] footer с ссылками(10)
  - [x] использование css стилей (10)
  - [x] страница по центру при уменьшении масштаба (10)
  - [x] фото/аватар с правильных пропорциях (10)
  - [x] секции с использованием списков ul > li (10)
- Содержание CV (40/40)
  - [x] информация о себе (5)
  - [x] контакты для связи (5)
  - [x] перечень навыков (5)
  - [x] пример кода (5)
  - [x] перечень проектов (5)
  - [x] образование и уровень английского (5)
  - [x] CV на английском языке (10)
7. A cross-check score of your Score 
![image](https://github.com/user-attachments/assets/37d3f2dd-a924-4c77-9794-3964349ac9ff)

**Comment by ynagay-js** [comment]
![image](https://github.com/user-attachments/assets/2c4608c3-4892-494f-b5b3-58a02463d9e5)

**Comment by anthony-th** [comment]
### Ваша оценка - 130 баллов из 120 максимально возможных за задание

Отзыв по пунктам ТЗ:

### Выполненные пункты:

1) студент засабмитил в rs app ссылку на своё CV, задеплоенное на gh-pages 

2) вёрстка валидная. Для проверки валидности вёрстки используйте сервис https://validator.w3.org/. Валидной вёрстке соответствует надпись "Document checking completed. No errors or warnings to show." В таком случае баллы за пункт требований выставляем полностью. Если есть предупреждения - warnings, но нет ошибок - errors, выставляем половину баллов за пункт требований 

3) header, main, footer 

4) элемент nav 

5) только один заголовок h1 

6) заголовки h2 

7) в footer есть ссылка на гитхаб автора работы, год создания приложения, логотип курса со ссылкой на курс. Если ссылка в футере ведёт на курс stage0, это не ошибка. 

8) для оформления СV используются css-стили 

9) при уменьшении масштаба страницы браузера вёрстка размещается по центру по горизонтали, а не сдвигается в сторону 

10) на странице СV есть фото или аватарка автора, пропорции изображения не искажены (т.е. картинка не деформирована, если её размер изменён, сохраняются пропорции исходного изображения), у изображения есть атрибут alt. 

11) навигация, контакты для связи и перечень навыков оформлены в виде списка ul > li или ul > li > a. Также допускается использование нумерованного списка ol > li или ol > li > a 

12) краткую информацию о себе 

13) контакты для связи 

14) перечень навыков 

15) пример кода. Код добавляется при помощи символов и тегов, а не картинкой 

16) перечень выполненных учебных проектов со ссылками на исходный код или страницу приложения 

17) информацию об образовании и уровне английского 

18) CV выполнено на английском языке

**Comment by helenakrasnova** [comment]
@anthony-th thank you!
