### ISSUE TITLE
Cross-Check 'webdev' - 'loktysh' 

### ISSUE THREAD

**Issue by Loktysh** [rolling-scopes-school/support#97]
Ссылка на деплой проекта: https://rolling-scopes-school.github.io/loktysh-JS2020Q3/webdev/
Ссылка на репозиторий: https://github.com/rolling-scopes-school/loktysh-JS2020Q3

Оценка в ходе самопроверки: 100. Все требования к таску выполнены в полном объеме, все блоки совпадаю с **_старым_** макетом согласно PerfectPixel.

**Апелляция первая :**
Student 1
Score: 70

1. Надпись webdev справа от интро, которой быть не должно.

2. Начиная с блока `sign up` идет не соответствие макету.

**Апелляция вторая:**
Student 2
Score: 82

Во всех блоках текст заголовков нарушает размеры по высоте.

Заголовок H1 не скрыт со страницы

**Баллы из Score:** 70 и 82.

**Comment by Alexey-Koren** [comment]
Ваш итоговый балл за таск 89 балл.
Ваша апелляция не подходит под правила, прочитайте пункт 4.
В разделе про апелляции https://docs.rs.school/#/cross-check-flow

Закрываю
