### ISSUE TITLE
Cross-Check Shelter Part 1 - @nadia-dia

### ISSUE THREAD

**Issue by Nadia-dia** [rolling-scopes-school/support#970]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/nadia-dia-JSFEPRESCHOOL2024Q2/shelter/pages/main/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/nadia-dia-JSFEPRESCHOOL2024Q2)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![image](https://github.com/user-attachments/assets/444fb7d5-7502-4012-80a2-e35a66403d76)
![image](https://github.com/user-attachments/assets/23663abf-3edf-4220-87ee-fe061f4cded6)

6. A final score after self-assessment, with comments

100/100 
The whole task has been done according to the requermentы and template in Figma.
Страница Main (60)
1) Проверка верстки +7/7
[+] верстка страницы валидная +4
[+] логотип в хедере состоит из текстовых элементов +1
[+] страница содержит ровно один элемент h1 +1
[+] добавлен favicon +1
2) Вёрстка соответствует макету +35/35
[+] блок +5
[+] блок Not only +5
[+] блок About +5
[+] блок Our Friends +5
[+] блок Help +5
[+] блок In addition +5
[+] блок +5
3) Требования к css +6/6
[+] для позиционирования элементов блока Help использована сеточная верстка (flexbox) +2
[+] при уменьшении масштаба страницы браузера или увеличении ширины страницы (>1280px) вёрстка размещается
по центру, а не сдвигается в сторону и не растягивается по всей ширине +2
[+] фоновый цвет тянется на всю ширину страницы +2
4) Интерактивность элементов +12/12
[+]элемент About the Shelter в навигации подсвечен и неинтерактивен, остальные элементы навигации интерактивны
+2
[+]каждая карточка с питомцем в блоке Our Friends интерактивна при наведении на любую область этой карточки +2
[+]плавная прокрутка по якорям +2
[+]выполняются все ссылочные связи согласно [Перечню ссылочных связей](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md#%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B5%D0%BD%D1%8C-%D1%81%D1%81%D1%8B%D0%BB%D0%BE%D1%87%D0%BD%D1%8B%D1%85-%D1%81%D0%B2%D1%8F%D0%B7%D0%B5%D0%B9) для страницы Main +2
[+] выполнена интерактивность ссылок и кнопок +2
[+] плавное изменение внешнего вида элемента при наведении и клике, не влияющее на соседние элементы +2
Страница Pets (40)
5) Проверка верстки +7/7
[+] верстка страницы валидная +4
[+] логотип в хедере состоит из текстовых элементов +1
[+] страница содержит ровно один элемент h1 +1
[+] добавлен favicon +1
6) Вёрстка соответствует макету +15/15
[+] блок +5
[+] блок Our Friends +5
[+] блок +5
7) Требования к css +4/4
[+] при уменьшении масштаба страницы браузера или увеличении ширины страницы (>1280px) вёрстка размещается
по центру, а не сдвигается в сторону и не растягивается по всей ширине +2
[+] фоновый цвет тянется на всю ширину страницы +2
8) Интерактивность элементов +14/14
[+] элемент Our pets в навигации подсвечен и неинтерактивен, остальные элементы навигации интерактивны +2
[+] доступные кнопки пагинации (вправо) активны, недоступные (влево) - неактивны (disabled) +2
[+] каждая карточка с питомцем в блоке Our Friends интерактивна при наведении на любую область этой карточки
+2
[+] плавная прокрутка по якорям +2
[+] выполняются все ссылочные связи согласно [Перечню ссылочных связей](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part1.md#%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B5%D0%BD%D1%8C-%D1%81%D1%81%D1%8B%D0%BB%D0%BE%D1%87%D0%BD%D1%8B%D1%85-%D1%81%D0%B2%D1%8F%D0%B7%D0%B5%D0%B9) для страницы Pets +2
[+] выполнена интерактивность ссылок и кнопок +2
[+] плавное изменение внешнего вида элемента при наведении и клике, не влияющее на соседние элементы +2
7. A cross-check score of your Score: 79 / 100

**Comment by lyutails** [comment]
hey there o/
you do have horizontal scroll on every screen width
![image](https://github.com/user-attachments/assets/945223cb-3213-4a1d-bf18-02d6e2122398)

then from what i see - based on points in your console output - you already can't get 100 points for the task - or maybe criteria in your console is not actual

![image](https://github.com/user-attachments/assets/004ba867-0699-4f32-9c18-42a1f02c77cb)

same on `Our Pets` page
![image](https://github.com/user-attachments/assets/446f11fb-9b9d-4657-b21b-ceb94f35223d)
