### ISSUE TITLE
Cross-Check 'Shelter. week-2 - Адаптивная вёрстка' -  vitasvichkar

### ISSUE THREAD

**Issue by VitaSvichkar** [rolling-scopes-school/support#971]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/vitasvichkar-JSFE2023Q4/shelter/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/vitasvichkar-JSFE2023Q4/tree/shelter-part2)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![Снимок экрана 2024-08-16 145422](https://github.com/user-attachments/assets/29d4e486-cef7-4683-a135-d1744ee36883)
![Снимок экрана 2024-08-16 145405](https://github.com/user-attachments/assets/f224a0af-05db-4370-b55d-6539bfa54a5e)
![Снимок экрана 2024-08-16 145412](https://github.com/user-attachments/assets/b0e1f01b-a90d-449a-b279-97fa8f308637)

6. A final score after self-assessment, with comments
100/100
7. A cross-check score of your Score 
82/100

**Comment by helenakrasnova** [comment]
Ишью называем его по шаблону: **Cross-Check 'название таска' - 'Ваше имя на Github'** - исправить

Вы должны выполнять задания в приватном репо школы соответсвующего курса - JSFEPRESCHOOL2024Q2, задание выполнено в репо предыдущего набора

**добавить**: A Link to the checklist for evaluating the task
