### ISSUE TITLE
Shelter. Part 3 - alexei57

### ISSUE THREAD

**Issue by alexei57** [rolling-scopes-school/support#973]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/alexei57-JSFEPRESCHOOL2024Q2/shelter/index.html)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/alexei57-JSFEPRESCHOOL2024Q2)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part3.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![image](https://github.com/user-attachments/assets/1e5494c1-c6df-48be-a23b-6ca45ada098a)

6. A final score after self-assessment, with comments
Ваша оценка - 69 баллов

Отзыв по пунктам ТЗ:

Не выполненные/не засчитанные пункты:

1) при нажатии на стрелки происходит переход к новому блоку элементов
2) смена блоков происходит с соответствующей анимацией карусели (способ выполнения анимации не проверяется)
3) слайдер бесконечен, т.е. можно бесконечно много нажимать влево или вправо, и каждый раз будет прокрутка в эту сторону с новым набором карточек
4) при переключении влево или вправо прокручивается ровно столько карточек, сколько показывается при текущей ширине экрана (3 для 1280px, 2 для 768px, 1 для 320px)
5) в текущем блоке слайда карточки с питомцами не повторяются
6) в следующем блоке нет дублирования карточек с текущим блоком. Например в слайдере из 3 элементов, следующий выезжающий слайд будет содержать 3 (из 8 доступных) новых карточки питомца, таких, каких не было среди 3х карточек на предыдущем уехавшем слайде
7) сохраняется только одно предыдущее состояние. Т.е. при последовательном переходе два раза влево, а потом два раза вправо, мы получим набор карточек, отличный от исходного
8) при каждой перезагрузке страницы формируется новая последовательность карточек
9) генерация наборов карточек происходит на основе 8 объектов с данными о животными
10) при изменении ширины экрана (от 1280px до 320px и обратно), слайдер перестраивается и работает без перезагрузки страницы (набор карточек при этом может как изменяться, так и оставаться тем же, скрывая лишнюю или добавляя недостающую, и сохраняя при этом описанные для слайдера требования)
11) карточки питомцев не должны повторяться на одной странице

Частично выполненные пункты:
1) попап появляется при нажатии на любое место карточки с описанием конкретного животного
Отзыв: На второй странице попап не открывается(

Выполненные пункты:

1) при ширине страницы меньше 768рх панель навигации скрывается, появляется бургер-иконка
2) при нажатии на бургер-иконку, справа плавно появляется адаптивное меню шириной 320px, бургер-иконка плавно поворачивается на 90 градусов
3) высота адаптивного меню занимает всю высоту экрана
4) при повторном нажатии на бургер-иконку или на свободное от бургер-меню пространство (оба варианта должны быть реализованы) адаптивное меню плавно скрывается уезжая за правую часть экрана, бургер-иконка плавно поворачивается на 90 градусов обратно
5) бургер-иконка создана при помощи html+css, без использования изображений
6) ссылки в адаптивном меню работают, обеспечивая плавную прокрутку по якорям, сохраняются заданные на первом этапе выполнения задания требования интерактивности элементов меню
7) при клике по любой ссылке (интерактивной или неинтерактивной) в меню адаптивное меню плавно скрывается вправо, бургер-иконка поворачивается на 90 градусов обратно
8) расположение и размеры элементов в бургер-меню соответствует макету (центрирование по вертикали и горизонтали элементов меню, расположение иконки). При этом на странице Pets цветовая схема может быть как темная, так и светлая
9) область, свободная от бургер-меню, затемняется
10) страница под бургер-меню не прокручивается
11) при перезагрузке страницы всегда открывается первая страница пагинации
12) при нажатии кнопок '>' или '<' открывается следующая или предыдущая страница пагинации соответственно
13) при нажатии кнопок '>>' или '<<' открывается последняя или первая страница пагинации соответственно
14) при открытии первой страницы кнопки '<<' и '<' неактивны
15) при открытии последней страницы кнопки '>' и '>>' неактивны
16) в кружке по центру указан номер текущей страницы. При переключении страниц номер меняется на актуальный
17) при загрузке страницы формируется массив из 48 объектов питомцев. Каждый из 8 питомцев должен встречаться ровно 6 раз
18) при каждой перезагрузке страницы формируется новый массив со случайной последовательностью
19) при переключении страницы данные меняются (для >1280px меняется порядок карточек, для остальных - меняется набор и порядок карточек)
20) при неизменных размерах области пагинации, в том числе размерах окна браузера, и без перезагрузки страницы, возвращаясь на страницу под определенным номером, контент на ней всегда будет одинаков. Т.е. карточки питомцев будут в том же расположении, что и были до перехода на другие страницы
21) общее количество страниц при ширине экрана 1280px - 6, при 768px - 8, при 320px - 16 страниц
22) при изменении ширины экрана (от 1280px до 320px и обратно), пагинация перестраивается и работает без перезагрузки страницы (страница может оставаться той же или переключаться, при этом сформированный массив - общая последовательность карточек - не обновляется, сохраняются все остальные требования к пагинации)
23) часть страницы вне попапа затемняется
24) при открытии попапа вертикальный скролл страницы становится неактивным, при закрытии - снова активным
25) при нажатии на область вокруг попапа или на кнопку с крестиком попап закрывается (оба варианта должны быть реализованы), при этом при нажатии на сам попап ничего не происходит
26) кнопка с крестиком интерактивная
27) окно попапа (не считая кнопку с крестиком) центрировано по всем осям, размеры элементов попапа и их расположение совпадают с макетом
7. A cross-check score of your Score 
 0 баллов (к сожалению мою работу никто не проверил)

**Comment by helenakrasnova** [comment]
отредактировать название ишью: 'Shelter. Part 3' - 'github'
