### ISSUE TITLE
 Cross-Check 'Shelter Part 3' - 0Milky0

### ISSUE THREAD

**Issue by 0Milky0** [rolling-scopes-school/support#974]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/0milky0-JSFEPRESCHOOL2024Q2/shelter/)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/0milky0-JSFEPRESCHOOL2024Q2)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part3.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![Снимок экрана 2024-09-13 120359](https://github.com/user-attachments/assets/786af852-0d42-4a3b-8ada-1d8ca5bb35f4)
![Снимок экрана 2024-09-13 120454](https://github.com/user-attachments/assets/36a7f90b-b554-4138-992d-b7dc85f8c21d)
6. A final score after self-assessment, with comments
Я считаю, что оценка должна быть 110, так как все пункты ТЗ были выполнены и все проверяющие поставили максимальную оценку, кроме одного, который в комментарии написал, что оценка максимальная, но видимо забыл поставить её в поле для оценки и оставил 0.
7. A cross-check score of your Score 
Мой балл - 73

**Comment by anthony-th** [comment]
Ваша оценка - **110** баллов

<details><summary>Отзыв по пунктам ТЗ:</summary>

### Выполненные пункты:

1) при ширине страницы меньше 768рх панель навигации скрывается, появляется бургер-иконка 

2) при нажатии на бургер-иконку, справа плавно появляется адаптивное меню шириной 320px, бургер-иконка плавно поворачивается на 90 градусов 

3) высота адаптивного меню занимает всю высоту экрана 

4) при повторном нажатии на бургер-иконку или на свободное от бургер-меню пространство (оба варианта должны быть реализованы) адаптивное меню плавно скрывается уезжая за правую часть экрана, бургер-иконка плавно поворачивается на 90 градусов обратно 

5) бургер-иконка создана при помощи html+css, без использования изображений 

6) ссылки в адаптивном меню работают, обеспечивая плавную прокрутку по якорям, сохраняются заданные на первом этапе выполнения задания требования интерактивности элементов меню 

7) при клике по любой ссылке (интерактивной или неинтерактивной) в меню адаптивное меню плавно скрывается вправо, бургер-иконка поворачивается на 90 градусов обратно 

8) расположение и размеры элементов в бургер-меню соответствует макету (центрирование по вертикали и горизонтали элементов меню, расположение иконки). При этом на странице Pets цветовая схема может быть как темная, так и светлая 

9) область, свободная от бургер-меню, затемняется 

10) страница под бургер-меню не прокручивается 

11) при нажатии на стрелки происходит переход к новому блоку элементов 

12) смена блоков происходит с соответствующей анимацией карусели (способ выполнения анимации не проверяется) 

13) слайдер бесконечен, т.е. можно бесконечно много нажимать влево или вправо, и каждый раз будет прокрутка в эту сторону с новым набором карточек 

14) при переключении влево или вправо прокручивается ровно столько карточек, сколько показывается при текущей ширине экрана (3 для 1280px, 2 для 768px, 1 для 320px) 

15) в текущем блоке слайда карточки с питомцами не повторяются 

16) в следующем блоке нет дублирования карточек с текущим блоком. Например в слайдере из 3 элементов, следующий выезжающий слайд будет содержать 3 (из 8 доступных) новых карточки питомца, таких, каких не было среди 3х карточек на предыдущем уехавшем слайде 

17) сохраняется только одно предыдущее состояние. Т.е. при последовательном переходе два раза влево, а потом два раза вправо, мы получим набор карточек, отличный от исходного 

18) при каждой перезагрузке страницы формируется новая последовательность карточек 

19) генерация наборов карточек происходит на основе 8 объектов с данными о животными 

20) при изменении ширины экрана (от 1280px до 320px и обратно), слайдер перестраивается и работает без перезагрузки страницы (набор карточек при этом может как изменяться, так и оставаться тем же, скрывая лишнюю или добавляя недостающую, и сохраняя при этом описанные для слайдера требования) 

21) при перезагрузке страницы всегда открывается первая страница пагинации 

22) при нажатии кнопок '>' или '<' открывается следующая или предыдущая страница пагинации соответственно 

23) при нажатии кнопок '>>' или '<<' открывается последняя или первая страница пагинации соответственно 

24) при открытии первой страницы кнопки '<<' и '<' неактивны 

25) при открытии последней страницы кнопки '>' и '>>' неактивны 

26) в кружке по центру указан номер текущей страницы. При переключении страниц номер меняется на актуальный 

27) при загрузке страницы формируется массив из 48 объектов питомцев. Каждый из 8 питомцев должен встречаться ровно 6 раз 

28) при каждой перезагрузке страницы формируется новый массив со случайной последовательностью 

29) карточки питомцев не должны повторяться на одной странице 

30) при переключении страницы данные меняются (для >1280px меняется порядок карточек, для остальных - меняется набор и порядок карточек) 

31) при неизменных размерах области пагинации, в том числе размерах окна браузера, и без перезагрузки страницы, возвращаясь на страницу под определенным номером, контент на ней всегда будет одинаков. Т.е. карточки питомцев будут в том же расположении, что и были до перехода на другие страницы 

32) общее количество страниц при ширине экрана 1280px - 6, при 768px - 8, при 320px - 16 страниц 

33) при изменении ширины экрана (от 1280px до 320px и обратно), пагинация перестраивается и работает без перезагрузки страницы (страница может оставаться той же или переключаться, при этом сформированный массив - общая последовательность карточек - не обновляется, сохраняются все остальные требования к пагинации) 

34) попап появляется при нажатии на любое место карточки с описанием конкретного животного 

35) часть страницы вне попапа затемняется 

36) при открытии попапа вертикальный скролл страницы становится неактивным, при закрытии - снова активным 

37) при нажатии на область вокруг попапа или на кнопку с крестиком попап закрывается (оба варианта должны быть реализованы), при этом при нажатии на сам попап ничего не происходит 

38) кнопка с крестиком интерактивная 

39) окно попапа (не считая кнопку с крестиком) центрировано по всем осям, размеры элементов попапа и их расположение совпадают с макетом 
</details>
