### ISSUE TITLE
Cross-Check 'Shelter Part 3' - 'burberman9000'

### ISSUE THREAD

**Issue by burberman9000** [rolling-scopes-school/support#975]
1. A link to your deployed project
    - [link](https://rolling-scopes-school.github.io/burberman9000-JSFEPRESCHOOL2024Q2/main.html)
2. A link to the project repository on Github.
    - [link](https://github.com/rolling-scopes-school/burberman9000-JSFEPRESCHOOL2024Q2)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/shelter/shelter-part3.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![image](https://github.com/user-attachments/assets/37c36e78-8b42-4710-861f-517c6104af78)
![image](https://github.com/user-attachments/assets/9de873f2-ee99-403d-888d-6790510ab246)
![image](https://github.com/user-attachments/assets/4307c8ad-afca-4f30-a4ef-4fc8dc086c34)

6. A final score after self-assessment, with comments:
Score: 100 / 110
  Ваша оценка - 100 баллов 
Отзыв по пунктам ТЗ:
Не выполненные/не засчитанные пункты:
1) сохраняется только одно предыдущее состояние. Т.е. при последовательном переходе два раза влево, а потом два раза вправо, мы получим набор карточек, отличный от исходного 

Частично выполненные пункты:
1) высота адаптивного меню занимает всю высоту экрана 
Отзыв: Занимает не всю высоту экрана
2) смена блоков происходит с соответствующей анимацией карусели (способ выполнения анимации не проверяется) 
Отзыв: Переключение есть, но без анимации
3) при переключении влево или вправо прокручивается ровно столько карточек, сколько показывается при текущей ширине экрана (3 для 1280px, 2 для 768px, 1 для 320px) 
Отзыв: Не везде реализован функционал с количеством страниц
4) общее количество страниц при ширине экрана 1280px - 6, при 768px - 8, при 320px - 16 страниц 
Отзыв: Не весь функционал работает
Выполненные пункты:
1) при ширине страницы меньше 768рх панель навигации скрывается, появляется бургер-иконка 

2) при нажатии на бургер-иконку, справа плавно появляется адаптивное меню шириной 320px, бургер-иконка плавно поворачивается на 90 градусов 

3) при повторном нажатии на бургер-иконку или на свободное от бургер-меню пространство (оба варианта должны быть реализованы) адаптивное меню плавно скрывается уезжая за правую часть экрана, бургер-иконка плавно поворачивается на 90 градусов обратно 

4) бургер-иконка создана при помощи html+css, без использования изображений 

5) ссылки в адаптивном меню работают, обеспечивая плавную прокрутку по якорям, сохраняются заданные на первом этапе выполнения задания требования интерактивности элементов меню 

6) при клике по любой ссылке (интерактивной или неинтерактивной) в меню адаптивное меню плавно скрывается вправо, бургер-иконка поворачивается на 90 градусов обратно 

7) расположение и размеры элементов в бургер-меню соответствует макету (центрирование по вертикали и горизонтали элементов меню, расположение иконки). При этом на странице Pets цветовая схема может быть как темная, так и светлая 

8) область, свободная от бургер-меню, затемняется 

9) страница под бургер-меню не прокручивается 

10) при нажатии на стрелки происходит переход к новому блоку элементов 

11) слайдер бесконечен, т.е. можно бесконечно много нажимать влево или вправо, и каждый раз будет прокрутка в эту сторону с новым набором карточек 

12) в текущем блоке слайда карточки с питомцами не повторяются 

13) в следующем блоке нет дублирования карточек с текущим блоком. Например в слайдере из 3 элементов, следующий выезжающий слайд будет содержать 3 (из 8 доступных) новых карточки питомца, таких, каких не было среди 3х карточек на предыдущем уехавшем слайде 

14) при каждой перезагрузке страницы формируется новая последовательность карточек 

15) генерация наборов карточек происходит на основе 8 объектов с данными о животными 

16) при изменении ширины экрана (от 1280px до 320px и обратно), слайдер перестраивается и работает без перезагрузки страницы (набор карточек при этом может как изменяться, так и оставаться тем же, скрывая лишнюю или добавляя недостающую, и сохраняя при этом описанные для слайдера требования) 

17) при перезагрузке страницы всегда открывается первая страница пагинации 

18) при нажатии кнопок '>' или '<' открывается следующая или предыдущая страница пагинации соответственно 

19) при нажатии кнопок '>>' или '<<' открывается последняя или первая страница пагинации соответственно 

20) при открытии первой страницы кнопки '<<' и '<' неактивны 

21) при открытии последней страницы кнопки '>' и '>>' неактивны 

22) в кружке по центру указан номер текущей страницы. При переключении страниц номер меняется на актуальный 

23) при загрузке страницы формируется массив из 48 объектов питомцев. Каждый из 8 питомцев должен встречаться ровно 6 раз 

24) при каждой перезагрузке страницы формируется новый массив со случайной последовательностью 

25) карточки питомцев не должны повторяться на одной странице 

26) при переключении страницы данные меняются (для >1280px меняется порядок карточек, для остальных - меняется набор и порядок карточек) 

27) при неизменных размерах области пагинации, в том числе размерах окна браузера, и без перезагрузки страницы, возвращаясь на страницу под определенным номером, контент на ней всегда будет одинаков. Т.е. карточки питомцев будут в том же расположении, что и были до перехода на другие страницы 

28) при изменении ширины экрана (от 1280px до 320px и обратно), пагинация перестраивается и работает без перезагрузки страницы (страница может оставаться той же или переключаться, при этом сформированный массив - общая последовательность карточек - не обновляется, сохраняются все остальные требования к пагинации) 

29) попап появляется при нажатии на любое место карточки с описанием конкретного животного 

30) часть страницы вне попапа затемняется 

31) при открытии попапа вертикальный скролл страницы становится неактивным, при закрытии - снова активным 

32) при нажатии на область вокруг попапа или на кнопку с крестиком попап закрывается (оба варианта должны быть реализованы), при этом при нажатии на сам попап ничего не происходит 

33) кнопка с крестиком интерактивная 

34) окно попапа (не считая кнопку с крестиком) центрировано по всем осям, размеры элементов попапа и их расположение совпадают с макетом 

8. A cross-check score of your Score 
66

**Comment by anthony-th** [comment]
Ваша оценка - **65** баллов 

<details><summary>Отзыв по пунктам ТЗ:</summary>

### Не выполненные/не засчитанные пункты:

1) высота адаптивного меню занимает всю высоту экрана 
_Отзыв_: https://postimg.cc/1VP7f4LN
https://postimg.cc/cKgbzpR6 не занимает всю высоту экрана

2) страница под бургер-меню не прокручивается 
_Отзыв_: https://imgur.com/i3a8cJ9 не реализовано

3) смена блоков происходит с соответствующей анимацией карусели (способ выполнения анимации не проверяется) 
_Отзыв_: https://i.imgur.com/hx7CIOk.gif анимация не реализована

4) сохраняется только одно предыдущее состояние. Т.е. при последовательном переходе два раза влево, а потом два раза вправо, мы получим набор карточек, отличный от исходного 
_Отзыв_: нет сохранения предыдущего состояния

5) при загрузке страницы формируется массив из 48 объектов питомцев. Каждый из 8 питомцев должен встречаться ровно 6 раз 
_Отзыв_: массива не формируется, на странице элементам присваиваются значения, но это сделано не с помощью формирования массива

6) при каждой перезагрузке страницы формируется новый массив со случайной последовательностью 
_Отзыв_: новый массив не формируется, так как он просто не создается

7) при изменении ширины экрана (от 1280px до 320px и обратно), пагинация перестраивается и работает без перезагрузки страницы (страница может оставаться той же или переключаться, при этом сформированный массив - общая последовательность карточек - не обновляется, сохраняются все остальные требования к пагинации) 

8) кнопка с крестиком интерактивная 
_Отзыв_: https://postimg.cc/njPdH0nM полностью неинтерактивная

### Частично выполненные пункты:

1) при нажатии на бургер-иконку, справа плавно появляется адаптивное меню шириной 320px, бургер-иконка плавно поворачивается на 90 градусов 
_Отзыв_: реализовано только в mobile, в десктоп режиме бургер не откликается ни на какие клики (на обеих страницах)

2) при повторном нажатии на бургер-иконку или на свободное от бургер-меню пространство (оба варианта должны быть реализованы) адаптивное меню плавно скрывается уезжая за правую часть экрана, бургер-иконка плавно поворачивается на 90 градусов обратно 
_Отзыв_: нажатие на свободное от бургер-меню пространство не работает на обеих страницах

3) ссылки в адаптивном меню работают, обеспечивая плавную прокрутку по якорям, сохраняются заданные на первом этапе выполнения задания требования интерактивности элементов меню 
_Отзыв_: требования интерактивности элементов меню заданные на первом этапе не сохраняются, так как касательно страницы pets "элемент Our pets в навигации подсвечен и неинтерактивен, остальные элементы навигации интерактивны" https://postimg.cc/CBrhHBV9

4) расположение и размеры элементов в бургер-меню соответствует макету (центрирование по вертикали и горизонтали элементов меню, расположение иконки). При этом на странице Pets цветовая схема может быть как темная, так и светлая 
_Отзыв_: расположение элементов не соответствует макету ( https://postimg.cc/MnDBSHYF https://postimg.cc/yDBRtc0R )

5) область, свободная от бургер-меню, затемняется 
_Отзыв_: на странице main не реализовано полноценно: https://postimg.cc/svKffht7 https://postimg.cc/PPdrk4Fd Затемняется не вся страница, некоторые элементы игнорируют затемнение

6) при переключении влево или вправо прокручивается ровно столько карточек, сколько показывается при текущей ширине экрана (3 для 1280px, 2 для 768px, 1 для 320px) 
_Отзыв_: https://postimg.cc/bDjHyWt6 для 1280 не всегда есть 3 карточки, есть случай с 2.

7) в текущем блоке слайда карточки с питомцами не повторяются 
_Отзыв_: не реализовано полностью, так как есть пустые места, которые не являются "карточками" https://postimg.cc/bDjHyWt6 Пустота !== карточка с питомцем

8) в следующем блоке нет дублирования карточек с текущим блоком. Например в слайдере из 3 элементов, следующий выезжающий слайд будет содержать 3 (из 8 доступных) новых карточки питомца, таких, каких не было среди 3х карточек на предыдущем уехавшем слайде 
_Отзыв_: https://postimg.cc/bDjHyWt6 не реализовано полностью и правильно, так как есть "пустота", а не карточка

9) при изменении ширины экрана (от 1280px до 320px и обратно), слайдер перестраивается и работает без перезагрузки страницы (набор карточек при этом может как изменяться, так и оставаться тем же, скрывая лишнюю или добавляя недостающую, и сохраняя при этом описанные для слайдера требования) 
_Отзыв_: не реализовано полностью и без ошибок: карточки съезжают, загораживая возможность переключения слайдов https://postimg.cc/MfqDDNZc https://postimg.cc/mPK2HGVS и улетают за край экрана https://postimg.cc/XZvXw80V https://postimg.cc/Z9fBgQLB

10) общее количество страниц при ширине экрана 1280px - 6, при 768px - 8, при 320px - 16 страниц 
_Отзыв_: https://postimg.cc/bGjfPY34 https://postimg.cc/dZ3z6hVZ не реализовано (768, 320)

11) окно попапа (не считая кнопку с крестиком) центрировано по всем осям, размеры элементов попапа и их расположение совпадают с макетом 
_Отзыв_: https://postimg.cc/CZMJkW1z https://postimg.cc/jnhLHkCS размеры не совпадают, контент выпадает из окна на 320px на обеих страницах

### Выполненные пункты:

1) при ширине страницы меньше 768рх панель навигации скрывается, появляется бургер-иконка 

2) бургер-иконка создана при помощи html+css, без использования изображений 

3) при клике по любой ссылке (интерактивной или неинтерактивной) в меню адаптивное меню плавно скрывается вправо, бургер-иконка поворачивается на 90 градусов обратно 

4) при нажатии на стрелки происходит переход к новому блоку элементов 

5) слайдер бесконечен, т.е. можно бесконечно много нажимать влево или вправо, и каждый раз будет прокрутка в эту сторону с новым набором карточек 

6) при каждой перезагрузке страницы формируется новая последовательность карточек 

7) генерация наборов карточек происходит на основе 8 объектов с данными о животными 
Отзыв: не на основе объектов, а просто переприсваиванием https://postimg.cc/SXWYrGZ3

8) при перезагрузке страницы всегда открывается первая страница пагинации 

9) при нажатии кнопок '>' или '<' открывается следующая или предыдущая страница пагинации соответственно 

10) при нажатии кнопок '>>' или '<<' открывается последняя или первая страница пагинации соответственно 

11) при открытии первой страницы кнопки '<<' и '<' неактивны 

12) при открытии последней страницы кнопки '>' и '>>' неактивны 

13) в кружке по центру указан номер текущей страницы. При переключении страниц номер меняется на актуальный 

14) карточки питомцев не должны повторяться на одной странице 

15) при переключении страницы данные меняются (для >1280px меняется порядок карточек, для остальных - меняется набор и порядок карточек) 

16) при неизменных размерах области пагинации, в том числе размерах окна браузера, и без перезагрузки страницы, возвращаясь на страницу под определенным номером, контент на ней всегда будет одинаков. Т.е. карточки питомцев будут в том же расположении, что и были до перехода на другие страницы 

17) попап появляется при нажатии на любое место карточки с описанием конкретного животного 

18) часть страницы вне попапа затемняется 

19) при открытии попапа вертикальный скролл страницы становится неактивным, при закрытии - снова активным 

20) при нажатии на область вокруг попапа или на кнопку с крестиком попап закрывается (оба варианта должны быть реализованы), при этом при нажатии на сам попап ничего не происходит 

</details>

**Comment by anthony-th** [comment]
Ваша оценка - **73** баллов 

<details><summary>Отзыв по пунктам ТЗ:</summary>

### Не выполненные/не засчитанные пункты:

1) высота адаптивного меню занимает всю высоту экрана 
_Отзыв_: https://postimg.cc/1VP7f4LN
https://postimg.cc/cKgbzpR6 не занимает всю высоту экрана

2) страница под бургер-меню не прокручивается 
_Отзыв_: https://imgur.com/i3a8cJ9 не реализовано

3) смена блоков происходит с соответствующей анимацией карусели (способ выполнения анимации не проверяется) 
_Отзыв_: https://i.imgur.com/hx7CIOk.gif анимация не реализована

4) сохраняется только одно предыдущее состояние. Т.е. при последовательном переходе два раза влево, а потом два раза вправо, мы получим набор карточек, отличный от исходного 
_Отзыв_: нет сохранения предыдущего состояния

5) при изменении ширины экрана (от 1280px до 320px и обратно), пагинация перестраивается и работает без перезагрузки страницы (страница может оставаться той же или переключаться, при этом сформированный массив - общая последовательность карточек - не обновляется, сохраняются все остальные требования к пагинации) 

6) кнопка с крестиком интерактивная 
_Отзыв_: https://postimg.cc/njPdH0nM полностью неинтерактивная

### Частично выполненные пункты:

1) при нажатии на бургер-иконку, справа плавно появляется адаптивное меню шириной 320px, бургер-иконка плавно поворачивается на 90 градусов 
_Отзыв_: реализовано только в mobile, в десктоп режиме бургер не откликается ни на какие клики (на обеих страницах)

2) при повторном нажатии на бургер-иконку или на свободное от бургер-меню пространство (оба варианта должны быть реализованы) адаптивное меню плавно скрывается уезжая за правую часть экрана, бургер-иконка плавно поворачивается на 90 градусов обратно 
_Отзыв_: нажатие на свободное от бургер-меню пространство не работает на обеих страницах

3) ссылки в адаптивном меню работают, обеспечивая плавную прокрутку по якорям, сохраняются заданные на первом этапе выполнения задания требования интерактивности элементов меню 
_Отзыв_: требования интерактивности элементов меню заданные на первом этапе не сохраняются, так как касательно страницы pets "элемент Our pets в навигации подсвечен и неинтерактивен, остальные элементы навигации интерактивны" https://postimg.cc/CBrhHBV9

4) расположение и размеры элементов в бургер-меню соответствует макету (центрирование по вертикали и горизонтали элементов меню, расположение иконки). При этом на странице Pets цветовая схема может быть как темная, так и светлая 
_Отзыв_: расположение элементов не соответствует макету ( https://postimg.cc/MnDBSHYF https://postimg.cc/yDBRtc0R )

5) область, свободная от бургер-меню, затемняется 
_Отзыв_: на странице main не реализовано полноценно: https://postimg.cc/svKffht7 https://postimg.cc/PPdrk4Fd Затемняется не вся страница, некоторые элементы игнорируют затемнение

6) при переключении влево или вправо прокручивается ровно столько карточек, сколько показывается при текущей ширине экрана (3 для 1280px, 2 для 768px, 1 для 320px) 
_Отзыв_: https://postimg.cc/bDjHyWt6 для 1280 не всегда есть 3 карточки, есть случай с 2.

7) в текущем блоке слайда карточки с питомцами не повторяются 
_Отзыв_: не реализовано полностью, так как есть пустые места, которые не являются "карточками" https://postimg.cc/bDjHyWt6 Пустота !== карточка с питомцем

8) в следующем блоке нет дублирования карточек с текущим блоком. Например в слайдере из 3 элементов, следующий выезжающий слайд будет содержать 3 (из 8 доступных) новых карточки питомца, таких, каких не было среди 3х карточек на предыдущем уехавшем слайде 
_Отзыв_: https://postimg.cc/bDjHyWt6 не реализовано полностью и правильно, так как есть "пустота", а не карточка

9) при изменении ширины экрана (от 1280px до 320px и обратно), слайдер перестраивается и работает без перезагрузки страницы (набор карточек при этом может как изменяться, так и оставаться тем же, скрывая лишнюю или добавляя недостающую, и сохраняя при этом описанные для слайдера требования) 
_Отзыв_: не реализовано полностью и без ошибок: карточки съезжают, загораживая возможность переключения слайдов https://postimg.cc/MfqDDNZc https://postimg.cc/mPK2HGVS и улетают за край экрана https://postimg.cc/XZvXw80V https://postimg.cc/Z9fBgQLB

10) общее количество страниц при ширине экрана 1280px - 6, при 768px - 8, при 320px - 16 страниц 
_Отзыв_: https://postimg.cc/bGjfPY34 https://postimg.cc/dZ3z6hVZ не реализовано (768, 320)

11) окно попапа (не считая кнопку с крестиком) центрировано по всем осям, размеры элементов попапа и их расположение совпадают с макетом 
_Отзыв_: https://postimg.cc/CZMJkW1z https://postimg.cc/jnhLHkCS размеры не совпадают, контент выпадает из окна на 320px на обеих страницах

### Выполненные пункты:

1) при ширине страницы меньше 768рх панель навигации скрывается, появляется бургер-иконка 

2) бургер-иконка создана при помощи html+css, без использования изображений 

3) при клике по любой ссылке (интерактивной или неинтерактивной) в меню адаптивное меню плавно скрывается вправо, бургер-иконка поворачивается на 90 градусов обратно 

4) при нажатии на стрелки происходит переход к новому блоку элементов 

5) слайдер бесконечен, т.е. можно бесконечно много нажимать влево или вправо, и каждый раз будет прокрутка в эту сторону с новым набором карточек 

6) при каждой перезагрузке страницы формируется новая последовательность карточек 

7) генерация наборов карточек происходит на основе 8 объектов с данными о животными 
Отзыв: не на основе объектов, а просто переприсваиванием https://postimg.cc/SXWYrGZ3

8) при перезагрузке страницы всегда открывается первая страница пагинации 

9) при нажатии кнопок '>' или '<' открывается следующая или предыдущая страница пагинации соответственно 

10) при нажатии кнопок '>>' или '<<' открывается последняя или первая страница пагинации соответственно 

11) при открытии первой страницы кнопки '<<' и '<' неактивны 

12) при открытии последней страницы кнопки '>' и '>>' неактивны 

13) в кружке по центру указан номер текущей страницы. При переключении страниц номер меняется на актуальный 

14) при загрузке страницы формируется массив из 48 объектов питомцев. Каждый из 8 питомцев должен встречаться ровно 6 раз 

15) при каждой перезагрузке страницы формируется новый массив со случайной последовательностью 

16) карточки питомцев не должны повторяться на одной странице 

17) при переключении страницы данные меняются (для >1280px меняется порядок карточек, для остальных - меняется набор и порядок карточек) 

18) при неизменных размерах области пагинации, в том числе размерах окна браузера, и без перезагрузки страницы, возвращаясь на страницу под определенным номером, контент на ней всегда будет одинаков. Т.е. карточки питомцев будут в том же расположении, что и были до перехода на другие страницы 

19) попап появляется при нажатии на любое место карточки с описанием конкретного животного 

20) часть страницы вне попапа затемняется 

21) при открытии попапа вертикальный скролл страницы становится неактивным, при закрытии - снова активным 

22) при нажатии на область вокруг попапа или на кнопку с крестиком попап закрывается (оба варианта должны быть реализованы), при этом при нажатии на сам попап ничего не происходит 

</details>
