### ISSUE TITLE
Cross-Check 'DevOps. Task 1. AWS Account Configuration' 'xorzee'

### ISSUE THREAD

**Issue by xorzee** [rolling-scopes-school/support#977]
1. A link to your deployed project
    - [PR 2](https://github.com/xorzee/rsschool-devops-course-tasks/pull/2)
2. A link to the project repository on Github.
    - [xorzee/rsschool-devops-course-tasks](https://github.com/xorzee/rsschool-devops-course-tasks)
3. A link to the task
    - [Task 1](https://github.com/rolling-scopes-school/tasks/blob/master/devops/modules/1_basic-configuration/task_1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [Evaluation Criteria](https://github.com/rolling-scopes-school/tasks/blob/master/devops/modules/1_basic-configuration/task_1.md#evaluation-criteria-100-points-for-covering-all-criteria)
5. A screenshot of cross-checking marks
![shot@2024-10-08 11 46 03@2x](https://github.com/user-attachments/assets/a42cb18c-03d2-4932-8f72-cd074827a07e)

7. A final score after self-assessment, with comments
100
✅ MFA User configured (10 points)
✅ Bucket and GithubActionsRole IAM role configured (30 points)
✅ Github Actions workflow is created (30 points)
✅ Code Organization (10 points)
✅ Verification (10 points)
✅ Additional Tasks (10 points)
	✅ Documentation (5 points)
    ✅ Submission (5 points)

9. A cross-check score of your Score 
???

**Comment by kustikov112** [comment]
Looks good for me. 
Scores have been updated.
Issue may be closed.
