### ISSUE TITLE
Cross-Check 'webdev' - 'Katerina-l' 

### ISSUE THREAD

**Issue by Katerina-L** [rolling-scopes-school/support#98]
Ссылка на деплой вашего проекта:
https://rolling-scopes-school.github.io/katerina-l-JS2020Q3/webdev/
Ссылка на репозиторий с проектом на GitHub:
https://github.com/rolling-scopes-school/katerina-l-JS2020Q3/tree/gh-pages/webdev
- Оценка в результате самопроверки, с ее аргументацией:
100/100 - выполнены все условия задания, нет расхождения более чем в 5px, прилагаю скрин с PixelPlex 
![](https://sun4-10.userapi.com/yobR3MaD5Qz6KO_xHvOP1Y2vJRlVfZsgsS10Mg/TGtxi70jRUg.jpg) 
Student 3
Score: 78
Заголовок и webdev сильно смещены относительно макета, также в блоках есть сдвиги > 5px (в основном текстовых составляющих)
-

**Comment by Alexey-Koren** [comment]
Обидно. Работа отличная.
Но ваш итоговый балл за таск 91 балл.
Ваша апелляция не подходит под правила, прочитайте пункт 4.
В разделе про апелляции https://docs.rs.school/#/cross-check-flow

Закрываю
