### ISSUE TITLE
Cross-Check 'Christmas Shop. Part 1: Fixed Layout' - ' Pasha109r'

### ISSUE THREAD

**Issue by Pasha109r** [rolling-scopes-school/support#987]
1. https://rolling-scopes-school.github.io/pasha109r-JSFE2024Q4/christmas-shop/
2. https://github.com/rolling-scopes-school/pasha109r-JSFE2024Q4
3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/christmas-shop/christmas-shop-part1.md

4. 
![Снимок экрана 2024-11-23 205133](https://github.com/user-attachments/assets/b8b661c5-ad37-4567-b172-62017dc11f85)
![Снимок экрана 2024-11-23 205127](https://github.com/user-attachments/assets/a88ebc75-c77f-4dbb-9cac-93edd874f86e)
![Снимок экрана 2024-11-23 205118](https://github.com/user-attachments/assets/1fc1ac64-2cb5-4ea1-8985-c3410e5d5639)

5. 80

6. 90

**Comment by KristiBo** [comment]
You have a commit after the deadline.
