### ISSUE TITLE
Cross-Check 'Home Library Service: Part 2' - 'natgeo89'

### ISSUE THREAD

**Issue by natgeo89** [rolling-scopes-school/support#988]
1. A link to your deployed project
    - [link](https://github.com/natgeo89/nodejs2024Q3-service/pull/2)
2. A link to the project repository on Github.
    - [link](https://github.com/natgeo89/nodejs2024Q3-service)
3. A link to the task
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/containerization-database-orm/assignment.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/AlreadyBored/nodejs-assignments/blob/main/assignments/containerization-database-orm/score.md)
5. A screenshot of cross-checking marks
![image](https://github.com/user-attachments/assets/afd5ad2f-af50-4ccc-a924-8a993d65e83e)
![image](https://github.com/user-attachments/assets/ba087097-441b-4aa3-bb0a-c6016242fe0c)

6. A final score after self-assessment, with comments
Self score: 330/360
all requirements implemented except these:
![image](https://github.com/user-attachments/assets/46113143-a9c7-4423-a262-6b33c07f9bd4)

![image](https://github.com/user-attachments/assets/c48208d6-7c1b-402a-ba0e-537e105d9d54)

7. A cross-check score of your Score 
General crosscheck score after all students review: 258

**Comment by AlreadyBored** [comment]
Check result: 330
