### ISSUE TITLE
Cross-Check 'Christmas Shop. Part-2 - Responsive Design' - 'dzmitryaliakseyeu'

### ISSUE THREAD

**Issue by DzmitryAliakseyeu** [rolling-scopes-school/support#989]
1. A link to your deployed project
    - [[link](https://github.com/)](https://rolling-scopes-school.github.io/dzmitryaliakseyeu-JSFEEN2024Q4/christmas-shop/)
2. A link to the project repository on Github.
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/dzmitryaliakseyeu-JSFEEN2024Q4/tree/christmas-shop-part2)
3. A link to the task
    - [[link](https://github.com/)](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/christmas-shop/christmas-shop-part2.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
![app rs school_course_student_cross-check-submit_course=js-fe-en-2024q4 taskId=3755](https://github.com/user-attachments/assets/2ab91463-1d20-432a-a164-be8e72b05c5b)
![app rs school_course_student_cross-check-submit_course=js-fe-en-2024q4 taskId=3755 (2)](https://github.com/user-attachments/assets/c3de7218-08c8-4d41-b69d-b8a41fa9bc09)

6. A final score after self-assessment, with comments
   - 100 points.  All requirements for this task completed.
7. A cross-check score of your Score 
   - 75 points.

**Comment by Anik188** [comment]
Checked by coordinator. It's not cheating. The points should be updated
