### ISSUE TITLE
Cross-Check 'webdev' - 'laranto-spb'

### ISSUE THREAD

**Issue by Laranto-spb** [rolling-scopes-school/support#99]
Ссылка на деплой https://laranto-spb-webdev.netlify.app/ 
Ссылка на репозиторий https://github.com/rolling-scopes-school/laranto-spb-JS2020Q3/tree/gh-pages/webdev

Выполнялось по старому макету.
Самооценка: 95 баллов. 
1. -2 Не выполнена одновременная анимация кнопки **вместе** с иконкой в блоке Download. Интерактивность только кнопки (курсор и цвет).
2. -3 Фоновая картинка с ноутбук совпадает не идеально

 
dmitri611 
Score: 76

Первый элемент не подсвечен - 2 балла **Сделано интерактивное подчеркивание при наведении курсора и первого пункта меню соотв**

При наведении на кнопку цвет не соответствует макету - 2 балла **По ТЗ кнопка должна быть интерактивной на выбор**

Съехала картинка на заднем фоне - 3 балла **Согласна**

Во втором блоке текст не соответствует макету **не согласна + h1 webdev есть и скрыт** и при наведении на кнопку цвет не соответствует макету - 5 баллов ** По ТЗ кнопка должна быть интерактивной на выбор  **
![image](https://user-images.githubusercontent.com/64079576/94360920-6fd34a80-00b9-11eb-86a3-7e2812e65411.png)

В третьем блоке 3 картинка не обрезалась средствами css - 3 балла **Сделано по ТЗ, на макете есть при отключении hidden по х, возможно я не поняла задачу**

В четвертом блоке текст не соответствует макету и при наведении на кнопку цвет не соответствует макету - 5 баллов **По ТЗ кнопка должна быть интерактивной на выбор**
![image](https://user-images.githubusercontent.com/64079576/94361013-06a00700-00ba-11eb-8d41-a36f36247712.png)
![image](https://user-images.githubusercontent.com/64079576/94361022-10296f00-00ba-11eb-94df-60d7b488c07d.png)

В пятом блоке кнопка при наведении не соответствует макету - 2 балла **По ТЗ кнопка должна быть интерактивной на выбор**

В шестом блоке тоже самое что и в пятом - 2 балла **По ТЗ кнопка должна быть интерактивной на выбор**

В дискорде ник не соответвует гитхаб, связывалась через в ВК (в задании CV у проверяющего оказалась ссылка на ВК)

**Comment by valerydluski** [comment]
Апелляция производится только если ожидаемый вами балл и полученным по результатам кросс-чека средний балл отличаются на 15 и более процентов.
