### ISSUE TITLE
Cross-Check 'Clean-code-s1e1' - 'AM1007'

### ISSUE THREAD

**Issue by AM1007** [rolling-scopes-school/support#990]
1. A link to your deployed project
    - [link](https://am1007.github.io/clean-code-s1e1/)
2. A link to the project repository on Github.
    - [link](https://github.com/AM1007/clean-code-s1e1)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://github.com/)
5. A screenshot of cross-checking marks
   - Аппеляция об восстановлении после отчисления (скриншот отсутствует)
6. A final score after self-assessment, with comments
  - 43 (два класса CSS не по BEM-методологии)
7. A cross-check score of your Score 
 -

**Comment by KristiBo** [comment]
Таск одним коммитом
