### ISSUE TITLE
Cross-Check 'Clean Code S1E1' - 'GKonopelko'.

### ISSUE THREAD

**Issue by GKonopelko** [rolling-scopes-school/support#991]
1. A link to your deployed project
    - [link](https://gkonopelko.github.io/clean-code-s1e1/)
2. A link to the project repository on Github.
    - [link](https://github.com/GKonopelko/clean-code-s1e1/pull/1)
4. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md)
6. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
8. A screenshot of cross-checking marks
![image](https://github.com/user-attachments/assets/e0eb6e37-5014-4335-ad23-bb6bb9ad4a23)
![image](https://github.com/user-attachments/assets/de1f3fa0-a984-46fd-92c9-c901be4e6ffe)
![image](https://github.com/user-attachments/assets/5e79cd69-6cce-4f25-83ac-d8f21ece6ce8)
![image](https://github.com/user-attachments/assets/4f2c61b4-67b4-4e08-857b-ff6649f4eba3)
![image](https://github.com/user-attachments/assets/091b6ec6-5a7d-46f9-9001-e60ed7221c51)
![image](https://github.com/user-attachments/assets/9233a6e4-5c1f-4aff-b513-12d9948cb423)
9. A final score after self-assessment, with comments
- 45/45 По-моему, все сделано в соответствие с ТЗ. 
10. A cross-check score of your Score 
- У меня было 3 проверяющих, оценки: 45, 45, 0,  Итоговая общая оценка - 30.

**Comment by KristiBo** [comment]
@GKonopelko исправь, пожалуйста:
- в названии ишью нужно указать имя профиля GitHub, а не ссылку.
- в п.2 нужно указать ссылку на твой репозиторий с таском.
- в п.5 приложи скриншот оценок с комментариями (ники проверяющих должны быть скрыты)

**Comment by GKonopelko** [comment]
Поправил.

**Comment by radomskaia** [comment]
Ваша оценка - 0 баллов 
Отзыв по пунктам ТЗ:
<details><summary>Выполненные пункты:</summary>

1) Basic rule 1.1. Indentation: implemented in the whole project. 

2) Basic rule 1.2. Use lowercase: implemented in the whole project. 

3) Basic rule 1.3. Quotes in HTML & CSS files: implemented in the whole project. 

4) Basic rule 2.1. HTML. Formatting: implemented in the whole project. 

5) Basic rule 2.2. Document Type: implemented in the project. 

6) Basic rule 2.3. Named character references: implemented in the whole project. 

7) Basic rule 2.4. 'type' attribute: implemented in the whole project. 

8) Basic rule 3.1. Single style for selectors naming: implemented in the whole project. 

9) Basic rule 3.2. Meaningful naming of identifiers and classes: implemented in the whole project. 

10) Basic rule 3.3. Keep the names of identifiers and classes concise: implemented in the whole project. 

11) Basic rule 3.4. Tag selectors: implemented in the whole project. 

12) Basic rule 3.5. Indentation in blocks: implemented in the whole project. 

13) Basic rule 3.6. Space after property name: implemented in the whole project. 

14) Basic rule 3.7. Semicolon after properties: implemented in the whole project. 

15) Basic rule 3.8. Separate selectors and properties: implemented in the whole project. 

16) Extended rule 1.1. HTML. Semantics: implemented in the whole project. 

17) Extended rule 1.2. Media alternatives: implemented in the whole project. 

18) Extended rule 2.1. BEM: implemented in the whole project. </details>

<details><summary>Штрафы:</summary>

>  Requrement "One commit must contain changes related to a single point of the guidelines, the commit message must reflect all the changes made in the commit. Intersection of two or more rules in a single commit is acceptable only if compliance of one rule automatically leads to compliance of another one and it is impossible to separate them (all the rules must be listed in a commit message in this case)" is not met 

  **Отзыв:** 
Два коммита содержат несколько правил, которые можно было разделить ранее. 
* [refactor(basic-3.2): change classnames and identifiers to meaningfull](https://github.com/GKonopelko/clean-code-s1e1/pull/1/commits/e961cf29530022ea1e57c6b577cb8b5545410736) в строке 14 HTML нет изменения класса с описательным именем `centered`. Он был изменен в коммите [refactor(basic-3.3): change classnames and identifiers to concise](https://github.com/GKonopelko/clean-code-s1e1/pull/1/commits/7f0ebc3f8ea848e75f63c4297ae4c39df49c1b04)
* [refactor(basic-3.3): change classnames and identifiers to concise](https://github.com/GKonopelko/clean-code-s1e1/pull/1/commits/7f0ebc3f8ea848e75f63c4297ae4c39df49c1b04) в строке 11 HTML - сокращение слова `info`, которое было изменено только в коммите [refactor(extended-2.1): add BEM notation](https://github.com/GKonopelko/clean-code-s1e1/pull/1/commits/c387e25153269f3b6d289a86168857c795244d3c). 

> Requrement "Each commit must be made according to the commit requirements and comply consistently with one of the commit message style options" is not met 

  **Отзыв:** 
Название коммита [refactor(basic-2.2): add DOCTYPE html tag](https://github.com/GKonopelko/clean-code-s1e1/pull/1/commits/e38597804f2a62b250cd56b34aebf136e3a6f5cd) указан `refactor`, хотя был произведен `fix`. 
В [ТЗ](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md#commit-message-style) данный фикс был приведен в качестве примера к стилям коммитов. 

В любом случае, добавление `DOCTYPE` - это точно не `refactor`, т.к. [меняется функциональность приложения](https://developer.mozilla.org/en-US/docs/Glossary/Doctype)
</details>

**Comment by GKonopelko** [comment]
Спасибо за уделенное время и за внимательную проверку!

**Comment by KristiBo** [comment]
@radomskaia спасибо за помощь.
@GKonopelko пожалуйста, больше не закрывай рассмотренное ишью самостоятельно.
Оценка обновлена.
