### ISSUE TITLE
Cross-Check 'Clean Code S1E1' - 'ksugaevskaya'

### ISSUE THREAD

**Issue by ksugaevskaya** [rolling-scopes-school/support#992]
1. A link to your deployed project
    - [link](https://sprightly-chimera-3c296d.netlify.app/)
2. A link to the project repository on Github.
    - [link](https://github.com/ksugaevskaya/clean-code-s1e1)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks

<img width="117" alt="image" src="https://github.com/user-attachments/assets/79d3bd3a-206c-4ab2-a222-9c6ec66bc024" />

<img width="119" alt="image" src="https://github.com/user-attachments/assets/be7a700c-9fa4-4b9b-986d-fdf602c40601" />

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/a32f80c5-8fc7-4723-8653-bd7fe883f9bc" />
<img width="1287" alt="image" src="https://github.com/user-attachments/assets/80608926-0cea-4104-af39-400cfcc3cfda" />

7. A final score after self-assessment, with comments

45/45 - я думаю, что я выполнила всё в соответствие с ТЗ. В случае каких-либо спорных моментов я готова объяснить почему такое решение было сделано.

<details>
  <summary>Нажмите, чтобы показать мои комментарии</summary>
  
  > 1. Вместе с редактированием кода в камках п. 1.1-basic произведено редактирование по правилам 2.1-basiс, 3.5-basic.
  > При этом п.3.5-basic отсутствует в списке коммитов.
  > Скриншоты: https://dropmefiles.com/V7Vv1 https://dropmefiles.com/pYB9c

  Я старалась делать всё последовательно. В первом пункте я поняла, что нужно ставить пробелы и по примеру перенесла теги на новые строчки (по стандарту HTML). Потом я увидела пункт, где требуется переносить теги. Работы уже было проделано много, и я не решилась, переделывать то с нуля. Это не было сделано intentionally, чтобы сломать структуру, все остальные коммиты были сделаны раздельно. Некоторые студенты группировали коммиты (например BEM) в один коммит, однако я специально перерабатывала коммит за коммитом, чтобы к спорным моментам не было вопросов.

  > 2. Вместе с редактированием кода в камках п. 3.4-basic произведено редактирование по правилу 3.6-basic. Скриншот: https://dropmefiles.com/XKPEA

   В этот коммит туда случайно залетело одно исправление, но ставить за такие нарушения 0 баллов - это слишком.
   
  > замена одних тэгов другими (в html): https://dropmefiles.com/OQI6X

  Я меняла селекторы и пыталась достичь консистентности кода. Когда избавляешься от селектора label - очевидно, что тег label в html тоже может быть изменён/удалён.

  > добавление переносов строк внутри тэгов html (пересечение с п.2.5-basic: HTML Line-Wrapping): https://dropmefiles.com/RE4iY, удаление переносов строк внутри тэгов html: https://dropmefiles.com/4Ozm8
  
  Это был глюк VSCode и то, что я не увидела при коммите. Это не было сделано специально. Я отключала все форматтеры в VSCode, потратила 2 часа, чтобы полностью их отключить и сделала пункт HTML wrapping и закоммитила его. Потом я перезагрузила копмьютер, и VSCode опять начал переносить длинные теги в две строчки - к сожалению, в данном коммите я этого не увидела, потому что меняла другую часть кода. Когда я это обнаружила (в самом конце) я пофиксила line wrapping снова. Сожалею, что VSCode при своём обновлении не сохранил настройки. Опять-таки - это очень жестокое и категоричное снятие баллов.
  
  > добавление новых деклараций в css правила: https://dropmefiles.com/aIVIN, https://dropmefiles.com/dvihD
  
  Так я рефакторила стили - я не в праве менять контент самих стилей и их иерархию? Это где-то было указано в задании, что так нельзя делать и за это надо ставить 0 баллов?

  > Вместе с редактированием кода в рамках п. 1.1-extended произведено редактирование по правилу 3.1-basic. Скриншот: https://dropmefiles.com/CMAJu
  
  Да, один id и его изменение имело место быть. Но после 4-х дней выполнения этого задания у меня просто по-человечески мог "замылиться" глаз...

  > В начале многих коммитов отсутствует глагол, обозначающий действие. Скриншоты: https://dropmefiles.com/fTWzA https://dropmefiles.com/InPPA

  Я не обратила внимания, на то что нужно было использовать глагол. Я уяснила главную структуру, что нужно указывать референс на подтаску, указывать её категорию и так далее. Указывать/не указывать глагол, в какой форме, в каком времени, в каком наклонении - это очень холиварный топик. Мне кажется что ставить за это 0 баллов - очень радикально и несправедливо.

</details>

8. A cross-check score of your Score 

У меня было 3 проверяющих, оценки: 45, 45, 0, Итоговая общая оценка - 30.

Последний 0 был засабмичен ночью буквально за час до дедлайна без возможности что-либо с этим сделать.

**Comment by KristiBo** [comment]
Апелляция рассматривается только при отсутствии коммитов после дедлайна. У тебя, к сожалению, был коммит:

![image](https://github.com/user-attachments/assets/47c4c475-2561-4db2-be78-9dc5129ef300)

![image](https://github.com/user-attachments/assets/9705bf12-c8d4-42bf-a7ce-138cf8a71d50)

**Comment by ksugaevskaya** [comment]
Это был optional requirement 😭 😭😭 И правда очень жаль...
