### ISSUE TITLE
Cross-Check 'Clean-code-s1e1' - 'KateGomel'

### ISSUE THREAD

**Issue by KateGomel** [rolling-scopes-school/support#993]
1. A link to your deployed project
    - [link](https://kategomel.github.io/clean-code-s1e1/)
2. A link to the project repository on Github.
    - [link](https://github.com/KateGomel/clean-code-s1e1/tree/clean-code-s1e1)
3. A link to the task
    - [link](https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md)
4. A Link to the checklist for evaluating the task (if it exists)
    - [link](https://rolling-scopes-school.github.io/checklist/)
5. A screenshot of cross-checking marks
![Снимок экрана 2024-12-21 154401](https://github.com/user-attachments/assets/edd798bc-edd4-4cfe-8ecd-ad7c0ddda891)
6. A final score after self-assessment, with comments
45/45 Выполнены все пункты в соответствии с требованиями ТЗ
7. A cross-check score of your Score 
Общая оценка из Score - 30. Работу проверили три человека - 0, 45, 45

**Comment by anthony-th** [comment]
Ваша оценка - **45** **баллов** 🎉🎉🎉

Отзыв по пунктам ТЗ:
<details><summary>Выполненные пункты:</summary>

1) Basic rule 1.1. Indentation: implemented in the whole project. 

2) Basic rule 1.2. Use lowercase: implemented in the whole project. 

3) Basic rule 1.3. Quotes in HTML & CSS files: implemented in the whole project. 

4) Basic rule 2.1. HTML. Formatting: implemented in the whole project. 

5) Basic rule 2.2. Document Type: implemented in the project. 

6) Basic rule 2.3. Named character references: implemented in the whole project. 

7) Basic rule 2.4. 'type' attribute: implemented in the whole project. 

8) Basic rule 3.1. Single style for selectors naming: implemented in the whole project. 

9) Basic rule 3.2. Meaningful naming of identifiers and classes: implemented in the whole project. 

10) Basic rule 3.3. Keep the names of identifiers and classes concise: implemented in the whole project. 

11) Basic rule 3.4. Tag selectors: implemented in the whole project. 

12) Basic rule 3.5. Indentation in blocks: implemented in the whole project. 

13) Basic rule 3.6. Space after property name: implemented in the whole project. 

14) Basic rule 3.7. Semicolon after properties: implemented in the whole project. 

15) Basic rule 3.8. Separate selectors and properties: implemented in the whole project. 

16) Extended rule 1.1. HTML. Semantics: implemented in the whole project. 

17) Extended rule 1.2. Media alternatives: implemented in the whole project. 

18) Extended rule 2.1. BEM: implemented in the whole project. 
</details>

**Comment by KristiBo** [comment]
@anthony-th спасибо!
@KateGomel оценка обновлена
