### ISSUE TITLE
Cross-Check Clean Code S1E1 - soulflamecompany

### ISSUE THREAD

**Issue by soulflamecompany** [rolling-scopes-school/support#994]
1. A link to your deployed project
    - https://soulflamecompany.github.io/clean-code-s1e1/
2. A link to the project repository on Github.
    - https://github.com/soulflamecompany/clean-code-s1e1
3. A link to the task
    - https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md
4. A Link to the checklist for evaluating the task (if it exists)
    - https://rolling-scopes-school.github.io/checklist/active-tasks/clean-code-s1e1.json
5. A screenshot of cross-checking marks
    -  ![cleanCodeIssue](https://github.com/user-attachments/assets/d3d03ccf-4940-41b9-b74d-ee5a61d1f44c)
6. A final score after self-assessment, with comments
    - 43/45 балла получила данная работа в прошлом году обучения. Сейчас же вышло так,что проверяющих было 2.Изначально обе были 0.В конце проверки один из проверяющих обновил оценку до 37.С оценками проверяющих нынешнего потока -  не согласен.
8. A cross-check score of your Score 
    - 19 / 45

**Comment by savryna** [comment]
### Ваша оценка - 0 баллов 
#### Отзыв по пунктам ТЗ:
<details>
  <summary>Не выполненные/не засчитанные пункты:</summary>
  
  **1) Basic rule 1.1. Indentation: implemented in the whole project.**
**Отзыв:** У каждого селектора первого порядка вложенности в **style.css** добавлен отступ, которого быть не должно.
**3) Basic rule 3.3. Keep the names of identifiers and classes concise: implemented in the whole project.**
**Отзыв:** Если следовать правилу basic-3.3  в файле **index.html** на 11 строке класс должен быть исправлен на "more_info".
**4) Extended rule 1.1. HTML. Semantics: implemented in the whole project.**
**Отзыв:** У каждой секции должен быть заголовок уровня h2. В вашем файле index.html порядок заголовков стартует с h3, пропуская h1-h2.
**5) Extended rule 2.1. BEM: implemented in the whole project.**
**Отзыв:** Файл **index.html** 17 строка, для элемента используется class="form-add__task form__task", но выше по дереву нет блока с классом "form__task", 18 строка этаже проблема. Если блок это section class="form-add", то у элемента input класс должен быть class="form-add__task form-add__task_modifier", у элемента button - class="form-add__btn". Дальше по дереву эта же ошибка.

</details>
<details>
  <summary>Выполненные пункты:</summary>

5. Basic rule 1.2. Use lowercase: implemented in the whole project.

6. Basic rule 1.3. Quotes in HTML & CSS files: implemented in the whole project.

7. Basic rule 2.1. HTML. Formatting: implemented in the whole project.

8. Basic rule 2.2. Document Type: implemented in the project.

9. Basic rule 2.3. Named character references: implemented in the whole project.

10. Basic rule 2.4. 'type' attribute: implemented in the whole project.

11. Basic rule 3.1. Single style for selectors naming: implemented in the whole project.

12. Basic rule 3.2. Meaningful naming of identifiers and classes: implemented in the whole project.

13. Basic rule 3.4. Tag selectors: implemented in the whole project.
    Отзыв: Ни один коммит не помечен правилом basic-3.4
14. Basic rule 3.5. Indentation in blocks: implemented in the whole project.
    Отзыв: Ни один коммит не помечен правилом basic-3.5
15. Basic rule 3.6. Space after property name: implemented in the whole project.
    Отзыв: 21, 40, 41, 44, 47 строки - на этапе коммита пробел не добавлен. В финальном файле пробелы есть.
16. Basic rule 3.7. Semicolon after properties: implemented in the whole project.
    Отзыв: На этапе коммита не все строчки исправлены, в финальном варианте файла правило выполнено.
17. Basic rule 3.8. Separate selectors and properties: implemented in the whole project.
   Отзыв: Ни один коммит не помечен правилом basic-3.8
18. Extended rule 1.2. Media alternatives: implemented in the whole project.
</details>

<details>
  <summary>Штрафы:</summary>
  
**1. Requrement "One commit must contain changes related to a single point of the guidelines, the commit message must reflect all the changes made in the commit. Intersection of two or more rules in a single commit is acceptable only if compliance of one rule automatically leads to compliance of another one and it is impossible to separate them (all the rules must be listed in a commit message in this case)" is not met**

   **Отзыв:**
   1) Коммит [cc650ab](https://github.com/soulflamecompany/clean-code-s1e1/commit/cc650abb2244172c20a6205ee821a422e76fcbf6) помечен правилом basic-1.1, содержит изменения не соответствующие коммиту. Файл **index.html** 2 строчка добавление lang="en". Файл **style.css** добавляются пустые строки между объявлением правил, добавляется перенос селекторов (43 строка, 46 строка), отступ добавляется даже у селекторов первого порядка, лишние пробелы (например, 21 строчка), добавление "***;***" 38 строчка и т.д.

2) Коммит [a5e0fc2](https://github.com/soulflamecompany/clean-code-s1e1/commit/a5e0fc21d121e1f35dda4c8dee07584dc169d720) включает 2 правила, которые должны быть закомичены отдельно.Этот же коммит содержит изменения не относящийся ни к одному из правил. Например, в файлу **style.css** 8-23 строчки, 44 строчка
3) Коммит [54586ee](https://github.com/soulflamecompany/clean-code-s1e1/commit/54586ee96b9689e294ea3b6a89465e6675871ed6) добавляете отступ для селектора первой вложенности.
4) Коммит [e8224fa](https://github.com/soulflamecompany/clean-code-s1e1/commit/e8224fab2e1ebddac7bf724ad8e689133f8629a5) излишнее исправление "Lato".
5) Коммит [07dc4b4](https://github.com/soulflamecompany/clean-code-s1e1/commit/07dc4b4bb87cafbdfa23028477deff240435fff4) помечен правилами basic-3.6, basic-3.7, которые следует коммитить отдельно. Содержит изменения не относящиеся к коммиту: файл **style.css** строчки 22-24, 26, 101, 119

**2. Requrement "Each commit must be made according to the commit requirements and comply consistently with one of the commit message style options" is not met**
   **Отзыв:** Коммиты (например, [07dc4b4](https://github.com/soulflamecompany/clean-code-s1e1/commit/07dc4b4bb87cafbdfa23028477deff240435fff4), [cc650ab](https://github.com/soulflamecompany/clean-code-s1e1/commit/cc650abb2244172c20a6205ee821a422e76fcbf6)) содержат изменения / правила не указанные в описание коммита.
</details>

**Comment by KristiBo** [comment]
@savryna спасибо.
Оценка обновлена.
